import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 목적지 주소 하나에 표의 줄이 여럿 맞으면 라우터는 어느 줄을 따르는가.
 */
export const longestPrefixMatchFacet: FacetJson = {
  id: 'facet:longestPrefixMatch',
  title: {
    en: 'Longest prefix match',
    ko: '최장 접두 일치',
    ja: 'ロンゲストプレフィックスマッチ',
    zh: '最长前缀匹配',
    ar: 'مطابقة أطول بادئة',
    es: 'Coincidencia del prefijo más largo',
    fr: 'Correspondance du plus long préfixe',
    hi: 'सबसे लंबा प्रीफ़िक्स मिलान',
    id: 'Pencocokan prefiks terpanjang',
    pt: 'Correspondência do prefixo mais longo',
  },
  description: {
    en: 'The destination is lined up against every row of the table; of the rows whose prefix matches all the way, the longest one wins.',
    ko: '목적지를 표의 줄마다 맞춰 보고, 접두가 끝까지 맞은 줄 가운데 가장 긴 줄을 고른다.',
    ja: '宛先を表の各行に重ねて照合し、プレフィックスが最後まで一致した行のうち最も長い行を選ぶ。',
    zh: '把目的地址逐行与表比对，在前缀完全吻合的行中选出最长的一行。',
    ar: 'يُطابَق عنوان الوجهة مع كل صف في الجدول، ومن بين الصفوف التي تطابقت بادئتها حتى النهاية يُختار الأطول.',
    es: 'El destino se compara con cada fila de la tabla; de las filas cuyo prefijo coincide por completo, gana la más larga.',
    fr: 'La destination est confrontée à chaque ligne de la table ; parmi les lignes dont le préfixe correspond entièrement, la plus longue l’emporte.',
    hi: 'गंतव्य को तालिका की हर पंक्ति से मिलाया जाता है; जिन पंक्तियों का प्रीफ़िक्स पूरा मिलता है, उनमें सबसे लंबी चुनी जाती है।',
    id: 'Tujuan dicocokkan dengan setiap baris tabel; dari baris yang prefiksnya cocok sampai habis, yang terpanjang dipilih.',
    pt: 'O destino é comparado com cada linha da tabela; entre as linhas cujo prefixo coincide por inteiro, vence a mais longa.',
  },
  algorithm: 'module:longestPrefixMatch',
  scene: 'module:longestPrefixMatchScene',
  initialData: {
    type: 'longest-prefix-match',
    stepMs: 1300,
    dest: '10.1.37.5',
    table: [
      { prefix: '10.0.0.0/8', out: 'eth1' },
      { prefix: '10.1.40.0/21', out: 'eth2' },
      { prefix: '0.0.0.0/0', out: 'eth0' },
      { prefix: '10.1.32.0/19', out: 'eth3' },
      { prefix: '10.1.0.0/16', out: 'eth4' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Destination {addr}. Rows to check: {n}.',
      ko: '목적지 {addr}. 맞춰 볼 줄: {n}.',
      ja: '宛先 {addr}。照合する行: {n}。',
      zh: '目的地址 {addr}。待比对的行: {n}。',
      ar: 'الوجهة {addr}. الصفوف المطلوب مطابقتها: {n}.',
      es: 'Destino {addr}. Filas por comprobar: {n}.',
      fr: 'Destination {addr}. Lignes à vérifier : {n}.',
      hi: 'गंतव्य {addr}। जाँचने वाली पंक्तियाँ: {n}।',
      id: 'Tujuan {addr}. Baris yang dicocokkan: {n}.',
      pt: 'Destino {addr}. Linhas a verificar: {n}.',
    },
    'caption.match': {
      en: 'Row {row} ({prefix}): every bit up to /{len} agrees. Match, length {len}.',
      ko: '줄 {row} ({prefix}): /{len} 까지 비트가 모두 같다. 맞음, 길이 {len}.',
      ja: '行 {row} ({prefix}): /{len} までのビットがすべて一致。一致、長さ {len}。',
      zh: '第 {row} 行 ({prefix}): 到 /{len} 为止的位全部相同。匹配，长度 {len}。',
      ar: 'الصف {row} ({prefix}): كل البتات حتى /{len} متطابقة. تطابق، الطول {len}.',
      es: 'Fila {row} ({prefix}): todos los bits hasta /{len} coinciden. Coincide, longitud {len}.',
      fr: 'Ligne {row} ({prefix}) : tous les bits jusqu’à /{len} concordent. Correspondance, longueur {len}.',
      hi: 'पंक्ति {row} ({prefix}): /{len} तक हर बिट मिलता है। मिलान, लंबाई {len}।',
      id: 'Baris {row} ({prefix}): semua bit sampai /{len} sama. Cocok, panjang {len}.',
      pt: 'Linha {row} ({prefix}): todos os bits até /{len} coincidem. Corresponde, comprimento {len}.',
    },
    'caption.matchZero': {
      en: 'Row {row} ({prefix}): no bits to compare. Match, length {len}.',
      ko: '줄 {row} ({prefix}): 견줄 비트가 없다. 맞음, 길이 {len}.',
      ja: '行 {row} ({prefix}): 比べるビットがない。一致、長さ {len}。',
      zh: '第 {row} 行 ({prefix}): 没有要比较的位。匹配，长度 {len}。',
      ar: 'الصف {row} ({prefix}): لا بتات للمقارنة. تطابق، الطول {len}.',
      es: 'Fila {row} ({prefix}): no hay bits que comparar. Coincide, longitud {len}.',
      fr: 'Ligne {row} ({prefix}) : aucun bit à comparer. Correspondance, longueur {len}.',
      hi: 'पंक्ति {row} ({prefix}): मिलाने को कोई बिट नहीं। मिलान, लंबाई {len}।',
      id: 'Baris {row} ({prefix}): tidak ada bit untuk dibandingkan. Cocok, panjang {len}.',
      pt: 'Linha {row} ({prefix}): não há bits a comparar. Corresponde, comprimento {len}.',
    },
    'caption.miss': {
      en: 'Row {row} ({prefix}): equal through bit {same}, differs at bit {bit}. No match.',
      ko: '줄 {row} ({prefix}): {same} 번째 비트까지 같고 {bit} 번째에서 갈린다. 안 맞음.',
      ja: '行 {row} ({prefix}): {same} ビット目まで同じで、{bit} ビット目で食い違う。不一致。',
      zh: '第 {row} 行 ({prefix}): 到第 {same} 位都相同，第 {bit} 位不同。不匹配。',
      ar: 'الصف {row} ({prefix}): متطابق حتى البت {same}، ويختلف عند البت {bit}. لا تطابق.',
      es: 'Fila {row} ({prefix}): igual hasta el bit {same}, difiere en el bit {bit}. No coincide.',
      fr: 'Ligne {row} ({prefix}) : identique jusqu’au bit {same}, diffère au bit {bit}. Pas de correspondance.',
      hi: 'पंक्ति {row} ({prefix}): बिट {same} तक समान, बिट {bit} पर अलग। मिलान नहीं।',
      id: 'Baris {row} ({prefix}): sama sampai bit {same}, berbeda di bit {bit}. Tidak cocok.',
      pt: 'Linha {row} ({prefix}): igual até o bit {same}, difere no bit {bit}. Não corresponde.',
    },
    'caption.pick': {
      en: 'Matched lengths: {lens}. Longest: /{best}, row {row}, out {port}.',
      ko: '맞은 길이: {lens}. 가장 긴 것: /{best}, 줄 {row}, 나가는 문 {port}.',
      ja: '一致した長さ: {lens}。最長: /{best}、行 {row}、出口 {port}。',
      zh: '匹配的长度: {lens}。最长: /{best}，第 {row} 行，出口 {port}。',
      ar: 'الأطوال المتطابقة: {lens}. الأطول: /{best}، الصف {row}، المخرج {port}.',
      es: 'Longitudes que coinciden: {lens}. La más larga: /{best}, fila {row}, salida {port}.',
      fr: 'Longueurs qui correspondent : {lens}. La plus longue : /{best}, ligne {row}, sortie {port}.',
      hi: 'मिली लंबाइयाँ: {lens}। सबसे लंबी: /{best}, पंक्ति {row}, निकास {port}।',
      id: 'Panjang yang cocok: {lens}. Terpanjang: /{best}, baris {row}, keluar {port}.',
      pt: 'Comprimentos que correspondem: {lens}. O mais longo: /{best}, linha {row}, saída {port}.',
    },
    'label.dest': {
      en: 'Destination',
      ko: '목적지',
      ja: '宛先',
      zh: '目的地址',
      ar: 'الوجهة',
      es: 'Destino',
      fr: 'Destination',
      hi: 'गंतव्य',
      id: 'Tujuan',
      pt: 'Destino',
    },
    'label.chosen': {
      en: 'Chosen',
      ko: '고른 줄',
      ja: '選んだ行',
      zh: '选中的行',
      ar: 'المختار',
      es: 'Elegida',
      fr: 'Retenue',
      hi: 'चुनी गई',
      id: 'Terpilih',
      pt: 'Escolhida',
    },
    'label.prefix': {
      en: 'Prefix',
      ko: '접두',
      ja: 'プレフィックス',
      zh: '前缀',
      ar: 'البادئة',
      es: 'Prefijo',
      fr: 'Préfixe',
      hi: 'प्रीफ़िक्स',
      id: 'Prefiks',
      pt: 'Prefixo',
    },
    'label.out': {
      en: 'Out',
      ko: '나가는 문',
      ja: '出口',
      zh: '出口',
      ar: 'المخرج',
      es: 'Salida',
      fr: 'Sortie',
      hi: 'निकास',
      id: 'Keluar',
      pt: 'Saída',
    },
  },
  blocks: {
    stage: { type: 'longest-prefix-match-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
