import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const diffusionFacet: FacetJson = {
  id: 'facet:diffusion',
  title: {
    en: 'Diffusion: removing noise in passes',
    ko: '확산 모형: 잡음을 나눠 걷어내기',
    ja: '拡散モデル: ノイズを数回に分けて取り除く',
    zh: '扩散模型：分多次去除噪声',
    ar: 'نموذج الانتشار: إزالة الضجيج على دفعات',
    es: 'Difusión: quitar el ruido por pasadas',
    fr: 'Diffusion : retirer le bruit en plusieurs passes',
    hi: 'डिफ़्यूज़न: शोर को कई बार में हटाना',
    id: 'Difusi: membuang derau dalam beberapa putaran',
    pt: 'Difusão: remover o ruído em passadas',
  },
  description: {
    en: 'Five samples start from the same noise and remove it T times. Turn T and watch whether the end points stay in a blurred mix between the two data or reach one of them.',
    ko: '표본 다섯이 같은 잡음에서 출발해 잡음을 T 번 걷어낸다. T 를 돌려 끝점이 두 자료 사이의 흐린 섞임에 머무는지, 자료 하나에 닿는지 본다.',
    ja: '5 つの標本が同じノイズから出発し、ノイズを T 回取り除く。T を回して、終点が 2 つのデータの間のぼやけた混ざりに留まるか、どちらかのデータに届くかを見る。',
    zh: '五个样本从同样的噪声出发，把噪声去除 T 次。调节 T，看终点停在两个数据之间的模糊混合里，还是抵达其中一个数据。',
    ar: 'تبدأ خمس عيّنات من الضجيج نفسه وتزيله T مرة. غيّر T وراقب هل تبقى نقاط النهاية في مزيج ضبابي بين البيانين أم تصل إلى أحدهما.',
    es: 'Cinco muestras parten del mismo ruido y lo quitan T veces. Gira T y observa si los puntos finales se quedan en una mezcla borrosa entre los dos datos o llegan a uno de ellos.',
    fr: 'Cinq échantillons partent du même bruit et le retirent T fois. Tournez T et voyez si les points finaux restent dans un mélange flou entre les deux données ou en atteignent une.',
    hi: 'पाँच नमूने एक ही शोर से शुरू होकर उसे T बार हटाते हैं। T बदलकर देखें कि अंतिम बिंदु दोनों डेटा के बीच धुँधले मिश्रण में रुकते हैं या किसी एक डेटा तक पहुँचते हैं।',
    id: 'Lima sampel berangkat dari derau yang sama dan membuangnya T kali. Putar T dan lihat apakah titik akhir tetap di campuran kabur di antara dua data atau mencapai salah satunya.',
    pt: 'Cinco amostras partem do mesmo ruído e o removem T vezes. Gire T e veja se os pontos finais ficam numa mistura borrada entre os dois dados ou chegam a um deles.',
  },
  algorithm: 'module:diffusion',
  projector: 'module:diffusionProjector',
  initialData: {
    type: 'diffusion',
    stepMs: 1200,
    settleMs: 1500,
    tStepMs: [2400, 2000, 1400, 800, 500],
    stepsLadder: [1, 2, 5, 10, 20],
    defaultSteps: 5,
    dataP: [-1.6, 0.4],
    dataQ: [1.6, -0.4],
    alphaBarEnd: 0.05,
    settleDistance: 0.05,
    plane: { xMin: -3, xMax: 3, yMin: -2, yMax: 2 },
    seeds: [77593189, 247443295, 797468573, 1063662932, 1650159263],
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'diffusion-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'steps',
          name: 'steps',
          label: {
            en: 'Denoising passes T',
            ko: '걷어내는 횟수 T',
            ja: 'ノイズ除去の回数 T',
            zh: '去噪次数 T',
            ar: 'عدد مرات إزالة الضجيج T',
            es: 'Pasadas de limpieza T',
            fr: 'Passes de débruitage T',
            hi: 'शोर हटाने के चक्र T',
            id: 'Putaran buang derau T',
            pt: 'Passadas de limpeza T',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 5, label: '5', default: true },
            { value: 10, label: '10' },
            { value: 20, label: '20' },
          ],
        },
      ],
      metrics: [
        {
          name: 'denoise-steps',
          label: {
            en: 'Passes done',
            ko: '걷어낸 횟수',
            ja: '取り除いた回数',
            zh: '已去噪次数',
            ar: 'المرات المنجزة',
            es: 'Pasadas hechas',
            fr: 'Passes faites',
            hi: 'पूरे हुए चक्र',
            id: 'Putaran selesai',
            pt: 'Passadas feitas',
          },
          initial: 0,
        },
        {
          name: 'settled',
          label: {
            en: 'Samples reached',
            ko: '닿은 표본',
            ja: '届いた標本',
            zh: '抵达的样本',
            ar: 'العيّنات الواصلة',
            es: 'Muestras que llegaron',
            fr: 'Échantillons arrivés',
            hi: 'पहुँचे नमूने',
            id: 'Sampel yang sampai',
            pt: 'Amostras que chegaram',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:diffusion-imperative',
      label: {
        en: 'One reverse pass',
        ko: '역과정 한 번',
        ja: '逆過程 1 回',
        zh: '一次逆过程',
        ar: 'تمريرة عكسية واحدة',
        es: 'Una pasada inversa',
        fr: 'Une passe inverse',
        hi: 'एक उलटा चक्र',
        id: 'Satu putaran balik',
        pt: 'Uma passada reversa',
      },
    },
  },
  messages: {
    'caption.round': {
      en: 'T = {steps} passes · β = {beta}',
      ko: 'T = {steps}번 걷어냄 · β = {beta}',
      ja: 'T = {steps} 回除去 · β = {beta}',
      zh: 'T = {steps} 次去噪 · β = {beta}',
      ar: 'T = {steps} مرات · β = {beta}',
      es: 'T = {steps} pasadas · β = {beta}',
      fr: 'T = {steps} passes · β = {beta}',
      hi: 'T = {steps} चक्र · β = {beta}',
      id: 'T = {steps} putaran · β = {beta}',
      pt: 'T = {steps} passadas · β = {beta}',
    },
    'caption.start': {
      en: 'Start: noise x_T',
      ko: '시작: 잡음 x_T',
      ja: '開始: ノイズ x_T',
      zh: '开始：噪声 x_T',
      ar: 'البداية: ضجيج x_T',
      es: 'Inicio: ruido x_T',
      fr: 'Départ : bruit x_T',
      hi: 'शुरुआत: शोर x_T',
      id: 'Mulai: derau x_T',
      pt: 'Início: ruído x_T',
    },
    'caption.reverse': {
      en: 'Remove noise: t {from} → {to}',
      ko: '잡음 걷어냄: t {from} → {to}',
      ja: 'ノイズ除去: t {from} → {to}',
      zh: '去除噪声：t {from} → {to}',
      ar: 'إزالة الضجيج: t {from} → {to}',
      es: 'Quitar ruido: t {from} → {to}',
      fr: 'Retrait du bruit : t {from} → {to}',
      hi: 'शोर हटाना: t {from} → {to}',
      id: 'Buang derau: t {from} → {to}',
      pt: 'Remover ruído: t {from} → {to}',
    },
    'caption.settle': {
      en: 'Reached a datum: {n}/{total}',
      ko: '자료에 닿음: {n}/{total}',
      ja: 'データに到達: {n}/{total}',
      zh: '抵达数据：{n}/{total}',
      ar: 'وصلت إلى بيان: {n}/{total}',
      es: 'Llegaron a un dato: {n}/{total}',
      fr: 'Donnée atteinte : {n}/{total}',
      hi: 'डेटा तक पहुँचे: {n}/{total}',
      id: 'Mencapai data: {n}/{total}',
      pt: 'Chegaram a um dado: {n}/{total}',
    },
    'label.dataP': { en: 'P', ko: 'P', ja: 'P', zh: 'P', ar: 'P', es: 'P', fr: 'P', hi: 'P', id: 'P', pt: 'P' },
    'label.dataQ': { en: 'Q', ko: 'Q', ja: 'Q', zh: 'Q', ar: 'Q', es: 'Q', fr: 'Q', hi: 'Q', id: 'Q', pt: 'Q' },
    'label.distance': {
      en: '{side} {distance}',
      ko: '{side} {distance}',
      ja: '{side} {distance}',
      zh: '{side} {distance}',
      ar: '{side} {distance}',
      es: '{side} {distance}',
      fr: '{side} {distance}',
      hi: '{side} {distance}',
      id: '{side} {distance}',
      pt: '{side} {distance}',
    },
    'label.legend': {
      en: 'Pale dot = prediction x̂₀ · line = path so far · ring = reached a datum',
      ko: '옅은 점 = 예측 x̂₀ · 선 = 지나온 자국 · 고리 = 자료에 닿음',
      ja: '薄い点 = 予測 x̂₀ · 線 = 通った跡 · 輪 = データに到達',
      zh: '淡点 = 预测 x̂₀ · 线 = 走过的轨迹 · 圆环 = 抵达数据',
      ar: 'النقطة الباهتة = التنبؤ x̂₀ · الخط = المسار حتى الآن · الحلقة = وصلت إلى بيان',
      es: 'Punto pálido = predicción x̂₀ · línea = camino recorrido · anillo = llegó a un dato',
      fr: 'Point pâle = prédiction x̂₀ · ligne = chemin parcouru · anneau = donnée atteinte',
      hi: 'हल्का बिंदु = अनुमान x̂₀ · रेखा = अब तक का रास्ता · छल्ला = डेटा तक पहुँचा',
      id: 'Titik pucat = prediksi x̂₀ · garis = jejak sejauh ini · cincin = mencapai data',
      pt: 'Ponto pálido = previsão x̂₀ · linha = caminho percorrido · anel = chegou a um dado',
    },
  },
};
