import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 최댓값 풀링은 특징 지도의 네 칸을 어떻게 한 칸으로 줄이고, 그때 무엇이 남고 무엇이 버려지는가.
 */
export const shrinkBySummaryFacet: FacetJson = {
  id: 'facet:shrinkBySummary',
  title: {
    en: 'Max pooling: four cells become one',
    ko: '최댓값 풀링 — 네 칸이 한 칸으로',
    ja: '最大値プーリング — 4マスが1マスに',
    zh: '最大池化——四格变一格',
    ar: 'التجميع الأقصى: أربع خلايا تصبح واحدة',
    es: 'Max pooling: cuatro celdas se vuelven una',
    fr: 'Max pooling : quatre cases deviennent une',
    hi: 'मैक्स पूलिंग: चार खाने एक बनते हैं',
    id: 'Max pooling: empat sel menjadi satu',
    pt: 'Max pooling: quatro células viram uma',
  },
  description: {
    en: 'A 2×2 window steps across the feature map two cells at a time. Only the largest of its four values goes up to the smaller map; the other three are dropped.',
    ko: '2×2 창이 특징 지도 위를 두 칸씩 옮겨 간다. 창 안 네 수 가운데 가장 큰 하나만 줄어든 지도로 올라가고 나머지 셋은 버려진다.',
    ja: '2×2 の窓が特徴マップの上を2マスずつ移動する。窓の中の4つの値のうち最大の1つだけが小さな地図へ上がり、残りの3つは捨てられる。',
    zh: '2×2 窗口在特征图上每次移动两格。窗口内四个数中只有最大的一个升到缩小后的图上，其余三个被丢弃。',
    ar: 'تتحرك نافذة 2×2 عبر خريطة السمات خليتين في كل مرة. أكبر قيمة من قيمها الأربع فقط تصعد إلى الخريطة الأصغر، وتُسقط الثلاث الأخرى.',
    es: 'Una ventana 2×2 recorre el mapa de características de dos en dos celdas. Solo el mayor de sus cuatro valores sube al mapa reducido; los otros tres se descartan.',
    fr: 'Une fenêtre 2×2 parcourt la carte de caractéristiques deux cases à la fois. Seule la plus grande de ses quatre valeurs monte dans la carte réduite ; les trois autres sont écartées.',
    hi: '2×2 खिड़की फ़ीचर मैप पर दो-दो खाने आगे बढ़ती है। उसके चार मानों में से केवल सबसे बड़ा छोटे मैप में ऊपर जाता है; बाकी तीन छोड़ दिए जाते हैं।',
    id: 'Jendela 2×2 bergeser di atas peta fitur dua sel sekaligus. Hanya nilai terbesar dari empat nilainya yang naik ke peta yang lebih kecil; tiga lainnya dibuang.',
    pt: 'Uma janela 2×2 percorre o mapa de características de duas em duas células. Só o maior dos seus quatro valores sobe para o mapa reduzido; os outros três são descartados.',
  },
  algorithm: 'module:shrinkBySummary',
  scene: 'module:shrinkBySummaryScene',
  initialData: {
    type: 'shrink-by-summary',
    grid: [
      [1, 4, 0, 2],
      [3, 2, 5, 1],
      [0, 6, 2, 3],
      [2, 1, 4, 0],
    ],
    window: 2,
    stride: 2,
    stepMs: 1800,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Each {k}×{k} window keeps only its largest value. Stride: {s}.',
      ko: '{k}×{k} 창마다 가장 큰 수 하나만 남긴다. 보폭: {s}.',
      ja: '{k}×{k} の窓ごとに最大の値を1つだけ残す。ストライド: {s}。',
      zh: '每个 {k}×{k} 窗口只保留最大的一个值。步幅：{s}。',
      ar: 'كل نافذة {k}×{k} تحتفظ بأكبر قيمة فيها فقط. الخطوة: {s}.',
      es: 'Cada ventana {k}×{k} conserva solo su valor más grande. Paso: {s}.',
      fr: 'Chaque fenêtre {k}×{k} ne garde que sa plus grande valeur. Pas : {s}.',
      hi: 'हर {k}×{k} खिड़की सिर्फ़ अपना सबसे बड़ा मान रखती है। स्ट्राइड: {s}।',
      id: 'Setiap jendela {k}×{k} hanya menyimpan nilai terbesarnya. Langkah: {s}.',
      pt: 'Cada janela {k}×{k} guarda só o seu maior valor. Passo: {s}.',
    },
    'caption.pool': {
      en: 'Window at ({r}, {c}): largest is {m}, at ({mr}, {mc}).',
      ko: '창 ({r}, {c}): 가장 큰 수 {m}, 자리 ({mr}, {mc}).',
      ja: '窓 ({r}, {c}): 最大は {m}、位置 ({mr}, {mc})。',
      zh: '窗口 ({r}, {c})：最大值 {m}，位置 ({mr}, {mc})。',
      ar: 'النافذة عند ({r}, {c}): الأكبر {m}، في ({mr}, {mc}).',
      es: 'Ventana en ({r}, {c}): el mayor es {m}, en ({mr}, {mc}).',
      fr: 'Fenêtre en ({r}, {c}) : la plus grande est {m}, en ({mr}, {mc}).',
      hi: 'खिड़की ({r}, {c}): सबसे बड़ा {m}, स्थान ({mr}, {mc})।',
      id: 'Jendela di ({r}, {c}): terbesar {m}, di ({mr}, {mc}).',
      pt: 'Janela em ({r}, {c}): o maior é {m}, em ({mr}, {mc}).',
    },
    'caption.pick': {
      en: 'Only it goes up; the other cells fall away.',
      ko: '그 수만 올라가고 나머지 칸은 떨어져 나간다.',
      ja: 'それだけが上がり、残りのマスは落ちていく。',
      zh: '只有它升上去，其余格子掉落。',
      ar: 'هي وحدها تصعد، وتسقط الخلايا الأخرى.',
      es: 'Solo ese sube; las demás celdas caen.',
      fr: 'Elle seule monte ; les autres cases tombent.',
      hi: 'सिर्फ़ वही ऊपर जाता है; बाकी खाने गिर जाते हैं।',
      id: 'Hanya nilai itu yang naik; sel lainnya jatuh.',
      pt: 'Só ele sobe; as outras células caem.',
    },
    'caption.done': {
      en: 'Cells: {from} → {to}',
      ko: '칸: {from} → {to}',
      ja: 'マス: {from} → {to}',
      zh: '格数：{from} → {to}',
      ar: 'الخلايا: {from} ← {to}',
      es: 'Celdas: {from} → {to}',
      fr: 'Cases : {from} → {to}',
      hi: 'खाने: {from} → {to}',
      id: 'Sel: {from} → {to}',
      pt: 'Células: {from} → {to}',
    },
    'label.input': {
      en: 'Feature map {rows}×{cols}',
      ko: '특징 지도 {rows}×{cols}',
      ja: '特徴マップ {rows}×{cols}',
      zh: '特征图 {rows}×{cols}',
      ar: 'خريطة السمات {rows}×{cols}',
      es: 'Mapa de características {rows}×{cols}',
      fr: 'Carte de caractéristiques {rows}×{cols}',
      hi: 'फ़ीचर मैप {rows}×{cols}',
      id: 'Peta fitur {rows}×{cols}',
      pt: 'Mapa de características {rows}×{cols}',
    },
    'label.output': {
      en: 'Pooled map {rows}×{cols}',
      ko: '줄어든 지도 {rows}×{cols}',
      ja: '縮んだマップ {rows}×{cols}',
      zh: '池化后的图 {rows}×{cols}',
      ar: 'الخريطة المجمّعة {rows}×{cols}',
      es: 'Mapa reducido {rows}×{cols}',
      fr: 'Carte réduite {rows}×{cols}',
      hi: 'पूल किया मैप {rows}×{cols}',
      id: 'Peta hasil pooling {rows}×{cols}',
      pt: 'Mapa reduzido {rows}×{cols}',
    },
    'label.kept': {
      en: 'Kept: {n}',
      ko: '남은 칸: {n}',
      ja: '残ったマス: {n}',
      zh: '保留：{n}',
      ar: 'المحتفظ بها: {n}',
      es: 'Conservadas: {n}',
      fr: 'Gardées : {n}',
      hi: 'बचे: {n}',
      id: 'Disimpan: {n}',
      pt: 'Mantidas: {n}',
    },
    'label.dropped': {
      en: 'Dropped: {n}',
      ko: '버린 칸: {n}',
      ja: '捨てたマス: {n}',
      zh: '丢弃：{n}',
      ar: 'المُسقطة: {n}',
      es: 'Descartadas: {n}',
      fr: 'Écartées : {n}',
      hi: 'छोड़े गए: {n}',
      id: 'Dibuang: {n}',
      pt: 'Descartadas: {n}',
    },
  },
  blocks: {
    stage: { type: 'shrink-by-summary-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
