import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

/**
 * @piece
 * 한 처리기 안에서 상태를 세 번 바꾸면 화면 조각은 몇 번 다시 그려지는가?
 */
export const coalesceUpdatesFacet: FacetJson = {
  id: 'facet:coalesceUpdates',
  title: {
    en: 'Coalesced updates',
    ko: '모아서 한 번에 그리기',
    ja: 'まとめて一度に描く',
    zh: '合并更新，一次绘制',
    ar: 'تحديثات مجمَّعة',
    es: 'Actualizaciones combinadas',
    fr: 'Mises à jour regroupées',
    hi: 'एक साथ जोड़े गए अपडेट',
    id: 'Pembaruan yang digabung',
    pt: 'Atualizações agrupadas',
  },
  description: {
    en: 'A handler writes state three times. The screen still redraws only once, at the end.',
    ko: '한 처리기가 상태를 세 번 쓴다. 그래도 화면은 끝에 딱 한 번만 다시 그려진다.',
    ja: 'ハンドラーが状態を三回書き込む。それでも画面は最後に一度だけ再描画される。',
    zh: '一个处理器写了三次状态,但屏幕最后只重绘一次。',
    ar: 'معالج واحد يكتب الحالة ثلاث مرات، لكن الشاشة تُعاد رسمها مرة واحدة فقط في النهاية.',
    es: 'Un manejador escribe el estado tres veces, pero la pantalla se vuelve a dibujar una sola vez, al final.',
    fr: 'Un gestionnaire écrit l’état trois fois, mais l’écran ne se redessine qu’une seule fois, à la fin.',
    hi: 'एक हैंडलर स्थिति को तीन बार लिखता है, फिर भी स्क्रीन अंत में केवल एक बार फिर से बनती है।',
    id: 'Satu handler menulis status tiga kali, tetapi layar hanya digambar ulang sekali, di akhir.',
    pt: 'Um manipulador escreve o estado três vezes, mas a tela só é redesenhada uma vez, no final.',
  },
  algorithm: 'module:coalesceUpdates',
  scene: 'module:coalesceUpdatesScene',
  initialData: {
    type: 'coalesce-updates',
    code: ['function onDrag()', '    left = 40', '    top = 20', '    left = 90'],
    initial: { left: 0, top: 0 },
    writes: [
      { name: 'left', value: 40 },
      { name: 'top', value: 20 },
      { name: 'left', value: 90 },
    ],
    stepMs: 1800,
  },
  shuffleOnReset: false,
  messages: {
    'caption.initial': {
      en: 'Screen at left {left}, top {top}. Drawn {renders} times so far.',
      ko: '화면은 left {left} · top {top}. 지금까지 그린 수는 {renders}.',
      ja: '画面は left {left} ・ top {top}。今までに描画した回数は {renders}。',
      zh: '屏幕位于 left {left} · top {top}。目前已绘制 {renders} 次。',
      ar: 'الشاشة عند left {left}، top {top}. عدد مرات الرسم حتى الآن {renders}.',
      es: 'Pantalla en left {left}, top {top}. Dibujada {renders} veces hasta ahora.',
      fr: 'Écran à left {left}, top {top}. Dessiné {renders} fois jusqu’ici.',
      hi: 'स्क्रीन left {left}, top {top} पर है। अब तक {renders} बार बनी है।',
      id: 'Layar di left {left}, top {top}. Sejauh ini digambar {renders} kali.',
      pt: 'Tela em left {left}, top {top}. Desenhada {renders} vezes até agora.',
    },
    'caption.write': {
      en: 'Write {name} = {value} enters the queue.',
      ko: '쓰기 {name} = {value} 이(가) 모아 두는 자리에 들어간다.',
      ja: '書き込み {name} = {value} がキューに入る。',
      zh: '写入 {name} = {value} 进入待处理队列。',
      ar: 'الكتابة {name} = {value} تدخل قائمة الانتظار.',
      es: 'La escritura {name} = {value} entra en la cola.',
      fr: 'L’écriture {name} = {value} entre dans la file d’attente.',
      hi: 'लेखन {name} = {value} कतार में जाता है।',
      id: 'Penulisan {name} = {value} masuk ke antrean.',
      pt: 'A escrita {name} = {value} entra na fila.',
    },
    'caption.overwrite': {
      en: 'Write {name} = {value} replaces the queued {previous}.',
      ko: '쓰기 {name} = {value} 이(가) 모아 둔 {previous} 을(를) 덮는다.',
      ja: '書き込み {name} = {value} がキューにあった {previous} を上書きする。',
      zh: '写入 {name} = {value} 覆盖了排队中的 {previous}。',
      ar: 'الكتابة {name} = {value} تستبدل القيمة المنتظرة {previous}.',
      es: 'La escritura {name} = {value} reemplaza el {previous} en cola.',
      fr: 'L’écriture {name} = {value} remplace le {previous} en file d’attente.',
      hi: 'लेखन {name} = {value} कतार में रखे {previous} की जगह लेता है।',
      id: 'Penulisan {name} = {value} menggantikan {previous} yang mengantre.',
      pt: 'A escrita {name} = {value} substitui o {previous} enfileirado.',
    },
    'caption.flush': {
      en: 'Handler ends. Draw once — screen left {left}, top {top}. Drawn {renders} times.',
      ko: '처리기가 끝난다. 한 번 그린다 — 화면 left {left} · top {top}. 그린 수 {renders}.',
      ja: 'ハンドラーが終わる。一度だけ描く — 画面 left {left} ・ top {top}。描画回数 {renders}。',
      zh: '处理器结束。绘制一次 — 屏幕 left {left} · top {top}。绘制次数 {renders}。',
      ar: 'ينتهي المعالج. رسم مرة واحدة — الشاشة left {left}، top {top}. عدد مرات الرسم {renders}.',
      es: 'El manejador termina. Se dibuja una vez — pantalla left {left}, top {top}. Dibujada {renders} veces.',
      fr: 'Le gestionnaire se termine. Un seul dessin — écran left {left}, top {top}. Dessiné {renders} fois.',
      hi: 'हैंडलर समाप्त होता है। एक बार बनता है — स्क्रीन left {left}, top {top}। बना {renders} बार।',
      id: 'Handler selesai. Gambar sekali — layar left {left}, top {top}. Digambar {renders} kali.',
      pt: 'O manipulador termina. Desenha uma vez — tela left {left}, top {top}. Desenhada {renders} vezes.',
    },
    'label.scheduled': {
      en: 'Scheduled draws: {n}',
      ko: '걸어 둔 그리기: {n}',
      ja: '予約された描画: {n}',
      zh: '已排定的绘制: {n}',
      ar: 'عمليات الرسم المجدولة: {n}',
      es: 'Dibujos programados: {n}',
      fr: 'Dessins planifiés : {n}',
      hi: 'निर्धारित ड्रॉ: {n}',
      id: 'Gambar terjadwal: {n}',
      pt: 'Desenhos agendados: {n}',
    },
    'label.code': {
      en: 'Handler',
      ko: '처리기',
      ja: 'ハンドラー',
      zh: '处理器',
      ar: 'المعالج',
      es: 'Manejador',
      fr: 'Gestionnaire',
      hi: 'हैंडलर',
      id: 'Handler',
      pt: 'Manipulador',
    },
    'label.pending': {
      en: 'Queued',
      ko: '모아 둔 것',
      ja: 'キュー',
      zh: '排队中',
      ar: 'قيد الانتظار',
      es: 'En cola',
      fr: 'En file d’attente',
      hi: 'कतार में',
      id: 'Dalam antrean',
      pt: 'Na fila',
    },
    'label.screen': {
      en: 'Screen',
      ko: '화면',
      ja: '画面',
      zh: '屏幕',
      ar: 'الشاشة',
      es: 'Pantalla',
      fr: 'Écran',
      hi: 'स्क्रीन',
      id: 'Layar',
      pt: 'Tela',
    },
    'label.neverDrawn': {
      en: 'Never drawn: {name} {value}',
      ko: '한 번도 그려지지 않음: {name} {value}',
      ja: '一度も描かれていない: {name} {value}',
      zh: '从未绘制: {name} {value}',
      ar: 'لم يُرسم أبدًا: {name} {value}',
      es: 'Nunca dibujado: {name} {value}',
      fr: 'Jamais dessiné : {name} {value}',
      hi: 'कभी नहीं बना: {name} {value}',
      id: 'Tidak pernah digambar: {name} {value}',
      pt: 'Nunca desenhado: {name} {value}',
    },
  },
  blocks: {
    stage: { type: 'coalesce-updates-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
