import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * @notation native
 *
 * 스크립트가 스타일을 바꾸고 곧바로 크기를 읽으면, 브라우저는 그 읽기에 답하려고 무엇을 하는가 —
 * 그것이 몇 번 일어나는가.
 *
 * 코드 글자는 실제 자바스크립트다 — `offsetWidth` 읽기와 `style.width` 쓰기가 곧 주장이다.
 */
export const forcedSyncLayoutFacet: FacetJson = {
  id: 'facet:forcedSyncLayout',
  title: {
    en: 'Forced synchronous layout',
    ko: '강제 동기 레이아웃',
    ja: '強制同期レイアウト',
    zh: '强制同步布局',
    ar: 'التخطيط المتزامن القسري',
    es: 'Diseño síncrono forzado',
    fr: 'Mise en page synchrone forcée',
    hi: 'ज़बरन समकालिक लेआउट',
    id: 'Tata letak sinkron paksa',
    pt: 'Layout síncrono forçado',
  },
  description: {
    en: 'A write only dirties layout; the next read stops the script until the whole page is measured again.',
    ko: '쓰기는 레이아웃을 더럽히기만 한다. 다음 읽기는 문서 전체를 다시 잴 때까지 스크립트를 멈춰 세운다.',
    ja: '書き込みはレイアウトを汚すだけ。次の読み取りはページ全体を測り直すまでスクリプトを止める。',
    zh: '写入只会把布局标脏；下一次读取会让脚本停下，直到整个页面重新测量完。',
    ar: 'الكتابة تجعل التخطيط متسخًا فقط؛ والقراءة التالية توقف السكربت حتى تُقاس الصفحة كلها من جديد.',
    es: 'Una escritura solo ensucia el diseño; la siguiente lectura detiene el script hasta medir de nuevo toda la página.',
    fr: 'Une écriture ne fait que salir la mise en page ; la lecture suivante arrête le script jusqu’à ce que toute la page soit remesurée.',
    hi: 'लिखना केवल लेआउट को गंदा करता है; अगला पढ़ना स्क्रिप्ट को तब तक रोकता है जब तक पूरा पेज फिर से नापा न जाए।',
    id: 'Penulisan hanya membuat tata letak kotor; pembacaan berikutnya menghentikan skrip sampai seluruh halaman diukur ulang.',
    pt: 'Uma escrita só suja o layout; a leitura seguinte para o script até a página inteira ser medida de novo.',
  },
  algorithm: 'module:forcedSyncLayout',
  scene: 'module:forcedSyncLayoutScene',
  initialData: {
    type: 'forced-sync-layout',
    stepMs: 1000,
    code: [
      'for (const box of boxes) {',
      '  const w = box.offsetWidth;',
      "  box.style.width = (w + 10) + 'px';",
      '}',
    ],
    boxes: [
      { id: 'box1', width: 100 },
      { id: 'box2', width: 120 },
      { id: 'box3', width: 140 },
      { id: 'box4', width: 160 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'The script is about to run. Layout is clean.',
      ko: '스크립트가 곧 돈다. 레이아웃은 깨끗하다.',
      ja: 'スクリプトがこれから走る。レイアウトはきれいだ。',
      zh: '脚本即将运行。布局是干净的。',
      ar: 'السكربت على وشك أن يعمل. التخطيط نظيف.',
      es: 'El script está por ejecutarse. El diseño está limpio.',
      fr: 'Le script va s’exécuter. La mise en page est propre.',
      hi: 'स्क्रिप्ट चलने वाली है। लेआउट साफ़ है।',
      id: 'Skrip akan berjalan. Tata letak bersih.',
      pt: 'O script está prestes a rodar. O layout está limpo.',
    },
    'caption.read': {
      en: 'Read {box}.offsetWidth: {value}. Layout is clean, so nothing is measured.',
      ko: '읽기 {box}.offsetWidth: {value}. 레이아웃이 깨끗해 다시 재지 않는다.',
      ja: '読み取り {box}.offsetWidth: {value}。レイアウトがきれいなので測り直さない。',
      zh: '读取 {box}.offsetWidth: {value}。布局是干净的，所以不重新测量。',
      ar: 'قراءة {box}.offsetWidth: {value}. التخطيط نظيف، فلا يُقاس شيء.',
      es: 'Lectura {box}.offsetWidth: {value}. El diseño está limpio, así que no se mide nada.',
      fr: 'Lecture {box}.offsetWidth : {value}. La mise en page est propre, rien n’est mesuré.',
      hi: 'पढ़ना {box}.offsetWidth: {value}। लेआउट साफ़ है, इसलिए कुछ नहीं नापा जाता।',
      id: 'Baca {box}.offsetWidth: {value}. Tata letak bersih, jadi tidak ada yang diukur.',
      pt: 'Leitura {box}.offsetWidth: {value}. O layout está limpo, então nada é medido.',
    },
    'caption.write': {
      en: 'Write {box}.style.width: {width}px. Layout is now dirty. The script keeps going.',
      ko: '쓰기 {box}.style.width: {width}px. 레이아웃이 더러워졌다. 스크립트는 멈추지 않는다.',
      ja: '書き込み {box}.style.width: {width}px。レイアウトが汚れた。スクリプトは止まらない。',
      zh: '写入 {box}.style.width: {width}px。布局变脏了。脚本继续运行。',
      ar: 'كتابة {box}.style.width: {width}px. أصبح التخطيط متسخًا. السكربت يواصل.',
      es: 'Escritura {box}.style.width: {width}px. Ahora el diseño está sucio. El script sigue.',
      fr: 'Écriture {box}.style.width : {width}px. La mise en page est maintenant sale. Le script continue.',
      hi: 'लिखना {box}.style.width: {width}px। अब लेआउट गंदा है। स्क्रिप्ट चलती रहती है।',
      id: 'Tulis {box}.style.width: {width}px. Tata letak kini kotor. Skrip terus berjalan.',
      pt: 'Escrita {box}.style.width: {width}px. Agora o layout está sujo. O script continua.',
    },
    'caption.forced': {
      en: 'Layout is dirty, so reading {box}.offsetWidth stops the script. The whole page is measured again. Layouts: {n}',
      ko: '레이아웃이 더러워 {box}.offsetWidth 읽기가 스크립트를 멈춰 세운다. 문서 전체를 다시 잰다. 레이아웃: {n}',
      ja: 'レイアウトが汚れているので、{box}.offsetWidth の読み取りがスクリプトを止める。ページ全体を測り直す。レイアウト: {n}',
      zh: '布局是脏的，所以读取 {box}.offsetWidth 让脚本停下。整个页面重新测量。布局次数: {n}',
      ar: 'التخطيط متسخ، لذا توقف قراءة {box}.offsetWidth السكربت. تُقاس الصفحة كلها من جديد. التخطيطات: {n}',
      es: 'El diseño está sucio, así que leer {box}.offsetWidth detiene el script. Se mide de nuevo toda la página. Diseños: {n}',
      fr: 'La mise en page est sale : lire {box}.offsetWidth arrête le script. Toute la page est remesurée. Mises en page : {n}',
      hi: 'लेआउट गंदा है, इसलिए {box}.offsetWidth पढ़ना स्क्रिप्ट को रोक देता है। पूरा पेज फिर से नापा जाता है। लेआउट: {n}',
      id: 'Tata letak kotor, jadi membaca {box}.offsetWidth menghentikan skrip. Seluruh halaman diukur ulang. Tata letak: {n}',
      pt: 'O layout está sujo, então ler {box}.offsetWidth para o script. A página inteira é medida de novo. Layouts: {n}',
    },
    'caption.frame': {
      en: 'The script is done. Layout is dirty, so it runs once before the frame. Layouts: {n} (forced: {forced}, frame: {frame})',
      ko: '스크립트가 끝났다. 레이아웃이 더러워 프레임 앞에서 한 번 돈다. 레이아웃: {n} (강제: {forced}, 프레임: {frame})',
      ja: 'スクリプトが終わった。レイアウトが汚れているので、フレームの前に一度走る。レイアウト: {n} (強制: {forced}, フレーム: {frame})',
      zh: '脚本结束了。布局是脏的，所以在帧之前运行一次。布局次数: {n} (强制: {forced}, 帧: {frame})',
      ar: 'انتهى السكربت. التخطيط متسخ، فيعمل مرة واحدة قبل الإطار. التخطيطات: {n} (قسري: {forced}، إطار: {frame})',
      es: 'El script terminó. El diseño está sucio, así que corre una vez antes del cuadro. Diseños: {n} (forzados: {forced}, de cuadro: {frame})',
      fr: 'Le script est fini. La mise en page est sale, elle tourne une fois avant l’image. Mises en page : {n} (forcées : {forced}, d’image : {frame})',
      hi: 'स्क्रिप्ट पूरी हुई। लेआउट गंदा है, इसलिए फ़्रेम से पहले एक बार चलता है। लेआउट: {n} (ज़बरन: {forced}, फ़्रेम: {frame})',
      id: 'Skrip selesai. Tata letak kotor, jadi berjalan sekali sebelum frame. Tata letak: {n} (paksa: {forced}, frame: {frame})',
      pt: 'O script terminou. O layout está sujo, então roda uma vez antes do quadro. Layouts: {n} (forçados: {forced}, de quadro: {frame})',
    },
    'label.clean': {
      en: 'Layout: clean',
      ko: '레이아웃: 깨끗',
      ja: 'レイアウト: きれい',
      zh: '布局: 干净',
      ar: 'التخطيط: نظيف',
      es: 'Diseño: limpio',
      fr: 'Mise en page : propre',
      hi: 'लेआउट: साफ़',
      id: 'Tata letak: bersih',
      pt: 'Layout: limpo',
    },
    'label.dirty': {
      en: 'Layout: dirty',
      ko: '레이아웃: 더러움',
      ja: 'レイアウト: 汚れ',
      zh: '布局: 脏',
      ar: 'التخطيط: متسخ',
      es: 'Diseño: sucio',
      fr: 'Mise en page : sale',
      hi: 'लेआउट: गंदा',
      id: 'Tata letak: kotor',
      pt: 'Layout: sujo',
    },
    'label.stopped': {
      en: 'stopped',
      ko: '멈춤',
      ja: '停止',
      zh: '停住',
      ar: 'متوقف',
      es: 'detenido',
      fr: 'arrêté',
      hi: 'रुका',
      id: 'berhenti',
      pt: 'parado',
    },
    'label.end': {
      en: 'script done',
      ko: '스크립트 끝',
      ja: 'スクリプト終了',
      zh: '脚本结束',
      ar: 'انتهى السكربت',
      es: 'script terminado',
      fr: 'script fini',
      hi: 'स्क्रिप्ट पूरी',
      id: 'skrip selesai',
      pt: 'script terminado',
    },
    'label.layouts': {
      en: 'Layouts',
      ko: '레이아웃',
      ja: 'レイアウト',
      zh: '布局次数',
      ar: 'التخطيطات',
      es: 'Diseños',
      fr: 'Mises en page',
      hi: 'लेआउट',
      id: 'Tata letak',
      pt: 'Layouts',
    },
    'chip.forced': {
      en: 'forced',
      ko: '강제',
      ja: '強制',
      zh: '强制',
      ar: 'قسري',
      es: 'forzado',
      fr: 'forcée',
      hi: 'ज़बरन',
      id: 'paksa',
      pt: 'forçado',
    },
    'chip.frame': {
      en: 'frame',
      ko: '프레임',
      ja: 'フレーム',
      zh: '帧',
      ar: 'إطار',
      es: 'cuadro',
      fr: 'image',
      hi: 'फ़्रेम',
      id: 'frame',
      pt: 'quadro',
    },
  },
  blocks: {
    stage: { type: 'forced-sync-layout-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
