/**
 * @piece
 * 질문: 인덱스를 셋 걸면 읽기에서 얻은 만큼 쓰기에서 무엇을 치르는가?
 *
 * @notation native
 * (SQL) 질의 글자는 SQL 그대로 둔다 — SQL 자체가 이 분야의 소재라 가상 표기로 옮기지 않는다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const indexCostsWriteFacet: FacetJson = {
  id: 'facet:indexCostsWrite',
  title: {
    en: 'Indexes speed reads, slow writes',
    ko: '읽기가 빨라진 만큼 쓰기가 느려진다',
    ja: '読みが速くなるぶん書きが遅くなる',
    zh: '读得越快，写得越慢',
    ar: 'الفهارس تسرّع القراءة وتبطئ الكتابة',
    es: 'Los índices aceleran la lectura y frenan la escritura',
    fr: 'Les index accélèrent la lecture et ralentissent l’écriture',
    hi: 'इंडेक्स पढ़ना तेज़ और लिखना धीमा करते हैं',
    id: 'Indeks mempercepat baca, memperlambat tulis',
    pt: 'Índices aceleram a leitura e atrasam a escrita',
  },
  description: {
    en: 'The same table twice: a read narrows down to a few pages with indexes, while a write spreads out into the table and every index.',
    ko: '같은 표 둘. 인덱스가 있으면 읽기는 페이지 몇 장으로 좁혀 들어가고, 쓰기는 표와 인덱스마다 퍼져 들어간다.',
    ja: '同じ表を二つ。インデックスがあると読みは数ページに絞り込まれ、書きは表とすべてのインデックスへ広がる。',
    zh: '同一张表放两份。有索引时，读取收窄到几页，写入则扩散到表和每个索引。',
    ar: 'الجدول نفسه مرتين: مع الفهارس تضيق القراءة إلى صفحات قليلة، بينما تنتشر الكتابة إلى الجدول وكل فهرس.',
    es: 'La misma tabla dos veces: con índices, la lectura se estrecha a pocas páginas y la escritura se reparte entre la tabla y cada índice.',
    fr: 'La même table deux fois : avec des index, la lecture se resserre sur quelques pages, l’écriture se répand dans la table et chaque index.',
    hi: 'एक ही तालिका दो बार: इंडेक्स होने पर पढ़ना कुछ पन्नों तक सिमटता है, लिखना तालिका और हर इंडेक्स में फैलता है।',
    id: 'Tabel yang sama dua kali: dengan indeks, baca menyempit ke beberapa halaman, sedangkan tulis menyebar ke tabel dan setiap indeks.',
    pt: 'A mesma tabela duas vezes: com índices, a leitura se estreita a poucas páginas e a escrita se espalha pela tabela e por cada índice.',
  },
  algorithm: 'module:indexCostsWrite',
  scene: 'module:indexCostsWriteScene',
  initialData: {
    type: 'index-costs-write',
    stepMs: 1600,
    table: { name: 'users', columns: ['id', 'email', 'city'], rows: 23, perPage: 4 },
    indexes: [
      { name: 'users_pkey', column: 'id', height: 2 },
      { name: 'users_email_idx', column: 'email', height: 2 },
      { name: 'users_city_idx', column: 'city', height: 2 },
    ],
    select: {
      sql: "SELECT * FROM users WHERE email = 'kai@ex.com'",
      column: 'email',
      value: 'kai@ex.com',
      row: 18,
    },
    insert: {
      sql: "INSERT INTO users VALUES (24, 'zoe@ex.com', 'Busan')",
      values: [24, 'zoe@ex.com', 'Busan'],
    },
  },
  shuffleOnReset: false,
  messages: {
    'label.noIndex': {
      en: 'No index',
      ko: '인덱스 없음',
      ja: 'インデックスなし',
      zh: '无索引',
      ar: 'بلا فهرس',
      es: 'Sin índice',
      fr: 'Sans index',
      hi: 'इंडेक्स नहीं',
      id: 'Tanpa indeks',
      pt: 'Sem índice',
    },
    'label.withIndexes': {
      en: 'Indexes: {n}',
      ko: '인덱스: {n}',
      ja: 'インデックス: {n}',
      zh: '索引：{n}',
      ar: 'الفهارس: {n}',
      es: 'Índices: {n}',
      fr: 'Index : {n}',
      hi: 'इंडेक्स: {n}',
      id: 'Indeks: {n}',
      pt: 'Índices: {n}',
    },
    'label.root': {
      en: 'Root',
      ko: '뿌리',
      ja: 'ルート',
      zh: '根',
      ar: 'الجذر',
      es: 'Raíz',
      fr: 'Racine',
      hi: 'मूल',
      id: 'Akar',
      pt: 'Raiz',
    },
    'label.leaf': {
      en: 'Leaf',
      ko: '잎',
      ja: '葉',
      zh: '叶',
      ar: 'ورقة',
      es: 'Hoja',
      fr: 'Feuille',
      hi: 'पत्ता',
      id: 'Daun',
      pt: 'Folha',
    },
    'label.pagesRead': {
      en: 'Pages read: {n}',
      ko: '읽은 페이지: {n}',
      ja: '読んだページ: {n}',
      zh: '读取页数：{n}',
      ar: 'الصفحات المقروءة: {n}',
      es: 'Páginas leídas: {n}',
      fr: 'Pages lues : {n}',
      hi: 'पढ़े गए पन्ने: {n}',
      id: 'Halaman dibaca: {n}',
      pt: 'Páginas lidas: {n}',
    },
    'label.pagesWritten': {
      en: 'Pages written: {n}',
      ko: '쓴 페이지: {n}',
      ja: '書いたページ: {n}',
      zh: '写入页数：{n}',
      ar: 'الصفحات المكتوبة: {n}',
      es: 'Páginas escritas: {n}',
      fr: 'Pages écrites : {n}',
      hi: 'लिखे गए पन्ने: {n}',
      id: 'Halaman ditulis: {n}',
      pt: 'Páginas escritas: {n}',
    },
    'caption.start': {
      en: 'The same table twice, side by side.',
      ko: '같은 표 둘을 나란히 둔다.',
      ja: '同じ表を二つ並べる。',
      zh: '同一张表，并排放两份。',
      ar: 'الجدول نفسه مرتين، جنبًا إلى جنب.',
      es: 'La misma tabla dos veces, una junto a otra.',
      fr: 'La même table deux fois, côte à côte.',
      hi: 'एक ही तालिका दो बार, अगल-बगल।',
      id: 'Tabel yang sama dua kali, berdampingan.',
      pt: 'A mesma tabela duas vezes, lado a lado.',
    },
    'caption.select': {
      en: 'One read goes to both tables.',
      ko: '읽기 하나가 두 표에 간다.',
      ja: '一つの読みが両方の表へ行く。',
      zh: '同一个读取发往两张表。',
      ar: 'قراءة واحدة تذهب إلى الجدولين.',
      es: 'Una lectura va a las dos tablas.',
      fr: 'Une lecture part vers les deux tables.',
      hi: 'एक पढ़ना दोनों तालिकाओं में जाता है।',
      id: 'Satu baca dikirim ke kedua tabel.',
      pt: 'Uma leitura vai para as duas tabelas.',
    },
    'caption.insert': {
      en: 'One write goes to both tables.',
      ko: '쓰기 하나가 두 표에 간다.',
      ja: '一つの書きが両方の表へ行く。',
      zh: '同一个写入发往两张表。',
      ar: 'كتابة واحدة تذهب إلى الجدولين.',
      es: 'Una escritura va a las dos tablas.',
      fr: 'Une écriture part vers les deux tables.',
      hi: 'एक लिखना दोनों तालिकाओं में जाता है।',
      id: 'Satu tulis dikirim ke kedua tabel.',
      pt: 'Uma escrita vai para as duas tabelas.',
    },
    'caption.scan': {
      en: 'No index: table pages read {from}–{to}. Page of the match: {page}',
      ko: '인덱스 없음: 읽은 표 페이지 {from}–{to}. 찾는 줄의 페이지: {page}',
      ja: 'インデックスなし: 読んだ表のページ {from}–{to}。見つけた行のページ: {page}',
      zh: '无索引：读取的表页 {from}–{to}。匹配行所在页：{page}',
      ar: 'بلا فهرس: صفحات الجدول المقروءة {from}–{to}. صفحة الصف المطابق: {page}',
      es: 'Sin índice: páginas leídas de la tabla {from}–{to}. Página de la fila: {page}',
      fr: 'Sans index : pages de la table lues {from}–{to}. Page de la ligne : {page}',
      hi: 'इंडेक्स नहीं: पढ़े गए तालिका पन्ने {from}–{to}। मिली पंक्ति का पन्ना: {page}',
      id: 'Tanpa indeks: halaman tabel dibaca {from}–{to}. Halaman baris yang cocok: {page}',
      pt: 'Sem índice: páginas lidas da tabela {from}–{to}. Página da linha: {page}',
    },
    'caption.seek': {
      en: 'With indexes: {index} root, then leaf, then table page {page}.',
      ko: '인덱스 쪽: {index} 뿌리 → 잎 → 표 페이지 {page}.',
      ja: 'インデックス側: {index} のルート → 葉 → 表のページ {page}。',
      zh: '有索引：{index} 的根 → 叶 → 表的第 {page} 页。',
      ar: 'مع الفهارس: جذر {index}، ثم الورقة، ثم صفحة الجدول {page}.',
      es: 'Con índices: raíz de {index}, luego hoja, luego página {page} de la tabla.',
      fr: 'Avec index : racine de {index}, puis feuille, puis page {page} de la table.',
      hi: 'इंडेक्स के साथ: {index} का मूल, फिर पत्ता, फिर तालिका पन्ना {page}।',
      id: 'Dengan indeks: akar {index}, lalu daun, lalu halaman tabel {page}.',
      pt: 'Com índices: raiz de {index}, depois folha, depois página {page} da tabela.',
    },
    'caption.write': {
      en: 'No index: new row → table page {page}.',
      ko: '인덱스 없음: 새 줄 → 표 페이지 {page}.',
      ja: 'インデックスなし: 新しい行 → 表のページ {page}。',
      zh: '无索引：新行 → 表的第 {page} 页。',
      ar: 'بلا فهرس: الصف الجديد ← صفحة الجدول {page}.',
      es: 'Sin índice: fila nueva → página {page} de la tabla.',
      fr: 'Sans index : nouvelle ligne → page {page} de la table.',
      hi: 'इंडेक्स नहीं: नई पंक्ति → तालिका पन्ना {page}।',
      id: 'Tanpa indeks: baris baru → halaman tabel {page}.',
      pt: 'Sem índice: linha nova → página {page} da tabela.',
    },
    'caption.fan': {
      en: 'With indexes: the row splits into table page {page} and one leaf per index.',
      ko: '인덱스 쪽: 새 줄이 갈라져 표 페이지 {page}, 그리고 인덱스마다 잎 하나로 들어간다.',
      ja: 'インデックス側: 新しい行が分かれ、表のページ {page} と各インデックスの葉一つに入る。',
      zh: '有索引：新行分散写入表的第 {page} 页和每个索引的一片叶。',
      ar: 'مع الفهارس: ينقسم الصف إلى صفحة الجدول {page} وورقة واحدة في كل فهرس.',
      es: 'Con índices: la fila se reparte en la página {page} y una hoja por índice.',
      fr: 'Avec index : la ligne se divise entre la page {page} et une feuille par index.',
      hi: 'इंडेक्स के साथ: पंक्ति बँटकर तालिका पन्ना {page} और हर इंडेक्स के एक पत्ते में जाती है।',
      id: 'Dengan indeks: baris terpecah ke halaman tabel {page} dan satu daun per indeks.',
      pt: 'Com índices: a linha se divide entre a página {page} e uma folha por índice.',
    },
  },
  blocks: {
    stage: { type: 'index-costs-write-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
