import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: Raft 리더가 받은 쓰기는 언제 확정되는가.
 *
 * 다섯 중 셋이 적은 순간 확정된다 — 전부를 기다리지 않는다. 응답이 제각각의 때에 돌아와
 * 사본 수가 하나씩 오르고, 과반 문턱을 넘는 걸음에 손님에게 ok 가 나간다.
 */
export const majorityDecidesFacet: FacetJson = {
  id: 'facet:majorityDecides',
  title: {
    en: 'A majority decides',
    ko: '과반이 정한다',
    ja: '過半数で決まる',
    zh: '多数派决定',
    ar: 'الأغلبية تحسم',
    es: 'Decide la mayoría',
    fr: 'La majorité décide',
    hi: 'बहुमत तय करता है',
    id: 'Mayoritas yang menentukan',
    pt: 'A maioria decide',
  },
  description: {
    en: 'When is a write received by a Raft leader committed?',
    ko: 'Raft 리더가 받은 쓰기는 언제 확정되는가?',
    ja: 'Raft のリーダーが受け取った書き込みはいつ確定するのか?',
    zh: 'Raft 领导者收到的写入何时提交?',
    ar: 'متى يُثبَّت الكتابة التي يستقبلها قائد Raft؟',
    es: '¿Cuándo se confirma una escritura que recibe el líder de Raft?',
    fr: 'Quand une écriture reçue par le leader Raft est-elle validée ?',
    hi: 'Raft लीडर को मिला लेखन कब पक्का होता है?',
    id: 'Kapan tulisan yang diterima pemimpin Raft dikomit?',
    pt: 'Quando uma escrita recebida pelo líder Raft é confirmada?',
  },
  algorithm: 'module:majorityDecides',
  scene: 'module:majorityDecidesScene',
  initialData: {
    type: 'majority-decides',
    stepMs: 1300,
    leader: 'S1',
    term: 4,
    log: [],
    nodes: [
      { id: 'S1' },
      { id: 'S2', roundTripMs: 30 },
      { id: 'S3', roundTripMs: 50 },
      { id: 'S4', roundTripMs: 90 },
      { id: 'S5', stopped: true },
    ],
    write: { atMs: 0, cmd: 'z=9' },
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Leader: {leader}, term {term}. Log: empty. Down from the start: {down}.',
      ko: '리더 {leader}, 임기 {term}. 로그는 비었다. 처음부터 멈춘 노드: {down}.',
      ja: 'リーダー: {leader}、任期 {term}。ログ: 空。最初から停止: {down}。',
      zh: '领导者: {leader},任期 {term}。日志: 空。一开始就停机: {down}。',
      ar: 'القائد: {leader}، الولاية {term}. السجل: فارغ. متوقف منذ البداية: {down}.',
      es: 'Líder: {leader}, mandato {term}. Registro: vacío. Caído desde el inicio: {down}.',
      fr: 'Leader : {leader}, mandat {term}. Journal : vide. En panne dès le départ : {down}.',
      hi: 'लीडर: {leader}, कार्यकाल {term}. लॉग: खाली. शुरू से बंद: {down}.',
      id: 'Pemimpin: {leader}, masa jabatan {term}. Log: kosong. Mati sejak awal: {down}.',
      pt: 'Líder: {leader}, mandato {term}. Log: vazio. Parado desde o início: {down}.',
    },
    'caption.write': {
      en: '{ms} ms: write {cmd} arrives at {leader}, goes into log slot {index}. Copies: {n} / {total}.',
      ko: '{ms} ms: 쓰기 {cmd} 도착 — 리더 {leader}, 로그 {index} 번 칸에 적는다. 사본 {n} / {total}.',
      ja: '{ms} ms: 書き込み {cmd} が {leader} に届き、ログの {index} 番に入る。コピー: {n} / {total}。',
      zh: '{ms} ms: 写入 {cmd} 到达 {leader},写进日志第 {index} 格。副本: {n} / {total}。',
      ar: '{ms} ms: تصل الكتابة {cmd} إلى {leader} وتدخل خانة السجل {index}. النسخ: {n} / {total}.',
      es: '{ms} ms: la escritura {cmd} llega a {leader} y entra en la casilla {index} del registro. Copias: {n} / {total}.',
      fr: '{ms} ms : l’écriture {cmd} arrive sur {leader} et entre dans la case {index} du journal. Copies : {n} / {total}.',
      hi: '{ms} ms: लेखन {cmd} {leader} पर पहुँचता है, लॉग के खाने {index} में जाता है. प्रतियाँ: {n} / {total}.',
      id: '{ms} ms: tulisan {cmd} tiba di {leader}, masuk ke slot log {index}. Salinan: {n} / {total}.',
      pt: '{ms} ms: a escrita {cmd} chega a {leader} e entra na casa {index} do log. Cópias: {n} / {total}.',
    },
    'caption.send': {
      en: '{ms} ms: the leader sends {cmd} to every follower. Never arrives: {lost}.',
      ko: '{ms} ms: 리더가 팔로워 모두에게 {cmd} 전송. 닿지 않는 곳: {lost}.',
      ja: '{ms} ms: リーダーが全フォロワーに {cmd} を送る。届かない先: {lost}。',
      zh: '{ms} ms: 领导者把 {cmd} 发给所有跟随者。送不到: {lost}。',
      ar: '{ms} ms: يرسل القائد {cmd} إلى كل تابع. لا يصل أبدًا: {lost}.',
      es: '{ms} ms: el líder envía {cmd} a todos los seguidores. Nunca llega: {lost}.',
      fr: '{ms} ms : le leader envoie {cmd} à chaque suiveur. N’arrive jamais : {lost}.',
      hi: '{ms} ms: लीडर हर फ़ॉलोअर को {cmd} भेजता है. कभी नहीं पहुँचता: {lost}.',
      id: '{ms} ms: pemimpin mengirim {cmd} ke semua pengikut. Tak pernah sampai: {lost}.',
      pt: '{ms} ms: o líder envia {cmd} a todos os seguidores. Nunca chega: {lost}.',
    },
    'caption.rise': {
      en: '{ms} ms: reply from {node}. Copies: {n} / {total}, below the majority {m}.',
      ko: '{ms} ms: 응답 도착 — {node}. 사본 {n} / {total}, 과반 {m} 아래.',
      ja: '{ms} ms: {node} から応答。コピー: {n} / {total}、過半数 {m} に届かない。',
      zh: '{ms} ms: {node} 回复。副本: {n} / {total},低于多数 {m}。',
      ar: '{ms} ms: رد من {node}. النسخ: {n} / {total}، دون الأغلبية {m}.',
      es: '{ms} ms: respuesta de {node}. Copias: {n} / {total}, por debajo de la mayoría {m}.',
      fr: '{ms} ms : réponse de {node}. Copies : {n} / {total}, sous la majorité {m}.',
      hi: '{ms} ms: {node} से जवाब. प्रतियाँ: {n} / {total}, बहुमत {m} से कम.',
      id: '{ms} ms: balasan dari {node}. Salinan: {n} / {total}, di bawah mayoritas {m}.',
      pt: '{ms} ms: resposta de {node}. Cópias: {n} / {total}, abaixo da maioria {m}.',
    },
    'caption.commit': {
      en: '{ms} ms: reply from {node}. Copies: {n} / {total}, majority {m} reached — committed, ok to the client.',
      ko: '{ms} ms: 응답 도착 — {node}. 사본 {n} / {total}, 과반 {m} 도달 — 확정, 손님에게 ok.',
      ja: '{ms} ms: {node} から応答。コピー: {n} / {total}、過半数 {m} に到達 — 確定、クライアントに ok。',
      zh: '{ms} ms: {node} 回复。副本: {n} / {total},达到多数 {m} — 提交,向客户端返回 ok。',
      ar: '{ms} ms: رد من {node}. النسخ: {n} / {total}، بلغت الأغلبية {m} — ثُبّتت، و ok إلى العميل.',
      es: '{ms} ms: respuesta de {node}. Copias: {n} / {total}, se alcanza la mayoría {m} — confirmada, ok al cliente.',
      fr: '{ms} ms : réponse de {node}. Copies : {n} / {total}, majorité {m} atteinte — validée, ok au client.',
      hi: '{ms} ms: {node} से जवाब. प्रतियाँ: {n} / {total}, बहुमत {m} पूरा — पक्का, क्लाइंट को ok.',
      id: '{ms} ms: balasan dari {node}. Salinan: {n} / {total}, mayoritas {m} tercapai — dikomit, ok ke klien.',
      pt: '{ms} ms: resposta de {node}. Cópias: {n} / {total}, maioria {m} atingida — confirmada, ok ao cliente.',
    },
    'caption.late': {
      en: '{ms} ms: reply from {node}. Copies: {n} / {total}. Commit time: {at} ms.',
      ko: '{ms} ms: 응답 도착 — {node}. 사본 {n} / {total}. 확정 시각 {at} ms.',
      ja: '{ms} ms: {node} から応答。コピー: {n} / {total}。確定時刻 {at} ms。',
      zh: '{ms} ms: {node} 回复。副本: {n} / {total}。提交时刻 {at} ms。',
      ar: '{ms} ms: رد من {node}. النسخ: {n} / {total}. وقت التثبيت: {at} ms.',
      es: '{ms} ms: respuesta de {node}. Copias: {n} / {total}. Hora de confirmación: {at} ms.',
      fr: '{ms} ms : réponse de {node}. Copies : {n} / {total}. Heure de validation : {at} ms.',
      hi: '{ms} ms: {node} से जवाब. प्रतियाँ: {n} / {total}. पक्का होने का समय: {at} ms.',
      id: '{ms} ms: balasan dari {node}. Salinan: {n} / {total}. Waktu komit: {at} ms.',
      pt: '{ms} ms: resposta de {node}. Cópias: {n} / {total}. Hora da confirmação: {at} ms.',
    },
    'caption.settle': {
      en: 'No reply ever: {silent}. Copies: {n} / {total}, committed at {at} ms.',
      ko: '끝까지 응답 없음: {silent}. 사본 {n} / {total}, 확정 {at} ms.',
      ja: '最後まで応答なし: {silent}。コピー: {n} / {total}、確定 {at} ms。',
      zh: '始终没有回复: {silent}。副本: {n} / {total},提交于 {at} ms。',
      ar: 'لا رد أبدًا: {silent}. النسخ: {n} / {total}، التثبيت عند {at} ms.',
      es: 'Nunca respondió: {silent}. Copias: {n} / {total}, confirmada en {at} ms.',
      fr: 'Jamais de réponse : {silent}. Copies : {n} / {total}, validée à {at} ms.',
      hi: 'कभी जवाब नहीं: {silent}. प्रतियाँ: {n} / {total}, पक्का {at} ms पर.',
      id: 'Tak pernah membalas: {silent}. Salinan: {n} / {total}, dikomit pada {at} ms.',
      pt: 'Nunca respondeu: {silent}. Cópias: {n} / {total}, confirmada em {at} ms.',
    },
    'caption.settleOpen': {
      en: 'No reply ever: {silent}. Copies: {n} / {total}, not committed.',
      ko: '끝까지 응답 없음: {silent}. 사본 {n} / {total}, 확정 안 됨.',
      ja: '最後まで応答なし: {silent}。コピー: {n} / {total}、未確定。',
      zh: '始终没有回复: {silent}。副本: {n} / {total},未提交。',
      ar: 'لا رد أبدًا: {silent}. النسخ: {n} / {total}، غير مثبّتة.',
      es: 'Nunca respondió: {silent}. Copias: {n} / {total}, sin confirmar.',
      fr: 'Jamais de réponse : {silent}. Copies : {n} / {total}, non validée.',
      hi: 'कभी जवाब नहीं: {silent}. प्रतियाँ: {n} / {total}, पक्का नहीं.',
      id: 'Tak pernah membalas: {silent}. Salinan: {n} / {total}, belum dikomit.',
      pt: 'Nunca respondeu: {silent}. Cópias: {n} / {total}, não confirmada.',
    },
    'label.client': {
      en: 'client',
      ko: '손님',
      ja: 'クライアント',
      zh: '客户端',
      ar: 'العميل',
      es: 'cliente',
      fr: 'client',
      hi: 'क्लाइंट',
      id: 'klien',
      pt: 'cliente',
    },
    'label.leader': {
      en: 'leader',
      ko: '리더',
      ja: 'リーダー',
      zh: '领导者',
      ar: 'قائد',
      es: 'líder',
      fr: 'leader',
      hi: 'लीडर',
      id: 'pemimpin',
      pt: 'líder',
    },
    'label.follower': {
      en: 'follower',
      ko: '팔로워',
      ja: 'フォロワー',
      zh: '跟随者',
      ar: 'تابع',
      es: 'seguidor',
      fr: 'suiveur',
      hi: 'फ़ॉलोअर',
      id: 'pengikut',
      pt: 'seguidor',
    },
    'label.down': {
      en: 'down',
      ko: '멈춤',
      ja: '停止',
      zh: '停机',
      ar: 'متوقف',
      es: 'caído',
      fr: 'en panne',
      hi: 'बंद',
      id: 'mati',
      pt: 'parado',
    },
    'label.term': {
      en: 'term {term}',
      ko: '임기 {term}',
      ja: '任期 {term}',
      zh: '任期 {term}',
      ar: 'الولاية {term}',
      es: 'mandato {term}',
      fr: 'mandat {term}',
      hi: 'कार्यकाल {term}',
      id: 'masa jabatan {term}',
      pt: 'mandato {term}',
    },
    'label.entry': {
      en: '({term}, {cmd})',
      ko: '({term}, {cmd})',
      ja: '({term}, {cmd})',
      zh: '({term}, {cmd})',
      ar: '({term}, {cmd})',
      es: '({term}, {cmd})',
      fr: '({term}, {cmd})',
      hi: '({term}, {cmd})',
      id: '({term}, {cmd})',
      pt: '({term}, {cmd})',
    },
    'label.committed': {
      en: 'committed · {ms} ms',
      ko: '확정 · {ms} ms',
      ja: '確定 · {ms} ms',
      zh: '已提交 · {ms} ms',
      ar: 'مثبّتة · {ms} ms',
      es: 'confirmada · {ms} ms',
      fr: 'validée · {ms} ms',
      hi: 'पक्का · {ms} ms',
      id: 'dikomit · {ms} ms',
      pt: 'confirmada · {ms} ms',
    },
    'label.ok': {
      en: 'ok',
      ko: 'ok',
      ja: 'ok',
      zh: 'ok',
      ar: 'ok',
      es: 'ok',
      fr: 'ok',
      hi: 'ok',
      id: 'ok',
      pt: 'ok',
    },
    'label.noReply': {
      en: 'no reply',
      ko: '응답 없음',
      ja: '応答なし',
      zh: '无回复',
      ar: 'لا رد',
      es: 'sin respuesta',
      fr: 'sans réponse',
      hi: 'जवाब नहीं',
      id: 'tak membalas',
      pt: 'sem resposta',
    },
    'label.copies': {
      en: 'copies: {n} / {total}',
      ko: '사본 {n} / {total}',
      ja: 'コピー {n} / {total}',
      zh: '副本 {n} / {total}',
      ar: 'النسخ: {n} / {total}',
      es: 'copias: {n} / {total}',
      fr: 'copies : {n} / {total}',
      hi: 'प्रतियाँ: {n} / {total}',
      id: 'salinan: {n} / {total}',
      pt: 'cópias: {n} / {total}',
    },
    'label.majority': {
      en: 'majority: {m}',
      ko: '과반 {m}',
      ja: '過半数 {m}',
      zh: '多数 {m}',
      ar: 'الأغلبية: {m}',
      es: 'mayoría: {m}',
      fr: 'majorité : {m}',
      hi: 'बहुमत: {m}',
      id: 'mayoritas: {m}',
      pt: 'maioria: {m}',
    },
    'label.at': {
      en: '{node} · {ms} ms',
      ko: '{node} · {ms} ms',
      ja: '{node} · {ms} ms',
      zh: '{node} · {ms} ms',
      ar: '{node} · {ms} ms',
      es: '{node} · {ms} ms',
      fr: '{node} · {ms} ms',
      hi: '{node} · {ms} ms',
      id: '{node} · {ms} ms',
      pt: '{node} · {ms} ms',
    },
  },
  blocks: {
    stage: { type: 'majority-decides-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
