import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 그래프 DB 는 "Ana 의 친구들이 일하는 회사" 를 어떻게 찾는가 —
 * 노드가 쥔 이음 가운데 길의 종류에 맞는 것만 따라 건너가고, 닿지 않은 곳은 건드리지 않는다.
 *
 * 노드 이름 · 종류(Person · Company) · 이음 종류(FRIEND · WORKS_AT)는 데이터베이스에 저장된
 * 자료라 번역하지 않는다.
 */
export const traverseRelationshipsFacet: FacetJson = {
  id: 'facet:traverseRelationships',
  title: {
    en: 'Following relationships',
    ko: '관계를 따라 건너가기',
    ja: '関係をたどって渡る',
    zh: '沿着关系前进',
    ar: 'اتّباع العلاقات',
    es: 'Seguir las relaciones',
    fr: 'Suivre les relations',
    hi: 'संबंधों के सहारे आगे बढ़ना',
    id: 'Menelusuri relasi',
    pt: 'Seguir as relações',
  },
  description: {
    en: 'A graph database looks only at the edges a node holds, crosses the ones whose type matches the path, and never touches the rest.',
    ko: '그래프 DB 는 노드가 쥔 이음만 들여다보고 길의 종류에 맞는 것만 건너며, 나머지는 건드리지 않는다.',
    ja: 'グラフDBはノードが持つエッジだけを見て、経路の種類に合うものだけを渡り、残りには触れない。',
    zh: '图数据库只查看节点自己持有的边，只走类型符合路径的边，其余的从不触及。',
    ar: 'تنظر قاعدة بيانات الرسم البياني فقط إلى الحواف التي تملكها العقدة، وتعبر ما يطابق نوعه المسار، ولا تلمس الباقي.',
    es: 'Una base de datos de grafos mira solo las aristas que tiene un nodo, cruza las del tipo del camino y nunca toca el resto.',
    fr: 'Une base de données orientée graphe ne regarde que les arêtes que détient un nœud, traverse celles du type du chemin et ne touche jamais au reste.',
    hi: 'ग्राफ़ डेटाबेस केवल उन किनारों को देखता है जो किसी नोड के पास हैं, पथ के प्रकार से मेल खाने वालों को पार करता है, और बाकी को कभी नहीं छूता।',
    id: 'Basis data graf hanya melihat sisi yang dimiliki sebuah simpul, melewati yang jenisnya cocok dengan jalur, dan tak pernah menyentuh sisanya.',
    pt: 'Um banco de dados de grafos olha só as arestas que um nó possui, atravessa as do tipo do caminho e nunca toca no resto.',
  },
  algorithm: 'module:traverseRelationships',
  scene: 'module:traverseRelationshipsScene',
  initialData: {
    type: 'traverse-relationships',
    stepMs: 1800,
    nodes: [
      { id: 'Ana', kind: 'Person' },
      { id: 'Ben', kind: 'Person' },
      { id: 'Cho', kind: 'Person' },
      { id: 'Dan', kind: 'Person' },
      { id: 'Eva', kind: 'Person' },
      { id: 'Fay', kind: 'Person' },
      { id: 'Acme', kind: 'Company' },
      { id: 'Zeta', kind: 'Company' },
      { id: 'Nova', kind: 'Company' },
    ],
    edges: [
      { from: 'Ana', type: 'FRIEND', to: 'Ben' },
      { from: 'Ana', type: 'FRIEND', to: 'Cho' },
      { from: 'Ana', type: 'WORKS_AT', to: 'Nova' },
      { from: 'Ben', type: 'FRIEND', to: 'Dan' },
      { from: 'Ben', type: 'WORKS_AT', to: 'Acme' },
      { from: 'Cho', type: 'FRIEND', to: 'Eva' },
      { from: 'Cho', type: 'WORKS_AT', to: 'Zeta' },
      { from: 'Dan', type: 'FRIEND', to: 'Fay' },
      { from: 'Dan', type: 'WORKS_AT', to: 'Nova' },
      { from: 'Eva', type: 'WORKS_AT', to: 'Acme' },
      { from: 'Eva', type: 'FRIEND', to: 'Ana' },
      { from: 'Fay', type: 'WORKS_AT', to: 'Zeta' },
    ],
    start: 'Ana',
    path: ['FRIEND', 'WORKS_AT'],
  },
  shuffleOnReset: false,
  messages: {
    'label.hop': {
      en: 'Hop {n}',
      ko: '홉 {n}',
      ja: 'ホップ {n}',
      zh: '第 {n} 跳',
      ar: 'القفزة {n}',
      es: 'Salto {n}',
      fr: 'Saut {n}',
      hi: 'हॉप {n}',
      id: 'Lompatan {n}',
      pt: 'Salto {n}',
    },
    'label.seen': {
      en: 'Edges looked at',
      ko: '본 이음',
      ja: '見たエッジ',
      zh: '查看过的边',
      ar: 'الحواف المفحوصة',
      es: 'Aristas examinadas',
      fr: 'Arêtes examinées',
      hi: 'देखे गए किनारे',
      id: 'Sisi yang dilihat',
      pt: 'Arestas examinadas',
    },
    'label.crossed': {
      en: 'Edges crossed',
      ko: '건넌 이음',
      ja: '渡ったエッジ',
      zh: '走过的边',
      ar: 'الحواف المعبورة',
      es: 'Aristas cruzadas',
      fr: 'Arêtes traversées',
      hi: 'पार किए गए किनारे',
      id: 'Sisi yang dilewati',
      pt: 'Arestas atravessadas',
    },
    'label.reached': {
      en: 'Nodes reached',
      ko: '닿은 노드',
      ja: '到達したノード',
      zh: '到达的节点',
      ar: 'العُقد التي وُصل إليها',
      es: 'Nodos alcanzados',
      fr: 'Nœuds atteints',
      hi: 'पहुँचे गए नोड',
      id: 'Simpul yang dicapai',
      pt: 'Nós alcançados',
    },
    'value.fraction': {
      en: '{n} / {total}',
      ko: '{n} / {total}',
      ja: '{n} / {total}',
      zh: '{n} / {total}',
      ar: '{n} / {total}',
      es: '{n} / {total}',
      fr: '{n} / {total}',
      hi: '{n} / {total}',
      id: '{n} / {total}',
      pt: '{n} / {total}',
    },
    'caption.start': {
      en: 'Start: {node} · path: {path}',
      ko: '출발: {node} · 길: {path}',
      ja: '出発: {node} · 経路: {path}',
      zh: '起点：{node} · 路径：{path}',
      ar: 'البداية: {node} · المسار: {path}',
      es: 'Inicio: {node} · camino: {path}',
      fr: 'Départ : {node} · chemin : {path}',
      hi: 'आरंभ: {node} · पथ: {path}',
      id: 'Mulai: {node} · jalur: {path}',
      pt: 'Início: {node} · caminho: {path}',
    },
    'caption.expand': {
      en: 'Hop {hop} · {node} — edges held: {seen} · {type} crossed: {crossed} → {targets}',
      ko: '홉 {hop} · {node} — 쥔 이음: {seen} · 건넌 {type}: {crossed} → {targets}',
      ja: 'ホップ {hop} · {node} — 持つエッジ: {seen} · 渡った {type}: {crossed} → {targets}',
      zh: '第 {hop} 跳 · {node} — 持有的边：{seen} · 走过的 {type}：{crossed} → {targets}',
      ar: 'القفزة {hop} · {node} — الحواف المملوكة: {seen} · {type} المعبورة: {crossed} → {targets}',
      es: 'Salto {hop} · {node} — aristas propias: {seen} · {type} cruzadas: {crossed} → {targets}',
      fr: 'Saut {hop} · {node} — arêtes détenues : {seen} · {type} traversées : {crossed} → {targets}',
      hi: 'हॉप {hop} · {node} — अपने किनारे: {seen} · पार किए {type}: {crossed} → {targets}',
      id: 'Lompatan {hop} · {node} — sisi milik sendiri: {seen} · {type} dilewati: {crossed} → {targets}',
      pt: 'Salto {hop} · {node} — arestas próprias: {seen} · {type} atravessadas: {crossed} → {targets}',
    },
    'caption.expandNone': {
      en: 'Hop {hop} · {node} — edges held: {seen} · {type} crossed: {crossed}',
      ko: '홉 {hop} · {node} — 쥔 이음: {seen} · 건넌 {type}: {crossed}',
      ja: 'ホップ {hop} · {node} — 持つエッジ: {seen} · 渡った {type}: {crossed}',
      zh: '第 {hop} 跳 · {node} — 持有的边：{seen} · 走过的 {type}：{crossed}',
      ar: 'القفزة {hop} · {node} — الحواف المملوكة: {seen} · {type} المعبورة: {crossed}',
      es: 'Salto {hop} · {node} — aristas propias: {seen} · {type} cruzadas: {crossed}',
      fr: 'Saut {hop} · {node} — arêtes détenues : {seen} · {type} traversées : {crossed}',
      hi: 'हॉप {hop} · {node} — अपने किनारे: {seen} · पार किए {type}: {crossed}',
      id: 'Lompatan {hop} · {node} — sisi milik sendiri: {seen} · {type} dilewati: {crossed}',
      pt: 'Salto {hop} · {node} — arestas próprias: {seen} · {type} atravessadas: {crossed}',
    },
    'caption.answer': {
      en: 'Answer: {answer} · never touched: {untouched}',
      ko: '답: {answer} · 한 번도 닿지 않은 노드: {untouched}',
      ja: '答え: {answer} · 一度も触れていないノード: {untouched}',
      zh: '答案：{answer} · 从未触及的节点：{untouched}',
      ar: 'الإجابة: {answer} · عُقد لم تُلمَس قط: {untouched}',
      es: 'Respuesta: {answer} · nunca tocados: {untouched}',
      fr: 'Réponse : {answer} · jamais touchés : {untouched}',
      hi: 'उत्तर: {answer} · कभी न छुए गए नोड: {untouched}',
      id: 'Jawaban: {answer} · tak pernah disentuh: {untouched}',
      pt: 'Resposta: {answer} · nunca tocados: {untouched}',
    },
  },
  blocks: {
    stage: { type: 'traverse-relationships-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
