import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 서버 넷 가운데 하나가 빠지면, 키 가운데 몇이 다른 서버로 옮겨 가야 하는가 —
 * 해시 링과 나머지 해싱(h mod N)에서.
 */
export const moveFewOnChangeFacet: FacetJson = {
  id: 'facet:moveFewOnChange',
  title: {
    en: 'One server leaves, few keys move',
    ko: '하나가 빠져도 조금만 옮긴다',
    ja: 'サーバーが一台抜けても、動くキーは少ない',
    zh: '少一台服务器，只有少数键搬家',
    ar: 'يغادر خادم واحد فتنتقل مفاتيح قليلة',
    es: 'Sale un servidor y se mueven pocas claves',
    fr: 'Un serveur part, peu de clés bougent',
    hi: 'एक सर्वर हटे तो कुछ ही कुंजियाँ खिसकती हैं',
    id: 'Satu server keluar, hanya sedikit kunci pindah',
    pt: 'Sai um servidor e poucas chaves mudam',
  },
  description: {
    en: 'When one of four servers leaves, how many keys must move to another server — on a hash ring and with h mod N?',
    ko: '서버 넷 가운데 하나가 빠지면, 키 가운데 몇이 다른 서버로 옮겨 가야 하는가 — 해시 링과 h mod N 에서.',
    ja: '4 台のサーバーのうち 1 台が抜けたとき、別のサーバーへ移るキーはいくつか — ハッシュリングと h mod N で。',
    zh: '四台服务器中少了一台时，有多少个键必须搬到别的服务器——在哈希环上和用 h mod N 时各是多少？',
    ar: 'عندما يغادر خادم من أربعة، كم مفتاحًا يجب أن ينتقل إلى خادم آخر — على حلقة التجزئة ومع h mod N؟',
    es: 'Cuando sale uno de cuatro servidores, ¿cuántas claves deben pasar a otro servidor, en un anillo de hash y con h mod N?',
    fr: 'Quand un serveur sur quatre part, combien de clés doivent changer de serveur — sur un anneau de hachage et avec h mod N ?',
    hi: 'चार में से एक सर्वर हटे तो कितनी कुंजियों को दूसरे सर्वर पर जाना पड़ता है — हैश रिंग पर और h mod N के साथ?',
    id: 'Saat satu dari empat server keluar, berapa kunci yang harus pindah ke server lain — pada cincin hash dan dengan h mod N?',
    pt: 'Quando sai um de quatro servidores, quantas chaves precisam ir para outro servidor — num anel de hash e com h mod N?',
  },
  algorithm: 'module:moveFewOnChange',
  scene: 'module:moveFewOnChangeScene',
  initialData: {
    type: 'move-few-on-change',
    stepMs: 900,
    ringSize: 100,
    servers: ['node-a', 'node-b', 'node-c', 'node-d'],
    keys: [
      'doc:153',
      'doc:154',
      'doc:155',
      'doc:156',
      'doc:157',
      'doc:158',
      'doc:159',
      'doc:160',
      'doc:161',
      'doc:162',
      'doc:163',
      'doc:164',
    ],
    removed: 'node-a',
  },
  shuffleOnReset: false,
  messages: {
    'label.ring': {
      en: 'Hash ring',
      ko: '해시 링',
      ja: 'ハッシュリング',
      zh: '哈希环',
      ar: 'حلقة التجزئة',
      es: 'Anillo de hash',
      fr: 'Anneau de hachage',
      hi: 'हैश रिंग',
      id: 'Cincin hash',
      pt: 'Anel de hash',
    },
    'label.mod': {
      en: 'Remainder hashing',
      ko: '나머지 해싱',
      ja: '剰余ハッシュ',
      zh: '取模哈希',
      ar: 'التجزئة بالباقي',
      es: 'Hash por resto',
      fr: 'Hachage par reste',
      hi: 'शेषफल हैशिंग',
      id: 'Hash sisa bagi',
      pt: 'Hash por resto',
    },
    'label.modN': {
      en: 'h mod {n}',
      ko: 'h mod {n}',
      ja: 'h mod {n}',
      zh: 'h mod {n}',
      ar: 'h mod {n}',
      es: 'h mod {n}',
      fr: 'h mod {n}',
      hi: 'h mod {n}',
      id: 'h mod {n}',
      pt: 'h mod {n}',
    },
    'label.pos': {
      en: 'Position: {p}',
      ko: '자리: {p}',
      ja: '位置: {p}',
      zh: '位置：{p}',
      ar: 'الموضع: {p}',
      es: 'Posición: {p}',
      fr: 'Position : {p}',
      hi: 'स्थान: {p}',
      id: 'Posisi: {p}',
      pt: 'Posição: {p}',
    },
    'label.modPair': {
      en: 'h mod {n0} = {a} → h mod {n1} = {b}',
      ko: 'h mod {n0} = {a} → h mod {n1} = {b}',
      ja: 'h mod {n0} = {a} → h mod {n1} = {b}',
      zh: 'h mod {n0} = {a} → h mod {n1} = {b}',
      ar: 'h mod {n0} = {a} → h mod {n1} = {b}',
      es: 'h mod {n0} = {a} → h mod {n1} = {b}',
      fr: 'h mod {n0} = {a} → h mod {n1} = {b}',
      hi: 'h mod {n0} = {a} → h mod {n1} = {b}',
      id: 'h mod {n0} = {a} → h mod {n1} = {b}',
      pt: 'h mod {n0} = {a} → h mod {n1} = {b}',
    },
    'label.moved': {
      en: 'Moved · {from} → {to}',
      ko: '옮김 · {from} → {to}',
      ja: '移動 · {from} → {to}',
      zh: '搬走 · {from} → {to}',
      ar: 'انتقل · {from} → {to}',
      es: 'Movida · {from} → {to}',
      fr: 'Déplacée · {from} → {to}',
      hi: 'खिसकी · {from} → {to}',
      id: 'Pindah · {from} → {to}',
      pt: 'Movida · {from} → {to}',
    },
    'label.stayed': {
      en: 'Stayed · {server}',
      ko: '제자리 · {server}',
      ja: 'そのまま · {server}',
      zh: '原地 · {server}',
      ar: 'بقي · {server}',
      es: 'Se queda · {server}',
      fr: 'Reste · {server}',
      hi: 'वहीं रही · {server}',
      id: 'Tetap · {server}',
      pt: 'Fica · {server}',
    },
    'label.tally': {
      en: 'Moved: {n} / {total}',
      ko: '옮김: {n} / {total}',
      ja: '移動: {n} / {total}',
      zh: '搬走：{n} / {total}',
      ar: 'انتقل: {n} / {total}',
      es: 'Movidas: {n} / {total}',
      fr: 'Déplacées : {n} / {total}',
      hi: 'खिसकीं: {n} / {total}',
      id: 'Pindah: {n} / {total}',
      pt: 'Movidas: {n} / {total}',
    },
    'caption.start': {
      en: 'Servers: {n} · Keys: {k}',
      ko: '서버: {n} · 키: {k}',
      ja: 'サーバー: {n} · キー: {k}',
      zh: '服务器：{n} · 键：{k}',
      ar: 'الخوادم: {n} · المفاتيح: {k}',
      es: 'Servidores: {n} · Claves: {k}',
      fr: 'Serveurs : {n} · Clés : {k}',
      hi: 'सर्वर: {n} · कुंजियाँ: {k}',
      id: 'Server: {n} · Kunci: {k}',
      pt: 'Servidores: {n} · Chaves: {k}',
    },
    'caption.remove': {
      en: 'Removed: {server}',
      ko: '빠짐: {server}',
      ja: '抜けた: {server}',
      zh: '移除：{server}',
      ar: 'أُزيل: {server}',
      es: 'Sale: {server}',
      fr: 'Retiré : {server}',
      hi: 'हटा: {server}',
      id: 'Keluar: {server}',
      pt: 'Sai: {server}',
    },
    'caption.place': {
      en: 'Placing again: {key}',
      ko: '다시 놓기: {key}',
      ja: '置き直し: {key}',
      zh: '重新放置：{key}',
      ar: 'إعادة الوضع: {key}',
      es: 'Colocando de nuevo: {key}',
      fr: 'Nouveau placement : {key}',
      hi: 'फिर से रखना: {key}',
      id: 'Menempatkan ulang: {key}',
      pt: 'Colocando de novo: {key}',
    },
  },
  blocks: {
    stage: { type: 'move-few-on-change-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
