/**
 * @piece 한 길로 흘릴 수 있는 양은 가장 좁은 곳이 정한다.
 *
 * 질문 — "여유가 남은 길을 찾았다. 그러면 얼마를 흘리는가?"
 * 답 — 그 길에서 여유가 가장 적은 관만큼. 흘리고 나면 그 관이 꽉 차서 다음
 * 길은 그리로 지나지 못한다.
 *
 * 화면에 뜨는 수는 모두 알고리즘이 이 구조에서 셈한 것이다 (여유 · 흘린 양 ·
 * 도착 총량). 여기 선언하는 것은 관의 굵기뿐이다.
 */

import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

export const bottleneckSetsFlowFacet: FacetJson = {
  id: 'facet:bottleneckSetsFlow',
  title: {
    en: 'The narrowest pipe sets the amount',
    ko: '가장 좁은 곳이 흘릴 양을 정한다',
    ja: '最も細い管が量を決める',
    zh: '最窄的管子决定流量',
    ar: 'أضيق أنبوب يحدّد الكمية',
    es: 'El tubo más estrecho fija la cantidad',
    fr: 'Le tuyau le plus étroit fixe la quantité',
    hi: 'सबसे सँकरी नली मात्रा तय करती है',
    id: 'Pipa tersempit menentukan jumlahnya',
    pt: 'O tubo mais estreito define a quantidade',
  },
  description: {
    en: 'How much a route can carry is decided by its narrowest pipe.',
    ko: '한 길로 흘릴 수 있는 양은 그 길에서 가장 좁은 관이 정한다.',
    ja: 'ひとつの経路に流せる量は、その経路で最も細い管が決める。',
    zh: '一条路径能通过多少，由它最窄的那根管子决定。',
    ar: 'ما يمكن أن يحمله مسار ما يحدّده أضيق أنبوب فيه.',
    es: 'Lo que puede llevar una ruta lo decide su tubo más estrecho.',
    fr: "Ce qu'un chemin peut transporter est décidé par son tuyau le plus étroit.",
    hi: 'कोई मार्ग कितना ले जा सकता है, यह उसकी सबसे सँकरी नली तय करती है।',
    id: 'Berapa banyak yang bisa dialirkan satu rute ditentukan oleh pipa tersempitnya.',
    pt: 'O quanto uma rota consegue levar é decidido pelo seu tubo mais estreito.',
  },
  algorithm: 'module:bottleneckSetsFlow',
  projector: 'module:bottleneckSetsFlowProjector',
  initialData: {
    type: 'bottleneck-sets-flow',
    nodes: ['S', 'A', 'B', 'T'],
    edges: [
      { id: 'S-A', from: 'S', to: 'A', capacity: 3 },
      { id: 'S-B', from: 'S', to: 'B', capacity: 2 },
      { id: 'A-T', from: 'A', to: 'T', capacity: 2 },
      { id: 'B-T', from: 'B', to: 'T', capacity: 3 },
      { id: 'A-B', from: 'A', to: 'B', capacity: 1 },
    ],
    source: 'S',
    sink: 'T',
    stepMs: 900,
  },
  blocks: {
    stage: { type: 'bottleneck-sets-flow-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'caption.pathFound': {
      en: 'Found a route that still has room: {route}',
      ko: '아직 여유가 남은 길을 찾았다 — {route}',
      ja: 'まだ余裕のある経路が見つかった — {route}',
      zh: '找到一条还有余量的路径：{route}',
      ar: 'وُجد مسار ما زال فيه متّسع: {route}',
      es: 'Se encontró una ruta con espacio libre: {route}',
      fr: 'Un chemin qui a encore de la place : {route}',
      hi: 'ऐसा मार्ग मिला जिसमें अब भी जगह है: {route}',
      id: 'Ditemukan rute yang masih longgar: {route}',
      pt: 'Encontrada uma rota que ainda tem espaço: {route}',
    },
    'caption.narrowest': {
      en: 'The narrowest pipe on this route has room for {amount} — that is all this route can take',
      ko: '이 길에서 가장 좁은 곳의 여유는 {amount} — 이 길로는 그만큼밖에 못 흘린다',
      ja: 'この経路で最も細い管の余裕は {amount} — この経路にはそれだけしか流せない',
      zh: '这条路径上最窄的管子只余 {amount} — 这条路就只能通过这么多',
      ar: 'أضيق أنبوب في هذا المسار يتّسع لـ{amount} — وهذا كل ما يحتمله المسار',
      es: 'El tubo más estrecho de esta ruta tiene espacio para {amount}: eso es todo lo que la ruta admite',
      fr: 'Le tuyau le plus étroit de ce chemin a de la place pour {amount} — le chemin ne peut pas en prendre plus',
      hi: 'इस मार्ग की सबसे सँकरी नली में {amount} की जगह है — मार्ग इससे ज़्यादा नहीं ले सकता',
      id: 'Pipa tersempit di rute ini masih muat {amount} — hanya sebanyak itu yang bisa lewat',
      pt: 'O tubo mais estreito desta rota tem espaço para {amount} — é tudo o que a rota aguenta',
    },
    'caption.pushed': {
      en: 'Sent {amount} through. {total} has arrived so far',
      ko: '{amount} 만큼 흘렸다. 지금까지 도착한 양은 {total}',
      ja: '{amount} を流した。ここまでに届いた量は {total}',
      zh: '流过 {amount}。到目前为止已抵达 {total}',
      ar: 'مرّرنا {amount}. ووصل حتى الآن {total}',
      es: 'Se envió {amount}. Hasta ahora han llegado {total}',
      fr: '{amount} envoyés. {total} sont arrivés jusque-là',
      hi: '{amount} बहाया गया। अब तक {total} पहुँचा है',
      id: 'Mengalirkan {amount}. Sejauh ini yang tiba {total}',
      pt: 'Passaram {amount}. Até agora chegaram {total}',
    },
    'caption.noMoreRoom': {
      en: 'Every pipe leaving the source is full — there is no route left',
      ko: '들어오는 곳에서 나가는 관이 모두 꽉 찼다 — 갈 길이 없다',
      ja: '源から出る管はすべて満杯だ — 通れる経路がない',
      zh: '源头引出的管子全都满了 — 已无路可走',
      ar: 'كل أنبوب يخرج من المنبع ممتلئ — لم يبقَ مسار',
      es: 'Todos los tubos que salen de la fuente están llenos: no queda ninguna ruta',
      fr: 'Tous les tuyaux qui partent de la source sont pleins — il ne reste aucun chemin',
      hi: 'स्रोत से निकलने वाली हर नली भरी है — कोई मार्ग नहीं बचा',
      id: 'Semua pipa yang keluar dari sumber sudah penuh — tak ada rute tersisa',
      pt: 'Todos os tubos que saem da fonte estão cheios — não resta nenhuma rota',
    },
    'caption.done': {
      en: '{total} in total — nothing more can get through',
      ko: '모두 {total} 만큼 흘렸다 — 더는 지나갈 수 없다',
      ja: '合わせて {total} — これ以上は通れない',
      zh: '总共 {total} — 再也过不去了',
      ar: 'المجموع {total} — لا شيء آخر يمكنه المرور',
      es: '{total} en total: no puede pasar nada más',
      fr: '{total} au total — plus rien ne peut passer',
      hi: 'कुल {total} — अब और कुछ नहीं गुज़र सकता',
      id: 'Totalnya {total} — tak ada lagi yang bisa lewat',
      pt: '{total} no total — nada mais consegue passar',
    },
    'label.room': {
      en: 'room {n}',
      ko: '여유 {n}',
      ja: '余裕 {n}',
      zh: '余量 {n}',
      ar: 'متّسع {n}',
      es: 'libre {n}',
      fr: 'libre {n}',
      hi: 'जगह {n}',
      id: 'sisa {n}',
      pt: 'livre {n}',
    },
    'label.full': {
      en: 'full',
      ko: '꽉 참',
      ja: '満杯',
      zh: '已满',
      ar: 'ممتلئ',
      es: 'lleno',
      fr: 'plein',
      hi: 'भरा',
      id: 'penuh',
      pt: 'cheio',
    },
    'label.arrived': {
      en: 'arrived {n}',
      ko: '도착 {n}',
      ja: '到着 {n}',
      zh: '已达 {n}',
      ar: 'وصل {n}',
      es: 'llegado {n}',
      fr: 'arrivé {n}',
      hi: 'पहुँचा {n}',
      id: 'tiba {n}',
      pt: 'chegou {n}',
    },
  },
};
