import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 2단계 잠금에서 다 쓴 잠금을 바로 놓지 못하는 까닭은?
 *
 * 기본 2단계 잠금 (엄격하지 않은 것) — 한 번 놓으면 더는 잡지 않는다. T1 의 일 넷이
 * 잠금을 하나씩 늘려 넷에서 정점을 찍고, 그 뒤로만 잡은 차례대로 하나씩 놓는다.
 */
export const growThenShrinkFacet: FacetJson = {
  id: 'facet:growThenShrink',
  title: {
    en: 'Two-phase locking: grow, then shrink',
    ko: '2단계 잠금 — 늘었다가 줄어든다',
    ja: '二相ロック — 増えてから減る',
    zh: '两阶段锁 — 先增长后收缩',
    ar: 'القفل على مرحلتين: نمو ثم انكماش',
    es: 'Bloqueo en dos fases: crecer y luego encoger',
    fr: 'Verrouillage à deux phases : croître, puis décroître',
    hi: 'दो-चरण लॉकिंग: पहले बढ़ना, फिर घटना',
    id: 'Penguncian dua fase: tumbuh, lalu menyusut',
    pt: 'Bloqueio em duas fases: crescer e depois encolher',
  },
  description: {
    en: 'Under two-phase locking a transaction takes every lock before it releases any, so a lock it is already done with keeps waiting until the last one is taken.',
    ko: '2단계 잠금에서는 잠금을 모두 잡은 뒤에야 놓기 시작한다. 그래서 다 쓴 잠금도 마지막 잠금을 잡을 때까지 쥔 채 기다린다.',
    ja: '二相ロックでは、すべてのロックを取ってから初めて解放を始める。だから使い終えたロックも、最後のロックを取るまで握ったまま待つ。',
    zh: '在两阶段锁中，事务要先取得全部锁才开始释放。所以已经用完的锁，也要一直持有到最后一把锁被取得。',
    ar: 'في القفل على مرحلتين تأخذ المعاملة كل الأقفال قبل أن تحرر أيًّا منها، فيبقى القفل الذي انتهت منه محجوزًا حتى يُؤخذ آخر قفل.',
    es: 'Con el bloqueo en dos fases, una transacción toma todos sus bloqueos antes de liberar alguno, así que un bloqueo que ya no usa sigue retenido hasta tomar el último.',
    fr: 'Avec le verrouillage à deux phases, une transaction prend tous ses verrous avant d’en libérer un seul ; un verrou dont elle n’a plus besoin reste donc tenu jusqu’à la prise du dernier.',
    hi: 'दो-चरण लॉकिंग में लेन-देन कोई भी लॉक छोड़ने से पहले सारे लॉक ले लेता है, इसलिए जिस लॉक का काम हो चुका है वह भी आख़िरी लॉक लिए जाने तक पकड़ा रहता है।',
    id: 'Dengan penguncian dua fase, transaksi mengambil semua kunci sebelum melepas satu pun, sehingga kunci yang sudah selesai dipakai tetap ditahan sampai kunci terakhir diambil.',
    pt: 'No bloqueio em duas fases, a transação toma todos os bloqueios antes de liberar qualquer um, então um bloqueio que já usou continua preso até o último ser tomado.',
  },
  algorithm: 'module:growThenShrink',
  scene: 'module:growThenShrinkScene',
  initialData: {
    type: 'grow-then-shrink',
    txn: 1,
    ops: [
      { op: 'R', row: 'a' },
      { op: 'W', row: 'b' },
      { op: 'R', row: 'c' },
      { op: 'W', row: 'd' },
    ],
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'No lock held yet.',
      ko: '아직 쥔 잠금이 없다.',
      ja: 'まだ握っているロックはない。',
      zh: '还没有持有任何锁。',
      ar: 'لا قفل محجوز بعد.',
      es: 'Todavía no hay bloqueos retenidos.',
      fr: 'Aucun verrou tenu pour l’instant.',
      hi: 'अभी कोई लॉक नहीं पकड़ा है।',
      id: 'Belum ada kunci yang ditahan.',
      pt: 'Nenhum bloqueio retido ainda.',
    },
    'caption.acquire': {
      en: 'Take {lock}, then run {op}.',
      ko: '잠금 잡기: {lock}. 이어서 {op}.',
      ja: 'ロックを取る: {lock}。続けて {op}。',
      zh: '取锁：{lock}。接着执行 {op}。',
      ar: 'خذ القفل: {lock}، ثم نفّذ: {op}.',
      es: 'Tomar {lock} y luego ejecutar {op}.',
      fr: 'Prendre {lock}, puis exécuter {op}.',
      hi: 'लॉक लें: {lock}, फिर चलाएँ: {op}।',
      id: 'Ambil {lock}, lalu jalankan {op}.',
      pt: 'Tomar {lock} e depois executar {op}.',
    },
    'caption.lockPoint': {
      en: 'Take {lock}, then run {op}. Lock point reached.',
      ko: '잠금 잡기: {lock}. 이어서 {op}. 여기가 잠금 지점.',
      ja: 'ロックを取る: {lock}。続けて {op}。ここがロックポイント。',
      zh: '取锁：{lock}。接着执行 {op}。到达锁点。',
      ar: 'خذ القفل: {lock}، ثم نفّذ: {op}. بلغنا نقطة القفل.',
      es: 'Tomar {lock} y luego ejecutar {op}. Punto de bloqueo alcanzado.',
      fr: 'Prendre {lock}, puis exécuter {op}. Point de verrouillage atteint.',
      hi: 'लॉक लें: {lock}, फिर चलाएँ: {op}। लॉक बिंदु आ गया।',
      id: 'Ambil {lock}, lalu jalankan {op}. Titik kunci tercapai.',
      pt: 'Tomar {lock} e depois executar {op}. Ponto de bloqueio alcançado.',
    },
    'caption.release': {
      en: 'Release: {lock}. Steps held after its use: {n}.',
      ko: '놓기: {lock}. 다 쓰고도 쥐고 있던 걸음: {n}.',
      ja: '解放: {lock}。使い終えてから握っていたステップ: {n}。',
      zh: '释放：{lock}。用完后仍持有的步数：{n}。',
      ar: 'تحرير: {lock}. خطوات بقي فيها محجوزًا بعد استعماله: {n}.',
      es: 'Liberar: {lock}. Pasos retenido tras usarlo: {n}.',
      fr: 'Libérer : {lock}. Étapes tenu après usage : {n}.',
      hi: 'छोड़ें: {lock}। काम के बाद पकड़े रहने के चरण: {n}।',
      id: 'Lepas: {lock}. Langkah ditahan setelah dipakai: {n}.',
      pt: 'Liberar: {lock}. Passos retido após o uso: {n}.',
    },
    'caption.releaseCommit': {
      en: 'Release: {lock}. Steps held after its use: {n}. Then commit: {commit}.',
      ko: '놓기: {lock}. 다 쓰고도 쥐고 있던 걸음: {n}. 이어서 커밋: {commit}.',
      ja: '解放: {lock}。使い終えてから握っていたステップ: {n}。続けてコミット: {commit}。',
      zh: '释放：{lock}。用完后仍持有的步数：{n}。接着提交：{commit}。',
      ar: 'تحرير: {lock}. خطوات بقي فيها محجوزًا بعد استعماله: {n}. ثم الالتزام: {commit}.',
      es: 'Liberar: {lock}. Pasos retenido tras usarlo: {n}. Luego confirmar: {commit}.',
      fr: 'Libérer : {lock}. Étapes tenu après usage : {n}. Puis valider : {commit}.',
      hi: 'छोड़ें: {lock}। काम के बाद पकड़े रहने के चरण: {n}। फिर कमिट: {commit}।',
      id: 'Lepas: {lock}. Langkah ditahan setelah dipakai: {n}. Lalu commit: {commit}.',
      pt: 'Liberar: {lock}. Passos retido após o uso: {n}. Depois confirmar: {commit}.',
    },
    'label.held': {
      en: 'Held: {n}',
      ko: '쥔 잠금: {n}',
      ja: '握っているロック: {n}',
      zh: '持有的锁：{n}',
      ar: 'الأقفال المحجوزة: {n}',
      es: 'Retenidos: {n}',
      fr: 'Tenus : {n}',
      hi: 'पकड़े लॉक: {n}',
      id: 'Ditahan: {n}',
      pt: 'Retidos: {n}',
    },
    'label.idle': {
      en: 'Idle steps',
      ko: '다 쓰고 쥔 걸음',
      ja: '使用後に握ったステップ',
      zh: '用完后持有的步数',
      ar: 'خطوات الانتظار',
      es: 'Pasos ocioso',
      fr: 'Étapes inactif',
      hi: 'निष्क्रिय चरण',
      id: 'Langkah menganggur',
      pt: 'Passos ocioso',
    },
    'label.growing': {
      en: 'Growing',
      ko: '늘어나는 단계',
      ja: '拡大フェーズ',
      zh: '增长阶段',
      ar: 'مرحلة النمو',
      es: 'Fase de crecimiento',
      fr: 'Phase de croissance',
      hi: 'बढ़ने का चरण',
      id: 'Fase tumbuh',
      pt: 'Fase de crescimento',
    },
    'label.shrinking': {
      en: 'Shrinking',
      ko: '줄어드는 단계',
      ja: '縮小フェーズ',
      zh: '收缩阶段',
      ar: 'مرحلة الانكماش',
      es: 'Fase de reducción',
      fr: 'Phase de décroissance',
      hi: 'घटने का चरण',
      id: 'Fase menyusut',
      pt: 'Fase de encolhimento',
    },
    'label.lockPoint': {
      en: 'Lock point',
      ko: '잠금 지점',
      ja: 'ロックポイント',
      zh: '锁点',
      ar: 'نقطة القفل',
      es: 'Punto de bloqueo',
      fr: 'Point de verrouillage',
      hi: 'लॉक बिंदु',
      id: 'Titik kunci',
      pt: 'Ponto de bloqueio',
    },
  },
  blocks: {
    stage: { type: 'grow-then-shrink-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
