/**
 * top-k / top-p 완제품 — 꼬리를 "몇 개" 로 자르는 것과 "얼마만큼" 으로 자르는 것은 분포의 모양이
 * 다를 때 어떻게 갈리는가.
 *
 * 두 문맥의 확률은 천분율 정수로 **예로 정한 값**이다. 소재 글(프롬프트 · 후보 낱말)은 번역하지 않는다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const topKTopPFacet: FacetJson = {
  id: 'facet:topKTopP',
  title: {
    en: 'Top-k vs top-p: count or share',
    ko: 'top-k · top-p — 개수로 자르기와 몫으로 자르기',
    ja: 'top-k と top-p — 個数で切るか割合で切るか',
    zh: 'top-k 与 top-p — 按个数切还是按份额切',
    ar: 'top-k و top-p — القطع بالعدد أم بالحصة',
    es: 'top-k y top-p: cortar por número o por parte',
    fr: 'top-k et top-p : couper au nombre ou à la part',
    hi: 'top-k और top-p — गिनती से काटें या हिस्से से',
    id: 'top-k dan top-p — memotong menurut jumlah atau bagian',
    pt: 'top-k e top-p — cortar por número ou por parte',
  },
  description: {
    en: 'Two contexts, one peaked and one flat, share the same knobs. k keeps the same number in both; p keeps the same share. Set both and p measures what k left, rescaled.',
    ko: '뾰족한 문맥과 평평한 문맥에 같은 손잡이를 건다. k 는 두 쪽에 같은 수를, p 는 같은 몫을 남긴다. 둘을 함께 걸면 p 는 k 가 남긴 것을 다시 나누어 잰다.',
    ja: '尖った文脈と平らな文脈に同じつまみを掛ける。k は両方に同じ数を、p は同じ割合を残す。両方掛けると、p は k が残したものを再配分して測る。',
    zh: '尖锐和平坦两个语境共用同一组旋钮。k 在两边留下相同的个数,p 留下相同的份额。两者同时设定时,p 在 k 留下的部分重新归一后再衡量。',
    ar: 'سياقان، أحدهما حاد والآخر مسطّح، يتشاركان المقابض نفسها. يُبقي k العدد نفسه في كليهما، ويُبقي p الحصة نفسها. عند ضبط الاثنين يقيس p ما تركه k بعد إعادة توزيعه.',
    es: 'Dos contextos, uno puntiagudo y otro plano, comparten los mismos mandos. k deja el mismo número en ambos; p deja la misma parte. Con los dos, p mide lo que dejó k, reescalado.',
    fr: 'Deux contextes, l’un pointu, l’autre plat, partagent les mêmes réglages. k garde le même nombre dans les deux ; p garde la même part. Avec les deux, p mesure ce que k a laissé, renormalisé.',
    hi: 'दो संदर्भ — एक नुकीला, एक सपाट — एक ही घुंडियाँ साझा करते हैं। k दोनों में उतनी ही गिनती रखता है; p उतना ही हिस्सा। दोनों लगाने पर p, k के छोड़े हिस्से को दोबारा बाँटकर मापता है।',
    id: 'Dua konteks, satu runcing dan satu datar, memakai kenop yang sama. k menyisakan jumlah yang sama di keduanya; p menyisakan bagian yang sama. Jika keduanya dipasang, p mengukur sisa dari k yang dibagi ulang.',
    pt: 'Dois contextos, um pontiagudo e outro plano, partilham os mesmos botões. k mantém o mesmo número nos dois; p mantém a mesma parte. Com os dois, p mede o que k deixou, reescalado.',
  },
  algorithm: 'module:topKTopP',
  projector: 'module:topKTopPProjector',
  initialData: {
    type: 'top-k-top-p',
    stepMs: 900,
    contexts: [
      {
        id: 'peaked',
        prompt: 'The opposite of hot is',
        tokens: ['cold', 'warm', 'not', 'cool', 'the', 'very', 'freezing', 'purple'],
        permille: [880, 40, 30, 20, 12, 10, 5, 3],
      },
      {
        id: 'flat',
        prompt: 'For breakfast I had',
        tokens: ['toast', 'eggs', 'cereal', 'fruit', 'pancakes', 'porridge', 'coffee', 'homework'],
        permille: [230, 190, 170, 140, 110, 90, 50, 20],
      },
    ],
    topKLadder: [1, 2, 3, 5, 8],
    topPLadder: [50, 75, 90, 100],
    topK: 8,
    topP: 100,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'top-k-top-p-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'topK',
          name: 'topK',
          label: {
            en: 'top-k',
            ko: 'top-k',
            ja: 'top-k',
            zh: 'top-k',
            ar: 'top-k',
            es: 'top-k',
            fr: 'top-k',
            hi: 'top-k',
            id: 'top-k',
            pt: 'top-k',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3' },
            { value: 5, label: '5' },
            { value: 8, label: '8', default: true },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'topP',
          name: 'topP',
          label: {
            en: 'top-p',
            ko: 'top-p',
            ja: 'top-p',
            zh: 'top-p',
            ar: 'top-p',
            es: 'top-p',
            fr: 'top-p',
            hi: 'top-p',
            id: 'top-p',
            pt: 'top-p',
          },
          segments: [
            { value: 50, label: '0.5' },
            { value: 75, label: '0.75' },
            { value: 90, label: '0.9' },
            { value: 100, label: '1', default: true },
          ],
        },
      ],
      metrics: [
        {
          name: 'peaked-kept-count',
          label: {
            en: 'Peaked · kept',
            ko: '뾰족 · 남김',
            ja: '尖った · 残り',
            zh: '尖锐 · 保留',
            ar: 'الحاد · المتبقي',
            es: 'Puntiagudo · quedan',
            fr: 'Pointu · restants',
            hi: 'नुकीला · बचे',
            id: 'Runcing · tersisa',
            pt: 'Pontiagudo · restam',
          },
          initial: 0,
        },
        {
          name: 'flat-kept-count',
          label: {
            en: 'Flat · kept',
            ko: '평평 · 남김',
            ja: '平ら · 残り',
            zh: '平坦 · 保留',
            ar: 'المسطّح · المتبقي',
            es: 'Plano · quedan',
            fr: 'Plat · restants',
            hi: 'सपाट · बचे',
            id: 'Datar · tersisa',
            pt: 'Plano · restam',
          },
          initial: 0,
        },
        {
          name: 'peaked-cut-percent',
          label: {
            en: 'Peaked · cut %',
            ko: '뾰족 · 잘린 %',
            ja: '尖った · 切られた %',
            zh: '尖锐 · 切掉 %',
            ar: 'الحاد · المقطوع %',
            es: 'Puntiagudo · cortado %',
            fr: 'Pointu · coupé %',
            hi: 'नुकीला · कटा %',
            id: 'Runcing · terpotong %',
            pt: 'Pontiagudo · cortado %',
          },
          initial: 0,
        },
        {
          name: 'flat-cut-percent',
          label: {
            en: 'Flat · cut %',
            ko: '평평 · 잘린 %',
            ja: '平ら · 切られた %',
            zh: '平坦 · 切掉 %',
            ar: 'المسطّح · المقطوع %',
            es: 'Plano · cortado %',
            fr: 'Plat · coupé %',
            hi: 'सपाट · कटा %',
            id: 'Datar · terpotong %',
            pt: 'Plano · cortado %',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:top-k-top-p-imperative',
      label: {
        en: 'Where the cut falls',
        ko: '칼날이 떨어지는 자리',
        ja: '刃が落ちる位置',
        zh: '刀落下的位置',
        ar: 'موضع القطع',
        es: 'Dónde cae el corte',
        fr: 'Où tombe la coupe',
        hi: 'कट कहाँ पड़ता है',
        id: 'Di mana potongan jatuh',
        pt: 'Onde cai o corte',
      },
    },
  },
  messages: {
    'label.peaked': {
      en: 'Peaked context',
      ko: '뾰족한 문맥',
      ja: '尖った文脈',
      zh: '尖锐的语境',
      ar: 'سياق حاد',
      es: 'Contexto puntiagudo',
      fr: 'Contexte pointu',
      hi: 'नुकीला संदर्भ',
      id: 'Konteks runcing',
      pt: 'Contexto pontiagudo',
    },
    'label.flat': {
      en: 'Flat context',
      ko: '평평한 문맥',
      ja: '平らな文脈',
      zh: '平坦的语境',
      ar: 'سياق مسطّح',
      es: 'Contexto plano',
      fr: 'Contexte plat',
      hi: 'सपाट संदर्भ',
      id: 'Konteks datar',
      pt: 'Contexto plano',
    },
    'label.cutShare': {
      en: 'Cut share',
      ko: '잘린 몫',
      ja: '切られた割合',
      zh: '被切掉的份额',
      ar: 'الحصة المقطوعة',
      es: 'Parte cortada',
      fr: 'Part coupée',
      hi: 'कटा हिस्सा',
      id: 'Bagian terpotong',
      pt: 'Parte cortada',
    },
    'label.share': {
      en: '{v}%',
      ko: '{v}%',
      ja: '{v}%',
      zh: '{v}%',
      ar: '{v}%',
      es: '{v}%',
      fr: '{v}%',
      hi: '{v}%',
      id: '{v}%',
      pt: '{v}%',
    },
    'label.kTag': {
      en: 'k {k}',
      ko: 'k {k}',
      ja: 'k {k}',
      zh: 'k {k}',
      ar: 'k {k}',
      es: 'k {k}',
      fr: 'k {k}',
      hi: 'k {k}',
      id: 'k {k}',
      pt: 'k {k}',
    },
    'label.pTag': {
      en: 'p {p}',
      ko: 'p {p}',
      ja: 'p {p}',
      zh: 'p {p}',
      ar: 'p {p}',
      es: 'p {p}',
      fr: 'p {p}',
      hi: 'p {p}',
      id: 'p {p}',
      pt: 'p {p}',
    },
    'label.cutBy.k': {
      en: 'Cut by: k',
      ko: '자른 쪽: k',
      ja: '切った側: k',
      zh: '切断者: k',
      ar: 'القاطع: k',
      es: 'Cortó: k',
      fr: 'Coupé par : k',
      hi: 'काटा: k',
      id: 'Dipotong oleh: k',
      pt: 'Cortou: k',
    },
    'label.cutBy.p': {
      en: 'Cut by: p',
      ko: '자른 쪽: p',
      ja: '切った側: p',
      zh: '切断者: p',
      ar: 'القاطع: p',
      es: 'Cortó: p',
      fr: 'Coupé par : p',
      hi: 'काटा: p',
      id: 'Dipotong oleh: p',
      pt: 'Cortou: p',
    },
    'label.cutBy.renormP': {
      en: 'Cut by: p on the rescaled rest',
      ko: '자른 쪽: 다시 나눈 p',
      ja: '切った側: 再配分した p',
      zh: '切断者: 重新归一后的 p',
      ar: 'القاطع: p على الباقي بعد إعادة التوزيع',
      es: 'Cortó: p sobre el resto reescalado',
      fr: 'Coupé par : p sur le reste renormalisé',
      hi: 'काटा: बचे हिस्से पर दोबारा बाँटा p',
      id: 'Dipotong oleh: p pada sisa yang dibagi ulang',
      pt: 'Cortou: p sobre o resto reescalado',
    },
    'label.cutBy.none': {
      en: 'Nothing cut',
      ko: '잘린 것 없음',
      ja: '何も切られない',
      zh: '没有被切掉',
      ar: 'لا شيء مقطوع',
      es: 'Nada cortado',
      fr: 'Rien de coupé',
      hi: 'कुछ नहीं कटा',
      id: 'Tidak ada yang terpotong',
      pt: 'Nada cortado',
    },
    'label.readShare': {
      en: 'The % beside a word is its share of what is still in.',
      ko: '낱말 옆의 % 는 아직 남은 것 안에서의 몫이다.',
      ja: '単語の横の % は、まだ残っているものの中での割合。',
      zh: '词旁的 % 是它在仍留下的部分中的份额。',
      ar: 'النسبة % بجانب الكلمة هي حصتها مما بقي.',
      es: 'El % junto a una palabra es su parte de lo que sigue dentro.',
      fr: 'Le % à côté d’un mot est sa part de ce qui reste.',
      hi: 'शब्द के पास का % बचे हुए में उसका हिस्सा है।',
      id: '% di samping kata adalah bagiannya dari yang masih tersisa.',
      pt: 'O % ao lado de uma palavra é a sua parte do que ainda resta.',
    },
    'caption.round': {
      en: 'Set — top-k: {k} · top-p: {p}. Both contexts start from the full distribution.',
      ko: '걸린 값 — top-k: {k} · top-p: {p}. 두 문맥 모두 온전한 분포에서 시작한다.',
      ja: '設定 — top-k: {k} · top-p: {p}。どちらの文脈も元の分布全体から始まる。',
      zh: '设定 — top-k: {k} · top-p: {p}。两个语境都从完整的分布开始。',
      ar: 'الضبط — top-k: {k} · top-p: {p}. يبدأ السياقان من التوزيع الكامل.',
      es: 'Ajuste — top-k: {k} · top-p: {p}. Ambos contextos parten de la distribución completa.',
      fr: 'Réglage — top-k : {k} · top-p : {p}. Les deux contextes partent de la distribution complète.',
      hi: 'सेटिंग — top-k: {k} · top-p: {p}. दोनों संदर्भ पूरे वितरण से शुरू होते हैं।',
      id: 'Setelan — top-k: {k} · top-p: {p}. Kedua konteks mulai dari distribusi utuh.',
      pt: 'Ajuste — top-k: {k} · top-p: {p}. Os dois contextos partem da distribuição completa.',
    },
    'caption.kNone': {
      en: 'top-k {k} cuts nothing — every candidate stays. Kept: {n}.',
      ko: 'top-k {k} — 아무것도 자르지 않는다. 남긴 수: {n}.',
      ja: 'top-k {k} は何も切らない。残した数: {n}。',
      zh: 'top-k {k} 什么也不切。保留数: {n}。',
      ar: 'top-k {k} لا يقطع شيئًا — يبقى كل المرشحين. المتبقي: {n}.',
      es: 'top-k {k} no corta nada: todos los candidatos se quedan. Quedan: {n}.',
      fr: 'top-k {k} ne coupe rien : tous les candidats restent. Restants : {n}.',
      hi: 'top-k {k} कुछ नहीं काटता — सभी उम्मीदवार बचे रहते हैं। बचे: {n}.',
      id: 'top-k {k} tidak memotong apa pun — semua kandidat tetap. Tersisa: {n}.',
      pt: 'top-k {k} não corta nada — todos os candidatos ficam. Restam: {n}.',
    },
    'caption.kCut': {
      en: 'top-k keeps the same number in both contexts — kept: {n}. The rest falls and the survivors swell to fill the column.',
      ko: 'top-k 는 두 문맥에서 같은 수를 남긴다 — 남긴 수: {n}. 나머지는 떨어지고 남은 것이 부풀어 기둥을 채운다.',
      ja: 'top-k は二つの文脈で同じ数を残す — 残した数: {n}。残りは落ち、生き残った候補が膨らんで柱を満たす。',
      zh: 'top-k 在两个语境中保留相同的数量 — 保留数: {n}。其余的掉落,留下的膨胀填满柱子。',
      ar: 'top-k يُبقي العدد نفسه في السياقين — المتبقي: {n}. يسقط الباقي وتنتفخ الناجيات لتملأ العمود.',
      es: 'top-k deja el mismo número en ambos contextos — quedan: {n}. El resto cae y los supervivientes se hinchan hasta llenar la columna.',
      fr: 'top-k garde le même nombre dans les deux contextes — restants : {n}. Le reste tombe et les survivants gonflent pour remplir la colonne.',
      hi: 'top-k दोनों संदर्भों में उतने ही रखता है — बचे: {n}. बाकी गिर जाते हैं और बचे हुए फूलकर स्तंभ भर देते हैं।',
      id: 'top-k menyisakan jumlah yang sama di kedua konteks — tersisa: {n}. Sisanya jatuh dan yang bertahan mengembang mengisi kolom.',
      pt: 'top-k mantém o mesmo número nos dois contextos — restam: {n}. O resto cai e os sobreviventes incham até encher a coluna.',
    },
    'caption.check': {
      en: 'Rank {rank} — add its share to the running total and compare it with the p line.',
      ko: '순위 {rank} — 그 몫을 누적에 더해 p 선과 견준다.',
      ja: '順位 {rank} — その割合を累積に足し、p の線と比べる。',
      zh: '第 {rank} 名 — 把它的份额加入累计,与 p 线比较。',
      ar: 'المرتبة {rank} — أضف حصتها إلى المجموع التراكمي وقارنه بخط p.',
      es: 'Puesto {rank} — suma su parte al acumulado y compáralo con la línea p.',
      fr: 'Rang {rank} — ajouter sa part au cumul et le comparer à la ligne p.',
      hi: 'क्रम {rank} — उसका हिस्सा संचयी योग में जोड़ो और p रेखा से तुलना करो।',
      id: 'Peringkat {rank} — tambahkan bagiannya ke jumlah berjalan dan bandingkan dengan garis p.',
      pt: 'Posição {rank} — somar a sua parte ao acumulado e compará-lo com a linha p.',
    },
    'caption.settle': {
      en: 'Kept — peaked: {a} · flat: {b}. What is left is rescaled to fill the column.',
      ko: '남은 수 — 뾰족: {a} · 평평: {b}. 남은 것을 다시 나누어 기둥을 채운다.',
      ja: '残った数 — 尖った: {a} · 平ら: {b}。残ったものを再配分して柱を満たす。',
      zh: '保留数 — 尖锐: {a} · 平坦: {b}。把留下的重新归一,填满柱子。',
      ar: 'المتبقي — الحاد: {a} · المسطّح: {b}. يُعاد توزيع ما بقي ليملأ العمود.',
      es: 'Quedan — puntiagudo: {a} · plano: {b}. Lo que queda se reescala hasta llenar la columna.',
      fr: 'Restants — pointu : {a} · plat : {b}. Ce qui reste est renormalisé pour remplir la colonne.',
      hi: 'बचे — नुकीला: {a} · सपाट: {b}. जो बचा है उसे फिर से बाँटकर स्तंभ भरा जाता है।',
      id: 'Tersisa — runcing: {a} · datar: {b}. Yang tersisa dibagi ulang hingga mengisi kolom.',
      pt: 'Restam — pontiagudo: {a} · plano: {b}. O que resta é reescalado até encher a coluna.',
    },
    'caption.measure': {
      en: 'Cut share — peaked: {a}% · flat: {b}%.',
      ko: '잘린 몫 — 뾰족: {a}% · 평평: {b}%.',
      ja: '切られた割合 — 尖った: {a}% · 平ら: {b}%。',
      zh: '被切掉的份额 — 尖锐: {a}% · 平坦: {b}%。',
      ar: 'الحصة المقطوعة — الحاد: {a}% · المسطّح: {b}%.',
      es: 'Parte cortada — puntiagudo: {a} % · plano: {b} %.',
      fr: 'Part coupée — pointu : {a} % · plat : {b} %.',
      hi: 'कटा हिस्सा — नुकीला: {a}% · सपाट: {b}%.',
      id: 'Bagian terpotong — runcing: {a}% · datar: {b}%.',
      pt: 'Parte cortada — pontiagudo: {a}% · plano: {b}%.',
    },
  },
};
