import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * HMAC 은 열쇠와 메시지를 어떻게 한데 접는가 — 열쇠는 왜 서로 다른 무늬와 겹쳐 두 번 들어가고,
 * 해시는 왜 두 번인가.
 */
export const hashTwiceWithPadsFacet: FacetJson = {
  id: 'facet:hashTwiceWithPads',
  title: {
    en: 'HMAC folds twice, inside and out',
    ko: 'HMAC 은 안팎으로 두 번 접는다',
    ja: 'HMAC は内と外で二度たたむ',
    zh: 'HMAC 内外折叠两次',
    ar: 'HMAC يطوي مرتين، من الداخل ثم من الخارج',
    es: 'HMAC pliega dos veces, dentro y fuera',
    fr: 'HMAC replie deux fois, dedans puis dehors',
    hi: 'HMAC भीतर और बाहर, दो बार मोड़ता है',
    id: 'HMAC melipat dua kali, di dalam dan di luar',
    pt: 'HMAC dobra duas vezes, por dentro e por fora',
  },
  description: {
    en: 'The key meets ipad and is folded with the message; that inner value then takes the message slot behind the key masked by opad and is folded again.',
    ko: '열쇠가 ipad 와 겹쳐 메시지와 한 번 접히고, 그 안쪽 값이 opad 와 겹친 열쇠 뒤 메시지 자리로 옮겨 가 한 번 더 접힌다.',
    ja: '鍵は ipad と重なってメッセージと一度たたまれ、その内側の値が opad と重なった鍵の後ろ、メッセージの位置へ移ってもう一度たたまれる。',
    zh: '密钥与 ipad 叠合后同消息折叠一次；这个内层值再移到与 opad 叠合的密钥后面、消息的位置上，再折叠一次。',
    ar: 'يلتقي المفتاح بـ ipad ويُطوى مع الرسالة؛ ثم تنتقل القيمة الداخلية إلى خانة الرسالة خلف المفتاح الممزوج بـ opad وتُطوى مرة أخرى.',
    es: 'La clave se cruza con ipad y se pliega con el mensaje; ese valor interior pasa luego al hueco del mensaje, tras la clave cruzada con opad, y se pliega otra vez.',
    fr: 'La clé croise ipad et se replie avec le message ; cette valeur intérieure prend ensuite la place du message derrière la clé croisée avec opad, et se replie encore.',
    hi: 'कुंजी ipad से मिलकर संदेश के साथ एक बार मुड़ती है; फिर वह भीतरी मान opad से मिली कुंजी के पीछे संदेश की जगह जाकर दोबारा मुड़ता है।',
    id: 'Kunci bertemu ipad lalu dilipat bersama pesan; nilai dalam itu kemudian pindah ke slot pesan di belakang kunci yang bertemu opad, lalu dilipat lagi.',
    pt: 'A chave cruza com ipad e é dobrada com a mensagem; esse valor interno passa então para o lugar da mensagem, atrás da chave cruzada com opad, e é dobrado de novo.',
  },
  algorithm: 'module:hashTwiceWithPads',
  scene: 'module:hashTwiceWithPadsScene',
  initialData: {
    type: 'hash-twice-with-pads',
    key: 0xa53f,
    ipad: 0x3636,
    opad: 0x5c5c,
    message: 'HI',
    stepMs: 1600,
  },
  shuffleOnReset: false,
  messages: {
    'label.key': {
      en: 'K', ko: 'K', ja: 'K', zh: 'K', ar: 'K', es: 'K', fr: 'K', hi: 'K', id: 'K', pt: 'K',
    },
    'label.xorKey': {
      en: '⊕K', ko: '⊕K', ja: '⊕K', zh: '⊕K', ar: '⊕K', es: '⊕K', fr: '⊕K', hi: '⊕K', id: '⊕K', pt: '⊕K',
    },
    'label.hash': {
      en: 'H', ko: 'H', ja: 'H', zh: 'H', ar: 'H', es: 'H', fr: 'H', hi: 'H', id: 'H', pt: 'H',
    },
    'label.ipad': {
      en: 'ipad', ko: 'ipad', ja: 'ipad', zh: 'ipad', ar: 'ipad', es: 'ipad', fr: 'ipad', hi: 'ipad', id: 'ipad', pt: 'ipad',
    },
    'label.opad': {
      en: 'opad', ko: 'opad', ja: 'opad', zh: 'opad', ar: 'opad', es: 'opad', fr: 'opad', hi: 'opad', id: 'opad', pt: 'opad',
    },
    'label.innerKey': {
      en: 'inner key',
      ko: '안쪽 열쇠',
      ja: '内側の鍵',
      zh: '内层密钥',
      ar: 'المفتاح الداخلي',
      es: 'clave interior',
      fr: 'clé intérieure',
      hi: 'भीतरी कुंजी',
      id: 'kunci dalam',
      pt: 'chave interna',
    },
    'label.outerKey': {
      en: 'outer key',
      ko: '바깥 열쇠',
      ja: '外側の鍵',
      zh: '外层密钥',
      ar: 'المفتاح الخارجي',
      es: 'clave exterior',
      fr: 'clé extérieure',
      hi: 'बाहरी कुंजी',
      id: 'kunci luar',
      pt: 'chave externa',
    },
    'label.message': {
      en: 'message {m}',
      ko: '메시지 {m}',
      ja: 'メッセージ {m}',
      zh: '消息 {m}',
      ar: 'الرسالة {m}',
      es: 'mensaje {m}',
      fr: 'message {m}',
      hi: 'संदेश {m}',
      id: 'pesan {m}',
      pt: 'mensagem {m}',
    },
    'label.messageSlot': {
      en: 'message slot',
      ko: '메시지 자리',
      ja: 'メッセージの位置',
      zh: '消息的位置',
      ar: 'خانة الرسالة',
      es: 'hueco del mensaje',
      fr: 'place du message',
      hi: 'संदेश की जगह',
      id: 'slot pesan',
      pt: 'lugar da mensagem',
    },
    'label.innerValue': {
      en: 'inner value',
      ko: '안쪽 값',
      ja: '内側の値',
      zh: '内层值',
      ar: 'القيمة الداخلية',
      es: 'valor interior',
      fr: 'valeur intérieure',
      hi: 'भीतरी मान',
      id: 'nilai dalam',
      pt: 'valor interno',
    },
    'label.hmac': {
      en: 'HMAC', ko: 'HMAC', ja: 'HMAC', zh: 'HMAC', ar: 'HMAC', es: 'HMAC', fr: 'HMAC', hi: 'HMAC', id: 'HMAC', pt: 'HMAC',
    },
    'caption.start': {
      en: 'Key K = {k} · message {m}',
      ko: '열쇠 K = {k} · 메시지 {m}',
      ja: '鍵 K = {k} · メッセージ {m}',
      zh: '密钥 K = {k} · 消息 {m}',
      ar: 'المفتاح K = {k} · الرسالة {m}',
      es: 'Clave K = {k} · mensaje {m}',
      fr: 'Clé K = {k} · message {m}',
      hi: 'कुंजी K = {k} · संदेश {m}',
      id: 'Kunci K = {k} · pesan {m}',
      pt: 'Chave K = {k} · mensagem {m}',
    },
    'caption.xorInner': {
      en: 'Inner key: K ⊕ ipad = {k} ⊕ {p} = {r}',
      ko: '안쪽 열쇠: K ⊕ ipad = {k} ⊕ {p} = {r}',
      ja: '内側の鍵: K ⊕ ipad = {k} ⊕ {p} = {r}',
      zh: '内层密钥：K ⊕ ipad = {k} ⊕ {p} = {r}',
      ar: 'المفتاح الداخلي: K ⊕ ipad = {k} ⊕ {p} = {r}',
      es: 'Clave interior: K ⊕ ipad = {k} ⊕ {p} = {r}',
      fr: 'Clé intérieure : K ⊕ ipad = {k} ⊕ {p} = {r}',
      hi: 'भीतरी कुंजी: K ⊕ ipad = {k} ⊕ {p} = {r}',
      id: 'Kunci dalam: K ⊕ ipad = {k} ⊕ {p} = {r}',
      pt: 'Chave interna: K ⊕ ipad = {k} ⊕ {p} = {r}',
    },
    'caption.foldInner': {
      en: 'Inner fold: H({a} ‖ {b}) = {r}',
      ko: '안쪽 접기: H({a} ‖ {b}) = {r}',
      ja: '内側のたたみ: H({a} ‖ {b}) = {r}',
      zh: '内层折叠：H({a} ‖ {b}) = {r}',
      ar: 'الطي الداخلي: H({a} ‖ {b}) = {r}',
      es: 'Pliegue interior: H({a} ‖ {b}) = {r}',
      fr: 'Repli intérieur : H({a} ‖ {b}) = {r}',
      hi: 'भीतरी मोड़: H({a} ‖ {b}) = {r}',
      id: 'Lipatan dalam: H({a} ‖ {b}) = {r}',
      pt: 'Dobra interna: H({a} ‖ {b}) = {r}',
    },
    'caption.xorOuter': {
      en: 'Outer key: K ⊕ opad = {k} ⊕ {p} = {r}',
      ko: '바깥 열쇠: K ⊕ opad = {k} ⊕ {p} = {r}',
      ja: '外側の鍵: K ⊕ opad = {k} ⊕ {p} = {r}',
      zh: '外层密钥：K ⊕ opad = {k} ⊕ {p} = {r}',
      ar: 'المفتاح الخارجي: K ⊕ opad = {k} ⊕ {p} = {r}',
      es: 'Clave exterior: K ⊕ opad = {k} ⊕ {p} = {r}',
      fr: 'Clé extérieure : K ⊕ opad = {k} ⊕ {p} = {r}',
      hi: 'बाहरी कुंजी: K ⊕ opad = {k} ⊕ {p} = {r}',
      id: 'Kunci luar: K ⊕ opad = {k} ⊕ {p} = {r}',
      pt: 'Chave externa: K ⊕ opad = {k} ⊕ {p} = {r}',
    },
    'caption.carry': {
      en: 'Inner value {v} takes the message slot — outer input: {bytes}',
      ko: '안쪽 값 {v} — 메시지 자리로 옮겨 간다. 바깥 입력: {bytes}',
      ja: '内側の値 {v} — メッセージの位置へ移る。外側の入力: {bytes}',
      zh: '内层值 {v} 移到消息的位置 — 外层输入：{bytes}',
      ar: 'القيمة الداخلية {v} تأخذ خانة الرسالة — المدخل الخارجي: {bytes}',
      es: 'El valor interior {v} ocupa el hueco del mensaje — entrada exterior: {bytes}',
      fr: 'La valeur intérieure {v} prend la place du message — entrée extérieure : {bytes}',
      hi: 'भीतरी मान {v} संदेश की जगह लेता है — बाहरी इनपुट: {bytes}',
      id: 'Nilai dalam {v} menempati slot pesan — masukan luar: {bytes}',
      pt: 'O valor interno {v} ocupa o lugar da mensagem — entrada externa: {bytes}',
    },
    'caption.foldOuter': {
      en: 'Outer fold: H({a} ‖ {b}) = {r} — HMAC',
      ko: '바깥 접기: H({a} ‖ {b}) = {r} — HMAC',
      ja: '外側のたたみ: H({a} ‖ {b}) = {r} — HMAC',
      zh: '外层折叠：H({a} ‖ {b}) = {r} — HMAC',
      ar: 'الطي الخارجي: H({a} ‖ {b}) = {r} — HMAC',
      es: 'Pliegue exterior: H({a} ‖ {b}) = {r} — HMAC',
      fr: 'Repli extérieur : H({a} ‖ {b}) = {r} — HMAC',
      hi: 'बाहरी मोड़: H({a} ‖ {b}) = {r} — HMAC',
      id: 'Lipatan luar: H({a} ‖ {b}) = {r} — HMAC',
      pt: 'Dobra externa: H({a} ‖ {b}) = {r} — HMAC',
    },
  },
  blocks: {
    stage: { type: 'hash-twice-with-pads-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
