/**
 * 서브워드 분할 facet 선언.
 *
 * 진행 모델: reactive. 선언 자리는 여기가 아니라 `index.ts` 의 등록 옵션이다.
 *
 * **코드 패널을 두지 않는다.** 까닭은 `irs.ts` 머리말에 적었다.
 *
 * ── 선언에 두는 것
 *
 * 말뭉치 열아홉과 빈도, 시험 문장, 낱말 끝 표식, 손잡이가 고를 병합 횟수뿐이다.
 * 조각 수 · 어휘 · 분할 결과는 전부 `algorithm.ts` 가 여기서 셈한다 — 파생값을
 * 손으로 옮겨 적으면 말뭉치를 고치는 날 둘이 어긋난다.
 *
 * 좌표도 두지 않는다. 타일을 어디에 놓을지는 캔버스 폭에서 stage 가 역산한다.
 */

import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const subwordSegmentationFacet: FacetJson = {
  id: 'facet:subwordSegmentation',
  title: {
    en: 'Subword segmentation — a bigger vocabulary cuts the same sentence less',
    ko: '서브워드 분할 — 어휘가 커질수록 같은 문장이 덜 잘린다',
    ja: 'サブワード分割 — 語彙が大きいほど同じ文は切られにくくなる',
    zh: '子词切分 — 词表越大，同一句话被切得越少',
    ar: 'تقطيع الكلمات الفرعية — كلما كبرت المفردات قلّ تقطيع الجملة نفسها',
    es: 'Segmentación en subpalabras: a mayor vocabulario, menos se corta la misma frase',
    fr: 'Segmentation en sous-mots — plus le vocabulaire est grand, moins la même phrase est découpée',
    hi: 'सबवर्ड विभाजन — शब्दकोश जितना बड़ा, वही वाक्य उतना कम कटता है',
    id: 'Segmentasi subkata — makin besar kosakata, makin sedikit kalimat yang sama dipotong',
    pt: 'Segmentação em subpalavras — quanto maior o vocabulário, menos a mesma frase é cortada',
  },
  description: {
    en: 'Turn the merge count up and scattered letters slide together: the same sentence goes from 33 pieces to 7',
    ko: '병합 횟수를 키우면 흩어져 있던 낱글자들이 서로에게 미끄러져 합쳐진다 — 같은 문장이 조각 33 에서 7 로 줄어든다',
    ja: 'マージ回数を増やすと、散らばっていた文字どうしが滑り寄って一つになる — 同じ文が 33 個から 7 個になる',
    zh: '把合并次数调大，散落的字母就会互相滑拢合为一体 — 同一句话从 33 块变成 7 块',
    ar: 'زد عدد عمليات الدمج تنزلق الحروف المتناثرة نحو بعضها وتلتحم — الجملة نفسها تنتقل من 33 قطعة إلى 7',
    es: 'Sube el número de fusiones y las letras dispersas se deslizan hasta unirse: la misma frase pasa de 33 piezas a 7',
    fr: 'Augmentez le nombre de fusions et les lettres éparses glissent les unes vers les autres : la même phrase passe de 33 morceaux à 7',
    hi: 'मर्ज की संख्या बढ़ाइए और बिखरे अक्षर एक-दूसरे की ओर सरककर जुड़ जाते हैं — वही वाक्य 33 टुकड़ों से 7 पर आ जाता है',
    id: 'Naikkan jumlah gabungan dan huruf-huruf yang berserak meluncur saling menyatu: kalimat yang sama turun dari 33 keping menjadi 7',
    pt: 'Aumente o número de fusões e as letras espalhadas deslizam umas para as outras: a mesma frase vai de 33 peças para 7',
  },
  algorithm: 'module:subwordSegmentation',
  projector: 'module:subwordSegmentationProjector',
  initialData: {
    type: 'subwordSegmentation',
    corpus: [
      { word: 'action', freq: 12 },
      { word: 'actor', freq: 8 },
      { word: 'active', freq: 7 },
      { word: 'react', freq: 6 },
      { word: 'motion', freq: 10 },
      { word: 'motor', freq: 7 },
      { word: 'remote', freq: 5 },
      { word: 'nation', freq: 9 },
      { word: 'native', freq: 6 },
      { word: 'station', freq: 8 },
      { word: 'state', freq: 11 },
      { word: 'statement', freq: 5 },
      { word: 'create', freq: 9 },
      { word: 'creative', freq: 5 },
      { word: 'creation', freq: 7 },
      { word: 'the', freq: 24 },
      { word: 'of', freq: 18 },
      { word: 'is', freq: 16 },
      { word: 'and', freq: 20 },
    ],
    sentence: 'the creation of a native station',
    endMark: '</w>',
    mergeCounts: [0, 12, 24, 36, 44],
    initialMerges: 24,
    stepMs: 340,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage', padding: '8px 0' }, { ref: 'controls' }],
  },
  messages: {
    'label.row': {
      en: 'the sentence, cut into pieces',
      ko: '조각으로 자른 문장',
      ja: '切り分けた文',
      zh: '被切成块的句子',
      ar: 'الجملة مقطّعة إلى قطع',
      es: 'la frase, cortada en piezas',
      fr: 'la phrase, découpée en morceaux',
      hi: 'टुकड़ों में कटा वाक्य',
      id: 'kalimat yang dipotong jadi keping',
      pt: 'a frase, cortada em peças',
    },
    'label.reference': {
      en: 'length with no merges',
      ko: '병합이 없을 때의 길이',
      ja: 'マージなしのときの長さ',
      zh: '不合并时的长度',
      ar: 'الطول بلا دمج',
      es: 'longitud sin fusiones',
      fr: 'longueur sans fusion',
      hi: 'बिना मर्ज की लंबाई',
      id: 'panjang tanpa penggabungan',
      pt: 'comprimento sem fusões',
    },
    'label.aria': {
      en: 'Subword segmentation: the sentence as tiles that slide together into fewer, longer pieces as the merge count grows',
      ko: '서브워드 분할 시각화 — 문장이 타일로 놓이고, 병합 횟수가 커질수록 타일들이 서로에게 미끄러져 더 적고 긴 조각이 된다',
      ja: 'サブワード分割の可視化 — 文をタイルで並べ、マージ回数が増えるほどタイルどうしが滑り寄って少なく長い断片になる',
      zh: '子词切分可视化 — 句子以方块排开，合并次数越多，方块越互相滑拢成更少更长的块',
      ar: 'تصور تقطيع الكلمات الفرعية: الجملة كمربعات تنزلق نحو بعضها لتصير قطعًا أقل وأطول كلما زاد عدد عمليات الدمج',
      es: 'Visualización de segmentación en subpalabras: la frase como fichas que se deslizan juntas en piezas menos numerosas y más largas a medida que crecen las fusiones',
      fr: 'Visualisation de la segmentation en sous-mots : la phrase en tuiles qui glissent ensemble en morceaux moins nombreux et plus longs à mesure que les fusions augmentent',
      hi: 'सबवर्ड विभाजन का दृश्य — वाक्य टाइलों में, और मर्ज बढ़ने पर टाइलें सरककर कम और लंबे टुकड़े बन जाती हैं',
      id: 'Visualisasi segmentasi subkata: kalimat sebagai ubin yang meluncur menyatu menjadi keping yang lebih sedikit dan lebih panjang seiring bertambahnya penggabungan',
      pt: 'Visualização da segmentação em subpalavras: a frase como blocos que deslizam juntos em peças menos numerosas e mais longas conforme as fusões aumentam',
    },
    'caption.begin': {
      en: 'Learning {merges} merges, then cutting. The sentence starts as single letters: {n}.',
      ko: '병합 {merges} 번을 배우고 자른다. 문장은 낱글자로 시작한다 — 조각 수 {n}.',
      ja: 'マージを {merges} 回学んでから切る。文は一文字ずつで始まる — 断片 {n}。',
      zh: '先学 {merges} 次合并，再切。句子从单个字母开始 — 块数 {n}。',
      ar: 'نتعلّم {merges} من عمليات الدمج ثم نقطّع. تبدأ الجملة بحروف مفردة — عدد القطع {n}.',
      es: 'Aprendiendo {merges} fusiones y luego cortando. La frase empieza en letras sueltas: {n}.',
      fr: 'On apprend {merges} fusions, puis on découpe. La phrase commence en lettres isolées : {n}.',
      hi: '{merges} मर्ज सीखकर फिर काटते हैं। वाक्य अलग-अलग अक्षरों से शुरू होता है — टुकड़े {n}.',
      id: 'Mempelajari {merges} penggabungan lalu memotong. Kalimat dimulai sebagai huruf tunggal: {n}.',
      pt: 'Aprendendo {merges} fusões e então cortando. A frase começa em letras soltas: {n}.',
    },
    'caption.merge': {
      en: 'Rule {rule} of {total}: "{left}" + "{right}" becomes "{joined}". Pieces left: {n}.',
      ko: '규칙 {rule} / {total}: "{left}" + "{right}" 가 "{joined}" 가 된다. 남은 조각 {n}.',
      ja: '規則 {rule} / {total}: "{left}" + "{right}" が "{joined}" になる。残り {n}。',
      zh: '规则 {rule} / {total}："{left}" + "{right}" 合成 "{joined}"。剩余块数 {n}。',
      ar: 'القاعدة {rule} من {total}: "{left}" + "{right}" تصير "{joined}". القطع المتبقية {n}.',
      es: 'Regla {rule} de {total}: "{left}" + "{right}" pasa a ser "{joined}". Piezas restantes: {n}.',
      fr: 'Règle {rule} sur {total} : "{left}" + "{right}" devient "{joined}". Morceaux restants : {n}.',
      hi: 'नियम {rule} / {total}: "{left}" + "{right}" मिलकर "{joined}" बनते हैं। शेष टुकड़े {n}.',
      id: 'Aturan {rule} dari {total}: "{left}" + "{right}" menjadi "{joined}". Sisa keping: {n}.',
      pt: 'Regra {rule} de {total}: "{left}" + "{right}" vira "{joined}". Peças restantes: {n}.',
    },
    'caption.settled': {
      en: 'With {merges} merges the vocabulary holds {vocab} symbols, and the sentence needs {n} pieces.',
      ko: '병합 {merges} 번이면 어휘는 {vocab} 종이고, 문장에 필요한 조각은 {n}.',
      ja: 'マージ {merges} 回なら語彙は {vocab} 種、文に要る断片は {n}。',
      zh: '合并 {merges} 次时词表有 {vocab} 种，这句话只需要 {n} 块。',
      ar: 'مع {merges} من عمليات الدمج تضم المفردات {vocab} رمزًا، وتحتاج الجملة إلى {n} من القطع.',
      es: 'Con {merges} fusiones el vocabulario tiene {vocab} símbolos y la frase necesita {n} piezas.',
      fr: 'Avec {merges} fusions le vocabulaire compte {vocab} symboles et la phrase tient en {n} morceaux.',
      hi: '{merges} मर्ज पर शब्दकोश में {vocab} प्रतीक होते हैं और वाक्य को {n} टुकड़े चाहिए।',
      id: 'Dengan {merges} penggabungan kosakata berisi {vocab} simbol, dan kalimat butuh {n} keping.',
      pt: 'Com {merges} fusões o vocabulário tem {vocab} símbolos e a frase precisa de {n} peças.',
    },
    'caption.settledNone': {
      en: 'With no merges every letter stands alone. Pieces: {n}.',
      ko: '병합이 없으면 낱글자가 저마다 조각이다. 조각 수 {n}.',
      ja: 'マージがなければ一文字ずつが断片になる。断片 {n}。',
      zh: '不做合并时，每个字母各自成块。块数 {n}。',
      ar: 'بلا دمج يقف كل حرف وحده. عدد القطع {n}.',
      es: 'Sin fusiones cada letra queda sola. Piezas: {n}.',
      fr: 'Sans fusion chaque lettre reste seule. Morceaux : {n}.',
      hi: 'बिना मर्ज हर अक्षर अकेला रहता है। टुकड़े {n}.',
      id: 'Tanpa penggabungan setiap huruf berdiri sendiri. Keping: {n}.',
      pt: 'Sem fusões cada letra fica sozinha. Peças: {n}.',
    },
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'subword-segmentation-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'merges',
          name: 'merges',
          label: {
            en: 'Merges',
            ko: '병합 횟수',
            ja: 'マージ回数',
            zh: '合并次数',
            ar: 'عمليات الدمج',
            es: 'Fusiones',
            fr: 'Fusions',
            hi: 'मर्ज की संख्या',
            id: 'Jumlah gabungan',
            pt: 'Fusões',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 12, label: '12' },
            { value: 24, label: '24', default: true },
            { value: 36, label: '36' },
            { value: 44, label: '44' },
          ],
        },
      ],
      metrics: [
        {
          name: 'piece-count',
          label: {
            en: 'pieces',
            ko: '조각 수',
            ja: '断片数',
            zh: '块数',
            ar: 'القطع',
            es: 'piezas',
            fr: 'morceaux',
            hi: 'टुकड़े',
            id: 'keping',
            pt: 'peças',
          },
          initial: 0,
        },
        {
          name: 'vocab-size',
          label: {
            en: 'vocabulary',
            ko: '어휘 크기',
            ja: '語彙数',
            zh: '词表大小',
            ar: 'المفردات',
            es: 'vocabulario',
            fr: 'vocabulaire',
            hi: 'शब्दकोश',
            id: 'kosakata',
            pt: 'vocabulário',
          },
          initial: 0,
        },
      ],
    },
  },
};
