import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const floatingPointFacet: FacetJson = {
  id: 'facet:floatingPoint',
  title: {
    en: 'Floating Point — Exponent or Mantissa',
    ko: '부동소수점 — 지수에 줄까 가수에 줄까',
    ja: '浮動小数点 — 指数か仮数か',
    zh: '浮点数 — 给指数还是给尾数',
    ar: 'الفاصلة العائمة — للأس أم للمعنِّي',
    es: 'Punto flotante — ¿al exponente o a la mantisa?',
    fr: "Virgule flottante — à l'exposant ou à la mantisse",
    hi: 'फ़्लोटिंग पॉइंट — घातांक को या अंशिका को',
    id: 'Titik mengambang — ke eksponen atau mantisa',
    pt: 'Ponto flutuante — ao expoente ou à mantissa',
  },
  description: {
    en: 'Eight bits, one for the sign: the remaining seven are split between exponent and mantissa, and every bit given to reach is a bit taken from resolution.',
    ko: '여덟 비트 중 부호 하나를 빼고 남은 일곱을 지수와 가수가 나눠 갖는다 — 멀리 닿으려 지수에 준 비트는 촘촘함에서 빼 온 것이다.',
    ja: '八ビットのうち符号を除く七ビットを指数と仮数で分け合う。遠くへ届くために指数へ渡したビットは、細かさから取り上げたものだ。',
    zh: '八位中除去符号位，其余七位由指数与尾数瓜分：给指数用来够得更远的每一位，都是从精细度里拿走的。',
    ar: 'ثماني بتات، واحدة للإشارة: تُقسَّم السبع الباقية بين الأس والمعنِّي، وكل بتّة تُمنح للمدى تُؤخذ من الدقة.',
    es: 'Ocho bits, uno para el signo: los siete restantes se reparten entre exponente y mantisa, y cada bit dado al alcance se le quita a la resolución.',
    fr: "Huit bits, un pour le signe : les sept autres se partagent entre exposant et mantisse, et chaque bit donné à la portée est pris à la finesse.",
    hi: 'आठ बिट, एक चिह्न के लिए: बचे सात घातांक और अंशिका में बँटते हैं, और पहुँच के लिए दिया हर बिट सूक्ष्मता से लिया गया है।',
    id: 'Delapan bit, satu untuk tanda: tujuh sisanya dibagi antara eksponen dan mantisa, dan setiap bit yang diberikan untuk jangkauan diambil dari kehalusan.',
    pt: 'Oito bits, um para o sinal: os sete restantes dividem-se entre expoente e mantissa, e cada bit dado ao alcance é tirado à resolução.',
  },
  algorithm: 'module:floatingPoint',
  projector: 'module:floatingPointProjector',
  initialData: {
    type: 'floating-point',
    totalBits: 8,
    signBits: 1,
    expBitsLadder: [2, 3, 4, 5],
    expBits: 3,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { ref: 'controls' },
      { ref: 'codePanel' },
    ],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'floating-point-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'expBits',
          name: 'expBits',
          label: {
            en: 'Exponent bits',
            ko: '지수 비트',
            ja: '指数ビット',
            zh: '指数位',
            ar: 'بتات الأس',
            es: 'Bits de exponente',
            fr: "Bits d'exposant",
            hi: 'घातांक बिट',
            id: 'Bit eksponen',
            pt: 'Bits de expoente',
          },
          segments: [
            { value: 2, label: '2' },
            { value: 3, label: '3', default: true },
            { value: 4, label: '4' },
            { value: 5, label: '5' },
          ],
        },
      ],
      metrics: [
        {
          name: 'max-value',
          label: {
            en: 'Largest value',
            ko: '담는 최대값',
            ja: '最大値',
            zh: '最大值',
            ar: 'أكبر قيمة',
            es: 'Valor máximo',
            fr: 'Valeur maximale',
            hi: 'सबसे बड़ा मान',
            id: 'Nilai terbesar',
            pt: 'Maior valor',
          },
          initial: 0,
        },
        {
          name: 'tick-count',
          label: {
            en: 'Ticks 1 to 2',
            ko: '1–2 눈금',
            ja: '1–2 の目盛り',
            zh: '1–2 刻度',
            ar: 'تدريج 1–2',
            es: 'Pasos 1–2',
            fr: 'Pas 1–2',
            hi: '1–2 चरण',
            id: 'Langkah 1–2',
            pt: 'Passos 1–2',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:floating-point-imperative',
      label: {
        en: 'How the format is computed',
        ko: '형식을 셈하는 법',
        ja: '形式の計算',
        zh: '格式的计算',
        ar: 'كيف تُحسب الصيغة',
        es: 'Cómo se calcula el formato',
        fr: 'Comment le format est calculé',
        hi: 'प्रारूप की गणना',
        id: 'Cara format dihitung',
        pt: 'Como o formato é calculado',
      },
    },
  },
  messages: {
    'label.split': {
      en: 'Sign {s} · Exponent {e} · Mantissa {m}',
      ko: '부호 {s} · 지수 {e} · 가수 {m}',
      ja: '符号 {s} · 指数 {e} · 仮数 {m}',
      zh: '符号 {s} · 指数 {e} · 尾数 {m}',
      ar: 'إشارة {s} · أس {e} · معنِّي {m}',
      es: 'Signo {s} · Exponente {e} · Mantisa {m}',
      fr: 'Signe {s} · Exposant {e} · Mantisse {m}',
      hi: 'चिह्न {s} · घातांक {e} · अंशिका {m}',
      id: 'Tanda {s} · Eksponen {e} · Mantisa {m}',
      pt: 'Sinal {s} · Expoente {e} · Mantissa {m}',
    },
    'label.bias': {
      en: 'Bias',
      ko: '치우침',
      ja: 'バイアス',
      zh: '偏移',
      ar: 'الانحياز',
      es: 'Sesgo',
      fr: 'Biais',
      hi: 'बायस',
      id: 'Bias',
      pt: 'Viés',
    },
    'label.maxValue': {
      en: 'Largest value',
      ko: '담는 최대값',
      ja: '最大値',
      zh: '最大值',
      ar: 'أكبر قيمة',
      es: 'Valor máximo',
      fr: 'Valeur maximale',
      hi: 'सबसे बड़ा मान',
      id: 'Nilai terbesar',
      pt: 'Maior valor',
    },
    'label.minNormal': {
      en: 'Smallest normal',
      ko: '최소 정규값',
      ja: '最小正規数',
      zh: '最小正规值',
      ar: 'أصغر قيمة عادية',
      es: 'Mínimo normal',
      fr: 'Plus petit normal',
      hi: 'सबसे छोटा सामान्य',
      id: 'Normal terkecil',
      pt: 'Menor normal',
    },
    'label.gap': {
      en: 'Gap next to 1.0',
      ko: '1.0 옆 간격',
      ja: '1.0 の隣との間隔',
      zh: '1.0 旁的间隔',
      ar: 'الفجوة بجوار 1.0',
      es: 'Salto junto a 1.0',
      fr: 'Écart près de 1.0',
      hi: '1.0 के पास अंतर',
      id: 'Jarak di sisi 1.0',
      pt: 'Intervalo junto a 1.0',
    },
    'caption.ruler': {
      en: 'From 1 to 2 in {n} steps',
      ko: '1 에서 2 까지 {n} 칸',
      ja: '1 から 2 まで {n} 段',
      zh: '从 1 到 2 共 {n} 格',
      ar: 'من 1 إلى 2 في {n} خطوة',
      es: 'De 1 a 2 en {n} pasos',
      fr: 'De 1 à 2 en {n} pas',
      hi: '1 से 2 तक {n} चरण',
      id: 'Dari 1 ke 2 dalam {n} langkah',
      pt: 'De 1 a 2 em {n} passos',
    },
    'caption.stored': {
      en: 'Store {x} and you get back {v}',
      ko: '{x} 를 담으면 {v} 가 된다',
      ja: '{x} を入れると {v} になる',
      zh: '存入 {x} 得到 {v}',
      ar: 'خزّن {x} فتستعيد {v}',
      es: 'Guarda {x} y recuperas {v}',
      fr: 'Stockez {x} et vous obtenez {v}',
      hi: '{x} रखें तो {v} मिलता है',
      id: 'Simpan {x} dan kembali {v}',
      pt: 'Guarde {x} e obtém {v}',
    },
    'caption.tradeoff': {
      en: 'Give the exponent more and you reach further with a coarser ruler.',
      ko: '지수에 더 주면 더 멀리 닿고 눈금은 성겨진다.',
      ja: '指数に多く与えるほど遠くまで届き、目盛りは粗くなる。',
      zh: '给指数越多，够得越远，刻度越粗。',
      ar: 'امنح الأس أكثر تبلغ أبعد بمسطرة أخشن.',
      es: 'Da más al exponente y llegarás más lejos con una regla más basta.',
      fr: "Donnez plus à l'exposant : vous allez plus loin avec une règle plus grossière.",
      hi: 'घातांक को अधिक दें तो पहुँच बढ़ती है और पैमाना मोटा होता है।',
      id: 'Beri eksponen lebih banyak: jangkauan jauh, penggaris kasar.',
      pt: 'Dê mais ao expoente e alcança mais longe com uma régua mais grosseira.',
    },
  },
};
