import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: `let` 에 타입을 적지 않으면 컴파일러는 그 이름의 타입을 어디서 얻는가.
 *
 * 답: 식의 맨 아래 잎(값 글자 · 이름)에서 타입이 먼저 정해지고, 연산을 하나 지날 때마다 규칙으로 합쳐져
 * 한 칸씩 위로 오른다. 뿌리에 닿은 타입이 그 이름의 타입이 된다. 값은 셈하지 않는다.
 */
export const typeFlowsUpFacet: FacetJson = {
  id: 'facet:typeFlowsUp',
  title: {
    en: 'The type flows up the expression',
    ko: '타입이 식을 타고 오른다',
    ja: '型は式を上へ流れる',
    zh: '类型沿表达式向上流动',
    ar: 'النوع يصعد عبر التعبير',
    es: 'El tipo sube por la expresión',
    fr: "Le type remonte l'expression",
    hi: 'टाइप व्यंजक में ऊपर चढ़ता है',
    id: 'Tipe naik melewati ekspresi',
    pt: 'O tipo sobe pela expressão',
  },
  description: {
    en: 'With no type written on let, types are fixed at the leaves and merge by rule at each operator on the way to the root. The root type becomes the name’s type.',
    ko: 'let 에 타입을 적지 않으면 잎에서 정해진 타입이 연산마다 규칙으로 합쳐지며 뿌리까지 오르고, 뿌리의 타입이 그 이름의 타입이 된다.',
    ja: 'let に型を書かないと、葉で決まった型が演算ごとに規則で合わさりながら根まで上り、根の型がその名前の型になる。',
    zh: '在 let 上不写类型时，叶子上确定的类型在每个运算处按规则合并并升到根，根的类型成为该名字的类型。',
    ar: 'حين لا يُكتب نوع على let، تتحدد الأنواع عند الأوراق وتندمج وفق القاعدة عند كل عملية حتى الجذر، ويصير نوع الجذر نوع الاسم.',
    es: 'Sin tipo escrito en let, los tipos se fijan en las hojas y se combinan por regla en cada operador hasta la raíz. El tipo de la raíz pasa a ser el del nombre.',
    fr: 'Sans type écrit sur let, les types se fixent aux feuilles et se combinent par règle à chaque opérateur jusqu’à la racine. Le type de la racine devient celui du nom.',
    hi: 'let पर टाइप न लिखा हो तो पत्तों पर तय टाइप हर संक्रिया पर नियम से मिलते हुए जड़ तक चढ़ते हैं, और जड़ का टाइप उस नाम का टाइप बन जाता है।',
    id: 'Tanpa tipe tertulis pada let, tipe ditetapkan di daun lalu digabung menurut aturan di tiap operator hingga akar. Tipe akar menjadi tipe nama itu.',
    pt: 'Sem tipo escrito no let, os tipos se fixam nas folhas e se combinam por regra em cada operador até a raiz. O tipo da raiz vira o tipo do nome.',
  },
  algorithm: 'module:typeFlowsUp',
  scene: 'module:typeFlowsUpScene',
  initialData: {
    type: 'type-flows-up',
    stepMs: 900,
    lines: [
      { indent: 0, text: 'let count = 4', stmt: { k: 'let', name: 'count', value: { k: 'int', v: 4 } } },
      { indent: 0, text: 'let price = 2.5', stmt: { k: 'let', name: 'price', value: { k: 'float', v: 2.5 } } },
      {
        indent: 0,
        text: 'let big = count * 3 + price > 10',
        stmt: {
          k: 'let',
          name: 'big',
          value: {
            k: 'op',
            op: '>',
            l: {
              k: 'op',
              op: '+',
              l: { k: 'op', op: '*', l: { k: 'var', name: 'count' }, r: { k: 'int', v: 3 } },
              r: { k: 'var', name: 'price' },
            },
            r: { k: 'int', v: 10 },
          },
        },
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.names': {
      en: 'Names',
      ko: '이름 표',
      ja: '名前の表',
      zh: '名字表',
      ar: 'الأسماء',
      es: 'Nombres',
      fr: 'Noms',
      hi: 'नाम',
      id: 'Nama',
      pt: 'Nomes',
    },
    'caption.start': {
      en: 'No type is written. No type is known yet.',
      ko: '적힌 타입이 없다. 아직 정해진 타입도 없다.',
      ja: '型は書かれていない。決まった型もまだない。',
      zh: '没有写出类型。也还没有确定的类型。',
      ar: 'لا نوع مكتوب. ولا نوع معروف بعد.',
      es: 'No hay tipos escritos. Aún no se conoce ninguno.',
      fr: 'Aucun type n’est écrit. Aucun type n’est encore connu.',
      hi: 'कोई टाइप लिखा नहीं है। अभी कोई टाइप तय भी नहीं है।',
      id: 'Tidak ada tipe tertulis. Belum ada tipe yang diketahui.',
      pt: 'Nenhum tipo está escrito. Nenhum tipo é conhecido ainda.',
    },
    'caption.literal': {
      en: 'Literal {text}: type {type}.',
      ko: '값 글자 {text}: 타입 {type}.',
      ja: 'リテラル {text}：型 {type}。',
      zh: '字面量 {text}：类型 {type}。',
      ar: 'القيمة الحرفية {text}: النوع {type}.',
      es: 'Literal {text}: tipo {type}.',
      fr: 'Littéral {text} : type {type}.',
      hi: 'लिटरल {text}: टाइप {type}।',
      id: 'Literal {text}: tipe {type}.',
      pt: 'Literal {text}: tipo {type}.',
    },
    'caption.name': {
      en: 'Name {name}: type {type}, from the names row (L{line}).',
      ko: '이름 {name}: 이름 표에 적힌 타입 {type} (L{line}).',
      ja: '名前 {name}：名前の表にある型 {type}（L{line}）。',
      zh: '名字 {name}：名字表中的类型 {type}（L{line}）。',
      ar: 'الاسم {name}: النوع {type} من صف الأسماء (L{line}).',
      es: 'Nombre {name}: tipo {type}, tomado de la fila de nombres (L{line}).',
      fr: 'Nom {name} : type {type}, lu dans la rangée des noms (L{line}).',
      hi: 'नाम {name}: नामों की पंक्ति से टाइप {type} (L{line})।',
      id: 'Nama {name}: tipe {type}, dari baris nama (L{line}).',
      pt: 'Nome {name}: tipo {type}, lido da fila de nomes (L{line}).',
    },
    'caption.keep': {
      en: 'Rule {l} {op} {r} → {type}: the type rises unchanged.',
      ko: '규칙 {l} {op} {r} → {type}: 타입이 그대로 오른다.',
      ja: '規則 {l} {op} {r} → {type}：型はそのまま上る。',
      zh: '规则 {l} {op} {r} → {type}：类型原样上升。',
      ar: 'القاعدة {l} {op} {r} → {type}: يصعد النوع دون تغيير.',
      es: 'Regla {l} {op} {r} → {type}: el tipo sube sin cambiar.',
      fr: 'Règle {l} {op} {r} → {type} : le type remonte tel quel.',
      hi: 'नियम {l} {op} {r} → {type}: टाइप बिना बदले चढ़ता है।',
      id: 'Aturan {l} {op} {r} → {type}: tipe naik tanpa berubah.',
      pt: 'Regra {l} {op} {r} → {type}: o tipo sobe sem mudar.',
    },
    'caption.widen': {
      en: 'Rule {l} {op} {r} → {type}: {from} widens on the way up.',
      ko: '규칙 {l} {op} {r} → {type}: 오르며 넓혀지는 쪽은 {from}.',
      ja: '規則 {l} {op} {r} → {type}：上る途中で広げられる側 {from}。',
      zh: '规则 {l} {op} {r} → {type}：上升时被拓宽的一侧 {from}。',
      ar: 'القاعدة {l} {op} {r} → {type}: يتّسع {from} في الصعود.',
      es: 'Regla {l} {op} {r} → {type}: {from} se ensancha al subir.',
      fr: 'Règle {l} {op} {r} → {type} : {from} s’élargit en remontant.',
      hi: 'नियम {l} {op} {r} → {type}: चढ़ते हुए {from} चौड़ा होता है।',
      id: 'Aturan {l} {op} {r} → {type}: {from} melebar saat naik.',
      pt: 'Regra {l} {op} {r} → {type}: {from} se alarga ao subir.',
    },
    'caption.turn': {
      en: 'Rule {l} {op} {r} → {type}: a type neither side had.',
      ko: '규칙 {l} {op} {r} → {type}: 양쪽 어디에도 없던 타입.',
      ja: '規則 {l} {op} {r} → {type}：どちらの側にもなかった型。',
      zh: '规则 {l} {op} {r} → {type}：两侧都没有的类型。',
      ar: 'القاعدة {l} {op} {r} → {type}: نوع لم يكن في أيّ من الطرفين.',
      es: 'Regla {l} {op} {r} → {type}: un tipo que ningún lado tenía.',
      fr: 'Règle {l} {op} {r} → {type} : un type qu’aucun côté n’avait.',
      hi: 'नियम {l} {op} {r} → {type}: ऐसा टाइप जो किसी भी ओर नहीं था।',
      id: 'Aturan {l} {op} {r} → {type}: tipe yang tidak dimiliki kedua sisi.',
      pt: 'Regra {l} {op} {r} → {type}: um tipo que nenhum lado tinha.',
    },
    'caption.concat': {
      en: 'Rule {l} {op} {r} → {type}: joined as text.',
      ko: '규칙 {l} {op} {r} → {type}: 글자로 이어진다.',
      ja: '規則 {l} {op} {r} → {type}：文字としてつながる。',
      zh: '规则 {l} {op} {r} → {type}：作为文字连接。',
      ar: 'القاعدة {l} {op} {r} → {type}: يُوصَل نصًّا.',
      es: 'Regla {l} {op} {r} → {type}: se une como texto.',
      fr: 'Règle {l} {op} {r} → {type} : joint comme texte.',
      hi: 'नियम {l} {op} {r} → {type}: पाठ की तरह जुड़ता है।',
      id: 'Aturan {l} {op} {r} → {type}: digabung sebagai teks.',
      pt: 'Regra {l} {op} {r} → {type}: unido como texto.',
    },
    'caption.bind': {
      en: 'The root type rises to the name: {name} → {type}.',
      ko: '뿌리의 타입이 이름으로 오른다: {name} → {type}.',
      ja: '根の型が名前へ上る：{name} → {type}。',
      zh: '根的类型升到名字上：{name} → {type}。',
      ar: 'يصعد نوع الجذر إلى الاسم: {name} → {type}.',
      es: 'El tipo de la raíz sube al nombre: {name} → {type}.',
      fr: 'Le type de la racine remonte au nom : {name} → {type}.',
      hi: 'जड़ का टाइप नाम तक चढ़ता है: {name} → {type}।',
      id: 'Tipe akar naik ke nama: {name} → {type}.',
      pt: 'O tipo da raiz sobe ao nome: {name} → {type}.',
    },
    'caption.done': {
      en: 'Inference done. Typed names: {n}.',
      ko: '추론을 마쳤다. 타입이 붙은 이름: {n}.',
      ja: '推論を終えた。型が付いた名前：{n}。',
      zh: '推断完成。带类型的名字：{n}。',
      ar: 'انتهى الاستنتاج. الأسماء ذات النوع: {n}.',
      es: 'Inferencia terminada. Nombres con tipo: {n}.',
      fr: 'Inférence terminée. Noms typés : {n}.',
      hi: 'अनुमान पूरा हुआ। टाइप वाले नाम: {n}।',
      id: 'Inferensi selesai. Nama bertipe: {n}.',
      pt: 'Inferência concluída. Nomes com tipo: {n}.',
    },
  },
  blocks: {
    stage: { type: 'type-flows-up-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
