/**
 * facet:ahoCorasick — 패턴을 더 넣어도 글은 한 번만 읽는다.
 *
 * 손잡이 하나가 논증을 진다. 패턴 개수를 1 에서 5 로 밀면 "따로 훑으면" 은
 * 32 에서 135 로 늘지만 "읽은 글자" 는 21 에서 꿈쩍하지 않는다.
 *
 * `initialData` 의 1차 데이터는 패턴 목록과 글뿐이다. 나무·실패 링크·찾은
 * 자리·두 수는 전부 algorithm 이 그 자리에서 셈한다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const ahoCorasickFacet: FacetJson = {
  id: 'facet:ahoCorasick',
  title: {
    en: 'Aho-Corasick',
    ko: '아호-코라식',
    ja: 'エイホ・コラシック',
    zh: 'Aho-Corasick 算法',
    ar: 'خوارزمية آهو-كوراسيك',
    es: 'Aho-Corasick',
    fr: 'Aho-Corasick',
    hi: 'अहो-कोरासिक',
    id: 'Aho-Corasick',
    pt: 'Aho-Corasick',
  },
  description: {
    en: 'Add more patterns and the text is still read once. Push the handle and watch one number refuse to move.',
    ko: '패턴을 더 넣어도 글은 한 번만 읽는다. 손잡이를 밀어 한 수가 꿈쩍하지 않는 것을 본다.',
    ja: 'パターンを増やしてもテキストは一度しか読まない。つまみを動かして、動かない数を見る。',
    zh: '再加模式，文本仍然只读一次。推动手柄，看一个数字纹丝不动。',
    ar: 'أضف أنماطًا أكثر ويبقى النص يُقرأ مرة واحدة. حرّك المقبض وانظر رقمًا لا يتزحزح.',
    es: 'Añade más patrones y el texto se sigue leyendo una sola vez. Mueve la perilla y mira un número que no se mueve.',
    fr: 'Ajoutez des motifs : le texte est toujours lu une seule fois. Déplacez la molette et voyez un nombre qui ne bouge pas.',
    hi: 'और पैटर्न जोड़ें, फिर भी पाठ एक ही बार पढ़ा जाता है। नियंत्रक घुमाएँ और देखें कि एक संख्या हिलती ही नहीं।',
    id: 'Tambah pola sebanyak apa pun, teks tetap dibaca sekali. Geser kenop dan lihat satu angka yang tak bergerak.',
    pt: 'Acrescente mais padrões e o texto continua a ser lido uma só vez. Mova o controlo e veja um número que não se move.',
  },
  algorithm: 'module:ahoCorasick',
  projector: 'module:ahoCorasickProjector',
  initialData: {
    type: 'aho-corasick',
    // 1차 데이터. 나무도 링크도 찾은 자리도 여기 없다 — 전부 algorithm 이 센다.
    patterns: ['abra', 'bra', 'cad', 'ada', 'raa'],
    text: 'abracadabraabracadabr',
    patternCount: 3,
    stepMs: 520,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { ref: 'controls' },
      { ref: 'codePanel' },
    ],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'aho-corasick-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'patterns',
          name: 'patterns',
          label: {
            en: 'Patterns',
            ko: '패턴 개수',
            ja: 'パターン数',
            zh: '模式个数',
            ar: 'عدد الأنماط',
            es: 'Patrones',
            fr: 'Motifs',
            hi: 'पैटर्न संख्या',
            id: 'Jumlah pola',
            pt: 'Padrões',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3', default: true },
            { value: 4, label: '4' },
            { value: 5, label: '5' },
          ],
        },
      ],
      metrics: [
        {
          name: 'chars-read',
          label: {
            en: 'Characters read',
            ko: '읽은 글자',
            ja: '読んだ文字',
            zh: '读过的字符',
            ar: 'الأحرف المقروءة',
            es: 'Caracteres leídos',
            fr: 'Caractères lus',
            hi: 'पढ़े गए अक्षर',
            id: 'Karakter dibaca',
            pt: 'Caracteres lidos',
          },
          initial: 0,
        },
        {
          name: 'separate-reads',
          label: {
            en: 'One at a time',
            ko: '따로 훑으면',
            ja: '別々に走査すると',
            zh: '逐个查找时',
            ar: 'واحدًا تلو الآخر',
            es: 'Uno por uno',
            fr: 'Un par un',
            hi: 'एक-एक करके',
            id: 'Satu per satu',
            pt: 'Um de cada vez',
          },
          initial: 0,
        },
        {
          name: 'match-count',
          label: {
            en: 'Matches',
            ko: '찾은 것',
            ja: '見つけた数',
            zh: '找到的数量',
            ar: 'المطابقات',
            es: 'Coincidencias',
            fr: 'Trouvailles',
            hi: 'मिले मेल',
            id: 'Kecocokan',
            pt: 'Ocorrências',
          },
          initial: 0,
        },
        {
          name: 'node-count',
          label: {
            en: 'Nodes',
            ko: '마디',
            ja: '節点',
            zh: '节点',
            ar: 'العقد',
            es: 'Nodos',
            fr: 'Nœuds',
            hi: 'नोड',
            id: 'Simpul',
            pt: 'Nós',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:aho-corasick-imperative',
      label: {
        en: 'Build and scan',
        ko: '나무 짓기와 훑기',
        ja: '木を建てて走査する',
        zh: '建树与扫描',
        ar: 'بناء الشجرة والمسح',
        es: 'Construir y recorrer',
        fr: 'Construire et parcourir',
        hi: 'पेड़ बनाना और स्कैन',
        id: 'Bangun dan pindai',
        pt: 'Construir e percorrer',
      },
    },
  },
  messages: {
    'label.patterns': {
      en: 'Patterns',
      ko: '패턴',
      ja: 'パターン',
      zh: '模式',
      ar: 'الأنماط',
      es: 'Patrones',
      fr: 'Motifs',
      hi: 'पैटर्न',
      id: 'Pola',
      pt: 'Padrões',
    },
    'label.text': {
      en: 'Text',
      ko: '글',
      ja: 'テキスト',
      zh: '文本',
      ar: 'النص',
      es: 'Texto',
      fr: 'Texte',
      hi: 'पाठ',
      id: 'Teks',
      pt: 'Texto',
    },
    'label.read': {
      en: 'Characters read',
      ko: '읽은 글자',
      ja: '読んだ文字',
      zh: '读过的字符',
      ar: 'الأحرف المقروءة',
      es: 'Caracteres leídos',
      fr: 'Caractères lus',
      hi: 'पढ़े गए अक्षर',
      id: 'Karakter dibaca',
      pt: 'Caracteres lidos',
    },
    'label.separate': {
      en: 'One at a time',
      ko: '따로 훑으면',
      ja: '別々に走査すると',
      zh: '逐个查找时',
      ar: 'واحدًا تلو الآخر',
      es: 'Uno por uno',
      fr: 'Un par un',
      hi: 'एक-एक करके',
      id: 'Satu per satu',
      pt: 'Um de cada vez',
    },
    'caption.setup': {
      en: 'Folding {k} patterns into one tree over {n} characters of text.',
      ko: '패턴 {k} 개를 한 나무로 포갠다. 글은 {n} 글자.',
      ja: '{k} 個のパターンを一本の木に重ねる。テキストは {n} 文字。',
      zh: '把 {k} 个模式叠成一棵树。文本共 {n} 个字符。',
      ar: 'نطوي {k} نمطًا في شجرة واحدة على نص من {n} حرفًا.',
      es: 'Plegamos {k} patrones en un solo árbol sobre un texto de {n} caracteres.',
      fr: 'On replie {k} motifs en un seul arbre sur un texte de {n} caractères.',
      hi: '{k} पैटर्न एक ही पेड़ में मोड़े जाते हैं; पाठ {n} अक्षरों का है।',
      id: 'Melipat {k} pola menjadi satu pohon atas teks {n} karakter.',
      pt: 'Dobramos {k} padrões numa única árvore sobre um texto de {n} caracteres.',
    },
    'caption.built': {
      en: 'One tree, {n} nodes. A shared prefix is a single node.',
      ko: '마디 {n} 개짜리 나무 하나. 같은 앞머리는 한 마디다.',
      ja: '節点 {n} 個の木が一本。共通の接頭辞は一つの節点になる。',
      zh: '一棵树，{n} 个节点。共同前缀就是同一个节点。',
      ar: 'شجرة واحدة بـ {n} عقدة. البادئة المشتركة عقدة واحدة.',
      es: 'Un solo árbol, {n} nodos. Un prefijo común es un único nodo.',
      fr: 'Un seul arbre, {n} nœuds. Un préfixe commun est un seul nœud.',
      hi: 'एक पेड़, {n} नोड। साझा उपसर्ग एक ही नोड होता है।',
      id: 'Satu pohon, {n} simpul. Awalan yang sama menjadi satu simpul.',
      pt: 'Uma árvore, {n} nós. Um prefixo comum é um único nó.',
    },
    'caption.linked': {
      en: '{n} fail links. On a mismatch it jumps to the longest overlap already read.',
      ko: '실패 링크 {n} 개. 어긋나면 이미 읽은 가장 긴 겹침으로 건너뛴다.',
      ja: '失敗リンクが {n} 本。ずれたら、すでに読んだ最長の重なりへ跳ぶ。',
      zh: '{n} 条失败链接。失配时跳到已经读过的最长重叠处。',
      ar: '{n} رابط فشل. عند عدم التطابق يقفز إلى أطول تداخل قُرئ سلفًا.',
      es: '{n} enlaces de fallo. Al fallar salta al solapamiento más largo ya leído.',
      fr: "{n} liens d'échec. En cas d'échec, on saute vers le plus long chevauchement déjà lu.",
      hi: '{n} फेल-लिंक। बेमेल होने पर पहले पढ़े गए सबसे लंबे अतिव्यापन पर कूदता है।',
      id: '{n} tautan gagal. Saat tak cocok, ia melompat ke tumpang tindih terpanjang yang sudah dibaca.',
      pt: '{n} ligações de falha. Ao falhar, salta para a maior sobreposição já lida.',
    },
    'caption.read': {
      en: '"{char}" — one step down to "{word}". Characters read: {n}.',
      ko: '"{char}" — 한 칸 내려가 "{word}" 에 선다. 읽은 글자 {n}.',
      ja: '「{char}」— 一段下って「{word}」に立つ。読んだ文字 {n}。',
      zh: '「{char}」— 向下走一层，停在「{word}」。已读 {n} 个字符。',
      ar: '«{char}» — خطوة نزولًا إلى «{word}». الأحرف المقروءة {n}.',
      es: '«{char}»: un paso abajo hasta «{word}». Caracteres leídos: {n}.',
      fr: '« {char} » : un pas plus bas jusqu’à « {word} ». Caractères lus : {n}.',
      hi: '«{char}» — एक कदम नीचे «{word}» तक। पढ़े गए अक्षर: {n}।',
      id: '"{char}" — turun satu langkah ke "{word}". Karakter dibaca: {n}.',
      pt: '«{char}» — um passo abaixo até «{word}». Caracteres lidos: {n}.',
    },
    'caption.slide': {
      en: '"{char}" — the path ended, so it slid back and went on to "{word}". The reading spot never moved.',
      ko: '"{char}" — 길이 끊겨 뒤로 미끄러진 뒤 "{word}" 로 이었다. 읽는 자리는 그대로다.',
      ja: '「{char}」— 道が途切れ、後ろへ滑ってから「{word}」へ続く。読む位置は動かない。',
      zh: '「{char}」— 路断了，先向后滑再接到「{word}」。读的位置没有后退。',
      ar: '«{char}» — انقطع المسار، فانزلق إلى الخلف وتابع إلى «{word}». موضع القراءة لم يتحرك.',
      es: '«{char}»: el camino se cortó, resbaló atrás y siguió hasta «{word}». El punto de lectura no se movió.',
      fr: '« {char} » : le chemin s’est arrêté, on a glissé en arrière puis continué jusqu’à « {word} ». Le point de lecture n’a pas bougé.',
      hi: '«{char}» — रास्ता टूटा, पीछे फिसलकर «{word}» तक आगे बढ़ा। पढ़ने की जगह नहीं हिली।',
      id: '"{char}" — jalur terputus, ia tergelincir mundur lalu lanjut ke "{word}". Titik baca tidak bergerak.',
      pt: '«{char}» — o caminho acabou, deslizou para trás e seguiu até «{word}». O ponto de leitura não recuou.',
    },
    'caption.restart': {
      en: '"{char}" — nothing continues here, so it starts again at the root. Even so the text never rewinds.',
      ko: '"{char}" — 이어갈 길이 없어 뿌리에서 다시 시작한다. 그래도 글은 되감지 않는다.',
      ja: '「{char}」— 続く道がないので根から始め直す。それでもテキストは巻き戻さない。',
      zh: '「{char}」— 没有可继续的路，于是从根重新开始。即便如此，文本也不回退。',
      ar: '«{char}» — لا شيء يكمل هنا، فيبدأ من الجذر مجددًا. ومع ذلك لا يعود النص إلى الوراء.',
      es: '«{char}»: aquí no continúa nada, así que empieza de nuevo en la raíz. Aun así el texto no retrocede.',
      fr: '« {char} » : rien ne continue ici, on repart donc de la racine. Le texte ne revient pas en arrière pour autant.',
      hi: '«{char}» — यहाँ कुछ आगे नहीं बढ़ता, इसलिए जड़ से फिर शुरू होता है। फिर भी पाठ पीछे नहीं जाता।',
      id: '"{char}" — tidak ada yang berlanjut di sini, jadi mulai lagi dari akar. Meski begitu teks tidak mundur.',
      pt: '«{char}» — nada continua aqui, então recomeça na raiz. Ainda assim o texto não volta atrás.',
    },
    'caption.hit': {
      en: 'A pattern ends here: {names}.',
      ko: '여기서 패턴 하나가 끝난다: {names}.',
      ja: 'ここでパターンが一つ終わる: {names}。',
      zh: '这里有一个模式结束：{names}。',
      ar: 'ينتهي هنا نمط واحد: {names}.',
      es: 'Aquí termina un patrón: {names}.',
      fr: 'Un motif se termine ici : {names}.',
      hi: 'यहाँ एक पैटर्न समाप्त होता है: {names}।',
      id: 'Satu pola berakhir di sini: {names}.',
      pt: 'Aqui termina um padrão: {names}.',
    },
    'caption.hitMany': {
      en: '{count} patterns end at this one node, caught in the same step: {names}.',
      ko: '한 마디에서 패턴 {count} 개가 같은 걸음에 함께 걸린다: {names}.',
      ja: '一つの節点でパターン {count} 個が同じ一歩で掛かる: {names}。',
      zh: '同一个节点上，{count} 个模式在同一步里一起被捕到：{names}。',
      ar: 'تنتهي {count} أنماط عند العقدة نفسها وتُلتقط في الخطوة ذاتها: {names}.',
      es: '{count} patrones terminan en el mismo nodo y se atrapan en el mismo paso: {names}.',
      fr: '{count} motifs se terminent au même nœud et sont attrapés dans le même pas : {names}.',
      hi: 'एक ही नोड पर {count} पैटर्न एक ही कदम में पकड़े जाते हैं: {names}।',
      id: '{count} pola berakhir di simpul yang sama dan tertangkap dalam langkah yang sama: {names}.',
      pt: '{count} padrões terminam no mesmo nó e são apanhados no mesmo passo: {names}.',
    },
    'caption.done': {
      en: 'Read {read} characters for {k} patterns. One at a time it would have been {separate}.',
      ko: '패턴 {k} 개를 찾는 데 읽은 글자는 {read}. 따로 훑었다면 {separate}.',
      ja: '{k} 個のパターンを見つけるのに読んだ文字は {read}。別々に走査していれば {separate}。',
      zh: '为了找 {k} 个模式，只读了 {read} 个字符。逐个查找则要 {separate} 个。',
      ar: 'قرأنا {read} حرفًا للبحث عن {k} أنماط. لو بحثنا واحدًا تلو الآخر لصارت {separate}.',
      es: 'Se leyeron {read} caracteres para {k} patrones. Uno por uno habrían sido {separate}.',
      fr: 'On a lu {read} caractères pour {k} motifs. Un par un, il en aurait fallu {separate}.',
      hi: '{k} पैटर्न के लिए {read} अक्षर पढ़े गए। एक-एक करके खोजते तो {separate} होते।',
      id: 'Membaca {read} karakter untuk {k} pola. Satu per satu akan menjadi {separate}.',
      pt: 'Lemos {read} caracteres para {k} padrões. Um de cada vez teriam sido {separate}.',
    },
  },
};
