import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: FIFO 에서 프레임을 늘렸는데 폴트가 오히려 늘 수 있는가.
 *
 * 같은 참조 열둘을 프레임 셋과 넷에 같은 걸음으로 흘리고, 두 쪽의 누적 폴트를
 * 경주 선 위의 말로 나란히 쌓는다. 넷 쪽이 뒤처졌다가 따라잡고 마지막 참조에서 앞지른다.
 * 값은 예로 정한 것이다.
 */
export const beladyAnomalyFacet: FacetJson = {
  id: 'facet:beladyAnomaly',
  title: {
    en: "Belady's anomaly",
    ko: '벨레이디의 역설',
    ja: 'ビレイディの異常',
    zh: '贝莱迪异常',
    ar: 'شذوذ بيلادي',
    es: 'Anomalía de Belady',
    fr: 'Anomalie de Belady',
    hi: 'बेलाडी की विसंगति',
    id: 'Anomali Belady',
    pt: 'Anomalia de Belady',
  },
  description: {
    en: 'The same references go to FIFO with 3 frames and with 4 frames. The side with more frames ends with more faults.',
    ko: '같은 참조를 FIFO 프레임 셋과 넷에 흘린다. 프레임이 많은 쪽이 폴트를 더 많이 내며 끝난다.',
    ja: '同じ参照を FIFO のフレーム 3 つと 4 つに流す。フレームが多い側のほうがフォールトが多くなって終わる。',
    zh: '把相同的访问序列交给 3 个帧和 4 个帧的 FIFO。帧更多的一方最后缺页更多。',
    ar: 'تمر المراجع نفسها إلى FIFO بثلاثة إطارات وبأربعة. الجانب ذو الإطارات الأكثر ينتهي بأخطاء صفحات أكثر.',
    es: 'Las mismas referencias pasan por FIFO con 3 marcos y con 4. El lado con más marcos termina con más fallos.',
    fr: 'Les mêmes références passent par FIFO avec 3 cadres et avec 4. Le côté qui a plus de cadres finit avec plus de défauts.',
    hi: 'वही संदर्भ 3 फ़्रेम और 4 फ़्रेम वाले FIFO में जाते हैं। ज़्यादा फ़्रेम वाला पक्ष अंत में ज़्यादा फ़ॉल्ट करता है।',
    id: 'Referensi yang sama masuk ke FIFO dengan 3 bingkai dan 4 bingkai. Sisi dengan bingkai lebih banyak berakhir dengan kesalahan lebih banyak.',
    pt: 'As mesmas referências passam por FIFO com 3 quadros e com 4. O lado com mais quadros termina com mais faltas.',
  },
  algorithm: 'module:beladyAnomaly',
  scene: 'module:beladyAnomalyScene',
  initialData: {
    type: 'belady-anomaly',
    refs: [1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5],
    frameCounts: [3, 4],
    stepMs: 1100,
  },
  shuffleOnReset: false,
  messages: {
    'label.refs': {
      en: 'References',
      ko: '참조',
      ja: '参照',
      zh: '访问',
      ar: 'المراجع',
      es: 'Referencias',
      fr: 'Références',
      hi: 'संदर्भ',
      id: 'Referensi',
      pt: 'Referências',
    },
    'label.side': {
      en: '{n}-frame side',
      ko: '프레임 {n}칸',
      ja: 'フレーム {n} 個',
      zh: '{n} 个帧',
      ar: 'جانب الإطارات: {n}',
      es: 'Marcos: {n}',
      fr: 'Cadres : {n}',
      hi: 'फ़्रेम: {n}',
      id: 'Bingkai: {n}',
      pt: 'Quadros: {n}',
    },
    'label.faults': {
      en: 'Faults',
      ko: '폴트',
      ja: 'フォールト',
      zh: '缺页',
      ar: 'أخطاء الصفحات',
      es: 'Fallos',
      fr: 'Défauts',
      hi: 'फ़ॉल्ट',
      id: 'Kesalahan',
      pt: 'Faltas',
    },
    'label.nextOut': {
      en: 'next out',
      ko: '다음에 나감',
      ja: '次に出る',
      zh: '下一个换出',
      ar: 'التالي للخروج',
      es: 'sale después',
      fr: 'sort ensuite',
      hi: 'अगला बाहर',
      id: 'keluar berikutnya',
      pt: 'sai a seguir',
    },
    'caption.start': {
      en: 'Same references go to both sides. Both start empty.',
      ko: '같은 참조를 두 쪽에 흘린다. 둘 다 비어 있다.',
      ja: '同じ参照を両側に流す。どちらも空から始まる。',
      zh: '相同的访问送往两边。两边一开始都是空的。',
      ar: 'تذهب المراجع نفسها إلى الجانبين. يبدأ كلاهما فارغًا.',
      es: 'Las mismas referencias van a ambos lados. Los dos empiezan vacíos.',
      fr: 'Les mêmes références vont des deux côtés. Les deux commencent vides.',
      hi: 'वही संदर्भ दोनों पक्षों में जाते हैं। दोनों खाली से शुरू होते हैं।',
      id: 'Referensi yang sama masuk ke kedua sisi. Keduanya mulai kosong.',
      pt: 'As mesmas referências vão para os dois lados. Ambos começam vazios.',
    },
    'caption.bothFault': {
      en: 'Page {page}: fault on both sides.',
      ko: '페이지 {page}: 두 쪽 모두 폴트.',
      ja: 'ページ {page}: 両側ともフォールト。',
      zh: '页 {page}：两边都缺页。',
      ar: 'الصفحة {page}: خطأ صفحة في الجانبين.',
      es: 'Página {page}: fallo en ambos lados.',
      fr: 'Page {page} : défaut des deux côtés.',
      hi: 'पेज {page}: दोनों पक्षों में फ़ॉल्ट।',
      id: 'Halaman {page}: kesalahan di kedua sisi.',
      pt: 'Página {page}: falta nos dois lados.',
    },
    'caption.bothHit': {
      en: 'Page {page}: hit on both sides.',
      ko: '페이지 {page}: 두 쪽 모두 적중.',
      ja: 'ページ {page}: 両側ともヒット。',
      zh: '页 {page}：两边都命中。',
      ar: 'الصفحة {page}: إصابة في الجانبين.',
      es: 'Página {page}: acierto en ambos lados.',
      fr: 'Page {page} : succès des deux côtés.',
      hi: 'पेज {page}: दोनों पक्षों में हिट।',
      id: 'Halaman {page}: kena di kedua sisi.',
      pt: 'Página {page}: acerto nos dois lados.',
    },
    'caption.hitFault': {
      en: 'Page {page}: hit on the {a}-frame side, fault on the {b}-frame side.',
      ko: '페이지 {page}: {a}칸 쪽 적중, {b}칸 쪽 폴트.',
      ja: 'ページ {page}: {a} 個側はヒット、{b} 個側はフォールト。',
      zh: '页 {page}：{a} 帧一方命中，{b} 帧一方缺页。',
      ar: 'الصفحة {page}: إصابة في جانب الإطارات {a}، وخطأ صفحة في جانب الإطارات {b}.',
      es: 'Página {page}: acierto en el lado de marcos {a}, fallo en el lado de marcos {b}.',
      fr: 'Page {page} : succès côté cadres {a}, défaut côté cadres {b}.',
      hi: 'पेज {page}: फ़्रेम {a} वाले पक्ष में हिट, फ़्रेम {b} वाले पक्ष में फ़ॉल्ट।',
      id: 'Halaman {page}: kena di sisi bingkai {a}, kesalahan di sisi bingkai {b}.',
      pt: 'Página {page}: acerto no lado de quadros {a}, falta no lado de quadros {b}.',
    },
    'caption.faultHit': {
      en: 'Page {page}: fault on the {a}-frame side, hit on the {b}-frame side.',
      ko: '페이지 {page}: {a}칸 쪽 폴트, {b}칸 쪽 적중.',
      ja: 'ページ {page}: {a} 個側はフォールト、{b} 個側はヒット。',
      zh: '页 {page}：{a} 帧一方缺页，{b} 帧一方命中。',
      ar: 'الصفحة {page}: خطأ صفحة في جانب الإطارات {a}، وإصابة في جانب الإطارات {b}.',
      es: 'Página {page}: fallo en el lado de marcos {a}, acierto en el lado de marcos {b}.',
      fr: 'Page {page} : défaut côté cadres {a}, succès côté cadres {b}.',
      hi: 'पेज {page}: फ़्रेम {a} वाले पक्ष में फ़ॉल्ट, फ़्रेम {b} वाले पक्ष में हिट।',
      id: 'Halaman {page}: kesalahan di sisi bingkai {a}, kena di sisi bingkai {b}.',
      pt: 'Página {page}: falta no lado de quadros {a}, acerto no lado de quadros {b}.',
    },
    'caption.fewer': {
      en: 'Fewer faults on the {b}-frame side. Gap: {n}.',
      ko: '{b}칸 쪽 폴트가 더 적다. 차이 {n}.',
      ja: '{b} 個側のフォールトが少ない。差: {n}。',
      zh: '{b} 帧一方缺页更少。差距：{n}。',
      ar: 'أخطاء أقل في جانب الإطارات {b}. الفرق: {n}.',
      es: 'Menos fallos en el lado de marcos {b}. Diferencia: {n}.',
      fr: 'Moins de défauts côté cadres {b}. Écart : {n}.',
      hi: 'फ़्रेम {b} वाले पक्ष में फ़ॉल्ट कम। अंतर: {n}।',
      id: 'Kesalahan lebih sedikit di sisi bingkai {b}. Selisih: {n}.',
      pt: 'Menos faltas no lado de quadros {b}. Diferença: {n}.',
    },
    'caption.catchUp': {
      en: 'The {b}-frame side catches up. Faults on each: {n}.',
      ko: '{b}칸 쪽이 따라잡았다. 두 쪽 폴트 {n}.',
      ja: '{b} 個側が追いついた。両側のフォールト: {n}。',
      zh: '{b} 帧一方追平了。两边缺页：{n}。',
      ar: 'جانب الإطارات {b} يلحق. أخطاء كل جانب: {n}.',
      es: 'El lado de marcos {b} alcanza al otro. Fallos en cada uno: {n}.',
      fr: 'Le côté cadres {b} rattrape l’autre. Défauts de chaque côté : {n}.',
      hi: 'फ़्रेम {b} वाला पक्ष बराबरी पर आ गया। हर पक्ष के फ़ॉल्ट: {n}।',
      id: 'Sisi bingkai {b} menyusul. Kesalahan tiap sisi: {n}.',
      pt: 'O lado de quadros {b} alcança o outro. Faltas em cada um: {n}.',
    },
    'caption.tied': {
      en: 'Faults on each: {n}.',
      ko: '두 쪽 폴트 {n}.',
      ja: '両側のフォールト: {n}。',
      zh: '两边缺页：{n}。',
      ar: 'أخطاء كل جانب: {n}.',
      es: 'Fallos en cada lado: {n}.',
      fr: 'Défauts de chaque côté : {n}.',
      hi: 'हर पक्ष के फ़ॉल्ट: {n}।',
      id: 'Kesalahan tiap sisi: {n}.',
      pt: 'Faltas em cada lado: {n}.',
    },
    'caption.overtake': {
      en: 'The {b}-frame side overtakes — more faults than the {a}-frame side. Gap: {n}.',
      ko: '{b}칸 쪽이 앞질렀다 — {a}칸 쪽보다 폴트가 많다. 차이 {n}.',
      ja: '{b} 個側が追い越した — {a} 個側よりフォールトが多い。差: {n}。',
      zh: '{b} 帧一方反超 — 缺页比 {a} 帧一方多。差距：{n}。',
      ar: 'جانب الإطارات {b} يتجاوز — أخطاء أكثر من جانب الإطارات {a}. الفرق: {n}.',
      es: 'El lado de marcos {b} adelanta — más fallos que el lado de marcos {a}. Diferencia: {n}.',
      fr: 'Le côté cadres {b} dépasse — plus de défauts que le côté cadres {a}. Écart : {n}.',
      hi: 'फ़्रेम {b} वाला पक्ष आगे निकल गया — फ़्रेम {a} वाले पक्ष से ज़्यादा फ़ॉल्ट। अंतर: {n}।',
      id: 'Sisi bingkai {b} menyalip — kesalahan lebih banyak daripada sisi bingkai {a}. Selisih: {n}.',
      pt: 'O lado de quadros {b} ultrapassa — mais faltas que o lado de quadros {a}. Diferença: {n}.',
    },
    'caption.more': {
      en: 'More faults on the {b}-frame side. Gap: {n}.',
      ko: '{b}칸 쪽 폴트가 더 많다. 차이 {n}.',
      ja: '{b} 個側のフォールトが多い。差: {n}。',
      zh: '{b} 帧一方缺页更多。差距：{n}。',
      ar: 'أخطاء أكثر في جانب الإطارات {b}. الفرق: {n}.',
      es: 'Más fallos en el lado de marcos {b}. Diferencia: {n}.',
      fr: 'Plus de défauts côté cadres {b}. Écart : {n}.',
      hi: 'फ़्रेम {b} वाले पक्ष में फ़ॉल्ट ज़्यादा। अंतर: {n}।',
      id: 'Kesalahan lebih banyak di sisi bingkai {b}. Selisih: {n}.',
      pt: 'Mais faltas no lado de quadros {b}. Diferença: {n}.',
    },
  },
  blocks: {
    stage: { type: 'belady-anomaly-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
