/**
 * @piece
 * 질문: 같은 답 조각을 맥락의 어디에 두느냐가 왜 문제인가?
 *
 * 답이 든 조각 하나를 맥락의 맨 앞 · 한가운데 · 맨 끝에 차례로 끼운다. 셈하는 것은
 * 자리와 가까운 끝까지 거리뿐이고, 흐려짐은 그 거리의 단조 함수로 그린 **예로 보인 경향**
 * (Liu 외 2023, "Lost in the Middle") 이다. 백분율 · 정답률 같은 수는 띄우지 않는다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const lostInTheMiddleFacet: FacetJson = {
  id: 'facet:lostInTheMiddle',
  title: {
    en: 'Lost in the middle',
    ko: '가운데 흘림',
    ja: '中間での見落とし',
    zh: '迷失在中间',
    ar: 'الضياع في المنتصف',
    es: 'Perdido en el medio',
    fr: 'Perdu au milieu',
    hi: 'बीच में खो जाना',
    id: 'Hilang di tengah',
    pt: 'Perdido no meio',
  },
  description: {
    en: 'The same answer chunk moves from the front of the context to the middle and on to the end. Models tend to notice the ends and miss what sits between them.',
    ko: '같은 답 조각이 맥락의 맨 앞에서 한가운데로, 다시 맨 끝으로 옮긴다. 모형은 앞뒤는 잘 보고 그 사이의 것은 놓치기 쉽다.',
    ja: '同じ答えのチャンクが、コンテキストの先頭から真ん中へ、さらに末尾へと移る。モデルは両端をよく拾い、その間にあるものを見落としやすい。',
    zh: '同一个答案片段从上下文的开头移到正中间，再移到末尾。模型往往注意到两端，却容易漏掉夹在中间的内容。',
    ar: 'ينتقل مقطع الإجابة نفسه من بداية السياق إلى منتصفه ثم إلى نهايته. تميل النماذج إلى ملاحظة الطرفين وتفويت ما بينهما.',
    es: 'El mismo fragmento con la respuesta pasa del principio del contexto al centro y luego al final. Los modelos tienden a fijarse en los extremos y a pasar por alto lo que queda entre ellos.',
    fr: 'Le même fragment porteur de la réponse passe du début du contexte au milieu, puis à la fin. Les modèles ont tendance à remarquer les extrémités et à manquer ce qui se trouve entre les deux.',
    hi: 'उत्तर वाला वही खंड संदर्भ की शुरुआत से बीच में और फिर अंत में जाता है। मॉडल अक्सर दोनों सिरों पर ध्यान देते हैं और बीच की चीज़ चूक जाते हैं।',
    id: 'Potongan jawaban yang sama berpindah dari awal konteks ke tengah, lalu ke akhir. Model cenderung memperhatikan kedua ujung dan melewatkan yang ada di antaranya.',
    pt: 'O mesmo trecho com a resposta passa do início do contexto para o meio e depois para o fim. Os modelos tendem a notar as pontas e a deixar escapar o que fica entre elas.',
  },
  algorithm: 'module:lostInTheMiddle',
  scene: 'module:lostInTheMiddleScene',
  initialData: {
    type: 'lost-in-the-middle',
    stepMs: 1400,
    question: 'When did the Golden Gate Bridge open?',
    chunks: [
      { id: 'span', text: 'Its main span is 1,280 meters long.' },
      { id: 'towers', text: 'Its towers rise 227 meters above the water.' },
      { id: 'color', text: 'The bridge is painted a color called International Orange.' },
      { id: 'links', text: 'It links San Francisco to Marin County.' },
      { id: 'opened', text: 'The bridge opened in 1937.' },
      { id: 'engineer', text: 'Joseph Strauss was the chief engineer.' },
      { id: 'fog', text: 'Fog often hides the bridge in summer.' },
    ],
    answer: 'opened',
    rest: ['span', 'towers', 'color', 'links', 'engineer', 'fog'],
    positions: [1, 4, 7],
  },
  shuffleOnReset: false,
  messages: {
    'label.question': {
      en: 'Question',
      ko: '질문',
      ja: '質問',
      zh: '问题',
      ar: 'السؤال',
      es: 'Pregunta',
      fr: 'Question',
      hi: 'प्रश्न',
      id: 'Pertanyaan',
      pt: 'Pergunta',
    },
    'label.front': {
      en: 'front of context',
      ko: '맥락의 앞',
      ja: 'コンテキストの先頭',
      zh: '上下文开头',
      ar: 'بداية السياق',
      es: 'inicio del contexto',
      fr: 'début du contexte',
      hi: 'संदर्भ की शुरुआत',
      id: 'awal konteks',
      pt: 'início do contexto',
    },
    'label.end': {
      en: 'end of context',
      ko: '맥락의 끝',
      ja: 'コンテキストの末尾',
      zh: '上下文末尾',
      ar: 'نهاية السياق',
      es: 'final del contexto',
      fr: 'fin du contexte',
      hi: 'संदर्भ का अंत',
      id: 'akhir konteks',
      pt: 'fim do contexto',
    },
    'label.dist': {
      en: 'distance {d}',
      ko: '거리 {d}',
      ja: '距離 {d}',
      zh: '距离 {d}',
      ar: 'المسافة {d}',
      es: 'distancia {d}',
      fr: 'distance {d}',
      hi: 'दूरी {d}',
      id: 'jarak {d}',
      pt: 'distância {d}',
    },
    'caption.ready': {
      en: '{k} chunks sit in the context. The answer chunk is not placed yet.',
      ko: '맥락에 놓인 조각 {k} 개. 답 조각은 아직 끼우지 않았다.',
      ja: 'コンテキストにあるチャンクは {k} 個。答えのチャンクはまだ入れていない。',
      zh: '上下文中有 {k} 个片段。答案片段还没有放进去。',
      ar: 'في السياق {k} مقاطع. لم يوضع مقطع الإجابة بعد.',
      es: 'Hay {k} fragmentos en el contexto. El fragmento con la respuesta aún no está colocado.',
      fr: '{k} fragments sont dans le contexte. Le fragment de la réponse n’est pas encore placé.',
      hi: 'संदर्भ में {k} खंड हैं। उत्तर वाला खंड अभी रखा नहीं गया है।',
      id: 'Ada {k} potongan di konteks. Potongan jawaban belum ditempatkan.',
      pt: 'Há {k} trechos no contexto. O trecho com a resposta ainda não foi colocado.',
    },
    'caption.place': {
      en: 'Answer chunk at slot {p} of {n}. Distance to the nearer end: {d}.',
      ko: '답 조각의 자리: {n} 칸 중 {p}번째. 가까운 끝까지 거리: {d}.',
      ja: '答えのチャンクの位置: {n} 枠中 {p} 番目。近いほうの端までの距離: {d}。',
      zh: '答案片段位于 {n} 个位置中的第 {p} 个。到较近一端的距离：{d}。',
      ar: 'مقطع الإجابة في الخانة {p} من {n}. المسافة إلى الطرف الأقرب: {d}.',
      es: 'Fragmento con la respuesta en la posición {p} de {n}. Distancia al extremo más cercano: {d}.',
      fr: 'Fragment de la réponse à la position {p} sur {n}. Distance à l’extrémité la plus proche : {d}.',
      hi: 'उत्तर वाला खंड {n} में से स्थान {p} पर। निकटतम सिरे तक दूरी: {d}।',
      id: 'Potongan jawaban di posisi {p} dari {n}. Jarak ke ujung terdekat: {d}.',
      pt: 'Trecho com a resposta na posição {p} de {n}. Distância até a ponta mais próxima: {d}.',
    },
    'caption.edge': {
      en: 'At an end of the context — a spot models tend to catch.',
      ko: '맥락의 끝자리 — 모형이 잘 잡아내는 경향이 있는 자리.',
      ja: 'コンテキストの端 — モデルが拾いやすい位置。',
      zh: '位于上下文的一端 —— 模型往往能注意到的位置。',
      ar: 'عند طرف السياق — موضع تميل النماذج إلى التقاطه.',
      es: 'En un extremo del contexto: un sitio que los modelos tienden a captar.',
      fr: 'À une extrémité du contexte — un endroit que les modèles ont tendance à repérer.',
      hi: 'संदर्भ के एक सिरे पर — ऐसी जगह जिसे मॉडल अक्सर पकड़ लेते हैं।',
      id: 'Di ujung konteks — posisi yang cenderung ditangkap model.',
      pt: 'Numa ponta do contexto — um lugar que os modelos tendem a captar.',
    },
    'caption.middle': {
      en: 'Toward the middle — a spot models tend to miss.',
      ko: '가운데 쪽 — 모형이 놓치기 쉬운 자리.',
      ja: '真ん中寄り — モデルが見落としやすい位置。',
      zh: '靠近中间 —— 模型容易漏掉的位置。',
      ar: 'نحو المنتصف — موضع تميل النماذج إلى تفويته.',
      es: 'Hacia el centro: un sitio que los modelos tienden a pasar por alto.',
      fr: 'Vers le milieu — un endroit que les modèles ont tendance à manquer.',
      hi: 'बीच की ओर — ऐसी जगह जिसे मॉडल अक्सर चूक जाते हैं।',
      id: 'Menuju tengah — posisi yang cenderung terlewat oleh model.',
      pt: 'Rumo ao meio — um lugar que os modelos tendem a deixar escapar.',
    },
    'caption.settle': {
      en: 'The same words in all {k} slots — only the distance to an end changed.',
      ko: '끼워 본 자리 {k} 곳 모두 같은 글 — 바뀐 것은 끝까지의 거리뿐.',
      ja: '入れた {k} か所すべてで同じ文 — 変わったのは端までの距離だけ。',
      zh: '放过的 {k} 个位置里文字完全相同 —— 变的只有到一端的距离。',
      ar: 'الكلمات نفسها في المواضع الـ{k} كلها — لم يتغير إلا البعد عن الطرف.',
      es: 'Las mismas palabras en las {k} posiciones: solo cambió la distancia a un extremo.',
      fr: 'Les mêmes mots aux {k} positions — seule la distance à une extrémité a changé.',
      hi: 'सभी {k} स्थानों पर वही शब्द — बदली केवल सिरे तक की दूरी।',
      id: 'Kata-kata yang sama di semua {k} posisi — hanya jarak ke ujung yang berubah.',
      pt: 'As mesmas palavras nas {k} posições — só mudou a distância até uma ponta.',
    },
  },
  blocks: {
    stage: { type: 'lost-in-the-middle-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
