import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * LEFT JOIN 은 짝이 없는 왼쪽 줄을 어떻게 하는가.
 *
 * @notation native — 화면의 질의는 SQL 그대로다. SQL 문이 곧 주장의 소재라 가상 표기로 옮기지 않는다.
 *
 * 표 이름 · 열 이름 · 줄의 값은 SQL 식별자와 한 화면에 짝지어 뜨는 자료라 번역하지 않는다.
 * 문안으로 빼는 것은 역할 이름(결과 · 짝 없음)과 캡션뿐이다.
 */
export const keepUnmatchedFacet: FacetJson = {
  id: 'facet:keepUnmatched',
  title: {
    en: 'Keeping rows with no match',
    ko: '짝 없는 줄도 남긴다',
    ja: '相手のない行も残す',
    zh: '保留没有匹配的行',
    ar: 'الإبقاء على الصفوف التي لا مطابق لها',
    es: 'Conservar las filas sin pareja',
    fr: 'Garder les lignes sans correspondance',
    hi: 'बिना मेल वाली पंक्तियाँ भी रहती हैं',
    id: 'Baris tanpa pasangan tetap disimpan',
    pt: 'Manter as linhas sem correspondência',
  },
  description: {
    en: 'What does a LEFT JOIN do with a left row that has no match?',
    ko: 'LEFT JOIN 은 짝이 없는 왼쪽 줄을 어떻게 하는가?',
    ja: 'LEFT JOIN は相手のない左側の行をどう扱うのか?',
    zh: 'LEFT JOIN 如何处理没有匹配的左侧行?',
    ar: 'ماذا يفعل LEFT JOIN بصف أيسر لا مطابق له؟',
    es: '¿Qué hace un LEFT JOIN con una fila izquierda que no tiene pareja?',
    fr: 'Que fait un LEFT JOIN d’une ligne de gauche sans correspondance ?',
    hi: 'LEFT JOIN बिना मेल वाली बाईं पंक्ति के साथ क्या करता है?',
    id: 'Apa yang dilakukan LEFT JOIN pada baris kiri yang tidak punya pasangan?',
    pt: 'O que um LEFT JOIN faz com uma linha da esquerda sem correspondência?',
  },
  algorithm: 'module:keepUnmatched',
  scene: 'module:keepUnmatchedScene',
  initialData: {
    type: 'keep-unmatched',
    stepMs: 1800,
    sql: [
      'SELECT c.name, o.item',
      'FROM customer c',
      'LEFT JOIN orders o ON o.cust_id = c.id;',
    ],
    left: {
      name: 'customer',
      columns: ['id', 'name'],
      rows: [
        [1, 'Ann'],
        [2, 'Bo'],
        [3, 'Cy'],
        [4, 'Di'],
        [5, 'Eve'],
      ],
    },
    right: {
      name: 'orders',
      columns: ['id', 'cust_id', 'item'],
      rows: [
        [101, 1, 'book'],
        [102, 3, 'lamp'],
        [103, 5, 'cup'],
      ],
    },
    on: { left: 'id', right: 'cust_id' },
    select: [
      { side: 'left', column: 'name' },
      { side: 'right', column: 'item' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.result': {
      en: 'Result',
      ko: '결과',
      ja: '結果',
      zh: '结果',
      ar: 'النتيجة',
      es: 'Resultado',
      fr: 'Résultat',
      hi: 'परिणाम',
      id: 'Hasil',
      pt: 'Resultado',
    },
    'label.unmatched': {
      en: 'No match',
      ko: '짝 없음',
      ja: '相手なし',
      zh: '无匹配',
      ar: 'بلا مطابق',
      es: 'Sin pareja',
      fr: 'Sans correspondance',
      hi: 'कोई मेल नहीं',
      id: 'Tanpa pasangan',
      pt: 'Sem par',
    },
    'caption.start': {
      en: 'Left table: {left} · right table: {right}',
      ko: '왼쪽 표: {left} · 오른쪽 표: {right}',
      ja: '左の表: {left} · 右の表: {right}',
      zh: '左表: {left} · 右表: {right}',
      ar: 'الجدول الأيسر: {left} · الجدول الأيمن: {right}',
      es: 'Tabla izquierda: {left} · tabla derecha: {right}',
      fr: 'Table de gauche : {left} · table de droite : {right}',
      hi: 'बाईं तालिका: {left} · दाईं तालिका: {right}',
      id: 'Tabel kiri: {left} · tabel kanan: {right}',
      pt: 'Tabela da esquerda: {left} · tabela da direita: {right}',
    },
    'caption.matched': {
      en: 'Rows with a match are joined. Result rows: {n}',
      ko: '짝이 맞는 줄이 이어졌다. 결과 줄: {n}',
      ja: '相手のある行がつながった。結果の行: {n}',
      zh: '有匹配的行已连接。结果行数: {n}',
      ar: 'رُبطت الصفوف التي لها مطابق. صفوف النتيجة: {n}',
      es: 'Las filas con pareja se unen. Filas del resultado: {n}',
      fr: 'Les lignes qui correspondent sont jointes. Lignes du résultat : {n}',
      hi: 'मेल वाली पंक्तियाँ जुड़ गईं। परिणाम की पंक्तियाँ: {n}',
      id: 'Baris yang punya pasangan digabung. Baris hasil: {n}',
      pt: 'As linhas com correspondência são unidas. Linhas do resultado: {n}',
    },
    'caption.innerStop': {
      en: 'An INNER JOIN would stop here.',
      ko: 'INNER JOIN 이라면 여기서 끝난다.',
      ja: 'INNER JOIN ならここで終わる。',
      zh: '如果是 INNER JOIN,到这里就结束了。',
      ar: 'لو كان INNER JOIN لتوقف هنا.',
      es: 'Un INNER JOIN terminaría aquí.',
      fr: 'Un INNER JOIN s’arrêterait ici.',
      hi: 'INNER JOIN यहीं रुक जाता।',
      id: 'INNER JOIN akan berhenti di sini.',
      pt: 'Um INNER JOIN pararia aqui.',
    },
    'caption.unmatched': {
      en: 'Left rows with no match in {right}: {n}',
      ko: '{right} 에 짝이 없는 왼쪽 줄: {n}',
      ja: '{right} に相手のない左の行: {n}',
      zh: '在 {right} 中没有匹配的左侧行: {n}',
      ar: 'صفوف يسرى بلا مطابق في {right}: {n}',
      es: 'Filas izquierdas sin pareja en {right}: {n}',
      fr: 'Lignes de gauche sans correspondance dans {right} : {n}',
      hi: '{right} में बिना मेल वाली बाईं पंक्तियाँ: {n}',
      id: 'Baris kiri tanpa pasangan di {right}: {n}',
      pt: 'Linhas da esquerda sem correspondência em {right}: {n}',
    },
    'caption.innerDrop': {
      en: 'An INNER JOIN would drop them.',
      ko: 'INNER JOIN 이라면 이 줄은 버려진다.',
      ja: 'INNER JOIN ならこれらの行は捨てられる。',
      zh: '如果是 INNER JOIN,这些行会被丢弃。',
      ar: 'لو كان INNER JOIN لأُسقطت هذه الصفوف.',
      es: 'Un INNER JOIN las descartaría.',
      fr: 'Un INNER JOIN les écarterait.',
      hi: 'INNER JOIN इन्हें छोड़ देता।',
      id: 'INNER JOIN akan membuangnya.',
      pt: 'Um INNER JOIN as descartaria.',
    },
    'caption.kept': {
      en: 'LEFT JOIN keeps them — their empty cells are filled with NULL.',
      ko: 'LEFT JOIN 은 이 줄도 남긴다 — 비어 있는 칸은 NULL 로 채워진다.',
      ja: 'LEFT JOIN はこれらの行も残す — 空いた欄は NULL で埋まる。',
      zh: 'LEFT JOIN 保留这些行 — 空着的格子用 NULL 填上。',
      ar: 'يُبقي LEFT JOIN عليها — وتُملأ خاناتها الفارغة بـ NULL.',
      es: 'LEFT JOIN las conserva: sus celdas vacías se rellenan con NULL.',
      fr: 'LEFT JOIN les garde : leurs cases vides sont remplies de NULL.',
      hi: 'LEFT JOIN इन्हें रखता है — इनके खाली खाने NULL से भरते हैं।',
      id: 'LEFT JOIN menyimpannya — sel kosongnya diisi NULL.',
      pt: 'O LEFT JOIN as mantém — as células vazias são preenchidas com NULL.',
    },
    'caption.count': {
      en: 'Result rows: {n} · kept without a match: {k}',
      ko: '결과 줄: {n} · 짝 없이 남은 줄: {k}',
      ja: '結果の行: {n} · 相手なしで残った行: {k}',
      zh: '结果行数: {n} · 无匹配而保留的行: {k}',
      ar: 'صفوف النتيجة: {n} · باقية بلا مطابق: {k}',
      es: 'Filas del resultado: {n} · conservadas sin pareja: {k}',
      fr: 'Lignes du résultat : {n} · gardées sans correspondance : {k}',
      hi: 'परिणाम की पंक्तियाँ: {n} · बिना मेल के रखी गईं: {k}',
      id: 'Baris hasil: {n} · disimpan tanpa pasangan: {k}',
      pt: 'Linhas do resultado: {n} · mantidas sem correspondência: {k}',
    },
  },
  blocks: {
    stage: { type: 'keep-unmatched-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
