/**
 * semantic-versioning — 선언.
 *
 * 데이터는 구조뿐이다 — 꾸러미 이름 · 깔린 버전 · 바뀜 식별자 · 받는 쪽의 범위와 잠금 · 잠금 줄.
 * 새 버전 · 두 끝 · 판정 · 깔린 것은 알고리즘이 셈한다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { SemanticVersioningData } from './algorithm.js';

const initialData: SemanticVersioningData = {
  type: 'semantic-versioning',
  stepMs: 1300,
  motionMs: 400,
  packageName: 'units',
  installed: '1.4.2',
  changes: ['fix', 'feature', 'breaking'],
  receivers: [
    { range: '^1.4.2', locked: false },
    { range: '~1.4.2', locked: false },
    { range: '^1.4.2', locked: true },
  ],
  lockLine: 'units 1.4.2',
  start: { change: 1, receiver: 0 },
};

export const semanticVersioningFacet: FacetJson = {
  id: 'facet:semanticVersioning',
  title: {
    en: 'Version ranges and locks',
    ko: '버전 범위와 잠금',
    ja: 'バージョン範囲とロック',
    zh: '版本范围与锁定',
    ar: 'نطاقات الإصدارات والقفل',
    es: 'Rangos de versión y bloqueo',
    fr: 'Plages de versions et verrouillage',
    hi: 'संस्करण सीमाएँ और लॉक',
    id: 'Rentang versi dan penguncian',
    pt: 'Intervalos de versão e bloqueio',
  },
  description: {
    en: 'The publisher picks which of the three digits to raise by the weight of the change; the receiver decides with a range how far it will follow; a lock file holds even a newer version inside the range.',
    ko: '내보내는 쪽은 바뀜의 무게로 세 자리 가운데 올릴 자리를 고르고, 받는 쪽은 범위로 어디까지 받을지 정하며, 잠금 파일은 범위 안의 새것도 막는다.',
    ja: '公開する側は変更の重さで三つの桁のどれを上げるかを選び、受け取る側は範囲でどこまで受け入れるかを決め、ロックファイルは範囲内の新しい版さえ止める。',
    zh: '发布方按改动的轻重选择三位中要升的一位，接收方用范围决定接受到哪里，锁文件连范围内的新版本也挡住。',
    ar: 'يختار الناشر أيّ الأرقام الثلاثة يرفع حسب ثقل التغيير، ويحدّد المستقبِل بنطاقٍ إلى أيّ حدّ يتبع، وملف القفل يمنع حتى الإصدار الأحدث داخل النطاق.',
    es: 'Quien publica elige cuál de los tres números subir según el peso del cambio; quien recibe decide con un rango hasta dónde acepta; el archivo de bloqueo frena incluso una versión nueva dentro del rango.',
    fr: "L'éditeur choisit lequel des trois chiffres monter selon le poids du changement ; le receveur décide par une plage jusqu'où il suit ; le fichier de verrouillage retient même une version plus récente dans la plage.",
    hi: 'प्रकाशक बदलाव के वज़न से तय करता है कि तीन अंकों में से कौन-सा बढ़े; प्राप्तकर्ता सीमा से तय करता है कि कहाँ तक ले; लॉक फ़ाइल सीमा के भीतर के नए संस्करण को भी रोक देती है।',
    id: 'Penerbit memilih angka mana dari tiga yang dinaikkan menurut bobot perubahan; penerima menentukan dengan rentang sampai mana ia ikut; berkas kunci menahan bahkan versi baru di dalam rentang.',
    pt: 'Quem publica escolhe qual dos três números subir pelo peso da mudança; quem recebe decide com um intervalo até onde aceita; o arquivo de bloqueio segura até uma versão nova dentro do intervalo.',
  },
  algorithm: 'module:semanticVersioning',
  projector: 'module:semanticVersioningProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'semantic-versioning-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'change',
          name: 'change',
          label: {
            en: 'Published change',
            ko: '내보낸 바뀜',
            ja: '公開した変更',
            zh: '发布的改动',
            ar: 'التغيير المنشور',
            es: 'Cambio publicado',
            fr: 'Changement publié',
            hi: 'प्रकाशित बदलाव',
            id: 'Perubahan terbit',
            pt: 'Mudança publicada',
          },
          segments: [
            {
              value: 0,
              label: { en: 'Fix', ko: '고침', ja: '修正', zh: '修复', ar: 'إصلاح', es: 'Arreglo', fr: 'Correctif', hi: 'सुधार', id: 'Perbaikan', pt: 'Correção' },
            },
            {
              value: 1,
              default: true,
              label: { en: 'New feature', ko: '기능 추가', ja: '機能追加', zh: '新功能', ar: 'ميزة جديدة', es: 'Función nueva', fr: 'Nouvelle fonction', hi: 'नई सुविधा', id: 'Fitur baru', pt: 'Recurso novo' },
            },
            {
              value: 2,
              label: { en: 'Breaking change', ko: '호환 깨짐', ja: '互換性の破壊', zh: '不兼容改动', ar: 'تغيير كاسر', es: 'Cambio incompatible', fr: 'Rupture', hi: 'असंगत बदलाव', id: 'Perubahan pemutus', pt: 'Quebra de compatibilidade' },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'receiver',
          name: 'receiver',
          label: {
            en: 'Receiver',
            ko: '받는 쪽',
            ja: '受け取る側',
            zh: '接收方',
            ar: 'المستقبِل',
            es: 'Receptor',
            fr: 'Receveur',
            hi: 'प्राप्तकर्ता',
            id: 'Penerima',
            pt: 'Receptor',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: { en: '^ range', ko: '^ 범위', ja: '^ 範囲', zh: '^ 范围', ar: 'نطاق ^', es: 'rango ^', fr: 'plage ^', hi: '^ सीमा', id: 'rentang ^', pt: 'intervalo ^' },
            },
            {
              value: 1,
              label: { en: '~ range', ko: '~ 범위', ja: '~ 範囲', zh: '~ 范围', ar: 'نطاق ~', es: 'rango ~', fr: 'plage ~', hi: '~ सीमा', id: 'rentang ~', pt: 'intervalo ~' },
            },
            {
              value: 2,
              label: { en: '^ + lock', ko: '^ + 잠금', ja: '^ + ロック', zh: '^ + 锁定', ar: '^ + قفل', es: '^ + bloqueo', fr: '^ + verrou', hi: '^ + लॉक', id: '^ + kunci', pt: '^ + bloqueio' },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'accepted',
          label: {
            en: 'Accepted',
            ko: '받음',
            ja: '受け入れ',
            zh: '已接受',
            ar: 'مقبول',
            es: 'Aceptada',
            fr: 'Acceptée',
            hi: 'स्वीकार',
            id: 'Diterima',
            pt: 'Aceita',
          },
          initial: 0,
        },
        {
          name: 'zeroed-digits',
          label: {
            en: 'Digits reset to 0',
            ko: '0 으로 떨어진 자리',
            ja: '0 に戻った桁',
            zh: '归零的位',
            ar: 'أرقام عادت إلى 0',
            es: 'Dígitos a 0',
            fr: 'Chiffres remis à 0',
            hi: '0 हुए अंक',
            id: 'Angka jadi 0',
            pt: 'Dígitos zerados',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:semantic-versioning-imperative',
      label: {
        en: 'Receive a release',
        ko: '새 버전 받기',
        ja: '新しい版を受け取る',
        zh: '接收新版本',
        ar: 'استقبال إصدار',
        es: 'Recibir una versión',
        fr: 'Recevoir une version',
        hi: 'नया संस्करण लेना',
        id: 'Menerima rilis',
        pt: 'Receber uma versão',
      },
    },
  },
  messages: {
    'label.change.fix': { en: 'Fix', ko: '고침', ja: '修正', zh: '修复', ar: 'إصلاح', es: 'Arreglo', fr: 'Correctif', hi: 'सुधार', id: 'Perbaikan', pt: 'Correção' },
    'label.change.feature': { en: 'New feature', ko: '기능 추가', ja: '機能追加', zh: '新功能', ar: 'ميزة جديدة', es: 'Función nueva', fr: 'Nouvelle fonction', hi: 'नई सुविधा', id: 'Fitur baru', pt: 'Recurso novo' },
    'label.change.breaking': { en: 'Breaking change', ko: '호환 깨짐', ja: '互換性の破壊', zh: '不兼容改动', ar: 'تغيير كاسر', es: 'Cambio incompatible', fr: 'Rupture', hi: 'असंगत बदलाव', id: 'Perubahan pemutus', pt: 'Quebra de compatibilidade' },
    'label.digit.major': { en: 'major', ko: '메이저', ja: 'メジャー', zh: '主版本', ar: 'رئيسي', es: 'mayor', fr: 'majeur', hi: 'मेजर', id: 'mayor', pt: 'maior' },
    'label.digit.minor': { en: 'minor', ko: '마이너', ja: 'マイナー', zh: '次版本', ar: 'ثانوي', es: 'menor', fr: 'mineur', hi: 'माइनर', id: 'minor', pt: 'menor' },
    'label.digit.patch': { en: 'patch', ko: '패치', ja: 'パッチ', zh: '修订号', ar: 'تصحيح', es: 'parche', fr: 'correctif', hi: 'पैच', id: 'patch', pt: 'patch' },
    'label.verdict.inside': { en: 'inside', ko: '안', ja: '範囲内', zh: '在范围内', ar: 'داخل النطاق', es: 'dentro', fr: 'dedans', hi: 'सीमा के भीतर', id: 'di dalam', pt: 'dentro' },
    'label.verdict.above': { en: 'above the range', ko: '위로 벗어남', ja: '上に外れる', zh: '超出上界', ar: 'فوق النطاق', es: 'por encima del rango', fr: 'au-dessus de la plage', hi: 'सीमा से ऊपर', id: 'di atas rentang', pt: 'acima do intervalo' },
    'label.verdict.below': { en: 'below the range', ko: '아래로 벗어남', ja: '下に外れる', zh: '低于下界', ar: 'تحت النطاق', es: 'por debajo del rango', fr: 'au-dessous de la plage', hi: 'सीमा से नीचे', id: 'di bawah rentang', pt: 'abaixo do intervalo' },
    'label.role.installed': { en: 'Installed', ko: '깔린 것', ja: '導入済み', zh: '已安装', ar: 'المثبَّت', es: 'Instalada', fr: 'Installée', hi: 'स्थापित', id: 'Terpasang', pt: 'Instalada' },
    'label.role.new': { en: 'New version', ko: '새 버전', ja: '新しい版', zh: '新版本', ar: 'الإصدار الجديد', es: 'Versión nueva', fr: 'Nouvelle version', hi: 'नया संस्करण', id: 'Versi baru', pt: 'Versão nova' },
    'label.role.lockFile': { en: 'Lock file', ko: '잠금 파일', ja: 'ロックファイル', zh: '锁文件', ar: 'ملف القفل', es: 'Archivo de bloqueo', fr: 'Fichier de verrouillage', hi: 'लॉक फ़ाइल', id: 'Berkas kunci', pt: 'Arquivo de bloqueio' },
    'label.role.receiver': { en: 'Receiver', ko: '받는 쪽', ja: '受け取る側', zh: '接收方', ar: 'المستقبِل', es: 'Receptor', fr: 'Receveur', hi: 'प्राप्तकर्ता', id: 'Penerima', pt: 'Receptor' },
    'caption.head': {
      en: 'Waiting for a new release',
      ko: '새 버전을 기다린다',
      ja: '新しい版を待つ',
      zh: '等待新版本',
      ar: 'في انتظار إصدار جديد',
      es: 'Esperando una versión nueva',
      fr: 'En attente d’une nouvelle version',
      hi: 'नए संस्करण की प्रतीक्षा',
      id: 'Menunggu rilis baru',
      pt: 'Esperando uma versão nova',
    },
    'caption.bump': {
      en: '{change}: {digit} +1',
      ko: '{change}: {digit} +1',
      ja: '{change}: {digit} +1',
      zh: '{change}：{digit} +1',
      ar: '{change}: {digit} +1',
      es: '{change}: {digit} +1',
      fr: '{change} : {digit} +1',
      hi: '{change}: {digit} +1',
      id: '{change}: {digit} +1',
      pt: '{change}: {digit} +1',
    },
    'caption.bumpZeroed': {
      en: '{change}: {digit} +1 · dropped to 0: {zeroed}',
      ko: '{change}: {digit} +1 · 0 으로 떨어진 자리: {zeroed}',
      ja: '{change}: {digit} +1 · 0 に戻った桁: {zeroed}',
      zh: '{change}：{digit} +1 · 归 0 的位：{zeroed}',
      ar: '{change}: {digit} +1 · عادت إلى 0: {zeroed}',
      es: '{change}: {digit} +1 · caen a 0: {zeroed}',
      fr: '{change} : {digit} +1 · remis à 0 : {zeroed}',
      hi: '{change}: {digit} +1 · 0 हुए अंक: {zeroed}',
      id: '{change}: {digit} +1 · jadi 0: {zeroed}',
      pt: '{change}: {digit} +1 · caem para 0: {zeroed}',
    },
    'caption.range': {
      en: '{range} → [{lower}, {upper})',
      ko: '{range} → [{lower}, {upper})',
      ja: '{range} → [{lower}, {upper})',
      zh: '{range} → [{lower}, {upper})',
      ar: '{range} → [{lower}, {upper})',
      es: '{range} → [{lower}, {upper})',
      fr: '{range} → [{lower}, {upper})',
      hi: '{range} → [{lower}, {upper})',
      id: '{range} → [{lower}, {upper})',
      pt: '{range} → [{lower}, {upper})',
    },
    'caption.compare': {
      en: '{version} — {verdict}',
      ko: '{version} — {verdict}',
      ja: '{version} — {verdict}',
      zh: '{version} — {verdict}',
      ar: '{version} — {verdict}',
      es: '{version} — {verdict}',
      fr: '{version} — {verdict}',
      hi: '{version} — {verdict}',
      id: '{version} — {verdict}',
      pt: '{version} — {verdict}',
    },
    'caption.accept': {
      en: 'Installed moves: {from} → {to}',
      ko: '깔린 것이 옮겨 간다: {from} → {to}',
      ja: '導入済みが移る: {from} → {to}',
      zh: '已安装的移过去：{from} → {to}',
      ar: 'المثبَّت ينتقل: {from} → {to}',
      es: 'La instalada pasa: {from} → {to}',
      fr: "L'installée passe : {from} → {to}",
      hi: 'स्थापित आगे बढ़ा: {from} → {to}',
      id: 'Yang terpasang pindah: {from} → {to}',
      pt: 'A instalada passa: {from} → {to}',
    },
    'caption.reject': {
      en: 'Installed stays: {version}',
      ko: '깔린 것 제자리: {version}',
      ja: '導入済みはそのまま: {version}',
      zh: '已安装的不动：{version}',
      ar: 'المثبَّت يبقى: {version}',
      es: 'La instalada se queda: {version}',
      fr: "L'installée reste : {version}",
      hi: 'स्थापित वहीं रहा: {version}',
      id: 'Yang terpasang tetap: {version}',
      pt: 'A instalada fica: {version}',
    },
    'caption.readLock': {
      en: 'Lock file read first: {line}',
      ko: '잠금 파일을 먼저 읽는다: {line}',
      ja: 'ロックファイルを先に読む: {line}',
      zh: '先读锁文件：{line}',
      ar: 'يُقرأ ملف القفل أولًا: {line}',
      es: 'Primero se lee el bloqueo: {line}',
      fr: "Le verrou est lu d'abord : {line}",
      hi: 'पहले लॉक फ़ाइल पढ़ी: {line}',
      id: 'Berkas kunci dibaca dulu: {line}',
      pt: 'O bloqueio é lido primeiro: {line}',
    },
    'caption.keepLock': {
      en: 'Installed stays at the locked version: {version}',
      ko: '깔린 것은 잠긴 버전 그대로: {version}',
      ja: '導入済みはロックされた版のまま: {version}',
      zh: '已安装的保持锁定版本：{version}',
      ar: 'المثبَّت يبقى على الإصدار المقفل: {version}',
      es: 'La instalada queda en la versión bloqueada: {version}',
      fr: "L'installée reste à la version verrouillée : {version}",
      hi: 'स्थापित लॉक किए संस्करण पर रहा: {version}',
      id: 'Yang terpasang tetap di versi terkunci: {version}',
      pt: 'A instalada fica na versão bloqueada: {version}',
    },
  },
};
