/**
 * @piece
 * 질문: 축마다 다른 배율로 늘이고 줄이면 도형은 무엇을 지키고 무엇을 잃는가.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const scaleStretchesFacet: FacetJson = {
  id: 'facet:scaleStretches',
  title: {
    en: 'Scaling stretches a shape',
    ko: '크기 변환 — 늘이고 줄인다',
    ja: '拡大縮小 — 伸ばして縮める',
    zh: '缩放 — 拉伸与压缩',
    ar: 'التحجيم — مدّ وضغط',
    es: 'El escalado estira una figura',
    fr: 'La mise à l’échelle étire une forme',
    hi: 'स्केलिंग — खींचना और सिकोड़ना',
    id: 'Penskalaan meregangkan bentuk',
    pt: 'A escala estica uma forma',
  },
  description: {
    en: 'Stretch a diamond by a different factor on each axis and watch its corners open, while opposite sides stay parallel and the origin stays put.',
    ko: '축마다 다른 배율로 마름모를 늘이고 줄이면 모서리 각이 벌어진다. 마주 보는 변은 평행으로 남고 원점은 제자리다.',
    ja: '軸ごとに違う倍率でひし形を伸縮すると角が開く。向かい合う辺は平行のまま、原点は動かない。',
    zh: '沿两个轴用不同倍率拉伸菱形,它的角会张开;对边保持平行,原点不动。',
    ar: 'مدّ معيّناً بمعامل مختلف على كل محور فتنفتح زواياه، بينما تبقى الأضلاع المتقابلة متوازية وتبقى نقطة الأصل في مكانها.',
    es: 'Estira un rombo con un factor distinto en cada eje y sus esquinas se abren, mientras los lados opuestos siguen paralelos y el origen no se mueve.',
    fr: 'Étirez un losange d’un facteur différent sur chaque axe : ses angles s’ouvrent, les côtés opposés restent parallèles et l’origine ne bouge pas.',
    hi: 'हर अक्ष पर अलग गुणक से समचतुर्भुज को खींचें तो उसके कोने खुलते हैं, जबकि आमने-सामने की भुजाएँ समानांतर रहती हैं और मूल बिंदु अपनी जगह रहता है।',
    id: 'Regangkan belah ketupat dengan faktor berbeda di tiap sumbu dan sudutnya membuka, sementara sisi yang berhadapan tetap sejajar dan titik asal tidak bergeser.',
    pt: 'Estique um losango com um fator diferente em cada eixo e seus cantos se abrem, enquanto os lados opostos continuam paralelos e a origem fica no lugar.',
  },
  algorithm: 'module:scaleStretches',
  scene: 'module:scaleStretchesScene',
  initialData: {
    type: 'scale-stretches',
    vertices: [
      { id: 'bottom', x: 0, y: 1 },
      { id: 'right', x: 1, y: 2 },
      { id: 'top', x: 0, y: 3 },
      { id: 'left', x: -1, y: 2 },
    ],
    angleAt: 'top',
    factors: [
      { sx: 1.5, sy: 1 },
      { sx: 2, sy: 1 },
      { sx: 3, sy: 1 },
      { sx: 3, sy: 0.5 },
    ],
    stepMs: 1400,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Starting shape. Scale x: {sx}, y: {sy}',
      ko: '처음 도형. 배율 x: {sx}, y: {sy}',
      ja: '元の図形。倍率 x: {sx}, y: {sy}',
      zh: '原始图形。缩放 x: {sx}, y: {sy}',
      ar: 'الشكل الأصلي. المقياس x: {sx}, y: {sy}',
      es: 'Forma inicial. Escala x: {sx}, y: {sy}',
      fr: 'Forme de départ. Échelle x : {sx}, y : {sy}',
      hi: 'मूल आकृति। पैमाना x: {sx}, y: {sy}',
      id: 'Bentuk awal. Skala x: {sx}, y: {sy}',
      pt: 'Forma inicial. Escala x: {sx}, y: {sy}',
    },
    'caption.stretchX': {
      en: 'Stretch across. Scale x: {sx}, y: {sy}',
      ko: '가로로 늘인다. 배율 x: {sx}, y: {sy}',
      ja: '横に伸ばす。倍率 x: {sx}, y: {sy}',
      zh: '横向拉伸。缩放 x: {sx}, y: {sy}',
      ar: 'مدّ أفقي. المقياس x: {sx}, y: {sy}',
      es: 'Estirar a lo ancho. Escala x: {sx}, y: {sy}',
      fr: 'Étirer en largeur. Échelle x : {sx}, y : {sy}',
      hi: 'चौड़ाई में खींचें। पैमाना x: {sx}, y: {sy}',
      id: 'Regangkan melebar. Skala x: {sx}, y: {sy}',
      pt: 'Esticar na largura. Escala x: {sx}, y: {sy}',
    },
    'caption.squashX': {
      en: 'Squeeze across. Scale x: {sx}, y: {sy}',
      ko: '가로로 줄인다. 배율 x: {sx}, y: {sy}',
      ja: '横に縮める。倍率 x: {sx}, y: {sy}',
      zh: '横向压缩。缩放 x: {sx}, y: {sy}',
      ar: 'ضغط أفقي. المقياس x: {sx}, y: {sy}',
      es: 'Comprimir a lo ancho. Escala x: {sx}, y: {sy}',
      fr: 'Resserrer en largeur. Échelle x : {sx}, y : {sy}',
      hi: 'चौड़ाई में सिकोड़ें। पैमाना x: {sx}, y: {sy}',
      id: 'Sempitkan melebar. Skala x: {sx}, y: {sy}',
      pt: 'Estreitar na largura. Escala x: {sx}, y: {sy}',
    },
    'caption.stretchY': {
      en: 'Stretch upward. Scale x: {sx}, y: {sy}',
      ko: '세로로 늘인다. 배율 x: {sx}, y: {sy}',
      ja: '縦に伸ばす。倍率 x: {sx}, y: {sy}',
      zh: '纵向拉伸。缩放 x: {sx}, y: {sy}',
      ar: 'مدّ رأسي. المقياس x: {sx}, y: {sy}',
      es: 'Estirar hacia arriba. Escala x: {sx}, y: {sy}',
      fr: 'Étirer vers le haut. Échelle x : {sx}, y : {sy}',
      hi: 'ऊपर की ओर खींचें। पैमाना x: {sx}, y: {sy}',
      id: 'Regangkan ke atas. Skala x: {sx}, y: {sy}',
      pt: 'Esticar para cima. Escala x: {sx}, y: {sy}',
    },
    'caption.squashY': {
      en: 'Squash down. Scale x: {sx}, y: {sy}',
      ko: '세로로 줄인다. 배율 x: {sx}, y: {sy}',
      ja: '縦に縮める。倍率 x: {sx}, y: {sy}',
      zh: '纵向压缩。缩放 x: {sx}, y: {sy}',
      ar: 'ضغط رأسي. المقياس x: {sx}, y: {sy}',
      es: 'Aplastar hacia abajo. Escala x: {sx}, y: {sy}',
      fr: 'Écraser vers le bas. Échelle x : {sx}, y : {sy}',
      hi: 'नीचे की ओर दबाएँ। पैमाना x: {sx}, y: {sy}',
      id: 'Pipihkan ke bawah. Skala x: {sx}, y: {sy}',
      pt: 'Achatar para baixo. Escala x: {sx}, y: {sy}',
    },
    'caption.both': {
      en: 'Rescale both axes. Scale x: {sx}, y: {sy}',
      ko: '두 축을 함께 바꾼다. 배율 x: {sx}, y: {sy}',
      ja: '両軸を変える。倍率 x: {sx}, y: {sy}',
      zh: '两轴同时缩放。缩放 x: {sx}, y: {sy}',
      ar: 'تغيير المحورين معاً. المقياس x: {sx}, y: {sy}',
      es: 'Cambiar ambos ejes. Escala x: {sx}, y: {sy}',
      fr: 'Changer les deux axes. Échelle x : {sx}, y : {sy}',
      hi: 'दोनों अक्ष बदलें। पैमाना x: {sx}, y: {sy}',
      id: 'Ubah kedua sumbu. Skala x: {sx}, y: {sy}',
      pt: 'Mudar os dois eixos. Escala x: {sx}, y: {sy}',
    },
    'label.axisX': {
      en: 'x',
      ko: 'x',
      ja: 'x',
      zh: 'x',
      ar: 'x',
      es: 'x',
      fr: 'x',
      hi: 'x',
      id: 'x',
      pt: 'x',
    },
    'label.axisY': {
      en: 'y',
      ko: 'y',
      ja: 'y',
      zh: 'y',
      ar: 'y',
      es: 'y',
      fr: 'y',
      hi: 'y',
      id: 'y',
      pt: 'y',
    },
    'label.origin': {
      en: 'Origin',
      ko: '원점',
      ja: '原点',
      zh: '原点',
      ar: 'نقطة الأصل',
      es: 'Origen',
      fr: 'Origine',
      hi: 'मूल बिंदु',
      id: 'Titik asal',
      pt: 'Origem',
    },
    'label.moved': {
      en: 'Moved: {d}',
      ko: '움직인 거리: {d}',
      ja: '移動量: {d}',
      zh: '移动距离: {d}',
      ar: 'المسافة المقطوعة: {d}',
      es: 'Desplazamiento: {d}',
      fr: 'Déplacement : {d}',
      hi: 'खिसकी दूरी: {d}',
      id: 'Jarak geser: {d}',
      pt: 'Deslocamento: {d}',
    },
    'readout.angle': {
      en: 'Top angle: {deg}°',
      ko: '위 꼭짓점 각: {deg}°',
      ja: '上の頂点の角: {deg}°',
      zh: '顶部顶点角: {deg}°',
      ar: 'زاوية الرأس العلوي: {deg}°',
      es: 'Ángulo superior: {deg}°',
      fr: 'Angle du haut : {deg}°',
      hi: 'ऊपरी शीर्ष कोण: {deg}°',
      id: 'Sudut puncak atas: {deg}°',
      pt: 'Ângulo de cima: {deg}°',
    },
    'readout.side': {
      en: 'Side: {len}',
      ko: '변의 길이: {len}',
      ja: '辺の長さ: {len}',
      zh: '边长: {len}',
      ar: 'طول الضلع: {len}',
      es: 'Lado: {len}',
      fr: 'Côté : {len}',
      hi: 'भुजा: {len}',
      id: 'Sisi: {len}',
      pt: 'Lado: {len}',
    },
  },
  blocks: {
    stage: { type: 'scale-stretches-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
