/**
 * map-filter-reduce — 선언.
 *
 * 구조(1차 데이터)는 marks · 사다리 · 시작값 · 첫 문턱뿐이다. kept · squares · 누적 · 계기는 알고리즘이 셈한다.
 * `code` 는 화면의 세 단계 문 이름표 (가상 표기 — tasks/pseudo-notation.md). `{threshold}` · `{start}` 자리만
 * 판의 값으로 채운다. 넘기는 함수(`chip`)는 문에 꽂힌 칩으로 그린다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const mapFilterReduceFacet: FacetJson = {
  id: 'facet:mapFilterReduce',
  title: {
    en: 'map / filter / reduce',
    ko: 'map / filter / reduce',
    ja: 'map / filter / reduce',
    zh: 'map / filter / reduce',
    ar: 'map / filter / reduce',
    es: 'map / filter / reduce',
    fr: 'map / filter / reduce',
    hi: 'map / filter / reduce',
    id: 'map / filter / reduce',
    pt: 'map / filter / reduce',
  },
  description: {
    en: 'Three stages, each changing one thing: filter changes how many, map changes the values, reduce folds the list into one number.',
    ko: '세 단계가 각자 한 가지만 바꾼다. filter 는 개수를, map 은 값을 바꾸고, reduce 는 목록을 수 하나로 접는다.',
    ja: '三つの段階はそれぞれ一つだけを変える。filter は個数を、map は値を変え、reduce はリストを一つの数に畳む。',
    zh: '三个阶段各自只改变一件事：filter 改变个数，map 改变值，reduce 把列表折叠成一个数。',
    ar: 'ثلاث مراحل، تغيّر كل منها شيئًا واحدًا: filter يغيّر العدد، وmap يغيّر القيم، وreduce يطوي القائمة في رقم واحد.',
    es: 'Tres etapas, cada una cambia una sola cosa: filter cambia cuántos hay, map cambia los valores y reduce pliega la lista en un número.',
    fr: 'Trois étapes, chacune ne change qu’une chose : filter change le nombre, map change les valeurs, reduce replie la liste en un seul nombre.',
    hi: 'तीन चरण, हर एक सिर्फ़ एक चीज़ बदलता है: filter गिनती बदलता है, map मान बदलता है, reduce सूची को एक संख्या में मोड़ देता है।',
    id: 'Tiga tahap, masing-masing hanya mengubah satu hal: filter mengubah jumlah, map mengubah nilai, reduce melipat daftar menjadi satu angka.',
    pt: 'Três etapas, cada uma muda uma só coisa: filter muda a quantidade, map muda os valores e reduce dobra a lista em um número.',
  },
  algorithm: 'module:mapFilterReduce',
  projector: 'module:mapFilterReduceProjector',
  initialData: {
    type: 'map-filter-reduce',
    stepMs: 600,
    marks: [6, 3, 8, 1, 5, 9],
    thresholds: [0, 2, 4, 6, 8],
    start: 0,
    threshold: 4,
    code: {
      source: 'marks',
      filter: { out: 'kept', head: 'let kept = filter(marks, ', chip: 'x => x > {threshold}', tail: ')' },
      map: { out: 'squares', head: 'let squares = map(kept, ', chip: 'x => x * x', tail: ')' },
      reduce: { out: 'sum', head: 'let sum = reduce(squares, {start}, ', chip: '(acc, x) => acc + x', tail: ')' },
    },
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'map-filter-reduce-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'threshold',
          name: 'threshold',
          label: {
            en: 'Threshold',
            ko: '문턱',
            ja: 'しきい値',
            zh: '阈值',
            ar: 'العتبة',
            es: 'Umbral',
            fr: 'Seuil',
            hi: 'सीमा',
            id: 'Ambang',
            pt: 'Limiar',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 2, label: '2' },
            { value: 4, label: '4', default: true },
            { value: 6, label: '6' },
            { value: 8, label: '8' },
          ],
        },
      ],
      metrics: [
        {
          name: 'filter-kept',
          label: {
            en: 'Kept by filter',
            ko: 'filter 뒤',
            ja: 'filter の後',
            zh: 'filter 之后',
            ar: 'بعد filter',
            es: 'Tras filter',
            fr: 'Après filter',
            hi: 'filter के बाद',
            id: 'Setelah filter',
            pt: 'Após filter',
          },
          initial: 0,
        },
        {
          name: 'map-out',
          label: {
            en: 'Out of map',
            ko: 'map 뒤',
            ja: 'map の後',
            zh: 'map 之后',
            ar: 'بعد map',
            es: 'Tras map',
            fr: 'Après map',
            hi: 'map के बाद',
            id: 'Setelah map',
            pt: 'Após map',
          },
          initial: 0,
        },
        {
          name: 'reduce-result',
          label: {
            en: 'Reduce result',
            ko: 'reduce 답',
            ja: 'reduce の結果',
            zh: 'reduce 结果',
            ar: 'نتيجة reduce',
            es: 'Resultado de reduce',
            fr: 'Résultat de reduce',
            hi: 'reduce का परिणाम',
            id: 'Hasil reduce',
            pt: 'Resultado de reduce',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:map-filter-reduce-imperative',
      label: {
        en: 'The loops inside the three stages',
        ko: '세 단계가 속에서 하는 반복',
        ja: '三つの段階の内側のループ',
        zh: '三个阶段内部的循环',
        ar: 'الحلقات داخل المراحل الثلاث',
        es: 'Los bucles dentro de las tres etapas',
        fr: 'Les boucles à l’intérieur des trois étapes',
        hi: 'तीनों चरणों के भीतर के लूप',
        id: 'Perulangan di dalam ketiga tahap',
        pt: 'Os laços dentro das três etapas',
      },
    },
  },
  messages: {
    'caption.start': {
      en: 'Threshold: {threshold}',
      ko: '문턱: {threshold}',
      ja: 'しきい値: {threshold}',
      zh: '阈值：{threshold}',
      ar: 'العتبة: {threshold}',
      es: 'Umbral: {threshold}',
      fr: 'Seuil : {threshold}',
      hi: 'सीमा: {threshold}',
      id: 'Ambang: {threshold}',
      pt: 'Limiar: {threshold}',
    },
    'caption.test': {
      en: '{x} > {threshold}: {verdict}',
      ko: '{x} > {threshold}: {verdict}',
      ja: '{x} > {threshold}: {verdict}',
      zh: '{x} > {threshold}：{verdict}',
      ar: '{x} > {threshold}: {verdict}',
      es: '{x} > {threshold}: {verdict}',
      fr: '{x} > {threshold} : {verdict}',
      hi: '{x} > {threshold}: {verdict}',
      id: '{x} > {threshold}: {verdict}',
      pt: '{x} > {threshold}: {verdict}',
    },
    'verdict.true': {
      en: 'true',
      ko: '참',
      ja: '真',
      zh: '真',
      ar: 'صحيح',
      es: 'verdadero',
      fr: 'vrai',
      hi: 'सत्य',
      id: 'benar',
      pt: 'verdadeiro',
    },
    'verdict.false': {
      en: 'false',
      ko: '거짓',
      ja: '偽',
      zh: '假',
      ar: 'خطأ',
      es: 'falso',
      fr: 'faux',
      hi: 'असत्य',
      id: 'salah',
      pt: 'falso',
    },
    'caption.map': {
      en: '{x} → {y}',
      ko: '{x} → {y}',
      ja: '{x} → {y}',
      zh: '{x} → {y}',
      ar: '{x} → {y}',
      es: '{x} → {y}',
      fr: '{x} → {y}',
      hi: '{x} → {y}',
      id: '{x} → {y}',
      pt: '{x} → {y}',
    },
    'caption.fold': {
      en: '{acc} + {y} = {next}',
      ko: '{acc} + {y} = {next}',
      ja: '{acc} + {y} = {next}',
      zh: '{acc} + {y} = {next}',
      ar: '{acc} + {y} = {next}',
      es: '{acc} + {y} = {next}',
      fr: '{acc} + {y} = {next}',
      hi: '{acc} + {y} = {next}',
      id: '{acc} + {y} = {next}',
      pt: '{acc} + {y} = {next}',
    },
    'caption.answer': {
      en: 'Result: {sum}',
      ko: '답: {sum}',
      ja: '結果: {sum}',
      zh: '结果：{sum}',
      ar: 'النتيجة: {sum}',
      es: 'Resultado: {sum}',
      fr: 'Résultat : {sum}',
      hi: 'परिणाम: {sum}',
      id: 'Hasil: {sum}',
      pt: 'Resultado: {sum}',
    },
    'label.dropped': {
      en: 'Dropped',
      ko: '떨어진 것',
      ja: '落ちたもの',
      zh: '被滤掉的',
      ar: 'المُسقَط',
      es: 'Descartados',
      fr: 'Écartés',
      hi: 'छूटे हुए',
      id: 'Tersaring keluar',
      pt: 'Descartados',
    },
    'tag.lost': {
      en: 'passed last time',
      ko: '앞 판에선 지났다',
      ja: '前回は通った',
      zh: '上一轮通过了',
      ar: 'مرّ في المرة السابقة',
      es: 'pasó la vez anterior',
      fr: 'passé la fois précédente',
      hi: 'पिछली बार निकल गया था',
      id: 'lolos sebelumnya',
      pt: 'passou da última vez',
    },
    'tag.revived': {
      en: 'dropped last time',
      ko: '앞 판에선 떨어졌다',
      ja: '前回は落ちた',
      zh: '上一轮被滤掉',
      ar: 'سقط في المرة السابقة',
      es: 'cayó la vez anterior',
      fr: 'écarté la fois précédente',
      hi: 'पिछली बार छूट गया था',
      id: 'tersaring sebelumnya',
      pt: 'caiu da última vez',
    },
  },
};
