import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 두 제안자가 서로 다른 값을 내놓을 때, 한번 정해진 값이 뒤에 온 제안에 밀려 바뀌지 않는 까닭은 무엇인가?
 */
export const agreeOnOneValueFacet: FacetJson = {
  id: 'facet:agreeOnOneValue',
  title: {
    en: 'Agree on one value',
    ko: '하나의 값에 합의하기',
    ja: '一つの値に合意する',
    zh: '就一个值达成一致',
    ar: 'الاتفاق على قيمة واحدة',
    es: 'Acordar un solo valor',
    fr: 'S’accorder sur une seule valeur',
    hi: 'एक ही मान पर सहमति',
    id: 'Sepakat pada satu nilai',
    pt: 'Concordar em um único valor',
  },
  description: {
    en: 'A later proposer asks a majority what it has accepted; the acceptor both majorities share hands back the value already decided.',
    ko: '뒤에 온 제안자가 과반에게 받아들인 것을 묻고, 두 과반이 겹친 받는 쪽이 이미 정해진 값을 돌려준다.',
    ja: '後から来た提案者が過半数に受け入れた値を尋ね、二つの過半数が重なる受け手がすでに決まった値を返す。',
    zh: '后来的提议者向多数派询问已接受的值，两个多数派共有的接受者交回已经确定的值。',
    ar: 'يسأل المقترِح المتأخر أغلبيةً عمّا قبلته، فيعيد المستقبِل المشترك بين الأغلبيتين القيمة التي تقرّرت من قبل.',
    es: 'Un proponente posterior pregunta a una mayoría qué ha aceptado; el aceptador que comparten ambas mayorías devuelve el valor ya decidido.',
    fr: 'Un proposant venu plus tard demande à une majorité ce qu’elle a accepté ; l’accepteur commun aux deux majorités renvoie la valeur déjà décidée.',
    hi: 'बाद में आया प्रस्तावक बहुमत से पूछता है कि उसने क्या स्वीकार किया; दोनों बहुमतों में साझा स्वीकारकर्ता पहले से तय मान लौटाता है।',
    id: 'Pengusul yang datang belakangan bertanya kepada mayoritas apa yang telah diterima; penerima yang dimiliki kedua mayoritas mengembalikan nilai yang sudah diputuskan.',
    pt: 'Um proponente posterior pergunta a uma maioria o que ela aceitou; o aceitador comum às duas maiorias devolve o valor já decidido.',
  },
  algorithm: 'module:agreeOnOneValue',
  scene: 'module:agreeOnOneValueScene',
  initialData: {
    type: 'agree-on-one-value',
    stepMs: 1000,
    acceptors: ['n1', 'n2', 'n3', 'n4', 'n5'],
    proposers: [
      { id: 'P1', ballot: 1, value: 5, to: ['n1', 'n2', 'n3'], asks: false },
      { id: 'P2', ballot: 2, value: 8, to: ['n3', 'n4', 'n5'], asks: true },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.init': {
      en: 'Proposers: {p} · Acceptors: {a}',
      ko: '제안자: {p} · 받는 쪽: {a}',
      ja: '提案者: {p} · 受け手: {a}',
      zh: '提议者：{p} · 接受者：{a}',
      ar: 'المقترِحون: {p} · المستقبِلون: {a}',
      es: 'Proponentes: {p} · Aceptadores: {a}',
      fr: 'Proposants : {p} · Accepteurs : {a}',
      hi: 'प्रस्तावक: {p} · स्वीकारकर्ता: {a}',
      id: 'Pengusul: {p} · Penerima: {a}',
      pt: 'Proponentes: {p} · Aceitadores: {a}',
    },
    'caption.initSub': {
      en: 'Majority: {m}',
      ko: '과반: {m}',
      ja: '過半数: {m}',
      zh: '多数：{m}',
      ar: 'الأغلبية: {m}',
      es: 'Mayoría: {m}',
      fr: 'Majorité : {m}',
      hi: 'बहुमत: {m}',
      id: 'Mayoritas: {m}',
      pt: 'Maioria: {m}',
    },
    'caption.ask': {
      en: '{p} asks {a}: what have you accepted?',
      ko: '{p} → {a} 물음: 받아들인 것은?',
      ja: '{p} → {a} の問い: 受け入れたものは?',
      zh: '{p} 问 {a}：你接受了什么？',
      ar: '{p} يسأل {a}: ماذا قبلت؟',
      es: '{p} pregunta a {a}: ¿qué has aceptado?',
      fr: '{p} demande à {a} : qu’as-tu accepté ?',
      hi: '{p} → {a} प्रश्न: तुमने क्या स्वीकार किया?',
      id: '{p} bertanya ke {a}: apa yang sudah kamu terima?',
      pt: '{p} pergunta a {a}: o que você aceitou?',
    },
    'caption.answerNone': {
      en: 'Answer: none',
      ko: '대답: 없음',
      ja: '答え: なし',
      zh: '回答：无',
      ar: 'الجواب: لا شيء',
      es: 'Respuesta: nada',
      fr: 'Réponse : rien',
      hi: 'उत्तर: कुछ नहीं',
      id: 'Jawaban: tidak ada',
      pt: 'Resposta: nada',
    },
    'caption.answer': {
      en: 'Answer: ballot {b}, value {v}',
      ko: '대답: 번호 {b} · 값 {v}',
      ja: '答え: 番号 {b} · 値 {v}',
      zh: '回答：编号 {b} · 值 {v}',
      ar: 'الجواب: الرقم {b} · القيمة {v}',
      es: 'Respuesta: número {b}, valor {v}',
      fr: 'Réponse : numéro {b}, valeur {v}',
      hi: 'उत्तर: क्रमांक {b} · मान {v}',
      id: 'Jawaban: nomor {b}, nilai {v}',
      pt: 'Resposta: número {b}, valor {v}',
    },
    'caption.adoptOwn': {
      en: '{p} carries its own value {own}.',
      ko: '{p} · 나르는 값: 제 값 {own} 그대로.',
      ja: '{p} が運ぶ値: 自分の値 {own} のまま。',
      zh: '{p} 携带的值：仍是自己的 {own}。',
      ar: '{p} يحمل قيمته الخاصة {own}.',
      es: '{p} lleva su propio valor {own}.',
      fr: '{p} porte sa propre valeur {own}.',
      hi: '{p} अपना मान {own} ही ले जाता है।',
      id: '{p} membawa nilainya sendiri {own}.',
      pt: '{p} leva o seu próprio valor {own}.',
    },
    'caption.adoptOwnSub': {
      en: 'No accepted value among the answers',
      ko: '대답 가운데 받아들인 값 없음',
      ja: '答えの中に受け入れた値はない',
      zh: '回答中没有已接受的值',
      ar: 'لا قيمة مقبولة بين الأجوبة',
      es: 'Ningún valor aceptado entre las respuestas',
      fr: 'Aucune valeur acceptée parmi les réponses',
      hi: 'उत्तरों में कोई स्वीकृत मान नहीं',
      id: 'Tidak ada nilai yang diterima di antara jawaban',
      pt: 'Nenhum valor aceito entre as respostas',
    },
    'caption.adopt': {
      en: '{p} carries {v} instead of its own {own}.',
      ko: '{p} · 나르는 값: {own} → {v}.',
      ja: '{p} が運ぶ値: {own} → {v}。',
      zh: '{p} 携带的值：{own} → {v}。',
      ar: '{p} يحمل {v} بدل قيمته {own}.',
      es: '{p} lleva {v} en lugar de su propio {own}.',
      fr: '{p} porte {v} au lieu de sa propre valeur {own}.',
      hi: '{p} अपने {own} की जगह {v} ले जाता है।',
      id: '{p} membawa {v}, bukan nilainya sendiri {own}.',
      pt: '{p} leva {v} em vez do seu próprio {own}.',
    },
    'caption.adoptSub': {
      en: 'Highest ballot among the answers: {b}, from {a}',
      ko: '대답 가운데 가장 큰 번호: {b} (자리 {a})',
      ja: '答えの中で最大の番号: {b} ({a})',
      zh: '回答中最大的编号：{b}（来自 {a}）',
      ar: 'أكبر رقم بين الأجوبة: {b}، من {a}',
      es: 'Número más alto entre las respuestas: {b}, de {a}',
      fr: 'Plus grand numéro parmi les réponses : {b}, venant de {a}',
      hi: 'उत्तरों में सबसे बड़ा क्रमांक: {b} ({a} से)',
      id: 'Nomor tertinggi di antara jawaban: {b}, dari {a}',
      pt: 'Maior número entre as respostas: {b}, de {a}',
    },
    'caption.accept': {
      en: '{a} accepts ballot {b}, value {v}.',
      ko: '{a} 받아들임 — 번호 {b} · 값 {v}.',
      ja: '{a} が受け入れる — 番号 {b} · 値 {v}。',
      zh: '{a} 接受 — 编号 {b} · 值 {v}。',
      ar: '{a} يقبل الرقم {b}، القيمة {v}.',
      es: '{a} acepta el número {b}, valor {v}.',
      fr: '{a} accepte le numéro {b}, valeur {v}.',
      hi: '{a} स्वीकार करता है — क्रमांक {b} · मान {v}।',
      id: '{a} menerima nomor {b}, nilai {v}.',
      pt: '{a} aceita o número {b}, valor {v}.',
    },
    'caption.acceptOver': {
      en: '{a} accepts ballot {b}, value {v} — before: ballot {wb}, value {wv}.',
      ko: '{a} 받아들임 — 번호 {b} · 값 {v}. 앞서 든 것: 번호 {wb} · 값 {wv}.',
      ja: '{a} が受け入れる — 番号 {b} · 値 {v}。以前: 番号 {wb} · 値 {wv}。',
      zh: '{a} 接受 — 编号 {b} · 值 {v}。此前：编号 {wb} · 值 {wv}。',
      ar: '{a} يقبل الرقم {b}، القيمة {v} — قبل ذلك: الرقم {wb}، القيمة {wv}.',
      es: '{a} acepta el número {b}, valor {v} — antes: número {wb}, valor {wv}.',
      fr: '{a} accepte le numéro {b}, valeur {v} — avant : numéro {wb}, valeur {wv}.',
      hi: '{a} स्वीकार करता है — क्रमांक {b} · मान {v}। पहले: क्रमांक {wb} · मान {wv}।',
      id: '{a} menerima nomor {b}, nilai {v} — sebelumnya: nomor {wb}, nilai {wv}.',
      pt: '{a} aceita o número {b}, valor {v} — antes: número {wb}, valor {wv}.',
    },
    'caption.decide': {
      en: 'Holding {v}: {n}/{total} · Majority: {m} · Decided value: {d}',
      ko: '값 {v} 든 곳: {n}/{total} · 과반: {m} · 정해진 값: {d}',
      ja: '値 {v} を持つところ: {n}/{total} · 過半数: {m} · 決まった値: {d}',
      zh: '持有 {v}：{n}/{total} · 多数：{m} · 确定的值：{d}',
      ar: 'تحمل {v}: {n}/{total} · الأغلبية: {m} · القيمة المقرّرة: {d}',
      es: 'Con {v}: {n}/{total} · Mayoría: {m} · Valor decidido: {d}',
      fr: 'Détiennent {v} : {n}/{total} · Majorité : {m} · Valeur décidée : {d}',
      hi: '{v} रखने वाले: {n}/{total} · बहुमत: {m} · तय मान: {d}',
      id: 'Memegang {v}: {n}/{total} · Mayoritas: {m} · Nilai diputuskan: {d}',
      pt: 'Com {v}: {n}/{total} · Maioria: {m} · Valor decidido: {d}',
    },
    'caption.tally': {
      en: 'Holding {v}: {n}/{total}',
      ko: '값 {v} 든 곳: {n}/{total}',
      ja: '値 {v} を持つところ: {n}/{total}',
      zh: '持有 {v}：{n}/{total}',
      ar: 'تحمل {v}: {n}/{total}',
      es: 'Con {v}: {n}/{total}',
      fr: 'Détiennent {v} : {n}/{total}',
      hi: '{v} रखने वाले: {n}/{total}',
      id: 'Memegang {v}: {n}/{total}',
      pt: 'Com {v}: {n}/{total}',
    },
    'caption.after': {
      en: 'Decided value: {d} · Holding {own}: {k}/{total}',
      ko: '정해진 값: {d} · 값 {own} 든 곳: {k}/{total}',
      ja: '決まった値: {d} · 値 {own} を持つところ: {k}/{total}',
      zh: '确定的值：{d} · 持有 {own}：{k}/{total}',
      ar: 'القيمة المقرّرة: {d} · تحمل {own}: {k}/{total}',
      es: 'Valor decidido: {d} · Con {own}: {k}/{total}',
      fr: 'Valeur décidée : {d} · Détiennent {own} : {k}/{total}',
      hi: 'तय मान: {d} · {own} रखने वाले: {k}/{total}',
      id: 'Nilai diputuskan: {d} · Memegang {own}: {k}/{total}',
      pt: 'Valor decidido: {d} · Com {own}: {k}/{total}',
    },
    'label.track': {
      en: 'Decided value at each step',
      ko: '걸음마다 정해진 값',
      ja: 'ステップごとの決まった値',
      zh: '每一步确定的值',
      ar: 'القيمة المقرّرة في كل خطوة',
      es: 'Valor decidido en cada paso',
      fr: 'Valeur décidée à chaque étape',
      hi: 'हर चरण पर तय मान',
      id: 'Nilai diputuskan di tiap langkah',
      pt: 'Valor decidido em cada passo',
    },
    'label.overlap': {
      en: 'overlap',
      ko: '겹친 자리',
      ja: '重なり',
      zh: '重叠处',
      ar: 'التقاطع',
      es: 'solapamiento',
      fr: 'recoupement',
      hi: 'साझा',
      id: 'irisan',
      pt: 'sobreposição',
    },
    'label.ballot': {
      en: 'ballot {b}',
      ko: '번호 {b}',
      ja: '番号 {b}',
      zh: '编号 {b}',
      ar: 'الرقم {b}',
      es: 'número {b}',
      fr: 'numéro {b}',
      hi: 'क्रमांक {b}',
      id: 'nomor {b}',
      pt: 'número {b}',
    },
    'label.acceptors': {
      en: 'Acceptors · majority: {m}',
      ko: '받는 쪽 · 과반: {m}',
      ja: '受け手 · 過半数: {m}',
      zh: '接受者 · 多数：{m}',
      ar: 'المستقبِلون · الأغلبية: {m}',
      es: 'Aceptadores · mayoría: {m}',
      fr: 'Accepteurs · majorité : {m}',
      hi: 'स्वीकारकर्ता · बहुमत: {m}',
      id: 'Penerima · mayoritas: {m}',
      pt: 'Aceitadores · maioria: {m}',
    },
    'label.proposer': {
      en: 'Proposer {id}',
      ko: '제안자 {id}',
      ja: '提案者 {id}',
      zh: '提议者 {id}',
      ar: 'المقترِح {id}',
      es: 'Proponente {id}',
      fr: 'Proposant {id}',
      hi: 'प्रस्तावक {id}',
      id: 'Pengusul {id}',
      pt: 'Proponente {id}',
    },
    'label.carries': {
      en: 'carries',
      ko: '나르는 값',
      ja: '運ぶ値',
      zh: '携带',
      ar: 'يحمل',
      es: 'lleva',
      fr: 'porte',
      hi: 'ले जाता',
      id: 'membawa',
      pt: 'leva',
    },
    'label.answers': {
      en: 'Answers',
      ko: '대답',
      ja: '答え',
      zh: '回答',
      ar: 'الأجوبة',
      es: 'Respuestas',
      fr: 'Réponses',
      hi: 'उत्तर',
      id: 'Jawaban',
      pt: 'Respostas',
    },
  },
  blocks: {
    stage: { type: 'agree-on-one-value-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
