import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 연결을 열 때 왜 두 번이 아니라 세 번을 주고받는가.
 *
 * 양쪽이 "상대가 알아야 할 것" 칸을 둘씩 쥐고, 메시지가 닿을 때마다 칸이 채워진다.
 * 가운데 SYN+ACK 는 칸 둘을 한꺼번에 채우지만, 둘째 메시지 뒤에도 서버의 칸 하나가 비어
 * 셋째 ACK 가 가서야 서버가 연다. 시작 번호 · 주소는 예로 정한 값이다.
 */
export const threeWaySyncFacet: FacetJson = {
  id: 'facet:threeWaySync',
  title: {
    en: 'Three-way handshake',
    ko: '3-way 핸드셰이크',
    ja: '3ウェイハンドシェイク',
    zh: '三次握手',
    ar: 'المصافحة الثلاثية',
    es: 'Saludo de tres vías',
    fr: 'Poignée de main en trois temps',
    hi: 'थ्री-वे हैंडशेक',
    id: 'Jabat tangan tiga arah',
    pt: 'Handshake de três vias',
  },
  description: {
    en: 'Each side holds two facts to confirm. The second message fills two at once, yet the server still waits for the third.',
    ko: '양쪽이 확인할 사실을 둘씩 쥐고 있다. 둘째 메시지가 칸 둘을 한꺼번에 채워도 서버는 셋째를 기다린다.',
    ja: '両側が確かめるべき事実を二つずつ持つ。二通目が二つを一度に埋めても、サーバーは三通目を待つ。',
    zh: '双方各持有两项待确认的事实。第二条消息一次填满两项，服务器仍要等第三条。',
    ar: 'يحمل كل طرف حقيقتين عليه تأكيدهما. تملأ الرسالة الثانية اثنتين معًا، لكن الخادم ما زال ينتظر الثالثة.',
    es: 'Cada lado tiene dos hechos por confirmar. El segundo mensaje llena dos a la vez, pero el servidor aún espera el tercero.',
    fr: 'Chaque côté a deux faits à confirmer. Le deuxième message en remplit deux d’un coup, mais le serveur attend encore le troisième.',
    hi: 'हर पक्ष के पास पुष्टि करने के लिए दो तथ्य हैं। दूसरा संदेश दोनों को एक साथ भरता है, फिर भी सर्वर तीसरे की प्रतीक्षा करता है।',
    id: 'Tiap sisi memegang dua fakta yang perlu dipastikan. Pesan kedua mengisi dua sekaligus, tetapi server masih menunggu yang ketiga.',
    pt: 'Cada lado tem dois fatos a confirmar. A segunda mensagem preenche dois de uma vez, mas o servidor ainda espera a terceira.',
  },
  algorithm: 'module:threeWaySync',
  scene: 'module:threeWaySyncScene',
  initialData: {
    type: 'three-way-sync',
    stepMs: 2200,
    // 주소는 문서용 범위, 시작 번호는 예로 정한 값 (실제 TCP 의 시작 번호는 무작위다).
    sides: [
      { id: 'client', addr: '192.0.2.10:49152', isn: 4200, state: 'CLOSED' },
      { id: 'server', addr: '198.51.100.20:80', isn: 9100, state: 'LISTEN' },
    ],
    facts: [
      { id: 'serverKnowsX', holder: 'server', kind: 'peerNumber' },
      { id: 'clientKnowsXAcked', holder: 'client', kind: 'ownAcked' },
      { id: 'clientKnowsY', holder: 'client', kind: 'peerNumber' },
      { id: 'serverKnowsYAcked', holder: 'server', kind: 'ownAcked' },
    ],
    exchange: [
      { from: 'client', to: 'server', flags: ['SYN'] },
      { from: 'server', to: 'client', flags: ['SYN', 'ACK'] },
      { from: 'client', to: 'server', flags: ['ACK'] },
    ],
    syn: 'SYN',
    ackFlag: 'ACK',
    states: { synSent: 'SYN-SENT', synReceived: 'SYN-RECEIVED', established: 'ESTABLISHED' },
    fieldText: { seq: 'seq=', ack: 'ack=' },
  },
  shuffleOnReset: false,
  messages: {
    'label.client': {
      en: 'Client', ko: '클라이언트', ja: 'クライアント', zh: '客户端', ar: 'العميل',
      es: 'Cliente', fr: 'Client', hi: 'क्लाइंट', id: 'Klien', pt: 'Cliente',
    },
    'label.server': {
      en: 'Server', ko: '서버', ja: 'サーバー', zh: '服务器', ar: 'الخادم',
      es: 'Servidor', fr: 'Serveur', hi: 'सर्वर', id: 'Server', pt: 'Servidor',
    },
    'fact.serverKnowsX': {
      en: "Has the client's number",
      ko: '클라이언트 번호를 받았다',
      ja: 'クライアントの番号を受け取った',
      zh: '已收到客户端的编号',
      ar: 'استلم رقم العميل',
      es: 'Tiene el número del cliente',
      fr: 'A reçu le numéro du client',
      hi: 'क्लाइंट का नंबर मिल गया',
      id: 'Sudah menerima nomor klien',
      pt: 'Tem o número do cliente',
    },
    'fact.clientKnowsXAcked': {
      en: 'Knows its number arrived',
      ko: '내 번호가 닿은 것을 안다',
      ja: '自分の番号が届いたと知っている',
      zh: '知道自己的编号已送达',
      ar: 'يعلم أن رقمه وصل',
      es: 'Sabe que su número llegó',
      fr: 'Sait que son numéro est arrivé',
      hi: 'जानता है कि उसका नंबर पहुँचा',
      id: 'Tahu nomornya sudah sampai',
      pt: 'Sabe que seu número chegou',
    },
    'fact.clientKnowsY': {
      en: "Has the server's number",
      ko: '서버 번호를 받았다',
      ja: 'サーバーの番号を受け取った',
      zh: '已收到服务器的编号',
      ar: 'استلم رقم الخادم',
      es: 'Tiene el número del servidor',
      fr: 'A reçu le numéro du serveur',
      hi: 'सर्वर का नंबर मिल गया',
      id: 'Sudah menerima nomor server',
      pt: 'Tem o número do servidor',
    },
    'fact.serverKnowsYAcked': {
      en: 'Knows its number arrived',
      ko: '내 번호가 닿은 것을 안다',
      ja: '自分の番号が届いたと知っている',
      zh: '知道自己的编号已送达',
      ar: 'يعلم أن رقمه وصل',
      es: 'Sabe que su número llegó',
      fr: 'Sait que son numéro est arrivé',
      hi: 'जानता है कि उसका नंबर पहुँचा',
      id: 'Tahu nomornya sudah sampai',
      pt: 'Sabe que seu número chegou',
    },
    'caption.start': {
      en: 'No message sent yet. Slots to fill on each side: {n}',
      ko: '아직 보낸 메시지가 없다. 끝마다 채울 칸: {n}',
      ja: 'まだメッセージは送られていない。各側で埋める枠: {n}',
      zh: '尚未发送任何消息。每一方待填的格子：{n}',
      ar: 'لم تُرسل أي رسالة بعد. الخانات التي يملؤها كل طرف: {n}',
      es: 'Aún no se ha enviado ningún mensaje. Casillas por llenar en cada lado: {n}',
      fr: 'Aucun message envoyé. Cases à remplir de chaque côté : {n}',
      hi: 'अभी कोई संदेश नहीं भेजा गया। हर पक्ष में भरने के खाने: {n}',
      id: 'Belum ada pesan terkirim. Kotak yang perlu diisi di tiap sisi: {n}',
      pt: 'Nenhuma mensagem enviada ainda. Casas a preencher em cada lado: {n}',
    },
    'caption.arrive': {
      en: 'Message {n} arrived: {flags}. Slots it filled: {k}',
      ko: '메시지 {n} 도착: {flags}. 이 메시지가 채운 칸: {k}',
      ja: 'メッセージ {n} 到着: {flags}。このメッセージが埋めた枠: {k}',
      zh: '消息 {n} 到达：{flags}。它填上的格子：{k}',
      ar: 'وصلت الرسالة {n}: {flags}. الخانات التي ملأتها: {k}',
      es: 'Llegó el mensaje {n}: {flags}. Casillas que llenó: {k}',
      fr: 'Message {n} arrivé : {flags}. Cases remplies : {k}',
      hi: 'संदेश {n} पहुँचा: {flags}। इसने भरे खाने: {k}',
      id: 'Pesan {n} tiba: {flags}. Kotak yang diisinya: {k}',
      pt: 'Mensagem {n} chegou: {flags}. Casas que preencheu: {k}',
    },
    'caption.count': {
      en: 'Filled: {filled}/{total} · Empty: {empty}',
      ko: '채운 칸: {filled}/{total} · 빈 칸: {empty}',
      ja: '埋まった枠: {filled}/{total} · 空き: {empty}',
      zh: '已填：{filled}/{total} · 空：{empty}',
      ar: 'المملوءة: {filled}/{total} · الفارغة: {empty}',
      es: 'Llenas: {filled}/{total} · Vacías: {empty}',
      fr: 'Remplies : {filled}/{total} · Vides : {empty}',
      hi: 'भरे: {filled}/{total} · खाली: {empty}',
      id: 'Terisi: {filled}/{total} · Kosong: {empty}',
      pt: 'Preenchidas: {filled}/{total} · Vazias: {empty}',
    },
    'caption.waiting': {
      en: 'Not open yet: {sides}',
      ko: '아직 열리지 않은 쪽: {sides}',
      ja: 'まだ開いていない側: {sides}',
      zh: '尚未打开的一方：{sides}',
      ar: 'لم يُفتح بعد: {sides}',
      es: 'Aún sin abrir: {sides}',
      fr: 'Pas encore ouvert : {sides}',
      hi: 'अभी नहीं खुला: {sides}',
      id: 'Belum terbuka: {sides}',
      pt: 'Ainda não aberto: {sides}',
    },
    'caption.open': {
      en: 'Open on both sides: {state}',
      ko: '양쪽 다 열림: {state}',
      ja: '両側とも開いた: {state}',
      zh: '双方均已打开：{state}',
      ar: 'مفتوح لدى الطرفين: {state}',
      es: 'Abierto en ambos lados: {state}',
      fr: 'Ouvert des deux côtés : {state}',
      hi: 'दोनों ओर खुला: {state}',
      id: 'Terbuka di kedua sisi: {state}',
      pt: 'Aberto dos dois lados: {state}',
    },
  },
  blocks: {
    stage: { type: 'three-way-sync-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
