import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 프로세스는 어떤 길로만 상태를 옮겨 다니는가.
 *
 * 프로세스 하나가 원인 하나를 받을 때마다 옮김표를 따라 한 칸 건너간다. 같은 실행 상태에서도
 * 원인이 건너갈 곳을 가르고, 대기를 벗어나면 실행이 아니라 준비로 내려앉는다.
 */
export const stateTransitionsFacet: FacetJson = {
  id: 'facet:stateTransitions',
  title: {
    en: 'Process state transitions',
    ko: '프로세스 상태 전이',
    ja: 'プロセスの状態遷移',
    zh: '进程状态转换',
    ar: 'انتقالات حالة العملية',
    es: 'Transiciones de estado de un proceso',
    fr: 'Transitions d’état d’un processus',
    hi: 'प्रक्रिया की अवस्था के बदलाव',
    id: 'Transisi status proses',
    pt: 'Transições de estado de um processo',
  },
  description: {
    en: 'Each cause moves one process one step along the transition table. From Running, the cause decides where it goes; leaving Waiting always lands in Ready.',
    ko: '원인 하나마다 프로세스 하나가 옮김표를 따라 한 칸 건너간다. 실행에서는 원인이 갈 곳을 가르고, 대기를 벗어나면 늘 준비로 내려앉는다.',
    ja: '原因が一つ来るたびに、プロセスは遷移表に沿って一つ先の状態へ移る。実行中からは原因が行き先を分け、待機を抜けると必ず実行可能に戻る。',
    zh: '每来一个原因，进程就沿着转换表移动一步。从运行出发，原因决定去向；离开等待时总是回到就绪。',
    ar: 'مع كل سبب تنتقل العملية خطوة واحدة على جدول الانتقالات. من حالة التشغيل يحدد السبب الوجهة، والخروج من الانتظار ينتهي دائمًا في حالة الجاهزية.',
    es: 'Cada causa mueve un proceso un paso por la tabla de transiciones. Desde En ejecución, la causa decide el destino; al salir de En espera siempre llega a Listo.',
    fr: 'Chaque cause fait avancer un processus d’un pas dans la table de transitions. Depuis En cours, la cause décide de la destination ; en quittant En attente, il revient toujours à Prêt.',
    hi: 'हर कारण पर प्रक्रिया बदलाव-तालिका के सहारे एक कदम आगे जाती है। चालू अवस्था से कारण तय करता है कि कहाँ जाना है; प्रतीक्षा से निकलकर वह हमेशा तैयार में आती है।',
    id: 'Setiap penyebab memindahkan satu proses satu langkah menurut tabel transisi. Dari Berjalan, penyebab menentukan tujuannya; keluar dari Menunggu selalu mendarat di Siap.',
    pt: 'Cada causa move um processo um passo pela tabela de transições. A partir de Executando, a causa decide o destino; ao sair de Esperando, ele sempre volta a Pronto.',
  },
  algorithm: 'module:stateTransitions',
  scene: 'module:stateTransitionsScene',
  initialData: {
    type: 'state-transitions',
    states: ['new', 'ready', 'running', 'waiting', 'terminated'],
    start: 'new',
    table: [
      { from: 'new', cause: 'admit', to: 'ready' },
      { from: 'ready', cause: 'dispatch', to: 'running' },
      { from: 'running', cause: 'timer', to: 'ready' },
      { from: 'running', cause: 'io-request', to: 'waiting' },
      { from: 'waiting', cause: 'io-done', to: 'ready' },
      { from: 'running', cause: 'exit', to: 'terminated' },
    ],
    causes: ['admit', 'dispatch', 'timer', 'dispatch', 'io-request', 'io-done', 'dispatch', 'exit'],
    stepMs: 1400,
  },
  shuffleOnReset: false,
  messages: {
    'label.state.new': {
      en: 'New',
      ko: '생성',
      ja: '生成',
      zh: '新建',
      ar: 'جديدة',
      es: 'Nuevo',
      fr: 'Nouveau',
      hi: 'नई',
      id: 'Baru',
      pt: 'Novo',
    },
    'label.state.ready': {
      en: 'Ready',
      ko: '준비',
      ja: '実行可能',
      zh: '就绪',
      ar: 'جاهزة',
      es: 'Listo',
      fr: 'Prêt',
      hi: 'तैयार',
      id: 'Siap',
      pt: 'Pronto',
    },
    'label.state.running': {
      en: 'Running',
      ko: '실행',
      ja: '実行中',
      zh: '运行',
      ar: 'قيد التشغيل',
      es: 'En ejecución',
      fr: 'En cours',
      hi: 'चालू',
      id: 'Berjalan',
      pt: 'Executando',
    },
    'label.state.waiting': {
      en: 'Waiting',
      ko: '대기',
      ja: '待機',
      zh: '等待',
      ar: 'منتظرة',
      es: 'En espera',
      fr: 'En attente',
      hi: 'प्रतीक्षा',
      id: 'Menunggu',
      pt: 'Esperando',
    },
    'label.state.terminated': {
      en: 'Terminated',
      ko: '종료',
      ja: '終了',
      zh: '终止',
      ar: 'منتهية',
      es: 'Terminado',
      fr: 'Terminé',
      hi: 'समाप्त',
      id: 'Selesai',
      pt: 'Terminado',
    },
    'label.cause.admit': {
      en: 'Admit',
      ko: '받아들임',
      ja: '受け入れ',
      zh: '接纳',
      ar: 'قبول',
      es: 'Admisión',
      fr: 'Admission',
      hi: 'प्रवेश',
      id: 'Diterima',
      pt: 'Admissão',
    },
    'label.cause.dispatch': {
      en: 'Dispatch',
      ko: '골라짐',
      ja: '選ばれる',
      zh: '调度',
      ar: 'إرسال',
      es: 'Despacho',
      fr: 'Élection',
      hi: 'चयन',
      id: 'Dijadwalkan',
      pt: 'Despacho',
    },
    'label.cause.timer': {
      en: 'Timer',
      ko: '타이머',
      ja: 'タイマー',
      zh: '定时器',
      ar: 'المؤقت',
      es: 'Temporizador',
      fr: 'Minuteur',
      hi: 'टाइमर',
      id: 'Pewaktu',
      pt: 'Temporizador',
    },
    'label.cause.ioRequest': {
      en: 'I/O request',
      ko: '입출력 요청',
      ja: '入出力要求',
      zh: 'I/O 请求',
      ar: 'طلب إدخال/إخراج',
      es: 'Petición de E/S',
      fr: 'Demande d’E/S',
      hi: 'I/O अनुरोध',
      id: 'Minta I/O',
      pt: 'Pedido de E/S',
    },
    'label.cause.ioDone': {
      en: 'I/O done',
      ko: '입출력 끝',
      ja: '入出力完了',
      zh: 'I/O 完成',
      ar: 'انتهاء الإدخال/الإخراج',
      es: 'Fin de E/S',
      fr: 'Fin d’E/S',
      hi: 'I/O पूरा',
      id: 'I/O selesai',
      pt: 'Fim de E/S',
    },
    'label.cause.exit': {
      en: 'Exit',
      ko: '끝냄',
      ja: '終了要求',
      zh: '退出',
      ar: 'خروج',
      es: 'Salida',
      fr: 'Sortie',
      hi: 'निकास',
      id: 'Keluar',
      pt: 'Saída',
    },
    'caption.start': {
      en: 'Starts in: {state}.',
      ko: '시작 상태: {state}.',
      ja: '開始状態: {state}。',
      zh: '起始状态：{state}。',
      ar: 'الحالة الأولى: {state}.',
      es: 'Estado inicial: {state}.',
      fr: 'État de départ : {state}.',
      hi: 'शुरुआती अवस्था: {state}।',
      id: 'Status awal: {state}.',
      pt: 'Estado inicial: {state}.',
    },
    'caption.cross': {
      en: 'Ways out of {from}: {n}. {cause} leads to {to}.',
      ko: '{from}에서 나가는 길: {n}. {cause} → {to}.',
      ja: '{from} から出る道: {n}。{cause} → {to}。',
      zh: '从 {from} 出去的路：{n}。{cause} → {to}。',
      ar: 'طرق الخروج من {from}: {n}. {cause} يؤدي إلى {to}.',
      es: 'Salidas de {from}: {n}. {cause} lleva a {to}.',
      fr: 'Sorties de {from} : {n}. {cause} mène à {to}.',
      hi: '{from} से निकलने के रास्ते: {n}। {cause} से {to}।',
      id: 'Jalan keluar dari {from}: {n}. {cause} menuju {to}.',
      pt: 'Saídas de {from}: {n}. {cause} leva a {to}.',
    },
    'caption.end': {
      en: 'Ways out of {state}: {n}. Moves: {moves} · roads used: {used}/{total}.',
      ko: '{state}에서 나가는 길: {n}. 건넌 횟수: {moves} · 지난 길: {used}/{total}.',
      ja: '{state} から出る道: {n}。移った回数: {moves} · 通った道: {used}/{total}。',
      zh: '从 {state} 出去的路：{n}。移动次数：{moves} · 走过的路：{used}/{total}。',
      ar: 'طرق الخروج من {state}: {n}. عدد الانتقالات: {moves} · الطرق المسلوكة: {used}/{total}.',
      es: 'Salidas de {state}: {n}. Pasos: {moves} · caminos usados: {used}/{total}.',
      fr: 'Sorties de {state} : {n}. Passages : {moves} · chemins empruntés : {used}/{total}.',
      hi: '{state} से निकलने के रास्ते: {n}। बदलाव: {moves} · चले गए रास्ते: {used}/{total}।',
      id: 'Jalan keluar dari {state}: {n}. Perpindahan: {moves} · jalan terpakai: {used}/{total}.',
      pt: 'Saídas de {state}: {n}. Passagens: {moves} · caminhos usados: {used}/{total}.',
    },
  },
  blocks: {
    stage: { type: 'state-transitions-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
