/**
 * self-attention 선언 — 같은 W_Q · W_K · W_V 를 머리 하나로 읽나, 열을 나눠 머리 둘로 읽나.
 *
 * initialData 는 1차 구조(토큰 · x · 행렬 · 머리 수 사다리)만 담는다. q · k · v · 점수 · 무게 · 짝 ·
 * 결과는 알고리즘이 셈한다. 토큰 기호는 식별자이자 표시라 번역하지 않는다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export type SelfAttentionInitialData = {
  type: 'self-attention';
  stepMs: number;
  tokens: string[];
  x: number[][];
  wq: number[][];
  wk: number[][];
  wv: number[][];
  headsLadder: number[];
  heads: number;
};

const initialData: SelfAttentionInitialData = {
  type: 'self-attention',
  stepMs: 2200,
  tokens: ['A', 'B', 'C', 'D'],
  x: [
    [2, 1, 2, 0],
    [-1, 2, 0, 3],
    [-2, -1, -2, 1],
    [1, -2, 1, -2],
  ],
  wq: [
    [1, 0, -1, 0],
    [0, 1, 0, -1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
  ],
  wk: [
    [0, -1, 1, 0],
    [1, 0, 0, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
  ],
  wv: [
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
  ],
  headsLadder: [1, 2],
  heads: 1,
};

export const selfAttentionFacet: FacetJson = {
  id: 'facet:selfAttention',
  title: {
    en: 'Self-Attention and Multi-Head',
    ko: '셀프 어텐션과 멀티 헤드',
    ja: 'セルフアテンションとマルチヘッド',
    zh: '自注意力与多头',
    ar: 'الانتباه الذاتي والرؤوس المتعددة',
    es: 'Autoatención y multicabeza',
    fr: 'Auto-attention et multi-tête',
    hi: 'सेल्फ़-अटेंशन और मल्टी-हेड',
    id: 'Self-attention dan multi-head',
    pt: 'Autoatenção e multi-cabeça',
  },
  description: {
    en: 'Four tokens attend to one another through the same projection matrices, read as one head or with their columns split into two heads.',
    ko: '토큰 넷이 같은 투영 행렬로 서로를 본다 — 머리 하나로 읽거나, 열을 나눠 머리 둘로 읽는다.',
    ja: '4つのトークンが同じ射影行列で互いを参照する。1つのヘッドで読むか、列を分けて2つのヘッドで読む。',
    zh: '四个词元通过同一组投影矩阵相互关注——用一个头读取，或把列分成两个头读取。',
    ar: 'أربعة رموز ينتبه كل منها إلى الآخر عبر مصفوفات الإسقاط نفسها، تُقرأ برأس واحد أو بتقسيم أعمدتها إلى رأسين.',
    es: 'Cuatro tokens se atienden entre sí con las mismas matrices de proyección, leídas con una cabeza o con sus columnas repartidas en dos cabezas.',
    fr: 'Quatre jetons s’observent mutuellement avec les mêmes matrices de projection, lues par une seule tête ou avec leurs colonnes réparties en deux têtes.',
    hi: 'चार टोकन एक ही प्रोजेक्शन मैट्रिक्स से एक-दूसरे को देखते हैं — एक हेड से पढ़ें या कॉलम बाँटकर दो हेड से।',
    id: 'Empat token saling memperhatikan melalui matriks proyeksi yang sama, dibaca dengan satu head atau dengan kolom yang dibagi menjadi dua head.',
    pt: 'Quatro tokens atendem uns aos outros pelas mesmas matrizes de projeção, lidas com uma cabeça ou com as colunas divididas em duas cabeças.',
  },
  algorithm: 'module:selfAttention',
  projector: 'module:selfAttentionProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 16,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'self-attention-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'heads',
          name: 'heads',
          label: {
            en: 'Heads',
            ko: '머리 수',
            ja: 'ヘッド数',
            zh: '头数',
            ar: 'عدد الرؤوس',
            es: 'Cabezas',
            fr: 'Têtes',
            hi: 'हेड की संख्या',
            id: 'Jumlah head',
            pt: 'Cabeças',
          },
          segments: [
            { value: 1, label: '1', default: true },
            { value: 2, label: '2' },
          ],
        },
      ],
      metrics: [
        {
          name: 'clear-rows',
          label: {
            en: 'Rows with a lone pair',
            ko: '짝이 홀로 선 줄',
            ja: 'ペアが単独の行',
            zh: '配对唯一的行',
            ar: 'صفوف بزوج منفرد',
            es: 'Filas con par único',
            fr: 'Lignes à paire unique',
            hi: 'अकेली जोड़ी वाली पंक्तियाँ',
            id: 'Baris berpasangan tunggal',
            pt: 'Linhas com par único',
          },
          initial: 0,
        },
        {
          name: 'tied-rows',
          label: {
            en: 'Rows with tied pairs',
            ko: '짝이 동률인 줄',
            ja: 'ペアが同点の行',
            zh: '配对并列的行',
            ar: 'صفوف بأزواج متعادلة',
            es: 'Filas con pares empatados',
            fr: 'Lignes à paires ex aequo',
            hi: 'बराबर जोड़ियों वाली पंक्तियाँ',
            id: 'Baris berpasangan seri',
            pt: 'Linhas com pares empatados',
          },
          initial: 0,
        },
        {
          name: 'weight-count',
          label: {
            en: 'Projection weights',
            ko: '투영 무게 수',
            ja: '射影の重み数',
            zh: '投影权重数',
            ar: 'أوزان الإسقاط',
            es: 'Pesos de proyección',
            fr: 'Poids de projection',
            hi: 'प्रोजेक्शन भार',
            id: 'Bobot proyeksi',
            pt: 'Pesos de projeção',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:self-attention-imperative',
      label: {
        en: 'Multi-head attention',
        ko: '멀티 헤드 어텐션',
        ja: 'マルチヘッドアテンション',
        zh: '多头注意力',
        ar: 'الانتباه متعدد الرؤوس',
        es: 'Atención multicabeza',
        fr: 'Attention multi-tête',
        hi: 'मल्टी-हेड अटेंशन',
        id: 'Atensi multi-head',
        pt: 'Atenção multi-cabeça',
      },
    },
  },
  messages: {
    'caption.frame': {
      en: 'Input {x} per token · projection columns grouped by head',
      ko: '토큰마다 입력 {x} · 투영 칸을 머리마다 무리 짓는다',
      ja: 'トークンごとの入力 {x} · 射影の列をヘッドごとにまとめる',
      zh: '每个词元的输入 {x} · 投影列按头分组',
      ar: 'المدخل {x} لكل رمز · أعمدة الإسقاط مجمّعة حسب الرأس',
      es: 'Entrada {x} por token · columnas de proyección agrupadas por cabeza',
      fr: 'Entrée {x} par jeton · colonnes de projection groupées par tête',
      hi: 'हर टोकन का इनपुट {x} · प्रोजेक्शन कॉलम हेड के अनुसार समूहित',
      id: 'Masukan {x} per token · kolom proyeksi dikelompokkan per head',
      pt: 'Entrada {x} por token · colunas de projeção agrupadas por cabeça',
    },
    'caption.project': {
      en: 'Projection: {q} · {k} · {v} for every token at once',
      ko: '투영 — 모든 토큰에서 {q} · {k} · {v} 셋이 한꺼번에',
      ja: '射影 — すべてのトークンの {q} · {k} · {v} を一度に',
      zh: '投影——所有词元的 {q} · {k} · {v} 一次算出',
      ar: 'الإسقاط: {q} · {k} · {v} لكل الرموز دفعة واحدة',
      es: 'Proyección: {q} · {k} · {v} de todos los tokens a la vez',
      fr: 'Projection : {q} · {k} · {v} de tous les jetons à la fois',
      hi: 'प्रोजेक्शन: सभी टोकन के {q} · {k} · {v} एक साथ',
      id: 'Proyeksi: {q} · {k} · {v} untuk semua token sekaligus',
      pt: 'Projeção: {q} · {k} · {v} de todos os tokens de uma vez',
    },
    'caption.score': {
      en: 'Scores: {qk} divided by {sqrtDk}, every head and every row at once',
      ko: '점수 — 모든 머리 · 모든 줄에서 {qk} 나누기 {sqrtDk}',
      ja: 'スコア — すべてのヘッド · すべての行で {qk} ÷ {sqrtDk}',
      zh: '分数——所有头 · 所有行同时计算 {qk} 除以 {sqrtDk}',
      ar: 'الدرجات: {qk} مقسومًا على {sqrtDk} لكل رأس وكل صف دفعة واحدة',
      es: 'Puntuaciones: {qk} dividido entre {sqrtDk}, en todas las cabezas y filas a la vez',
      fr: 'Scores : {qk} divisé par {sqrtDk}, pour toutes les têtes et lignes à la fois',
      hi: 'स्कोर: {qk} भाग {sqrtDk}, सभी हेड और सभी पंक्तियों में एक साथ',
      id: 'Skor: {qk} dibagi {sqrtDk}, untuk semua head dan baris sekaligus',
      pt: 'Pontuações: {qk} dividido por {sqrtDk}, em todas as cabeças e linhas de uma vez',
    },
    'caption.softmax': {
      en: 'Weights: {softmax} across each row',
      ko: '무게 — 줄마다 {softmax}',
      ja: '重み — 行ごとに {softmax}',
      zh: '权重——每行做 {softmax}',
      ar: 'الأوزان: {softmax} على كل صف',
      es: 'Pesos: {softmax} en cada fila',
      fr: 'Poids : {softmax} sur chaque ligne',
      hi: 'भार: हर पंक्ति पर {softmax}',
      id: 'Bobot: {softmax} di setiap baris',
      pt: 'Pesos: {softmax} em cada linha',
    },
    'caption.pick': {
      en: 'Pairs: the largest {qk} in each row, compared as integers',
      ko: '짝 — 줄마다 가장 큰 {qk}, 정수로 견준다',
      ja: 'ペア — 行ごとに最大の {qk}、整数で比べる',
      zh: '配对——每行最大的 {qk}，按整数比较',
      ar: 'الأزواج: أكبر {qk} في كل صف، بمقارنة الأعداد الصحيحة',
      es: 'Pares: el mayor {qk} de cada fila, comparado como entero',
      fr: 'Paires : le plus grand {qk} de chaque ligne, comparé en entiers',
      hi: 'जोड़ियाँ: हर पंक्ति का सबसे बड़ा {qk}, पूर्णांकों से तुलना',
      id: 'Pasangan: {qk} terbesar di setiap baris, dibandingkan sebagai bilangan bulat',
      pt: 'Pares: o maior {qk} de cada linha, comparado como inteiro',
    },
    'caption.mix': {
      en: 'Result: weights times {v}, summed; head results joined per token',
      ko: '결과 — 무게 곱하기 {v} 의 합 · 머리 결과를 토큰마다 잇는다',
      ja: '結果 — 重み × {v} の和 · ヘッドの結果をトークンごとにつなぐ',
      zh: '结果——权重乘 {v} 求和 · 各头结果按词元拼接',
      ar: 'النتيجة: مجموع الأوزان مضروبة في {v}، وتُوصل نتائج الرؤوس لكل رمز',
      es: 'Resultado: suma de pesos por {v}; resultados de cabezas unidos por token',
      fr: 'Résultat : somme des poids fois {v} ; résultats des têtes joints par jeton',
      hi: 'परिणाम: भार गुणा {v} का योग; हेड के परिणाम हर टोकन पर जोड़े गए',
      id: 'Hasil: jumlah bobot kali {v}; hasil tiap head disambung per token',
      pt: 'Resultado: soma dos pesos vezes {v}; resultados das cabeças unidos por token',
    },
    'info.frame': {
      en: 'heads {h} · {dkSym} {dk} · {sqrtSym} {s}',
      ko: '머리 수 {h} · {dkSym} {dk} · {sqrtSym} {s}',
      ja: 'ヘッド数 {h} · {dkSym} {dk} · {sqrtSym} {s}',
      zh: '头数 {h} · {dkSym} {dk} · {sqrtSym} {s}',
      ar: 'الرؤوس {h} · {dkSym} {dk} · {sqrtSym} {s}',
      es: 'cabezas {h} · {dkSym} {dk} · {sqrtSym} {s}',
      fr: 'têtes {h} · {dkSym} {dk} · {sqrtSym} {s}',
      hi: 'हेड {h} · {dkSym} {dk} · {sqrtSym} {s}',
      id: 'head {h} · {dkSym} {dk} · {sqrtSym} {s}',
      pt: 'cabeças {h} · {dkSym} {dk} · {sqrtSym} {s}',
    },
    'label.result': {
      en: 'result',
      ko: '결과',
      ja: '結果',
      zh: '结果',
      ar: 'النتيجة',
      es: 'resultado',
      fr: 'résultat',
      hi: 'परिणाम',
      id: 'hasil',
      pt: 'resultado',
    },
    'label.axes': {
      en: 'rows: query · columns: key',
      ko: '줄: 물음 · 칸: 열쇠',
      ja: '行: クエリ · 列: キー',
      zh: '行：查询 · 列：键',
      ar: 'الصفوف: الاستعلام · الأعمدة: المفتاح',
      es: 'filas: consulta · columnas: clave',
      fr: 'lignes : requête · colonnes : clé',
      hi: 'पंक्तियाँ: क्वेरी · कॉलम: कुंजी',
      id: 'baris: kueri · kolom: kunci',
      pt: 'linhas: consulta · colunas: chave',
    },
    'label.headCols': {
      en: 'head {h} · columns {a}–{b}',
      ko: '머리 {h} · 열 {a}–{b}',
      ja: 'ヘッド {h} · 列 {a}–{b}',
      zh: '头 {h} · 列 {a}–{b}',
      ar: 'الرأس {h} · الأعمدة {a}–{b}',
      es: 'cabeza {h} · columnas {a}–{b}',
      fr: 'tête {h} · colonnes {a}–{b}',
      hi: 'हेड {h} · कॉलम {a}–{b}',
      id: 'head {h} · kolom {a}–{b}',
      pt: 'cabeça {h} · colunas {a}–{b}',
    },
    'label.pairTied': {
      en: 'tie {keys}',
      ko: '동률 {keys}',
      ja: '同点 {keys}',
      zh: '并列 {keys}',
      ar: 'تعادل {keys}',
      es: 'empate {keys}',
      fr: 'égalité {keys}',
      hi: 'बराबरी {keys}',
      id: 'seri {keys}',
      pt: 'empate {keys}',
    },
    'label.pairClear': {
      en: 'pair {keys}',
      ko: '짝 {keys}',
      ja: 'ペア {keys}',
      zh: '配对 {keys}',
      ar: 'الزوج {keys}',
      es: 'par {keys}',
      fr: 'paire {keys}',
      hi: 'जोड़ी {keys}',
      id: 'pasangan {keys}',
      pt: 'par {keys}',
    },
    'stat.clear': {
      en: 'rows whose pair stands alone',
      ko: '짝이 홀로 선 줄',
      ja: 'ペアが単独の行',
      zh: '配对唯一的行',
      ar: 'صفوف زوجها منفرد',
      es: 'filas con par único',
      fr: 'lignes à paire unique',
      hi: 'अकेली जोड़ी वाली पंक्तियाँ',
      id: 'baris berpasangan tunggal',
      pt: 'linhas com par único',
    },
    'stat.tied': {
      en: 'rows whose pairs tie',
      ko: '짝이 동률인 줄',
      ja: 'ペアが同点の行',
      zh: '配对并列的行',
      ar: 'صفوف أزواجها متعادلة',
      es: 'filas con pares empatados',
      fr: 'lignes à paires ex aequo',
      hi: 'बराबर जोड़ियों वाली पंक्तियाँ',
      id: 'baris berpasangan seri',
      pt: 'linhas com pares empatados',
    },
    'stat.topWeight': {
      en: 'smallest of the row-top weights',
      ko: '줄마다 가장 큰 무게의 최솟값',
      ja: '行ごとの最大の重みのうち最小',
      zh: '各行最大权重中的最小值',
      ar: 'أصغر أكبر وزن بين الصفوف',
      es: 'menor de los pesos máximos por fila',
      fr: 'plus petit des poids maximaux par ligne',
      hi: 'हर पंक्ति के सबसे बड़े भार में सबसे छोटा',
      id: 'terkecil dari bobot terbesar tiap baris',
      pt: 'menor dos pesos máximos por linha',
    },
    'value.ofTotal': {
      en: '{n} / {total}',
      ko: '{n} / {total}',
      ja: '{n} / {total}',
      zh: '{n} / {total}',
      ar: '{n} / {total}',
      es: '{n} / {total}',
      fr: '{n} / {total}',
      hi: '{n} / {total}',
      id: '{n} / {total}',
      pt: '{n} / {total}',
    },
    'sym.x': {
      en: 'x',
      ko: 'x',
      ja: 'x',
      zh: 'x',
      ar: 'x',
      es: 'x',
      fr: 'x',
      hi: 'x',
      id: 'x',
      pt: 'x',
    },
    'sym.q': {
      en: 'q',
      ko: 'q',
      ja: 'q',
      zh: 'q',
      ar: 'q',
      es: 'q',
      fr: 'q',
      hi: 'q',
      id: 'q',
      pt: 'q',
    },
    'sym.k': {
      en: 'k',
      ko: 'k',
      ja: 'k',
      zh: 'k',
      ar: 'k',
      es: 'k',
      fr: 'k',
      hi: 'k',
      id: 'k',
      pt: 'k',
    },
    'sym.v': {
      en: 'v',
      ko: 'v',
      ja: 'v',
      zh: 'v',
      ar: 'v',
      es: 'v',
      fr: 'v',
      hi: 'v',
      id: 'v',
      pt: 'v',
    },
    'sym.qk': {
      en: 'q·k',
      ko: 'q·k',
      ja: 'q·k',
      zh: 'q·k',
      ar: 'q·k',
      es: 'q·k',
      fr: 'q·k',
      hi: 'q·k',
      id: 'q·k',
      pt: 'q·k',
    },
    'sym.dk': {
      en: 'd_k',
      ko: 'd_k',
      ja: 'd_k',
      zh: 'd_k',
      ar: 'd_k',
      es: 'd_k',
      fr: 'd_k',
      hi: 'd_k',
      id: 'd_k',
      pt: 'd_k',
    },
    'sym.sqrtDk': {
      en: '√d_k',
      ko: '√d_k',
      ja: '√d_k',
      zh: '√d_k',
      ar: '√d_k',
      es: '√d_k',
      fr: '√d_k',
      hi: '√d_k',
      id: '√d_k',
      pt: '√d_k',
    },
    'sym.softmax': {
      en: 'softmax',
      ko: 'softmax',
      ja: 'softmax',
      zh: 'softmax',
      ar: 'softmax',
      es: 'softmax',
      fr: 'softmax',
      hi: 'softmax',
      id: 'softmax',
      pt: 'softmax',
    },
  },
};
