/**
 * trie — 접두사 나무 완결형 선언.
 *
 * 조각 둘(`sharePrefixPath` · `walkPerCharacter`)이 넣기와 찾기를 덮는다.
 * 이 완제품이 더하는 것은 **trie 를 쓰는 까닭** 자체다 — 자동완성, 그리고
 * 지울 때 남는 것.
 *
 * 식별자 (C1): `node:<id>`. id 는 뿌리에서 내려온 글자를 이은 것이라 그 자체로
 * 접두사다.
 */

import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL } from '@ffacet/core/runtime';

export const trieFacet: FacetJson = {
  id: 'facet:trie',
  // 제목은 카탈로그 카드의 이름과 같다 (C4).
  title: {
    en: 'Trie',
    ko: 'Trie',
    ja: 'トライ木',
    zh: '字典树',
    ar: 'شجرة البادئات',
    es: 'Trie',
    fr: 'Trie',
    hi: 'ट्राई',
    id: 'Trie',
    pt: 'Trie',
  },
  description: {
    en: 'Words that start alike share one path — so a prefix finds them all at once.',
    ko: '앞이 같은 낱말은 한 길을 함께 쓴다 — 그래서 접두사 하나로 한꺼번에 찾는다',
    ja: '出だしが同じ語は一本の道を共有する — だから接頭辞ひとつでまとめて見つかる。',
    zh: '开头相同的词共用一条路径 — 所以一个前缀就能一次全找到。',
    ar: 'الكلمات المتشابهة البداية تتشارك مسارًا واحدًا — فبادئة واحدة تجدها كلها.',
    es: 'Las palabras que empiezan igual comparten un camino: un prefijo las encuentra todas.',
    fr: 'Les mots qui commencent pareil partagent un chemin — un préfixe les trouve tous.',
    hi: 'एक जैसे शुरू होने वाले शब्द एक ही रास्ता साझा करते हैं — इसलिए एक उपसर्ग सबको ढूँढ लेता है।',
    id: 'Kata yang berawal sama berbagi satu jalur — jadi satu awalan menemukan semuanya.',
    pt: 'Palavras que começam igual partilham um caminho — um prefixo acha todas de uma vez.',
  },
  algorithm: 'module:trie',
  projector: 'module:trieProjector',
  initialData: {
    type: 'trie',
    // 앞을 나눠 쓰는 것과 아예 갈라지는 것이 함께 있어야 공유가 보인다.
    // 'do' 와 'dog' 은 하나가 다른 하나의 접두사인 경우다.
    seed: ['car', 'cart', 'cat', 'do', 'dog'],
    // 나무의 깊이를 이것이 정한다. stage 의 RESERVE_DEPTH 와 같아야 한다.
    maxLength: 6,
    stepMs: 420,
  },
  shuffleOnReset: false,
  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { type: 'row', gap: 8, children: [{ ref: 'resultHud' }, { ref: 'sizeHud' }] },
      { ref: 'controls' },
    ],
  },
  messages: {
    'caption.empty': {
      en: 'Nothing here yet.',
      ko: '아직 아무것도 없다.',
      ja: 'まだ何もありません。',
      zh: '这里还什么都没有。',
      ar: 'لا شيء هنا بعد.',
      es: 'Aún no hay nada.',
      fr: 'Rien pour le moment.',
      hi: 'यहाँ अभी कुछ नहीं है।',
      id: 'Belum ada apa-apa.',
      pt: 'Ainda não há nada.',
    },
    'caption.start': {
      en: 'Adding words — matching letters reuse the same path.',
      ko: '낱말을 넣는다 — 글자가 같은 동안은 같은 길을 다시 쓴다',
      ja: '語を入れていく — 文字が同じ間は同じ道を使い回す。',
      zh: '正在加入词 — 字母相同的部分复用同一条路。',
      ar: 'نضيف كلمات — الحروف المتطابقة تعيد استخدام المسار نفسه.',
      es: 'Añadiendo palabras: las letras iguales reutilizan el mismo camino.',
      fr: 'Ajout de mots — les lettres identiques réutilisent le même chemin.',
      hi: 'शब्द जोड़े जा रहे हैं — समान अक्षर वही रास्ता दोबारा उपयोग करते हैं।',
      id: 'Menambah kata — huruf yang sama memakai ulang jalur yang sama.',
      pt: 'Adicionando palavras — letras iguais reutilizam o mesmo caminho.',
    },
    'caption.ride': {
      en: "'{ch}' is already on the path — ride it.",
      ko: "'{ch}' 는 이미 길에 있다 — 그대로 탄다",
      ja: "'{ch}' はすでに道にある — そのまま進む。",
      zh: "'{ch}' 已在路径上 — 直接沿用。",
      ar: "'{ch}' موجود على المسار — نسير عليه.",
      es: "'{ch}' ya está en el camino: lo aprovechamos.",
      fr: "'{ch}' est déjà sur le chemin — on l'emprunte.",
      hi: "'{ch}' पहले से रास्ते पर है — उसी पर चलें।",
      id: "'{ch}' sudah ada di jalur — pakai saja.",
      pt: "'{ch}' já está no caminho — siga por ele.",
    },
    'caption.grow': {
      en: "'{ch}' is new — a branch sprouts here.",
      ko: "'{ch}' 는 처음이다 — 여기서 가지가 돋는다",
      ja: "'{ch}' は初めて — ここで枝が生える。",
      zh: "'{ch}' 是新的 — 这里长出一条分支。",
      ar: "'{ch}' جديد — ينبت فرع هنا.",
      es: "'{ch}' es nueva: aquí brota una rama.",
      fr: "'{ch}' est nouvelle — une branche pousse ici.",
      hi: "'{ch}' नया है — यहाँ एक शाखा फूटती है।",
      id: "'{ch}' baru — cabang tumbuh di sini.",
      pt: "'{ch}' é nova — um ramo brota aqui.",
    },
    'caption.step': {
      en: "Follow '{ch}' — one step down.",
      ko: "'{ch}' 를 따라 한 칸 내려간다",
      ja: "'{ch}' をたどって一段下る。",
      zh: "沿 '{ch}' 向下一格。",
      ar: "نتبع '{ch}' — درجة واحدة للأسفل.",
      es: "Sigue '{ch}': un paso abajo.",
      fr: "Suivre '{ch}' — un cran plus bas.",
      hi: "'{ch}' का अनुसरण करें — एक कदम नीचे।",
      id: "Ikuti '{ch}' — turun satu.",
      pt: "Siga '{ch}' — um passo abaixo.",
    },
    'caption.isWord': {
      en: '"{w}" ends here — it is a word.',
      ko: '"{w}" 가 여기서 끝난다 — 낱말이다',
      ja: '"{w}" はここで終わる — 語だ。',
      zh: '"{w}" 到此结束 — 这是一个词。',
      ar: '"{w}" ينتهي هنا — إنها كلمة.',
      es: '"{w}" termina aquí: es una palabra.',
      fr: '"{w}" se termine ici — c\'est un mot.',
      hi: '"{w}" यहाँ समाप्त — यह एक शब्द है।',
      id: '"{w}" berakhir di sini — ini kata.',
      pt: '"{w}" termina aqui — é uma palavra.',
    },
    'caption.notWord': {
      en: 'The path exists, but no word ends here.',
      ko: '길은 있는데 여기서 끝나는 낱말이 없다',
      ja: '道はあるが、ここで終わる語はない。',
      zh: '路径存在，但没有词在此结束。',
      ar: 'المسار موجود، لكن لا كلمة تنتهي هنا.',
      es: 'El camino existe, pero ninguna palabra acaba aquí.',
      fr: 'Le chemin existe, mais aucun mot ne s\'y termine.',
      hi: 'रास्ता है, पर यहाँ कोई शब्द समाप्त नहीं होता।',
      id: 'Jalurnya ada, tapi tak ada kata yang berakhir di sini.',
      pt: 'O caminho existe, mas nenhuma palavra termina aqui.',
    },
    'caption.noBranch': {
      en: "No '{ch}' branch — it stops here.",
      ko: "'{ch}' 가지가 없다 — 여기서 멈춘다",
      ja: "'{ch}' の枝がない — ここで止まる。",
      zh: "没有 '{ch}' 分支 — 到此为止。",
      ar: "لا فرع لـ '{ch}' — نتوقف هنا.",
      es: "No hay rama '{ch}': se detiene aquí.",
      fr: "Pas de branche '{ch}' — on s'arrête ici.",
      hi: "'{ch}' शाखा नहीं — यहीं रुक जाता है।",
      id: "Tak ada cabang '{ch}' — berhenti di sini.",
      pt: "Sem ramo '{ch}' — para aqui.",
    },
    'caption.collect': {
      en: '{n} words start with "{p}".',
      ko: '"{p}" 로 시작하는 낱말이 {n} 개다',
      ja: '"{p}" で始まる語が {n} 個。',
      zh: '以 "{p}" 开头的词有 {n} 个。',
      ar: '{n} كلمات تبدأ بـ "{p}".',
      es: '{n} palabras empiezan por "{p}".',
      fr: '{n} mots commencent par "{p}".',
      hi: '"{p}" से शुरू होने वाले {n} शब्द।',
      id: '{n} kata diawali "{p}".',
      pt: '{n} palavras começam com "{p}".',
    },
    'caption.prune': {
      en: '"{w}" removed; {n} seats freed — the rest are shared.',
      ko: '"{w}" 를 지웠다. 걷어낸 자리는 {n} 개 — 나머지는 다른 낱말이 쓴다',
      ja: '"{w}" を削除。空いた席は {n} 個 — 残りは他の語が使っている。',
      zh: '删除 "{w}"，释放 {n} 个位置 — 其余仍被共享。',
      ar: 'حُذفت "{w}"؛ تحررت {n} مواضع — والباقي مشترك.',
      es: '"{w}" eliminada; {n} posiciones liberadas: el resto se comparte.',
      fr: '"{w}" supprimé ; {n} places libérées — le reste est partagé.',
      hi: '"{w}" हटाया; {n} स्थान खाली — बाकी साझा हैं।',
      id: '"{w}" dihapus; {n} posisi bebas — sisanya dipakai bersama.',
      pt: '"{w}" removida; {n} posições liberadas — o resto é partilhado.',
    },
    'hud.size': {
      en: '{w} words / {n} seats',
      ko: '낱말 {w} · 자리 {n}',
      ja: '語 {w} · 席 {n}',
      zh: '{w} 词 / {n} 位',
      ar: '{w} كلمات / {n} مواضع',
      es: '{w} palabras / {n} posiciones',
      fr: '{w} mots / {n} places',
      hi: '{w} शब्द / {n} स्थान',
      id: '{w} kata / {n} posisi',
      pt: '{w} palavras / {n} posições',
    },
    'hud.none': {
      en: 'none',
      ko: '없다',
      ja: 'なし',
      zh: '无',
      ar: 'لا شيء',
      es: 'ninguna',
      fr: 'aucun',
      hi: 'कोई नहीं',
      id: 'tidak ada',
      pt: 'nenhuma',
    },
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'trie-stage' },
    resultHud: {
      type: 'text-display',
      label: { en: 'Completions', ko: '자동완성', ja: '補完候補', zh: '补全结果', ar: 'الإكمالات', es: 'Completados', fr: 'Complétions', hi: 'पूर्तियाँ', id: 'Pelengkapan', pt: 'Completações' },
    },
    sizeHud: {
      type: 'text-display',
      label: { en: 'Held', ko: '담긴 것', ja: '保持', zh: '已存', ar: 'المحفوظ', es: 'Guardado', fr: 'Contenu', hi: 'रखा', id: 'Tersimpan', pt: 'Guardado' },
    },
    controls: {
      type: 'control-bar',
      controls: [
        {
          widget: 'value-input',
          name: 'word',
          action: 'input',
          label: { en: 'Word', ko: '낱말', ja: '語', zh: '词', ar: 'كلمة', es: 'Palabra', fr: 'Mot', hi: 'शब्द', id: 'Kata', pt: 'Palavra' },
          placeholder: { en: 'e.g. card', ko: '예: card', ja: '例: card', zh: '例: card', ar: 'مثال: card', es: 'p. ej. card', fr: 'ex. card', hi: 'जैसे card', id: 'mis. card', pt: 'ex.: card' },
          default: '',
        },
        CONTROL.insert,
        CONTROL.search,
        {
          widget: 'button',
          action: 'complete',
          label: { en: 'Complete', ko: '자동완성', ja: '補完', zh: '补全', ar: 'أكمل', es: 'Completar', fr: 'Compléter', hi: 'पूरा करें', id: 'Lengkapi', pt: 'Completar' },
        },
        CONTROL.remove,
        CONTROL.reset,
      ],
      metrics: [
        { name: 'word-count', label: { en: 'Words', ko: '낱말', ja: '語数', zh: '词数', ar: 'كلمات', es: 'Palabras', fr: 'Mots', hi: 'शब्द', id: 'Kata', pt: 'Palavras' }, initial: 0 },
        { name: 'step-count', label: { en: 'Steps', ko: '걸음', ja: '歩数', zh: '步数', ar: 'خطوات', es: 'Pasos', fr: 'Pas', hi: 'कदम', id: 'Langkah', pt: 'Passos' }, initial: 0 },
      ],
    },
  },
};
