import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * @notation native — 문법 규칙(화살표 · 세로줄)은 컴파일러 내부 표기이고 이 조각의 소재 그 자체다.
 *   파서 함수의 코드 글자는 pseudo-notation 으로 쓴다.
 *
 * 질문: 재귀 하강 파서는 문법을 어떻게 코드로 옮기는가 — 규칙마다 함수 하나면, 입력을 읽는 동안 흐름은 어디를 다니는가.
 */
export const oneFunctionPerRuleFacet: FacetJson = {
  id: 'facet:oneFunctionPerRule',
  title: {
    en: 'One function per rule',
    ko: '규칙마다 함수 하나',
    ja: '規則ごとに関数ひとつ',
    zh: '每条规则一个函数',
    ar: 'دالة واحدة لكل قاعدة',
    es: 'Una función por regla',
    fr: 'Une fonction par règle',
    hi: 'हर नियम के लिए एक फ़ंक्शन',
    id: 'Satu fungsi per aturan',
    pt: 'Uma função por regra',
  },
  description: {
    en: 'A recursive-descent parser turns each grammar rule into a function. While it reads the tokens, control steps into the function named by each nonterminal and comes back out once that body is done.',
    ko: '재귀 하강 파서는 문법 규칙 하나를 함수 하나로 옮긴다. 토큰을 읽는 동안 흐름은 비단말을 만날 때마다 그 이름의 함수 안으로 들어가고, 몸을 다 따라가면 돌아 나온다.',
    ja: '再帰下降パーサは文法規則ひとつを関数ひとつに移す。トークンを読む間、流れは非終端記号に出会うたびにその名前の関数へ入り、本体を終えると戻ってくる。',
    zh: '递归下降解析器把每条文法规则写成一个函数。读取词法单元时，控制流每遇到一个非终结符就进入同名函数，走完函数体后再返回。',
    ar: 'يحوّل المحلل التنازلي العودي كل قاعدة نحوية إلى دالة. وأثناء قراءة الرموز يدخل التحكم في الدالة التي تحمل اسم كل رمز غير طرفي، ثم يعود منها حين ينتهي جسمها.',
    es: 'Un analizador descendente recursivo convierte cada regla de la gramática en una función. Mientras lee los tokens, el control entra en la función de cada no terminal y sale de ella al terminar su cuerpo.',
    fr: 'Un analyseur descendant récursif fait de chaque règle de grammaire une fonction. Pendant la lecture des jetons, le contrôle entre dans la fonction de chaque non-terminal et en ressort une fois son corps terminé.',
    hi: 'रिकर्सिव डिसेंट पार्सर व्याकरण के हर नियम को एक फ़ंक्शन बना देता है। टोकन पढ़ते समय नियंत्रण हर नॉन-टर्मिनल के नाम वाले फ़ंक्शन में जाता है और उसका शरीर पूरा होने पर लौट आता है।',
    id: 'Parser turun rekursif mengubah setiap aturan tata bahasa menjadi satu fungsi. Saat membaca token, kendali masuk ke fungsi bernama nonterminal yang ditemuinya dan keluar lagi setelah badannya selesai.',
    pt: 'Um analisador descendente recursivo transforma cada regra da gramática em uma função. Enquanto lê os tokens, o controle entra na função de cada não terminal e sai dela quando o corpo termina.',
  },
  algorithm: 'module:oneFunctionPerRule',
  scene: 'module:oneFunctionPerRuleScene',
  initialData: {
    type: 'one-function-per-rule',
    stepMs: 850,
    source: 'show (a + 1) + b',
    tokens: [
      { kind: 'SHOW', text: 'show' },
      { kind: 'PUNCT', text: '(' },
      { kind: 'NAME', text: 'a' },
      { kind: 'OP', text: '+' },
      { kind: 'NUM', text: '1' },
      { kind: 'PUNCT', text: ')' },
      { kind: 'OP', text: '+' },
      { kind: 'NAME', text: 'b' },
    ],
    rules: [
      { id: 'R1', lhs: 'Stmt', rhs: ['show', 'Expr'] },
      { id: 'R2', lhs: 'Expr', rhs: ['Atom', '+', 'Atom'] },
      { id: 'R3', lhs: 'Atom', rhs: ['(', 'Expr', ')'] },
      { id: 'R4', lhs: 'Atom', rhs: ['NAME'] },
      { id: 'R5', lhs: 'Atom', rhs: ['NUM'] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'No function called yet. Tokens: {n}',
      ko: '아직 아무 함수도 불리지 않았다. 토큰: {n}',
      ja: 'まだどの関数も呼ばれていない。トークン: {n}',
      zh: '还没有调用任何函数。词法单元: {n}',
      ar: 'لم تُستدعَ أي دالة بعد. الرموز: {n}',
      es: 'Aún no se ha llamado ninguna función. Tokens: {n}',
      fr: 'Aucune fonction appelée pour l’instant. Jetons : {n}',
      hi: 'अभी तक कोई फ़ंक्शन नहीं बुलाया गया। टोकन: {n}',
      id: 'Belum ada fungsi yang dipanggil. Token: {n}',
      pt: 'Nenhuma função chamada ainda. Tokens: {n}',
    },
    'caption.enter': {
      en: 'Outside calls {to}.',
      ko: '바깥에서 {to} 부름.',
      ja: '外側から {to} を呼ぶ。',
      zh: '从外部调用 {to}。',
      ar: 'الخارج يستدعي {to}.',
      es: 'Desde fuera se llama a {to}.',
      fr: 'L’extérieur appelle {to}.',
      hi: 'बाहर से {to} को बुलाया।',
      id: 'Dari luar, {to} dipanggil.',
      pt: 'De fora, chama-se {to}.',
    },
    'caption.call': {
      en: '{from} calls {to}.',
      ko: '{from} 에서 {to} 부름.',
      ja: '{from} が {to} を呼ぶ。',
      zh: '{from} 调用 {to}。',
      ar: '{from} تستدعي {to}.',
      es: '{from} llama a {to}.',
      fr: '{from} appelle {to}.',
      hi: '{from} ने {to} को बुलाया।',
      id: '{from} memanggil {to}.',
      pt: '{from} chama {to}.',
    },
    'caption.callAte': {
      en: '{from} eats {eaten}, then calls {to}.',
      ko: '{from} 안에서 먹음: {eaten}. 이어서 {to} 부름.',
      ja: '{from} が {eaten} を食べ、{to} を呼ぶ。',
      zh: '{from} 吃掉 {eaten}，然后调用 {to}。',
      ar: '{from} تستهلك {eaten} ثم تستدعي {to}.',
      es: '{from} consume {eaten} y luego llama a {to}.',
      fr: '{from} consomme {eaten}, puis appelle {to}.',
      hi: '{from} ने {eaten} खाया, फिर {to} को बुलाया।',
      id: '{from} memakan {eaten}, lalu memanggil {to}.',
      pt: '{from} consome {eaten} e depois chama {to}.',
    },
    'caption.return': {
      en: '{from} is done — back into {to}.',
      ko: '{from} 끝 — 돌아가는 곳: {to}.',
      ja: '{from} が終わり、{to} に戻る。',
      zh: '{from} 结束，回到 {to}。',
      ar: 'انتهت {from} — عودة إلى {to}.',
      es: '{from} termina: se vuelve a {to}.',
      fr: '{from} a fini — retour dans {to}.',
      hi: '{from} पूरा हुआ — वापस {to} में।',
      id: '{from} selesai — kembali ke {to}.',
      pt: '{from} termina — volta para {to}.',
    },
    'caption.returnAte': {
      en: '{from} eats {eaten} and is done — back into {to}.',
      ko: '{from} 안에서 먹음: {eaten}. {from} 끝 — 돌아가는 곳: {to}.',
      ja: '{from} が {eaten} を食べて終わり、{to} に戻る。',
      zh: '{from} 吃掉 {eaten} 后结束，回到 {to}。',
      ar: '{from} تستهلك {eaten} وتنتهي — عودة إلى {to}.',
      es: '{from} consume {eaten} y termina: se vuelve a {to}.',
      fr: '{from} consomme {eaten} et a fini — retour dans {to}.',
      hi: '{from} ने {eaten} खाया और पूरा हुआ — वापस {to} में।',
      id: '{from} memakan {eaten} dan selesai — kembali ke {to}.',
      pt: '{from} consome {eaten} e termina — volta para {to}.',
    },
    'caption.leave': {
      en: '{from} is done — back outside. Next: EOF · Eaten: {k} / {n}',
      ko: '{from} 끝 — 바깥으로 돌아옴. 다음: EOF · 먹은 토큰: {k} / {n}',
      ja: '{from} が終わり、外側に戻る。次: EOF · 食べたトークン: {k} / {n}',
      zh: '{from} 结束，回到外部。下一个: EOF · 已吃掉: {k} / {n}',
      ar: 'انتهت {from} — عودة إلى الخارج. التالي: EOF · المستهلك: {k} / {n}',
      es: '{from} termina: se vuelve afuera. Siguiente: EOF · Consumidos: {k} / {n}',
      fr: '{from} a fini — retour à l’extérieur. Suivant : EOF · Consommés : {k} / {n}',
      hi: '{from} पूरा हुआ — वापस बाहर। अगला: EOF · खाए गए: {k} / {n}',
      id: '{from} selesai — kembali ke luar. Berikutnya: EOF · Dimakan: {k} / {n}',
      pt: '{from} termina — volta para fora. Próximo: EOF · Consumidos: {k} / {n}',
    },
    'caption.leaveAte': {
      en: '{from} eats {eaten} and is done — back outside. Next: EOF · Eaten: {k} / {n}',
      ko: '{from} 안에서 먹음: {eaten}. {from} 끝 — 바깥으로 돌아옴. 다음: EOF · 먹은 토큰: {k} / {n}',
      ja: '{from} が {eaten} を食べて終わり、外側に戻る。次: EOF · 食べたトークン: {k} / {n}',
      zh: '{from} 吃掉 {eaten} 后结束，回到外部。下一个: EOF · 已吃掉: {k} / {n}',
      ar: '{from} تستهلك {eaten} وتنتهي — عودة إلى الخارج. التالي: EOF · المستهلك: {k} / {n}',
      es: '{from} consume {eaten} y termina: se vuelve afuera. Siguiente: EOF · Consumidos: {k} / {n}',
      fr: '{from} consomme {eaten} et a fini — retour à l’extérieur. Suivant : EOF · Consommés : {k} / {n}',
      hi: '{from} ने {eaten} खाया और पूरा हुआ — वापस बाहर। अगला: EOF · खाए गए: {k} / {n}',
      id: '{from} memakan {eaten} dan selesai — kembali ke luar. Berikutnya: EOF · Dimakan: {k} / {n}',
      pt: '{from} consome {eaten} e termina — volta para fora. Próximo: EOF · Consumidos: {k} / {n}',
    },
    'label.outside': {
      en: 'outside',
      ko: '바깥',
      ja: '外側',
      zh: '外部',
      ar: 'الخارج',
      es: 'fuera',
      fr: 'extérieur',
      hi: 'बाहर',
      id: 'luar',
      pt: 'fora',
    },
    'label.depth': {
      en: 'Depth: {d}',
      ko: '깊이: {d}',
      ja: '深さ: {d}',
      zh: '深度: {d}',
      ar: 'العمق: {d}',
      es: 'Profundidad: {d}',
      fr: 'Profondeur : {d}',
      hi: 'गहराई: {d}',
      id: 'Kedalaman: {d}',
      pt: 'Profundidade: {d}',
    },
    'label.input': {
      en: 'Input',
      ko: '입력',
      ja: '入力',
      zh: '输入',
      ar: 'المدخل',
      es: 'Entrada',
      fr: 'Entrée',
      hi: 'इनपुट',
      id: 'Masukan',
      pt: 'Entrada',
    },
  },
  blocks: {
    stage: { type: 'one-function-per-rule-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
