import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 모든 스레드가 번호 작은 자물쇠부터 잡으면 왜 기다림이 고리가 되지 않는가.
 *
 * 자물쇠가 번호 차례로 층을 이루고, 잠든 스레드의 기다림은 쥔 층에서 더 높은 층으로만 뻗는다.
 * 맨 위의 스레드가 먼저 끝나고, 넘겨주기가 위층에서 아래층으로 차례차례 내려온다.
 */
export const lockOrderingFacet: FacetJson = {
  id: 'facet:lockOrdering',
  title: {
    en: 'Lock ordering',
    ko: '잠금 순서',
    ja: 'ロックの順序',
    zh: '加锁顺序',
    ar: 'ترتيب الأقفال',
    es: 'Orden de los cerrojos',
    fr: 'Ordre des verrous',
    hi: 'लॉक का क्रम',
    id: 'Urutan kunci',
    pt: 'Ordem dos cadeados',
  },
  description: {
    en: 'When every thread locks the lower number first, each wait reaches only upward, so the waits never close into a cycle.',
    ko: '모든 스레드가 번호 작은 자물쇠부터 잡으면 기다림은 위로만 뻗어, 고리로 닫히지 않는다.',
    ja: 'すべてのスレッドが番号の小さいロックから取れば、待ちは上へしか伸びず、輪に閉じない。',
    zh: '所有线程都先锁编号小的锁时，等待只会向上延伸，永远不会闭合成环。',
    ar: 'حين يأخذ كل خيط القفل ذا الرقم الأصغر أولًا، لا يمتد الانتظار إلا إلى الأعلى، فلا ينغلق في حلقة أبدًا.',
    es: 'Si todos los hilos toman primero el cerrojo de número menor, cada espera solo apunta hacia arriba y nunca se cierra un ciclo.',
    fr: 'Si chaque thread prend d’abord le verrou de plus petit numéro, chaque attente ne pointe que vers le haut et ne se referme jamais en cycle.',
    hi: 'जब हर थ्रेड पहले छोटे क्रमांक वाला लॉक लेता है, तो हर इंतज़ार केवल ऊपर की ओर जाता है और कभी चक्र नहीं बनता।',
    id: 'Jika setiap thread mengambil kunci bernomor lebih kecil lebih dulu, setiap penantian hanya mengarah ke atas dan tak pernah menutup menjadi siklus.',
    pt: 'Se toda thread pega primeiro o cadeado de número menor, cada espera só aponta para cima e nunca fecha um ciclo.',
  },
  algorithm: 'module:lockOrdering',
  scene: 'module:lockOrderingScene',
  initialData: {
    type: 'lock-ordering',
    stepMs: 600,
    locks: ['m1', 'm2', 'm3', 'm4'],
    threads: [
      {
        id: 'A',
        program: [
          { op: 'lock', lock: 'm1' },
          { op: 'lock', lock: 'm2' },
          { op: 'work' },
          { op: 'unlock', lock: 'm2' },
          { op: 'unlock', lock: 'm1' },
        ],
      },
      {
        id: 'B',
        program: [
          { op: 'lock', lock: 'm2' },
          { op: 'lock', lock: 'm3' },
          { op: 'work' },
          { op: 'unlock', lock: 'm3' },
          { op: 'unlock', lock: 'm2' },
        ],
      },
      {
        id: 'C',
        program: [
          { op: 'lock', lock: 'm3' },
          { op: 'lock', lock: 'm4' },
          { op: 'work' },
          { op: 'unlock', lock: 'm4' },
          { op: 'unlock', lock: 'm3' },
        ],
      },
      {
        id: 'D',
        program: [
          { op: 'lock', lock: 'm4' },
          { op: 'lock', lock: 'm1' },
          { op: 'work' },
          { op: 'unlock', lock: 'm1' },
          { op: 'unlock', lock: 'm4' },
        ],
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'As written — higher number first: {threads}',
      ko: '처음 쓰인 대로 — 높은 번호부터 잡는 스레드: {threads}',
      ja: '書かれたまま — 大きい番号から取るスレッド: {threads}',
      zh: '按原写法 — 先锁大编号的线程：{threads}',
      ar: 'كما كُتب — خيوط تبدأ بالرقم الأعلى: {threads}',
      es: 'Tal como está escrito — empiezan por el número mayor: {threads}',
      fr: 'Tel qu’écrit — commencent par le plus grand numéro : {threads}',
      hi: 'जैसा लिखा है — बड़े क्रमांक से शुरू करने वाले थ्रेड: {threads}',
      id: 'Seperti tertulis — mulai dari nomor lebih besar: {threads}',
      pt: 'Como está escrito — começam pelo número maior: {threads}',
    },
    'caption.startNone': {
      en: 'As written — every thread already locks the lower number first.',
      ko: '처음 쓰인 대로 — 모든 스레드가 이미 번호 작은 자물쇠부터 잡는다.',
      ja: '書かれたまま — どのスレッドもすでに小さい番号から取る。',
      zh: '按原写法 — 每个线程都已先锁小编号。',
      ar: 'كما كُتب — كل خيط يأخذ الرقم الأصغر أولًا بالفعل.',
      es: 'Tal como está escrito — todos los hilos ya toman primero el número menor.',
      fr: 'Tel qu’écrit — chaque thread prend déjà le plus petit numéro d’abord.',
      hi: 'जैसा लिखा है — हर थ्रेड पहले से छोटा क्रमांक पहले लेता है।',
      id: 'Seperti tertulis — setiap thread sudah mengambil nomor lebih kecil lebih dulu.',
      pt: 'Como está escrito — toda thread já pega primeiro o número menor.',
    },
    'caption.ruleHead': {
      en: 'Rule: every thread locks the lower number first.',
      ko: '규칙: 모든 스레드가 번호 작은 자물쇠부터 잡는다.',
      ja: '規則: すべてのスレッドが小さい番号のロックから取る。',
      zh: '规则：所有线程都先锁编号小的锁。',
      ar: 'القاعدة: كل خيط يأخذ القفل ذا الرقم الأصغر أولًا.',
      es: 'Regla: todos los hilos toman primero el cerrojo de número menor.',
      fr: 'Règle : chaque thread prend d’abord le verrou de plus petit numéro.',
      hi: 'नियम: हर थ्रेड पहले छोटे क्रमांक वाला लॉक लेता है।',
      id: 'Aturan: setiap thread mengambil kunci bernomor lebih kecil lebih dulu.',
      pt: 'Regra: toda thread pega primeiro o cadeado de número menor.',
    },
    'caption.ruleChange': {
      en: '{thread}: {first} now comes before {second}.',
      ko: '{thread}: 이제 {first} 먼저, 그다음 {second}.',
      ja: '{thread}: 今は {first} が先、次に {second}。',
      zh: '{thread}：现在先 {first}，再 {second}。',
      ar: '{thread}: الآن {first} أولًا، ثم {second}.',
      es: '{thread}: ahora primero {first}, luego {second}.',
      fr: '{thread} : désormais {first} d’abord, puis {second}.',
      hi: '{thread}: अब पहले {first}, फिर {second}।',
      id: '{thread}: sekarang {first} dulu, lalu {second}.',
      pt: '{thread}: agora primeiro {first}, depois {second}.',
    },
    'caption.take': {
      en: 'Tick {tick} · {thread} takes {lock}.',
      ko: '틱 {tick} · {thread}: {lock} 잡음.',
      ja: 'ティック {tick} · {thread}: {lock} を取る。',
      zh: '第 {tick} 拍 · {thread}：拿到 {lock}。',
      ar: 'النبضة {tick} · {thread}: يأخذ {lock}.',
      es: 'Tic {tick} · {thread} toma {lock}.',
      fr: 'Tic {tick} · {thread} prend {lock}.',
      hi: 'टिक {tick} · {thread}: {lock} लिया।',
      id: 'Tik {tick} · {thread} mengambil {lock}.',
      pt: 'Tique {tick} · {thread} pega {lock}.',
    },
    'caption.block': {
      en: 'Tick {tick} · {thread} sleeps waiting for {lock}. Holder: {holder}.',
      ko: '틱 {tick} · {thread}: {lock} 기다리며 잠듦. 주인: {holder}.',
      ja: 'ティック {tick} · {thread}: {lock} を待って眠る。持ち主: {holder}。',
      zh: '第 {tick} 拍 · {thread}：等 {lock} 而睡眠。持有者：{holder}。',
      ar: 'النبضة {tick} · {thread}: ينام منتظرًا {lock}. الحائز: {holder}.',
      es: 'Tic {tick} · {thread} duerme esperando {lock}. Dueño: {holder}.',
      fr: 'Tic {tick} · {thread} dort en attendant {lock}. Détenteur : {holder}.',
      hi: 'टिक {tick} · {thread}: {lock} की प्रतीक्षा में सोया। धारक: {holder}।',
      id: 'Tik {tick} · {thread} tidur menunggu {lock}. Pemegang: {holder}.',
      pt: 'Tique {tick} · {thread} dorme esperando {lock}. Dono: {holder}.',
    },
    'caption.waitEmpty': {
      en: 'Holds: nothing · waits for: {lock}',
      ko: '쥔 것: 없음 · 기다리는 것: {lock}',
      ja: '持っているもの: なし · 待つもの: {lock}',
      zh: '持有：无 · 等待：{lock}',
      ar: 'يحوز: لا شيء · ينتظر: {lock}',
      es: 'Tiene: nada · espera: {lock}',
      fr: 'Détient : rien · attend : {lock}',
      hi: 'पास में: कुछ नहीं · प्रतीक्षा: {lock}',
      id: 'Memegang: tidak ada · menunggu: {lock}',
      pt: 'Segura: nada · espera: {lock}',
    },
    'caption.waitHigher': {
      en: 'Holds: {held} · waits for: {lock} — a higher number.',
      ko: '쥔 것: {held} · 기다리는 것: {lock} — 더 높은 번호.',
      ja: '持っているもの: {held} · 待つもの: {lock} — より大きい番号。',
      zh: '持有：{held} · 等待：{lock} — 更大的编号。',
      ar: 'يحوز: {held} · ينتظر: {lock} — رقم أعلى.',
      es: 'Tiene: {held} · espera: {lock} — un número mayor.',
      fr: 'Détient : {held} · attend : {lock} — un numéro plus grand.',
      hi: 'पास में: {held} · प्रतीक्षा: {lock} — बड़ा क्रमांक।',
      id: 'Memegang: {held} · menunggu: {lock} — nomor lebih besar.',
      pt: 'Segura: {held} · espera: {lock} — um número maior.',
    },
    'caption.waitLower': {
      en: 'Holds: {held} · waits for: {lock} — a lower number.',
      ko: '쥔 것: {held} · 기다리는 것: {lock} — 더 낮은 번호.',
      ja: '持っているもの: {held} · 待つもの: {lock} — より小さい番号。',
      zh: '持有：{held} · 等待：{lock} — 更小的编号。',
      ar: 'يحوز: {held} · ينتظر: {lock} — رقم أدنى.',
      es: 'Tiene: {held} · espera: {lock} — un número menor.',
      fr: 'Détient : {held} · attend : {lock} — un numéro plus petit.',
      hi: 'पास में: {held} · प्रतीक्षा: {lock} — छोटा क्रमांक।',
      id: 'Memegang: {held} · menunggu: {lock} — nomor lebih kecil.',
      pt: 'Segura: {held} · espera: {lock} — um número menor.',
    },
    'caption.work': {
      en: 'Tick {tick} · {thread} runs work() holding {held}.',
      ko: '틱 {tick} · {thread}: {held} 쥔 채 work().',
      ja: 'ティック {tick} · {thread}: {held} を持ったまま work()。',
      zh: '第 {tick} 拍 · {thread}：持有 {held}，执行 work()。',
      ar: 'النبضة {tick} · {thread}: ينفّذ work() وهو يحوز {held}.',
      es: 'Tic {tick} · {thread} ejecuta work() con {held}.',
      fr: 'Tic {tick} · {thread} exécute work() en détenant {held}.',
      hi: 'टिक {tick} · {thread}: {held} पकड़े हुए work()।',
      id: 'Tik {tick} · {thread} menjalankan work() sambil memegang {held}.',
      pt: 'Tique {tick} · {thread} executa work() segurando {held}.',
    },
    'caption.releaseFree': {
      en: 'Tick {tick} · {thread} releases {lock}. No one is waiting for it.',
      ko: '틱 {tick} · {thread}: {lock} 놓음. 기다리는 스레드 없음.',
      ja: 'ティック {tick} · {thread}: {lock} を放す。待つスレッドなし。',
      zh: '第 {tick} 拍 · {thread}：释放 {lock}。没有线程在等。',
      ar: 'النبضة {tick} · {thread}: يحرّر {lock}. لا أحد ينتظره.',
      es: 'Tic {tick} · {thread} suelta {lock}. Nadie lo espera.',
      fr: 'Tic {tick} · {thread} libère {lock}. Personne ne l’attend.',
      hi: 'टिक {tick} · {thread}: {lock} छोड़ा। कोई प्रतीक्षा में नहीं।',
      id: 'Tik {tick} · {thread} melepas {lock}. Tak ada yang menunggu.',
      pt: 'Tique {tick} · {thread} solta {lock}. Ninguém espera por ele.',
    },
    'caption.releaseHand': {
      en: 'Tick {tick} · {thread} releases {lock}. {to} wakes up holding it.',
      ko: '틱 {tick} · {thread}: {lock} 놓음 → {to} 깨어나 넘겨받음.',
      ja: 'ティック {tick} · {thread}: {lock} を放す → {to} が起きて受け取る。',
      zh: '第 {tick} 拍 · {thread}：释放 {lock} → {to} 醒来并接手。',
      ar: 'النبضة {tick} · {thread}: يحرّر {lock} ← يستيقظ {to} حائزًا إياه.',
      es: 'Tic {tick} · {thread} suelta {lock}. {to} despierta con él.',
      fr: 'Tic {tick} · {thread} libère {lock}. {to} se réveille en le détenant.',
      hi: 'टिक {tick} · {thread}: {lock} छोड़ा → {to} जागा और उसे पाया।',
      id: 'Tik {tick} · {thread} melepas {lock}. {to} bangun sambil memegangnya.',
      pt: 'Tique {tick} · {thread} solta {lock}. {to} acorda segurando-o.',
    },
    'caption.finished': {
      en: '{thread} is finished.',
      ko: '{thread}: 끝남.',
      ja: '{thread}: 終了。',
      zh: '{thread}：结束。',
      ar: '{thread}: انتهى.',
      es: '{thread} ha terminado.',
      fr: '{thread} a terminé.',
      hi: '{thread}: समाप्त।',
      id: '{thread} selesai.',
      pt: '{thread} terminou.',
    },
    'caption.allDone': {
      en: 'All finished. Order: {order}',
      ko: '모두 끝남. 끝난 차례: {order}',
      ja: 'すべて終了。終わった順: {order}',
      zh: '全部结束。结束顺序：{order}',
      ar: 'انتهى الجميع. الترتيب: {order}',
      es: 'Todos terminaron. Orden: {order}',
      fr: 'Tous ont terminé. Ordre : {order}',
      hi: 'सब समाप्त। क्रम: {order}',
      id: 'Semua selesai. Urutan: {order}',
      pt: 'Todos terminaram. Ordem: {order}',
    },
    'label.finished': {
      en: 'Done #{n}',
      ko: '끝 #{n}',
      ja: '終了 #{n}',
      zh: '结束 #{n}',
      ar: 'انتهى #{n}',
      es: 'Fin #{n}',
      fr: 'Fini #{n}',
      hi: 'समाप्त #{n}',
      id: 'Selesai #{n}',
      pt: 'Fim #{n}',
    },
    'label.nothing': {
      en: 'nothing',
      ko: '없음',
      ja: 'なし',
      zh: '无',
      ar: 'لا شيء',
      es: 'nada',
      fr: 'rien',
      hi: 'कुछ नहीं',
      id: 'tidak ada',
      pt: 'nada',
    },
  },
  blocks: {
    stage: { type: 'lock-ordering-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
