import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 최소 연결 분배는 새 요청을 받을 서버를 무엇을 보고 고르는가.
 *
 * 틱마다 끝난 연결이 먼저 빠져나가고, 그 틱의 요청이 지금 열린 연결 수가 가장 적은
 * 서버로 간다. 받은 총수 · 남은 시간은 보지 않는다.
 */
export const sendToIdlestFacet: FacetJson = {
  id: 'facet:sendToIdlest',
  title: {
    en: 'Send to the idlest',
    ko: '가장 한가한 쪽으로',
    ja: '一番空いているサーバーへ',
    zh: '发往最空闲的服务器',
    ar: 'أرسل إلى الأقل انشغالًا',
    es: 'Enviar al más libre',
    fr: 'Envoyer au moins occupé',
    hi: 'सबसे खाली सर्वर को भेजो',
    id: 'Kirim ke yang paling senggang',
    pt: 'Enviar ao mais livre',
  },
  description: {
    en: 'Least connection: each new request goes to the server with the fewest open connections right now, filling the gap a finished connection leaves.',
    ko: '최소 연결: 새 요청은 지금 열린 연결이 가장 적은 서버로 가서, 끝난 연결이 빠져나간 자리를 채운다.',
    ja: '最小接続: 新しいリクエストは、今開いている接続が最も少ないサーバーへ行き、終わった接続が抜けた空きを埋める。',
    zh: '最少连接：每个新请求都发往当前打开连接最少的服务器，填补刚结束的连接留下的空位。',
    ar: 'أقل اتصالات: يذهب كل طلب جديد إلى الخادم الذي لديه أقل عدد من الاتصالات المفتوحة الآن، فيملأ الفراغ الذي تركه اتصال انتهى.',
    es: 'Menos conexiones: cada petición nueva va al servidor con menos conexiones abiertas ahora mismo y ocupa el hueco que deja una conexión terminada.',
    fr: 'Moins de connexions : chaque nouvelle requête va au serveur qui a le moins de connexions ouvertes à cet instant et comble la place laissée par une connexion terminée.',
    hi: 'न्यूनतम कनेक्शन: हर नया अनुरोध उस सर्वर पर जाता है जिसके अभी सबसे कम कनेक्शन खुले हैं, और ख़त्म हुए कनेक्शन की छोड़ी जगह भरता है।',
    id: 'Koneksi paling sedikit: setiap permintaan baru pergi ke server dengan koneksi terbuka paling sedikit saat ini, mengisi celah yang ditinggalkan koneksi yang selesai.',
    pt: 'Menos conexões: cada nova requisição vai para o servidor com menos conexões abertas agora, ocupando o espaço deixado por uma conexão encerrada.',
  },
  algorithm: 'module:sendToIdlest',
  scene: 'module:sendToIdlestScene',
  initialData: {
    type: 'send-to-idlest',
    stepMs: 1300,
    servers: ['s1', 's2', 's3'],
    openAtStart: [
      { server: 's1', endsAt: [2, 9] },
      { server: 's2', endsAt: [8] },
      { server: 's3', endsAt: [3, 6] },
    ],
    requests: [
      { id: 'r1', arrives: 1, takes: 3 },
      { id: 'r2', arrives: 2, takes: 3 },
      { id: 'r3', arrives: 3, takes: 8 },
      { id: 'r4', arrives: 4, takes: 3 },
      { id: 'r5', arrives: 5, takes: 8 },
      { id: 'r6', arrives: 6, takes: 5 },
      { id: 'r7', arrives: 7, takes: 9 },
      { id: 'r8', arrives: 8, takes: 7 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Already open: {n}',
      ko: '이미 열린 연결: {n}',
      ja: 'すでに開いている接続: {n}',
      zh: '已打开的连接：{n}',
      ar: 'اتصالات مفتوحة مسبقًا: {n}',
      es: 'Ya abiertas: {n}',
      fr: 'Déjà ouvertes : {n}',
      hi: 'पहले से खुले कनेक्शन: {n}',
      id: 'Sudah terbuka: {n}',
      pt: 'Já abertas: {n}',
    },
    'caption.leftNone': {
      en: 'Nothing finished this tick',
      ko: '이번 틱에 끝난 연결 없음',
      ja: 'このティックで終わった接続はない',
      zh: '这一刻没有连接结束',
      ar: 'لم ينتهِ أي اتصال في هذه النبضة',
      es: 'Ninguna terminó en este tic',
      fr: 'Aucune ne s’est terminée à ce tic',
      hi: 'इस टिक में कोई कनेक्शन ख़त्म नहीं हुआ',
      id: 'Tak ada yang selesai pada tik ini',
      pt: 'Nenhuma terminou neste tique',
    },
    'caption.leftOne': {
      en: 'Finished and left: {server}',
      ko: '끝나서 빠져나감: {server}',
      ja: '終わって抜けた: {server}',
      zh: '结束并离开：{server}',
      ar: 'انتهى وغادر: {server}',
      es: 'Terminó y salió: {server}',
      fr: 'Terminée et partie : {server}',
      hi: 'ख़त्म होकर निकला: {server}',
      id: 'Selesai dan keluar: {server}',
      pt: 'Terminou e saiu: {server}',
    },
    'caption.leftMany': {
      en: 'Finished and left: {n}',
      ko: '끝나서 빠져나간 수: {n}',
      ja: '終わって抜けた数: {n}',
      zh: '结束并离开的数量：{n}',
      ar: 'عدد ما انتهى وغادر: {n}',
      es: 'Terminaron y salieron: {n}',
      fr: 'Terminées et parties : {n}',
      hi: 'ख़त्म होकर निकले: {n}',
      id: 'Selesai dan keluar: {n}',
      pt: 'Terminaram e saíram: {n}',
    },
    'caption.pick': {
      en: 'Fewest open: {n} · {request} → {server}',
      ko: '가장 적게 열림: {n} · {request} → {server}',
      ja: '開いている数が最少: {n} · {request} → {server}',
      zh: '打开最少：{n} · {request} → {server}',
      ar: 'الأقل انفتاحًا: {n} · {request} → {server}',
      es: 'Menos abiertas: {n} · {request} → {server}',
      fr: 'Le moins d’ouvertes : {n} · {request} → {server}',
      hi: 'सबसे कम खुले: {n} · {request} → {server}',
      id: 'Paling sedikit terbuka: {n} · {request} → {server}',
      pt: 'Menos abertas: {n} · {request} → {server}',
    },
    'label.tick': {
      en: 'Tick {tick}',
      ko: '틱 {tick}',
      ja: 'ティック {tick}',
      zh: '时刻 {tick}',
      ar: 'النبضة {tick}',
      es: 'Tic {tick}',
      fr: 'Tic {tick}',
      hi: 'टिक {tick}',
      id: 'Tik {tick}',
      pt: 'Tique {tick}',
    },
    'label.s1': {
      en: 'Server 1',
      ko: '서버 1',
      ja: 'サーバー 1',
      zh: '服务器 1',
      ar: 'الخادم 1',
      es: 'Servidor 1',
      fr: 'Serveur 1',
      hi: 'सर्वर 1',
      id: 'Server 1',
      pt: 'Servidor 1',
    },
    'label.s2': {
      en: 'Server 2',
      ko: '서버 2',
      ja: 'サーバー 2',
      zh: '服务器 2',
      ar: 'الخادم 2',
      es: 'Servidor 2',
      fr: 'Serveur 2',
      hi: 'सर्वर 2',
      id: 'Server 2',
      pt: 'Servidor 2',
    },
    'label.s3': {
      en: 'Server 3',
      ko: '서버 3',
      ja: 'サーバー 3',
      zh: '服务器 3',
      ar: 'الخادم 3',
      es: 'Servidor 3',
      fr: 'Serveur 3',
      hi: 'सर्वर 3',
      id: 'Server 3',
      pt: 'Servidor 3',
    },
    'label.balancer': {
      en: 'Load balancer',
      ko: '로드 밸런서',
      ja: 'ロードバランサー',
      zh: '负载均衡器',
      ar: 'موازن الحمل',
      es: 'Balanceador',
      fr: 'Répartiteur',
      hi: 'लोड बैलेंसर',
      id: 'Penyeimbang beban',
      pt: 'Balanceador',
    },
    'label.queue': {
      en: 'Arriving',
      ko: '도착 차례',
      ja: '到着順',
      zh: '到达顺序',
      ar: 'الواصلة',
      es: 'Llegan',
      fr: 'Arrivées',
      hi: 'आने वाले',
      id: 'Datang',
      pt: 'Chegando',
    },
    'label.open': {
      en: 'Open',
      ko: '열린 수',
      ja: '開いている数',
      zh: '打开数',
      ar: 'مفتوحة',
      es: 'Abiertas',
      fr: 'Ouvertes',
      hi: 'खुले',
      id: 'Terbuka',
      pt: 'Abertas',
    },
    'label.left': {
      en: 'Left',
      ko: '빠짐',
      ja: '抜けた',
      zh: '离开',
      ar: 'غادرت',
      es: 'Salieron',
      fr: 'Parties',
      hi: 'निकले',
      id: 'Keluar',
      pt: 'Saíram',
    },
    'label.got': {
      en: 'Received',
      ko: '받은 수',
      ja: '受けた数',
      zh: '接收数',
      ar: 'المستلمة',
      es: 'Recibidas',
      fr: 'Reçues',
      hi: 'प्राप्त',
      id: 'Diterima',
      pt: 'Recebidas',
    },
  },
  blocks: {
    stage: { type: 'send-to-idlest-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
