import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/** initialData — 자료. 이름 글자 · 소수 · e · 저장소 항목은 사양 그대로이고 파생값(n · d · 후보 · 요약 · 서명)은 알고리즘이 셈한다. */
export type CertificateInitialData = {
  type: 'certificate';
  stepMs: number;
  ca: { name: string; p: number; q: number; e: number };
  store: { name: string; n: number; e: number };
  owner: { name: string; p: number; q: number; e: number };
  mallory: { name: string; p: number; q: number; targetE: number };
  fakeRoot: { name: string; p: number; q: number; e: number };
  nameDigit: Record<string, number>;
  eRange: [number, number];
  signTargetLadder: number[];
  signTarget: number;
  forgeryLadder: number[];
  forgery: number;
  forgeries: string[];
};

const initialData: CertificateInitialData = {
  type: 'certificate',
  stepMs: 1600,
  ca: { name: 'CN=Sample CA', p: 53, q: 71, e: 11 },
  store: { name: 'CN=Sample CA', n: 3763, e: 11 },
  owner: { name: 'CN=mail.example', p: 41, q: 59, e: 3 },
  mallory: { name: 'CN=mallory.example', p: 37, q: 73, targetE: 5 },
  fakeRoot: { name: 'CN=Sample CA', p: 59, q: 79, e: 7 },
  nameDigit: { 'CN=mallory.example': 1, 'CN=mail.example': 2 },
  eRange: [5, 376],
  signTargetLadder: [0, 1],
  signTarget: 1,
  forgeryLadder: [0, 1, 2, 3],
  forgery: 1,
  forgeries: ['multiply', 'pair', 'swap', 'fakeroot'],
};

export const certificateFacet: FacetJson = {
  id: 'facet:certificate',
  title: {
    en: 'Certificates and signature forgery',
    ko: '인증서와 서명 위조',
    ja: '証明書と署名の偽造',
    zh: '证书与签名伪造',
    ar: 'الشهادات وتزوير التواقيع',
    es: 'Certificados y falsificación de firmas',
    fr: 'Certificats et falsification de signatures',
    hi: 'प्रमाणपत्र और हस्ताक्षर की जालसाज़ी',
    id: 'Sertifikat dan pemalsuan tanda tangan',
    pt: 'Certificados e falsificação de assinaturas',
  },
  description: {
    en: 'One CA signs certificates with toy RSA. Choose what it signs (the raw document number or a digest) and how the attacker forges, then watch the forged certificate go down the receiver’s checks and see where it stops.',
    ko: 'CA 하나가 장난감 RSA 로 인증서에 서명한다. 서명 대상(문서 그대로 · 요약)과 공격자의 위조 방법을 고른 뒤, 위조 인증서가 받는 쪽의 확인 줄을 내려가다 어디서 멈추는지 본다.',
    ja: '1つの CA がおもちゃの RSA で証明書に署名する。署名する対象(文書そのまま・要約)と攻撃者の偽造方法を選び、偽造証明書が受け手の確認の列を下りてどこで止まるかを見る。',
    zh: '一个 CA 用玩具 RSA 为证书签名。选择签名对象(原始文档编号或摘要)和攻击者的伪造方法,然后看伪造证书沿着接收方的检查一路下行,停在哪里。',
    ar: 'جهة إصدار واحدة (CA) توقّع الشهادات بـ RSA مصغّر. اختر ما توقّعه (رقم المستند كما هو أو الملخص) وطريقة المهاجم في التزوير، ثم تابع الشهادة المزوّرة وهي تنزل عبر فحوص المستلم لترى أين تتوقف.',
    es: 'Una CA firma certificados con un RSA de juguete. Elige qué firma (el número del documento tal cual o un resumen) y cómo falsifica el atacante, y sigue al certificado falso por las comprobaciones del receptor hasta donde se detiene.',
    fr: 'Une CA signe des certificats avec un RSA jouet. Choisissez ce qu’elle signe (le numéro du document tel quel ou un condensé) et la façon dont l’attaquant falsifie, puis suivez le faux certificat le long des contrôles du destinataire jusqu’à son arrêt.',
    hi: 'एक CA खिलौना RSA से प्रमाणपत्रों पर हस्ताक्षर करता है। चुनें कि वह किस पर हस्ताक्षर करता है (दस्तावेज़ संख्या जैसी की तैसी या सारांश) और हमलावर कैसे जालसाज़ी करता है, फिर देखें कि जाली प्रमाणपत्र प्राप्तकर्ता की जाँचों से गुज़रते हुए कहाँ रुकता है।',
    id: 'Satu CA menandatangani sertifikat dengan RSA mainan. Pilih apa yang ditandatangani (nomor dokumen apa adanya atau ringkasan) dan cara penyerang memalsukan, lalu ikuti sertifikat palsu menuruni pemeriksaan penerima sampai tempat ia berhenti.',
    pt: 'Uma CA assina certificados com um RSA de brinquedo. Escolha o que ela assina (o número do documento como está ou um resumo) e como o atacante falsifica, e acompanhe o certificado falso pelas verificações do receptor até onde ele para.',
  },
  algorithm: 'module:certificate',
  projector: 'module:certificateProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'certificate-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback!,
        {
          widget: 'segmented-slider',
          action: 'signTarget',
          name: 'signTarget',
          label: {
            en: 'Signed value',
            ko: '서명 대상',
            ja: '署名の対象',
            zh: '签名对象',
            ar: 'ما يُوقَّع',
            es: 'Qué se firma',
            fr: 'Valeur signée',
            hi: 'हस्ताक्षरित मान',
            id: 'Yang ditandatangani',
            pt: 'O que é assinado',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Raw document',
                ko: '문서 그대로',
                ja: '文書そのまま',
                zh: '原始文档',
                ar: 'المستند كما هو',
                es: 'Documento tal cual',
                fr: 'Document brut',
                hi: 'मूल दस्तावेज़',
                id: 'Dokumen apa adanya',
                pt: 'Documento puro',
              },
            },
            {
              value: 1,
              label: {
                en: 'Digest',
                ko: '요약',
                ja: '要約',
                zh: '摘要',
                ar: 'الملخص',
                es: 'Resumen',
                fr: 'Condensé',
                hi: 'सारांश',
                id: 'Ringkasan',
                pt: 'Resumo',
              },
              default: true,
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'forgery',
          name: 'forgery',
          label: {
            en: 'Forgery',
            ko: '위조',
            ja: '偽造',
            zh: '伪造',
            ar: 'التزوير',
            es: 'Falsificación',
            fr: 'Falsification',
            hi: 'जालसाज़ी',
            id: 'Pemalsuan',
            pt: 'Falsificação',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Multiply',
                ko: '곱하기',
                ja: '掛け算',
                zh: '相乘',
                ar: 'الضرب',
                es: 'Multiplicar',
                fr: 'Multiplier',
                hi: 'गुणा',
                id: 'Kalikan',
                pt: 'Multiplicar',
              },
            },
            {
              value: 1,
              label: {
                en: 'Colliding pair',
                ko: '겹치는 짝',
                ja: '衝突する組',
                zh: '碰撞对',
                ar: 'زوج متصادم',
                es: 'Par en colisión',
                fr: 'Paire en collision',
                hi: 'टकराती जोड़ी',
                id: 'Pasangan bertabrakan',
                pt: 'Par em colisão',
              },
              default: true,
            },
            {
              value: 2,
              label: {
                en: 'Key swap',
                ko: '열쇠 바꿔 끼우기',
                ja: '鍵のすり替え',
                zh: '换钥匙',
                ar: 'تبديل المفتاح',
                es: 'Cambio de clave',
                fr: 'Échange de clé',
                hi: 'कुंजी बदलना',
                id: 'Tukar kunci',
                pt: 'Troca de chave',
              },
            },
            {
              value: 3,
              label: {
                en: 'Fake root',
                ko: '가짜 뿌리',
                ja: '偽のルート',
                zh: '伪造根',
                ar: 'جذر مزيّف',
                es: 'Raíz falsa',
                fr: 'Fausse racine',
                hi: 'नकली मूल',
                id: 'Akar palsu',
                pt: 'Raiz falsa',
              },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'forger-tries',
          label: {
            en: 'Forger tries',
            ko: '공격자 후보',
            ja: '攻撃者の候補',
            zh: '攻击者尝试',
            ar: 'محاولات المزوّر',
            es: 'Intentos del atacante',
            fr: 'Essais du faussaire',
            hi: 'हमलावर के प्रयास',
            id: 'Percobaan penyerang',
            pt: 'Tentativas do atacante',
          },
          initial: 0,
        },
        {
          name: 'ca-signatures',
          label: {
            en: 'CA signatures',
            ko: 'CA 서명',
            ja: 'CA の署名',
            zh: 'CA 签名',
            ar: 'تواقيع CA',
            es: 'Firmas de la CA',
            fr: 'Signatures de la CA',
            hi: 'CA हस्ताक्षर',
            id: 'Tanda tangan CA',
            pt: 'Assinaturas da CA',
          },
          initial: 0,
        },
        {
          name: 'accepted',
          label: {
            en: 'Accepted',
            ko: '통과',
            ja: '通過',
            zh: '通过',
            ar: 'مقبولة',
            es: 'Aceptado',
            fr: 'Accepté',
            hi: 'स्वीकृत',
            id: 'Diterima',
            pt: 'Aceito',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:certificate-imperative',
      label: {
        en: 'Receiver check',
        ko: '받는 쪽의 확인',
        ja: '受け手の確認',
        zh: '接收方检查',
        ar: 'فحص المستلم',
        es: 'Comprobación del receptor',
        fr: 'Contrôle du destinataire',
        hi: 'प्राप्तकर्ता की जाँच',
        id: 'Pemeriksaan penerima',
        pt: 'Verificação do receptor',
      },
    },
  },
  messages: {
    'label.signers': {
      en: 'Who signs',
      ko: '서명하는 쪽',
      ja: '署名する側',
      zh: '签名方',
      ar: 'من يوقّع',
      es: 'Quién firma',
      fr: 'Qui signe',
      hi: 'कौन हस्ताक्षर करता है',
      id: 'Yang menandatangani',
      pt: 'Quem assina',
    },
    'label.requesters': {
      en: 'Who asks',
      ko: '청하는 쪽',
      ja: '依頼する側',
      zh: '申请方',
      ar: 'من يطلب',
      es: 'Quién pide',
      fr: 'Qui demande',
      hi: 'कौन माँगता है',
      id: 'Yang meminta',
      pt: 'Quem pede',
    },
    'label.verifier': {
      en: 'Receiver',
      ko: '받는 쪽',
      ja: '受け手',
      zh: '接收方',
      ar: 'المستلم',
      es: 'Receptor',
      fr: 'Destinataire',
      hi: 'प्राप्तकर्ता',
      id: 'Penerima',
      pt: 'Receptor',
    },
    'label.store': {
      en: 'Trust store',
      ko: '신뢰 저장소',
      ja: '信頼ストア',
      zh: '信任存储',
      ar: 'مخزن الثقة',
      es: 'Almacén de confianza',
      fr: 'Magasin de confiance',
      hi: 'ट्रस्ट स्टोर',
      id: 'Penyimpanan tepercaya',
      pt: 'Repositório confiável',
    },
    'label.verify': {
      en: 'Signature check',
      ko: '서명 확인',
      ja: '署名の確認',
      zh: '签名检查',
      ar: 'فحص التوقيع',
      es: 'Comprobación de firma',
      fr: 'Contrôle de signature',
      hi: 'हस्ताक्षर जाँच',
      id: 'Pemeriksaan tanda tangan',
      pt: 'Verificação da assinatura',
    },
    'label.pass': {
      en: 'Accepted',
      ko: '통과',
      ja: '通過',
      zh: '通过',
      ar: 'مقبولة',
      es: 'Aceptado',
      fr: 'Accepté',
      hi: 'स्वीकृत',
      id: 'Diterima',
      pt: 'Aceito',
    },
    'label.ca': {
      en: 'CA',
      ko: 'CA',
      ja: 'CA',
      zh: 'CA',
      ar: 'CA',
      es: 'CA',
      fr: 'CA',
      hi: 'CA',
      id: 'CA',
      pt: 'CA',
    },
    'label.fakeRoot': {
      en: 'Fake root',
      ko: '가짜 뿌리',
      ja: '偽のルート',
      zh: '伪造根',
      ar: 'جذر مزيّف',
      es: 'Raíz falsa',
      fr: 'Fausse racine',
      hi: 'नकली मूल',
      id: 'Akar palsu',
      pt: 'Raiz falsa',
    },
    'label.owner': {
      en: 'Owner',
      ko: '주인',
      ja: '持ち主',
      zh: '所有者',
      ar: 'المالك',
      es: 'Dueño',
      fr: 'Propriétaire',
      hi: 'मालिक',
      id: 'Pemilik',
      pt: 'Dono',
    },
    'label.mallory': {
      en: 'Attacker',
      ko: '공격자',
      ja: '攻撃者',
      zh: '攻击者',
      ar: 'المهاجم',
      es: 'Atacante',
      fr: 'Attaquant',
      hi: 'हमलावर',
      id: 'Penyerang',
      pt: 'Atacante',
    },
    'label.tries': {
      en: 'Forger tries {n}',
      ko: '공격자 후보 {n}',
      ja: '攻撃者の候補 {n}',
      zh: '攻击者尝试 {n}',
      ar: 'محاولات المزوّر {n}',
      es: 'Intentos del atacante {n}',
      fr: 'Essais du faussaire {n}',
      hi: 'हमलावर के प्रयास {n}',
      id: 'Percobaan penyerang {n}',
      pt: 'Tentativas do atacante {n}',
    },
    'label.target': {
      en: 'Target',
      ko: '목표',
      ja: '目標',
      zh: '目标',
      ar: 'الهدف',
      es: 'Objetivo',
      fr: 'Cible',
      hi: 'लक्ष्य',
      id: 'Sasaran',
      pt: 'Alvo',
    },
    'label.request': {
      en: 'Sent to the CA',
      ko: 'CA 에 청함',
      ja: 'CA に依頼',
      zh: '交给 CA',
      ar: 'مُرسلة إلى CA',
      es: 'Enviado a la CA',
      fr: 'Envoyé à la CA',
      hi: 'CA को भेजा',
      id: 'Dikirim ke CA',
      pt: 'Enviado à CA',
    },
    'label.forged': {
      en: 'Forged certificate',
      ko: '위조 인증서',
      ja: '偽造証明書',
      zh: '伪造证书',
      ar: 'شهادة مزوّرة',
      es: 'Certificado falso',
      fr: 'Faux certificat',
      hi: 'जाली प्रमाणपत्र',
      id: 'Sertifikat palsu',
      pt: 'Certificado falso',
    },
    'label.sig': {
      en: 'sig {s}',
      ko: '서명 {s}',
      ja: '署名 {s}',
      zh: '签名 {s}',
      ar: 'توقيع {s}',
      es: 'firma {s}',
      fr: 'sig. {s}',
      hi: 'हस्ता. {s}',
      id: 'ttd {s}',
      pt: 'assin. {s}',
    },
    'label.issuer': {
      en: 'issuer ({n}, {e})',
      ko: '발급자 ({n}, {e})',
      ja: '発行者 ({n}, {e})',
      zh: '签发者 ({n}, {e})',
      ar: 'المُصدِر ({n}, {e})',
      es: 'emisor ({n}, {e})',
      fr: 'émetteur ({n}, {e})',
      hi: 'जारीकर्ता ({n}, {e})',
      id: 'penerbit ({n}, {e})',
      pt: 'emissor ({n}, {e})',
    },
    'label.through': {
      en: 'Passed',
      ko: '지나감',
      ja: '通り抜けた',
      zh: '已通过',
      ar: 'عبرت',
      es: 'Pasó',
      fr: 'Franchi',
      hi: 'पार हुआ',
      id: 'Lolos',
      pt: 'Passou',
    },
    'label.blocked': {
      en: 'Stopped here',
      ko: '여기서 막힘',
      ja: 'ここで止まる',
      zh: '在此被拦',
      ar: 'توقفت هنا',
      es: 'Se detiene aquí',
      fr: 'Arrêté ici',
      hi: 'यहीं रुका',
      id: 'Berhenti di sini',
      pt: 'Parou aqui',
    },
    'label.accepted': {
      en: 'Made it through',
      ko: '끝까지 왔다',
      ja: '最後まで来た',
      zh: '一路通过',
      ar: 'وصلت إلى النهاية',
      es: 'Llegó hasta el final',
      fr: 'Arrivé au bout',
      hi: 'अंत तक पहुँचा',
      id: 'Sampai ke ujung',
      pt: 'Chegou ao fim',
    },
    'label.recovered': {
      en: 'opened {r} · signed value {x}',
      ko: '푼 값 {r} · 서명받는 수 {x}',
      ja: '開いた値 {r} · 署名された数 {x}',
      zh: '解开的值 {r} · 被签名的数 {x}',
      ar: 'القيمة المفكوكة {r} · القيمة الموقّعة {x}',
      es: 'abierto {r} · valor firmado {x}',
      fr: 'ouvert {r} · valeur signée {x}',
      hi: 'खोला मान {r} · हस्ताक्षरित मान {x}',
      id: 'dibuka {r} · nilai bertanda tangan {x}',
      pt: 'aberto {r} · valor assinado {x}',
    },
    'card.doc': {
      en: 'number {v}',
      ko: '문서 번호 {v}',
      ja: '文書番号 {v}',
      zh: '文档编号 {v}',
      ar: 'رقم المستند {v}',
      es: 'número {v}',
      fr: 'numéro {v}',
      hi: 'संख्या {v}',
      id: 'nomor {v}',
      pt: 'número {v}',
    },
    'card.digest': {
      en: 'digest {v} (H {h})',
      ko: '요약 {v} (H {h})',
      ja: '要約 {v} (H {h})',
      zh: '摘要 {v} (H {h})',
      ar: 'الملخص {v} (H {h})',
      es: 'resumen {v} (H {h})',
      fr: 'condensé {v} (H {h})',
      hi: 'सारांश {v} (H {h})',
      id: 'ringkasan {v} (H {h})',
      pt: 'resumo {v} (H {h})',
    },
    'caption.start': {
      en: 'Goal: the name {target} carrying the attacker key ({n}, {e})',
      ko: '목표: 이름 {target} · 공격자 열쇠 ({n}, {e})',
      ja: '目標: 名前 {target} · 攻撃者の鍵 ({n}, {e})',
      zh: '目标: 名称 {target} 配上攻击者的密钥 ({n}, {e})',
      ar: 'الهدف: الاسم {target} مع مفتاح المهاجم ({n}, {e})',
      es: 'Objetivo: el nombre {target} con la clave del atacante ({n}, {e})',
      fr: 'But : le nom {target} avec la clé de l’attaquant ({n}, {e})',
      hi: 'लक्ष्य: नाम {target} के साथ हमलावर की कुंजी ({n}, {e})',
      id: 'Sasaran: nama {target} dengan kunci penyerang ({n}, {e})',
      pt: 'Alvo: o nome {target} com a chave do atacante ({n}, {e})',
    },
    'caption.multiply': {
      en: 'Multiply: after {tries} tries, {a} × {b} mod {n} = {x}',
      ko: '곱하기: 후보 {tries} 번째에 {a} × {b} mod {n} = {x}',
      ja: '掛け算: 候補 {tries} 番目で {a} × {b} mod {n} = {x}',
      zh: '相乘: 第 {tries} 次尝试时 {a} × {b} mod {n} = {x}',
      ar: 'الضرب: بعد {tries} محاولة، {a} × {b} mod {n} = {x}',
      es: 'Multiplicar: tras {tries} intentos, {a} × {b} mod {n} = {x}',
      fr: 'Multiplier : après {tries} essais, {a} × {b} mod {n} = {x}',
      hi: 'गुणा: {tries} प्रयासों के बाद {a} × {b} mod {n} = {x}',
      id: 'Kalikan: setelah {tries} percobaan, {a} × {b} mod {n} = {x}',
      pt: 'Multiplicar: após {tries} tentativas, {a} × {b} mod {n} = {x}',
    },
    'caption.multiplyDigest': {
      en: 'Multiply: after {tries} tries, e {ea} · e {eb} (by document number); digests {da} × {db} mod {n} = {p}',
      ko: '곱하기: 후보 {tries} 번째에 e {ea} · e {eb} (문서 번호로 고름) · 요약 {da} × {db} mod {n} = {p}',
      ja: '掛け算: 候補 {tries} 番目で e {ea} · e {eb} (文書番号で選ぶ) · 要約 {da} × {db} mod {n} = {p}',
      zh: '相乘: 第 {tries} 次尝试时 e {ea} · e {eb} (按文档编号选出) · 摘要 {da} × {db} mod {n} = {p}',
      ar: 'الضرب: بعد {tries} محاولة، e {ea} · e {eb} (بحسب رقم المستند)؛ الملخصان {da} × {db} mod {n} = {p}',
      es: 'Multiplicar: tras {tries} intentos, e {ea} · e {eb} (por número de documento); resúmenes {da} × {db} mod {n} = {p}',
      fr: 'Multiplier : après {tries} essais, e {ea} · e {eb} (par numéro de document) ; condensés {da} × {db} mod {n} = {p}',
      hi: 'गुणा: {tries} प्रयासों के बाद e {ea} · e {eb} (दस्तावेज़ संख्या से चुने); सारांश {da} × {db} mod {n} = {p}',
      id: 'Kalikan: setelah {tries} percobaan, e {ea} · e {eb} (menurut nomor dokumen); ringkasan {da} × {db} mod {n} = {p}',
      pt: 'Multiplicar: após {tries} tentativas, e {ea} · e {eb} (pelo número do documento); resumos {da} × {db} mod {n} = {p}',
    },
    'caption.pair': {
      en: 'Colliding pair after {tries} certificates: e {e1} and e {e2} both give {v}',
      ko: '겹치는 짝: 인증서 {tries} 장째 · e {e1} · e {e2} 둘 다 {v}',
      ja: '衝突する組: 証明書 {tries} 枚目 · e {e1} と e {e2} がどちらも {v}',
      zh: '碰撞对: 第 {tries} 张证书时 e {e1} 与 e {e2} 都得 {v}',
      ar: 'زوج متصادم بعد {tries} شهادة: e {e1} و e {e2} كلاهما يعطي {v}',
      es: 'Par en colisión tras {tries} certificados: e {e1} y e {e2} dan {v}',
      fr: 'Paire en collision après {tries} certificats : e {e1} et e {e2} donnent {v}',
      hi: '{tries} प्रमाणपत्रों के बाद टकराती जोड़ी: e {e1} और e {e2} दोनों {v}',
      id: 'Pasangan bertabrakan setelah {tries} sertifikat: e {e1} dan e {e2} sama-sama {v}',
      pt: 'Par em colisão após {tries} certificados: e {e1} e e {e2} dão {v}',
    },
    'caption.pairNone': {
      en: 'No colliding pair in {tries} certificates: the attacker keeps only e {e}',
      ko: '인증서 {tries} 장에 짝이 없다 · 공격자는 e {e} 하나만 받는다',
      ja: '証明書 {tries} 枚に組はない · 攻撃者は e {e} だけを受け取る',
      zh: '{tries} 张证书中没有碰撞对: 攻击者只拿到 e {e}',
      ar: 'لا زوج متصادم في {tries} شهادة: يحتفظ المهاجم بـ e {e} فقط',
      es: 'Ningún par en colisión en {tries} certificados: el atacante solo obtiene e {e}',
      fr: 'Aucune paire en collision sur {tries} certificats : l’attaquant n’obtient que e {e}',
      hi: '{tries} प्रमाणपत्रों में कोई टकराती जोड़ी नहीं: हमलावर को केवल e {e} मिलता है',
      id: 'Tak ada pasangan bertabrakan dalam {tries} sertifikat: penyerang hanya mendapat e {e}',
      pt: 'Nenhum par em colisão em {tries} certificados: o atacante só obtém e {e}',
    },
    'caption.swap': {
      en: 'Key swap: the owner asks the CA for {name} ({n}, {e})',
      ko: '바꿔 끼우기: 주인이 CA 에 청한 인증서 {name} ({n}, {e})',
      ja: '鍵のすり替え: 持ち主が CA に依頼した証明書 {name} ({n}, {e})',
      zh: '换钥匙: 所有者向 CA 申请 {name} ({n}, {e})',
      ar: 'تبديل المفتاح: يطلب المالك من CA الشهادة {name} ({n}, {e})',
      es: 'Cambio de clave: el dueño pide a la CA {name} ({n}, {e})',
      fr: 'Échange de clé : le propriétaire demande à la CA {name} ({n}, {e})',
      hi: 'कुंजी बदलना: मालिक CA से {name} ({n}, {e}) माँगता है',
      id: 'Tukar kunci: pemilik meminta CA untuk {name} ({n}, {e})',
      pt: 'Troca de chave: o dono pede à CA {name} ({n}, {e})',
    },
    'caption.fakeroot': {
      en: 'Fake root: the attacker sets up its own {name} with key ({n}, {e})',
      ko: '가짜 뿌리: 공격자가 세운 {name} · 열쇠 ({n}, {e})',
      ja: '偽のルート: 攻撃者が立てた {name} · 鍵 ({n}, {e})',
      zh: '伪造根: 攻击者自建 {name},密钥 ({n}, {e})',
      ar: 'جذر مزيّف: ينشئ المهاجم {name} خاصًا به بالمفتاح ({n}, {e})',
      es: 'Raíz falsa: el atacante monta su propio {name} con clave ({n}, {e})',
      fr: 'Fausse racine : l’attaquant monte son propre {name} avec la clé ({n}, {e})',
      hi: 'नकली मूल: हमलावर अपना {name} कुंजी ({n}, {e}) के साथ खड़ा करता है',
      id: 'Akar palsu: penyerang mendirikan {name} sendiri dengan kunci ({n}, {e})',
      pt: 'Raiz falsa: o atacante monta seu próprio {name} com a chave ({n}, {e})',
    },
    'caption.signed': {
      en: '{who} signs: {sums}',
      ko: '{who} 서명: {sums}',
      ja: '{who} の署名: {sums}',
      zh: '{who} 签名: {sums}',
      ar: 'توقيع {who}: {sums}',
      es: '{who} firma: {sums}',
      fr: '{who} signe : {sums}',
      hi: '{who} हस्ताक्षर करता है: {sums}',
      id: '{who} menandatangani: {sums}',
      pt: '{who} assina: {sums}',
    },
    'caption.forge.multiply': {
      en: 'Multiply the two signatures: {s1} × {s2} mod {n} = {s}',
      ko: '두 서명을 곱한다: {s1} × {s2} mod {n} = {s}',
      ja: '2つの署名を掛ける: {s1} × {s2} mod {n} = {s}',
      zh: '两个签名相乘: {s1} × {s2} mod {n} = {s}',
      ar: 'اضرب التوقيعين: {s1} × {s2} mod {n} = {s}',
      es: 'Multiplica las dos firmas: {s1} × {s2} mod {n} = {s}',
      fr: 'Multiplier les deux signatures : {s1} × {s2} mod {n} = {s}',
      hi: 'दोनों हस्ताक्षरों का गुणा: {s1} × {s2} mod {n} = {s}',
      id: 'Kalikan kedua tanda tangan: {s1} × {s2} mod {n} = {s}',
      pt: 'Multiplica as duas assinaturas: {s1} × {s2} mod {n} = {s}',
    },
    'caption.forge.fakeroot': {
      en: 'Sent: signature {s} with the fake root key ({n}, {e})',
      ko: '보냄: 서명 {s} · 가짜 뿌리 열쇠 ({n}, {e})',
      ja: '送る: 署名 {s} · 偽のルートの鍵 ({n}, {e})',
      zh: '发出: 签名 {s} 附带伪造根的密钥 ({n}, {e})',
      ar: 'أُرسل: التوقيع {s} مع مفتاح الجذر المزيّف ({n}, {e})',
      es: 'Enviado: firma {s} con la clave de la raíz falsa ({n}, {e})',
      fr: 'Envoyé : signature {s} avec la clé de la fausse racine ({n}, {e})',
      hi: 'भेजा: हस्ताक्षर {s} नकली मूल की कुंजी ({n}, {e}) के साथ',
      id: 'Dikirim: tanda tangan {s} dengan kunci akar palsu ({n}, {e})',
      pt: 'Enviado: assinatura {s} com a chave da raiz falsa ({n}, {e})',
    },
    'caption.forge.move': {
      en: 'Signature {s} moved onto {subject} ({n}, {e})',
      ko: '서명 {s} 옮겨 붙임 → {subject} ({n}, {e})',
      ja: '署名 {s} を付け替え → {subject} ({n}, {e})',
      zh: '签名 {s} 移到 {subject} ({n}, {e}) 上',
      ar: 'نُقل التوقيع {s} إلى {subject} ({n}, {e})',
      es: 'Firma {s} trasladada a {subject} ({n}, {e})',
      fr: 'Signature {s} déplacée sur {subject} ({n}, {e})',
      hi: 'हस्ताक्षर {s} को {subject} ({n}, {e}) पर लगाया',
      id: 'Tanda tangan {s} dipindah ke {subject} ({n}, {e})',
      pt: 'Assinatura {s} passada para {subject} ({n}, {e})',
    },
    'caption.store.ok': {
      en: 'Trust store: issuer key ({n}, {e}) = stored ({sn}, {se}), goes on',
      ko: '신뢰 저장소: 발급자 열쇠 ({n}, {e}) = 저장된 ({sn}, {se}) · 지나간다',
      ja: '信頼ストア: 発行者の鍵 ({n}, {e}) = 保存済み ({sn}, {se}) · 通る',
      zh: '信任存储: 签发者密钥 ({n}, {e}) = 存储的 ({sn}, {se}),继续',
      ar: 'مخزن الثقة: مفتاح المُصدِر ({n}, {e}) = المخزَّن ({sn}, {se})، تستمر',
      es: 'Almacén de confianza: clave del emisor ({n}, {e}) = guardada ({sn}, {se}), sigue',
      fr: 'Magasin de confiance : clé de l’émetteur ({n}, {e}) = stockée ({sn}, {se}), continue',
      hi: 'ट्रस्ट स्टोर: जारीकर्ता कुंजी ({n}, {e}) = संग्रहीत ({sn}, {se}), आगे बढ़ा',
      id: 'Penyimpanan tepercaya: kunci penerbit ({n}, {e}) = tersimpan ({sn}, {se}), lanjut',
      pt: 'Repositório confiável: chave do emissor ({n}, {e}) = guardada ({sn}, {se}), segue',
    },
    'caption.store.blocked': {
      en: 'Trust store: issuer key ({n}, {e}) ≠ stored ({sn}, {se}), stopped here',
      ko: '신뢰 저장소: 발급자 열쇠 ({n}, {e}) ≠ 저장된 ({sn}, {se}) · 여기서 막힌다',
      ja: '信頼ストア: 発行者の鍵 ({n}, {e}) ≠ 保存済み ({sn}, {se}) · ここで止まる',
      zh: '信任存储: 签发者密钥 ({n}, {e}) ≠ 存储的 ({sn}, {se}),在此被拦',
      ar: 'مخزن الثقة: مفتاح المُصدِر ({n}, {e}) ≠ المخزَّن ({sn}, {se})، توقفت هنا',
      es: 'Almacén de confianza: clave del emisor ({n}, {e}) ≠ guardada ({sn}, {se}), se detiene aquí',
      fr: 'Magasin de confiance : clé de l’émetteur ({n}, {e}) ≠ stockée ({sn}, {se}), arrêté ici',
      hi: 'ट्रस्ट स्टोर: जारीकर्ता कुंजी ({n}, {e}) ≠ संग्रहीत ({sn}, {se}), यहीं रुका',
      id: 'Penyimpanan tepercaya: kunci penerbit ({n}, {e}) ≠ tersimpan ({sn}, {se}), berhenti di sini',
      pt: 'Repositório confiável: chave do emissor ({n}, {e}) ≠ guardada ({sn}, {se}), parou aqui',
    },
    'caption.verify.pass': {
      en: 'Signature check: {s}^{e} mod {n} = {r} = signed value {x}, accepted',
      ko: '서명 확인: {s}^{e} mod {n} = {r} = 서명받는 수 {x} · 통과',
      ja: '署名の確認: {s}^{e} mod {n} = {r} = 署名された数 {x} · 通過',
      zh: '签名检查: {s}^{e} mod {n} = {r} = 被签名的数 {x},通过',
      ar: 'فحص التوقيع: {s}^{e} mod {n} = {r} = القيمة الموقّعة {x}، مقبولة',
      es: 'Comprobación de firma: {s}^{e} mod {n} = {r} = valor firmado {x}, aceptado',
      fr: 'Contrôle de signature : {s}^{e} mod {n} = {r} = valeur signée {x}, accepté',
      hi: 'हस्ताक्षर जाँच: {s}^{e} mod {n} = {r} = हस्ताक्षरित मान {x}, स्वीकृत',
      id: 'Pemeriksaan tanda tangan: {s}^{e} mod {n} = {r} = nilai bertanda tangan {x}, diterima',
      pt: 'Verificação da assinatura: {s}^{e} mod {n} = {r} = valor assinado {x}, aceito',
    },
    'caption.verify.blocked': {
      en: 'Signature check: {s}^{e} mod {n} = {r} ≠ signed value {x}, stopped here',
      ko: '서명 확인: {s}^{e} mod {n} = {r} ≠ 서명받는 수 {x} · 여기서 막힌다',
      ja: '署名の確認: {s}^{e} mod {n} = {r} ≠ 署名された数 {x} · ここで止まる',
      zh: '签名检查: {s}^{e} mod {n} = {r} ≠ 被签名的数 {x},在此被拦',
      ar: 'فحص التوقيع: {s}^{e} mod {n} = {r} ≠ القيمة الموقّعة {x}، توقفت هنا',
      es: 'Comprobación de firma: {s}^{e} mod {n} = {r} ≠ valor firmado {x}, se detiene aquí',
      fr: 'Contrôle de signature : {s}^{e} mod {n} = {r} ≠ valeur signée {x}, arrêté ici',
      hi: 'हस्ताक्षर जाँच: {s}^{e} mod {n} = {r} ≠ हस्ताक्षरित मान {x}, यहीं रुका',
      id: 'Pemeriksaan tanda tangan: {s}^{e} mod {n} = {r} ≠ nilai bertanda tangan {x}, berhenti di sini',
      pt: 'Verificação da assinatura: {s}^{e} mod {n} = {r} ≠ valor assinado {x}, parou aqui',
    },
  },
};
