/**
 * @piece 밀도 기반 군집 — 무리를 "가운데로부터의 거리" 말고 무엇으로 정할 수 있는가.
 *
 * 답 하나: **이웃의 이웃으로 번지는 것**으로 정할 수 있다. 가운데를 아예 두지
 * 않으므로 무리가 둥글 필요가 없다.
 *
 * 자료는 바깥 고리 열넷과 가운데 덩이 여섯이다. 좌표는 구조이므로 여기 두고,
 * 화면 좌표·거리·이웃 수는 전부 algorithm 과 stage 가 이 좌표에서 셈한다 (S-piece).
 */

import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

export const denseNeighborhoodFacet: FacetJson = {
  id: 'facet:denseNeighborhood',
  title: {
    en: 'A group is what the spreading reaches',
    ko: '번짐이 닿는 데까지가 한 무리',
    ja: '広がりが届く範囲がひとつの集まり',
    zh: '蔓延所及即为一群',
    ar: 'المجموعة هي ما يبلغه الانتشار',
    es: 'Un grupo es hasta donde llega la propagación',
    fr: "Un groupe, c'est jusqu'où la propagation atteint",
    hi: 'जहाँ तक फैलाव पहुँचे, वहीं तक एक समूह',
    id: 'Satu kelompok adalah sejauh perambatan sampai',
    pt: 'Um grupo é até onde o alastramento chega',
  },
  description: {
    en: 'Neighbours of neighbours join the same group, so the group need not be round.',
    ko: '이웃의 이웃이 같은 무리가 된다. 그래서 무리가 둥글 필요가 없다.',
    ja: '隣の隣も同じ集まりに入る。だから集まりが丸い必要はない。',
    zh: '邻居的邻居也归入同一群，所以群不必是圆的。',
    ar: 'جيران الجيران ينضمون إلى المجموعة نفسها، فلا حاجة لأن تكون المجموعة مستديرة.',
    es: 'Los vecinos de los vecinos entran al mismo grupo, así que el grupo no tiene por qué ser redondo.',
    fr: "Les voisins des voisins rejoignent le même groupe : le groupe n'a donc pas à être rond.",
    hi: 'पड़ोसियों के पड़ोसी भी उसी समूह में आ जाते हैं, इसलिए समूह का गोल होना जरूरी नहीं।',
    id: 'Tetangga dari tetangga masuk kelompok yang sama, jadi kelompok tak perlu bulat.',
    pt: 'Os vizinhos dos vizinhos entram no mesmo grupo, por isso o grupo não precisa ser redondo.',
  },
  algorithm: 'module:denseNeighborhood',
  projector: 'module:denseNeighborhoodProjector',
  initialData: {
    type: 'dense-neighborhood',
    points: [
      { x: 7.2, y: 4.0 },
      { x: 6.88, y: 5.39 },
      { x: 6.0, y: 6.5 },
      { x: 4.71, y: 7.12 },
      { x: 3.29, y: 7.12 },
      { x: 2.0, y: 6.5 },
      { x: 1.12, y: 5.39 },
      { x: 0.8, y: 4.0 },
      { x: 1.12, y: 2.61 },
      { x: 2.0, y: 1.5 },
      { x: 3.29, y: 0.88 },
      { x: 4.71, y: 0.88 },
      { x: 6.0, y: 1.5 },
      { x: 6.88, y: 2.61 },
      { x: 4.0, y: 4.0 },
      { x: 4.5, y: 4.2 },
      { x: 3.6, y: 4.4 },
      { x: 4.2, y: 3.5 },
      { x: 3.5, y: 3.6 },
      { x: 4.6, y: 3.7 },
    ],
    eps: 1.6,
    minPts: 3,
    stepMs: 700,
  },
  blocks: {
    stage: { type: 'dense-neighborhood-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'caption.start': {
      en: 'Points on a plane, no group yet. Count: {n}.',
      ko: '평면 위의 점들. 아직 무리는 없다. 개수: {n}.',
      ja: '平面上の点。まだ集まりはない。個数: {n}。',
      zh: '平面上的点，还没有分群。数量：{n}。',
      ar: 'نقاط على مستوٍ، لا مجموعات بعد. العدد: {n}.',
      es: 'Puntos en un plano, aún sin grupos. Cantidad: {n}.',
      fr: 'Des points sur un plan, pas encore de groupe. Nombre : {n}.',
      hi: 'समतल पर बिंदु, अभी कोई समूह नहीं। संख्या: {n}।',
      id: 'Titik-titik pada bidang, belum ada kelompok. Jumlah: {n}.',
      pt: 'Pontos num plano, ainda sem grupo. Quantidade: {n}.',
    },
    'caption.ignite': {
      en: 'A spark here. Neighbours inside eps, itself included: {n}.',
      ko: '여기에 불씨를 놓는다. eps 안의 이웃은 자기를 넣어 {n}.',
      ja: 'ここに火種を置く。eps 内の隣は自分を入れて {n}。',
      zh: '在这里点一个火种。eps 内的邻居，含自身：{n}。',
      ar: 'شرارة هنا. الجيران داخل eps، بما فيها هي نفسها: {n}.',
      es: 'Una chispa aquí. Vecinos dentro de eps, incluido él mismo: {n}.',
      fr: 'Une étincelle ici. Voisins dans eps, lui compris : {n}.',
      hi: 'यहाँ एक चिंगारी। eps के भीतर पड़ोसी, स्वयं सहित: {n}।',
      id: 'Sebuah percikan di sini. Tetangga dalam eps, termasuk dirinya: {n}.',
      pt: 'Uma faísca aqui. Vizinhos dentro de eps, ele incluído: {n}.',
    },
    'caption.reignite': {
      en: 'A new spark where the fire never reached. Neighbours inside eps: {n}.',
      ko: '불이 닿지 않은 곳에 새 불씨를 놓는다. eps 안의 이웃은 {n}.',
      ja: '火の届かなかった場所に新しい火種を置く。eps 内の隣は {n}。',
      zh: '在火没烧到的地方点新火种。eps 内的邻居：{n}。',
      ar: 'شرارة جديدة حيث لم تصل النار. الجيران داخل eps: {n}.',
      es: 'Una nueva chispa donde el fuego no llegó. Vecinos dentro de eps: {n}.',
      fr: "Une nouvelle étincelle là où le feu n'est pas allé. Voisins dans eps : {n}.",
      hi: 'जहाँ आग नहीं पहुँची, वहाँ नई चिंगारी। eps के भीतर पड़ोसी: {n}।',
      id: 'Percikan baru di tempat api tak pernah sampai. Tetangga dalam eps: {n}.',
      pt: 'Uma nova faísca onde o fogo não chegou. Vizinhos dentro de eps: {n}.',
    },
    'caption.spread': {
      en: 'The fire jumps to the neighbours of neighbours. In the group: {total}.',
      ko: '이웃의 이웃으로 옮아붙는다. 무리에 든 것은 {total}.',
      ja: '火が隣の隣へ移る。集まりに入ったのは {total}。',
      zh: '火苗跳到邻居的邻居。已入群：{total}。',
      ar: 'تنتقل النار إلى جيران الجيران. في المجموعة: {total}.',
      es: 'El fuego salta a los vecinos de los vecinos. En el grupo: {total}.',
      fr: 'Le feu saute aux voisins des voisins. Dans le groupe : {total}.',
      hi: 'आग पड़ोसियों के पड़ोसियों तक फैलती है। समूह में: {total}।',
      id: 'Api meloncat ke tetangga dari tetangga. Dalam kelompok: {total}.',
      pt: 'O fogo salta para os vizinhos dos vizinhos. No grupo: {total}.',
    },
    'caption.blocked': {
      en: 'Nothing more inside eps. Distance to the nearest point outside: {d}.',
      ko: 'eps 안에 더는 이웃이 없다. 무리 밖에서 가장 가까운 점까지의 거리는 {d}.',
      ja: 'eps 内にもう隣はない。外で最も近い点までの距離は {d}。',
      zh: 'eps 内再没有邻居。到群外最近点的距离是 {d}。',
      ar: 'لا شيء آخر داخل eps. المسافة إلى أقرب نقطة بالخارج: {d}.',
      es: 'Ya no hay nada más dentro de eps. Distancia al punto más cercano de fuera: {d}.',
      fr: 'Plus rien dans eps. Distance au point extérieur le plus proche : {d}.',
      hi: 'eps के भीतर और कुछ नहीं। बाहर के निकटतम बिंदु तक दूरी: {d}।',
      id: 'Tak ada lagi di dalam eps. Jarak ke titik terdekat di luar: {d}.',
      pt: 'Não há mais nada dentro de eps. Distância ao ponto mais próximo de fora: {d}.',
    },
    'caption.done': {
      en: 'Groups the fire settled into: {k}. Sizes: {list}.',
      ko: '불이 앉은 무리의 수는 {k}. 크기: {list}.',
      ja: '火が落ち着いた集まりは {k}。大きさ: {list}。',
      zh: '火最终落定的群：{k}。大小：{list}。',
      ar: 'المجموعات التي استقرت فيها النار: {k}. الأحجام: {list}.',
      es: 'Grupos donde el fuego se asentó: {k}. Tamaños: {list}.',
      fr: "Groupes où le feu s'est posé : {k}. Tailles : {list}.",
      hi: 'आग जिन समूहों में ठहरी: {k}। आकार: {list}।',
      id: 'Kelompok tempat api mengendap: {k}. Ukuran: {list}.',
      pt: 'Grupos onde o fogo assentou: {k}. Tamanhos: {list}.',
    },
    'label.pairDistance': {
      en: 'distance between the two points',
      ko: '두 점 사이의 거리',
      ja: '二点間の距離',
      zh: '两点之间的距离',
      ar: 'المسافة بين النقطتين',
      es: 'distancia entre los dos puntos',
      fr: 'distance entre les deux points',
      hi: 'दोनों बिंदुओं के बीच की दूरी',
      id: 'jarak antara dua titik',
      pt: 'distância entre os dois pontos',
    },
    'label.linked': {
      en: 'linked',
      ko: '이어진다',
      ja: 'つながる',
      zh: '相连',
      ar: 'متصل',
      es: 'conectado',
      fr: 'relié',
      hi: 'जुड़े हुए',
      id: 'tersambung',
      pt: 'ligado',
    },
    'label.tooFar': {
      en: 'too far',
      ko: '너무 멀다',
      ja: '遠すぎる',
      zh: '太远',
      ar: 'بعيد جدًا',
      es: 'demasiado lejos',
      fr: 'trop loin',
      hi: 'बहुत दूर',
      id: 'terlalu jauh',
      pt: 'longe demais',
    },
  },
};
