import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: CDN 을 쓰면 먼 나라의 사용자도 왜 빨리 받는가.
 *
 * 네 도시의 사용자 요청이 저마다 왕복이 가장 짧은 엣지로 가서 거기서 돌아선다.
 * 오리진까지의 먼 길은 걷지 않은 길로 남는다.
 */
export const serveFromNearFacet: FacetJson = {
  id: 'facet:serveFromNear',
  title: {
    en: 'Served from nearby',
    ko: '가까운 곳에서 내어 준다',
    ja: '近くから届ける',
    zh: '就近提供',
    ar: 'التقديم من الأقرب',
    es: 'Servido desde cerca',
    fr: 'Servi depuis tout près',
    hi: 'पास से परोसा गया',
    id: 'Dilayani dari dekat',
    pt: 'Servido de perto',
  },
  description: {
    en: 'Each request turns back at the nearest edge, so the long road to the origin is never walked.',
    ko: '요청마다 가장 가까운 엣지에서 돌아서고, 오리진까지의 먼 길은 걷지 않는다.',
    ja: '各リクエストは最も近いエッジで折り返し、オリジンまでの長い道は通らない。',
    zh: '每个请求都在最近的边缘节点折返，通往源站的远路从未走过。',
    ar: 'يعود كل طلب من أقرب حافة، فلا يُسلك الطريق الطويل إلى الأصل أبدًا.',
    es: 'Cada solicitud da la vuelta en el borde más cercano; el largo camino al origen nunca se recorre.',
    fr: 'Chaque requête fait demi-tour au nœud de bordure le plus proche ; le long chemin vers l’origine n’est jamais parcouru.',
    hi: 'हर अनुरोध सबसे पास के एज से लौट आता है, ओरिजिन तक का लंबा रास्ता कभी तय नहीं होता।',
    id: 'Setiap permintaan berbalik di edge terdekat, jadi jalan panjang ke origin tidak pernah ditempuh.',
    pt: 'Cada requisição volta na borda mais próxima; o longo caminho até a origem nunca é percorrido.',
  },
  algorithm: 'module:serveFromNear',
  scene: 'module:serveFromNearScene',
  initialData: {
    type: 'serve-from-near',
    stepMs: 1800,
    edges: ['icn', 'fra', 'gru'],
    origin: 'iad',
    holding: ['icn', 'fra', 'gru'],
    users: ['seoul', 'tokyo', 'berlin', 'lima'],
    rtt: {
      seoul: { icn: 5, fra: 250, gru: 320, iad: 190 },
      tokyo: { icn: 35, fra: 240, gru: 280, iad: 160 },
      berlin: { icn: 260, fra: 12, gru: 210, iad: 95 },
      lima: { icn: 330, fra: 230, gru: 70, iad: 120 },
    },
  },
  shuffleOnReset: false,
  messages: {
    'caption.ready': {
      en: 'Requests waiting: {n}',
      ko: '기다리는 요청: {n}',
      ja: '待っているリクエスト: {n}',
      zh: '等待中的请求：{n}',
      ar: 'الطلبات المنتظرة: {n}',
      es: 'Solicitudes en espera: {n}',
      fr: 'Requêtes en attente : {n}',
      hi: 'प्रतीक्षा में अनुरोध: {n}',
      id: 'Permintaan menunggu: {n}',
      pt: 'Requisições aguardando: {n}',
    },
    'caption.serve': {
      en: '{user} → {edge}: {ms} ms · Via origin: {origin} ms · Saved: {saved} ms',
      ko: '{user} → {edge}: {ms} ms · 오리진이었다면: {origin} ms · 줄어든 것: {saved} ms',
      ja: '{user} → {edge}: {ms} ms · オリジンなら: {origin} ms · 短縮: {saved} ms',
      zh: '{user} → {edge}：{ms} ms · 若走源站：{origin} ms · 节省：{saved} ms',
      ar: '{user} → {edge}: {ms} ms · عبر الأصل: {origin} ms · الموفَّر: {saved} ms',
      es: '{user} → {edge}: {ms} ms · Por el origen: {origin} ms · Ahorro: {saved} ms',
      fr: '{user} → {edge} : {ms} ms · Via l’origine : {origin} ms · Gagné : {saved} ms',
      hi: '{user} → {edge}: {ms} ms · ओरिजिन से: {origin} ms · बचत: {saved} ms',
      id: '{user} → {edge}: {ms} ms · Lewat origin: {origin} ms · Hemat: {saved} ms',
      pt: '{user} → {edge}: {ms} ms · Pela origem: {origin} ms · Economia: {saved} ms',
    },
    'label.totals': {
      en: 'Edge total: {edge} ms · Via origin: {origin} ms',
      ko: '엣지 합: {edge} ms · 오리진이었다면: {origin} ms',
      ja: 'エッジ合計: {edge} ms · オリジンなら: {origin} ms',
      zh: '边缘合计：{edge} ms · 若走源站：{origin} ms',
      ar: 'مجموع الحافة: {edge} ms · عبر الأصل: {origin} ms',
      es: 'Total en bordes: {edge} ms · Por el origen: {origin} ms',
      fr: 'Total bordure : {edge} ms · Via l’origine : {origin} ms',
      hi: 'एज कुल: {edge} ms · ओरिजिन से: {origin} ms',
      id: 'Total edge: {edge} ms · Lewat origin: {origin} ms',
      pt: 'Total nas bordas: {edge} ms · Pela origem: {origin} ms',
    },
    'label.ms': {
      en: '{n} ms',
      ko: '{n} ms',
      ja: '{n} ms',
      zh: '{n} ms',
      ar: '{n} ms',
      es: '{n} ms',
      fr: '{n} ms',
      hi: '{n} ms',
      id: '{n} ms',
      pt: '{n} ms',
    },
    'label.edge': {
      en: 'Edge',
      ko: '엣지',
      ja: 'エッジ',
      zh: '边缘',
      ar: 'حافة',
      es: 'Borde',
      fr: 'Bordure',
      hi: 'एज',
      id: 'Edge',
      pt: 'Borda',
    },
    'label.origin': {
      en: 'Origin',
      ko: '오리진',
      ja: 'オリジン',
      zh: '源站',
      ar: 'الأصل',
      es: 'Origen',
      fr: 'Origine',
      hi: 'ओरिजिन',
      id: 'Origin',
      pt: 'Origem',
    },
    'label.city.icn': {
      en: 'Seoul',
      ko: '서울',
      ja: 'ソウル',
      zh: '首尔',
      ar: 'سيول',
      es: 'Seúl',
      fr: 'Séoul',
      hi: 'सियोल',
      id: 'Seoul',
      pt: 'Seul',
    },
    'label.city.fra': {
      en: 'Frankfurt',
      ko: '프랑크푸르트',
      ja: 'フランクフルト',
      zh: '法兰克福',
      ar: 'فرانكفورت',
      es: 'Fráncfort',
      fr: 'Francfort',
      hi: 'फ्रैंकफर्ट',
      id: 'Frankfurt',
      pt: 'Frankfurt',
    },
    'label.city.gru': {
      en: 'São Paulo',
      ko: '상파울루',
      ja: 'サンパウロ',
      zh: '圣保罗',
      ar: 'ساو باولو',
      es: 'São Paulo',
      fr: 'São Paulo',
      hi: 'साओ पाउलो',
      id: 'São Paulo',
      pt: 'São Paulo',
    },
    'label.city.iad': {
      en: 'Virginia',
      ko: '버지니아',
      ja: 'バージニア',
      zh: '弗吉尼亚',
      ar: 'فيرجينيا',
      es: 'Virginia',
      fr: 'Virginie',
      hi: 'वर्जीनिया',
      id: 'Virginia',
      pt: 'Virgínia',
    },
    'label.user.seoul': {
      en: 'Seoul',
      ko: '서울',
      ja: 'ソウル',
      zh: '首尔',
      ar: 'سيول',
      es: 'Seúl',
      fr: 'Séoul',
      hi: 'सियोल',
      id: 'Seoul',
      pt: 'Seul',
    },
    'label.user.tokyo': {
      en: 'Tokyo',
      ko: '도쿄',
      ja: '東京',
      zh: '东京',
      ar: 'طوكيو',
      es: 'Tokio',
      fr: 'Tokyo',
      hi: 'टोक्यो',
      id: 'Tokyo',
      pt: 'Tóquio',
    },
    'label.user.berlin': {
      en: 'Berlin',
      ko: '베를린',
      ja: 'ベルリン',
      zh: '柏林',
      ar: 'برلين',
      es: 'Berlín',
      fr: 'Berlin',
      hi: 'बर्लिन',
      id: 'Berlin',
      pt: 'Berlim',
    },
    'label.user.lima': {
      en: 'Lima',
      ko: '리마',
      ja: 'リマ',
      zh: '利马',
      ar: 'ليما',
      es: 'Lima',
      fr: 'Lima',
      hi: 'लीमा',
      id: 'Lima',
      pt: 'Lima',
    },
  },
  blocks: {
    stage: { type: 'serve-from-near-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
