/**
 * 거짓 공유 — 다른 값인데 같은 줄이라 부딪친다.
 *
 * 질문 하나에만 답한다: 두 코어가 서로 다른 값을 고치는데 왜 서로를 늦추는가.
 *
 * @piece
 */

import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

export const falseSharingFacet: FacetJson = {
  id: 'facet:falseSharing',
  title: {
    en: 'False sharing',
    ko: '거짓 공유',
    ja: 'フォルスシェアリング',
    zh: '伪共享',
    ar: 'المشاركة الزائفة',
    es: 'Compartición falsa',
    fr: 'Faux partage',
    hi: 'फ़ॉल्स शेयरिंग',
    id: 'Berbagi semu',
    pt: 'Compartilhamento falso',
  },
  description: {
    en: 'Two cores touch different values, but one cache line holds both — so every write throws away the other core’s copy.',
    ko: '두 코어가 서로 다른 값을 만지는데 한 캐시 라인이 둘을 품고 있어, 고칠 때마다 상대의 사본이 버려진다.',
    ja: '2 つのコアが別々の値を触るのに、1 つのキャッシュラインが両方を抱えているため、書くたびに相手の複製が捨てられる。',
    zh: '两个核心改的是不同的值，但同一条缓存行同时装着它们，于是每次写入都会作废对方的副本。',
    ar: 'نواتان تعدّلان قيمتين مختلفتين، لكن سطر ذاكرة مخبئية واحدًا يحتويهما معًا، فكل كتابة تُبطل نسخة الأخرى.',
    es: 'Dos núcleos tocan valores distintos, pero una sola línea de caché contiene ambos: cada escritura invalida la copia del otro.',
    fr: "Deux cœurs modifient des valeurs différentes, mais une seule ligne de cache les contient toutes les deux : chaque écriture invalide la copie de l'autre.",
    hi: 'दो कोर अलग-अलग मानों को बदलते हैं, पर एक ही कैश लाइन दोनों को रखती है — इसलिए हर लेखन दूसरे की प्रति को रद्द कर देता है।',
    id: 'Dua inti menyentuh nilai yang berbeda, tetapi satu baris cache memuat keduanya, sehingga setiap tulis membuang salinan pihak lain.',
    pt: 'Dois núcleos alteram valores diferentes, mas uma única linha de cache contém ambos: cada escrita invalida a cópia do outro.',
  },
  algorithm: 'module:falseSharing',
  scene: 'module:falseSharingScene',
  initialData: {
    type: 'false-sharing',
    lineBytes: 16,
    elemBytes: 4,
    together: [0, 1],
    apart: [0, 4],
    writes: 8,
    stepMs: 750,
  },
  blocks: {
    stage: { type: 'false-sharing-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.together': {
      en: 'Core A writes a[{a}], core B writes a[{b}] — two different cells, and one line holds them both: {line}.',
      ko: '코어 A 는 a[{a}] 를, 코어 B 는 a[{b}] 를 고친다 — 서로 다른 칸인데 한 줄이 둘을 품는다: {line}.',
      ja: 'コア A は a[{a}] を、コア B は a[{b}] を書き換える — 別々のマスなのに、ひとつの行が両方を抱える: {line}。',
      zh: '核心 A 写 a[{a}]，核心 B 写 a[{b}] —— 是两个不同的格子，却由同一行装着：{line}。',
      ar: 'النواة A تكتب a[{a}] والنواة B تكتب a[{b}] — خانتان مختلفتان يحتويهما سطر واحد: {line}.',
      es: 'El núcleo A escribe a[{a}] y el núcleo B escribe a[{b}]: dos celdas distintas que una sola línea contiene: {line}.',
      fr: 'Le cœur A écrit a[{a}], le cœur B écrit a[{b}] — deux cases différentes, mais une seule ligne les contient : {line}.',
      hi: 'कोर A लिखता है a[{a}], कोर B लिखता है a[{b}] — दो अलग खाने, फिर भी दोनों एक ही लाइन में: {line}.',
      id: 'Inti A menulis a[{a}], inti B menulis a[{b}] — dua sel berbeda, tetapi satu baris memuat keduanya: {line}.',
      pt: 'O núcleo A escreve a[{a}] e o núcleo B escreve a[{b}] — duas células diferentes que uma só linha contém: {line}.',
    },
    'caption.collide': {
      en: 'A drags the line over to change a[{a}]; B drags it back for a[{b}]. Writes: {writes}. Invalidations: {inval}.',
      ko: 'A 가 a[{a}] 를 고치려고 줄을 끌어가고, B 가 a[{b}] 때문에 도로 끌어온다. 고친 횟수: {writes}. 무효화: {inval}.',
      ja: 'A は a[{a}] を書き換えるため行を引き寄せ、B は a[{b}] のために引き戻す。書き換え: {writes}。無効化: {inval}。',
      zh: 'A 为改 a[{a}] 把这一行拽过去，B 又为 a[{b}] 拽回来。写入次数：{writes}。作废次数：{inval}。',
      ar: 'تسحب A السطر لتعديل a[{a}]، ثم تسحبه B من أجل a[{b}]. الكتابات: {writes}. الإبطالات: {inval}.',
      es: 'A se lleva la línea para cambiar a[{a}]; B la recupera para a[{b}]. Escrituras: {writes}. Invalidaciones: {inval}.',
      fr: 'A tire la ligne pour modifier a[{a}] ; B la reprend pour a[{b}]. Écritures : {writes}. Invalidations : {inval}.',
      hi: 'A उस लाइन को a[{a}] बदलने के लिए खींचता है; B उसे a[{b}] के लिए वापस खींचता है। लेखन: {writes}. रद्दीकरण: {inval}.',
      id: 'A menarik baris itu untuk mengubah a[{a}]; B menariknya kembali demi a[{b}]. Penulisan: {writes}. Pembatalan: {inval}.',
      pt: 'A puxa a linha para alterar a[{a}]; B a puxa de volta por a[{b}]. Escritas: {writes}. Invalidações: {inval}.',
    },
    'caption.tally': {
      en: 'Writes: {writes}. Invalidations: {inval}. Values both cores use: {shared}.',
      ko: '고친 횟수: {writes}. 무효화: {inval}. 두 코어가 함께 쓰는 값: {shared}.',
      ja: '書き換え: {writes}。無効化: {inval}。両方のコアが使う値: {shared}。',
      zh: '写入次数：{writes}。作废次数：{inval}。两个核心共用的值：{shared}。',
      ar: 'الكتابات: {writes}. الإبطالات: {inval}. القيم التي تستخدمها النواتان معًا: {shared}.',
      es: 'Escrituras: {writes}. Invalidaciones: {inval}. Valores que ambos núcleos usan: {shared}.',
      fr: 'Écritures : {writes}. Invalidations : {inval}. Valeurs utilisées par les deux cœurs : {shared}.',
      hi: 'लेखन: {writes}. रद्दीकरण: {inval}. दोनों कोर जिन मानों को साझा करते हैं: {shared}.',
      id: 'Penulisan: {writes}. Pembatalan: {inval}. Nilai yang dipakai kedua inti: {shared}.',
      pt: 'Escritas: {writes}. Invalidações: {inval}. Valores que ambos os núcleos usam: {shared}.',
    },
    'caption.apart': {
      en: 'Give core B a line of its own — a[{b}]. Its address: {addr}. That puts it on another line: {line}.',
      ko: '코어 B 에게 제 줄을 준다 — a[{b}]. 그 주소: {addr}. 그래서 앉는 줄이 달라진다: {line}.',
      ja: 'コア B に自分の行を与える — a[{b}]。そのアドレス: {addr}。だから座る行が変わる: {line}。',
      zh: '给核心 B 一条自己的行 —— a[{b}]。它的地址：{addr}。于是它落在另一行：{line}。',
      ar: 'امنح النواة B سطرًا خاصًا بها — a[{b}]. عنوانها: {addr}. لذلك تقع في سطر آخر: {line}.',
      es: 'Dale al núcleo B una línea propia: a[{b}]. Su dirección: {addr}. Eso lo sitúa en otra línea: {line}.',
      fr: "Donnons au cœur B sa propre ligne — a[{b}]. Son adresse : {addr}. Elle tombe donc sur une autre ligne : {line}.",
      hi: 'कोर B को अपनी लाइन दें — a[{b}]. उसका पता: {addr}. इससे वह दूसरी लाइन पर जाता है: {line}.',
      id: 'Beri inti B baris miliknya sendiri — a[{b}]. Alamatnya: {addr}. Maka ia jatuh di baris lain: {line}.',
      pt: 'Dê ao núcleo B uma linha só dele — a[{b}]. Seu endereço: {addr}. Isso o coloca em outra linha: {line}.',
    },
    'caption.quiet': {
      en: 'Each core holds a line of its own, and nothing is dragged away. Writes: {writes}.',
      ko: '코어마다 제 줄을 쥐고 있어 끌려가는 것이 없다. 고친 횟수: {writes}.',
      ja: 'どちらのコアも自分の行を持っているので、引き剝がされるものがない。書き換え: {writes}。',
      zh: '每个核心都握着自己的行，没有谁被拽走。写入次数：{writes}。',
      ar: 'كل نواة تمسك سطرها الخاص، فلا شيء يُنتزع. الكتابات: {writes}.',
      es: 'Cada núcleo tiene su propia línea y nada le es arrebatado. Escrituras: {writes}.',
      fr: 'Chaque cœur tient sa propre ligne, rien ne lui est arraché. Écritures : {writes}.',
      hi: 'हर कोर के पास अपनी लाइन है, कुछ भी छीना नहीं जाता। लेखन: {writes}.',
      id: 'Tiap inti memegang barisnya sendiri, tak ada yang direbut. Penulisan: {writes}.',
      pt: 'Cada núcleo tem sua própria linha e nada lhe é arrancado. Escritas: {writes}.',
    },
    'caption.tallyApart': {
      en: 'The same count of writes: {writes}. Invalidations: {inval}.',
      ko: '고친 횟수는 그대로: {writes}. 무효화: {inval}.',
      ja: '書き換えの回数は同じ: {writes}。無効化: {inval}。',
      zh: '写入次数照旧：{writes}。作废次数：{inval}。',
      ar: 'عدد الكتابات نفسه: {writes}. الإبطالات: {inval}.',
      es: 'El mismo número de escrituras: {writes}. Invalidaciones: {inval}.',
      fr: "Le même nombre d'écritures : {writes}. Invalidations : {inval}.",
      hi: 'लेखन की संख्या वही: {writes}. रद्दीकरण: {inval}.',
      id: 'Jumlah penulisan tetap sama: {writes}. Pembatalan: {inval}.',
      pt: 'O mesmo número de escritas: {writes}. Invalidações: {inval}.',
    },
    'caption.done': {
      en: 'One thing changed — whether the two values sit on the same line. Values they truly share: {shared}.',
      ko: '달라진 것은 하나뿐이다 — 두 값이 같은 줄에 앉아 있느냐. 정말로 함께 쓰는 값: {shared}.',
      ja: '変わったのはひとつだけ — 二つの値が同じ行に座っているかどうか。本当に共有している値: {shared}。',
      zh: '变的只有一件事 —— 两个值是否坐在同一行上。它们真正共用的值：{shared}。',
      ar: 'تغيّر شيء واحد فقط — هل تقع القيمتان في السطر نفسه. القيم المشتركة فعلًا: {shared}.',
      es: 'Solo cambió una cosa: si los dos valores están en la misma línea. Valores realmente compartidos: {shared}.',
      fr: 'Une seule chose a changé : les deux valeurs sont-elles sur la même ligne. Valeurs réellement partagées : {shared}.',
      hi: 'बदला सिर्फ़ एक बात — क्या दोनों मान एक ही लाइन पर बैठे हैं। वे सचमुच जो साझा करते हैं: {shared}.',
      id: 'Hanya satu hal yang berubah — apakah kedua nilai berada di baris yang sama. Nilai yang benar-benar dibagi: {shared}.',
      pt: 'Só uma coisa mudou: se os dois valores estão na mesma linha. Valores realmente compartilhados: {shared}.',
    },
    'label.line': {
      en: 'line {n} · {bytes} B',
      ko: '줄 {n} · {bytes} B',
      ja: '行 {n} · {bytes} B',
      zh: '行 {n} · {bytes} B',
      ar: 'سطر {n} · {bytes} B',
      es: 'línea {n} · {bytes} B',
      fr: 'ligne {n} · {bytes} B',
      hi: 'लाइन {n} · {bytes} B',
      id: 'baris {n} · {bytes} B',
      pt: 'linha {n} · {bytes} B',
    },
    'label.inval': {
      en: 'invalidated: {n}',
      ko: '무효화: {n}',
      ja: '無効化: {n}',
      zh: '作废：{n}',
      ar: 'مُبطَل: {n}',
      es: 'invalidaciones: {n}',
      fr: 'invalidations : {n}',
      hi: 'रद्द: {n}',
      id: 'dibatalkan: {n}',
      pt: 'invalidações: {n}',
    },
  },
};
