/**
 * verify-vs-find — 조각(piece).
 *
 * @piece 답을 찾는 일과 맞는지 보는 일은 왜 값이 다른가.
 *
 * 1차 데이터는 수 여섯과 목표 하나뿐이다. 후보의 수(2^n)도, 합이 목표가 되는
 * 조합도, 확인 쪽에 건네지는 후보도 알고리즘이 그 자리에서 셈한다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const verifyVsFindFacet: FacetJson = {
  id: 'facet:verifyVsFind',
  title: {
    en: 'Checking vs. finding',
    ko: '맞는지 보기와 답 찾기',
    ja: '検証と探索',
    zh: '验证与搜索',
    ar: 'التحقق مقابل البحث',
    es: 'Comprobar frente a buscar',
    fr: 'Vérifier ou trouver',
    hi: 'जाँचना बनाम खोजना',
    id: 'Memeriksa versus mencari',
    pt: 'Conferir contra procurar',
  },
  description: {
    en: 'Finding a subset that hits the target means looking at every candidate; checking a given one takes a single look.',
    ko: '합이 목표가 되는 부분집합을 찾으려면 후보를 다 들여다봐야 하지만, 건네받은 후보 하나가 맞는지는 한 번 보면 끝난다.',
    ja: '合計が目標になる部分集合を探すには候補をすべて見る必要があるが、渡された候補が正しいかは一度見れば済む。',
    zh: '要找出和为目标的子集必须看遍所有候选，而检验别人给出的一个候选只需看一次。',
    ar: 'إيجاد مجموعة جزئية مجموعها يساوي الهدف يتطلب فحص كل المرشحين، أما التحقق من مرشح معطى فتكفيه نظرة واحدة.',
    es: 'Encontrar un subconjunto que sume el objetivo obliga a mirar todos los candidatos; comprobar uno que te dan basta con una mirada.',
    fr: "Trouver un sous-ensemble dont la somme atteint la cible oblige à examiner tous les candidats ; en vérifier un qu'on vous donne ne demande qu'un regard.",
    hi: 'लक्ष्य के बराबर योग वाला उपसमुच्चय खोजने के लिए हर उम्मीदवार को देखना पड़ता है, पर दिए गए एक उम्मीदवार की जाँच एक ही नज़र में हो जाती है।',
    id: 'Menemukan himpunan bagian yang jumlahnya sama dengan target menuntut semua kandidat dilihat; memeriksa satu kandidat yang diberikan cukup sekali lihat.',
    pt: 'Encontrar um subconjunto cuja soma atinge o alvo exige olhar todos os candidatos; conferir um candidato que lhe entregam basta um olhar.',
  },
  algorithm: 'module:verifyVsFind',
  scene: 'module:verifyVsFindScene',
  initialData: {
    type: 'verify-vs-find',
    values: [3, 7, 12, 19, 24, 31],
    target: 50,
    stepMs: 850,
  },
  blocks: {
    stage: { type: 'verify-vs-find-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'label.target': {
      en: 'Target',
      ko: '목표',
      ja: '目標',
      zh: '目标',
      ar: 'الهدف',
      es: 'Objetivo',
      fr: 'Cible',
      hi: 'लक्ष्य',
      id: 'Target',
      pt: 'Alvo',
    },
    'label.verify': {
      en: 'Checking',
      ko: '맞는지 보기',
      ja: '検証',
      zh: '验证',
      ar: 'التحقق',
      es: 'Comprobar',
      fr: 'Vérifier',
      hi: 'जाँच',
      id: 'Memeriksa',
      pt: 'Conferir',
    },
    'label.find': {
      en: 'Finding',
      ko: '답 찾기',
      ja: '探索',
      zh: '搜索',
      ar: 'البحث',
      es: 'Buscar',
      fr: 'Chercher',
      hi: 'खोज',
      id: 'Mencari',
      pt: 'Procurar',
    },
    'caption.setup': {
      en: '{count} numbers, and a target of {target}.',
      ko: '고를 수 있는 수 {count}. 목표는 {target}.',
      ja: '選べる数は {count}。目標は {target}。',
      zh: '可选的数有 {count} 个，目标是 {target}。',
      ar: 'عدد الأرقام {count}، والهدف {target}.',
      es: 'Números disponibles: {count}. Objetivo: {target}.',
      fr: 'Nombres disponibles : {count}. Cible : {target}.',
      hi: 'उपलब्ध संख्याएँ: {count}. लक्ष्य: {target}.',
      id: 'Angka yang tersedia: {count}. Target: {target}.',
      pt: 'Números disponíveis: {count}. Alvo: {target}.',
    },
    'caption.verify': {
      en: 'Someone hands you one candidate. Add it up: {sum}. One look and it is done.',
      ko: '누군가 후보 하나를 건넨다. 더해 보면 {sum}. 한 번 보면 끝난다.',
      ja: '誰かが候補を一つ渡してくる。足すと {sum}。一度見れば終わりだ。',
      zh: '有人递来一个候选。加起来是 {sum}。看一次就结束了。',
      ar: 'يناولك أحدهم مرشحًا واحدًا. اجمعه: {sum}. نظرة واحدة وينتهي الأمر.',
      es: 'Alguien te entrega un candidato. Súmalo: {sum}. Con una mirada basta.',
      fr: "Quelqu'un vous tend un candidat. La somme fait {sum}. Un seul regard suffit.",
      hi: 'कोई एक उम्मीदवार थमा देता है। जोड़ने पर {sum}. एक नज़र में काम खत्म।',
      id: 'Seseorang menyodorkan satu kandidat. Dijumlahkan: {sum}. Sekali lihat, selesai.',
      pt: 'Alguém entrega um candidato. Somando: {sum}. Um olhar e acabou.',
    },
    'caption.sweep': {
      en: 'Nobody hands you anything, so every candidate gets a look. Looked at: {seen} of {total}.',
      ko: '건네주는 이가 없으니 후보를 하나도 빠짐없이 본다. 지금까지 본 후보는 {seen} / {total}.',
      ja: '渡してくれる人はいないので、候補を一つ残らず見る。ここまで見たのは {seen} / {total}。',
      zh: '没有人递来什么，于是每个候选都要看一遍。已看 {seen} / {total}。',
      ar: 'لا أحد يناولك شيئًا، لذا يُنظر في كل مرشح. ما تم النظر فيه: {seen} من {total}.',
      es: 'Nadie te entrega nada, así que hay que mirar todos los candidatos. Vistos: {seen} de {total}.',
      fr: 'Personne ne vous tend rien : il faut regarder chaque candidat. Vus : {seen} sur {total}.',
      hi: 'कोई कुछ नहीं थमाता, इसलिए हर उम्मीदवार को देखना पड़ता है। अब तक देखे: {seen} / {total}.',
      id: 'Tidak ada yang menyodorkan apa pun, jadi setiap kandidat dilihat. Sudah dilihat: {seen} dari {total}.',
      pt: 'Ninguém entrega nada, então todo candidato é olhado. Vistos: {seen} de {total}.',
    },
    'caption.hit': {
      en: 'A match turns up in this batch. Looked at: {seen} of {total}.',
      ko: '이 묶음에서 답이 하나 나왔다. 지금까지 본 후보는 {seen} / {total}.',
      ja: 'この束から答えが一つ出た。ここまで見たのは {seen} / {total}。',
      zh: '这一批里出现了一个答案。已看 {seen} / {total}。',
      ar: 'ظهرت إجابة في هذه الدفعة. ما تم النظر فيه: {seen} من {total}.',
      es: 'En este lote aparece una respuesta. Vistos: {seen} de {total}.',
      fr: 'Une réponse apparaît dans ce lot. Vus : {seen} sur {total}.',
      hi: 'इस बैच में एक उत्तर निकला। अब तक देखे: {seen} / {total}.',
      id: 'Satu jawaban muncul di kelompok ini. Sudah dilihat: {seen} dari {total}.',
      pt: 'Uma resposta aparece neste lote. Vistos: {seen} de {total}.',
    },
    'caption.done': {
      en: 'Checking looked at {verifySeen}. Finding had to look at all {findSeen}.',
      ko: '확인이 본 후보는 {verifySeen}. 찾기가 본 후보는 {findSeen}.',
      ja: '検証が見た候補は {verifySeen}。探索が見た候補は {findSeen}。',
      zh: '验证看了 {verifySeen} 个候选，搜索看了 {findSeen} 个。',
      ar: 'التحقق نظر في {verifySeen}. البحث نظر في {findSeen}.',
      es: 'Comprobar miró {verifySeen}. Buscar tuvo que mirar {findSeen}.',
      fr: 'La vérification en a regardé {verifySeen}. La recherche a dû en regarder {findSeen}.',
      hi: 'जाँच ने देखे {verifySeen}. खोज ने देखे {findSeen}.',
      id: 'Memeriksa melihat {verifySeen}. Mencari harus melihat {findSeen}.',
      pt: 'Conferir olhou {verifySeen}. Procurar teve de olhar {findSeen}.',
    },
  },
};
