/**
 * @piece
 * 질문: 같은 키스트림으로 두 메시지를 잠그면, 키스트림을 모르는 사람이 두 암호문에서 무엇을 알아내는가.
 *
 * 두 메시지(SELL · HOLD)가 같은 키스트림으로 잠긴다. 공격자가 두 암호문을 겹치면 양쪽에 똑같이
 * 들어 있던 키스트림이 지워지고 두 평문의 겹침만 남는다. 한쪽 평문을 짐작해 겹치면 다른 쪽이 나온다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const neverReuseKeystreamFacet: FacetJson = {
  id: 'facet:neverReuseKeystream',
  title: {
    en: 'Never reuse a keystream',
    ko: '키스트림을 다시 쓰지 않는다',
    ja: 'キーストリームを使い回さない',
    zh: '密钥流不可重复使用',
    ar: 'لا تُعِد استخدام تيار المفاتيح',
    es: 'Nunca reutilices un flujo de clave',
    fr: 'Ne jamais réutiliser un flux de clé',
    hi: 'कीस्ट्रीम दोबारा कभी न इस्तेमाल करें',
    id: 'Jangan pernah memakai ulang keystream',
    pt: 'Nunca reutilize um fluxo de chave',
  },
  description: {
    en: 'Two messages locked with the same keystream: overlaying the two ciphertexts erases the keystream and leaves the two plaintexts overlaid.',
    ko: '같은 키스트림으로 잠근 두 메시지 — 두 암호문을 겹치면 키스트림이 지워지고 두 평문의 겹침이 남는다.',
    ja: '同じキーストリームで暗号化した二つのメッセージ — 二つの暗号文を重ねるとキーストリームが消え、二つの平文の重なりが残る。',
    zh: '用同一密钥流加密的两条消息——把两段密文叠加，密钥流被抵消，只剩两段明文的叠加。',
    ar: 'رسالتان مقفلتان بتيار المفاتيح نفسه: تراكب النصين المشفرين يمحو تيار المفاتيح ويترك تراكب النصين الأصليين.',
    es: 'Dos mensajes cifrados con el mismo flujo de clave: al superponer los dos textos cifrados, el flujo se borra y queda la superposición de los dos textos en claro.',
    fr: 'Deux messages chiffrés avec le même flux de clé : superposer les deux chiffrés efface le flux et laisse la superposition des deux clairs.',
    hi: 'एक ही कीस्ट्रीम से बंद दो संदेश — दोनों सिफ़रटेक्स्ट को मिलाने पर कीस्ट्रीम मिट जाती है और दोनों प्लेनटेक्स्ट का मेल बचता है।',
    id: 'Dua pesan dikunci dengan keystream yang sama: menumpuk kedua ciphertext menghapus keystream dan menyisakan tumpukan kedua plaintext.',
    pt: 'Duas mensagens cifradas com o mesmo fluxo de chave: sobrepor os dois textos cifrados apaga o fluxo e deixa a sobreposição dos dois textos claros.',
  },
  algorithm: 'module:neverReuseKeystream',
  scene: 'module:neverReuseKeystreamScene',
  initialData: {
    type: 'never-reuse-keystream',
    stepMs: 2200,
    // 메시지 바이트는 번역하지 않는 자료다 — 글자가 곧 바이트 값이다
    p1: 'SELL',
    p2: 'HOLD',
    // 뽑힌 값 그대로 — 한 벌을 두 메시지에 쓴다
    keystream: '7CD109A4',
    // 공격자가 짐작한 한쪽 평문의 꼴
    guess: 'SELL',
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'never-reuse-keystream-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'term.p1': { en: 'P1', ko: 'P1', ja: 'P1', zh: 'P1', ar: 'P1', es: 'P1', fr: 'P1', hi: 'P1', id: 'P1', pt: 'P1' },
    'term.p2': { en: 'P2', ko: 'P2', ja: 'P2', zh: 'P2', ar: 'P2', es: 'P2', fr: 'P2', hi: 'P2', id: 'P2', pt: 'P2' },
    'term.s': { en: 'S', ko: 'S', ja: 'S', zh: 'S', ar: 'S', es: 'S', fr: 'S', hi: 'S', id: 'S', pt: 'S' },
    'label.p1': { en: 'P1', ko: 'P1', ja: 'P1', zh: 'P1', ar: 'P1', es: 'P1', fr: 'P1', hi: 'P1', id: 'P1', pt: 'P1' },
    'label.p2': { en: 'P2', ko: 'P2', ja: 'P2', zh: 'P2', ar: 'P2', es: 'P2', fr: 'P2', hi: 'P2', id: 'P2', pt: 'P2' },
    'label.keystream': {
      en: 'Keystream S',
      ko: '키스트림 S',
      ja: 'キーストリーム S',
      zh: '密钥流 S',
      ar: 'تيار المفاتيح S',
      es: 'Flujo de clave S',
      fr: 'Flux de clé S',
      hi: 'कीस्ट्रीम S',
      id: 'Keystream S',
      pt: 'Fluxo de chave S',
    },
    'label.c1': { en: 'C1', ko: 'C1', ja: 'C1', zh: 'C1', ar: 'C1', es: 'C1', fr: 'C1', hi: 'C1', id: 'C1', pt: 'C1' },
    'label.c2': { en: 'C2', ko: 'C2', ja: 'C2', zh: 'C2', ar: 'C2', es: 'C2', fr: 'C2', hi: 'C2', id: 'C2', pt: 'C2' },
    'label.x': {
      en: 'C1 ⊕ C2',
      ko: 'C1 ⊕ C2',
      ja: 'C1 ⊕ C2',
      zh: 'C1 ⊕ C2',
      ar: 'C1 ⊕ C2',
      es: 'C1 ⊕ C2',
      fr: 'C1 ⊕ C2',
      hi: 'C1 ⊕ C2',
      id: 'C1 ⊕ C2',
      pt: 'C1 ⊕ C2',
    },
    'label.guess': {
      en: 'Guess',
      ko: '짐작',
      ja: '推測',
      zh: '猜测',
      ar: 'تخمين',
      es: 'Conjetura',
      fr: 'Supposition',
      hi: 'अनुमान',
      id: 'Tebakan',
      pt: 'Palpite',
    },
    'label.result': {
      en: 'Guess ⊕ (C1 ⊕ C2)',
      ko: '짐작 ⊕ (C1 ⊕ C2)',
      ja: '推測 ⊕ (C1 ⊕ C2)',
      zh: '猜测 ⊕ (C1 ⊕ C2)',
      ar: 'تخمين ⊕ (C1 ⊕ C2)',
      es: 'Conjetura ⊕ (C1 ⊕ C2)',
      fr: 'Supposition ⊕ (C1 ⊕ C2)',
      hi: 'अनुमान ⊕ (C1 ⊕ C2)',
      id: 'Tebakan ⊕ (C1 ⊕ C2)',
      pt: 'Palpite ⊕ (C1 ⊕ C2)',
    },
    'label.sender': {
      en: 'Sender',
      ko: '보내는 쪽',
      ja: '送信側',
      zh: '发送方',
      ar: 'المرسِل',
      es: 'Emisor',
      fr: 'Expéditeur',
      hi: 'भेजने वाला',
      id: 'Pengirim',
      pt: 'Remetente',
    },
    'label.attacker': {
      en: 'Attacker',
      ko: '공격자',
      ja: '攻撃者',
      zh: '攻击者',
      ar: 'المهاجم',
      es: 'Atacante',
      fr: 'Attaquant',
      hi: 'हमलावर',
      id: 'Penyerang',
      pt: 'Atacante',
    },
    'caption.start': {
      en: 'Sender: two plaintexts, one keystream',
      ko: '보내는 쪽: 평문 둘, 키스트림 한 벌',
      ja: '送信側: 平文二つ、キーストリーム一本',
      zh: '发送方：两段明文，一条密钥流',
      ar: 'المرسِل: نصان أصليان وتيار مفاتيح واحد',
      es: 'Emisor: dos textos en claro, un flujo de clave',
      fr: 'Expéditeur : deux clairs, un flux de clé',
      hi: 'भेजने वाला: दो प्लेनटेक्स्ट, एक कीस्ट्रीम',
      id: 'Pengirim: dua plaintext, satu keystream',
      pt: 'Remetente: dois textos claros, um fluxo de chave',
    },
    'caption.startS': {
      en: 'S = {hex}',
      ko: 'S = {hex}',
      ja: 'S = {hex}',
      zh: 'S = {hex}',
      ar: 'S = {hex}',
      es: 'S = {hex}',
      fr: 'S = {hex}',
      hi: 'S = {hex}',
      id: 'S = {hex}',
      pt: 'S = {hex}',
    },
    'caption.lock': {
      en: 'Sender: C{n} = P{n} ⊕ S = {hex}',
      ko: '보내는 쪽: C{n} = P{n} ⊕ S = {hex}',
      ja: '送信側: C{n} = P{n} ⊕ S = {hex}',
      zh: '发送方：C{n} = P{n} ⊕ S = {hex}',
      ar: 'المرسِل: C{n} = P{n} ⊕ S = {hex}',
      es: 'Emisor: C{n} = P{n} ⊕ S = {hex}',
      fr: 'Expéditeur : C{n} = P{n} ⊕ S = {hex}',
      hi: 'भेजने वाला: C{n} = P{n} ⊕ S = {hex}',
      id: 'Pengirim: C{n} = P{n} ⊕ S = {hex}',
      pt: 'Remetente: C{n} = P{n} ⊕ S = {hex}',
    },
    'caption.lockUses': {
      en: 'Times the keystream was used: {uses}',
      ko: '키스트림을 쓴 횟수: {uses}',
      ja: 'キーストリームを使った回数: {uses}',
      zh: '密钥流已使用次数：{uses}',
      ar: 'عدد مرات استخدام تيار المفاتيح: {uses}',
      es: 'Veces que se usó el flujo de clave: {uses}',
      fr: 'Nombre d’utilisations du flux de clé : {uses}',
      hi: 'कीस्ट्रीम कितनी बार इस्तेमाल हुई: {uses}',
      id: 'Berapa kali keystream dipakai: {uses}',
      pt: 'Vezes que o fluxo de chave foi usado: {uses}',
    },
    'caption.overlay': {
      en: 'Attacker: C1 ⊕ C2 = {hex}',
      ko: '공격자: C1 ⊕ C2 = {hex}',
      ja: '攻撃者: C1 ⊕ C2 = {hex}',
      zh: '攻击者：C1 ⊕ C2 = {hex}',
      ar: 'المهاجم: C1 ⊕ C2 = {hex}',
      es: 'Atacante: C1 ⊕ C2 = {hex}',
      fr: 'Attaquant : C1 ⊕ C2 = {hex}',
      hi: 'हमलावर: C1 ⊕ C2 = {hex}',
      id: 'Penyerang: C1 ⊕ C2 = {hex}',
      pt: 'Atacante: C1 ⊕ C2 = {hex}',
    },
    'caption.overlayLeft': {
      en: 'S terms left: {left}',
      ko: '남은 S 항: {left}',
      ja: '残った S の項: {left}',
      zh: '剩下的 S 项：{left}',
      ar: 'حدود S المتبقية: {left}',
      es: 'Términos S restantes: {left}',
      fr: 'Termes S restants : {left}',
      hi: 'बचे हुए S पद: {left}',
      id: 'Suku S yang tersisa: {left}',
      pt: 'Termos S restantes: {left}',
    },
    'caption.overlayZeros': {
      en: 'S terms left: {left} · Zero byte at position: {zeros}',
      ko: '남은 S 항: {left} · 0 인 바이트 자리: {zeros}',
      ja: '残った S の項: {left} · 0 のバイトの位置: {zeros}',
      zh: '剩下的 S 项：{left} · 值为 0 的字节位置：{zeros}',
      ar: 'حدود S المتبقية: {left} · موضع البايت الصفري: {zeros}',
      es: 'Términos S restantes: {left} · Byte cero en la posición: {zeros}',
      fr: 'Termes S restants : {left} · Octet nul à la position : {zeros}',
      hi: 'बचे हुए S पद: {left} · शून्य बाइट का स्थान: {zeros}',
      id: 'Suku S yang tersisa: {left} · Byte nol di posisi: {zeros}',
      pt: 'Termos S restantes: {left} · Byte zero na posição: {zeros}',
    },
    'caption.recover': {
      en: 'Attacker: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      ko: '공격자: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      ja: '攻撃者: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      zh: '攻击者：{guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      ar: 'المهاجم: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      es: 'Atacante: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      fr: 'Attaquant : {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      hi: 'हमलावर: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      id: 'Penyerang: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
      pt: 'Atacante: {guess} ⊕ (C1 ⊕ C2) = {text} ({hex})',
    },
    'caption.recoverSame': {
      en: 'Bytes equal to P2: {same} / {total} · Times the attacker used the keystream: {uses}',
      ko: 'P2 와 같은 바이트: {same} / {total} · 공격자가 키스트림을 쓴 횟수: {uses}',
      ja: 'P2 と同じバイト: {same} / {total} · 攻撃者がキーストリームを使った回数: {uses}',
      zh: '与 P2 相同的字节：{same} / {total} · 攻击者使用密钥流的次数：{uses}',
      ar: 'البايتات المطابقة لـ P2: {same} / {total} · عدد مرات استخدام المهاجم لتيار المفاتيح: {uses}',
      es: 'Bytes iguales a P2: {same} / {total} · Veces que el atacante usó el flujo de clave: {uses}',
      fr: 'Octets égaux à P2 : {same} / {total} · Utilisations du flux de clé par l’attaquant : {uses}',
      hi: 'P2 के बराबर बाइट: {same} / {total} · हमलावर ने कीस्ट्रीम कितनी बार इस्तेमाल की: {uses}',
      id: 'Byte yang sama dengan P2: {same} / {total} · Berapa kali penyerang memakai keystream: {uses}',
      pt: 'Bytes iguais a P2: {same} / {total} · Vezes que o atacante usou o fluxo de chave: {uses}',
    },
  },
};
