import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 다른 브랜치의 커밋 하나만 가져오면, 그 커밋의 무엇이 오는가?
 */
export const pickOneOutFacet: FacetJson = {
  id: 'facet:pickOneOut',
  title: {
    en: 'Pick one commit',
    ko: '커밋 하나만 가져오기',
    ja: 'コミットを一つだけ持ってくる',
    zh: '只取一个提交',
    ar: 'اختيار التزام واحد',
    es: 'Tomar un solo commit',
    fr: 'Prendre un seul commit',
    hi: 'एक ही कमिट लेना',
    id: 'Mengambil satu commit saja',
    pt: 'Trazer um único commit',
  },
  description: {
    en: 'What comes over is not the snapshot but the change against its parent.',
    ko: '오는 것은 스냅숏이 아니라 부모와의 차이 한 뭉치다.',
    ja: '運ばれるのはスナップショットではなく、親との差分ひとかたまりだ。',
    zh: '搬过来的不是快照，而是它与父提交之间的一块差异。',
    ar: 'ما يُنقل ليس اللقطة، بل كتلة الفرق عن الأب.',
    es: 'Lo que llega no es la instantánea, sino el cambio respecto a su padre.',
    fr: 'Ce qui arrive n’est pas l’instantané, mais la différence avec son parent.',
    hi: 'जो आता है वह स्नैपशॉट नहीं, बल्कि पैरेंट से अंतर का एक टुकड़ा है।',
    id: 'Yang terbawa bukan snapshot, melainkan perbedaan terhadap induknya.',
    pt: 'O que vem não é o instantâneo, e sim a diferença em relação ao pai.',
  },
  algorithm: 'module:pickOneOut',
  scene: 'module:pickOneOutScene',
  initialData: {
    type: 'pick-one-out',
    stepMs: 2400,
    commits: [
      { id: 'B', parents: [], lines: ['let name = "app"', 'let timeout = 10'] },
      { id: 'M', parents: ['B'], lines: ['let name = "app"', 'let timeout = 10', 'let port = 80'] },
      { id: 'X', parents: ['B'], lines: ['let name = "app"', 'let retry = 3', 'let timeout = 10'] },
      { id: 'Y', parents: ['X'], lines: ['let name = "app"', 'let retry = 3', 'let timeout = 30'] },
      { id: 'Z', parents: ['Y'], lines: ['let name = "app"', 'let retry = 3', 'let timeout = 30', 'show name'] },
    ],
    names: [
      { name: 'main', commit: 'M' },
      { name: 'feature', commit: 'Z' },
    ],
    head: 'main',
    pick: 'Y',
  },
  shuffleOnReset: false,
  messages: {
    'label.picked': {
      en: 'File of {pick}',
      ko: '{pick} 의 파일',
      ja: '{pick} のファイル',
      zh: '{pick} 的文件',
      ar: 'ملف {pick}',
      es: 'Archivo de {pick}',
      fr: 'Fichier de {pick}',
      hi: '{pick} की फ़ाइल',
      id: 'Berkas {pick}',
      pt: 'Arquivo de {pick}',
    },
    'label.change': {
      en: 'Change of {pick} against {parent}',
      ko: '{pick} 의 변경 · 견준 부모: {parent}',
      ja: '{pick} の変更 · 比べた親: {parent}',
      zh: '{pick} 的变更 · 对比的父提交: {parent}',
      ar: 'تغيير {pick} مقارنةً بـ {parent}',
      es: 'Cambio de {pick} frente a {parent}',
      fr: 'Modification de {pick} par rapport à {parent}',
      hi: '{pick} का बदलाव · तुलना का पैरेंट: {parent}',
      id: 'Perubahan {pick} terhadap {parent}',
      pt: 'Mudança de {pick} em relação a {parent}',
    },
    'label.file': {
      en: 'File on {branch}',
      ko: '{branch} 의 파일',
      ja: '{branch} のファイル',
      zh: '{branch} 上的文件',
      ar: 'الملف على {branch}',
      es: 'Archivo en {branch}',
      fr: 'Fichier sur {branch}',
      hi: '{branch} पर फ़ाइल',
      id: 'Berkas di {branch}',
      pt: 'Arquivo em {branch}',
    },
    'caption.start': {
      en: 'Picked: {pick} · Lines on {branch}: {n}',
      ko: '고른 커밋: {pick} · {branch} 파일의 줄: {n}',
      ja: '選んだコミット: {pick} · {branch} のファイルの行: {n}',
      zh: '选中的提交: {pick} · {branch} 文件的行数: {n}',
      ar: 'الالتزام المختار: {pick} · أسطر الملف على {branch}: {n}',
      es: 'Elegido: {pick} · Líneas en {branch}: {n}',
      fr: 'Choisi : {pick} · Lignes sur {branch} : {n}',
      hi: 'चुना गया: {pick} · {branch} पर पंक्तियाँ: {n}',
      id: 'Dipilih: {pick} · Baris di {branch}: {n}',
      pt: 'Escolhido: {pick} · Linhas em {branch}: {n}',
    },
    'caption.diff': {
      en: 'Changed block · Removed: {del} · Added: {add}',
      ko: '바뀐 줄 뭉치 · 지운 줄: {del} · 넣은 줄: {add}',
      ja: '変わった行のかたまり · 消した行: {del} · 足した行: {add}',
      zh: '改动的行块 · 删除行: {del} · 新增行: {add}',
      ar: 'كتلة الأسطر المتغيّرة · محذوفة: {del} · مضافة: {add}',
      es: 'Bloque cambiado · Quitadas: {del} · Añadidas: {add}',
      fr: 'Bloc modifié · Retirées : {del} · Ajoutées : {add}',
      hi: 'बदली पंक्तियों का टुकड़ा · हटाई: {del} · जोड़ी: {add}',
      id: 'Blok yang berubah · Dihapus: {del} · Ditambah: {add}',
      pt: 'Bloco alterado · Removidas: {del} · Adicionadas: {add}',
    },
    'caption.land': {
      en: 'Landed on {branch} · Moved: −{del} +{add} · Lines in file: {n}',
      ko: '{branch} 파일에 얹힘 · 옮긴 줄: −{del} +{add} · 파일의 줄: {n}',
      ja: '{branch} のファイルに載った · 移した行: −{del} +{add} · ファイルの行: {n}',
      zh: '落在 {branch} 的文件上 · 搬过来的行: −{del} +{add} · 文件行数: {n}',
      ar: 'استقرّ على {branch} · المنقول: −{del} +{add} · أسطر الملف: {n}',
      es: 'Aplicado en {branch} · Movido: −{del} +{add} · Líneas del archivo: {n}',
      fr: 'Posé sur {branch} · Déplacé : −{del} +{add} · Lignes du fichier : {n}',
      hi: '{branch} पर रखा गया · लाया गया: −{del} +{add} · फ़ाइल की पंक्तियाँ: {n}',
      id: 'Mendarat di {branch} · Dipindah: −{del} +{add} · Baris berkas: {n}',
      pt: 'Aplicado em {branch} · Movido: −{del} +{add} · Linhas do arquivo: {n}',
    },
    'caption.commit': {
      en: 'New commit {made} · Parent: {parent} · {branch} → {made}',
      ko: '새 커밋 {made} · 부모: {parent} · {branch} → {made}',
      ja: '新しいコミット {made} · 親: {parent} · {branch} → {made}',
      zh: '新提交 {made} · 父提交: {parent} · {branch} → {made}',
      ar: 'التزام جديد {made} · الأب: {parent} · {branch} → {made}',
      es: 'Nuevo commit {made} · Padre: {parent} · {branch} → {made}',
      fr: 'Nouveau commit {made} · Parent : {parent} · {branch} → {made}',
      hi: 'नया कमिट {made} · पैरेंट: {parent} · {branch} → {made}',
      id: 'Commit baru {made} · Induk: {parent} · {branch} → {made}',
      pt: 'Novo commit {made} · Pai: {parent} · {branch} → {made}',
    },
  },
  blocks: {
    stage: { type: 'pick-one-out-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
