import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * 정렬과 패딩.
 *
 * @piece
 * 질문: 구조체의 크기는 왜 필드 크기의 합보다 큰가.
 *
 * 필드가 차례로 들어오다 제 정렬 자리(크기의 배수)까지 밀려 앉고, 지나친 칸이 빈틈으로
 * 남는다. 끝에서는 전체가 가장 큰 정렬의 배수가 되도록 꼬리 빈틈이 붙는다.
 */
export const paddingGapFacet: FacetJson = {
  id: 'facet:paddingGap',
  title: {
    en: 'Alignment and padding',
    ko: '정렬과 패딩',
    ja: 'アラインメントとパディング',
    zh: '对齐与填充',
    ar: 'المحاذاة والحشو',
    es: 'Alineación y relleno',
    fr: 'Alignement et remplissage',
    hi: 'संरेखण और पैडिंग',
    id: 'Penyelarasan dan padding',
    pt: 'Alinhamento e preenchimento',
  },
  description: {
    en: 'Each field slides to a multiple of its own alignment, and the bytes it skips stay empty.',
    ko: '필드마다 제 정렬의 배수 자리까지 밀려 앉고, 지나친 바이트는 빈틈으로 남는다.',
    ja: '各フィールドは自分のアラインメントの倍数の位置まで押し出され、飛ばしたバイトは隙間として残る。',
    zh: '每个字段都会滑到自身对齐值的倍数位置，跳过的字节留作空隙。',
    ar: 'ينزلق كل حقل إلى مضاعف لمحاذاته، وتبقى البايتات التي يتخطاها فارغة.',
    es: 'Cada campo se desplaza hasta un múltiplo de su propia alineación, y los bytes que salta quedan vacíos.',
    fr: 'Chaque champ glisse jusqu’à un multiple de son propre alignement, et les octets sautés restent vides.',
    hi: 'हर फ़ील्ड अपने संरेखण के गुणज तक खिसकता है, और छोड़े गए बाइट खाली रह जाते हैं।',
    id: 'Setiap field bergeser ke kelipatan penyelarasannya sendiri, dan byte yang dilewati tetap kosong.',
    pt: 'Cada campo desliza até um múltiplo do seu próprio alinhamento, e os bytes que salta ficam vazios.',
  },
  algorithm: 'module:paddingGap',
  scene: 'module:paddingGapScene',
  initialData: {
    type: 'padding-gap',
    stepMs: 800,
    fields: [
      { name: 'a', type: 'char' },
      { name: 'b', type: 'int' },
      { name: 'c', type: 'char' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.init': {
      en: 'Fields come in one at a time: {n} in all.',
      ko: '필드가 하나씩 들어온다. 모두: {n}.',
      ja: 'フィールドが一つずつ入ってくる。全部で {n}。',
      zh: '字段逐个进入：共 {n} 个。',
      ar: 'تدخل الحقول واحدًا تلو الآخر: {n} في المجموع.',
      es: 'Los campos entran de uno en uno: {n} en total.',
      fr: 'Les champs arrivent un par un : {n} en tout.',
      hi: 'फ़ील्ड एक-एक करके आते हैं: कुल {n}।',
      id: 'Field masuk satu per satu: {n} seluruhnya.',
      pt: 'Os campos entram um de cada vez: {n} no total.',
    },
    'caption.fits': {
      en: '{name} ({type}, alignment {align}) sits right at byte {offset}.',
      ko: '{name} · {type} · 정렬 단위 {align}. 앉는 자리: 바이트 {offset}, 밀리지 않는다.',
      ja: '{name}（{type}、アラインメント {align}）はそのままバイト {offset} に収まる。',
      zh: '{name}（{type}，对齐 {align}）直接落在字节 {offset}。',
      ar: 'يستقر {name} ({type}، محاذاة {align}) مباشرة عند البايت {offset}.',
      es: '{name} ({type}, alineación {align}) se sienta justo en el byte {offset}.',
      fr: '{name} ({type}, alignement {align}) se pose directement à l’octet {offset}.',
      hi: '{name} ({type}, संरेखण {align}) सीधे बाइट {offset} पर बैठता है।',
      id: '{name} ({type}, penyelarasan {align}) langsung duduk di byte {offset}.',
      pt: '{name} ({type}, alinhamento {align}) assenta logo no byte {offset}.',
    },
    'caption.pushed': {
      en: '{name} ({type}) must start at a multiple of {align}. It slides from byte {from} to {offset}, leaving {gap} bytes empty.',
      ko: '{name} · {type} · 정렬 단위 {align}. 밀려 앉는 자리: 바이트 {from} → {offset}. 남는 빈틈: {gap} 바이트.',
      ja: '{name}（{type}）は {align} の倍数から始まらなければならない。バイト {from} から {offset} へ滑り、{gap} バイトが空く。',
      zh: '{name}（{type}）必须从 {align} 的倍数开始。它从字节 {from} 滑到 {offset}，空出 {gap} 字节。',
      ar: 'يجب أن يبدأ {name} ({type}) عند مضاعف لـ {align}. ينزلق من البايت {from} إلى {offset} تاركًا {gap} بايت فارغة.',
      es: '{name} ({type}) debe empezar en un múltiplo de {align}. Se desplaza del byte {from} al {offset} y deja {gap} bytes vacíos.',
      fr: '{name} ({type}) doit commencer à un multiple de {align}. Il glisse de l’octet {from} à {offset} et laisse {gap} octets vides.',
      hi: '{name} ({type}) को {align} के गुणज से शुरू होना चाहिए। यह बाइट {from} से {offset} तक खिसकता है और {gap} बाइट खाली छोड़ता है।',
      id: '{name} ({type}) harus mulai di kelipatan {align}. Ia bergeser dari byte {from} ke {offset}, menyisakan {gap} byte kosong.',
      pt: '{name} ({type}) tem de começar num múltiplo de {align}. Desliza do byte {from} para {offset} e deixa {gap} bytes vazios.',
    },
    'caption.tail': {
      en: 'The whole must be a multiple of the largest alignment, {align}. The end moves from {end} to {size}: {gap} bytes of tail padding.',
      ko: '전체는 가장 큰 정렬 단위의 배수여야 한다. 가장 큰 정렬 단위: {align}. 끝 자리: {end} → {size}. 꼬리 빈틈: {gap} 바이트.',
      ja: '全体は最大のアラインメント {align} の倍数でなければならない。末尾が {end} から {size} へ移り、{gap} バイトの末尾パディングが付く。',
      zh: '整体必须是最大对齐值 {align} 的倍数。末尾从 {end} 移到 {size}：尾部填充 {gap} 字节。',
      ar: 'يجب أن يكون الكل مضاعفًا لأكبر محاذاة، {align}. تنتقل النهاية من {end} إلى {size}: حشو ذيلي من {gap} بايت.',
      es: 'El conjunto debe ser múltiplo de la mayor alineación, {align}. El final pasa de {end} a {size}: {gap} bytes de relleno de cola.',
      fr: 'L’ensemble doit être un multiple du plus grand alignement, {align}. La fin passe de {end} à {size} : {gap} octets de remplissage final.',
      hi: 'पूरा ढाँचा सबसे बड़े संरेखण {align} का गुणज होना चाहिए। अंत {end} से {size} तक जाता है: {gap} बाइट की पूँछ पैडिंग।',
      id: 'Keseluruhan harus kelipatan penyelarasan terbesar, {align}. Ujungnya bergeser dari {end} ke {size}: {gap} byte padding ekor.',
      pt: 'O todo tem de ser múltiplo do maior alinhamento, {align}. O fim passa de {end} para {size}: {gap} bytes de preenchimento final.',
    },
    'caption.tailNone': {
      en: 'The end, {end}, is already a multiple of the largest alignment, {align}. No tail padding.',
      ko: '끝 자리: {end}. 가장 큰 정렬 단위: {align}. 이미 배수라 꼬리 빈틈은 없다.',
      ja: '末尾 {end} はすでに最大のアラインメント {align} の倍数。末尾パディングはない。',
      zh: '末尾 {end} 已是最大对齐值 {align} 的倍数，无需尾部填充。',
      ar: 'النهاية {end} مضاعف بالفعل لأكبر محاذاة {align}. لا حشو ذيلي.',
      es: 'El final, {end}, ya es múltiplo de la mayor alineación, {align}. Sin relleno de cola.',
      fr: 'La fin, {end}, est déjà un multiple du plus grand alignement, {align}. Pas de remplissage final.',
      hi: 'अंत {end} पहले से ही सबसे बड़े संरेखण {align} का गुणज है। कोई पूँछ पैडिंग नहीं।',
      id: 'Ujung {end} sudah kelipatan penyelarasan terbesar, {align}. Tanpa padding ekor.',
      pt: 'O fim, {end}, já é múltiplo do maior alinhamento, {align}. Sem preenchimento final.',
    },
    'caption.total': {
      en: 'Size {size} = fields {sum} + gaps {gaps}.',
      ko: '크기 {size} = 필드 {sum} + 빈틈 {gaps}.',
      ja: 'サイズ {size} = フィールド {sum} + 隙間 {gaps}。',
      zh: '大小 {size} = 字段 {sum} + 空隙 {gaps}。',
      ar: 'الحجم {size} = الحقول {sum} + الفراغات {gaps}.',
      es: 'Tamaño {size} = campos {sum} + huecos {gaps}.',
      fr: 'Taille {size} = champs {sum} + vides {gaps}.',
      hi: 'आकार {size} = फ़ील्ड {sum} + खाली जगह {gaps}।',
      id: 'Ukuran {size} = field {sum} + celah {gaps}.',
      pt: 'Tamanho {size} = campos {sum} + lacunas {gaps}.',
    },
    'label.size': {
      en: 'size {size}',
      ko: '크기 {size}',
      ja: 'サイズ {size}',
      zh: '大小 {size}',
      ar: 'الحجم {size}',
      es: 'tamaño {size}',
      fr: 'taille {size}',
      hi: 'आकार {size}',
      id: 'ukuran {size}',
      pt: 'tamanho {size}',
    },
  },
  blocks: {
    stage: { type: 'padding-gap-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
