import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 망이 얼마나 받아 줄지 모를 때, 보내는 양을 어떻게 늘려 가는가.
 *
 * 처음 창 1 · 문턱 16 · 왕복 일곱은 예로 정한 값이다. 창은 조각 수로 센다 (실제 TCP 는 바이트).
 */
export const slowStartFacet: FacetJson = {
  id: 'facet:slowStart',
  title: {
    en: 'Slow start',
    ko: '슬로 스타트',
    ja: 'スロースタート',
    zh: '慢启动',
    ar: 'البدء البطيء',
    es: 'Arranque lento',
    fr: 'Démarrage lent',
    hi: 'स्लो स्टार्ट',
    id: 'Slow start',
    pt: 'Partida lenta',
  },
  description: {
    en: 'Every returning ack widens the window by one, so each round sends twice as many as the last — until the threshold, then one more per round.',
    ko: '돌아온 확인 하나마다 창이 하나씩 넓어져, 왕복마다 앞 왕복의 두 배를 보낸다 — 문턱에 닿은 뒤로는 왕복마다 하나씩만 는다.',
    ja: '確認応答が一つ戻るたびにウィンドウが一つ広がり、各往復で前の往復の二倍を送る。しきい値に達した後は往復ごとに一つずつしか増えない。',
    zh: '每收到一个确认，窗口就加一，于是每个往返发送的数量是上一个的两倍——到达阈值后，每个往返只加一。',
    ar: 'كل إقرار يعود يوسّع النافذة بمقدار واحد، فيُرسَل في كل جولة ضعف ما أُرسل في سابقتها — حتى العتبة، ثم واحد إضافي فقط في كل جولة.',
    es: 'Cada confirmación que vuelve ensancha la ventana en uno, así que cada ronda envía el doble que la anterior — hasta el umbral; después, solo uno más por ronda.',
    fr: 'Chaque accusé qui revient élargit la fenêtre d’un, donc chaque aller-retour envoie deux fois plus que le précédent — jusqu’au seuil, puis un de plus par aller-retour.',
    hi: 'हर लौटी पावती खिड़की को एक बढ़ा देती है, इसलिए हर चक्कर पिछले से दोगुना भेजता है — दहलीज़ तक; उसके बाद हर चक्कर में बस एक और।',
    id: 'Setiap ack yang kembali melebarkan jendela satu, sehingga tiap putaran mengirim dua kali lipat putaran sebelumnya — sampai ambang, lalu hanya bertambah satu per putaran.',
    pt: 'Cada confirmação que volta alarga a janela em um, então cada rodada envia o dobro da anterior — até o limiar; depois, só mais um por rodada.',
  },
  algorithm: 'module:slowStart',
  scene: 'module:slowStartScene',
  initialData: {
    type: 'slow-start',
    window: 1,
    ssthresh: 16,
    rounds: 7,
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'label.threshold': {
      en: 'Threshold: {s}',
      ko: '문턱: {s}',
      ja: 'しきい値: {s}',
      zh: '阈值：{s}',
      ar: 'العتبة: {s}',
      es: 'Umbral: {s}',
      fr: 'Seuil : {s}',
      hi: 'दहलीज़: {s}',
      id: 'Ambang: {s}',
      pt: 'Limiar: {s}',
    },
    'label.round': {
      en: 'Round {r}',
      ko: '왕복 {r}',
      ja: '往復 {r}',
      zh: '往返 {r}',
      ar: 'الجولة {r}',
      es: 'Ronda {r}',
      fr: 'Aller-retour {r}',
      hi: 'चक्कर {r}',
      id: 'Putaran {r}',
      pt: 'Rodada {r}',
    },
    'label.window': {
      en: 'Window',
      ko: '창',
      ja: 'ウィンドウ',
      zh: '窗口',
      ar: 'النافذة',
      es: 'Ventana',
      fr: 'Fenêtre',
      hi: 'खिड़की',
      id: 'Jendela',
      pt: 'Janela',
    },
    'caption.start': {
      en: 'Window: {w} · threshold: {s}. Nothing sent yet.',
      ko: '창: {w} · 문턱: {s}. 아직 보낸 것이 없다.',
      ja: 'ウィンドウ: {w} · しきい値: {s}。まだ何も送っていない。',
      zh: '窗口：{w} · 阈值：{s}。还没有发送任何东西。',
      ar: 'النافذة: {w} · العتبة: {s}. لم يُرسَل شيء بعد.',
      es: 'Ventana: {w} · umbral: {s}. Aún no se ha enviado nada.',
      fr: 'Fenêtre : {w} · seuil : {s}. Rien n’est encore envoyé.',
      hi: 'खिड़की: {w} · दहलीज़: {s}। अभी कुछ नहीं भेजा गया।',
      id: 'Jendela: {w} · ambang: {s}. Belum ada yang dikirim.',
      pt: 'Janela: {w} · limiar: {s}. Nada enviado ainda.',
    },
    'caption.slow': {
      en: 'Round {r} — sent: {n} · acks back: {n}. Each ack adds 1 to the window.',
      ko: '왕복 {r} — 보냄: {n} · 돌아온 확인: {n}. 확인마다 창 + 1.',
      ja: '往復 {r} — 送信: {n} · 戻った確認: {n}。確認ごとにウィンドウ + 1。',
      zh: '往返 {r} — 发送：{n} · 返回的确认：{n}。每个确认使窗口 + 1。',
      ar: 'الجولة {r} — المُرسَل: {n} · الإقرارات العائدة: {n}. كل إقرار يضيف 1 إلى النافذة.',
      es: 'Ronda {r} — enviados: {n} · confirmaciones de vuelta: {n}. Cada confirmación suma 1 a la ventana.',
      fr: 'Aller-retour {r} — envoyés : {n} · accusés revenus : {n}. Chaque accusé ajoute 1 à la fenêtre.',
      hi: 'चक्कर {r} — भेजे: {n} · लौटी पावतियाँ: {n}। हर पावती खिड़की में 1 जोड़ती है।',
      id: 'Putaran {r} — terkirim: {n} · ack kembali: {n}. Tiap ack menambah jendela 1.',
      pt: 'Rodada {r} — enviados: {n} · confirmações de volta: {n}. Cada confirmação soma 1 à janela.',
    },
    'caption.avoid': {
      en: 'Round {r} — sent: {n} · acks back: {n}. Each ack adds 1/{n} to the window.',
      ko: '왕복 {r} — 보냄: {n} · 돌아온 확인: {n}. 확인마다 창 + 1/{n}.',
      ja: '往復 {r} — 送信: {n} · 戻った確認: {n}。確認ごとにウィンドウ + 1/{n}。',
      zh: '往返 {r} — 发送：{n} · 返回的确认：{n}。每个确认使窗口 + 1/{n}。',
      ar: 'الجولة {r} — المُرسَل: {n} · الإقرارات العائدة: {n}. كل إقرار يضيف 1/{n} إلى النافذة.',
      es: 'Ronda {r} — enviados: {n} · confirmaciones de vuelta: {n}. Cada confirmación suma 1/{n} a la ventana.',
      fr: 'Aller-retour {r} — envoyés : {n} · accusés revenus : {n}. Chaque accusé ajoute 1/{n} à la fenêtre.',
      hi: 'चक्कर {r} — भेजे: {n} · लौटी पावतियाँ: {n}। हर पावती खिड़की में 1/{n} जोड़ती है।',
      id: 'Putaran {r} — terkirim: {n} · ack kembali: {n}. Tiap ack menambah jendela 1/{n}.',
      pt: 'Rodada {r} — enviados: {n} · confirmações de volta: {n}. Cada confirmação soma 1/{n} à janela.',
    },
    'caption.window': {
      en: 'Window: {w} → {next} · sent so far: {sent}',
      ko: '창: {w} → {next} · 지금까지 보낸 조각: {sent}',
      ja: 'ウィンドウ: {w} → {next} · これまでに送ったセグメント: {sent}',
      zh: '窗口：{w} → {next} · 至今发送的分段：{sent}',
      ar: 'النافذة: {w} → {next} · المُرسَل حتى الآن: {sent}',
      es: 'Ventana: {w} → {next} · enviados hasta ahora: {sent}',
      fr: 'Fenêtre : {w} → {next} · envoyés jusqu’ici : {sent}',
      hi: 'खिड़की: {w} → {next} · अब तक भेजे: {sent}',
      id: 'Jendela: {w} → {next} · terkirim sejauh ini: {sent}',
      pt: 'Janela: {w} → {next} · enviados até agora: {sent}',
    },
  },
  blocks: {
    stage: { type: 'slow-start-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
