/**
 * Tokenization (어휘 분석) facet JSON 선언.
 *
 * 진행 모델: 입력 반응형 (ReactiveMechanism). mount 직후 자동 1회 스캔이
 * 자율 박자 (한 글자 ≈ 280ms) 로 흘러간 뒤 waitForInput. 사용자는 예제 전환,
 * 재생, 리셋, 속도 슬라이더로 다시 박자를 깨운다.
 *
 * 컨트롤바 어휘 (기획 §8):
 *   [ next-example ] [ replay ] [ speed-slider ] [ reset ]
 *
 * 식별자 (C1): `gaze` `segment` `card:<index>` 명시 prefix.
 *
 * 종류 색 팔레트 — 기획 §9 와 일치 (categorical 시드 위에 의미 라벨로 매핑).
 *   keyword (보라) / identifier (청록) / number (주황) / operator (노랑) /
 *   punct (회청) / string (연두) / error (빨강) / swallow (연회색).
 *   실제 hex 는 view 가 design-tokens 의 categorical/palette 에서 받아 채운다 —
 *   facet.ts 는 의미 라벨만 선언하고 색은 view 결정.
 */

import type { FacetJson } from '@ffacet/core/runtime';

export const tokenizationFacet: FacetJson = {
  id: 'facet:tokenization',
  title: { en: 'Tokenization (Lexical Analysis)', ko: '토큰화 (어휘 분석)', ja: 'トークン化 (字句解析)', zh: '词法切分 (词法分析)', ar: 'التقطيع إلى رموز (التحليل المعجمي)', es: 'Tokenización (análisis léxico)', fr: 'Tokenisation (analyse lexicale)', hi: 'टोकनीकरण (शाब्दिक विश्लेषण)', id: 'Tokenisasi (analisis leksikal)', pt: 'Tokenização (análise léxica)' },
  description: { en: 'A left-to-right gaze that fuses same-kind characters into a single segment until it cannot extend further, then drops the closed run as a labeled token card onto the output row', ko: '응시가 좌에서 우로 한 글자씩 전진하며 같은 종류 글자들을 한 구간으로 묶다가 더는 못 묶이는 순간 닫고, 그 구간을 종류 라벨과 원문이 함께 새겨진 한 장의 카드로 떨궈 출력열에 붙이는 첫 변환 단계', ja: '左から右へ進む視線が同じ種類の文字を一つの区間に融かしていき、もう伸ばせなくなった時点で閉じて、その区間を種類のラベルを付けたトークンカードとして出力の列へ落とす', zh: '自左向右的目光把同类字符熔进一个区段，直到再也伸不长时闭合，然后把这个闭合的段落作为带类别标签的词元卡片落到输出行', ar: 'نظرة تمضي من اليسار إلى اليمين تصهر الحروف المتماثلة في مقطع واحد حتى يعجز عن الامتداد، ثم تُسقط المقطع المغلق بطاقةَ رمزٍ تحمل نوعها في صف الإخراج', es: 'Una mirada de izquierda a derecha funde caracteres del mismo tipo en un segmento hasta que no puede extenderse más, y entonces deja el tramo cerrado como tarjeta de token etiquetada en la fila de salida', fr: 'Un regard de gauche à droite fond les caractères de même nature en un segment jusqu\'à ne plus pouvoir s\'étendre, puis dépose ce segment clos en carte de jeton étiquetée sur la ligne de sortie', hi: 'बाएँ से दाएँ बढ़ती दृष्टि एक ही प्रकार के अक्षरों को एक खंड में पिघलाती जाती है जब तक और न बढ़ सके, फिर उस बंद खंड को प्रकार-लेबल वाले टोकन कार्ड के रूप में निर्गत पंक्ति पर गिरा देती है', id: 'Pandangan dari kiri ke kanan melebur karakter sejenis menjadi satu segmen sampai tak bisa diperpanjang lagi, lalu menjatuhkan runtunan tertutup itu sebagai kartu token berlabel ke baris keluaran', pt: 'Um olhar da esquerda para a direita funde caracteres do mesmo tipo num segmento até não poder mais estender, e então solta o trecho fechado como uma carta de token rotulada na linha de saída' },
  algorithm: 'module:tokenization',
  projector: 'module:tokenizationProjector',
  initialData: {
    type: 'tokenization',
    initialExampleIndex: 1,
    examples: [
      {
        id: 'basic',
        name: { en: 'var x = 42;', ko: '간단 — var x = 42;', ja: 'var x = 42;', zh: 'var x = 42;', ar: 'var x = 42;', es: 'var x = 42;', fr: 'var x = 42;', hi: 'var x = 42;', id: 'var x = 42;', pt: 'var x = 42;' },
        source: 'var x = 42;',
      },
      {
        id: 'compound',
        name: { en: 'if x >= 10 // ok', ko: '복합 — if x >= 10  // ok', ja: 'if x >= 10 // ok', zh: 'if x >= 10 // ok', ar: 'if x >= 10 // ok', es: 'if x >= 10 // ok', fr: 'if x >= 10 // ok', hi: 'if x >= 10 // ok', id: 'if x >= 10 // ok', pt: 'if x >= 10 // ok' },
        source: 'if x >= 10  // ok\n  return x;',
      },
      {
        id: 'comment',
        name: { en: '// note + return n', ko: '주석 — // note + return n', ja: '// note + return n', zh: '// note + return n', ar: '// note + return n', es: '// note + return n', fr: '// note + return n', hi: '// note + return n', id: '// note + return n', pt: '// note + return n' },
        source: '// note\n  return n',
      },
    ],
    stepMs: 280,
    closePulseRatio: 0.9,
    endHoldMs: 1100,
    keywords: [
      'if',
      'else',
      'return',
      'var',
      'let',
      'const',
      'while',
      'for',
      'function',
      'true',
      'false',
      'null',
    ],
    kindPalette: {
      keyword: { swatch: 'keyword', label: { en: 'keyword', ko: '키워드', ja: 'キーワード', zh: '关键字', ar: 'كلمة مفتاحية', es: 'palabra clave', fr: 'mot-clé', hi: 'कीवर्ड', id: 'kata kunci', pt: 'palavra-chave' } },
      identifier: { swatch: 'identifier', label: { en: 'identifier', ko: '식별자', ja: '識別子', zh: '标识符', ar: 'مُعرِّف', es: 'identificador', fr: 'identifiant', hi: 'पहचानकर्ता', id: 'pengenal', pt: 'identificador' } },
      number: { swatch: 'number', label: { en: 'number', ko: '숫자', ja: '数値', zh: '数字', ar: 'عدد', es: 'número', fr: 'nombre', hi: 'संख्या', id: 'angka', pt: 'número' } },
      operator: { swatch: 'operator', label: { en: 'operator', ko: '연산자', ja: '演算子', zh: '运算符', ar: 'عامل', es: 'operador', fr: 'opérateur', hi: 'संकारक', id: 'operator', pt: 'operador' } },
      punct: { swatch: 'punct', label: { en: 'punct', ko: '구분자', ja: '区切り', zh: '标点', ar: 'ترقيم', es: 'punt.', fr: 'ponct.', hi: 'विराम', id: 'tanda baca', pt: 'pontuação' } },
      string: { swatch: 'string', label: { en: 'string', ko: '문자열', ja: '文字列', zh: '字符串', ar: 'سلسلة', es: 'cadena', fr: 'chaîne', hi: 'स्ट्रिंग', id: 'string', pt: 'cadeia' } },
      error: { swatch: 'error', label: { en: 'error', ko: '오류', ja: 'エラー', zh: '错误', ar: 'خطأ', es: 'error', fr: 'erreur', hi: 'त्रुटि', id: 'galat', pt: 'erro' } },
      swallow: { swatch: 'swallow', label: { en: 'whitespace', ko: '삼킴', ja: '空白', zh: '空白', ar: 'مسافة', es: 'espacio', fr: 'espace', hi: 'रिक्ति', id: 'spasi', pt: 'espaço' } },
    },
  },
  shuffleOnReset: false,
  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { ref: 'controls' },
    ],
  },
  messages: {
    'caption.base': {
      en: 'Tokenization is the first stage of a compiler. It reads the source a character at a time from left to right and cuts it into the smallest units that carry meaning — taking the longest run it can, and leaving whitespace and comments as nothing but traces.',
      ko: '토큰화는 컴파일러의 첫 단계다. 사람이 쓴 소스 문자열을 좌에서 우로 한 글자씩 읽어 의미 있는 최소 단위로 끊는다. 더 길게 묶을 수 있으면 더 길게 묶고, 공백과 주석은 흔적으로만 남는다.',
      ja: 'トークン化はコンパイラの最初の段階だ。人が書いたソースの文字列を左から右へ一文字ずつ読み、意味を担う最小の単位へ切り分ける。より長くまとめられるならまとめ、空白とコメントは痕跡としてしか残らない。',
      zh: '词法切分是编译器的第一步。它把人写下的源码从左到右一次读一个字符，切成携带意义的最小单位；能连多长就连多长，而空白和注释只留下痕迹。',
      ar: 'التقطيع إلى رموز هو أول مراحل المترجم. يقرأ الشيفرة التي كتبها الإنسان حرفًا حرفًا من اليسار إلى اليمين ويقطّعها إلى أصغر وحدات تحمل معنى — آخذًا أطول امتداد ممكن، ولا تبقى المسافات والتعليقات إلا أثرًا.',
      es: 'La tokenización es la primera etapa de un compilador. Lee el código escrito por una persona carácter a carácter, de izquierda a derecha, y lo corta en las unidades más pequeñas que llevan significado, tomando la tirada más larga posible; los espacios y comentarios quedan solo como rastros.',
      fr: 'La tokenisation est la première étape d\'un compilateur. Elle lit la source écrite par un humain caractère par caractère, de gauche à droite, et la découpe en les plus petites unités porteuses de sens — en prenant la plus longue tirade possible ; espaces et commentaires ne restent que comme traces.',
      hi: 'टोकनीकरण संकलक का पहला चरण है। यह मनुष्य के लिखे स्रोत को बाएँ से दाएँ एक-एक अक्षर पढ़कर अर्थ धारण करने वाली सबसे छोटी इकाइयों में काटता है — जितना लंबा जोड़ सके जोड़ता है, और रिक्ति व टिप्पणियाँ केवल निशान भर रह जाती हैं।',
      id: 'Tokenisasi adalah tahap pertama kompilator. Ia membaca sumber tulisan manusia satu karakter setiap kali dari kiri ke kanan dan memotongnya menjadi unit terkecil yang bermakna — mengambil rentetan terpanjang yang bisa, sementara spasi dan komentar hanya tersisa sebagai jejak.',
      pt: 'A tokenização é a primeira etapa de um compilador. Ela lê a fonte escrita por uma pessoa um caractere por vez, da esquerda para a direita, e a corta nas menores unidades que carregam significado — pegando a maior tirada possível, e espaços e comentários ficam apenas como rastros.',
    },
    'caption.comment': {
      en: 'A comment never becomes a token — it stays as a trace.',
      ko: '주석은 토큰이 되지 못해 흔적으로만 남는다.',
      ja: 'コメントはトークンになりません — 痕跡として残るだけです。',
      zh: '注释永远不会成为词元 — 它只留下痕迹。',
      ar: 'لا يصير التعليق رمزًا أبدًا — يبقى أثرًا فقط.',
      es: 'Un comentario nunca se vuelve token: queda solo como rastro.',
      fr: 'Un commentaire ne devient jamais un jeton — il ne reste qu\'une trace.',
      hi: 'टिप्पणी कभी टोकन नहीं बनती — वह केवल निशान रह जाती है।',
      id: 'Komentar tak pernah menjadi token — ia tinggal sebagai jejak.',
      pt: 'Um comentário nunca vira token — fica apenas como rastro.',
    },
    'caption.example': {
      en: 'Example {n} — {name}',
      ko: '예제 {n} — {name}',
      ja: '例 {n} — {name}',
      zh: '示例 {n} — {name}',
      ar: 'مثال {n} — {name}',
      es: 'Ejemplo {n} — {name}',
      fr: 'Exemple {n} — {name}',
      hi: 'उदाहरण {n} — {name}',
      id: 'Contoh {n} — {name}',
      pt: 'Exemplo {n} — {name}',
    },
    'caption.ignoredInput': {
      en: 'Input ignored — {op}: {raw}',
      ko: '입력 무시 — {op}: {raw}',
      ja: '入力を無視しました — {op}: {raw}',
      zh: '忽略了输入 — {op}: {raw}',
      ar: 'تُجوهل الإدخال — {op}: {raw}',
      es: 'Entrada ignorada — {op}: {raw}',
      fr: 'Saisie ignorée — {op} : {raw}',
      hi: 'इनपुट अनदेखा किया गया — {op}: {raw}',
      id: 'Masukan diabaikan — {op}: {raw}',
      pt: 'Entrada ignorada — {op}: {raw}',
    },
    'caption.scanDone': {
      en: 'Scan complete — {count} tokens.',
      ko: '스캔 완료 — {count}장의 토큰.',
      ja: '走査完了 — トークン {count} 枚。',
      zh: '扫描完成 — 共 {count} 个词元。',
      ar: 'اكتمل المسح — {count} رمزًا.',
      es: 'Escaneo completo: {count} tokens.',
      fr: 'Balayage terminé — {count} jetons.',
      hi: 'स्कैन पूरा — {count} टोकन।',
      id: 'Pemindaian selesai — {count} token.',
      pt: 'Varredura completa — {count} tokens.',
    },
    'caption.unrecognized': {
      en: 'An unrecognized character — it lands as a red card.',
      ko: '인식 불가 글자 — 빨간 카드로 박힌다.',
      ja: '認識できない文字です — 赤いカードとして刺さります。',
      zh: '无法识别的字符 — 会落成一张红卡。',
      ar: 'حرف غير معروف — يستقر كبطاقة حمراء.',
      es: 'Un carácter no reconocido: aterriza como tarjeta roja.',
      fr: 'Un caractère non reconnu — il atterrit en carte rouge.',
      hi: 'अपरिचित अक्षर — यह लाल कार्ड बनकर टिकता है।',
      id: 'Karakter tak dikenal — mendarat sebagai kartu merah.',
      pt: 'Um caractere não reconhecido — pousa como carta vermelha.',
    },
    'concept.line1': {
      en: 'Tokenization is the first stage of a compiler — reading left to right, one',
      ko: '토큰화는 컴파일러의 첫 단계 — 좌에서 우로 한 글자씩 읽어 의미 있는 최소',
      ja: 'トークン化はコンパイラの最初の段階 — 左から右へ一文字',
      zh: '词法切分是编译器的第一步 — 从左到右一次读',
      ar: 'التقطيع أول مراحل المترجم — يقرأ من اليسار إلى اليمين',
      es: 'La tokenización es la primera etapa del compilador: leyendo de',
      fr: 'La tokenisation est la première étape du compilateur — en lisant',
      hi: 'टोकनीकरण संकलक का पहला चरण है — बाएँ से दाएँ एक-एक',
      id: 'Tokenisasi adalah tahap pertama kompilator — membaca dari kiri',
      pt: 'A tokenização é a primeira etapa do compilador — lendo da',
    },
    'concept.line2': {
      en: 'character at a time, it cuts the source into the smallest meaningful units',
      ko: '단위 (토큰) 로 끊어 낸다. 더 길게 묶을 수 있으면 더 길게 묶고, 공백·주석',
      ja: 'ずつ読み、意味を担う最小の単位 (トークン) へ切り分ける。',
      zh: '一个字符，把源码切成携带意义的最小单位 (词元)，',
      ar: 'حرفًا حرفًا ويقطّع المصدر إلى أصغر وحدات حاملة للمعنى (رموز)،',
      es: 'izquierda a derecha, carácter a carácter, corta el código en las',
      fr: 'de gauche à droite, caractère par caractère, il découpe la source en',
      hi: 'अक्षर पढ़ते हुए वह स्रोत को अर्थ धारण करने वाली सबसे छोटी',
      id: 'ke kanan, satu karakter setiap kali, ia memotong sumber menjadi',
      pt: 'esquerda para a direita, um caractere por vez, ele corta a fonte',
    },
    'concept.line3': {
      en: '(tokens), taking the longest run it can. Whitespace and comments never',
      ko: '은 토큰이 되지 못하고 회색으로 가라앉는다. 위 띠에서 글자가 어떻게 묶여',
      ja: 'より長くまとめられるならまとめる。空白とコメントは',
      zh: '能连多长就连多长。空白和注释永远不会成为',
      ar: 'آخذًا أطول امتداد ممكن. المسافات والتعليقات لا تصير',
      es: 'unidades más pequeñas con significado (tokens), tomando la tirada',
      fr: 'les plus petites unités porteuses de sens (jetons), en prenant la plus',
      hi: 'इकाइयों (टोकन) में काटता है, जितना लंबा जोड़ सके जोड़ता है।',
      id: 'unit terkecil yang bermakna (token), mengambil rentetan terpanjang',
      pt: 'nas menores unidades com significado (tokens), pegando a maior',
    },
    'concept.line4': {
      en: 'become tokens and sink into grey. Watch the strip above feed the cards below.',
      ko: '아래 카드로 떨어지는지 보자.',
      ja: 'トークンにならず灰色に沈む。上の帯が下のカードを生む様子を見よう。',
      zh: '词元，而是沉入灰色。看上方的带子如何喂养下方的卡片。',
      ar: 'رموزًا أبدًا بل تغرق في الرمادي. راقب الشريط أعلاه وهو يغذّي البطاقات أدناه.',
      es: 'más larga posible. Los espacios y comentarios nunca son tokens y se hunden en gris.',
      fr: 'longue possible. Espaces et commentaires ne deviennent jamais des jetons et sombrent en gris.',
      hi: 'रिक्ति और टिप्पणियाँ कभी टोकन नहीं बनतीं, धूसर में डूब जाती हैं।',
      id: 'yang bisa. Spasi dan komentar tak pernah jadi token dan tenggelam kelabu.',
      pt: 'tirada possível. Espaços e comentários nunca viram tokens e afundam no cinza.',
    },
    'kind.error': {
      en: 'error',
      ko: '오류',
      ja: 'エラー',
      zh: '错误',
      ar: 'خطأ',
      es: 'error',
      fr: 'erreur',
      hi: 'त्रुटि',
      id: 'galat',
      pt: 'erro',
    },
    'kind.identifier': {
      en: 'identifier',
      ko: '식별자',
      ja: '識別子',
      zh: '标识符',
      ar: 'مُعرِّف',
      es: 'identificador',
      fr: 'identifiant',
      hi: 'पहचानकर्ता',
      id: 'pengenal',
      pt: 'identificador',
    },
    'kind.keyword': {
      en: 'keyword',
      ko: '키워드',
      ja: 'キーワード',
      zh: '关键字',
      ar: 'كلمة مفتاحية',
      es: 'palabra clave',
      fr: 'mot-clé',
      hi: 'कीवर्ड',
      id: 'kata kunci',
      pt: 'palavra-chave',
    },
    'kind.number': {
      en: 'number',
      ko: '숫자',
      ja: '数値',
      zh: '数字',
      ar: 'عدد',
      es: 'número',
      fr: 'nombre',
      hi: 'संख्या',
      id: 'angka',
      pt: 'número',
    },
    'kind.operator': {
      en: 'operator',
      ko: '연산자',
      ja: '演算子',
      zh: '运算符',
      ar: 'عامل',
      es: 'operador',
      fr: 'opérateur',
      hi: 'संकारक',
      id: 'operator',
      pt: 'operador',
    },
    'kind.punctuation': {
      en: 'punctuation',
      ko: '구분자',
      ja: '区切り記号',
      zh: '标点',
      ar: 'علامة ترقيم',
      es: 'puntuación',
      fr: 'ponctuation',
      hi: 'विराम चिह्न',
      id: 'tanda baca',
      pt: 'pontuação',
    },
    'kind.string': {
      en: 'string',
      ko: '문자열',
      ja: '文字列',
      zh: '字符串',
      ar: 'سلسلة نصية',
      es: 'cadena',
      fr: 'chaîne',
      hi: 'स्ट्रिंग',
      id: 'string',
      pt: 'cadeia',
    },
    'kind.swallowed': {
      en: 'swallowed',
      ko: '삼킴',
      ja: '飲み込み',
      zh: '吞掉',
      ar: 'مُبتلَع',
      es: 'absorbido',
      fr: 'avalé',
      hi: 'निगला गया',
      id: 'tertelan',
      pt: 'engolido',
    },
    'label.closed': {
      en: '↓ closed',
      ko: '↓ 닫힘',
      ja: '↓ 確定',
      zh: '↓ 已闭合',
      ar: '↓ مُغلق',
      es: '↓ cerrado',
      fr: '↓ fermé',
      hi: '↓ बंद',
      id: '↓ tertutup',
      pt: '↓ fechado',
    },
    'label.input': {
      en: 'input',
      ko: '입력',
      ja: '入力',
      zh: '输入',
      ar: 'الإدخال',
      es: 'entrada',
      fr: 'entrée',
      hi: 'इनपुट',
      id: 'masukan',
      pt: 'entrada',
    },
    'label.legend': {
      en: 'legend',
      ko: '범례',
      ja: '凡例',
      zh: '图例',
      ar: 'مفتاح',
      es: 'leyenda',
      fr: 'légende',
      hi: 'संकेत-सूची',
      id: 'legenda',
      pt: 'legenda',
    },
    'label.output': {
      en: 'output tokens',
      ko: '출력 토큰',
      ja: '出力トークン',
      zh: '输出词元',
      ar: 'الرموز الناتجة',
      es: 'tokens de salida',
      fr: 'jetons de sortie',
      hi: 'निर्गत टोकन',
      id: 'token keluaran',
      pt: 'tokens de saída',
    },
    'label.references': {
      en: 'see also',
      ko: '참고',
      ja: '参考',
      zh: '参考',
      ar: 'انظر أيضًا',
      es: 'véase también',
      fr: 'voir aussi',
      hi: 'और देखें',
      id: 'lihat juga',
      pt: 'veja também',
    },
    'label.title': {
      en: 'Tokenization — one beat of condensation',
      ko: '토큰화 — 한 박자의 응결',
      ja: 'トークン化 — 一拍の凝結',
      zh: '词法切分 — 一拍的凝结',
      ar: 'التقطيع إلى رموز — تكثّف في نبضة واحدة',
      es: 'Tokenización: una condensación en un solo compás',
      fr: 'Tokenisation — une condensation en un temps',
      hi: 'टोकनीकरण — एक ताल का संघनन',
      id: 'Tokenisasi — satu ketuk pengembunan',
      pt: 'Tokenização — uma condensação num só compasso',
    },
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'tokenization-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        {
          widget: 'button',
          action: 'next-example',
          label: { en: 'Next example', ko: '다음 예제', ja: '次の例', zh: '下一个示例', ar: 'المثال التالي', es: 'Siguiente ejemplo', fr: 'Exemple suivant', hi: 'अगला उदाहरण', id: 'Contoh berikutnya', pt: 'Próximo exemplo' },
        },
        { widget: 'button', action: 'replay', label: { en: 'Replay', ko: '다시 재생', ja: '再演', zh: '重播', ar: 'إعادة العرض', es: 'Repetir', fr: 'Rejouer', hi: 'दोबारा', id: 'Ulangi', pt: 'Repetir' } },
        { widget: 'speed-slider', action: 'speed' },
        { widget: 'button', action: 'reset', label: { en: 'Reset', ko: '초기화', ja: 'リセット', zh: '重置', ar: 'إعادة', es: 'Reiniciar', fr: 'Réinit.', hi: 'रीसेट', id: 'Atur ulang', pt: 'Reiniciar' } },
      ],
    },
  },
};
