/**
 * @piece 정렬부 삽입 — 조각(piece) facet 선언.
 *
 * 답하는 질문 하나: **"끼워 넣는다" 는 자리가 저절로 벌어지는 일인가?**
 * 벌어지는 자리는 누군가 비켜서야 생기고, 비켜서는 순서는 뒤에서부터여야 하며,
 * 왼쪽이 이미 줄 서 있으므로 걸음은 왼쪽 끝에 닿기 전에 멈춘다.
 *
 * 제목·metrics·layout 을 두지 않는다 — 제목은 글의 문단이 주고, 조각은 셀 것이
 * 없으며, stage 와 controls 뿐이라 배치는 러너 기본값으로 족하다 (S-piece).
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const insertIntoSortedPartFacet: FacetJson = {
  id: 'facet:insertIntoSortedPart',
  title: {
    en: 'Insert into the sorted part',
    ko: '정렬부 삽입',
    ja: '整列済みの部分へ挿入',
    zh: '插入到已排序的部分',
    ar: 'الإدراج في الجزء المرتَّب',
    es: 'Insertar en la parte ordenada',
    fr: 'Insérer dans la partie triée',
    hi: 'क्रमित भाग में सम्मिलन',
    id: 'Sisipkan ke bagian terurut',
    pt: 'Inserir na parte ordenada',
  },
  description: {
    en: 'A new value is lifted out of the row, values step aside from the back, and it settles into the gap.',
    ko: '새 값이 줄에서 들리고, 값들이 뒤에서부터 비켜서고, 빈자리가 나면 내려앉는다.',
    ja: '新しい値を列から持ち上げ、後ろから順に値がずれ、空いた場所に収まる。',
    zh: '把新值从队列中提起来，后面的值依次让位，它落进空出的位置。',
    ar: 'تُرفع قيمة جديدة من الصف، وتتنحّى القيم بدءًا من الخلف، ثم تستقر في الفراغ.',
    es: 'Se levanta un valor nuevo de la fila, los valores se apartan desde atrás y él se asienta en el hueco.',
    fr: "Une nouvelle valeur est retirée de la rangée, les valeurs s'écartent en partant de la fin, et elle se pose dans le trou.",
    hi: 'नया मान पंक्ति से उठाया जाता है, मान पीछे से खिसकते हैं, और वह खाली जगह में बैठ जाता है।',
    id: 'Nilai baru diangkat dari barisan, nilai-nilai menggeser dari belakang, lalu ia turun ke celah itu.',
    pt: 'Um valor novo é tirado da fila, os valores se afastam a partir do fim e ele se acomoda na lacuna.',
  },
  algorithm: 'module:insertIntoSortedPart',
  projector: 'module:insertIntoSortedPartProjector',
  initialData: {
    type: 'insert-into-sorted-part',
    sorted: [2, 5, 8],
    incoming: 4,
    // 걸음 간격. 무대의 이동 애니메이션이 이 위에 더해지므로 걸음 하나는
    // 대략 1.1초다 (S-piece).
    stepMs: 750,
  },
  blocks: {
    stage: { type: 'insert-into-sorted-part-stage' },
    controls: {
      type: 'control-bar',
      controls: CONTROL_SET.piece,
    },
  },
  messages: {
    'caption.begin': {
      en: 'The left side is already in order. {value} goes in next.',
      ko: '왼쪽은 이미 줄이 서 있다. 다음 차례는 새 값({value}).',
      ja: '左側はすでに並んでいる。次は {value} の番だ。',
      zh: '左边已经排好了。接下来轮到 {value}。',
      ar: 'الجانب الأيسر مرتَّب بالفعل. الدور الآن على {value}.',
      es: 'La parte izquierda ya está ordenada. Ahora entra {value}.',
      fr: 'La partie gauche est déjà triée. Au tour de {value}.',
      hi: 'बाईं ओर पहले से क्रम में है। अब {value} की बारी।',
      id: 'Sisi kiri sudah terurut. Berikutnya giliran {value}.',
      pt: 'O lado esquerdo já está ordenado. Agora entra {value}.',
    },
    'caption.lift': {
      en: 'Lift {value} out of the row. That slot is empty now.',
      ko: '새 값({value})을 줄에서 들어 올린다. 그 칸은 이제 비었다.',
      ja: '{value} を列から持ち上げる。その枠は空いた。',
      zh: '把 {value} 从队列里提起来。那个位置空了。',
      ar: 'ارفع {value} من الصف. أصبح ذلك الموضع فارغًا.',
      es: 'Levanta {value} de la fila. Ese hueco queda vacío.',
      fr: 'Retire {value} de la rangée. Cette case est vide.',
      hi: '{value} को पंक्ति से उठाएँ। वह खाना अब खाली है।',
      id: 'Angkat {value} dari barisan. Kotak itu kini kosong.',
      pt: 'Tira {value} da fila. Aquela casa agora está vazia.',
    },
    'caption.compareYields': {
      en: '{other} > {value} — {other} has to step aside.',
      ko: '{other} > {value} — 큰 값({other})이 비켜서야 한다.',
      ja: '{other} > {value} — {other} が横へどく。',
      zh: '{other} > {value} — {other} 必须让位。',
      ar: '{other} > {value} — على {other} أن يتنحّى.',
      es: '{other} > {value}: {other} tiene que apartarse.',
      fr: '{other} > {value} — {other} doit se décaler.',
      hi: '{other} > {value} — {other} को खिसकना होगा।',
      id: '{other} > {value} — {other} harus menggeser.',
      pt: '{other} > {value} — {other} tem de se afastar.',
    },
    'caption.compareHolds': {
      en: '{other} is not greater than {value}.',
      ko: '견준 값({other})은 새 값({value})보다 크지 않다.',
      ja: '{other} は {value} より大きくない。',
      zh: '{other} 不比 {value} 大。',
      ar: '{other} ليس أكبر من {value}.',
      es: '{other} no es mayor que {value}.',
      fr: "{other} n'est pas plus grand que {value}.",
      hi: '{other} {value} से बड़ा नहीं है।',
      id: '{other} tidak lebih besar dari {value}.',
      pt: '{other} não é maior que {value}.',
    },
    'caption.stepAside': {
      en: '{value} moves one slot to the right. The gap comes one slot closer.',
      ko: '값({value})이 오른쪽으로 한 칸 비켜선다. 빈자리가 한 칸 왼쪽으로 옮겨 온다.',
      ja: '{value} が右へ一つずれる。空きが一つ手前に来る。',
      zh: '{value} 向右挪一格。空位向左靠近一格。',
      ar: 'ينتقل {value} موضعًا واحدًا إلى اليمين. ويقترب الفراغ موضعًا واحدًا.',
      es: '{value} se mueve un hueco a la derecha. El vacío se acerca un hueco.',
      fr: "{value} se décale d'une case vers la droite. Le trou se rapproche d'une case.",
      hi: '{value} एक खाना दाईं ओर खिसकता है। खाली जगह एक खाना पास आ जाती है।',
      id: '{value} bergeser satu kotak ke kanan. Celahnya maju satu kotak.',
      pt: '{value} anda uma casa para a direita. A lacuna chega uma casa mais perto.',
    },
    'caption.stop': {
      en: '{other} stays put — the walk stops here, short of the left end.',
      ko: '이 값({other})은 비키지 않는다 — 왼쪽 끝에 닿기 전에 걸음이 멈춘다.',
      ja: '{other} は動かない — 左端に届く前に歩みが止まる。',
      zh: '{other} 不动 — 还没到最左端，移动就停了。',
      ar: '{other} يبقى مكانه — تتوقف المسيرة هنا قبل الطرف الأيسر.',
      es: '{other} se queda: el recorrido se detiene aquí, sin llegar al extremo izquierdo.',
      fr: "{other} ne bouge pas — la marche s'arrête ici, avant le bout à gauche.",
      hi: '{other} अपनी जगह रहता है — चाल यहीं रुक जाती है, बाएँ छोर से पहले।',
      id: '{other} tetap di tempat — langkahnya berhenti di sini, sebelum ujung kiri.',
      pt: '{other} fica onde está — a caminhada para aqui, antes do fim à esquerda.',
    },
    'caption.settle': {
      en: 'The gap is the slot {value} belongs in. It comes down.',
      ko: '빈자리가 곧 새 값({value})의 자리다. 그 자리로 내려앉는다.',
      ja: 'その空きこそ {value} の居場所だ。そこへ下りる。',
      zh: '这个空位正是 {value} 该待的地方。它落下去。',
      ar: 'هذا الفراغ هو موضع {value}. ينزل إليه.',
      es: 'El hueco es justo el sitio de {value}. Baja ahí.',
      fr: 'Le trou est la place de {value}. Elle y descend.',
      hi: 'यह खाली जगह ही {value} का ठिकाना है। वह वहीं उतर आता है।',
      id: 'Celah itu memang tempat {value}. Ia turun ke sana.',
      pt: 'A lacuna é o lugar de {value}. Ele desce ali.',
    },
    'caption.done': {
      en: '{compares} comparisons, {shifts} step-asides — the walk never reached the left end.',
      ko: '견줌 {compares}회 · 비켜섬 {shifts}회 — 왼쪽 끝까지 가지 않았다.',
      ja: '比較 {compares} 回・ずらし {shifts} 回 — 左端までは行かなかった。',
      zh: '比较 {compares} 次、让位 {shifts} 次 — 始终没有走到最左端。',
      ar: '{compares} مقارنة و{shifts} إزاحة — لم تصل المسيرة إلى الطرف الأيسر.',
      es: '{compares} comparaciones, {shifts} desplazamientos: el recorrido nunca llegó al extremo izquierdo.',
      fr: "{compares} comparaisons, {shifts} décalages — la marche n'a jamais atteint le bout à gauche.",
      hi: '{compares} तुलनाएँ, {shifts} खिसकाव — चाल कभी बाएँ छोर तक नहीं पहुँची।',
      id: '{compares} perbandingan, {shifts} pergeseran — langkahnya tak pernah sampai ujung kiri.',
      pt: '{compares} comparações, {shifts} deslocamentos — a caminhada nunca chegou ao fim à esquerda.',
    },
  },
};
