/**
 * assignThenMove — 할당과 갱신이 번갈아 도는 한 걸음 (k-평균).
 *
 * 답하는 질문: **무리의 가운데가 어디인지 모르는데 어떻게 찾는가.**
 * 붙이고 옮기기를 번갈아 하다가 아무도 안 움직이면 멎는다.
 *
 * 중심 셋은 일부러 가운데에 몰아 놓는다 — 어느 덩이에도 맞지 않는 자리라
 * 첫 걸음에 크게 움직이고, 그래서 왕복이 눈에 보인다.
 *
 * @piece
 */

import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

export const assignThenMoveFacet: FacetJson = {
  id: 'facet:assignThenMove',
  title: {
    en: 'Assign, then move',
    ko: '붙이고, 옮긴다',
    ja: '割り当てて、動かす',
    zh: '先归属，再移动',
    ar: 'اضمم ثم انقل',
    es: 'Asignar y luego mover',
    fr: 'Assigner, puis déplacer',
    hi: 'जोड़ें, फिर खिसकाएँ',
    id: 'Tempel, lalu geser',
    pt: 'Atribuir e depois mover',
  },
  description: {
    en: 'Points grab the nearest center; each center slides to the middle of what grabbed it. The two take turns until nothing moves.',
    ko: '점이 가장 가까운 중심을 잡고, 중심은 저를 잡은 것들의 가운데로 옮겨 간다. 아무도 안 움직일 때까지 둘이 번갈아 돈다.',
    ja: '点は最も近い中心をつかみ、中心はつかんだ点たちの真ん中へ滑る。動きが止まるまで交互に繰り返す。',
    zh: '每个点抓住最近的中心，每个中心滑向抓住它的那些点的中间。两者轮流，直到无人再动。',
    ar: 'كل نقطة تلتقط أقرب مركز، وكل مركز ينزلق إلى وسط ما التقطه. يتناوبان حتى يتوقف كل شيء عن الحركة.',
    es: 'Cada punto se aferra al centro más cercano; cada centro se desliza al medio de los que lo tomaron. Se alternan hasta que nada se mueve.',
    fr: "Chaque point saisit le centre le plus proche ; chaque centre glisse au milieu de ceux qui l'ont saisi. Les deux alternent jusqu'à ce que rien ne bouge.",
    hi: 'हर बिंदु निकटतम केंद्र को पकड़ता है; हर केंद्र अपने पकड़ने वालों के बीच खिसक जाता है। जब तक कुछ न हिले, दोनों बारी-बारी चलते हैं।',
    id: 'Setiap titik memilih pusat terdekat; setiap pusat bergeser ke tengah titik-titik yang memilihnya. Keduanya bergantian sampai tidak ada yang bergerak.',
    pt: 'Cada ponto agarra o centro mais próximo; cada centro desliza para o meio dos que o agarraram. Os dois se alternam até nada mais se mover.',
  },
  algorithm: 'module:assignThenMove',
  projector: 'module:assignThenMoveProjector',
  initialData: {
    type: 'assign-then-move',
    // 세 덩이로 놓인 점 열셋. 좌표는 데이터이고, 화면의 자리는 stage 가 셈한다.
    points: [
      { x: 1, y: 1 },
      { x: 1.5, y: 2 },
      { x: 2, y: 1.2 },
      { x: 1.2, y: 2.5 },
      { x: 2.2, y: 2.2 },
      { x: 6, y: 1.5 },
      { x: 6.5, y: 2.2 },
      { x: 7, y: 1 },
      { x: 6.2, y: 2.8 },
      { x: 3.5, y: 6 },
      { x: 4.2, y: 6.5 },
      { x: 3, y: 6.8 },
      { x: 4.5, y: 5.8 },
    ],
    // 어느 덩이에도 맞지 않는 자리. 일부러 가운데에 몰아 놓고 시작한다.
    seeds: [
      { x: 4, y: 2 },
      { x: 4.5, y: 3 },
      { x: 3, y: 4 },
    ],
    stepMs: 800,
  },
  blocks: {
    stage: { type: 'assign-then-move-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'caption.start': {
      en: 'Three centers sit where no cluster is.',
      ko: '중심 셋이 어느 덩이에도 맞지 않는 자리에 몰려 있다.',
      ja: '三つの中心が、どの塊にも合わない場所にある。',
      zh: '三个中心落在没有任何簇的位置。',
      ar: 'ثلاثة مراكز تقف حيث لا توجد أي كتلة.',
      es: 'Tres centros están donde no hay ningún grupo.',
      fr: "Trois centres se trouvent là où il n'y a aucun groupe.",
      hi: 'तीन केंद्र वहाँ हैं जहाँ कोई समूह नहीं है।',
      id: 'Tiga pusat berada di tempat yang tidak ada gugusnya.',
      pt: 'Três centros estão onde não há nenhum grupo.',
    },
    'caption.attach': {
      en: 'Round {round} · attach: every point grabs its nearest center. Sizes {sizes}.',
      ko: '{round}회 · 붙는다: 점마다 가장 가까운 중심을 잡는다. 무리 크기 {sizes}.',
      ja: '{round}巡目 · 割り当て：各点が最も近い中心をつかむ。大きさ {sizes}。',
      zh: '第 {round} 轮 · 归属：每个点抓住最近的中心。规模 {sizes}。',
      ar: 'الجولة {round} · الضم: كل نقطة تلتقط أقرب مركز. الأحجام {sizes}.',
      es: 'Ronda {round} · asignar: cada punto toma su centro más cercano. Tamaños {sizes}.',
      fr: 'Tour {round} · assigner : chaque point saisit son centre le plus proche. Tailles {sizes}.',
      hi: 'चक्र {round} · जोड़ना: हर बिंदु अपना निकटतम केंद्र पकड़ता है। आकार {sizes}।',
      id: 'Putaran {round} · tempel: tiap titik memilih pusat terdekat. Ukuran {sizes}.',
      pt: 'Rodada {round} · atribuir: cada ponto toma o centro mais próximo. Tamanhos {sizes}.',
    },
    'caption.move': {
      en: 'Round {round} · move: each center slides to the middle of its own points. Moved {dists}.',
      ko: '{round}회 · 옮긴다: 중심이 제 점들의 가운데로 미끄러진다. 옮긴 거리 {dists}.',
      ja: '{round}巡目 · 移動：各中心が自分の点たちの真ん中へ滑る。移動量 {dists}。',
      zh: '第 {round} 轮 · 移动：每个中心滑向自己那些点的中间。移动 {dists}。',
      ar: 'الجولة {round} · النقل: كل مركز ينزلق إلى وسط نقاطه. المسافة {dists}.',
      es: 'Ronda {round} · mover: cada centro se desliza al medio de sus puntos. Se movió {dists}.',
      fr: 'Tour {round} · déplacer : chaque centre glisse au milieu de ses points. Déplacement {dists}.',
      hi: 'चक्र {round} · खिसकना: हर केंद्र अपने बिंदुओं के बीच खिसकता है। दूरी {dists}।',
      id: 'Putaran {round} · geser: tiap pusat bergeser ke tengah titiknya. Bergerak {dists}.',
      pt: 'Rodada {round} · mover: cada centro desliza para o meio dos seus pontos. Moveu {dists}.',
    },
    'caption.settled': {
      en: 'Nobody moved, so it stops. Rounds: {rounds}.',
      ko: '아무도 움직이지 않았다. 그래서 멎는다. 돈 횟수 {rounds}.',
      ja: '誰も動かなかったので止まる。巡回 {rounds} 回。',
      zh: '无人移动，于是停下。共 {rounds} 轮。',
      ar: 'لم يتحرك أحد، فتوقف. الجولات: {rounds}.',
      es: 'Nadie se movió, así que se detiene. Rondas: {rounds}.',
      fr: "Personne n'a bougé, donc ça s'arrête. Tours : {rounds}.",
      hi: 'कोई नहीं हिला, इसलिए रुक जाता है। चक्र: {rounds}।',
      id: 'Tidak ada yang bergerak, jadi berhenti. Putaran: {rounds}.',
      pt: 'Ninguém se moveu, então para. Rodadas: {rounds}.',
    },
    'caption.capped': {
      en: 'Still moving. Rounds: {rounds}.',
      ko: '아직 움직인다. 돈 횟수 {rounds}.',
      ja: 'まだ動いている。巡回 {rounds} 回。',
      zh: '还在移动。共 {rounds} 轮。',
      ar: 'لا يزال يتحرك. الجولات: {rounds}.',
      es: 'Todavía se mueve. Rondas: {rounds}.',
      fr: 'Ça bouge encore. Tours : {rounds}.',
      hi: 'अब भी हिल रहा है। चक्र: {rounds}।',
      id: 'Masih bergerak. Putaran: {rounds}.',
      pt: 'Ainda se move. Rodadas: {rounds}.',
    },
    'label.attach': {
      en: 'attach',
      ko: '붙는다',
      ja: '割り当て',
      zh: '归属',
      ar: 'ضم',
      es: 'asignar',
      fr: 'assigner',
      hi: 'जोड़ना',
      id: 'tempel',
      pt: 'atribuir',
    },
    'label.move': {
      en: 'move',
      ko: '옮긴다',
      ja: '移動',
      zh: '移动',
      ar: 'نقل',
      es: 'mover',
      fr: 'déplacer',
      hi: 'खिसकना',
      id: 'geser',
      pt: 'mover',
    },
    'label.ledger': {
      en: 'how far each center moved',
      ko: '중심이 옮긴 거리',
      ja: '各中心の移動距離',
      zh: '各中心移动的距离',
      ar: 'المسافة التي قطعها كل مركز',
      es: 'cuánto se movió cada centro',
      fr: 'distance parcourue par chaque centre',
      hi: 'हर केंद्र कितना खिसका',
      id: 'jarak gerak tiap pusat',
      pt: 'quanto cada centro se moveu',
    },
    'label.round': {
      en: 'round {n}',
      ko: '{n}회',
      ja: '{n}巡目',
      zh: '第 {n} 轮',
      ar: 'الجولة {n}',
      es: 'ronda {n}',
      fr: 'tour {n}',
      hi: 'चक्र {n}',
      id: 'putaran {n}',
      pt: 'rodada {n}',
    },
    'label.settled': {
      en: 'no movement',
      ko: '움직임 없음',
      ja: '動きなし',
      zh: '无移动',
      ar: 'لا حركة',
      es: 'sin movimiento',
      fr: 'aucun mouvement',
      hi: 'कोई हलचल नहीं',
      id: 'tidak bergerak',
      pt: 'sem movimento',
    },
  },
};
