/**
 * facet:pNp — 크기를 밀면 확인은 기고 찾기는 뛴다.
 *
 * 손잡이 하나가 논증을 진다. 원소 개수 n 을 6 → 20 으로 밀면 확인이 드는 덧셈은
 * 5 → 19 로 거의 그대로인데 찾기가 들여다볼 후보는 64 → 1,048,576 이 된다.
 *
 * `initialData` 의 1차 데이터는 수 스물과 목표 하나, 그리고 손잡이의 시작값과 걸음
 * 간격뿐이다. 후보의 수도 덧셈의 수도 건네받는 후보도 여기 적지 않는다 — 전부
 * algorithm 이 그 자리에서 센다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const pNpFacet: FacetJson = {
  id: 'facet:pNp',

  title: {
    en: 'P vs NP',
    ko: 'P/NP 분류',
    ja: 'P対NP',
    zh: 'P 与 NP',
    ar: 'P مقابل NP',
    es: 'P frente a NP',
    fr: 'P contre NP',
    hi: 'P बनाम NP',
    id: 'P versus NP',
    pt: 'P contra NP',
  },

  description: {
    en: 'Checking an answer and finding one are not the same job — push the size and watch the two costs split.',
    ko: '답을 확인하는 일과 찾아내는 일은 같은 일이 아니다 — 크기를 밀어 두 값이 갈리는 것을 본다.',
    ja: '答えを確かめる仕事と見つけ出す仕事は同じではない — 大きさを動かして二つの値が分かれるのを見る。',
    zh: '验证一个答案和找出一个答案不是同一件事 — 推动规模，看两种代价如何分开。',
    ar: 'التحقق من إجابة وإيجادها ليسا العمل نفسه — حرّك الحجم وانظر كيف تفترق الكلفتان.',
    es: 'Comprobar una respuesta y encontrarla no son el mismo trabajo: mueve el tamaño y mira cómo se separan los dos costes.',
    fr: 'Vérifier une réponse et en trouver une ne sont pas le même travail : déplacez la taille et voyez les deux coûts diverger.',
    hi: 'उत्तर जाँचना और उत्तर खोजना एक ही काम नहीं हैं — आकार बढ़ाइए और देखिए दोनों लागतें अलग होती हैं।',
    id: 'Memeriksa jawaban dan menemukannya bukan pekerjaan yang sama — geser ukurannya dan lihat kedua biaya itu memisah.',
    pt: 'Conferir uma resposta e encontrá-la não são o mesmo trabalho — mova o tamanho e veja os dois custos se separarem.',
  },

  algorithm: 'module:pNp',
  projector: 'module:pNpProjector',

  initialData: {
    type: 'p-np',
    // 고를 수 있는 수 스물. 손잡이가 앞에서부터 n 개를 쓴다. 앞 여섯은 조각
    // verifyVsFind 가 쓴 것 그대로라, 그 조각을 본 사람은 같은 문제가 커지는 것을 본다.
    values: [3, 7, 12, 19, 24, 31, 38, 45, 52, 58, 63, 69, 74, 78, 82, 85, 88, 91, 94, 97],
    target: 50,
    n: 6,
    // 걸음 하나가 이만큼이다. 가장 얇은 걸음이 800ms 아래로 떨어지면 캡션을 읽을
    // 틈이 사라진다 (S-piece 의 걸음 벽시계). stage 가 전면 동기라 얹히는 것이 없다.
    stepMs: 840,
  },

  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { ref: 'controls' },
      { ref: 'codePanel' },
    ],
  },

  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'p-np-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'size',
          name: 'size',
          label: {
            en: 'Numbers',
            ko: '수의 개수',
            ja: '数の個数',
            zh: '数的个数',
            ar: 'عدد الأرقام',
            es: 'Cantidad de números',
            fr: 'Nombre de nombres',
            hi: 'संख्याओं की गिनती',
            id: 'Banyak angka',
            pt: 'Quantidade de números',
          },
          segments: [
            { value: 6, label: '6', default: true },
            { value: 8, label: '8' },
            { value: 10, label: '10' },
            { value: 12, label: '12' },
            { value: 15, label: '15' },
            { value: 20, label: '20' },
          ],
        },
      ],
      metrics: [
        {
          name: 'check-looks',
          label: {
            en: 'Checking looks at',
            ko: '확인이 본 후보',
            ja: '検証が見た候補',
            zh: '验证看的候选',
            ar: 'ما نظر فيه التحقق',
            es: 'Comprobar mira',
            fr: 'Vérifier regarde',
            hi: 'जाँच ने देखे',
            id: 'Memeriksa melihat',
            pt: 'Conferir olha',
          },
          initial: 0,
        },
        {
          name: 'find-looks',
          label: {
            en: 'Finding looks at',
            ko: '찾기가 본 후보',
            ja: '探索が見た候補',
            zh: '搜索看的候选',
            ar: 'ما نظر فيه البحث',
            es: 'Buscar mira',
            fr: 'Chercher regarde',
            hi: 'खोज ने देखे',
            id: 'Mencari melihat',
            pt: 'Procurar olha',
          },
          initial: 0,
        },
        {
          name: 'add-steps',
          label: {
            en: 'Additions per candidate',
            ko: '후보당 덧셈',
            ja: '候補あたりの加算',
            zh: '每个候选的加法',
            ar: 'الجمع لكل مرشح',
            es: 'Sumas por candidato',
            fr: 'Additions par candidat',
            hi: 'प्रति उम्मीदवार जोड़',
            id: 'Penjumlahan per kandidat',
            pt: 'Somas por candidato',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:p-np-imperative',
      label: {
        en: 'Check one, count them all',
        ko: '하나를 확인하고, 전부를 세기',
        ja: '一つを確かめ、全部を数える',
        zh: '验证一个，数清全部',
        ar: 'تحقّق من واحد، وعُدّ الجميع',
        es: 'Comprobar uno, contarlos todos',
        fr: 'Vérifier un, les compter tous',
        hi: 'एक को जाँचो, सबको गिनो',
        id: 'Periksa satu, hitung semua',
        pt: 'Conferir um, contar todos',
      },
    },
  },

  messages: {
    'label.numbers': {
      en: 'Numbers to choose from',
      ko: '고를 수 있는 수',
      ja: '選べる数',
      zh: '可选的数',
      ar: 'الأرقام المتاحة',
      es: 'Números disponibles',
      fr: 'Nombres disponibles',
      hi: 'चुनने योग्य संख्याएँ',
      id: 'Angka yang tersedia',
      pt: 'Números disponíveis',
    },
    'label.target': {
      en: 'Target',
      ko: '목표',
      ja: '目標',
      zh: '目标',
      ar: 'الهدف',
      es: 'Objetivo',
      fr: 'Cible',
      hi: 'लक्ष्य',
      id: 'Target',
      pt: 'Alvo',
    },
    'label.check': {
      en: 'Checking one handed to you',
      ko: '건네받은 하나를 확인하기',
      ja: '渡された一つを確かめる',
      zh: '验证别人递来的一个',
      ar: 'التحقق من واحد يُناوَل لك',
      es: 'Comprobar el que te entregan',
      fr: 'Vérifier celui qu’on vous tend',
      hi: 'थमाए गए एक की जाँच',
      id: 'Memeriksa satu yang disodorkan',
      pt: 'Conferir o que lhe entregam',
    },
    'label.find': {
      en: 'Finding one yourself',
      ko: '스스로 찾아내기',
      ja: '自分で見つけ出す',
      zh: '自己找出一个',
      ar: 'أن تجده بنفسك',
      es: 'Encontrarlo tú mismo',
      fr: 'En trouver un soi-même',
      hi: 'खुद खोज निकालना',
      id: 'Menemukannya sendiri',
      pt: 'Encontrar por conta própria',
    },
    'label.adds': {
      en: 'Additions',
      ko: '덧셈',
      ja: '加算',
      zh: '加法',
      ar: 'عمليات الجمع',
      es: 'Sumas',
      fr: 'Additions',
      hi: 'जोड़',
      id: 'Penjumlahan',
      pt: 'Somas',
    },
    'label.sheet': {
      en: 'One sheet holds {n} candidates',
      ko: '한 장이 후보 {n} 을 담는다',
      ja: '一枚が候補 {n} を収める',
      zh: '一张容纳 {n} 个候选',
      ar: 'الورقة الواحدة تسع {n} مرشحًا',
      es: 'Una hoja contiene {n} candidatos',
      fr: 'Une feuille contient {n} candidats',
      hi: 'एक पन्ना {n} उम्मीदवार समेटता है',
      id: 'Satu lembar memuat {n} kandidat',
      pt: 'Uma folha comporta {n} candidatos',
    },
    'label.sheets': {
      en: 'Sheets needed',
      ko: '필요한 장',
      ja: '必要な枚数',
      zh: '需要的张数',
      ar: 'الأوراق اللازمة',
      es: 'Hojas necesarias',
      fr: 'Feuilles nécessaires',
      hi: 'कितने पन्ने चाहिए',
      id: 'Lembar yang dibutuhkan',
      pt: 'Folhas necessárias',
    },
    'caption.problem': {
      en: '{count} numbers and a target of {target}. Two jobs start from exactly the same place.',
      ko: '고를 수 있는 수 {count}, 목표 {target}. 두 일이 똑같은 자리에서 갈라진다.',
      ja: '選べる数 {count}、目標 {target}。二つの仕事がまったく同じ場所から分かれる。',
      zh: '可选的数 {count} 个，目标 {target}。两件事从完全相同的地方分开。',
      ar: '{count} من الأرقام وهدف قدره {target}. عملان ينطلقان من الموضع نفسه تمامًا.',
      es: '{count} números y un objetivo de {target}. Dos trabajos parten del mismo sitio.',
      fr: '{count} nombres et une cible de {target}. Deux tâches partent exactement du même point.',
      hi: '{count} संख्याएँ और {target} का लक्ष्य। दोनों काम ठीक एक ही जगह से अलग होते हैं।',
      id: '{count} angka dan target {target}. Dua pekerjaan berangkat dari tempat yang persis sama.',
      pt: '{count} números e um alvo de {target}. Dois trabalhos partem exatamente do mesmo lugar.',
    },
    'caption.check': {
      en: 'The handed candidate adds up in {used} additions. No candidate ever needs more than {adds}.',
      ko: '건네받은 후보는 덧셈 {used} 번이면 더해진다. 어느 후보도 {adds} 번을 넘지 않는다.',
      ja: '渡された候補は加算 {used} 回で足し終わる。どの候補も {adds} 回を超えない。',
      zh: '递来的候选加 {used} 次就算完。任何候选都不会超过 {adds} 次。',
      ar: 'المرشح المُناوَل يُجمع في {used} من عمليات الجمع. ولا يحتاج أي مرشح أكثر من {adds}.',
      es: 'El candidato entregado se suma en {used} sumas. Ningún candidato necesita más de {adds}.',
      fr: 'Le candidat qu’on vous tend se somme en {used} additions. Aucun candidat n’en demande plus de {adds}.',
      hi: 'थमाया गया उम्मीदवार {used} जोड़ में जुड़ जाता है। किसी भी उम्मीदवार को {adds} से ज़्यादा नहीं लगते।',
      id: 'Kandidat yang disodorkan selesai dijumlah dalam {used} penjumlahan. Tidak ada kandidat yang butuh lebih dari {adds}.',
      pt: 'O candidato entregue soma em {used} somas. Nenhum candidato precisa de mais que {adds}.',
    },
    'caption.verdict': {
      en: 'The sum is {sum}, exactly the target {target}. Checking looked at one candidate and stopped.',
      ko: '합이 {sum} 으로 목표 {target} 과 같다. 확인은 후보 하나를 보고 멈춘다.',
      ja: '合計は {sum} で目標 {target} と等しい。検証は候補を一つ見て止まる。',
      zh: '和是 {sum}，正好是目标 {target}。验证看了一个候选就停下。',
      ar: 'المجموع {sum}، وهو الهدف {target} بالضبط. نظر التحقق في مرشح واحد ثم توقف.',
      es: 'La suma es {sum}, justo el objetivo {target}. Comprobar miró un candidato y se detuvo.',
      fr: 'La somme fait {sum}, exactement la cible {target}. La vérification a regardé un candidat et s’est arrêtée.',
      hi: 'योग {sum} है, ठीक लक्ष्य {target}। जाँच ने एक उम्मीदवार देखा और रुक गई।',
      id: 'Jumlahnya {sum}, persis target {target}. Memeriksa melihat satu kandidat lalu berhenti.',
      pt: 'A soma é {sum}, exatamente o alvo {target}. Conferir olhou um candidato e parou.',
    },
    'caption.count': {
      en: 'Nobody hands anything over now. Each extra number doubles the candidates, and there are {total}.',
      ko: '이번에는 건네주는 이가 없다. 수가 하나 늘 때마다 후보가 두 배가 되어 {total} 이다.',
      ja: '今度は渡してくれる人がいない。数が一つ増えるごとに候補は倍になり、{total} になる。',
      zh: '这次没有人递来什么。每多一个数，候选就翻倍，一共 {total} 个。',
      ar: 'لا أحد يناولك شيئًا الآن. كل رقم إضافي يضاعف المرشحين، وعددهم {total}.',
      es: 'Ahora nadie te entrega nada. Cada número extra duplica los candidatos, y hay {total}.',
      fr: 'Cette fois personne ne vous tend rien. Chaque nombre de plus double les candidats : il y en a {total}.',
      hi: 'अब कोई कुछ नहीं थमाता। हर अतिरिक्त संख्या उम्मीदवारों को दुगुना करती है, और वे {total} हैं।',
      id: 'Kali ini tidak ada yang menyodorkan apa pun. Setiap angka tambahan melipatduakan kandidat, dan jumlahnya {total}.',
      pt: 'Agora ninguém entrega nada. Cada número a mais dobra os candidatos, e são {total}.',
    },
    'caption.sweep': {
      en: 'Every candidate has to be looked at. So far: {seen} of {total}.',
      ko: '후보를 하나도 빠짐없이 들여다봐야 한다. 지금까지 {seen} / {total}.',
      ja: '候補を一つ残らず見なければならない。ここまで {seen} / {total}。',
      zh: '每个候选都得看一遍。到目前为止 {seen} / {total}。',
      ar: 'لا بد من النظر في كل مرشح. حتى الآن: {seen} من {total}.',
      es: 'Hay que mirar todos los candidatos. Hasta ahora: {seen} de {total}.',
      fr: 'Il faut regarder chaque candidat. Jusqu’ici : {seen} sur {total}.',
      hi: 'हर उम्मीदवार को देखना ही पड़ता है। अब तक: {seen} / {total}.',
      id: 'Setiap kandidat harus dilihat. Sejauh ini: {seen} dari {total}.',
      pt: 'É preciso olhar todo candidato. Até agora: {seen} de {total}.',
    },
    'caption.gap': {
      en: 'Checking stopped at one candidate. Finding had to look at all {total} — the same look, {total} times over.',
      ko: '확인은 후보 하나에서 멈췄다. 찾기는 {total} 을 다 봐야 했다 — 같은 들여다보기를 {total} 번.',
      ja: '検証は候補一つで止まった。探索は {total} をすべて見るほかない — 同じ一瞥を {total} 回。',
      zh: '验证停在一个候选上。搜索却要看遍 {total} 个 — 同样的一眼，重复 {total} 次。',
      ar: 'توقف التحقق عند مرشح واحد. أما البحث فكان عليه النظر في {total} كلها — النظرة نفسها، مكرّرة {total} مرة.',
      es: 'Comprobar se detuvo en un candidato. Buscar tuvo que mirar los {total} — la misma mirada, {total} veces.',
      fr: 'La vérification s’est arrêtée à un candidat. La recherche a dû tous les regarder, {total} — le même regard, {total} fois.',
      hi: 'जाँच एक उम्मीदवार पर रुक गई। खोज को पूरे {total} देखने पड़े — वही एक नज़र, {total} बार।',
      id: 'Memeriksa berhenti di satu kandidat. Mencari harus melihat seluruh {total} — tatapan yang sama, {total} kali.',
      pt: 'Conferir parou num candidato. Procurar teve de olhar todos os {total} — o mesmo olhar, {total} vezes.',
    },
    'caption.push': {
      en: 'Easy to check is not the same as easy to find. Push the size and watch only one side grow.',
      ko: '확인이 쉽다고 찾기가 쉬운 것은 아니다. 크기를 밀어 한쪽만 자라는 것을 보라.',
      ja: '確かめやすいことと見つけやすいことは別だ。大きさを動かして、片側だけが育つのを見よう。',
      zh: '容易验证不等于容易找到。推动规模，看只有一侧在长大。',
      ar: 'سهولة التحقق ليست سهولة الإيجاد. حرّك الحجم وانظر كيف ينمو جانب واحد فقط.',
      es: 'Fácil de comprobar no es lo mismo que fácil de encontrar. Mueve el tamaño y mira crecer solo un lado.',
      fr: 'Facile à vérifier n’est pas facile à trouver. Déplacez la taille et voyez un seul côté grandir.',
      hi: 'जाँचना आसान होना, खोजना आसान होना नहीं है। आकार बढ़ाइए और देखिए सिर्फ़ एक ओर बढ़ती है।',
      id: 'Mudah diperiksa tidak sama dengan mudah ditemukan. Geser ukurannya dan lihat hanya satu sisi yang tumbuh.',
      pt: 'Fácil de conferir não é o mesmo que fácil de encontrar. Mova o tamanho e veja só um lado crescer.',
    },
  },
};
