import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 같은 빛을 받는데 왜 빛 쪽에서 기운 면일수록 어두운가.
 *
 * 폭이 같은 빛줄기 하나가 차례로 기울어 가는 면 일곱에 떨어진다. 면이 빛에서 돌아설수록
 * 같은 빛줄기가 면의 더 긴 구간에 퍼지고, 그만큼 한 자리가 받는 밝기가 준다(max(0, cosθ)).
 * 면이 빛을 등지면 빛줄기는 앞면에 닿지 않고 밝기는 0 에 붙는다.
 */
export const normalDecidesBrightnessFacet: FacetJson = {
  id: 'facet:normalDecidesBrightness',
  title: {
    en: 'The normal decides brightness',
    ko: '법선이 밝기를 정한다',
    ja: '法線が明るさを決める',
    zh: '法线决定亮度',
    ar: 'العمود على السطح يحدد السطوع',
    es: 'La normal decide el brillo',
    fr: 'La normale décide de la luminosité',
    hi: 'अभिलंब चमक तय करता है',
    id: 'Normal menentukan kecerahan',
    pt: 'A normal decide o brilho',
  },
  description: {
    en: 'As a face turns away from the light, the same beam spreads over a longer stretch of it, so each spot on the face receives less.',
    ko: '면이 빛에서 돌아설수록 같은 빛줄기가 면의 더 긴 구간에 퍼져, 면의 한 자리가 받는 밝기가 준다.',
    ja: '面が光からそむくほど、同じ光の束が面のより長い区間に広がり、面の一点が受ける明るさは減る。',
    zh: '面越是背离光，同一束光就铺在面上越长的一段，面上每一点得到的亮度就越少。',
    ar: 'كلما ابتعد السطح عن الضوء امتدت الحزمة نفسها على جزء أطول منه، فتتلقى كل نقطة عليه سطوعًا أقل.',
    es: 'Cuanto más se aparta una cara de la luz, el mismo haz se extiende sobre un tramo más largo de ella, y cada punto recibe menos.',
    fr: 'Plus une face se détourne de la lumière, plus le même faisceau s’étale sur une portion longue de la face, et chaque point en reçoit moins.',
    hi: 'सतह जितनी प्रकाश से मुड़ती है, वही किरण-पुंज उसके उतने लंबे हिस्से पर फैलता है, और हर बिंदु को कम चमक मिलती है।',
    id: 'Makin jauh sebuah permukaan berpaling dari cahaya, berkas yang sama menyebar di bagian yang lebih panjang, sehingga tiap titik menerima lebih sedikit.',
    pt: 'Quanto mais uma face se afasta da luz, mais o mesmo feixe se espalha por um trecho longo dela, e cada ponto recebe menos.',
  },
  algorithm: 'module:normalDecidesBrightness',
  scene: 'module:normalDecidesBrightnessScene',
  initialData: {
    type: 'normal-decides-brightness',
    stepMs: 1400,
    light: {
      direction: [0, 1, 0],
      beamWidth: 1,
      intensity: 1,
    },
    faces: [
      { id: 'f1', tilt: 0 },
      { id: 'f2', tilt: 25 },
      { id: 'f3', tilt: 45 },
      { id: 'f4', tilt: 60 },
      { id: 'f5', tilt: 75 },
      { id: 'f6', tilt: 100 },
      { id: 'f7', tilt: 135 },
    ],
    material: { kd: 1 },
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Faces waiting below: {n} · Beam width: {w}',
      ko: '아래에서 기다리는 면: {n} · 빛줄기 폭: {w}',
      ja: '下で待つ面: {n} · 光の束の幅: {w}',
      zh: '下方等待的面: {n} · 光束宽度: {w}',
      ar: 'الأسطح المنتظرة في الأسفل: {n} · عرض الحزمة: {w}',
      es: 'Caras esperando abajo: {n} · Ancho del haz: {w}',
      fr: 'Faces en attente en dessous : {n} · Largeur du faisceau : {w}',
      hi: 'नीचे प्रतीक्षा करती सतहें: {n} · किरण-पुंज की चौड़ाई: {w}',
      id: 'Permukaan yang menunggu di bawah: {n} · Lebar berkas: {w}',
      pt: 'Faces esperando abaixo: {n} · Largura do feixe: {w}',
    },
    'caption.facing': {
      en: 'Tilt: {deg}°. The face looks straight at the light. Brightness: {b}',
      ko: '기울기: {deg}°. 면이 빛을 똑바로 본다. 밝기: {b}',
      ja: '傾き: {deg}°。面は光をまっすぐ向いている。明るさ: {b}',
      zh: '倾角: {deg}°。面正对着光。亮度: {b}',
      ar: 'الميل: {deg}°. السطح يواجه الضوء مباشرة. السطوع: {b}',
      es: 'Inclinación: {deg}°. La cara mira de frente a la luz. Brillo: {b}',
      fr: 'Inclinaison : {deg}°. La face regarde droit vers la lumière. Luminosité : {b}',
      hi: 'झुकाव: {deg}°. सतह सीधे प्रकाश की ओर है। चमक: {b}',
      id: 'Kemiringan: {deg}°. Permukaan menghadap lurus ke cahaya. Kecerahan: {b}',
      pt: 'Inclinação: {deg}°. A face olha direto para a luz. Brilho: {b}',
    },
    'caption.tilted': {
      en: 'Tilt: {deg}°. The same beam lies along a longer stretch of the face. Brightness: {b}',
      ko: '기울기: {deg}°. 같은 빛줄기가 면의 더 긴 구간에 눕는다. 밝기: {b}',
      ja: '傾き: {deg}°。同じ光の束が面のより長い区間に横たわる。明るさ: {b}',
      zh: '倾角: {deg}°。同一束光铺在面上更长的一段。亮度: {b}',
      ar: 'الميل: {deg}°. الحزمة نفسها تمتد على جزء أطول من السطح. السطوع: {b}',
      es: 'Inclinación: {deg}°. El mismo haz se tiende sobre un tramo más largo de la cara. Brillo: {b}',
      fr: 'Inclinaison : {deg}°. Le même faisceau s’étend sur une portion plus longue de la face. Luminosité : {b}',
      hi: 'झुकाव: {deg}°. वही किरण-पुंज सतह के अधिक लंबे हिस्से पर फैलता है। चमक: {b}',
      id: 'Kemiringan: {deg}°. Berkas yang sama terbentang di bagian permukaan yang lebih panjang. Kecerahan: {b}',
      pt: 'Inclinação: {deg}°. O mesmo feixe se estende por um trecho mais longo da face. Brilho: {b}',
    },
    'caption.away': {
      en: 'Tilt: {deg}°. The face turns its back on the light; the beam never reaches its front. Brightness: {b}',
      ko: '기울기: {deg}°. 면이 빛을 등져 빛줄기가 앞면에 닿지 않는다. 밝기: {b}',
      ja: '傾き: {deg}°。面は光に背を向け、光の束は表側に届かない。明るさ: {b}',
      zh: '倾角: {deg}°。面背对着光，光束照不到正面。亮度: {b}',
      ar: 'الميل: {deg}°. السطح يدير ظهره للضوء، فلا تصل الحزمة إلى وجهه. السطوع: {b}',
      es: 'Inclinación: {deg}°. La cara da la espalda a la luz; el haz no llega a su frente. Brillo: {b}',
      fr: 'Inclinaison : {deg}°. La face tourne le dos à la lumière ; le faisceau n’atteint pas son recto. Luminosité : {b}',
      hi: 'झुकाव: {deg}°. सतह प्रकाश की ओर पीठ करती है; किरण-पुंज उसके सामने वाले भाग तक नहीं पहुँचता। चमक: {b}',
      id: 'Kemiringan: {deg}°. Permukaan membelakangi cahaya; berkas tidak mencapai sisi depannya. Kecerahan: {b}',
      pt: 'Inclinação: {deg}°. A face dá as costas à luz; o feixe não chega à sua frente. Brilho: {b}',
    },
    'label.light': {
      en: 'Light',
      ko: '빛',
      ja: '光',
      zh: '光',
      ar: 'الضوء',
      es: 'Luz',
      fr: 'Lumière',
      hi: 'प्रकाश',
      id: 'Cahaya',
      pt: 'Luz',
    },
    'label.width': {
      en: 'Width: {w}',
      ko: '폭: {w}',
      ja: '幅: {w}',
      zh: '宽度: {w}',
      ar: 'العرض: {w}',
      es: 'Ancho: {w}',
      fr: 'Largeur : {w}',
      hi: 'चौड़ाई: {w}',
      id: 'Lebar: {w}',
      pt: 'Largura: {w}',
    },
    'label.normal': {
      en: 'Normal',
      ko: '법선',
      ja: '法線',
      zh: '法线',
      ar: 'العمود',
      es: 'Normal',
      fr: 'Normale',
      hi: 'अभिलंब',
      id: 'Normal',
      pt: 'Normal',
    },
    'label.deg': {
      en: '{deg}°',
      ko: '{deg}°',
      ja: '{deg}°',
      zh: '{deg}°',
      ar: '{deg}°',
      es: '{deg}°',
      fr: '{deg}°',
      hi: '{deg}°',
      id: '{deg}°',
      pt: '{deg}°',
    },
    'label.brightness': {
      en: 'Brightness',
      ko: '밝기',
      ja: '明るさ',
      zh: '亮度',
      ar: 'السطوع',
      es: 'Brillo',
      fr: 'Luminosité',
      hi: 'चमक',
      id: 'Kecerahan',
      pt: 'Brilho',
    },
  },
  blocks: {
    stage: { type: 'normal-decides-brightness-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
