/**
 * @piece 한계 기반 가지치기.
 *
 * 답하는 질문 하나 — "아무 조건도 어기지 않은 갈래를 왜 미리 접는가?"
 * 갈래마다 최선을 내다본 값(한계)을 재고, 그것이 지금까지의 최고를 못 넘으면
 * 그 아래는 볼 것이 없다. 최고가 일찍 높아질수록 더 많이 잘린다.
 *
 * 조각이므로 header · metrics · code-view · layout 을 두지 않는다 (S-piece).
 */

import { CONTROL, type FacetJson } from '@ffacet/core/runtime';

export const boundAndCutFacet: FacetJson = {
  id: 'facet:boundAndCut',
  title: {
    en: 'Bound and cut',
    ko: '한계 기반 가지치기',
    ja: '限界で枝を刈る',
    zh: '界限剪枝',
    ar: 'الحد والتقليم',
    es: 'Cota y poda',
    fr: 'Borne et élagage',
    hi: 'सीमा और छँटाई',
    id: 'Batas dan pangkas',
    pt: 'Limite e poda',
  },
  description: {
    en: 'A branch whose best possible outcome cannot beat the current best is cut before it is explored.',
    ko: '최선을 내다본 값이 지금 최고보다 못하면 그 아래는 볼 것도 없다.',
    ja: '最善を見積もっても今の最高に届かない枝は、たどる前に刈る。',
    zh: '一个分支即使发挥到最好也超不过当前最优，就在展开之前剪掉。',
    ar: 'الفرع الذي لا يتجاوز أفضل ما وصلنا إليه حتى في أحسن الأحوال يُقلَّم قبل استكشافه.',
    es: 'Una rama cuyo mejor resultado posible no supera al mejor actual se poda antes de explorarla.',
    fr: "Une branche dont le meilleur résultat possible ne dépasse pas le meilleur actuel est élaguée avant d'être explorée.",
    hi: 'जिस शाखा का सर्वोत्तम संभव परिणाम भी मौजूदा सर्वोत्तम को नहीं हरा सकता, उसे खोजने से पहले ही काट दिया जाता है।',
    id: 'Cabang yang hasil terbaiknya pun tak bisa melampaui yang terbaik saat ini dipangkas sebelum ditelusuri.',
    pt: 'Um ramo cujo melhor resultado possível não supera o melhor atual é podado antes de ser explorado.',
  },
  algorithm: 'module:boundAndCut',
  projector: 'module:boundAndCutProjector',
  initialData: {
    type: 'bound-and-cut',
    capacity: 5,
    items: [
      { id: 'A', weight: 2, value: 12 },
      { id: 'B', weight: 3, value: 15 },
      { id: 'C', weight: 4, value: 16 },
    ],
    stepMs: 850,
  },
  blocks: {
    stage: { type: 'bound-and-cut-stage' },
    controls: {
      type: 'control-bar',
      controls: [CONTROL.replay, CONTROL.advance],
    },
  },
  messages: {
    'label.best': {
      en: 'Best',
      ko: '최고',
      ja: '最高',
      zh: '最优',
      ar: 'الأفضل',
      es: 'Mejor',
      fr: 'Meilleur',
      hi: 'सर्वोत्तम',
      id: 'Terbaik',
      pt: 'Melhor',
    },
    'label.capacity': {
      en: 'Capacity {c}',
      ko: '한도 {c}',
      ja: '容量 {c}',
      zh: '容量 {c}',
      ar: 'السعة {c}',
      es: 'Capacidad {c}',
      fr: 'Capacité {c}',
      hi: 'क्षमता {c}',
      id: 'Kapasitas {c}',
      pt: 'Capacidade {c}',
    },
    'label.itemSpec': {
      en: 'w {w} · v {v}',
      ko: '무게 {w} · 값 {v}',
      ja: '重さ {w} · 価値 {v}',
      zh: '重 {w} · 值 {v}',
      ar: 'وزن {w} · قيمة {v}',
      es: 'p {w} · v {v}',
      fr: 'p {w} · v {v}',
      hi: 'भार {w} · मूल्य {v}',
      id: 'b {w} · n {v}',
      pt: 'p {w} · v {v}',
    },

    'caption.root': {
      en: 'If items could be split, at most {bound}',
      ko: '쪼갤 수 있다 치면 많아야 {bound}',
      ja: '分割できるとしても、せいぜい {bound}',
      zh: '就算物品可以切分，最多也只有 {bound}',
      ar: 'لو أمكن تقسيم الأغراض، فأقصى ما نصل إليه {bound}',
      es: 'Si los objetos se pudieran partir, como mucho {bound}',
      fr: "Si l'on pouvait couper les objets, au plus {bound}",
      hi: 'अगर वस्तुएँ बाँटी जा सकतीं, तो अधिक से अधिक {bound}',
      id: 'Andai barang bisa dipotong, paling banyak {bound}',
      pt: 'Se os itens pudessem ser partidos, no máximo {bound}',
    },
    'caption.measure': {
      en: 'This branch tops out at {bound}',
      ko: '이 갈래는 아무리 잘해도 {bound}',
      ja: 'この枝はどうがんばっても {bound}',
      zh: '这个分支最高也就到 {bound}',
      ar: 'هذا الفرع لا يتجاوز {bound}',
      es: 'Esta rama no pasa de {bound}',
      fr: 'Cette branche plafonne à {bound}',
      hi: 'यह शाखा अधिक से अधिक {bound} तक जाती है',
      id: 'Cabang ini mentok di {bound}',
      pt: 'Este ramo não passa de {bound}',
    },
    'caption.settled': {
      en: 'Every item is decided — value {value}',
      ko: '물건이 모두 정해졌다 — 값 {value}',
      ja: '品物がすべて決まった — 価値 {value}',
      zh: '所有物品都已定下 — 价值 {value}',
      ar: 'تقرَّر مصير كل غرض — القيمة {value}',
      es: 'Todos los objetos están decididos: valor {value}',
      fr: 'Tous les objets sont décidés — valeur {value}',
      hi: 'हर वस्तु तय हो गई — मूल्य {value}',
      id: 'Semua barang sudah diputuskan — nilai {value}',
      pt: 'Todos os itens estão decididos — valor {value}',
    },
    'caption.newBest': {
      en: 'New best: {best}',
      ko: '새 최고 {best} — 자르는 기준이 올라간다',
      ja: '新しい最高は {best}',
      zh: '新的最优：{best}',
      ar: 'أفضل جديد: {best}',
      es: 'Nuevo mejor: {best}',
      fr: 'Nouveau meilleur : {best}',
      hi: 'नया सर्वोत्तम: {best}',
      id: 'Terbaik baru: {best}',
      pt: 'Novo melhor: {best}',
    },
    // 숫자 뒤에 조사를 붙이지 않는다 — 읽는 소리에 따라 은/는·이/가가 갈려
    // {값} 자리에 무엇이 오든 맞는 문장이 되게 어순을 잡는다.
    'caption.cut': {
      en: '{bound} cannot beat {best} — cut this branch',
      ko: '한계 {bound}, 최고 {best} — 못 넘으니 이 갈래를 자른다',
      ja: '{bound} では {best} に届かない — この枝を刈る',
      zh: '{bound} 超不过 {best} — 剪掉这个分支',
      ar: '{bound} لا يتجاوز {best} — قلّم هذا الفرع',
      es: '{bound} no supera a {best}: se poda esta rama',
      fr: '{bound} ne dépasse pas {best} — on élague cette branche',
      hi: '{bound} {best} को नहीं हरा सकता — यह शाखा काट दें',
      id: '{bound} tak bisa melampaui {best} — pangkas cabang ini',
      pt: '{bound} não supera {best} — poda-se este ramo',
    },
    'caption.done': {
      en: 'Cut {cuts} branches and the best is still {best}',
      ko: '자르기 {cuts}번 — 그래도 최적은 {best}',
      ja: '{cuts} 本の枝を刈っても、最適は {best} のまま',
      zh: '剪掉了 {cuts} 个分支，最优仍然是 {best}',
      ar: 'قُلِّمت {cuts} فروع والأفضل ما زال {best}',
      es: 'Se podaron {cuts} ramas y el mejor sigue siendo {best}',
      fr: '{cuts} branches élaguées et le meilleur reste {best}',
      hi: '{cuts} शाखाएँ काटीं और सर्वोत्तम अब भी {best} है',
      id: 'Memangkas {cuts} cabang dan yang terbaik tetap {best}',
      pt: 'Podados {cuts} ramos e o melhor continua {best}',
    },
  },
};
