import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 디스크 여기저기 흩어진 블록들이 한 파일이고 그 차례가 무엇인지를 무엇이 아는가 — inode 의 칸 차례다.
 */
export const inodePointsBlocksFacet: FacetJson = {
  id: 'facet:inodePointsBlocks',
  title: {
    en: 'The inode holds the order',
    ko: 'inode 가 차례를 쥔다',
    ja: 'inode が順番を握る',
    zh: 'inode 掌握顺序',
    ar: 'الـ inode يحفظ الترتيب',
    es: 'El inode guarda el orden',
    fr: 'L’inode tient l’ordre',
    hi: 'क्रम inode के पास है',
    id: 'inode memegang urutan',
    pt: 'O inode guarda a ordem',
  },
  description: {
    en: 'Following the inode slot by slot gathers blocks scattered across the disk into one file.',
    ko: 'inode 의 칸을 차례로 따라가면 디스크 곳곳에 흩어진 블록이 한 파일로 모인다.',
    ja: 'inode のスロットを順にたどると、ディスクに散らばったブロックが一つのファイルにまとまる。',
    zh: '按顺序沿着 inode 的槽位走，散落在磁盘各处的块就汇成一个文件。',
    ar: 'باتباع خانات inode واحدة تلو الأخرى تتجمع الكتل المتناثرة على القرص في ملف واحد.',
    es: 'Siguiendo las ranuras del inode una a una, los bloques dispersos por el disco se reúnen en un solo archivo.',
    fr: 'En suivant les cases de l’inode une à une, les blocs éparpillés sur le disque se rassemblent en un seul fichier.',
    hi: 'inode के खानों को क्रम से देखने पर डिस्क पर बिखरे ब्लॉक एक फ़ाइल में जुड़ जाते हैं।',
    id: 'Dengan mengikuti slot inode satu per satu, blok yang tersebar di disk terkumpul menjadi satu berkas.',
    pt: 'Seguindo as posições do inode uma a uma, os blocos espalhados pelo disco se juntam num só arquivo.',
  },
  algorithm: 'module:inodePointsBlocks',
  scene: 'module:inodePointsBlocksScene',
  initialData: {
    type: 'inode-points-blocks',
    stepMs: 1300,
    diskSize: 16,
    otherBlocks: [2, 4, 7, 8, 12, 13],
    file: 'kernel',
    slots: [11, 3, 14, 6, 9, 1],
    contents: [
      { block: 11, letter: 'K' },
      { block: 3, letter: 'E' },
      { block: 14, letter: 'R' },
      { block: 6, letter: 'N' },
      { block: 9, letter: 'E' },
      { block: 1, letter: 'L' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.disk': {
      en: 'Disk blocks',
      ko: '디스크 블록',
      ja: 'ディスクブロック',
      zh: '磁盘块',
      ar: 'كتل القرص',
      es: 'Bloques del disco',
      fr: 'Blocs du disque',
      hi: 'डिस्क ब्लॉक',
      id: 'Blok disk',
      pt: 'Blocos do disco',
    },
    'legend.other': {
      en: 'Other file',
      ko: '다른 파일',
      ja: '別のファイル',
      zh: '其他文件',
      ar: 'ملف آخر',
      es: 'Otro archivo',
      fr: 'Autre fichier',
      hi: 'दूसरी फ़ाइल',
      id: 'Berkas lain',
      pt: 'Outro arquivo',
    },
    'legend.free': {
      en: 'Free',
      ko: '빈 블록',
      ja: '空き',
      zh: '空闲',
      ar: 'فارغة',
      es: 'Libre',
      fr: 'Libre',
      hi: 'खाली',
      id: 'Kosong',
      pt: 'Livre',
    },
    'label.inode': {
      en: 'inode · {file}',
      ko: 'inode · {file}',
      ja: 'inode · {file}',
      zh: 'inode · {file}',
      ar: 'inode · {file}',
      es: 'inode · {file}',
      fr: 'inode · {file}',
      hi: 'inode · {file}',
      id: 'inode · {file}',
      pt: 'inode · {file}',
    },
    'label.contents': {
      en: 'File contents',
      ko: '파일 내용',
      ja: 'ファイルの内容',
      zh: '文件内容',
      ar: 'محتوى الملف',
      es: 'Contenido del archivo',
      fr: 'Contenu du fichier',
      hi: 'फ़ाइल की सामग्री',
      id: 'Isi berkas',
      pt: 'Conteúdo do arquivo',
    },
    'label.read': {
      en: 'Slots read: {n}/{total}',
      ko: '읽은 칸: {n}/{total}',
      ja: '読んだスロット: {n}/{total}',
      zh: '已读槽位：{n}/{total}',
      ar: 'الخانات المقروءة: {n}/{total}',
      es: 'Ranuras leídas: {n}/{total}',
      fr: 'Cases lues : {n}/{total}',
      hi: 'पढ़े गए खाने: {n}/{total}',
      id: 'Slot terbaca: {n}/{total}',
      pt: 'Posições lidas: {n}/{total}',
    },
    'caption.show': {
      en: 'To read the file, follow the inode slot by slot.',
      ko: '파일을 읽으려면 inode 의 칸을 차례로 따라간다.',
      ja: 'ファイルを読むには inode のスロットを順にたどる。',
      zh: '读取文件时，按顺序沿着 inode 的槽位走。',
      ar: 'لقراءة الملف، اتبع خانات inode واحدة تلو الأخرى.',
      es: 'Para leer el archivo, se siguen las ranuras del inode una a una.',
      fr: 'Pour lire le fichier, on suit les cases de l’inode une à une.',
      hi: 'फ़ाइल पढ़ने के लिए inode के खानों को क्रम से देखा जाता है।',
      id: 'Untuk membaca berkas, ikuti slot inode satu per satu.',
      pt: 'Para ler o arquivo, seguem-se as posições do inode uma a uma.',
    },
    'caption.read': {
      en: 'Slot {slot} → block {block} · {letter}',
      ko: '칸 {slot} → 블록 {block} · {letter}',
      ja: 'スロット {slot} → ブロック {block} · {letter}',
      zh: '槽位 {slot} → 块 {block} · {letter}',
      ar: 'الخانة {slot} → الكتلة {block} · {letter}',
      es: 'Ranura {slot} → bloque {block} · {letter}',
      fr: 'Case {slot} → bloc {block} · {letter}',
      hi: 'खाना {slot} → ब्लॉक {block} · {letter}',
      id: 'Slot {slot} → blok {block} · {letter}',
      pt: 'Posição {slot} → bloco {block} · {letter}',
    },
  },
  blocks: {
    stage: { type: 'inode-points-blocks-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
