/**
 * @piece
 * FIFO 는 누구를 내보내는가 — 방금 쓴 페이지라도 내보내는가.
 *
 * 값은 모두 예로 정한 것이다 (프레임 3, 참조 4 · 8 · 3 · 4 · 6 · 4).
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const evictOldestFacet: FacetJson = {
  id: 'facet:evictOldest',
  title: {
    en: 'FIFO evicts the oldest arrival',
    ko: 'FIFO 는 가장 먼저 들어온 것을 내보낸다',
    ja: 'FIFO は最初に入ったものを追い出す',
    zh: 'FIFO 淘汰最早进入的页',
    ar: 'FIFO يطرد أقدم الواصلين',
    es: 'FIFO expulsa la página que llegó primero',
    fr: 'FIFO évince la page arrivée la première',
    hi: 'FIFO सबसे पहले आए पेज को निकालता है',
    id: 'FIFO mengeluarkan halaman yang paling awal masuk',
    pt: 'FIFO expulsa a página que chegou primeiro',
  },
  description: {
    en: 'FIFO looks only at arrival order, not at use. A page used one step ago still falls out first and is loaded right back.',
    ko: 'FIFO 는 들어온 차례만 보고 쓰였는지는 보지 않는다. 한 걸음 전에 쓰인 페이지도 먼저 밀려 나가고 곧바로 다시 불려 온다.',
    ja: 'FIFO は入った順番だけを見て、使われたかどうかは見ない。一つ前に使われたページも先に押し出され、すぐに呼び戻される。',
    zh: 'FIFO 只看进入顺序，不看是否被使用。上一步刚用过的页也会先被挤出，随即又被调回。',
    ar: 'لا ينظر FIFO إلا إلى ترتيب الوصول، لا إلى الاستخدام. الصفحة المستخدمة قبل خطوة واحدة تُطرد أولًا ثم تُستدعى فورًا من جديد.',
    es: 'FIFO solo mira el orden de llegada, no el uso. Una página usada un paso antes sale primero y vuelve a cargarse enseguida.',
    fr: "FIFO ne regarde que l'ordre d'arrivée, pas l'usage. Une page utilisée un pas plus tôt sort la première et est aussitôt rechargée.",
    hi: 'FIFO केवल आने का क्रम देखता है, उपयोग नहीं। एक कदम पहले उपयोग हुआ पेज भी पहले बाहर होता है और तुरंत वापस लाया जाता है।',
    id: 'FIFO hanya melihat urutan masuk, bukan pemakaian. Halaman yang dipakai satu langkah sebelumnya tetap keluar lebih dulu lalu segera dimuat lagi.',
    pt: 'FIFO só olha a ordem de chegada, não o uso. Uma página usada um passo antes sai primeiro e é logo carregada de novo.',
  },
  algorithm: 'module:evictOldest',
  scene: 'module:evictOldestScene',
  initialData: {
    type: 'evict-oldest',
    frames: 3,
    refs: [4, 8, 3, 4, 6, 4],
    stepMs: 1500,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Frames: {n} · all empty',
      ko: '프레임 칸: {n} · 모두 비어 있음',
      ja: 'フレーム数: {n} · すべて空き',
      zh: '帧数: {n} · 全部空闲',
      ar: 'الإطارات: {n} · كلها فارغة',
      es: 'Marcos: {n} · todos vacíos',
      fr: 'Cadres : {n} · tous vides',
      hi: 'फ़्रेम: {n} · सभी खाली',
      id: 'Bingkai: {n} · semua kosong',
      pt: 'Quadros: {n} · todos vazios',
    },
    'caption.hit': {
      en: 'Reference {t}: page {page} · hit',
      ko: '참조 {t}: 페이지 {page} · 적중',
      ja: '参照 {t}: ページ {page} · ヒット',
      zh: '引用 {t}: 页 {page} · 命中',
      ar: 'المرجع {t}: الصفحة {page} · إصابة',
      es: 'Referencia {t}: página {page} · acierto',
      fr: 'Référence {t} : page {page} · succès',
      hi: 'संदर्भ {t}: पेज {page} · हिट',
      id: 'Referensi {t}: halaman {page} · hit',
      pt: 'Referência {t}: página {page} · acerto',
    },
    'detail.hit': {
      en: 'Place in line: {pos} of {n} · last used: {used}',
      ko: '줄에서 자리: {pos} / {n} · 마지막 쓰임: {used}',
      ja: '列での位置: {pos} / {n} · 最後の使用: {used}',
      zh: '队列位置: {pos} / {n} · 最近使用: {used}',
      ar: 'الموضع في الصف: {pos} من {n} · آخر استخدام: {used}',
      es: 'Puesto en la fila: {pos} de {n} · último uso: {used}',
      fr: 'Place dans la file : {pos} sur {n} · dernier usage : {used}',
      hi: 'कतार में स्थान: {pos} / {n} · अंतिम उपयोग: {used}',
      id: 'Posisi dalam antrean: {pos} dari {n} · terakhir dipakai: {used}',
      pt: 'Posição na fila: {pos} de {n} · último uso: {used}',
    },
    'caption.fault': {
      en: 'Reference {t}: page {page} · fault',
      ko: '참조 {t}: 페이지 {page} · 폴트',
      ja: '参照 {t}: ページ {page} · フォールト',
      zh: '引用 {t}: 页 {page} · 缺页',
      ar: 'المرجع {t}: الصفحة {page} · خطأ صفحة',
      es: 'Referencia {t}: página {page} · fallo',
      fr: 'Référence {t} : page {page} · défaut',
      hi: 'संदर्भ {t}: पेज {page} · फ़ॉल्ट',
      id: 'Referensi {t}: halaman {page} · fault',
      pt: 'Referência {t}: página {page} · falta',
    },
    'caption.faultAgain': {
      en: 'Reference {t}: page {page} · fault · evicted at {out}',
      ko: '참조 {t}: 페이지 {page} · 폴트 · 내보낸 때: {out}',
      ja: '参照 {t}: ページ {page} · フォールト · 追い出した時点: {out}',
      zh: '引用 {t}: 页 {page} · 缺页 · 被淘汰于: {out}',
      ar: 'المرجع {t}: الصفحة {page} · خطأ صفحة · طُردت عند: {out}',
      es: 'Referencia {t}: página {page} · fallo · expulsada en: {out}',
      fr: 'Référence {t} : page {page} · défaut · évincée à : {out}',
      hi: 'संदर्भ {t}: पेज {page} · फ़ॉल्ट · निकाला गया: {out}',
      id: 'Referensi {t}: halaman {page} · fault · dikeluarkan pada: {out}',
      pt: 'Referência {t}: página {page} · falta · expulsa em: {out}',
    },
    'detail.free': {
      en: 'Into free frame {frame} · end of the line',
      ko: '빈 프레임 {frame} 에 올림 · 줄의 맨 끝',
      ja: '空きフレーム {frame} へ · 列の末尾',
      zh: '放入空闲帧 {frame} · 排到队尾',
      ar: 'إلى الإطار الفارغ {frame} · آخر الصف',
      es: 'Al marco libre {frame} · final de la fila',
      fr: 'Dans le cadre libre {frame} · fin de la file',
      hi: 'खाली फ़्रेम {frame} में · कतार के अंत में',
      id: 'Ke bingkai kosong {frame} · ujung antrean',
      pt: 'No quadro livre {frame} · fim da fila',
    },
    'detail.evict': {
      en: 'Out: page {victim}, first in line, last used {used} · into frame {frame}',
      ko: '나감: 줄 맨 앞의 페이지 {victim} · 마지막 쓰임: {used} · 새 페이지는 프레임 {frame} 에',
      ja: '退出: 列の先頭のページ {victim} · 最後の使用: {used} · 新しいページはフレーム {frame} へ',
      zh: '淘汰: 队首的页 {victim} · 最近使用: {used} · 新页放入帧 {frame}',
      ar: 'خرجت: الصفحة {victim} أول الصف · آخر استخدام: {used} · إلى الإطار {frame}',
      es: 'Sale: página {victim}, primera de la fila, último uso {used} · al marco {frame}',
      fr: 'Sort : page {victim}, première de la file, dernier usage {used} · dans le cadre {frame}',
      hi: 'बाहर: कतार में पहला पेज {victim} · अंतिम उपयोग: {used} · फ़्रेम {frame} में',
      id: 'Keluar: halaman {victim}, terdepan di antrean, terakhir dipakai {used} · ke bingkai {frame}',
      pt: 'Sai: página {victim}, primeira da fila, último uso {used} · no quadro {frame}',
    },
    'label.front': {
      en: 'First in · out next',
      ko: '맨 처음 · 다음에 나감',
      ja: '最初に入った · 次に出る',
      zh: '最先进入 · 下一个淘汰',
      ar: 'الأول وصولًا · التالي خروجًا',
      es: 'Primera en entrar · sale después',
      fr: 'Première entrée · sort ensuite',
      hi: 'सबसे पहले आया · अगला बाहर',
      id: 'Pertama masuk · keluar berikutnya',
      pt: 'Primeira a entrar · sai a seguir',
    },
    'label.back': {
      en: 'New pages join here',
      ko: '새 페이지는 여기로',
      ja: '新しいページはここへ',
      zh: '新页从这里加入',
      ar: 'الصفحات الجديدة تنضم هنا',
      es: 'Las páginas nuevas entran aquí',
      fr: 'Les nouvelles pages entrent ici',
      hi: 'नए पेज यहाँ जुड़ते हैं',
      id: 'Halaman baru masuk di sini',
      pt: 'Páginas novas entram aqui',
    },
    'label.order': {
      en: 'Arrival order',
      ko: '들어온 차례',
      ja: '入った順番',
      zh: '进入顺序',
      ar: 'ترتيب الوصول',
      es: 'Orden de llegada',
      fr: "Ordre d'arrivée",
      hi: 'आने का क्रम',
      id: 'Urutan masuk',
      pt: 'Ordem de chegada',
    },
    'label.evicted': {
      en: 'Evicted',
      ko: '내보낸 페이지',
      ja: '追い出したページ',
      zh: '已淘汰的页',
      ar: 'صفحات مطرودة',
      es: 'Expulsadas',
      fr: 'Évincées',
      hi: 'निकाले गए पेज',
      id: 'Dikeluarkan',
      pt: 'Expulsas',
    },
    'label.frame': {
      en: 'Frame {f}',
      ko: '프레임 {f}',
      ja: 'フレーム {f}',
      zh: '帧 {f}',
      ar: 'الإطار {f}',
      es: 'Marco {f}',
      fr: 'Cadre {f}',
      hi: 'फ़्रेम {f}',
      id: 'Bingkai {f}',
      pt: 'Quadro {f}',
    },
    'label.in': {
      en: 'In: {t}',
      ko: '들어옴: {t}',
      ja: '入った: {t}',
      zh: '进入: {t}',
      ar: 'دخلت: {t}',
      es: 'Entró: {t}',
      fr: 'Entrée : {t}',
      hi: 'आया: {t}',
      id: 'Masuk: {t}',
      pt: 'Entrou: {t}',
    },
    'label.used': {
      en: 'Used: {t}',
      ko: '쓰임: {t}',
      ja: '使用: {t}',
      zh: '使用: {t}',
      ar: 'استُخدمت: {t}',
      es: 'Usada: {t}',
      fr: 'Utilisée : {t}',
      hi: 'उपयोग: {t}',
      id: 'Dipakai: {t}',
      pt: 'Usada: {t}',
    },
    'label.out': {
      en: 'Out: {t}',
      ko: '나감: {t}',
      ja: '退出: {t}',
      zh: '淘汰: {t}',
      ar: 'خرجت: {t}',
      es: 'Salió: {t}',
      fr: 'Sortie : {t}',
      hi: 'बाहर: {t}',
      id: 'Keluar: {t}',
      pt: 'Saiu: {t}',
    },
    'label.tick': {
      en: 't{n}',
      ko: 't{n}',
      ja: 't{n}',
      zh: 't{n}',
      ar: 't{n}',
      es: 't{n}',
      fr: 't{n}',
      hi: 't{n}',
      id: 't{n}',
      pt: 't{n}',
    },
    'label.faults': {
      en: 'Faults: {n}',
      ko: '폴트: {n}',
      ja: 'フォールト: {n}',
      zh: '缺页: {n}',
      ar: 'أخطاء الصفحة: {n}',
      es: 'Fallos: {n}',
      fr: 'Défauts : {n}',
      hi: 'फ़ॉल्ट: {n}',
      id: 'Fault: {n}',
      pt: 'Faltas: {n}',
    },
    'label.hits': {
      en: 'Hits: {n}',
      ko: '적중: {n}',
      ja: 'ヒット: {n}',
      zh: '命中: {n}',
      ar: 'الإصابات: {n}',
      es: 'Aciertos: {n}',
      fr: 'Succès : {n}',
      hi: 'हिट: {n}',
      id: 'Hit: {n}',
      pt: 'Acertos: {n}',
    },
  },
  blocks: {
    stage: { type: 'evict-oldest-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
