import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 줄 몇 개를 다른 자리로 옮기기만 했을 때, 줄 단위 diff 는 그것을 무엇으로 적는가.
 */
export const moveLooksLikeRewriteFacet: FacetJson = {
  id: 'facet:moveLooksLikeRewrite',
  title: {
    en: 'A move looks like a rewrite',
    ko: '옮김은 다시 쓴 것처럼 보인다',
    ja: '移動は書き直しに見える',
    zh: '移动看起来像重写',
    ar: 'النقل يبدو كإعادة كتابة',
    es: 'Mover parece reescribir',
    fr: 'Un déplacement ressemble à une réécriture',
    hi: 'खिसकाना दोबारा लिखने जैसा दिखता है',
    id: 'Memindah tampak seperti menulis ulang',
    pt: 'Mover parece reescrever',
  },
  description: {
    en: 'Move a block of lines without changing a character: a person sees one move, a line-by-line diff sees deletions and insertions.',
    ko: '글자 하나 바꾸지 않고 줄 덩이를 옮긴다. 사람은 옮김 한 번으로 보고, 줄 단위 diff 는 지움과 넣음으로 적는다.',
    ja: '一文字も変えずに行のまとまりを移す。人は一回の移動と見て、行単位の diff は削除と挿入として記す。',
    zh: '不改一个字地移动一段行。人看到的是一次移动，逐行 diff 记下的是删除和插入。',
    ar: 'انقل كتلة أسطر دون تغيير حرف: يرى الإنسان نقلة واحدة، ويرى diff السطري حذفًا وإدراجًا.',
    es: 'Mueve un bloque de líneas sin cambiar un carácter: una persona ve un movimiento, un diff por líneas ve borrados e inserciones.',
    fr: 'Déplacez un bloc de lignes sans changer un caractère : une personne voit un déplacement, un diff ligne à ligne voit des suppressions et des insertions.',
    hi: 'एक भी अक्षर बदले बिना पंक्तियों का खंड खिसकाइए: इंसान को एक खिसकाव दिखता है, पंक्ति-दर-पंक्ति diff को हटाना और जोड़ना।',
    id: 'Pindahkan satu blok baris tanpa mengubah satu huruf pun: orang melihat satu pemindahan, diff per baris melihat penghapusan dan penyisipan.',
    pt: 'Mova um bloco de linhas sem mudar um caractere: uma pessoa vê um movimento, um diff por linhas vê remoções e inserções.',
  },
  algorithm: 'module:moveLooksLikeRewrite',
  scene: 'module:moveLooksLikeRewriteScene',
  initialData: {
    type: 'move-looks-like-rewrite',
    stepMs: 1400,
    a: ['let data = load()', 'let n = count(data)', 'show n', 'function load()', '    return read()'],
    b: ['function load()', '    return read()', 'let data = load()', 'let n = count(data)', 'show n'],
    moves: [{ from: 3, count: 2, to: 0 }],
    marks: { keep: ' ', del: '-', ins: '+' },
  },
  shuffleOnReset: false,
  messages: {
    'label.a': {
      en: 'Before the move',
      ko: '옮기기 전',
      ja: '移動前',
      zh: '移动前',
      ar: 'قبل النقل',
      es: 'Antes de mover',
      fr: 'Avant le déplacement',
      hi: 'खिसकाने से पहले',
      id: 'Sebelum dipindah',
      pt: 'Antes de mover',
    },
    'label.b': {
      en: 'After the move',
      ko: '옮긴 뒤',
      ja: '移動後',
      zh: '移动后',
      ar: 'بعد النقل',
      es: 'Después de mover',
      fr: 'Après le déplacement',
      hi: 'खिसकाने के बाद',
      id: 'Sesudah dipindah',
      pt: 'Depois de mover',
    },
    'label.human': {
      en: 'Human eye',
      ko: '사람의 눈',
      ja: '人の目',
      zh: '人的眼光',
      ar: 'عين الإنسان',
      es: 'Ojo humano',
      fr: 'Œil humain',
      hi: 'इंसान की नज़र',
      id: 'Mata manusia',
      pt: 'Olho humano',
    },
    'label.line': {
      en: 'Line eye',
      ko: '줄의 눈',
      ja: '行の目',
      zh: '逐行的眼光',
      ar: 'عين الأسطر',
      es: 'Ojo de líneas',
      fr: 'Œil ligne à ligne',
      hi: 'पंक्ति की नज़र',
      id: 'Mata baris',
      pt: 'Olho de linhas',
    },
    'count.moves': {
      en: 'Moves: {n}',
      ko: '옮김: {n}',
      ja: '移動: {n}',
      zh: '移动：{n}',
      ar: 'نقل: {n}',
      es: 'Movimientos: {n}',
      fr: 'Déplacements : {n}',
      hi: 'खिसकाव: {n}',
      id: 'Pindah: {n}',
      pt: 'Movimentos: {n}',
    },
    'count.deletes': {
      en: 'Deletes: {n}',
      ko: '지움: {n}',
      ja: '削除: {n}',
      zh: '删除：{n}',
      ar: 'حذف: {n}',
      es: 'Borrados: {n}',
      fr: 'Suppressions : {n}',
      hi: 'हटाना: {n}',
      id: 'Hapus: {n}',
      pt: 'Remoções: {n}',
    },
    'count.inserts': {
      en: 'Inserts: {n}',
      ko: '넣음: {n}',
      ja: '挿入: {n}',
      zh: '插入：{n}',
      ar: 'إدراج: {n}',
      es: 'Inserciones: {n}',
      fr: 'Insertions : {n}',
      hi: 'जोड़ना: {n}',
      id: 'Sisip: {n}',
      pt: 'Inserções: {n}',
    },
    'count.edits': {
      en: 'Edits: {n}',
      ko: '손질: {n}',
      ja: '編集: {n}',
      zh: '编辑：{n}',
      ar: 'تعديلات: {n}',
      es: 'Ediciones: {n}',
      fr: 'Modifications : {n}',
      hi: 'संपादन: {n}',
      id: 'Suntingan: {n}',
      pt: 'Edições: {n}',
    },
    'caption.start': {
      en: 'The same lines, before and after a move. How many edits apart are the two files?',
      ko: '옮기기 전과 뒤, 같은 줄들이 다른 차례로 섰다. 두 파일은 손질 몇 번만큼 떨어져 있나?',
      ja: '移動の前と後、同じ行が別の順に並ぶ。二つのファイルは何回の編集ぶん離れているか?',
      zh: '移动前后，同样的行换了顺序。两个文件相差几次编辑？',
      ar: 'الأسطر نفسها قبل النقل وبعده. كم تعديلًا يفصل بين الملفين؟',
      es: 'Las mismas líneas, antes y después de mover. ¿Cuántas ediciones separan los dos archivos?',
      fr: 'Les mêmes lignes, avant et après un déplacement. Combien de modifications séparent les deux fichiers ?',
      hi: 'खिसकाने से पहले और बाद में वही पंक्तियाँ। दोनों फ़ाइलों में कितने संपादनों का फ़ासला है?',
      id: 'Baris yang sama, sebelum dan sesudah dipindah. Berapa suntingan jarak kedua berkas?',
      pt: 'As mesmas linhas, antes e depois de mover. Quantas edições separam os dois arquivos?',
    },
    'caption.move': {
      en: 'Human eye: the block A {from}–{last} travels in one piece to B {to}. Moves: {n}',
      ko: '사람의 눈: A {from}–{last} 덩이가 통째로 B {to} 자리로 간다. 옮김: {n}',
      ja: '人の目: A {from}–{last} のまとまりがそのまま B {to} の位置へ行く。移動: {n}',
      zh: '人的眼光：A {from}–{last} 这一段整块移到 B {to} 的位置。移动：{n}',
      ar: 'عين الإنسان: الكتلة A {from}–{last} تنتقل قطعة واحدة إلى B {to}. نقل: {n}',
      es: 'Ojo humano: el bloque A {from}–{last} viaja entero a B {to}. Movimientos: {n}',
      fr: 'Œil humain : le bloc A {from}–{last} part d’un seul tenant vers B {to}. Déplacements : {n}',
      hi: 'इंसान की नज़र: खंड A {from}–{last} एक टुकड़े में B {to} पर जाता है। खिसकाव: {n}',
      id: 'Mata manusia: blok A {from}–{last} pindah utuh ke B {to}. Pindah: {n}',
      pt: 'Olho humano: o bloco A {from}–{last} viaja inteiro para B {to}. Movimentos: {n}',
    },
    'caption.keep': {
      en: 'Line eye: link equal lines, as many as possible, with no two links crossing. Kept: {n}',
      ko: '줄의 눈: 같은 줄끼리 잇되 선이 서로 엇갈리지 않게, 가장 많이 잇는다. 남김: {n}',
      ja: '行の目: 同じ行どうしを、線が交差しないように、できるだけ多く結ぶ。残す: {n}',
      zh: '逐行的眼光：把相同的行连起来，连线互不交叉，连得越多越好。保留：{n}',
      ar: 'عين الأسطر: صِل الأسطر المتطابقة بأكبر عدد ممكن دون أن يتقاطع خطّان. إبقاء: {n}',
      es: 'Ojo de líneas: une líneas iguales, tantas como se pueda, sin que dos uniones se crucen. Conservadas: {n}',
      fr: 'Œil ligne à ligne : relier les lignes égales, le plus possible, sans que deux liens se croisent. Gardées : {n}',
      hi: 'पंक्ति की नज़र: समान पंक्तियों को जितना हो सके जोड़ो, पर कोई दो जोड़ एक-दूसरे को न काटें। बचीं: {n}',
      id: 'Mata baris: sambungkan baris yang sama sebanyak mungkin, tanpa dua sambungan bersilangan. Tetap: {n}',
      pt: 'Olho de linhas: ligue linhas iguais, o máximo possível, sem que duas ligações se cruzem. Mantidas: {n}',
    },
    'caption.cross': {
      en: 'The moved lines have word-for-word twins across, but linking them crosses the kept links, so they snap. Crossings: {n}',
      ko: '옮긴 줄은 건너편에 글자가 똑같은 짝이 있다. 그러나 이으면 남긴 선과 엇갈려 끊긴다. 엇갈림: {n}',
      ja: '移した行には向こう側に一字一句同じ相手がいる。だが結ぶと残した線と交差して切れる。交差: {n}',
      zh: '移动的行在对面有一字不差的同伴，但一连就与保留的连线交叉，于是断开。交叉：{n}',
      ar: 'للأسطر المنقولة توائم مطابقة حرفًا بحرف في الجهة الأخرى، لكن وصلها يقطع الروابط المُبقاة فتنكسر. تقاطعات: {n}',
      es: 'Las líneas movidas tienen gemelas idénticas al otro lado, pero unirlas cruza las uniones conservadas y se rompen. Cruces: {n}',
      fr: 'Les lignes déplacées ont des jumelles identiques en face, mais les relier croise les liens gardés : ils cassent. Croisements : {n}',
      hi: 'खिसकाई पंक्तियों की हूबहू जुड़वाँ उस पार हैं, पर उन्हें जोड़ने पर जोड़ बची हुई कड़ियों को काटते हैं और टूट जाते हैं। काट: {n}',
      id: 'Baris yang dipindah punya kembaran persis di seberang, tetapi menyambungnya memotong sambungan yang tetap, jadi putus. Silangan: {n}',
      pt: 'As linhas movidas têm gêmeas idênticas do outro lado, mas ligá-las cruza as ligações mantidas e elas se partem. Cruzamentos: {n}',
    },
    'caption.delete': {
      en: 'On the A side the snapped lines fall out as deletions. Deletes: {n}',
      ko: 'A 쪽에서 끊긴 줄은 지움으로 떨어진다. 지움: {n}',
      ja: 'A 側では切れた行が削除として落ちる。削除: {n}',
      zh: '在 A 这一侧，断开的行作为删除掉出去。删除：{n}',
      ar: 'في جهة A تسقط الأسطر المنكسرة حذفًا. حذف: {n}',
      es: 'Del lado A, las líneas rotas caen como borrados. Borrados: {n}',
      fr: 'Côté A, les lignes cassées tombent en suppressions. Suppressions : {n}',
      hi: 'A की ओर टूटी पंक्तियाँ हटाने के रूप में गिरती हैं। हटाना: {n}',
      id: 'Di sisi A, baris yang putus jatuh sebagai penghapusan. Hapus: {n}',
      pt: 'Do lado A, as linhas partidas caem como remoções. Remoções: {n}',
    },
    'caption.insert': {
      en: 'On the B side the same text comes back as insertions. Inserts: {n}',
      ko: 'B 쪽에서는 같은 글자가 넣음으로 떨어진다. 넣음: {n}',
      ja: 'B 側では同じ文字列が挿入として落ちる。挿入: {n}',
      zh: '在 B 这一侧，同样的文字作为插入回来。插入：{n}',
      ar: 'في جهة B يعود النص نفسه إدراجًا. إدراج: {n}',
      es: 'Del lado B, el mismo texto vuelve como inserciones. Inserciones: {n}',
      fr: 'Côté B, le même texte revient en insertions. Insertions : {n}',
      hi: 'B की ओर वही पाठ जोड़ने के रूप में लौटता है। जोड़ना: {n}',
      id: 'Di sisi B, teks yang sama kembali sebagai penyisipan. Sisip: {n}',
      pt: 'Do lado B, o mesmo texto volta como inserções. Inserções: {n}',
    },
    'caption.compare': {
      en: 'Edits by the human eye: {h} · Edits by the line eye: {l}',
      ko: '사람의 눈이 센 손질: {h} · 줄의 눈이 센 손질: {l}',
      ja: '人の目が数えた編集: {h} · 行の目が数えた編集: {l}',
      zh: '人的眼光数出的编辑：{h} · 逐行的眼光数出的编辑：{l}',
      ar: 'تعديلات بعين الإنسان: {h} · تعديلات بعين الأسطر: {l}',
      es: 'Ediciones según el ojo humano: {h} · Ediciones según el ojo de líneas: {l}',
      fr: 'Modifications selon l’œil humain : {h} · Modifications selon l’œil ligne à ligne : {l}',
      hi: 'इंसान की नज़र से संपादन: {h} · पंक्ति की नज़र से संपादन: {l}',
      id: 'Suntingan menurut mata manusia: {h} · Suntingan menurut mata baris: {l}',
      pt: 'Edições pelo olho humano: {h} · Edições pelo olho de linhas: {l}',
    },
  },
  blocks: {
    stage: { type: 'move-looks-like-rewrite-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
