import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 브라우저가 페이지 하나를 여는 데 왜 요청이 여러 번 오가는가.
 *
 * 물은 것만 답으로 온다. 답 안에서 새로 알게 된 자원은 줄 끝에 서서 다시 물어야 온다.
 */
export const requestResponseFacet: FacetJson = {
  id: 'facet:requestResponse',
  title: {
    en: 'One page, many requests',
    ko: '페이지 하나, 요청 여럿',
    ja: 'ページひとつに要求がいくつも',
    zh: '一个页面，多次请求',
    ar: 'صفحة واحدة وطلبات كثيرة',
    es: 'Una página, muchas peticiones',
    fr: 'Une page, plusieurs requêtes',
    hi: 'एक पेज, कई अनुरोध',
    id: 'Satu halaman, banyak permintaan',
    pt: 'Uma página, vários pedidos',
  },
  description: {
    en: 'Only what is asked for comes back. Names found inside an answer have to be asked for again.',
    ko: '물은 것만 답으로 온다. 답 안에서 새로 알게 된 것은 다시 물어야 온다.',
    ja: '問い合わせたものだけが返ってくる。応答の中で知った名前は、もう一度問い合わせないと来ない。',
    zh: '只有请求过的才会返回。响应里新发现的名字，要再请求一次才会来。',
    ar: 'لا يعود إلا ما طُلب. الأسماء التي تظهر داخل الرد يجب طلبها من جديد.',
    es: 'Solo vuelve lo que se pide. Los nombres que aparecen dentro de una respuesta hay que pedirlos otra vez.',
    fr: 'Seul ce qui est demandé revient. Les noms trouvés dans une réponse doivent être demandés à nouveau.',
    hi: 'जो पूछा जाए वही लौटता है। जवाब के अंदर मिले नए नाम फिर से पूछने पड़ते हैं।',
    id: 'Hanya yang diminta yang kembali. Nama yang ditemukan di dalam jawaban harus diminta lagi.',
    pt: 'Só volta o que foi pedido. Os nomes encontrados dentro de uma resposta precisam ser pedidos de novo.',
  },
  algorithm: 'module:requestResponse',
  scene: 'module:requestResponseScene',
  initialData: {
    type: 'request-response',
    stepMs: 1000,
    host: 'www.example.com',
    method: 'GET',
    version: 'HTTP/1.1',
    found: { code: 200, reason: 'OK' },
    missing: { code: 404, reason: 'Not Found' },
    start: '/index.html',
    resources: [
      { path: '/index.html', refs: ['/style.css', '/app.js', '/logo.png'] },
      { path: '/style.css', refs: ['/font.woff2'] },
      { path: '/app.js', refs: [] },
      { path: '/font.woff2', refs: [] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.browser': {
      en: 'Browser',
      ko: '브라우저',
      ja: 'ブラウザ',
      zh: '浏览器',
      ar: 'المتصفح',
      es: 'Navegador',
      fr: 'Navigateur',
      hi: 'ब्राउज़र',
      id: 'Peramban',
      pt: 'Navegador',
    },
    'label.server': {
      en: 'Server',
      ko: '서버',
      ja: 'サーバー',
      zh: '服务器',
      ar: 'الخادم',
      es: 'Servidor',
      fr: 'Serveur',
      hi: 'सर्वर',
      id: 'Server',
      pt: 'Servidor',
    },
    'label.sent': {
      en: 'Requests: {n}',
      ko: '보낸 요청: {n}',
      ja: '送った要求: {n}',
      zh: '已发请求: {n}',
      ar: 'الطلبات المرسلة: {n}',
      es: 'Peticiones: {n}',
      fr: 'Requêtes : {n}',
      hi: 'भेजे अनुरोध: {n}',
      id: 'Permintaan: {n}',
      pt: 'Pedidos: {n}',
    },
    'label.replied': {
      en: 'Responses: {n}',
      ko: '보낸 응답: {n}',
      ja: '返した応答: {n}',
      zh: '已回响应: {n}',
      ar: 'الردود المرسلة: {n}',
      es: 'Respuestas: {n}',
      fr: 'Réponses : {n}',
      hi: 'भेजे जवाब: {n}',
      id: 'Respons: {n}',
      pt: 'Respostas: {n}',
    },
    'label.queue': {
      en: 'To ask',
      ko: '물을 줄',
      ja: '問い合わせ待ち',
      zh: '待请求',
      ar: 'بانتظار الطلب',
      es: 'Por pedir',
      fr: 'À demander',
      hi: 'पूछना बाकी',
      id: 'Akan diminta',
      pt: 'A pedir',
    },
    'label.empty': {
      en: 'empty',
      ko: '비었음',
      ja: '空',
      zh: '空',
      ar: 'فارغ',
      es: 'vacía',
      fr: 'vide',
      hi: 'खाली',
      id: 'kosong',
      pt: 'vazia',
    },
    'label.log': {
      en: 'Answered',
      ko: '받은 답',
      ja: '受け取った応答',
      zh: '已收到',
      ar: 'ما وصل',
      es: 'Respondidas',
      fr: 'Reçues',
      hi: 'मिले जवाब',
      id: 'Terjawab',
      pt: 'Respondidas',
    },
    'caption.start': {
      en: 'First to ask: {path}',
      ko: '먼저 물을 것: {path}',
      ja: '最初に問い合わせるもの: {path}',
      zh: '最先请求: {path}',
      ar: 'أول ما يُطلب: {path}',
      es: 'Lo primero que se pide: {path}',
      fr: 'À demander d’abord : {path}',
      hi: 'सबसे पहले पूछना है: {path}',
      id: 'Yang pertama diminta: {path}',
      pt: 'Primeiro a pedir: {path}',
    },
    'caption.request': {
      en: 'Asking: {path}. Left in the queue: {q}',
      ko: '묻는 것: {path}. 줄에 남은 것: {q}',
      ja: '問い合わせ: {path}。待ちの残り: {q}',
      zh: '请求: {path}。队列剩余: {q}',
      ar: 'الطلب: {path}. الباقي في الطابور: {q}',
      es: 'Se pide: {path}. Quedan en la cola: {q}',
      fr: 'Demande : {path}. Restent dans la file : {q}',
      hi: 'पूछ रहे हैं: {path}. कतार में बाकी: {q}',
      id: 'Meminta: {path}. Sisa di antrean: {q}',
      pt: 'Pedindo: {path}. Restam na fila: {q}',
    },
    'caption.found': {
      en: 'Answer: {status}. New names inside: {n}. In the queue: {q}',
      ko: '답: {status}. 안에서 새로 나온 이름: {n}. 줄: {q}',
      ja: '応答: {status}。中の新しい名前: {n}。待ち: {q}',
      zh: '响应: {status}。其中的新名字: {n}。队列: {q}',
      ar: 'الرد: {status}. أسماء جديدة فيه: {n}. في الطابور: {q}',
      es: 'Respuesta: {status}. Nombres nuevos dentro: {n}. En la cola: {q}',
      fr: 'Réponse : {status}. Noms nouveaux dedans : {n}. Dans la file : {q}',
      hi: 'जवाब: {status}. इसमें नए नाम: {n}. कतार में: {q}',
      id: 'Jawaban: {status}. Nama baru di dalamnya: {n}. Di antrean: {q}',
      pt: 'Resposta: {status}. Nomes novos dentro: {n}. Na fila: {q}',
    },
    'caption.missing': {
      en: 'Answer: {status}. It points to nothing. In the queue: {q}',
      ko: '답: {status}. 가리키는 것 없음. 줄: {q}',
      ja: '応答: {status}。指す名前はない。待ち: {q}',
      zh: '响应: {status}。没有指向任何名字。队列: {q}',
      ar: 'الرد: {status}. لا يشير إلى شيء. في الطابور: {q}',
      es: 'Respuesta: {status}. No señala a nada. En la cola: {q}',
      fr: 'Réponse : {status}. Elle ne désigne rien. Dans la file : {q}',
      hi: 'जवाब: {status}. यह किसी ओर इशारा नहीं करता. कतार में: {q}',
      id: 'Jawaban: {status}. Tidak menunjuk apa pun. Di antrean: {q}',
      pt: 'Resposta: {status}. Não aponta para nada. Na fila: {q}',
    },
    'caption.done': {
      en: 'Answer: {status}. The queue is empty. Requests: {req} · responses: {res}',
      ko: '답: {status}. 줄이 비었다. 요청: {req} · 응답: {res}',
      ja: '応答: {status}。待ちは空。要求: {req} · 応答: {res}',
      zh: '响应: {status}。队列已空。请求: {req} · 响应: {res}',
      ar: 'الرد: {status}. الطابور فارغ. الطلبات: {req} · الردود: {res}',
      es: 'Respuesta: {status}. La cola está vacía. Peticiones: {req} · respuestas: {res}',
      fr: 'Réponse : {status}. La file est vide. Requêtes : {req} · réponses : {res}',
      hi: 'जवाब: {status}. कतार खाली है. अनुरोध: {req} · जवाब: {res}',
      id: 'Jawaban: {status}. Antrean kosong. Permintaan: {req} · respons: {res}',
      pt: 'Resposta: {status}. A fila está vazia. Pedidos: {req} · respostas: {res}',
    },
  },
  blocks: {
    stage: { type: 'request-response-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
