import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 자물쇠 하나는 세 스레드 가운데 어떻게 한 번에 하나만 들이는가.
 *
 * 세 스레드가 같은 세 줄(`lock(m)` · `work()` · `unlock(m)`)을 돌림 차례로 한 줄씩 실행한다.
 * 쥔 이가 있는 동안 온 스레드는 자물쇠 앞 줄에 서서 잠들고, 놓는 틱에 주인 자리가 줄 맨 앞에게
 * 곧바로 건네진다.
 */
export const lockExcludesFacet: FacetJson = {
  id: 'facet:lockExcludes',
  title: {
    en: 'One lock, one owner at a time',
    ko: '자물쇠 하나, 주인은 한 번에 하나',
    ja: '一つのロック、所有者は一度に一人',
    zh: '一把锁，每次只有一个持有者',
    ar: 'قفل واحد، ومالك واحد في كل مرة',
    es: 'Un cerrojo, un dueño a la vez',
    fr: 'Un verrou, un seul détenteur à la fois',
    hi: 'एक लॉक, एक समय में एक ही मालिक',
    id: 'Satu kunci, satu pemilik dalam satu waktu',
    pt: 'Um bloqueio, um dono de cada vez',
  },
  description: {
    en: 'Taking the lock shuts the others out; releasing it hands the owner seat to the front of the queue.',
    ko: '자물쇠를 잡으면 나머지를 막고, 놓으면 주인 자리를 줄 맨 앞에게 건넨다.',
    ja: 'ロックを取ると他は締め出され、放すと所有者の席が列の先頭に渡される。',
    zh: '拿到锁就把其他线程挡在外面；释放时把持有者的位置交给队首。',
    ar: 'أخذ القفل يُبقي الآخرين خارجًا، وتحريره يُسلّم مقعد المالك إلى أول الطابور.',
    es: 'Tomar el cerrojo deja fuera a los demás; soltarlo pasa el puesto de dueño al primero de la cola.',
    fr: 'Prendre le verrou tient les autres dehors ; le relâcher passe la place de détenteur au premier de la file.',
    hi: 'लॉक लेने पर बाकी बाहर रुकते हैं; छोड़ने पर मालिक की जगह कतार में सबसे आगे वाले को मिलती है।',
    id: 'Mengambil kunci menahan yang lain di luar; melepasnya menyerahkan kursi pemilik ke yang terdepan di antrean.',
    pt: 'Pegar o bloqueio deixa os outros de fora; soltá-lo passa o lugar de dono ao primeiro da fila.',
  },
  algorithm: 'module:lockExcludes',
  scene: 'module:lockExcludesScene',
  initialData: {
    type: 'lock-excludes',
    lock: 'm',
    threads: ['A', 'B', 'C'],
    program: ['lock(m)', 'work()', 'unlock(m)'],
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Each thread runs the same lines. Owner of {lock}: none.',
      ko: '스레드마다 같은 줄을 돈다. {lock} 의 주인: 없음.',
      ja: 'どのスレッドも同じ行を実行する。{lock} の所有者: なし。',
      zh: '每个线程运行相同的几行。{lock} 的持有者：无。',
      ar: 'كل خيط ينفّذ الأسطر نفسها. مالك {lock}: لا أحد.',
      es: 'Cada hilo ejecuta las mismas líneas. Dueño de {lock}: ninguno.',
      fr: 'Chaque thread exécute les mêmes lignes. Détenteur de {lock} : aucun.',
      hi: 'हर थ्रेड वही पंक्तियाँ चलाता है। {lock} का मालिक: कोई नहीं।',
      id: 'Setiap thread menjalankan baris yang sama. Pemilik {lock}: tidak ada.',
      pt: 'Cada thread executa as mesmas linhas. Dono de {lock}: nenhum.',
    },
    'caption.take': {
      en: '{who} runs lock({lock}). It was free. Owner: {who}.',
      ko: '{who}: lock({lock}) — 비어 있었다. 주인: {who}.',
      ja: '{who}: lock({lock}) — 空いていた。所有者: {who}。',
      zh: '{who} 执行 lock({lock})。锁是空的。持有者：{who}。',
      ar: '{who} ينفّذ lock({lock}). كان القفل فارغًا. المالك: {who}.',
      es: '{who} ejecuta lock({lock}). Estaba libre. Dueño: {who}.',
      fr: '{who} exécute lock({lock}). Il était libre. Détenteur : {who}.',
      hi: '{who} lock({lock}) चलाता है। लॉक खाली था। मालिक: {who}।',
      id: '{who} menjalankan lock({lock}). Kunci kosong. Pemilik: {who}.',
      pt: '{who} executa lock({lock}). Estava livre. Dono: {who}.',
    },
    'caption.block': {
      en: '{who} runs lock({lock}). Owner is {owner}, so {who} sleeps at the back of the queue.',
      ko: '{who}: lock({lock}) — 주인은 {owner}. 줄 끝에 서서 잠든다.',
      ja: '{who}: lock({lock}) — 所有者は {owner}。列の最後に並んで眠る。',
      zh: '{who} 执行 lock({lock})。持有者是 {owner}，于是 {who} 排到队尾睡下。',
      ar: '{who} ينفّذ lock({lock}). المالك هو {owner}، فينام {who} في آخر الطابور.',
      es: '{who} ejecuta lock({lock}). El dueño es {owner}, así que {who} duerme al final de la cola.',
      fr: '{who} exécute lock({lock}). Le détenteur est {owner}, donc {who} s’endort en bout de file.',
      hi: '{who} lock({lock}) चलाता है। मालिक {owner} है, इसलिए {who} कतार के अंत में सो जाता है।',
      id: '{who} menjalankan lock({lock}). Pemiliknya {owner}, jadi {who} tidur di ujung antrean.',
      pt: '{who} executa lock({lock}). O dono é {owner}, então {who} dorme no fim da fila.',
    },
    'caption.work': {
      en: '{who} runs work() in the owner seat. The queue stays asleep.',
      ko: '{who}: work() — 주인 자리에서 일한다. 줄은 잠든 그대로.',
      ja: '{who}: work() — 所有者の席で働く。列は眠ったまま。',
      zh: '{who} 在持有者的位置上执行 work()。队列仍在睡眠。',
      ar: '{who} ينفّذ work() في مقعد المالك. يبقى الطابور نائمًا.',
      es: '{who} ejecuta work() en el puesto de dueño. La cola sigue dormida.',
      fr: '{who} exécute work() à la place du détenteur. La file reste endormie.',
      hi: '{who} मालिक की जगह पर work() चलाता है। कतार सोई रहती है।',
      id: '{who} menjalankan work() di kursi pemilik. Antrean tetap tidur.',
      pt: '{who} executa work() no lugar de dono. A fila continua dormindo.',
    },
    'caption.workAlone': {
      en: '{who} runs work() in the owner seat. Nobody is waiting.',
      ko: '{who}: work() — 주인 자리에서 일한다. 기다리는 스레드는 없다.',
      ja: '{who}: work() — 所有者の席で働く。待つスレッドはない。',
      zh: '{who} 在持有者的位置上执行 work()。没有线程在等待。',
      ar: '{who} ينفّذ work() في مقعد المالك. لا أحد ينتظر.',
      es: '{who} ejecuta work() en el puesto de dueño. Nadie espera.',
      fr: '{who} exécute work() à la place du détenteur. Personne n’attend.',
      hi: '{who} मालिक की जगह पर work() चलाता है। कोई प्रतीक्षा में नहीं।',
      id: '{who} menjalankan work() di kursi pemilik. Tidak ada yang menunggu.',
      pt: '{who} executa work() no lugar de dono. Ninguém espera.',
    },
    'caption.handoff': {
      en: '{who} runs unlock({lock}). Handed straight to {to}, who wakes and goes on at work().',
      ko: '{who}: unlock({lock}) — 줄 맨 앞 {to} 에게 곧바로 건넨다. 깨어나 work() 부터 잇는다.',
      ja: '{who}: unlock({lock}) — 列の先頭 {to} にそのまま渡す。目覚めて work() から続ける。',
      zh: '{who} 执行 unlock({lock})。锁直接交给队首的 {to}，它醒来后从 work() 接着运行。',
      ar: '{who} ينفّذ unlock({lock}). يُسلَّم مباشرةً إلى {to}، فيستيقظ ويكمل من work().',
      es: '{who} ejecuta unlock({lock}). Pasa directo a {to}, que despierta y sigue en work().',
      fr: '{who} exécute unlock({lock}). Passé directement à {to}, qui se réveille et reprend à work().',
      hi: '{who} unlock({lock}) चलाता है। लॉक सीधे {to} को मिलता है, जो जागकर work() से आगे चलता है।',
      id: '{who} menjalankan unlock({lock}). Langsung diserahkan ke {to}, yang bangun dan lanjut di work().',
      pt: '{who} executa unlock({lock}). Passa direto para {to}, que acorda e segue em work().',
    },
    'caption.free': {
      en: '{who} runs unlock({lock}). Nobody is waiting. Owner: none.',
      ko: '{who}: unlock({lock}) — 기다리는 스레드가 없다. 주인: 없음.',
      ja: '{who}: unlock({lock}) — 待つスレッドはない。所有者: なし。',
      zh: '{who} 执行 unlock({lock})。没有线程在等待。持有者：无。',
      ar: '{who} ينفّذ unlock({lock}). لا أحد ينتظر. المالك: لا أحد.',
      es: '{who} ejecuta unlock({lock}). Nadie espera. Dueño: ninguno.',
      fr: '{who} exécute unlock({lock}). Personne n’attend. Détenteur : aucun.',
      hi: '{who} unlock({lock}) चलाता है। कोई प्रतीक्षा में नहीं। मालिक: कोई नहीं।',
      id: '{who} menjalankan unlock({lock}). Tidak ada yang menunggu. Pemilik: tidak ada.',
      pt: '{who} executa unlock({lock}). Ninguém espera. Dono: nenhum.',
    },
    'label.tick': {
      en: 'Tick {n}',
      ko: '틱 {n}',
      ja: 'ティック {n}',
      zh: '时钟 {n}',
      ar: 'النبضة {n}',
      es: 'Tic {n}',
      fr: 'Tic {n}',
      hi: 'टिक {n}',
      id: 'Tik {n}',
      pt: 'Tique {n}',
    },
    'label.ready': {
      en: 'Ready',
      ko: '준비',
      ja: '実行可能',
      zh: '就绪',
      ar: 'جاهز',
      es: 'Listo',
      fr: 'Prêt',
      hi: 'तैयार',
      id: 'Siap',
      pt: 'Pronto',
    },
    'label.queue': {
      en: 'Queue',
      ko: '줄',
      ja: '待ち行列',
      zh: '队列',
      ar: 'الطابور',
      es: 'Cola',
      fr: 'File',
      hi: 'कतार',
      id: 'Antrean',
      pt: 'Fila',
    },
    'label.owner': {
      en: 'Owner',
      ko: '주인',
      ja: '所有者',
      zh: '持有者',
      ar: 'المالك',
      es: 'Dueño',
      fr: 'Détenteur',
      hi: 'मालिक',
      id: 'Pemilik',
      pt: 'Dono',
    },
    'label.done': {
      en: 'Done',
      ko: '끝남',
      ja: '完了',
      zh: '完成',
      ar: 'انتهى',
      es: 'Hecho',
      fr: 'Terminé',
      hi: 'पूर्ण',
      id: 'Selesai',
      pt: 'Concluído',
    },
    'label.asleep': {
      en: 'asleep',
      ko: '잠듦',
      ja: '眠り中',
      zh: '睡眠',
      ar: 'نائم',
      es: 'dormido',
      fr: 'endormi',
      hi: 'सोया',
      id: 'tidur',
      pt: 'dormindo',
    },
  },
  blocks: {
    stage: { type: 'lock-excludes-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
