/**
 * @piece
 * 질문: 작은 모형이 먼저 쓴 토큰을 큰 모형은 어떻게 한 번에 확인하는가
 *
 * 작은 모형의 초안 넷이 문장 끝 너머로 앞서 나가 놓이고, 큰 모형 한 번이 넷을 앞에서부터
 * 훑어 맞는 데까지 붙인다. 처음 틀린 자리부터 뒤는 떨어져 나가고 그 자리에 큰 모형의
 * 토큰 하나가 들어간다. 판정은 탐욕 판정(같으면 받는다)이라 난수가 없다.
 * 초안과 큰 모형의 토큰은 예로 정한 값이다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const draftThenVerifyFacet: FacetJson = {
  id: 'facet:draftThenVerify',
  title: {
    en: 'Draft, then verify',
    ko: '먼저 찍고 확인하기',
    ja: '下書きしてから確かめる',
    zh: '先起草，再验证',
    ar: 'مسودة ثم تحقق',
    es: 'Borrador y luego verificación',
    fr: 'Ébaucher, puis vérifier',
    hi: 'पहले मसौदा, फिर जाँच',
    id: 'Draf dulu, lalu periksa',
    pt: 'Rascunhar e depois verificar',
  },
  description: {
    en: 'A small model drafts four tokens ahead; one call of the large model checks them all at once and keeps the matching run.',
    ko: '작은 모형이 토큰 넷을 앞서 쓰고, 큰 모형은 한 번 불려 넷을 한꺼번에 확인해 앞에서부터 맞는 데까지 남긴다.',
    ja: '小さなモデルが四つのトークンを先に書き、大きなモデルは一回の呼び出しでそれをまとめて確かめ、先頭から合っているところまでを残す。',
    zh: '小模型先写出四个词元，大模型只调用一次就一并检查，从前往后保留相符的部分。',
    ar: 'يكتب النموذج الصغير أربعة رموز مسبقًا، ويتحقق منها النموذج الكبير كلها في استدعاء واحد ويُبقي الجزء المتطابق من البداية.',
    es: 'Un modelo pequeño adelanta cuatro tokens; una sola llamada al modelo grande los revisa todos a la vez y conserva el tramo que coincide.',
    fr: 'Un petit modèle ébauche quatre jetons d’avance ; un seul appel au grand modèle les vérifie d’un coup et garde la partie qui concorde.',
    hi: 'छोटा मॉडल चार टोकन पहले से लिख देता है; बड़े मॉडल की एक ही पुकार उन्हें एक साथ जाँचती है और शुरू से मेल खाने वाला हिस्सा रखती है।',
    id: 'Model kecil menulis empat token lebih dulu; satu panggilan model besar memeriksa semuanya sekaligus dan menyimpan bagian yang cocok dari depan.',
    pt: 'Um modelo pequeno adianta quatro tokens; uma única chamada ao modelo grande confere todos de uma vez e mantém o trecho que coincide.',
  },
  algorithm: 'module:draftThenVerify',
  scene: 'module:draftThenVerifyScene',
  initialData: {
    type: 'draft-then-verify',
    stepMs: 800,
    prompt: ['the', 'quick', 'brown', 'fox'],
    rounds: [
      { draft: ['runs', 'over', 'the', 'lazy'], picks: ['jumps'] },
      { draft: ['over', 'a', 'lazy', 'dog'], picks: ['over', 'the'] },
      { draft: ['lazy', 'dog', 'and', 'runs'], picks: ['lazy', 'dog', 'and', 'runs', 'away'] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.draft': {
      en: 'Round {round}: the small model drafts {count} tokens past the end of the sentence.',
      ko: '판 {round}: 작은 모형이 문장 끝 너머로 초안 {count}개를 앞서 쓴다.',
      ja: '第 {round} 回: 小さなモデルが文の終わりの先に下書きを {count} 個書く。',
      zh: '第 {round} 轮：小模型在句子末尾之后先写出 {count} 个草稿词元。',
      ar: 'الجولة {round}: يكتب النموذج الصغير {count} رموز مسودة بعد نهاية الجملة.',
      es: 'Ronda {round}: el modelo pequeño escribe {count} tokens de borrador más allá del final de la frase.',
      fr: 'Tour {round} : le petit modèle ébauche {count} jetons au-delà de la fin de la phrase.',
      hi: 'दौर {round}: छोटा मॉडल वाक्य के अंत से आगे {count} मसौदा टोकन लिखता है।',
      id: 'Putaran {round}: model kecil menulis {count} token draf melewati akhir kalimat.',
      pt: 'Rodada {round}: o modelo pequeno escreve {count} tokens de rascunho além do fim da frase.',
    },
    'caption.all': {
      en: 'One large-model call checks all {count} at once. All {accepted} match, and the same call yields the next token.',
      ko: '큰 모형 한 번 부름으로 {count}개를 한꺼번에 확인한다. {accepted}개 모두 맞고, 같은 부름에서 다음 토큰 하나가 더 나온다.',
      ja: '大きなモデルの一回の呼び出しで {count} 個をまとめて確かめる。{accepted} 個すべてが合い、同じ呼び出しから次のトークンも一つ出る。',
      zh: '大模型调用一次就一并检查全部 {count} 个。{accepted} 个全部相符，同一次调用还给出下一个词元。',
      ar: 'استدعاء واحد للنموذج الكبير يتحقق من الـ {count} كلها دفعة واحدة. تتطابق كل الـ {accepted}، ويعطي الاستدعاء نفسه الرمز التالي.',
      es: 'Una llamada al modelo grande revisa los {count} a la vez. Coinciden los {accepted}, y la misma llamada da el token siguiente.',
      fr: 'Un appel au grand modèle vérifie les {count} d’un coup. Les {accepted} concordent, et le même appel donne le jeton suivant.',
      hi: 'बड़े मॉडल की एक पुकार सभी {count} को एक साथ जाँचती है। सभी {accepted} मेल खाते हैं, और वही पुकार अगला टोकन भी देती है।',
      id: 'Satu panggilan model besar memeriksa {count} token sekaligus. Semua {accepted} cocok, dan panggilan yang sama memberi token berikutnya.',
      pt: 'Uma chamada ao modelo grande confere os {count} de uma vez. Os {accepted} coincidem, e a mesma chamada dá o token seguinte.',
    },
    'caption.reject': {
      en: 'One large-model call checks all {count} at once, front to back. Matches: {accepted}. Draft {pos} differs, so the check stops there.',
      ko: '큰 모형 한 번 부름으로 {count}개를 앞에서부터 한꺼번에 확인한다. 맞은 것: {accepted}. 초안 {pos}번째가 달라 거기서 멈춘다.',
      ja: '大きなモデルの一回の呼び出しで {count} 個を先頭からまとめて確かめる。一致: {accepted}。下書きの {pos} 番目が違うので、そこで止まる。',
      zh: '大模型调用一次，从前往后一并检查全部 {count} 个。相符：{accepted}。第 {pos} 个草稿不同，检查在此停止。',
      ar: 'استدعاء واحد للنموذج الكبير يتحقق من الـ {count} كلها دفعة واحدة من البداية. المتطابق: {accepted}. المسودة رقم {pos} مختلفة، فيتوقف التحقق عندها.',
      es: 'Una llamada al modelo grande revisa los {count} a la vez, de delante hacia atrás. Coinciden: {accepted}. El borrador {pos} difiere, así que la revisión se detiene ahí.',
      fr: 'Un appel au grand modèle vérifie les {count} d’un coup, du début à la fin. Concordances : {accepted}. Le brouillon {pos} diffère, la vérification s’arrête là.',
      hi: 'बड़े मॉडल की एक पुकार सभी {count} को शुरू से एक साथ जाँचती है। मेल: {accepted}। मसौदा {pos} अलग है, इसलिए जाँच वहीं रुकती है।',
      id: 'Satu panggilan model besar memeriksa {count} token sekaligus, dari depan. Cocok: {accepted}. Draf ke-{pos} berbeda, jadi pemeriksaan berhenti di sana.',
      pt: 'Uma chamada ao modelo grande confere os {count} de uma vez, da frente para trás. Coincidem: {accepted}. O rascunho {pos} difere, então a conferência para ali.',
    },
    'caption.commitAll': {
      en: 'All {accepted} drafts attach, plus the large model’s next token: +{added}.',
      ko: '초안 {accepted}개가 모두 붙고, 큰 모형의 다음 토큰 하나가 더 붙는다: +{added}.',
      ja: '下書き {accepted} 個がすべて付き、大きなモデルの次のトークンも一つ付く: +{added}。',
      zh: '全部 {accepted} 个草稿接上，再加上大模型的下一个词元：+{added}。',
      ar: 'تُلحق المسودات الـ {accepted} كلها، ومعها الرمز التالي من النموذج الكبير: +{added}.',
      es: 'Se añaden los {accepted} borradores, más el token siguiente del modelo grande: +{added}.',
      fr: 'Les {accepted} brouillons s’ajoutent, plus le jeton suivant du grand modèle : +{added}.',
      hi: 'सभी {accepted} मसौदे जुड़ते हैं, साथ में बड़े मॉडल का अगला टोकन: +{added}।',
      id: 'Semua {accepted} draf tersambung, ditambah token berikutnya dari model besar: +{added}.',
      pt: 'Os {accepted} rascunhos se juntam, mais o token seguinte do modelo grande: +{added}.',
    },
    'caption.commitNone': {
      en: 'No draft attaches. The whole draft falls away and the large model’s token takes its place: +{added}.',
      ko: '붙는 초안이 없다. 초안 전부가 떨어져 나가고 그 자리에 큰 모형의 토큰이 들어간다: +{added}.',
      ja: '付く下書きはない。下書き全体が落ち、その場所に大きなモデルのトークンが入る: +{added}。',
      zh: '没有草稿被接上。整个草稿脱落，大模型的词元填入该位置：+{added}。',
      ar: 'لا تُلحق أي مسودة. تسقط المسودة كلها ويحل رمز النموذج الكبير مكانها: +{added}.',
      es: 'No se añade ningún borrador. Todo el borrador se cae y el token del modelo grande ocupa su lugar: +{added}.',
      fr: 'Aucun brouillon ne s’ajoute. Tout le brouillon tombe et le jeton du grand modèle prend sa place : +{added}.',
      hi: 'कोई मसौदा नहीं जुड़ता। पूरा मसौदा गिर जाता है और उसकी जगह बड़े मॉडल का टोकन आता है: +{added}।',
      id: 'Tidak ada draf yang tersambung. Seluruh draf terlepas dan token model besar mengisi tempatnya: +{added}.',
      pt: 'Nenhum rascunho se junta. O rascunho inteiro cai e o token do modelo grande toma seu lugar: +{added}.',
    },
    'caption.commitReject': {
      en: 'The {accepted} matching drafts attach. From draft {pos} on, the rest falls away and the large model’s token takes its place: +{added}.',
      ko: '맞은 초안 {accepted}개가 붙는다. 초안 {pos}번째부터 뒤는 떨어져 나가고 그 자리에 큰 모형의 토큰이 들어간다: +{added}.',
      ja: '一致した下書き {accepted} 個が付く。下書きの {pos} 番目から後ろは落ち、その場所に大きなモデルのトークンが入る: +{added}。',
      zh: '相符的 {accepted} 个草稿接上。从第 {pos} 个草稿起，其余部分脱落，大模型的词元填入该位置：+{added}。',
      ar: 'تُلحق المسودات المتطابقة وعددها {accepted}. من المسودة رقم {pos} فصاعدًا يسقط الباقي ويحل رمز النموذج الكبير مكانه: +{added}.',
      es: 'Se añaden los {accepted} borradores que coinciden. Desde el borrador {pos}, el resto se cae y el token del modelo grande ocupa su lugar: +{added}.',
      fr: 'Les {accepted} brouillons concordants s’ajoutent. À partir du brouillon {pos}, le reste tombe et le jeton du grand modèle prend sa place : +{added}.',
      hi: 'मेल खाने वाले {accepted} मसौदे जुड़ते हैं। मसौदा {pos} से आगे बाकी गिर जाता है और उसकी जगह बड़े मॉडल का टोकन आता है: +{added}।',
      id: '{accepted} draf yang cocok tersambung. Mulai draf ke-{pos}, sisanya terlepas dan token model besar mengisi tempatnya: +{added}.',
      pt: 'Os {accepted} rascunhos que coincidem se juntam. A partir do rascunho {pos}, o resto cai e o token do modelo grande toma seu lugar: +{added}.',
    },
    'caption.summary': {
      en: '{added} tokens from {calls} large-model calls; one token per call would take {added} calls. Drafts accepted: {accepted} of {drafted}.',
      ko: '큰 모형 부름 {calls}번으로 토큰 {added}개가 늘었다. 한 부름에 토큰 하나씩이면 부름 {added}번. 받은 초안: {drafted}개 중 {accepted}개.',
      ja: '大きなモデルの呼び出し {calls} 回でトークンが {added} 個増えた。一回に一つずつなら呼び出し {added} 回。受け入れた下書き: {drafted} 個中 {accepted} 個。',
      zh: '大模型调用 {calls} 次，增加了 {added} 个词元；每次只出一个词元则需调用 {added} 次。接受的草稿：{drafted} 个中的 {accepted} 个。',
      ar: '{added} رموز من {calls} استدعاءات للنموذج الكبير؛ رمز واحد لكل استدعاء كان سيحتاج {added} استدعاءات. المسودات المقبولة: {accepted} من {drafted}.',
      es: '{added} tokens con {calls} llamadas al modelo grande; un token por llamada necesitaría {added} llamadas. Borradores aceptados: {accepted} de {drafted}.',
      fr: '{added} jetons pour {calls} appels au grand modèle ; un jeton par appel en demanderait {added}. Brouillons acceptés : {accepted} sur {drafted}.',
      hi: 'बड़े मॉडल की {calls} पुकारों से {added} टोकन; हर पुकार में एक टोकन होता तो {added} पुकारें लगतीं। स्वीकृत मसौदे: {drafted} में से {accepted}।',
      id: '{added} token dari {calls} panggilan model besar; satu token per panggilan butuh {added} panggilan. Draf diterima: {accepted} dari {drafted}.',
      pt: '{added} tokens com {calls} chamadas ao modelo grande; um token por chamada exigiria {added} chamadas. Rascunhos aceitos: {accepted} de {drafted}.',
    },
    'label.tally': {
      en: 'Large-model calls: {calls} · tokens added: {added}',
      ko: '큰 모형 부름: {calls} · 늘어난 토큰: {added}',
      ja: '大きなモデルの呼び出し: {calls} · 増えたトークン: {added}',
      zh: '大模型调用：{calls} · 新增词元：{added}',
      ar: 'استدعاءات النموذج الكبير: {calls} · الرموز المضافة: {added}',
      es: 'Llamadas al modelo grande: {calls} · tokens añadidos: {added}',
      fr: 'Appels au grand modèle : {calls} · jetons ajoutés : {added}',
      hi: 'बड़े मॉडल की पुकारें: {calls} · जुड़े टोकन: {added}',
      id: 'Panggilan model besar: {calls} · token bertambah: {added}',
      pt: 'Chamadas ao modelo grande: {calls} · tokens adicionados: {added}',
    },
    'legend.draft': {
      en: 'accepted draft',
      ko: '받은 초안',
      ja: '受け入れた下書き',
      zh: '被接受的草稿',
      ar: 'مسودة مقبولة',
      es: 'borrador aceptado',
      fr: 'brouillon accepté',
      hi: 'स्वीकृत मसौदा',
      id: 'draf diterima',
      pt: 'rascunho aceito',
    },
    'legend.large': {
      en: 'large-model token',
      ko: '큰 모형의 토큰',
      ja: '大きなモデルのトークン',
      zh: '大模型的词元',
      ar: 'رمز النموذج الكبير',
      es: 'token del modelo grande',
      fr: 'jeton du grand modèle',
      hi: 'बड़े मॉडल का टोकन',
      id: 'token model besar',
      pt: 'token do modelo grande',
    },
    'label.large': {
      en: 'large model · one call',
      ko: '큰 모형 · 한 번 부름',
      ja: '大きなモデル · 一回の呼び出し',
      zh: '大模型 · 一次调用',
      ar: 'النموذج الكبير · استدعاء واحد',
      es: 'modelo grande · una llamada',
      fr: 'grand modèle · un appel',
      hi: 'बड़ा मॉडल · एक पुकार',
      id: 'model besar · satu panggilan',
      pt: 'modelo grande · uma chamada',
    },
    'label.gain': {
      en: '+{n}',
      ko: '+{n}',
      ja: '+{n}',
      zh: '+{n}',
      ar: '+{n}',
      es: '+{n}',
      fr: '+{n}',
      hi: '+{n}',
      id: '+{n}',
      pt: '+{n}',
    },
  },
  blocks: {
    stage: { type: 'draft-then-verify-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
