import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 읽은 줄을 모두 잠갔는데도 같은 질의가 두 번째에 줄을 더 돌려주는 까닭은?
 *
 * @notation native
 * SQL 이 곧 소재다 — 화면의 문장은 사양의 SQL 을 글자 그대로 쓴다.
 */
export const phantomReadFacet: FacetJson = {
  id: 'facet:phantomRead',
  title: {
    en: 'Phantom read',
    ko: '팬텀 리드',
    ja: 'ファントムリード',
    zh: '幻读',
    ar: 'القراءة الشبحية',
    es: 'Lectura fantasma',
    fr: 'Lecture fantôme',
    hi: 'फ़ैंटम रीड',
    id: 'Phantom read',
    pt: 'Leitura fantasma',
  },
  description: {
    en: 'Every row the query read is locked, yet the same query returns one more row the second time — a new row slips into the result.',
    ko: '질의가 읽은 줄은 모두 잠겼는데도 같은 질의가 두 번째에 줄을 하나 더 돌려준다 — 새 줄이 결과 안으로 끼어든다.',
    ja: 'クエリが読んだ行はすべてロックされているのに、同じクエリが二度目には一行多く返す — 新しい行が結果に割り込む。',
    zh: '查询读过的行都已加锁,同一查询第二次却多返回一行 — 新行挤进了结果。',
    ar: 'كل صف قرأه الاستعلام مقفل، ومع ذلك يعيد الاستعلام نفسه صفًا إضافيًا في المرة الثانية — صف جديد يتسلل إلى النتيجة.',
    es: 'Todas las filas que leyó la consulta están bloqueadas, pero la misma consulta devuelve una fila más la segunda vez: una fila nueva se cuela en el resultado.',
    fr: 'Chaque ligne lue par la requête est verrouillée, et pourtant la même requête renvoie une ligne de plus la seconde fois : une nouvelle ligne se glisse dans le résultat.',
    hi: 'क्वेरी की पढ़ी हर पंक्ति लॉक है, फिर भी वही क्वेरी दूसरी बार एक पंक्ति ज़्यादा लौटाती है — नई पंक्ति परिणाम में घुस आती है।',
    id: 'Setiap baris yang dibaca kueri terkunci, tetapi kueri yang sama mengembalikan satu baris lebih banyak pada kali kedua — baris baru menyusup ke hasil.',
    pt: 'Toda linha lida pela consulta está bloqueada, mas a mesma consulta devolve uma linha a mais na segunda vez — uma linha nova se infiltra no resultado.',
  },
  algorithm: 'module:phantomRead',
  scene: 'module:phantomReadScene',
  initialData: {
    type: 'phantom-read',
    stepMs: 1500,
    table: 'orders',
    columns: ['id', 'amount'],
    rows: [
      [1, 80],
      [2, 120],
      [3, 45],
      [4, 200],
      [5, 150],
    ],
    isolation: 'REPEATABLE READ',
    schedule: [
      { txn: 'T1', sql: 'SELECT id, amount FROM orders WHERE amount >= 100;' },
      { txn: 'T2', sql: 'INSERT INTO orders VALUES (6, 130);' },
      { txn: 'T2', sql: 'INSERT INTO orders VALUES (7, 60);' },
      { txn: 'T2', sql: 'COMMIT;' },
      { txn: 'T1', sql: 'SELECT id, amount FROM orders WHERE amount >= 100;' },
    ],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'phantom-read-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'Isolation of {txn}: {level}. No statement has run yet.',
      ko: '{txn} 격리 수준: {level}. 아직 아무 문장도 돌지 않았다.',
      ja: '{txn} の分離レベル: {level}。まだどの文も実行されていない。',
      zh: '{txn} 的隔离级别:{level}。还没有执行任何语句。',
      ar: 'مستوى عزل {txn}: {level}. لم تُنفَّذ أي عبارة بعد.',
      es: 'Aislamiento de {txn}: {level}. Aún no se ha ejecutado ninguna sentencia.',
      fr: 'Isolation de {txn} : {level}. Aucune instruction n’a encore été exécutée.',
      hi: '{txn} का आइसोलेशन: {level}। अभी कोई कथन नहीं चला।',
      id: 'Isolasi {txn}: {level}. Belum ada pernyataan yang dijalankan.',
      pt: 'Isolamento de {txn}: {level}. Nenhuma instrução foi executada ainda.',
    },
    'caption.query': {
      en: 'Query {n} of {txn}. Rows returned: {count}. New S locks on id: {ids}.',
      ko: '{txn} 질의 {n}. 돌려준 줄 수: {count}. 새로 S 잠금을 잡은 id: {ids}.',
      ja: '{txn} のクエリ {n}。返した行数: {count}。新たに S ロックを取った id: {ids}。',
      zh: '{txn} 的查询 {n}。返回行数:{count}。新加 S 锁的 id:{ids}。',
      ar: 'الاستعلام {n} من {txn}. الصفوف المُعادة: {count}. أقفال S جديدة على المعرّف: {ids}.',
      es: 'Consulta {n} de {txn}. Filas devueltas: {count}. Nuevos bloqueos S en id: {ids}.',
      fr: 'Requête {n} de {txn}. Lignes renvoyées : {count}. Nouveaux verrous S sur id : {ids}.',
      hi: '{txn} की क्वेरी {n}। लौटी पंक्तियाँ: {count}। नए S लॉक वाले id: {ids}।',
      id: 'Kueri {n} milik {txn}. Baris dikembalikan: {count}. Kunci S baru pada id: {ids}.',
      pt: 'Consulta {n} de {txn}. Linhas devolvidas: {count}. Novos bloqueios S no id: {ids}.',
    },
    'caption.queryNoLock': {
      en: 'Query {n} of {txn}. Rows returned: {count}. No new S locks.',
      ko: '{txn} 질의 {n}. 돌려준 줄 수: {count}. 새로 잡은 S 잠금은 없다.',
      ja: '{txn} のクエリ {n}。返した行数: {count}。新しい S ロックはない。',
      zh: '{txn} 的查询 {n}。返回行数:{count}。没有新加的 S 锁。',
      ar: 'الاستعلام {n} من {txn}. الصفوف المُعادة: {count}. لا أقفال S جديدة.',
      es: 'Consulta {n} de {txn}. Filas devueltas: {count}. Ningún bloqueo S nuevo.',
      fr: 'Requête {n} de {txn}. Lignes renvoyées : {count}. Aucun nouveau verrou S.',
      hi: '{txn} की क्वेरी {n}। लौटी पंक्तियाँ: {count}। कोई नया S लॉक नहीं।',
      id: 'Kueri {n} milik {txn}. Baris dikembalikan: {count}. Tidak ada kunci S baru.',
      pt: 'Consulta {n} de {txn}. Linhas devolvidas: {count}. Nenhum bloqueio S novo.',
    },
    'caption.kept': {
      en: 'Rows unchanged since query {m}: {kept}/{prev}. New in the result: id {ids}.',
      ko: '질의 {m} 결과에서 그대로인 줄: {kept}/{prev}. 결과에 새로 끼어든 id: {ids}.',
      ja: 'クエリ {m} から変わらない行: {kept}/{prev}。結果に新しく割り込んだ id: {ids}。',
      zh: '自查询 {m} 以来未变的行:{kept}/{prev}。新挤进结果的 id:{ids}。',
      ar: 'صفوف لم تتغير منذ الاستعلام {m}: {kept}/{prev}. جديد في النتيجة: المعرّف {ids}.',
      es: 'Filas sin cambios desde la consulta {m}: {kept}/{prev}. Nuevo en el resultado: id {ids}.',
      fr: 'Lignes inchangées depuis la requête {m} : {kept}/{prev}. Nouveau dans le résultat : id {ids}.',
      hi: 'क्वेरी {m} से अपरिवर्तित पंक्तियाँ: {kept}/{prev}। परिणाम में नया: id {ids}।',
      id: 'Baris tak berubah sejak kueri {m}: {kept}/{prev}. Baru di hasil: id {ids}.',
      pt: 'Linhas inalteradas desde a consulta {m}: {kept}/{prev}. Novo no resultado: id {ids}.',
    },
    'caption.keptAll': {
      en: 'Rows unchanged since query {m}: {kept}/{prev}. Nothing new in the result.',
      ko: '질의 {m} 결과에서 그대로인 줄: {kept}/{prev}. 결과에 새로 든 줄은 없다.',
      ja: 'クエリ {m} から変わらない行: {kept}/{prev}。結果に新しい行はない。',
      zh: '自查询 {m} 以来未变的行:{kept}/{prev}。结果中没有新行。',
      ar: 'صفوف لم تتغير منذ الاستعلام {m}: {kept}/{prev}. لا جديد في النتيجة.',
      es: 'Filas sin cambios desde la consulta {m}: {kept}/{prev}. Nada nuevo en el resultado.',
      fr: 'Lignes inchangées depuis la requête {m} : {kept}/{prev}. Rien de nouveau dans le résultat.',
      hi: 'क्वेरी {m} से अपरिवर्तित पंक्तियाँ: {kept}/{prev}। परिणाम में कुछ नया नहीं।',
      id: 'Baris tak berubah sejak kueri {m}: {kept}/{prev}. Tidak ada yang baru di hasil.',
      pt: 'Linhas inalteradas desde a consulta {m}: {kept}/{prev}. Nada novo no resultado.',
    },
    'caption.insert': {
      en: '{txn} inserts id {id}. X lock on the new row: granted without waiting.',
      ko: '{txn} 삽입 — id {id}. 새 줄의 X 잠금: 기다림 없이 허락.',
      ja: '{txn} が id {id} を挿入。新しい行の X ロック: 待たずに許可。',
      zh: '{txn} 插入 id {id}。新行的 X 锁:无需等待即获准。',
      ar: '{txn} يُدرج المعرّف {id}. قفل X على الصف الجديد: مُنح دون انتظار.',
      es: '{txn} inserta el id {id}. Bloqueo X sobre la fila nueva: concedido sin esperar.',
      fr: '{txn} insère l’id {id}. Verrou X sur la nouvelle ligne : accordé sans attente.',
      hi: '{txn} ने id {id} डाला। नई पंक्ति पर X लॉक: बिना प्रतीक्षा के मिला।',
      id: '{txn} menyisipkan id {id}. Kunci X pada baris baru: diberikan tanpa menunggu.',
      pt: '{txn} insere o id {id}. Bloqueio X na linha nova: concedido sem esperar.',
    },
    'caption.fits': {
      en: 'The new row meets the query condition.',
      ko: '새 줄은 질의 조건에 맞는다.',
      ja: '新しい行はクエリの条件に合う。',
      zh: '新行符合查询条件。',
      ar: 'الصف الجديد يستوفي شرط الاستعلام.',
      es: 'La fila nueva cumple la condición de la consulta.',
      fr: 'La nouvelle ligne satisfait la condition de la requête.',
      hi: 'नई पंक्ति क्वेरी की शर्त पूरी करती है।',
      id: 'Baris baru memenuhi syarat kueri.',
      pt: 'A linha nova atende à condição da consulta.',
    },
    'caption.misses': {
      en: 'The new row does not meet the query condition.',
      ko: '새 줄은 질의 조건에 맞지 않는다.',
      ja: '新しい行はクエリの条件に合わない。',
      zh: '新行不符合查询条件。',
      ar: 'الصف الجديد لا يستوفي شرط الاستعلام.',
      es: 'La fila nueva no cumple la condición de la consulta.',
      fr: 'La nouvelle ligne ne satisfait pas la condition de la requête.',
      hi: 'नई पंक्ति क्वेरी की शर्त पूरी नहीं करती।',
      id: 'Baris baru tidak memenuhi syarat kueri.',
      pt: 'A linha nova não atende à condição da consulta.',
    },
    'caption.commit': {
      en: '{txn} commits. X locks released: {count}.',
      ko: '{txn} 커밋. 놓은 X 잠금 수: {count}.',
      ja: '{txn} がコミット。解放した X ロック数: {count}。',
      zh: '{txn} 提交。释放的 X 锁数:{count}。',
      ar: '{txn} يُثبّت. أقفال X المُحرَّرة: {count}.',
      es: '{txn} confirma. Bloqueos X liberados: {count}.',
      fr: '{txn} valide. Verrous X libérés : {count}.',
      hi: '{txn} कमिट करता है। छोड़े गए X लॉक: {count}।',
      id: '{txn} melakukan commit. Kunci X dilepas: {count}.',
      pt: '{txn} confirma. Bloqueios X liberados: {count}.',
    },
    'label.query': {
      en: 'Query {n}',
      ko: '질의 {n}',
      ja: 'クエリ {n}',
      zh: '查询 {n}',
      ar: 'الاستعلام {n}',
      es: 'Consulta {n}',
      fr: 'Requête {n}',
      hi: 'क्वेरी {n}',
      id: 'Kueri {n}',
      pt: 'Consulta {n}',
    },
    'label.rows': {
      en: 'Rows: {n}',
      ko: '줄 수: {n}',
      ja: '行数: {n}',
      zh: '行数:{n}',
      ar: 'الصفوف: {n}',
      es: 'Filas: {n}',
      fr: 'Lignes : {n}',
      hi: 'पंक्तियाँ: {n}',
      id: 'Baris: {n}',
      pt: 'Linhas: {n}',
    },
  },
};
