/**
 * tcp-handshake — TCP 와 UDP. 잃음 · 뒤바뀜을 무엇으로 치러 앱이 모두를 차례대로 받는가.
 *
 * 1차 데이터는 구조다 — 주소 · 조각 이름 · 길 지연 · 잃는 차례 · 사다리 · 핸드셰이크 한 방향 틱 · 확인 틱 · 기한.
 * 도착 틱 · 넘긴 틱 · 확인 번호 · 계기 값은 알고리즘이 셈한다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { TcpHandshakeData } from './algorithm.js';

const initialData: TcpHandshakeData = {
  type: 'tcp-handshake',
  stepMs: 550,
  client: '192.0.2.10:50000',
  server: '198.51.100.20:5004',
  segments: ['d1', 'd2', 'd3', 'd4', 'd5', 'd6'],
  delays: [2, 2, 2, 3, 1, 2],
  lostOrder: [3, 5],
  lossLadder: [0, 1, 2],
  methods: ['udp', 'tcp'],
  method: 1,
  lossCount: 1,
  handshakeLeg: 2,
  ackLeg: 2,
  rto: 6,
  flags: { syn: 'SYN', synAck: 'SYN+ACK', ack: 'ACK' },
  states: {
    closed: 'CLOSED',
    listen: 'LISTEN',
    synSent: 'SYN-SENT',
    synReceived: 'SYN-RECEIVED',
    established: 'ESTABLISHED',
  },
};

export const tcpHandshakeFacet: FacetJson = {
  id: 'facet:tcpHandshake',
  title: {
    en: 'TCP and UDP',
    ko: 'TCP 와 UDP',
    ja: 'TCP と UDP',
    zh: 'TCP 与 UDP',
    ar: 'TCP و UDP',
    es: 'TCP y UDP',
    fr: 'TCP et UDP',
    hi: 'TCP और UDP',
    id: 'TCP dan UDP',
    pt: 'TCP e UDP',
  },
  description: {
    en: 'When segments are lost or reordered on the way, TCP pays with time and extra packets so the app gets all six in order; UDP hands over what arrives, as it arrives.',
    ko: '길에서 조각을 잃거나 차례가 뒤바뀔 때, TCP 는 시간과 덧붙은 패킷을 치러 앱에 여섯을 모두 차례대로 주고, UDP 는 닿은 것을 닿은 차례대로 준다.',
    ja: '途中でセグメントが失われたり順序が入れ替わったりしたとき、TCP は時間と追加のパケットを払ってアプリに六つすべてを順番どおりに渡し、UDP は届いたものを届いた順に渡す。',
    zh: '当分段在途中丢失或乱序时，TCP 以时间和额外的数据包为代价，把六个分段按顺序全部交给应用；UDP 则把到达的分段按到达的顺序交出。',
    ar: 'حين تضيع المقاطع أو يختلّ ترتيبها في الطريق، يدفع TCP وقتًا وحزمًا إضافية ليسلّم التطبيق الستة كلها بالترتيب، أما UDP فيسلّم ما يصل بترتيب وصوله.',
    es: 'Cuando se pierden o se desordenan segmentos por el camino, TCP paga con tiempo y paquetes extra para que la app reciba los seis en orden; UDP entrega lo que llega, en el orden en que llega.',
    fr: "Quand des segments se perdent ou arrivent dans le désordre, TCP paie en temps et en paquets supplémentaires pour que l'app reçoive les six dans l'ordre ; UDP livre ce qui arrive, dans l'ordre d'arrivée.",
    hi: 'जब रास्ते में खंड खो जाते हैं या क्रम बदल जाता है, TCP समय और अतिरिक्त पैकेट चुकाकर ऐप को छहों खंड क्रम से देता है; UDP जो पहुँचता है उसे पहुँचने के क्रम में दे देता है।',
    id: 'Saat segmen hilang atau tertukar urutannya di jalan, TCP membayar dengan waktu dan paket tambahan agar aplikasi menerima keenamnya berurutan; UDP menyerahkan yang tiba, sesuai urutan tibanya.',
    pt: 'Quando segmentos se perdem ou chegam fora de ordem, o TCP paga com tempo e pacotes extras para que o app receba os seis em ordem; o UDP entrega o que chega, na ordem em que chega.',
  },
  algorithm: 'module:tcpHandshake',
  projector: 'module:tcpHandshakeProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'tcp-handshake-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'method',
          name: 'method',
          label: {
            en: 'Transport',
            ko: '전송 방식',
            ja: '転送方式',
            zh: '传输方式',
            ar: 'طريقة النقل',
            es: 'Transporte',
            fr: 'Transport',
            hi: 'परिवहन तरीका',
            id: 'Cara kirim',
            pt: 'Transporte',
          },
          segments: [
            { value: 0, label: 'UDP' },
            { value: 1, label: 'TCP', default: true },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'lossCount',
          name: 'lossCount',
          label: {
            en: 'Segments lost',
            ko: '잃는 조각 수',
            ja: '失うセグメント数',
            zh: '丢失分段数',
            ar: 'المقاطع المفقودة',
            es: 'Segmentos perdidos',
            fr: 'Segments perdus',
            hi: 'खोए खंड',
            id: 'Segmen hilang',
            pt: 'Segmentos perdidos',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 1, label: '1', default: true },
            { value: 2, label: '2' },
          ],
        },
      ],
      metrics: [
        {
          name: 'app-received',
          label: {
            en: 'Received by app',
            ko: '앱이 받은 조각',
            ja: 'アプリが受け取った数',
            zh: '应用收到的分段',
            ar: 'ما استلمه التطبيق',
            es: 'Recibidos por la app',
            fr: "Reçus par l'app",
            hi: 'ऐप को मिले खंड',
            id: 'Diterima aplikasi',
            pt: 'Recebidos pelo app',
          },
          initial: 0,
        },
        {
          name: 'last-delivery-tick',
          label: {
            en: 'Last handover tick',
            ko: '마지막 넘김 틱',
            ja: '最後に渡したティック',
            zh: '最后交付的时刻',
            ar: 'نبضة آخر تسليم',
            es: 'Tic de la última entrega',
            fr: 'Tic de la dernière remise',
            hi: 'आख़िरी सौंपने का टिक',
            id: 'Tik serah terakhir',
            pt: 'Tique da última entrega',
          },
          initial: 0,
        },
        {
          name: 'extra-packets',
          label: {
            en: 'Extra packets',
            ko: '덧붙은 패킷',
            ja: '追加のパケット',
            zh: '额外数据包',
            ar: 'حزم إضافية',
            es: 'Paquetes extra',
            fr: 'Paquets en plus',
            hi: 'अतिरिक्त पैकेट',
            id: 'Paket tambahan',
            pt: 'Pacotes extras',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:tcp-handshake-imperative',
      label: {
        en: 'Receiver: hand over in order',
        ko: '받는 쪽: 차례대로 넘기기',
        ja: '受信側: 順番どおりに渡す',
        zh: '接收方：按序交付',
        ar: 'المستقبِل: التسليم بالترتيب',
        es: 'Receptor: entregar en orden',
        fr: 'Récepteur : remettre dans l’ordre',
        hi: 'प्राप्तकर्ता: क्रम से सौंपना',
        id: 'Penerima: serahkan berurutan',
        pt: 'Receptor: entregar em ordem',
      },
    },
  },
  messages: {
    'label.client': {
      en: 'Client',
      ko: '클라이언트',
      ja: 'クライアント',
      zh: '客户端',
      ar: 'العميل',
      es: 'Cliente',
      fr: 'Client',
      hi: 'क्लाइंट',
      id: 'Klien',
      pt: 'Cliente',
    },
    'label.server': {
      en: 'Server',
      ko: '서버',
      ja: 'サーバー',
      zh: '服务器',
      ar: 'الخادم',
      es: 'Servidor',
      fr: 'Serveur',
      hi: 'सर्वर',
      id: 'Server',
      pt: 'Servidor',
    },
    'label.app': {
      en: 'Tick each segment reached the app',
      ko: '조각마다 앱에 넘긴 틱',
      ja: 'セグメントごとにアプリへ渡したティック',
      zh: '每个分段交给应用的时刻',
      ar: 'نبضة تسليم كل مقطع إلى التطبيق',
      es: 'Tic en que cada segmento llegó a la app',
      fr: "Tic où chaque segment atteint l'app",
      hi: 'हर खंड ऐप तक पहुँचने का टिक',
      id: 'Tik tiap segmen sampai ke aplikasi',
      pt: 'Tique em que cada segmento chegou ao app',
    },
    'label.copies': {
      en: 'Sender copies',
      ko: '보내는 쪽 사본',
      ja: '送信側の控え',
      zh: '发送方副本',
      ar: 'نسخ المرسِل',
      es: 'Copias del emisor',
      fr: "Copies de l'émetteur",
      hi: 'भेजने वाले की प्रतियाँ',
      id: 'Salinan pengirim',
      pt: 'Cópias do emissor',
    },
    'label.holdQueue': {
      en: 'Receiver queue',
      ko: '받는 쪽 대기',
      ja: '受信側の待ち',
      zh: '接收方等待区',
      ar: 'انتظار المستقبِل',
      es: 'Espera del receptor',
      fr: 'Attente du récepteur',
      hi: 'प्राप्तकर्ता की कतार',
      id: 'Antrean penerima',
      pt: 'Espera do receptor',
    },
    'label.listenSocket': {
      en: 'Listening socket · port {port}',
      ko: '듣는 소켓 · 포트 {port}',
      ja: '待ち受けソケット · ポート {port}',
      zh: '监听套接字 · 端口 {port}',
      ar: 'مقبس الاستماع · المنفذ {port}',
      es: 'Socket de escucha · puerto {port}',
      fr: "Socket d'écoute · port {port}",
      hi: 'सुनने वाला सॉकेट · पोर्ट {port}',
      id: 'Soket dengar · port {port}',
      pt: 'Socket de escuta · porta {port}',
    },
    'label.connSocket': {
      en: 'Connection socket',
      ko: '연결 소켓',
      ja: '接続ソケット',
      zh: '连接套接字',
      ar: 'مقبس الاتصال',
      es: 'Socket de conexión',
      fr: 'Socket de connexion',
      hi: 'कनेक्शन सॉकेट',
      id: 'Soket koneksi',
      pt: 'Socket de conexão',
    },
    'label.notReceived': {
      en: 'Not received',
      ko: '못 받음',
      ja: '未受信',
      zh: '未收到',
      ar: 'لم يصل',
      es: 'No recibido',
      fr: 'Non reçu',
      hi: 'नहीं मिला',
      id: 'Tak diterima',
      pt: 'Não recebido',
    },
    'label.tick': {
      en: 'tick {n}',
      ko: '틱 {n}',
      ja: 'ティック {n}',
      zh: '时刻 {n}',
      ar: 'النبضة {n}',
      es: 'tic {n}',
      fr: 'tic {n}',
      hi: 'टिक {n}',
      id: 'tik {n}',
      pt: 'tique {n}',
    },
    'label.ackPacket': {
      en: 'ACK {n}',
      ko: '확인 {n}',
      ja: '確認 {n}',
      zh: '确认 {n}',
      ar: 'تأكيد {n}',
      es: 'ACK {n}',
      fr: 'ACK {n}',
      hi: 'पुष्टि {n}',
      id: 'ACK {n}',
      pt: 'ACK {n}',
    },
    'caption.listen': {
      en: 'Receiving port: {port}',
      ko: '받는 포트: {port}',
      ja: '受信ポート: {port}',
      zh: '接收端口：{port}',
      ar: 'منفذ الاستقبال: {port}',
      es: 'Puerto receptor: {port}',
      fr: 'Port de réception : {port}',
      hi: 'पाने वाला पोर्ट: {port}',
      id: 'Port penerima: {port}',
      pt: 'Porta receptora: {port}',
    },
    'caption.synArrived': {
      en: 'Arrived: {flag} · sent: {reply}',
      ko: '닿음: {flag} · 보냄: {reply}',
      ja: '到着: {flag} · 送信: {reply}',
      zh: '到达：{flag} · 发送：{reply}',
      ar: 'وصل: {flag} · أُرسل: {reply}',
      es: 'Llegó: {flag} · enviado: {reply}',
      fr: 'Arrivé : {flag} · envoyé : {reply}',
      hi: 'पहुँचा: {flag} · भेजा: {reply}',
      id: 'Tiba: {flag} · dikirim: {reply}',
      pt: 'Chegou: {flag} · enviado: {reply}',
    },
    'caption.ackArrived': {
      en: 'Arrived: {flag} · connection socket opened',
      ko: '닿음: {flag} · 연결 소켓 생김',
      ja: '到着: {flag} · 接続ソケットができた',
      zh: '到达：{flag} · 连接套接字建立',
      ar: 'وصل: {flag} · فُتح مقبس الاتصال',
      es: 'Llegó: {flag} · se abrió el socket de conexión',
      fr: 'Arrivé : {flag} · socket de connexion ouvert',
      hi: 'पहुँचा: {flag} · कनेक्शन सॉकेट बना',
      id: 'Tiba: {flag} · soket koneksi terbuka',
      pt: 'Chegou: {flag} · socket de conexão aberto',
    },
    'caption.handedUdp': {
      en: 'Arrived: {seg} · to the app: {seg}',
      ko: '닿음: {seg} · 앱에 넘김: {seg}',
      ja: '到着: {seg} · アプリへ: {seg}',
      zh: '到达：{seg} · 交给应用：{seg}',
      ar: 'وصل: {seg} · إلى التطبيق: {seg}',
      es: 'Llegó: {seg} · a la app: {seg}',
      fr: "Arrivé : {seg} · à l'app : {seg}",
      hi: 'पहुँचा: {seg} · ऐप को: {seg}',
      id: 'Tiba: {seg} · ke aplikasi: {seg}',
      pt: 'Chegou: {seg} · para o app: {seg}',
    },
    'caption.handed': {
      en: 'Arrived: {seg} · to the app: {list} · sent ACK {ack}',
      ko: '닿음: {seg} · 앱에 넘김: {list} · 확인 {ack} 보냄',
      ja: '到着: {seg} · アプリへ: {list} · 確認 {ack} を送信',
      zh: '到达：{seg} · 交给应用：{list} · 发出确认 {ack}',
      ar: 'وصل: {seg} · إلى التطبيق: {list} · أُرسل التأكيد {ack}',
      es: 'Llegó: {seg} · a la app: {list} · enviado ACK {ack}',
      fr: "Arrivé : {seg} · à l'app : {list} · ACK {ack} envoyé",
      hi: 'पहुँचा: {seg} · ऐप को: {list} · पुष्टि {ack} भेजी',
      id: 'Tiba: {seg} · ke aplikasi: {list} · ACK {ack} dikirim',
      pt: 'Chegou: {seg} · para o app: {list} · enviado ACK {ack}',
    },
    'caption.held': {
      en: 'Arrived: {seg} · waiting for: {want} · segments held: {count} · sent ACK {ack}',
      ko: '닿음: {seg} · 기다리는 조각: {want} · 쥔 조각: {count} · 확인 {ack} 보냄',
      ja: '到着: {seg} · 待っているセグメント: {want} · 保持数: {count} · 確認 {ack} を送信',
      zh: '到达：{seg} · 等待的分段：{want} · 暂存分段：{count} · 发出确认 {ack}',
      ar: 'وصل: {seg} · المقطع المنتظر: {want} · المقاطع المحتجزة: {count} · أُرسل التأكيد {ack}',
      es: 'Llegó: {seg} · se espera: {want} · segmentos retenidos: {count} · enviado ACK {ack}',
      fr: 'Arrivé : {seg} · attendu : {want} · segments retenus : {count} · ACK {ack} envoyé',
      hi: 'पहुँचा: {seg} · प्रतीक्षित खंड: {want} · रोके गए खंड: {count} · पुष्टि {ack} भेजी',
      id: 'Tiba: {seg} · ditunggu: {want} · segmen ditahan: {count} · ACK {ack} dikirim',
      pt: 'Chegou: {seg} · aguardando: {want} · segmentos retidos: {count} · enviado ACK {ack}',
    },
    'caption.synSent': {
      en: 'Sent: {flag}',
      ko: '보냄: {flag}',
      ja: '送信: {flag}',
      zh: '发送：{flag}',
      ar: 'أُرسل: {flag}',
      es: 'Enviado: {flag}',
      fr: 'Envoyé : {flag}',
      hi: 'भेजा: {flag}',
      id: 'Dikirim: {flag}',
      pt: 'Enviado: {flag}',
    },
    'caption.synAckArrived': {
      en: 'Arrived: {flag} · sent: {reply}',
      ko: '닿음: {flag} · 보냄: {reply}',
      ja: '到着: {flag} · 送信: {reply}',
      zh: '到达：{flag} · 发送：{reply}',
      ar: 'وصل: {flag} · أُرسل: {reply}',
      es: 'Llegó: {flag} · enviado: {reply}',
      fr: 'Arrivé : {flag} · envoyé : {reply}',
      hi: 'पहुँचा: {flag} · भेजा: {reply}',
      id: 'Tiba: {flag} · dikirim: {reply}',
      pt: 'Chegou: {flag} · enviado: {reply}',
    },
    'caption.ackBack': {
      en: 'ACK {ack} arrived',
      ko: '확인 {ack} 닿음',
      ja: '確認 {ack} 到着',
      zh: '确认 {ack} 到达',
      ar: 'وصل التأكيد {ack}',
      es: 'Llegó ACK {ack}',
      fr: 'ACK {ack} arrivé',
      hi: 'पुष्टि {ack} पहुँची',
      id: 'ACK {ack} tiba',
      pt: 'Chegou ACK {ack}',
    },
    'caption.sent': {
      en: 'Sent: {seg}',
      ko: '보냄: {seg}',
      ja: '送信: {seg}',
      zh: '发送：{seg}',
      ar: 'أُرسل: {seg}',
      es: 'Enviado: {seg}',
      fr: 'Envoyé : {seg}',
      hi: 'भेजा: {seg}',
      id: 'Dikirim: {seg}',
      pt: 'Enviado: {seg}',
    },
    'caption.sentLost': {
      en: 'Sent: {seg} · lost on the way',
      ko: '보냄: {seg} · 길에서 사라짐',
      ja: '送信: {seg} · 途中で消えた',
      zh: '发送：{seg} · 途中丢失',
      ar: 'أُرسل: {seg} · ضاع في الطريق',
      es: 'Enviado: {seg} · perdido por el camino',
      fr: 'Envoyé : {seg} · perdu en route',
      hi: 'भेजा: {seg} · रास्ते में खो गया',
      id: 'Dikirim: {seg} · hilang di jalan',
      pt: 'Enviado: {seg} · perdido no caminho',
    },
    'caption.resent': {
      en: 'Timer expired · resent: {seg}',
      ko: '기한 지남 · 다시 보냄: {seg}',
      ja: '期限切れ · 再送: {seg}',
      zh: '超时 · 重发：{seg}',
      ar: 'انتهت المهلة · أُعيد إرسال: {seg}',
      es: 'Plazo vencido · reenviado: {seg}',
      fr: 'Délai écoulé · renvoyé : {seg}',
      hi: 'समय-सीमा बीती · दोबारा भेजा: {seg}',
      id: 'Batas waktu lewat · dikirim ulang: {seg}',
      pt: 'Prazo esgotado · reenviado: {seg}',
    },
    'caption.quiet': {
      en: 'nothing arrives or leaves',
      ko: '오가는 것 없음',
      ja: '行き来なし',
      zh: '无收发',
      ar: 'لا وصول ولا إرسال',
      es: 'nada llega ni sale',
      fr: 'rien ne part ni n’arrive',
      hi: 'न कुछ पहुँचा न गया',
      id: 'tak ada yang tiba atau pergi',
      pt: 'nada chega nem sai',
    },
    'caption.final': {
      en: 'Round over · segments the app received: {n} · last handed over: tick {last}',
      ko: '판 끝 · 앱이 받은 조각: {n} · 마지막 넘김: 틱 {last}',
      ja: '回の終わり · アプリが受け取ったセグメント: {n} · 最後に渡した: ティック {last}',
      zh: '本轮结束 · 应用收到的分段：{n} · 最后交付：时刻 {last}',
      ar: 'انتهت الجولة · المقاطع التي استلمها التطبيق: {n} · آخر تسليم: النبضة {last}',
      es: 'Fin de la ronda · segmentos recibidos por la app: {n} · última entrega: tic {last}',
      fr: "Fin du tour · segments reçus par l'app : {n} · dernière remise : tic {last}",
      hi: 'दौर समाप्त · ऐप को मिले खंड: {n} · आख़िरी सौंपना: टिक {last}',
      id: 'Putaran selesai · segmen diterima aplikasi: {n} · serah terakhir: tik {last}',
      pt: 'Fim da rodada · segmentos recebidos pelo app: {n} · última entrega: tique {last}',
    },
    'caption.missing': {
      en: 'not received: {list}',
      ko: '못 받은 조각: {list}',
      ja: '受け取れなかったセグメント: {list}',
      zh: '未收到的分段：{list}',
      ar: 'لم يصل: {list}',
      es: 'no recibidos: {list}',
      fr: 'non reçus : {list}',
      hi: 'नहीं मिले: {list}',
      id: 'tak diterima: {list}',
      pt: 'não recebidos: {list}',
    },
  },
};
