import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 메모리에 올라와 있지 않은 페이지를 건드리면 무슨 일이 일어나는가.
 *
 * 값은 모두 예로 정한 것이다 — 페이지 넷의 표(0 만 프레임 1 에 있다), 빈 프레임 3 · 5,
 * 접근 차례 0 · 2 · 0 · 2 · 3. 폴트 수와 어느 프레임에 올리는지는 알고리즘이 셈한다.
 */
export const pageFaultFacet: FacetJson = {
  id: 'facet:pageFault',
  title: {
    en: 'Page fault',
    ko: '페이지 폴트',
    ja: 'ページフォールト',
    zh: '缺页',
    ar: 'خطأ الصفحة',
    es: 'Fallo de página',
    fr: 'Défaut de page',
    hi: 'पेज फ़ॉल्ट',
    id: 'Page fault',
    pt: 'Falta de página',
  },
  description: {
    en: 'What happens when a program touches a page that is not in memory?',
    ko: '메모리에 올라와 있지 않은 페이지를 건드리면 무슨 일이 일어나는가?',
    ja: 'メモリに載っていないページに触れると何が起きるのか?',
    zh: '访问一个不在内存中的页时会发生什么？',
    ar: 'ماذا يحدث عندما يلمس برنامج صفحة ليست في الذاكرة؟',
    es: '¿Qué ocurre cuando un programa toca una página que no está en memoria?',
    fr: 'Que se passe-t-il quand un programme touche une page absente de la mémoire ?',
    hi: 'जब प्रोग्राम ऐसे पृष्ठ को छूता है जो मेमोरी में नहीं है, तब क्या होता है?',
    id: 'Apa yang terjadi ketika program menyentuh halaman yang tidak ada di memori?',
    pt: 'O que acontece quando um programa toca uma página que não está na memória?',
  },
  algorithm: 'module:pageFault',
  scene: 'module:pageFaultScene',
  initialData: {
    type: 'page-fault',
    stepMs: 1100,
    pages: [
      { page: 0, frame: 1 },
      { page: 1, frame: null },
      { page: 2, frame: null },
      { page: 3, frame: null },
    ],
    freeFrames: [3, 5],
    accesses: [0, 2, 0, 2, 3],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Accesses to run: {n}. Free frames: {free}.',
      ko: '실행할 접근: {n}. 빈 프레임: {free}.',
      ja: 'これから行うアクセス: {n}。空きフレーム: {free}。',
      zh: '待执行的访问：{n}。空闲帧：{free}。',
      ar: 'الوصولات المطلوب تنفيذها: {n}. الإطارات الفارغة: {free}.',
      es: 'Accesos por ejecutar: {n}. Marcos libres: {free}.',
      fr: 'Accès à exécuter : {n}. Cadres libres : {free}.',
      hi: 'चलाने के लिए एक्सेस: {n}. खाली फ़्रेम: {free}.',
      id: 'Akses yang akan dijalankan: {n}. Bingkai kosong: {free}.',
      pt: 'Acessos a executar: {n}. Quadros livres: {free}.',
    },
    'caption.access': {
      en: 'Page {page} is in frame {frame} — the access goes straight through.',
      ko: '페이지 {page}: 프레임 {frame} 안에 있다. 접근이 멈추지 않고 곧바로 지나간다.',
      ja: 'ページ {page}: フレーム {frame} にある。アクセスはそのまま通る。',
      zh: '页 {page} 在帧 {frame} 中——访问直接通过。',
      ar: 'الصفحة {page} في الإطار {frame} — يمر الوصول مباشرة.',
      es: 'La página {page} está en el marco {frame}: el acceso pasa de inmediato.',
      fr: 'La page {page} est dans le cadre {frame} : l’accès passe directement.',
      hi: 'पृष्ठ {page} फ़्रेम {frame} में है — एक्सेस सीधे निकल जाता है।',
      id: 'Halaman {page} ada di bingkai {frame} — akses langsung lewat.',
      pt: 'A página {page} está no quadro {frame}: o acesso passa direto.',
    },
    'caption.fault': {
      en: 'Page {page}: the table says none. Execution stops — page fault.',
      ko: '페이지 {page}: 표에는 없음. 실행이 멈춘다 — 페이지 폴트.',
      ja: 'ページ {page}: 表には「なし」。実行が止まる — ページフォールト。',
      zh: '页 {page}：表中为“无”。执行停止——缺页。',
      ar: 'الصفحة {page}: الجدول يقول لا شيء. يتوقف التنفيذ — خطأ صفحة.',
      es: 'Página {page}: la tabla dice ninguno. La ejecución se detiene: fallo de página.',
      fr: 'Page {page} : la table indique aucun. L’exécution s’arrête — défaut de page.',
      hi: 'पृष्ठ {page}: तालिका में कुछ नहीं। निष्पादन रुकता है — पेज फ़ॉल्ट।',
      id: 'Halaman {page}: tabel berkata tidak ada. Eksekusi berhenti — page fault.',
      pt: 'Página {page}: a tabela diz nenhum. A execução para: falta de página.',
    },
    'caption.load': {
      en: 'Page {page} comes up from disk into free frame {frame}.',
      ko: '디스크에서 올라온다 — 페이지 {page} → 빈 프레임 {frame}.',
      ja: 'ディスクから上がってくる — ページ {page} → 空きフレーム {frame}。',
      zh: '从磁盘调入——页 {page} → 空闲帧 {frame}。',
      ar: 'تصعد الصفحة {page} من القرص إلى الإطار الفارغ {frame}.',
      es: 'La página {page} sube del disco al marco libre {frame}.',
      fr: 'La page {page} monte du disque vers le cadre libre {frame}.',
      hi: 'पृष्ठ {page} डिस्क से खाली फ़्रेम {frame} में ऊपर आता है।',
      id: 'Halaman {page} naik dari disk ke bingkai kosong {frame}.',
      pt: 'A página {page} sobe do disco para o quadro livre {frame}.',
    },
    'caption.map': {
      en: 'The table row for page {page} is fixed: frame {frame}.',
      ko: '표의 줄을 고친다 — 페이지 {page} → 프레임 {frame}.',
      ja: '表の行を書き換える — ページ {page} → フレーム {frame}。',
      zh: '改写表中的一行——页 {page} → 帧 {frame}。',
      ar: 'يُصحَّح سطر الصفحة {page} في الجدول: الإطار {frame}.',
      es: 'Se corrige la fila de la página {page}: marco {frame}.',
      fr: 'La ligne de la page {page} est corrigée : cadre {frame}.',
      hi: 'तालिका में पृष्ठ {page} की पंक्ति ठीक होती है: फ़्रेम {frame}।',
      id: 'Baris tabel untuk halaman {page} diperbaiki: bingkai {frame}.',
      pt: 'A linha da página {page} é corrigida: quadro {frame}.',
    },
    'caption.retry': {
      en: 'The same access restarts and this time reaches frame {frame}.',
      ko: '멈췄던 같은 접근이 처음부터 다시 돈다. 이번엔 닿는다 — 프레임 {frame}.',
      ja: '止まった同じアクセスが最初からやり直し、今度はフレーム {frame} に届く。',
      zh: '同一次访问从头重来，这次到达帧 {frame}。',
      ar: 'يعاد الوصول نفسه من البداية، ويصل هذه المرة إلى الإطار {frame}.',
      es: 'El mismo acceso vuelve a empezar y esta vez llega al marco {frame}.',
      fr: 'Le même accès recommence et atteint cette fois le cadre {frame}.',
      hi: 'वही एक्सेस फिर से शुरू होता है और इस बार फ़्रेम {frame} तक पहुँचता है।',
      id: 'Akses yang sama diulang dari awal dan kali ini sampai ke bingkai {frame}.',
      pt: 'O mesmo acesso recomeça e desta vez chega ao quadro {frame}.',
    },
    'stat.done': {
      en: 'Accesses done: {n} / {total}',
      ko: '끝난 접근: {n} / {total}',
      ja: '終わったアクセス: {n} / {total}',
      zh: '已完成访问：{n} / {total}',
      ar: 'الوصولات المنجزة: {n} / {total}',
      es: 'Accesos hechos: {n} / {total}',
      fr: 'Accès faits : {n} / {total}',
      hi: 'पूरे हुए एक्सेस: {n} / {total}',
      id: 'Akses selesai: {n} / {total}',
      pt: 'Acessos feitos: {n} / {total}',
    },
    'stat.faults': {
      en: 'Page faults: {n}',
      ko: '페이지 폴트: {n}',
      ja: 'ページフォールト: {n}',
      zh: '缺页次数：{n}',
      ar: 'أخطاء الصفحات: {n}',
      es: 'Fallos de página: {n}',
      fr: 'Défauts de page : {n}',
      hi: 'पेज फ़ॉल्ट: {n}',
      id: 'Page fault: {n}',
      pt: 'Faltas de página: {n}',
    },
    'label.accesses': {
      en: 'Accesses',
      ko: '접근',
      ja: 'アクセス',
      zh: '访问',
      ar: 'الوصولات',
      es: 'Accesos',
      fr: 'Accès',
      hi: 'एक्सेस',
      id: 'Akses',
      pt: 'Acessos',
    },
    'label.program': {
      en: 'Program',
      ko: '프로그램',
      ja: 'プログラム',
      zh: '程序',
      ar: 'البرنامج',
      es: 'Programa',
      fr: 'Programme',
      hi: 'प्रोग्राम',
      id: 'Program',
      pt: 'Programa',
    },
    'status.run': {
      en: 'running',
      ko: '실행 중',
      ja: '実行中',
      zh: '运行中',
      ar: 'قيد التشغيل',
      es: 'en marcha',
      fr: 'en cours',
      hi: 'चल रहा',
      id: 'berjalan',
      pt: 'executando',
    },
    'status.stop': {
      en: 'stopped',
      ko: '멈춤',
      ja: '停止',
      zh: '已停止',
      ar: 'متوقف',
      es: 'detenido',
      fr: 'arrêté',
      hi: 'रुका',
      id: 'berhenti',
      pt: 'parado',
    },
    'label.table': {
      en: 'Page table',
      ko: '페이지 표',
      ja: 'ページ表',
      zh: '页表',
      ar: 'جدول الصفحات',
      es: 'Tabla de páginas',
      fr: 'Table des pages',
      hi: 'पेज तालिका',
      id: 'Tabel halaman',
      pt: 'Tabela de páginas',
    },
    'label.page': {
      en: 'Page',
      ko: '페이지',
      ja: 'ページ',
      zh: '页',
      ar: 'الصفحة',
      es: 'Página',
      fr: 'Page',
      hi: 'पृष्ठ',
      id: 'Halaman',
      pt: 'Página',
    },
    'label.frame': {
      en: 'Frame',
      ko: '프레임',
      ja: 'フレーム',
      zh: '帧',
      ar: 'الإطار',
      es: 'Marco',
      fr: 'Cadre',
      hi: 'फ़्रेम',
      id: 'Bingkai',
      pt: 'Quadro',
    },
    'label.none': {
      en: 'none',
      ko: '없음',
      ja: 'なし',
      zh: '无',
      ar: 'لا شيء',
      es: 'ninguno',
      fr: 'aucun',
      hi: 'कुछ नहीं',
      id: 'tidak ada',
      pt: 'nenhum',
    },
    'label.memory': {
      en: 'Memory',
      ko: '메모리',
      ja: 'メモリ',
      zh: '内存',
      ar: 'الذاكرة',
      es: 'Memoria',
      fr: 'Mémoire',
      hi: 'मेमोरी',
      id: 'Memori',
      pt: 'Memória',
    },
    'label.disk': {
      en: 'Disk',
      ko: '디스크',
      ja: 'ディスク',
      zh: '磁盘',
      ar: 'القرص',
      es: 'Disco',
      fr: 'Disque',
      hi: 'डिस्क',
      id: 'Disk',
      pt: 'Disco',
    },
    'label.pageN': {
      en: 'Page {n}',
      ko: '페이지 {n}',
      ja: 'ページ {n}',
      zh: '页 {n}',
      ar: 'الصفحة {n}',
      es: 'Página {n}',
      fr: 'Page {n}',
      hi: 'पृष्ठ {n}',
      id: 'Halaman {n}',
      pt: 'Página {n}',
    },
    'label.frameN': {
      en: 'Frame {n}',
      ko: '프레임 {n}',
      ja: 'フレーム {n}',
      zh: '帧 {n}',
      ar: 'الإطار {n}',
      es: 'Marco {n}',
      fr: 'Cadre {n}',
      hi: 'फ़्रेम {n}',
      id: 'Bingkai {n}',
      pt: 'Quadro {n}',
    },
    'label.free': {
      en: 'free',
      ko: '비어 있음',
      ja: '空き',
      zh: '空闲',
      ar: 'فارغ',
      es: 'libre',
      fr: 'libre',
      hi: 'खाली',
      id: 'kosong',
      pt: 'livre',
    },
  },
  blocks: {
    stage: { type: 'page-fault-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
