import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 오래 보내면 혼잡 창은 어떤 모양을 그리며, 망이 받아 줄 수 있는 양의 몇 할을 쓰는가.
 *
 * 용량 · 처음 창 · 왕복 수는 예로 정한 값이다.
 */
export const sawtoothFacet: FacetJson = {
  id: 'facet:sawtooth',
  title: {
    en: 'Sawtooth',
    ko: '톱니 패턴',
    ja: 'のこぎり波',
    zh: '锯齿模式',
    ar: 'نمط سن المنشار',
    es: 'Diente de sierra',
    fr: 'Dents de scie',
    hi: 'आरा-दाँत पैटर्न',
    id: 'Pola gigi gergaji',
    pt: 'Dente de serra',
  },
  description: {
    en: 'Round trip after round trip, the congestion window climbs by one and halves when it overflows the network, leaving a repeating sawtooth whose mean stays below capacity.',
    ko: '왕복마다 혼잡 창은 하나씩 오르다 망을 넘치면 절반으로 떨어진다. 남은 값들이 되풀이되는 톱니를 그리고, 그 평균은 용량 아래에 머문다.',
    ja: '往復ごとに輻輳ウィンドウは一つずつ増え、ネットワークを溢れると半分に落ちる。残った値が繰り返すのこぎり波を描き、その平均は容量の下にとどまる。',
    zh: '每个往返中拥塞窗口加一，超出网络容量时减半。留下的值画出重复的锯齿，其平均值低于容量。',
    ar: 'في كل رحلة ذهاب وإياب تزداد نافذة الازدحام بواحد، وتنخفض إلى النصف حين تتجاوز سعة الشبكة، فتترك أسنان منشار متكررة يبقى متوسطها دون السعة.',
    es: 'En cada ida y vuelta la ventana de congestión sube de uno en uno y se reduce a la mitad al desbordar la red, dejando un diente de sierra repetido cuya media queda por debajo de la capacidad.',
    fr: 'À chaque aller-retour, la fenêtre de congestion monte d’un cran et se divise par deux quand elle déborde le réseau, laissant des dents de scie répétées dont la moyenne reste sous la capacité.',
    hi: 'हर राउंड ट्रिप में कंजेशन विंडो एक-एक बढ़ती है और नेटवर्क की क्षमता पार करने पर आधी हो जाती है; बचे मान दोहराते आरा-दाँत बनाते हैं जिनका औसत क्षमता से नीचे रहता है।',
    id: 'Setiap pulang-pergi, jendela kemacetan naik satu dan terbelah dua saat melebihi kapasitas jaringan, meninggalkan gigi gergaji berulang yang rata-ratanya tetap di bawah kapasitas.',
    pt: 'A cada ida e volta a janela de congestionamento sobe de um em um e cai pela metade ao transbordar a rede, deixando um dente de serra repetido cuja média fica abaixo da capacidade.',
  },
  algorithm: 'module:sawtooth',
  scene: 'module:sawtoothScene',
  initialData: {
    type: 'sawtooth',
    capacity: 8,
    startWindow: 4,
    rounds: 13,
    stepMs: 900,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Capacity per round trip: {cap} · starting window: {w}',
      ko: '한 왕복의 용량: {cap} · 처음 창: {w}',
      ja: '1往復あたりの容量: {cap} · 最初のウィンドウ: {w}',
      zh: '每个往返的容量: {cap} · 初始窗口: {w}',
      ar: 'السعة في كل رحلة: {cap} · النافذة الأولى: {w}',
      es: 'Capacidad por ida y vuelta: {cap} · ventana inicial: {w}',
      fr: 'Capacité par aller-retour : {cap} · fenêtre de départ : {w}',
      hi: 'प्रति राउंड ट्रिप क्षमता: {cap} · शुरुआती विंडो: {w}',
      id: 'Kapasitas per pulang-pergi: {cap} · jendela awal: {w}',
      pt: 'Capacidade por ida e volta: {cap} · janela inicial: {w}',
    },
    'caption.rise': {
      en: 'Round trip {r} · window: {w} · no loss · next window: {next}',
      ko: '왕복 {r} · 창: {w} · 잃음 없음 · 다음 창: {next}',
      ja: '往復 {r} · ウィンドウ: {w} · 損失なし · 次のウィンドウ: {next}',
      zh: '往返 {r} · 窗口: {w} · 无丢失 · 下一窗口: {next}',
      ar: 'الرحلة {r} · النافذة: {w} · لا فقد · النافذة التالية: {next}',
      es: 'Ida y vuelta {r} · ventana: {w} · sin pérdida · siguiente ventana: {next}',
      fr: 'Aller-retour {r} · fenêtre : {w} · aucune perte · fenêtre suivante : {next}',
      hi: 'राउंड ट्रिप {r} · विंडो: {w} · कोई हानि नहीं · अगली विंडो: {next}',
      id: 'Pulang-pergi {r} · jendela: {w} · tanpa kehilangan · jendela berikutnya: {next}',
      pt: 'Ida e volta {r} · janela: {w} · sem perda · próxima janela: {next}',
    },
    'caption.loss': {
      en: 'Round trip {r} · window: {w} > capacity: {cap} · loss · next window: {next}',
      ko: '왕복 {r} · 창: {w} > 용량: {cap} · 잃음 · 다음 창: {next}',
      ja: '往復 {r} · ウィンドウ: {w} > 容量: {cap} · 損失 · 次のウィンドウ: {next}',
      zh: '往返 {r} · 窗口: {w} > 容量: {cap} · 丢失 · 下一窗口: {next}',
      ar: 'الرحلة {r} · النافذة: {w} > السعة: {cap} · فقد · النافذة التالية: {next}',
      es: 'Ida y vuelta {r} · ventana: {w} > capacidad: {cap} · pérdida · siguiente ventana: {next}',
      fr: 'Aller-retour {r} · fenêtre : {w} > capacité : {cap} · perte · fenêtre suivante : {next}',
      hi: 'राउंड ट्रिप {r} · विंडो: {w} > क्षमता: {cap} · हानि · अगली विंडो: {next}',
      id: 'Pulang-pergi {r} · jendela: {w} > kapasitas: {cap} · hilang · jendela berikutnya: {next}',
      pt: 'Ida e volta {r} · janela: {w} > capacidade: {cap} · perda · próxima janela: {next}',
    },
    'caption.tooth': {
      en: 'Tooth, round trips {a}–{b} · mean window: {mean} · mean ÷ capacity: {ratio}',
      ko: '톱니, 왕복 {a}–{b} · 평균 창: {mean} · 평균 ÷ 용량: {ratio}',
      ja: 'のこぎりの歯, 往復 {a}–{b} · 平均ウィンドウ: {mean} · 平均 ÷ 容量: {ratio}',
      zh: '一个锯齿, 往返 {a}–{b} · 平均窗口: {mean} · 平均 ÷ 容量: {ratio}',
      ar: 'سن واحد، الرحلات {a}–{b} · متوسط النافذة: {mean} · المتوسط ÷ السعة: {ratio}',
      es: 'Diente, idas y vueltas {a}–{b} · ventana media: {mean} · media ÷ capacidad: {ratio}',
      fr: 'Dent, allers-retours {a}–{b} · fenêtre moyenne : {mean} · moyenne ÷ capacité : {ratio}',
      hi: 'एक दाँत, राउंड ट्रिप {a}–{b} · औसत विंडो: {mean} · औसत ÷ क्षमता: {ratio}',
      id: 'Satu gigi, pulang-pergi {a}–{b} · rata-rata jendela: {mean} · rata-rata ÷ kapasitas: {ratio}',
      pt: 'Dente, idas e voltas {a}–{b} · janela média: {mean} · média ÷ capacidade: {ratio}',
    },
    'label.axisRound': {
      en: 'Round trip',
      ko: '왕복',
      ja: '往復',
      zh: '往返',
      ar: 'الرحلة',
      es: 'Ida y vuelta',
      fr: 'Aller-retour',
      hi: 'राउंड ट्रिप',
      id: 'Pulang-pergi',
      pt: 'Ida e volta',
    },
    'label.axisWindow': {
      en: 'Window (segments)',
      ko: '창 (조각 수)',
      ja: 'ウィンドウ (セグメント数)',
      zh: '窗口 (报文段数)',
      ar: 'النافذة (عدد المقاطع)',
      es: 'Ventana (segmentos)',
      fr: 'Fenêtre (segments)',
      hi: 'विंडो (सेगमेंट)',
      id: 'Jendela (segmen)',
      pt: 'Janela (segmentos)',
    },
    'label.capacity': {
      en: 'Capacity: {cap}',
      ko: '용량: {cap}',
      ja: '容量: {cap}',
      zh: '容量: {cap}',
      ar: 'السعة: {cap}',
      es: 'Capacidad: {cap}',
      fr: 'Capacité : {cap}',
      hi: 'क्षमता: {cap}',
      id: 'Kapasitas: {cap}',
      pt: 'Capacidade: {cap}',
    },
    'label.mean': {
      en: 'Mean: {mean}',
      ko: '평균: {mean}',
      ja: '平均: {mean}',
      zh: '平均: {mean}',
      ar: 'المتوسط: {mean}',
      es: 'Media: {mean}',
      fr: 'Moyenne : {mean}',
      hi: 'औसत: {mean}',
      id: 'Rata-rata: {mean}',
      pt: 'Média: {mean}',
    },
  },
  blocks: {
    stage: { type: 'sawtooth-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
