import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 함수를 부른 뒤에도 바깥은 부르기 전 그대로인가.
 *
 * `add` 와 `addTracked` 는 같은 인자에 같은 값을 돌려준다. 다른 것은 바깥이다 — `addTracked` 의
 * 몸은 `let` 없이 `calls` 에 넣어 바깥 이름을 바꾼다. 그 쓰기가 방의 벽을 뚫고 바깥에 자국으로 남는다.
 */
export const noSideEffectFacet: FacetJson = {
  id: 'facet:noSideEffect',
  title: {
    en: 'No side effect',
    ko: '부수 효과 없음',
    ja: '副作用なし',
    zh: '无副作用',
    ar: 'بلا أثر جانبي',
    es: 'Sin efectos secundarios',
    fr: 'Sans effet de bord',
    hi: 'कोई साइड इफ़ेक्ट नहीं',
    id: 'Tanpa efek samping',
    pt: 'Sem efeito colateral',
  },
  description: {
    en: 'Both functions return the same value. Only one of them changes the outside every time it is called.',
    ko: '두 함수는 같은 값을 돌려준다. 그중 하나만 부를 때마다 바깥을 바꿔 놓는다.',
    ja: '二つの関数は同じ値を返す。そのうち一つだけが、呼ぶたびに外側を書き換える。',
    zh: '两个函数返回相同的值。只有其中一个每次被调用时都会改变外部。',
    ar: 'تُعيد الدالتان القيمة نفسها. واحدة منهما فقط تغيّر ما في الخارج في كل مرة تُستدعى.',
    es: 'Las dos funciones devuelven el mismo valor. Solo una de ellas cambia el exterior cada vez que se llama.',
    fr: 'Les deux fonctions renvoient la même valeur. Une seule modifie l’extérieur à chaque appel.',
    hi: 'दोनों फ़ंक्शन एक ही मान लौटाते हैं। उनमें से सिर्फ़ एक हर बार बुलाए जाने पर बाहर को बदल देता है।',
    id: 'Kedua fungsi mengembalikan nilai yang sama. Hanya salah satunya yang mengubah bagian luar setiap kali dipanggil.',
    pt: 'As duas funções devolvem o mesmo valor. Só uma delas muda o exterior a cada chamada.',
  },
  algorithm: 'module:noSideEffect',
  scene: 'module:noSideEffectScene',
  initialData: {
    type: 'no-side-effect',
    stepMs: 1500,
    lines: [
      { indent: 0, text: 'let calls = 0', stmt: { k: 'assign', to: 'calls', value: { num: 0 }, declare: true } },
      { indent: 0, text: 'function add(a, b)', stmt: { k: 'function', name: 'add', params: ['a', 'b'] } },
      { indent: 1, text: 'return a + b', stmt: { k: 'return', value: { op: '+', l: { var: 'a' }, r: { var: 'b' } } } },
      { indent: 0, text: 'function addTracked(a, b)', stmt: { k: 'function', name: 'addTracked', params: ['a', 'b'] } },
      {
        indent: 1,
        text: 'calls = calls + 1',
        stmt: { k: 'assign', to: 'calls', value: { op: '+', l: { var: 'calls' }, r: { num: 1 } } },
      },
      { indent: 1, text: 'return a + b', stmt: { k: 'return', value: { op: '+', l: { var: 'a' }, r: { var: 'b' } } } },
      { indent: 0, text: 'show add(2, 3)', stmt: { k: 'show', value: { call: 'add', args: [{ num: 2 }, { num: 3 }] } } },
      {
        indent: 0,
        text: 'show addTracked(2, 3)',
        stmt: { k: 'show', value: { call: 'addTracked', args: [{ num: 2 }, { num: 3 }] } },
      },
      { indent: 0, text: 'show add(2, 3)', stmt: { k: 'show', value: { call: 'add', args: [{ num: 2 }, { num: 3 }] } } },
      {
        indent: 0,
        text: 'show addTracked(2, 3)',
        stmt: { k: 'show', value: { call: 'addTracked', args: [{ num: 2 }, { num: 3 }] } },
      },
      { indent: 0, text: 'show calls', stmt: { k: 'show', value: { var: 'calls' } } },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Start — no line has run yet.',
      ko: '시작 — 아직 어느 줄도 실행하지 않았다.',
      ja: '開始 — まだどの行も実行していない。',
      zh: '开始 — 还没有执行任何一行。',
      ar: 'البداية — لم يُنفَّذ أي سطر بعد.',
      es: 'Inicio: todavía no se ha ejecutado ninguna línea.',
      fr: 'Départ — aucune ligne n’a encore été exécutée.',
      hi: 'शुरुआत — अभी तक कोई पंक्ति नहीं चली।',
      id: 'Mulai — belum ada baris yang dijalankan.',
      pt: 'Início — nenhuma linha foi executada ainda.',
    },
    'caption.declare': {
      en: 'Outer name {name} starts at {value}.',
      ko: '바깥 이름 {name} — 처음 값 {value}.',
      ja: '外側の名前 {name} — 最初の値 {value}。',
      zh: '外部名字 {name} — 初始值 {value}。',
      ar: 'الاسم الخارجي {name} — قيمته الأولى {value}.',
      es: 'Nombre exterior {name}: valor inicial {value}.',
      fr: 'Nom extérieur {name} — valeur de départ {value}.',
      hi: 'बाहरी नाम {name} — शुरुआती मान {value}।',
      id: 'Nama luar {name} — nilai awal {value}.',
      pt: 'Nome externo {name} — valor inicial {value}.',
    },
    'caption.clean': {
      en: '{call} returned {out}. Outside: {change}.',
      ko: '{call} → {out}. 바깥 {change}.',
      ja: '{call} → {out}。外側 {change}。',
      zh: '{call} → {out}。外部 {change}。',
      ar: '{call} ← {out}. الخارج: {change}.',
      es: '{call} devolvió {out}. Exterior: {change}.',
      fr: '{call} a renvoyé {out}. Extérieur : {change}.',
      hi: '{call} → {out}। बाहर: {change}।',
      id: '{call} mengembalikan {out}. Luar: {change}.',
      pt: '{call} devolveu {out}. Exterior: {change}.',
    },
    'caption.marked': {
      en: '{call} returned {out}. Its body wrote to the outside — {writes}.',
      ko: '{call} → {out}. 몸 안에서 바깥에 썼다 — {writes}.',
      ja: '{call} → {out}。本体の中から外側に書き込んだ — {writes}。',
      zh: '{call} → {out}。函数体里写入了外部 — {writes}。',
      ar: '{call} ← {out}. كتب جسمها إلى الخارج — {writes}.',
      es: '{call} devolvió {out}. Su cuerpo escribió en el exterior: {writes}.',
      fr: '{call} a renvoyé {out}. Son corps a écrit à l’extérieur — {writes}.',
      hi: '{call} → {out}। उसके भीतर से बाहर लिखा गया — {writes}।',
      id: '{call} mengembalikan {out}. Badannya menulis ke luar — {writes}.',
      pt: '{call} devolveu {out}. O corpo escreveu no exterior — {writes}.',
    },
    'caption.show': {
      en: '{code} printed {out}. Calls that marked the outside: {marked} · calls that did not: {clean}.',
      ko: '{code} → {out}. 바깥에 자국을 남긴 부르기 {marked} · 남기지 않은 부르기 {clean}.',
      ja: '{code} → {out}。外側に跡を残した呼び出し {marked} · 残さなかった呼び出し {clean}。',
      zh: '{code} → {out}。在外部留下痕迹的调用 {marked} · 没有留下的调用 {clean}。',
      ar: '{code} ← {out}. استدعاءات تركت أثرًا في الخارج: {marked} · لم تترك: {clean}.',
      es: '{code} mostró {out}. Llamadas que dejaron marca fuera: {marked} · que no: {clean}.',
      fr: '{code} a affiché {out}. Appels qui ont marqué l’extérieur : {marked} · sans marque : {clean}.',
      hi: '{code} → {out}। बाहर निशान छोड़ने वाली कॉल: {marked} · न छोड़ने वाली: {clean}।',
      id: '{code} menampilkan {out}. Panggilan yang meninggalkan bekas di luar: {marked} · yang tidak: {clean}.',
      pt: '{code} mostrou {out}. Chamadas que marcaram o exterior: {marked} · que não marcaram: {clean}.',
    },
    'label.outer': {
      en: 'Outside',
      ko: '바깥',
      ja: '外側',
      zh: '外部',
      ar: 'الخارج',
      es: 'Exterior',
      fr: 'Extérieur',
      hi: 'बाहर',
      id: 'Luar',
      pt: 'Exterior',
    },
    'label.output': {
      en: 'Output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المُخرَج',
      es: 'Salida',
      fr: 'Sortie',
      hi: 'आउटपुट',
      id: 'Keluaran',
      pt: 'Saída',
    },
  },
  blocks: {
    stage: { type: 'no-side-effect-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
