import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

const I = (v: number) => ({ k: 'int', v });
const V = (name: string) => ({ k: 'var', name });
const O = (op: string, l: unknown, r: unknown) => ({ k: 'op', op, l, r });
const C = (name: string, ...args: unknown[]) => ({ k: 'call', name, args });

/**
 * @piece
 * 질문: 컴파일러는 글을 읽어 내려가며 선언을 어디에 적고, 몸을 벗어나면 적은 것은 어떻게 되는가.
 */
export const tablePerScopeFacet: FacetJson = {
  id: 'facet:tablePerScope',
  title: {
    en: 'A table per scope',
    ko: '스코프마다 표 하나',
    ja: 'スコープごとに表をひとつ',
    zh: '每个作用域一张表',
    ar: 'جدول لكل نطاق',
    es: 'Una tabla por ámbito',
    fr: 'Une table par portée',
    hi: 'हर स्कोप की एक तालिका',
    id: 'Satu tabel per cakupan',
    pt: 'Uma tabela por escopo',
  },
  description: {
    en: 'Reading the program once from top to bottom, the compiler stacks a name table for each body, writes each declaration into the top table, and removes the whole top table when the body ends.',
    ko: '컴파일러는 프로그램을 위에서 아래로 한 번 읽으며 몸마다 이름 표를 얹고, 선언을 맨 위 표에 적고, 몸이 끝나면 맨 위 표를 통째로 걷는다.',
    ja: 'コンパイラはプログラムを上から下へ一度読み、本体ごとに名前の表を積み、宣言を一番上の表に書き、本体が終わると一番上の表を丸ごと取り除く。',
    zh: '编译器从上到下读一遍程序，每进入一个代码体就叠上一张名字表，把声明写进最上面的表，代码体结束时把最上面的表整张撤走。',
    ar: 'يقرأ المترجم البرنامج مرة واحدة من الأعلى إلى الأسفل، فيضع جدول أسماء لكل جسم، ويكتب كل تصريح في الجدول العلوي، ويزيل الجدول العلوي كله عند انتهاء الجسم.',
    es: 'Al leer el programa una vez de arriba abajo, el compilador apila una tabla de nombres por cada cuerpo, escribe cada declaración en la tabla superior y retira entera la tabla superior cuando el cuerpo termina.',
    fr: 'En lisant le programme une fois de haut en bas, le compilateur empile une table de noms par corps, inscrit chaque déclaration dans la table du dessus et retire entièrement celle-ci quand le corps se termine.',
    hi: 'कंपाइलर प्रोग्राम को ऊपर से नीचे एक बार पढ़ते हुए हर बॉडी के लिए नामों की एक तालिका रखता है, हर घोषणा सबसे ऊपर की तालिका में लिखता है, और बॉडी खत्म होने पर सबसे ऊपर की तालिका पूरी हटा देता है।',
    id: 'Sambil membaca program sekali dari atas ke bawah, kompiler menumpuk tabel nama untuk tiap badan, menulis tiap deklarasi di tabel teratas, dan mengangkat seluruh tabel teratas saat badan berakhir.',
    pt: 'Lendo o programa uma vez de cima para baixo, o compilador empilha uma tabela de nomes para cada corpo, escreve cada declaração na tabela do topo e retira inteira a tabela do topo quando o corpo termina.',
  },
  algorithm: 'module:tablePerScope',
  scene: 'module:tablePerScopeScene',
  initialData: {
    type: 'table-per-scope',
    stepMs: 1000,
    lines: [
      { indent: 0, text: 'let limit = 3', stmt: { k: 'let', name: 'limit', value: I(3) } },
      { indent: 0, text: 'function scale(x)', stmt: { k: 'function', name: 'scale', params: ['x'] } },
      { indent: 1, text: 'let factor = 2', stmt: { k: 'let', name: 'factor', value: I(2) } },
      { indent: 1, text: 'return x * factor', stmt: { k: 'return', value: O('*', V('x'), V('factor')) } },
      { indent: 0, text: 'for i from 1 to limit', stmt: { k: 'for', var: 'i', lo: I(1), hi: V('limit') } },
      { indent: 1, text: 'let y = scale(i)', stmt: { k: 'let', name: 'y', value: C('scale', V('i')) } },
      { indent: 1, text: 'if y > limit', stmt: { k: 'if', cond: O('>', V('y'), V('limit')) } },
      { indent: 2, text: 'let big = y', stmt: { k: 'let', name: 'big', value: V('y') } },
      { indent: 2, text: 'show big', stmt: { k: 'show', value: V('big') } },
      { indent: 0, text: 'show limit', stmt: { k: 'show', value: V('limit') } },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Reading starts at the top. One table is already there: the outermost.',
      ko: '위에서부터 읽기 시작한다. 표 하나는 이미 있다 — 맨 바깥 표.',
      ja: '上から読み始める。表はすでにひとつある — 一番外側の表。',
      zh: '从最上面开始读。已经有一张表 — 最外层的表。',
      ar: 'تبدأ القراءة من الأعلى. هناك جدول موجود بالفعل: الجدول الخارجي.',
      es: 'La lectura empieza arriba. Ya hay una tabla: la más externa.',
      fr: 'La lecture commence en haut. Une table est déjà là : la plus externe.',
      hi: 'पढ़ना ऊपर से शुरू होता है। एक तालिका पहले से है: सबसे बाहरी।',
      id: 'Pembacaan mulai dari atas. Satu tabel sudah ada: yang terluar.',
      pt: 'A leitura começa no topo. Uma tabela já está lá: a mais externa.',
    },
    'caption.open': {
      en: 'L{line}: a body opens. The {scope} table goes on top.',
      ko: 'L{line}: 몸이 열린다. {scope} 표를 맨 위에 얹는다.',
      ja: 'L{line}: 本体が始まる。{scope} の表を一番上に積む。',
      zh: 'L{line}：一个代码体开始。把 {scope} 的表叠在最上面。',
      ar: 'L{line}: يبدأ جسم. يوضع جدول {scope} في الأعلى.',
      es: 'L{line}: se abre un cuerpo. La tabla «{scope}» va encima.',
      fr: 'L{line} : un corps s’ouvre. La table « {scope} » se pose au-dessus.',
      hi: 'L{line}: एक बॉडी खुलती है। {scope} की तालिका सबसे ऊपर रखी जाती है।',
      id: 'L{line}: sebuah badan dibuka. Tabel {scope} ditaruh di atas.',
      pt: 'L{line}: um corpo se abre. A tabela “{scope}” vai para o topo.',
    },
    'caption.openWith': {
      en: 'L{line}: a body opens. The {scope} table goes on top, already holding: {names}',
      ko: 'L{line}: 몸이 열린다. {scope} 표를 맨 위에 얹는다. 처음부터 든 이름: {names}',
      ja: 'L{line}: 本体が始まる。{scope} の表を一番上に積む。最初から入っている名前: {names}',
      zh: 'L{line}：一个代码体开始。把 {scope} 的表叠在最上面，表里一开始就有：{names}',
      ar: 'L{line}: يبدأ جسم. يوضع جدول {scope} في الأعلى، وفيه منذ البداية: {names}',
      es: 'L{line}: se abre un cuerpo. La tabla «{scope}» va encima, ya con: {names}',
      fr: 'L{line} : un corps s’ouvre. La table « {scope} » se pose au-dessus, avec déjà : {names}',
      hi: 'L{line}: एक बॉडी खुलती है। {scope} की तालिका सबसे ऊपर रखी जाती है, शुरू से इसमें: {names}',
      id: 'L{line}: sebuah badan dibuka. Tabel {scope} ditaruh di atas, sudah berisi: {names}',
      pt: 'L{line}: um corpo se abre. A tabela “{scope}” vai para o topo, já com: {names}',
    },
    'caption.declare': {
      en: 'L{line} declares {name}. It is written in the top table: {scope}.',
      ko: 'L{line}: 선언 {name}. 맨 위 표({scope})에 적는다.',
      ja: 'L{line}: 宣言 {name}。一番上の表（{scope}）に書く。',
      zh: 'L{line}：声明 {name}。写进最上面的表（{scope}）。',
      ar: 'L{line} يصرّح بـ {name}. يُكتب في الجدول العلوي: {scope}.',
      es: 'L{line} declara {name}. Se escribe en la tabla superior: {scope}.',
      fr: 'L{line} déclare {name}. Le nom s’inscrit dans la table du dessus : {scope}.',
      hi: 'L{line} में घोषणा: {name}। यह सबसे ऊपर की तालिका ({scope}) में लिखा जाता है।',
      id: 'L{line} mendeklarasikan {name}. Ditulis di tabel teratas: {scope}.',
      pt: 'L{line} declara {name}. É escrito na tabela do topo: {scope}.',
    },
    'caption.close': {
      en: 'After L{line}, a body ends. The {scope} table comes off with every name in it.',
      ko: 'L{line} 뒤: 몸이 끝난다. {scope} 표를 적힌 이름째 걷는다.',
      ja: 'L{line} の後: 本体が終わる。{scope} の表を書かれた名前ごと取り除く。',
      zh: 'L{line} 之后：代码体结束。{scope} 的表连同里面的名字整张撤走。',
      ar: 'بعد L{line} ينتهي جسم. يُزال جدول {scope} بكل الأسماء التي فيه.',
      es: 'Tras L{line}, un cuerpo termina. La tabla «{scope}» se retira con todos sus nombres.',
      fr: 'Après L{line}, un corps se termine. La table « {scope} » est retirée avec tous ses noms.',
      hi: 'L{line} के बाद एक बॉडी खत्म होती है। {scope} की तालिका अपने सभी नामों समेत हटा दी जाती है।',
      id: 'Setelah L{line}, sebuah badan berakhir. Tabel {scope} diangkat beserta semua nama di dalamnya.',
      pt: 'Depois de L{line}, um corpo termina. A tabela “{scope}” sai com todos os nomes nela.',
    },
    'label.scope.top': {
      en: 'outermost',
      ko: '맨 바깥',
      ja: '一番外側',
      zh: '最外层',
      ar: 'الخارجي',
      es: 'exterior',
      fr: 'extérieur',
      hi: 'सबसे बाहरी',
      id: 'terluar',
      pt: 'externo',
    },
    'label.scope.function': {
      en: '{name} body',
      ko: '{name} 의 몸',
      ja: '{name} の本体',
      zh: '{name} 的代码体',
      ar: 'جسم {name}',
      es: 'cuerpo de {name}',
      fr: 'corps de {name}',
      hi: '{name} की बॉडी',
      id: 'badan {name}',
      pt: 'corpo de {name}',
    },
    'label.scope.for': {
      en: 'for body',
      ko: 'for 의 몸',
      ja: 'for の本体',
      zh: 'for 的代码体',
      ar: 'جسم for',
      es: 'cuerpo de for',
      fr: 'corps de for',
      hi: 'for की बॉडी',
      id: 'badan for',
      pt: 'corpo de for',
    },
    'label.scope.if': {
      en: 'if body',
      ko: 'if 의 몸',
      ja: 'if の本体',
      zh: 'if 的代码体',
      ar: 'جسم if',
      es: 'cuerpo de if',
      fr: 'corps de if',
      hi: 'if की बॉडी',
      id: 'badan if',
      pt: 'corpo de if',
    },
    'label.span': {
      en: 'L{from}–L{to}',
      ko: 'L{from}–L{to}',
      ja: 'L{from}–L{to}',
      zh: 'L{from}–L{to}',
      ar: 'L{from}–L{to}',
      es: 'L{from}–L{to}',
      fr: 'L{from}–L{to}',
      hi: 'L{from}–L{to}',
      id: 'L{from}–L{to}',
      pt: 'L{from}–L{to}',
    },
    'label.line': {
      en: 'L{n}',
      ko: 'L{n}',
      ja: 'L{n}',
      zh: 'L{n}',
      ar: 'L{n}',
      es: 'L{n}',
      fr: 'L{n}',
      hi: 'L{n}',
      id: 'L{n}',
      pt: 'L{n}',
    },
    'label.empty': {
      en: 'no names yet',
      ko: '아직 이름 없음',
      ja: 'まだ名前なし',
      zh: '还没有名字',
      ar: 'لا أسماء بعد',
      es: 'aún sin nombres',
      fr: 'aucun nom pour l’instant',
      hi: 'अभी कोई नाम नहीं',
      id: 'belum ada nama',
      pt: 'ainda sem nomes',
    },
    'label.stacked': {
      en: 'Tables stacked: {n}',
      ko: '쌓인 표: {n}',
      ja: '積まれた表: {n}',
      zh: '叠着的表：{n}',
      ar: 'الجداول المكدّسة: {n}',
      es: 'Tablas apiladas: {n}',
      fr: 'Tables empilées : {n}',
      hi: 'रखी गई तालिकाएँ: {n}',
      id: 'Tabel bertumpuk: {n}',
      pt: 'Tabelas empilhadas: {n}',
    },
  },
  blocks: {
    stage: { type: 'table-per-scope-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
