/**
 * 덜 뒤지면 놓친다 — 빠를수록 빠뜨리는 것이 는다.
 *
 * @piece
 *
 * 선언에 두는 것은 구조다 — 점 스물넷의 좌표, 무리 넷의 대표, 질의, 찾을 개수.
 * 거리 · 본 점 수 · 재현율은 algorithm 이 셈하고, 자리는 stage 가 역산한다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const recallSpeedTradeoffFacet: FacetJson = {
  id: 'facet:recallSpeedTradeoff',
  title: {
    en: 'Search less, miss more',
    ko: '덜 뒤지면 놓친다',
    ja: '探す範囲を狭めると取りこぼす',
    zh: '搜得越少，漏得越多',
    ar: 'كلما قلّ البحث زاد ما يفوتك',
    es: 'Buscar menos, perder más',
    fr: 'Chercher moins, en manquer plus',
    hi: 'कम खोजें, ज़्यादा छूटे',
    id: 'Cari lebih sedikit, lebih banyak terlewat',
    pt: 'Buscar menos, perder mais',
  },
  description: {
    en: 'The five truly nearest are fixed. Search fewer cells and some of them slip out of the answer while farther points take their seats.',
    ko: '참으로 가까운 다섯은 정해져 있다. 덜 뒤지면 그중 몇이 답에서 빠져나가고 더 먼 것이 그 자리를 메운다.',
    ja: '本当に近い五つは決まっている。探す範囲を狭めると、そのうちいくつかが答えから抜け、より遠い点がその席を埋める。',
    zh: '真正最近的五个是固定的。少搜几个格子，其中一些就会从答案中滑出，由更远的点占据它们的座位。',
    ar: 'الأقرب خمسة حقًا محددة. ابحث في خلايا أقل فينزلق بعضها خارج الإجابة وتأخذ نقاط أبعد مقاعدها.',
    es: 'Los cinco verdaderamente más cercanos están fijados. Busca en menos celdas y algunos se escapan de la respuesta mientras puntos más lejanos ocupan sus asientos.',
    fr: 'Les cinq vraiment les plus proches sont fixés. Cherchez dans moins de cellules et certains glissent hors de la réponse tandis que des points plus lointains prennent leur place.',
    hi: 'सचमुच सबसे नज़दीकी पाँच तय हैं। कम खानों में खोजें तो उनमें से कुछ उत्तर से फिसल जाते हैं और दूर के बिंदु उनकी जगह ले लेते हैं।',
    id: 'Lima yang benar-benar terdekat sudah tetap. Cari di lebih sedikit sel dan beberapa di antaranya terlepas dari jawaban sementara titik yang lebih jauh mengambil kursinya.',
    pt: 'Os cinco verdadeiramente mais próximos estão fixados. Busque em menos células e alguns escapam da resposta enquanto pontos mais distantes ocupam seus assentos.',
  },
  algorithm: 'module:recallSpeedTradeoff',
  projector: 'module:recallSpeedTradeoffProjector',
  initialData: {
    type: 'recall-speed-tradeoff',
    points: [
      { x: 2, y: 2, cell: 0 },
      { x: 3, y: 1, cell: 0 },
      { x: 1, y: 3, cell: 0 },
      { x: 3, y: 3, cell: 0 },
      { x: 2, y: 4, cell: 0 },
      { x: 4, y: 2, cell: 0 },
      { x: 9, y: 2, cell: 1 },
      { x: 10, y: 3, cell: 1 },
      { x: 11, y: 1, cell: 1 },
      { x: 10, y: 1, cell: 1 },
      { x: 9, y: 4, cell: 1 },
      { x: 11, y: 3, cell: 1 },
      { x: 2, y: 10, cell: 2 },
      { x: 3, y: 11, cell: 2 },
      { x: 1, y: 9, cell: 2 },
      { x: 3, y: 9, cell: 2 },
      { x: 2, y: 12, cell: 2 },
      { x: 4, y: 10, cell: 2 },
      { x: 9, y: 10, cell: 3 },
      { x: 10, y: 11, cell: 3 },
      { x: 11, y: 9, cell: 3 },
      { x: 10, y: 9, cell: 3 },
      { x: 9, y: 12, cell: 3 },
      { x: 11, y: 11, cell: 3 },
    ],
    cells: [
      { x: 2.5, y: 2.5 },
      { x: 10, y: 2.3 },
      { x: 2.5, y: 10.2 },
      { x: 10, y: 10.3 },
    ],
    query: { x: 6, y: 6 },
    k: 5,
    stepMs: 900,
  },
  blocks: {
    stage: { type: 'recall-speed-tradeoff-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'label.probe': {
      en: 'Cells opened {opened}/{cells} · points seen {seen}/{total}',
      ko: '연 칸 {opened}/{cells} · 본 점 {seen}/{total}',
      ja: '開いた区画 {opened}/{cells} · 見た点 {seen}/{total}',
      zh: '已开格子 {opened}/{cells} · 已看点 {seen}/{total}',
      ar: 'الخلايا المفتوحة {opened}/{cells} · النقاط المفحوصة {seen}/{total}',
      es: 'Celdas abiertas {opened}/{cells} · puntos vistos {seen}/{total}',
      fr: 'Cellules ouvertes {opened}/{cells} · points vus {seen}/{total}',
      hi: 'खोले गए खाने {opened}/{cells} · देखे गए बिंदु {seen}/{total}',
      id: 'Sel dibuka {opened}/{cells} · titik dilihat {seen}/{total}',
      pt: 'Células abertas {opened}/{cells} · pontos vistos {seen}/{total}',
    },
    'label.recall': {
      en: 'recall',
      ko: '재현율',
      ja: '再現率',
      zh: '召回率',
      ar: 'الاستدعاء',
      es: 'exhaustividad',
      fr: 'rappel',
      hi: 'रिकॉल',
      id: 'recall',
      pt: 'revocação',
    },
    'caption.truth': {
      en: 'The five truly nearest are fixed — the answer should be exactly these.',
      ko: '참으로 가까운 다섯이 정해져 있다 — 답은 이 다섯이어야 한다.',
      ja: '本当に近い五つは決まっている — 答えはこの五つであるべきだ。',
      zh: '真正最近的五个是固定的 — 答案应当正是这五个。',
      ar: 'الأقرب خمسة حقًا محددة — يجب أن تكون الإجابة هي هذه الخمسة بالضبط.',
      es: 'Los cinco verdaderamente más cercanos están fijados: la respuesta debería ser exactamente estos.',
      fr: 'Les cinq vraiment les plus proches sont fixés — la réponse devrait être exactement ceux-là.',
      hi: 'सचमुच सबसे नज़दीकी पाँच तय हैं — उत्तर ठीक यही पाँच होने चाहिए।',
      id: 'Lima yang benar-benar terdekat sudah tetap — jawabannya harus tepat kelima ini.',
      pt: 'Os cinco verdadeiramente mais próximos estão fixados — a resposta deveria ser exatamente estes.',
    },
    'caption.miss': {
      en: 'Points seen: {seen}. Missing from the true nearest: {missed}. Recall: {recall}%.',
      ko: '본 점 {seen}. 참값에서 빠진 것 {missed}. 재현율 {recall}%.',
      ja: '見た点 {seen}。本当に近いものから抜けた数 {missed}。再現率 {recall}%。',
      zh: '已看点 {seen}。从真正最近者中漏掉 {missed}。召回率 {recall}%。',
      ar: 'النقاط المفحوصة: {seen}. المفقود من الأقرب حقًا: {missed}. الاستدعاء: {recall}%.',
      es: 'Puntos vistos: {seen}. Faltan de los verdaderos más cercanos: {missed}. Exhaustividad: {recall}%.',
      fr: 'Points vus : {seen}. Manquants parmi les vrais plus proches : {missed}. Rappel : {recall}%.',
      hi: 'देखे गए बिंदु: {seen}. सच्चे निकटतम में से छूटे: {missed}. रिकॉल: {recall}%.',
      id: 'Titik dilihat: {seen}. Hilang dari yang benar-benar terdekat: {missed}. Recall: {recall}%.',
      pt: 'Pontos vistos: {seen}. Faltando dos verdadeiros mais próximos: {missed}. Revocação: {recall}%.',
    },
    'caption.full': {
      en: 'Points seen: {seen}. Nothing is missing. Recall: {recall}%.',
      ko: '본 점 {seen}. 빠진 것 없다. 재현율 {recall}%.',
      ja: '見た点 {seen}。抜けたものはない。再現率 {recall}%。',
      zh: '已看点 {seen}。没有遗漏。召回率 {recall}%。',
      ar: 'النقاط المفحوصة: {seen}. لا شيء مفقود. الاستدعاء: {recall}%.',
      es: 'Puntos vistos: {seen}. No falta nada. Exhaustividad: {recall}%.',
      fr: 'Points vus : {seen}. Rien ne manque. Rappel : {recall}%.',
      hi: 'देखे गए बिंदु: {seen}. कुछ नहीं छूटा। रिकॉल: {recall}%.',
      id: 'Titik dilihat: {seen}. Tidak ada yang hilang. Recall: {recall}%.',
      pt: 'Pontos vistos: {seen}. Nada está faltando. Revocação: {recall}%.',
    },
    'caption.done': {
      en: 'Search less and you miss more — a farther point takes the empty seat.',
      ko: '덜 뒤질수록 빠뜨리는 것이 는다 — 빈자리는 더 먼 것이 메운다.',
      ja: '探す量が少ないほど取りこぼしは増える — 空いた席はより遠い点が埋める。',
      zh: '搜得越少，漏得越多 — 空出的座位由更远的点填补。',
      ar: 'كلما بحثت أقل زاد ما يفوتك — نقطة أبعد تشغل المقعد الفارغ.',
      es: 'Cuanto menos buscas, más pierdes: un punto más lejano ocupa el asiento vacío.',
      fr: 'Moins on cherche, plus on en manque — un point plus lointain prend la place vide.',
      hi: 'जितना कम खोजेंगे, उतना ज़्यादा छूटेगा — खाली जगह को दूर का बिंदु भर देता है।',
      id: 'Semakin sedikit mencari, semakin banyak terlewat — titik yang lebih jauh mengisi kursi kosong.',
      pt: 'Quanto menos você busca, mais perde — um ponto mais distante ocupa o assento vazio.',
    },
  },
};
