/**
 * @piece
 * @notation native
 *
 * 같은 질의를 다른 차례로 풀면 답도 달라지는가.
 *
 * SQL 은 그 자체가 소재라 그대로 둔다 (질의 언어 자체가 주장의 소재 — tasks/pseudo-notation.md 적용 범위).
 * 표 · 줄 · 값은 예로 정한 작은 자료다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const sameAnswerDifferentPlanFacet: FacetJson = {
  id: 'facet:sameAnswerDifferentPlan',
  title: {
    en: 'Same answer, different plan',
    ko: '같은 답, 다른 길',
    ja: '同じ答え、違う計画',
    zh: '同样的答案，不同的计划',
    ar: 'الجواب نفسه، خطة مختلفة',
    es: 'Misma respuesta, otro plan',
    fr: 'Même réponse, autre plan',
    hi: 'वही उत्तर, अलग योजना',
    id: 'Jawaban sama, rencana berbeda',
    pt: 'Mesma resposta, outro plano',
  },
  description: {
    en: 'One query run in two orders — join then filter, or filter then join. The answer rows land on each other; the check counts do not.',
    ko: '한 질의를 두 차례로 푼다 — 잇고 나서 거르거나, 거르고 나서 잇는다. 답의 줄은 서로 포개지고 검사 수는 포개지지 않는다.',
    ja: '一つの問い合わせを二つの順序で実行する — 結合してから絞り込むか、絞り込んでから結合するか。答えの行は重なり、検査の回数は重ならない。',
    zh: '同一个查询用两种顺序执行——先连接后过滤，或先过滤后连接。答案的行彼此重合，检查次数却不重合。',
    ar: 'استعلام واحد يُنفَّذ بترتيبين — ربط ثم تصفية، أو تصفية ثم ربط. صفوف الجواب تنطبق بعضها على بعض، أما عدد الفحوص فلا.',
    es: 'Una consulta en dos órdenes: unir y luego filtrar, o filtrar y luego unir. Las filas de la respuesta se superponen; el número de comprobaciones no.',
    fr: 'Une requête exécutée dans deux ordres : joindre puis filtrer, ou filtrer puis joindre. Les lignes de la réponse se superposent ; le nombre de vérifications, non.',
    hi: 'एक क्वेरी दो क्रमों में — पहले जोड़ो फिर छानो, या पहले छानो फिर जोड़ो। उत्तर की पंक्तियाँ एक-दूसरे पर बैठ जाती हैं; जाँचों की गिनती नहीं।',
    id: 'Satu kueri dijalankan dalam dua urutan — gabung lalu saring, atau saring lalu gabung. Baris jawaban saling menumpuk; jumlah pemeriksaan tidak.',
    pt: 'Uma consulta em duas ordens: juntar e depois filtrar, ou filtrar e depois juntar. As linhas da resposta se sobrepõem; a contagem de verificações não.',
  },
  algorithm: 'module:sameAnswerDifferentPlan',
  scene: 'module:sameAnswerDifferentPlanScene',
  initialData: {
    type: 'same-answer-different-plan',
    stepMs: 1800,
    sql: [
      'SELECT o.id, c.name',
      'FROM orders o JOIN customers c ON o.cust_id = c.id',
      "WHERE c.city = 'Busan'",
    ],
    orders: {
      table: 'orders',
      rows: [
        { id: 101, custId: 1 },
        { id: 102, custId: 2 },
        { id: 103, custId: 3 },
        { id: 104, custId: 2 },
        { id: 105, custId: 1 },
        { id: 106, custId: 4 },
        { id: 107, custId: 3 },
        { id: 108, custId: 1 },
      ],
    },
    customers: {
      table: 'customers',
      rows: [
        { id: 1, name: 'Ana', city: 'Seoul' },
        { id: 2, name: 'Ben', city: 'Busan' },
        { id: 3, name: 'Cho', city: 'Daegu' },
        { id: 4, name: 'Dev', city: 'Busan' },
      ],
    },
    joinOn: 'o.cust_id = c.id',
    where: { text: "c.city = 'Busan'", city: 'Busan' },
    paths: [
      { id: 'join-first', ops: ['join', 'filter'] },
      { id: 'filter-first', ops: ['filter', 'join'] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'path.joinFirst': {
      en: 'Join, then filter',
      ko: '잇고 나서 거르기',
      ja: '結合してから絞り込む',
      zh: '先连接，后过滤',
      ar: 'ربط ثم تصفية',
      es: 'Unir y luego filtrar',
      fr: 'Joindre puis filtrer',
      hi: 'पहले जोड़ो, फिर छानो',
      id: 'Gabung, lalu saring',
      pt: 'Juntar e depois filtrar',
    },
    'path.filterFirst': {
      en: 'Filter, then join',
      ko: '거르고 나서 잇기',
      ja: '絞り込んでから結合する',
      zh: '先过滤，后连接',
      ar: 'تصفية ثم ربط',
      es: 'Filtrar y luego unir',
      fr: 'Filtrer puis joindre',
      hi: 'पहले छानो, फिर जोड़ो',
      id: 'Saring, lalu gabung',
      pt: 'Filtrar e depois juntar',
    },
    'role.join': {
      en: 'Join',
      ko: '잇기',
      ja: '結合',
      zh: '连接',
      ar: 'ربط',
      es: 'Unir',
      fr: 'Joindre',
      hi: 'जोड़',
      id: 'Gabung',
      pt: 'Juntar',
    },
    'role.filter': {
      en: 'Filter',
      ko: '거르기',
      ja: '絞り込み',
      zh: '过滤',
      ar: 'تصفية',
      es: 'Filtrar',
      fr: 'Filtrer',
      hi: 'छानना',
      id: 'Saring',
      pt: 'Filtrar',
    },
    'label.checks': {
      en: 'Checks: {n}',
      ko: '검사: {n}',
      ja: '検査: {n}',
      zh: '检查: {n}',
      ar: 'الفحوص: {n}',
      es: 'Comprobaciones: {n}',
      fr: 'Vérifications : {n}',
      hi: 'जाँचें: {n}',
      id: 'Pemeriksaan: {n}',
      pt: 'Verificações: {n}',
    },
    'label.total': {
      en: 'Total checks: {n}',
      ko: '검사 합: {n}',
      ja: '検査の合計: {n}',
      zh: '检查合计: {n}',
      ar: 'مجموع الفحوص: {n}',
      es: 'Comprobaciones en total: {n}',
      fr: 'Vérifications au total : {n}',
      hi: 'कुल जाँचें: {n}',
      id: 'Total pemeriksaan: {n}',
      pt: 'Total de verificações: {n}',
    },
    'label.answer': {
      en: 'Answer',
      ko: '답',
      ja: '答え',
      zh: '答案',
      ar: 'الجواب',
      es: 'Respuesta',
      fr: 'Réponse',
      hi: 'उत्तर',
      id: 'Jawaban',
      pt: 'Resposta',
    },
    'caption.start': {
      en: 'One SQL statement splits into two plans.',
      ko: 'SQL 한 문장에서 길이 둘로 갈라진다.',
      ja: '一つの SQL 文から計画が二つに分かれる。',
      zh: '一条 SQL 语句分成两个计划。',
      ar: 'جملة SQL واحدة تتفرع إلى خطتين.',
      es: 'Una sola sentencia SQL se divide en dos planes.',
      fr: 'Une seule instruction SQL se divise en deux plans.',
      hi: 'एक SQL कथन दो योजनाओं में बँट जाता है।',
      id: 'Satu pernyataan SQL bercabang menjadi dua rencana.',
      pt: 'Uma única instrução SQL se divide em dois planos.',
    },
    'caption.join': {
      en: '{path} — join. Checks: {checks} · Rows out: {rows}',
      ko: '{path} — 잇기. 검사: {checks} · 나온 줄: {rows}',
      ja: '{path} — 結合。検査: {checks} · 出た行: {rows}',
      zh: '{path} — 连接。检查: {checks} · 输出行: {rows}',
      ar: '{path} — ربط. الفحوص: {checks} · الصفوف الناتجة: {rows}',
      es: '{path} — unir. Comprobaciones: {checks} · Filas de salida: {rows}',
      fr: '{path} — jointure. Vérifications : {checks} · Lignes produites : {rows}',
      hi: '{path} — जोड़। जाँचें: {checks} · निकली पंक्तियाँ: {rows}',
      id: '{path} — gabung. Pemeriksaan: {checks} · Baris keluar: {rows}',
      pt: '{path} — juntar. Verificações: {checks} · Linhas de saída: {rows}',
    },
    'caption.filter': {
      en: '{path} — filter. Checks: {checks} · Rows kept: {rows}',
      ko: '{path} — 거르기. 검사: {checks} · 남은 줄: {rows}',
      ja: '{path} — 絞り込み。検査: {checks} · 残った行: {rows}',
      zh: '{path} — 过滤。检查: {checks} · 保留行: {rows}',
      ar: '{path} — تصفية. الفحوص: {checks} · الصفوف الباقية: {rows}',
      es: '{path} — filtrar. Comprobaciones: {checks} · Filas que quedan: {rows}',
      fr: '{path} — filtre. Vérifications : {checks} · Lignes gardées : {rows}',
      hi: '{path} — छानना। जाँचें: {checks} · बची पंक्तियाँ: {rows}',
      id: '{path} — saring. Pemeriksaan: {checks} · Baris tersisa: {rows}',
      pt: '{path} — filtrar. Verificações: {checks} · Linhas mantidas: {rows}',
    },
    'caption.overlay': {
      en: 'Answer rows laid on each other: {same} / {total}',
      ko: '서로 포개진 답의 줄: {same} / {total}',
      ja: '重なった答えの行: {same} / {total}',
      zh: '重合的答案行: {same} / {total}',
      ar: 'صفوف الجواب المتطابقة: {same} / {total}',
      es: 'Filas de la respuesta superpuestas: {same} / {total}',
      fr: 'Lignes de réponse superposées : {same} / {total}',
      hi: 'एक-दूसरे पर बैठी उत्तर पंक्तियाँ: {same} / {total}',
      id: 'Baris jawaban yang menumpuk: {same} / {total}',
      pt: 'Linhas da resposta sobrepostas: {same} / {total}',
    },
  },
  blocks: {
    stage: { type: 'same-answer-different-plan-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
