import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 모형을 더 유연하게 할수록 훈련 오차는 줄기만 하는데, 검증 오차도 그런가?
 *
 * 다항식의 차수를 0 부터 6 까지 하나씩 올려 매번 훈련 점에 다시 맞추고, 훈련 MSE 와
 * 검증 MSE 를 차수 축 위에 나란히 잰다. 가로축은 모형의 유연함(차수)이지 학습 시간이 아니다.
 */
export const trainDownValUpFacet: FacetJson = {
  id: 'facet:trainDownValUp',
  title: {
    en: 'Train error falls, validation error turns',
    ko: '훈련 오차는 내려가고, 검증 오차는 꺾인다',
    ja: '訓練誤差は下がり、検証誤差は折り返す',
    zh: '训练误差下降，验证误差掉头',
    ar: 'خطأ التدريب يهبط، وخطأ التحقق ينعطف',
    es: 'El error de entrenamiento baja, el de validación da la vuelta',
    fr: "L'erreur d'entraînement baisse, celle de validation fait demi-tour",
    hi: 'प्रशिक्षण त्रुटि घटती है, सत्यापन त्रुटि मुड़ जाती है',
    id: 'Galat latih turun, galat validasi berbalik',
    pt: 'O erro de treino cai, o de validação dá a volta',
  },
  description: {
    en: 'Raise the polynomial degree one at a time, refit to the train points each time, and measure train and validation MSE side by side.',
    ko: '다항식의 차수를 하나씩 올려 매번 훈련 점에 다시 맞추고, 훈련 MSE 와 검증 MSE 를 나란히 잰다.',
    ja: '多項式の次数を一つずつ上げ、そのたびに訓練点へ当てはめ直し、訓練 MSE と検証 MSE を並べて測る。',
    zh: '把多项式的次数一次加一，每次都重新拟合训练点，并排测量训练 MSE 和验证 MSE。',
    ar: 'ارفع درجة كثير الحدود درجةً واحدة في كل مرة، وأعد الملاءمة على نقاط التدريب كل مرة، وقِس MSE التدريب وMSE التحقق جنبًا إلى جنب.',
    es: 'Sube el grado del polinomio de uno en uno, reajústalo a los puntos de entrenamiento cada vez y mide el MSE de entrenamiento y el de validación lado a lado.',
    fr: "Augmente le degré du polynôme d'un cran à la fois, réajuste-le chaque fois aux points d'entraînement et mesure côte à côte le MSE d'entraînement et celui de validation.",
    hi: 'बहुपद की घात एक-एक करके बढ़ाओ, हर बार प्रशिक्षण बिंदुओं पर फिर से फ़िट करो, और प्रशिक्षण MSE व सत्यापन MSE साथ-साथ मापो।',
    id: 'Naikkan derajat polinomial satu per satu, cocokkan ulang ke titik latih setiap kali, lalu ukur MSE latih dan MSE validasi berdampingan.',
    pt: 'Suba o grau do polinômio um de cada vez, reajuste aos pontos de treino a cada vez e meça o MSE de treino e o de validação lado a lado.',
  },
  algorithm: 'module:trainDownValUp',
  scene: 'module:trainDownValUpScene',
  initialData: {
    type: 'train-down-val-up',
    stepMs: 1700,
    train: [
      { x: -1, y: 1.5 },
      { x: -0.72, y: 3.7 },
      { x: -0.44, y: 4.1 },
      { x: -0.16, y: 5.5 },
      { x: 0.12, y: 6.1 },
      { x: 0.4, y: 5.8 },
      { x: 0.68, y: 4.4 },
      { x: 0.96, y: 0.9 },
    ],
    validation: [
      { x: -0.86, y: 1.7 },
      { x: -0.58, y: 4.5 },
      { x: -0.3, y: 5.9 },
      { x: -0.02, y: 6.5 },
      { x: 0.26, y: 5.3 },
      { x: 0.54, y: 5.1 },
      { x: 0.82, y: 2.3 },
    ],
    maxDegree: 6,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Degree {d}: one constant fitted to the train points',
      ko: '차수 {d}: 훈련 점에 상수 하나를 맞췄다',
      ja: '次数 {d}：訓練点に定数一つを当てはめた',
      zh: '次数 {d}：用一个常数拟合训练点',
      ar: 'الدرجة {d}: ثابت واحد مُلاءَم على نقاط التدريب',
      es: 'Grado {d}: una sola constante ajustada a los puntos de entrenamiento',
      fr: "Degré {d} : une seule constante ajustée aux points d'entraînement",
      hi: 'घात {d}: प्रशिक्षण बिंदुओं पर एक स्थिरांक फ़िट किया',
      id: 'Derajat {d}: satu konstanta dicocokkan ke titik latih',
      pt: 'Grau {d}: uma única constante ajustada aos pontos de treino',
    },
    'caption.raise': {
      en: 'Degree {d}: refitted to the train points',
      ko: '차수 {d}: 훈련 점에 다시 맞췄다',
      ja: '次数 {d}：訓練点に当てはめ直した',
      zh: '次数 {d}：重新拟合训练点',
      ar: 'الدرجة {d}: أُعيدت الملاءمة على نقاط التدريب',
      es: 'Grado {d}: reajustado a los puntos de entrenamiento',
      fr: "Degré {d} : réajusté aux points d'entraînement",
      hi: 'घात {d}: प्रशिक्षण बिंदुओं पर फिर से फ़िट किया',
      id: 'Derajat {d}: dicocokkan ulang ke titik latih',
      pt: 'Grau {d}: reajustado aos pontos de treino',
    },
    'caption.errors': {
      en: 'Train MSE: {tr} · validation MSE: {va}',
      ko: '훈련 MSE: {tr} · 검증 MSE: {va}',
      ja: '訓練 MSE：{tr} · 検証 MSE：{va}',
      zh: '训练 MSE：{tr} · 验证 MSE：{va}',
      ar: 'MSE التدريب: {tr} · MSE التحقق: {va}',
      es: 'MSE de entrenamiento: {tr} · MSE de validación: {va}',
      fr: "MSE d'entraînement : {tr} · MSE de validation : {va}",
      hi: 'प्रशिक्षण MSE: {tr} · सत्यापन MSE: {va}',
      id: 'MSE latih: {tr} · MSE validasi: {va}',
      pt: 'MSE de treino: {tr} · MSE de validação: {va}',
    },
    'label.train': {
      en: 'train',
      ko: '훈련',
      ja: '訓練',
      zh: '训练',
      ar: 'التدريب',
      es: 'entrenamiento',
      fr: 'entraînement',
      hi: 'प्रशिक्षण',
      id: 'latih',
      pt: 'treino',
    },
    'label.validation': {
      en: 'validation',
      ko: '검증',
      ja: '検証',
      zh: '验证',
      ar: 'التحقق',
      es: 'validación',
      fr: 'validation',
      hi: 'सत्यापन',
      id: 'validasi',
      pt: 'validação',
    },
    'label.degreeAxis': {
      en: 'degree (model flexibility)',
      ko: '차수 (모형의 유연함)',
      ja: '次数（モデルの柔軟さ）',
      zh: '次数（模型的灵活度）',
      ar: 'الدرجة (مرونة النموذج)',
      es: 'grado (flexibilidad del modelo)',
      fr: 'degré (souplesse du modèle)',
      hi: 'घात (मॉडल का लचीलापन)',
      id: 'derajat (kelenturan model)',
      pt: 'grau (flexibilidade do modelo)',
    },
    'label.valLow': {
      en: 'lowest validation MSE',
      ko: '가장 낮았던 검증 MSE',
      ja: '最も低かった検証 MSE',
      zh: '最低的验证 MSE',
      ar: 'أدنى MSE للتحقق',
      es: 'MSE de validación más bajo',
      fr: 'MSE de validation le plus bas',
      hi: 'सबसे कम सत्यापन MSE',
      id: 'MSE validasi terendah',
      pt: 'MSE de validação mais baixo',
    },
  },
  blocks: {
    stage: { type: 'train-down-val-up-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
