/**
 * 한 칸의 값을 정하는 세 갈래.
 *
 * @piece 편집거리 표의 칸 하나가 어떻게 정해지는가에만 답한다. 표를 채우는 것은
 * 이 조각의 일이 아니다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const threeEditChoicesFacet: FacetJson = {
  id: 'facet:threeEditChoices',
  title: {
    en: 'Three ways into one cell',
    ko: '한 칸을 정하는 세 갈래',
    ja: '一つのマスを決める三つの道',
    zh: '决定一个格子的三条路',
    ar: 'ثلاث طرق إلى خلية واحدة',
    es: 'Tres caminos hacia una celda',
    fr: 'Trois chemins vers une case',
    hi: 'एक कोष्ठ तक तीन रास्ते',
    id: 'Tiga jalan menuju satu sel',
    pt: 'Três caminhos para uma célula',
  },
  description: {
    en: 'A cell of the edit-distance table takes the cheapest of three offers — delete from above, insert from the left, replace or keep from the diagonal.',
    ko: '편집거리 표의 한 칸은 세 갈래 중 가장 싼 것을 고른다 — 위에서 오는 지움, 왼쪽에서 오는 넣음, 대각선에서 오는 바꿈 또는 그대로.',
    ja: '編集距離の表のマスは三つの提案のうち最も安いものを取る — 上からの削除、左からの挿入、斜めからの置換またはそのまま。',
    zh: '编辑距离表中的一个格子取三个提议中最便宜的那个——上方的删除、左方的插入、对角线的替换或保持。',
    ar: 'تأخذ خلية جدول مسافة التحرير أرخص العروض الثلاثة: الحذف من الأعلى، والإدراج من اليسار، والاستبدال أو الإبقاء من القطر.',
    es: 'Una celda de la tabla de distancia de edición toma la más barata de tres ofertas: borrar desde arriba, insertar desde la izquierda, sustituir o mantener desde la diagonal.',
    fr: "Une case du tableau de distance d'édition retient la moins chère de trois propositions : supprimer depuis le haut, insérer depuis la gauche, remplacer ou garder depuis la diagonale.",
    hi: 'संपादन दूरी की तालिका का एक कोष्ठ तीन प्रस्तावों में सबसे सस्ता चुनता है — ऊपर से हटाना, बाएँ से जोड़ना, विकर्ण से बदलना या यथावत रखना।',
    id: 'Sebuah sel pada tabel jarak sunting mengambil yang termurah dari tiga tawaran: hapus dari atas, sisip dari kiri, ganti atau tetap dari diagonal.',
    pt: 'Uma célula da tabela de distância de edição fica com a mais barata de três propostas: apagar de cima, inserir da esquerda, substituir ou manter da diagonal.',
  },
  algorithm: 'module:threeEditChoices',
  projector: 'module:threeEditChoicesProjector',
  initialData: {
    type: 'three-edit-choices',
    source: 'kitten',
    target: 'sitting',
    visits: [
      { i: 2, j: 3 },
      { i: 6, j: 5 },
      { i: 2, j: 2 },
    ],
    stepMs: 880,
  },
  blocks: {
    stage: { type: 'three-edit-choices-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'caption.open': {
      en: 'Cell ({i},{j}) — the two letters that meet here: {a} and {b}.',
      ko: '칸 ({i},{j}) 에서 만나는 두 글자: {a} · {b}.',
      ja: 'マス ({i},{j}) で出会う二文字: {a} · {b}。',
      zh: '格子 ({i},{j}) 相遇的两个字母：{a} · {b}。',
      ar: 'الخلية ({i},{j}) — الحرفان اللذان يلتقيان هنا: {a} · {b}.',
      es: 'Celda ({i},{j}): las dos letras que se encuentran aquí son {a} y {b}.',
      fr: 'Case ({i},{j}) — les deux lettres qui se rencontrent ici : {a} et {b}.',
      hi: 'कोष्ठ ({i},{j}) — यहाँ मिलने वाले दो अक्षर: {a} · {b}।',
      id: 'Sel ({i},{j}) — dua huruf yang bertemu di sini: {a} dan {b}.',
      pt: 'Célula ({i},{j}) — as duas letras que se encontram aqui: {a} e {b}.',
    },
    'caption.offer': {
      en: 'Each neighbour hands over its value plus its own cost.',
      ko: '이웃마다 제 값에 제 비용을 더해 내놓는다.',
      ja: '隣のマスはそれぞれ自分の値に自分のコストを足して差し出す。',
      zh: '每个邻居把自己的值加上自己的代价交出来。',
      ar: 'كل جار يقدم قيمته مضافًا إليها تكلفته الخاصة.',
      es: 'Cada vecina entrega su valor más su propio coste.',
      fr: 'Chaque voisine propose sa valeur augmentée de son propre coût.',
      hi: 'हर पड़ोसी अपना मान और अपनी लागत जोड़कर सामने रखता है।',
      id: 'Setiap tetangga menyerahkan nilainya ditambah biayanya sendiri.',
      pt: 'Cada vizinha entrega o seu valor mais o seu próprio custo.',
    },
    'caption.offerFree': {
      en: 'The two letters are the same, so the diagonal adds nothing.',
      ko: '두 글자가 같아 대각선은 더하는 것이 없다.',
      ja: '二文字が同じなので、斜めは何も足さない。',
      zh: '两个字母相同，所以对角线不加任何代价。',
      ar: 'الحرفان متطابقان، لذا لا يضيف القطر شيئًا.',
      es: 'Las dos letras son iguales, así que la diagonal no añade nada.',
      fr: "Les deux lettres sont identiques : la diagonale n'ajoute rien.",
      hi: 'दोनों अक्षर एक ही हैं, इसलिए विकर्ण कुछ नहीं जोड़ता।',
      id: 'Kedua huruf itu sama, jadi diagonal tidak menambah apa pun.',
      pt: 'As duas letras são iguais, portanto a diagonal não acrescenta nada.',
    },
    'caption.weigh': {
      en: 'The cheapest offer settles at {v}.',
      ko: '가장 싼 값은 {v}.',
      ja: '最も安い値は {v}。',
      zh: '最便宜的值是 {v}。',
      ar: 'أرخص عرض يستقر عند {v}.',
      es: 'La oferta más barata se queda en {v}.',
      fr: 'La proposition la moins chère se fixe à {v}.',
      hi: 'सबसे सस्ता प्रस्ताव: {v}।',
      id: 'Tawaran termurah berhenti di {v}.',
      pt: 'A proposta mais barata fica em {v}.',
    },
    'caption.weighTie': {
      en: 'Two offers are level at {v} — either path gives the same answer.',
      ko: '두 값이 나란히 {v} — 어느 길로 가도 답은 같다.',
      ja: '二つの値が並んで {v} — どちらの道を通っても答えは同じ。',
      zh: '两个值并列为 {v} — 走哪条路答案都一样。',
      ar: 'عرضان متعادلان عند {v} — كلا المسارين يعطي الجواب نفسه.',
      es: 'Dos ofertas empatan en {v}: cualquiera de los dos caminos da la misma respuesta.',
      fr: 'Deux propositions sont à égalité à {v} : les deux chemins donnent la même réponse.',
      hi: 'दो प्रस्ताव बराबरी पर: {v} — दोनों रास्ते एक ही उत्तर देते हैं।',
      id: 'Dua tawaran seri di {v} — kedua jalur memberi jawaban yang sama.',
      pt: 'Duas propostas empatam em {v} — os dois caminhos dão a mesma resposta.',
    },
    'caption.settle': {
      en: 'The winner moves in. Cell ({i},{j}) holds {v}.',
      ko: '이긴 값이 칸으로 들어간다 — ({i},{j}) 의 값은 {v}.',
      ja: '勝った値がマスに入る — ({i},{j}) の値は {v}。',
      zh: '获胜的值搬进来 — ({i},{j}) 的值是 {v}。',
      ar: 'القيمة الفائزة تنتقل إلى مكانها — قيمة الخلية ({i},{j}) هي {v}.',
      es: 'El valor ganador ocupa su lugar: la celda ({i},{j}) vale {v}.',
      fr: 'La valeur gagnante prend sa place : la case ({i},{j}) vaut {v}.',
      hi: 'जीता हुआ मान भीतर आता है — कोष्ठ ({i},{j}) का मान है {v}।',
      id: 'Nilai pemenang masuk — sel ({i},{j}) bernilai {v}.',
      pt: 'O valor vencedor entra — a célula ({i},{j}) vale {v}.',
    },
    'caption.done': {
      en: 'Every cell in the table is decided by this contest.',
      ko: '표의 모든 칸이 이 겨룸으로 정해진다.',
      ja: '表のすべてのマスがこの競り合いで決まる。',
      zh: '表中每个格子都由这场比拼决定。',
      ar: 'كل خلية في الجدول تُحسم بهذه المنافسة.',
      es: 'Cada celda de la tabla se decide con esta competición.',
      fr: 'Chaque case du tableau se décide par cette confrontation.',
      hi: 'तालिका का हर कोष्ठ इसी मुक़ाबले से तय होता है।',
      id: 'Setiap sel dalam tabel ditentukan oleh perlombaan ini.',
      pt: 'Cada célula da tabela é decidida por esta disputa.',
    },
    'label.delete': {
      en: 'delete',
      ko: '지움',
      ja: '削除',
      zh: '删除',
      ar: 'حذف',
      es: 'borrar',
      fr: 'supprimer',
      hi: 'हटाना',
      id: 'hapus',
      pt: 'apagar',
    },
    'label.insert': {
      en: 'insert',
      ko: '넣음',
      ja: '挿入',
      zh: '插入',
      ar: 'إدراج',
      es: 'insertar',
      fr: 'insérer',
      hi: 'जोड़ना',
      id: 'sisip',
      pt: 'inserir',
    },
    'label.replace': {
      en: 'replace',
      ko: '바꿈',
      ja: '置換',
      zh: '替换',
      ar: 'استبدال',
      es: 'sustituir',
      fr: 'remplacer',
      hi: 'बदलना',
      id: 'ganti',
      pt: 'substituir',
    },
    'label.keep': {
      en: 'keep',
      ko: '그대로',
      ja: 'そのまま',
      zh: '保持',
      ar: 'إبقاء',
      es: 'mantener',
      fr: 'garder',
      hi: 'यथावत',
      id: 'tetap',
      pt: 'manter',
    },
  },
};
