import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { SegmentationData } from './algorithm.js';

const initialData: SegmentationData = {
  type: 'segmentation',
  stepMs: 900,
  memoryKiB: 32,
  frameKiB: 4,
  blocks: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
  requests: [
    { kind: 'in', block: 'A', size: 7 },
    { kind: 'in', block: 'B', size: 7 },
    { kind: 'in', block: 'C', size: 4 },
    { kind: 'in', block: 'D', size: 4 },
    { kind: 'in', block: 'E', size: 5 },
    { kind: 'out', block: 'E' },
    { kind: 'out', block: 'C' },
    { kind: 'out-leaver' },
    { kind: 'in', block: 'F', size: 4 },
    { kind: 'in', block: 'G', size: 7 },
    { kind: 'in', block: 'H', size: 8 },
  ],
  leavers: ['A', 'B'],
  leaverLadder: [0, 1],
  fitLadder: [0, 1, 2, 3],
  leaver: 0,
  fit: 0,
};

export const segmentationFacet: FacetJson = {
  id: 'facet:segmentation',
  title: {
    en: 'Segmentation and Holes',
    ko: '세그멘테이션과 틈',
    ja: 'セグメンテーションと空き',
    zh: '分段与空洞',
    ar: 'التجزئة والفجوات',
    es: 'Segmentación y huecos',
    fr: 'Segmentation et trous',
    hi: 'सेगमेंटेशन और खाली जगहें',
    id: 'Segmentasi dan Celah',
    pt: 'Segmentação e lacunas',
  },
  description: {
    en: 'Each block goes into a free hole at its own length. The free total can be enough while no single hole fits — and the rule for picking a hole only moves where that happens.',
    ko: '덩이마다 제 길이로 빈 틈에 넣는다. 빈 몫의 합이 넉넉해도 어느 한 틈에도 못 들어가는 때가 오고, 틈 고르는 규칙은 그 자리만 옮긴다.',
    ja: 'ブロックはそれぞれ自分の長さで空きに入る。空きの合計が足りていても、どの空きにも入らないときが来る。空きを選ぶ規則はその場所を動かすだけだ。',
    zh: '每个块按自己的长度放进空洞。空闲总量足够时,也可能没有任何一个空洞放得下——选洞规则只会改变这件事发生的位置。',
    ar: 'تدخل كل كتلة في فجوة فارغة بطولها الخاص. قد يكفي مجموع المساحة الحرة ولا تتسع أي فجوة واحدة — وقاعدة اختيار الفجوة تنقل فقط مكان حدوث ذلك.',
    es: 'Cada bloque entra en un hueco libre con su propio tamaño. El total libre puede bastar sin que quepa en ningún hueco — y la regla para elegir hueco solo cambia dónde ocurre.',
    fr: 'Chaque bloc entre dans un trou libre à sa propre taille. Le total libre peut suffire sans qu’aucun trou ne convienne — et la règle de choix du trou ne fait que déplacer l’endroit où cela arrive.',
    hi: 'हर खंड अपनी लंबाई के साथ किसी खाली जगह में जाता है। कुल खाली जगह काफ़ी होने पर भी कोई एक जगह पूरी नहीं पड़ती — और जगह चुनने का नियम बस यह बदलता है कि ऐसा कहाँ होता है।',
    id: 'Setiap blok masuk ke celah kosong dengan panjangnya sendiri. Total ruang kosong bisa cukup tetapi tidak ada satu celah pun yang muat — dan aturan memilih celah hanya memindahkan tempat hal itu terjadi.',
    pt: 'Cada bloco entra numa lacuna livre com o seu próprio tamanho. O total livre pode bastar sem que caiba em nenhuma lacuna — e a regra de escolha só muda onde isso acontece.',
  },
  algorithm: 'module:segmentation',
  projector: 'module:segmentationProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'segmentation-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'fit',
          name: 'fit',
          label: {
            en: 'Placement',
            ko: '배치',
            ja: '配置',
            zh: '放置方式',
            ar: 'طريقة الوضع',
            es: 'Colocación',
            fr: 'Placement',
            hi: 'रखने का तरीका',
            id: 'Penempatan',
            pt: 'Colocação',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: {
                en: 'First fit',
                ko: '처음 맞는 틈',
                ja: '最初に合う空き',
                zh: '首次适配',
                ar: 'أول ملائم',
                es: 'Primer ajuste',
                fr: 'Premier trou',
                hi: 'पहली फिट',
                id: 'Pertama muat',
                pt: 'Primeiro ajuste',
              },
            },
            {
              value: 1,
              label: {
                en: 'Best fit',
                ko: '꼭 맞는 틈',
                ja: '最適な空き',
                zh: '最佳适配',
                ar: 'أنسب ملائم',
                es: 'Mejor ajuste',
                fr: 'Meilleur trou',
                hi: 'सबसे सटीक',
                id: 'Paling pas',
                pt: 'Melhor ajuste',
              },
            },
            {
              value: 2,
              label: {
                en: 'Worst fit',
                ko: '가장 큰 틈',
                ja: '最大の空き',
                zh: '最差适配',
                ar: 'أكبر فجوة',
                es: 'Peor ajuste',
                fr: 'Plus grand trou',
                hi: 'सबसे बड़ी जगह',
                id: 'Celah terbesar',
                pt: 'Pior ajuste',
              },
            },
            {
              value: 3,
              label: {
                en: 'Fixed frames',
                ko: '고정 칸',
                ja: '固定枠',
                zh: '固定页框',
                ar: 'إطارات ثابتة',
                es: 'Marcos fijos',
                fr: 'Cadres fixes',
                hi: 'स्थिर फ़्रेम',
                id: 'Bingkai tetap',
                pt: 'Quadros fixos',
              },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'leaver',
          name: 'leaver',
          label: {
            en: 'Third to leave',
            ko: '셋째로 나감',
            ja: '三番目に出る',
            zh: '第三个离开',
            ar: 'الثالث المغادر',
            es: 'Tercero en salir',
            fr: 'Troisième à sortir',
            hi: 'तीसरा बाहर',
            id: 'Keluar ketiga',
            pt: 'Terceiro a sair',
          },
          segments: [
            { value: 0, label: 'A', default: true },
            { value: 1, label: 'B' },
          ],
        },
      ],
      metrics: [
        {
          name: 'free-total',
          initial: 0,
          label: {
            en: 'Free total (KiB)',
            ko: '빈 몫 합 (KiB)',
            ja: '空き合計 (KiB)',
            zh: '空闲总量 (KiB)',
            ar: 'مجموع الفراغ (KiB)',
            es: 'Total libre (KiB)',
            fr: 'Total libre (Kio)',
            hi: 'कुल खाली (KiB)',
            id: 'Total kosong (KiB)',
            pt: 'Total livre (KiB)',
          },
        },
        {
          name: 'largest-hole',
          initial: 0,
          label: {
            en: 'Largest hole (KiB)',
            ko: '가장 큰 틈 (KiB)',
            ja: '最大の空き (KiB)',
            zh: '最大空洞 (KiB)',
            ar: 'أكبر فجوة (KiB)',
            es: 'Hueco mayor (KiB)',
            fr: 'Plus grand trou (Kio)',
            hi: 'सबसे बड़ी जगह (KiB)',
            id: 'Celah terbesar (KiB)',
            pt: 'Maior lacuna (KiB)',
          },
        },
        {
          name: 'rejected',
          initial: 0,
          label: {
            en: 'Rejected',
            ko: '못 들어감',
            ja: '入らなかった',
            zh: '未放入',
            ar: 'المرفوض',
            es: 'Rechazados',
            fr: 'Refusés',
            hi: 'अस्वीकृत',
            id: 'Ditolak',
            pt: 'Recusados',
          },
        },
        {
          name: 'inside-waste',
          initial: 0,
          label: {
            en: 'Internal waste (KiB)',
            ko: '안쪽 낭비 (KiB)',
            ja: '内部の無駄 (KiB)',
            zh: '内部浪费 (KiB)',
            ar: 'هدر داخلي (KiB)',
            es: 'Desperdicio interno (KiB)',
            fr: 'Perte interne (Kio)',
            hi: 'अंदरूनी बर्बादी (KiB)',
            id: 'Sisa internal (KiB)',
            pt: 'Desperdício interno (KiB)',
          },
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:segmentation-imperative',
      label: {
        en: 'Hole placer',
        ko: '틈 배치기',
        ja: '空き配置器',
        zh: '空洞放置器',
        ar: 'مُوزِّع الفجوات',
        es: 'Colocador en huecos',
        fr: 'Placeur de trous',
        hi: 'जगह आवंटक',
        id: 'Penempat celah',
        pt: 'Colocador em lacunas',
      },
    },
  },
  messages: {
    'caption.start': {
      en: 'Free total: {free} KiB · Largest hole: {big} KiB',
      ko: '빈 몫 합: {free} KiB · 가장 큰 틈: {big} KiB',
      ja: '空き合計: {free} KiB · 最大の空き: {big} KiB',
      zh: '空闲总量: {free} KiB · 最大空洞: {big} KiB',
      ar: 'مجموع الفراغ: {free} KiB · أكبر فجوة: {big} KiB',
      es: 'Total libre: {free} KiB · Hueco mayor: {big} KiB',
      fr: 'Total libre : {free} Kio · Plus grand trou : {big} Kio',
      hi: 'कुल खाली: {free} KiB · सबसे बड़ी जगह: {big} KiB',
      id: 'Total kosong: {free} KiB · Celah terbesar: {big} KiB',
      pt: 'Total livre: {free} KiB · Maior lacuna: {big} KiB',
    },
    'caption.placed': {
      en: 'Placed at {start}–{end} KiB',
      ko: '놓은 자리: {start}–{end} KiB',
      ja: '置いた位置: {start}–{end} KiB',
      zh: '放在: {start}–{end} KiB',
      ar: 'وُضع عند: {start}–{end} KiB',
      es: 'Colocado en {start}–{end} KiB',
      fr: 'Placé à {start}–{end} Kio',
      hi: 'रखा गया: {start}–{end} KiB',
      id: 'Ditempatkan di {start}–{end} KiB',
      pt: 'Colocado em {start}–{end} KiB',
    },
    'caption.placedFrames': {
      en: 'Placed in frames: {frames}',
      ko: '놓은 프레임: {frames}',
      ja: '置いたフレーム: {frames}',
      zh: '放入页框: {frames}',
      ar: 'وُضع في الإطارات: {frames}',
      es: 'Colocado en marcos: {frames}',
      fr: 'Placé dans les cadres : {frames}',
      hi: 'इन फ़्रेमों में रखा: {frames}',
      id: 'Ditempatkan di bingkai: {frames}',
      pt: 'Colocado nos quadros: {frames}',
    },
    'caption.freed': {
      en: 'Freed: {block}',
      ko: '비움: {block}',
      ja: '解放: {block}',
      zh: '释放: {block}',
      ar: 'تحرير: {block}',
      es: 'Liberado: {block}',
      fr: 'Libéré : {block}',
      hi: 'खाली किया: {block}',
      id: 'Dibebaskan: {block}',
      pt: 'Liberado: {block}',
    },
    'caption.rejected': {
      en: 'No hole fits: {size} KiB',
      ko: '맞는 틈 없음: {size} KiB',
      ja: '合う空きなし: {size} KiB',
      zh: '没有合适的空洞: {size} KiB',
      ar: 'لا فجوة تتسع: {size} KiB',
      es: 'Ningún hueco cabe: {size} KiB',
      fr: 'Aucun trou ne convient : {size} Kio',
      hi: 'कोई जगह फिट नहीं: {size} KiB',
      id: 'Tak ada celah muat: {size} KiB',
      pt: 'Nenhuma lacuna cabe: {size} KiB',
    },
    'req.in': {
      en: 'In: {block} · {size} KiB',
      ko: '들어옴: {block} · {size} KiB',
      ja: '入る: {block} · {size} KiB',
      zh: '进入: {block} · {size} KiB',
      ar: 'دخول: {block} · {size} KiB',
      es: 'Entra: {block} · {size} KiB',
      fr: 'Entre : {block} · {size} Kio',
      hi: 'अंदर: {block} · {size} KiB',
      id: 'Masuk: {block} · {size} KiB',
      pt: 'Entra: {block} · {size} KiB',
    },
    'req.out': {
      en: 'Out: {block}',
      ko: '나감: {block}',
      ja: '出る: {block}',
      zh: '离开: {block}',
      ar: 'خروج: {block}',
      es: 'Sale: {block}',
      fr: 'Sort : {block}',
      hi: 'बाहर: {block}',
      id: 'Keluar: {block}',
      pt: 'Sai: {block}',
    },
    'label.memory': {
      en: 'Memory',
      ko: '메모리',
      ja: 'メモリ',
      zh: '内存',
      ar: 'الذاكرة',
      es: 'Memoria',
      fr: 'Mémoire',
      hi: 'मेमोरी',
      id: 'Memori',
      pt: 'Memória',
    },
    'label.lastRound': {
      en: 'Last round',
      ko: '앞 판',
      ja: '前の回',
      zh: '上一轮',
      ar: 'الجولة السابقة',
      es: 'Ronda previa',
      fr: 'Tour précédent',
      hi: 'पिछला दौर',
      id: 'Putaran lalu',
      pt: 'Rodada anterior',
    },
    'label.frame': {
      en: 'frame {n}',
      ko: '프레임 {n}',
      ja: 'フレーム {n}',
      zh: '页框 {n}',
      ar: 'إطار {n}',
      es: 'marco {n}',
      fr: 'cadre {n}',
      hi: 'फ़्रेम {n}',
      id: 'bingkai {n}',
      pt: 'quadro {n}',
    },
    'label.kib': {
      en: '{n} KiB',
      ko: '{n} KiB',
      ja: '{n} KiB',
      zh: '{n} KiB',
      ar: '{n} KiB',
      es: '{n} KiB',
      fr: '{n} Kio',
      hi: '{n} KiB',
      id: '{n} KiB',
      pt: '{n} KiB',
    },
    'label.kibAxis': {
      en: 'KiB',
      ko: 'KiB',
      ja: 'KiB',
      zh: 'KiB',
      ar: 'KiB',
      es: 'KiB',
      fr: 'Kio',
      hi: 'KiB',
      id: 'KiB',
      pt: 'KiB',
    },
    'label.freeTotal': {
      en: 'Free total',
      ko: '빈 몫 합',
      ja: '空き合計',
      zh: '空闲总量',
      ar: 'مجموع الفراغ',
      es: 'Total libre',
      fr: 'Total libre',
      hi: 'कुल खाली',
      id: 'Total kosong',
      pt: 'Total livre',
    },
    'label.largestHole': {
      en: 'Largest hole',
      ko: '가장 큰 틈',
      ja: '最大の空き',
      zh: '最大空洞',
      ar: 'أكبر فجوة',
      es: 'Hueco mayor',
      fr: 'Plus grand trou',
      hi: 'सबसे बड़ी जगह',
      id: 'Celah terbesar',
      pt: 'Maior lacuna',
    },
    'label.request': {
      en: 'Request',
      ko: '요청',
      ja: '要求',
      zh: '请求',
      ar: 'الطلب',
      es: 'Solicitud',
      fr: 'Demande',
      hi: 'अनुरोध',
      id: 'Permintaan',
      pt: 'Pedido',
    },
    'label.waste': {
      en: 'Internal waste',
      ko: '안쪽 낭비',
      ja: '内部の無駄',
      zh: '内部浪费',
      ar: 'هدر داخلي',
      es: 'Desperdicio interno',
      fr: 'Perte interne',
      hi: 'अंदरूनी बर्बादी',
      id: 'Sisa internal',
      pt: 'Desperdício interno',
    },
  },
};
