/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-facet-catalog.mts)
 * 출처: 각 facet 의 facet.ts(title/description) + taxonomy/taxonomy.json(분야).
 */

import type { FacetCatalog } from '../catalog-types.js';

export const CATALOG: FacetCatalog = {
  locale: "ja",
  domains: [
    {"id":"cs-fundamentals","name":"コンピュータサイエンスの基礎","subdomains":[{"id":"data-structures","name":"データ構造"},{"id":"probabilistic-structures","name":"確率的データ構造"},{"id":"algorithms","name":"アルゴリズム"},{"id":"graph-algorithms","name":"グラフアルゴリズム"},{"id":"string-algorithms","name":"文字列アルゴリズム"},{"id":"numerical-algorithms","name":"数値アルゴリズム"},{"id":"complexity","name":"計算量"}]},
    {"id":"programming-fundamentals","name":"プログラミングの基礎","subdomains":[{"id":"control-flow","name":"制御フロー"}]},
    {"id":"computer-architecture","name":"コンピュータアーキテクチャ","subdomains":[{"id":"number-representation","name":"数とビット表現"},{"id":"cache-hierarchy","name":"キャッシュ階層"},{"id":"instruction-pipeline","name":"命令パイプライン"},{"id":"branch-prediction","name":"分岐予測"},{"id":"data-layout","name":"データ配置とアクセス"}]},
    {"id":"operating-systems","name":"オペレーティングシステム","subdomains":[{"id":"process-thread","name":"プロセスとスレッド"}]},
    {"id":"networks","name":"コンピュータネットワーク","subdomains":[{"id":"network-routing","name":"ネットワーク層"}]},
    {"id":"databases","name":"データベース","subdomains":[{"id":"relational","name":"リレーショナルモデル"}]},
    {"id":"compilers","name":"コンパイラと言語","subdomains":[{"id":"lexical","name":"字句解析"}]},
    {"id":"ml-foundations","name":"機械学習の基礎","subdomains":[{"id":"supervised","name":"教師あり学習"},{"id":"unsupervised","name":"教師なし学習"}]},
    {"id":"ai-engineering","name":"AI エンジニアリング","subdomains":[{"id":"text-tokenization","name":"トークン化"},{"id":"vector-search","name":"埋め込みとベクトル検索"},{"id":"retrieval-augmentation","name":"検索拡張"},{"id":"decoding","name":"生成の制御"},{"id":"inference-efficiency","name":"推論効率"}]},
    {"id":"system-design","name":"システム設計","subdomains":[{"id":"caching","name":"キャッシング"},{"id":"messaging","name":"メッセージキュー"}]},
    {"id":"security","name":"セキュリティと暗号","subdomains":[{"id":"asymmetric","name":"公開鍵暗号"},{"id":"hash","name":"ハッシュ"},{"id":"signature","name":"デジタル署名"}]},
    {"id":"graphics","name":"コンピュータグラフィックス","subdomains":[{"id":"transform-2d","name":"2D 変換"}]},
  ],
  facets: [
    {"id":"facet:array","title":"配列","description":"隣どうしがぴたりと並ぶ — 番号さえ分かれば一歩で届くが、真ん中を触ると隣が次々ずれる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:linkedListSingly","title":"連結リスト","description":"ノードは自分の次だけを指す一本の指を持つ — 挿入も削除もカードではなく指をつなぎ直す仕事だ","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:stack","title":"スタック (LIFO)","description":"触れるのは一箇所だけ — 最後に入ったものが最初に出る","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:queueFifo","title":"キュー (FIFO)","description":"ベルトコンベア — 最も長く待ったものが最も早く去る機械","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:hashTableChaining","title":"ハッシュテーブル","description":"キーは関数が決めた一つのマスへ落ちる — 同じマスに落ちれば混乱ではなく鎖が伸びる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bst","title":"二分探索木","description":"比較一回で世界の半分を畳む — BST の決定的な一刀","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:avlTree","title":"AVL 木","description":"戻りながら測る — 傾きが続けば一回、折れれば二回まわす。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:redBlackTree","title":"赤黒木","description":"塗り替えは問題を上へ押し、回転はそこで終える — 二つの規則が木を低く保つ。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bTree","title":"B木","description":"一つの席に鍵が複数、その間ごとに分かれ道 — 枝が広いので木は低い。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:trie","title":"トライ木","description":"出だしが同じ語は一本の道を共有する — だから接頭辞ひとつでまとめて見つかる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heapBinary","title":"ヒープ","description":"木のように考え、配列に収める — 最小値がつねに頂上にある。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:unionFind","title":"ユニオン・ファインド","description":"二度尋ねれば二度目はほぼ無料 — 上るついでに道が畳まれる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:indexAddressCalc","title":"添字からアドレスへ","description":"掛け算ひとつと足し算ひとつで、添字がアドレスになる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:shiftOnInsert","title":"真ん中に入れると後ろが押される","description":"挿入位置より後ろの値は、後ろから順に本当に一つずつ右へ動く。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:shiftOnRemove","title":"削除でずれる","description":"真ん中を一つ抜くと、後ろのものが左へ引き寄せられる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:growAndCopy","title":"拡張して複写","description":"領域が満杯になると、別の場所により大きな領域を取り、値をすべて写して、古い領域を返す。アドレスが変わる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:outOfBounds","title":"範囲外アクセス","description":"配列の終わりを越えた添字が実際に何を指すのか。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:nodePointsNext","title":"ノードが次を指す","description":"ノードはメモリに散らばっているのに順序がある — その順序を作るのは、値の横に持っているアドレスだ。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:traverseFromHead","title":"四番目のノードに届くまで","description":"ノードに届くには、head からリンクを一つずつたどるしかない。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:relinkInsert","title":"つなぎ直し","description":"連結リストの挿入は、位置ではなく矢印を書き換える。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:lostLink","title":"リンクの喪失","description":"順序を誤って矢印を付け替えると、その先がまるごと届かなくなる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:pushPopTop","title":"プッシュ・ポップ・トップ","description":"出入口がひとつ — 最後に入ったものが先に出る。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:enqueueDequeueEnds","title":"一方から入れ、反対から出す","description":"出入り口が両端にあるので、先に入ったものが先に出る。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:circularBufferWrap","title":"循環バッファ: 一周して戻る","description":"最後のマスの次は最初のマスだ。マスは増えず、場所を使い回すだけ。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:dequeBothEnds","title":"両端がどちらも開いている","description":"両端キューの扉は四つではなく二つで、その二つが出入りを兼ねる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:hashToBucket","title":"キーをバケットへ畳む","description":"ハッシュ関数がどんなキーも一つの整数に畳み、剰余がその整数を決まった数の枠のどれか一つに畳み直す。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:chainingBucket","title":"チェイン法 — 同じ枠なら、そこにぶら下げる","description":"二つ目のキーが埋まった枠に来ても、何も押し出されない。その枠からぶら下がる鎖の端に掛かり、探すときはその鎖だけをたどる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:openAddressingProbe","title":"オープンアドレス法 — 次の席を探る","description":"席が埋まっていると、鍵は空いた席が見つかるまで横へ一つずつずれていく。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:loadFactorRehash","title":"負荷率と再ハッシュ","description":"詰まりすぎたら表を広げ、すべての鍵を一から置き直す。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:parentTwoChildren","title":"一つの席から、二つの枝","description":"一つの節点から下へ伸びるのは多くて二つ。左と右は名の違う席で、入れ替えられない。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:traversalOrder","title":"巡回の順序","description":"一本の木を三通りに歩く。自分の場所を踏む瞬間だけがずれる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:depthDoublesCount","title":"深さが一つ増えると席は倍","description":"一段下がるごとに、木が抱えられる席の数は倍になる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstCompareAndGo","title":"二分探索木: 比べて降りる","description":"比較のたびに枝が丸ごと候補から外れ、一段下へ降りる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstInorderSorted","title":"二分探索木の通りがけ順は整列して出る","description":"通りがけ順に歩く — 左を空にし、自分を置き、右へ渡る — すると値は小さい順に出てくる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstDegenerate","title":"片側にだけ伸びれば一本の線になる","description":"同じ六つの値を二通りの順で入れ、片方が鎖になり、もう片方が横に広がるのを見る。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heightBalanceCheck","title":"高さの均衡チェック","description":"均衡因子は上から見て得るものではなく、葉から上へ運ばれて積み上がる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:rotateToBalance","title":"均衡のための回転","description":"一度の回転が傾いた木を立て直す。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:recolorThenRotate","title":"塗り替え、そして回転","description":"同じ違反が二度起こる — 隣の色が、塗り替えで済むか回さねばならないかを分ける","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:blackHeightEqual","title":"黒の高さは、どこでも同じ","description":"根から nil まで四つの道をたどる — 黒の数はいつも同じ値に落ち着く","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:nodeHoldsMany","title":"一つのノードに複数の鍵","description":"一つのノードが鍵をいくつも持つ。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:splitWhenFull","title":"満杯なら分ける","description":"満杯のノードがあふれると、真ん中のキーが親へ上がり、残りは二つに分かれる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heightStaysLow","title":"木の高さは低いまま","description":"二本の木が同じ百万枚の葉を覆う — 枝が広いほうがはるかに少ない段で終わる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:sharePrefixPath","title":"接頭辞の共有","description":"同じ書き出しの語は、文字が分かれるまで同じ道をたどる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:walkPerCharacter","title":"トライを一文字ずつたどる","description":"語をまるごと比べることはない。一文字が枝を一つ選び、枝がなければそこで終わる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heapProperty","title":"ヒープ条件","description":"親は必ず子より先に来る — けれど兄弟どうしには何の順序も約束されない","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:siftUp","title":"シフトアップ","description":"最後の空きに入れ、自分の場所が見つかるまで登る。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:siftDown","title":"シフトダウン","description":"最後の値が空いた頂上を埋め、収まる場所まで一段ずつ降りていく。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:arrayAsTree","title":"配列で表す木","description":"配列一つで木を表す方法 — 保存されたリンクはなく、添字の計算だけ。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:adjacencyListVsMatrix","title":"隣接リストと隣接行列","description":"同じ辺が、伸びていくリストと、はじめから用意された表の両方に落ちる","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:findRoot","title":"根を探す","description":"どの位置も上を指し、自分自身を指す位置がその集まりの名前になる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:unionByRank","title":"ランクによる併合","description":"低い方を高い方の下に入れれば高さは変わらない。同じときだけ一つ伸びる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:pathCompression","title":"経路圧縮","description":"根まで登った手間は、尋ねたノードだけでなく途中のすべてのノードに報いる。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bloomFilter","title":"ブルームフィルタ","description":"わずかな領域で「ない」を確実に言える。二つのつまみを動かすと、一方が他方の最適点をずらす。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:countMinSketch","title":"Count-Min Sketch","description":"キーの数よりずっと少ないセルで「何回見たか」を数える。幅は衝突の頻度を減らし、深さは衝突したときの代償を減らす。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:hyperloglog","title":"HyperLogLog","description":"何ひとつ保存せずに異なるものの数を数える — 容器の数を動かして誤差が縮むのを見る。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:tDigest","title":"少ない席で分位に答え、それでも尾を正確に","description":"圧縮係数δを上げると、尾の誤差は真ん中よりずっと速く減る — 尾に席を寄せて買ったものがこれだ。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:skipList","title":"ランダムが均衡を保つ仕事を肩代わりする","description":"誰も形を管理していないのに探索の歩数が log n で伸びる。つまみを動かして見る。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:severalHashesOneValue","title":"1 つの値と複数のハッシュ","description":"ブルームフィルタへの挿入 — 1 つの値が 3 つのハッシュに分かれ、ビット配列の 3 か所を点灯させる。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:wrongInOneDirection","title":"間違いは一方向だけ","description":"ブルームフィルタは入れていないものを「ある」と答えることはあっても、入れたものを「ない」とは答えない。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:cannotUnset","title":"消せない","description":"ブルームフィルタで一つを消すと、その枠を共有していた別の値まで消えてしまう。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:trustTheSmallest","title":"最小値を信じる","description":"Count-Min Sketch は 3 行から読んだ値のうち最も小さいものを答えとする。共有されたセルは値を膨らませることはあっても減らすことはない。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:leadingZerosTell","title":"先頭のゼロが個数を告げる","description":"まれなゼロの並びを見たなら、それだけ多くを見たということ — 何ひとつ保存せずに異なりの数を測る。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:averageTheBuckets","title":"容器に分けて測り平均する","description":"外れ値一つが推定を丸ごと引きずる。四つに分ければその跳ねは一つの容器に閉じ込められる。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:crowdTheTails","title":"尾に席を寄せる","description":"分位を測るダイジェストは、真ん中より尾に多くのバケットを割り当てる。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:skipALayer","title":"層が複数あるリストでの探索","description":"上の層では遠くまで跳び、行き過ぎたら一層下りて絞り込む。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:coinFlipHeight","title":"塔の高さを決めるのは何か","description":"コイン投げが各塔の高さを決め、各層は自然に半分ずつ減る。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:spaceErrorTradeoff","title":"Count-Min Sketch をどれだけ大きく取るか","description":"節約した領域は誤差で支払う。表が狭いほど読み出す値は膨らむ。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:bubbleSort","title":"バブルソート","description":"隣どうしの比較と交換の波が、パスごとに最大値を末尾へ押し上げる","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:selectionSort","title":"選択ソート","description":"残り全部を見て最小を見つけ、ちょうど一度だけ動かす","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:insertionSort","title":"挿入ソート","description":"値を一つ手に取り、大きいものを脇へどかしてから差し込む — すでに並んだ入力ではほとんど働かない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:mergeSort","title":"マージソート","description":"一つずつになるまで分け、両方の先頭だけを見ながら戻りつつ併合する。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:quickSort","title":"クイックソート","description":"基準をひとつ選んで左右に分ける — 一度分ければ、その基準の位置は決まる","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:heapSort","title":"ヒープソート","description":"配列を最大ヒープにしてから、頂点を後ろへ移すのを繰り返す — 余分な配列はいらない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:countingSort","title":"カウンティングソート","description":"値どうしを比べない — 数えて、足し合わせて、席に着かせる。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:radixSort","title":"基数ソート","description":"一桁ずつ見て並べる — 値どうしを比べることがない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:shellSort","title":"シェルソート","description":"歩幅を広げた挿入ソート — 遠くの乱れを先に片づければ、最後の一巡に残る仕事は少ない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:linearSearch","title":"線形探索","description":"前から一つずつ見る — 並びに頼れないなら、「ない」と言い切るにはそれしかない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:binarySearch","title":"二分探索","description":"真ん中を見て半分を捨てる — 「ない」と答えるには区間が空にならねばならない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:interpolationSearch","title":"補間探索","description":"半分に割る代わりに値の大きさで狙う — 二分探索との違いはたった一行だ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:dynamicProgramming","title":"動的計画法","description":"表を一度だけ埋める — ひとつの枠は上の行のふたつの枠しか見ない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:greedy","title":"貪欲法","description":"いつも一番早く終わるものを取る — それが最適になる。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:backtracking","title":"バックトラッキング","description":"盤が詰まったらクイーンを戻して次の列を試す — 引き返すことは失敗ではなく手順だ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:branchAndBound","title":"分枝限定法","description":"同じナップサックを表なしで解く — 枝を伸ばし、その枝が届きうる最大を測り、勝てない枝を切る。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:compareAndSwap","title":"比較と交換","description":"比較は判定であり、交換はその判定が真のときだけ続く結果だ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:sortStability","title":"ソートの安定性","description":"値が同じ項目があると、正しい並びはひとつではない。入力の順序を保つものだけを安定と呼ぶ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:inPlaceVsExtra","title":"その場での整列","description":"二つの整列が同じ並びに届く。場所を余分に求めるのは片方だけだ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bubbleAdjacentSwap","title":"隣どうしの交換","description":"隣どうしを比べながら左から右へ一度なでるだけで、その時点の最大が一マスずつ運ばれ、右端に落ち着く。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:selectMinEachPass","title":"最小値の選択","description":"走査の間は目印だけが動き、値が動くのは一巡が終わったあとの一度きり","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:insertIntoSortedPart","title":"整列済みの部分へ挿入","description":"新しい値を列から持ち上げ、後ろから順に値がずれ、空いた場所に収まる。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:splitUntilOne","title":"分割","description":"区間を半分に割り続けても、変わるのは束の境界だけだ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:mergeTwoSorted","title":"マージ","description":"並んだ二列が一つになる — 先頭の二つだけを見て。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:partitionAroundPivot","title":"パーティション分割","description":"値ごとに同じ基準ひとつと見比べ、どちらかへ渡る。基準そのものは線に残る。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:pivotChoiceMatters","title":"ピボットの選び方","description":"同じ並んだ値を二通りに割る。真ん中の値は仕事を半分にし、先頭の値はひとつ減らすだけだ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:heapSortExtract","title":"ヒープの取り出し","description":"頂点を取り出すとヒープの最後のマスが空き、結果はまさにそこに収まる","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:countThenPlace","title":"計数ソートの配置","description":"値ごとに数えておけば、置き場所はあらかじめ決まる — 値どうしを見比べることは一度もない。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:digitByDigit","title":"桁ごとの整列","description":"下の位から一桁ずつ見るだけ。それで列全体が並ぶ。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:gapShrink","title":"ギャップの縮小","description":"遠く離れた乱れを先に片づけておけば、最後の隣どうしの巡回はやることが減る。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:scanUntilFound","title":"線形探索","description":"同じ目が同じ列を二度たどる — 一度は途中で止まり、一度は端を越えて出ていく。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:halveTheRange","title":"区間を半分にする","description":"一度の比較で、ちょうどこれだけの候補が消える。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:requiresSorted","title":"ソート済みという前提","description":"同じ七つの値を並べた二列に、同じ二分探索をかける。片方は整列、片方は乱れたまま。乱れた列は、そこにある値を「ない」と答える。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:guessByValue","title":"補間推定","description":"値が均等に散らばっていれば、値そのものがどこを見るか教えてくれる。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:divideConquerCombine","title":"分割統治","description":"割りながら下り、答えになって上がる — 同じ場所を逆にたどる","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:overlappingSubproblems","title":"重なり合う部分問題","description":"再帰定義をそのままたどると、同じ項が別の枝で何度も芽を出す","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:memoWriteOnce","title":"メモ化","description":"解けた項は表へ移して書き、また出会えば枝を伸ばさずに表から値を読む。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bottomUpTable","title":"ボトムアップの表","description":"小さいほうから表を埋めていけば、再帰はそもそも要らない","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:takeBestNow","title":"貪欲な選択","description":"基準ひとつで一枚を取り、振り返らない — 残りに収まる最大の硬貨が下り、残りが減る","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:greedyCanFail","title":"貪欲法が失敗するとき","description":"同じ硬貨で同じ金額を作る二列。大きいほうから取った列のほうが枚数は多くなる。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:tryAndUndo","title":"バックトラッキング","description":"手を戻すことが失敗の後始末ではなく、手順の片割れである理由。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:pruneBranch","title":"枝を刈る","description":"部分木ごと飛ばしても答えを失わない理由。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:boundAndCut","title":"限界で枝を刈る","description":"最善を見積もっても今の最高に届かない枝は、たどる前に刈る。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bfs","title":"幅優先探索 (BFS)","description":"同心の波面 — 同じ距離の頂点が一度の閃光で同時に見つかる","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:dfs","title":"深さ優先探索","description":"一つの枝を行き止まりまでたどり、戻って次の枝に入る。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:dijkstra","title":"ダイクストラ法","description":"未確定のうち最も近い頂点を確定し、その隣を緩める。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:bellmanFord","title":"ベルマン-フォード","description":"全辺を n-1 回なでる — 一巡ごとに距離が一層ずつ深く染みる。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:floydWarshall","title":"フロイド–ワーシャル","description":"全点対間の最短経路 — 中継する頂点をひとつずつ変えながら。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:primMst","title":"プリム法","description":"木を一本だけ育てる — 外へ出るいちばん軽い辺をつないで。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:kruskalMst","title":"クラスカル法 — 軽い辺から","description":"辺を重み順に並べて上から取り、両端がすでに同じグループにある辺は捨てる。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:topologicalSort","title":"トポロジカルソート","description":"入ってくる矢がないものから取り出す — 取るたびに次のものが解ける。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:scc","title":"強連結成分","description":"深さ優先の巡回一度で、互いに行き来できる頂点の集まりをすべて見つける。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:maxFlow","title":"最大流","description":"余裕の残る道を見つけ、ボトルネックの分だけ流す。道がなくなるまで繰り返す。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:oneWayEdge","title":"有向辺","description":"同じ線でも、矢が付けば戻る道が消える。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:fewerHopsNotShorter","title":"経る辺が少なくても短いとは限らない","description":"同じ二頂点を結ぶ道が二本。辺の数が少ないほうが、重さでは遠い道だ。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:queueVsStackOrder","title":"順序を決めるのは器","description":"同じグラフ、同じ隣の順 — 器を替えるだけで訪問順が分かれる。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:diveThenBacktrack","title":"潜って、たどって戻る","description":"深さ優先の探索は、潜る歩数と同じだけ、戻る歩数を使う。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:markVisitedOrLoop","title":"訪問の印","description":"通った場所に印を残さないと、探索は同じ三か所をいつまでも回り続ける","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:separateComponents","title":"分かれた連結成分","description":"一度の探索は自分の塊から外へ出られない — 残りは出発し直さないと灯らない","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:twoColorConflict","title":"奇数の輪で二色がぶつかる","description":"頂点五つの輪を回りながら二色を交互に塗り、最後の辺で破れるのを見る。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:relaxShorterPath","title":"緩和","description":"短い道が見つかれば、書いてあった距離を消して小さい数に書き直す。上がることは決してない。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:pickNearestUnsettled","title":"一番近いものから固める","description":"揺れているもののうち最小の数を持つものは、もう下がりようがない。だから固まり、固まった後は何が触れても揺れない。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:negativeEdgeBreaks","title":"負の辺が確定を壊す","description":"近いものから確定していく方法は、負の辺があると誤った数を残す。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:repeatRelaxAll","title":"すべての辺を、巡るたびにゆるめる","description":"一巡では終わらない理由 — 一巡で情報はちょうど一つ分しか進まない。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:oneMoreRoundDrops","title":"もう一周すると、また下がる","description":"n−1 周を終えてもなお距離が下がるなら、グラフに負の閉路がある。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:throughMiddleNode","title":"真ん中を経ると短くなるか","description":"最短距離表がすべての組に投げ続ける、たった一つの問い。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:heuristicGuides","title":"推測が探索を導く","description":"残りの距離を見積もって足すと、探索が目標のほうへ傾く。見つかる道は同じで、開いたマスの数が変わる。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:growOneTree","title":"木を一本だけ育てる","description":"プリム法は、すでに木に接している辺の中からしか選ばない。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:sortEdgesAvoidCycle","title":"辺を軽い順に、輪になるものは捨てる","description":"軽い辺から順に取り、両端がすでに同じ組にある辺は捨てる。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:indegreeZeroFirst","title":"入ってくるものがないものから取る","description":"入ってくる矢のない頂点だけを取れる。取ればその頂点が掛けていた矢が落ち、0 になったものが次に落ちる。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:cycleBlocksOrder","title":"輪があれば順序はない","description":"輪に囚われた頂点は互いを待ち合い、ついに何も取り出せなくなる","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:mutuallyReachable","title":"互いに行き来できる仲間","description":"片道だけでは仲間にならない — 行き来できてこそ一つの群れだ。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:bottleneckSetsFlow","title":"最も細い管が量を決める","description":"ひとつの経路に流せる量は、その経路で最も細い管が決める。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:undoByBackEdge","title":"逆辺で取り消す","description":"流した分だけ押し戻せる余地ができ、詰まった流れはその余地でほどける。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:kmp","title":"KMP","description":"一つずつずらす方法は、それまで一致した分をすべて捨てる。KMP はパターンが自分の中に持つ重なりの分だけを残す。つまみを動かすと、その差が広がるのが見える。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:boyerMoore","title":"Boyer-Moore","description":"後ろから照合すると、一度の不一致が何マス分もの跳躍になり、跳ぶ距離は不一致だったその文字が決める。パターンが長いほど遠くまで跳ぶ。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:rabinKarp","title":"パターンが長くなっても触れる文字は変わらない","description":"パターンを長くしても、転がるハッシュが触れる文字数は動かない。その隣で単純な比較は三倍になる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:suffixArray","title":"接尾辞配列","description":"接尾辞を一度並べておけば、どんなパターンも二分探索で見つかる — すべての出現が一つの塊に集まる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:zAlgorithm","title":"Zアルゴリズム","description":"各位置が先頭とどれだけ重なるかを一度求めておけば、文字列検索はその表から落ちてくる。しかもその表を作る作業自体が、同じ文字を二度見ない。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:ahoCorasick","title":"エイホ・コラシック","description":"パターンを増やしてもテキストは一度しか読まない。つまみを動かして、動かない数を見る。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:editDistance","title":"編集距離","description":"表を埋めると数が一つ出るが、その表を逆にたどると実際の修正の一覧が出る。そして何を高く見積もるかがその一覧を変える。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:naiveShiftByOne","title":"パターンを1文字ずつずらす","description":"先頭から比べ、食い違ったらそれまでに一致した分をすべて捨ててパターンを1つずらす。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:prefixSuffixJump","title":"接頭と接尾の重なり","description":"パターンが自分の体を折り返して重なる場所を見つけ、食い違ったら重なった分だけ滑らせる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:matchFromBack","title":"後ろから照合する","description":"パターンを最後の文字から照合すると、前を読まずに位置ごと除外できる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:badCharSkip","title":"一致しない文字が跳ぶ距離を決める","description":"パターンに含まれない文字はどのマスとも一致しないので、パターンは一度でその文字を越えた先に立つ。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:rollingHash","title":"転がるハッシュ","description":"窓を一つずらすとき、前を引いて後ろを足せば、ハッシュは次の値へ転がる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:allSuffixesSorted","title":"すべての接尾辞を並べる","description":"文字列のすべての接尾辞を並べ替えると、先頭が同じものが隣り合う。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:matchLengthPerSpot","title":"位置ごとの一致の長さ","description":"すでに確認した区間の中なら、比べ直さずに鏡の位置から答えを借りる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:manyPatternsOnePass","title":"複数のパターンを一度の走査で","description":"四つのパターンを一本の木に重ねると、テキストを一度通るだけで全部が掛かる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:failLink","title":"ずれたとき、どこへ戻るのか","description":"ずれたら最初ではなく、重なる位置へ滑る。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:editTableFill","title":"編集表を埋める","description":"表の各マスは二つの接頭辞の編集距離であり、すでに埋まった三つの隣から作られる。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:threeEditChoices","title":"一つのマスを決める三つの道","description":"編集距離の表のマスは三つの提案のうち最も安いものを取る — 上からの削除、左からの挿入、斜めからの置換またはそのまま。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:euclidean","title":"ユークリッドの互除法","description":"大きいほうを余りに置き換えて縮めていくと最大公約数にたどり着く。つまみを動かして最も手数のかかる組を見てほしい。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:fastPower","title":"高速な冪乗","description":"一つずつ掛ける代わりに二乗を重ねて冪乗に届く。指数を動かすと単純な方は爆発し、速い方はほとんど動かない。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:sieve","title":"エラトステネスの篩","description":"倍数を消すと残るのが素数だ — 上限を動かしても消す数が増えないのを見る。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:primality","title":"素数判定","description":"平方根までで判定は終わる。それがどれほどの節約かは素数でこそ見えてくる。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:matrixMul","title":"行列の掛け算 — 一段で掛け算を一つ減らすと","description":"一段は掛け算一つを足し算いくつかと引き換える。差はちょうど一つ、そして再帰がその一つを爆発させる。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:squareAndHalve","title":"繰り返し二乗法 — 列を半分に折る","description":"3 を十三回掛ければ掛け算は十二回かかる。代わりに十三枡の列を半分に折る。対になった二つが出会って二乗になり、折るときに余る奇数の一枡は答えへ送る。掛け算六回で同じ数に届き、送った枡は 13 を二進法で書いた 1101 の 1 の桁とぴったり同じだ。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:divisorPairsSqrt","title":"約数のペア","description":"約数は必ず対になり、対の小さい側は常に平方根以下にある。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:rowTimesColumn","title":"行かける列","description":"積の1マスはどこから来るのか — Aの行1つとBの列1つが1か所で噛み合う。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:bigO","title":"Big-O 記法","description":"n が大きくなると 4 つの項が席を入れ替える。最初は 1 位だった定数が最下位になり、名として残るのは n³ ひとつだ。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:asymptotic","title":"漸近解析","description":"同じ階級の二つの関数は比が最後まで一定にとどまり、階級が違えば比は際限なく開いていく。入力の大きさを動かして、どちらの比が 2 のままかを見てほしい。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:pNp","title":"P対NP","description":"答えを確かめる仕事と見つけ出す仕事は同じではない — 大きさを動かして二つの値が分かれるのを見る。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:growthOutpaces","title":"最大の項が残りを飲み込む","description":"n² + 10n + 100 を1本の帯の3つの取り分に分ける。n が大きくなると n² が残りを飲み込む。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:constantFades","title":"定数を消す理由","description":"定数は二つの増加速度が出会う場所を先送りするだけで、勝つ側を変えはしない。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:curvesCross","title":"曲線が交わるところ","description":"入力が小さいうちは遅いはずのアルゴリズムが実際に速い — ある大きさで前後が入れ替わるまで。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:verifyVsFind","title":"検証と探索","description":"合計が目標になる部分集合を探すには候補をすべて見る必要があるが、渡された候補が正しいかは一度見れば済む。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:reduceToKnown","title":"既知の問題に置き換えて解く","description":"試験の時間割がグラフ彩色に移る — 科目が頂点になり、重なりが辺になり、時間帯が色になる。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:conditionalStatement","title":"if / else if / else","description":"流れが分かれ道に着き、条件を上から順に見ていって最初に真になった一つの枝だけを灯し、また一本の線に合流する","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:twosComplement","title":"2の補数 — 同じビット列、二つの数","description":"同じビット列が二通りの数として読まれる。どちらかは約束が決め、ビット幅もその約束の一部だ。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:floatingPoint","title":"浮動小数点 — 指数か仮数か","description":"八ビットのうち符号を除く七ビットを指数と仮数で分け合う。遠くへ届くために指数へ渡したビットは、細かさから取り上げたものだ。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitwiseOps","title":"ビット演算 — 八つの桁がそれぞれ","description":"同じ二バイトに六つの規則。各桁が一行の規則を単独で適用し、桁どうしが関わるのはシフトだけ。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:integerOverflow","title":"オーバーフロー — 増える数列が器を超える場所","description":"どこで超えるかは器の大きさが決める。超えた瞬間、値は大きく間違うのではなく、意味をなさなくなる。そして誰も知らせてくれない。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:positionalValue","title":"位取りと基数","description":"同じ数を別の基数で書く。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:negateAndAddOne","title":"ビットを反転して1を足す","description":"すべてのビットを反転して1を足すと負数になる。その理由を桁上がりが示す。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:signedWraparound","title":"数の端と端","description":"8ビット符号つきでは、最大の数の次が最小の数になる — 直線ではなく輪だ","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:silentTruncation","title":"静かに切り捨てられる上位ビット","description":"器より大きい値は上位ビットを失う。それを知らせるものは何もない。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:mantissaAndExponent","title":"仮数と指数","description":"32 ビットが三つに分かれ、その三つが一つの数を組み立てる。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:unrepresentableFraction","title":"終わらない小数","description":"0.1 は 2 進法では割り切れない。2 を掛けて桁を一つずつ取り出すと、四桁の模様が永遠に戻ってくる。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:unevenFloatGaps","title":"均一でない目盛り","description":"右へ進むほど、隣り合う二つの数の間隔が倍になる。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitMask","title":"ビットマスク","description":"マスクは穴の開いた覆いだ。穴の下のビットだけが通り、残りは 0 で覆われる。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitShift","title":"ビットシフト","description":"ビットを 1 つずらすと数は 2 倍か半分になる。端を越えたビットは消える。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:byteOrder","title":"バイト順序","description":"同じ値がメモリに正反対の順序で置かれること、そして誤った順序で読んだときに何になるか。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:cacheLine","title":"キャッシュライン — 1 バイトではなく行ごと動く","description":"行を広げると連続読みは一段ごとに良くなるが、飛び飛び読みは歩幅が同じ行に二度落ちるほど広がるまで動かない。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:directMappedCache","title":"ダイレクトマップ方式キャッシュ — 置き場所はひとつ、そして崖","description":"アドレスが置き場所を決めるので、探す場所はひとつだけ。キャッシュに収まるうちはほぼすべてヒットするが、一行はみ出した瞬間にミスが崖のように落ちる。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:setAssociativeCache","title":"セットアソシアティブキャッシュ — 同じ八つの枠、違うまとめ方","description":"枠は八つのまま。まとめを広げると押し出し合っていたアドレスが隣に座る — ある点までは。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:cacheReplacement","title":"キャッシュ置換ポリシー — 同じ11回でも答えは分かれる","description":"4つの枠に11回のアクセス。捨てる規則だけを変えると、ミス数は3通りに分かれる。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:writePolicy","title":"書き込みポリシー — 変更はいつ下へ降りるか","description":"十回の変更、二つのポリシー。下層が見る書き込みは十か五か。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:lineFill","title":"1つ呼ぶと1行まるごと上がってくる","description":"キャッシュは決まった大きさの行単位で運ぶ。1つの要素に触れると、同じ行にいる隣り3つも一緒に上がってくる。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:temporalLocality","title":"時間的局所性","description":"今読んだものをすぐまた読む — だから上の階にとどまる。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:spatialLocality","title":"空間局所性","description":"1 ラインが上がれば、続く 3 つはただで済む。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:indexAndTag","title":"インデックスとタグ","description":"アドレスを三つに切る。インデックスが行を選び、タグはその行に残って誰のものかを示し、オフセットは行の中のバイトを指す。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:conflictMiss","title":"コンフリクトミス","description":"空きがあるのに追い出される","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:associativityRelief","title":"連想度 — 一つの席に複数置けば追い出されにくい","description":"同じ四つの枠をまとめ直す。一席に一つなら追い出し合い、二つなら隣り合って座る。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:latencyLadder","title":"レイテンシの階段","description":"一段下りるたびに数十倍。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:writeBackVsThrough","title":"今すぐ書き戻すか、ためておくか","description":"同じ七回の書き込みが、write-through では七回、write-back では四回のメモリ書き込みになる。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:falseSharing","title":"フォルスシェアリング","description":"2 つのコアが別々の値を触るのに、1 つのキャッシュラインが両方を抱えているため、書くたびに相手の複製が捨てられる。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:fiveStagePipeline","title":"5段パイプライン","description":"命令を五つの段に分け、前の命令が出る前に次の命令を入れる。命令一つは相変わらず 5 サイクルかかり、たくさんの命令はより早く終わる。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:dataHazard","title":"データハザード","description":"後の命令が、前の命令がまだ書いていない値を読む。待たなければ速いが古い値を読み、待てば正しいがサイクルを失う。フォワーディングでほとんど取り戻し、最後のバブルは並べ替えでしか埋まらない。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:controlHazard","title":"制御ハザード","description":"「分岐しない」と予測して取り込み続けると、分岐が成立するたびに判定前に入ったものを捨てる。判定が遅いほど捨てる尾が長い。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:outOfOrderExecution","title":"アウトオブオーダー実行","description":"ウィンドウを広げると、後ろの命令が追い越してロード待ちの空きサイクルを埋める。それでもコミットはプログラム順のままだ。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:stageOverlap","title":"ステージの重なり","description":"前の命令が終わる前に次の命令が入る。サイクルごとに全員が一段進み、空いた IF に次の命令が入る。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:throughputNotLatency","title":"速くなるのはスループット","description":"二つの機械が同じ五つの命令を並んで実行する。一つの命令が中にいる時間はどちらも五サイクルで、最後の命令が出てくる時刻だけが違う。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:readBeforeWrite","title":"まだ出ていない値","description":"後の命令はなぜ前の命令を待たなければならないのか?","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:operandForwarding","title":"フォワーディング","description":"I1 が EX で出した結果は、レジスタファイルに書かれる前に I2 の EX へ直接渡る。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:pipelineBubble","title":"パイプラインのバブル","description":"ロード命令の直後の命令がその値を使うと、フォワーディングでも間に合わない。パイプラインは 1 サイクル止まり、その空きが命令のように EX・MEM・WB を流れていき、後ろの命令はみな 1 サイクル遅れて終わる。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:branchFlush","title":"誤って入れたものを捨てる","description":"分岐の行き先を読み違えると、先に詰めたものを空にする。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:dualIssue","title":"一拍に二つ","description":"一拍に二つ発行できるインオーダーの機械は、二つ目が一つ目の結果を読まないときだけ二つを一緒に出す。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:readyFirst","title":"準備できたものから","description":"アウトオブオーダー実行は準備できた命令から実行するが、結果は元の順序でコミットする。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:staticPrediction","title":"静的分岐予測","description":"分岐を方向だけで推測したとき、失うサイクルがどこへ移るかを見る。常に不成立はループの後方分岐をすべて外し、常に成立はまれな検査の前方分岐を外し、「後方なら成立」は両方を当てる。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:saturatingCounter","title":"飽和カウンタ","description":"一度外れただけで考えを変える分岐予測器は、ループを抜けるたびに二度外す。どれだけ持ちこたえるべきか。カウンタのビット数を変えて、針がしきい値をまたぐ様子を見る。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:branchHistoryTable","title":"分岐履歴テーブル","description":"分岐の直近数回の結果で 2 ビットカウンタを選ぶ。繰り返す模様は履歴が十分長くなると外れが止まり、ランダムな分岐は半分を超えない。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:mispredictionPenalty","title":"外れた予測の代償","description":"分岐の予測を外すたびに、その後ろで取り込んだサイクルを捨てる。判定が遅いパイプラインほど、一度に高く積み上がる。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:backwardTaken","title":"後ろへ跳ぶならループ","description":"結果が出る前に向きだけで分岐を予想する静的な規則 — 後ろへの分岐は成立、前への分岐は不成立。ループは繰り返すたびに後ろへ跳ぶので、この規則はほぼいつも当たる。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:oneBitDoubleFault","title":"1ビット予測の二度の外れ","description":"直前の結果だけを覚える予測器は、ループを抜けるときに外し、記憶が反転したせいで次にループに入るときにも外す。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:fourStateHysteresis","title":"四つの段を一段ずつ","description":"2ビットカウンタは一度外れただけでは予測を変えない。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:patternFromHistory","title":"直近の数回が次を指す","description":"直近二回の結果が表の一つのマスを指し、予測はそのマスから出る。マスが埋まると交互のパターンが表に刻まれ、もう外れない。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:unpredictableBranch","title":"予測できない分岐","description":"分岐が硬貨投げに従うなら、どの予測器も正解は半分あたりに落ち着く。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:structAlignment","title":"構造体のアラインメント","description":"同じ5つのフィールドが16バイトにも32バイトにもなる。アラインメントを厳しくするほどフィールドが押し出されて隙間が開き、大きい順に並べると隙間はすべて閉じる。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:arrayTraversalOrder","title":"配列の走査順序","description":"同じ合計でも順序を変えるとキャッシュミスが4倍になる——ただし行数がキャッシュを超えたときだけ。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:prefetching","title":"プリフェッチ","description":"使う行を先に呼べば待ちが消える。先に呼びすぎると、使う前にキャッシュから押し出される。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:simd","title":"SIMD","description":"1 回の加算が複数のレーンをまとめて押し進める。だが割り切れずに残った端数は 1 つずつ進むしかない。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:paddingGap","title":"アラインメントとパディング","description":"各フィールドは自分のアラインメントの倍数の位置まで押し出され、飛ばしたバイトは隙間として残る。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:fieldOrderSize","title":"並べ順でサイズが変わる","description":"同じ4つのフィールドを大きい順に並べ直すと、隙間が埋まって構造体が小さくなる。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:rowVsColumnWalk","title":"行優先と列優先の走査","description":"同じ配列を行ごと・列ごとに足す。合計は同じだが、キャッシュミスは違う。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:strideAndMiss","title":"飛ばし読みの間隔","description":"キャッシュラインは常に丸ごと上がってくるが、使われるのは読んだ要素だけ。ストライドが長いほど上がる行が増え、捨てる分も増える。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:fetchAhead","title":"先回りして読み込む","description":"要素を順に読むとき、今の行を読み始めた時点で次の行を要求すれば、カーソルが着く前にその行は届いている。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:lanesInStep","title":"並んで進むレーン","description":"SIMD 命令ひとつは a + b の 4 レーンを一度に押し進め、同じ拍でスカラー側は要素をひとつだけ足す。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:contextSwitching","title":"コンテキストスイッチ — 一つの舞台, 二人の主","description":"ただ一つの CPU 舞台で主が入れ替わる — 一方の流れのレジスタ束が自分の保管所へ持ち上げられ、他方の束が同じ場所へ戻され、それぞれ止まった時点から時間が再び動き出す","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:ipRouting","title":"IP ルーティング","description":"パケットはルータからルータへ跳ぶ — どのルータも自分の表だけを見て最長一致の next-hop を選び、跳ぶたびに TTL が一つ減る","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:relationalTablesAndKeys","title":"テーブルとキー","description":"名前を持つ二つの格子 — 一方の主キーが各行の身元を固定し、他方の外部キーがその固定値を指して、二つを一貫した一つの構造に結ぶ","domain":"databases","subdomain":"relational"},
    {"id":"facet:tokenization","title":"トークン化 (字句解析)","description":"左から右へ進む視線が同じ種類の文字を一つの区間に融かしていき、もう伸ばせなくなった時点で閉じて、その区間を種類のラベルを付けたトークンカードとして出力の列へ落とす","domain":"compilers","subdomain":"lexical"},
    {"id":"facet:linearRegression","title":"線形回帰 — 点の間を貫く直線","description":"(w, b) を坂の下へ滑らせて直線を合わせる — 残差の正方形が縮むにつれ、点が谷へ転がっていく","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:logisticRegression","title":"ロジスティック回帰 — 確率を学び、線を選ぶ","description":"重みは学び、しきい値は選ぶ。上げれば空振りが減り、見落としが増える。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:knn","title":"k 近傍法 — 何人に尋ねるか","description":"学習はしない。問うたびにデータを見直す。k を動かせば境界全体が変わる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:decisionTree","title":"決定木 — 質問はどこで止めるべきか","description":"ノードごとにすべての切り方を試し、最も混ざりの少ないものを選んで両側でまた問う — 深さの上限を上げて、得るものが尽きる地点を見る。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:randomForest","title":"ランダムフォレスト — 木を増やすと何が加わるか","description":"木が一本なら、どこでも 100% 言い切る。森はどれだけ確かかまで教えてくれる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:svm","title":"サポートベクターマシン — 隙間の中に点が入ってしまったら","description":"ヒンジ損失と劣勾配降下。最も広い隙間がどれだけの誤りを飲み込んでよいかを C が決める","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:residualDistance","title":"残差","description":"点が直線からどれだけ離れているかを、y 方向にまっすぐ測る。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:leastSquares","title":"最小二乗","description":"符号のあるずれをそのまま足してはなぜいけないのか、そして二乗が何を直すのか。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:squashToProbability","title":"スコアを確率へ押し込める","description":"果てのない軸が、0 と 1 のあいだの帯に折り畳まれる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:decisionBoundary","title":"決定境界 — 最後に現れる線","description":"まず場所ごとに確率が付き、それが半分をまたぐところが境界になる","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:voteByNeighbors","title":"近い隣人の投票","description":"近い五つが一つずつ呼ばれ、それぞれ自分の側に票を入れる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kChangesBoundary","title":"k が答えを変える","description":"最も近い一つと最も近い三つが違う答えを出す。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:splitByQuestion","title":"良い問いとは何か","description":"一つの軸に沿って切り線を滑らせてもラベルは分かれない。もう一方の軸に立て直せば、最初の位置できれいに分かれる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:impurityDrops","title":"「よく分けた」を何で測るか","description":"混ざり具合が一つの数になり、分けるたびにその数が下がる。その数は個数ではなく割合を読む。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:manyTreesVote","title":"アンサンブルの多数決","description":"五本の木が同じ五問に答える。全問正解の木はないが、多数決は全問当てる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:baggingSample","title":"バギング","description":"戻しながら引くと、袋ごとに学ぶものが変わる。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:widestMargin","title":"最大マージン","description":"二つの群を分ける線のうち、帯が最も厚く開くものを選ぶ。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:supportVectorsOnly","title":"線を決めるのは縁に触れたものだけ","description":"十個の点のうち、この線を決めたのは何個か。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kernelLifts","title":"カーネルトリック — まっすぐな線で足りるまで持ち上げる","description":"分けられなかったものも、次元をひとつ上げれば分けられる","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kmeans","title":"k-means — 中心を知らないまま集まりを見つける","description":"同じ k でも出発点が違えば答えが違う — しかも最も詰まった答えは人が見る集まりではない。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:hierarchical","title":"階層的クラスタリング — 二つの群れの距離を何で測るか","description":"単連結・完全連結・平均連結は同じ八点から三つの違う木を作り、同じ高さで切っても答えが三つに分かれる","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:dbscan","title":"DBSCAN — 二つのつまみは別のものを触る","description":"eps は離れていたものをつなぎ、minPts は小さな塊を崩す。群れの数が同じでも、その中身はまるで違う組み合わせから来る。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:pca","title":"PCA — 最も広がった方向は軸の単位しだいだ","description":"べき乗法で主軸を見つける。二つの軸を標準化すると、その主軸が 42 度回る","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:tsne","title":"t-SNE — 平らにした絵から読めるものと読めないもの","description":"パープレキシティが集まりを壊すか、ぼかすか、きれいに分けるかを決める — そしてきれいに分かれた絵でも集まり同士の距離は残らない","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:assignThenMove","title":"割り当てて、動かす","description":"点は最も近い中心をつかみ、中心はつかんだ点たちの真ん中へ滑る。動きが止まるまで交互に繰り返す。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:kMustBeGiven","title":"k は与えるしかない","description":"同じ十二点が三通りに分かれ、散らばりを測ってもどれかを選べない。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:mergeNearestPair","title":"個数を先に決めずにクラスタリングできるか","description":"最も近い二つを合わせ、その距離の高さに継ぎ目を吊る。そうして育つ木の高さが、どれだけ離れたものを合わせたかを語る。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:dendrogramCut","title":"デンドログラムを切る","description":"木のどこで切るかが、まとまりの数を決める。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:denseNeighborhood","title":"広がりが届く範囲がひとつの集まり","description":"隣の隣も同じ集まりに入る。だから集まりが丸い必要はない。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:noiseLeftOut","title":"ノイズ点","description":"どの群れにも属さない点を、方法はどう扱うか。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:directionOfMostSpread","title":"最も広がる方向","description":"点の群れを貫く軸をまわし、落とした跡が最も広がるところで止める。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:projectAndLose","title":"射影して失う","description":"次元を一つ落とすと何が消えるのか。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:keepNeighborsClose","title":"近いものを近いままに","description":"輪の上の十点を一直線に伸ばす。隣り合う九組は保たれ、一組が裂ける。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:globalAndLocal","title":"大域と局所 — 二通りの平坦化を並べて","description":"等間隔に見えるクラスタの隔たりが、実は等間隔とは限らない","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:subwordSegmentation","title":"サブワード分割 — 語彙が大きいほど同じ文は切られにくくなる","description":"マージ回数を増やすと、散らばっていた文字どうしが滑り寄って一つになる — 同じ文が 33 個から 7 個になる","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:bpeTraining","title":"BPE 学習 — よく出るものが、何を先に結合するかを決める","description":"一つの語の頻度を動かすと、ペアが順位を争って入れ替わり、結合の順番が組み替えられ、最後には別の語彙が出てくる","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:vocabulary","title":"語彙辞書 — 何を入れたかが、何をうまく切れるかを決める","description":"同じ BPE を三つのコーパスで学習すると、同じ六つの単語が違う形に割れる — biology と code は合計 32 で並ぶのに、うまく切れる単語は正反対だ","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:betweenLetterAndWord","title":"文字と単語のあいだ","description":"一つの文を三つの大きさで切る — かけらは文字と単語のあいだに落ち着く。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:mergeTheFrequentPair","title":"よく隣り合う組を合わせる","description":"最も頻繁に隣り合う組が一つの断片になり、同じ継ぎ目がコーパス全体で一度に閉じる。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:unknownBecomesKnown","title":"知らない語を受け取る","description":"語彙が一度も見たことのない語が、見たことのある二つの断片に割れ、その断片で綴られて通り抜ける。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:spaceIsPartOfIt","title":"空白もひとつの文字","description":"空白をひとつの文字として書くと、その印は断片にくっついて回り、同じ単語が語彙の中で二つの席を占めることになる。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:tokensPerLanguage","title":"言語ごとに違うトークン数","description":"同じ意味の文でも、言語によってトークン数が何倍も変わる。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:boundaryShift","title":"一文字の違いで","description":"文字を一つ変えるとトークンの境界が崩れ、ひとまとまりだった語が三つの断片に割れる。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:vectorSimilarity","title":"ベクトル類似度","description":"何で測るかが、誰が似ているかを変える。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:exhaustiveSearch","title":"全探索","description":"候補は64のままだが、次元を上げると走査する量が板を埋め尽くすほど膨れ上がる。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:hnsw","title":"HNSW — 層を重ねればどこから出発しても届く","description":"層の数を回してみる。1 層では 6 つの歩みのうち 1 つしか真の最近傍に届かないが、3 層では 6 つとも届く。その代わり見る点は減らず増える。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:invertedFileIndex","title":"転置ファイル索引","description":"いくつの区画を開くかが、正確さと速さを同時に決める。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:productQuantization","title":"直積量子化","description":"ベクトルを区画に分け、区画ごとに番号を一つだけ残す。細かく分けるほど誤差は減り、記憶は増える。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:angleNotLength","title":"長さではなく角度","description":"コサイン類似度は方向を比べる。順位を決めるのは角度で長さは外れるため、ユークリッド距離と食い違うことがある。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:compareWithAll","title":"すべてと見比べる","description":"正確だが数が増えると持ちこたえられない — 掛け算が候補数かける次元だけ積み上がる。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:neighborsLinkedAhead","title":"近い点をあらかじめつないでおく","description":"道が先に引かれていれば、すべてを測らずに歩いて答えにたどり着ける。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:coarseThenFine","title":"粗い層で大きく、下の層で細かく","description":"点の少ない上の層で大きく跳んで場所を決め、下の層がその場所を受け継いでさらに細かく絞る。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:probeAFewCells","title":"いくつかのセルだけを開く","description":"クエリは近いセルの点とだけ比べられ、開かなかったセルの点には触れない。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:splitAndNumber","title":"分割して番号に","description":"ベクトルを二つの断片に切り分け、断片ごとに最も近い代表の番号だけを残す。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:recallSpeedTradeoff","title":"探す範囲を狭めると取りこぼす","description":"本当に近い五つは決まっている。探す範囲を狭めると、そのうちいくつかが答えから抜け、より遠い点がその席を埋める。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:whereToCut","title":"切る位置","description":"一定の語数ごとに文章を切ると、切れ目が文の途中に落ちる。段落の終わりで切れば、同じチャンク数でも文はどれも切れずに残る。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:overlapTheSeam","title":"継ぎ目を重ねて切る","description":"次の窓が継ぎ目から数語さかのぼって始まり、切れ目にかかった文が一つのチャンクにまるごと収まる。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:sameWordVsSameMeaning","title":"同じ単語と同じ意味","description":"キーワード検索(BM25)と意味検索(コサイン)が、同じ5つの文書を別々の順に並べる。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:fuseTwoRankings","title":"二つの順位を合わせる","description":"各リストが順位だけで決まる取り分を文書に渡し、積み上がった分で新しい並びができる。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:lookCloselyAtFew","title":"少数だけを見直す","description":"8件の候補のうち上位4件だけが線を越えてクエリと一つずつ突き合わされ、その4件の間で順位が入れ替わる。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:budgetRunsOut","title":"枠が足りなくなる","description":"指示文・質問・回答枠が先に席を取り、チャンクは残りの枠を順位順に埋めていき、入りきらないチャンクで止まる。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:lostInTheMiddle","title":"中間での見落とし","description":"同じ答えのチャンクが、コンテキストの先頭から真ん中へ、さらに末尾へと移る。モデルは両端をよく拾い、その間にあるものを見落としやすい。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:alwaysTheHighest","title":"いつも1位だけ","description":"貪欲デコーディングは毎回もっとも確率の高い次のトークンを選ぶ — すると文は自分の通った道を繰り返す。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:flattenOrSharpen","title":"温度: 平らにするか、尖らせるか","description":"softmax の前にロジットを温度で割ると、確率は1位に集まるか下位へ広がる。順位は変わらない。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:cutTheTail","title":"top-k — 裾を切ってから引く","description":"top-k は k 位より下の候補を捨て、その分を残った候補に大きさに比例して配り、残りからだけ引く。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:fillToAShare","title":"割合が満ちるまで","description":"top-p は確率の高い候補から順に加え、その割合が p に達するまで残す。尖った文脈は二つで、平らな文脈は七つで止まる。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:carrySeveralLines","title":"複数の列を運ぶ","description":"ビームサーチは貪欲法が見逃す文をどう捉えるか。残った列がそれぞれ枝分かれし、すべての枝を対数確率の和で並べ、上位のいくつかだけを残す。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:penalizeRepeats","title":"繰り返しペナルティ","description":"すでに書いた候補のロジットを削る。正の値は θ で割り、負の値は掛ける。削られた1位が新しい候補の下に沈む。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:eraseTheImpossible","title":"不可能な候補は先に消す","description":"文法制約付きデコーディング — 選ぶ前に文法が禁じる候補を消し、その分を残りの候補が分け合う。ロジットは例として決めた値。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:dontRecountThePast","title":"過去を数え直さない","description":"トークンをもう一つ出すには、それまでのすべての位置の K と V が要る。キャッシュがなければ毎ステップすべてを計算し直し、KV キャッシュがあれば新しい位置一つだけを計算して残りはそのまま留まる。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:cacheKeepsGrowing","title":"キャッシュは増え続ける","description":"文章が長くなると KV キャッシュはどれだけ大きくなるか","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:shortWaitsForLong","title":"短いリクエストは長いものを待つ","description":"長さの違うリクエストを一つのバッチで回すと、先に終わったリクエストはどうなるのか?","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:refillTheEmptySlot","title":"空いた席をすぐ埋める","description":"ひとつのリクエストが終わって席が空くと、キューの次のリクエストがすぐ次のステップでその席に入る。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:draftThenVerify","title":"下書きしてから確かめる","description":"小さなモデルが四つのトークンを先に書き、大きなモデルは一回の呼び出しでそれをまとめて確かめ、先頭から合っているところまでを残す。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:firstTokenVsRest","title":"最初の一回とその後","description":"最初のステップではプロンプト全体が一度に K·V 計算を通り、その後は直前に出したトークンだけが入る。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:lruCache","title":"LRU キャッシュ","description":"容量の決まったキー値ストア — 触れたノードはすべて MRU 端へ引き上げられ、あふれれば LRU 端が消える","domain":"system-design","subdomain":"caching"},
    {"id":"facet:cachingCdn","title":"CDN","description":"世界中に散らばったエッジキャッシュが近くのクライアントを受ける — 手元にある答えは短く返り、無い答えは上位階層まで行って戻り、エッジを満たしていく","domain":"system-design","subdomain":"caching"},
    {"id":"facet:messagingPubsub","title":"Pub/Sub メッセージング","description":"発行者と購読者が互いではなく broker のトピックだけを知る多対多の非同期メッセージング — 一度の発行が全購読者へ複製として広がる","domain":"system-design","subdomain":"messaging"},
    {"id":"facet:asymmetricRsa","title":"RSA — 公開鍵暗号","description":"二つの素数から生まれた一対の非対称鍵 — 片方でしか掛からず、もう片方でしか外れず、掛けた鍵では決して戻せない","domain":"security","subdomain":"asymmetric"},
    {"id":"facet:hashFixedLength","title":"固定長の出力","description":"入力は空からファイル一つ分まで、出力はいつも同じ大きさ","domain":"security","subdomain":"hash"},
    {"id":"facet:hashAvalanche","title":"なだれ効果","description":"一文字変えるだけで、ハッシュ出力の半分ほどが反転する","domain":"security","subdomain":"hash"},
    {"id":"facet:pigeonholeCollision","title":"鳩の巣原理","description":"席は十六、入力は十七 — ひとつは自分の席を持てない","domain":"security","subdomain":"hash"},
    {"id":"facet:hashIntegrityCheck","title":"完全性の検証","description":"公開されたハッシュ一つが、受け取った複製に手が加わったかを教える","domain":"security","subdomain":"hash"},
    {"id":"facet:hashSalt","title":"ソルト","description":"アカウントごとに違うソルトが、同じパスワードを同じ形で保存させない","domain":"security","subdomain":"hash"},
    {"id":"facet:hashChain","title":"ハッシュチェーン","description":"各欄が前のハッシュを抱えているので、一度の書き換えがその後をすべて狂わせる","domain":"security","subdomain":"hash"},
    {"id":"facet:merkleTree","title":"マークル木","description":"ハッシュを二つずつ畳んでおけば、葉が一つ変わっても頂上まで一筋だけが動く","domain":"security","subdomain":"hash"},
    {"id":"facet:signatureKeyDirection","title":"鍵の向き","description":"暗号化と署名は同じ鍵の対を逆向きに使う","domain":"security","subdomain":"signature"},
    {"id":"facet:signatureOnHash","title":"ダイジェストに署名する","description":"文書がどれほど大きくても署名は 64 バイトのままだ","domain":"security","subdomain":"signature"},
    {"id":"facet:matrixTransform2d","title":"2D 行列変換 — 二つの列は二つの基底の行き先","description":"2×2 行列は i-hat と j-hat の行き先そのものだ — 平面上のどの点も同じ (u, v) 係数のまま新しい基底の組み合わせへ移り、直線は直線のまま、原点はその場に残る","domain":"graphics","subdomain":"transform-2d"},
  ],
};
