/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-facet-catalog.mts)
 * 출처: 각 facet 의 facet.ts(title/description) + taxonomy/taxonomy.json(분야).
 */

import type { FacetCatalog } from '../catalog-types.js';

export const CATALOG: FacetCatalog = {
  locale: "zh",
  domains: [
    {"id":"cs-fundamentals","name":"计算机科学基础","subdomains":[{"id":"data-structures","name":"数据结构"},{"id":"probabilistic-structures","name":"概率数据结构"},{"id":"algorithms","name":"算法"},{"id":"graph-algorithms","name":"图算法"},{"id":"string-algorithms","name":"字符串算法"},{"id":"numerical-algorithms","name":"数值算法"},{"id":"complexity","name":"计算复杂度"}]},
    {"id":"programming-fundamentals","name":"编程基础","subdomains":[{"id":"control-flow","name":"控制流"},{"id":"variables-types","name":"变量与类型"},{"id":"functions","name":"函数"},{"id":"oop","name":"面向对象编程"},{"id":"fp","name":"函数式编程"},{"id":"memory-model","name":"内存模型"}]},
    {"id":"computer-architecture","name":"计算机体系结构","subdomains":[{"id":"number-representation","name":"数与位表示"},{"id":"cache-hierarchy","name":"缓存层次结构"},{"id":"instruction-pipeline","name":"指令流水线"},{"id":"branch-prediction","name":"分支预测"},{"id":"data-layout","name":"数据布局与访问"}]},
    {"id":"operating-systems","name":"操作系统","subdomains":[{"id":"process-thread","name":"进程与线程"},{"id":"scheduling","name":"调度"},{"id":"synchronization","name":"同步"},{"id":"memory-management","name":"内存管理"},{"id":"file-system","name":"文件系统"},{"id":"io","name":"输入输出"}]},
    {"id":"networks","name":"计算机网络","subdomains":[{"id":"osi-tcp","name":"OSI / TCP-IP 分层"},{"id":"data-link","name":"数据链路层"},{"id":"network-routing","name":"网络层"},{"id":"transport","name":"传输层"},{"id":"application","name":"应用层"},{"id":"network-security","name":"网络安全"}]},
    {"id":"databases","name":"数据库","subdomains":[{"id":"relational","name":"关系模型"},{"id":"sql","name":"SQL"},{"id":"indexes","name":"索引"},{"id":"query-processing","name":"查询处理"},{"id":"transaction","name":"事务"},{"id":"distributed-db","name":"分布式数据库"},{"id":"nosql","name":"NoSQL"}]},
    {"id":"compilers","name":"编译器与语言","subdomains":[{"id":"lexical","name":"词法分析"}]},
    {"id":"ml-foundations","name":"机器学习基础","subdomains":[{"id":"supervised","name":"监督学习"},{"id":"unsupervised","name":"无监督学习"}]},
    {"id":"ai-engineering","name":"AI 工程","subdomains":[{"id":"text-tokenization","name":"分词"},{"id":"vector-search","name":"嵌入与向量检索"},{"id":"retrieval-augmentation","name":"检索增强"},{"id":"decoding","name":"生成控制"},{"id":"inference-efficiency","name":"推理效率"}]},
    {"id":"system-design","name":"系统设计","subdomains":[{"id":"caching","name":"缓存"},{"id":"messaging","name":"消息队列"}]},
    {"id":"security","name":"安全与密码学","subdomains":[{"id":"asymmetric","name":"非对称加密"},{"id":"hash","name":"哈希"},{"id":"signature","name":"数字签名"}]},
    {"id":"graphics","name":"计算机图形学","subdomains":[{"id":"transform-2d","name":"2D 变换"}]},
  ],
  facets: [
    {"id":"facet:array","title":"数组","description":"格子紧挨着排 — 知道编号就能一步抵达，可一碰中间，后面就接连挪位","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:linkedListSingly","title":"链表","description":"每个节点只有一根手指指向自己的下一个 — 插入和删除是重接手指，不是搬动卡片","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:stack","title":"栈 (LIFO)","description":"只碰一个位置 — 最后进来的最先出去","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:queueFifo","title":"队列 (FIFO)","description":"传送带 — 等得最久的最先离开的机器","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:hashTableChaining","title":"哈希表","description":"键落进函数选定的一个槽 — 落到同一槽里长出的是链条，不是混乱","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bst","title":"二叉搜索树","description":"一次比较折掉一半世界 — BST 那决定性的一刀","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:avlTree","title":"AVL 树","description":"回溯时测量 — 倾斜一致转一次，折向则转两次。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:redBlackTree","title":"红黑树","description":"重新着色把问题往上推，旋转则就此结束 — 两条规则让树保持低矮。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bTree","title":"B 树","description":"一个位置放多个键，键之间各有岔路 — 分支宽，树就矮。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:trie","title":"字典树","description":"开头相同的词共用一条路径 — 所以一个前缀就能一次全找到。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heapBinary","title":"堆","description":"按树来想，用数组来存 — 最小的总在顶端。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:unionFind","title":"并查集","description":"问两次，第二次几乎免费 — 上爬的同时路被折叠。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:indexAddressCalc","title":"从下标到地址","description":"一次乘法和一次加法，下标就变成地址。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:shiftOnInsert","title":"插在中间，后面都得挪","description":"插入点后面的值，从后往前，真的一个个向右挪一格。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:shiftOnRemove","title":"删除后前移","description":"从中间抽走一个，后面的全都往左拉。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:growAndCopy","title":"扩容并复制","description":"一块空间满了，就在别处取一块更大的，把每个值都复制过去，再把旧的还回去。地址变了。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:outOfBounds","title":"越界访问","description":"越过数组末尾的下标实际指向什么。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:nodePointsNext","title":"节点指向下一个","description":"节点散落在内存各处，却有顺序 — 顺序来自每个节点在值旁边握着的那个地址。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:traverseFromHead","title":"走到第四个节点","description":"要到某个节点，只能从 head 开始一条一条地跟着链接走。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:relinkInsert","title":"重新连接","description":"链表插入改写的是箭头，不是位置。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:lostLink","title":"链接丢失","description":"顺序错了再改指针，后面的一整段就都够不着了。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:pushPopTop","title":"入栈 · 出栈 · 栈顶","description":"只有一个口 — 最后进去的最先出来。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:enqueueDequeueEnds","title":"一头进，另一头出","description":"两道门分处两端，所以先进的先出。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:circularBufferWrap","title":"环形缓冲区: 绕回来","description":"最后一格之后就是第一格。格子不会增加，只是重复使用。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:dequeBothEnds","title":"两端都是开的","description":"双端队列的门不是四扇而是两扇 — 每扇门既进也出。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:hashToBucket","title":"把键折进桶里","description":"哈希函数把任何键折成一个整数，取余再把这个整数折进固定数目的槽位之一。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:chainingBucket","title":"链地址法 — 落到同一格，就挂在那里","description":"第二个键落到已被占用的格子时，什么也不会被挤出去。它挂到那一格垂下的链尾，查找时只沿着那条链走。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:openAddressingProbe","title":"开放定址法 — 探查下一个座位","description":"桶被占了，键就一格一格往旁边挪，直到找到空位。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:loadFactorRehash","title":"装载因子与重新散列","description":"表太满就扩容，每个键都从头重新安放。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:parentTwoChildren","title":"一个位置，两条分枝","description":"一个结点向下最多伸出两个孩子，左和右是不同名的位置，不能对调。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:traversalOrder","title":"遍历顺序","description":"同一棵树走三种顺序。只有踩到自己位置的时刻在移动。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:depthDoublesCount","title":"深一层，位置翻倍","description":"每往下一层，树能容纳的位置就翻一倍。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstCompareAndGo","title":"二叉搜索树：比较后下行","description":"每比较一次，就有整整一枝退出候选，并向下走一层","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstInorderSorted","title":"二叉搜索树的中序遍历是有序的","description":"按中序走 — 先清空左边，放下自己，再过到右边 — 值就从小到大出来","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstDegenerate","title":"只往一边长，就长成一条线","description":"把同样的六个值按两种顺序插入，看一棵树变成链条，另一棵横向铺开。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heightBalanceCheck","title":"高度平衡检查","description":"平衡因子不是从上往下看出来的，而是从叶子一层层带上来的。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:rotateToBalance","title":"为平衡而旋转","description":"一次旋转就能把倾斜的树扶正。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:recolorThenRotate","title":"先重涂，再旋转","description":"同样的违规发生两次 — 旁边那个的颜色决定重涂就够，还是必须旋转","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:blackHeightEqual","title":"黑高处处相等","description":"从根到 nil 走四条不同的路 — 黑色的个数总落在同一个数上","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:nodeHoldsMany","title":"一个节点装多个键","description":"一个节点装着好几个键。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:splitWhenFull","title":"满了就分裂","description":"满了的节点一溢出，中间的键就升到父节点，剩下的一分为二","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heightStaysLow","title":"高度保持在低位","description":"两棵树覆盖同样的一百万片叶子 — 分叉更宽的那棵用少得多的层数就结束","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:sharePrefixPath","title":"共享前缀","description":"开头相同的词会走同一条路，直到字母分岔","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:walkPerCharacter","title":"沿着字典树，一次一个字符","description":"从不整词比较 — 每个字符选定一条分支，分支不在就到此为止。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heapProperty","title":"堆性质","description":"父节点总在子节点之前 — 但兄弟之间毫无顺序可言","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:siftUp","title":"上浮调整","description":"先放到最后一个位置，再往上爬到属于自己的位置。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:siftDown","title":"下沉调整","description":"最后一个值填上空出的顶端，再一格一格往下走到合适的位置。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:arrayAsTree","title":"用数组表示树","description":"一个数组如何充当一棵树 — 不存链接，只用下标运算。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:adjacencyListVsMatrix","title":"邻接表与邻接矩阵","description":"同样的边，落进不断变长的表，也落进早已备好的方格","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:findRoot","title":"找到根","description":"每个位置都指向上方，指向自己的那个位置就是这一组的名字。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:unionByRank","title":"按秩合并","description":"把矮的接到高的下面，高度不变；只有一样高时才会长一层。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:pathCompression","title":"路径压缩","description":"爬到根的代价，回报的不只是你问的那个节点，而是路上的每一个节点。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bloomFilter","title":"布隆过滤器","description":"用很少的位置就能确定地说\"没有\"。推动两个手柄，看一个如何移动另一个的最佳值。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:countMinSketch","title":"Count-Min Sketch","description":"用远少于键数的格子数出\"看过几次\"。宽度降低碰撞的频率，深度降低碰撞的代价。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:hyperloglog","title":"HyperLogLog","description":"不保存任何元素也能数出有多少不同的东西 — 推动桶数，看误差如何变小。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:tDigest","title":"用很少的位置回答分位数，但把尾部答准","description":"提高压缩系数 δ，尾部误差比中间下降得快得多 —— 这就是把刻度挤向尾部换来的东西。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:skipList","title":"随机代替了维持平衡的工作","description":"没有人管理形状，查找的步数却按 log n 增长。拨动手柄看看。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:severalHashesOneValue","title":"一个值，多个哈希","description":"向布隆过滤器插入值：一个值分成三条哈希分支，点亮位数组中的三个位置。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:wrongInOneDirection","title":"只会朝一个方向出错","description":"布隆过滤器可能对没放进去的东西回答\"有\"，但绝不会对放进去的东西回答\"没有\"。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:cannotUnset","title":"无法删除","description":"在布隆过滤器中删除一个值时，共用同一格的其他值也会一并消失。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:trustTheSmallest","title":"相信最小值","description":"Count-Min Sketch 从三行中读数并取最小值作为答案。共享的格子只会让计数变大，不会变小。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:leadingZerosTell","title":"前导零告诉你有多少","description":"看到罕见的前导零，说明你已经见过很多 — 不保存任何元素也能估计不同元素的个数。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:averageTheBuckets","title":"分桶测量再平均","description":"一个离群值就能把估计整个带偏。分成四个桶后，这个跳变只困在其中一个里。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:crowdTheTails","title":"把刻度挤向尾部","description":"分位摘要把更多的桶分给尾部，而不是中间。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:skipALayer","title":"在多层链表中查找","description":"在上层远跳，一旦跳过头就下降一层，逐步收窄。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:coinFlipHeight","title":"是什么决定了塔的高度","description":"一次抛硬币决定每座塔的高度，各层自然减半。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:spaceErrorTradeoff","title":"Count-Min Sketch 该开多大","description":"省下的空间要用误差偿还：表越窄，读出的值越膨胀。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:bubbleSort","title":"冒泡排序","description":"相邻比较与交换的浪，每一趟把最大值推到末尾","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:selectionSort","title":"选择排序","description":"把剩下的全扫一遍找出最小的，然后只挪动一次","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:insertionSort","title":"插入排序","description":"拿起一个值，让更大的往旁边让，再把它放进去 — 输入若已排好，它几乎不用干活。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:mergeSort","title":"归并排序","description":"一直拆到单个元素，再只看两边最前端，一路合并回去。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:quickSort","title":"快速排序","description":"选一个基准，把左右分开 — 分一次，这个基准的位置就此定下","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:heapSort","title":"堆排序","description":"把这一行变成大顶堆，然后不断把堆顶挪到末尾 — 不需要额外数组。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:countingSort","title":"计数排序","description":"从不比较两个值 — 先数，再累加，然后各就各位。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:radixSort","title":"基数排序","description":"每次只看一位数来排队 — 从不比较两个值。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:shellSort","title":"希尔排序","description":"迈大步的插入排序 — 先清掉远处的错乱，最后一趟就没剩多少活。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:linearSearch","title":"线性查找","description":"从头一个一个看 — 没有顺序可依靠时，这是说「不在这里」的唯一诚实办法。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:binarySearch","title":"二分查找","description":"看中间，扔掉一半 — 要回答「不在这里」，区间必须走到空。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:interpolationSearch","title":"插值查找","description":"不再对半切分，而是按值的大小瞄准 — 与二分查找只差一行。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:dynamicProgramming","title":"动态规划","description":"只填一次表 — 每个格子只看上一行的两个格子。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:greedy","title":"贪心","description":"总是选最早结束的那个 — 而它恰好就是最优。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:backtracking","title":"回溯法","description":"棋盘走不通就把皇后收回，试下一列 — 后退是方法，不是失败。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:branchAndBound","title":"分支限界法","description":"同一个背包，不用表 — 分出枝杈，量一量这条枝最多能到多少，砍掉赢不了的。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:compareAndSwap","title":"比较与交换","description":"比较是判断，交换只是判断为真时才随之发生的结果。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:sortStability","title":"排序的稳定性","description":"有相同的值时，正确的排序结果不止一种。只有保留输入顺序的那一种才叫稳定。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:inPlaceVsExtra","title":"原地排序","description":"两种排序到达同样的顺序，只有一种要额外的空间。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bubbleAdjacentSwap","title":"相邻交换","description":"只把相邻的两个比一遍，从左扫到右，当前最大的就一格一格被带到最右端。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:selectMinEachPass","title":"选择最小值","description":"扫描时只有标记在动，值只在一轮结束后挪动一次","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:insertIntoSortedPart","title":"插入到已排序的部分","description":"把新值从队列中提起来，后面的值依次让位，它落进空出的位置。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:splitUntilOne","title":"分割","description":"把区间一再对半分开，变的只有分组的边界。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:mergeTwoSorted","title":"归并","description":"两条有序的行合成一条 — 只看两个队首。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:partitionAroundPivot","title":"划分","description":"每个值都与同一个基准相比，然后越到一侧。基准本身留在线上。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:pivotChoiceMatters","title":"基准值的选择","description":"把同一组已排好的值切两次：取中间值可把工作量减半，取第一个值只减少一个。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:heapSortExtract","title":"堆的取出","description":"取走顶端后堆的最后一格空出来，结果就落在那一格","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:countThenPlace","title":"计数排序的放置","description":"把每个值先数一遍，位置就都提前定下了 — 从不拿两个值互相比较。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:digitByDigit","title":"逐位排序","description":"从最低位起，一次只看一位 — 整排却排好了序。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:gapShrink","title":"间隔缩小","description":"先清掉相隔较远的乱序，最后一轮相邻比较要做的事就少了。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:scanUntilFound","title":"线性查找","description":"同一道目光两次扫过同一行 — 一次中途停下，一次冲出末端。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:halveTheRange","title":"区间对半分","description":"一次比较，恰好这么多候选就没了。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:requiresSorted","title":"有序这个前提","description":"同样的七个值排成两行，跑同一个二分查找 — 一行有序，一行无序。无序那行会对明明就在那里的值答「找不到」。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:guessByValue","title":"插值猜测","description":"值分布均匀时，值本身就会告诉你该看哪里。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:divideConquerCombine","title":"分治","description":"一路向下切分，再一路向上带回答案 — 同样的地方，顺序相反","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:overlappingSubproblems","title":"重叠子问题","description":"照搬递归定义，同一项就会在不同分支上一再冒出来","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:memoWriteOnce","title":"记忆化","description":"解出的项写进表里；再遇到它就从表中读值，而不再往下分叉。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bottomUpTable","title":"自底向上填表","description":"从小的一端开始填表，递归就干脆不存在了","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:takeBestNow","title":"贪心选择","description":"一条规则，取一枚，绝不回头 — 还装得下的最大硬币落下，余额随之变小","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:greedyCanFail","title":"贪心失效的时候","description":"两行用同样的硬币凑出同样的金额。先拿最大面额的那行反而用得更多。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:tryAndUndo","title":"回溯法","description":"为什么撤回一步是流程的一半，而不是失败后的收拾。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:pruneBranch","title":"剪枝","description":"整棵子树跳过，为什么不会漏掉答案。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:boundAndCut","title":"界限剪枝","description":"一个分支即使发挥到最好也超不过当前最优，就在展开之前剪掉。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bfs","title":"广度优先搜索 (BFS)","description":"同心的波前 — 同距离的顶点在一次闪光中同时被发现","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:dfs","title":"深度优先搜索","description":"沿一条分支走到底，再退回来走下一条。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:dijkstra","title":"迪杰斯特拉算法","description":"在未确定的顶点中选最近的一个定下来，再松弛它的邻居。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:bellmanFord","title":"贝尔曼-福特","description":"把每条边扫 n-1 遍 — 每一轮距离都多渗进一层。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:floydWarshall","title":"弗洛伊德–沃舍尔","description":"所有点对的最短路径 — 每次只换一个中间顶点。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:primMst","title":"Prim 算法","description":"只养一棵树 — 每次都接上从树里伸出的最轻的边。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:kruskalMst","title":"Kruskal — 从最轻的边开始","description":"把边按权重排好，从上往下取，两端已在同一组的边就丢掉。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:topologicalSort","title":"拓扑排序","description":"先取没有箭头指进来的 — 每取走一个，下一个就松开了。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:scc","title":"强连通分量","description":"一次深度优先遍历，就能找出所有彼此可达的顶点集合。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:maxFlow","title":"最大流","description":"找一条还有余量的路，按瓶颈的量灌进去，直到再也找不到路。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:oneWayEdge","title":"有向边","description":"同一条线，一旦带上箭头，回头的路就没了。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:fewerHopsNotShorter","title":"经过的边少不等于路更短","description":"连接同一对顶点的两条路。经过边数少的那条，权重反而更大。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:queueVsStackOrder","title":"容器决定顺序","description":"同一张图，同样的邻居顺序 — 只换容器，访问顺序就分道。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:diveThenBacktrack","title":"一头扎下去，再原路退回","description":"深度优先的走法，退回来花的步数和扎进去一样多。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:markVisitedOrLoop","title":"标记已访问","description":"不给走过的地方留标记，遍历就会永远绕着同样的三个位置转","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:separateComponents","title":"互不相连的分块","description":"一次搜索走不出自己所在的分块 — 其余的要重新出发才会亮","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:twoColorConflict","title":"两种颜色在奇数环上撞车","description":"绕着五个顶点的环交替涂两种颜色，看最后一条边如何失败。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:relaxShorterPath","title":"松弛","description":"一旦出现更短的路，就擦掉写好的距离，改写成更小的数。它从不回升。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:pickNearestUnsettled","title":"先把最近的钉死","description":"还在晃动的当中，背着最小数的那个已经降无可降 — 于是它凝住，此后什么都撼不动它。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:negativeEdgeBreaks","title":"负权边破坏“确定”","description":"先确定最近的做法，遇到负权边就会留下错误的数。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:repeatRelaxAll","title":"一轮又一轮，扫过每一条边","description":"一轮为什么不够 — 每轮信息只往前推进一个顶点。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:oneMoreRoundDrops","title":"再走一轮，又降下去","description":"走完 n−1 轮后距离仍在下降，说明图里有负权环。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:throughMiddleNode","title":"经过中间会更短吗","description":"最短路径表对每一对顶点反复追问的同一个问题。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:heuristicGuides","title":"一个估计引导搜索","description":"加上对剩余距离的估计，搜索就会偏向目标。找到的路一样，打开的格子数不一样。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:growOneTree","title":"只养一棵树","description":"普里姆算法只在已经接到树上的边中挑选。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:sortEdgesAvoidCycle","title":"按权重排边，成环就丢弃","description":"从最轻的边开始取，两端已在同一组的边就丢掉。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:indegreeZeroFirst","title":"先取没有入边的","description":"只有没有入箭的顶点才能取走。取走后它挂着的箭随之落下，谁归零谁就接着落。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:cycleBlocksOrder","title":"有环就排不出顺序","description":"困在环里的顶点互相等待，最后什么也取不出来","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:mutuallyReachable","title":"能互相到达的一群","description":"只能单向到达还不算一群 — 能来能回才是一群。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:bottleneckSetsFlow","title":"最窄的管子决定流量","description":"一条路径能通过多少，由它最窄的那根管子决定。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:undoByBackEdge","title":"用反向边撤回","description":"流过多少，就能推回多少 — 卡住的流量正是靠这个松开。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:kmp","title":"KMP","description":"逐位右移会丢弃已经匹配的全部内容。KMP 只保留模式与自身重叠的那一部分。推动手柄，看差距如何拉开。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:boyerMoore","title":"Boyer-Moore","description":"从末尾开始比较，一次失配就能换来跨越多格，跨多远由那个失配的字符决定。模式越长，一次跳得越远。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:rabinKarp","title":"模式变长，触碰的字符却不变","description":"把模式加长，滚动哈希触碰的字符数纹丝不动，而单纯比较却变成三倍。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:suffixArray","title":"后缀数组","description":"把后缀排好序一次，任何模式都能用二分查找找到 —— 所有出现位置都聚在一段里。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:zAlgorithm","title":"Z 算法","description":"只要把每个位置与开头重叠多少算出一次，字符串查找就从那张表里掉出来；而制表本身从不重看同一个字符。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:ahoCorasick","title":"Aho-Corasick 算法","description":"再加模式，文本仍然只读一次。推动手柄，看一个数字纹丝不动。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:editDistance","title":"编辑距离","description":"把表填满会得到一个数字，而倒着回溯这张表会得到真正的修改清单——你把什么定得贵，清单就会跟着变。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:naiveShiftByOne","title":"把模式串逐位右移","description":"从头逐字比较；一旦不匹配，就丢弃已经匹配的部分，把模式串右移一位。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:prefixSuffixJump","title":"前缀与后缀的重叠","description":"模式把自己折叠起来，找到与自身重叠的位置，错开时只滑动重叠的那么多。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:matchFromBack","title":"从末尾开始比较","description":"从模式的最后一个字符开始比较，无需读取前面就能整体排除一个位置。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:badCharSkip","title":"不匹配的字符决定跳过多远","description":"模式中没有的字符与任何一格都不可能匹配，所以模式一次就越过那个字符。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:rollingHash","title":"滚动哈希","description":"窗口每移一格，减去前面的字母、加上后面的字母，哈希就滚到下一个值。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:allSuffixesSorted","title":"把所有后缀排好序","description":"把一个字符串的所有后缀排好序，开头相同的就会挨在一起。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:matchLengthPerSpot","title":"每个位置的匹配长度","description":"若落在已确认的区间内，就不再逐字比较，而从镜像位置借来答案。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:manyPatternsOnePass","title":"多个模式，一次扫描","description":"把四个模式叠成一棵树，只遍历一次文本就能全部捕到。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:failLink","title":"失配时退回到哪里","description":"失配时不回到开头，而是滑到重叠处。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:editTableFill","title":"填满编辑表","description":"表中每格是两个前缀之间的编辑距离，由已经填好的三个相邻格算出。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:threeEditChoices","title":"决定一个格子的三条路","description":"编辑距离表中的一个格子取三个提议中最便宜的那个——上方的删除、左方的插入、对角线的替换或保持。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:euclidean","title":"欧几里得算法","description":"把大数换成余数不断缩小，就会到达最大公约数。推动手柄，看看最费步数的那些数对。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:fastPower","title":"快速幂","description":"不逐个相乘，而是不断平方去到达幂。拨动指数，简单的一边爆炸式增长，快的一边几乎不动。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:sieve","title":"埃拉托斯特尼筛法","description":"划掉倍数，剩下的就是素数 — 推动上限，看划掉者纹丝不动。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:primality","title":"素数判定","description":"只除到平方根就能定下答案 — 而这能省下多少，只有在素数上才看得出来。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:matrixMul","title":"矩阵乘法 — 每层少做一次乘法","description":"一层用一次乘法换来几次加法。差距恰好是一 —— 而递归让这个一爆炸式增长。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:squareAndHalve","title":"快速幂 — 把一行对折","description":"把 3 乘十三次要十二次乘法。换个办法：把十三格的一行对折，成对的两格相遇成为平方，每次对折剩下的那一格送进答案。六次乘法就能到达同一个数，而送进答案的格子恰好是 13 的二进制 1101 中为 1 的位。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:divisorPairsSqrt","title":"约数成对","description":"约数总是成对出现，每一对中较小的那个都不超过平方根。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:rowTimesColumn","title":"行乘列","description":"乘积的一格从何而来 — A 的一行与 B 的一列在同一处咬合。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:bigO","title":"Big-O 表示法","description":"n 变大时，四个项互换位次：起初居首的常数落到最后，最终留下来的名字只有 n³。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:asymptotic","title":"渐近分析","description":"同一增长等级的两个函数，比值始终固定不变；等级不同，比值就会无止境地拉开。拨动输入规模，看看哪个比值一直停在 2。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:pNp","title":"P 与 NP","description":"验证一个答案和找出一个答案不是同一件事 — 推动规模，看两种代价如何分开。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:growthOutpaces","title":"最大的项吞掉其余","description":"把 n² + 10n + 100 拆成一根条的三份:n 变大时,n² 吞掉其余两项。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:constantFades","title":"为什么略去常数","description":"常数只会推迟两种增长率相遇的位置，并不会改变最终谁胜出。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:curvesCross","title":"曲线交叉之处","description":"只要输入还小，较慢的算法确实更快 — 直到某个大小让领先者互换。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:verifyVsFind","title":"验证与搜索","description":"要找出和为目标的子集必须看遍所有候选，而检验别人给出的一个候选只需看一次。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:reduceToKnown","title":"化归为已知的问题","description":"考试排期搬进图着色 — 科目变成顶点，冲突变成边，节次变成颜色。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:conditionalStatement","title":"if / else if / else","description":"流走到岔路口，自上而下逐个判断条件，在第一个为真处只点亮一条分支，然后重新汇成一条线","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:loopVsRecursion","title":"循环与递归","description":"同一个平方和算两次。循环停在一个栈帧里、跳回条件处；递归每调用一次就叠一层栈帧，再从顶上逐层拆掉，把值往下一层传。","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:branchTakeOnePath","title":"岔路口只走一边","description":"if-else 会走过两个分支吗?","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:multiwayBranch","title":"多路分支 — 从上往下逐个询问","description":"条件有多个时，流程走哪条分支？","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:loopBack","title":"循环再次走过同样的行","description":"在循环体末尾，执行流回到条件行，再次走过同样的行；只有条件为假时才向下离开。","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:loopTermination","title":"条件永不改变的循环","description":"如果循环体从不写入条件读取的变量，条件每次都给出同样的答案，循环永不结束。","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:recursionSelfCall","title":"递归调用：函数再次调用自己","description":"函数调用自己的名字时，流程带着新的 n 回到同一函数体的第一行，先前进入的函数体停在调用行上等待。","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:callStackUnwind","title":"调用栈的回退顺序","description":"递归调用按什么顺序结束,返回的值又去了哪里?","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:baseCase","title":"基线条件","description":"递归要碰到底才会开始返回——被跳过的底什么也拦不住。","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:exceptionPropagate","title":"异常沿着调用处向上传播","description":"在函数深处抛出的错误离开自己的栈帧，跳过所有没有 try 的栈帧，停在第一个位于 try 内的调用处。","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:valueInPlace","title":"值就在位置里","description":"把一个数放进另一个名字时，过去的是这个数的副本——原来的数留在原处。","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:referenceHoldsAddress","title":"引用保存的是地址","description":"列表放在槽位之外；scores 的槽位里只有一个地址，每次赋值时被换掉。","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:aliasing","title":"别名","description":"两个名字，一个列表 — 通过 prices 做的修改，从 backup 读了出来。","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:narrowingLoss","title":"转成更窄的类型，高位会掉下去","description":"把 32 位整数转成 8 位整数，值还能保持不变吗？","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:shadowing","title":"遮蔽 — 内层的名字挡住外层的名字","description":"在代码块里用 let 声明与外层同名的变量,外层的变量会怎样?","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:scopeExit","title":"在代码块里声明的名字随代码块一起消失","description":"流程离开 if 的代码块时，块内声明的名字连同它的位置一起被清走。后面的行再叫这个名字就找不到，程序在那里停下。","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:danglingReference","title":"悬空引用","description":"被指向的变量先消失了,持有那个地址的变量现在指向什么?","domain":"programming-fundamentals","subdomain":"variables-types"},
    {"id":"facet:copyVsShare","title":"复制与共享","description":"把同一个 +1 调用 k 次。传数字时只有副本过去，随栈帧一起消失；传列表时只有地址过去，调用方指向的格子会变大。","domain":"programming-fundamentals","subdomain":"functions"},
    {"id":"facet:passByValueVsReference","title":"按值传递与按引用传递","description":"同样的函数体，不同的参数 —— 传过去的是值的副本，还是变量的位置本身。","domain":"programming-fundamentals","subdomain":"functions"},
    {"id":"facet:returnToCaller","title":"回到调用处","description":"返回的值会落进它的调用式原本写着的那个位置。","domain":"programming-fundamentals","subdomain":"functions"},
    {"id":"facet:closureCaptures","title":"闭包带着外部变量走","description":"创建函数的栈帧已经消失，它用到的外部变量却附着在函数上继续存在 — 每次调用都到达同一个槽位。","domain":"programming-fundamentals","subdomain":"functions"},
    {"id":"facet:functionAsValue","title":"像值一样传递的函数","description":"一个函数被存进变量,又作为参数传出去。换个名字调用,运行的还是同一个函数体。","domain":"programming-fundamentals","subdomain":"functions"},
    {"id":"facet:curryingPartial","title":"柯里化——一次一个参数","description":"给接收三个参数的函数只传一个，得到的是一个还有两个空位的函数。","domain":"programming-fundamentals","subdomain":"functions"},
    {"id":"facet:polymorphism","title":"方法查找 — 从接收者的类向上","description":"同一行调用 s.m() 从接收对象的类出发，向上查找，直到第一个拥有该名字的类。只换接收对象，执行的方法体、向上的层数或错误都会改变。","domain":"programming-fundamentals","subdomain":"oop"},
    {"id":"facet:instantiateFromClass","title":"从类创建对象","description":"用一个类创建多个对象，这些对象会共享值吗","domain":"programming-fundamentals","subdomain":"oop"},
    {"id":"facet:methodLookupUp","title":"方法查找向上攀升","description":"对象调用自己类中没有的方法时，调用的是什么？","domain":"programming-fundamentals","subdomain":"oop"},
    {"id":"facet:dynamicDispatch","title":"动态分派","description":"调用行只有一行，到达的方法体却有三个 — 那一刻接收到的对象的类决定调用去哪里。","domain":"programming-fundamentals","subdomain":"oop"},
    {"id":"facet:interfaceSlot","title":"接口 — 方法体插入的空槽","description":"接口只规定名字和参数。运行的方法体来自插入的实现，不改调用方就能替换。","domain":"programming-fundamentals","subdomain":"oop"},
    {"id":"facet:encapsulationBoundary","title":"封装的边界","description":"类外的代码可以穿过门触及 public 方法,却在 private 字段前的墙边停下。","domain":"programming-fundamentals","subdomain":"oop"},
    {"id":"facet:pureFunction","title":"纯函数与调用顺序","description":"把同样的三次调用换着顺序来调用。修改收到的列表，每次的答案取决于顺序；写入新的副本，无论什么顺序答案都一样。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:mapFilterReduce","title":"map / filter / reduce","description":"三个阶段各自只改变一件事：filter 改变个数，map 改变值，reduce 把列表折叠成一个数。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:pureSameOutput","title":"同样的输入，同样的输出？","description":"同一个参数 3 分别传给两个函数各三次。double 的输出叠在同一个位置；读取外部值的 scale，输出却在摇摆。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:noSideEffect","title":"无副作用","description":"两个函数返回相同的值。只有其中一个每次被调用时都会改变外部。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:immutableCopy","title":"修改它，还是新建一个","description":"覆盖一个位置，旧值就消失了。带着修改复制一份，旧列表就原样留在新列表旁边。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:mapOneByOne","title":"map 逐个改变元素","description":"每个元素都经过同一个函数，变化后的值落在新列表的同一位置。数量不变。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:filterKeepSome","title":"filter 只留下一部分","description":"元素逐个站到条件前。通过的元素原样进入新列表，其余的掉落。个数变少，值不变。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:reduceFold","title":"reduce — 把列表折叠成一个值","description":"一个累积值从前往后逐个吸收元素而增长，最后留下的不是列表，而是一个值。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:monadChainInBox","title":"装在盒子里沿链传递","description":"把可能为空的盒子用 then 依次传给多个函数。有值的盒子被打开,值传下去;盒子一旦变空,后面的函数都不再被调用。","domain":"programming-fundamentals","subdomain":"fp"},
    {"id":"facet:tracingVsRefcount","title":"追踪回收与引用计数","description":"放开根，在同一张指针图上运行两种回收器：追踪看从根是否仍可达，计数看还剩几个指向。打开环，比较各自留下了什么。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:allocateAndFree","title":"分配与释放","description":"函数返回时栈帧随之消失，但从堆上借来的块会一直留到归还为止。归还的时机和次数决定了泄漏、不泄漏、写入已归还的块，以及同一块被发放两次。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:stackVsHeap","title":"栈与堆 — 调用结束后留下什么","description":"函数返回时，它的帧被整个撤下，而借来的堆单元留在原处，只靠返回的地址相连。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:pointerDereference","title":"沿着指针走 — 一次，再两次","description":"valueAt 把格子里的数当作地址读出，跳到那个格子。套两层，就要跳两次才到达值。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:gcReachableFromRoot","title":"能否从根到达","description":"标记从根沿着指针扩散，随后扫过堆的手回收所有未标记的对象——即使仍有东西指向它。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:refcountZero","title":"计数归零就回收","description":"每有一个名字指向对象，计数加一；放手则减一。把计数变为零的那一行之后，对象立刻被回收。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:referenceCycle","title":"循环引用","description":"互相指向的两个对象，即使所有名字都放开，彼此给的 1 仍然留着，计数到不了 0。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:manualFree","title":"手动释放","description":"用 free 归还的内存会怎样?","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:doubleFree","title":"重复释放","description":"把同一个格子释放两次，它就在空闲列表里出现两次——分配器把这一个格子交给了两个名字。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:memoryLeak","title":"内存泄漏","description":"每一轮都借一块新内存，并覆盖上一块唯一的地址。丢失地址的块不断堆积，最后的 free 只归还一块。","domain":"programming-fundamentals","subdomain":"memory-model"},
    {"id":"facet:twosComplement","title":"二进制补码 — 同一位串，两个数","description":"同一串位可以读成两个不同的数。读成哪个由约定决定，而位宽也是约定的一部分。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:floatingPoint","title":"浮点数 — 给指数还是给尾数","description":"八位中除去符号位，其余七位由指数与尾数瓜分：给指数用来够得更远的每一位，都是从精细度里拿走的。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitwiseOps","title":"位运算 — 八个位各自独立","description":"同样的两个字节，六种规则。每一位独自应用一行规则，只有移位让位之间发生关系。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:integerOverflow","title":"溢出 — 增长的数列超出容器的地方","description":"在哪里溢出由容器大小决定。溢出的那一刻，值不是错得很多，而是变得毫无意义。而且没有人会提醒你。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:positionalValue","title":"位值与进制","description":"同一个数，用另一种进制来写。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:negateAndAddOne","title":"取反加一得负数","description":"翻转每一位再加一就得到负数，进位说明了原因。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:signedWraparound","title":"数的两端","description":"在 8 位有符号运算里，最大的数之后就是最小的数 — 它是环，不是直线","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:silentTruncation","title":"被悄悄截断的高位","description":"超出容器的值会丢掉高位，而且没有任何提示。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:mantissaAndExponent","title":"尾数与指数","description":"32 个比特分成三段，三段共同组装出一个数。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:unrepresentableFraction","title":"永不终止的小数","description":"0.1 在二进制中无法整除。乘以 2 逐位取出后，四位的图样会无休止地重复。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:unevenFloatGaps","title":"不均匀的刻度","description":"越往右，相邻两个数之间的距离就翻一倍。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitMask","title":"位掩码","description":"掩码是一块打了孔的盖子——只有孔下面的位能透过来，其余的都被 0 盖住。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitShift","title":"位移","description":"把比特移动一格，数值就翻倍或减半。越过边界的比特会消失。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:byteOrder","title":"字节序","description":"同一个值以相反的顺序放入内存，以及用错误的顺序读取时会变成什么。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:cacheLine","title":"缓存行 — 移动的是整行，不是一个字节","description":"加宽缓存行，顺序读取每一档都在变好，而跳跃读取在行宽到能被落入两次之前纹丝不动。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:directMappedCache","title":"直接映射缓存 — 只有一个位置，然后是悬崖","description":"地址决定行放在哪里，所以只有一个地方要找。放得进缓存时几乎全部命中；只要多出一行，未命中就像跌落悬崖。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:setAssociativeCache","title":"组相联缓存 — 同样八个格子，不同分组","description":"格子始终是八个。把分组放宽，原本互相挤走的地址就并排坐下，但只到某一点为止。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:cacheReplacement","title":"缓存替换策略 — 同样十一次访问，答案却不同","description":"四个槽位，十一次访问。只改替换规则，缺失次数就分成三种。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:writePolicy","title":"写策略 — 修改何时写回下层","description":"十次修改，两种策略：下层看到的写入是十次还是五次。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:lineFill","title":"只要一格，整行一起上来","description":"缓存以固定大小的行为单位搬运。碰到一个元素，同一行的另外三个邻居也会跟着上来。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:temporalLocality","title":"时间局部性","description":"刚读过的马上又读 — 所以它留在上层。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:spatialLocality","title":"空间局部性","description":"一行上来之后，接下来的三个不再花代价。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:indexAndTag","title":"索引与标记","description":"把地址切成三段：索引挑选行，标记留在行里证明它属于谁，偏移指出行内的第几个字节。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:conflictMiss","title":"冲突失效","description":"明明有空位，却被挤出去","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:associativityRelief","title":"组相联 — 一个位置能放多个就少被挤出","description":"同样的四个块，换一种分组。每个位置放一个就互相挤出，放两个就并排坐下。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:latencyLadder","title":"延迟阶梯","description":"每往下一层，代价就贵上几十倍。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:writeBackVsThrough","title":"立刻写下去，还是先攒着","description":"同样的七次写入，write-through 要写七次内存，write-back 只写四次。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:falseSharing","title":"伪共享","description":"两个核心改的是不同的值，但同一条缓存行同时装着它们，于是每次写入都会作废对方的副本。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:fiveStagePipeline","title":"五级流水线","description":"把每条指令分成五级，前一条尚未离开时就让下一条进入。单条指令仍需 5 个周期，多条指令则更早完成。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:dataHazard","title":"数据冒险","description":"后面的指令读取前面指令尚未写回的值。不等待很快但读到旧值；等待正确但损失周期；转发找回大部分；最后一个气泡只能靠重排指令填补。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:controlHazard","title":"控制冒险","description":"猜测“不跳转”并继续取指，每次分支跳转都要丢弃判定前取入的指令。判定越晚，丢弃的尾巴越长。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:outOfOrderExecution","title":"乱序执行","description":"窗口变宽后，后面的指令会超前开始，填满等待加载的空周期——但提交仍按程序顺序。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:stageOverlap","title":"阶段重叠","description":"前一条指令还没完成，下一条就已进入：每个周期所有指令前进一级，空出的 IF 接纳下一条指令。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:throughputNotLatency","title":"变快的是吞吐量","description":"两台机器并排执行同样的五条指令。每条指令在里面都要待五个周期，只有最后一条出来的时刻不同。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:readBeforeWrite","title":"尚未产生的值","description":"后面的指令为什么必须等待前面的指令?","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:operandForwarding","title":"数据前递","description":"I1 在 EX 得出的结果，在写回寄存器堆之前就直接送到 I2 的 EX。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:pipelineBubble","title":"流水线气泡","description":"加载指令紧接着的指令要用它的值时，转发也来不及。流水线停顿一个周期，空出的槽像指令一样流过 EX、MEM、WB，后面的指令都晚一个周期完成。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:branchFlush","title":"丢弃猜错放入的指令","description":"猜错分支方向时，流水线会清空事先填入的指令。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:dualIssue","title":"一拍发两条","description":"每拍可发射两条指令的顺序执行机器，只有当第二条不读第一条的结果时，才把两条一起发出。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:readyFirst","title":"就绪者先行","description":"乱序执行先运行已就绪的指令，但仍按程序顺序提交结果。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:staticPrediction","title":"静态分支预测","description":"只凭方向猜测分支时，观察损失的周期移向何处：总是不跳转会猜错所有循环回跳，总是跳转会猜错罕见检查的前跳，而“向后就跳转”两者都能猜对。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:saturatingCounter","title":"饱和计数器","description":"只错一次就改变主意的分支预测器，每次退出循环都会错两次。它应该坚持多久？调整计数器位数，观察指针如何越过阈值。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:branchHistoryTable","title":"分支历史表","description":"用分支最近几次的结果来选择 2 位计数器：重复的模式在历史足够长时不再猜错，随机分支始终超不过一半。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:mispredictionPenalty","title":"猜错一次的代价","description":"每次猜错分支，都要丢掉它后面取来的周期。流水线越晚得知结果，每次堆得越高。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:backwardTaken","title":"向后跳就是循环","description":"在结果出来之前只看方向来猜分支的静态规则——向后跳就跳转，向前跳就不跳转。循环每重复一次都向后跳，所以这条规则几乎总是猜对。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:oneBitDoubleFault","title":"一位预测器的两次失误","description":"只记得上一次结果的预测器在循环退出时猜错，记忆随之翻转，下一次进入循环时又猜错。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:fourStateHysteresis","title":"四格之间一步一挪","description":"2 位计数器不会因为错一次就改变预测。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:patternFromHistory","title":"最近几次指向下一次","description":"最近两次结果指向表中的一格，预测就取自那一格。格子填满后，交替的规律就记在表里，不再猜错。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:unpredictableBranch","title":"无法预测的分支","description":"分支结果若像抛硬币，任何预测器的命中率都会落在一半附近。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:structAlignment","title":"结构体对齐","description":"同样的五个字段可以占 16 字节，也可以占 32 字节：对齐越严格，字段被推得越开、空隙越大；按从大到小排列，空隙全部消失。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:arrayTraversalOrder","title":"数组遍历顺序","description":"同样的和，换一种顺序缓存未命中就多出四倍——但只在行数超过缓存时。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:prefetching","title":"预取","description":"提前调入要用的行，等待就消失了；调得太早，它会在使用前就被挤出缓存。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:simd","title":"SIMD","description":"一次加法同时推进多个通道——但除不尽剩下的尾部仍要一个一个地加。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:paddingGap","title":"对齐与填充","description":"每个字段都会滑到自身对齐值的倍数位置，跳过的字节留作空隙。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:fieldOrderSize","title":"顺序改变大小","description":"同样的四个字段按从大到小重新排列，空隙被填上，结构体变小。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:rowVsColumnWalk","title":"行优先与列优先遍历","description":"同一个数组按行求和、按列求和：和相同，缓存未命中却不同。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:strideAndMiss","title":"跳跃的步长","description":"缓存行总是整行调入，但只有读到的元素被使用。步长越长，调入的行越多，丢弃的部分也越多。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:fetchAhead","title":"提前取数","description":"按顺序读取元素时，一开始读当前行就请求下一行，光标到达之前那一行已经到了。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:lanesInStep","title":"并排的通道","description":"一条 SIMD 指令一次推进 a + b 的四个通道，同一拍里标量一侧只加一个元素。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:processState","title":"进程状态与多道程序设计","description":"一个进程只短暂使用 CPU，却要长时间等待输入输出。增加进程，CPU 条上的空闲拍会被其他进程填满；没有空隙之后，多出来的进程只能挤进就绪队列。","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:contextSwitching","title":"上下文切换 — 一个舞台, 两位主人","description":"唯一的 CPU 舞台上主人交替 — 一个流的寄存器束被抬进自己的保管处，另一个的被放回同样的位置，时间各自从停下的地方重新开始","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:stateTransitions","title":"进程状态转换","description":"每来一个原因，进程就沿着转换表移动一步。从运行出发，原因决定去向；离开等待时总是回到就绪。","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:blockedWaitsEvent","title":"唤醒睡眠进程的是什么","description":"是 CPU 空闲，还是它等待的事件？每个事件都有自己的等待队列，到达的事件只从自己的队列中取出一个进程。","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:saveAndRestore","title":"上下文的保存与恢复","description":"两个程序轮流使用一个 CPU。每次切换时，pc 和 r 中的数被写入记录，另一份记录中的数被取回到同样的格子里。","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:switchCosts","title":"切换进程的真实代价","description":"切换本身只花固定的几个时钟刻。之后换入的进程发现缓存里全是对方的数据，每次读取都挤出一个，再慢慢装入自己的。","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:pcbHoldsState","title":"PCB — 得到的东西都写在它的表里","description":"进程得到的内存槽和打开的文件都写在它自己的表里；结束时内核只沿着这一张表全部收回，然后删除这张表。","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:schedulingPolicy","title":"CPU 调度策略","description":"把同一批任务按 FCFS、SJF、SRTF、MLFQ 重新排列。等待不会消失，只是从一个进程转移到另一个进程。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:roundRobinQuantum","title":"轮转调度 — 时间片的大小","description":"时间片越小，每个进程越早轮到一次，但切换也越频繁；若每次切换要花一个节拍，每次切换都把结束时刻往右推。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:priorityAging","title":"优先级与老化","description":"按等待时间提升优先级，低优先级的进程就不会饿死——代价是高优先级的进程要多等。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:weightedFairShare","title":"按权重公平分配 (CFS)","description":"每个时钟滴答都运行虚拟时间最小的进程，CPU 就按权重分配。迟到者从哪里起步，决定了这种分配能否保持。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:readyQueuePick","title":"就绪队列","description":"CPU 忙碌时，到达的进程排到队尾；只有在 CPU 空出来的那一刻，队首才离开队列登上 CPU。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:turnaroundVsWait","title":"周转时间与等待时间","description":"从到达到完成的长度，分成在队列中等待的部分和在 CPU 上运行的部分。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:firstComeFirstRun","title":"先到先运行","description":"在 FCFS 中，每个进程在其到达时刻与前一个进程结束时刻中较晚的那个时刻开始。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:convoyEffect","title":"护航效应","description":"在先来先服务下，一个长作业占着 CPU 时，排在后面的每个短作业都在等待——它们的等待时间每过一个时钟一起增长。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:shortestFirst","title":"短作业优先","description":"把最短的作业一个位置一个位置地拉到前面，看等待总和如何变小。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:starvationOfLong","title":"长作业的饥饿","description":"在 SJF 下，只要短作业不断到来，长作业每次挑选都会被跳过。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:timeSliceRotate","title":"轮转调度 — 用完时间片就回到队尾","description":"用完时间片仍未结束的进程离开 CPU，回到就绪队列末尾，一直轮转到剩余量为 0。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:quantumSizeTradeoff","title":"时间片越小，切换越频繁","description":"把同样的作业用两种时间片的轮转调度逐个时钟周期并排运行：小时间片切换多得多，但每个作业都更早轮到第一次。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:priorityPreempt","title":"优先级抢占","description":"更高优先级到达时,会把正在运行的进程挤下 CPU;被挤下的进程之后只运行剩下的部分。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:aging","title":"老化","description":"在队列中等得越久，优先级升得越高——低优先级的任务终会被选中。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:demoteOnOveruse","title":"用完时间片就降一级","description":"用完整个时间片的进程会降到下一级队列，越往下时间片越长；在时间片内完成的进程不会离开自己的队列。","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:virtualRuntime","title":"虚拟运行时间","description":"每个时钟节拍，虚拟时间最落后的进程运行并追上来","domain":"operating-systems","subdomain":"scheduling"},
    {"id":"facet:mutex","title":"互斥锁：切换点决定结果，锁消除运气","description":"两个线程各把 count 加 1 两次，结果应为 4。转动时间片，各行重新交错：写入是否丢失取决于切换落在哪里，时间片越大并不一定越好。打开锁后，每次递增聚成五行一块。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:deadlock","title":"死锁","description":"三个线程各取两把锁，围成一个环。改变时间片和两次加锁间的工作，等待箭头会闭合成环或解开；按编号顺序加锁，图上任何一格都不会死锁。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:producerConsumer","title":"生产者-消费者","description":"两个信号量守护有界缓冲区。增加槽位能让快的生产者提早结束，但慢的消费者取完的时刻不变。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:interleaving","title":"交错执行","description":"两个线程的语句一行一行地插入同一条执行序列。插入的位置每次都不同，但每个线程内部的顺序不变。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:nonAtomicIncrement","title":"非原子的自增","description":"count = count + 1 这一行在 CPU 上要分几步执行?","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:lostUpdate","title":"丢失更新","description":"两个线程各自给共享值加了数，其中一方加的部分却被另一方的写入覆盖而消失。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:criticalSection","title":"临界区","description":"一次只能放一个线程进入的行，从第一个触及共享值的行一直到最后一个。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:lockExcludes","title":"一把锁，每次只有一个持有者","description":"拿到锁就把其他线程挡在外面；释放时把持有者的位置交给队首。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:countingPermits","title":"数着许可证放行的信号量","description":"每个进入的线程拿走一张许可证。数到 0 时,下一个线程在队列里睡眠,直到有许可证交到它手上。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:waitAndSignal","title":"等待与通知","description":"条件尚未成立时，线程放下锁并睡眠；直到重新拿回锁，才再次检查条件。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:holdAndWait","title":"占有并等待","description":"一个线程在等待一把锁的同时攥着另一把锁，就把那把锁拴住了，来要它的线程也只能睡下。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:noPreemption","title":"不可抢占","description":"高优先级线程能抢走 CPU，却抢不走别人持有的锁。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:waitCycle","title":"循环等待","description":"三个线程互相等待时，为什么谁都无法前进？","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:lockOrdering","title":"加锁顺序","description":"所有线程都先锁编号小的锁时，等待只会向上延伸，永远不会闭合成环。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:boundedBuffer","title":"有界缓冲区","description":"槽位全满时下一个物品放不进去；全空时取出方空手而回。","domain":"operating-systems","subdomain":"synchronization"},
    {"id":"facet:paging","title":"分页与 TLB","description":"每个地址都拆成页号和偏移，页号必须翻译成帧号。TLB 里存着的几条翻译能省去去页表的一趟 — 调整槽数，看哪些访问从页表一侧移到 TLB 一侧。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:segmentation","title":"分段与空洞","description":"每个块按自己的长度放进空洞。空闲总量足够时,也可能没有任何一个空洞放得下——选洞规则只会改变这件事发生的位置。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:virtualMemory","title":"虚拟内存与抖动","description":"多加一个进程，CPU 会更忙吗——工作集的总和超过 12 个帧时呢？","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:pageReplacement","title":"页面置换","description":"换一种置换策略，连增加一个页框时缺页的变化方向都会改变。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:pageTableLookup","title":"页表查找","description":"地址一分为二，只有前半部分经过页表被替换。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:fixedSizeFrames","title":"切成等长的页装入帧","description":"分页把进程切成等长的页，即使空闲帧彼此分散，也逐一放入。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:tlbCachesTranslation","title":"TLB 把地址转换留在手边","description":"在页表中查到的转换被写入 TLB。同一页的下一个地址直接在那里转换，不必再查页表。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:variableSizeSegments","title":"段按含义切分","description":"分段在含义改变之处切分程序——代码、数据、堆、栈——因此每段长度不同，各自移入第一个放得下的空隙。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:externalFragmentation","title":"外部碎片","description":"空闲内存加起来很充足，却分散成许多空隙，没有一个足够大。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:pageFault","title":"缺页","description":"访问一个不在内存中的页时会发生什么？","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:swapInOut","title":"交换 — 换出到磁盘，再换入到另一个位置","description":"内存已满，又来了一个新进程。正在等待的进程被整个换出到磁盘，新进程占用它的位置；等有位置空出来，被换出的进程再换入回来——进入另一个位置。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:thrashing","title":"抖动","description":"帧不够时，刚被换出的页面在下一次引用时又被需要——每次引用都成了缺页。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:evictLeastRecent","title":"LRU 换出谁","description":"没有空帧时，LRU 回溯每个页面最后一次被使用的时刻，换出最久未用的那个。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:recencyReorder","title":"最近使用重排","description":"每次使用都把该页拉到最前面，于是队尾总是下一个被换出的页。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:evictOldest","title":"FIFO 淘汰最早进入的页","description":"FIFO 只看进入顺序，不看是否被使用。上一步刚用过的页也会先被挤出，随即又被调回。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:beladyAnomaly","title":"贝莱迪异常","description":"把相同的访问序列交给 3 个帧和 4 个帧的 FIFO。帧更多的一方最后缺页更多。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:secondChance","title":"第二次机会","description":"指针绕着槽位转动：亮着的标记被清除后跳过，未亮的槽位中的页面被换出。","domain":"operating-systems","subdomain":"memory-management"},
    {"id":"facet:fileBlockPlacement","title":"文件块的布局","description":"用两种方式找到同一文件的第 k 块：FAT 链每多一块就多读一次，inode 索引只在 k 越过边界时才多一级。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:journaling","title":"日志记录","description":"三个块一起改变。移动崩溃的时刻：没有日志时磁盘在中途错乱；有日志时要么是旧的，要么是新的。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:inodePointsBlocks","title":"inode 掌握顺序","description":"按顺序沿着 inode 的槽位走，散落在磁盘各处的块就汇成一个文件。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:indirectBlock","title":"间接块","description":"文件超出 inode 的直接槽位后，后续的块号会溢出，落到一个专门存放块号的磁盘块里。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:chainOfBlocks","title":"FAT 链","description":"下一个块号不在块里，而在一张每块各占一格的表中。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:writeIntentFirst","title":"先写下要做的事","description":"日志文件系统先把要改的块写进日志，用结束标记封好，然后才把它们写回原位。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:replayAfterCrash","title":"崩溃后重放日志","description":"恢复供电后，日志中写到结束标记的事务会被重新写回原位，其余的被丢弃。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:pathResolution","title":"路径解析","description":"文件系统沿着路径名一层一层往下走目录，直到到达文件的 inode。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:hardVsSoftLink","title":"硬链接与符号链接","description":"删除原来的名字后，硬链接仍按 inode 号到达文件，符号链接则重新查找写在里面的名字，却扑了个空。","domain":"operating-systems","subdomain":"file-system"},
    {"id":"facet:ioTransferModes","title":"输入输出方式","description":"轮询、中断和 DMA 接收同样的字。哪种方式让 CPU 损失的时钟最少，取决于字的数量和设备的快慢。","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:diskScheduling","title":"磁盘调度","description":"五种策略处理同样的八个请求。观察磁臂移动的柱面总数，以及磁臂从别处出发时最短的策略如何改变。","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:transferWithoutCpu","title":"DMA — 不经过 CPU 的传输","description":"设备的数据被搬进内存的时候,CPU 在做什么?","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:interruptPreempts","title":"中断——跳出去，再回来","description":"设备在一条指令执行中途发出请求。CPU 先把这条指令执行完，记下返回的位置，运行处理程序，然后回到紧接着的下一条指令。","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:pollingVsInterrupt","title":"轮询与中断","description":"两个 CPU 等待同一个设备。一个不停地询问是否就绪，另一个在设备呼叫之前做自己的工作。","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:seekDistanceCosts","title":"磁臂移动多远，就要多久","description":"读取同样大小的一个块，每个请求的耗时却不同。磁臂移到请求所在柱面的距离越长，寻道时间就越长；旋转与传输的部分则对每个请求都一样。","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:elevatorSweep","title":"电梯式扫描","description":"磁盘请求按到达顺序排队，但磁臂按自己路径上的顺序处理：先处理前进方向上最近的请求，只有那一侧没有剩余请求时才掉头。新请求若在磁臂前方就加入本次扫描，在后方则等到掉头回来。","domain":"operating-systems","subdomain":"io"},
    {"id":"facet:physicalLayer","title":"线路编码与成帧","description":"接收方必须在线路上找到两种边界——比特从哪里开始，帧从哪里开始。线路编码守住前者，字节填充守住后者，两者都有代价。","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:networkLayer","title":"封装与逐跳传递","description":"把消息切分后每一片都要加报头，但多条链路可以同时工作——最快到达的切分数由链路数决定。","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:layerWrapsPayload","title":"每一层都包裹载荷","description":"在发送端，应用数据在上线路之前被加上了什么，又变大了多少？","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:peerLayerTalk","title":"对等层之间的对话","description":"接收方的每一层只打开发送方同一层写下的头部；其下各层原封不动地搬运了它。","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:bitsAsSignal","title":"变成信号的比特","description":"曼彻斯特编码把每个比特变成两个半位的电压，线路总在比特中间翻转。","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:frameBoundary","title":"帧定界 — 字节填充","description":"如果数据中有与结束标志相同的字节,接收方如何认出帧的结尾?","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:hopByHop","title":"逐跳转发","description":"每个时刻，每个节点把一个已完整收到的数据包交给紧邻的下一个节点。三个数据包穿过两台路由器时，各条链路相继同时忙碌起来。","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:portDemultiplex","title":"端口多路分解","description":"到达同一地址的报文段按目的端口分流，进入正在监听的应用。","domain":"networks","subdomain":"osi-tcp"},
    {"id":"facet:ethernet","title":"CSMA/CD 退避","description":"共享一根线的站点发生冲突后退避。退避范围固定时，同样的站点反复冲突直到丢弃帧；每次冲突后范围加倍，所有帧都能发出。","domain":"networks","subdomain":"data-link"},
    {"id":"facet:arp","title":"ARP 与 MAC 地址","description":"帧离不开自己的链路。发往另一个网络时，发送者询问第一台路由器的 MAC，每条链路都要重新询问。比较有无缓存时的广播次数。","domain":"networks","subdomain":"data-link"},
    {"id":"facet:collisionAndBackoff","title":"相撞后退让，再试一次","description":"共用一条线路的两个站同时发送而相撞后，下一次如何避免再次相撞？","domain":"networks","subdomain":"data-link"},
    {"id":"facet:macIsLocal","title":"MAC 地址只在自己的链路内有效","description":"发往另一个网络时, IP 对原样穿过每条链路, 而 MAC 对在每条链路上重新换过。","domain":"networks","subdomain":"data-link"},
    {"id":"facet:askWhoHas","title":"ARP 请求","description":"向所有人询问这个 IP 属于谁——询问同时传到每一台，只有主人回答。","domain":"networks","subdomain":"data-link"},
    {"id":"facet:arpCache","title":"ARP 缓存","description":"知道一次，就记下来","domain":"networks","subdomain":"data-link"},
    {"id":"facet:ipRouting","title":"IP 路由","description":"数据包在路由器之间逐跳前进 — 每台只看自己的表，挑出最长前缀匹配的下一跳，每跳 TTL 减一","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:rip","title":"路由协议","description":"在同一个五路由器环、同一处断开上比较距离矢量、水平分割、路径矢量和链路状态 —— 各自持有错误路由表多少轮，发出多少条通告。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:nat","title":"NAT","description":"多台设备共用一个公网地址。只改写地址还是连端口一起改写，决定了谁能收到回复，以及陌生方能否进来。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:longestPrefixMatch","title":"最长前缀匹配","description":"把目的地址逐行与表比对，在前缀完全吻合的行中选出最长的一行。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:forwardingTable","title":"转发表","description":"从一个接口进入的数据包从不同的接口离开。路由器在表中查找目的网络，把数据包交给那里写的下一跳。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:hopCountMetric","title":"跳数","description":"每台路由器把邻居通告的数加一记下——两个数同时到达时，较小的留下。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:countToInfinity","title":"无穷计数","description":"链路断开后，两台路由器在彼此的数上一级一级往上加，直到 16 才停下。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:linkStateFlood","title":"链路状态泛洪","description":"一台路由器写下的邻居通告，以一字不改的副本从邻居传到邻居。副本到达已持有它的路由器时就地丢弃，因此即使网络有环，泛洪也会停止。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:shortestPathTree","title":"最短路径树","description":"每台路由器都持有同一张地图，却各自以自己为根，立起一棵代价最小的树。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:pathVectorPolicy","title":"路径向量 — 按策略选择","description":"四个邻居发来的路径到达，含有自己编号的路径被丢弃，其余按关系设定的优先级排队。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:rewriteAddressPort","title":"出去时被换掉的地址和端口","description":"两台使用私有地址的设备通过一个公网地址出去。在 NAT 边界，发送方地址和端口被取出，换入公网的值；接收方的字段原样通过。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:natMappingTable","title":"NAT 映射表","description":"每个出去的数据包都会写下一行。回来的应答凭到达的端口找到它的主人。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:echoAndReply","title":"回显请求与回显应答","description":"带编号的请求在对方处弹回，成为标识符与 seq 相同的应答；发送方按编号配对，并计算两个时刻之差。","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:ttlExpiredReports","title":"寿命耗尽时，路由器会回报","description":"寿命(TTL)耗尽的数据包会怎样？发送方又如何借此得知路径上的路由器？","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:tcpHandshake","title":"TCP 与 UDP","description":"当分段在途中丢失或乱序时，TCP 以时间和额外的数据包为代价，把六个分段按顺序全部交给应用；UDP 则把到达的分段按到达的顺序交出。","domain":"networks","subdomain":"transport"},
    {"id":"facet:congestionControl","title":"流量控制与拥塞控制","description":"发送方每个往返只发送两个窗口 — 接收窗口与拥塞窗口 — 中较小的那个。调节应用的读取量,看限制方从接收方移到网络。","domain":"networks","subdomain":"transport"},
    {"id":"facet:threeWaySync","title":"三次握手","description":"双方各持有两项待确认的事实。第二条消息一次填满两项，服务器仍要等第三条。","domain":"networks","subdomain":"transport"},
    {"id":"facet:sequenceNumber","title":"序列号","description":"空缺之后的分段先到达时，确认号停在原地；空缺一被填上，它就按字节数一次跳过所有暂存的分段。","domain":"networks","subdomain":"transport"},
    {"id":"facet:receiverWindow","title":"接收窗口","description":"接收方把缓冲区的空位以数字返回，发送方只发送那么多。","domain":"networks","subdomain":"transport"},
    {"id":"facet:slowStart","title":"慢启动","description":"每收到一个确认，窗口就加一，于是每个往返发送的数量是上一个的两倍——到达阈值后，每个往返只加一。","domain":"networks","subdomain":"transport"},
    {"id":"facet:backOffOnLoss","title":"丢失就减半","description":"相同的确认号不断堆积，第三个重复到来时窗口折半，仅此一次。","domain":"networks","subdomain":"transport"},
    {"id":"facet:sawtooth","title":"锯齿模式","description":"每个往返中拥塞窗口加一，超出网络容量时减半。留下的值画出重复的锯齿，其平均值低于容量。","domain":"networks","subdomain":"transport"},
    {"id":"facet:sendAndForget","title":"发出即忘","description":"UDP 每个数据报只发一次，从不确认：一个丢失，两个顺序颠倒到达，应用按到达顺序接收。","domain":"networks","subdomain":"transport"},
    {"id":"facet:http","title":"HTTP 与 WebSocket","description":"服务器不能先开口，客户端只能去问。轮询间隔只是在延迟和白费的请求之间交换；升级一次并保持打开的连接站在这种交换之外。","domain":"networks","subdomain":"application"},
    {"id":"facet:dns","title":"DNS 委派与缓存","description":"把解析器的 TTL 调大，沿委派树向下的查询变少，代价是源记录改变后旧答案被返回的时间变长。","domain":"networks","subdomain":"application"},
    {"id":"facet:requestResponse","title":"一个页面，多次请求","description":"只有请求过的才会返回。响应里新发现的名字，要再请求一次才会来。","domain":"networks","subdomain":"application"},
    {"id":"facet:statelessNeedsToken","title":"服务器什么都不记得 —— Cookie 随请求带来","description":"响应发出后，服务器就放下这个请求。只有请求携带的 Cookie 能连到会话表。","domain":"networks","subdomain":"application"},
    {"id":"facet:delegateDownTheTree","title":"DNS 委派：沿着树往下问","description":"没有哪台服务器知道所有名字。解析器先问最上层的服务器，被指向下一层，再问同一个问题，直到最底层给出答案。","domain":"networks","subdomain":"application"},
    {"id":"facet:cacheTtl","title":"在 TTL 耗尽之前一直保留的答案","description":"解析器在 TTL 期间保留收到的答案。即使源头已变，在剩余时间归零之前仍返回旧地址。","domain":"networks","subdomain":"application"},
    {"id":"facet:storeAndForward","title":"存储转发","description":"在下一处回答 250 之前，当前保管的一方不会删除邮件——因此服务器宕机、发件人离线都不会让邮件丢失。","domain":"networks","subdomain":"application"},
    {"id":"facet:controlAndDataChannel","title":"控制通道与数据通道","description":"FTP 命令在一条始终打开的通路上往返，列表或文件则各自走一条随开随关的通路。","domain":"networks","subdomain":"application"},
    {"id":"facet:upgradeThenKeepOpen","title":"升级之后保持打开","description":"一个带 Upgrade 的 HTTP 请求，把同一个连接变成双方随时都能说话的通道。","domain":"networks","subdomain":"application"},
    {"id":"facet:tlsHandshake","title":"TLS 握手","description":"迪菲-赫尔曼能挡住窃听者，却挡不住插在中间的人。只有检查证书链和服务器签名，才能确定密钥是和谁商定的。","domain":"networks","subdomain":"network-security"},
    {"id":"facet:auth","title":"令牌认证与有效期","description":"门只看令牌，分不清偷来的和自己的。能缩短的只有时间：有效期越短，泄露的令牌越没用，但也要越频繁地重新领取。","domain":"networks","subdomain":"network-security"},
    {"id":"facet:firewall","title":"防火墙","description":"防火墙在第一条匹配的规则处停下，因此规则的位置决定判定。把拒绝规则 R2 移到第 1–4 位，观察六个数据包的判定如何翻转。","domain":"networks","subdomain":"network-security"},
    {"id":"facet:sharedSecretInPublic","title":"在公开线路上约定秘密","description":"线路上传过的一切都被窃听者抄了下来，两端又怎样得到窃听者不知道的同一个数？","domain":"networks","subdomain":"network-security"},
    {"id":"facet:certificateChain","title":"沿证书链向上验证","description":"从叶证书出发，沿着签发者一级一级向上，直到到达客户端已经信任的根证书为止。","domain":"networks","subdomain":"network-security"},
    {"id":"facet:tokenBearer","title":"门只看令牌","description":"持有者令牌在人手之间传递，副本和原件一样有效：无论来自哪个地址，API 服务器都会放行出示令牌的一方。","domain":"networks","subdomain":"network-security"},
    {"id":"facet:ruleMatchOrder","title":"防火墙规则的顺序","description":"数据包从上往下逐条比对规则列表，在第一条匹配的规则处停下。","domain":"networks","subdomain":"network-security"},
    {"id":"facet:relationalTablesAndKeys","title":"表与键","description":"两张有名字的格子 — 一边的主键锁定每一行的身份，另一边的外键指向那个被锁定的值，把两者绑成一个一致的结构","domain":"databases","subdomain":"relational"},
    {"id":"facet:normalForms","title":"范式","description":"把一张选课表从 UNF 一步步拆到 BCNF，每一步都数一数：改一条事实要动的行、条件找到的行，以及没有任何一张表能容纳的依赖。","domain":"databases","subdomain":"relational"},
    {"id":"facet:primaryKeyIdentifies","title":"主键唯一地挑出一行","description":"按姓名或城市调用会剩下两行，按主键调用只剩一行。","domain":"databases","subdomain":"relational"},
    {"id":"facet:foreignKeyPoints","title":"外键按值指向一行","description":"每个订单的外键值都会到达键相同的客户行。没有可到达行的值会被拒绝，订单表保持不变。","domain":"databases","subdomain":"relational"},
    {"id":"facet:rowIsAFact","title":"一行就是一个事实","description":"表头是带空格的句子,每一行的值填进空格,成为一句真话。没有对应行的组合为假。","domain":"databases","subdomain":"relational"},
    {"id":"facet:setOfRows","title":"关系是行的集合","description":"改变行的顺序，或再次插入已有的行，都不会得到不同的关系。","domain":"databases","subdomain":"relational"},
    {"id":"facet:updateAnomaly","title":"更新异常","description":"同一个事实写在多行里。更新只落到其中一行，答案分成了两个。","domain":"databases","subdomain":"relational"},
    {"id":"facet:atomicCell","title":"一个单元格只放一个值","description":"与其他值挤在同一单元格里的值,条件找不到它。把单元格拆开、每个值占一行,同样的条件就能找到。","domain":"databases","subdomain":"relational"},
    {"id":"facet:partialDependency","title":"部分函数依赖","description":"只挂在双列键其中一列上的列，会带着那一列分离出去，成为自己的表。","domain":"databases","subdomain":"relational"},
    {"id":"facet:transitiveDependency","title":"传递依赖","description":"只能经由非键列才挂到键上的列","domain":"databases","subdomain":"relational"},
    {"id":"facet:determinantMustBeKey","title":"决定因素必须是键","description":"把每个决定因素当作种子，沿依赖扩散。键能到达所有列；中途停下的决定因素会让它决定的组合在多行中重复。","domain":"databases","subdomain":"relational"},
    {"id":"facet:dml","title":"DML 语句的顺序","description":"按所选顺序执行同样的 INSERT、UPDATE、DELETE。每个 WHERE 看的是其语句执行那一刻的表。","domain":"databases","subdomain":"sql"},
    {"id":"facet:joinKinds","title":"连接的种类","description":"用 INNER、LEFT、RIGHT、FULL、CROSS 连接同样的两张表，观察没有配对的行中哪些进入结果、哪些被丢弃。","domain":"databases","subdomain":"sql"},
    {"id":"facet:subquery","title":"子查询","description":"括号里的查询要么只执行一次、值留在原处,要么对外层每一行重新执行、值每次被替换。","domain":"databases","subdomain":"sql"},
    {"id":"facet:windowFunction","title":"窗口函数","description":"窗口函数在不折叠行的情况下汇集相邻的行。逐步放宽窗口框，把保留下来的每一行的和与 GROUP BY 按队伍折叠出的总和相比较。","domain":"databases","subdomain":"sql"},
    {"id":"facet:insertUpdateDelete","title":"插入、更新、删除","description":"INSERT、UPDATE、DELETE 各自改变了表中的什么?","domain":"databases","subdomain":"sql"},
    {"id":"facet:groupThenAggregate","title":"GROUP BY 把多行折叠成一行","description":"city 相同的行聚到一起，每组折叠成只保留行数和总和的一行。","domain":"databases","subdomain":"sql"},
    {"id":"facet:schemaDefinesShape","title":"模式决定每一行进入时的形状","description":"CREATE TABLE 先定下形状。每条 INSERT 的值逐个与之比对，只要有一格不符，整行都会被退回。","domain":"databases","subdomain":"sql"},
    {"id":"facet:matchOnKey","title":"INNER JOIN — 键相同的行连在一起","description":"emp 的每一行带着自己的 dept_id 去 dept 找 id 相同的行，那一行的副本贴上来，合成结果中的一行。","domain":"databases","subdomain":"sql"},
    {"id":"facet:keepUnmatched","title":"保留没有匹配的行","description":"LEFT JOIN 如何处理没有匹配的左侧行?","domain":"databases","subdomain":"sql"},
    {"id":"facet:allPairs","title":"CROSS JOIN 生成所有配对","description":"没有条件，sizes 的每一行一次性伸向 colors 的所有行。结果按 4 · 8 · 12 增长——行数乘以行数。","domain":"databases","subdomain":"sql"},
    {"id":"facet:queryInsideQuery","title":"外层查询使用内层的答案","description":"括号内的查询先执行并变成一个值，这个值替换括号所在的位置，然后外层查询才筛选行。","domain":"databases","subdomain":"sql"},
    {"id":"facet:windowSlides","title":"窗口函数 — 窗框滑动，行都留下","description":"框住前一行和后一行的窗框按 day 顺序向下滑动。框内的和写进该行自己的格子里，没有任何一行被合并掉。","domain":"databases","subdomain":"sql"},
    {"id":"facet:indexChoice","title":"索引与查询形态","description":"把同一个查询同时交给全表扫描、B+ 树和哈希索引，数出每条路径要读的页，沿最便宜的路径读取，再看一次 INSERT 如何写入每个索引。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:bitmapIndex","title":"位图索引","description":"每个条件读取一行位串。改变叠加的条件数量和组合方式，看看读取了什么。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:compositeIndex","title":"复合索引","description":"复合索引的列顺序决定哪些查询代价低。交换顺序，条目就重新排列。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:leavesLinked","title":"叶子之间的链接","description":"B+ 树的范围扫描只向下走一次，到达含有下界的叶子，之后在叶子之间横向跳转。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:allDataInLeaves","title":"值只在叶子里","description":"在 B+ 树中，要找的键已经在上层出现了，为什么还要一直往下走？","domain":"databases","subdomain":"indexes"},
    {"id":"facet:exactMatchOnly","title":"只有精确匹配才快","description":"在哈希索引中，= 查询直接落到一个桶里，而范围查询必须打开所有的桶。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:bitPerRow","title":"每行一位","description":"位图索引为每个值保留一条位行。表中每一行在自己值的位行记 1，在其余位行记 0。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:bitwiseCombine","title":"用 AND 叠合位图","description":"把每个条件各一条的两条位串叠在一起，只留下两者都为 1 的位置，也只读取那些行。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:leftmostPrefix","title":"最左前缀","description":"(last_name, first_name) 索引只有在给出首列时才能缩小查找范围；只有 first_name 时要读遍所有条目。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:indexCostsWrite","title":"读得越快，写得越慢","description":"同一张表放两份。有索引时，读取收窄到几页，写入则扩散到表和每个索引。","domain":"databases","subdomain":"indexes"},
    {"id":"facet:optimizer","title":"连接顺序与执行计划","description":"过滤后留下的客户数量不同，两种连接顺序产生的中间行数也随之不同。","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:costModel","title":"代价模型与统计信息","description":"改变直方图的桶数，比较优化器估计的行数、实际的行数以及它选择的路径。","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:sameAnswerDifferentPlan","title":"同样的答案，不同的计划","description":"同一个查询用两种顺序执行——先连接后过滤，或先过滤后连接。答案的行彼此重合，检查次数却不重合。","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:reorderJoins","title":"连接顺序","description":"先连接哪两张表，决定了中间结果会膨胀到多大。最后剩下的行在两种顺序中相同。","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:planIsATree","title":"执行计划是一棵树——行自下而上流动","description":"行从表扫描中逐一出发，依次穿过各个算子向上。构建侧先汇集到哈希表中；被过滤的行停在失败处；只有到达顶端的行才成为答案。","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:estimateFromStats","title":"用统计信息估算行数","description":"优化器不读表，如何知道结果有多少行？","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:badEstimateBadPlan","title":"估算错了，计划也就错了","description":"优化器根据统计信息估算行数并选择较便宜的路径，而实际行数一出现，两条路径的代价顺序就颠倒了。","domain":"databases","subdomain":"query-processing"},
    {"id":"facet:acid","title":"ACID","description":"数据库对提交回复了 OK。断电之后这个事务还在吗?把 OK 移到日志刷盘之前或之后看看。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:isolation","title":"隔离级别与锁","description":"一个调度中同时含有脏读、不可重复读和幻读。提高隔离级别，它们会逐个消失——因为 T1 持锁更久、范围更广，其他操作随之等待，在执行顺序中被推后。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:mvcc","title":"MVCC","description":"在事务开始时取得的快照会一直看到当时可见的版本，因此清理无法回收该版本及其之后的版本。按语句取得的快照不保留任何版本。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:allOrNothing","title":"要么全做，要么全不做","description":"事务中一条语句失败时，之前的写入会按撤销日志从最后一条开始倒回。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:durableAfterCommit","title":"提交之后即持久","description":"提交记录落到磁盘上的日志文件之后，OK 才会返回——所以崩溃也夺不走它。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:dirtyRead","title":"脏读","description":"已写入但尚未提交的值泄漏到另一个事务，写入方回滚之后仍留在它手中。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:nonRepeatableRead","title":"不可重复读","description":"在同一个事务中把同一行读两次，会得到两个不同的已提交值。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:phantomRead","title":"幻读","description":"查询读过的行都已加锁,同一查询第二次却多返回一行 — 新行挤进了结果。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:sharedVsExclusive","title":"共享锁与排他锁","description":"可以一起读，不能一起写。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:lockWait","title":"锁等待","description":"想修改别人已锁住的行的事务会排队停下,直到持有者提交并释放锁。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:keepOldVersion","title":"保留旧版本","description":"MVCC 从不覆盖一行：每次写入都在旧版本旁叠上一个新版本，提交时刻关闭旧版本并开启新版本。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:readSeesSnapshot","title":"读取看到的是快照","description":"两个事务先后读取同一行，却得到不同的值：各自取的是其开始时刻所落入的版本。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:growThenShrink","title":"两阶段锁 — 先增长后收缩","description":"在两阶段锁中，事务要先取得全部锁才开始释放。所以已经用完的锁，也要一直持有到最后一把锁被取得。","domain":"databases","subdomain":"transaction"},
    {"id":"facet:sharding","title":"分片","description":"按递增的 order_id 编号进来的新行被分到各个分片，再用范围查询取最近的几行。切换划分方式和分片数，看新的写入落在哪里、查询要打开几个分片。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:replication","title":"复制与 CAP","description":"领导者在对写入回复 OK 之前应等待多少个跟随者？网络分区时，这个选择又变成了什么？","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:raft","title":"Raft","description":"调整节点数和停止的节点数，看多数门槛落在返回的选票与副本中的哪一个上。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:paxos","title":"Paxos","description":"两个提议者向三个接受者发送 prepare 和 accept。用旋钮改变 P2 的 prepare 插在 P1 的 accept 之间的位置,以及 P2 询问哪些接受者,观察哪个值被选定、有多少 accept 被弹回。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:splitByKey","title":"按键拆分","description":"仅凭键值就决定一行去哪个分片——所以按键查找时只需访问一个分片。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:hotShard","title":"热点分片","description":"在范围分片下，不断增大的键全部落入最后一个范围，只堆在一个分片上。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:copyToFollowers","title":"复制到跟随者","description":"领导者写下值，复制给两个跟随者，三者都写好后才回复。领导者停止后，跟随者仍能回答读取。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:replicationLag","title":"复制延迟","description":"领导者立即回复 ok;新值在不同时刻到达各个跟随者,期间的读取拿到旧值。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:partitionForcesChoice","title":"网络分区迫使你做选择","description":"网络分区期间,被隔开的节点收到读请求时,要么拒绝(一致性),要么用旧值回答(可用性)——不能两者兼得。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:electALeader","title":"选出领导者","description":"计时器最先耗尽的节点请求投票，获得多数票即成为领导者。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:majorityDecides","title":"多数派决定","description":"Raft 领导者收到的写入何时提交?","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:logReplicateInOrder","title":"回退并修复日志","description":"当 Raft 跟随者的日志与领导者不一致时,领导者如何把它修正过来?","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:splitBrain","title":"脑裂","description":"网络分区后出现两个领导者。只有拥有多数的一侧能提交，连接恢复后较低的 term 退下。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:proposeAndPromise","title":"提议与承诺","description":"已向更大编号作出承诺的接受者，不会接受编号更小的提议。","domain":"databases","subdomain":"distributed-db"},
    {"id":"facet:documentKv","title":"文档与键值","description":"同样的三笔订单，分别存成三张表、文档或键值。切换存储方式和查询，看哪些块被从存储中取出。","domain":"databases","subdomain":"nosql"},
    {"id":"facet:columnFamily","title":"列族","description":"把列按什么分组存进页里，决定了一次查询要读多少页。试着改变分组方式和查询的列数。","domain":"databases","subdomain":"nosql"},
    {"id":"facet:graphDb","title":"图数据库","description":"查找 Ana 在 k 跳以内的朋友。改变跳数，并在“节点自己持有边”与“所有边放在一张表里”之间切换，看每种方式读取多少条边。","domain":"databases","subdomain":"nosql"},
    {"id":"facet:nestedDocument","title":"把分散的行折进一个文档","description":"分散在三张表里的一个订单，一行一行地折进一个嵌套文档。连接各行的键列消失了——被装在里面本身就是联系。","domain":"databases","subdomain":"nosql"},
    {"id":"facet:keyToValue","title":"按键取一个，按值内容取全部","description":"键值存储靠什么找到值？如果问的是值里面的内容，会发生什么？","domain":"databases","subdomain":"nosql"},
    {"id":"facet:columnOriented","title":"列式存储","description":"把值按列聚在一起存放，只问一列的查询就只读那一列的页。","domain":"databases","subdomain":"nosql"},
    {"id":"facet:traverseRelationships","title":"沿着关系前进","description":"图数据库只查看节点自己持有的边，只走类型符合路径的边，其余的从不触及。","domain":"databases","subdomain":"nosql"},
    {"id":"facet:tokenization","title":"词法切分 (词法分析)","description":"自左向右的目光把同类字符熔进一个区段，直到再也伸不长时闭合，然后把这个闭合的段落作为带类别标签的词元卡片落到输出行","domain":"compilers","subdomain":"lexical"},
    {"id":"facet:linearRegression","title":"线性回归 — 穿过点群的一条直线","description":"让 (w, b) 顺坡下滑来拟合直线 — 残差方块缩小，点也就滚进了谷底","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:logisticRegression","title":"逻辑回归 — 学出概率，选定一条线","description":"权重是学出来的，阈值是选出来的。调高它，误报变少，漏报变多。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:knn","title":"k 近邻 — 要问多少个？","description":"它不学习；每次提问都重新扫一遍数据。移动 k，整条边界都会变。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:decisionTree","title":"决策树 — 提问该在何时停下","description":"每个节点都试遍所有切法，留下混杂最少的那一刀，再对两边继续追问 — 抬高深度上限，看看收益在哪里耗尽。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:randomForest","title":"随机森林 — 多种几棵树能多出什么","description":"一棵树在哪里都是 100% 笃定。森林还会告诉你它有多笃定。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:svm","title":"支持向量机 — 当一个点掉进缝里","description":"合页损失与次梯度下降，由 C 决定最宽的缝可以吞下多少错误","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:residualDistance","title":"残差","description":"点离直线有多远 — 沿 y 方向直着量。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:leastSquares","title":"最小二乘","description":"带符号的偏差为什么不能直接相加，平方又修好了什么。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:squashToProbability","title":"把分数压成概率","description":"无尽的轴，被折进 0 与 1 之间的窄带里。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:decisionBoundary","title":"决策边界 — 最后才出现的那条线","description":"先给每个位置一个概率，越过一半的地方才是边界","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:voteByNeighbors","title":"近邻投票","description":"最近的五个被一个个叫出来，各自投下一票。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kChangesBoundary","title":"k 如何改变答案","description":"最近的一个说这样，最近的三个说那样。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:splitByQuestion","title":"什么才是好问题","description":"切分线沿着一个轴滑动，始终分不开标签。把它换到另一个轴上，第一个位置就切得干干净净。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:impurityDrops","title":"怎样衡量一次好的划分","description":"混杂程度化为一个数字，每切一刀它就下降。这个数看的是比例，不是个数。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:manyTreesVote","title":"集成投票","description":"五棵树回答同样的五个问题。没有一棵全对，多数决却全对。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:baggingSample","title":"装袋法","description":"有放回地抽样，于是每一袋学到的东西都不一样。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:widestMargin","title":"最大间隔","description":"在能分开两个类别的直线中，让间隔带张得最宽的那条获胜。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:supportVectorsOnly","title":"决定这条线的只有贴在边上的点","description":"十个点里，有几个决定了这条线？","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kernelLifts","title":"核技巧 — 抬到一条直线就够为止","description":"分不开的，升一个维度就分得开","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kmeans","title":"k-均值 — 在不知道中心的情况下找出群","description":"同样的 k，起点不同答案就不同 — 而且最紧凑的答案并不是人眼看到的那一群。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:hierarchical","title":"层次聚类 — 两个群之间的距离该怎么算","description":"单连接、全连接与平均连接从同样的八个点长出三棵不同的树，同一个切割高度也给出三种不同的答案","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:dbscan","title":"DBSCAN — 两个旋钮拨的是不同的东西","description":"eps 把原本分开的连起来，minPts 把小团打散。同样的组数，可能来自完全不同的两个取值。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:pca","title":"PCA — 最宽的方向取决于坐标轴的单位","description":"幂迭代找出主轴；把两个轴标准化，主轴就转了 42 度","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:tsne","title":"t-SNE — 摊平后的图能告诉你什么，不能告诉你什么","description":"困惑度决定了群会被打碎、被模糊，还是干净分开 — 而即便分得干净，群与群之间的距离也留不下来","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:assignThenMove","title":"先归属，再移动","description":"每个点抓住最近的中心，每个中心滑向抓住它的那些点的中间。两者轮流，直到无人再动。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:kMustBeGiven","title":"簇数只能由人给定","description":"同样的十二个点分出三种结果，量了离散度也挑不出哪一种。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:mergeNearestPair","title":"不先定好数目，能不能聚类","description":"把最近的两个合并，并把接点挂在这段距离的高度上。长出来的那棵树，说的就是它们原本相隔多远。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:dendrogramCut","title":"切分树状图","description":"在树的哪个高度切开，决定了你得到几个簇。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:denseNeighborhood","title":"蔓延所及即为一群","description":"邻居的邻居也归入同一群，所以群不必是圆的。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:noiseLeftOut","title":"噪声点","description":"不属于任何一群的点，方法怎么处理。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:directionOfMostSpread","title":"散布最广的方向","description":"让一根轴穿过点云旋转，在投影散得最开处停下。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:projectAndLose","title":"投影与丢失","description":"少了一个维度，会消失什么。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:keepNeighborsClose","title":"让近的保持近","description":"环上十个点展成一条线：九对邻居的间距保住了，一对被撕开。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:globalAndLocal","title":"全局与局部 — 两种展平并排看","description":"看起来一样宽的簇间距，未必真的一样","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:subwordSegmentation","title":"子词切分 — 词表越大，同一句话被切得越少","description":"把合并次数调大，散落的字母就会互相滑拢合为一体 — 同一句话从 33 块变成 7 块","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:bpeTraining","title":"BPE 训练 — 什么常见，就决定先合并什么","description":"调一个词的频率，配对就会争夺名次互换位置，合并顺序被重排，最终得到不同的词表","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:vocabulary","title":"词表 — 装了什么，决定了它能把什么切得好","description":"同一套 BPE 在三份语料上训练，同样的六个词被切成不同的样子 — biology 与 code 的总数同为 32，切得好的词却正好相反","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:betweenLetterAndWord","title":"字母与单词之间","description":"同一个句子切成三种大小 — 片段落在字母与单词之间。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:mergeTheFrequentPair","title":"合并最常相邻的一对","description":"最常相邻的一对合成一个片段，同一道接缝在整个语料里同时合上。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:unknownBecomesKnown","title":"接住陌生的词","description":"词表从未见过的词被切成两个见过的碎片，然后以这些碎片拼写着通过。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:spaceIsPartOfIt","title":"空格也是一个字符","description":"把空格写成一个字符后，这个标记就会粘在片段上随之移动，同一个单词因而在词表中占据两个位置。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:tokensPerLanguage","title":"每种语言的词元数不同","description":"同样意思的句子，在不同语言里被切成的片段数相差数倍。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:boundaryShift","title":"一个字母之差","description":"改动一个字母，词元边界就塌了：原本完整的词裂成三块。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:vectorSimilarity","title":"向量相似度","description":"用什么来量，决定了谁算相近。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:exhaustiveSearch","title":"穷举搜索","description":"候选始终是 64，但提高维度后，需要遍历的量会膨胀到填满整块板。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:hnsw","title":"HNSW — 层够多，从哪出发都能到","description":"转动层数。只有一层时六条路径中仅一条到达真正最近邻；三层时六条全都到达，而看过的点不减反增。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:invertedFileIndex","title":"倒排文件索引","description":"打开多少分区，同时决定了准确度与速度。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:productQuantization","title":"乘积量化","description":"把向量切成若干段，每段只保留一个编号。切得越细，误差越小，占用越多。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:angleNotLength","title":"比的是角度，不是长度","description":"余弦相似度比较的是方向：角度决定排名，长度被排除在外，因此可能与欧氏距离相反。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:compareWithAll","title":"与全部比较","description":"精确，但数量一大就撑不住 — 乘法按候选数乘以维度不断堆积。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:neighborsLinkedAhead","title":"预先连好邻居","description":"路若已经铺好，就不必逐一度量，走过去便能找到答案。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:coarseThenFine","title":"先在稀疏层大步走，再到下层细找","description":"在点很少的顶层用大步跳跃定下位置，下面的层继承这个位置并进一步收窄。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:probeAFewCells","title":"只打开少数单元","description":"查询只与最近几个单元内的点比较，未打开单元中的点从不触及。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:splitAndNumber","title":"切分后编号","description":"把向量切成两段，每段只留下最接近的代表编号。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:recallSpeedTradeoff","title":"搜得越少，漏得越多","description":"真正最近的五个是固定的。少搜几个格子，其中一些就会从答案中滑出，由更远的点占据它们的座位。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:chunking","title":"文本分块","description":"把一段文字按词数、按半重叠或在句末切成检索用的块——看哪些句子被切断、一共存了多少词、每块把窗口填满了多少。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:hybridSearch","title":"混合检索","description":"把按共同词语的排名和按语义的排名混合起来。给每一边多少份额决定了谁排在前面——偏向任何一边太多，又会丢掉正确答案。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:reranking","title":"重排序","description":"细致但昂贵的重排器只在交给它的文档里调整顺序。多交一些候选，门槛就往下移，交过去的文档或升或降——前3名填满之后，只有调用次数还在增长。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:contextAssembly","title":"上下文组装","description":"把检索到的片段放进上下文越多，答案片段就越往中间沉。放在哪里和放不放进去一样重要。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:whereToCut","title":"在哪里切分","description":"按固定词数切分文本，切口会落在句子中间。按段落结尾切分，块数相同，每个句子都保持完整。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:overlapTheSeam","title":"在接缝处重叠切分","description":"下一个窗口从接缝处后退几个词再开始，被切口卡住的句子便完整落入一个分块。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:sameWordVsSameMeaning","title":"同样的词与同样的意思","description":"关键词检索(BM25)与语义检索(余弦)把同样的五篇文档排成不同的顺序。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:fuseTwoRankings","title":"合并两个排名","description":"每个列表只按名次给文档一份分数，分数叠起来后排出新的顺序。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:lookCloselyAtFew","title":"只细看少数几个","description":"八个候选中只有前四个越过门槛，逐一与查询对照，然后这四个之间调换位置。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:budgetRunsOut","title":"预算用完了","description":"指令、问题和回答空间先占好位置，片段按排名填充剩余空间，直到有一个放不下为止。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:lostInTheMiddle","title":"迷失在中间","description":"同一个答案片段从上下文的开头移到正中间，再移到末尾。模型往往注意到两端，却容易漏掉夹在中间的内容。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:greedyDecoding","title":"贪心解码","description":"每一步都选第 1 名，整句话也不一定最可能。把第一步让给第 2 或第 3 名，文本就换到另一条分支上。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:temperatureSampling","title":"温度与采样","description":"温度让下一个词的份额聚拢或散开，重复惩罚削减已经说过的词。同样的三十个随机数落进新的格子。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:topKTopP","title":"top-k 与 top-p — 按个数切还是按份额切","description":"尖锐和平坦两个语境共用同一组旋钮。k 在两边留下相同的个数,p 留下相同的份额。两者同时设定时,p 在 k 留下的部分重新归一后再衡量。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:beamSearch","title":"束搜索","description":"同时带着几条序列前进，每一步只保留最好的几条。要找到最可能的句子，束需要多宽——先删掉不可能的词，这个宽度又会怎样变化？","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:alwaysTheHighest","title":"永远只选第一","description":"贪心解码每次都选概率最高的下一个词元——于是句子沿着自己走过的路又走了一遍。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:flattenOrSharpen","title":"温度：变平还是变尖","description":"在 softmax 之前把 logit 除以温度，概率会向第一名集中或向其余候选分散——顺序从不改变。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:cutTheTail","title":"top-k：先剪掉尾部，再抽取","description":"top-k 丢掉排名 k 以下的候选，把它们的份额按大小比例分给剩下的候选，只在剩下的里面抽取。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:fillToAShare","title":"装满到一定份额","description":"top-p 按概率从高到低加入候选，直到份额达到 p——尖锐的语境两个就停，平坦的语境要七个。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:carrySeveralLines","title":"同时带着几条句子走","description":"束搜索如何抓住贪心解码错过的句子：每条保留的句子都分出分支，所有分支按对数概率之和排序，只留下前几条。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:penalizeRepeats","title":"重复惩罚","description":"已经写过的候选词被削减 logit——正值除以 θ，负值乘以 θ——原来的第一名沉到新候选之下。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:eraseTheImpossible","title":"先删去不可能的候选","description":"语法约束解码:在选择之前,语法删去它禁止的候选,其份额由其余候选分摊。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:kvCache","title":"KV 缓存","description":"保留过去词元的 K 和 V，之后每一步只需计算一个新位置。代价是缓存随文本增长，而注意力仍要看过去的所有位置。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:batchingAndPadding","title":"批处理与填充","description":"八个请求并排运行。槽位越多步数越少，但空格越多——除非完成的槽位立即被补上。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:speculativeDecoding","title":"推测解码","description":"小模型先写出 γ 个词，大模型一次调用把它们全部检查。草稿越长调用越少，但第一个错词之后的部分全被丢弃——成本在中间最低。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:dontRecountThePast","title":"不必重算过去","description":"再生成一个词元，需要前面每个位置的 K 和 V。没有缓存时每一步都把它们全部重算；有 KV 缓存时只计算最新的位置，其余原地保留。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:cacheKeepsGrowing","title":"缓存不断增长","description":"文本变长时，KV 缓存会变得多大？","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:shortWaitsForLong","title":"短请求等待长请求","description":"把长度不同的请求放进同一批运行时,先结束的请求会怎样?","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:refillTheEmptySlot","title":"空位立刻补上","description":"一个请求完成、空出位置后，队列中的下一个请求在紧接着的下一步就进入该位置。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:draftThenVerify","title":"先起草，再验证","description":"小模型先写出四个词元，大模型只调用一次就一并检查，从前往后保留相符的部分。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:firstTokenVsRest","title":"第一次与之后","description":"第一步时整个提示一次性通过 K·V 计算，之后只有刚生成的那个词元进入。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:lruCache","title":"LRU 缓存","description":"容量固定的键值存储 — 每次触碰都把节点拖到 MRU 端，溢出时 LRU 端消失","domain":"system-design","subdomain":"caching"},
    {"id":"facet:cachingCdn","title":"CDN","description":"遍布全球的边缘缓存承接就近的客户端 — 手上有的答案很快返回，没有的则上溯层级取回并顺手填满边缘","domain":"system-design","subdomain":"caching"},
    {"id":"facet:messagingPubsub","title":"Pub/Sub 消息传递","description":"发布者与订阅者只认识 broker 的主题而不认识彼此的多对多异步消息 — 一次发布以副本形式扇出给所有订阅者","domain":"system-design","subdomain":"messaging"},
    {"id":"facet:asymmetricRsa","title":"RSA — 公钥密码","description":"由两个素数所生的一对非对称密钥 — 一把只能锁，另一把才能开，用上锁的那把绝不能还原","domain":"security","subdomain":"asymmetric"},
    {"id":"facet:hashFixedLength","title":"定长输出","description":"输入从空到整个文件，输出始终一样大","domain":"security","subdomain":"hash"},
    {"id":"facet:hashAvalanche","title":"雪崩效应","description":"只改一个字符，哈希输出就有近一半被翻转","domain":"security","subdomain":"hash"},
    {"id":"facet:pigeonholeCollision","title":"鸽巢原理","description":"十六个位置，十七个输入 — 总有一个没有自己的位置","domain":"security","subdomain":"hash"},
    {"id":"facet:hashIntegrityCheck","title":"完整性校验","description":"公开的一行哈希，就能告诉你收到的副本是否被动过","domain":"security","subdomain":"hash"},
    {"id":"facet:hashSalt","title":"盐","description":"每个账号一份不同的盐，让相同的密码不会被存成相同的值","domain":"security","subdomain":"hash"},
    {"id":"facet:hashChain","title":"哈希链","description":"每一格都带着前一格的哈希，改动一处，其后全都对不上","domain":"security","subdomain":"hash"},
    {"id":"facet:merkleTree","title":"默克尔树","description":"把哈希两两折叠，一片叶子变了，也只有它到顶的那条路会动","domain":"security","subdomain":"hash"},
    {"id":"facet:signatureKeyDirection","title":"密钥的方向","description":"加密与签名用同一对密钥，方向相反","domain":"security","subdomain":"signature"},
    {"id":"facet:signatureOnHash","title":"对摘要签名","description":"不论文档多大，签名始终是 64 字节","domain":"security","subdomain":"signature"},
    {"id":"facet:matrixTransform2d","title":"2D 矩阵变换 — 两列即两个基的落点","description":"2×2 矩阵就是 i-hat 与 j-hat 的落点 — 平面上每个点都以同样的 (u, v) 系数进入新基的组合，直线仍是直线，原点留在原处","domain":"graphics","subdomain":"transform-2d"},
  ],
};
