/**
 * 자동 생성 파일 — 직접 편집하지 말 것.
 *
 * 생성: pnpm catalog:gen  (scripts/gen-facet-catalog.mts)
 * 출처: 각 facet 의 facet.ts(title/description) + taxonomy/taxonomy.json(분야).
 */

import type { FacetCatalog } from '../catalog-types.js';

export const CATALOG: FacetCatalog = {
  locale: "zh",
  domains: [
    {"id":"cs-fundamentals","name":"计算机科学基础","subdomains":[{"id":"data-structures","name":"数据结构"},{"id":"probabilistic-structures","name":"概率数据结构"},{"id":"algorithms","name":"算法"},{"id":"graph-algorithms","name":"图算法"},{"id":"string-algorithms","name":"字符串算法"},{"id":"numerical-algorithms","name":"数值算法"},{"id":"complexity","name":"计算复杂度"}]},
    {"id":"programming-fundamentals","name":"编程基础","subdomains":[{"id":"control-flow","name":"控制流"}]},
    {"id":"computer-architecture","name":"计算机体系结构","subdomains":[{"id":"number-representation","name":"数与位表示"},{"id":"cache-hierarchy","name":"缓存层次结构"},{"id":"instruction-pipeline","name":"指令流水线"},{"id":"branch-prediction","name":"分支预测"},{"id":"data-layout","name":"数据布局与访问"}]},
    {"id":"operating-systems","name":"操作系统","subdomains":[{"id":"process-thread","name":"进程与线程"}]},
    {"id":"networks","name":"计算机网络","subdomains":[{"id":"network-routing","name":"网络层"}]},
    {"id":"databases","name":"数据库","subdomains":[{"id":"relational","name":"关系模型"}]},
    {"id":"compilers","name":"编译器与语言","subdomains":[{"id":"lexical","name":"词法分析"}]},
    {"id":"ml-foundations","name":"机器学习基础","subdomains":[{"id":"supervised","name":"监督学习"},{"id":"unsupervised","name":"无监督学习"}]},
    {"id":"ai-engineering","name":"AI 工程","subdomains":[{"id":"text-tokenization","name":"分词"},{"id":"vector-search","name":"嵌入与向量检索"},{"id":"retrieval-augmentation","name":"检索增强"},{"id":"decoding","name":"生成控制"},{"id":"inference-efficiency","name":"推理效率"}]},
    {"id":"system-design","name":"系统设计","subdomains":[{"id":"caching","name":"缓存"},{"id":"messaging","name":"消息队列"}]},
    {"id":"security","name":"安全与密码学","subdomains":[{"id":"asymmetric","name":"非对称加密"},{"id":"hash","name":"哈希"},{"id":"signature","name":"数字签名"}]},
    {"id":"graphics","name":"计算机图形学","subdomains":[{"id":"transform-2d","name":"2D 变换"}]},
  ],
  facets: [
    {"id":"facet:array","title":"数组","description":"格子紧挨着排 — 知道编号就能一步抵达，可一碰中间，后面就接连挪位","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:linkedListSingly","title":"链表","description":"每个节点只有一根手指指向自己的下一个 — 插入和删除是重接手指，不是搬动卡片","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:stack","title":"栈 (LIFO)","description":"只碰一个位置 — 最后进来的最先出去","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:queueFifo","title":"队列 (FIFO)","description":"传送带 — 等得最久的最先离开的机器","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:hashTableChaining","title":"哈希表","description":"键落进函数选定的一个槽 — 落到同一槽里长出的是链条，不是混乱","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bst","title":"二叉搜索树","description":"一次比较折掉一半世界 — BST 那决定性的一刀","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:avlTree","title":"AVL 树","description":"回溯时测量 — 倾斜一致转一次，折向则转两次。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:redBlackTree","title":"红黑树","description":"重新着色把问题往上推，旋转则就此结束 — 两条规则让树保持低矮。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bTree","title":"B 树","description":"一个位置放多个键，键之间各有岔路 — 分支宽，树就矮。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:trie","title":"字典树","description":"开头相同的词共用一条路径 — 所以一个前缀就能一次全找到。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heapBinary","title":"堆","description":"按树来想，用数组来存 — 最小的总在顶端。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:unionFind","title":"并查集","description":"问两次，第二次几乎免费 — 上爬的同时路被折叠。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:indexAddressCalc","title":"从下标到地址","description":"一次乘法和一次加法，下标就变成地址。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:shiftOnInsert","title":"插在中间，后面都得挪","description":"插入点后面的值，从后往前，真的一个个向右挪一格。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:shiftOnRemove","title":"删除后前移","description":"从中间抽走一个，后面的全都往左拉。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:growAndCopy","title":"扩容并复制","description":"一块空间满了，就在别处取一块更大的，把每个值都复制过去，再把旧的还回去。地址变了。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:outOfBounds","title":"越界访问","description":"越过数组末尾的下标实际指向什么。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:nodePointsNext","title":"节点指向下一个","description":"节点散落在内存各处，却有顺序 — 顺序来自每个节点在值旁边握着的那个地址。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:traverseFromHead","title":"走到第四个节点","description":"要到某个节点，只能从 head 开始一条一条地跟着链接走。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:relinkInsert","title":"重新连接","description":"链表插入改写的是箭头，不是位置。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:lostLink","title":"链接丢失","description":"顺序错了再改指针，后面的一整段就都够不着了。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:pushPopTop","title":"入栈 · 出栈 · 栈顶","description":"只有一个口 — 最后进去的最先出来。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:enqueueDequeueEnds","title":"一头进，另一头出","description":"两道门分处两端，所以先进的先出。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:circularBufferWrap","title":"环形缓冲区: 绕回来","description":"最后一格之后就是第一格。格子不会增加，只是重复使用。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:dequeBothEnds","title":"两端都是开的","description":"双端队列的门不是四扇而是两扇 — 每扇门既进也出。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:hashToBucket","title":"把键折进桶里","description":"哈希函数把任何键折成一个整数，取余再把这个整数折进固定数目的槽位之一。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:chainingBucket","title":"链地址法 — 落到同一格，就挂在那里","description":"第二个键落到已被占用的格子时，什么也不会被挤出去。它挂到那一格垂下的链尾，查找时只沿着那条链走。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:openAddressingProbe","title":"开放定址法 — 探查下一个座位","description":"桶被占了，键就一格一格往旁边挪，直到找到空位。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:loadFactorRehash","title":"装载因子与重新散列","description":"表太满就扩容，每个键都从头重新安放。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:parentTwoChildren","title":"一个位置，两条分枝","description":"一个结点向下最多伸出两个孩子，左和右是不同名的位置，不能对调。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:traversalOrder","title":"遍历顺序","description":"同一棵树走三种顺序。只有踩到自己位置的时刻在移动。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:depthDoublesCount","title":"深一层，位置翻倍","description":"每往下一层，树能容纳的位置就翻一倍。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstCompareAndGo","title":"二叉搜索树：比较后下行","description":"每比较一次，就有整整一枝退出候选，并向下走一层","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstInorderSorted","title":"二叉搜索树的中序遍历是有序的","description":"按中序走 — 先清空左边，放下自己，再过到右边 — 值就从小到大出来","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bstDegenerate","title":"只往一边长，就长成一条线","description":"把同样的六个值按两种顺序插入，看一棵树变成链条，另一棵横向铺开。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heightBalanceCheck","title":"高度平衡检查","description":"平衡因子不是从上往下看出来的，而是从叶子一层层带上来的。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:rotateToBalance","title":"为平衡而旋转","description":"一次旋转就能把倾斜的树扶正。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:recolorThenRotate","title":"先重涂，再旋转","description":"同样的违规发生两次 — 旁边那个的颜色决定重涂就够，还是必须旋转","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:blackHeightEqual","title":"黑高处处相等","description":"从根到 nil 走四条不同的路 — 黑色的个数总落在同一个数上","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:nodeHoldsMany","title":"一个节点装多个键","description":"一个节点装着好几个键。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:splitWhenFull","title":"满了就分裂","description":"满了的节点一溢出，中间的键就升到父节点，剩下的一分为二","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heightStaysLow","title":"高度保持在低位","description":"两棵树覆盖同样的一百万片叶子 — 分叉更宽的那棵用少得多的层数就结束","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:sharePrefixPath","title":"共享前缀","description":"开头相同的词会走同一条路，直到字母分岔","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:walkPerCharacter","title":"沿着字典树，一次一个字符","description":"从不整词比较 — 每个字符选定一条分支，分支不在就到此为止。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:heapProperty","title":"堆性质","description":"父节点总在子节点之前 — 但兄弟之间毫无顺序可言","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:siftUp","title":"上浮调整","description":"先放到最后一个位置，再往上爬到属于自己的位置。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:siftDown","title":"下沉调整","description":"最后一个值填上空出的顶端，再一格一格往下走到合适的位置。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:arrayAsTree","title":"用数组表示树","description":"一个数组如何充当一棵树 — 不存链接，只用下标运算。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:adjacencyListVsMatrix","title":"邻接表与邻接矩阵","description":"同样的边，落进不断变长的表，也落进早已备好的方格","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:findRoot","title":"找到根","description":"每个位置都指向上方，指向自己的那个位置就是这一组的名字。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:unionByRank","title":"按秩合并","description":"把矮的接到高的下面，高度不变；只有一样高时才会长一层。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:pathCompression","title":"路径压缩","description":"爬到根的代价，回报的不只是你问的那个节点，而是路上的每一个节点。","domain":"cs-fundamentals","subdomain":"data-structures"},
    {"id":"facet:bloomFilter","title":"布隆过滤器","description":"用很少的位置就能确定地说\"没有\"。推动两个手柄，看一个如何移动另一个的最佳值。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:countMinSketch","title":"Count-Min Sketch","description":"用远少于键数的格子数出\"看过几次\"。宽度降低碰撞的频率，深度降低碰撞的代价。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:hyperloglog","title":"HyperLogLog","description":"不保存任何元素也能数出有多少不同的东西 — 推动桶数，看误差如何变小。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:tDigest","title":"用很少的位置回答分位数，但把尾部答准","description":"提高压缩系数 δ，尾部误差比中间下降得快得多 —— 这就是把刻度挤向尾部换来的东西。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:skipList","title":"随机代替了维持平衡的工作","description":"没有人管理形状，查找的步数却按 log n 增长。拨动手柄看看。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:severalHashesOneValue","title":"一个值，多个哈希","description":"向布隆过滤器插入值：一个值分成三条哈希分支，点亮位数组中的三个位置。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:wrongInOneDirection","title":"只会朝一个方向出错","description":"布隆过滤器可能对没放进去的东西回答\"有\"，但绝不会对放进去的东西回答\"没有\"。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:cannotUnset","title":"无法删除","description":"在布隆过滤器中删除一个值时，共用同一格的其他值也会一并消失。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:trustTheSmallest","title":"相信最小值","description":"Count-Min Sketch 从三行中读数并取最小值作为答案。共享的格子只会让计数变大，不会变小。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:leadingZerosTell","title":"前导零告诉你有多少","description":"看到罕见的前导零，说明你已经见过很多 — 不保存任何元素也能估计不同元素的个数。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:averageTheBuckets","title":"分桶测量再平均","description":"一个离群值就能把估计整个带偏。分成四个桶后，这个跳变只困在其中一个里。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:crowdTheTails","title":"把刻度挤向尾部","description":"分位摘要把更多的桶分给尾部，而不是中间。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:skipALayer","title":"在多层链表中查找","description":"在上层远跳，一旦跳过头就下降一层，逐步收窄。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:coinFlipHeight","title":"是什么决定了塔的高度","description":"一次抛硬币决定每座塔的高度，各层自然减半。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:spaceErrorTradeoff","title":"Count-Min Sketch 该开多大","description":"省下的空间要用误差偿还：表越窄，读出的值越膨胀。","domain":"cs-fundamentals","subdomain":"probabilistic-structures"},
    {"id":"facet:bubbleSort","title":"冒泡排序","description":"相邻比较与交换的浪，每一趟把最大值推到末尾","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:selectionSort","title":"选择排序","description":"把剩下的全扫一遍找出最小的，然后只挪动一次","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:insertionSort","title":"插入排序","description":"拿起一个值，让更大的往旁边让，再把它放进去 — 输入若已排好，它几乎不用干活。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:mergeSort","title":"归并排序","description":"一直拆到单个元素，再只看两边最前端，一路合并回去。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:quickSort","title":"快速排序","description":"选一个基准，把左右分开 — 分一次，这个基准的位置就此定下","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:heapSort","title":"堆排序","description":"把这一行变成大顶堆，然后不断把堆顶挪到末尾 — 不需要额外数组。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:countingSort","title":"计数排序","description":"从不比较两个值 — 先数，再累加，然后各就各位。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:radixSort","title":"基数排序","description":"每次只看一位数来排队 — 从不比较两个值。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:shellSort","title":"希尔排序","description":"迈大步的插入排序 — 先清掉远处的错乱，最后一趟就没剩多少活。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:linearSearch","title":"线性查找","description":"从头一个一个看 — 没有顺序可依靠时，这是说「不在这里」的唯一诚实办法。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:binarySearch","title":"二分查找","description":"看中间，扔掉一半 — 要回答「不在这里」，区间必须走到空。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:interpolationSearch","title":"插值查找","description":"不再对半切分，而是按值的大小瞄准 — 与二分查找只差一行。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:dynamicProgramming","title":"动态规划","description":"只填一次表 — 每个格子只看上一行的两个格子。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:greedy","title":"贪心","description":"总是选最早结束的那个 — 而它恰好就是最优。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:backtracking","title":"回溯法","description":"棋盘走不通就把皇后收回，试下一列 — 后退是方法，不是失败。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:branchAndBound","title":"分支限界法","description":"同一个背包，不用表 — 分出枝杈，量一量这条枝最多能到多少，砍掉赢不了的。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:compareAndSwap","title":"比较与交换","description":"比较是判断，交换只是判断为真时才随之发生的结果。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:sortStability","title":"排序的稳定性","description":"有相同的值时，正确的排序结果不止一种。只有保留输入顺序的那一种才叫稳定。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:inPlaceVsExtra","title":"原地排序","description":"两种排序到达同样的顺序，只有一种要额外的空间。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bubbleAdjacentSwap","title":"相邻交换","description":"只把相邻的两个比一遍，从左扫到右，当前最大的就一格一格被带到最右端。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:selectMinEachPass","title":"选择最小值","description":"扫描时只有标记在动，值只在一轮结束后挪动一次","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:insertIntoSortedPart","title":"插入到已排序的部分","description":"把新值从队列中提起来，后面的值依次让位，它落进空出的位置。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:splitUntilOne","title":"分割","description":"把区间一再对半分开，变的只有分组的边界。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:mergeTwoSorted","title":"归并","description":"两条有序的行合成一条 — 只看两个队首。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:partitionAroundPivot","title":"划分","description":"每个值都与同一个基准相比，然后越到一侧。基准本身留在线上。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:pivotChoiceMatters","title":"基准值的选择","description":"把同一组已排好的值切两次：取中间值可把工作量减半，取第一个值只减少一个。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:heapSortExtract","title":"堆的取出","description":"取走顶端后堆的最后一格空出来，结果就落在那一格","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:countThenPlace","title":"计数排序的放置","description":"把每个值先数一遍，位置就都提前定下了 — 从不拿两个值互相比较。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:digitByDigit","title":"逐位排序","description":"从最低位起，一次只看一位 — 整排却排好了序。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:gapShrink","title":"间隔缩小","description":"先清掉相隔较远的乱序，最后一轮相邻比较要做的事就少了。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:scanUntilFound","title":"线性查找","description":"同一道目光两次扫过同一行 — 一次中途停下，一次冲出末端。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:halveTheRange","title":"区间对半分","description":"一次比较，恰好这么多候选就没了。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:requiresSorted","title":"有序这个前提","description":"同样的七个值排成两行，跑同一个二分查找 — 一行有序，一行无序。无序那行会对明明就在那里的值答「找不到」。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:guessByValue","title":"插值猜测","description":"值分布均匀时，值本身就会告诉你该看哪里。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:divideConquerCombine","title":"分治","description":"一路向下切分，再一路向上带回答案 — 同样的地方，顺序相反","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:overlappingSubproblems","title":"重叠子问题","description":"照搬递归定义，同一项就会在不同分支上一再冒出来","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:memoWriteOnce","title":"记忆化","description":"解出的项写进表里；再遇到它就从表中读值，而不再往下分叉。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bottomUpTable","title":"自底向上填表","description":"从小的一端开始填表，递归就干脆不存在了","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:takeBestNow","title":"贪心选择","description":"一条规则，取一枚，绝不回头 — 还装得下的最大硬币落下，余额随之变小","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:greedyCanFail","title":"贪心失效的时候","description":"两行用同样的硬币凑出同样的金额。先拿最大面额的那行反而用得更多。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:tryAndUndo","title":"回溯法","description":"为什么撤回一步是流程的一半，而不是失败后的收拾。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:pruneBranch","title":"剪枝","description":"整棵子树跳过，为什么不会漏掉答案。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:boundAndCut","title":"界限剪枝","description":"一个分支即使发挥到最好也超不过当前最优，就在展开之前剪掉。","domain":"cs-fundamentals","subdomain":"algorithms"},
    {"id":"facet:bfs","title":"广度优先搜索 (BFS)","description":"同心的波前 — 同距离的顶点在一次闪光中同时被发现","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:dfs","title":"深度优先搜索","description":"沿一条分支走到底，再退回来走下一条。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:dijkstra","title":"迪杰斯特拉算法","description":"在未确定的顶点中选最近的一个定下来，再松弛它的邻居。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:bellmanFord","title":"贝尔曼-福特","description":"把每条边扫 n-1 遍 — 每一轮距离都多渗进一层。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:floydWarshall","title":"弗洛伊德–沃舍尔","description":"所有点对的最短路径 — 每次只换一个中间顶点。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:primMst","title":"Prim 算法","description":"只养一棵树 — 每次都接上从树里伸出的最轻的边。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:kruskalMst","title":"Kruskal — 从最轻的边开始","description":"把边按权重排好，从上往下取，两端已在同一组的边就丢掉。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:topologicalSort","title":"拓扑排序","description":"先取没有箭头指进来的 — 每取走一个，下一个就松开了。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:scc","title":"强连通分量","description":"一次深度优先遍历，就能找出所有彼此可达的顶点集合。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:maxFlow","title":"最大流","description":"找一条还有余量的路，按瓶颈的量灌进去，直到再也找不到路。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:oneWayEdge","title":"有向边","description":"同一条线，一旦带上箭头，回头的路就没了。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:fewerHopsNotShorter","title":"经过的边少不等于路更短","description":"连接同一对顶点的两条路。经过边数少的那条，权重反而更大。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:queueVsStackOrder","title":"容器决定顺序","description":"同一张图，同样的邻居顺序 — 只换容器，访问顺序就分道。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:diveThenBacktrack","title":"一头扎下去，再原路退回","description":"深度优先的走法，退回来花的步数和扎进去一样多。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:markVisitedOrLoop","title":"标记已访问","description":"不给走过的地方留标记，遍历就会永远绕着同样的三个位置转","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:separateComponents","title":"互不相连的分块","description":"一次搜索走不出自己所在的分块 — 其余的要重新出发才会亮","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:twoColorConflict","title":"两种颜色在奇数环上撞车","description":"绕着五个顶点的环交替涂两种颜色，看最后一条边如何失败。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:relaxShorterPath","title":"松弛","description":"一旦出现更短的路，就擦掉写好的距离，改写成更小的数。它从不回升。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:pickNearestUnsettled","title":"先把最近的钉死","description":"还在晃动的当中，背着最小数的那个已经降无可降 — 于是它凝住，此后什么都撼不动它。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:negativeEdgeBreaks","title":"负权边破坏“确定”","description":"先确定最近的做法，遇到负权边就会留下错误的数。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:repeatRelaxAll","title":"一轮又一轮，扫过每一条边","description":"一轮为什么不够 — 每轮信息只往前推进一个顶点。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:oneMoreRoundDrops","title":"再走一轮，又降下去","description":"走完 n−1 轮后距离仍在下降，说明图里有负权环。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:throughMiddleNode","title":"经过中间会更短吗","description":"最短路径表对每一对顶点反复追问的同一个问题。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:heuristicGuides","title":"一个估计引导搜索","description":"加上对剩余距离的估计，搜索就会偏向目标。找到的路一样，打开的格子数不一样。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:growOneTree","title":"只养一棵树","description":"普里姆算法只在已经接到树上的边中挑选。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:sortEdgesAvoidCycle","title":"按权重排边，成环就丢弃","description":"从最轻的边开始取，两端已在同一组的边就丢掉。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:indegreeZeroFirst","title":"先取没有入边的","description":"只有没有入箭的顶点才能取走。取走后它挂着的箭随之落下，谁归零谁就接着落。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:cycleBlocksOrder","title":"有环就排不出顺序","description":"困在环里的顶点互相等待，最后什么也取不出来","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:mutuallyReachable","title":"能互相到达的一群","description":"只能单向到达还不算一群 — 能来能回才是一群。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:bottleneckSetsFlow","title":"最窄的管子决定流量","description":"一条路径能通过多少，由它最窄的那根管子决定。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:undoByBackEdge","title":"用反向边撤回","description":"流过多少，就能推回多少 — 卡住的流量正是靠这个松开。","domain":"cs-fundamentals","subdomain":"graph-algorithms"},
    {"id":"facet:kmp","title":"KMP","description":"逐位右移会丢弃已经匹配的全部内容。KMP 只保留模式与自身重叠的那一部分。推动手柄，看差距如何拉开。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:boyerMoore","title":"Boyer-Moore","description":"从末尾开始比较，一次失配就能换来跨越多格，跨多远由那个失配的字符决定。模式越长，一次跳得越远。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:rabinKarp","title":"模式变长，触碰的字符却不变","description":"把模式加长，滚动哈希触碰的字符数纹丝不动，而单纯比较却变成三倍。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:suffixArray","title":"后缀数组","description":"把后缀排好序一次，任何模式都能用二分查找找到 —— 所有出现位置都聚在一段里。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:zAlgorithm","title":"Z 算法","description":"只要把每个位置与开头重叠多少算出一次，字符串查找就从那张表里掉出来；而制表本身从不重看同一个字符。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:ahoCorasick","title":"Aho-Corasick 算法","description":"再加模式，文本仍然只读一次。推动手柄，看一个数字纹丝不动。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:editDistance","title":"编辑距离","description":"把表填满会得到一个数字，而倒着回溯这张表会得到真正的修改清单——你把什么定得贵，清单就会跟着变。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:naiveShiftByOne","title":"把模式串逐位右移","description":"从头逐字比较；一旦不匹配，就丢弃已经匹配的部分，把模式串右移一位。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:prefixSuffixJump","title":"前缀与后缀的重叠","description":"模式把自己折叠起来，找到与自身重叠的位置，错开时只滑动重叠的那么多。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:matchFromBack","title":"从末尾开始比较","description":"从模式的最后一个字符开始比较，无需读取前面就能整体排除一个位置。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:badCharSkip","title":"不匹配的字符决定跳过多远","description":"模式中没有的字符与任何一格都不可能匹配，所以模式一次就越过那个字符。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:rollingHash","title":"滚动哈希","description":"窗口每移一格，减去前面的字母、加上后面的字母，哈希就滚到下一个值。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:allSuffixesSorted","title":"把所有后缀排好序","description":"把一个字符串的所有后缀排好序，开头相同的就会挨在一起。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:matchLengthPerSpot","title":"每个位置的匹配长度","description":"若落在已确认的区间内，就不再逐字比较，而从镜像位置借来答案。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:manyPatternsOnePass","title":"多个模式，一次扫描","description":"把四个模式叠成一棵树，只遍历一次文本就能全部捕到。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:failLink","title":"失配时退回到哪里","description":"失配时不回到开头，而是滑到重叠处。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:editTableFill","title":"填满编辑表","description":"表中每格是两个前缀之间的编辑距离，由已经填好的三个相邻格算出。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:threeEditChoices","title":"决定一个格子的三条路","description":"编辑距离表中的一个格子取三个提议中最便宜的那个——上方的删除、左方的插入、对角线的替换或保持。","domain":"cs-fundamentals","subdomain":"string-algorithms"},
    {"id":"facet:euclidean","title":"欧几里得算法","description":"把大数换成余数不断缩小，就会到达最大公约数。推动手柄，看看最费步数的那些数对。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:fastPower","title":"快速幂","description":"不逐个相乘，而是不断平方去到达幂。拨动指数，简单的一边爆炸式增长，快的一边几乎不动。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:sieve","title":"埃拉托斯特尼筛法","description":"划掉倍数，剩下的就是素数 — 推动上限，看划掉者纹丝不动。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:primality","title":"素数判定","description":"只除到平方根就能定下答案 — 而这能省下多少，只有在素数上才看得出来。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:matrixMul","title":"矩阵乘法 — 每层少做一次乘法","description":"一层用一次乘法换来几次加法。差距恰好是一 —— 而递归让这个一爆炸式增长。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:squareAndHalve","title":"快速幂 — 把一行对折","description":"把 3 乘十三次要十二次乘法。换个办法：把十三格的一行对折，成对的两格相遇成为平方，每次对折剩下的那一格送进答案。六次乘法就能到达同一个数，而送进答案的格子恰好是 13 的二进制 1101 中为 1 的位。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:divisorPairsSqrt","title":"约数成对","description":"约数总是成对出现，每一对中较小的那个都不超过平方根。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:rowTimesColumn","title":"行乘列","description":"乘积的一格从何而来 — A 的一行与 B 的一列在同一处咬合。","domain":"cs-fundamentals","subdomain":"numerical-algorithms"},
    {"id":"facet:bigO","title":"Big-O 表示法","description":"n 变大时，四个项互换位次：起初居首的常数落到最后，最终留下来的名字只有 n³。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:asymptotic","title":"渐近分析","description":"同一增长等级的两个函数，比值始终固定不变；等级不同，比值就会无止境地拉开。拨动输入规模，看看哪个比值一直停在 2。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:pNp","title":"P 与 NP","description":"验证一个答案和找出一个答案不是同一件事 — 推动规模，看两种代价如何分开。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:growthOutpaces","title":"最大的项吞掉其余","description":"把 n² + 10n + 100 拆成一根条的三份:n 变大时,n² 吞掉其余两项。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:constantFades","title":"为什么略去常数","description":"常数只会推迟两种增长率相遇的位置，并不会改变最终谁胜出。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:curvesCross","title":"曲线交叉之处","description":"只要输入还小，较慢的算法确实更快 — 直到某个大小让领先者互换。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:verifyVsFind","title":"验证与搜索","description":"要找出和为目标的子集必须看遍所有候选，而检验别人给出的一个候选只需看一次。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:reduceToKnown","title":"化归为已知的问题","description":"考试排期搬进图着色 — 科目变成顶点，冲突变成边，节次变成颜色。","domain":"cs-fundamentals","subdomain":"complexity"},
    {"id":"facet:conditionalStatement","title":"if / else if / else","description":"流走到岔路口，自上而下逐个判断条件，在第一个为真处只点亮一条分支，然后重新汇成一条线","domain":"programming-fundamentals","subdomain":"control-flow"},
    {"id":"facet:twosComplement","title":"二进制补码 — 同一位串，两个数","description":"同一串位可以读成两个不同的数。读成哪个由约定决定，而位宽也是约定的一部分。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:floatingPoint","title":"浮点数 — 给指数还是给尾数","description":"八位中除去符号位，其余七位由指数与尾数瓜分：给指数用来够得更远的每一位，都是从精细度里拿走的。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitwiseOps","title":"位运算 — 八个位各自独立","description":"同样的两个字节，六种规则。每一位独自应用一行规则，只有移位让位之间发生关系。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:integerOverflow","title":"溢出 — 增长的数列超出容器的地方","description":"在哪里溢出由容器大小决定。溢出的那一刻，值不是错得很多，而是变得毫无意义。而且没有人会提醒你。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:positionalValue","title":"位值与进制","description":"同一个数，用另一种进制来写。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:negateAndAddOne","title":"取反加一得负数","description":"翻转每一位再加一就得到负数，进位说明了原因。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:signedWraparound","title":"数的两端","description":"在 8 位有符号运算里，最大的数之后就是最小的数 — 它是环，不是直线","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:silentTruncation","title":"被悄悄截断的高位","description":"超出容器的值会丢掉高位，而且没有任何提示。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:mantissaAndExponent","title":"尾数与指数","description":"32 个比特分成三段，三段共同组装出一个数。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:unrepresentableFraction","title":"永不终止的小数","description":"0.1 在二进制中无法整除。乘以 2 逐位取出后，四位的图样会无休止地重复。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:unevenFloatGaps","title":"不均匀的刻度","description":"越往右，相邻两个数之间的距离就翻一倍。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitMask","title":"位掩码","description":"掩码是一块打了孔的盖子——只有孔下面的位能透过来，其余的都被 0 盖住。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:bitShift","title":"位移","description":"把比特移动一格，数值就翻倍或减半。越过边界的比特会消失。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:byteOrder","title":"字节序","description":"同一个值以相反的顺序放入内存，以及用错误的顺序读取时会变成什么。","domain":"computer-architecture","subdomain":"number-representation"},
    {"id":"facet:cacheLine","title":"缓存行 — 移动的是整行，不是一个字节","description":"加宽缓存行，顺序读取每一档都在变好，而跳跃读取在行宽到能被落入两次之前纹丝不动。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:directMappedCache","title":"直接映射缓存 — 只有一个位置，然后是悬崖","description":"地址决定行放在哪里，所以只有一个地方要找。放得进缓存时几乎全部命中；只要多出一行，未命中就像跌落悬崖。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:setAssociativeCache","title":"组相联缓存 — 同样八个格子，不同分组","description":"格子始终是八个。把分组放宽，原本互相挤走的地址就并排坐下，但只到某一点为止。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:cacheReplacement","title":"缓存替换策略 — 同样十一次访问，答案却不同","description":"四个槽位，十一次访问。只改替换规则，缺失次数就分成三种。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:writePolicy","title":"写策略 — 修改何时写回下层","description":"十次修改，两种策略：下层看到的写入是十次还是五次。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:lineFill","title":"只要一格，整行一起上来","description":"缓存以固定大小的行为单位搬运。碰到一个元素，同一行的另外三个邻居也会跟着上来。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:temporalLocality","title":"时间局部性","description":"刚读过的马上又读 — 所以它留在上层。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:spatialLocality","title":"空间局部性","description":"一行上来之后，接下来的三个不再花代价。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:indexAndTag","title":"索引与标记","description":"把地址切成三段：索引挑选行，标记留在行里证明它属于谁，偏移指出行内的第几个字节。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:conflictMiss","title":"冲突失效","description":"明明有空位，却被挤出去","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:associativityRelief","title":"组相联 — 一个位置能放多个就少被挤出","description":"同样的四个块，换一种分组。每个位置放一个就互相挤出，放两个就并排坐下。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:latencyLadder","title":"延迟阶梯","description":"每往下一层，代价就贵上几十倍。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:writeBackVsThrough","title":"立刻写下去，还是先攒着","description":"同样的七次写入，write-through 要写七次内存，write-back 只写四次。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:falseSharing","title":"伪共享","description":"两个核心改的是不同的值，但同一条缓存行同时装着它们，于是每次写入都会作废对方的副本。","domain":"computer-architecture","subdomain":"cache-hierarchy"},
    {"id":"facet:fiveStagePipeline","title":"五级流水线","description":"把每条指令分成五级，前一条尚未离开时就让下一条进入。单条指令仍需 5 个周期，多条指令则更早完成。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:dataHazard","title":"数据冒险","description":"后面的指令读取前面指令尚未写回的值。不等待很快但读到旧值；等待正确但损失周期；转发找回大部分；最后一个气泡只能靠重排指令填补。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:controlHazard","title":"控制冒险","description":"猜测“不跳转”并继续取指，每次分支跳转都要丢弃判定前取入的指令。判定越晚，丢弃的尾巴越长。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:outOfOrderExecution","title":"乱序执行","description":"窗口变宽后，后面的指令会超前开始，填满等待加载的空周期——但提交仍按程序顺序。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:stageOverlap","title":"阶段重叠","description":"前一条指令还没完成，下一条就已进入：每个周期所有指令前进一级，空出的 IF 接纳下一条指令。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:throughputNotLatency","title":"变快的是吞吐量","description":"两台机器并排执行同样的五条指令。每条指令在里面都要待五个周期，只有最后一条出来的时刻不同。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:readBeforeWrite","title":"尚未产生的值","description":"后面的指令为什么必须等待前面的指令?","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:operandForwarding","title":"数据前递","description":"I1 在 EX 得出的结果，在写回寄存器堆之前就直接送到 I2 的 EX。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:pipelineBubble","title":"流水线气泡","description":"加载指令紧接着的指令要用它的值时，转发也来不及。流水线停顿一个周期，空出的槽像指令一样流过 EX、MEM、WB，后面的指令都晚一个周期完成。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:branchFlush","title":"丢弃猜错放入的指令","description":"猜错分支方向时，流水线会清空事先填入的指令。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:dualIssue","title":"一拍发两条","description":"每拍可发射两条指令的顺序执行机器，只有当第二条不读第一条的结果时，才把两条一起发出。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:readyFirst","title":"就绪者先行","description":"乱序执行先运行已就绪的指令，但仍按程序顺序提交结果。","domain":"computer-architecture","subdomain":"instruction-pipeline"},
    {"id":"facet:staticPrediction","title":"静态分支预测","description":"只凭方向猜测分支时，观察损失的周期移向何处：总是不跳转会猜错所有循环回跳，总是跳转会猜错罕见检查的前跳，而“向后就跳转”两者都能猜对。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:saturatingCounter","title":"饱和计数器","description":"只错一次就改变主意的分支预测器，每次退出循环都会错两次。它应该坚持多久？调整计数器位数，观察指针如何越过阈值。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:branchHistoryTable","title":"分支历史表","description":"用分支最近几次的结果来选择 2 位计数器：重复的模式在历史足够长时不再猜错，随机分支始终超不过一半。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:mispredictionPenalty","title":"猜错一次的代价","description":"每次猜错分支，都要丢掉它后面取来的周期。流水线越晚得知结果，每次堆得越高。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:backwardTaken","title":"向后跳就是循环","description":"在结果出来之前只看方向来猜分支的静态规则——向后跳就跳转，向前跳就不跳转。循环每重复一次都向后跳，所以这条规则几乎总是猜对。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:oneBitDoubleFault","title":"一位预测器的两次失误","description":"只记得上一次结果的预测器在循环退出时猜错，记忆随之翻转，下一次进入循环时又猜错。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:fourStateHysteresis","title":"四格之间一步一挪","description":"2 位计数器不会因为错一次就改变预测。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:patternFromHistory","title":"最近几次指向下一次","description":"最近两次结果指向表中的一格，预测就取自那一格。格子填满后，交替的规律就记在表里，不再猜错。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:unpredictableBranch","title":"无法预测的分支","description":"分支结果若像抛硬币，任何预测器的命中率都会落在一半附近。","domain":"computer-architecture","subdomain":"branch-prediction"},
    {"id":"facet:structAlignment","title":"结构体对齐","description":"同样的五个字段可以占 16 字节，也可以占 32 字节：对齐越严格，字段被推得越开、空隙越大；按从大到小排列，空隙全部消失。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:arrayTraversalOrder","title":"数组遍历顺序","description":"同样的和，换一种顺序缓存未命中就多出四倍——但只在行数超过缓存时。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:prefetching","title":"预取","description":"提前调入要用的行，等待就消失了；调得太早，它会在使用前就被挤出缓存。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:simd","title":"SIMD","description":"一次加法同时推进多个通道——但除不尽剩下的尾部仍要一个一个地加。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:paddingGap","title":"对齐与填充","description":"每个字段都会滑到自身对齐值的倍数位置，跳过的字节留作空隙。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:fieldOrderSize","title":"顺序改变大小","description":"同样的四个字段按从大到小重新排列，空隙被填上，结构体变小。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:rowVsColumnWalk","title":"行优先与列优先遍历","description":"同一个数组按行求和、按列求和：和相同，缓存未命中却不同。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:strideAndMiss","title":"跳跃的步长","description":"缓存行总是整行调入，但只有读到的元素被使用。步长越长，调入的行越多，丢弃的部分也越多。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:fetchAhead","title":"提前取数","description":"按顺序读取元素时，一开始读当前行就请求下一行，光标到达之前那一行已经到了。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:lanesInStep","title":"并排的通道","description":"一条 SIMD 指令一次推进 a + b 的四个通道，同一拍里标量一侧只加一个元素。","domain":"computer-architecture","subdomain":"data-layout"},
    {"id":"facet:contextSwitching","title":"上下文切换 — 一个舞台, 两位主人","description":"唯一的 CPU 舞台上主人交替 — 一个流的寄存器束被抬进自己的保管处，另一个的被放回同样的位置，时间各自从停下的地方重新开始","domain":"operating-systems","subdomain":"process-thread"},
    {"id":"facet:ipRouting","title":"IP 路由","description":"数据包在路由器之间逐跳前进 — 每台只看自己的表，挑出最长前缀匹配的下一跳，每跳 TTL 减一","domain":"networks","subdomain":"network-routing"},
    {"id":"facet:relationalTablesAndKeys","title":"表与键","description":"两张有名字的格子 — 一边的主键锁定每一行的身份，另一边的外键指向那个被锁定的值，把两者绑成一个一致的结构","domain":"databases","subdomain":"relational"},
    {"id":"facet:tokenization","title":"词法切分 (词法分析)","description":"自左向右的目光把同类字符熔进一个区段，直到再也伸不长时闭合，然后把这个闭合的段落作为带类别标签的词元卡片落到输出行","domain":"compilers","subdomain":"lexical"},
    {"id":"facet:linearRegression","title":"线性回归 — 穿过点群的一条直线","description":"让 (w, b) 顺坡下滑来拟合直线 — 残差方块缩小，点也就滚进了谷底","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:logisticRegression","title":"逻辑回归 — 学出概率，选定一条线","description":"权重是学出来的，阈值是选出来的。调高它，误报变少，漏报变多。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:knn","title":"k 近邻 — 要问多少个？","description":"它不学习；每次提问都重新扫一遍数据。移动 k，整条边界都会变。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:decisionTree","title":"决策树 — 提问该在何时停下","description":"每个节点都试遍所有切法，留下混杂最少的那一刀，再对两边继续追问 — 抬高深度上限，看看收益在哪里耗尽。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:randomForest","title":"随机森林 — 多种几棵树能多出什么","description":"一棵树在哪里都是 100% 笃定。森林还会告诉你它有多笃定。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:svm","title":"支持向量机 — 当一个点掉进缝里","description":"合页损失与次梯度下降，由 C 决定最宽的缝可以吞下多少错误","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:residualDistance","title":"残差","description":"点离直线有多远 — 沿 y 方向直着量。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:leastSquares","title":"最小二乘","description":"带符号的偏差为什么不能直接相加，平方又修好了什么。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:squashToProbability","title":"把分数压成概率","description":"无尽的轴，被折进 0 与 1 之间的窄带里。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:decisionBoundary","title":"决策边界 — 最后才出现的那条线","description":"先给每个位置一个概率，越过一半的地方才是边界","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:voteByNeighbors","title":"近邻投票","description":"最近的五个被一个个叫出来，各自投下一票。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kChangesBoundary","title":"k 如何改变答案","description":"最近的一个说这样，最近的三个说那样。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:splitByQuestion","title":"什么才是好问题","description":"切分线沿着一个轴滑动，始终分不开标签。把它换到另一个轴上，第一个位置就切得干干净净。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:impurityDrops","title":"怎样衡量一次好的划分","description":"混杂程度化为一个数字，每切一刀它就下降。这个数看的是比例，不是个数。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:manyTreesVote","title":"集成投票","description":"五棵树回答同样的五个问题。没有一棵全对，多数决却全对。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:baggingSample","title":"装袋法","description":"有放回地抽样，于是每一袋学到的东西都不一样。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:widestMargin","title":"最大间隔","description":"在能分开两个类别的直线中，让间隔带张得最宽的那条获胜。","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:supportVectorsOnly","title":"决定这条线的只有贴在边上的点","description":"十个点里，有几个决定了这条线？","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kernelLifts","title":"核技巧 — 抬到一条直线就够为止","description":"分不开的，升一个维度就分得开","domain":"ml-foundations","subdomain":"supervised"},
    {"id":"facet:kmeans","title":"k-均值 — 在不知道中心的情况下找出群","description":"同样的 k，起点不同答案就不同 — 而且最紧凑的答案并不是人眼看到的那一群。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:hierarchical","title":"层次聚类 — 两个群之间的距离该怎么算","description":"单连接、全连接与平均连接从同样的八个点长出三棵不同的树，同一个切割高度也给出三种不同的答案","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:dbscan","title":"DBSCAN — 两个旋钮拨的是不同的东西","description":"eps 把原本分开的连起来，minPts 把小团打散。同样的组数，可能来自完全不同的两个取值。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:pca","title":"PCA — 最宽的方向取决于坐标轴的单位","description":"幂迭代找出主轴；把两个轴标准化，主轴就转了 42 度","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:tsne","title":"t-SNE — 摊平后的图能告诉你什么，不能告诉你什么","description":"困惑度决定了群会被打碎、被模糊，还是干净分开 — 而即便分得干净，群与群之间的距离也留不下来","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:assignThenMove","title":"先归属，再移动","description":"每个点抓住最近的中心，每个中心滑向抓住它的那些点的中间。两者轮流，直到无人再动。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:kMustBeGiven","title":"簇数只能由人给定","description":"同样的十二个点分出三种结果，量了离散度也挑不出哪一种。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:mergeNearestPair","title":"不先定好数目，能不能聚类","description":"把最近的两个合并，并把接点挂在这段距离的高度上。长出来的那棵树，说的就是它们原本相隔多远。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:dendrogramCut","title":"切分树状图","description":"在树的哪个高度切开，决定了你得到几个簇。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:denseNeighborhood","title":"蔓延所及即为一群","description":"邻居的邻居也归入同一群，所以群不必是圆的。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:noiseLeftOut","title":"噪声点","description":"不属于任何一群的点，方法怎么处理。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:directionOfMostSpread","title":"散布最广的方向","description":"让一根轴穿过点云旋转，在投影散得最开处停下。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:projectAndLose","title":"投影与丢失","description":"少了一个维度，会消失什么。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:keepNeighborsClose","title":"让近的保持近","description":"环上十个点展成一条线：九对邻居的间距保住了，一对被撕开。","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:globalAndLocal","title":"全局与局部 — 两种展平并排看","description":"看起来一样宽的簇间距，未必真的一样","domain":"ml-foundations","subdomain":"unsupervised"},
    {"id":"facet:subwordSegmentation","title":"子词切分 — 词表越大，同一句话被切得越少","description":"把合并次数调大，散落的字母就会互相滑拢合为一体 — 同一句话从 33 块变成 7 块","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:bpeTraining","title":"BPE 训练 — 什么常见，就决定先合并什么","description":"调一个词的频率，配对就会争夺名次互换位置，合并顺序被重排，最终得到不同的词表","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:vocabulary","title":"词表 — 装了什么，决定了它能把什么切得好","description":"同一套 BPE 在三份语料上训练，同样的六个词被切成不同的样子 — biology 与 code 的总数同为 32，切得好的词却正好相反","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:betweenLetterAndWord","title":"字母与单词之间","description":"同一个句子切成三种大小 — 片段落在字母与单词之间。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:mergeTheFrequentPair","title":"合并最常相邻的一对","description":"最常相邻的一对合成一个片段，同一道接缝在整个语料里同时合上。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:unknownBecomesKnown","title":"接住陌生的词","description":"词表从未见过的词被切成两个见过的碎片，然后以这些碎片拼写着通过。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:spaceIsPartOfIt","title":"空格也是一个字符","description":"把空格写成一个字符后，这个标记就会粘在片段上随之移动，同一个单词因而在词表中占据两个位置。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:tokensPerLanguage","title":"每种语言的词元数不同","description":"同样意思的句子，在不同语言里被切成的片段数相差数倍。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:boundaryShift","title":"一个字母之差","description":"改动一个字母，词元边界就塌了：原本完整的词裂成三块。","domain":"ai-engineering","subdomain":"text-tokenization"},
    {"id":"facet:vectorSimilarity","title":"向量相似度","description":"用什么来量，决定了谁算相近。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:exhaustiveSearch","title":"穷举搜索","description":"候选始终是 64，但提高维度后，需要遍历的量会膨胀到填满整块板。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:hnsw","title":"HNSW — 层够多，从哪出发都能到","description":"转动层数。只有一层时六条路径中仅一条到达真正最近邻；三层时六条全都到达，而看过的点不减反增。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:invertedFileIndex","title":"倒排文件索引","description":"打开多少分区，同时决定了准确度与速度。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:productQuantization","title":"乘积量化","description":"把向量切成若干段，每段只保留一个编号。切得越细，误差越小，占用越多。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:angleNotLength","title":"比的是角度，不是长度","description":"余弦相似度比较的是方向：角度决定排名，长度被排除在外，因此可能与欧氏距离相反。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:compareWithAll","title":"与全部比较","description":"精确，但数量一大就撑不住 — 乘法按候选数乘以维度不断堆积。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:neighborsLinkedAhead","title":"预先连好邻居","description":"路若已经铺好，就不必逐一度量，走过去便能找到答案。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:coarseThenFine","title":"先在稀疏层大步走，再到下层细找","description":"在点很少的顶层用大步跳跃定下位置，下面的层继承这个位置并进一步收窄。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:probeAFewCells","title":"只打开少数单元","description":"查询只与最近几个单元内的点比较，未打开单元中的点从不触及。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:splitAndNumber","title":"切分后编号","description":"把向量切成两段，每段只留下最接近的代表编号。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:recallSpeedTradeoff","title":"搜得越少，漏得越多","description":"真正最近的五个是固定的。少搜几个格子，其中一些就会从答案中滑出，由更远的点占据它们的座位。","domain":"ai-engineering","subdomain":"vector-search"},
    {"id":"facet:whereToCut","title":"在哪里切分","description":"按固定词数切分文本，切口会落在句子中间。按段落结尾切分，块数相同，每个句子都保持完整。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:overlapTheSeam","title":"在接缝处重叠切分","description":"下一个窗口从接缝处后退几个词再开始，被切口卡住的句子便完整落入一个分块。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:sameWordVsSameMeaning","title":"同样的词与同样的意思","description":"关键词检索(BM25)与语义检索(余弦)把同样的五篇文档排成不同的顺序。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:fuseTwoRankings","title":"合并两个排名","description":"每个列表只按名次给文档一份分数，分数叠起来后排出新的顺序。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:lookCloselyAtFew","title":"只细看少数几个","description":"八个候选中只有前四个越过门槛，逐一与查询对照，然后这四个之间调换位置。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:budgetRunsOut","title":"预算用完了","description":"指令、问题和回答空间先占好位置，片段按排名填充剩余空间，直到有一个放不下为止。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:lostInTheMiddle","title":"迷失在中间","description":"同一个答案片段从上下文的开头移到正中间，再移到末尾。模型往往注意到两端，却容易漏掉夹在中间的内容。","domain":"ai-engineering","subdomain":"retrieval-augmentation"},
    {"id":"facet:alwaysTheHighest","title":"永远只选第一","description":"贪心解码每次都选概率最高的下一个词元——于是句子沿着自己走过的路又走了一遍。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:flattenOrSharpen","title":"温度：变平还是变尖","description":"在 softmax 之前把 logit 除以温度，概率会向第一名集中或向其余候选分散——顺序从不改变。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:cutTheTail","title":"top-k：先剪掉尾部，再抽取","description":"top-k 丢掉排名 k 以下的候选，把它们的份额按大小比例分给剩下的候选，只在剩下的里面抽取。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:fillToAShare","title":"装满到一定份额","description":"top-p 按概率从高到低加入候选，直到份额达到 p——尖锐的语境两个就停，平坦的语境要七个。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:carrySeveralLines","title":"同时带着几条句子走","description":"束搜索如何抓住贪心解码错过的句子：每条保留的句子都分出分支，所有分支按对数概率之和排序，只留下前几条。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:penalizeRepeats","title":"重复惩罚","description":"已经写过的候选词被削减 logit——正值除以 θ，负值乘以 θ——原来的第一名沉到新候选之下。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:eraseTheImpossible","title":"先删去不可能的候选","description":"语法约束解码:在选择之前,语法删去它禁止的候选,其份额由其余候选分摊。对数几率为示例值。","domain":"ai-engineering","subdomain":"decoding"},
    {"id":"facet:dontRecountThePast","title":"不必重算过去","description":"再生成一个词元，需要前面每个位置的 K 和 V。没有缓存时每一步都把它们全部重算；有 KV 缓存时只计算最新的位置，其余原地保留。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:cacheKeepsGrowing","title":"缓存不断增长","description":"文本变长时，KV 缓存会变得多大？","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:shortWaitsForLong","title":"短请求等待长请求","description":"把长度不同的请求放进同一批运行时,先结束的请求会怎样?","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:refillTheEmptySlot","title":"空位立刻补上","description":"一个请求完成、空出位置后，队列中的下一个请求在紧接着的下一步就进入该位置。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:draftThenVerify","title":"先起草，再验证","description":"小模型先写出四个词元，大模型只调用一次就一并检查，从前往后保留相符的部分。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:firstTokenVsRest","title":"第一次与之后","description":"第一步时整个提示一次性通过 K·V 计算，之后只有刚生成的那个词元进入。","domain":"ai-engineering","subdomain":"inference-efficiency"},
    {"id":"facet:lruCache","title":"LRU 缓存","description":"容量固定的键值存储 — 每次触碰都把节点拖到 MRU 端，溢出时 LRU 端消失","domain":"system-design","subdomain":"caching"},
    {"id":"facet:cachingCdn","title":"CDN","description":"遍布全球的边缘缓存承接就近的客户端 — 手上有的答案很快返回，没有的则上溯层级取回并顺手填满边缘","domain":"system-design","subdomain":"caching"},
    {"id":"facet:messagingPubsub","title":"Pub/Sub 消息传递","description":"发布者与订阅者只认识 broker 的主题而不认识彼此的多对多异步消息 — 一次发布以副本形式扇出给所有订阅者","domain":"system-design","subdomain":"messaging"},
    {"id":"facet:asymmetricRsa","title":"RSA — 公钥密码","description":"由两个素数所生的一对非对称密钥 — 一把只能锁，另一把才能开，用上锁的那把绝不能还原","domain":"security","subdomain":"asymmetric"},
    {"id":"facet:hashFixedLength","title":"定长输出","description":"输入从空到整个文件，输出始终一样大","domain":"security","subdomain":"hash"},
    {"id":"facet:hashAvalanche","title":"雪崩效应","description":"只改一个字符，哈希输出就有近一半被翻转","domain":"security","subdomain":"hash"},
    {"id":"facet:pigeonholeCollision","title":"鸽巢原理","description":"十六个位置，十七个输入 — 总有一个没有自己的位置","domain":"security","subdomain":"hash"},
    {"id":"facet:hashIntegrityCheck","title":"完整性校验","description":"公开的一行哈希，就能告诉你收到的副本是否被动过","domain":"security","subdomain":"hash"},
    {"id":"facet:hashSalt","title":"盐","description":"每个账号一份不同的盐，让相同的密码不会被存成相同的值","domain":"security","subdomain":"hash"},
    {"id":"facet:hashChain","title":"哈希链","description":"每一格都带着前一格的哈希，改动一处，其后全都对不上","domain":"security","subdomain":"hash"},
    {"id":"facet:merkleTree","title":"默克尔树","description":"把哈希两两折叠，一片叶子变了，也只有它到顶的那条路会动","domain":"security","subdomain":"hash"},
    {"id":"facet:signatureKeyDirection","title":"密钥的方向","description":"加密与签名用同一对密钥，方向相反","domain":"security","subdomain":"signature"},
    {"id":"facet:signatureOnHash","title":"对摘要签名","description":"不论文档多大，签名始终是 64 字节","domain":"security","subdomain":"signature"},
    {"id":"facet:matrixTransform2d","title":"2D 矩阵变换 — 两列即两个基的落点","description":"2×2 矩阵就是 i-hat 与 j-hat 的落点 — 平面上每个点都以同样的 (u, v) 系数进入新基的组合，直线仍是直线，原点留在原处","domain":"graphics","subdomain":"transform-2d"},
  ],
};
