/**
 * svd 선언 — 그림 넷(6 × 7, 0..9 정수)과 손잡이 둘(그림 · 남길 겹). 코드 패널은 두지 않는다 (irs.ts).
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const svdFacet: FacetJson = {
  id: 'facet:svd',
  title: {
    en: 'SVD and low-rank approximation',
    ko: 'SVD 와 저랭크 근사',
    ja: 'SVD と低ランク近似',
    zh: 'SVD 与低秩近似',
    ar: 'SVD والتقريب منخفض الرتبة',
    es: 'SVD y aproximación de rango bajo',
    fr: 'SVD et approximation de rang faible',
    hi: 'SVD और निम्न-रैंक सन्निकटन',
    id: 'SVD dan aproksimasi peringkat rendah',
    pt: 'SVD e aproximação de posto baixo',
  },
  description: {
    en: 'Split a 6 × 7 table of numbers into layers in singular-value order and stack them from the largest. For each picture, watch the six σ and how the error % and matching cells move as layers are added.',
    ko: '6 × 7 수의 표를 특이값 순서의 겹으로 나누어 큰 겹부터 쌓는다. 그림마다 σ 여섯과, 겹을 더할 때 오차 % 와 같은 칸이 어떻게 옮겨 가는지 본다.',
    ja: '6 × 7 の数の表を特異値の順の層に分け、大きい層から積む。絵ごとに σ 6 つと、層を足すにつれて誤差 % と一致するマスがどう動くかを見る。',
    zh: '把 6 × 7 的数表按奇异值顺序分成若干层，从最大的一层开始叠加。对每幅图案，观察六个 σ，以及每加一层时误差 % 和相同格如何变化。',
    ar: 'قسّم جدول أرقام 6 × 7 إلى طبقات بترتيب القيم المفردة وكدّسها بدءًا من الأكبر. لكل صورة، راقب قيم σ الست وكيف تتحرك نسبة الخطأ والخانات المطابقة مع إضافة الطبقات.',
    es: 'Divide una tabla de números de 6 × 7 en capas por orden de valor singular y apílalas desde la mayor. Para cada imagen, observa los seis σ y cómo cambian el error % y las celdas iguales al añadir capas.',
    fr: 'Découpe une table de nombres 6 × 7 en couches dans l’ordre des valeurs singulières et empile-les de la plus grande. Pour chaque image, observe les six σ et comment l’erreur % et les cases identiques bougent à chaque couche ajoutée.',
    hi: '6 × 7 संख्याओं की तालिका को विलक्षण मानों के क्रम में परतों में बाँटकर सबसे बड़ी परत से जमा करें। हर चित्र के लिए छह σ देखें और परत जोड़ने पर त्रुटि % और मेल खाते खाने कैसे बदलते हैं।',
    id: 'Bagi tabel angka 6 × 7 menjadi lapisan menurut urutan nilai singular lalu tumpuk dari yang terbesar. Untuk tiap gambar, lihat enam σ dan bagaimana galat % serta sel sama bergerak saat lapisan ditambah.',
    pt: 'Divida uma tabela de números 6 × 7 em camadas na ordem dos valores singulares e empilhe a partir da maior. Para cada imagem, veja os seis σ e como o erro % e as células iguais mudam a cada camada somada.',
  },
  algorithm: 'module:svd',
  projector: 'module:svdProjector',
  initialData: {
    type: 'svd',
    stepMs: 1400,
    motionMs: 600,
    pictures: [
      { id: 'heart', cells: [[0, 3, 3, 0, 3, 2, 0], [3, 9, 9, 3, 9, 9, 2], [3, 9, 9, 9, 9, 9, 3], [1, 6, 9, 9, 9, 7, 1], [0, 1, 6, 9, 6, 2, 0], [0, 0, 1, 6, 1, 0, 0]] },
      { id: 'plus', cells: [[0, 0, 6, 0, 0, 0, 0], [8, 8, 9, 8, 8, 8, 8], [0, 0, 6, 0, 0, 0, 0], [0, 0, 6, 0, 0, 0, 0], [0, 0, 6, 0, 0, 0, 0], [0, 0, 6, 0, 0, 0, 0]] },
      { id: 'stairs', cells: [[9, 0, 0, 0, 0, 0, 0], [9, 9, 0, 0, 0, 0, 0], [9, 9, 9, 0, 0, 0, 0], [9, 9, 9, 9, 0, 0, 0], [9, 9, 9, 9, 9, 0, 0], [9, 9, 9, 9, 9, 9, 0]] },
      { id: 'scatter', cells: [[7, 1, 4, 0, 8, 2, 5], [0, 6, 2, 9, 1, 7, 3], [5, 3, 8, 1, 6, 0, 9], [2, 9, 0, 7, 3, 5, 1], [8, 0, 6, 2, 9, 4, 0], [1, 7, 3, 5, 0, 8, 6]] },
    ],
    pictureLadder: [0, 1, 2, 3],
    picture: 0,
    keepLadder: [1, 2, 3, 4, 5, 6],
    keep: 4,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'svd-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'picture',
          name: 'picture',
          label: { en: 'Picture', ko: '그림', ja: '絵', zh: '图案', ar: 'الصورة', es: 'Imagen', fr: 'Image', hi: 'चित्र', id: 'Gambar', pt: 'Imagem' },
          segments: [
            { value: 0, label: { en: 'Heart', ko: '하트', ja: 'ハート', zh: '心形', ar: 'قلب', es: 'Corazón', fr: 'Cœur', hi: 'दिल', id: 'Hati', pt: 'Coração' }, default: true },
            { value: 1, label: { en: 'Plus', ko: '십자', ja: '十字', zh: '十字', ar: 'صليب', es: 'Cruz', fr: 'Croix', hi: 'क्रॉस', id: 'Silang', pt: 'Cruz' } },
            { value: 2, label: { en: 'Stairs', ko: '계단', ja: '階段', zh: '阶梯', ar: 'درج', es: 'Escalera', fr: 'Escalier', hi: 'सीढ़ी', id: 'Tangga', pt: 'Escada' } },
            { value: 3, label: { en: 'Scatter', ko: '흩어짐', ja: '散らばり', zh: '散点', ar: 'تبعثر', es: 'Dispersión', fr: 'Dispersion', hi: 'बिखराव', id: 'Sebaran', pt: 'Dispersão' } },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'keep',
          name: 'keep',
          label: { en: 'Layers kept', ko: '남길 겹', ja: '残す層', zh: '保留层数', ar: 'الطبقات المبقاة', es: 'Capas guardadas', fr: 'Couches gardées', hi: 'रखी परतें', id: 'Lapisan disimpan', pt: 'Camadas mantidas' },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3' },
            { value: 4, label: '4', default: true },
            { value: 5, label: '5' },
            { value: 6, label: '6' },
          ],
        },
      ],
      metrics: [
        {
          name: 'layers',
          label: { en: 'Layers stacked', ko: '쌓은 겹', ja: '積んだ層', zh: '已叠层数', ar: 'الطبقات المكدسة', es: 'Capas apiladas', fr: 'Couches empilées', hi: 'जमा परतें', id: 'Lapisan ditumpuk', pt: 'Camadas empilhadas' },
          initial: 0,
        },
        {
          name: 'same-cells',
          label: { en: 'Matching cells', ko: '같은 칸', ja: '一致するマス', zh: '相同格', ar: 'خانات مطابقة', es: 'Celdas iguales', fr: 'Cases identiques', hi: 'मेल खाते खाने', id: 'Sel sama', pt: 'Células iguais' },
          initial: 0,
        },
      ],
    },
  },
  messages: {
    'label.picture.heart': { en: 'Heart', ko: '하트', ja: 'ハート', zh: '心形', ar: 'قلب', es: 'Corazón', fr: 'Cœur', hi: 'दिल', id: 'Hati', pt: 'Coração' },
    'label.picture.plus': { en: 'Plus', ko: '십자', ja: '十字', zh: '十字', ar: 'صليب', es: 'Cruz', fr: 'Croix', hi: 'क्रॉस', id: 'Silang', pt: 'Cruz' },
    'label.picture.stairs': { en: 'Stairs', ko: '계단', ja: '階段', zh: '阶梯', ar: 'درج', es: 'Escalera', fr: 'Escalier', hi: 'सीढ़ी', id: 'Tangga', pt: 'Escada' },
    'label.picture.scatter': { en: 'Scatter', ko: '흩어짐', ja: '散らばり', zh: '散点', ar: 'تبعثر', es: 'Dispersión', fr: 'Dispersion', hi: 'बिखराव', id: 'Sebaran', pt: 'Dispersão' },
    'label.original': { en: 'Original table', ko: '원래 표', ja: '元の表', zh: '原始表', ar: 'الجدول الأصلي', es: 'Tabla original', fr: 'Table d’origine', hi: 'मूल तालिका', id: 'Tabel asli', pt: 'Tabela original' },
    'label.stacked': { en: 'Stacked table', ko: '쌓은 표', ja: '積んだ表', zh: '叠加表', ar: 'الجدول المتراكم', es: 'Tabla apilada', fr: 'Table empilée', hi: 'जमा तालिका', id: 'Tabel tumpukan', pt: 'Tabela empilhada' },
    'label.left': { en: 'Layers left', ko: '남은 겹', ja: '残りの層', zh: '剩余层', ar: 'الطبقات المتبقية', es: 'Capas restantes', fr: 'Couches restantes', hi: 'बची परतें', id: 'Lapisan tersisa', pt: 'Camadas restantes' },
    'label.done': { en: 'Layers stacked', ko: '쌓은 겹', ja: '積んだ層', zh: '已叠层', ar: 'الطبقات المكدسة', es: 'Capas apiladas', fr: 'Couches empilées', hi: 'जमा परतें', id: 'Lapisan tertumpuk', pt: 'Camadas empilhadas' },
    'label.keep': { en: 'To stack: {k}', ko: '쌓을 몫: {k}', ja: '積む層: {k}', zh: '要叠: {k}', ar: 'للتكديس: {k}', es: 'Por apilar: {k}', fr: 'À empiler : {k}', hi: 'जमा करनी: {k}', id: 'Akan ditumpuk: {k}', pt: 'A empilhar: {k}' },
    'caption.start': {
      en: 'Start — original table {name} · six σ bars · the stacked table is an empty grid',
      ko: '처음 — 원래 표 {name} · σ 막대 여섯 · 쌓은 표는 빈 칸 틀',
      ja: '最初 — 元の表 {name} · σ の棒 6 本 · 積んだ表は空のマス枠',
      zh: '开始 — 原始表 {name} · 六根 σ 柱 · 叠加表是空格框',
      ar: 'البداية — الجدول الأصلي {name} · ستة أعمدة σ · الجدول المتراكم شبكة فارغة',
      es: 'Inicio — tabla original {name} · seis barras σ · la tabla apilada es una cuadrícula vacía',
      fr: 'Début — table d’origine {name} · six barres σ · la table empilée est une grille vide',
      hi: 'शुरुआत — मूल तालिका {name} · छह σ पट्टियाँ · जमा तालिका खाली ग्रिड है',
      id: 'Awal — tabel asli {name} · enam batang σ · tabel tumpukan masih kisi kosong',
      pt: 'Início — tabela original {name} · seis barras σ · a tabela empilhada é uma grade vazia',
    },
    'caption.layer': {
      en: 'Layer {j} ({sigmaName} {sigma}) → {stackName}',
      ko: '겹 {j} ({sigmaName} {sigma}) → {stackName}',
      ja: '層 {j} ({sigmaName} {sigma}) → {stackName}',
      zh: '第 {j} 层 ({sigmaName} {sigma}) → {stackName}',
      ar: 'الطبقة {j} ({sigmaName} {sigma}) → {stackName}',
      es: 'Capa {j} ({sigmaName} {sigma}) → {stackName}',
      fr: 'Couche {j} ({sigmaName} {sigma}) → {stackName}',
      hi: 'परत {j} ({sigmaName} {sigma}) → {stackName}',
      id: 'Lapisan {j} ({sigmaName} {sigma}) → {stackName}',
      pt: 'Camada {j} ({sigmaName} {sigma}) → {stackName}',
    },
    'caption.readout': {
      en: 'Error {error} % · Matching cells {same} / 42',
      ko: '오차 {error} % · 같은 칸 {same} / 42',
      ja: '誤差 {error} % · 一致するマス {same} / 42',
      zh: '误差 {error} % · 相同格 {same} / 42',
      ar: 'الخطأ {error} % · الخانات المطابقة {same} / 42',
      es: 'Error {error} % · Celdas iguales {same} / 42',
      fr: 'Erreur {error} % · Cases identiques {same} / 42',
      hi: 'त्रुटि {error} % · मेल खाते खाने {same} / 42',
      id: 'Galat {error} % · Sel sama {same} / 42',
      pt: 'Erro {error} % · Células iguais {same} / 42',
    },
    'caption.end.full': {
      en: 'End — first layer at 42 / 42: {first}',
      ko: '끝 — 42 / 42 첫 겹: {first}',
      ja: '終わり — 42 / 42 に届いた最初の層: {first}',
      zh: '结束 — 首次达到 42 / 42 的层: {first}',
      ar: 'النهاية — أول طبقة تبلغ 42 / 42: {first}',
      es: 'Fin — primera capa con 42 / 42: {first}',
      fr: 'Fin — première couche à 42 / 42 : {first}',
      hi: 'अंत — 42 / 42 तक पहुँची पहली परत: {first}',
      id: 'Selesai — lapisan pertama yang mencapai 42 / 42: {first}',
      pt: 'Fim — primeira camada com 42 / 42: {first}',
    },
    'caption.end.none': {
      en: 'End — no layer reached 42 / 42 by layer {k}',
      ko: '끝 — 겹 {k} 까지 42 / 42 없음',
      ja: '終わり — 層 {k} までに 42 / 42 なし',
      zh: '结束 — 到第 {k} 层为止没有 42 / 42',
      ar: 'النهاية — لا طبقة بلغت 42 / 42 حتى الطبقة {k}',
      es: 'Fin — ninguna capa llegó a 42 / 42 hasta la capa {k}',
      fr: 'Fin — aucune couche à 42 / 42 jusqu’à la couche {k}',
      hi: 'अंत — परत {k} तक कोई 42 / 42 नहीं',
      id: 'Selesai — belum ada 42 / 42 sampai lapisan {k}',
      pt: 'Fim — nenhuma camada chegou a 42 / 42 até a camada {k}',
    },
  },
};
