import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 요청이 처리되는 것보다 빨리 들어오면 줄은 어떻게 되는가.
 */
export const arrivalVsServiceFacet: FacetJson = {
  id: 'facet:arrivalVsService',
  title: {
    en: 'Arrivals outpace service',
    ko: '처리보다 빠른 도착',
    ja: '処理より速い到着',
    zh: '到达快于处理',
    ar: 'الوصول أسرع من الخدمة',
    es: 'Llegan más rápido de lo que se atienden',
    fr: 'Les arrivées dépassent le service',
    hi: 'सेवा से तेज़ आगमन',
    id: 'Kedatangan lebih cepat dari layanan',
    pt: 'Chegadas mais rápidas que o atendimento',
  },
  description: {
    en: 'One request arrives every second, but the server finishes one only every two seconds. The line grows and never shrinks.',
    ko: '요청은 1초마다 하나씩 오는데 서버는 2초마다 하나씩만 끝낸다. 줄은 자라기만 하고 줄지 않는다.',
    ja: 'リクエストは1秒ごとに1件届くが、サーバーは2秒ごとに1件しか終えない。列は伸びるだけで縮まない。',
    zh: '请求每秒到达一个，但服务器每两秒才处理完一个。队列只增不减。',
    ar: 'يصل طلب كل ثانية، لكن الخادم لا ينهي إلا طلبًا كل ثانيتين. يطول الطابور ولا يقصر أبدًا.',
    es: 'Llega una solicitud por segundo, pero el servidor termina una solo cada dos segundos. La fila crece y nunca se acorta.',
    fr: 'Une requête arrive chaque seconde, mais le serveur n’en termine qu’une toutes les deux secondes. La file s’allonge sans jamais raccourcir.',
    hi: 'हर सेकंड एक अनुरोध आता है, पर सर्वर हर दो सेकंड में सिर्फ़ एक पूरा करता है। कतार बढ़ती ही जाती है, कभी घटती नहीं।',
    id: 'Satu permintaan datang tiap detik, tetapi server hanya menyelesaikan satu tiap dua detik. Antrean terus memanjang dan tak pernah memendek.',
    pt: 'Chega uma requisição por segundo, mas o servidor só termina uma a cada dois segundos. A fila cresce e nunca diminui.',
  },
  algorithm: 'module:arrivalVsService',
  scene: 'module:arrivalVsServiceScene',
  initialData: {
    type: 'arrival-vs-service',
    stepMs: 1000,
    serviceSec: 2,
    requests: [
      { id: 'r0', arriveAt: 0 },
      { id: 'r1', arriveAt: 1 },
      { id: 'r2', arriveAt: 2 },
      { id: 'r3', arriveAt: 3 },
      { id: 'r4', arriveAt: 4 },
      { id: 'r5', arriveAt: 5 },
      { id: 'r6', arriveAt: 6 },
      { id: 'r7', arriveAt: 7 },
      { id: 'r8', arriveAt: 8 },
      { id: 'r9', arriveAt: 9 },
      { id: 'r10', arriveAt: 10 },
      { id: 'r11', arriveAt: 11 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.time': {
      en: 'Time: {sec} s',
      ko: '시각: {sec}초',
      ja: '時刻: {sec} 秒',
      zh: '时刻：{sec} 秒',
      ar: 'الوقت: {sec} ث',
      es: 'Tiempo: {sec} s',
      fr: 'Temps : {sec} s',
      hi: 'समय: {sec} से.',
      id: 'Waktu: {sec} dtk',
      pt: 'Tempo: {sec} s',
    },
    'caption.left': {
      en: 'Done, left: {id}',
      ko: '처리를 마치고 떠남: {id}',
      ja: '処理を終えて退出: {id}',
      zh: '处理完毕离开：{id}',
      ar: 'انتهى وغادر: {id}',
      es: 'Atendida, sale: {id}',
      fr: 'Traitée, sort : {id}',
      hi: 'पूरा होकर निकला: {id}',
      id: 'Selesai, keluar: {id}',
      pt: 'Atendida, sai: {id}',
    },
    'caption.came': {
      en: 'Joined the tail: {id}',
      ko: '줄 끝에 섬: {id}',
      ja: '列の最後尾に並ぶ: {id}',
      zh: '排到队尾：{id}',
      ar: 'انضم إلى آخر الطابور: {id}',
      es: 'Se pone al final: {id}',
      fr: 'Se place en fin de file : {id}',
      hi: 'कतार के अंत में लगा: {id}',
      id: 'Masuk ke ujung antrean: {id}',
      pt: 'Entra no fim da fila: {id}',
    },
    'caption.started': {
      en: 'Into service: {id}',
      ko: '처리 시작: {id}',
      ja: '処理開始: {id}',
      zh: '开始处理：{id}',
      ar: 'بدأت خدمته: {id}',
      es: 'Empieza a atenderse: {id}',
      fr: 'Pris en charge : {id}',
      hi: 'सेवा शुरू: {id}',
      id: 'Mulai dilayani: {id}',
      pt: 'Começa a ser atendida: {id}',
    },
    'label.in': {
      en: 'In: {n}',
      ko: '들어옴: {n}',
      ja: '到着: {n}',
      zh: '到达：{n}',
      ar: 'الداخل: {n}',
      es: 'Entran: {n}',
      fr: 'Entrées : {n}',
      hi: 'आए: {n}',
      id: 'Masuk: {n}',
      pt: 'Entram: {n}',
    },
    'label.out': {
      en: 'Out: {n}',
      ko: '나감: {n}',
      ja: '退出: {n}',
      zh: '离开：{n}',
      ar: 'الخارج: {n}',
      es: 'Salen: {n}',
      fr: 'Sorties : {n}',
      hi: 'गए: {n}',
      id: 'Keluar: {n}',
      pt: 'Saem: {n}',
    },
    'label.gap': {
      en: 'In − Out: {n}',
      ko: '들어옴 − 나감: {n}',
      ja: '到着 − 退出: {n}',
      zh: '到达 − 离开：{n}',
      ar: 'الداخل − الخارج: {n}',
      es: 'Entran − Salen: {n}',
      fr: 'Entrées − Sorties : {n}',
      hi: 'आए − गए: {n}',
      id: 'Masuk − Keluar: {n}',
      pt: 'Entram − Saem: {n}',
    },
    'label.queue': {
      en: 'Waiting: {n}',
      ko: '줄: {n}',
      ja: '待ち: {n}',
      zh: '等待：{n}',
      ar: 'في الانتظار: {n}',
      es: 'Esperan: {n}',
      fr: 'En attente : {n}',
      hi: 'प्रतीक्षा में: {n}',
      id: 'Menunggu: {n}',
      pt: 'Esperando: {n}',
    },
    'label.server': {
      en: 'Server',
      ko: '서버',
      ja: 'サーバー',
      zh: '服务器',
      ar: 'الخادم',
      es: 'Servidor',
      fr: 'Serveur',
      hi: 'सर्वर',
      id: 'Server',
      pt: 'Servidor',
    },
    'label.done': {
      en: 'Done',
      ko: '처리 끝',
      ja: '処理済み',
      zh: '已处理',
      ar: 'منتهية',
      es: 'Atendidas',
      fr: 'Traitées',
      hi: 'पूरे',
      id: 'Selesai',
      pt: 'Atendidas',
    },
    'axis.count': {
      en: 'Total count',
      ko: '누적 수',
      ja: '累積数',
      zh: '累计数',
      ar: 'العدد التراكمي',
      es: 'Total acumulado',
      fr: 'Total cumulé',
      hi: 'कुल संख्या',
      id: 'Jumlah kumulatif',
      pt: 'Total acumulado',
    },
    'axis.time': {
      en: 'Time (s)',
      ko: '시각 (초)',
      ja: '時刻 (秒)',
      zh: '时刻 (秒)',
      ar: 'الوقت (ث)',
      es: 'Tiempo (s)',
      fr: 'Temps (s)',
      hi: 'समय (से.)',
      id: 'Waktu (dtk)',
      pt: 'Tempo (s)',
    },
  },
  blocks: {
    stage: { type: 'arrival-vs-service-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
