import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 3차원의 두 벡터 a · b 에 둘 다 수직인 방향은 두 쪽이다 — a × b 는 어느 쪽을 가리키고,
 * 정말 둘 다에 수직인가?
 */
export const crossProductPerpendicularFacet: FacetJson = {
  id: 'facet:crossProductPerpendicular',
  title: {
    en: 'Cross product: perpendicular to both',
    ko: '외적 — 둘 다에 수직인 방향',
    ja: '外積 — 両方に垂直な向き',
    zh: '叉积——同时垂直于两者的方向',
    ar: 'الضرب الاتجاهي: عمودي على كليهما',
    es: 'Producto vectorial: perpendicular a ambos',
    fr: 'Produit vectoriel : perpendiculaire aux deux',
    hi: 'सदिश गुणनफल: दोनों पर लंबवत',
    id: 'Hasil kali silang: tegak lurus terhadap keduanya',
    pt: 'Produto vetorial: perpendicular aos dois',
  },
  description: {
    en: 'Two vectors in 3D have two directions perpendicular to both. Which one does the cross product take, and is it truly perpendicular to both?',
    ko: '3차원의 두 벡터에 둘 다 수직인 방향은 두 쪽이다. 외적은 어느 쪽을 가리키고, 정말 둘 다에 수직인가?',
    ja: '3次元の2つのベクトルの両方に垂直な向きは2つある。外積はどちらを指し、本当に両方に垂直なのか?',
    zh: '三维空间中同时垂直于两个向量的方向有两个。叉积指向哪一个？它真的同时垂直于两者吗？',
    ar: 'لمتجهين في الفضاء الثلاثي اتجاهان عموديان على كليهما. أيهما يأخذ الضرب الاتجاهي، وهل هو عمودي حقًا على كليهما؟',
    es: 'Dos vectores en 3D tienen dos direcciones perpendiculares a ambos. ¿Cuál toma el producto vectorial, y es de verdad perpendicular a los dos?',
    fr: 'Deux vecteurs de l’espace ont deux directions perpendiculaires aux deux. Laquelle prend le produit vectoriel, et est-il vraiment perpendiculaire aux deux ?',
    hi: '3D में दो सदिशों पर एक साथ लंबवत दो दिशाएँ होती हैं। सदिश गुणनफल किस ओर जाता है, और क्या वह सचमुच दोनों पर लंबवत है?',
    id: 'Dua vektor di ruang 3D punya dua arah yang tegak lurus terhadap keduanya. Arah mana yang diambil hasil kali silang, dan apakah ia sungguh tegak lurus terhadap keduanya?',
    pt: 'Dois vetores em 3D têm duas direções perpendiculares a ambos. Qual delas o produto vetorial toma, e ele é mesmo perpendicular aos dois?',
  },
  algorithm: 'module:crossProductPerpendicular',
  scene: 'module:crossProductPerpendicularScene',
  initialData: {
    type: 'cross-product-perpendicular',
    stepMs: 2000,
    a: { name: 'a', v: [2, 1, 0] },
    b: { name: 'b', v: [1, 2, 2] },
    crossName: 'c',
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'The plane spanned by {a} and {b}',
      ko: '{a}, {b} 두 벡터가 벌린 판',
      ja: '{a}, {b} の2つのベクトルが張る平面',
      zh: '{a}、{b} 两个向量张成的平面',
      ar: 'المستوى الذي يولّده {a} و {b}',
      es: 'El plano que generan {a} y {b}',
      fr: 'Le plan engendré par {a} et {b}',
      hi: '{a} और {b} से बना तल',
      id: 'Bidang yang direntang oleh {a} dan {b}',
      pt: 'O plano gerado por {a} e {b}',
    },
    'caption.cross': {
      en: '{c} = {expr} stands out of the plane',
      ko: '{c} = {expr}, 판을 뚫고 선다',
      ja: '{c} = {expr}、平面を突き抜けて立つ',
      zh: '{c} = {expr}，穿过平面立起',
      ar: '{c} = {expr} يقف خارجًا من المستوى',
      es: '{c} = {expr} se levanta atravesando el plano',
      fr: '{c} = {expr} se dresse à travers le plan',
      hi: '{c} = {expr} तल को भेदकर खड़ा होता है',
      id: '{c} = {expr} berdiri menembus bidang',
      pt: '{c} = {expr} se ergue atravessando o plano',
    },
    'caption.dot': {
      en: 'Dot product {expr}: {value}',
      ko: '내적 {expr}: {value}',
      ja: '内積 {expr}: {value}',
      zh: '点积 {expr}：{value}',
      ar: 'الضرب القياسي {expr}: {value}',
      es: 'Producto escalar {expr}: {value}',
      fr: 'Produit scalaire {expr} : {value}',
      hi: 'अदिश गुणनफल {expr}: {value}',
      id: 'Hasil kali titik {expr}: {value}',
      pt: 'Produto escalar {expr}: {value}',
    },
    'caption.swap': {
      en: 'Order swapped: {expr}',
      ko: '차례를 바꿨다: {expr}',
      ja: '順番を入れ替えた: {expr}',
      zh: '交换顺序：{expr}',
      ar: 'بعد تبديل الترتيب: {expr}',
      es: 'Orden invertido: {expr}',
      fr: 'Ordre inversé : {expr}',
      hi: 'क्रम बदला: {expr}',
      id: 'Urutan ditukar: {expr}',
      pt: 'Ordem trocada: {expr}',
    },
    'label.angle': {
      en: 'Angle ({u}, {v}): {deg}°',
      ko: '사이각 ({u}, {v}): {deg}°',
      ja: 'なす角 ({u}, {v}): {deg}°',
      zh: '夹角 ({u}, {v})：{deg}°',
      ar: 'الزاوية ({u}, {v}): {deg}°',
      es: 'Ángulo ({u}, {v}): {deg}°',
      fr: 'Angle ({u}, {v}) : {deg}°',
      hi: 'कोण ({u}, {v}): {deg}°',
      id: 'Sudut ({u}, {v}): {deg}°',
      pt: 'Ângulo ({u}, {v}): {deg}°',
    },
  },
  blocks: {
    stage: { type: 'cross-product-perpendicular-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
