import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece 잘못 넣은 것 버리기 (control-hazard)
 *
 * 질문: 분기의 갈래를 틀리게 짐작하면 무슨 일이 생기는가?
 *
 * 가져오기는 언제나 "안 탄다" 로 짐작해 다음 주소를 채워 넣는다. 분기가 EX 끝에서
 * "탄다" 로 판정되면 IF · ID 에 미리 채워 둔 두 명령어가 버려지고, 비운 칸이 파이프를
 * 따라 흘러가는 사이 목표 주소의 명령어가 그 자리로 들어온다.
 */
export const branchFlushFacet: FacetJson = {
  id: 'facet:branchFlush',
  title: {
    en: 'Throwing out a wrong guess',
    ko: '잘못 넣은 것 버리기',
    ja: '誤って入れたものを捨てる',
    zh: '丢弃猜错放入的指令',
    ar: 'التخلّص مما أُدخل خطأً',
    es: 'Desechar lo que entró por error',
    fr: 'Jeter ce qui est entré à tort',
    hi: 'ग़लत भरी चीज़ें फेंकना',
    id: 'Membuang yang salah masuk',
    pt: 'Descartar o que entrou por engano',
  },
  description: {
    en: 'Guess a branch wrong, and the pipeline empties what it filled in advance.',
    ko: '분기의 갈래를 틀리게 짐작하면 미리 채운 것을 비운다.',
    ja: '分岐の行き先を読み違えると、先に詰めたものを空にする。',
    zh: '猜错分支方向时，流水线会清空事先填入的指令。',
    ar: 'إذا أخطأ التخمين في اتجاه التفرّع، يُفرِغ خط الأنابيب ما ملأه مسبقًا.',
    es: 'Si se adivina mal el camino de un salto, la segmentación vacía lo que había llenado antes.',
    fr: 'Si l’on devine mal la branche, le pipeline vide ce qu’il avait rempli d’avance.',
    hi: 'शाखा का रास्ता ग़लत अनुमान करें तो पाइपलाइन पहले से भरी चीज़ें खाली कर देती है।',
    id: 'Jika arah cabang ditebak salah, pipeline mengosongkan apa yang sudah diisi lebih dulu.',
    pt: 'Se o caminho do desvio for adivinhado errado, o pipeline esvazia o que tinha preenchido antes.',
  },
  algorithm: 'module:branchFlush',
  scene: 'module:branchFlushScene',
  initialData: {
    type: 'branch-flush',
    stepMs: 800,
    registers: [
      { name: 'r1', value: 4 },
      { name: 'r2', value: 4 },
    ],
    program: [
      { id: 'I1', text: 'beq r1, r2, L' },
      { id: 'I2', text: 'add r3, r4, r5' },
      { id: 'I3', text: 'sub r6, r7, r8' },
      { id: 'I4', text: 'and r12, r13, r14' },
      { id: 'I5', text: 'or r9, r10, r11', label: 'L' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'stage.if': { en: 'IF', ko: 'IF', ja: 'IF', zh: 'IF', ar: 'IF', es: 'IF', fr: 'IF', hi: 'IF', id: 'IF', pt: 'IF' },
    'stage.id': { en: 'ID', ko: 'ID', ja: 'ID', zh: 'ID', ar: 'ID', es: 'ID', fr: 'ID', hi: 'ID', id: 'ID', pt: 'ID' },
    'stage.ex': { en: 'EX', ko: 'EX', ja: 'EX', zh: 'EX', ar: 'EX', es: 'EX', fr: 'EX', hi: 'EX', id: 'EX', pt: 'EX' },
    'stage.mem': { en: 'MEM', ko: 'MEM', ja: 'MEM', zh: 'MEM', ar: 'MEM', es: 'MEM', fr: 'MEM', hi: 'MEM', id: 'MEM', pt: 'MEM' },
    'stage.wb': { en: 'WB', ko: 'WB', ja: 'WB', zh: 'WB', ar: 'WB', es: 'WB', fr: 'WB', hi: 'WB', id: 'WB', pt: 'WB' },
    'label.program': {
      en: 'Program',
      ko: '명령어',
      ja: '命令',
      zh: '指令',
      ar: 'البرنامج',
      es: 'Programa',
      fr: 'Programme',
      hi: 'प्रोग्राम',
      id: 'Program',
      pt: 'Programa',
    },
    'label.registers': {
      en: 'Registers',
      ko: '레지스터',
      ja: 'レジスタ',
      zh: '寄存器',
      ar: 'السجلات',
      es: 'Registros',
      fr: 'Registres',
      hi: 'रजिस्टर',
      id: 'Register',
      pt: 'Registradores',
    },
    'label.cycle': {
      en: 'Cycle {n}',
      ko: '사이클 {n}',
      ja: 'サイクル {n}',
      zh: '周期 {n}',
      ar: 'الدورة {n}',
      es: 'Ciclo {n}',
      fr: 'Cycle {n}',
      hi: 'चक्र {n}',
      id: 'Siklus {n}',
      pt: 'Ciclo {n}',
    },
    'label.empty': {
      en: 'empty',
      ko: '빈 칸',
      ja: '空',
      zh: '空',
      ar: 'فارغ',
      es: 'vacío',
      fr: 'vide',
      hi: 'खाली',
      id: 'kosong',
      pt: 'vazio',
    },
    'label.taken': {
      en: 'taken',
      ko: '탄다',
      ja: '分岐する',
      zh: '跳转',
      ar: 'يتفرّع',
      es: 'salta',
      fr: 'pris',
      hi: 'लेगा',
      id: 'diambil',
      pt: 'desvia',
    },
    'label.notTaken': {
      en: 'not taken',
      ko: '안 탄다',
      ja: '分岐しない',
      zh: '不跳转',
      ar: 'لا يتفرّع',
      es: 'no salta',
      fr: 'pas pris',
      hi: 'नहीं लेगा',
      id: 'tidak diambil',
      pt: 'não desvia',
    },
    'label.compare': {
      en: '{ra} = {a} · {rb} = {b}',
      ko: '{ra} = {a} · {rb} = {b}',
      ja: '{ra} = {a} · {rb} = {b}',
      zh: '{ra} = {a} · {rb} = {b}',
      ar: '{ra} = {a} · {rb} = {b}',
      es: '{ra} = {a} · {rb} = {b}',
      fr: '{ra} = {a} · {rb} = {b}',
      hi: '{ra} = {a} · {rb} = {b}',
      id: '{ra} = {a} · {rb} = {b}',
      pt: '{ra} = {a} · {rb} = {b}',
    },
    'label.discarded': {
      en: 'Thrown out',
      ko: '버린 것',
      ja: '捨てたもの',
      zh: '已丢弃',
      ar: 'ما تم التخلّص منه',
      es: 'Desechado',
      fr: 'Jeté',
      hi: 'फेंका गया',
      id: 'Dibuang',
      pt: 'Descartado',
    },
    'label.written': {
      en: 'written',
      ko: '씀',
      ja: '書いた',
      zh: '已写',
      ar: 'كُتب',
      es: 'escrito',
      fr: 'écrit',
      hi: 'लिखा',
      id: 'ditulis',
      pt: 'escrito',
    },
    'label.kept': {
      en: 'unchanged',
      ko: '그대로',
      ja: '変化なし',
      zh: '未变',
      ar: 'لم يتغيّر',
      es: 'igual',
      fr: 'intact',
      hi: 'वैसा ही',
      id: 'tetap',
      pt: 'igual',
    },
    'caption.init': {
      en: 'The pipeline is empty. The first fetch is {id}.',
      ko: '파이프가 비어 있다. 처음 가져올 것은 {id}.',
      ja: 'パイプラインは空だ。最初に取り込むのは {id}。',
      zh: '流水线是空的。第一个取入的是 {id}。',
      ar: 'خط الأنابيب فارغ. أول ما يُجلب هو {id}.',
      es: 'La segmentación está vacía. Lo primero que se trae es {id}.',
      fr: 'Le pipeline est vide. Le premier chargé sera {id}.',
      hi: 'पाइपलाइन खाली है। सबसे पहले {id} लाया जाएगा।',
      id: 'Pipeline kosong. Yang pertama diambil adalah {id}.',
      pt: 'O pipeline está vazio. O primeiro a ser buscado é {id}.',
    },
    'caption.write': {
      en: 'Cycle {n}: {id} writes {reg}.',
      ko: '사이클 {n}: 레지스터 쓰기 — {id} → {reg}.',
      ja: 'サイクル {n}: {id} が {reg} に書き込む。',
      zh: '周期 {n}：{id} 写入 {reg}。',
      ar: 'الدورة {n}: ‏{id} يكتب في {reg}.',
      es: 'Ciclo {n}: {id} escribe {reg}.',
      fr: 'Cycle {n} : {id} écrit {reg}.',
      hi: 'चक्र {n}: {id}, {reg} में लिखता है।',
      id: 'Siklus {n}: {id} menulis {reg}.',
      pt: 'Ciclo {n}: {id} escreve {reg}.',
    },
    'caption.redirect': {
      en: 'Cycle {n}: {id} comes in from {label}, the path actually taken.',
      ko: '사이클 {n}: 비운 자리로 옳은 갈래가 들어온다 — {label} 의 {id}.',
      ja: 'サイクル {n}: 実際の行き先 {label} から {id} が入ってくる。',
      zh: '周期 {n}：真正的去向 {label} 处的 {id} 进来了。',
      ar: 'الدورة {n}: يدخل {id} من {label}، وهو المسار الفعلي.',
      es: 'Ciclo {n}: entra {id} desde {label}, el camino que sí se tomó.',
      fr: 'Cycle {n} : {id} arrive depuis {label}, la branche réellement prise.',
      hi: 'चक्र {n}: असली रास्ते {label} से {id} अंदर आता है।',
      id: 'Siklus {n}: {id} masuk dari {label}, jalur yang benar-benar diambil.',
      pt: 'Ciclo {n}: {id} entra a partir de {label}, o caminho de fato tomado.',
    },
    'caption.guess': {
      en: 'Cycle {n}: fetch {id}, guessing the branch is not taken.',
      ko: '사이클 {n}: "안 탄다" 로 짐작하고 가져온다 — {id}.',
      ja: 'サイクル {n}: 分岐しないと予測して {id} を取り込む。',
      zh: '周期 {n}：猜分支不跳转，取入 {id}。',
      ar: 'الدورة {n}: جلب {id} بتخمين أن التفرّع لا يحدث.',
      es: 'Ciclo {n}: se trae {id} suponiendo que el salto no se toma.',
      fr: 'Cycle {n} : on charge {id} en pariant que la branche n’est pas prise.',
      hi: 'चक्र {n}: शाखा नहीं लेगी मानकर {id} लाया जाता है।',
      id: 'Siklus {n}: ambil {id}, menebak cabang tidak diambil.',
      pt: 'Ciclo {n}: busca {id}, supondo que o desvio não é tomado.',
    },
    'caption.fetch': {
      en: 'Cycle {n}: fetch {id}.',
      ko: '사이클 {n}: 가져온다 — {id}.',
      ja: 'サイクル {n}: {id} を取り込む。',
      zh: '周期 {n}：取入 {id}。',
      ar: 'الدورة {n}: جلب {id}.',
      es: 'Ciclo {n}: se trae {id}.',
      fr: 'Cycle {n} : on charge {id}.',
      hi: 'चक्र {n}: {id} लाया जाता है।',
      id: 'Siklus {n}: ambil {id}.',
      pt: 'Ciclo {n}: busca {id}.',
    },
    'caption.bubble': {
      en: 'Cycle {n}: the emptied slots move on; nothing is done in them.',
      ko: '사이클 {n}: 비운 칸이 흘러간다. 그 칸에서는 아무 일도 없다.',
      ja: 'サイクル {n}: 空にした枠が流れていく。その枠では何も起きない。',
      zh: '周期 {n}：清空的格子继续前移，里面什么也不做。',
      ar: 'الدورة {n}: تتقدّم الخانات المُفرَغة، ولا يحدث فيها شيء.',
      es: 'Ciclo {n}: las casillas vaciadas avanzan; en ellas no se hace nada.',
      fr: 'Cycle {n} : les cases vidées avancent ; rien ne s’y fait.',
      hi: 'चक्र {n}: खाली किए गए खाने आगे बढ़ते हैं; उनमें कुछ नहीं होता।',
      id: 'Siklus {n}: slot yang dikosongkan bergerak maju; tak ada kerja di dalamnya.',
      pt: 'Ciclo {n}: as casas esvaziadas avançam; nada acontece nelas.',
    },
    'caption.cycle': {
      en: 'Cycle {n}.',
      ko: '사이클 {n}.',
      ja: 'サイクル {n}。',
      zh: '周期 {n}。',
      ar: 'الدورة {n}.',
      es: 'Ciclo {n}.',
      fr: 'Cycle {n}.',
      hi: 'चक्र {n}।',
      id: 'Siklus {n}.',
      pt: 'Ciclo {n}.',
    },
    'caption.taken': {
      en: 'End of cycle {n}: {ra} = {a}, {rb} = {b}. Equal, so the branch is taken. The guess was wrong.',
      ko: '사이클 {n} 끝: {ra} = {a}, {rb} = {b}. 같으니 탄다. 짐작이 틀렸다.',
      ja: 'サイクル {n} の終わり: {ra} = {a}、{rb} = {b}。等しいので分岐する。予測は外れた。',
      zh: '周期 {n} 结束：{ra} = {a}，{rb} = {b}。相等，所以跳转。猜错了。',
      ar: 'نهاية الدورة {n}: ‏{ra} = {a}، {rb} = {b}. متساويان، إذن يتفرّع. كان التخمين خاطئًا.',
      es: 'Fin del ciclo {n}: {ra} = {a}, {rb} = {b}. Son iguales, así que salta. La suposición falló.',
      fr: 'Fin du cycle {n} : {ra} = {a}, {rb} = {b}. Égaux, donc la branche est prise. Le pari était faux.',
      hi: 'चक्र {n} का अंत: {ra} = {a}, {rb} = {b}। बराबर हैं, इसलिए शाखा ली जाती है। अनुमान ग़लत था।',
      id: 'Akhir siklus {n}: {ra} = {a}, {rb} = {b}. Sama, jadi cabang diambil. Tebakannya salah.',
      pt: 'Fim do ciclo {n}: {ra} = {a}, {rb} = {b}. Iguais, então desvia. O palpite errou.',
    },
    'caption.notTaken': {
      en: 'End of cycle {n}: {ra} = {a}, {rb} = {b}. Not equal, so not taken. The guess was right.',
      ko: '사이클 {n} 끝: {ra} = {a}, {rb} = {b}. 다르니 안 탄다. 짐작이 맞았다.',
      ja: 'サイクル {n} の終わり: {ra} = {a}、{rb} = {b}。等しくないので分岐しない。予測は当たった。',
      zh: '周期 {n} 结束：{ra} = {a}，{rb} = {b}。不相等，所以不跳转。猜对了。',
      ar: 'نهاية الدورة {n}: ‏{ra} = {a}، {rb} = {b}. غير متساويين، إذن لا يتفرّع. كان التخمين صحيحًا.',
      es: 'Fin del ciclo {n}: {ra} = {a}, {rb} = {b}. Distintos, así que no salta. La suposición acertó.',
      fr: 'Fin du cycle {n} : {ra} = {a}, {rb} = {b}. Différents, donc pas pris. Le pari était juste.',
      hi: 'चक्र {n} का अंत: {ra} = {a}, {rb} = {b}। बराबर नहीं, इसलिए शाखा नहीं ली जाती। अनुमान सही था।',
      id: 'Akhir siklus {n}: {ra} = {a}, {rb} = {b}. Tidak sama, jadi tidak diambil. Tebakannya benar.',
      pt: 'Fim do ciclo {n}: {ra} = {a}, {rb} = {b}. Diferentes, então não desvia. O palpite acertou.',
    },
    'caption.flush': {
      en: '{ids} thrown out. {stages} are now empty, and the next fetch jumps to {label}.',
      ko: '버린다 — {ids}. 이제 {stages} 는 비었고, 다음 가져오기는 {label} 로 건너뛴다.',
      ja: '{ids} を捨てる。{stages} は空になり、次の取り込みは {label} へ跳ぶ。',
      zh: '丢弃 {ids}。{stages} 现在是空的，下一次取指跳到 {label}。',
      ar: 'تم التخلّص من {ids}. أصبحت {stages} فارغة، والجلب التالي يقفز إلى {label}.',
      es: 'Se desechan {ids}. {stages} quedan vacías y la siguiente búsqueda salta a {label}.',
      fr: '{ids} jetés. {stages} sont maintenant vides, et le prochain chargement saute à {label}.',
      hi: '{ids} फेंक दिए गए। {stages} अब खाली हैं, और अगला लाना {label} पर कूदता है।',
      id: '{ids} dibuang. {stages} kini kosong, dan pengambilan berikutnya melompat ke {label}.',
      pt: '{ids} descartados. {stages} agora estão vazios, e a próxima busca salta para {label}.',
    },
    'caption.done': {
      en: '{id} finished in cycle {finish}. Cycles lost: {lost}. {regs} never changed.',
      ko: '끝난 것은 {id}, 사이클 {finish}. 잃은 사이클은 {lost}. 바뀌지 않은 레지스터: {regs}.',
      ja: '{id} はサイクル {finish} で終わった。失ったサイクル: {lost}。{regs} は変わらなかった。',
      zh: '{id} 在周期 {finish} 完成。损失的周期：{lost}。{regs} 从未改变。',
      ar: 'انتهى {id} في الدورة {finish}. الدورات الضائعة: {lost}. لم يتغيّر {regs}.',
      es: '{id} terminó en el ciclo {finish}. Ciclos perdidos: {lost}. {regs} no cambiaron.',
      fr: '{id} a fini au cycle {finish}. Cycles perdus : {lost}. {regs} n’ont pas changé.',
      hi: '{id} चक्र {finish} में पूरा हुआ। खोए चक्र: {lost}। {regs} नहीं बदले।',
      id: '{id} selesai di siklus {finish}. Siklus yang hilang: {lost}. {regs} tidak berubah.',
      pt: '{id} terminou no ciclo {finish}. Ciclos perdidos: {lost}. {regs} não mudaram.',
    },
    'caption.doneNone': {
      en: '{id} finished in cycle {finish}. Cycles lost: {lost}.',
      ko: '끝난 것은 {id}, 사이클 {finish}. 잃은 사이클은 {lost}.',
      ja: '{id} はサイクル {finish} で終わった。失ったサイクル: {lost}。',
      zh: '{id} 在周期 {finish} 完成。损失的周期：{lost}。',
      ar: 'انتهى {id} في الدورة {finish}. الدورات الضائعة: {lost}.',
      es: '{id} terminó en el ciclo {finish}. Ciclos perdidos: {lost}.',
      fr: '{id} a fini au cycle {finish}. Cycles perdus : {lost}.',
      hi: '{id} चक्र {finish} में पूरा हुआ। खोए चक्र: {lost}।',
      id: '{id} selesai di siklus {finish}. Siklus yang hilang: {lost}.',
      pt: '{id} terminou no ciclo {finish}. Ciclos perdidos: {lost}.',
    },
  },
  blocks: {
    stage: { type: 'branch-flush-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
