import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { ArpData } from './algorithm.js';

/** 주소 · 기호 · 방송 MAC 은 번역하지 않는 자료다. 홉 · 표 줄 · 셈은 알고리즘이 한다 */
const arpInitialData: ArpData = {
  type: 'arp',
  stepMs: 800,
  nodes: [
    { id: 'a', symbol: 'A', ifaces: [{ link: 'l1', mac: '3c:52:82:1a:7e:05', ip: '192.168.1.5' }] },
    { id: 'c', symbol: 'C', ifaces: [{ link: 'l1', mac: '0a:3e:71:5c:22:09', ip: '192.168.1.9' }] },
    {
      id: 'r1',
      symbol: 'R1',
      ifaces: [
        { link: 'l1', mac: '00:1b:21:3a:40:01', ip: '192.168.1.1' },
        { link: 'l2', mac: '00:1b:21:3a:40:02', ip: '10.0.12.1' },
      ],
    },
    {
      id: 'r2',
      symbol: 'R2',
      ifaces: [
        { link: 'l2', mac: 'f0:9f:c2:11:08:0e', ip: '10.0.12.2' },
        { link: 'l3', mac: 'f0:9f:c2:11:08:0f', ip: '172.16.5.1' },
      ],
    },
    { id: 'b', symbol: 'B', ifaces: [{ link: 'l3', mac: 'a4:83:e7:6c:d2:31', ip: '172.16.5.20' }] },
  ],
  prefixLength: 24,
  sender: 'a',
  gateway: '192.168.1.1',
  routes: [
    { node: 'r1', next: '10.0.12.2' },
    { node: 'r2', next: '172.16.5.20' },
  ],
  destinations: ['192.168.1.9', '172.16.5.20'],
  cacheModes: ['off', 'on'],
  sends: 3,
  broadcastMac: 'ff:ff:ff:ff:ff:ff',
  startDest: 1,
  startCache: 0,
};

export const arpFacet: FacetJson = {
  id: 'facet:arp',
  title: {
    en: 'ARP and MAC addresses',
    ko: 'ARP 와 MAC 주소',
    ja: 'ARP と MAC アドレス',
    zh: 'ARP 与 MAC 地址',
    ar: 'ARP وعناوين MAC',
    es: 'ARP y direcciones MAC',
    fr: 'ARP et adresses MAC',
    hi: 'ARP और MAC पते',
    id: 'ARP dan alamat MAC',
    pt: 'ARP e endereços MAC',
  },
  description: {
    en: 'A frame never leaves its own link. To reach another network the sender asks for the first router’s MAC, and every link asks again. Count the broadcasts with and without a cache.',
    ko: '프레임은 제 링크를 벗어나지 못한다. 다른 망으로 보낼 때 보내는 이는 첫 라우터의 MAC 을 묻고, 링크마다 다시 묻는다. 캐시가 있을 때와 없을 때 방송 물음을 센다.',
    ja: 'フレームは自分のリンクから出られない。別のネットワークへ送るとき送信者は最初のルーターの MAC を尋ね、リンクごとにまた尋ねる。キャッシュの有無で ARP ブロードキャストの数を数える。',
    zh: '帧离不开自己的链路。发往另一个网络时，发送者询问第一台路由器的 MAC，每条链路都要重新询问。比较有无缓存时的广播次数。',
    ar: 'لا يغادر الإطار رابطه أبدًا. للوصول إلى شبكة أخرى يسأل المرسل عن MAC أول موجّه، ويُعاد السؤال على كل رابط. عُدّ البثّات مع ذاكرة التخزين وبدونها.',
    es: 'Una trama nunca sale de su enlace. Para llegar a otra red, el emisor pregunta la MAC del primer router, y cada enlace vuelve a preguntar. Cuenta las difusiones con y sin caché.',
    fr: 'Une trame ne quitte jamais son lien. Pour atteindre un autre réseau, l’émetteur demande la MAC du premier routeur, et chaque lien redemande. Comptez les diffusions avec et sans cache.',
    hi: 'फ्रेम अपने लिंक से बाहर नहीं जाता। दूसरे नेटवर्क तक पहुँचने के लिए भेजने वाला पहले राउटर का MAC पूछता है, और हर लिंक फिर पूछता है। कैश के साथ और बिना ब्रॉडकास्ट गिनिए।',
    id: 'Frame tidak pernah keluar dari link-nya. Untuk mencapai jaringan lain, pengirim menanyakan MAC router pertama, dan setiap link bertanya lagi. Hitung siaran dengan dan tanpa cache.',
    pt: 'Um quadro nunca sai do seu enlace. Para chegar a outra rede, o emissor pergunta o MAC do primeiro roteador, e cada enlace pergunta de novo. Conte as difusões com e sem cache.',
  },
  algorithm: 'module:arp',
  projector: 'module:arpProjector',
  initialData: arpInitialData,
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'arp-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'dest',
          name: 'dest',
          label: {
            en: 'Destination',
            ko: '목적지',
            ja: '宛先',
            zh: '目的地',
            ar: 'الوجهة',
            es: 'Destino',
            fr: 'Destination',
            hi: 'गंतव्य',
            id: 'Tujuan',
            pt: 'Destino',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Same network',
                ko: '같은 망',
                ja: '同じネットワーク',
                zh: '同一网络',
                ar: 'الشبكة نفسها',
                es: 'Misma red',
                fr: 'Même réseau',
                hi: 'वही नेटवर्क',
                id: 'Jaringan sama',
                pt: 'Mesma rede',
              },
            },
            {
              value: 1,
              default: true,
              label: {
                en: 'Other network',
                ko: '다른 망',
                ja: '別のネットワーク',
                zh: '其他网络',
                ar: 'شبكة أخرى',
                es: 'Otra red',
                fr: 'Autre réseau',
                hi: 'दूसरा नेटवर्क',
                id: 'Jaringan lain',
                pt: 'Outra rede',
              },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'cache',
          name: 'cache',
          label: {
            en: 'ARP cache',
            ko: 'ARP 캐시',
            ja: 'ARP キャッシュ',
            zh: 'ARP 缓存',
            ar: 'ذاكرة ARP',
            es: 'Caché ARP',
            fr: 'Cache ARP',
            hi: 'ARP कैश',
            id: 'Cache ARP',
            pt: 'Cache ARP',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: {
                en: 'Off',
                ko: '없음',
                ja: 'なし',
                zh: '无',
                ar: 'بدون',
                es: 'No',
                fr: 'Non',
                hi: 'नहीं',
                id: 'Tidak',
                pt: 'Não',
              },
            },
            {
              value: 1,
              label: {
                en: 'On',
                ko: '있음',
                ja: 'あり',
                zh: '有',
                ar: 'مع',
                es: 'Sí',
                fr: 'Oui',
                hi: 'हाँ',
                id: 'Ya',
                pt: 'Sim',
              },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'broadcasts',
          label: {
            en: 'Broadcasts',
            ko: '방송 물음',
            ja: 'ブロードキャスト',
            zh: '广播询问',
            ar: 'البثّات',
            es: 'Difusiones',
            fr: 'Diffusions',
            hi: 'ब्रॉडकास्ट',
            id: 'Siaran',
            pt: 'Difusões',
          },
          initial: 0,
        },
        {
          name: 'from-table',
          label: {
            en: 'From table',
            ko: '표에서',
            ja: '表から',
            zh: '查表',
            ar: 'من الجدول',
            es: 'De la tabla',
            fr: 'De la table',
            hi: 'तालिका से',
            id: 'Dari tabel',
            pt: 'Da tabela',
          },
          initial: 0,
        },
        {
          name: 'mac-pairs',
          label: {
            en: 'MAC pairs',
            ko: 'MAC 쌍',
            ja: 'MAC の組',
            zh: 'MAC 对',
            ar: 'أزواج MAC',
            es: 'Pares MAC',
            fr: 'Paires MAC',
            hi: 'MAC जोड़े',
            id: 'Pasangan MAC',
            pt: 'Pares MAC',
          },
          initial: 0,
        },
        {
          name: 'frames',
          label: {
            en: 'Frames',
            ko: '프레임',
            ja: 'フレーム',
            zh: '帧',
            ar: 'الإطارات',
            es: 'Tramas',
            fr: 'Trames',
            hi: 'फ्रेम',
            id: 'Frame',
            pt: 'Quadros',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:arp-imperative',
      label: {
        en: 'Counting ARP questions',
        ko: 'ARP 물음 세기',
        ja: 'ARP の問い合わせを数える',
        zh: '统计 ARP 询问',
        ar: 'عدّ أسئلة ARP',
        es: 'Contar preguntas ARP',
        fr: 'Compter les requêtes ARP',
        hi: 'ARP प्रश्न गिनना',
        id: 'Menghitung pertanyaan ARP',
        pt: 'Contar perguntas ARP',
      },
    },
  },
  messages: {
    'label.destination': {
      en: 'Destination',
      ko: '목적지',
      ja: '宛先',
      zh: '目的地',
      ar: 'الوجهة',
      es: 'Destino',
      fr: 'Destination',
      hi: 'गंतव्य',
      id: 'Tujuan',
      pt: 'Destino',
    },
    'label.askFor': {
      en: 'Ask for',
      ko: '묻는 IP',
      ja: '尋ねる IP',
      zh: '询问的 IP',
      ar: 'العنوان المسؤول عنه',
      es: 'IP buscada',
      fr: 'IP demandée',
      hi: 'पूछा गया IP',
      id: 'IP yang ditanya',
      pt: 'IP procurado',
    },
    'label.frame': {
      en: 'Data frame',
      ko: '데이터 프레임',
      ja: 'データフレーム',
      zh: '数据帧',
      ar: 'إطار البيانات',
      es: 'Trama de datos',
      fr: 'Trame de données',
      hi: 'डेटा फ्रेम',
      id: 'Frame data',
      pt: 'Quadro de dados',
    },
    'label.mac': {
      en: 'MAC',
      ko: 'MAC',
      ja: 'MAC',
      zh: 'MAC',
      ar: 'MAC',
      es: 'MAC',
      fr: 'MAC',
      hi: 'MAC',
      id: 'MAC',
      pt: 'MAC',
    },
    'label.ip': {
      en: 'IP',
      ko: 'IP',
      ja: 'IP',
      zh: 'IP',
      ar: 'IP',
      es: 'IP',
      fr: 'IP',
      hi: 'IP',
      id: 'IP',
      pt: 'IP',
    },
    'label.link': {
      en: 'Link {n}',
      ko: '링크 {n}',
      ja: 'リンク {n}',
      zh: '链路 {n}',
      ar: 'الرابط {n}',
      es: 'Enlace {n}',
      fr: 'Lien {n}',
      hi: 'लिंक {n}',
      id: 'Link {n}',
      pt: 'Enlace {n}',
    },
    'label.table': {
      en: 'ARP table · {node}',
      ko: 'ARP 표 · {node}',
      ja: 'ARP 表 · {node}',
      zh: 'ARP 表 · {node}',
      ar: 'جدول ARP · {node}',
      es: 'Tabla ARP · {node}',
      fr: 'Table ARP · {node}',
      hi: 'ARP तालिका · {node}',
      id: 'Tabel ARP · {node}',
      pt: 'Tabela ARP · {node}',
    },
    'label.noTable': {
      en: 'no table',
      ko: '표 없음',
      ja: '表なし',
      zh: '无表',
      ar: 'لا جدول',
      es: 'sin tabla',
      fr: 'pas de table',
      hi: 'तालिका नहीं',
      id: 'tanpa tabel',
      pt: 'sem tabela',
    },
    'caption.compare': {
      en: 'Sender {src} · destination {dst}',
      ko: '보내는 이 {src} · 목적지 {dst}',
      ja: '送信者 {src} · 宛先 {dst}',
      zh: '发送者 {src} · 目的地 {dst}',
      ar: 'المرسل {src} · الوجهة {dst}',
      es: 'Emisor {src} · destino {dst}',
      fr: 'Émetteur {src} · destination {dst}',
      hi: 'भेजने वाला {src} · गंतव्य {dst}',
      id: 'Pengirim {src} · tujuan {dst}',
      pt: 'Emissor {src} · destino {dst}',
    },
    'caption.pickSame': {
      en: 'First {n} octets match · ask for: {ip} (the destination)',
      ko: '앞 {n} 옥텟 같음 · 묻는 IP: {ip} (목적지)',
      ja: '先頭 {n} オクテットが一致 · 尋ねる IP: {ip}（宛先）',
      zh: '前 {n} 个八位组相同 · 询问的 IP：{ip}（目的地）',
      ar: 'أول {n} ثمانيات متطابقة · السؤال عن: {ip} (الوجهة)',
      es: 'Los primeros {n} octetos coinciden · se pregunta por: {ip} (el destino)',
      fr: 'Les {n} premiers octets concordent · on demande : {ip} (la destination)',
      hi: 'पहले {n} ऑक्टेट समान · पूछा गया: {ip} (गंतव्य)',
      id: '{n} oktet pertama sama · yang ditanya: {ip} (tujuan)',
      pt: 'Os primeiros {n} octetos coincidem · pergunta-se por: {ip} (o destino)',
    },
    'caption.pickOther': {
      en: 'First {n} octets differ · ask for: {ip} (the gateway)',
      ko: '앞 {n} 옥텟 다름 · 묻는 IP: {ip} (게이트웨이)',
      ja: '先頭 {n} オクテットが異なる · 尋ねる IP: {ip}（ゲートウェイ）',
      zh: '前 {n} 个八位组不同 · 询问的 IP：{ip}（网关）',
      ar: 'أول {n} ثمانيات مختلفة · السؤال عن: {ip} (البوابة)',
      es: 'Los primeros {n} octetos difieren · se pregunta por: {ip} (la puerta de enlace)',
      fr: 'Les {n} premiers octets diffèrent · on demande : {ip} (la passerelle)',
      hi: 'पहले {n} ऑक्टेट अलग · पूछा गया: {ip} (गेटवे)',
      id: '{n} oktet pertama berbeda · yang ditanya: {ip} (gateway)',
      pt: 'Os primeiros {n} octetos diferem · pergunta-se por: {ip} (o gateway)',
    },
    'caption.step': {
      en: 'Send {s} · hop {h} · link {l} · {from} → {to}',
      ko: '{s}번째 보냄 · {h}번째 홉 · 링크 {l} · {from} → {to}',
      ja: '{s} 回目の送信 · {h} 番目のホップ · リンク {l} · {from} → {to}',
      zh: '第 {s} 次发送 · 第 {h} 跳 · 链路 {l} · {from} → {to}',
      ar: 'الإرسال {s} · القفزة {h} · الرابط {l} · {from} → {to}',
      es: 'Envío {s} · salto {h} · enlace {l} · {from} → {to}',
      fr: 'Envoi {s} · saut {h} · lien {l} · {from} → {to}',
      hi: 'भेजना {s} · हॉप {h} · लिंक {l} · {from} → {to}',
      id: 'Kiriman ke-{s} · hop ke-{h} · link {l} · {from} → {to}',
      pt: 'Envio {s} · salto {h} · enlace {l} · {from} → {to}',
    },
    'caption.broadcast': {
      en: 'Broadcast (to {bmac}) · who has {ip}? · heard by: {heard} · reply from: {owner}',
      ko: '방송 (받는 이 {bmac}) · {ip} 주인? · 들은 곳: {heard} · 답: {owner}',
      ja: 'ブロードキャスト（宛先 {bmac}） · {ip} は誰? · 受信: {heard} · 応答: {owner}',
      zh: '广播（发往 {bmac}） · 谁是 {ip}？ · 收到：{heard} · 应答：{owner}',
      ar: 'بثّ (إلى {bmac}) · من يملك {ip}؟ · سمعه: {heard} · الرد من: {owner}',
      es: 'Difusión (a {bmac}) · ¿quién tiene {ip}? · la oyen: {heard} · responde: {owner}',
      fr: 'Diffusion (vers {bmac}) · qui a {ip} ? · entendue par : {heard} · réponse de : {owner}',
      hi: 'ब्रॉडकास्ट ({bmac} पर) · {ip} किसका? · सुना: {heard} · उत्तर: {owner}',
      id: 'Siaran (ke {bmac}) · siapa pemilik {ip}? · didengar: {heard} · jawaban dari: {owner}',
      pt: 'Difusão (para {bmac}) · quem tem {ip}? · ouvida por: {heard} · resposta de: {owner}',
    },
    'caption.wrote': {
      en: 'Written to tables: {nodes}',
      ko: '표에 적음: {nodes}',
      ja: '表に記録: {nodes}',
      zh: '写入表：{nodes}',
      ar: 'كُتب في الجداول: {nodes}',
      es: 'Anotado en las tablas: {nodes}',
      fr: 'Inscrit dans les tables : {nodes}',
      hi: 'तालिकाओं में लिखा: {nodes}',
      id: 'Dicatat di tabel: {nodes}',
      pt: 'Anotado nas tabelas: {nodes}',
    },
    'caption.fromTable': {
      en: 'From the table: {ip} → {mac} · no broadcast',
      ko: '표에서: {ip} → {mac} · 방송 없음',
      ja: '表から: {ip} → {mac} · ブロードキャストなし',
      zh: '查表：{ip} → {mac} · 无广播',
      ar: 'من الجدول: {ip} → {mac} · بلا بثّ',
      es: 'De la tabla: {ip} → {mac} · sin difusión',
      fr: 'De la table : {ip} → {mac} · pas de diffusion',
      hi: 'तालिका से: {ip} → {mac} · कोई ब्रॉडकास्ट नहीं',
      id: 'Dari tabel: {ip} → {mac} · tanpa siaran',
      pt: 'Da tabela: {ip} → {mac} · sem difusão',
    },
    'caption.done': {
      en: 'Done · IP pairs: {ip} · MAC pairs: {mac} · broadcasts: {b}',
      ko: '끝 · IP 쌍: {ip} · MAC 쌍: {mac} · 방송 물음: {b}',
      ja: '完了 · IP の組: {ip} · MAC の組: {mac} · ブロードキャスト: {b}',
      zh: '完成 · IP 对：{ip} · MAC 对：{mac} · 广播询问：{b}',
      ar: 'انتهى · أزواج IP: {ip} · أزواج MAC: {mac} · البثّات: {b}',
      es: 'Fin · pares IP: {ip} · pares MAC: {mac} · difusiones: {b}',
      fr: 'Fin · paires IP : {ip} · paires MAC : {mac} · diffusions : {b}',
      hi: 'समाप्त · IP जोड़े: {ip} · MAC जोड़े: {mac} · ब्रॉडकास्ट: {b}',
      id: 'Selesai · pasangan IP: {ip} · pasangan MAC: {mac} · siaran: {b}',
      pt: 'Fim · pares IP: {ip} · pares MAC: {mac} · difusões: {b}',
    },
  },
};
