import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 중첩된 식 한 줄은 컴파일러 안에서 어떤 줄들이 되는가 — 뜻은 그대로인가.
 *
 * @notation native — 세 주소 코드는 컴파일러 내부 표기이고 그 표기 자체가 주장이다.
 * 원시 한 줄(`let r = (a + b) * (c - d) / 2 + a`)은 식 나무로 두고 화면이 거기서 찍어 낸다.
 * a=3 · b=5 · c=7 · d=4 는 뜻 대조에 쓰는 예로 정한 값이다.
 */
export const lowerToSimplerFacet: FacetJson = {
  id: 'facet:lowerToSimpler',
  title: {
    en: 'Lowering: one operation per line',
    ko: '낮추기 — 한 줄에 연산 하나',
    ja: '低水準化 — 1行に演算1つ',
    zh: '降低 — 每行一个运算',
    ar: 'الخفض — عملية واحدة في كل سطر',
    es: 'Descenso: una operación por línea',
    fr: 'Abaissement : une opération par ligne',
    hi: 'लोअरिंग — हर पंक्ति में एक संक्रिया',
    id: 'Penurunan: satu operasi per baris',
    pt: 'Rebaixamento: uma operação por linha',
  },
  description: {
    en: 'A nested expression is taken apart innermost operation first; each one drops to its own three-address line, and the lines give the same value.',
    ko: '중첩된 식 한 줄에서 가장 먼저 끝나는 연산부터 떼어져 세 주소 줄로 하나씩 내려앉고, 그 줄들은 같은 값을 낸다.',
    ja: '入れ子の式から最初に終わる演算を順に外し、1つずつ三番地コードの行へ降ろす。その行たちは同じ値を出す。',
    zh: '从嵌套的表达式里先取出最先完成的运算，逐个落成三地址码的一行，这些行得出相同的值。',
    ar: 'يُفكّ تعبير متداخل بدءًا بالعملية الداخلية، فتنزل كل عملية إلى سطر ثلاثي العناوين خاص بها، وتعطي الأسطر القيمة نفسها.',
    es: 'Una expresión anidada se desarma empezando por la operación más interna; cada una baja a su propia línea de tres direcciones y las líneas dan el mismo valor.',
    fr: 'Une expression imbriquée est démontée en commençant par l’opération la plus interne ; chacune descend sur sa propre ligne à trois adresses, et les lignes donnent la même valeur.',
    hi: 'गुँथे हुए व्यंजक को सबसे भीतरी संक्रिया से खोला जाता है; हर संक्रिया अपनी त्रि-पता पंक्ति में उतरती है, और पंक्तियाँ वही मान देती हैं।',
    id: 'Ekspresi bersarang dibongkar mulai dari operasi terdalam; masing-masing turun ke baris tiga alamatnya sendiri, dan baris-baris itu memberi nilai yang sama.',
    pt: 'Uma expressão aninhada é desmontada a partir da operação mais interna; cada uma desce para sua própria linha de três endereços, e as linhas dão o mesmo valor.',
  },
  algorithm: 'module:lowerToSimpler',
  scene: 'module:lowerToSimplerScene',
  initialData: {
    type: 'lower-to-simpler',
    stepMs: 1500,
    dst: 'r',
    expr: {
      op: '+',
      l: {
        op: '/',
        l: {
          op: '*',
          l: { op: '+', l: { var: 'a' }, r: { var: 'b' } },
          r: { op: '-', l: { var: 'c' }, r: { var: 'd' } },
        },
        r: { num: 2 },
      },
      r: { var: 'a' },
    },
    env: { a: 3, b: 5, c: 7, d: 4 },
  },
  shuffleOnReset: false,
  messages: {
    'label.source': {
      en: 'Source line',
      ko: '원시 한 줄',
      ja: 'ソースの1行',
      zh: '源代码一行',
      ar: 'سطر المصدر',
      es: 'Línea fuente',
      fr: 'Ligne source',
      hi: 'स्रोत पंक्ति',
      id: 'Baris sumber',
      pt: 'Linha-fonte',
    },
    'label.ir': {
      en: 'Three-address code',
      ko: '세 주소 코드',
      ja: '三番地コード',
      zh: '三地址码',
      ar: 'شيفرة العناوين الثلاثة',
      es: 'Código de tres direcciones',
      fr: 'Code à trois adresses',
      hi: 'त्रि-पता कोड',
      id: 'Kode tiga alamat',
      pt: 'Código de três endereços',
    },
    'caption.start': {
      en: 'One line, operations nested inside: {n}',
      ko: '한 줄 안에 겹쳐 든 연산: {n}',
      ja: '1行の中に入れ子になった演算: {n}',
      zh: '一行里嵌套的运算: {n}',
      ar: 'سطر واحد، العمليات المتداخلة فيه: {n}',
      es: 'Una línea, operaciones anidadas: {n}',
      fr: 'Une ligne, opérations imbriquées : {n}',
      hi: 'एक पंक्ति, भीतर गुँथी संक्रियाएँ: {n}',
      id: 'Satu baris, operasi bersarang di dalamnya: {n}',
      pt: 'Uma linha, operações aninhadas: {n}',
    },
    'caption.peel': {
      en: 'Finishes first, drops to its own line: {expr} · left in its place: {name}',
      ko: '가장 먼저 끝나는 연산이 제 줄로 내려앉음: {expr} · 떼어진 자리에 남은 이름: {name}',
      ja: '最初に終わる演算が自分の行へ降りる: {expr} · 抜けた場所に残る名前: {name}',
      zh: '最先完成的运算落到自己的一行: {expr} · 原处留下的名字: {name}',
      ar: 'العملية التي تنتهي أولًا تنزل إلى سطرها: {expr} · ما يبقى مكانها: {name}',
      es: 'La que termina primero baja a su propia línea: {expr} · queda en su lugar: {name}',
      fr: 'La première à finir descend sur sa propre ligne : {expr} · reste à sa place : {name}',
      hi: 'सबसे पहले पूरी होने वाली संक्रिया अपनी पंक्ति में उतरती है: {expr} · उसकी जगह बचा नाम: {name}',
      id: 'Yang selesai pertama turun ke barisnya sendiri: {expr} · tertinggal di tempatnya: {name}',
      pt: 'A que termina primeiro desce para sua própria linha: {expr} · fica no lugar: {name}',
    },
    'caption.last': {
      en: 'Outermost operation, no temporary — written straight into: {dst}',
      ko: '가장 바깥 연산은 임시 없이 곧장 넣음 — 넣는 이름: {dst}',
      ja: '一番外の演算は一時名なしで直接書き込む — 書き込む名前: {dst}',
      zh: '最外层的运算不经临时名直接写入 — 写入的名字: {dst}',
      ar: 'العملية الخارجية بلا مؤقت — تُكتب مباشرة في: {dst}',
      es: 'Operación más externa, sin temporal — se escribe directo en: {dst}',
      fr: 'Opération la plus externe, sans temporaire — écrite directement dans : {dst}',
      hi: 'सबसे बाहरी संक्रिया, बिना अस्थायी के — सीधे लिखी जाती है: {dst}',
      id: 'Operasi terluar, tanpa sementara — langsung ditulis ke: {dst}',
      pt: 'Operação mais externa, sem temporário — escrita direto em: {dst}',
    },
    'caption.check': {
      en: 'Same inputs — source: {src} · last line: {ir}',
      ko: '같은 값을 넣으면 — 원시 식: {src} · 마지막 줄: {ir}',
      ja: '同じ値を入れると — 元の式: {src} · 最後の行: {ir}',
      zh: '代入相同的值 — 原式: {src} · 最后一行: {ir}',
      ar: 'بالقيم نفسها — المصدر: {src} · السطر الأخير: {ir}',
      es: 'Mismas entradas — fuente: {src} · última línea: {ir}',
      fr: 'Mêmes entrées — source : {src} · dernière ligne : {ir}',
      hi: 'वही मान डालने पर — स्रोत: {src} · अंतिम पंक्ति: {ir}',
      id: 'Masukan sama — sumber: {src} · baris terakhir: {ir}',
      pt: 'Mesmas entradas — fonte: {src} · última linha: {ir}',
    },
    'caption.lines': {
      en: 'Lines: {lines}',
      ko: '줄: {lines}',
      ja: '行: {lines}',
      zh: '行数: {lines}',
      ar: 'الأسطر: {lines}',
      es: 'Líneas: {lines}',
      fr: 'Lignes : {lines}',
      hi: 'पंक्तियाँ: {lines}',
      id: 'Baris: {lines}',
      pt: 'Linhas: {lines}',
    },
    'caption.count': {
      en: 'Lines: {lines} · Operations left in the source: {left}',
      ko: '줄: {lines} · 원시에 남은 연산: {left}',
      ja: '行: {lines} · 元の式に残る演算: {left}',
      zh: '行数: {lines} · 原式中剩下的运算: {left}',
      ar: 'الأسطر: {lines} · العمليات الباقية في المصدر: {left}',
      es: 'Líneas: {lines} · operaciones que quedan en la fuente: {left}',
      fr: 'Lignes : {lines} · opérations restant dans la source : {left}',
      hi: 'पंक्तियाँ: {lines} · स्रोत में बची संक्रियाएँ: {left}',
      id: 'Baris: {lines} · operasi tersisa di sumber: {left}',
      pt: 'Linhas: {lines} · operações restantes na fonte: {left}',
    },
  },
  blocks: {
    stage: { type: 'lower-to-simpler-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
