import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 우선순위가 높은 스레드는 CPU 를 빼앗을 수 있는데, 남이 쥔 자물쇠도 빼앗을 수 있는가.
 */
export const noPreemptionFacet: FacetJson = {
  id: 'facet:noPreemption',
  title: {
    en: 'No preemption',
    ko: '비선점',
    ja: '非プリエンプション',
    zh: '不可抢占',
    ar: 'عدم الاستباق',
    es: 'Sin expropiación',
    fr: 'Pas de préemption',
    hi: 'अ-प्रीएम्प्शन',
    id: 'Tanpa preemption',
    pt: 'Sem preempção',
  },
  description: {
    en: 'A higher-priority thread can take the CPU, but not a lock someone else holds.',
    ko: '우선순위가 높은 스레드는 CPU 는 빼앗아도, 남이 쥔 자물쇠는 빼앗지 못한다.',
    ja: '優先度の高いスレッドは CPU は奪えても、他者が持つロックは奪えない。',
    zh: '高优先级线程能抢走 CPU，却抢不走别人持有的锁。',
    ar: 'الخيط ذو الأولوية الأعلى يستطيع أخذ المعالج، لكنه لا يستطيع أخذ قفل يمسكه غيره.',
    es: 'Un hilo de mayor prioridad puede quitar la CPU, pero no un cerrojo que tiene otro.',
    fr: 'Un thread plus prioritaire peut prendre le CPU, mais pas un verrou tenu par un autre.',
    hi: 'ऊँची प्राथमिकता वाला थ्रेड CPU छीन सकता है, पर किसी और का पकड़ा ताला नहीं।',
    id: 'Thread berprioritas lebih tinggi bisa merebut CPU, tetapi tidak kunci yang dipegang pihak lain.',
    pt: 'Uma thread de maior prioridade pode tomar a CPU, mas não um cadeado que outra segura.',
  },
  algorithm: 'module:noPreemption',
  scene: 'module:noPreemptionScene',
  initialData: {
    type: 'no-preemption',
    stepMs: 1300,
    locks: ['m'],
    threads: [
      {
        id: 'L',
        priority: 1,
        arrive: 0,
        lines: ['lock(m)', 'work()', 'work()', 'work()', 'unlock(m)', 'work()'],
      },
      {
        id: 'H',
        priority: 9,
        arrive: 2,
        lines: ['lock(m)', 'work()', 'unlock(m)'],
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.L': {
      en: 'Low priority',
      ko: '낮은 우선순위',
      ja: '低優先度',
      zh: '低优先级',
      ar: 'أولوية منخفضة',
      es: 'Prioridad baja',
      fr: 'Priorité basse',
      hi: 'निम्न प्राथमिकता',
      id: 'Prioritas rendah',
      pt: 'Prioridade baixa',
    },
    'label.H': {
      en: 'High priority',
      ko: '높은 우선순위',
      ja: '高優先度',
      zh: '高优先级',
      ar: 'أولوية عالية',
      es: 'Prioridad alta',
      fr: 'Priorité haute',
      hi: 'उच्च प्राथमिकता',
      id: 'Prioritas tinggi',
      pt: 'Prioridade alta',
    },
    'label.noTick': {
      en: 'Before the first tick',
      ko: '첫 틱 앞',
      ja: '最初のティックの前',
      zh: '第一个时钟周期之前',
      ar: 'قبل النبضة الأولى',
      es: 'Antes del primer tic',
      fr: 'Avant le premier tic',
      hi: 'पहली टिक से पहले',
      id: 'Sebelum tik pertama',
      pt: 'Antes do primeiro tique',
    },
    'label.tick': {
      en: 'Tick {n}',
      ko: '틱 {n}',
      ja: 'ティック {n}',
      zh: '时钟周期 {n}',
      ar: 'النبضة {n}',
      es: 'Tic {n}',
      fr: 'Tic {n}',
      hi: 'टिक {n}',
      id: 'Tik {n}',
      pt: 'Tique {n}',
    },
    'label.switches': {
      en: 'CPU passed: {n}',
      ko: 'CPU 넘어감: {n}',
      ja: 'CPU の移動: {n}',
      zh: 'CPU 转手: {n}',
      ar: 'انتقال المعالج: {n}',
      es: 'La CPU cambió de manos: {n}',
      fr: 'Passages du CPU : {n}',
      hi: 'CPU हस्तांतरण: {n}',
      id: 'CPU berpindah: {n}',
      pt: 'A CPU passou: {n}',
    },
    'label.ownerChanges': {
      en: 'Lock changed hands: {n}',
      ko: '자물쇠 주인 바뀜: {n}',
      ja: 'ロックの持ち主の交代: {n}',
      zh: '锁易主: {n}',
      ar: 'انتقال القفل بين الأيدي: {n}',
      es: 'El cerrojo cambió de manos: {n}',
      fr: 'Changements de détenteur du verrou : {n}',
      hi: 'ताले का मालिक बदला: {n}',
      id: 'Pemilik kunci berganti: {n}',
      pt: 'O cadeado mudou de mãos: {n}',
    },
    'label.free': {
      en: 'free',
      ko: '비어 있음',
      ja: '空き',
      zh: '空闲',
      ar: 'حر',
      es: 'libre',
      fr: 'libre',
      hi: 'खाली',
      id: 'bebas',
      pt: 'livre',
    },
    'label.priority': {
      en: 'Priority {p}',
      ko: '우선순위 {p}',
      ja: '優先度 {p}',
      zh: '优先级 {p}',
      ar: 'الأولوية {p}',
      es: 'Prioridad {p}',
      fr: 'Priorité {p}',
      hi: 'प्राथमिकता {p}',
      id: 'Prioritas {p}',
      pt: 'Prioridade {p}',
    },
    'label.notYet': {
      en: 'Arrives at tick {n}',
      ko: '오는 틱: {n}',
      ja: '到着ティック: {n}',
      zh: '到达周期: {n}',
      ar: 'يصل في النبضة {n}',
      es: 'Llega en el tic {n}',
      fr: 'Arrive au tic {n}',
      hi: 'आगमन टिक: {n}',
      id: 'Tiba di tik {n}',
      pt: 'Chega no tique {n}',
    },
    'label.asleep': {
      en: 'Asleep',
      ko: '잠듦',
      ja: '休眠',
      zh: '休眠',
      ar: 'نائم',
      es: 'Dormido',
      fr: 'Endormi',
      hi: 'सोया हुआ',
      id: 'Tidur',
      pt: 'Dormindo',
    },
    'label.done': {
      en: 'Done',
      ko: '끝남',
      ja: '完了',
      zh: '已结束',
      ar: 'انتهى',
      es: 'Terminado',
      fr: 'Terminé',
      hi: 'समाप्त',
      id: 'Selesai',
      pt: 'Concluída',
    },
    'label.sleptTicks': {
      en: 'Ticks asleep: {n}',
      ko: '잠든 틱: {n}',
      ja: '休眠ティック: {n}',
      zh: '休眠周期: {n}',
      ar: 'نبضات النوم: {n}',
      es: 'Tics dormido: {n}',
      fr: 'Tics endormi : {n}',
      hi: 'सोए टिक: {n}',
      id: 'Tik tidur: {n}',
      pt: 'Tiques dormindo: {n}',
    },
    'label.cpu': {
      en: 'CPU',
      ko: 'CPU',
      ja: 'CPU',
      zh: 'CPU',
      ar: 'المعالج',
      es: 'CPU',
      fr: 'CPU',
      hi: 'CPU',
      id: 'CPU',
      pt: 'CPU',
    },
    'caption.cpuPreempt': {
      en: 'CPU: {from} → {to}. Priority {a} > {b}.',
      ko: 'CPU: {from} → {to}. 우선순위 {a} > {b}.',
      ja: 'CPU: {from} → {to}。優先度 {a} > {b}。',
      zh: 'CPU：{from} → {to}。优先级 {a} > {b}。',
      ar: 'المعالج: {from} ← {to}. الأولوية {a} > {b}.',
      es: 'CPU: {from} → {to}. Prioridad {a} > {b}.',
      fr: 'CPU : {from} → {to}. Priorité {a} > {b}.',
      hi: 'CPU: {from} → {to}। प्राथमिकता {a} > {b}।',
      id: 'CPU: {from} → {to}. Prioritas {a} > {b}.',
      pt: 'CPU: {from} → {to}. Prioridade {a} > {b}.',
    },
    'caption.cpuAsleep': {
      en: 'CPU: {from} → {to}. {from}: asleep.',
      ko: 'CPU: {from} → {to}. {from}: 잠듦.',
      ja: 'CPU: {from} → {to}。{from}: 休眠。',
      zh: 'CPU：{from} → {to}。{from}：休眠。',
      ar: 'المعالج: {from} ← {to}. {from}: نائم.',
      es: 'CPU: {from} → {to}. {from}: dormido.',
      fr: 'CPU : {from} → {to}. {from} : endormi.',
      hi: 'CPU: {from} → {to}। {from}: सोया हुआ।',
      id: 'CPU: {from} → {to}. {from}: tidur.',
      pt: 'CPU: {from} → {to}. {from}: dormindo.',
    },
    'caption.cpuDone': {
      en: 'CPU: {from} → {to}. {from}: done.',
      ko: 'CPU: {from} → {to}. {from}: 끝남.',
      ja: 'CPU: {from} → {to}。{from}: 完了。',
      zh: 'CPU：{from} → {to}。{from}：已结束。',
      ar: 'المعالج: {from} ← {to}. {from}: انتهى.',
      es: 'CPU: {from} → {to}. {from}: terminado.',
      fr: 'CPU : {from} → {to}. {from} : terminé.',
      hi: 'CPU: {from} → {to}। {from}: समाप्त।',
      id: 'CPU: {from} → {to}. {from}: selesai.',
      pt: 'CPU: {from} → {to}. {from}: concluída.',
    },
    'caption.cpu': {
      en: 'CPU: {from} → {to}.',
      ko: 'CPU: {from} → {to}.',
      ja: 'CPU: {from} → {to}。',
      zh: 'CPU：{from} → {to}。',
      ar: 'المعالج: {from} ← {to}.',
      es: 'CPU: {from} → {to}.',
      fr: 'CPU : {from} → {to}.',
      hi: 'CPU: {from} → {to}।',
      id: 'CPU: {from} → {to}.',
      pt: 'CPU: {from} → {to}.',
    },
    'caption.start': {
      en: 'Nothing has run yet. Lock {lock}: free.',
      ko: '아직 아무것도 달리지 않았다. 자물쇠 {lock}: 비어 있음.',
      ja: 'まだ何も動いていない。ロック {lock}: 空き。',
      zh: '还没有任何线程运行。锁 {lock}：空闲。',
      ar: 'لم يعمل شيء بعد. القفل {lock}: حر.',
      es: 'Aún no se ha ejecutado nada. Cerrojo {lock}: libre.',
      fr: 'Rien ne s’est encore exécuté. Verrou {lock} : libre.',
      hi: 'अभी कुछ नहीं चला। ताला {lock}: खाली।',
      id: 'Belum ada yang berjalan. Kunci {lock}: bebas.',
      pt: 'Nada rodou ainda. Cadeado {lock}: livre.',
    },
    'caption.take': {
      en: 'Takes lock {lock}.',
      ko: '잡는다 — 자물쇠 {lock}.',
      ja: 'ロック {lock} を取る。',
      zh: '拿到锁 {lock}。',
      ar: 'يأخذ القفل {lock}.',
      es: 'Toma el cerrojo {lock}.',
      fr: 'Prend le verrou {lock}.',
      hi: 'ताला {lock} ले लेता है।',
      id: 'Mengambil kunci {lock}.',
      pt: 'Pega o cadeado {lock}.',
    },
    'caption.block': {
      en: 'Lock {lock} is held by {owner}. Cannot take it — asleep.',
      ko: '자물쇠 {lock} — 주인: {owner}. 잡지 못하고 잠든다.',
      ja: 'ロック {lock} の持ち主: {owner}。取れずに休眠する。',
      zh: '锁 {lock} 的持有者：{owner}。拿不到，进入休眠。',
      ar: 'القفل {lock} يمسكه: {owner}. لا يستطيع أخذه — ينام.',
      es: 'El cerrojo {lock} lo tiene: {owner}. No puede tomarlo: se duerme.',
      fr: 'Le verrou {lock} est tenu par : {owner}. Impossible de le prendre — s’endort.',
      hi: 'ताला {lock} का मालिक: {owner}। ले नहीं पाता — सो जाता है।',
      id: 'Kunci {lock} dipegang oleh: {owner}. Tak bisa diambil — tidur.',
      pt: 'O cadeado {lock} está com: {owner}. Não consegue pegá-lo: dorme.',
    },
    'caption.workHold': {
      en: 'Runs one line, still holding lock {lock}.',
      ko: '한 줄을 실행한다. 쥔 자물쇠: {lock}.',
      ja: 'ロック {lock} を持ったまま一行を実行する。',
      zh: '仍持有锁 {lock}，执行一行。',
      ar: 'ينفّذ سطرًا واحدًا وما زال يمسك القفل {lock}.',
      es: 'Ejecuta una línea sin soltar el cerrojo {lock}.',
      fr: 'Exécute une ligne en tenant toujours le verrou {lock}.',
      hi: 'ताला {lock} पकड़े हुए एक पंक्ति चलाता है।',
      id: 'Menjalankan satu baris sambil tetap memegang kunci {lock}.',
      pt: 'Executa uma linha, ainda segurando o cadeado {lock}.',
    },
    'caption.work': {
      en: 'Runs one line.',
      ko: '한 줄을 실행한다.',
      ja: '一行を実行する。',
      zh: '执行一行。',
      ar: 'ينفّذ سطرًا واحدًا.',
      es: 'Ejecuta una línea.',
      fr: 'Exécute une ligne.',
      hi: 'एक पंक्ति चलाता है।',
      id: 'Menjalankan satu baris.',
      pt: 'Executa uma linha.',
    },
    'caption.handoff': {
      en: 'Releases lock {lock}. Handed straight to {to}, who wakes.',
      ko: '놓는다 — 자물쇠 {lock}. 곧바로 넘겨받음: {to}. 깨어난다.',
      ja: 'ロック {lock} を放す。すぐに受け取る: {to}。目を覚ます。',
      zh: '释放锁 {lock}。直接交给：{to}，它被唤醒。',
      ar: 'يحرّر القفل {lock}. ينتقل مباشرة إلى: {to}، فيستيقظ.',
      es: 'Suelta el cerrojo {lock}. Pasa directo a: {to}, que despierta.',
      fr: 'Relâche le verrou {lock}. Remis aussitôt à : {to}, qui se réveille.',
      hi: 'ताला {lock} छोड़ता है। सीधे मिलता है: {to} — जो जाग जाता है।',
      id: 'Melepas kunci {lock}. Langsung diserahkan ke: {to}, yang bangun.',
      pt: 'Solta o cadeado {lock}. Passa direto para: {to}, que acorda.',
    },
    'caption.release': {
      en: 'Releases lock {lock}. Nobody waiting: free.',
      ko: '놓는다 — 자물쇠 {lock}. 기다리는 쪽 없음: 비어 있음.',
      ja: 'ロック {lock} を放す。待つ者なし: 空き。',
      zh: '释放锁 {lock}。无人等待：空闲。',
      ar: 'يحرّر القفل {lock}. لا أحد ينتظر: حر.',
      es: 'Suelta el cerrojo {lock}. Nadie espera: libre.',
      fr: 'Relâche le verrou {lock}. Personne n’attend : libre.',
      hi: 'ताला {lock} छोड़ता है। कोई प्रतीक्षा में नहीं: खाली।',
      id: 'Melepas kunci {lock}. Tak ada yang menunggu: bebas.',
      pt: 'Solta o cadeado {lock}. Ninguém esperando: livre.',
    },
  },
  blocks: {
    stage: { type: 'no-preemption-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
