/**
 * @piece
 * 질문: 리더 없이 여러 사본이 저마다 쓰기를 받으면 값이 갈라지는데, 쓰기가 멈추면 사본들은 어떻게 같은 값에 이르는가.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const eventuallyAgreesFacet: FacetJson = {
  id: 'facet:eventuallyAgrees',
  title: {
    en: 'Replicas eventually agree',
    ko: '사본들은 결국 같아진다',
    ja: 'レプリカはやがて一致する',
    zh: '副本最终会一致',
    ar: 'النسخ تتفق في النهاية',
    es: 'Las réplicas acaban coincidiendo',
    fr: 'Les répliques finissent par s’accorder',
    hi: 'प्रतियाँ अंततः एक हो जाती हैं',
    id: 'Replika akhirnya sepakat',
    pt: 'As réplicas acabam concordando',
  },
  description: {
    en: 'Without a leader, each replica takes its own writes and the values split. Once writes stop, pairwise exchanges where the larger stamp wins bring every replica to one value.',
    ko: '리더 없이 사본마다 따로 쓰기를 받으면 값이 갈라진다. 쓰기가 멈추면, 도장이 큰 쪽이 이기는 둘씩의 주고받기가 모든 사본을 한 값으로 모은다.',
    ja: 'リーダーなしで各レプリカが別々に書き込みを受けると値が分かれる。書き込みが止まると、スタンプの大きい方が勝つ二者間の交換が全レプリカを一つの値にまとめる。',
    zh: '没有领导者时，各副本各自接受写入，值就会分叉。写入停止后，两两交换、时间戳大者胜，让所有副本汇聚到同一个值。',
    ar: 'بلا قائد، تقبل كل نسخة كتاباتها الخاصة فتتفرق القيم. حين تتوقف الكتابات، تجمع التبادلات الثنائية — حيث يفوز الختم الأكبر — كل النسخ على قيمة واحدة.',
    es: 'Sin líder, cada réplica acepta sus propias escrituras y los valores se separan. Cuando cesan las escrituras, los intercambios por pares en los que gana el sello mayor llevan a todas las réplicas a un solo valor.',
    fr: 'Sans leader, chaque réplique accepte ses propres écritures et les valeurs divergent. Quand les écritures cessent, des échanges deux à deux où le plus grand tampon gagne amènent toutes les répliques à une seule valeur.',
    hi: 'बिना लीडर के हर प्रति अपने लेखन अलग से लेती है और मान बँट जाते हैं। लेखन रुकने पर, जोड़ियों में होने वाले आदान-प्रदान — जिनमें बड़ी मुहर जीतती है — सभी प्रतियों को एक मान पर ले आते हैं।',
    id: 'Tanpa pemimpin, tiap replika menerima penulisannya sendiri dan nilainya terpecah. Setelah penulisan berhenti, pertukaran berpasangan tempat cap terbesar menang membawa semua replika ke satu nilai.',
    pt: 'Sem líder, cada réplica aceita suas próprias escritas e os valores se dividem. Quando as escritas param, trocas aos pares em que vence o carimbo maior levam todas as réplicas a um só valor.',
  },
  algorithm: 'module:eventuallyAgrees',
  scene: 'module:eventuallyAgreesScene',
  initialData: {
    type: 'eventually-agrees',
    stepMs: 1400,
    key: 'x',
    replicas: [
      { id: 'n1', value: 0, stamp: 0 },
      { id: 'n2', value: 0, stamp: 0 },
      { id: 'n3', value: 0, stamp: 0 },
      { id: 'n4', value: 0, stamp: 0 },
    ],
    happenings: [
      { kind: 'write', at: 'n1', value: 7, stamp: 1 },
      { kind: 'write', at: 'n3', value: 4, stamp: 2 },
      { kind: 'gossip', a: 'n1', b: 'n3' },
      { kind: 'write', at: 'n4', value: 9, stamp: 3 },
      { kind: 'gossip', a: 'n2', b: 'n4' },
      { kind: 'gossip', a: 'n1', b: 'n2' },
      { kind: 'gossip', a: 'n3', b: 'n4' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Replicas: {n}. No leader — any replica takes a write.',
      ko: '사본: {n}. 리더가 없다 — 어느 사본이든 쓰기를 받는다.',
      ja: 'レプリカ: {n}。リーダーなし — どのレプリカも書き込みを受ける。',
      zh: '副本：{n}。没有领导者——任何副本都可接受写入。',
      ar: 'النسخ: {n}. لا قائد — أي نسخة تقبل الكتابة.',
      es: 'Réplicas: {n}. Sin líder: cualquier réplica acepta una escritura.',
      fr: 'Répliques : {n}. Pas de leader — toute réplique accepte une écriture.',
      hi: 'प्रतियाँ: {n}। कोई लीडर नहीं — कोई भी प्रति लेखन ले सकती है।',
      id: 'Replika: {n}. Tanpa pemimpin — replika mana pun menerima penulisan.',
      pt: 'Réplicas: {n}. Sem líder — qualquer réplica aceita uma escrita.',
    },
    'caption.write': {
      en: 'A write lands on {at}.',
      ko: '쓰기 하나가 {at} 에 떨어진다.',
      ja: '書き込みが {at} に届く。',
      zh: '一次写入落在 {at}。',
      ar: 'كتابة تصل إلى {at}.',
      es: 'Una escritura llega a {at}.',
      fr: 'Une écriture arrive sur {at}.',
      hi: 'एक लेखन {at} पर पहुँचता है।',
      id: 'Satu penulisan jatuh di {at}.',
      pt: 'Uma escrita chega a {at}.',
    },
    'detail.write': {
      en: '{key} = {value}, stamp {stamp}',
      ko: '{key} = {value}, 도장 {stamp}',
      ja: '{key} = {value}、スタンプ {stamp}',
      zh: '{key} = {value}，时间戳 {stamp}',
      ar: '{key} = {value}، الختم {stamp}',
      es: '{key} = {value}, sello {stamp}',
      fr: '{key} = {value}, tampon {stamp}',
      hi: '{key} = {value}, मुहर {stamp}',
      id: '{key} = {value}, cap {stamp}',
      pt: '{key} = {value}, carimbo {stamp}',
    },
    'detail.writeLast': {
      en: '{key} = {value}, stamp {stamp} — no writes after this',
      ko: '{key} = {value}, 도장 {stamp} — 이 뒤로 쓰기 없음',
      ja: '{key} = {value}、スタンプ {stamp} — この後に書き込みはない',
      zh: '{key} = {value}，时间戳 {stamp}——此后没有写入',
      ar: '{key} = {value}، الختم {stamp} — لا كتابات بعد هذه',
      es: '{key} = {value}, sello {stamp} — no hay escrituras después',
      fr: '{key} = {value}, tampon {stamp} — aucune écriture après celle-ci',
      hi: '{key} = {value}, मुहर {stamp} — इसके बाद कोई लेखन नहीं',
      id: '{key} = {value}, cap {stamp} — tidak ada penulisan setelah ini',
      pt: '{key} = {value}, carimbo {stamp} — nenhuma escrita depois desta',
    },
    'caption.gossip': {
      en: '{a} ↔ {b} exchange values. The larger stamp wins.',
      ko: '{a} ↔ {b} 값을 주고받는다. 도장이 큰 쪽이 이긴다.',
      ja: '{a} ↔ {b} で値を交換する。スタンプの大きい方が勝つ。',
      zh: '{a} ↔ {b} 交换值。时间戳大的一方获胜。',
      ar: '{a} ↔ {b} تتبادلان القيم. الختم الأكبر يفوز.',
      es: '{a} ↔ {b} intercambian valores. Gana el sello mayor.',
      fr: '{a} ↔ {b} échangent leurs valeurs. Le plus grand tampon gagne.',
      hi: '{a} ↔ {b} मान बदलते हैं। बड़ी मुहर जीतती है।',
      id: '{a} ↔ {b} bertukar nilai. Cap yang lebih besar menang.',
      pt: '{a} ↔ {b} trocam valores. Vence o carimbo maior.',
    },
    'detail.gossip': {
      en: 'Both now {key} = {value}, stamp {stamp}',
      ko: '이제 둘 다 {key} = {value}, 도장 {stamp}',
      ja: 'どちらも {key} = {value}、スタンプ {stamp}',
      zh: '两者现在都是 {key} = {value}，时间戳 {stamp}',
      ar: 'كلتاهما الآن {key} = {value}، الختم {stamp}',
      es: 'Ambas ahora {key} = {value}, sello {stamp}',
      fr: 'Les deux : {key} = {value}, tampon {stamp}',
      hi: 'अब दोनों {key} = {value}, मुहर {stamp}',
      id: 'Keduanya kini {key} = {value}, cap {stamp}',
      pt: 'Ambas agora {key} = {value}, carimbo {stamp}',
    },
    'detail.settle': {
      en: 'Both now {key} = {value}, stamp {stamp} · holding it: {k} of {n}',
      ko: '이제 둘 다 {key} = {value}, 도장 {stamp} · 이 값을 든 사본 {k} / {n}',
      ja: 'どちらも {key} = {value}、スタンプ {stamp} · この値を持つレプリカ {k} / {n}',
      zh: '两者现在都是 {key} = {value}，时间戳 {stamp} · 持有此值的副本 {k} / {n}',
      ar: 'كلتاهما الآن {key} = {value}، الختم {stamp} · النسخ التي تحملها: {k} من {n}',
      es: 'Ambas ahora {key} = {value}, sello {stamp} · réplicas con ese valor: {k} de {n}',
      fr: 'Les deux : {key} = {value}, tampon {stamp} · répliques qui l’ont : {k} sur {n}',
      hi: 'अब दोनों {key} = {value}, मुहर {stamp} · यह मान रखने वाली प्रतियाँ: {n} में से {k}',
      id: 'Keduanya kini {key} = {value}, cap {stamp} · replika yang memegangnya: {k} dari {n}',
      pt: 'Ambas agora {key} = {value}, carimbo {stamp} · réplicas com esse valor: {k} de {n}',
    },
    'label.distinct': {
      en: 'Distinct values',
      ko: '서로 다른 값',
      ja: '異なる値の数',
      zh: '不同的值',
      ar: 'قيم مختلفة',
      es: 'Valores distintos',
      fr: 'Valeurs distinctes',
      hi: 'अलग-अलग मान',
      id: 'Nilai berbeda',
      pt: 'Valores distintos',
    },
    'label.stamp': {
      en: 'stamp {s}',
      ko: '도장 {s}',
      ja: 'スタンプ {s}',
      zh: '时间戳 {s}',
      ar: 'الختم {s}',
      es: 'sello {s}',
      fr: 'tampon {s}',
      hi: 'मुहर {s}',
      id: 'cap {s}',
      pt: 'carimbo {s}',
    },
  },
  blocks: {
    stage: { type: 'eventually-agrees-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
