/**
 * @piece
 * 한 서버가 값을 고칠 때, 다른 서버들의 옛 사본이 읽히지 않게 하려면 무엇을 보내는가.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const invalidateOthersFacet: FacetJson = {
  id: 'facet:invalidateOthers',
  title: {
    en: 'Invalidate the other copies',
    ko: '다른 사본을 무른다',
    ja: '他のコピーを無効にする',
    zh: '让其他副本失效',
    ar: 'إبطال النسخ الأخرى',
    es: 'Invalidar las otras copias',
    fr: 'Invalider les autres copies',
    hi: 'बाकी प्रतियों को अमान्य करना',
    id: 'Membatalkan salinan lain',
    pt: 'Invalidar as outras cópias',
  },
  description: {
    en: 'When one server changes a value, what does it send so that stale copies on the other servers are never read?',
    ko: '한 서버가 값을 고칠 때, 다른 서버들의 옛 사본이 읽히지 않게 하려면 무엇을 보내는가?',
    ja: 'あるサーバーが値を書き換えるとき、他のサーバーの古いコピーが読まれないようにするには何を送るのか?',
    zh: '一台服务器修改值时，要让其他服务器上的旧副本不被读到，它要发送什么？',
    ar: 'عندما يغيّر خادم قيمة، ماذا يرسل كي لا تُقرأ النسخ القديمة على الخوادم الأخرى؟',
    es: 'Cuando un servidor cambia un valor, ¿qué envía para que nunca se lean las copias viejas de los otros servidores?',
    fr: 'Quand un serveur modifie une valeur, qu’envoie-t-il pour que les copies périmées des autres serveurs ne soient jamais lues ?',
    hi: 'जब एक सर्वर कोई मान बदलता है, तो वह क्या भेजे कि बाकी सर्वरों की पुरानी प्रतियाँ कभी न पढ़ी जाएँ?',
    id: 'Saat satu server mengubah nilai, apa yang ia kirim agar salinan usang di server lain tidak pernah terbaca?',
    pt: 'Quando um servidor muda um valor, o que ele envia para que as cópias velhas nos outros servidores nunca sejam lidas?',
  },
  algorithm: 'module:invalidateOthers',
  scene: 'module:invalidateOthersScene',
  initialData: {
    type: 'invalidate-others',
    stepMs: 1600,
    key: 'stock:7',
    dbValue: 5,
    servers: ['s1', 's2', 's3', 's4'],
    cachedAt: ['s1', 's2', 's3', 's4'],
    events: [
      { op: 'write', server: 's1', value: 4 },
      { op: 'invalidate', server: 's1' },
      { op: 'read', server: 's3' },
      { op: 'read', server: 's2' },
      { op: 'read', server: 's3' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.init': {
      en: 'Every server caches a copy of {key}',
      ko: '서버마다 {key} 의 사본을 캐시에 든다',
      ja: 'どのサーバーも {key} のコピーをキャッシュに持つ',
      zh: '每台服务器都在缓存里存着 {key} 的副本',
      ar: 'كل خادم يحفظ في ذاكرته المؤقتة نسخة من {key}',
      es: 'Cada servidor guarda en caché una copia de {key}',
      fr: 'Chaque serveur garde en cache une copie de {key}',
      hi: 'हर सर्वर कैश में {key} की एक प्रति रखता है',
      id: 'Setiap server menyimpan salinan {key} di cache',
      pt: 'Cada servidor guarda em cache uma cópia de {key}',
    },
    'caption.write': {
      en: 'Write at server {server} · New value: {value} · Stale copies: {n}',
      ko: '서버 {server} 에서 쓰기 · 새 값: {value} · 옛 사본: {n}',
      ja: 'サーバー {server} で書き込み · 新しい値: {value} · 古いコピー: {n}',
      zh: '在服务器 {server} 写入 · 新值: {value} · 旧副本: {n}',
      ar: 'كتابة على الخادم {server} · القيمة الجديدة: {value} · نسخ قديمة: {n}',
      es: 'Escritura en el servidor {server} · Valor nuevo: {value} · Copias viejas: {n}',
      fr: 'Écriture sur le serveur {server} · Nouvelle valeur : {value} · Copies périmées : {n}',
      hi: 'सर्वर {server} पर लिखना · नया मान: {value} · पुरानी प्रतियाँ: {n}',
      id: 'Tulis di server {server} · Nilai baru: {value} · Salinan usang: {n}',
      pt: 'Escrita no servidor {server} · Valor novo: {value} · Cópias velhas: {n}',
    },
    'caption.invalidate': {
      en: 'Server {from} sends "drop" with no value · Messages: {n}',
      ko: '서버 {from} 에서 값 없이 "버려라" 만 보낸다 · 통 수: {n}',
      ja: 'サーバー {from} から値なしで「捨てろ」だけを送る · 通数: {n}',
      zh: '服务器 {from} 只发送不带值的“丢弃” · 条数: {n}',
      ar: 'الخادم {from} يرسل «تخلَّص» بلا قيمة · عدد الرسائل: {n}',
      es: 'El servidor {from} envía «descartar» sin valor · Mensajes: {n}',
      fr: 'Le serveur {from} envoie « jeter » sans valeur · Messages : {n}',
      hi: 'सर्वर {from} बिना मान के सिर्फ़ "हटाओ" भेजता है · संदेश: {n}',
      id: 'Server {from} mengirim "buang" tanpa nilai · Pesan: {n}',
      pt: 'O servidor {from} envia "descartar" sem valor · Mensagens: {n}',
    },
    'caption.hit': {
      en: 'Read at server {server}: hit · Value: {value}',
      ko: '서버 {server} 에서 읽기: 적중 · 값: {value}',
      ja: 'サーバー {server} で読み取り: ヒット · 値: {value}',
      zh: '在服务器 {server} 读取: 命中 · 值: {value}',
      ar: 'قراءة على الخادم {server}: إصابة · القيمة: {value}',
      es: 'Lectura en el servidor {server}: acierto · Valor: {value}',
      fr: 'Lecture sur le serveur {server} : succès · Valeur : {value}',
      hi: 'सर्वर {server} पर पढ़ना: हिट · मान: {value}',
      id: 'Baca di server {server}: hit · Nilai: {value}',
      pt: 'Leitura no servidor {server}: acerto · Valor: {value}',
    },
    'caption.miss': {
      en: 'Read at server {server}: miss, refilled from the DB · Value: {value}',
      ko: '서버 {server} 에서 읽기: 실패, DB 에서 다시 채움 · 값: {value}',
      ja: 'サーバー {server} で読み取り: ミス、DB から埋め直す · 値: {value}',
      zh: '在服务器 {server} 读取: 未命中，从 DB 重新填入 · 值: {value}',
      ar: 'قراءة على الخادم {server}: إخفاق، أُعيد الملء من قاعدة البيانات · القيمة: {value}',
      es: 'Lectura en el servidor {server}: fallo, se rellena desde la BD · Valor: {value}',
      fr: 'Lecture sur le serveur {server} : échec, rempli à nouveau depuis la BD · Valeur : {value}',
      hi: 'सर्वर {server} पर पढ़ना: मिस, DB से फिर भरा · मान: {value}',
      id: 'Baca di server {server}: miss, diisi ulang dari DB · Nilai: {value}',
      pt: 'Leitura no servidor {server}: falha, preenchido de novo pelo BD · Valor: {value}',
    },
    'label.db': {
      en: 'DB',
      ko: 'DB',
      ja: 'DB',
      zh: 'DB',
      ar: 'قاعدة البيانات',
      es: 'BD',
      fr: 'BD',
      hi: 'DB',
      id: 'DB',
      pt: 'BD',
    },
    'label.server': {
      en: 'Server {id}',
      ko: '서버 {id}',
      ja: 'サーバー {id}',
      zh: '服务器 {id}',
      ar: 'الخادم {id}',
      es: 'Servidor {id}',
      fr: 'Serveur {id}',
      hi: 'सर्वर {id}',
      id: 'Server {id}',
      pt: 'Servidor {id}',
    },
    'label.empty': {
      en: 'empty',
      ko: '빈 자리',
      ja: '空き',
      zh: '空',
      ar: 'فارغ',
      es: 'vacío',
      fr: 'vide',
      hi: 'खाली',
      id: 'kosong',
      pt: 'vazio',
    },
    'label.stale': {
      en: 'stale',
      ko: '옛값',
      ja: '古い値',
      zh: '旧值',
      ar: 'قديمة',
      es: 'viejo',
      fr: 'périmé',
      hi: 'पुराना',
      id: 'usang',
      pt: 'velho',
    },
    'label.drop': {
      en: 'drop',
      ko: '버려라',
      ja: '捨てろ',
      zh: '丢弃',
      ar: 'تخلَّص',
      es: 'descartar',
      fr: 'jeter',
      hi: 'हटाओ',
      id: 'buang',
      pt: 'descartar',
    },
    'counter.held': {
      en: 'Copies held',
      ko: '들고 있는 사본',
      ja: '持っているコピー',
      zh: '持有的副本',
      ar: 'النسخ المحفوظة',
      es: 'Copias guardadas',
      fr: 'Copies détenues',
      hi: 'रखी गई प्रतियाँ',
      id: 'Salinan yang dipegang',
      pt: 'Cópias guardadas',
    },
    'counter.dbReads': {
      en: 'Reads sent to the DB',
      ko: 'DB 에 간 읽기',
      ja: 'DB へ行った読み取り',
      zh: '去 DB 的读取',
      ar: 'قراءات ذهبت إلى قاعدة البيانات',
      es: 'Lecturas a la BD',
      fr: 'Lectures envoyées à la BD',
      hi: 'DB तक गए पाठ',
      id: 'Bacaan ke DB',
      pt: 'Leituras ao BD',
    },
    'mark.write': {
      en: 'Write: {value}',
      ko: '쓰기: {value}',
      ja: '書き込み: {value}',
      zh: '写入: {value}',
      ar: 'كتابة: {value}',
      es: 'Escritura: {value}',
      fr: 'Écriture : {value}',
      hi: 'लिखना: {value}',
      id: 'Tulis: {value}',
      pt: 'Escrita: {value}',
    },
    'mark.hit': {
      en: 'Hit: {value}',
      ko: '적중: {value}',
      ja: 'ヒット: {value}',
      zh: '命中: {value}',
      ar: 'إصابة: {value}',
      es: 'Acierto: {value}',
      fr: 'Succès : {value}',
      hi: 'हिट: {value}',
      id: 'Hit: {value}',
      pt: 'Acerto: {value}',
    },
    'mark.miss': {
      en: 'Miss: {value}',
      ko: '실패: {value}',
      ja: 'ミス: {value}',
      zh: '未命中: {value}',
      ar: 'إخفاق: {value}',
      es: 'Fallo: {value}',
      fr: 'Échec : {value}',
      hi: 'मिस: {value}',
      id: 'Miss: {value}',
      pt: 'Falha: {value}',
    },
  },
  blocks: {
    stage: { type: 'invalidate-others-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
