import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 소스 하나를 고친 뒤 다시 빌드하면, 대상 일곱 가운데 무엇을 다시 세우고 무엇을 그대로 쓰는가.
 *
 * 규칙은 "대상 ← 입력들" 이다. 고친 소스는 데이터가 준다 — 어떻게 알아냈는지는 이 조각이 말하지 않는다.
 */
export const onlyWhatChangedFacet: FacetJson = {
  id: 'facet:onlyWhatChanged',
  title: {
    en: 'Only what changed',
    ko: '바뀐 것만',
    ja: '変わったものだけ',
    zh: '只重建变了的',
    ar: 'ما تغيّر فقط',
    es: 'Solo lo que cambió',
    fr: 'Seulement ce qui a changé',
    hi: 'सिर्फ़ जो बदला',
    id: 'Hanya yang berubah',
    pt: 'Só o que mudou',
  },
  description: {
    en: 'After one source is edited, the build checks each target in turn and rebuilds only those with a changed input — the rest keep the previous result.',
    ko: '소스 하나를 고친 뒤 빌드는 대상을 차례로 들여다보며 바뀐 입력이 있는 것만 다시 세운다 — 나머지는 지난번 결과를 그대로 쓴다.',
    ja: 'ソースを一つ直したあと、ビルドは対象を順に確かめ、変わった入力を持つものだけを作り直す。残りは前回の結果をそのまま使う。',
    zh: '改动一个源文件后，构建依次检查每个目标，只重建有输入变化的那些——其余沿用上次的结果。',
    ar: 'بعد تعديل مصدر واحد، يفحص البناء كل هدف بالترتيب ويعيد بناء ما تغيّر أحد مدخلاته فقط — ويبقي الباقي على نتيجة المرة السابقة.',
    es: 'Tras editar una fuente, la compilación revisa cada objetivo por turno y reconstruye solo los que tienen una entrada cambiada; el resto conserva el resultado anterior.',
    fr: 'Après la modification d’une source, la compilation examine chaque cible à tour de rôle et ne reconstruit que celles dont une entrée a changé ; les autres gardent le résultat précédent.',
    hi: 'एक स्रोत बदलने के बाद बिल्ड हर लक्ष्य को बारी-बारी से देखता है और सिर्फ़ उन्हीं को फिर से बनाता है जिनका कोई इनपुट बदला है — बाक़ी पिछला नतीजा रखते हैं।',
    id: 'Setelah satu sumber diubah, build memeriksa tiap target bergiliran dan hanya membangun ulang yang masukannya berubah — sisanya memakai hasil sebelumnya.',
    pt: 'Depois de editar uma fonte, o build examina cada alvo por vez e reconstrói só os que têm uma entrada alterada; o resto mantém o resultado anterior.',
  },
  algorithm: 'module:onlyWhatChanged',
  scene: 'module:onlyWhatChangedScene',
  initialData: {
    type: 'only-what-changed',
    stepMs: 1300,
    rules: [
      { target: 'lex.o', inputs: ['lex.c'] },
      { target: 'parse.o', inputs: ['parse.c'] },
      { target: 'check.o', inputs: ['check.c'] },
      { target: 'emit.o', inputs: ['emit.c'] },
      { target: 'front.a', inputs: ['lex.o', 'parse.o'] },
      { target: 'back.a', inputs: ['check.o', 'emit.o'] },
      { target: 'tool', inputs: ['front.a', 'back.a'] },
    ],
    sources: ['lex.c', 'parse.c', 'check.c', 'emit.c'],
    edited: ['emit.c'],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Previous build results: {n}',
      ko: '지난번 빌드 결과: {n}',
      ja: '前回のビルド結果: {n}',
      zh: '上次构建的结果：{n}',
      ar: 'نتائج البناء السابق: {n}',
      es: 'Resultados de la compilación anterior: {n}',
      fr: 'Résultats de la compilation précédente : {n}',
      hi: 'पिछले बिल्ड के नतीजे: {n}',
      id: 'Hasil build sebelumnya: {n}',
      pt: 'Resultados do build anterior: {n}',
    },
    'caption.edit': {
      en: 'Edited: {names}',
      ko: '고친 소스: {names}',
      ja: '直したソース: {names}',
      zh: '改动的源文件：{names}',
      ar: 'المصدر المعدَّل: {names}',
      es: 'Editado: {names}',
      fr: 'Modifié : {names}',
      hi: 'बदला गया: {names}',
      id: 'Diubah: {names}',
      pt: 'Editado: {names}',
    },
    'caption.keep': {
      en: 'Kept: {name} — no changed input',
      ko: '그대로: {name} — 바뀐 입력 없음',
      ja: 'そのまま: {name} — 変わった入力なし',
      zh: '保留：{name} —— 没有变化的输入',
      ar: 'أُبقي: {name} — لا مدخل متغيّر',
      es: 'Conservado: {name} — ninguna entrada cambiada',
      fr: 'Conservé : {name} — aucune entrée modifiée',
      hi: 'वैसा ही: {name} — कोई इनपुट नहीं बदला',
      id: 'Tetap: {name} — tak ada masukan yang berubah',
      pt: 'Mantido: {name} — nenhuma entrada alterada',
    },
    'caption.rebuild': {
      en: 'Rebuilt: {name} — changed input: {inputs}',
      ko: '다시 세움: {name} — 바뀐 입력: {inputs}',
      ja: '作り直し: {name} — 変わった入力: {inputs}',
      zh: '重建：{name} —— 变化的输入：{inputs}',
      ar: 'أُعيد بناؤه: {name} — المدخل المتغيّر: {inputs}',
      es: 'Reconstruido: {name} — entrada cambiada: {inputs}',
      fr: 'Reconstruit : {name} — entrée modifiée : {inputs}',
      hi: 'फिर से बना: {name} — बदला इनपुट: {inputs}',
      id: 'Dibangun ulang: {name} — masukan berubah: {inputs}',
      pt: 'Reconstruído: {name} — entrada alterada: {inputs}',
    },
    'caption.tally': {
      en: 'Rebuilt: {r}   Kept: {k}   Not yet checked: {u}',
      ko: '다시 세움: {r}   그대로: {k}   아직 안 봄: {u}',
      ja: '作り直し: {r}   そのまま: {k}   未確認: {u}',
      zh: '重建：{r}   保留：{k}   未检查：{u}',
      ar: 'أُعيد بناؤه: {r}   أُبقي: {k}   لم يُفحص بعد: {u}',
      es: 'Reconstruidos: {r}   Conservados: {k}   Sin revisar: {u}',
      fr: 'Reconstruits : {r}   Conservés : {k}   Pas encore examinés : {u}',
      hi: 'फिर से बने: {r}   वैसे ही: {k}   अभी नहीं देखे: {u}',
      id: 'Dibangun ulang: {r}   Tetap: {k}   Belum diperiksa: {u}',
      pt: 'Reconstruídos: {r}   Mantidos: {k}   Ainda não vistos: {u}',
    },
    'status.edited': {
      en: 'edited',
      ko: '고침',
      ja: '修正',
      zh: '已改',
      ar: 'معدَّل',
      es: 'editado',
      fr: 'modifié',
      hi: 'बदला',
      id: 'diubah',
      pt: 'editado',
    },
    'status.previous': {
      en: 'previous',
      ko: '지난번',
      ja: '前回',
      zh: '上次',
      ar: 'السابق',
      es: 'anterior',
      fr: 'précédent',
      hi: 'पिछला',
      id: 'sebelumnya',
      pt: 'anterior',
    },
    'status.kept': {
      en: 'kept',
      ko: '그대로',
      ja: 'そのまま',
      zh: '保留',
      ar: 'أُبقي',
      es: 'conservado',
      fr: 'conservé',
      hi: 'वैसा ही',
      id: 'tetap',
      pt: 'mantido',
    },
    'status.rebuilt': {
      en: 'rebuilt',
      ko: '다시 세움',
      ja: '作り直し',
      zh: '重建',
      ar: 'أُعيد بناؤه',
      es: 'reconstruido',
      fr: 'reconstruit',
      hi: 'फिर से बना',
      id: 'dibangun ulang',
      pt: 'reconstruído',
    },
    'label.targets': {
      en: 'Targets',
      ko: '대상',
      ja: '対象',
      zh: '目标',
      ar: 'الأهداف',
      es: 'Objetivos',
      fr: 'Cibles',
      hi: 'लक्ष्य',
      id: 'Target',
      pt: 'Alvos',
    },
    'label.sources': {
      en: 'Sources',
      ko: '소스',
      ja: 'ソース',
      zh: '源文件',
      ar: 'المصادر',
      es: 'Fuentes',
      fr: 'Sources',
      hi: 'स्रोत',
      id: 'Sumber',
      pt: 'Fontes',
    },
  },
  blocks: {
    stage: { type: 'only-what-changed-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
