import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 같은 열쇠로 같은 메시지를 두 번 보낼 때, IV 만 바꾸면 두 암호문은 얼마나 다른가.
 *
 * 같은 메시지 `PAY100` 을 두 쪽에 나란히 두고 같은 열쇠로 CBC 로 잠근다. 다른 것은 맨 앞의
 * IV 하나뿐인데 첫 덩어리부터 두 암호문이 갈라지고, 덩어리마다 다른 비트 수를 센다.
 */
export const ivMakesDifferentFacet: FacetJson = {
  id: 'facet:ivMakesDifferent',
  title: {
    en: 'The IV locks the same message differently',
    ko: 'IV 가 같은 메시지를 다르게 잠근다',
    ja: 'IV が同じメッセージを違うように暗号化する',
    zh: 'IV 让同一条消息加密成不同的密文',
    ar: 'متجه التهيئة يقفل الرسالة نفسها بشكل مختلف',
    es: 'El IV cifra el mismo mensaje de forma distinta',
    fr: 'Le IV chiffre le même message autrement',
    hi: 'IV एक ही संदेश को अलग तरह से बंद करता है',
    id: 'IV mengunci pesan yang sama secara berbeda',
    pt: 'O IV cifra a mesma mensagem de forma diferente',
  },
  description: {
    en: 'Send the same message twice with the same key. If only the IV changes, how different are the two ciphertexts?',
    ko: '같은 열쇠로 같은 메시지를 두 번 보낼 때, IV 만 바꾸면 두 암호문은 얼마나 다른가?',
    ja: '同じ鍵で同じメッセージを二回送るとき、IV だけを変えると二つの暗号文はどれほど違うか?',
    zh: '用同一把密钥把同一条消息发送两次,只换 IV,两份密文会有多不同?',
    ar: 'عند إرسال الرسالة نفسها مرتين بالمفتاح نفسه، إذا تغيّر متجه التهيئة وحده، فما مقدار اختلاف النصين المشفرين؟',
    es: 'Si envías el mismo mensaje dos veces con la misma clave y solo cambia el IV, ¿cuánto difieren los dos textos cifrados?',
    fr: 'On envoie deux fois le même message avec la même clé. Si seul le IV change, à quel point les deux chiffrés diffèrent-ils ?',
    hi: 'एक ही कुंजी से एक ही संदेश दो बार भेजें और केवल IV बदलें, तो दोनों सिफरटेक्स्ट कितने अलग होंगे?',
    id: 'Jika pesan yang sama dikirim dua kali dengan kunci yang sama dan hanya IV yang diganti, seberapa berbeda kedua cipherteks?',
    pt: 'Ao enviar a mesma mensagem duas vezes com a mesma chave, trocando só o IV, quão diferentes ficam os dois textos cifrados?',
  },
  algorithm: 'module:ivMakesDifferent',
  scene: 'module:ivMakesDifferentScene',
  initialData: {
    type: 'iv-makes-different',
    stepMs: 2400,
    message: 'PAY100',
    key: '61D4F29A',
    sides: [
      { id: 'a', iv: '3C5E' },
      { id: 'b', iv: 'D18B' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Same message, same key on both sides. Only the IV differs.',
      ko: '두 쪽 모두 같은 메시지, 같은 열쇠. IV 만 다르다.',
      ja: '両側とも同じメッセージ、同じ鍵。違うのは IV だけ。',
      zh: '两边是同一条消息、同一把密钥。只有 IV 不同。',
      ar: 'الرسالة نفسها والمفتاح نفسه في الجانبين. متجه التهيئة وحده مختلف.',
      es: 'Mismo mensaje y misma clave en los dos lados. Solo cambia el IV.',
      fr: 'Même message, même clé des deux côtés. Seul le IV diffère.',
      hi: 'दोनों ओर वही संदेश, वही कुंजी। केवल IV अलग है।',
      id: 'Pesan sama, kunci sama di kedua sisi. Hanya IV yang berbeda.',
      pt: 'Mesma mensagem e mesma chave dos dois lados. Só o IV muda.',
    },
    'caption.ivDiff': {
      en: 'Differing bits between the two IVs: {bits} / {total}',
      ko: '두 IV 의 다른 비트: {bits} / {total}',
      ja: '二つの IV の異なるビット: {bits} / {total}',
      zh: '两个 IV 不同的比特: {bits} / {total}',
      ar: 'البتات المختلفة بين متجهي التهيئة: {bits} / {total}',
      es: 'Bits distintos entre los dos IV: {bits} / {total}',
      fr: 'Bits différents entre les deux IV : {bits} / {total}',
      hi: 'दोनों IV में अलग बिट: {bits} / {total}',
      id: 'Bit yang berbeda di antara kedua IV: {bits} / {total}',
      pt: 'Bits diferentes entre os dois IV: {bits} / {total}',
    },
    'caption.block': {
      en: 'Block {i}: each side XORs in its previous value and locks with the same key.',
      ko: '덩어리 {i} — 두 쪽이 저마다 앞 값을 겹치고 같은 열쇠로 잠갔다.',
      ja: 'ブロック {i} — 両側がそれぞれ前の値を重ね、同じ鍵で暗号化した。',
      zh: '分组 {i}:两边各自异或上前一个值,再用同一把密钥加密。',
      ar: 'الكتلة {i}: كل جانب يدمج قيمته السابقة بـ XOR ثم يقفل بالمفتاح نفسه.',
      es: 'Bloque {i}: cada lado aplica XOR con su valor anterior y cifra con la misma clave.',
      fr: 'Bloc {i} : chaque côté applique un XOR avec sa valeur précédente et chiffre avec la même clé.',
      hi: 'ब्लॉक {i}: हर ओर अपना पिछला मान XOR करती है और उसी कुंजी से बंद करती है।',
      id: 'Blok {i}: tiap sisi meng-XOR nilai sebelumnya lalu mengunci dengan kunci yang sama.',
      pt: 'Bloco {i}: cada lado faz XOR com o seu valor anterior e cifra com a mesma chave.',
    },
    'caption.blockDiff': {
      en: 'Differing bits between the two ciphertexts: {bits} / {total}',
      ko: '두 암호문의 다른 비트: {bits} / {total}',
      ja: '二つの暗号文の異なるビット: {bits} / {total}',
      zh: '两份密文不同的比特: {bits} / {total}',
      ar: 'البتات المختلفة بين النصين المشفرين: {bits} / {total}',
      es: 'Bits distintos entre los dos textos cifrados: {bits} / {total}',
      fr: 'Bits différents entre les deux chiffrés : {bits} / {total}',
      hi: 'दोनों सिफरटेक्स्ट में अलग बिट: {bits} / {total}',
      id: 'Bit yang berbeda di antara kedua cipherteks: {bits} / {total}',
      pt: 'Bits diferentes entre os dois textos cifrados: {bits} / {total}',
    },
    'caption.total': {
      en: 'Blocks that differ: {blocks} / {n} · differing bits in all: {sum} / {all}',
      ko: '다른 덩어리: {blocks} / {n} · 다른 비트 합: {sum} / {all}',
      ja: '異なるブロック: {blocks} / {n} · 異なるビットの合計: {sum} / {all}',
      zh: '不同的分组: {blocks} / {n} · 不同比特合计: {sum} / {all}',
      ar: 'الكتل المختلفة: {blocks} / {n} · مجموع البتات المختلفة: {sum} / {all}',
      es: 'Bloques distintos: {blocks} / {n} · bits distintos en total: {sum} / {all}',
      fr: 'Blocs différents : {blocks} / {n} · bits différents au total : {sum} / {all}',
      hi: 'अलग ब्लॉक: {blocks} / {n} · कुल अलग बिट: {sum} / {all}',
      id: 'Blok yang berbeda: {blocks} / {n} · total bit berbeda: {sum} / {all}',
      pt: 'Blocos diferentes: {blocks} / {n} · bits diferentes no total: {sum} / {all}',
    },
    'label.side.a': {
      en: 'Sent first',
      ko: '첫 번째로 보낸 것',
      ja: '一回目に送ったもの',
      zh: '第一次发送',
      ar: 'المرسلة أولًا',
      es: 'Primer envío',
      fr: 'Premier envoi',
      hi: 'पहली बार भेजा',
      id: 'Kiriman pertama',
      pt: 'Primeiro envio',
    },
    'label.side.b': {
      en: 'Sent second',
      ko: '두 번째로 보낸 것',
      ja: '二回目に送ったもの',
      zh: '第二次发送',
      ar: 'المرسلة ثانيًا',
      es: 'Segundo envío',
      fr: 'Second envoi',
      hi: 'दूसरी बार भेजा',
      id: 'Kiriman kedua',
      pt: 'Segundo envio',
    },
    'label.iv': {
      en: 'IV',
      ko: 'IV',
      ja: 'IV',
      zh: 'IV',
      ar: 'IV',
      es: 'IV',
      fr: 'IV',
      hi: 'IV',
      id: 'IV',
      pt: 'IV',
    },
    'label.key': {
      en: 'Key (both sides)',
      ko: '열쇠 (두 쪽 같음)',
      ja: '鍵 (両側共通)',
      zh: '密钥(两边相同)',
      ar: 'المفتاح (للجانبين)',
      es: 'Clave (ambos lados)',
      fr: 'Clé (deux côtés)',
      hi: 'कुंजी (दोनों ओर)',
      id: 'Kunci (kedua sisi)',
      pt: 'Chave (ambos os lados)',
    },
    'label.box': {
      en: 'E',
      ko: 'E',
      ja: 'E',
      zh: 'E',
      ar: 'E',
      es: 'E',
      fr: 'E',
      hi: 'E',
      id: 'E',
      pt: 'E',
    },
    'label.block': {
      en: 'Block {i}',
      ko: '덩어리 {i}',
      ja: 'ブロック {i}',
      zh: '分组 {i}',
      ar: 'الكتلة {i}',
      es: 'Bloque {i}',
      fr: 'Bloc {i}',
      hi: 'ब्लॉक {i}',
      id: 'Blok {i}',
      pt: 'Bloco {i}',
    },
    'label.diff': {
      en: 'Differ: {bits} / {total}',
      ko: '다른 비트 {bits} / {total}',
      ja: '異なる: {bits} / {total}',
      zh: '不同: {bits} / {total}',
      ar: 'مختلفة: {bits} / {total}',
      es: 'Distintos: {bits} / {total}',
      fr: 'Différents : {bits} / {total}',
      hi: 'अलग: {bits} / {total}',
      id: 'Beda: {bits} / {total}',
      pt: 'Diferentes: {bits} / {total}',
    },
  },
  blocks: {
    stage: { type: 'iv-makes-different-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
