import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { GlobalIlluminationData } from './algorithm.js';

/**
 * 평면 래디오시티 방 — x 오른쪽 · y 위, 방 0..4 × 0..4, 벽마다 길이 1 인 패치 넷.
 * 형태 계수 · B · 더한 빛 · 쌓인 반사광 · 바닥 평균 · R − B · 멈춘 튐은 알고리즘이 셈한다.
 */
export const globalIlluminationData: GlobalIlluminationData = {
  type: 'global-illumination',
  stepMs: 1200,
  patches: [
    // 바닥 왼쪽 → 오른쪽
    { id: 'f1', kind: 'floor', a: [0, 0], b: [1, 0] },
    { id: 'f2', kind: 'floor', a: [1, 0], b: [2, 0] },
    { id: 'f3', kind: 'floor', a: [2, 0], b: [3, 0] },
    { id: 'f4', kind: 'floor', a: [3, 0], b: [4, 0] },
    // 오른벽 아래 → 위
    { id: 'r1', kind: 'green', a: [4, 0], b: [4, 1] },
    { id: 'r2', kind: 'green', a: [4, 1], b: [4, 2] },
    { id: 'r3', kind: 'green', a: [4, 2], b: [4, 3] },
    { id: 'r4', kind: 'green', a: [4, 3], b: [4, 4] },
    // 천장 왼쪽 → 오른쪽
    { id: 'c1', kind: 'ceiling', a: [0, 4], b: [1, 4] },
    { id: 'c2', kind: 'ceiling', a: [1, 4], b: [2, 4] },
    { id: 'c3', kind: 'ceiling', a: [2, 4], b: [3, 4] },
    { id: 'c4', kind: 'ceiling', a: [3, 4], b: [4, 4] },
    // 왼벽 아래 → 위
    { id: 'l1', kind: 'red', a: [0, 0], b: [0, 1] },
    { id: 'l2', kind: 'red', a: [0, 1], b: [0, 2] },
    { id: 'l3', kind: 'red', a: [0, 2], b: [0, 3] },
    { id: 'l4', kind: 'red', a: [0, 3], b: [0, 4] },
  ],
  emitters: ['c2', 'c3'],
  emission: [1, 1, 1],
  tints: { floor: [1, 1, 1], ceiling: [1, 1, 1], red: [1, 0, 0], green: [0, 1, 0] },
  rhos: [0.2, 0.5, 0.6, 0.75, 0.85],
  initialRho: 0.6,
  tolerance: 0.01,
  maxBounces: 12,
  chart: { bounces: 8, light: 0.35 },
  floorKind: 'floor',
  probe: 'f1',
};

export const globalIlluminationFacet: FacetJson = {
  id: 'facet:globalIllumination',
  title: {
    en: 'Global Illumination',
    ko: '전역 조명',
    ja: '大域照明',
    zh: '全局光照',
    ar: 'الإضاءة الشاملة',
    es: 'Iluminación global',
    fr: 'Illumination globale',
    hi: 'वैश्विक प्रदीपन',
    id: 'Iluminasi global',
    pt: 'Iluminação global',
  },
  description: {
    en: 'Each time light bounces it is multiplied by the reflectance, so the light added to the whole room shrinks and the total settles. In this 2D radiosity room, raising the reflectance from 0.2 to 0.85 raises the bounces needed to settle from 4 to 8, the final floor mean from 0.045 to 0.272, and the red that the red wall leaves on the left of the white floor (R − B) from 0.003 to 0.116.',
    ko: '빛이 튈 때마다 반사율이 곱해져 방 전체로 더하는 빛이 줄며 모인다. 이 평면 래디오시티 방에서 반사율을 0.2 에서 0.85 로 올리면 모이는 데 드는 튐이 4 에서 8 로, 끝 바닥 평균이 0.045 에서 0.272 로, 빨간 벽이 흰 바닥 왼쪽에 묻힌 붉은 기(R − B)가 0.003 에서 0.116 으로 는다.',
    ja: '光は跳ね返るたびに反射率を掛けられ、部屋全体に加わる光が減って収束する。この平面ラジオシティの部屋で反射率を 0.2 から 0.85 に上げると、収束までの跳ね返り回数は 4 から 8 に、最終的な床の平均は 0.045 から 0.272 に、赤い壁が白い床の左端に残す赤み(R − B)は 0.003 から 0.116 に増える。',
    zh: '光每反弹一次就乘上一次反射率，整个房间新增的光越来越少并收敛。在这个平面辐射度房间里，把反射率从 0.2 调到 0.85，收敛所需的反弹次数从 4 增到 8，最终地板平均从 0.045 增到 0.272，红墙染在白地板左端的红色（R − B）从 0.003 增到 0.116。',
    ar: 'في كل ارتداد يُضرب الضوء في معامل الانعكاس، فيقلّ الضوء المضاف إلى الغرفة كلها ويستقر المجموع. في غرفة الإشعاعية المستوية هذه، رفع معامل الانعكاس من 0.2 إلى 0.85 يرفع عدد الارتدادات اللازمة للاستقرار من 4 إلى 8، ومتوسط الأرضية النهائي من 0.045 إلى 0.272، والحمرة التي يتركها الجدار الأحمر على يسار الأرضية البيضاء (R − B) من 0.003 إلى 0.116.',
    es: 'Cada vez que la luz rebota se multiplica por la reflectancia, así que la luz añadida a toda la sala disminuye y el total converge. En esta sala de radiosidad plana, subir la reflectancia de 0.2 a 0.85 sube los rebotes necesarios de 4 a 8, la media final del suelo de 0.045 a 0.272 y el rojo que la pared roja deja a la izquierda del suelo blanco (R − B) de 0.003 a 0.116.',
    fr: 'À chaque rebond, la lumière est multipliée par la réflectance : la lumière ajoutée à toute la pièce diminue et le total converge. Dans cette pièce de radiosité plane, faire passer la réflectance de 0.2 à 0.85 fait passer les rebonds nécessaires de 4 à 8, la moyenne finale du sol de 0.045 à 0.272 et le rouge que le mur rouge dépose à gauche du sol blanc (R − B) de 0.003 à 0.116.',
    hi: 'हर उछाल पर प्रकाश परावर्तकता से गुणा होता है, इसलिए पूरे कमरे में जुड़ने वाला प्रकाश घटता है और कुल स्थिर हो जाता है। इस समतल रेडियोसिटी कमरे में परावर्तकता 0.2 से 0.85 करने पर स्थिर होने के लिए लगने वाले उछाल 4 से 8, अंतिम फ़र्श औसत 0.045 से 0.272 और लाल दीवार द्वारा सफ़ेद फ़र्श के बाएँ सिरे पर छोड़ी गई लाली (R − B) 0.003 से 0.116 हो जाती है।',
    id: 'Setiap kali cahaya memantul, ia dikalikan reflektansi sehingga cahaya yang ditambahkan ke seluruh ruangan mengecil dan totalnya konvergen. Di ruang radiositas datar ini, menaikkan reflektansi dari 0.2 ke 0.85 menaikkan jumlah pantulan sampai konvergen dari 4 ke 8, rata-rata lantai akhir dari 0.045 ke 0.272, dan merah yang ditinggalkan dinding merah di kiri lantai putih (R − B) dari 0.003 ke 0.116.',
    pt: 'A cada ressalto a luz é multiplicada pela refletância, então a luz somada à sala inteira diminui e o total converge. Nesta sala de radiosidade plana, subir a refletância de 0.2 para 0.85 sobe os ressaltos necessários de 4 para 8, a média final do piso de 0.045 para 0.272 e o vermelho que a parede vermelha deixa à esquerda do piso branco (R − B) de 0.003 para 0.116.',
  },
  algorithm: 'module:globalIllumination',
  projector: 'module:globalIlluminationProjector',
  initialData: globalIlluminationData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'global-illumination-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'reflectance',
          name: 'reflectance',
          label: {
            en: 'Reflectance',
            ko: '반사율',
            ja: '反射率',
            zh: '反射率',
            ar: 'معامل الانعكاس',
            es: 'Reflectancia',
            fr: 'Réflectance',
            hi: 'परावर्तकता',
            id: 'Reflektansi',
            pt: 'Refletância',
          },
          segments: [
            { value: 0.2, label: '0.2' },
            { value: 0.5, label: '0.5' },
            { value: 0.6, label: '0.6', default: true },
            { value: 0.75, label: '0.75' },
            { value: 0.85, label: '0.85' },
          ],
        },
      ],
      metrics: [
        {
          name: 'bounces',
          label: {
            en: 'Bounces',
            ko: '튐 수',
            ja: '跳ね返り回数',
            zh: '反弹次数',
            ar: 'عدد الارتدادات',
            es: 'Rebotes',
            fr: 'Rebonds',
            hi: 'उछाल',
            id: 'Pantulan',
            pt: 'Ressaltos',
          },
          initial: 0,
        },
        {
          name: 'floor-red',
          label: {
            en: 'Floor redness ×1000',
            ko: '바닥의 붉은 기 ×1000',
            ja: '床の赤み ×1000',
            zh: '地板红色 ×1000',
            ar: 'حمرة الأرضية ×1000',
            es: 'Rojo del suelo ×1000',
            fr: 'Rouge du sol ×1000',
            hi: 'फ़र्श की लाली ×1000',
            id: 'Merah lantai ×1000',
            pt: 'Vermelho do piso ×1000',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:global-illumination-imperative',
      label: {
        en: 'Radiosity',
        ko: '래디오시티',
        ja: 'ラジオシティ',
        zh: '辐射度',
        ar: 'الإشعاعية',
        es: 'Radiosidad',
        fr: 'Radiosité',
        hi: 'रेडियोसिटी',
        id: 'Radiositas',
        pt: 'Radiosidade',
      },
    },
  },
  messages: {
    'label.floor': { en: 'floor', ko: '바닥', ja: '床', zh: '地板', ar: 'الأرضية', es: 'suelo', fr: 'sol', hi: 'फ़र्श', id: 'lantai', pt: 'piso' },
    'label.ceiling': { en: 'ceiling', ko: '천장', ja: '天井', zh: '天花板', ar: 'السقف', es: 'techo', fr: 'plafond', hi: 'छत', id: 'langit-langit', pt: 'teto' },
    'label.red': { en: 'red wall', ko: '빨간 벽', ja: '赤い壁', zh: '红墙', ar: 'الجدار الأحمر', es: 'pared roja', fr: 'mur rouge', hi: 'लाल दीवार', id: 'dinding merah', pt: 'parede vermelha' },
    'label.green': { en: 'green wall', ko: '초록 벽', ja: '緑の壁', zh: '绿墙', ar: 'الجدار الأخضر', es: 'pared verde', fr: 'mur vert', hi: 'हरी दीवार', id: 'dinding hijau', pt: 'parede verde' },
    'label.light': { en: 'light', ko: '빛', ja: '光源', zh: '光源', ar: 'الضوء', es: 'luz', fr: 'lumière', hi: 'प्रकाश', id: 'cahaya', pt: 'luz' },
    'legend.bars': {
      en: 'Bars: R · G · B of each patch · one patch length = {axis}',
      ko: '막대: 패치마다 R · G · B · 패치 길이 하나 = {axis}',
      ja: '棒: パッチごとの R · G · B · パッチ 1 枚の長さ = {axis}',
      zh: '柱：每个面片的 R · G · B · 一个面片长 = {axis}',
      ar: 'الأعمدة: R · G · B لكل رقعة · طول رقعة واحدة = {axis}',
      es: 'Barras: R · G · B de cada parche · un parche de largo = {axis}',
      fr: 'Barres : R · G · B de chaque patch · une longueur de patch = {axis}',
      hi: 'स्तंभ: हर पैच के R · G · B · एक पैच की लंबाई = {axis}',
      id: 'Batang: R · G · B tiap patch · satu panjang patch = {axis}',
      pt: 'Barras: R · G · B de cada patch · um patch de comprimento = {axis}',
    },
    'legend.prev': {
      en: 'Dashed = previous run',
      ko: '점선 = 앞 판',
      ja: '点線 = 前の回',
      zh: '虚线 = 上一轮',
      ar: 'المتقطع = الجولة السابقة',
      es: 'Discontinua = pasada anterior',
      fr: 'Pointillés = passe précédente',
      hi: 'बिंदुदार = पिछला दौर',
      id: 'Putus-putus = putaran sebelumnya',
      pt: 'Tracejado = rodada anterior',
    },
    'stage.rho': { en: 'ρ {rho}', ko: 'ρ {rho}', ja: 'ρ {rho}', zh: 'ρ {rho}', ar: 'ρ {rho}', es: 'ρ {rho}', fr: 'ρ {rho}', hi: 'ρ {rho}', id: 'ρ {rho}', pt: 'ρ {rho}' },
    'probe.name': { en: 'floor 1', ko: '바닥 1', ja: '床 1', zh: '地板 1', ar: 'الأرضية 1', es: 'suelo 1', fr: 'sol 1', hi: 'फ़र्श 1', id: 'lantai 1', pt: 'piso 1' },
    'probe.bleed': {
      en: 'floor 1 · R − B {bleed}',
      ko: '바닥 1 · R − B {bleed}',
      ja: '床 1 · R − B {bleed}',
      zh: '地板 1 · R − B {bleed}',
      ar: 'الأرضية 1 · R − B {bleed}',
      es: 'suelo 1 · R − B {bleed}',
      fr: 'sol 1 · R − B {bleed}',
      hi: 'फ़र्श 1 · R − B {bleed}',
      id: 'lantai 1 · R − B {bleed}',
      pt: 'piso 1 · R − B {bleed}',
    },
    'axis.bounce': { en: 'bounce', ko: '튐', ja: '跳ね返り', zh: '反弹', ar: 'الارتداد', es: 'rebote', fr: 'rebond', hi: 'उछाल', id: 'pantulan', pt: 'ressalto' },
    'axis.floorMean': {
      en: 'floor mean',
      ko: '바닥 평균',
      ja: '床の平均',
      zh: '地板平均',
      ar: 'متوسط الأرضية',
      es: 'media del suelo',
      fr: 'moyenne du sol',
      hi: 'फ़र्श औसत',
      id: 'rata-rata lantai',
      pt: 'média do piso',
    },
    'caption.init': {
      en: 'Reflectance ρ {rho} · bounce 0: only the light patches glow',
      ko: '반사율 ρ {rho} · 튐 0: 빛 패치만 빛난다',
      ja: '反射率 ρ {rho} · 跳ね返り 0: 光源パッチだけが光る',
      zh: '反射率 ρ {rho} · 反弹 0：只有光源面片发光',
      ar: 'معامل الانعكاس ρ {rho} · الارتداد 0: رقع الضوء وحدها تضيء',
      es: 'Reflectancia ρ {rho} · rebote 0: solo brillan los parches de luz',
      fr: 'Réflectance ρ {rho} · rebond 0 : seuls les patchs lumineux brillent',
      hi: 'परावर्तकता ρ {rho} · उछाल 0: केवल प्रकाश पैच चमकते हैं',
      id: 'Reflektansi ρ {rho} · pantulan 0: hanya patch cahaya yang menyala',
      pt: 'Refletância ρ {rho} · ressalto 0: só os patches de luz brilham',
    },
    'caption.bounce': {
      en: 'Bounce {k} · added {added} · reflected {acc} · floor mean {floor} · floor 1 R − B {bleed}',
      ko: '튐 {k} · 더한 빛 {added} · 쌓인 반사광 {acc} · 바닥 평균 {floor} · 바닥 1 R − B {bleed}',
      ja: '跳ね返り {k} · 加わった光 {added} · 累積 {acc} · 床の平均 {floor} · 床 1 R − B {bleed}',
      zh: '反弹 {k} · 新增 {added} · 累计 {acc} · 地板平均 {floor} · 地板 1 R − B {bleed}',
      ar: 'الارتداد {k} · المضاف {added} · المتراكم {acc} · متوسط الأرضية {floor} · الأرضية 1 R − B {bleed}',
      es: 'Rebote {k} · añadida {added} · total {acc} · media suelo {floor} · suelo 1 R − B {bleed}',
      fr: 'Rebond {k} · ajout {added} · total {acc} · moyenne sol {floor} · sol 1 R − B {bleed}',
      hi: 'उछाल {k} · जोड़ा {added} · कुल {acc} · फ़र्श औसत {floor} · फ़र्श 1 R − B {bleed}',
      id: 'Pantulan {k} · tambah {added} · total {acc} · rata lantai {floor} · lantai 1 R − B {bleed}',
      pt: 'Ressalto {k} · somada {added} · total {acc} · média piso {floor} · piso 1 R − B {bleed}',
    },
    'caption.converged': {
      en: 'Stop: bounce {k} added {added} ≤ {tol} × {acc} = {limit}',
      ko: '멈춤: 튐 {k} · 더한 빛 {added} ≤ {tol} × {acc} = {limit}',
      ja: '停止: 跳ね返り {k} で加わった光 {added} ≤ {tol} × {acc} = {limit}',
      zh: '停止：反弹 {k} 新增 {added} ≤ {tol} × {acc} = {limit}',
      ar: 'توقف: المضاف في الارتداد {k} {added} ≤ {tol} × {acc} = {limit}',
      es: 'Parada: rebote {k} añadió {added} ≤ {tol} × {acc} = {limit}',
      fr: 'Arrêt : le rebond {k} ajoute {added} ≤ {tol} × {acc} = {limit}',
      hi: 'रुकना: उछाल {k} में जोड़ा {added} ≤ {tol} × {acc} = {limit}',
      id: 'Berhenti: pantulan {k} menambah {added} ≤ {tol} × {acc} = {limit}',
      pt: 'Parada: ressalto {k} somou {added} ≤ {tol} × {acc} = {limit}',
    },
    'channel.r': { en: 'R', ko: 'R', ja: 'R', zh: 'R', ar: 'R', es: 'R', fr: 'R', hi: 'R', id: 'R', pt: 'R' },
    'channel.g': { en: 'G', ko: 'G', ja: 'G', zh: 'G', ar: 'G', es: 'G', fr: 'G', hi: 'G', id: 'G', pt: 'G' },
    'channel.b': { en: 'B', ko: 'B', ja: 'B', zh: 'B', ar: 'B', es: 'B', fr: 'B', hi: 'B', id: 'B', pt: 'B' },
    'mark.stop': { en: 'stop', ko: '멈춤', ja: '停止', zh: '停止', ar: 'توقف', es: 'parada', fr: 'arrêt', hi: 'रुकना', id: 'berhenti', pt: 'parada' },
  },
};
