import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 커밋에 "됐다" 고 답하는 것은 언제이며, 그 뒤 전원이 나가도 왜 남는가.
 *
 * 커밋 기록이 메모리의 로그 버퍼에서 디스크의 로그 파일로 내려앉은 뒤에야 OK 가 돌아간다.
 * 고친 값은 메모리에만 있다가 충돌로 사라지고, 다시 켜면 로그 파일에서 데이터 파일로 다시 선다.
 */
export const durableAfterCommitFacet: FacetJson = {
  id: 'facet:durableAfterCommit',
  title: {
    en: 'Durable after commit',
    ko: '커밋 뒤에는 남는다',
    ja: 'コミット後は残る',
    zh: '提交之后即持久',
    ar: 'الدوام بعد الالتزام',
    es: 'Duradero tras el commit',
    fr: 'Durable après le commit',
    hi: 'कमिट के बाद टिकाऊ',
    id: 'Tahan setelah commit',
    pt: 'Durável após o commit',
  },
  description: {
    en: 'OK comes back only after the commit record lands in the log file on disk — so a crash cannot take it away.',
    ko: '커밋 기록이 디스크의 로그 파일에 내려앉은 뒤에야 OK 가 돌아간다. 그래서 충돌도 그것을 앗아 가지 못한다.',
    ja: 'コミット記録がディスクのログファイルに書き込まれてから初めて OK が返る。だからクラッシュしても消えない。',
    zh: '提交记录落到磁盘上的日志文件之后，OK 才会返回——所以崩溃也夺不走它。',
    ar: 'لا يعود OK إلا بعد أن يستقر سجل الالتزام في ملف السجل على القرص — لذلك لا يستطيع الانهيار أن يمحوه.',
    es: 'El OK vuelve solo cuando el registro de commit ya está en el archivo de log en disco; por eso un fallo no puede borrarlo.',
    fr: "Le OK ne revient qu'une fois l'enregistrement de commit posé dans le fichier journal sur disque — un crash ne peut donc pas l'effacer.",
    hi: 'OK तभी लौटता है जब कमिट रिकॉर्ड डिस्क की लॉग फ़ाइल में उतर जाता है — इसलिए क्रैश उसे मिटा नहीं सकता।',
    id: 'OK baru kembali setelah catatan commit mendarat di berkas log pada disk — jadi crash tidak bisa menghapusnya.',
    pt: 'O OK só volta depois que o registro de commit pousa no arquivo de log em disco — por isso uma falha não o apaga.',
  },
  algorithm: 'module:durableAfterCommit',
  scene: 'module:durableAfterCommitScene',
  initialData: {
    type: 'durable-after-commit',
    stepMs: 1100,
    rows: [
      { key: 'x', value: 100 },
      { key: 'y', value: 50 },
    ],
    events: [
      { op: 'write', txn: 'T1', key: 'x', value: 70 },
      { op: 'commit', txn: 'T1' },
      { op: 'write', txn: 'T2', key: 'y', value: 20 },
      { op: 'crash' },
      { op: 'restart' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has run yet. The data file on disk holds the starting values.',
      ko: '아직 아무것도 돌지 않았다. 디스크의 데이터 파일에 처음 값이 있다.',
      ja: 'まだ何も実行されていない。ディスクのデータファイルに初期値がある。',
      zh: '还什么都没执行。磁盘上的数据文件保存着初始值。',
      ar: 'لم يُنفَّذ شيء بعد. ملف البيانات على القرص يحمل القيم الأولى.',
      es: 'Aún no se ha ejecutado nada. El archivo de datos en disco guarda los valores iniciales.',
      fr: "Rien n'a encore tourné. Le fichier de données sur disque contient les valeurs de départ.",
      hi: 'अभी कुछ नहीं चला है। डिस्क की डेटा फ़ाइल में शुरुआती मान हैं।',
      id: 'Belum ada yang berjalan. Berkas data di disk menyimpan nilai awal.',
      pt: 'Nada rodou ainda. O arquivo de dados em disco guarda os valores iniciais.',
    },
    'caption.write': {
      en: '{op}: record LSN {lsn} goes to the log buffer, the new value to the buffer pool.',
      ko: '{op} — 기록 LSN {lsn}, 로그 버퍼로. 새 값은 버퍼 풀로.',
      ja: '{op}：記録 LSN {lsn} はログバッファへ、新しい値はバッファプールへ。',
      zh: '{op}：记录 LSN {lsn} 进入日志缓冲区，新值进入缓冲池。',
      ar: '{op}: السجل LSN {lsn} يذهب إلى مخزن السجل المؤقت، والقيمة الجديدة إلى مجمّع المخازن.',
      es: '{op}: el registro LSN {lsn} va al búfer de log; el valor nuevo, al búfer de páginas.',
      fr: '{op} : l’enregistrement LSN {lsn} va dans le tampon de journal, la nouvelle valeur dans le pool de tampons.',
      hi: '{op}: रिकॉर्ड LSN {lsn} लॉग बफ़र में जाता है, नया मान बफ़र पूल में।',
      id: '{op}: catatan LSN {lsn} masuk ke buffer log, nilai baru ke buffer pool.',
      pt: '{op}: o registro LSN {lsn} vai para o buffer de log; o novo valor, para o buffer pool.',
    },
    'caption.commit': {
      en: '{op}: commit record LSN {lsn} goes to the log buffer.',
      ko: '{op} — 커밋 기록 LSN {lsn}, 로그 버퍼로.',
      ja: '{op}：コミット記録 LSN {lsn} がログバッファへ。',
      zh: '{op}：提交记录 LSN {lsn} 进入日志缓冲区。',
      ar: '{op}: سجل الالتزام LSN {lsn} يذهب إلى مخزن السجل المؤقت.',
      es: '{op}: el registro de commit LSN {lsn} va al búfer de log.',
      fr: '{op} : l’enregistrement de commit LSN {lsn} va dans le tampon de journal.',
      hi: '{op}: कमिट रिकॉर्ड LSN {lsn} लॉग बफ़र में जाता है।',
      id: '{op}: catatan commit LSN {lsn} masuk ke buffer log.',
      pt: '{op}: o registro de commit LSN {lsn} vai para o buffer de log.',
    },
    'caption.flush': {
      en: 'The whole log buffer lands in the log file on disk. LSN: {lsns}',
      ko: '로그 버퍼 전부가 디스크의 로그 파일로 내려앉는다. LSN: {lsns}',
      ja: 'ログバッファ全体がディスクのログファイルへ降りる。LSN：{lsns}',
      zh: '整个日志缓冲区落到磁盘上的日志文件。LSN：{lsns}',
      ar: 'ينزل مخزن السجل المؤقت كله إلى ملف السجل على القرص. LSN: {lsns}',
      es: 'Todo el búfer de log baja al archivo de log en disco. LSN: {lsns}',
      fr: 'Tout le tampon de journal descend dans le fichier journal sur disque. LSN : {lsns}',
      hi: 'पूरा लॉग बफ़र डिस्क की लॉग फ़ाइल में उतरता है। LSN: {lsns}',
      id: 'Seluruh buffer log turun ke berkas log di disk. LSN: {lsns}',
      pt: 'Todo o buffer de log desce para o arquivo de log em disco. LSN: {lsns}',
    },
    'caption.ok': {
      en: 'Only now does OK go back. To: {txn}',
      ko: '이제야 OK 가 돌아간다. 받는 쪽: {txn}',
      ja: 'ここで初めて OK が返る。宛先：{txn}',
      zh: '直到此刻 OK 才返回。接收方：{txn}',
      ar: 'الآن فقط يعود OK. إلى: {txn}',
      es: 'Solo ahora vuelve el OK. Para: {txn}',
      fr: 'Ce n’est que maintenant que le OK revient. Pour : {txn}',
      hi: 'अब जाकर OK लौटता है। किसे: {txn}',
      id: 'Baru sekarang OK kembali. Kepada: {txn}',
      pt: 'Só agora o OK volta. Para: {txn}',
    },
    'caption.crash': {
      en: 'Crash. Memory is wiped: buffer pool and log buffer.',
      ko: '충돌. 메모리가 통째로 지워진다 — 버퍼 풀과 로그 버퍼.',
      ja: 'クラッシュ。メモリが丸ごと消える — バッファプールとログバッファ。',
      zh: '崩溃。内存被整个清空——缓冲池和日志缓冲区。',
      ar: 'انهيار. تُمحى الذاكرة كلها: مجمّع المخازن ومخزن السجل المؤقت.',
      es: 'Fallo. La memoria se borra entera: búfer de páginas y búfer de log.',
      fr: 'Crash. La mémoire est effacée : pool de tampons et tampon de journal.',
      hi: 'क्रैश। मेमोरी पूरी मिट जाती है: बफ़र पूल और लॉग बफ़र।',
      id: 'Crash. Memori terhapus seluruhnya: buffer pool dan buffer log.',
      pt: 'Falha. A memória é apagada: buffer pool e buffer de log.',
    },
    'caption.crashLsn': {
      en: 'Lost LSN: {lost}. Kept on disk, LSN: {kept}',
      ko: '사라진 LSN: {lost}. 디스크에 남은 LSN: {kept}',
      ja: '失われた LSN：{lost}。ディスクに残った LSN：{kept}',
      zh: '丢失的 LSN：{lost}。留在磁盘上的 LSN：{kept}',
      ar: 'LSN المفقودة: {lost}. الباقية على القرص، LSN: {kept}',
      es: 'LSN perdidos: {lost}. En disco quedan, LSN: {kept}',
      fr: 'LSN perdus : {lost}. Restés sur disque, LSN : {kept}',
      hi: 'खोए LSN: {lost}। डिस्क पर बचे LSN: {kept}',
      id: 'LSN yang hilang: {lost}. Tersisa di disk, LSN: {kept}',
      pt: 'LSN perdidos: {lost}. Ficam no disco, LSN: {kept}',
    },
    'caption.redo': {
      en: 'Restart: redo from the log file into the data file. LSN: {lsns}',
      ko: '다시 켜기 — 로그 파일에서 데이터 파일로 다시 한다. LSN: {lsns}',
      ja: '再起動：ログファイルからデータファイルへやり直す（redo）。LSN：{lsns}',
      zh: '重启：从日志文件重做到数据文件。LSN：{lsns}',
      ar: 'إعادة التشغيل: إعادة التنفيذ من ملف السجل إلى ملف البيانات. LSN: {lsns}',
      es: 'Reinicio: rehacer desde el archivo de log hacia el archivo de datos. LSN: {lsns}',
      fr: 'Redémarrage : refaire depuis le fichier journal vers le fichier de données. LSN : {lsns}',
      hi: 'फिर से चालू: लॉग फ़ाइल से डेटा फ़ाइल में दोबारा लागू करना। LSN: {lsns}',
      id: 'Nyala ulang: ulangi dari berkas log ke berkas data. LSN: {lsns}',
      pt: 'Reinício: refazer do arquivo de log para o arquivo de dados. LSN: {lsns}',
    },
    'caption.result': {
      en: 'Got OK: {ok}. Never got OK: {notOk}',
      ko: 'OK 를 받은 쪽: {ok}. 받지 못한 쪽: {notOk}',
      ja: 'OK を受け取った側：{ok}。受け取れなかった側：{notOk}',
      zh: '收到 OK 的：{ok}。没收到 OK 的：{notOk}',
      ar: 'تلقّى OK: {ok}. لم يتلقَّ OK: {notOk}',
      es: 'Recibió OK: {ok}. Nunca recibió OK: {notOk}',
      fr: 'A reçu OK : {ok}. N’a jamais reçu OK : {notOk}',
      hi: 'OK मिला: {ok}। OK नहीं मिला: {notOk}',
      id: 'Menerima OK: {ok}. Tidak pernah menerima OK: {notOk}',
      pt: 'Recebeu OK: {ok}. Nunca recebeu OK: {notOk}',
    },
    'label.lsn': {
      en: 'LSN {n}',
      ko: 'LSN {n}',
      ja: 'LSN {n}',
      zh: 'LSN {n}',
      ar: 'LSN {n}',
      es: 'LSN {n}',
      fr: 'LSN {n}',
      hi: 'LSN {n}',
      id: 'LSN {n}',
      pt: 'LSN {n}',
    },
    'label.memory': {
      en: 'Memory',
      ko: '메모리',
      ja: 'メモリ',
      zh: '内存',
      ar: 'الذاكرة',
      es: 'Memoria',
      fr: 'Mémoire',
      hi: 'मेमोरी',
      id: 'Memori',
      pt: 'Memória',
    },
    'label.memoryLost': {
      en: 'Memory — power lost',
      ko: '메모리 — 전원이 나갔다',
      ja: 'メモリ — 電源が落ちた',
      zh: '内存——断电',
      ar: 'الذاكرة — انقطعت الطاقة',
      es: 'Memoria — sin corriente',
      fr: 'Mémoire — courant coupé',
      hi: 'मेमोरी — बिजली गई',
      id: 'Memori — listrik padam',
      pt: 'Memória — sem energia',
    },
    'label.disk': {
      en: 'Disk',
      ko: '디스크',
      ja: 'ディスク',
      zh: '磁盘',
      ar: 'القرص',
      es: 'Disco',
      fr: 'Disque',
      hi: 'डिस्क',
      id: 'Disk',
      pt: 'Disco',
    },
    'label.bufferPool': {
      en: 'Buffer pool',
      ko: '버퍼 풀',
      ja: 'バッファプール',
      zh: '缓冲池',
      ar: 'مجمّع المخازن',
      es: 'Búfer de páginas',
      fr: 'Pool de tampons',
      hi: 'बफ़र पूल',
      id: 'Buffer pool',
      pt: 'Buffer pool',
    },
    'label.logBuffer': {
      en: 'Log buffer',
      ko: '로그 버퍼',
      ja: 'ログバッファ',
      zh: '日志缓冲区',
      ar: 'مخزن السجل المؤقت',
      es: 'Búfer de log',
      fr: 'Tampon de journal',
      hi: 'लॉग बफ़र',
      id: 'Buffer log',
      pt: 'Buffer de log',
    },
    'label.dataFile': {
      en: 'Data file',
      ko: '데이터 파일',
      ja: 'データファイル',
      zh: '数据文件',
      ar: 'ملف البيانات',
      es: 'Archivo de datos',
      fr: 'Fichier de données',
      hi: 'डेटा फ़ाइल',
      id: 'Berkas data',
      pt: 'Arquivo de dados',
    },
    'label.logFile': {
      en: 'Log file',
      ko: '로그 파일',
      ja: 'ログファイル',
      zh: '日志文件',
      ar: 'ملف السجل',
      es: 'Archivo de log',
      fr: 'Fichier journal',
      hi: 'लॉग फ़ाइल',
      id: 'Berkas log',
      pt: 'Arquivo de log',
    },
    'label.empty': {
      en: 'empty',
      ko: '비어 있음',
      ja: '空',
      zh: '空',
      ar: 'فارغ',
      es: 'vacío',
      fr: 'vide',
      hi: 'खाली',
      id: 'kosong',
      pt: 'vazio',
    },
    'label.ok': {
      en: 'OK',
      ko: 'OK',
      ja: 'OK',
      zh: 'OK',
      ar: 'OK',
      es: 'OK',
      fr: 'OK',
      hi: 'OK',
      id: 'OK',
      pt: 'OK',
    },
  },
  blocks: {
    stage: { type: 'durable-after-commit-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
