import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { SaveAndRestoreFacetData } from './algorithm.js';

const data: SaveAndRestoreFacetData = {
  type: 'save-and-restore',
  stepMs: 1100,
  programs: [
    { id: 'a', lines: ['let sum = 0', 'sum = sum + 3', 'sum = sum + 4', 'sum = sum + 5', 'show sum'] },
    { id: 'b', lines: ['let n = 10', 'n = n - 1', 'n = n - 1', 'show n'] },
  ],
  start: { owner: 'a', pc: 1, r: 0 },
  records: { a: null, b: { pc: 1, r: 0 } },
  plan: [
    { do: 'run', count: 2 },
    { do: 'save' },
    { do: 'restore', prog: 'b' },
    { do: 'run', count: 2 },
    { do: 'save' },
    { do: 'restore', prog: 'a' },
    { do: 'run', count: 3 },
  ],
};

/**
 * @piece
 * 질문: 한 CPU 를 번갈아 쓰는데 둘 다 제 계산을 틀리지 않고 이어 가는 것은 무엇을 적어 두기 때문인가
 */
export const saveAndRestoreFacet: FacetJson = {
  id: 'facet:saveAndRestore',
  title: {
    en: 'Save and restore',
    ko: '문맥 저장과 복원',
    ja: 'コンテキストの保存と復元',
    zh: '上下文的保存与恢复',
    ar: 'حفظ السياق واستعادته',
    es: 'Guardar y restaurar el contexto',
    fr: 'Sauvegarder et restaurer le contexte',
    hi: 'संदर्भ सहेजना और बहाल करना',
    id: 'Menyimpan dan memulihkan konteks',
    pt: 'Salvar e restaurar o contexto',
  },
  description: {
    en: 'Two programs take turns on one CPU. At each switch the numbers in pc and r are copied into a record, and the other record is copied back into the same cells.',
    ko: '두 프로그램이 CPU 하나를 번갈아 쓴다. 바꿀 때마다 pc 와 r 의 수가 기록으로 적히고, 다른 기록의 수가 같은 칸으로 꺼내진다.',
    ja: '二つのプログラムが一つのCPUを交代で使う。切り替えのたびにpcとrの数が記録に書き出され、もう一方の記録の数が同じ枠に読み込まれる。',
    zh: '两个程序轮流使用一个 CPU。每次切换时，pc 和 r 中的数被写入记录，另一份记录中的数被取回到同样的格子里。',
    ar: 'برنامجان يتناوبان على معالج واحد. عند كل تبديل تُنسخ أعداد pc و r إلى سجل، وتُعاد أعداد السجل الآخر إلى الخانتين نفسيهما.',
    es: 'Dos programas se turnan una CPU. En cada cambio, los números de pc y r se copian a una ficha y los de la otra ficha vuelven a las mismas celdas.',
    fr: 'Deux programmes se partagent un CPU à tour de rôle. À chaque bascule, les nombres de pc et r sont copiés dans une fiche, et ceux de l’autre fiche reviennent dans les mêmes cases.',
    hi: 'दो प्रोग्राम बारी-बारी से एक CPU चलाते हैं। हर अदला-बदली पर pc और r की संख्याएँ अभिलेख में लिखी जाती हैं, और दूसरे अभिलेख की संख्याएँ उन्हीं खानों में वापस आती हैं।',
    id: 'Dua program bergiliran memakai satu CPU. Setiap berganti, angka di pc dan r disalin ke catatan, dan angka dari catatan lain disalin kembali ke sel yang sama.',
    pt: 'Dois programas se revezam em uma CPU. A cada troca, os números de pc e r são copiados para uma ficha, e os da outra ficha voltam para as mesmas células.',
  },
  algorithm: 'module:saveAndRestore',
  scene: 'module:saveAndRestoreScene',
  initialData: data,
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Running on the CPU: {name}',
      ko: 'CPU 에서 도는 것: {name}',
      ja: 'CPUで実行中: {name}',
      zh: 'CPU 正在运行: {name}',
      ar: 'يعمل على المعالج: {name}',
      es: 'En la CPU: {name}',
      fr: 'Sur le CPU : {name}',
      hi: 'CPU पर चल रहा है: {name}',
      id: 'Berjalan di CPU: {name}',
      pt: 'Na CPU: {name}',
    },
    'caption.run': {
      en: '{name}, line {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      ko: '{name} · 줄 {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      ja: '{name} · {line}行目 — r {r0} → {r1} · pc {pc0} → {pc1}',
      zh: '{name} · 第 {line} 行 — r {r0} → {r1} · pc {pc0} → {pc1}',
      ar: '{name}، السطر {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      es: '{name}, línea {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      fr: '{name}, ligne {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      hi: '{name}, पंक्ति {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      id: '{name}, baris {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
      pt: '{name}, linha {line} — r {r0} → {r1} · pc {pc0} → {pc1}',
    },
    'caption.show': {
      en: '{name}, line {line} — shown: {value} · pc {pc0} → {pc1}',
      ko: '{name} · 줄 {line} — 보인 값: {value} · pc {pc0} → {pc1}',
      ja: '{name} · {line}行目 — 表示: {value} · pc {pc0} → {pc1}',
      zh: '{name} · 第 {line} 行 — 显示: {value} · pc {pc0} → {pc1}',
      ar: '{name}، السطر {line} — المعروض: {value} · pc {pc0} → {pc1}',
      es: '{name}, línea {line} — mostrado: {value} · pc {pc0} → {pc1}',
      fr: '{name}, ligne {line} — affiché : {value} · pc {pc0} → {pc1}',
      hi: '{name}, पंक्ति {line} — दिखाया: {value} · pc {pc0} → {pc1}',
      id: '{name}, baris {line} — ditampilkan: {value} · pc {pc0} → {pc1}',
      pt: '{name}, linha {line} — mostrado: {value} · pc {pc0} → {pc1}',
    },
    'caption.save': {
      en: 'Save {name} — record ← pc {pc} · r {r}',
      ko: '적기 · {name} — 기록 ← pc {pc} · r {r}',
      ja: '保存 · {name} — 記録 ← pc {pc} · r {r}',
      zh: '保存 · {name} — 记录 ← pc {pc} · r {r}',
      ar: 'حفظ {name} — السجل ← pc {pc} · r {r}',
      es: 'Guardar {name} — ficha ← pc {pc} · r {r}',
      fr: 'Enregistrer {name} — fiche ← pc {pc} · r {r}',
      hi: 'सहेजें {name} — अभिलेख ← pc {pc} · r {r}',
      id: 'Simpan {name} — catatan ← pc {pc} · r {r}',
      pt: 'Salvar {name} — ficha ← pc {pc} · r {r}',
    },
    'caption.restore': {
      en: 'Restore {name} — record → pc {pc} · r {r} · r overwritten: {was}',
      ko: '꺼내기 · {name} — 기록 → pc {pc} · r {r} · 덮인 r: {was}',
      ja: '復元 · {name} — 記録 → pc {pc} · r {r} · 上書きされた r: {was}',
      zh: '恢复 · {name} — 记录 → pc {pc} · r {r} · 被覆盖的 r: {was}',
      ar: 'استعادة {name} — السجل → pc {pc} · r {r} · r المستبدَل: {was}',
      es: 'Restaurar {name} — ficha → pc {pc} · r {r} · r sobrescrito: {was}',
      fr: 'Restaurer {name} — fiche → pc {pc} · r {r} · r écrasé : {was}',
      hi: 'बहाल करें {name} — अभिलेख → pc {pc} · r {r} · मिटाया गया r: {was}',
      id: 'Pulihkan {name} — catatan → pc {pc} · r {r} · r tertimpa: {was}',
      pt: 'Restaurar {name} — ficha → pc {pc} · r {r} · r sobrescrito: {was}',
    },
    'label.a': { en: 'A', ko: 'A', ja: 'A', zh: 'A', ar: 'A', es: 'A', fr: 'A', hi: 'A', id: 'A', pt: 'A' },
    'label.b': { en: 'B', ko: 'B', ja: 'B', zh: 'B', ar: 'B', es: 'B', fr: 'B', hi: 'B', id: 'B', pt: 'B' },
    'label.cpu': { en: 'CPU', ko: 'CPU', ja: 'CPU', zh: 'CPU', ar: 'المعالج', es: 'CPU', fr: 'CPU', hi: 'CPU', id: 'CPU', pt: 'CPU' },
    'label.cpuOwner': {
      en: 'CPU — {name}',
      ko: 'CPU — {name}',
      ja: 'CPU — {name}',
      zh: 'CPU — {name}',
      ar: 'المعالج — {name}',
      es: 'CPU — {name}',
      fr: 'CPU — {name}',
      hi: 'CPU — {name}',
      id: 'CPU — {name}',
      pt: 'CPU — {name}',
    },
    'label.pc': { en: 'pc', ko: 'pc', ja: 'pc', zh: 'pc', ar: 'pc', es: 'pc', fr: 'pc', hi: 'pc', id: 'pc', pt: 'pc' },
    'label.r': { en: 'r', ko: 'r', ja: 'r', zh: 'r', ar: 'r', es: 'r', fr: 'r', hi: 'r', id: 'r', pt: 'r' },
    'label.record': {
      en: 'Record of {name}',
      ko: '{name} 의 기록',
      ja: '{name} の記録',
      zh: '{name} 的记录',
      ar: 'سجل {name}',
      es: 'Ficha de {name}',
      fr: 'Fiche de {name}',
      hi: '{name} का अभिलेख',
      id: 'Catatan {name}',
      pt: 'Ficha de {name}',
    },
    'label.out': {
      en: '→ {value}',
      ko: '→ {value}',
      ja: '→ {value}',
      zh: '→ {value}',
      ar: '→ {value}',
      es: '→ {value}',
      fr: '→ {value}',
      hi: '→ {value}',
      id: '→ {value}',
      pt: '→ {value}',
    },
    'label.end': { en: 'end', ko: '끝', ja: '終了', zh: '结束', ar: 'النهاية', es: 'fin', fr: 'fin', hi: 'अंत', id: 'selesai', pt: 'fim' },
  },
  blocks: {
    stage: { type: 'save-and-restore-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
