import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { OverfittingData } from './algorithm.js';

/**
 * 1차 데이터 — 참 f = 6 + x − 5x² 에 잡음을 더해 한 자리로 반올림한 값 (값이 데이터다. 생성 식은 대조만).
 * 훈련 서른둘 (x, y, 처음 드는 n): 셋째 값이 8 인 점이 n 8, 8 · 16 인 점이 n 16, 모두가 n 32.
 * 검증 스물 (x, y) 은 맞춤에 쓰지 않는다. 오차 · 곡선 · 축 범위는 알고리즘이 셈한다.
 */
const initialData: OverfittingData = {
  type: 'overfitting',
  stepMs: 1600,
  train: [
    [-0.93, 0.0, 32], [-0.87, 1.6, 8], [-0.81, 2.5, 32], [-0.75, 2.1, 16], [-0.69, 2.1, 32], [-0.63, 3.3, 8],
    [-0.57, 4.1, 32], [-0.51, 4.8, 16], [-0.45, 3.8, 32], [-0.39, 4.1, 8], [-0.33, 5.5, 32], [-0.27, 5.6, 16],
    [-0.21, 6.5, 32], [-0.15, 6.3, 8], [-0.09, 5.8, 32], [-0.03, 5.8, 16], [0.03, 7.6, 32], [0.09, 5.9, 8],
    [0.15, 5.6, 32], [0.21, 5.3, 16], [0.27, 6.0, 32], [0.33, 5.9, 8], [0.39, 5.4, 32], [0.45, 5.4, 16],
    [0.51, 5.4, 32], [0.57, 5.4, 8], [0.63, 5.3, 32], [0.69, 4.4, 16], [0.75, 2.9, 32], [0.81, 4.0, 8],
    [0.87, 2.2, 32], [0.93, 2.5, 16],
  ],
  val: [
    [-0.95, -0.3], [-0.85, 1.5], [-0.75, 2.0], [-0.65, 3.4], [-0.55, 5.9], [-0.45, 4.5], [-0.35, 5.5],
    [-0.25, 4.6], [-0.15, 5.6], [-0.05, 6.3], [0.05, 6.0], [0.15, 6.3], [0.25, 6.0], [0.35, 5.1],
    [0.45, 5.8], [0.55, 4.6], [0.65, 5.7], [0.75, 3.6], [0.85, 3.6], [0.95, 2.4],
  ],
  pointsLadder: [8, 16, 32],
  degreeLadder: [0, 1, 2, 3, 4, 5, 6],
  points: 8,
  degree: 6,
};

export const overfittingFacet: FacetJson = {
  id: 'facet:overfitting',
  title: {
    en: 'Overfitting — number of points and flexibility',
    ko: '과적합 — 점 수와 유연함',
    ja: '過学習 — 点の数と柔軟さ',
    zh: '过拟合 — 点的数量与灵活度',
    ar: 'الإفراط في التوافق — عدد النقاط والمرونة',
    es: 'Sobreajuste — número de puntos y flexibilidad',
    fr: 'Surapprentissage — nombre de points et souplesse',
    hi: 'ओवरफ़िटिंग — बिंदुओं की संख्या और लचीलापन',
    id: 'Overfitting — jumlah titik dan kelenturan',
    pt: 'Sobreajuste — número de pontos e flexibilidade',
  },
  description: {
    en: 'A polynomial is fitted to the training points in one closed-form solve, and its error is measured on the training points and on twenty validation points. At degree 6, raising the training points from 8 to 16 to 32 brings the validation error down and the training error up, so the two error markers move closer.',
    ko: '다항식을 훈련 점에 닫힌 셈 한 번으로 맞추고, 그 오차를 훈련 점과 검증 점 스물에서 잰다. 차수 6 에서 훈련 점을 8 · 16 · 32 로 늘리면 검증 오차는 내려오고 훈련 오차는 올라와 두 오차 표지가 다가선다.',
    ja: '多項式を訓練点に閉じた計算一回で当てはめ、その誤差を訓練点と二十個の検証点で測る。次数 6 で訓練点を 8 · 16 · 32 と増やすと、検証誤差は下がり訓練誤差は上がって、二つの誤差の目印が近づく。',
    zh: '用一次闭式求解把多项式拟合到训练点上，再在训练点和二十个验证点上测量误差。在 6 次时，把训练点从 8 增加到 16 再到 32，验证误差下降、训练误差上升，两个误差标记相互靠近。',
    ar: 'يُوفَّق كثير حدود مع نقاط التدريب بحل مغلق واحد، ويُقاس خطؤه على نقاط التدريب وعلى عشرين نقطة تحقق. عند الدرجة 6، رفع نقاط التدريب من 8 إلى 16 إلى 32 يُنزل خطأ التحقق ويرفع خطأ التدريب، فتقترب علامتا الخطأ.',
    es: 'Un polinomio se ajusta a los puntos de entrenamiento con una única resolución cerrada, y su error se mide en los puntos de entrenamiento y en veinte puntos de validación. En grado 6, pasar de 8 a 16 a 32 puntos de entrenamiento baja el error de validación y sube el de entrenamiento, y las dos marcas de error se acercan.',
    fr: "Un polynôme est ajusté aux points d'entraînement par une seule résolution exacte, et son erreur est mesurée sur les points d'entraînement et sur vingt points de validation. Au degré 6, passer de 8 à 16 puis 32 points d'entraînement fait baisser l'erreur de validation et monter l'erreur d'entraînement : les deux repères d'erreur se rapprochent.",
    hi: 'एक बहुपद को प्रशिक्षण बिंदुओं पर एक ही बंद हल से बैठाया जाता है, और उसकी त्रुटि प्रशिक्षण बिंदुओं और बीस सत्यापन बिंदुओं पर मापी जाती है। घात 6 पर प्रशिक्षण बिंदु 8 से 16 से 32 करने पर सत्यापन त्रुटि घटती है और प्रशिक्षण त्रुटि बढ़ती है, और दोनों त्रुटि चिह्न पास आते हैं।',
    id: 'Sebuah polinomial dicocokkan ke titik latih dengan satu penyelesaian tertutup, lalu galatnya diukur pada titik latih dan pada dua puluh titik validasi. Pada derajat 6, menambah titik latih dari 8 ke 16 ke 32 menurunkan galat validasi dan menaikkan galat latih, sehingga kedua penanda galat saling mendekat.',
    pt: 'Um polinômio é ajustado aos pontos de treino com uma única resolução fechada, e seu erro é medido nos pontos de treino e em vinte pontos de validação. No grau 6, passar de 8 para 16 e 32 pontos de treino baixa o erro de validação e sobe o de treino, e as duas marcas de erro se aproximam.',
  },
  algorithm: 'module:overfitting',
  projector: 'module:overfittingProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'overfitting-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'points',
          name: 'points',
          label: {
            en: 'Training points',
            ko: '훈련 점 수',
            ja: '訓練点の数',
            zh: '训练点数',
            ar: 'نقاط التدريب',
            es: 'Puntos de entrenamiento',
            fr: "Points d'entraînement",
            hi: 'प्रशिक्षण बिंदु',
            id: 'Titik latih',
            pt: 'Pontos de treino',
          },
          segments: [
            { value: 8, label: '8', default: true },
            { value: 16, label: '16' },
            { value: 32, label: '32' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'degree',
          name: 'degree',
          label: {
            en: 'Degree',
            ko: '차수',
            ja: '次数',
            zh: '次数',
            ar: 'الدرجة',
            es: 'Grado',
            fr: 'Degré',
            hi: 'घात',
            id: 'Derajat',
            pt: 'Grau',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3' },
            { value: 4, label: '4' },
            { value: 5, label: '5' },
            { value: 6, label: '6', default: true },
          ],
        },
      ],
      metrics: [
        {
          name: 'train-points',
          label: {
            en: 'Training points',
            ko: '훈련 점',
            ja: '訓練点',
            zh: '训练点',
            ar: 'نقاط التدريب',
            es: 'Puntos de entrenamiento',
            fr: "Points d'entraînement",
            hi: 'प्रशिक्षण बिंदु',
            id: 'Titik latih',
            pt: 'Pontos de treino',
          },
          initial: 0,
        },
        {
          name: 'coefficients',
          label: {
            en: 'Coefficients',
            ko: '계수',
            ja: '係数',
            zh: '系数',
            ar: 'المعاملات',
            es: 'Coeficientes',
            fr: 'Coefficients',
            hi: 'गुणांक',
            id: 'Koefisien',
            pt: 'Coeficientes',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:overfitting-imperative',
      label: {
        en: 'Fit and both errors',
        ko: '맞춤과 두 오차',
        ja: '当てはめと二つの誤差',
        zh: '拟合与两种误差',
        ar: 'التوفيق والخطآن',
        es: 'Ajuste y los dos errores',
        fr: 'Ajustement et les deux erreurs',
        hi: 'फ़िट और दोनों त्रुटियाँ',
        id: 'Pencocokan dan kedua galat',
        pt: 'Ajuste e os dois erros',
      },
    },
  },
  messages: {
    'caption.points': {
      en: 'Training points: {n} · Validation points: {m} · Degree: {d}',
      ko: '훈련 점: {n} 개 · 검증 점: {m} 개 · 차수: {d}',
      ja: '訓練点: {n} 個 · 検証点: {m} 個 · 次数: {d}',
      zh: '训练点: {n} 个 · 验证点: {m} 个 · 次数: {d}',
      ar: 'نقاط التدريب: {n} · نقاط التحقق: {m} · الدرجة: {d}',
      es: 'Puntos de entrenamiento: {n} · Puntos de validación: {m} · Grado: {d}',
      fr: "Points d'entraînement : {n} · Points de validation : {m} · Degré : {d}",
      hi: 'प्रशिक्षण बिंदु: {n} · सत्यापन बिंदु: {m} · घात: {d}',
      id: 'Titik latih: {n} · Titik validasi: {m} · Derajat: {d}',
      pt: 'Pontos de treino: {n} · Pontos de validação: {m} · Grau: {d}',
    },
    'caption.fit': {
      en: 'Fitted on the training points only · Coefficients: {k}',
      ko: '훈련 점만으로 맞춘 곡선 · 계수: {k} 개',
      ja: '訓練点だけで当てはめた曲線 · 係数: {k} 個',
      zh: '只用训练点拟合的曲线 · 系数: {k} 个',
      ar: 'منحنى موفَّق على نقاط التدريب وحدها · المعاملات: {k}',
      es: 'Ajustada solo con los puntos de entrenamiento · Coeficientes: {k}',
      fr: "Ajustée sur les seuls points d'entraînement · Coefficients : {k}",
      hi: 'केवल प्रशिक्षण बिंदुओं पर बैठाया वक्र · गुणांक: {k}',
      id: 'Dicocokkan hanya pada titik latih · Koefisien: {k}',
      pt: 'Ajustada só com os pontos de treino · Coeficientes: {k}',
    },
    'caption.train': {
      en: 'Training MSE: {v}',
      ko: '훈련 오차 MSE: {v}',
      ja: '訓練誤差 MSE: {v}',
      zh: '训练误差 MSE: {v}',
      ar: 'خطأ التدريب MSE: {v}',
      es: 'MSE de entrenamiento: {v}',
      fr: "MSE d'entraînement : {v}",
      hi: 'प्रशिक्षण MSE: {v}',
      id: 'MSE latih: {v}',
      pt: 'MSE de treino: {v}',
    },
    'caption.val': {
      en: 'Validation MSE: {v} · Training MSE: {tr}',
      ko: '검증 오차 MSE: {v} · 훈련 오차 MSE: {tr}',
      ja: '検証誤差 MSE: {v} · 訓練誤差 MSE: {tr}',
      zh: '验证误差 MSE: {v} · 训练误差 MSE: {tr}',
      ar: 'خطأ التحقق MSE: {v} · خطأ التدريب MSE: {tr}',
      es: 'MSE de validación: {v} · MSE de entrenamiento: {tr}',
      fr: "MSE de validation : {v} · MSE d'entraînement : {tr}",
      hi: 'सत्यापन MSE: {v} · प्रशिक्षण MSE: {tr}',
      id: 'MSE validasi: {v} · MSE latih: {tr}',
      pt: 'MSE de validação: {v} · MSE de treino: {tr}',
    },
    'label.trainPoints': {
      en: 'Training points',
      ko: '훈련 점',
      ja: '訓練点',
      zh: '训练点',
      ar: 'نقاط التدريب',
      es: 'Puntos de entrenamiento',
      fr: "Points d'entraînement",
      hi: 'प्रशिक्षण बिंदु',
      id: 'Titik latih',
      pt: 'Pontos de treino',
    },
    'label.valPoints': {
      en: 'Validation points',
      ko: '검증 점',
      ja: '検証点',
      zh: '验证点',
      ar: 'نقاط التحقق',
      es: 'Puntos de validación',
      fr: 'Points de validation',
      hi: 'सत्यापन बिंदु',
      id: 'Titik validasi',
      pt: 'Pontos de validação',
    },
    'label.curve': {
      en: 'Fitted curve',
      ko: '맞춘 곡선',
      ja: '当てはめた曲線',
      zh: '拟合曲线',
      ar: 'المنحنى الموفَّق',
      es: 'Curva ajustada',
      fr: 'Courbe ajustée',
      hi: 'बैठाया गया वक्र',
      id: 'Kurva hasil cocok',
      pt: 'Curva ajustada',
    },
    'label.gauge': {
      en: 'Error (MSE)',
      ko: '오차 (MSE)',
      ja: '誤差 (MSE)',
      zh: '误差 (MSE)',
      ar: 'الخطأ (MSE)',
      es: 'Error (MSE)',
      fr: 'Erreur (MSE)',
      hi: 'त्रुटि (MSE)',
      id: 'Galat (MSE)',
      pt: 'Erro (MSE)',
    },
    'label.formula': {
      en: 'MSE = Σ(ŷ − y)² / n',
      ko: 'MSE = Σ(ŷ − y)² / n',
      ja: 'MSE = Σ(ŷ − y)² / n',
      zh: 'MSE = Σ(ŷ − y)² / n',
      ar: 'MSE = Σ(ŷ − y)² / n',
      es: 'MSE = Σ(ŷ − y)² / n',
      fr: 'MSE = Σ(ŷ − y)² / n',
      hi: 'MSE = Σ(ŷ − y)² / n',
      id: 'MSE = Σ(ŷ − y)² / n',
      pt: 'MSE = Σ(ŷ − y)² / n',
    },
    'label.train': {
      en: 'Training',
      ko: '훈련',
      ja: '訓練',
      zh: '训练',
      ar: 'التدريب',
      es: 'Entrenamiento',
      fr: 'Entraînement',
      hi: 'प्रशिक्षण',
      id: 'Latih',
      pt: 'Treino',
    },
    'label.val': {
      en: 'Validation',
      ko: '검증',
      ja: '検証',
      zh: '验证',
      ar: 'التحقق',
      es: 'Validación',
      fr: 'Validation',
      hi: 'सत्यापन',
      id: 'Validasi',
      pt: 'Validação',
    },
  },
};
