/**
 * 카운팅 정렬 완결형 선언.
 *
 * 블록은 셋뿐이다 — `stage` · `controls` · `codePanel`. 제목 블록을 두지 않는다
 * (이름은 카탈로그 카드와 글의 문단이 준다). 미리보기 · 스냅샷 · 걸음 표시는
 * 빌트인 view 를 빌리지 않고 stage 가 직접 그린다.
 *
 * 이 facet 의 산출물은 그림이 아니라 **코드** 다. `ir:countingsort-stable` 하나가
 * 여섯 언어로 펼쳐지고, 재생 중인 phase 가 그 줄을 짚는다.
 *
 * 자료는 섞지 않는다 (`shuffleOnReset` 없음). 값 1 과 4 가 하나도 없다는 것이
 * 이 배치의 요점이라 — 빈 칸이 남고, 개수가 0 인 값이 앞 값과 같은 자리를 갖는
 * 장면이 거기서 나온다 — 섞으면 그것이 사라진다.
 *
 * 식별자 (C1): `index:<i>`.
 */

import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const countingSortFacet: FacetJson = {
  id: 'facet:countingSort',
  // 제목은 카탈로그 카드의 이름과 같다 (C4 명명 규칙 5).
  title: {
    en: 'Counting Sort',
    ko: '카운팅 정렬',
    ar: 'ترتيب العدّ',
    es: 'Ordenamiento por conteo',
    fr: 'Tri par comptage',
    hi: 'काउंटिंग सॉर्ट',
    id: 'Pengurutan hitung',
    pt: 'Ordenação por contagem',
  },
  description: {
    en: 'Never compares two values — it counts them, adds the counts up, and seats each one.',
    ko: '값을 견주지 않는다 — 세고, 더해서 자리를 얻고, 그 자리에 놓는다',
    ar: 'لا يقارن قيمتين أبدًا — بل يعدّها، ويجمع الأعداد، ويضع كل قيمة في مقعدها.',
    es: 'Nunca compara dos valores: los cuenta, suma los conteos y sienta cada uno en su sitio.',
    fr: 'Ne compare jamais deux valeurs — il les compte, cumule les comptes et place chacune à son siège.',
    hi: 'यह दो मानों की तुलना कभी नहीं करता — गिनता है, गिनतियाँ जोड़ता है, और हर मान को उसकी सीट पर बैठाता है।',
    id: 'Tidak pernah membandingkan dua nilai — ia menghitungnya, menjumlahkan hitungan, lalu mendudukkan tiap nilai.',
    pt: 'Nunca compara dois valores — conta-os, soma as contagens e senta cada um no seu lugar.',
  },
  algorithm: 'module:countingSort',
  projector: 'module:countingSortProjector',
  // 사양이 정한 자료. 값은 0..5 이고 1 과 4 는 하나도 없다.
  initialData: { type: 'array', values: [2, 5, 3, 0, 2, 3, 0, 3], range: 6 },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    stage: { type: 'counting-sort-stage' },
    controls: {
      type: 'control-bar',
      controls: CONTROL_SET.playback,
      metrics: [
        {
          name: 'count-count',
          label: {
            en: 'Count',
            ko: '세기',
            ar: 'عدّ',
            es: 'Conteo',
            fr: 'Comptage',
            hi: 'गिनती',
            id: 'Hitung',
            pt: 'Contagem',
          },
          initial: 0,
        },
        {
          name: 'place-count',
          label: {
            en: 'Place',
            ko: '놓기',
            ar: 'وضع',
            es: 'Colocación',
            fr: 'Placement',
            hi: 'रखना',
            id: 'Penempatan',
            pt: 'Colocação',
          },
          initial: 0,
        },
        {
          // 끝까지 0 이다. 그것이 이 facet 이 하려는 말이라 자리를 비워 두지 않는다.
          name: 'compare-count',
          label: {
            en: 'Compare',
            ko: '견줌',
            ar: 'مقارنة',
            es: 'Comparar',
            fr: 'Comparer',
            hi: 'तुलना',
            id: 'Banding',
            pt: 'Comparar',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      label: {
        en: 'Code',
        ko: '코드',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
      ir: 'ir:countingsort-stable',
    },
  },
  messages: {
    'label.input': {
      en: 'input',
      ko: '입력',
      ar: 'الدخل',
      es: 'entrada',
      fr: 'entrée',
      hi: 'इनपुट',
      id: 'masukan',
      pt: 'entrada',
    },
    'label.value': {
      en: 'value',
      ko: '값',
      ar: 'القيمة',
      es: 'valor',
      fr: 'valeur',
      hi: 'मान',
      id: 'nilai',
      pt: 'valor',
    },
    'label.count': {
      en: 'count',
      ko: '개수',
      ar: 'العدد',
      es: 'conteo',
      fr: 'compte',
      hi: 'गिनती',
      id: 'jumlah',
      pt: 'contagem',
    },
    'label.start': {
      en: 'start',
      ko: '시작 자리',
      ar: 'البداية',
      es: 'inicio',
      fr: 'début',
      hi: 'शुरुआत',
      id: 'awal',
      pt: 'início',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ar: 'الخرج',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
    'step.count': {
      en: '1. count',
      ko: '1. 세기',
      ar: '1. العدّ',
      es: '1. contar',
      fr: '1. compter',
      hi: '1. गिनें',
      id: '1. hitung',
      pt: '1. contar',
    },
    'step.prefix': {
      en: '2. add up',
      ko: '2. 누적합',
      ar: '2. الجمع',
      es: '2. acumular',
      fr: '2. cumuler',
      hi: '2. जोड़ें',
      id: '2. jumlahkan',
      pt: '2. acumular',
    },
    'step.place': {
      en: '3. place',
      ko: '3. 놓기',
      ar: '3. الوضع',
      es: '3. colocar',
      fr: '3. placer',
      hi: '3. रखें',
      id: '3. tempatkan',
      pt: '3. colocar',
    },
    'caption.start': {
      en: 'No value is ever compared with another. Count first, then place.',
      ko: '값을 다른 값과 견주지 않는다. 먼저 세고, 그 다음에 놓는다',
      ar: 'لا تُقارن أي قيمة بأخرى. عُدّ أولًا ثم ضَع.',
      es: 'Ningún valor se compara con otro. Primero contar, después colocar.',
      fr: "Aucune valeur n'est comparée à une autre. D'abord compter, ensuite placer.",
      hi: 'किसी मान की तुलना दूसरे से नहीं होती। पहले गिनें, फिर रखें।',
      id: 'Tidak ada nilai yang dibandingkan dengan nilai lain. Hitung dulu, baru tempatkan.',
      pt: 'Nenhum valor é comparado com outro. Primeiro contar, depois colocar.',
    },
    'caption.alloc': {
      en: 'Make one slot per value and one seat per item.',
      ko: '값마다 칸 하나, 항목마다 자리 하나를 마련한다',
      ar: 'جهّز خانة لكل قيمة ومقعدًا لكل عنصر.',
      es: 'Prepara una casilla por valor y un asiento por elemento.',
      fr: 'Prépare une case par valeur et un siège par élément.',
      hi: 'हर मान के लिए एक खाना और हर वस्तु के लिए एक सीट बनाएँ।',
      id: 'Siapkan satu slot untuk tiap nilai dan satu kursi untuk tiap item.',
      pt: 'Prepare uma casa por valor e um assento por item.',
    },
    'caption.readForCount': {
      en: 'Read {value} — one more for its slot.',
      ko: '{value} 를 읽는다 — 그 값의 칸에 하나 더',
      ar: 'اقرأ {value} — واحد إضافي لخانته.',
      es: 'Lee {value}: uno más para su casilla.',
      fr: 'Lit {value} — un de plus pour sa case.',
      hi: '{value} पढ़ें — उसके खाने में एक और।',
      id: 'Baca {value} — satu lagi untuk slotnya.',
      pt: 'Lê {value} — mais um para a sua casa.',
    },
    'caption.count': {
      en: 'Slot {value} now holds {count}.',
      ko: '{value} 칸의 개수가 {count} 가 됐다',
      ar: 'خانة {value} صارت تحمل {count}.',
      es: 'La casilla {value} ya contiene {count}.',
      fr: 'La case {value} contient maintenant {count}.',
      hi: 'खाना {value} में अब {count} है।',
      id: 'Slot {value} kini berisi {count}.',
      pt: 'A casa {value} contém agora {count}.',
    },
    'caption.countsDone': {
      en: 'Every item is counted. Slots nobody visited stay empty.',
      ko: '모두 셌다. 아무도 들르지 않은 칸은 빈 채로 남는다',
      ar: 'عُدّت كل العناصر. الخانات التي لم يزرها أحد تبقى فارغة.',
      es: 'Todo está contado. Las casillas que nadie visitó siguen vacías.',
      fr: "Tout est compté. Les cases que personne n'a visitées restent vides.",
      hi: 'सब कुछ गिना जा चुका है। जिन खानों में कोई नहीं आया, वे खाली रहते हैं।',
      id: 'Semua sudah dihitung. Slot yang tak dikunjungi siapa pun tetap kosong.',
      pt: 'Tudo contado. As casas que ninguém visitou continuam vazias.',
    },
    'caption.prefix': {
      en: 'Value {value} starts at seat {start}.',
      ko: '값 {value} 는 {start} 번 자리에서 시작한다',
      ar: 'القيمة {value} تبدأ عند المقعد {start}.',
      es: 'El valor {value} empieza en el asiento {start}.',
      fr: 'La valeur {value} commence au siège {start}.',
      hi: 'मान {value} सीट {start} से शुरू होता है।',
      id: 'Nilai {value} mulai di kursi {start}.',
      pt: 'O valor {value} começa no assento {start}.',
    },
    'caption.prefixEmpty': {
      en: 'Nothing of value {value} — seat {start} stays free for the next value.',
      ko: '값 {value} 는 하나도 없다 — {start} 번 자리는 다음 값에게 그대로 넘어간다',
      ar: 'لا وجود للقيمة {value} — المقعد {start} يبقى للقيمة التالية.',
      es: 'No hay ningún {value}: el asiento {start} queda para el siguiente valor.',
      fr: 'Aucun {value} — le siège {start} reste pour la valeur suivante.',
      hi: '{value} एक भी नहीं — सीट {start} अगले मान के लिए बची रहती है।',
      id: 'Tidak ada nilai {value} — kursi {start} tetap untuk nilai berikutnya.',
      pt: 'Não há nenhum {value} — o assento {start} fica para o valor seguinte.',
    },
    'caption.startsDone': {
      en: 'Every value knows its first seat. Now place them in order.',
      ko: '값마다 첫 자리를 얻었다. 이제 앞에서부터 놓는다',
      ar: 'كل قيمة تعرف مقعدها الأول. الآن ضَعها بالترتيب.',
      es: 'Cada valor conoce su primer asiento. Ahora colócalos en orden.',
      fr: "Chaque valeur connaît son premier siège. Place-les maintenant dans l'ordre.",
      hi: 'हर मान को उसकी पहली सीट पता है। अब उन्हें क्रम से रखें।',
      id: 'Tiap nilai tahu kursi pertamanya. Sekarang tempatkan berurutan.',
      pt: 'Cada valor conhece o seu primeiro assento. Agora coloque-os por ordem.',
    },
    'caption.readForPlace': {
      en: 'Read {value} — where does it sit?',
      ko: '{value} 를 읽는다 — 어느 자리인가',
      ar: 'اقرأ {value} — أين يجلس؟',
      es: 'Lee {value}: ¿dónde se sienta?',
      fr: 'Lit {value} — à quel siège ?',
      hi: '{value} पढ़ें — यह कहाँ बैठेगा?',
      id: 'Baca {value} — di mana ia duduk?',
      pt: 'Lê {value} — onde é que se senta?',
    },
    'caption.place': {
      en: '{value} takes seat {slot}.',
      ko: '{value} 가 {slot} 번 자리에 앉는다',
      ar: '{value} يأخذ المقعد {slot}.',
      es: '{value} ocupa el asiento {slot}.',
      fr: '{value} prend le siège {slot}.',
      hi: '{value} सीट {slot} पर बैठता है।',
      id: '{value} menempati kursi {slot}.',
      pt: '{value} ocupa o assento {slot}.',
    },
    'caption.advance': {
      en: 'Push the seat of {value} on to {start} — the next one waits there.',
      ko: '{value} 의 자리를 {start} 로 한 칸 민다 — 다음 {value} 는 거기서 기다린다',
      ar: 'ادفع مقعد {value} إلى {start} — التالي ينتظر هناك.',
      es: 'Empuja el asiento de {value} hasta {start}: el siguiente espera ahí.',
      fr: 'Décale le siège de {value} vers {start} — le suivant y attend.',
      hi: '{value} की सीट को {start} तक खिसकाएँ — अगला वहीं प्रतीक्षा करता है।',
      id: 'Geser kursi {value} ke {start} — yang berikutnya menunggu di sana.',
      pt: 'Empurre o assento de {value} para {start} — o próximo espera ali.',
    },
    'caption.done': {
      en: '{placements} placements, {comparisons} comparisons.',
      ko: '놓기 {placements} 번, 견줌 {comparisons} 번',
      ar: '{placements} عمليات وضع، {comparisons} مقارنات.',
      es: '{placements} colocaciones, {comparisons} comparaciones.',
      fr: '{placements} placements, {comparisons} comparaisons.',
      hi: '{placements} बार रखा गया, {comparisons} तुलनाएँ।',
      id: '{placements} penempatan, {comparisons} perbandingan.',
      pt: '{placements} colocações, {comparisons} comparações.',
    },
  },
};
