/**
 * @piece
 * 질문: 카메라가 세상 속 어느 자리에서 어느 쪽을 볼 때, 세상의 점들을 "눈에서 본 좌표" 로 바꾸면
 * 무슨 일이 일어나는가 — 세상이 통째로 옮겨 가고 돌아 눈이 원점 · 앞이 −z 에 서고, 점마다 z 의 부호로
 * 눈의 앞인지 뒤인지 읽힌다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const worldToCameraFacet: FacetJson = {
  id: 'facet:worldToCamera',
  title: {
    en: 'Move the world to the eye',
    ko: '눈이 있는 자리로 세상을 옮긴다',
    ja: '目のある場所へ世界を動かす',
    zh: '把世界移到眼睛所在的位置',
    ar: 'انقل العالم إلى موضع العين',
    es: 'Llevar el mundo hasta el ojo',
    fr: 'Amener le monde jusqu’à l’œil',
    hi: 'दुनिया को आँख की जगह तक ले जाना',
    id: 'Memindahkan dunia ke tempat mata',
    pt: 'Levar o mundo até o olho',
  },
  description: {
    en: 'The eye stays put and the whole world moves: first it shifts so the eye sits at the origin, then it turns so the eye looks down −z. Afterwards one number, z, tells whether each point is in front of the eye or behind it.',
    ko: '눈은 제자리에 있고 세상이 통째로 움직인다. 먼저 옮겨 가 눈이 원점에 서고, 이어 돌아 눈의 앞이 −z 에 눕는다. 그 뒤에는 z 하나로 점마다 눈의 앞인지 뒤인지 읽힌다.',
    ja: '目はそのままで、世界がまるごと動く。まず平行移動して目が原点に来て、次に回転して目の前方が −z を向く。その後は z ひとつで各点が目の前か後ろかが読める。',
    zh: '眼睛不动，整个世界在动：先平移让眼睛落在原点，再旋转让眼睛朝向 −z。之后只看 z 就能判断每个点在眼前还是眼后。',
    ar: 'تبقى العين مكانها ويتحرك العالم كله: أولاً ينزاح حتى تقع العين في الأصل، ثم يدور حتى تنظر العين نحو −z. بعدها يكفي رقم واحد، z، لمعرفة إن كانت كل نقطة أمام العين أم خلفها.',
    es: 'El ojo se queda quieto y se mueve el mundo entero: primero se desplaza hasta que el ojo queda en el origen, luego gira hasta que el ojo mira hacia −z. Después, un solo número, z, dice si cada punto está delante o detrás del ojo.',
    fr: 'L’œil reste en place et c’est le monde entier qui bouge : il se décale d’abord pour que l’œil soit à l’origine, puis il tourne pour que l’œil regarde vers −z. Ensuite, un seul nombre, z, dit si chaque point est devant ou derrière l’œil.',
    hi: 'आँख अपनी जगह रहती है और पूरी दुनिया हिलती है: पहले वह खिसकती है ताकि आँख मूल बिंदु पर आ जाए, फिर घूमती है ताकि आँख −z की ओर देखे। उसके बाद एक ही संख्या z बताती है कि हर बिंदु आँख के आगे है या पीछे।',
    id: 'Mata tetap di tempatnya dan seluruh dunia bergerak: pertama bergeser sampai mata berada di titik asal, lalu berputar sampai mata menghadap −z. Sesudahnya satu angka, z, menunjukkan apakah tiap titik ada di depan atau di belakang mata.',
    pt: 'O olho fica parado e o mundo inteiro se move: primeiro desliza até o olho ficar na origem, depois gira até o olho olhar para −z. Depois disso, um único número, z, diz se cada ponto está à frente ou atrás do olho.',
  },
  algorithm: 'module:worldToCamera',
  scene: 'module:worldToCameraScene',
  initialData: {
    type: 'world-to-camera',
    stepMs: 1500,
    eye: [2, 1, 5],
    yaw: 30,
    points: [
      { id: 'tree', at: [-1, 0, -2] },
      { id: 'house', at: [-3, 1, 1] },
      { id: 'rock', at: [5, 0, 7] },
      { id: 'lamp', at: [2, 2, 1] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Eye at {eye}, yaw {yaw}° · eye forward {forward}',
      ko: '눈의 자리 {eye} · yaw {yaw}° · 눈의 앞 {forward}',
      ja: '目の位置 {eye} · yaw {yaw}° · 目の前方 {forward}',
      zh: '眼睛位置 {eye} · yaw {yaw}° · 眼睛前方 {forward}',
      ar: 'موضع العين {eye} · yaw {yaw}° · اتجاه العين {forward}',
      es: 'Ojo en {eye}, yaw {yaw}° · frente del ojo {forward}',
      fr: 'Œil en {eye}, yaw {yaw}° · avant de l’œil {forward}',
      hi: 'आँख की जगह {eye} · yaw {yaw}° · आँख का आगे {forward}',
      id: 'Mata di {eye}, yaw {yaw}° · arah depan mata {forward}',
      pt: 'Olho em {eye}, yaw {yaw}° · frente do olho {forward}',
    },
    'caption.translate': {
      en: 'The whole world shifts by {offset} · eye now at {eye}',
      ko: '세상 전체를 {offset} 만큼 옮긴다 · 눈의 자리 {eye}',
      ja: '世界全体を {offset} だけ動かす · 目の位置 {eye}',
      zh: '整个世界平移 {offset} · 眼睛位置 {eye}',
      ar: 'ينزاح العالم كله بمقدار {offset} · موضع العين الآن {eye}',
      es: 'Todo el mundo se desplaza {offset} · ojo ahora en {eye}',
      fr: 'Le monde entier se décale de {offset} · œil maintenant en {eye}',
      hi: 'पूरी दुनिया {offset} खिसकती है · आँख अब {eye} पर',
      id: 'Seluruh dunia bergeser {offset} · mata kini di {eye}',
      pt: 'O mundo inteiro desliza {offset} · olho agora em {eye}',
    },
    'caption.rotate': {
      en: 'The whole world turns {angle}° about the y axis · eye forward now {forward}',
      ko: '세상 전체를 y 축 둘레로 {angle}° 돌린다 · 눈의 앞 {forward}',
      ja: '世界全体を y 軸まわりに {angle}° 回す · 目の前方 {forward}',
      zh: '整个世界绕 y 轴旋转 {angle}° · 眼睛前方 {forward}',
      ar: 'يدور العالم كله حول المحور y بزاوية {angle}° · اتجاه العين الآن {forward}',
      es: 'Todo el mundo gira {angle}° alrededor del eje y · frente del ojo ahora {forward}',
      fr: 'Le monde entier tourne de {angle}° autour de l’axe y · avant de l’œil maintenant {forward}',
      hi: 'पूरी दुनिया y अक्ष के चारों ओर {angle}° घूमती है · आँख का आगे अब {forward}',
      id: 'Seluruh dunia berputar {angle}° mengelilingi sumbu y · arah depan mata kini {forward}',
      pt: 'O mundo inteiro gira {angle}° em torno do eixo y · frente do olho agora {forward}',
    },
    'caption.judgeFront': {
      en: '{name}: camera z {z} < 0',
      ko: '{name}: 카메라 z {z} < 0',
      ja: '{name}: カメラ z {z} < 0',
      zh: '{name}: 相机 z {z} < 0',
      ar: '{name}: z في الكاميرا {z} < 0',
      es: '{name}: z de cámara {z} < 0',
      fr: '{name} : z caméra {z} < 0',
      hi: '{name}: कैमरा z {z} < 0',
      id: '{name}: z kamera {z} < 0',
      pt: '{name}: z da câmera {z} < 0',
    },
    'caption.judgeBehind': {
      en: '{name}: camera z {z} > 0',
      ko: '{name}: 카메라 z {z} > 0',
      ja: '{name}: カメラ z {z} > 0',
      zh: '{name}: 相机 z {z} > 0',
      ar: '{name}: z في الكاميرا {z} > 0',
      es: '{name}: z de cámara {z} > 0',
      fr: '{name} : z caméra {z} > 0',
      hi: '{name}: कैमरा z {z} > 0',
      id: '{name}: z kamera {z} > 0',
      pt: '{name}: z da câmera {z} > 0',
    },
    'label.tree': { en: 'Tree', ko: '나무', ja: '木', zh: '树', ar: 'شجرة', es: 'Árbol', fr: 'Arbre', hi: 'पेड़', id: 'Pohon', pt: 'Árvore' },
    'label.house': { en: 'House', ko: '집', ja: '家', zh: '房子', ar: 'بيت', es: 'Casa', fr: 'Maison', hi: 'घर', id: 'Rumah', pt: 'Casa' },
    'label.rock': { en: 'Rock', ko: '바위', ja: '岩', zh: '岩石', ar: 'صخرة', es: 'Roca', fr: 'Rocher', hi: 'चट्टान', id: 'Batu', pt: 'Rocha' },
    'label.lamp': { en: 'Lamp', ko: '가로등', ja: '街灯', zh: '路灯', ar: 'مصباح', es: 'Farola', fr: 'Lampadaire', hi: 'लैंप', id: 'Lampu', pt: 'Poste' },
    'label.eye': { en: 'Eye', ko: '눈', ja: '目', zh: '眼睛', ar: 'العين', es: 'Ojo', fr: 'Œil', hi: 'आँख', id: 'Mata', pt: 'Olho' },
    'label.origin': { en: 'Origin', ko: '원점', ja: '原点', zh: '原点', ar: 'الأصل', es: 'Origen', fr: 'Origine', hi: 'मूल बिंदु', id: 'Titik asal', pt: 'Origem' },
    'label.minusZ': { en: '−z', ko: '−z', ja: '−z', zh: '−z', ar: '−z', es: '−z', fr: '−z', hi: '−z', id: '−z', pt: '−z' },
    'label.front': { en: 'Front', ko: '앞', ja: '前', zh: '前', ar: 'أمام', es: 'Delante', fr: 'Devant', hi: 'आगे', id: 'Depan', pt: 'Frente' },
    'label.behind': { en: 'Behind', ko: '뒤', ja: '後ろ', zh: '后', ar: 'خلف', es: 'Detrás', fr: 'Derrière', hi: 'पीछे', id: 'Belakang', pt: 'Atrás' },
    'label.colX': { en: 'x', ko: 'x', ja: 'x', zh: 'x', ar: 'x', es: 'x', fr: 'x', hi: 'x', id: 'x', pt: 'x' },
    'label.colY': { en: 'y', ko: 'y', ja: 'y', zh: 'y', ar: 'y', es: 'y', fr: 'y', hi: 'y', id: 'y', pt: 'y' },
    'label.colZ': { en: 'z', ko: 'z', ja: 'z', zh: 'z', ar: 'z', es: 'z', fr: 'z', hi: 'z', id: 'z', pt: 'z' },
    'label.dist': { en: 'Dist.', ko: '거리', ja: '距離', zh: '距离', ar: 'المسافة', es: 'Dist.', fr: 'Dist.', hi: 'दूरी', id: 'Jarak', pt: 'Dist.' },
    'label.tally': {
      en: 'Front {front} · Behind {behind}',
      ko: '앞 {front} · 뒤 {behind}',
      ja: '前 {front} · 後ろ {behind}',
      zh: '前 {front} · 后 {behind}',
      ar: 'أمام {front} · خلف {behind}',
      es: 'Delante {front} · Detrás {behind}',
      fr: 'Devant {front} · Derrière {behind}',
      hi: 'आगे {front} · पीछे {behind}',
      id: 'Depan {front} · Belakang {behind}',
      pt: 'Frente {front} · Atrás {behind}',
    },
  },
  blocks: {
    stage: { type: 'world-to-camera-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
