import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 서버가 보낸 인증서를 믿어도 되는지, 클라이언트는 어디까지 거슬러 올라가 확인하는가?
 */
export const certificateChainFacet: FacetJson = {
  id: 'facet:certificateChain',
  title: {
    en: 'Climbing the certificate chain',
    ko: '인증서 사슬을 거슬러 오르기',
    ja: '証明書チェーンをさかのぼる',
    zh: '沿证书链向上验证',
    ar: 'الصعود في سلسلة الشهادات',
    es: 'Subir por la cadena de certificados',
    fr: 'Remonter la chaîne de certificats',
    hi: 'प्रमाणपत्र शृंखला में ऊपर चढ़ना',
    id: 'Menelusuri rantai sertifikat ke atas',
    pt: 'Subindo a cadeia de certificados',
  },
  description: {
    en: 'From the leaf certificate, the check follows each issuer one link up, until it reaches a root the client already trusts.',
    ko: '잎 인증서에서 발급자를 따라 한 칸씩 올라가, 클라이언트가 이미 믿는 뿌리에 닿으면 멈춘다.',
    ja: '葉の証明書から発行者をたどって一段ずつ上り、クライアントがすでに信頼するルートに着いたら止まる。',
    zh: '从叶证书出发，沿着签发者一级一级向上，直到到达客户端已经信任的根证书为止。',
    ar: 'من شهادة الورقة يتبع التحقق كل جهة إصدار خطوةً إلى الأعلى، حتى يبلغ جذرًا يثق به العميل مسبقًا.',
    es: 'Desde el certificado hoja, la verificación sigue a cada emisor un eslabón hacia arriba hasta llegar a una raíz en la que el cliente ya confía.',
    fr: "Depuis le certificat feuille, la vérification suit chaque émetteur d'un maillon vers le haut, jusqu'à une racine en laquelle le client a déjà confiance.",
    hi: 'लीफ़ प्रमाणपत्र से जाँच हर जारीकर्ता के पीछे एक कड़ी ऊपर जाती है, जब तक वह उस रूट तक न पहुँचे जिस पर क्लाइंट पहले से भरोसा करता है।',
    id: 'Dari sertifikat daun, pemeriksaan mengikuti setiap penerbit satu mata rantai ke atas, sampai tiba di akar yang sudah dipercaya klien.',
    pt: 'A partir do certificado folha, a verificação segue cada emissor um elo acima, até chegar a uma raiz em que o cliente já confia.',
  },
  algorithm: 'module:certificateChain',
  scene: 'module:certificateChainScene',
  initialData: {
    type: 'certificate-chain',
    stepMs: 1600,
    certs: [
      { id: 'leaf', subject: 'CN=shop.example', issuer: 'CN=Example Issuing CA', n: 2881, e: 5, sig: 528 },
      { id: 'inter', subject: 'CN=Example Issuing CA', issuer: 'CN=Example Root CA', n: 2773, e: 17, sig: 636 },
      { id: 'root', subject: 'CN=Example Root CA', n: 3233, e: 17 },
      { id: 'other', subject: 'CN=Other Root CA', n: 2627, e: 11 },
      { id: 'old', subject: 'CN=Old Root CA', n: 2263, e: 7 },
    ],
    bundle: ['leaf', 'inter'],
    store: ['other', 'root', 'old'],
  },
  shuffleOnReset: false,
  messages: {
    'label.client': {
      en: 'Client', ko: '클라이언트', ja: 'クライアント', zh: '客户端', ar: 'العميل',
      es: 'Cliente', fr: 'Client', hi: 'क्लाइंट', id: 'Klien', pt: 'Cliente',
    },
    'label.server': {
      en: 'Server', ko: '서버', ja: 'サーバー', zh: '服务器', ar: 'الخادم',
      es: 'Servidor', fr: 'Serveur', hi: 'सर्वर', id: 'Server', pt: 'Servidor',
    },
    'label.store': {
      en: 'Trust store', ko: '신뢰 저장소', ja: '信頼ストア', zh: '信任存储', ar: 'مخزن الثقة',
      es: 'Almacén de confianza', fr: 'Magasin de confiance', hi: 'ट्रस्ट स्टोर', id: 'Penyimpanan tepercaya', pt: 'Repositório confiável',
    },
    'label.bundle': {
      en: 'Received bundle', ko: '받은 꾸러미', ja: '受け取った束', zh: '收到的证书包', ar: 'الحزمة المستلمة',
      es: 'Paquete recibido', fr: 'Lot reçu', hi: 'प्राप्त बंडल', id: 'Bundel diterima', pt: 'Pacote recebido',
    },
    'label.key': {
      en: 'public key', ko: '공개 열쇠', ja: '公開鍵', zh: '公钥', ar: 'مفتاح عام',
      es: 'clave pública', fr: 'clé publique', hi: 'सार्वजनिक कुंजी', id: 'kunci publik', pt: 'chave pública',
    },
    'label.sig': {
      en: 'signature', ko: '서명', ja: '署名', zh: '签名', ar: 'توقيع',
      es: 'firma', fr: 'signature', hi: 'हस्ताक्षर', id: 'tanda tangan', pt: 'assinatura',
    },
    'caption.ready': {
      en: 'The server is about to send its certificates.',
      ko: '서버가 인증서를 보내려 한다.',
      ja: 'サーバーが証明書を送ろうとしている。',
      zh: '服务器即将发送它的证书。',
      ar: 'الخادم على وشك إرسال شهاداته.',
      es: 'El servidor está a punto de enviar sus certificados.',
      fr: "Le serveur s'apprête à envoyer ses certificats.",
      hi: 'सर्वर अपने प्रमाणपत्र भेजने वाला है।',
      id: 'Server akan mengirim sertifikatnya.',
      pt: 'O servidor está prestes a enviar seus certificados.',
    },
    'caption.receive': {
      en: 'Certificates received from the server: {n}',
      ko: '서버에게서 받은 인증서: {n}',
      ja: 'サーバーから受け取った証明書: {n}',
      zh: '从服务器收到的证书：{n}',
      ar: 'الشهادات المستلمة من الخادم: {n}',
      es: 'Certificados recibidos del servidor: {n}',
      fr: 'Certificats reçus du serveur : {n}',
      hi: 'सर्वर से मिले प्रमाणपत्र: {n}',
      id: 'Sertifikat yang diterima dari server: {n}',
      pt: 'Certificados recebidos do servidor: {n}',
    },
    'caption.findBundle': {
      en: 'Issuer {issuer} — found in the received bundle.',
      ko: '발급자 {issuer} — 받은 꾸러미에서 찾았다.',
      ja: '発行者 {issuer} — 受け取った束の中で見つかった。',
      zh: '签发者 {issuer} — 在收到的证书包中找到。',
      ar: 'جهة الإصدار {issuer} — وُجدت في الحزمة المستلمة.',
      es: 'Emisor {issuer}: encontrado en el paquete recibido.',
      fr: 'Émetteur {issuer} — trouvé dans le lot reçu.',
      hi: 'जारीकर्ता {issuer} — प्राप्त बंडल में मिला।',
      id: 'Penerbit {issuer} — ditemukan di bundel yang diterima.',
      pt: 'Emissor {issuer} — encontrado no pacote recebido.',
    },
    'caption.findStore': {
      en: 'Issuer {issuer} — not in the received bundle; found in the trust store.',
      ko: '발급자 {issuer} — 받은 꾸러미에는 없고, 신뢰 저장소에서 찾았다.',
      ja: '発行者 {issuer} — 受け取った束にはなく、信頼ストアで見つかった。',
      zh: '签发者 {issuer} — 不在收到的证书包里，在信任存储中找到。',
      ar: 'جهة الإصدار {issuer} — ليست في الحزمة المستلمة؛ وُجدت في مخزن الثقة.',
      es: 'Emisor {issuer}: no está en el paquete recibido; encontrado en el almacén de confianza.',
      fr: 'Émetteur {issuer} — absent du lot reçu ; trouvé dans le magasin de confiance.',
      hi: 'जारीकर्ता {issuer} — प्राप्त बंडल में नहीं; ट्रस्ट स्टोर में मिला।',
      id: 'Penerbit {issuer} — tidak ada di bundel yang diterima; ditemukan di penyimpanan tepercaya.',
      pt: 'Emissor {issuer} — não está no pacote recebido; encontrado no repositório confiável.',
    },
    'caption.verifyOk': {
      en: "Opened the signature with the issuer's public key — it matches the digest.",
      ko: '발급자의 공개 열쇠로 서명을 풀었다 — 요약과 맞다.',
      ja: '発行者の公開鍵で署名を開いた — 要約と一致する。',
      zh: '用签发者的公钥解开签名 — 与摘要一致。',
      ar: 'فُتح التوقيع بالمفتاح العام لجهة الإصدار — يطابق الملخص.',
      es: 'Se abrió la firma con la clave pública del emisor: coincide con el resumen.',
      fr: "Signature ouverte avec la clé publique de l'émetteur — elle correspond au condensé.",
      hi: 'जारीकर्ता की सार्वजनिक कुंजी से हस्ताक्षर खोला — सारांश से मेल खाता है।',
      id: 'Tanda tangan dibuka dengan kunci publik penerbit — cocok dengan ringkasan.',
      pt: 'A assinatura foi aberta com a chave pública do emissor — confere com o resumo.',
    },
    'caption.verifyBad': {
      en: "Opened the signature with the issuer's public key — it does not match. The climb stops.",
      ko: '발급자의 공개 열쇠로 서명을 풀었다 — 요약과 어긋난다. 오르기를 멈춘다.',
      ja: '発行者の公開鍵で署名を開いた — 一致しない。上りはここで止まる。',
      zh: '用签发者的公钥解开签名 — 不一致。向上验证就此停止。',
      ar: 'فُتح التوقيع بالمفتاح العام لجهة الإصدار — لا يطابق. يتوقف الصعود.',
      es: 'Se abrió la firma con la clave pública del emisor: no coincide. La subida se detiene.',
      fr: "Signature ouverte avec la clé publique de l'émetteur — elle ne correspond pas. La remontée s'arrête.",
      hi: 'जारीकर्ता की सार्वजनिक कुंजी से हस्ताक्षर खोला — मेल नहीं खाता। चढ़ना रुक जाता है।',
      id: 'Tanda tangan dibuka dengan kunci publik penerbit — tidak cocok. Pendakian berhenti.',
      pt: 'A assinatura foi aberta com a chave pública do emissor — não confere. A subida para.',
    },
    'caption.anchor': {
      en: 'Reached a certificate from the trust store — stop and trust it. Links in the chain: {n}',
      ko: '신뢰 저장소의 인증서에 닿았다 — 멈추고 믿는다. 사슬의 칸: {n}',
      ja: '信頼ストアの証明書に着いた — 止まって信頼する。チェーンの段数: {n}',
      zh: '到达信任存储中的证书 — 停下并信任它。链上的证书数：{n}',
      ar: 'وصلنا إلى شهادة من مخزن الثقة — نتوقف ونثق بها. حلقات السلسلة: {n}',
      es: 'Se llegó a un certificado del almacén de confianza: parar y confiar. Eslabones de la cadena: {n}',
      fr: 'Un certificat du magasin de confiance est atteint — on s’arrête et on lui fait confiance. Maillons de la chaîne : {n}',
      hi: 'ट्रस्ट स्टोर के प्रमाणपत्र तक पहुँचे — रुककर भरोसा करें। शृंखला की कड़ियाँ: {n}',
      id: 'Tiba di sertifikat dari penyimpanan tepercaya — berhenti dan percayai. Mata rantai: {n}',
      pt: 'Chegou a um certificado do repositório confiável — parar e confiar. Elos da cadeia: {n}',
    },
  },
  blocks: {
    stage: { type: 'certificate-chain-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
