/**
 * facet:rip — 라우팅 프로토콜 넷을 같은 다섯 고리 · 같은 끊김 위에서 견준다.
 *
 * initialData 는 구조뿐이다 — 라우터 · 선 · 목적지 · 방식 사다리 · 끊는 선 사다리. 표 · 참값 · 알림 수 ·
 * 틀린 표 여부는 알고리즘이 셈한다. 라우터 이름 · 망 주소는 번역하지 않는 자료다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { RipData } from './algorithm';

const initialData: RipData = {
  type: 'rip',
  stepMs: 900,
  motionMs: 500,
  routers: ['A', 'B', 'C', 'D', 'E'],
  links: [
    ['A', 'B'],
    ['B', 'E'],
    ['A', 'C'],
    ['C', 'D'],
    ['D', 'E'],
  ],
  dest: 'E',
  network: '172.20.0.0/16',
  unreachable: 16,
  methods: ['dv', 'dv-sh', 'pv', 'ls'],
  cutLadder: [
    [],
    [['B', 'E']],
    [
      ['B', 'E'],
      ['D', 'E'],
    ],
  ],
  defaultMethod: 0,
  defaultCut: 2,
  roundLimit: 40,
};

export const ripFacet: FacetJson = {
  id: 'facet:rip',
  title: {
    en: 'Routing protocols',
    ko: '라우팅 프로토콜',
    ja: 'ルーティングプロトコル',
    zh: '路由协议',
    ar: 'بروتوكولات التوجيه',
    es: 'Protocolos de enrutamiento',
    fr: 'Protocoles de routage',
    hi: 'राउटिंग प्रोटोकॉल',
    id: 'Protokol perutean',
    pt: 'Protocolos de roteamento',
  },
  description: {
    en: 'Distance vector, split horizon, path vector and link state on the same five-router ring and the same cut: how many rounds each keeps a wrong table, and how many adverts it spends.',
    ko: '거리 벡터 · 스플릿 호라이즌 · 경로 벡터 · 링크 상태를 같은 다섯 고리, 같은 끊김 위에서 견준다 — 틀린 표를 몇 라운드 쥐고 알림을 몇 개 쓰는가.',
    ja: '距離ベクトル・スプリットホライズン・パスベクトル・リンクステートを同じ五つの輪、同じ切断の上で比べる — 誤った表を何ラウンド持ち、広告をいくつ使うか。',
    zh: '在同一个五路由器环、同一处断开上比较距离矢量、水平分割、路径矢量和链路状态 —— 各自持有错误路由表多少轮，发出多少条通告。',
    ar: 'متجه المسافة والأفق المنقسم ومتجه المسار وحالة الوصلة على الحلقة نفسها من خمسة موجّهات والقطع نفسه: كم جولة يبقى الجدول خاطئًا، وكم إعلانًا يُرسل.',
    es: 'Vector de distancia, horizonte dividido, vector de ruta y estado de enlace sobre el mismo anillo de cinco routers y el mismo corte: cuántas rondas mantiene cada uno una tabla errónea y cuántos anuncios gasta.',
    fr: 'Vecteur de distance, horizon partagé, vecteur de chemin et état de lien sur le même anneau de cinq routeurs et la même coupure : combien de tours chacun garde une table fausse, et combien d’annonces il dépense.',
    hi: 'एक ही पाँच राउटर के घेरे और एक ही कटाव पर डिस्टेंस वेक्टर, स्प्लिट होराइज़न, पाथ वेक्टर और लिंक स्टेट की तुलना: हर तरीका कितने राउंड गलत तालिका रखता है और कितने विज्ञापन खर्च करता है।',
    id: 'Vektor jarak, split horizon, vektor jalur, dan status tautan pada cincin lima router yang sama dan putusan yang sama: berapa putaran masing-masing memegang tabel salah, dan berapa iklan yang dihabiskan.',
    pt: 'Vetor de distância, horizonte dividido, vetor de caminho e estado de enlace no mesmo anel de cinco roteadores e no mesmo corte: quantas rodadas cada um mantém uma tabela errada e quantos anúncios gasta.',
  },
  algorithm: 'module:rip',
  projector: 'module:ripProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'rip-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'method',
          name: 'method',
          label: {
            en: 'Method',
            ko: '방식',
            ja: '方式',
            zh: '方式',
            ar: 'الطريقة',
            es: 'Método',
            fr: 'Méthode',
            hi: 'तरीका',
            id: 'Metode',
            pt: 'Método',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: {
                en: 'Distance vector',
                ko: '거리 벡터',
                ja: '距離ベクトル',
                zh: '距离矢量',
                ar: 'متجه المسافة',
                es: 'Vector de distancia',
                fr: 'Vecteur de distance',
                hi: 'डिस्टेंस वेक्टर',
                id: 'Vektor jarak',
                pt: 'Vetor de distância',
              },
            },
            {
              value: 1,
              label: {
                en: 'Split horizon',
                ko: '스플릿 호라이즌',
                ja: 'スプリットホライズン',
                zh: '水平分割',
                ar: 'الأفق المنقسم',
                es: 'Horizonte dividido',
                fr: 'Horizon partagé',
                hi: 'स्प्लिट होराइज़न',
                id: 'Split horizon',
                pt: 'Horizonte dividido',
              },
            },
            {
              value: 2,
              label: {
                en: 'Path vector',
                ko: '경로 벡터',
                ja: 'パスベクトル',
                zh: '路径矢量',
                ar: 'متجه المسار',
                es: 'Vector de ruta',
                fr: 'Vecteur de chemin',
                hi: 'पाथ वेक्टर',
                id: 'Vektor jalur',
                pt: 'Vetor de caminho',
              },
            },
            {
              value: 3,
              label: {
                en: 'Link state',
                ko: '링크 상태',
                ja: 'リンクステート',
                zh: '链路状态',
                ar: 'حالة الوصلة',
                es: 'Estado de enlace',
                fr: 'État de lien',
                hi: 'लिंक स्टेट',
                id: 'Status tautan',
                pt: 'Estado de enlace',
              },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'cut',
          name: 'cut',
          label: {
            en: 'Cut links',
            ko: '끊는 선',
            ja: '切る線',
            zh: '断开的链路',
            ar: 'الوصلات المقطوعة',
            es: 'Enlaces cortados',
            fr: 'Liens coupés',
            hi: 'कटे लिंक',
            id: 'Tautan putus',
            pt: 'Enlaces cortados',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'From scratch',
                ko: '처음부터',
                ja: '最初から',
                zh: '从头开始',
                ar: 'من البداية',
                es: 'Desde cero',
                fr: 'Depuis zéro',
                hi: 'शुरू से',
                id: 'Dari awal',
                pt: 'Do zero',
              },
            },
            { value: 1, label: 'B–E' },
            { value: 2, label: 'B–E · D–E', default: true },
          ],
        },
      ],
      metrics: [
        {
          name: 'rounds',
          label: {
            en: 'Rounds',
            ko: '라운드',
            ja: 'ラウンド',
            zh: '轮次',
            ar: 'الجولات',
            es: 'Rondas',
            fr: 'Tours',
            hi: 'राउंड',
            id: 'Putaran',
            pt: 'Rodadas',
          },
          initial: 0,
        },
        {
          name: 'adverts',
          label: {
            en: 'Adverts',
            ko: '알림',
            ja: '広告',
            zh: '通告',
            ar: 'الإعلانات',
            es: 'Anuncios',
            fr: 'Annonces',
            hi: 'विज्ञापन',
            id: 'Iklan',
            pt: 'Anúncios',
          },
          initial: 0,
        },
        {
          name: 'wrong-rounds',
          label: {
            en: 'Wrong rounds',
            ko: '틀린 표 라운드',
            ja: '誤った表のラウンド',
            zh: '错误表轮次',
            ar: 'جولات الجدول الخاطئ',
            es: 'Rondas erróneas',
            fr: 'Tours faux',
            hi: 'गलत तालिका राउंड',
            id: 'Putaran tabel salah',
            pt: 'Rodadas erradas',
          },
          initial: 0,
        },
      ],
    },
  },
  messages: {
    'caption.startScratch': {
      en: 'Start: only router {dest} has a row for {net}',
      ko: '시작 — {net} 줄은 라우터 {dest} 만 가진다',
      ja: '開始 — {net} の行を持つのはルーター {dest} だけ',
      zh: '开始 —— 只有路由器 {dest} 有 {net} 的表项',
      ar: 'البداية: الموجّه {dest} وحده لديه سطر لـ {net}',
      es: 'Inicio: solo el router {dest} tiene una fila para {net}',
      fr: 'Départ : seul le routeur {dest} a une ligne pour {net}',
      hi: 'शुरुआत: {net} की पंक्ति केवल राउटर {dest} के पास है',
      id: 'Awal: hanya router {dest} yang punya baris untuk {net}',
      pt: 'Início: só o roteador {dest} tem uma linha para {net}',
    },
    'caption.startScratchLs': {
      en: 'Start: each router holds only its own advert',
      ko: '시작 — 라우터마다 제 알림 하나만 쥔다',
      ja: '開始 — 各ルーターは自分の広告だけを持つ',
      zh: '开始 —— 每个路由器只持有自己的通告',
      ar: 'البداية: كل موجّه يحمل إعلانه وحده',
      es: 'Inicio: cada router solo tiene su propio anuncio',
      fr: 'Départ : chaque routeur ne tient que sa propre annonce',
      hi: 'शुरुआत: हर राउटर के पास केवल अपना विज्ञापन है',
      id: 'Awal: tiap router hanya memegang iklannya sendiri',
      pt: 'Início: cada roteador só tem o próprio anúncio',
    },
    'caption.cutDv': {
      en: 'Cut {links}: rows whose next hop lay across it jump to {inf}',
      ko: '{links} 끊김 — 그 너머가 다음 홉이던 줄은 곧바로 {inf}',
      ja: '{links} 切断 — その先が次ホップだった行はすぐ {inf}',
      zh: '断开 {links} —— 下一跳在断线另一侧的表项立刻变为 {inf}',
      ar: 'قطع {links}: الأسطر التي كانت قفزتها التالية عبره تقفز إلى {inf}',
      es: 'Corte {links}: las filas cuyo siguiente salto estaba al otro lado pasan a {inf}',
      fr: 'Coupure {links} : les lignes dont le saut suivant était de l’autre côté passent à {inf}',
      hi: '{links} कटा: जिन पंक्तियों का अगला हॉप उस पार था वे तुरंत {inf}',
      id: 'Putus {links}: baris yang lompatan berikutnya di seberang langsung jadi {inf}',
      pt: 'Corte {links}: as linhas cujo próximo salto estava do outro lado passam a {inf}',
    },
    'caption.cutPv': {
      en: 'Cut {links}: paths learned over it are removed and each end picks again',
      ko: '{links} 끊김 — 그 선으로 받은 길을 지우고 두 끝이 다시 고른다',
      ja: '{links} 切断 — その線で受けた経路を消し、両端が選び直す',
      zh: '断开 {links} —— 删除经它学到的路径，两端重新挑选',
      ar: 'قطع {links}: تُحذف المسارات المتعلَّمة عبره ويختار الطرفان من جديد',
      es: 'Corte {links}: se borran las rutas aprendidas por él y cada extremo vuelve a elegir',
      fr: 'Coupure {links} : les chemins appris par ce lien sont retirés et chaque bout choisit à nouveau',
      hi: '{links} कटा: उससे सीखे पथ हटते हैं और दोनों सिरे फिर चुनते हैं',
      id: 'Putus {links}: jalur yang dipelajari lewat sana dihapus dan kedua ujung memilih ulang',
      pt: 'Corte {links}: os caminhos aprendidos por ele são removidos e cada ponta escolhe de novo',
    },
    'caption.cutLs': {
      en: 'Cut {links}: both ends issue a new advert and recompute from their own map',
      ko: '{links} 끊김 — 두 끝이 새 알림을 내고 제 지도로 다시 셈한다',
      ja: '{links} 切断 — 両端が新しい広告を出し、自分の地図で計算し直す',
      zh: '断开 {links} —— 两端发出新通告，并用自己的地图重新计算',
      ar: 'قطع {links}: يُصدر الطرفان إعلانًا جديدًا ويعيدان الحساب من خريطتيهما',
      es: 'Corte {links}: ambos extremos emiten un anuncio nuevo y recalculan con su propio mapa',
      fr: 'Coupure {links} : les deux bouts émettent une nouvelle annonce et recalculent sur leur carte',
      hi: '{links} कटा: दोनों सिरे नया विज्ञापन निकालते हैं और अपने नक्शे से फिर गिनते हैं',
      id: 'Putus {links}: kedua ujung mengeluarkan iklan baru dan menghitung ulang dari petanya',
      pt: 'Corte {links}: as duas pontas emitem um anúncio novo e recalculam com o próprio mapa',
    },
    'caption.wrong': {
      en: 'Wrong tables: {n}',
      ko: '틀린 표: {n}',
      ja: '誤った表: {n}',
      zh: '错误的表: {n}',
      ar: 'جداول خاطئة: {n}',
      es: 'Tablas erróneas: {n}',
      fr: 'Tables fausses : {n}',
      hi: 'गलत तालिकाएँ: {n}',
      id: 'Tabel salah: {n}',
      pt: 'Tabelas erradas: {n}',
    },
    'caption.round': {
      en: 'Round {n} · sent: {sent} · taken in: {taken}',
      ko: '라운드 {n} · 보냄: {sent} · 받아들임: {taken}',
      ja: 'ラウンド {n} · 送信: {sent} · 採用: {taken}',
      zh: '第 {n} 轮 · 发出: {sent} · 采纳: {taken}',
      ar: 'الجولة {n} · أُرسل: {sent} · قُبل: {taken}',
      es: 'Ronda {n} · enviados: {sent} · aceptados: {taken}',
      fr: 'Tour {n} · envoyées : {sent} · retenues : {taken}',
      hi: 'राउंड {n} · भेजे: {sent} · अपनाए: {taken}',
      id: 'Putaran {n} · dikirim: {sent} · diterima: {taken}',
      pt: 'Rodada {n} · enviados: {sent} · aceitos: {taken}',
    },
    'caption.roundHeld': {
      en: 'Round {n} · sent: {sent} · taken in: {taken} · held back: {held}',
      ko: '라운드 {n} · 보냄: {sent} · 받아들임: {taken} · 보내지 않음: {held}',
      ja: 'ラウンド {n} · 送信: {sent} · 採用: {taken} · 送らず: {held}',
      zh: '第 {n} 轮 · 发出: {sent} · 采纳: {taken} · 未发: {held}',
      ar: 'الجولة {n} · أُرسل: {sent} · قُبل: {taken} · حُجب: {held}',
      es: 'Ronda {n} · enviados: {sent} · aceptados: {taken} · retenidos: {held}',
      fr: 'Tour {n} · envoyées : {sent} · retenues : {taken} · non envoyées : {held}',
      hi: 'राउंड {n} · भेजे: {sent} · अपनाए: {taken} · रोके: {held}',
      id: 'Putaran {n} · dikirim: {sent} · diterima: {taken} · ditahan: {held}',
      pt: 'Rodada {n} · enviados: {sent} · aceitos: {taken} · retidos: {held}',
    },
    'caption.roundDropped': {
      en: 'Round {n} · sent: {sent} · taken in: {taken} · discarded: {dropped}',
      ko: '라운드 {n} · 보냄: {sent} · 받아들임: {taken} · 버림: {dropped}',
      ja: 'ラウンド {n} · 送信: {sent} · 採用: {taken} · 破棄: {dropped}',
      zh: '第 {n} 轮 · 发出: {sent} · 采纳: {taken} · 丢弃: {dropped}',
      ar: 'الجولة {n} · أُرسل: {sent} · قُبل: {taken} · أُهمل: {dropped}',
      es: 'Ronda {n} · enviados: {sent} · aceptados: {taken} · descartados: {dropped}',
      fr: 'Tour {n} · envoyées : {sent} · retenues : {taken} · jetées : {dropped}',
      hi: 'राउंड {n} · भेजे: {sent} · अपनाए: {taken} · छोड़े: {dropped}',
      id: 'Putaran {n} · dikirim: {sent} · diterima: {taken} · dibuang: {dropped}',
      pt: 'Rodada {n} · enviados: {sent} · aceitos: {taken} · descartados: {dropped}',
    },
    'caption.stopUnchanged': {
      en: 'No table changed in round {n}: stop',
      ko: '라운드 {n} · 바뀐 표 없음 — 멈춤',
      ja: 'ラウンド {n} で変わった表なし — 停止',
      zh: '第 {n} 轮没有表发生变化 —— 停止',
      ar: 'لم يتغير أي جدول في الجولة {n}: توقف',
      es: 'Ninguna tabla cambió en la ronda {n}: fin',
      fr: 'Aucune table n’a changé au tour {n} : arrêt',
      hi: 'राउंड {n} में कोई तालिका नहीं बदली: रुकें',
      id: 'Tak ada tabel yang berubah di putaran {n}: berhenti',
      pt: 'Nenhuma tabela mudou na rodada {n}: fim',
    },
    'caption.stopNoCopies': {
      en: 'Nothing left to forward after round {n}: stop',
      ko: '라운드 {n} · 다음에 넘길 사본 없음 — 멈춤',
      ja: 'ラウンド {n} の後、転送する写しなし — 停止',
      zh: '第 {n} 轮之后没有要转发的副本 —— 停止',
      ar: 'لا شيء يُمرَّر بعد الجولة {n}: توقف',
      es: 'Nada que reenviar tras la ronda {n}: fin',
      fr: 'Plus rien à relayer après le tour {n} : arrêt',
      hi: 'राउंड {n} के बाद आगे भेजने को कुछ नहीं: रुकें',
      id: 'Tak ada lagi yang diteruskan setelah putaran {n}: berhenti',
      pt: 'Nada mais a repassar após a rodada {n}: fim',
    },
    'label.direct': {
      en: 'direct',
      ko: '직접',
      ja: '直結',
      zh: '直连',
      ar: 'مباشر',
      es: 'directa',
      fr: 'directe',
      hi: 'सीधा',
      id: 'langsung',
      pt: 'direta',
    },
    'label.rounds': {
      en: 'Rounds',
      ko: '라운드',
      ja: 'ラウンド',
      zh: '轮次',
      ar: 'الجولات',
      es: 'Rondas',
      fr: 'Tours',
      hi: 'राउंड',
      id: 'Putaran',
      pt: 'Rodadas',
    },
  },
};
