/**
 * @piece
 * 함수를 부를 때 인자 자리에 들어가는 것은 값의 복사본인가, 변수의 자리 그 자체인가.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { PassByValueVsReferenceFacetData } from './algorithm.js';

const n = { var: 'n' };
const bumpBody = { k: 'assign', to: 'n', value: { op: '+', l: n, r: { num: 1 } } } as const;

const data: PassByValueVsReferenceFacetData = {
  type: 'pass-by-value-vs-reference',
  stepMs: 1400,
  lines: [
    { indent: 0, text: 'function bump(n)', stmt: { k: 'function', name: 'bump', params: ['n'] } },
    { indent: 1, text: 'n = n + 1', stmt: bumpBody },
    { indent: 0, text: 'function bumpRef(ref n)', stmt: { k: 'function', name: 'bumpRef', params: [{ name: 'n', ref: true }] } },
    { indent: 1, text: 'n = n + 1', stmt: bumpBody },
    { indent: 0, text: 'let a = 5', stmt: { k: 'assign', to: 'a', declare: true, value: { num: 5 } } },
    { indent: 0, text: 'let b = 5', stmt: { k: 'assign', to: 'b', declare: true, value: { num: 5 } } },
    { indent: 0, text: 'bump(a)', stmt: { k: 'expr', value: { call: 'bump', args: [{ var: 'a' }] } } },
    { indent: 0, text: 'bumpRef(b)', stmt: { k: 'expr', value: { call: 'bumpRef', args: [{ var: 'b' }] } } },
    { indent: 0, text: 'show a', stmt: { k: 'show', value: { var: 'a' } } },
    { indent: 0, text: 'show b', stmt: { k: 'show', value: { var: 'b' } } },
  ],
};

export const passByValueVsReferenceFacet: FacetJson = {
  id: 'facet:passByValueVsReference',
  title: {
    en: 'Pass by value vs. by reference',
    ko: '값 전달과 참조 전달',
    ja: '値渡しと参照渡し',
    zh: '按值传递与按引用传递',
    ar: 'التمرير بالقيمة مقابل التمرير بالمرجع',
    es: 'Paso por valor frente a paso por referencia',
    fr: 'Passage par valeur ou par référence',
    hi: 'मान से पास बनाम संदर्भ से पास',
    id: 'Pass by value vs pass by reference',
    pt: 'Passagem por valor vs. por referência',
  },
  description: {
    en: "Same body, different parameter: a copy of the value crosses over, or the variable's place itself does.",
    ko: '같은 몸, 다른 인자 — 건너가는 것이 값의 복사본인가, 변수의 자리 그 자체인가.',
    ja: '同じ本体、違う引数 — 渡るのは値のコピーか、変数の場所そのものか。',
    zh: '同样的函数体，不同的参数 —— 传过去的是值的副本，还是变量的位置本身。',
    ar: 'الجسم نفسه والمعامل مختلف: هل يعبر نسخةٌ من القيمة أم مكان المتغير نفسه؟',
    es: 'Mismo cuerpo, distinto parámetro: pasa una copia del valor o el propio lugar de la variable.',
    fr: 'Même corps, paramètre différent : passe une copie de la valeur, ou la place même de la variable.',
    hi: 'वही शरीर, अलग पैरामीटर — मान की प्रति जाती है या वेरिएबल की जगह ही।',
    id: 'Badan sama, parameter beda: yang menyeberang salinan nilai, atau tempat variabel itu sendiri.',
    pt: 'Mesmo corpo, parâmetro diferente: passa uma cópia do valor ou o próprio lugar da variável.',
  },
  algorithm: 'module:passByValueVsReference',
  scene: 'module:passByValueVsReferenceScene',
  initialData: data,
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has run yet.',
      ko: '아직 아무 줄도 밟지 않았다.',
      ja: 'まだどの行も実行していない。',
      zh: '还没有执行任何一行。',
      ar: 'لم يُنفَّذ أي سطر بعد.',
      es: 'Todavía no se ha ejecutado nada.',
      fr: "Rien n'a encore été exécuté.",
      hi: 'अभी तक कोई पंक्ति नहीं चली।',
      id: 'Belum ada baris yang dijalankan.',
      pt: 'Nada foi executado ainda.',
    },
    'caption.declare': {
      en: 'New place {name}, holding {value}.',
      ko: '새 자리 {name} — 들어간 값: {value}.',
      ja: '新しい場所 {name}、入った値: {value}。',
      zh: '新的位置 {name}，存入的值：{value}。',
      ar: 'مكان جديد {name} يحمل {value}.',
      es: 'Nuevo lugar {name}, con el valor {value}.',
      fr: 'Nouvelle place {name}, qui contient {value}.',
      hi: 'नई जगह {name}, जिसमें मान {value} है।',
      id: 'Tempat baru {name}, berisi {value}.',
      pt: 'Novo lugar {name}, com o valor {value}.',
    },
    'caption.callPlain': {
      en: 'Call {fn}.',
      ko: '{fn} 부름.',
      ja: '{fn} を呼ぶ。',
      zh: '调用 {fn}。',
      ar: 'استدعاء {fn}.',
      es: 'Llamada a {fn}.',
      fr: 'Appel de {fn}.',
      hi: '{fn} को बुलाया।',
      id: 'Memanggil {fn}.',
      pt: 'Chamada de {fn}.',
    },
    'caption.callCopy': {
      en: '{fn}({arg}): the value {value} is copied into a new place {param}. {arg} is still {srcValue}.',
      ko: '{fn}({arg}) 부름 — 값을 복사해 새 자리 {param} 에 넣는다: {value}. {arg} 의 값: {srcValue}.',
      ja: '{fn}({arg}): 値 {value} がコピーされ、新しい場所 {param} に入る。{arg} の値: {srcValue}。',
      zh: '{fn}({arg})：值 {value} 被复制到新的位置 {param}。{arg} 的值：{srcValue}。',
      ar: '{fn}({arg}): تُنسخ القيمة {value} إلى مكان جديد {param}. قيمة {arg}: {srcValue}.',
      es: '{fn}({arg}): el valor {value} se copia en un nuevo lugar {param}. {arg} vale {srcValue}.',
      fr: '{fn}({arg}) : la valeur {value} est copiée dans une nouvelle place {param}. {arg} vaut {srcValue}.',
      hi: '{fn}({arg}): मान {value} की प्रति नई जगह {param} में जाती है। {arg} का मान: {srcValue}।',
      id: '{fn}({arg}): nilai {value} disalin ke tempat baru {param}. Nilai {arg}: {srcValue}.',
      pt: '{fn}({arg}): o valor {value} é copiado para um novo lugar {param}. {arg} vale {srcValue}.',
    },
    'caption.callCopyExpr': {
      en: '{fn}({arg}): the value {value} is copied into a new place {param}.',
      ko: '{fn}({arg}) 부름 — 값을 복사해 새 자리 {param} 에 넣는다: {value}.',
      ja: '{fn}({arg}): 値 {value} がコピーされ、新しい場所 {param} に入る。',
      zh: '{fn}({arg})：值 {value} 被复制到新的位置 {param}。',
      ar: '{fn}({arg}): تُنسخ القيمة {value} إلى مكان جديد {param}.',
      es: '{fn}({arg}): el valor {value} se copia en un nuevo lugar {param}.',
      fr: '{fn}({arg}) : la valeur {value} est copiée dans une nouvelle place {param}.',
      hi: '{fn}({arg}): मान {value} की प्रति नई जगह {param} में जाती है।',
      id: '{fn}({arg}): nilai {value} disalin ke tempat baru {param}.',
      pt: '{fn}({arg}): o valor {value} é copiado para um novo lugar {param}.',
    },
    'caption.callPlace': {
      en: '{fn}({arg}): nothing is copied. The name {param} is attached to the place of {arg}.',
      ko: '{fn}({arg}) 부름 — 복사하지 않는다. {arg} 의 자리에 이름 하나를 더 붙인다: {param}.',
      ja: '{fn}({arg}): 何もコピーされない。名前 {param} が {arg} の場所に付く。',
      zh: '{fn}({arg})：什么都不复制。名字 {param} 贴到 {arg} 的位置上。',
      ar: '{fn}({arg}): لا يُنسخ شيء. يُلصق الاسم {param} على مكان {arg}.',
      es: '{fn}({arg}): no se copia nada. El nombre {param} se pega al lugar de {arg}.',
      fr: "{fn}({arg}) : rien n'est copié. Le nom {param} est collé sur la place de {arg}.",
      hi: '{fn}({arg}): कुछ भी कॉपी नहीं होता। नाम {param}, {arg} की जगह पर लग जाता है।',
      id: '{fn}({arg}): tidak ada yang disalin. Nama {param} ditempelkan pada tempat {arg}.',
      pt: '{fn}({arg}): nada é copiado. O nome {param} é colado no lugar de {arg}.',
    },
    'caption.assignThrough': {
      en: '{name} = {value}: {name} is the place of {owner}, so {owner} is now {value}.',
      ko: '{name} = {value} — 이 자리가 곧 {owner} 의 자리. 이제 {owner} 의 값: {value}.',
      ja: '{name} = {value}: {name} は {owner} の場所なので、{owner} も今は {value}。',
      zh: '{name} = {value}：{name} 就是 {owner} 的位置，所以 {owner} 现在是 {value}。',
      ar: '{name} = {value}: {name} هو مكان {owner}، لذا صار {owner} الآن {value}.',
      es: '{name} = {value}: {name} es el lugar de {owner}, así que ahora {owner} vale {value}.',
      fr: '{name} = {value} : {name} est la place de {owner}, donc {owner} vaut maintenant {value}.',
      hi: '{name} = {value}: {name} ही {owner} की जगह है, इसलिए अब {owner} का मान {value} है।',
      id: '{name} = {value}: {name} adalah tempat {owner}, jadi {owner} sekarang {value}.',
      pt: '{name} = {value}: {name} é o lugar de {owner}, então agora {owner} vale {value}.',
    },
    'caption.assignCopy': {
      en: '{name} = {value}: only the copy changes. {src} is still {srcValue}.',
      ko: '{name} = {value} — 바뀐 것은 복사본뿐. {src} 의 값: 여전히 {srcValue}.',
      ja: '{name} = {value}: 変わるのはコピーだけ。{src} はまだ {srcValue}。',
      zh: '{name} = {value}：只有副本改变。{src} 仍是 {srcValue}。',
      ar: '{name} = {value}: تتغير النسخة فقط. ما زال {src} يساوي {srcValue}.',
      es: '{name} = {value}: solo cambia la copia. {src} sigue valiendo {srcValue}.',
      fr: '{name} = {value} : seule la copie change. {src} vaut toujours {srcValue}.',
      hi: '{name} = {value}: केवल प्रति बदलती है। {src} अब भी {srcValue} है।',
      id: '{name} = {value}: hanya salinannya yang berubah. {src} masih {srcValue}.',
      pt: '{name} = {value}: só a cópia muda. {src} ainda vale {srcValue}.',
    },
    'caption.assign': {
      en: '{name}: {was} becomes {value}.',
      ko: '{name} 의 값: {was} → {value}.',
      ja: '{name}: {was} から {value} へ。',
      zh: '{name}：{was} 变为 {value}。',
      ar: '{name}: {was} يصبح {value}.',
      es: '{name}: {was} pasa a ser {value}.',
      fr: '{name} : {was} devient {value}.',
      hi: '{name}: {was} से {value} हुआ।',
      id: '{name}: {was} menjadi {value}.',
      pt: '{name}: {was} passa a ser {value}.',
    },
    'caption.returnPlain': {
      en: 'Back from {fn}, no value returned.',
      ko: '{fn} 에서 돌아온다 — 돌려준 값 없음.',
      ja: '{fn} から戻る。返す値はない。',
      zh: '从 {fn} 返回，没有返回值。',
      ar: 'العودة من {fn} دون قيمة مُعادة.',
      es: 'Vuelta de {fn}, sin valor devuelto.',
      fr: 'Retour de {fn}, sans valeur renvoyée.',
      hi: '{fn} से वापसी, कोई मान नहीं लौटा।',
      id: 'Kembali dari {fn}, tanpa nilai kembalian.',
      pt: 'Volta de {fn}, sem valor retornado.',
    },
    'caption.returnCopy': {
      en: 'Back from {fn}, no value returned. The frame goes, and the copy {param} = {value} goes with it.',
      ko: '{fn} 에서 돌아온다 — 돌려준 값 없음. 틀이 걷히며 복사본 {param} = {value} 도 함께 사라진다.',
      ja: '{fn} から戻る。返す値はない。フレームが消え、コピー {param} = {value} も一緒に消える。',
      zh: '从 {fn} 返回，没有返回值。栈帧撤去，副本 {param} = {value} 也随之消失。',
      ar: 'العودة من {fn} دون قيمة مُعادة. يزول الإطار وتزول معه النسخة {param} = {value}.',
      es: 'Vuelta de {fn}, sin valor devuelto. El marco desaparece y la copia {param} = {value} con él.',
      fr: 'Retour de {fn}, sans valeur renvoyée. Le cadre disparaît, et la copie {param} = {value} avec lui.',
      hi: '{fn} से वापसी, कोई मान नहीं लौटा। फ़्रेम हटता है और प्रति {param} = {value} भी उसके साथ मिट जाती है।',
      id: 'Kembali dari {fn}, tanpa nilai kembalian. Bingkainya hilang, dan salinan {param} = {value} ikut hilang.',
      pt: 'Volta de {fn}, sem valor retornado. O quadro some, e a cópia {param} = {value} vai junto.',
    },
    'caption.returnPlace': {
      en: 'Back from {fn}, no value returned. The name {param} comes off; the place of {arg} keeps {value}.',
      ko: '{fn} 에서 돌아온다 — 돌려준 값 없음. 이름 {param} 만 떨어지고, {arg} 의 자리에 남은 값: {value}.',
      ja: '{fn} から戻る。返す値はない。名前 {param} が外れ、{arg} の場所には {value} が残る。',
      zh: '从 {fn} 返回，没有返回值。名字 {param} 脱落；{arg} 的位置保留 {value}。',
      ar: 'العودة من {fn} دون قيمة مُعادة. يُنزع الاسم {param}، ويحتفظ مكان {arg} بالقيمة {value}.',
      es: 'Vuelta de {fn}, sin valor devuelto. El nombre {param} se despega; el lugar de {arg} conserva {value}.',
      fr: 'Retour de {fn}, sans valeur renvoyée. Le nom {param} se détache ; la place de {arg} garde {value}.',
      hi: '{fn} से वापसी, कोई मान नहीं लौटा। नाम {param} हट जाता है; {arg} की जगह में {value} बचा रहता है।',
      id: 'Kembali dari {fn}, tanpa nilai kembalian. Nama {param} terlepas; tempat {arg} tetap menyimpan {value}.',
      pt: 'Volta de {fn}, sem valor retornado. O nome {param} se solta; o lugar de {arg} guarda {value}.',
    },
    'caption.showFrom': {
      en: 'Output {value}, read from the place of {name}.',
      ko: '출력: {value} — {name} 의 자리에서 읽었다.',
      ja: '出力 {value}。{name} の場所から読んだ。',
      zh: '输出 {value}，从 {name} 的位置读取。',
      ar: 'الإخراج {value}، مقروءًا من مكان {name}.',
      es: 'Salida {value}, leída del lugar de {name}.',
      fr: 'Sortie {value}, lue à la place de {name}.',
      hi: 'आउटपुट {value}, {name} की जगह से पढ़ा गया।',
      id: 'Keluaran {value}, dibaca dari tempat {name}.',
      pt: 'Saída {value}, lida do lugar de {name}.',
    },
    'caption.show': {
      en: 'Output {value}.',
      ko: '출력: {value}.',
      ja: '出力 {value}。',
      zh: '输出 {value}。',
      ar: 'الإخراج {value}.',
      es: 'Salida {value}.',
      fr: 'Sortie {value}.',
      hi: 'आउटपुट {value}।',
      id: 'Keluaran {value}.',
      pt: 'Saída {value}.',
    },
    'label.outer': {
      en: 'outside',
      ko: '바깥',
      ja: '外側',
      zh: '外层',
      ar: 'الخارج',
      es: 'fuera',
      fr: 'extérieur',
      hi: 'बाहर',
      id: 'luar',
      pt: 'fora',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'الإخراج',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
  },
  blocks: {
    stage: { type: 'pass-by-value-vs-reference-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
