/**
 * @piece
 * @notation native — 기계 명령은 원시 프로그램의 표기가 아니라 컴파일러가 만드는 자료다.
 *
 * 질문: 레지스터가 모자라는 순간, 값은 어디로 가는가.
 *
 * 빈 레지스터가 없을 때 가장 늦게 다시 쓰일 값이 스택 칸으로 밀려나고, 제가 쓰일 줄 바로 앞에서
 * 빈 레지스터로 되불려 온다. 밀어냄과 되불러옴마다 명령 열에 줄이 하나씩 끼어든다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const spillToMemoryFacet: FacetJson = {
  id: 'facet:spillToMemory',
  title: {
    en: 'Spill to memory',
    ko: '메모리로 밀어내기',
    ja: 'メモリへの退避',
    zh: '溢出到内存',
    ar: 'الإزاحة إلى الذاكرة',
    es: 'Derrame a memoria',
    fr: 'Débordement vers la mémoire',
    hi: 'मेमोरी में स्पिल',
    id: 'Tumpahkan ke memori',
    pt: 'Derramamento para a memória',
  },
  description: {
    en: 'When no register is free, the value read last goes out to a stack slot and comes back just before it is needed.',
    ko: '빈 레지스터가 없으면 가장 늦게 읽힐 값이 스택 칸으로 나갔다가, 쓰일 줄 바로 앞에서 돌아온다.',
    ja: '空きレジスタがないとき、最も遅く読まれる値がスタック領域へ出て、使われる直前に戻ってくる。',
    zh: '没有空闲寄存器时，最晚才被读取的值被移到栈槽，并在要用它的那一行之前取回。',
    ar: 'حين لا يبقى سجل فارغ، تخرج القيمة التي ستُقرأ في الأخير إلى خانة في المكدس ثم تعود قبيل الحاجة إليها.',
    es: 'Si no queda un registro libre, el valor que se leerá más tarde sale a una ranura de pila y vuelve justo antes de usarse.',
    fr: 'Quand aucun registre n’est libre, la valeur lue le plus tard part dans une case de pile et revient juste avant d’être utilisée.',
    hi: 'जब कोई रजिस्टर खाली नहीं होता, तो सबसे देर से पढ़ा जाने वाला मान स्टैक खाने में जाता है और ज़रूरत से ठीक पहले लौट आता है।',
    id: 'Bila tak ada register kosong, nilai yang paling akhir dibaca keluar ke slot tumpukan lalu kembali tepat sebelum dipakai.',
    pt: 'Sem registrador livre, o valor lido por último vai para uma posição da pilha e volta logo antes de ser usado.',
  },
  algorithm: 'module:spillToMemory',
  scene: 'module:spillToMemoryScene',
  initialData: {
    type: 'spill-to-memory',
    stepMs: 1300,
    k: 2,
    program: [
      { op: 'load', dst: 't1', srcs: [], mem: 'a', imm: null },
      { op: 'load', dst: 't2', srcs: [], mem: 'b', imm: null },
      { op: 'mul', dst: 't3', srcs: ['t1', 't2'], mem: null, imm: null },
      { op: 'load', dst: 't4', srcs: [], mem: 'c', imm: null },
      { op: 'load', dst: 't5', srcs: [], mem: 'd', imm: null },
      { op: 'sub', dst: 't6', srcs: ['t4', 't5'], mem: null, imm: null },
      { op: 'add', dst: 't7', srcs: ['t3', 't6'], mem: null, imm: null },
      { op: 'store', dst: null, srcs: ['t7'], mem: 'x', imm: null },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.program': {
      en: 'Instructions',
      ko: '명령 열',
      ja: '命令列',
      zh: '指令序列',
      ar: 'التعليمات',
      es: 'Instrucciones',
      fr: 'Instructions',
      hi: 'निर्देश',
      id: 'Instruksi',
      pt: 'Instruções',
    },
    'label.registers': {
      en: 'Registers',
      ko: '레지스터',
      ja: 'レジスタ',
      zh: '寄存器',
      ar: 'السجلات',
      es: 'Registros',
      fr: 'Registres',
      hi: 'रजिस्टर',
      id: 'Register',
      pt: 'Registradores',
    },
    'label.stack': {
      en: 'Stack slots (memory)',
      ko: '스택 칸 (메모리)',
      ja: 'スタック領域 (メモリ)',
      zh: '栈槽 (内存)',
      ar: 'خانات المكدس (الذاكرة)',
      es: 'Ranuras de pila (memoria)',
      fr: 'Cases de pile (mémoire)',
      hi: 'स्टैक खाने (मेमोरी)',
      id: 'Slot tumpukan (memori)',
      pt: 'Posições da pilha (memória)',
    },
    'label.pressure': {
      en: 'Live values: {n} · registers: {k}',
      ko: '산 값: {n} · 레지스터: {k}',
      ja: '生きている値: {n} · レジスタ: {k}',
      zh: '活跃值: {n} · 寄存器: {k}',
      ar: 'القيم الحية: {n} · السجلات: {k}',
      es: 'Valores vivos: {n} · registros: {k}',
      fr: 'Valeurs vivantes : {n} · registres : {k}',
      hi: 'जीवित मान: {n} · रजिस्टर: {k}',
      id: 'Nilai hidup: {n} · register: {k}',
      pt: 'Valores vivos: {n} · registradores: {k}',
    },
    'label.empty': {
      en: 'empty',
      ko: '빔',
      ja: '空き',
      zh: '空',
      ar: 'فارغ',
      es: 'libre',
      fr: 'libre',
      hi: 'खाली',
      id: 'kosong',
      pt: 'livre',
    },
    'label.last': {
      en: 'last read: L{line}',
      ko: '마지막 읽기: L{line}',
      ja: '最後の読み出し: L{line}',
      zh: '最后读取: L{line}',
      ar: 'آخر قراءة: L{line}',
      es: 'última lectura: L{line}',
      fr: 'dernière lecture : L{line}',
      hi: 'अंतिम पठन: L{line}',
      id: 'baca terakhir: L{line}',
      pt: 'última leitura: L{line}',
    },
    'label.spill': {
      en: 'spill',
      ko: '밀어냄',
      ja: '退避',
      zh: '溢出',
      ar: 'إزاحة',
      es: 'derrame',
      fr: 'débordement',
      hi: 'स्पिल',
      id: 'tumpah',
      pt: 'derrame',
    },
    'label.reload': {
      en: 'reload',
      ko: '되불러옴',
      ja: '再読み込み',
      zh: '取回',
      ar: 'إعادة تحميل',
      es: 'recarga',
      fr: 'rechargement',
      hi: 'पुनः लोड',
      id: 'muat ulang',
      pt: 'recarga',
    },
    'caption.start': {
      en: 'Registers: {k}. Assigning them from L1, line by line.',
      ko: '레지스터: {k}. L1 부터 한 줄씩 준다.',
      ja: 'レジスタ: {k}。L1 から一行ずつ割り当てる。',
      zh: '寄存器: {k}。从 L1 开始逐行分配。',
      ar: 'السجلات: {k}. نوزعها سطرًا سطرًا بدءًا من L1.',
      es: 'Registros: {k}. Se asignan línea a línea desde L1.',
      fr: 'Registres : {k}. On les attribue ligne par ligne depuis L1.',
      hi: 'रजिस्टर: {k}. L1 से एक-एक पंक्ति करके दिए जाते हैं।',
      id: 'Register: {k}. Dibagikan baris demi baris mulai L1.',
      pt: 'Registradores: {k}. Atribuídos linha a linha a partir de L1.',
    },
    'caption.get': {
      en: 'L{line}: {v} → {reg}.',
      ko: 'L{line}: {v} → {reg}.',
      ja: 'L{line}: {v} → {reg}。',
      zh: 'L{line}: {v} → {reg}。',
      ar: 'L{line}: {v} → {reg}.',
      es: 'L{line}: {v} → {reg}.',
      fr: 'L{line} : {v} → {reg}.',
      hi: 'L{line}: {v} → {reg}.',
      id: 'L{line}: {v} → {reg}.',
      pt: 'L{line}: {v} → {reg}.',
    },
    'caption.freeGet': {
      en: 'L{line}: last read of {freed}, register freed. {v} → {reg}.',
      ko: 'L{line}: {freed} — 마지막 읽기라 레지스터를 풀어 준다. {v} → {reg}.',
      ja: 'L{line}: {freed} — 最後の読み出しなのでレジスタを解放。{v} → {reg}。',
      zh: 'L{line}: {freed} — 最后一次读取，释放寄存器。{v} → {reg}。',
      ar: 'L{line}: {freed} — آخر قراءة، فيُحرَّر السجل. {v} → {reg}.',
      es: 'L{line}: última lectura de {freed}, registro liberado. {v} → {reg}.',
      fr: 'L{line} : dernière lecture de {freed}, registre libéré. {v} → {reg}.',
      hi: 'L{line}: {freed} — अंतिम पठन, रजिस्टर मुक्त। {v} → {reg}.',
      id: 'L{line}: baca terakhir {freed}, register dilepas. {v} → {reg}.',
      pt: 'L{line}: última leitura de {freed}, registrador liberado. {v} → {reg}.',
    },
    'caption.free': {
      en: 'L{line}: last read of {freed}, register freed.',
      ko: 'L{line}: {freed} — 마지막 읽기라 레지스터를 풀어 준다.',
      ja: 'L{line}: {freed} — 最後の読み出しなのでレジスタを解放。',
      zh: 'L{line}: {freed} — 最后一次读取，释放寄存器。',
      ar: 'L{line}: {freed} — آخر قراءة، فيُحرَّر السجل.',
      es: 'L{line}: última lectura de {freed}, registro liberado.',
      fr: 'L{line} : dernière lecture de {freed}, registre libéré.',
      hi: 'L{line}: {freed} — अंतिम पठन, रजिस्टर मुक्त।',
      id: 'L{line}: baca terakhir {freed}, register dilepas.',
      pt: 'L{line}: última leitura de {freed}, registrador liberado.',
    },
    'caption.keep': {
      en: 'L{line}: {used} still read later, register kept.',
      ko: 'L{line}: {used} — 뒤에서 또 읽혀 레지스터에 남는다.',
      ja: 'L{line}: {used} — 後でまた読まれるのでレジスタに残る。',
      zh: 'L{line}: {used} — 之后还要读取，留在寄存器中。',
      ar: 'L{line}: {used} — ستُقرأ لاحقًا، فتبقى في السجل.',
      es: 'L{line}: {used} se leerá después, el registro se conserva.',
      fr: 'L{line} : {used} sera relu plus tard, le registre est gardé.',
      hi: 'L{line}: {used} — बाद में फिर पढ़ा जाएगा, रजिस्टर बना रहता है।',
      id: 'L{line}: {used} masih dibaca nanti, register tetap dipegang.',
      pt: 'L{line}: {used} ainda será lido depois, registrador mantido.',
    },
    'caption.spill': {
      en: 'L{line}: no free register for {v}. Read last: {victim} (L{last}) → [sp+{slot}], then {reg} → {v}.',
      ko: 'L{line}: {v} 에 줄 빈 레지스터가 없다. 가장 늦게 읽힐 {victim} (L{last}) → [sp+{slot}], 비운 {reg} → {v}.',
      ja: 'L{line}: {v} に渡す空きレジスタがない。最も遅く読まれる {victim} (L{last}) → [sp+{slot}]、空いた {reg} → {v}。',
      zh: 'L{line}: 没有空闲寄存器给 {v}。最晚读取的 {victim} (L{last}) → [sp+{slot}]，腾出的 {reg} → {v}。',
      ar: 'L{line}: لا سجل فارغًا لـ {v}. الأبعد قراءةً {victim} (L{last}) → [sp+{slot}]، ثم {reg} → {v}.',
      es: 'L{line}: no hay registro libre para {v}. Se lee más tarde: {victim} (L{last}) → [sp+{slot}], y {reg} → {v}.',
      fr: 'L{line} : aucun registre libre pour {v}. Lu le plus tard : {victim} (L{last}) → [sp+{slot}], puis {reg} → {v}.',
      hi: 'L{line}: {v} के लिए कोई खाली रजिस्टर नहीं। सबसे देर से पढ़ा जाने वाला {victim} (L{last}) → [sp+{slot}], फिर {reg} → {v}.',
      id: 'L{line}: tak ada register kosong untuk {v}. Dibaca paling akhir: {victim} (L{last}) → [sp+{slot}], lalu {reg} → {v}.',
      pt: 'L{line}: não há registrador livre para {v}. Lido por último: {victim} (L{last}) → [sp+{slot}], e {reg} → {v}.',
    },
    'caption.reload': {
      en: 'Before L{line}: {v} is read here, so [sp+{slot}] → {reg}.',
      ko: 'L{line} 앞: 여기서 읽을 {v} — [sp+{slot}] → {reg}.',
      ja: 'L{line} の前: ここで読む {v} — [sp+{slot}] → {reg}。',
      zh: 'L{line} 之前: 这里要读 {v} — [sp+{slot}] → {reg}。',
      ar: 'قبل L{line}: هنا تُقرأ {v}، لذا [sp+{slot}] → {reg}.',
      es: 'Antes de L{line}: aquí se lee {v}, así que [sp+{slot}] → {reg}.',
      fr: 'Avant L{line} : {v} est lu ici, donc [sp+{slot}] → {reg}.',
      hi: 'L{line} से पहले: यहाँ {v} पढ़ा जाता है, इसलिए [sp+{slot}] → {reg}.',
      id: 'Sebelum L{line}: {v} dibaca di sini, jadi [sp+{slot}] → {reg}.',
      pt: 'Antes de L{line}: {v} é lido aqui, então [sp+{slot}] → {reg}.',
    },
    'sub.cands': {
      en: 'Last reads compared — {cands}',
      ko: '견준 마지막 읽기 — {cands}',
      ja: '比べた最後の読み出し — {cands}',
      zh: '比较的最后读取 — {cands}',
      ar: 'آخر القراءات المقارنة — {cands}',
      es: 'Últimas lecturas comparadas — {cands}',
      fr: 'Dernières lectures comparées — {cands}',
      hi: 'तुलना किए गए अंतिम पठन — {cands}',
      id: 'Baca terakhir yang dibandingkan — {cands}',
      pt: 'Últimas leituras comparadas — {cands}',
    },
    'sub.inserted': {
      en: 'Lines inserted: {n}',
      ko: '끼어든 줄: {n}',
      ja: '挿入された行: {n}',
      zh: '插入的行: {n}',
      ar: 'الأسطر المُدرجة: {n}',
      es: 'Líneas insertadas: {n}',
      fr: 'Lignes insérées : {n}',
      hi: 'जोड़ी गई पंक्तियाँ: {n}',
      id: 'Baris yang disisipkan: {n}',
      pt: 'Linhas inseridas: {n}',
    },
    'sub.done': {
      en: 'Lines: {from} → {to} · memory trips: {trips} · most live at once: {peak}, registers: {k}',
      ko: '명령 줄: {from} → {to} · 메모리 오감: {trips} · 한때 가장 많이 산 값: {peak}, 레지스터: {k}',
      ja: '命令行: {from} → {to} · メモリ往復: {trips} · 同時に生きた値の最大: {peak}、レジスタ: {k}',
      zh: '指令行: {from} → {to} · 内存往返: {trips} · 同时活跃值最多: {peak}，寄存器: {k}',
      ar: 'الأسطر: {from} → {to} · رحلات الذاكرة: {trips} · أكثر القيم الحية معًا: {peak}، السجلات: {k}',
      es: 'Líneas: {from} → {to} · viajes a memoria: {trips} · máximo de vivos a la vez: {peak}, registros: {k}',
      fr: 'Lignes : {from} → {to} · allers-retours mémoire : {trips} · vivantes au plus à la fois : {peak}, registres : {k}',
      hi: 'पंक्तियाँ: {from} → {to} · मेमोरी यात्राएँ: {trips} · एक साथ सबसे अधिक जीवित मान: {peak}, रजिस्टर: {k}',
      id: 'Baris: {from} → {to} · perjalanan memori: {trips} · paling banyak hidup bersamaan: {peak}, register: {k}',
      pt: 'Linhas: {from} → {to} · idas à memória: {trips} · máximo de vivos ao mesmo tempo: {peak}, registradores: {k}',
    },
  },
  blocks: {
    stage: { type: 'spill-to-memory-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
