import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 행위자가 지금 자리를 보고 행동 하나를 고르면, 그다음 자리와 상은 누가 정하는가.
 *
 * 행위자는 정책표에서 행동을 골라 환경으로 넘기고, 환경은 주사위로 실제 방향을 정해
 * 다음 자리와 상을 되돌려준다. 같은 자리 (0,1) 에서 같은 행동을 두 번 넘기는데 한 번은
 * 미끄러지고 한 번은 목표에 든다.
 */
export const stateActionRewardFacet: FacetJson = {
  id: 'facet:stateActionReward',
  title: {
    en: 'State, action, reward',
    ko: '자리, 행동, 상',
    ja: '状態・行動・報酬',
    zh: '状态、动作、奖励',
    ar: 'الحالة والفعل والمكافأة',
    es: 'Estado, acción, recompensa',
    fr: 'État, action, récompense',
    hi: 'अवस्था, क्रिया, पुरस्कार',
    id: 'Keadaan, aksi, imbalan',
    pt: 'Estado, ação, recompensa',
  },
  description: {
    en: 'The agent picks an action from where it stands; the environment decides where it lands and what it earns.',
    ko: '행위자는 지금 자리에서 행동을 고르고, 어디로 가서 무엇을 받는지는 환경이 정한다.',
    ja: 'エージェントは今いる状態から行動を選び、どこへ移り何を受け取るかは環境が決める。',
    zh: '智能体根据当前状态选择动作，落到哪里、得到什么由环境决定。',
    ar: 'يختار الوكيل فعلًا من حالته الراهنة، وتقرر البيئة أين ينتهي وما المكافأة التي يتلقاها.',
    es: 'El agente elige una acción desde donde está; el entorno decide adónde llega y qué recibe.',
    fr: 'L’agent choisit une action depuis là où il se trouve ; l’environnement décide où il arrive et ce qu’il reçoit.',
    hi: 'एजेंट अपनी मौजूदा अवस्था से क्रिया चुनता है; वह कहाँ पहुँचेगा और क्या पाएगा, यह पर्यावरण तय करता है।',
    id: 'Agen memilih aksi dari tempatnya berada; lingkungan menentukan ke mana ia sampai dan apa yang ia terima.',
    pt: 'O agente escolhe uma ação a partir de onde está; o ambiente decide aonde ele chega e o que recebe.',
  },
  algorithm: 'module:stateActionReward',
  scene: 'module:stateActionRewardScene',
  initialData: {
    type: 'state-action-reward',
    stepMs: 1100,
    rows: 2,
    cols: 3,
    start: [1, 0],
    goal: [0, 2],
    policy: [
      { s: [1, 0], action: 'up' },
      { s: [0, 0], action: 'right' },
      { s: [0, 1], action: 'right' },
      { s: [1, 1], action: 'up' },
      { s: [1, 2], action: 'up' },
    ],
    slip: { intended: 0.8, left: 0.1, right: 0.1 },
    rewards: { goal: 10, move: -1 },
    dice: [0.41, 0.66, 0.93, 0.27, 0.52],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'state-action-reward-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'action.up': {
      en: 'up', ko: '위', ja: '上', zh: '上', ar: 'أعلى', es: 'arriba', fr: 'haut', hi: 'ऊपर', id: 'atas', pt: 'cima',
    },
    'action.down': {
      en: 'down', ko: '아래', ja: '下', zh: '下', ar: 'أسفل', es: 'abajo', fr: 'bas', hi: 'नीचे', id: 'bawah', pt: 'baixo',
    },
    'action.left': {
      en: 'left', ko: '왼쪽', ja: '左', zh: '左', ar: 'يسار', es: 'izquierda', fr: 'gauche', hi: 'बाएँ', id: 'kiri', pt: 'esquerda',
    },
    'action.right': {
      en: 'right', ko: '오른쪽', ja: '右', zh: '右', ar: 'يمين', es: 'derecha', fr: 'droite', hi: 'दाएँ', id: 'kanan', pt: 'direita',
    },
    'label.agent': {
      en: 'Agent', ko: '행위자', ja: 'エージェント', zh: '智能体', ar: 'الوكيل', es: 'Agente', fr: 'Agent', hi: 'एजेंट', id: 'Agen', pt: 'Agente',
    },
    'label.env': {
      en: 'Environment', ko: '환경', ja: '環境', zh: '环境', ar: 'البيئة', es: 'Entorno', fr: 'Environnement', hi: 'पर्यावरण', id: 'Lingkungan', pt: 'Ambiente',
    },
    'label.sees': {
      en: 'Sees: {s}',
      ko: '보는 자리: {s}',
      ja: '見ている状態: {s}',
      zh: '所见状态：{s}',
      ar: 'يرى: {s}',
      es: 'Ve: {s}',
      fr: 'Voit : {s}',
      hi: 'देखता है: {s}',
      id: 'Melihat: {s}',
      pt: 'Vê: {s}',
    },
    'label.policy': {
      en: 'Policy', ko: '정책표', ja: '方策表', zh: '策略表', ar: 'جدول السياسة', es: 'Política', fr: 'Politique', hi: 'नीति तालिका', id: 'Tabel kebijakan', pt: 'Política',
    },
    'label.laneAction': {
      en: 'action', ko: '행동', ja: '行動', zh: '动作', ar: 'الفعل', es: 'acción', fr: 'action', hi: 'क्रिया', id: 'aksi', pt: 'ação',
    },
    'label.laneReturn': {
      en: 'next state · reward',
      ko: '다음 자리 · 상',
      ja: '次の状態 · 報酬',
      zh: '下一状态 · 奖励',
      ar: 'الحالة التالية · المكافأة',
      es: 'siguiente estado · recompensa',
      fr: 'état suivant · récompense',
      hi: 'अगली अवस्था · पुरस्कार',
      id: 'keadaan berikut · imbalan',
      pt: 'próximo estado · recompensa',
    },
    'label.goal': {
      en: 'goal', ko: '목표', ja: 'ゴール', zh: '目标', ar: 'الهدف', es: 'meta', fr: 'but', hi: 'लक्ष्य', id: 'tujuan', pt: 'meta',
    },
    'label.start': {
      en: 'start', ko: '출발', ja: 'スタート', zh: '起点', ar: 'البداية', es: 'inicio', fr: 'départ', hi: 'आरंभ', id: 'awal', pt: 'início',
    },
    'label.asMeant': {
      en: 'as meant', ko: '뜻대로', ja: '意図どおり', zh: '按意图', ar: 'كما قُصد', es: 'según lo previsto', fr: 'comme voulu', hi: 'इरादे के अनुसार', id: 'sesuai niat', pt: 'como pretendido',
    },
    'label.slip': {
      en: 'slip', ko: '미끄러짐', ja: '滑り', zh: '打滑', ar: 'انزلاق', es: 'desliz', fr: 'glissade', hi: 'फिसलन', id: 'tergelincir', pt: 'deslize',
    },
    'label.die': {
      en: 'Die: {u}',
      ko: '주사위: {u}',
      ja: 'サイコロ: {u}',
      zh: '骰子：{u}',
      ar: 'النرد: {u}',
      es: 'Dado: {u}',
      fr: 'Dé : {u}',
      hi: 'पासा: {u}',
      id: 'Dadu: {u}',
      pt: 'Dado: {u}',
    },
    'label.pair': {
      en: '{a} · {b}', ko: '{a} · {b}', ja: '{a} · {b}', zh: '{a} · {b}', ar: '{a} · {b}', es: '{a} · {b}', fr: '{a} · {b}', hi: '{a} · {b}', id: '{a} · {b}', pt: '{a} · {b}',
    },
    'label.reward': {
      en: 'Reward: {r}',
      ko: '상: {r}',
      ja: '報酬: {r}',
      zh: '奖励：{r}',
      ar: 'المكافأة: {r}',
      es: 'Recompensa: {r}',
      fr: 'Récompense : {r}',
      hi: 'पुरस्कार: {r}',
      id: 'Imbalan: {r}',
      pt: 'Recompensa: {r}',
    },
    'label.trajectory': {
      en: 'Trajectory (state, action, reward)',
      ko: '궤적 (자리, 행동, 상)',
      ja: '軌跡(状態、行動、報酬)',
      zh: '轨迹（状态，动作，奖励）',
      ar: 'المسار (الحالة، الفعل، المكافأة)',
      es: 'Trayectoria (estado, acción, recompensa)',
      fr: 'Trajectoire (état, action, récompense)',
      hi: 'पथ (अवस्था, क्रिया, पुरस्कार)',
      id: 'Lintasan (keadaan, aksi, imbalan)',
      pt: 'Trajetória (estado, ação, recompensa)',
    },
    'label.counts': {
      en: 'Actions handed: {a} · Slips: {k}',
      ko: '넘긴 행동: {a} · 미끄러짐: {k}',
      ja: '渡した行動: {a} · 滑り: {k}',
      zh: '交出的动作：{a} · 打滑：{k}',
      ar: 'الأفعال المُسلَّمة: {a} · الانزلاقات: {k}',
      es: 'Acciones entregadas: {a} · Deslices: {k}',
      fr: 'Actions transmises : {a} · Glissades : {k}',
      hi: 'सौंपी गई क्रियाएँ: {a} · फिसलन: {k}',
      id: 'Aksi diserahkan: {a} · Tergelincir: {k}',
      pt: 'Ações entregues: {a} · Deslizes: {k}',
    },
    'caption.start': {
      en: 'Start: {s}',
      ko: '처음 자리: {s}',
      ja: '最初の状態: {s}',
      zh: '起始状态：{s}',
      ar: 'البداية: {s}',
      es: 'Inicio: {s}',
      fr: 'Départ : {s}',
      hi: 'आरंभ: {s}',
      id: 'Awal: {s}',
      pt: 'Início: {s}',
    },
    'caption.act': {
      en: 'At {s} the policy gives: {action}. Handed to the environment.',
      ko: '자리 {s} 에서 정책표가 고른 행동: {action} — 환경으로 넘긴다.',
      ja: '状態 {s} で方策表が選んだ行動: {action} — 環境へ渡す。',
      zh: '在 {s}，策略表给出的动作：{action} — 交给环境。',
      ar: 'في {s} تعطي السياسة الفعل: {action} — يُسلَّم إلى البيئة.',
      es: 'En {s} la política da: {action}. Se entrega al entorno.',
      fr: 'En {s}, la politique donne : {action}. Transmise à l’environnement.',
      hi: '{s} पर नीति की क्रिया: {action} — पर्यावरण को सौंपी गई।',
      id: 'Di {s} kebijakan memberi: {action}. Diserahkan ke lingkungan.',
      pt: 'Em {s} a política dá: {action}. Entregue ao ambiente.',
    },
    'caption.asMeant': {
      en: 'Die: {u} → as meant: {dir}',
      ko: '주사위: {u} → 뜻대로: {dir}',
      ja: 'サイコロ: {u} → 意図どおり: {dir}',
      zh: '骰子：{u} → 按意图：{dir}',
      ar: 'النرد: {u} → كما قُصد: {dir}',
      es: 'Dado: {u} → según lo previsto: {dir}',
      fr: 'Dé : {u} → comme voulu : {dir}',
      hi: 'पासा: {u} → इरादे के अनुसार: {dir}',
      id: 'Dadu: {u} → sesuai niat: {dir}',
      pt: 'Dado: {u} → como pretendido: {dir}',
    },
    'caption.slip': {
      en: 'Die: {u} → slipped. Meant: {meant} · Went: {dir}',
      ko: '주사위: {u} → 미끄러짐. 뜻한 방향: {meant} · 실제 방향: {dir}',
      ja: 'サイコロ: {u} → 滑った。意図: {meant} · 実際: {dir}',
      zh: '骰子：{u} → 打滑。意图：{meant} · 实际：{dir}',
      ar: 'النرد: {u} → انزلاق. المقصود: {meant} · الفعلي: {dir}',
      es: 'Dado: {u} → desliz. Previsto: {meant} · Real: {dir}',
      fr: 'Dé : {u} → glissade. Voulu : {meant} · Réel : {dir}',
      hi: 'पासा: {u} → फिसलन। इरादा: {meant} · वास्तविक: {dir}',
      id: 'Dadu: {u} → tergelincir. Niat: {meant} · Nyata: {dir}',
      pt: 'Dado: {u} → deslize. Pretendido: {meant} · Real: {dir}',
    },
    'caption.next': {
      en: 'Next state: {next} · Reward: {r}',
      ko: '다음 자리: {next} · 상: {r}',
      ja: '次の状態: {next} · 報酬: {r}',
      zh: '下一状态：{next} · 奖励：{r}',
      ar: 'الحالة التالية: {next} · المكافأة: {r}',
      es: 'Siguiente estado: {next} · Recompensa: {r}',
      fr: 'État suivant : {next} · Récompense : {r}',
      hi: 'अगली अवस्था: {next} · पुरस्कार: {r}',
      id: 'Keadaan berikut: {next} · Imbalan: {r}',
      pt: 'Próximo estado: {next} · Recompensa: {r}',
    },
    'caption.nextGoal': {
      en: 'Next state: {next} (goal) · Reward: {r} — the episode ends',
      ko: '다음 자리: {next} (목표) · 상: {r} — 판이 끝난다',
      ja: '次の状態: {next}(ゴール) · 報酬: {r} — エピソード終了',
      zh: '下一状态：{next}（目标） · 奖励：{r} — 回合结束',
      ar: 'الحالة التالية: {next} (الهدف) · المكافأة: {r} — تنتهي الحلقة',
      es: 'Siguiente estado: {next} (meta) · Recompensa: {r} — termina el episodio',
      fr: 'État suivant : {next} (but) · Récompense : {r} — l’épisode se termine',
      hi: 'अगली अवस्था: {next} (लक्ष्य) · पुरस्कार: {r} — एपिसोड समाप्त',
      id: 'Keadaan berikut: {next} (tujuan) · Imbalan: {r} — episode berakhir',
      pt: 'Próximo estado: {next} (meta) · Recompensa: {r} — o episódio termina',
    },
    'caption.bump': {
      en: 'Blocked by the wall. Next state: {next} · Reward: {r}',
      ko: '벽에 막혀 제자리. 다음 자리: {next} · 상: {r}',
      ja: '壁に阻まれてその場。次の状態: {next} · 報酬: {r}',
      zh: '被墙挡住，原地不动。下一状态：{next} · 奖励：{r}',
      ar: 'صدّه الجدار. الحالة التالية: {next} · المكافأة: {r}',
      es: 'Bloqueado por la pared. Siguiente estado: {next} · Recompensa: {r}',
      fr: 'Bloqué par le mur. État suivant : {next} · Récompense : {r}',
      hi: 'दीवार से रुका। अगली अवस्था: {next} · पुरस्कार: {r}',
      id: 'Terhalang dinding. Keadaan berikut: {next} · Imbalan: {r}',
      pt: 'Bloqueado pela parede. Próximo estado: {next} · Recompensa: {r}',
    },
    'caption.repeat': {
      en: 'Same state {s} and same action {action} as before — then: {was} · now: {next}',
      ko: '앞서와 같은 자리 {s} · 같은 행동 {action} — 그때 다음 자리: {was} · 이번: {next}',
      ja: '前と同じ状態 {s} · 同じ行動 {action} — そのとき: {was} · 今回: {next}',
      zh: '与之前相同的状态 {s} · 相同的动作 {action} — 那时：{was} · 这次：{next}',
      ar: 'الحالة نفسها {s} والفعل نفسه {action} كما سبق — آنذاك: {was} · الآن: {next}',
      es: 'Mismo estado {s} y misma acción {action} que antes — entonces: {was} · ahora: {next}',
      fr: 'Même état {s} et même action {action} qu’avant — alors : {was} · cette fois : {next}',
      hi: 'पहले जैसी अवस्था {s} और वही क्रिया {action} — तब: {was} · अब: {next}',
      id: 'Keadaan {s} dan aksi {action} yang sama seperti sebelumnya — dulu: {was} · kini: {next}',
      pt: 'Mesmo estado {s} e mesma ação {action} de antes — então: {was} · agora: {next}',
    },
  },
};
