import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 행렬을 곱하면 벡터는 대개 방향이 돌아간다 — 곱해도 제 방향 그대로 길이만 바뀌는 벡터가 있는가,
 * 있다면 몇 배가 되는가?
 */
export const eigenvectorDirectionFacet: FacetJson = {
  id: 'facet:eigenvectorDirection',
  title: {
    en: 'Eigenvectors: the directions that do not turn',
    ko: '고유벡터 — 곱해도 돌지 않는 방향',
    ja: '固有ベクトル — 掛けても回らない向き',
    zh: '特征向量 — 相乘后不转向的方向',
    ar: 'المتجهات الذاتية — اتجاهات لا تدور',
    es: 'Vectores propios: las direcciones que no giran',
    fr: 'Vecteurs propres : les directions qui ne tournent pas',
    hi: 'आइगेन सदिश — वे दिशाएँ जो नहीं घूमतीं',
    id: 'Vektor eigen: arah yang tidak berputar',
    pt: 'Autovetores: as direções que não giram',
  },
  description: {
    en: 'One matrix is multiplied once into each of seven vectors, and the turn from v to Av is measured. Most turn; two stay on their own line and only stretch.',
    ko: '한 행렬을 일곱 벡터에 한 번씩 곱해 v 에서 Av 까지 돈 각을 잰다. 대부분은 돌고, 둘은 제 직선 위에 남아 길이만 늘어난다.',
    ja: '一つの行列を七つのベクトルにそれぞれ一度掛け、v から Av まで回った角を測る。ほとんどは回り、二つだけが自分の直線上に残って長さだけ伸びる。',
    zh: '把一个矩阵分别乘到七个向量上各一次，测量从 v 到 Av 转过的角。大多数会转，只有两个留在自身直线上，只是变长。',
    ar: 'نضرب مصفوفة واحدة في سبعة متجهات مرة لكل منها ونقيس الزاوية من v إلى Av. معظمها يدور، واثنان فقط يبقيان على خطهما ويطولان فقط.',
    es: 'Una matriz se multiplica una vez por cada uno de siete vectores y se mide el giro de v a Av. La mayoría gira; dos se quedan en su propia recta y solo se alargan.',
    fr: 'Une matrice multiplie une fois chacun de sept vecteurs, et l’on mesure la rotation de v à Av. La plupart tournent ; deux restent sur leur propre droite et ne font que s’allonger.',
    hi: 'एक आव्यूह को सात सदिशों में से हर एक से एक बार गुणा कर v से Av तक घूमा कोण नापा जाता है। अधिकतर घूमते हैं; दो अपनी ही रेखा पर रहकर केवल लंबे होते हैं।',
    id: 'Satu matriks dikalikan sekali ke tiap dari tujuh vektor, lalu sudut putar dari v ke Av diukur. Sebagian besar berputar; dua tetap di garisnya sendiri dan hanya memanjang.',
    pt: 'Uma matriz multiplica uma vez cada um de sete vetores e mede-se o giro de v até Av. A maioria gira; dois ficam na própria reta e só se alongam.',
  },
  algorithm: 'module:eigenvectorDirection',
  scene: 'module:eigenvectorDirectionScene',
  initialData: {
    type: 'eigenvector-direction',
    stepMs: 1600,
    matrix: [
      [5, -1],
      [2, 2],
    ],
    vectors: [
      [1, 0],
      [2, 1],
      [1, 1],
      [2, 3],
      [1, 2],
      [0, 1],
      [-1, 1],
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Multiply each vector by A once · vectors: {n}',
      ko: '벡터마다 A 를 한 번씩 곱한다 · 훑을 벡터: {n}',
      ja: 'それぞれのベクトルに A を一度ずつ掛ける · ベクトル: {n}',
      zh: '把 A 分别乘到每个向量上一次 · 向量: {n}',
      ar: 'اضرب كل متجه في A مرة واحدة · المتجهات: {n}',
      es: 'Multiplica cada vector por A una vez · vectores: {n}',
      fr: 'Multiplier chaque vecteur par A une fois · vecteurs : {n}',
      hi: 'हर सदिश को A से एक बार गुणा करें · सदिश: {n}',
      id: 'Kalikan setiap vektor dengan A sekali · vektor: {n}',
      pt: 'Multiplique cada vetor por A uma vez · vetores: {n}',
    },
    'caption.turned': {
      en: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · turned: {deg}° · length: ×{k}',
      ko: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · 돈 각: {deg}° · 길이: ×{k}',
      ja: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · 回った角: {deg}° · 長さ: ×{k}',
      zh: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · 转过的角: {deg}° · 长度: ×{k}',
      ar: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · زاوية الدوران: {deg}° · الطول: ×{k}',
      es: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · giro: {deg}° · longitud: ×{k}',
      fr: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · rotation : {deg}° · longueur : ×{k}',
      hi: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · घूमा कोण: {deg}° · लंबाई: ×{k}',
      id: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · sudut putar: {deg}° · panjang: ×{k}',
      pt: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · giro: {deg}° · comprimento: ×{k}',
    },
    'caption.onLine': {
      en: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · turned: {deg}° · v × Av = {cross} · λ = {ev}',
      ko: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · 돈 각: {deg}° · v × Av = {cross} · λ = {ev}',
      ja: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · 回った角: {deg}° · v × Av = {cross} · λ = {ev}',
      zh: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · 转过的角: {deg}° · v × Av = {cross} · λ = {ev}',
      ar: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · زاوية الدوران: {deg}° · v × Av = {cross} · λ = {ev}',
      es: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · giro: {deg}° · v × Av = {cross} · λ = {ev}',
      fr: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · rotation : {deg}° · v × Av = {cross} · λ = {ev}',
      hi: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · घूमा कोण: {deg}° · v × Av = {cross} · λ = {ev}',
      id: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · sudut putar: {deg}° · v × Av = {cross} · λ = {ev}',
      pt: 'v ({vx}, {vy}) → Av ({ax}, {ay}) · giro: {deg}° · v × Av = {cross} · λ = {ev}',
    },
    tally: {
      en: 'Turned: {turned} · On its own line: {kept}',
      ko: '돈 것: {turned} · 제 직선 위: {kept}',
      ja: '回ったもの: {turned} · 自分の直線上: {kept}',
      zh: '转了的: {turned} · 在自身直线上: {kept}',
      ar: 'دارت: {turned} · على خطها نفسه: {kept}',
      es: 'Giraron: {turned} · En su propia recta: {kept}',
      fr: 'Ont tourné : {turned} · Sur leur propre droite : {kept}',
      hi: 'घूमे: {turned} · अपनी ही रेखा पर: {kept}',
      id: 'Berputar: {turned} · Di garisnya sendiri: {kept}',
      pt: 'Giraram: {turned} · Na própria reta: {kept}',
    },
    'head.turn': {
      en: 'Turned',
      ko: '돈 각',
      ja: '回った角',
      zh: '转角',
      ar: 'الدوران',
      es: 'Giro',
      fr: 'Rotation',
      hi: 'घुमाव',
      id: 'Putaran',
      pt: 'Giro',
    },
    'head.length': {
      en: 'Length',
      ko: '길이 배수',
      ja: '長さの倍率',
      zh: '长度倍数',
      ar: 'الطول',
      es: 'Longitud',
      fr: 'Longueur',
      hi: 'लंबाई',
      id: 'Panjang',
      pt: 'Comprimento',
    },
    'label.matrix': {
      en: 'A =',
      ko: 'A =',
      ja: 'A =',
      zh: 'A =',
      ar: 'A =',
      es: 'A =',
      fr: 'A =',
      hi: 'A =',
      id: 'A =',
      pt: 'A =',
    },
    'label.vec': {
      en: '({x}, {y})',
      ko: '({x}, {y})',
      ja: '({x}, {y})',
      zh: '({x}, {y})',
      ar: '({x}, {y})',
      es: '({x}, {y})',
      fr: '({x}, {y})',
      hi: '({x}, {y})',
      id: '({x}, {y})',
      pt: '({x}, {y})',
    },
    'label.deg': {
      en: '{deg}°',
      ko: '{deg}°',
      ja: '{deg}°',
      zh: '{deg}°',
      ar: '{deg}°',
      es: '{deg}°',
      fr: '{deg}°',
      hi: '{deg}°',
      id: '{deg}°',
      pt: '{deg}°',
    },
    'label.factor': {
      en: '×{k}',
      ko: '×{k}',
      ja: '×{k}',
      zh: '×{k}',
      ar: '×{k}',
      es: '×{k}',
      fr: '×{k}',
      hi: '×{k}',
      id: '×{k}',
      pt: '×{k}',
    },
    'label.eigen': {
      en: 'λ = {ev}',
      ko: 'λ = {ev}',
      ja: 'λ = {ev}',
      zh: 'λ = {ev}',
      ar: 'λ = {ev}',
      es: 'λ = {ev}',
      fr: 'λ = {ev}',
      hi: 'λ = {ev}',
      id: 'λ = {ev}',
      pt: 'λ = {ev}',
    },
    'label.v': {
      en: 'v',
      ko: 'v',
      ja: 'v',
      zh: 'v',
      ar: 'v',
      es: 'v',
      fr: 'v',
      hi: 'v',
      id: 'v',
      pt: 'v',
    },
    'label.av': {
      en: 'Av',
      ko: 'Av',
      ja: 'Av',
      zh: 'Av',
      ar: 'Av',
      es: 'Av',
      fr: 'Av',
      hi: 'Av',
      id: 'Av',
      pt: 'Av',
    },
  },
  blocks: {
    stage: { type: 'eigenvector-direction-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
