import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: CFS 는 매번 누구에게 CPU 를 주는가.
 *
 * 틱마다 가상 시간이 가장 작은(가장 뒤처진) 프로세스가 뽑혀 한 틱을 돌고, 그 가상 시간이
 * 제 무게에 따라 늘어난다. 무거운 것은 천천히 늘어 더 자주 뽑힌다.
 */
export const virtualRuntimeFacet: FacetJson = {
  id: 'facet:virtualRuntime',
  title: {
    en: 'Virtual runtime',
    ko: '가상 실행 시간',
    ja: '仮想実行時間',
    zh: '虚拟运行时间',
    ar: 'وقت التشغيل الافتراضي',
    es: 'Tiempo de ejecución virtual',
    fr: "Temps d'exécution virtuel",
    hi: 'वर्चुअल रनटाइम',
    id: 'Waktu jalan virtual',
    pt: 'Tempo de execução virtual',
  },
  description: {
    en: 'Each tick, the process furthest behind in virtual time runs and catches up',
    ko: '틱마다 가상 시간이 가장 뒤처진 프로세스가 돌며 따라붙는다',
    ja: '毎ティック、仮想時間が最も遅れているプロセスが走って追いつく',
    zh: '每个时钟节拍，虚拟时间最落后的进程运行并追上来',
    ar: 'في كل نبضة، تعمل العملية الأكثر تأخرًا في الوقت الافتراضي فتلحق بالبقية',
    es: 'En cada tic corre el proceso más atrasado en tiempo virtual y se pone al día',
    fr: 'À chaque tic, le processus le plus en retard en temps virtuel s’exécute et rattrape',
    hi: 'हर टिक पर वर्चुअल समय में सबसे पीछे की प्रक्रिया चलती है और बराबर आती है',
    id: 'Setiap tik, proses yang paling tertinggal dalam waktu virtual berjalan dan menyusul',
    pt: 'A cada tique, o processo mais atrasado no tempo virtual executa e alcança os outros',
  },
  algorithm: 'module:virtualRuntime',
  scene: 'module:virtualRuntimeScene',
  initialData: {
    type: 'virtual-runtime',
    stepMs: 1000,
    baseWeight: 2,
    ticks: 12,
    tasks: [
      { id: 'a', weight: 2 },
      { id: 'b', weight: 1 },
      { id: 'c', weight: 1 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Every virtual time starts at {v}',
      ko: '가상 시간은 모두 {v} 에서 출발한다',
      ja: '仮想時間はすべて {v} から始まる',
      zh: '所有虚拟时间都从 {v} 开始',
      ar: 'تبدأ كل الأوقات الافتراضية من {v}',
      es: 'Todos los tiempos virtuales empiezan en {v}',
      fr: 'Tous les temps virtuels partent de {v}',
      hi: 'सभी वर्चुअल समय {v} से शुरू होते हैं',
      id: 'Semua waktu virtual mulai dari {v}',
      pt: 'Todos os tempos virtuais começam em {v}',
    },
    'caption.pick': {
      en: 'Tick {tick} · furthest behind: {name}',
      ko: '틱 {tick} · 가장 뒤처진 것: {name}',
      ja: 'ティック {tick} · 最も遅れているもの: {name}',
      zh: '节拍 {tick} · 最落后的: {name}',
      ar: 'النبضة {tick} · الأكثر تأخرًا: {name}',
      es: 'Tic {tick} · el más atrasado: {name}',
      fr: 'Tic {tick} · le plus en retard : {name}',
      hi: 'टिक {tick} · सबसे पीछे: {name}',
      id: 'Tik {tick} · paling tertinggal: {name}',
      pt: 'Tique {tick} · o mais atrasado: {name}',
    },
    'caption.tie': {
      en: 'Tick {tick} · tied: {names} · longest since it ran: {name}',
      ko: '틱 {tick} · 동률: {names} · 가장 오래전에 돈 것: {name}',
      ja: 'ティック {tick} · 同点: {names} · 最も前に走ったもの: {name}',
      zh: '节拍 {tick} · 并列: {names} · 最久没运行的: {name}',
      ar: 'النبضة {tick} · تعادل: {names} · الأطول منذ آخر تشغيل: {name}',
      es: 'Tic {tick} · empate: {names} · el que corrió hace más tiempo: {name}',
      fr: 'Tic {tick} · égalité : {names} · exécuté il y a le plus longtemps : {name}',
      hi: 'टिक {tick} · बराबरी: {names} · सबसे पहले चला हुआ: {name}',
      id: 'Tik {tick} · seri: {names} · paling lama sejak berjalan: {name}',
      pt: 'Tique {tick} · empate: {names} · o que executou há mais tempo: {name}',
    },
    'caption.tieNever': {
      en: 'Tick {tick} · tied: {names} · first in the list not yet run: {name}',
      ko: '틱 {tick} · 동률: {names} · 아직 안 돈 것 중 목록 첫째: {name}',
      ja: 'ティック {tick} · 同点: {names} · まだ走っていないもののうち一覧の先頭: {name}',
      zh: '节拍 {tick} · 并列: {names} · 尚未运行者中列表第一个: {name}',
      ar: 'النبضة {tick} · تعادل: {names} · الأولى في القائمة بين ما لم يعمل بعد: {name}',
      es: 'Tic {tick} · empate: {names} · el primero de la lista que aún no ha corrido: {name}',
      fr: 'Tic {tick} · égalité : {names} · premier de la liste pas encore exécuté : {name}',
      hi: 'टिक {tick} · बराबरी: {names} · जो अभी नहीं चले उनमें सूची का पहला: {name}',
      id: 'Tik {tick} · seri: {names} · pertama dalam daftar yang belum berjalan: {name}',
      pt: 'Tique {tick} · empate: {names} · o primeiro da lista que ainda não executou: {name}',
    },
    'caption.advance': {
      en: 'Virtual time {from} → {to} (+{inc}, weight {w})',
      ko: '가상 시간 {from} → {to} (+{inc}, 무게 {w})',
      ja: '仮想時間 {from} → {to} (+{inc}、重み {w})',
      zh: '虚拟时间 {from} → {to}（+{inc}，权重 {w}）',
      ar: 'الوقت الافتراضي {from} ← {to} (+{inc}، الوزن {w})',
      es: 'Tiempo virtual {from} → {to} (+{inc}, peso {w})',
      fr: 'Temps virtuel {from} → {to} (+{inc}, poids {w})',
      hi: 'वर्चुअल समय {from} → {to} (+{inc}, भार {w})',
      id: 'Waktu virtual {from} → {to} (+{inc}, bobot {w})',
      pt: 'Tempo virtual {from} → {to} (+{inc}, peso {w})',
    },
    'caption.done': {
      en: 'Ticks run: {n}',
      ko: '돈 틱: {n}',
      ja: '実行したティック: {n}',
      zh: '已运行节拍: {n}',
      ar: 'النبضات المنفَّذة: {n}',
      es: 'Tics ejecutados: {n}',
      fr: 'Tics exécutés : {n}',
      hi: 'चले टिक: {n}',
      id: 'Tik yang dijalankan: {n}',
      pt: 'Tiques executados: {n}',
    },
    'caption.ratio': {
      en: 'Ticks used {used} · weights {weights}',
      ko: '쓴 틱 {used} · 무게 {weights}',
      ja: '使ったティック {used} · 重み {weights}',
      zh: '使用的节拍 {used} · 权重 {weights}',
      ar: 'النبضات المستخدمة {used} · الأوزان {weights}',
      es: 'Tics usados {used} · pesos {weights}',
      fr: 'Tics utilisés {used} · poids {weights}',
      hi: 'उपयोग किए टिक {used} · भार {weights}',
      id: 'Tik terpakai {used} · bobot {weights}',
      pt: 'Tiques usados {used} · pesos {weights}',
    },
    'label.axis': {
      en: 'Virtual time',
      ko: '가상 시간',
      ja: '仮想時間',
      zh: '虚拟时间',
      ar: 'الوقت الافتراضي',
      es: 'Tiempo virtual',
      fr: 'Temps virtuel',
      hi: 'वर्चुअल समय',
      id: 'Waktu virtual',
      pt: 'Tempo virtual',
    },
    'label.used': {
      en: 'Ticks used',
      ko: '쓴 틱',
      ja: '使ったティック',
      zh: '使用的节拍',
      ar: 'النبضات المستخدمة',
      es: 'Tics usados',
      fr: 'Tics utilisés',
      hi: 'उपयोग किए टिक',
      id: 'Tik terpakai',
      pt: 'Tiques usados',
    },
    'label.min': {
      en: 'Smallest virtual time',
      ko: '가장 작은 가상 시간',
      ja: '最小の仮想時間',
      zh: '最小虚拟时间',
      ar: 'أصغر وقت افتراضي',
      es: 'Menor tiempo virtual',
      fr: 'Plus petit temps virtuel',
      hi: 'सबसे कम वर्चुअल समय',
      id: 'Waktu virtual terkecil',
      pt: 'Menor tempo virtual',
    },
    'label.weight': {
      en: 'Weight {w}',
      ko: '무게 {w}',
      ja: '重み {w}',
      zh: '权重 {w}',
      ar: 'الوزن {w}',
      es: 'Peso {w}',
      fr: 'Poids {w}',
      hi: 'भार {w}',
      id: 'Bobot {w}',
      pt: 'Peso {w}',
    },
    'label.last': {
      en: 'Last ran: tick {n}',
      ko: '마지막: 틱 {n}',
      ja: '最後: ティック {n}',
      zh: '上次: 节拍 {n}',
      ar: 'آخر تشغيل: النبضة {n}',
      es: 'Última vez: tic {n}',
      fr: 'Dernière fois : tic {n}',
      hi: 'पिछली बार: टिक {n}',
      id: 'Terakhir: tik {n}',
      pt: 'Última vez: tique {n}',
    },
    'label.never': {
      en: 'Not run yet',
      ko: '아직 안 돎',
      ja: 'まだ走っていない',
      zh: '尚未运行',
      ar: 'لم تعمل بعد',
      es: 'Aún sin correr',
      fr: 'Pas encore exécuté',
      hi: 'अभी नहीं चला',
      id: 'Belum berjalan',
      pt: 'Ainda não executou',
    },
  },
  blocks: {
    stage: { type: 'virtual-runtime-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
