import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 줄을 뒤섞거나 같은 줄을 한 번 더 넣으면 다른 릴레이션이 되는가?
 *
 * 차례 A 의 네 줄이 차례 B 의 자리로 옮겨 앉고, 두 모음은 줄마다 짝이 맞아 같다고 판정된다.
 * 이미 있는 줄이 한 번 더 들어오면 같은 줄 위에 포개져 하나가 되고 줄 수는 그대로다.
 */
export const setOfRowsFacet: FacetJson = {
  id: 'facet:setOfRows',
  title: {
    en: 'A relation is a set of rows',
    ko: '릴레이션은 줄의 모음',
    ja: 'リレーションは行の集合',
    zh: '关系是行的集合',
    ar: 'العلاقة مجموعة من الصفوف',
    es: 'Una relación es un conjunto de filas',
    fr: 'Une relation est un ensemble de lignes',
    hi: 'संबंध पंक्तियों का समुच्चय है',
    id: 'Relasi adalah himpunan baris',
    pt: 'Uma relação é um conjunto de linhas',
  },
  description: {
    en: 'Reordering the rows or inserting an existing row again does not make a different relation.',
    ko: '줄의 차례를 바꾸거나 이미 있는 줄을 또 넣어도 다른 릴레이션이 되지 않는다.',
    ja: '行の順序を変えても、既にある行をもう一度入れても、別のリレーションにはならない。',
    zh: '改变行的顺序，或再次插入已有的行，都不会得到不同的关系。',
    ar: 'تغيير ترتيب الصفوف أو إدراج صف موجود مرة أخرى لا ينتج علاقة مختلفة.',
    es: 'Reordenar las filas o insertar otra vez una fila existente no da una relación distinta.',
    fr: 'Réordonner les lignes ou réinsérer une ligne existante ne donne pas une autre relation.',
    hi: 'पंक्तियों का क्रम बदलने या मौजूदा पंक्ति को फिर डालने से अलग संबंध नहीं बनता।',
    id: 'Mengubah urutan baris atau menyisipkan lagi baris yang sudah ada tidak menghasilkan relasi yang berbeda.',
    pt: 'Reordenar as linhas ou inserir de novo uma linha existente não gera uma relação diferente.',
  },
  algorithm: 'module:setOfRows',
  scene: 'module:setOfRowsScene',
  initialData: {
    type: 'set-of-rows',
    stepMs: 1600,
    relation: 'parts',
    columns: ['part_no', 'color'],
    orderA: [
      ['P1', 'red'],
      ['P2', 'blue'],
      ['P3', 'red'],
      ['P4', 'green'],
    ],
    orderB: [
      ['P3', 'red'],
      ['P1', 'red'],
      ['P4', 'green'],
      ['P2', 'blue'],
    ],
    incoming: ['P2', 'blue'],
  },
  shuffleOnReset: false,
  messages: {
    'label.orderA': {
      en: 'Order A',
      ko: '차례 A',
      ja: '順序 A',
      zh: '顺序 A',
      ar: 'الترتيب A',
      es: 'Orden A',
      fr: 'Ordre A',
      hi: 'क्रम A',
      id: 'Urutan A',
      pt: 'Ordem A',
    },
    'label.orderB': {
      en: 'Order B',
      ko: '차례 B',
      ja: '順序 B',
      zh: '顺序 B',
      ar: 'الترتيب B',
      es: 'Orden B',
      fr: 'Ordre B',
      hi: 'क्रम B',
      id: 'Urutan B',
      pt: 'Ordem B',
    },
    'label.rows': {
      en: 'Rows: {n}',
      ko: '줄 수: {n}',
      ja: '行数: {n}',
      zh: '行数：{n}',
      ar: 'عدد الصفوف: {n}',
      es: 'Filas: {n}',
      fr: 'Lignes : {n}',
      hi: 'पंक्तियाँ: {n}',
      id: 'Jumlah baris: {n}',
      pt: 'Linhas: {n}',
    },
    'caption.start': {
      en: 'The rows of the relation, listed in order A.',
      ko: '릴레이션의 줄들을 차례 A 로 적었다.',
      ja: 'リレーションの行を順序 A で並べた。',
      zh: '按顺序 A 列出关系的各行。',
      ar: 'صفوف العلاقة مرتبة بالترتيب A.',
      es: 'Las filas de la relación, listadas en el orden A.',
      fr: 'Les lignes de la relation, listées dans l’ordre A.',
      hi: 'संबंध की पंक्तियाँ, क्रम A में लिखी गईं।',
      id: 'Baris-baris relasi, ditulis dalam urutan A.',
      pt: 'As linhas da relação, listadas na ordem A.',
    },
    'caption.move': {
      en: 'The same rows take their seats in order B.',
      ko: '같은 줄들이 차례 B 의 자리로 옮겨 앉는다.',
      ja: '同じ行が順序 B の位置へ移って座る。',
      zh: '同样的行移到顺序 B 的位置上。',
      ar: 'الصفوف نفسها تنتقل إلى أماكنها في الترتيب B.',
      es: 'Las mismas filas ocupan sus puestos en el orden B.',
      fr: 'Les mêmes lignes prennent place dans l’ordre B.',
      hi: 'वही पंक्तियाँ क्रम B की जगहों पर जा बैठती हैं।',
      id: 'Baris yang sama pindah ke tempatnya dalam urutan B.',
      pt: 'As mesmas linhas ocupam seus lugares na ordem B.',
    },
    'caption.match': {
      en: 'Rows of A found in B: {x}/{n} · Rows of B found in A: {y}/{m}',
      ko: 'B 에 있는 A 의 줄: {x}/{n} · A 에 있는 B 의 줄: {y}/{m}',
      ja: 'B にある A の行: {x}/{n} · A にある B の行: {y}/{m}',
      zh: 'A 的行在 B 中：{x}/{n} · B 的行在 A 中：{y}/{m}',
      ar: 'صفوف A الموجودة في B: {x}/{n} · صفوف B الموجودة في A: {y}/{m}',
      es: 'Filas de A presentes en B: {x}/{n} · Filas de B presentes en A: {y}/{m}',
      fr: 'Lignes de A présentes dans B : {x}/{n} · Lignes de B présentes dans A : {y}/{m}',
      hi: 'B में मिली A की पंक्तियाँ: {x}/{n} · A में मिली B की पंक्तियाँ: {y}/{m}',
      id: 'Baris A yang ada di B: {x}/{n} · Baris B yang ada di A: {y}/{m}',
      pt: 'Linhas de A presentes em B: {x}/{n} · Linhas de B presentes em A: {y}/{m}',
    },
    'caption.enter': {
      en: 'Inserted once more: {row}',
      ko: '한 번 더 넣는 줄: {row}',
      ja: 'もう一度入れる行: {row}',
      zh: '再插入一次的行：{row}',
      ar: 'صف يُدرج مرة أخرى: {row}',
      es: 'Fila insertada otra vez: {row}',
      fr: 'Ligne insérée une fois de plus : {row}',
      hi: 'फिर से डाली गई पंक्ति: {row}',
      id: 'Baris yang disisipkan sekali lagi: {row}',
      pt: 'Linha inserida mais uma vez: {row}',
    },
    'caption.merge': {
      en: 'It lands on the equal row and becomes one. Rows: {before} → {after}',
      ko: '같은 줄 위에 포개져 하나가 된다. 줄 수: {before} → {after}',
      ja: '同じ行の上に重なって一つになる。行数: {before} → {after}',
      zh: '它落在相同的行上，合为一行。行数：{before} → {after}',
      ar: 'يستقر فوق الصف المطابق ويصبحان واحدًا. عدد الصفوف: {before} → {after}',
      es: 'Cae sobre la fila igual y queda una sola. Filas: {before} → {after}',
      fr: 'Elle se pose sur la ligne égale et n’en fait plus qu’une. Lignes : {before} → {after}',
      hi: 'यह बराबर पंक्ति पर आ बैठती है और दोनों एक हो जाती हैं। पंक्तियाँ: {before} → {after}',
      id: 'Baris itu menumpuk pada baris yang sama dan menjadi satu. Jumlah baris: {before} → {after}',
      pt: 'Ela pousa sobre a linha igual e vira uma só. Linhas: {before} → {after}',
    },
    'caption.join': {
      en: 'No equal row, so it is added. Rows: {before} → {after}',
      ko: '같은 줄이 없어 새로 더해진다. 줄 수: {before} → {after}',
      ja: '同じ行がないので新しく加わる。行数: {before} → {after}',
      zh: '没有相同的行，于是被加入。行数：{before} → {after}',
      ar: 'لا يوجد صف مطابق، فيُضاف. عدد الصفوف: {before} → {after}',
      es: 'No hay una fila igual, así que se añade. Filas: {before} → {after}',
      fr: 'Aucune ligne égale, elle est donc ajoutée. Lignes : {before} → {after}',
      hi: 'कोई बराबर पंक्ति नहीं, इसलिए यह जुड़ जाती है। पंक्तियाँ: {before} → {after}',
      id: 'Tidak ada baris yang sama, jadi baris itu ditambahkan. Jumlah baris: {before} → {after}',
      pt: 'Não há linha igual, então ela é adicionada. Linhas: {before} → {after}',
    },
    'verdict.same': {
      en: 'Same relation as A',
      ko: 'A 와 같은 릴레이션',
      ja: 'A と同じリレーション',
      zh: '与 A 是同一个关系',
      ar: 'العلاقة نفسها مثل A',
      es: 'La misma relación que A',
      fr: 'Même relation que A',
      hi: 'A जैसा ही संबंध',
      id: 'Relasi yang sama dengan A',
      pt: 'A mesma relação que A',
    },
    'verdict.differ': {
      en: 'Not the same relation as A',
      ko: 'A 와 다른 릴레이션',
      ja: 'A とは別のリレーション',
      zh: '与 A 不是同一个关系',
      ar: 'ليست العلاقة نفسها مثل A',
      es: 'No es la misma relación que A',
      fr: 'Pas la même relation que A',
      hi: 'A जैसा संबंध नहीं',
      id: 'Bukan relasi yang sama dengan A',
      pt: 'Não é a mesma relação que A',
    },
  },
  blocks: {
    stage: { type: 'set-of-rows-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
