import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 숫자 두 개 (3, 2) 는 어떻게 화살표 하나가 되고, 그 화살표는 평면의 어디에 있는가.
 *
 * 원점에서 가로로 3, 이어 세로로 2 를 걸어 간 끝이 머리가 되고, 원점에서 머리까지가
 * 화살표다. 같은 화살표를 모양 그대로 꼬리 셋으로 옮기면 머리 − 꼬리 는 옮길 때마다
 * 셈해도 같다 — 숫자쌍이 정하는 것은 자리가 아니라 옮겨 감이다.
 */
export const vectorAsArrowFacet: FacetJson = {
  id: 'facet:vectorAsArrow',
  title: {
    en: 'A pair of numbers becomes an arrow',
    ko: '숫자쌍이 화살표가 된다',
    ja: '数の組が矢印になる',
    zh: '数对变成箭头',
    ar: 'زوج من الأعداد يصبح سهمًا',
    es: 'Un par de números se vuelve una flecha',
    fr: 'Un couple de nombres devient une flèche',
    hi: 'संख्याओं का युग्म एक तीर बन जाता है',
    id: 'Sepasang bilangan menjadi panah',
    pt: 'Um par de números vira uma seta',
  },
  description: {
    en: 'Walk across, then up, from the origin: where you stop is the head, and the arrow runs from the origin to it. Slide the same arrow to other tails and head − tail stays the same pair.',
    ko: '원점에서 가로로, 이어 세로로 걸어 간 끝이 머리이고, 원점에서 그 머리까지가 화살표다. 같은 화살표를 다른 꼬리로 옮겨도 머리 − 꼬리 는 같은 숫자쌍이다.',
    ja: '原点から横へ、続いて縦へ歩いた先が終点で、原点からそこまでが矢印になる。同じ矢印を別の始点へ移しても、終点 − 始点 は同じ数の組のままだ。',
    zh: '从原点先横着走、再竖着走，停下的地方就是终点，从原点到终点就是箭头。把同一支箭头平移到别的起点，终点 − 起点 仍是同一个数对。',
    ar: 'امشِ أفقيًا ثم رأسيًا من نقطة الأصل: حيث تتوقف هو الرأس، والسهم يمتد من الأصل إليه. انقل السهم نفسه إلى ذيول أخرى فيبقى الرأس − الذيل الزوج نفسه.',
    es: 'Camina en horizontal y luego en vertical desde el origen: donde te detienes es la punta, y la flecha va del origen hasta ella. Desliza la misma flecha a otras colas y punta − cola sigue siendo el mismo par.',
    fr: "Depuis l'origine, avancez à l'horizontale puis à la verticale : le point d'arrivée est la tête, et la flèche va de l'origine jusqu'à elle. Glissez la même flèche vers d'autres queues : tête − queue reste le même couple.",
    hi: 'मूल बिंदु से पहले क्षैतिज, फिर ऊर्ध्वाधर चलिए: जहाँ रुकते हैं वह सिर है, और तीर मूल बिंदु से वहाँ तक जाता है। उसी तीर को दूसरी पूँछों पर खिसकाइए, सिर − पूँछ वही युग्म रहता है।',
    id: 'Dari titik asal, melangkah mendatar lalu tegak: tempat berhenti adalah kepala, dan panah membentang dari titik asal ke sana. Geser panah yang sama ke ekor lain, kepala − ekor tetap pasangan yang sama.',
    pt: 'Ande na horizontal e depois na vertical a partir da origem: onde você para é a ponta, e a seta vai da origem até ela. Deslize a mesma seta para outras caudas e ponta − cauda continua o mesmo par.',
  },
  algorithm: 'module:vectorAsArrow',
  scene: 'module:vectorAsArrowScene',
  initialData: {
    type: 'vector-as-arrow',
    stepMs: 1600,
    name: 'v',
    v: [3, 2],
    tails: [
      [-5, 1],
      [-2, -4],
      [1, -3],
    ],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'vector-as-arrow-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'Pair {pair} · start: origin {origin}',
      ko: '숫자쌍 {pair} · 출발: 원점 {origin}',
      ja: '数の組 {pair} · 出発: 原点 {origin}',
      zh: '数对 {pair} · 出发: 原点 {origin}',
      ar: 'الزوج {pair} · البداية: نقطة الأصل {origin}',
      es: 'Par {pair} · salida: origen {origin}',
      fr: 'Couple {pair} · départ : origine {origin}',
      hi: 'युग्म {pair} · आरंभ: मूल बिंदु {origin}',
      id: 'Pasangan {pair} · mulai: titik asal {origin}',
      pt: 'Par {pair} · partida: origem {origin}',
    },
    'caption.walkX': {
      en: 'Horizontal: {n} · {from} → {to}',
      ko: '가로: {n} · {from} → {to}',
      ja: '横: {n} · {from} → {to}',
      zh: '横向: {n} · {from} → {to}',
      ar: 'أفقيًا: {n} · {from} → {to}',
      es: 'Horizontal: {n} · {from} → {to}',
      fr: 'Horizontal : {n} · {from} → {to}',
      hi: 'क्षैतिज: {n} · {from} → {to}',
      id: 'Mendatar: {n} · {from} → {to}',
      pt: 'Horizontal: {n} · {from} → {to}',
    },
    'caption.walkY': {
      en: 'Vertical: {n} · {from} → {to} · arrow {tail} → {head}',
      ko: '세로: {n} · {from} → {to} · 화살표 {tail} → {head}',
      ja: '縦: {n} · {from} → {to} · 矢印 {tail} → {head}',
      zh: '纵向: {n} · {from} → {to} · 箭头 {tail} → {head}',
      ar: 'رأسيًا: {n} · {from} → {to} · السهم {tail} → {head}',
      es: 'Vertical: {n} · {from} → {to} · flecha {tail} → {head}',
      fr: 'Vertical : {n} · {from} → {to} · flèche {tail} → {head}',
      hi: 'ऊर्ध्वाधर: {n} · {from} → {to} · तीर {tail} → {head}',
      id: 'Tegak: {n} · {from} → {to} · panah {tail} → {head}',
      pt: 'Vertical: {n} · {from} → {to} · seta {tail} → {head}',
    },
    'caption.place': {
      en: 'Moved · tail {tail} · head {head} · head − tail = {diff}',
      ko: '옮김 · 꼬리 {tail} · 머리 {head} · 머리 − 꼬리 = {diff}',
      ja: '移動 · 始点 {tail} · 終点 {head} · 終点 − 始点 = {diff}',
      zh: '平移 · 起点 {tail} · 终点 {head} · 终点 − 起点 = {diff}',
      ar: 'نُقل · الذيل {tail} · الرأس {head} · الرأس − الذيل = {diff}',
      es: 'Movida · cola {tail} · punta {head} · punta − cola = {diff}',
      fr: 'Déplacée · queue {tail} · tête {head} · tête − queue = {diff}',
      hi: 'खिसकाया · पूँछ {tail} · सिर {head} · सिर − पूँछ = {diff}',
      id: 'Dipindah · ekor {tail} · kepala {head} · kepala − ekor = {diff}',
      pt: 'Movida · cauda {tail} · ponta {head} · ponta − cauda = {diff}',
    },
    'label.tail': {
      en: 'tail',
      ko: '꼬리',
      ja: '始点',
      zh: '起点',
      ar: 'الذيل',
      es: 'cola',
      fr: 'queue',
      hi: 'पूँछ',
      id: 'ekor',
      pt: 'cauda',
    },
    'label.head': {
      en: 'head',
      ko: '머리',
      ja: '終点',
      zh: '终点',
      ar: 'الرأس',
      es: 'punta',
      fr: 'tête',
      hi: 'सिर',
      id: 'kepala',
      pt: 'ponta',
    },
    'label.diff': {
      en: 'head − tail',
      ko: '머리 − 꼬리',
      ja: '終点 − 始点',
      zh: '终点 − 起点',
      ar: 'الرأس − الذيل',
      es: 'punta − cola',
      fr: 'tête − queue',
      hi: 'सिर − पूँछ',
      id: 'kepala − ekor',
      pt: 'ponta − cauda',
    },
  },
};
