import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: BGP 는 같은 목적지로 가는 길 여럿을 받으면 무엇을 보고 하나를 고르는가.
 *
 * 이웃 넷이 보낸 길(거쳐 온 AS 번호의 줄)이 닿고, 내 번호가 든 길이 먼저 걸러져 나가고,
 * 남은 셋이 이웃과의 관계로 매긴 선호에 따라 줄을 서서 가장 짧은 길이 아닌 길이 맨 앞에 선다.
 * AS 번호는 문서용 대역(64496–64511), 목적지는 문서용 망이다. 선호 값은 예로 정한 값이다.
 */
export const pathVectorPolicyFacet: FacetJson = {
  id: 'facet:pathVectorPolicy',
  title: {
    en: 'Path vector: chosen by policy',
    ko: '경로 벡터 — 정책으로 고른다',
    ja: 'パスベクトル — ポリシーで選ぶ',
    zh: '路径向量 — 按策略选择',
    ar: 'متجه المسار — الاختيار حسب السياسة',
    es: 'Vector de rutas: elegido por política',
    fr: 'Vecteur de chemins : choisi par politique',
    hi: 'पाथ वेक्टर — नीति से चुनाव',
    id: 'Path vector: dipilih menurut kebijakan',
    pt: 'Vetor de caminhos: escolhido por política',
  },
  description: {
    en: 'Paths from four neighbors arrive; the one holding our own number is dropped, and the rest line up by relationship preference.',
    ko: '이웃 넷이 보낸 길이 닿고, 내 번호가 든 길은 걸러지고, 남은 길은 관계로 매긴 선호대로 줄을 선다.',
    ja: '四つの隣接 AS から経路が届き、自分の番号を含む経路は捨てられ、残りは関係による優先度の順に並ぶ。',
    zh: '四个邻居发来的路径到达，含有自己编号的路径被丢弃，其余按关系设定的优先级排队。',
    ar: 'تصل مسارات من أربعة جيران؛ يُسقَط المسار الذي يحوي رقمنا، ويصطف الباقي حسب تفضيل العلاقة.',
    es: 'Llegan rutas de cuatro vecinos; la que contiene nuestro propio número se descarta y el resto se ordena por la preferencia de la relación.',
    fr: 'Les chemins de quatre voisins arrivent ; celui qui contient notre propre numéro est écarté, les autres se rangent selon la préférence de la relation.',
    hi: 'चार पड़ोसियों के पथ आते हैं; जिस पथ में अपना नंबर है वह हटता है, बाकी संबंध की पसंद के क्रम में लगते हैं।',
    id: 'Jalur dari empat tetangga tiba; jalur yang memuat nomor sendiri dibuang, sisanya berbaris menurut preferensi hubungan.',
    pt: 'Chegam caminhos de quatro vizinhos; o que contém o nosso próprio número é descartado e o resto se ordena pela preferência da relação.',
  },
  algorithm: 'module:pathVectorPolicy',
  scene: 'module:pathVectorPolicyScene',
  initialData: {
    type: 'path-vector-policy',
    stepMs: 2000,
    me: 64500,
    prefix: '192.0.2.0/24',
    origin: 64510,
    prefs: [
      { rel: 'customer', pref: 200 },
      { rel: 'peer', pref: 150 },
      { rel: 'provider', pref: 100 },
    ],
    routes: [
      { from: 64501, rel: 'provider', path: [64501, 64510] },
      { from: 64502, rel: 'customer', path: [64502, 64505, 64507, 64510] },
      { from: 64503, rel: 'peer', path: [64503, 64508, 64510] },
      { from: 64504, rel: 'peer', path: [64504, 64500, 64510] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.me': {
      en: 'Me',
      ko: '나',
      ja: '自分',
      zh: '自己',
      ar: 'أنا',
      es: 'Yo',
      fr: 'Moi',
      hi: 'मैं',
      id: 'Saya',
      pt: 'Eu',
    },
    'label.destination': {
      en: 'Destination',
      ko: '목적지',
      ja: '宛先',
      zh: '目的地',
      ar: 'الوجهة',
      es: 'Destino',
      fr: 'Destination',
      hi: 'गंतव्य',
      id: 'Tujuan',
      pt: 'Destino',
    },
    'label.discarded': {
      en: 'Discarded',
      ko: '버림',
      ja: '破棄',
      zh: '丢弃',
      ar: 'مُسقَط',
      es: 'Descartado',
      fr: 'Écarté',
      hi: 'हटाया गया',
      id: 'Dibuang',
      pt: 'Descartado',
    },
    'label.pref': {
      en: 'Preference',
      ko: '선호',
      ja: '優先度',
      zh: '优先级',
      ar: 'التفضيل',
      es: 'Preferencia',
      fr: 'Préférence',
      hi: 'पसंद',
      id: 'Preferensi',
      pt: 'Preferência',
    },
    'label.customer': {
      en: 'Customer',
      ko: '고객',
      ja: '顧客',
      zh: '客户',
      ar: 'عميل',
      es: 'Cliente',
      fr: 'Client',
      hi: 'ग्राहक',
      id: 'Pelanggan',
      pt: 'Cliente',
    },
    'label.peer': {
      en: 'Peer',
      ko: '동등',
      ja: 'ピア',
      zh: '对等',
      ar: 'نظير',
      es: 'Par',
      fr: 'Pair',
      hi: 'समकक्ष',
      id: 'Setara',
      pt: 'Par',
    },
    'label.provider': {
      en: 'Provider',
      ko: '제공자',
      ja: 'プロバイダ',
      zh: '提供商',
      ar: 'مزوّد',
      es: 'Proveedor',
      fr: 'Fournisseur',
      hi: 'प्रदाता',
      id: 'Penyedia',
      pt: 'Provedor',
    },
    'caption.start': {
      en: 'Waiting for paths from the neighbors.',
      ko: '이웃이 보낼 길을 기다린다.',
      ja: '隣接 AS から経路が届くのを待つ。',
      zh: '等待邻居发来的路径。',
      ar: 'بانتظار المسارات من الجيران.',
      es: 'Esperando las rutas de los vecinos.',
      fr: 'En attente des chemins des voisins.',
      hi: 'पड़ोसियों के पथों की प्रतीक्षा।',
      id: 'Menunggu jalur dari para tetangga.',
      pt: 'Aguardando os caminhos dos vizinhos.',
    },
    'caption.arrive': {
      en: 'Paths received: {n}',
      ko: '받은 길: {n}',
      ja: '届いた経路: {n}',
      zh: '收到的路径: {n}',
      ar: 'المسارات المستلمة: {n}',
      es: 'Rutas recibidas: {n}',
      fr: 'Chemins reçus : {n}',
      hi: 'मिले पथ: {n}',
      id: 'Jalur diterima: {n}',
      pt: 'Caminhos recebidos: {n}',
    },
    'caption.left': {
      en: 'Paths left: {n}',
      ko: '남은 길: {n}',
      ja: '残った経路: {n}',
      zh: '剩余路径: {n}',
      ar: 'المسارات المتبقية: {n}',
      es: 'Rutas restantes: {n}',
      fr: 'Chemins restants : {n}',
      hi: 'बचे पथ: {n}',
      id: 'Jalur tersisa: {n}',
      pt: 'Caminhos restantes: {n}',
    },
    'caption.noLoop': {
      en: 'No path holds own number AS{me}.',
      ko: '내 번호 AS{me} — 든 길이 없다.',
      ja: '自分の番号 AS{me} — 含む経路はない。',
      zh: '自己的编号 AS{me} — 没有路径包含它。',
      ar: 'لا يحوي أي مسار رقمنا AS{me}.',
      es: 'Ninguna ruta contiene nuestro número AS{me}.',
      fr: 'Aucun chemin ne contient notre numéro AS{me}.',
      hi: 'अपना नंबर AS{me} — किसी पथ में नहीं।',
      id: 'Tidak ada jalur yang memuat nomor sendiri AS{me}.',
      pt: 'Nenhum caminho contém o nosso número AS{me}.',
    },
    'caption.loop': {
      en: 'Own number AS{me} in the path from {from}: a loop, dropped.',
      ko: '{from} 에게서 온 길에 내 번호 AS{me} — 고리라서 버린다.',
      ja: '{from} からの経路に自分の番号 AS{me} — ループなので捨てる。',
      zh: '来自 {from} 的路径中有自己的编号 AS{me} — 是环路，丢弃。',
      ar: 'رقمنا AS{me} في المسار القادم من {from}: حلقة، يُسقَط.',
      es: 'Nuestro número AS{me} en la ruta de {from}: un bucle, se descarta.',
      fr: 'Notre numéro AS{me} dans le chemin venu de {from} : une boucle, écarté.',
      hi: '{from} से आए पथ में अपना नंबर AS{me} — लूप, हटाया।',
      id: 'Nomor sendiri AS{me} ada di jalur dari {from}: putaran, dibuang.',
      pt: 'Nosso número AS{me} no caminho vindo de {from}: um laço, descartado.',
    },
    'caption.rank': {
      en: 'Each path gets a preference from the relationship with its neighbor.',
      ko: '이웃과의 관계로 길마다 선호를 매긴다.',
      ja: '隣接 AS との関係で経路ごとに優先度を付ける。',
      zh: '按与邻居的关系给每条路径设定优先级。',
      ar: 'يأخذ كل مسار تفضيلًا من العلاقة مع جاره.',
      es: 'Cada ruta recibe una preferencia según la relación con su vecino.',
      fr: 'Chaque chemin reçoit une préférence selon la relation avec son voisin.',
      hi: 'पड़ोसी से संबंध के अनुसार हर पथ को पसंद मिलती है।',
      id: 'Setiap jalur diberi preferensi menurut hubungan dengan tetangganya.',
      pt: 'Cada caminho recebe uma preferência pela relação com seu vizinho.',
    },
    'caption.pick': {
      en: 'Chosen: AS{from} — preference {pref} · length {len}',
      ko: '고른 길: AS{from} — 선호 {pref} · 길이 {len}',
      ja: '選んだ経路: AS{from} — 優先度 {pref} · 長さ {len}',
      zh: '选中的路径: AS{from} — 优先级 {pref} · 长度 {len}',
      ar: 'المختار: AS{from} — التفضيل {pref} · الطول {len}',
      es: 'Elegida: AS{from} — preferencia {pref} · longitud {len}',
      fr: 'Choisi : AS{from} — préférence {pref} · longueur {len}',
      hi: 'चुना गया: AS{from} — पसंद {pref} · लंबाई {len}',
      id: 'Dipilih: AS{from} — preferensi {pref} · panjang {len}',
      pt: 'Escolhido: AS{from} — preferência {pref} · comprimento {len}',
    },
    'caption.shortest': {
      en: 'Shortest: AS{from} — length {len} · place {rank}/{count}',
      ko: '가장 짧은 길: AS{from} — 길이 {len} · 순위 {rank}/{count}',
      ja: '最短の経路: AS{from} — 長さ {len} · 順位 {rank}/{count}',
      zh: '最短路径: AS{from} — 长度 {len} · 名次 {rank}/{count}',
      ar: 'الأقصر: AS{from} — الطول {len} · الترتيب {rank}/{count}',
      es: 'La más corta: AS{from} — longitud {len} · puesto {rank}/{count}',
      fr: 'Le plus court : AS{from} — longueur {len} · rang {rank}/{count}',
      hi: 'सबसे छोटा: AS{from} — लंबाई {len} · स्थान {rank}/{count}',
      id: 'Terpendek: AS{from} — panjang {len} · urutan {rank}/{count}',
      pt: 'O mais curto: AS{from} — comprimento {len} · posição {rank}/{count}',
    },
  },
  blocks: {
    stage: { type: 'path-vector-policy-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
