import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 일관 해싱에서 키 하나는 어느 서버가 맡는지 어떻게 정해지는가.
 *
 * 서버 셋이 제 이름의 해시로 고리 위 자리를 잡고, 키 여섯이 하나씩 제 해시로 자리를 잡은 뒤
 * 수가 커지는 쪽(시계 방향)으로 걸어 처음 만나는 서버에 멈춘다. 자리 · 주인 · 걸은 칸은
 * 알고리즘이 셈한다 — initialData 에는 해시 입력(식별자)과 고리 크기만 둔다.
 */
export const ringOfHashesFacet: FacetJson = {
  id: 'facet:ringOfHashes',
  title: {
    en: 'Ring of hashes',
    ko: '해시 고리',
    ja: 'ハッシュのリング',
    zh: '哈希环',
    ar: 'حلقة التجزئة',
    es: 'Anillo de hashes',
    fr: 'Anneau de hachage',
    hi: 'हैश का वलय',
    id: 'Cincin hash',
    pt: 'Anel de hashes',
  },
  description: {
    en: 'A server takes its place on the ring by the hash of its name; a key walks clockwise from its own place to the first server it meets.',
    ko: '서버는 제 이름의 해시로 고리 위에 자리를 잡고, 키는 제 자리에서 시계 방향으로 걸어 처음 만나는 서버에 멈춘다.',
    ja: 'サーバーは名前のハッシュでリング上の位置を取り、キーは自分の位置から時計回りに歩いて最初に出会うサーバーで止まる。',
    zh: '服务器按名字的哈希在环上占位；键从自己的位置顺时针走，停在遇到的第一台服务器。',
    ar: 'يأخذ الخادم مكانه على الحلقة من تجزئة اسمه، ويمشي المفتاح من مكانه باتجاه عقارب الساعة حتى أول خادم يلقاه.',
    es: 'Un servidor ocupa su lugar en el anillo según el hash de su nombre; una clave camina en sentido horario desde su lugar hasta el primer servidor que encuentra.',
    fr: 'Un serveur prend sa place sur l’anneau selon le hachage de son nom ; une clé marche dans le sens horaire depuis sa place jusqu’au premier serveur rencontré.',
    hi: 'सर्वर अपने नाम के हैश से वलय पर जगह लेता है; कुंजी अपनी जगह से घड़ी की दिशा में चलकर पहले मिलने वाले सर्वर पर रुकती है।',
    id: 'Server mengambil tempat di cincin menurut hash namanya; kunci berjalan searah jarum jam dari tempatnya sampai server pertama yang ditemui.',
    pt: 'Um servidor ocupa seu lugar no anel pelo hash do próprio nome; uma chave caminha no sentido horário a partir do seu lugar até o primeiro servidor que encontra.',
  },
  algorithm: 'module:ringOfHashes',
  scene: 'module:ringOfHashesScene',
  initialData: {
    type: 'ring-of-hashes',
    stepMs: 1100,
    size: 100,
    servers: ['cache-a', 'cache-b', 'cache-c'],
    keys: ['cart:ben', 'cart:gus', 'cart:ian', 'cart:eva', 'cart:cho', 'cart:ana'],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'The ring is empty. Positions: 0–{max}.',
      ko: '고리는 비어 있다. 자리는 0–{max}.',
      ja: 'リングは空です。位置: 0–{max}。',
      zh: '环是空的。位置：0–{max}。',
      ar: 'الحلقة فارغة. المواضع: 0–{max}.',
      es: 'El anillo está vacío. Posiciones: 0–{max}.',
      fr: 'L’anneau est vide. Positions : 0–{max}.',
      hi: 'वलय खाली है। स्थान: 0–{max}।',
      id: 'Cincin masih kosong. Posisi: 0–{max}.',
      pt: 'O anel está vazio. Posições: 0–{max}.',
    },
    'caption.server': {
      en: '{server} hashes its own name and takes position {p}.',
      ko: '{server} — 제 이름을 해시한 자리: {p}.',
      ja: '{server} — 自分の名前のハッシュで位置 {p} を取る。',
      zh: '{server} 用自己名字的哈希占据位置 {p}。',
      ar: '{server} يجزّئ اسمه ويأخذ الموضع {p}.',
      es: '{server} calcula el hash de su nombre y ocupa la posición {p}.',
      fr: '{server} hache son propre nom et prend la position {p}.',
      hi: '{server} अपने नाम का हैश लेकर स्थान {p} पर बैठता है।',
      id: '{server} meng-hash namanya sendiri dan mengambil posisi {p}.',
      pt: '{server} calcula o hash do próprio nome e ocupa a posição {p}.',
    },
    'caption.key': {
      en: '{key} hashes to position {p} and walks clockwise. First server met: {server}. Positions walked: {d}.',
      ko: '{key} — 해시한 자리: {p}. 시계 방향으로 걸어 처음 만난 서버: {server} · 걸은 칸: {d}.',
      ja: '{key} — ハッシュの位置: {p}。時計回りに歩く。最初に出会うサーバー: {server}。歩いた位置数: {d}。',
      zh: '{key} 哈希到位置 {p}，顺时针走。遇到的第一台服务器：{server}。走过的位置数：{d}。',
      ar: '{key} يُجزَّأ إلى الموضع {p} ويمشي باتجاه عقارب الساعة. أول خادم يلقاه: {server}. المواضع المقطوعة: {d}.',
      es: '{key} cae en la posición {p} y camina en sentido horario. Primer servidor encontrado: {server}. Posiciones recorridas: {d}.',
      fr: '{key} tombe à la position {p} et marche dans le sens horaire. Premier serveur rencontré : {server}. Positions parcourues : {d}.',
      hi: '{key} का हैश स्थान {p} देता है, और वह घड़ी की दिशा में चलती है। पहला मिला सर्वर: {server}। चले गए स्थान: {d}।',
      id: '{key} jatuh di posisi {p} dan berjalan searah jarum jam. Server pertama yang ditemui: {server}. Posisi yang dilalui: {d}.',
      pt: '{key} cai na posição {p} e caminha no sentido horário. Primeiro servidor encontrado: {server}. Posições percorridas: {d}.',
    },
    'caption.keyWrap': {
      en: '{key} hashes to position {p} and walks clockwise, past {max} back to 0. First server met: {server}. Positions walked: {d}.',
      ko: '{key} — 해시한 자리: {p}. 시계 방향으로 걷다 {max} 다음 0 으로 감아 돈다. 처음 만난 서버: {server} · 걸은 칸: {d}.',
      ja: '{key} — ハッシュの位置: {p}。時計回りに歩き、{max} を越えて 0 に戻る。最初に出会うサーバー: {server}。歩いた位置数: {d}。',
      zh: '{key} 哈希到位置 {p}，顺时针走，越过 {max} 回到 0。遇到的第一台服务器：{server}。走过的位置数：{d}。',
      ar: '{key} يُجزَّأ إلى الموضع {p} ويمشي باتجاه عقارب الساعة، متجاوزًا {max} عائدًا إلى 0. أول خادم يلقاه: {server}. المواضع المقطوعة: {d}.',
      es: '{key} cae en la posición {p} y camina en sentido horario, pasa de {max} y vuelve a 0. Primer servidor encontrado: {server}. Posiciones recorridas: {d}.',
      fr: '{key} tombe à la position {p} et marche dans le sens horaire, dépasse {max} et revient à 0. Premier serveur rencontré : {server}. Positions parcourues : {d}.',
      hi: '{key} का हैश स्थान {p} देता है; वह घड़ी की दिशा में चलती है, {max} के बाद 0 पर लौटती है। पहला मिला सर्वर: {server}। चले गए स्थान: {d}।',
      id: '{key} jatuh di posisi {p} dan berjalan searah jarum jam, melewati {max} kembali ke 0. Server pertama yang ditemui: {server}. Posisi yang dilalui: {d}.',
      pt: '{key} cai na posição {p} e caminha no sentido horário, passa de {max} e volta a 0. Primeiro servidor encontrado: {server}. Posições percorridas: {d}.',
    },
    'label.servers': {
      en: 'Servers',
      ko: '서버',
      ja: 'サーバー',
      zh: '服务器',
      ar: 'الخوادم',
      es: 'Servidores',
      fr: 'Serveurs',
      hi: 'सर्वर',
      id: 'Server',
      pt: 'Servidores',
    },
    'label.keys': {
      en: 'Keys',
      ko: '키',
      ja: 'キー',
      zh: '键',
      ar: 'المفاتيح',
      es: 'Claves',
      fr: 'Clés',
      hi: 'कुंजियाँ',
      id: 'Kunci',
      pt: 'Chaves',
    },
  },
  blocks: {
    stage: { type: 'ring-of-hashes-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
