/**
 * 경사 하강 — 어느 바닥에 서는가. 선언.
 *
 * initialData 는 1차 데이터(사다리 · 멈춤 규약 · 곡선 표본 격자)만 둔다. 두 바닥 · 언덕 · 곡선 표본 ·
 * 끝난 모양 · 계기는 algorithm 이 셈한다. `lossTop` 은 곡선 단면 창의 L 윗끝(그림 틀)이다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { GradientDescentData } from './algorithm.js';

const initialData: GradientDescentData = {
  type: 'gradient-descent',
  stepMs: 300,
  etaLadder: [0.02, 0.1, 0.15, 0.2, 0.25, 0.35],
  eta: 0.15,
  startLadder: [1.6, 1.4],
  start: 1.6,
  maxSteps: 60,
  stopBelow: 0.01,
  blowUp: 100,
  gridFrom: -200,
  gridTo: 200,
  gridDiv: 100,
  lossTop: 3,
};

export const gradientDescentFacet: FacetJson = {
  id: 'facet:gradientDescent',
  title: {
    en: 'Gradient descent — which valley?',
    ko: '경사 하강법 — 어느 바닥에 서는가',
    ja: '勾配降下法 — どの谷に止まるか',
    zh: '梯度下降 — 停在哪个谷底',
    ar: 'الانحدار التدريجي — في أي وادٍ يستقر؟',
    es: 'Descenso de gradiente — ¿en qué valle?',
    fr: 'Descente de gradient — dans quelle vallée ?',
    hi: 'ग्रेडिएंट डिसेंट — किस घाटी में रुकता है?',
    id: 'Penurunan gradien — di lembah mana?',
    pt: 'Descida do gradiente — em qual vale?',
  },
  description: {
    en: 'On one curve with two valleys, gradient descent repeats w ← w − η·g. The learning rate η and the start w₀ pick the valley together: at η 0.15, starting from 1.6 ends in the deep valley while 1.4 ends in the shallow one. At η 0.25 it does not stop within 60 updates, and at 0.35 from 1.6 it leaves the curve.',
    ko: '바닥이 둘인 곡선 하나에서 경사 하강이 w ← w − η·g 를 되풀이한다. 학습률 η 와 출발 w₀ 가 함께 바닥을 고른다 — η 0.15 에서 출발 1.6 은 깊은 바닥에, 1.4 는 얕은 바닥에 선다. η 0.25 에서는 갱신 60 번 안에 서지 못하고, 0.35 에서 출발 1.6 은 곡선 밖으로 나간다.',
    ja: '谷が二つある一本の曲線の上で、勾配降下は w ← w − η·g を繰り返す。学習率 η と出発点 w₀ が一緒に谷を選ぶ — η 0.15 では出発 1.6 は深い谷に、1.4 は浅い谷に止まる。η 0.25 では 60 回の更新のうちに止まらず、0.35 で出発 1.6 だと曲線の外へ出ていく。',
    zh: '在一条有两个谷底的曲线上，梯度下降反复执行 w ← w − η·g。学习率 η 和起点 w₀ 共同决定停在哪个谷底：η 0.15 时，从 1.6 出发停在深谷，从 1.4 出发停在浅谷。η 0.25 时在 60 次更新内停不下来，η 0.35 从 1.6 出发会离开曲线。',
    ar: 'على منحنى واحد له واديان، يكرر الانحدار التدريجي w ← w − η·g. معدل التعلم η ونقطة البداية w₀ يختاران الوادي معًا: عند η 0.15 تنتهي البداية من 1.6 في الوادي العميق بينما تنتهي البداية من 1.4 في الوادي الضحل. عند η 0.25 لا يستقر خلال 60 تحديثًا، وعند 0.35 من 1.6 يخرج عن المنحنى.',
    es: 'En una curva con dos valles, el descenso de gradiente repite w ← w − η·g. La tasa de aprendizaje η y el inicio w₀ eligen el valle juntos: con η 0.15, empezar en 1.6 termina en el valle profundo y empezar en 1.4 en el poco profundo. Con η 0.25 no se detiene en 60 actualizaciones, y con 0.35 desde 1.6 sale de la curva.',
    fr: 'Sur une courbe à deux vallées, la descente de gradient répète w ← w − η·g. Le taux d’apprentissage η et le départ w₀ choisissent la vallée ensemble : avec η 0.15, partir de 1.6 finit dans la vallée profonde et partir de 1.4 dans la vallée peu profonde. Avec η 0.25 elle ne s’arrête pas en 60 mises à jour, et avec 0.35 depuis 1.6 elle sort de la courbe.',
    hi: 'दो घाटियों वाले एक वक्र पर ग्रेडिएंट डिसेंट w ← w − η·g दोहराता है। सीखने की दर η और शुरुआत w₀ मिलकर घाटी चुनते हैं: η 0.15 पर 1.6 से शुरू करने पर यह गहरी घाटी में रुकता है, जबकि 1.4 से उथली घाटी में। η 0.25 पर यह 60 अद्यतनों के भीतर नहीं रुकता, और 0.35 पर 1.6 से यह वक्र से बाहर चला जाता है।',
    id: 'Pada satu kurva dengan dua lembah, penurunan gradien mengulang w ← w − η·g. Laju belajar η dan awal w₀ bersama-sama memilih lembah: pada η 0.15, mulai dari 1.6 berakhir di lembah dalam, sedangkan dari 1.4 di lembah dangkal. Pada η 0.25 ia tidak berhenti dalam 60 pembaruan, dan pada 0.35 dari 1.6 ia keluar dari kurva.',
    pt: 'Numa curva com dois vales, a descida do gradiente repete w ← w − η·g. A taxa de aprendizado η e o início w₀ escolhem o vale juntos: com η 0.15, começar em 1.6 termina no vale profundo e começar em 1.4 no vale raso. Com η 0.25 não para em 60 atualizações, e com 0.35 a partir de 1.6 sai da curva.',
  },
  algorithm: 'module:gradientDescent',
  projector: 'module:gradientDescentProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'gradient-descent-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'eta',
          name: 'eta',
          label: {
            en: 'Learning rate η',
            ko: '학습률 η',
            ja: '学習率 η',
            zh: '学习率 η',
            ar: 'معدل التعلم η',
            es: 'Tasa de aprendizaje η',
            fr: 'Taux d’apprentissage η',
            hi: 'सीखने की दर η',
            id: 'Laju belajar η',
            pt: 'Taxa de aprendizado η',
          },
          segments: [
            { value: 0.02, label: '0.02' },
            { value: 0.1, label: '0.1' },
            { value: 0.15, label: '0.15', default: true },
            { value: 0.2, label: '0.2' },
            { value: 0.25, label: '0.25' },
            { value: 0.35, label: '0.35' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'start',
          name: 'start',
          label: {
            en: 'Start w₀',
            ko: '출발 w₀',
            ja: '出発点 w₀',
            zh: '起点 w₀',
            ar: 'البداية w₀',
            es: 'Inicio w₀',
            fr: 'Départ w₀',
            hi: 'शुरुआत w₀',
            id: 'Awal w₀',
            pt: 'Início w₀',
          },
          segments: [
            { value: 1.6, label: '1.6', default: true },
            { value: 1.4, label: '1.4' },
          ],
        },
      ],
      metrics: [
        {
          name: 'updates',
          label: {
            en: 'Updates',
            ko: '갱신 수',
            ja: '更新回数',
            zh: '更新次数',
            ar: 'عدد التحديثات',
            es: 'Actualizaciones',
            fr: 'Mises à jour',
            hi: 'अद्यतन',
            id: 'Pembaruan',
            pt: 'Atualizações',
          },
          initial: 0,
        },
        {
          name: 'hump-crossings',
          label: {
            en: 'Hump crossings',
            ko: '언덕 넘은 갱신',
            ja: '丘を越えた更新',
            zh: '越过山丘的更新',
            ar: 'تحديثات عبرت التل',
            es: 'Saltos sobre la loma',
            fr: 'Passages de la bosse',
            hi: 'टीला पार करने वाले अद्यतन',
            id: 'Lompatan atas bukit',
            pt: 'Saltos sobre a lomba',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:gradient-descent-imperative',
      label: {
        en: 'Gradient descent',
        ko: '경사 하강',
        ja: '勾配降下',
        zh: '梯度下降',
        ar: 'الانحدار التدريجي',
        es: 'Descenso de gradiente',
        fr: 'Descente de gradient',
        hi: 'ग्रेडिएंट डिसेंट',
        id: 'Penurunan gradien',
        pt: 'Descida do gradiente',
      },
    },
  },
  messages: {
    'label.rule': {
      en: 'w ← w − η·g',
      ko: 'w ← w − η·g',
      ja: 'w ← w − η·g',
      zh: 'w ← w − η·g',
      ar: 'w ← w − η·g',
      es: 'w ← w − η·g',
      fr: 'w ← w − η·g',
      hi: 'w ← w − η·g',
      id: 'w ← w − η·g',
      pt: 'w ← w − η·g',
    },
    'label.setting': {
      en: 'η = {eta} · w₀ = {start}',
      ko: 'η = {eta} · w₀ = {start}',
      ja: 'η = {eta} · w₀ = {start}',
      zh: 'η = {eta} · w₀ = {start}',
      ar: 'η = {eta} · w₀ = {start}',
      es: 'η = {eta} · w₀ = {start}',
      fr: 'η = {eta} · w₀ = {start}',
      hi: 'η = {eta} · w₀ = {start}',
      id: 'η = {eta} · w₀ = {start}',
      pt: 'η = {eta} · w₀ = {start}',
    },
    'label.axisW': { en: 'w', ko: 'w', ja: 'w', zh: 'w', ar: 'w', es: 'w', fr: 'w', hi: 'w', id: 'w', pt: 'w' },
    'label.axisL': { en: 'L', ko: 'L', ja: 'L', zh: 'L', ar: 'L', es: 'L', fr: 'L', hi: 'L', id: 'L', pt: 'L' },
    'label.startMark': {
      en: 'w₀',
      ko: 'w₀',
      ja: 'w₀',
      zh: 'w₀',
      ar: 'w₀',
      es: 'w₀',
      fr: 'w₀',
      hi: 'w₀',
      id: 'w₀',
      pt: 'w₀',
    },
    'label.edge': {
      en: 'w = {w}',
      ko: 'w = {w}',
      ja: 'w = {w}',
      zh: 'w = {w}',
      ar: 'w = {w}',
      es: 'w = {w}',
      fr: 'w = {w}',
      hi: 'w = {w}',
      id: 'w = {w}',
      pt: 'w = {w}',
    },
    'label.bottomAt': {
      en: 'w {w} · L {L}',
      ko: 'w {w} · L {L}',
      ja: 'w {w} · L {L}',
      zh: 'w {w} · L {L}',
      ar: 'w {w} · L {L}',
      es: 'w {w} · L {L}',
      fr: 'w {w} · L {L}',
      hi: 'w {w} · L {L}',
      id: 'w {w} · L {L}',
      pt: 'w {w} · L {L}',
    },
    'label.hump': {
      en: 'hump · w {w}',
      ko: '언덕 · w {w}',
      ja: '丘 · w {w}',
      zh: '山丘 · w {w}',
      ar: 'التل · w {w}',
      es: 'loma · w {w}',
      fr: 'bosse · w {w}',
      hi: 'टीला · w {w}',
      id: 'bukit · w {w}',
      pt: 'lomba · w {w}',
    },
    'label.deep': {
      en: 'deep valley',
      ko: '깊은 바닥',
      ja: '深い谷',
      zh: '深谷',
      ar: 'الوادي العميق',
      es: 'valle profundo',
      fr: 'vallée profonde',
      hi: 'गहरी घाटी',
      id: 'lembah dalam',
      pt: 'vale profundo',
    },
    'label.shallow': {
      en: 'shallow valley',
      ko: '얕은 바닥',
      ja: '浅い谷',
      zh: '浅谷',
      ar: 'الوادي الضحل',
      es: 'valle poco profundo',
      fr: 'vallée peu profonde',
      hi: 'उथली घाटी',
      id: 'lembah dangkal',
      pt: 'vale raso',
    },
    'label.stoodHere': {
      en: 'stood here',
      ko: '여기 섰다',
      ja: 'ここに止まった',
      zh: '停在这里',
      ar: 'استقر هنا',
      es: 'se detuvo aquí',
      fr: 's’est arrêtée ici',
      hi: 'यहाँ रुका',
      id: 'berhenti di sini',
      pt: 'parou aqui',
    },
    'label.swings': {
      en: 'swings back and forth',
      ko: '두 자리를 오간다',
      ja: '二つの位置を行き来する',
      zh: '在两个位置之间来回',
      ar: 'يتأرجح ذهابًا وإيابًا',
      es: 'va y viene',
      fr: 'va et vient',
      hi: 'आगे-पीछे झूलता है',
      id: 'bolak-balik',
      pt: 'vai e volta',
    },
    'readout.inside': {
      en: 'w {w}   L {L}',
      ko: 'w {w}   L {L}',
      ja: 'w {w}   L {L}',
      zh: 'w {w}   L {L}',
      ar: 'w {w}   L {L}',
      es: 'w {w}   L {L}',
      fr: 'w {w}   L {L}',
      hi: 'w {w}   L {L}',
      id: 'w {w}   L {L}',
      pt: 'w {w}   L {L}',
    },
    'readout.outside': {
      en: 'w {w}   (off the window)',
      ko: 'w {w}   (창 밖)',
      ja: 'w {w}   (枠の外)',
      zh: 'w {w}   (窗口之外)',
      ar: 'w {w}   (خارج النافذة)',
      es: 'w {w}   (fuera de la ventana)',
      fr: 'w {w}   (hors de la fenêtre)',
      hi: 'w {w}   (खिड़की से बाहर)',
      id: 'w {w}   (di luar jendela)',
      pt: 'w {w}   (fora da janela)',
    },
    'caption.start': {
      en: 'Start · slope g = {g}',
      ko: '출발 · 기울기 g = {g}',
      ja: '出発 · 傾き g = {g}',
      zh: '出发 · 斜率 g = {g}',
      ar: 'البداية · الميل g = {g}',
      es: 'Inicio · pendiente g = {g}',
      fr: 'Départ · pente g = {g}',
      hi: 'शुरुआत · ढलान g = {g}',
      id: 'Awal · kemiringan g = {g}',
      pt: 'Início · inclinação g = {g}',
    },
    'caption.update': {
      en: 'Update {t} · slope g = {g} · new w = {w}',
      ko: '갱신 {t} · 기울기 g = {g} · 새 자리 w = {w}',
      ja: '更新 {t} · 傾き g = {g} · 新しい位置 w = {w}',
      zh: '更新 {t} · 斜率 g = {g} · 新位置 w = {w}',
      ar: 'التحديث {t} · الميل g = {g} · الموضع الجديد w = {w}',
      es: 'Actualización {t} · pendiente g = {g} · nuevo w = {w}',
      fr: 'Mise à jour {t} · pente g = {g} · nouveau w = {w}',
      hi: 'अद्यतन {t} · ढलान g = {g} · नया w = {w}',
      id: 'Pembaruan {t} · kemiringan g = {g} · w baru = {w}',
      pt: 'Atualização {t} · inclinação g = {g} · novo w = {w}',
    },
    'caption.crossed': {
      en: 'This jump went over the hump.',
      ko: '이 뜀은 언덕을 넘었다.',
      ja: 'この跳躍は丘を越えた。',
      zh: '这一跳越过了山丘。',
      ar: 'هذه القفزة عبرت التل.',
      es: 'Este salto pasó por encima de la loma.',
      fr: 'Ce saut a franchi la bosse.',
      hi: 'यह छलांग टीले के पार गई।',
      id: 'Lompatan ini melewati bukit.',
      pt: 'Este salto passou por cima da lomba.',
    },
    'caption.settleDeep': {
      en: 'Settled in the deep valley · |g| = {g} < {limit}',
      ko: '깊은 바닥에 섰다 · |g| = {g} < {limit}',
      ja: '深い谷に止まった · |g| = {g} < {limit}',
      zh: '停在深谷 · |g| = {g} < {limit}',
      ar: 'استقر في الوادي العميق · |g| = {g} < {limit}',
      es: 'Se asentó en el valle profundo · |g| = {g} < {limit}',
      fr: 'Arrêtée dans la vallée profonde · |g| = {g} < {limit}',
      hi: 'गहरी घाटी में रुका · |g| = {g} < {limit}',
      id: 'Berhenti di lembah dalam · |g| = {g} < {limit}',
      pt: 'Assentou no vale profundo · |g| = {g} < {limit}',
    },
    'caption.settleShallow': {
      en: 'Settled in the shallow valley · |g| = {g} < {limit}',
      ko: '얕은 바닥에 섰다 · |g| = {g} < {limit}',
      ja: '浅い谷に止まった · |g| = {g} < {limit}',
      zh: '停在浅谷 · |g| = {g} < {limit}',
      ar: 'استقر في الوادي الضحل · |g| = {g} < {limit}',
      es: 'Se asentó en el valle poco profundo · |g| = {g} < {limit}',
      fr: 'Arrêtée dans la vallée peu profonde · |g| = {g} < {limit}',
      hi: 'उथली घाटी में रुका · |g| = {g} < {limit}',
      id: 'Berhenti di lembah dangkal · |g| = {g} < {limit}',
      pt: 'Assentou no vale raso · |g| = {g} < {limit}',
    },
    'caption.settleCap': {
      en: 'No stop within {n} updates · swings {a} ↔ {b} · |g| = {g}',
      ko: '갱신 {n} 번 안에 멈추지 않는다 · {a} ↔ {b} 사이를 오간다 · |g| = {g}',
      ja: '{n} 回の更新のうちに止まらない · {a} ↔ {b} の間を行き来する · |g| = {g}',
      zh: '{n} 次更新内停不下来 · 在 {a} ↔ {b} 之间来回 · |g| = {g}',
      ar: 'لا يتوقف خلال {n} تحديثًا · يتأرجح {a} ↔ {b} · |g| = {g}',
      es: 'No se detiene en {n} actualizaciones · va y viene {a} ↔ {b} · |g| = {g}',
      fr: 'Pas d’arrêt en {n} mises à jour · va et vient {a} ↔ {b} · |g| = {g}',
      hi: '{n} अद्यतनों के भीतर नहीं रुकता · {a} ↔ {b} के बीच झूलता है · |g| = {g}',
      id: 'Tidak berhenti dalam {n} pembaruan · bolak-balik {a} ↔ {b} · |g| = {g}',
      pt: 'Não para em {n} atualizações · vai e volta {a} ↔ {b} · |g| = {g}',
    },
    'caption.settleBlowup': {
      en: 'Left the curve · w = {w}',
      ko: '곡선 밖으로 나갔다 · w = {w}',
      ja: '曲線の外へ出た · w = {w}',
      zh: '离开了曲线 · w = {w}',
      ar: 'خرج عن المنحنى · w = {w}',
      es: 'Salió de la curva · w = {w}',
      fr: 'Sortie de la courbe · w = {w}',
      hi: 'वक्र से बाहर चला गया · w = {w}',
      id: 'Keluar dari kurva · w = {w}',
      pt: 'Saiu da curva · w = {w}',
    },
  },
};
