/**
 * sgd — 확률적 경사 하강과 미니배치. 손잡이 하나(묶음 크기 B).
 * 1차 데이터(점 열여섯 · 두 에폭의 섞은 차례 · 사다리 · η · 처음 자리)만 initialData 에 둔다.
 * 갱신 수 · 비낌 · 거꾸로 간 갱신 · 손실은 algorithm 이 셈한다.
 */
import { CONTROL_SET } from '@ffacet/core/runtime';
import type { FacetJson } from '@ffacet/core/runtime';

export const sgdFacet: FacetJson = {
  id: 'facet:sgd',
  title: {
    en: 'Stochastic gradient descent: batch size',
    ko: '확률적 경사 하강: 묶음 크기',
    ja: '確率的勾配降下法: バッチサイズ',
    zh: '随机梯度下降: 批大小',
    ar: 'الانحدار التدرجي العشوائي: حجم الدفعة',
    es: 'Descenso de gradiente estocástico: tamaño de lote',
    fr: 'Descente de gradient stochastique : taille de lot',
    hi: 'स्टोकेस्टिक ग्रेडिएंट डिसेंट: बैच आकार',
    id: 'Penurunan gradien stokastik: ukuran batch',
    pt: 'Descida de gradiente estocástica: tamanho do lote',
  },
  description: {
    en: 'Two epochs over the same sixteen points in the same shuffled order. Shrink the batch and the weights move more often in one pass — 32 updates at batch 1, 2 at batch 16 — and on average the moves skew further from the full downhill direction: mean skew 65° at batch 1, 39° at batch 2, 0° at batch 16.',
    ko: '같은 점 열여섯을 같은 섞은 차례로 두 에폭 본다. 묶음을 줄이면 한 바퀴에 무게가 더 자주 움직이고 — 묶음 1 에서 갱신 32 번, 묶음 16 에서 2 번 — 갱신이 전체 내리막 방향에서 평균으로 더 비낀다: 평균 비낌이 묶음 1 에서 65°, 묶음 2 에서 39°, 묶음 16 에서 0°.',
    ja: '同じ16個の点を同じシャッフル順で2エポック見る。バッチを小さくすると1周の間に重みがより頻繁に動き（バッチ1で更新32回、バッチ16で2回）、動きが全体の下り方向から平均してより大きくずれる: 平均のずれはバッチ1で65°、バッチ2で39°、バッチ16で0°。',
    zh: '以同一打乱顺序把同样的十六个点看两个轮次。批越小，一轮里权重移动得越频繁（批 1 更新 32 次，批 16 更新 2 次），移动平均偏离整体下坡方向也越多: 平均偏角在批 1 为 65°，批 2 为 39°，批 16 为 0°。',
    ar: 'حقبتان على النقاط الست عشرة نفسها بالترتيب المخلوط نفسه. صغّر الدفعة فتتحرك الأوزان أكثر في الدورة الواحدة — 32 تحديثًا عند الدفعة 1 و2 عند الدفعة 16 — وتنحرف الحركات في المتوسط أكثر عن اتجاه الانحدار الكلي: متوسط الانحراف 65° عند الدفعة 1 و39° عند الدفعة 2 و0° عند الدفعة 16.',
    es: 'Dos épocas sobre los mismos dieciséis puntos en el mismo orden barajado. Reduce el lote y los pesos se mueven más veces en una pasada — 32 actualizaciones con lote 1, 2 con lote 16 — y en promedio los pasos se desvían más de la dirección de bajada total: desvío medio 65° con lote 1, 39° con lote 2, 0° con lote 16.',
    fr: 'Deux époques sur les mêmes seize points dans le même ordre mélangé. Réduisez le lot et les poids bougent plus souvent en un passage — 32 mises à jour au lot 1, 2 au lot 16 — et en moyenne les mouvements dévient davantage de la pente totale : déviation moyenne 65° au lot 1, 39° au lot 2, 0° au lot 16.',
    hi: 'वही सोलह बिंदु, वही फेंटा हुआ क्रम, दो एपॉक। बैच छोटा करें तो एक चक्कर में वज़न ज़्यादा बार हिलते हैं — बैच 1 पर 32 अपडेट, बैच 16 पर 2 — और चालें औसतन पूरी ढलान की दिशा से ज़्यादा भटकती हैं: औसत भटकाव बैच 1 पर 65°, बैच 2 पर 39°, बैच 16 पर 0°।',
    id: 'Dua epoch atas enam belas titik yang sama dengan urutan acak yang sama. Perkecil batch dan bobot bergerak lebih sering dalam satu putaran — 32 pembaruan pada batch 1, 2 pada batch 16 — dan rata-rata gerakan makin menyimpang dari arah turunan penuh: simpangan rata-rata 65° pada batch 1, 39° pada batch 2, 0° pada batch 16.',
    pt: 'Duas épocas sobre os mesmos dezesseis pontos na mesma ordem embaralhada. Diminua o lote e os pesos se movem mais vezes numa passagem — 32 atualizações com lote 1, 2 com lote 16 — e em média os passos se desviam mais da direção de descida total: desvio médio 65° com lote 1, 39° com lote 2, 0° com lote 16.',
  },
  algorithm: 'module:sgd',
  projector: 'module:sgdProjector',
  initialData: {
    type: 'sgd',
    stepMs: 420,
    xs: [-2.0, -1.75, -1.5, -1.25, -1.0, -0.75, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
    ys: [-2.1, -2.8, -1.6, -0.5, -1.3, -1.3, 0.4, 0.2, 0.0, 1.6, 1.1, 1.9, 1.1, 2.9, 2.8, 2.7],
    order: [
      10, 5, 0, 1, 9, 4, 6, 2, 3, 15, 11, 7, 12, 8, 13, 14,
      1, 7, 14, 11, 12, 3, 9, 0, 6, 2, 5, 13, 8, 10, 4, 15,
    ],
    batchLadder: [1, 2, 4, 8, 16],
    batch: 2,
    eta: 0.05,
    w0: 0,
    b0: 0,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'sgd-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'batch',
          name: 'batch',
          label: {
            en: 'Batch size',
            ko: '묶음 크기',
            ja: 'バッチサイズ',
            zh: '批大小',
            ar: 'حجم الدفعة',
            es: 'Tamaño de lote',
            fr: 'Taille de lot',
            hi: 'बैच आकार',
            id: 'Ukuran batch',
            pt: 'Tamanho do lote',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2', default: true },
            { value: 4, label: '4' },
            { value: 8, label: '8' },
            { value: 16, label: '16' },
          ],
        },
      ],
      metrics: [
        {
          name: 'updates',
          label: {
            en: 'Updates',
            ko: '갱신 수',
            ja: '更新回数',
            zh: '更新次数',
            ar: 'التحديثات',
            es: 'Actualizaciones',
            fr: 'Mises à jour',
            hi: 'अपडेट',
            id: 'Pembaruan',
            pt: 'Atualizações',
          },
          initial: 0,
        },
        {
          name: 'backward-updates',
          label: {
            en: 'Against downhill',
            ko: '거꾸로 간 갱신',
            ja: '逆向きの更新',
            zh: '逆向更新',
            ar: 'عكس الانحدار',
            es: 'Contra la bajada',
            fr: 'À contre-pente',
            hi: 'उल्टी दिशा वाले',
            id: 'Melawan turunan',
            pt: 'Contra a descida',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:sgd-imperative',
      label: {
        en: 'Mini-batch updates over two epochs',
        ko: '두 에폭의 미니배치 갱신',
        ja: '2エポックのミニバッチ更新',
        zh: '两个轮次的小批量更新',
        ar: 'تحديثات الدفعات الصغيرة عبر حقبتين',
        es: 'Actualizaciones por minilote en dos épocas',
        fr: 'Mises à jour par mini-lot sur deux époques',
        hi: 'दो एपॉक में मिनी-बैच अपडेट',
        id: 'Pembaruan mini-batch selama dua epoch',
        pt: 'Atualizações por minilote em duas épocas',
      },
    },
  },
  messages: {
    'legend.needle': {
      en: 'Needle: up = full downhill direction · below the dashed line = against it (past 90°)',
      ko: '바늘: 위 = 전체 내리막 방향 · 점선 아래 = 거꾸로 간 갱신 (90° 넘음)',
      ja: '針: 上 = 全体の下り方向 · 点線より下 = 逆向きの更新 (90° 超え)',
      zh: '指针: 向上 = 整体下坡方向 · 虚线以下 = 逆向更新 (超过 90°)',
      ar: 'الإبرة: للأعلى = اتجاه الانحدار الكلي · تحت الخط المتقطع = عكسه (أكثر من 90°)',
      es: 'Aguja: arriba = dirección de bajada total · bajo la línea discontinua = en contra (más de 90°)',
      fr: 'Aiguille : haut = sens de la pente totale · sous le pointillé = à contre-pente (plus de 90°)',
      hi: 'सुई: ऊपर = पूरी ढलान की दिशा · डैश रेखा के नीचे = उल्टी दिशा (90° से ज़्यादा)',
      id: 'Jarum: atas = arah turunan penuh · di bawah garis putus = melawannya (lebih dari 90°)',
      pt: 'Agulha: cima = direção de descida total · abaixo da linha tracejada = contra ela (mais de 90°)',
    },
    'label.epoch': {
      en: 'Epoch {e}',
      ko: '에폭 {e}',
      ja: 'エポック {e}',
      zh: '轮次 {e}',
      ar: 'الحقبة {e}',
      es: 'Época {e}',
      fr: 'Époque {e}',
      hi: 'एपॉक {e}',
      id: 'Epoch {e}',
      pt: 'Época {e}',
    },
    'readout.state': {
      en: 'w = {w}, b = {b} · full loss {loss}',
      ko: 'w = {w}, b = {b} · 전체 손실 {loss}',
      ja: 'w = {w}, b = {b} · 全体の損失 {loss}',
      zh: 'w = {w}, b = {b} · 整体损失 {loss}',
      ar: 'w = {w}، b = {b} · الخسارة الكلية {loss}',
      es: 'w = {w}, b = {b} · pérdida total {loss}',
      fr: 'w = {w}, b = {b} · perte totale {loss}',
      hi: 'w = {w}, b = {b} · पूरा लॉस {loss}',
      id: 'w = {w}, b = {b} · loss penuh {loss}',
      pt: 'w = {w}, b = {b} · perda total {loss}',
    },
    'caption.start': {
      en: 'Batch size {B}: each epoch splits into {k} batches · {u} updates to come over {E} epochs',
      ko: '묶음 크기 {B}: 한 에폭이 묶음 {k} 개로 갈린다 · 에폭 {E} 바퀴 동안 할 갱신 {u} 번',
      ja: 'バッチサイズ {B}: 1エポックが {k} 個のバッチに分かれる · {E} エポックでこれから行う更新 {u} 回',
      zh: '批大小 {B}: 每轮分成 {k} 个批 · {E} 轮里将要进行的更新 {u} 次',
      ar: 'حجم الدفعة {B}: تنقسم كل حقبة إلى دفعات عددها {k} · التحديثات القادمة على {E} حقب: {u}',
      es: 'Tamaño de lote {B}: cada época se parte en {k} lotes · {u} actualizaciones por venir en {E} épocas',
      fr: 'Taille de lot {B} : chaque époque se découpe en {k} lots · {u} mises à jour à venir sur {E} époques',
      hi: 'बैच आकार {B}: हर एपॉक {k} बैचों में बँटता है · {E} एपॉक में आगे होने वाले {u} अपडेट',
      id: 'Ukuran batch {B}: tiap epoch terbagi menjadi {k} batch · {u} pembaruan yang akan datang dalam {E} epoch',
      pt: 'Tamanho do lote {B}: cada época se divide em {k} lotes · {u} atualizações por vir em {E} épocas',
    },
    'caption.epoch': {
      en: 'Epoch {e}: this epoch’s shuffled order lights up its strip',
      ko: '에폭 {e}: 이 에폭의 섞은 차례가 띠에 켜진다',
      ja: 'エポック {e}: このエポックのシャッフル順が帯に灯る',
      zh: '轮次 {e}: 本轮的打乱顺序在条带上亮起',
      ar: 'الحقبة {e}: يضيء ترتيب هذه الحقبة المخلوط على شريطها',
      es: 'Época {e}: el orden barajado de esta época se enciende en su franja',
      fr: 'Époque {e} : l’ordre mélangé de cette époque s’allume sur sa bande',
      hi: 'एपॉक {e}: इस एपॉक का फेंटा हुआ क्रम उसकी पट्टी पर जलता है',
      id: 'Epoch {e}: urutan acak epoch ini menyala di pitanya',
      pt: 'Época {e}: a ordem embaralhada desta época acende na sua faixa',
    },
    'caption.step': {
      en: 'Update {u} (epoch {e}, batch {k}): skew {deg}°',
      ko: '갱신 {u} (에폭 {e} · 묶음 {k}): 비낌 {deg}°',
      ja: '更新 {u} (エポック {e} · バッチ {k}): ずれ {deg}°',
      zh: '更新 {u} (轮次 {e} · 批 {k}): 偏角 {deg}°',
      ar: 'التحديث {u} (الحقبة {e}، الدفعة {k}): الانحراف {deg}°',
      es: 'Actualización {u} (época {e}, lote {k}): desvío {deg}°',
      fr: 'Mise à jour {u} (époque {e}, lot {k}) : déviation {deg}°',
      hi: 'अपडेट {u} (एपॉक {e}, बैच {k}): भटकाव {deg}°',
      id: 'Pembaruan {u} (epoch {e}, batch {k}): simpangan {deg}°',
      pt: 'Atualização {u} (época {e}, lote {k}): desvio {deg}°',
    },
    'caption.back': {
      en: 'Update {u} (epoch {e}, batch {k}): skew {deg}° — past 90°, against the full downhill',
      ko: '갱신 {u} (에폭 {e} · 묶음 {k}): 비낌 {deg}° — 90° 를 넘어 전체 내리막을 거슬렀다',
      ja: '更新 {u} (エポック {e} · バッチ {k}): ずれ {deg}° — 90° を超え、全体の下りに逆らった',
      zh: '更新 {u} (轮次 {e} · 批 {k}): 偏角 {deg}° — 超过 90°，逆着整体下坡',
      ar: 'التحديث {u} (الحقبة {e}، الدفعة {k}): الانحراف {deg}° — أكثر من 90°، عكس الانحدار الكلي',
      es: 'Actualización {u} (época {e}, lote {k}): desvío {deg}° — más de 90°, contra la bajada total',
      fr: 'Mise à jour {u} (époque {e}, lot {k}) : déviation {deg}° — plus de 90°, à contre-pente',
      hi: 'अपडेट {u} (एपॉक {e}, बैच {k}): भटकाव {deg}° — 90° से ज़्यादा, पूरी ढलान के उलट',
      id: 'Pembaruan {u} (epoch {e}, batch {k}): simpangan {deg}° — lebih dari 90°, melawan turunan penuh',
      pt: 'Atualização {u} (época {e}, lote {k}): desvio {deg}° — mais de 90°, contra a descida total',
    },
    'caption.end': {
      en: 'After {E} epochs: {u} updates · {back} against the downhill · mean |skew| {mean}°',
      ko: '에폭 {E} 바퀴 끝: 갱신 {u} 번 · 거꾸로 간 갱신 {back} 개 · 평균 |비낌| {mean}°',
      ja: '{E} エポック後: 更新 {u} 回 · 逆向き {back} 回 · 平均 |ずれ| {mean}°',
      zh: '{E} 轮之后: 更新 {u} 次 · 逆向 {back} 次 · 平均 |偏角| {mean}°',
      ar: 'بعد {E} حقب: التحديثات {u} · عكس الانحدار {back} · متوسط |الانحراف| {mean}°',
      es: 'Tras {E} épocas: {u} actualizaciones · {back} contra la bajada · |desvío| medio {mean}°',
      fr: 'Après {E} époques : {u} mises à jour · {back} à contre-pente · |déviation| moyenne {mean}°',
      hi: '{E} एपॉक के बाद: {u} अपडेट · {back} उल्टी दिशा में · औसत |भटकाव| {mean}°',
      id: 'Setelah {E} epoch: {u} pembaruan · {back} melawan turunan · |simpangan| rata-rata {mean}°',
      pt: 'Após {E} épocas: {u} atualizações · {back} contra a descida · |desvio| médio {mean}°',
    },
  },
};
