import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 같은 이름에 여러 번 넣는 코드를 SSA 로 바꾸면 이름은 어떻게 되는가.
 *
 * @notation native — 세 주소 코드 · SSA 는 컴파일러 내부 표기이고, 그 표기(판 번호가 붙은 이름) 자체가 주장이다.
 */
export const assignOnceFacet: FacetJson = {
  id: 'facet:assignOnce',
  title: {
    en: 'Assign once',
    ko: '한 번만 넣는다',
    ja: '一度だけ代入する',
    zh: '只赋值一次',
    ar: 'إسناد مرة واحدة',
    es: 'Asignar una sola vez',
    fr: 'Affecter une seule fois',
    hi: 'केवल एक बार असाइन',
    id: 'Ditugaskan sekali saja',
    pt: 'Atribuir uma só vez',
  },
  description: {
    en: 'Rewriting straight-line code into SSA: each new assignment to a name makes a fresh version, and each read points to the version alive at that line.',
    ko: '곧은 줄 코드를 SSA 로 바꾼다. 한 이름에 다시 넣을 때마다 새 판이 생기고, 읽는 자리는 그 줄에서 살아 있는 판을 가리킨다.',
    ja: '一直線のコードを SSA に書き換える。名前に代入し直すたびに新しい版が生まれ、読む場所はその行で生きている版を指す。',
    zh: '把直线代码改写成 SSA：每次给一个名字重新赋值都会产生新版本，每处读取都指向该行仍然有效的版本。',
    ar: 'إعادة كتابة شيفرة مستقيمة بصيغة SSA: كل إسناد جديد لاسم يصنع نسخة جديدة، وكل قراءة تشير إلى النسخة الحيّة عند ذلك السطر.',
    es: 'Reescribir código lineal en SSA: cada nueva asignación a un nombre crea una versión nueva, y cada lectura apunta a la versión viva en esa línea.',
    fr: 'Réécrire du code en ligne droite en SSA : chaque nouvelle affectation d’un nom crée une nouvelle version, et chaque lecture désigne la version vivante à cette ligne.',
    hi: 'सीधी पंक्ति वाले कोड को SSA में बदलना: किसी नाम में हर नया असाइनमेंट नया संस्करण बनाता है, और हर पढ़ना उस पंक्ति पर जीवित संस्करण की ओर इशारा करता है।',
    id: 'Menulis ulang kode lurus ke SSA: setiap penugasan baru ke sebuah nama membuat versi baru, dan setiap pembacaan menunjuk versi yang hidup di baris itu.',
    pt: 'Reescrever código em linha reta em SSA: cada nova atribuição a um nome cria uma versão nova, e cada leitura aponta para a versão viva naquela linha.',
  },
  algorithm: 'module:assignOnce',
  scene: 'module:assignOnceScene',
  initialData: {
    type: 'assign-once',
    stepMs: 1600,
    code: [
      { label: null, k: 'copy', dst: 'x', src: { num: 4 } },
      { label: null, k: 'bin', dst: 'y', l: { var: 'x' }, op: '+', r: { num: 1 } },
      { label: null, k: 'bin', dst: 'x', l: { var: 'y' }, op: '*', r: { num: 2 } },
      { label: null, k: 'bin', dst: 'x', l: { var: 'x' }, op: '-', r: { var: 'y' } },
      { label: null, k: 'return', value: { var: 'x' } },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Assignments per name — {counts}',
      ko: '이름마다 넣는 횟수 — {counts}',
      ja: '名前ごとの代入回数 — {counts}',
      zh: '每个名字的赋值次数 — {counts}',
      ar: 'عدد الإسنادات لكل اسم — {counts}',
      es: 'Asignaciones por nombre — {counts}',
      fr: 'Affectations par nom — {counts}',
      hi: 'हर नाम के असाइनमेंट — {counts}',
      id: 'Penugasan per nama — {counts}',
      pt: 'Atribuições por nome — {counts}',
    },
    'caption.both': {
      en: 'Line {line} — reads: {reads} · new version: {dst}',
      ko: '줄 {line} — 읽기: {reads} · 새 판: {dst}',
      ja: '行 {line} — 読み: {reads} · 新しい版: {dst}',
      zh: '行 {line} — 读取: {reads} · 新版本: {dst}',
      ar: 'السطر {line} — يقرأ: {reads} · نسخة جديدة: {dst}',
      es: 'Línea {line} — lee: {reads} · versión nueva: {dst}',
      fr: 'Ligne {line} — lit : {reads} · nouvelle version : {dst}',
      hi: 'पंक्ति {line} — पढ़ता है: {reads} · नया संस्करण: {dst}',
      id: 'Baris {line} — membaca: {reads} · versi baru: {dst}',
      pt: 'Linha {line} — lê: {reads} · nova versão: {dst}',
    },
    'caption.def': {
      en: 'Line {line} — new version: {dst}',
      ko: '줄 {line} — 새 판: {dst}',
      ja: '行 {line} — 新しい版: {dst}',
      zh: '行 {line} — 新版本: {dst}',
      ar: 'السطر {line} — نسخة جديدة: {dst}',
      es: 'Línea {line} — versión nueva: {dst}',
      fr: 'Ligne {line} — nouvelle version : {dst}',
      hi: 'पंक्ति {line} — नया संस्करण: {dst}',
      id: 'Baris {line} — versi baru: {dst}',
      pt: 'Linha {line} — nova versão: {dst}',
    },
    'caption.read': {
      en: 'Line {line} — reads: {reads}',
      ko: '줄 {line} — 읽기: {reads}',
      ja: '行 {line} — 読み: {reads}',
      zh: '行 {line} — 读取: {reads}',
      ar: 'السطر {line} — يقرأ: {reads}',
      es: 'Línea {line} — lee: {reads}',
      fr: 'Ligne {line} — lit : {reads}',
      hi: 'पंक्ति {line} — पढ़ता है: {reads}',
      id: 'Baris {line} — membaca: {reads}',
      pt: 'Linha {line} — lê: {reads}',
    },
    'caption.none': {
      en: 'Line {line} — no name to version',
      ko: '줄 {line} — 판을 매길 이름 없음',
      ja: '行 {line} — 版を付ける名前なし',
      zh: '行 {line} — 没有要编版本的名字',
      ar: 'السطر {line} — لا اسم يحتاج نسخة',
      es: 'Línea {line} — ningún nombre que versionar',
      fr: 'Ligne {line} — aucun nom à versionner',
      hi: 'पंक्ति {line} — संस्करण देने को कोई नाम नहीं',
      id: 'Baris {line} — tidak ada nama untuk diberi versi',
      pt: 'Linha {line} — nenhum nome a versionar',
    },
    'caption.end': {
      en: 'Assignments per version — {counts}',
      ko: '판마다 넣는 횟수 — {counts}',
      ja: '版ごとの代入回数 — {counts}',
      zh: '每个版本的赋值次数 — {counts}',
      ar: 'عدد الإسنادات لكل نسخة — {counts}',
      es: 'Asignaciones por versión — {counts}',
      fr: 'Affectations par version — {counts}',
      hi: 'हर संस्करण के असाइनमेंट — {counts}',
      id: 'Penugasan per versi — {counts}',
      pt: 'Atribuições por versão — {counts}',
    },
    'label.name': {
      en: 'name',
      ko: '이름',
      ja: '名前',
      zh: '名字',
      ar: 'الاسم',
      es: 'nombre',
      fr: 'nom',
      hi: 'नाम',
      id: 'nama',
      pt: 'nome',
    },
    'label.versions': {
      en: 'versions',
      ko: '판',
      ja: '版',
      zh: '版本',
      ar: 'النسخ',
      es: 'versiones',
      fr: 'versions',
      hi: 'संस्करण',
      id: 'versi',
      pt: 'versões',
    },
  },
  blocks: {
    stage: { type: 'assign-once-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
