import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 몸 안에서 바깥과 같은 이름을 `let` 하면 바깥 변수는 어떻게 되는가.
 *
 * 안쪽 `let` 은 같은 이름의 새 자리를 바깥 자리 **앞에** 세운다. 이름 찾기는 처음 닿는
 * 자리에서 멈추므로 몸 안의 읽기 · 쓰기는 모두 안쪽 자리에 닿고, 바깥 자리는 가려진 채
 * 한 번도 닿지 않는다. 몸을 벗어나 안쪽 자리가 걷히면 같은 이름이 다시 바깥 자리에 닿는다.
 */
export const shadowingFacet: FacetJson = {
  id: 'facet:shadowing',
  title: {
    en: 'Shadowing: the inner name hides the outer one',
    ko: '섀도잉 — 안쪽 이름이 바깥 이름을 가린다',
    ja: 'シャドーイング — 内側の名前が外側の名前を隠す',
    zh: '遮蔽 — 内层的名字挡住外层的名字',
    ar: 'التظليل: الاسم الداخلي يحجب الاسم الخارجي',
    es: 'Sombreado: el nombre interior oculta al exterior',
    fr: 'Masquage : le nom intérieur cache le nom extérieur',
    hi: 'शैडोइंग — भीतरी नाम बाहरी नाम को ढक देता है',
    id: 'Shadowing: nama di dalam menutupi nama di luar',
    pt: 'Sombreamento: o nome interno esconde o externo',
  },
  description: {
    en: 'If a body uses let to declare the same name as an outer variable, what happens to the outer variable?',
    ko: '몸 안에서 바깥과 같은 이름을 let 하면 바깥 변수는 어떻게 되는가?',
    ja: 'ブロックの中で外側と同じ名前を let で宣言すると、外側の変数はどうなるか?',
    zh: '在代码块里用 let 声明与外层同名的变量,外层的变量会怎样?',
    ar: 'إذا استُخدم let داخل جسمٍ للتصريح باسمٍ مطابق لمتغير خارجي، فماذا يحدث للمتغير الخارجي؟',
    es: 'Si dentro de un cuerpo se usa let para declarar el mismo nombre que una variable exterior, ¿qué le pasa a la variable exterior?',
    fr: 'Si un corps utilise let pour déclarer le même nom qu’une variable extérieure, que devient la variable extérieure ?',
    hi: 'अगर किसी बॉडी के भीतर let से वही नाम घोषित किया जाए जो बाहरी वेरिएबल का है, तो बाहरी वेरिएबल का क्या होता है?',
    id: 'Jika di dalam sebuah badan let dipakai untuk mendeklarasikan nama yang sama dengan variabel luar, apa yang terjadi pada variabel luar?',
    pt: 'Se dentro de um corpo se usa let para declarar o mesmo nome de uma variável externa, o que acontece com a variável externa?',
  },
  algorithm: 'module:shadowing',
  scene: 'module:shadowingScene',
  initialData: {
    type: 'shadowing',
    stepMs: 1700,
    lines: [
      { indent: 0, text: 'let level = 1', stmt: { k: 'assign', to: 'level', value: { num: 1 }, declare: true } },
      { indent: 0, text: 'if level > 0', stmt: { k: 'if', cond: { op: '>', l: { var: 'level' }, r: { num: 0 } } } },
      { indent: 1, text: 'let level = 2', stmt: { k: 'assign', to: 'level', value: { num: 2 }, declare: true } },
      {
        indent: 1,
        text: 'level = level + 10',
        stmt: { k: 'assign', to: 'level', value: { op: '+', l: { var: 'level' }, r: { num: 10 } } },
      },
      { indent: 1, text: 'show level', stmt: { k: 'show', value: { var: 'level' } } },
      { indent: 0, text: 'show level', stmt: { k: 'show', value: { var: 'level' } } },
    ],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'shadowing-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'No line has run yet.',
      ko: '아직 아무 줄도 실행하지 않았다.',
      ja: 'まだどの行も実行していない。',
      zh: '还没有执行任何一行。',
      ar: 'لم يُنفَّذ أي سطر بعد.',
      es: 'Todavía no se ha ejecutado ninguna línea.',
      fr: 'Aucune ligne n’a encore été exécutée.',
      hi: 'अभी तक कोई पंक्ति नहीं चली।',
      id: 'Belum ada baris yang dijalankan.',
      pt: 'Nenhuma linha foi executada ainda.',
    },
    'caption.declare': {
      en: 'let sets up a new slot. Name {name}, value {value}.',
      ko: 'let 이 새 자리를 세운다. 이름 {name}, 값 {value}.',
      ja: 'let が新しい場所を立てる。名前 {name}、値 {value}。',
      zh: 'let 立起一个新位置。名字 {name},值 {value}。',
      ar: 'ينشئ let خانة جديدة. الاسم {name}، القيمة {value}.',
      es: 'let levanta un espacio nuevo. Nombre {name}, valor {value}.',
      fr: 'let installe un nouvel emplacement. Nom {name}, valeur {value}.',
      hi: 'let एक नई जगह खड़ी करता है। नाम {name}, मान {value}।',
      id: 'let mendirikan tempat baru. Nama {name}, nilai {value}.',
      pt: 'let ergue um novo espaço. Nome {name}, valor {value}.',
    },
    'caption.declareShadow': {
      en: 'let sets up a new slot with the same name in front of the outer one. Name {name}, value {value}. The outer slot is only hidden; it still holds {outer}.',
      ko: 'let 이 바깥 자리 앞에 같은 이름의 새 자리를 세운다. 이름 {name}, 값 {value}. 바깥 자리는 가려졌을 뿐, 값은 그대로 {outer}.',
      ja: 'let が外側の場所の前に、同じ名前の新しい場所を立てる。名前 {name}、値 {value}。外側の場所は隠れただけで、値は {outer} のまま。',
      zh: 'let 在外层位置前面立起一个同名的新位置。名字 {name},值 {value}。外层位置只是被挡住,值仍是 {outer}。',
      ar: 'ينشئ let خانة جديدة بالاسم نفسه أمام الخانة الخارجية. الاسم {name}، القيمة {value}. الخانة الخارجية محجوبة فقط، وما زالت تحمل {outer}.',
      es: 'let levanta un espacio nuevo con el mismo nombre delante del exterior. Nombre {name}, valor {value}. El espacio exterior solo queda oculto; sigue guardando {outer}.',
      fr: 'let installe un nouvel emplacement du même nom devant l’extérieur. Nom {name}, valeur {value}. L’emplacement extérieur est seulement caché ; il contient toujours {outer}.',
      hi: 'let बाहरी जगह के आगे उसी नाम की नई जगह खड़ी करता है। नाम {name}, मान {value}। बाहरी जगह बस ढकी है; उसमें अब भी {outer} है।',
      id: 'let mendirikan tempat baru bernama sama di depan tempat luar. Nama {name}, nilai {value}. Tempat luar hanya tertutup; isinya tetap {outer}.',
      pt: 'let ergue um novo espaço com o mesmo nome à frente do externo. Nome {name}, valor {value}. O espaço externo está apenas escondido; ainda guarda {outer}.',
    },
    'caption.test': {
      en: 'The lookup for {name} stops at the first slot it reaches: {value}. The condition is {result}.',
      ko: '이름 {name} 찾기는 처음 닿는 자리에서 멈춘다: 값 {value}. 조건은 {result}.',
      ja: '名前 {name} の探索は最初に届いた場所で止まる: 値 {value}。条件は {result}。',
      zh: '查找名字 {name} 时,在最先碰到的位置停下:值 {value}。条件为 {result}。',
      ar: 'البحث عن {name} يتوقف عند أول خانة يصل إليها: {value}. الشرط {result}.',
      es: 'La búsqueda de {name} se detiene en el primer espacio que alcanza: {value}. La condición es {result}.',
      fr: 'La recherche de {name} s’arrête au premier emplacement atteint : {value}. La condition vaut {result}.',
      hi: '{name} की खोज पहली मिली जगह पर रुकती है: {value}। शर्त {result} है।',
      id: 'Pencarian {name} berhenti di tempat pertama yang dicapainya: {value}. Kondisinya {result}.',
      pt: 'A busca por {name} para no primeiro espaço que alcança: {value}. A condição é {result}.',
    },
    'caption.testPlain': {
      en: 'The condition is {result}.',
      ko: '조건은 {result}.',
      ja: '条件は {result}。',
      zh: '条件为 {result}。',
      ar: 'الشرط {result}.',
      es: 'La condición es {result}.',
      fr: 'La condition vaut {result}.',
      hi: 'शर्त {result} है।',
      id: 'Kondisinya {result}.',
      pt: 'A condição é {result}.',
    },
    'caption.write': {
      en: 'The value in the {name} slot changes: {before} → {value}.',
      ko: '{name} 자리의 값이 바뀐다: {before} → {value}.',
      ja: '{name} の場所の値が変わる: {before} → {value}。',
      zh: '{name} 位置的值改变:{before} → {value}。',
      ar: 'تتغير القيمة في خانة {name}: {before} → {value}.',
      es: 'Cambia el valor del espacio {name}: {before} → {value}.',
      fr: 'La valeur de l’emplacement {name} change : {before} → {value}.',
      hi: '{name} जगह का मान बदलता है: {before} → {value}।',
      id: 'Nilai di tempat {name} berubah: {before} → {value}.',
      pt: 'O valor do espaço {name} muda: {before} → {value}.',
    },
    'caption.writeShadow': {
      en: 'Both the read and the write stop at the slot in front: {before} → {value}. The outer slot behind still holds {outer}.',
      ko: '읽기도 쓰기도 앞에 선 자리에서 멈춘다: {before} → {value}. 뒤의 바깥 자리는 그대로 {outer}.',
      ja: '読み取りも書き込みも前に立つ場所で止まる: {before} → {value}。後ろの外側の場所は {outer} のまま。',
      zh: '读和写都停在前面的位置:{before} → {value}。后面的外层位置仍是 {outer}。',
      ar: 'القراءة والكتابة كلتاهما تتوقفان عند الخانة الأمامية: {before} → {value}. الخانة الخارجية خلفها ما زالت تحمل {outer}.',
      es: 'La lectura y la escritura se detienen en el espacio de delante: {before} → {value}. El espacio exterior de atrás sigue guardando {outer}.',
      fr: 'La lecture comme l’écriture s’arrêtent à l’emplacement de devant : {before} → {value}. L’emplacement extérieur derrière contient toujours {outer}.',
      hi: 'पढ़ना और लिखना दोनों आगे वाली जगह पर रुकते हैं: {before} → {value}। पीछे की बाहरी जगह में अब भी {outer} है।',
      id: 'Baca dan tulis sama-sama berhenti di tempat depan: {before} → {value}. Tempat luar di belakang tetap berisi {outer}.',
      pt: 'A leitura e a escrita param no espaço da frente: {before} → {value}. O espaço externo atrás ainda guarda {outer}.',
    },
    'caption.show': {
      en: 'show also reads from the first slot it reaches. Output {value}.',
      ko: 'show 도 처음 닿는 자리에서 읽는다. 출력 {value}.',
      ja: 'show も最初に届いた場所から読む。出力 {value}。',
      zh: 'show 也从最先碰到的位置读取。输出 {value}。',
      ar: 'يقرأ show أيضًا من أول خانة يصل إليها. الناتج {value}.',
      es: 'show también lee del primer espacio que alcanza. Salida {value}.',
      fr: 'show lit lui aussi le premier emplacement atteint. Sortie {value}.',
      hi: 'show भी पहली मिली जगह से पढ़ता है। आउटपुट {value}।',
      id: 'show juga membaca dari tempat pertama yang dicapainya. Keluaran {value}.',
      pt: 'show também lê do primeiro espaço que alcança. Saída {value}.',
    },
    'caption.showPlain': {
      en: 'Output {value}.',
      ko: '출력 {value}.',
      ja: '出力 {value}。',
      zh: '输出 {value}。',
      ar: 'الناتج {value}.',
      es: 'Salida {value}.',
      fr: 'Sortie {value}.',
      hi: 'आउटपुट {value}।',
      id: 'Keluaran {value}.',
      pt: 'Saída {value}.',
    },
    'caption.showReveal': {
      en: 'The body is over, so the inner slot is gone. The same name now reaches the outer slot. Output {value}.',
      ko: '몸이 끝나 안쪽 자리가 걷혔다. 같은 이름이 이제 바깥 자리에 닿는다. 출력 {value}.',
      ja: 'ブロックが終わり、内側の場所は片付けられた。同じ名前がいまは外側の場所に届く。出力 {value}。',
      zh: '代码块结束,内层位置被撤走。同一个名字现在碰到外层位置。输出 {value}。',
      ar: 'انتهى الجسم فأُزيلت الخانة الداخلية. الاسم نفسه يصل الآن إلى الخانة الخارجية. الناتج {value}.',
      es: 'El cuerpo terminó y el espacio interior se retiró. El mismo nombre ahora alcanza el espacio exterior. Salida {value}.',
      fr: 'Le corps est terminé, l’emplacement intérieur est retiré. Le même nom atteint maintenant l’emplacement extérieur. Sortie {value}.',
      hi: 'बॉडी खत्म हुई, इसलिए भीतरी जगह हट गई। वही नाम अब बाहरी जगह तक पहुँचता है। आउटपुट {value}।',
      id: 'Badan selesai, jadi tempat dalam dibongkar. Nama yang sama kini mencapai tempat luar. Keluaran {value}.',
      pt: 'O corpo acabou e o espaço interno foi retirado. O mesmo nome agora alcança o espaço externo. Saída {value}.',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'الناتج',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
    'label.outer': {
      en: 'outer',
      ko: '바깥',
      ja: '外側',
      zh: '外层',
      ar: 'خارجي',
      es: 'exterior',
      fr: 'extérieur',
      hi: 'बाहरी',
      id: 'luar',
      pt: 'externo',
    },
    'label.inner': {
      en: 'inner',
      ko: '안쪽',
      ja: '内側',
      zh: '内层',
      ar: 'داخلي',
      es: 'interior',
      fr: 'intérieur',
      hi: 'भीतरी',
      id: 'dalam',
      pt: 'interno',
    },
    'label.hidden': {
      en: 'hidden',
      ko: '가려짐',
      ja: '隠れている',
      zh: '被挡住',
      ar: 'محجوب',
      es: 'oculto',
      fr: 'caché',
      hi: 'ढका हुआ',
      id: 'tertutup',
      pt: 'escondido',
    },
  },
};
