/**
 * 힙 정렬 완결형 선언.
 *
 * 블록은 셋뿐이다 — `stage` · `controls` · `codePanel`. 제목 블록을 두지 않는다
 * (이름은 카탈로그 카드와 글의 문단이 준다). 미리보기 · 스냅샷 · 패스 표시는
 * 빌트인 view 를 빌리지 않고 stage 가 직접 그린다.
 *
 * 이 facet 의 산출물은 그림이 아니라 **코드** 다. `ir:heapsort-inplace` 하나가
 * 여섯 언어로 펼쳐지고, 재생 중인 phase 가 그 줄을 짚는다.
 *
 * 식별자 (C1): `index:<i>`.
 */

import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const heapSortFacet: FacetJson = {
  id: 'facet:heapSort',
  // 제목은 카탈로그 카드의 이름과 같다 (C4 명명 규칙 5).
  title: {
    en: 'Heap Sort',
    ko: '힙 정렬',
    ar: 'الترتيب بالكومة',
    es: 'Ordenamiento por montículo',
    fr: 'Tri par tas',
    hi: 'हीप सॉर्ट',
    id: 'Pengurutan heap',
    pt: 'Ordenação por heap',
  },
  description: {
    en: 'Make the row a max heap, then keep moving the top to the back — no spare array needed.',
    ko: '배열을 최대 힙으로 만든 뒤 꼭대기를 뒤로 옮기기를 되풀이한다 — 자리를 빌리지 않는다',
    ar: 'حوّل الصف إلى كومة عظمى ثم انقل القمة إلى المؤخرة مرارًا — دون مصفوفة إضافية.',
    es: 'Convierte la fila en un montículo máximo y lleva la cima al final una y otra vez, sin arreglo extra.',
    fr: "Transformez la rangée en tas max, puis déplacez le sommet vers la fin — sans tableau supplémentaire.",
    hi: 'पंक्ति को अधिकतम हीप बनाएँ, फिर शिखर को बार-बार पीछे भेजें — कोई अतिरिक्त सरणी नहीं।',
    id: 'Jadikan baris itu heap maksimum, lalu pindahkan puncaknya ke belakang berulang kali — tanpa larik cadangan.',
    pt: 'Transforme a fila num heap máximo e leve o topo para o fim repetidamente — sem arranjo extra.',
  },
  algorithm: 'module:heapSort',
  projector: 'module:heapSortProjector',
  // 사양이 정한 자료. 섞으면 힙 만들기가 이 배치에서 만드는 [90,25,64,…] 가
  // 사라지고 글의 대조표와 어긋난다.
  initialData: { type: 'array', values: [64, 25, 12, 22, 11, 90, 34] },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    stage: { type: 'heap-sort-stage' },
    controls: {
      type: 'control-bar',
      controls: CONTROL_SET.playback,
      metrics: [
        {
          name: 'compare-count',
          label: {
            en: 'Compare',
            ko: '견줌',
            ar: 'مقارنة',
            es: 'Comparar',
            fr: 'Comparer',
            hi: 'तुलना',
            id: 'Banding',
            pt: 'Comparar',
          },
          initial: 0,
        },
        {
          name: 'swap-count',
          label: {
            en: 'Swap',
            ko: '맞바꿈',
            ar: 'تبديل',
            es: 'Intercambio',
            fr: 'Échange',
            hi: 'अदला-बदली',
            id: 'Tukar',
            pt: 'Troca',
          },
          initial: 0,
        },
        {
          name: 'sorted-count',
          label: {
            en: 'Settled',
            ko: '확정된 칸',
            ar: 'مستقرة',
            es: 'Fijadas',
            fr: 'Fixées',
            hi: 'तय',
            id: 'Tetap',
            pt: 'Fixadas',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      label: {
        en: 'Code',
        ko: '코드',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
      ir: 'ir:heapsort-inplace',
    },
  },
  messages: {
    'label.heap': {
      en: 'Heap',
      ko: '힙',
      ar: 'الكومة',
      es: 'Montículo',
      fr: 'Tas',
      hi: 'हीप',
      id: 'Heap',
      pt: 'Heap',
    },
    'label.sorted': {
      en: 'Sorted',
      ko: '정렬 끝',
      ar: 'مرتّب',
      es: 'Ordenado',
      fr: 'Trié',
      hi: 'क्रमित',
      id: 'Terurut',
      pt: 'Ordenado',
    },
    'caption.start': {
      en: 'One row is already a tree — the children of seat i are 2i+1 and 2i+2.',
      ko: '이 한 줄이 이미 트리다 — 자리 i 의 자식은 2i+1 과 2i+2',
      ar: 'هذا الصف شجرة بالفعل — أبناء الموضع i هما 2i+1 و 2i+2.',
      es: 'Esta fila ya es un árbol: los hijos del puesto i son 2i+1 y 2i+2.',
      fr: "Cette rangée est déjà un arbre — les enfants de la place i sont 2i+1 et 2i+2.",
      hi: 'यह एक पंक्ति पहले से ही एक वृक्ष है — स्थान i के बच्चे 2i+1 और 2i+2 हैं।',
      id: 'Satu baris ini sudah berupa pohon — anak dari kursi i adalah 2i+1 dan 2i+2.',
      pt: 'Esta fila já é uma árvore — os filhos do lugar i são 2i+1 e 2i+2.',
    },
    'caption.buildBegin': {
      en: 'Start at seat {index}, the last seat that has children.',
      ko: '자식을 가진 마지막 자리 {index} 번부터 시작한다',
      ar: 'ابدأ من الموضع {index}، آخر موضع له أبناء.',
      es: 'Empieza en el puesto {index}, el último que tiene hijos.',
      fr: 'Commencer à la place {index}, la dernière qui a des enfants.',
      hi: 'स्थान {index} से शुरू करें — बच्चों वाला अंतिम स्थान।',
      id: 'Mulai dari kursi {index}, kursi terakhir yang punya anak.',
      pt: 'Comece no lugar {index}, o último que tem filhos.',
    },
    'caption.siftBuild': {
      en: 'Sink the value at seat {index} as far as it must go.',
      ko: '{index} 번 자리의 값을 내려갈 만큼 내린다',
      ar: 'أنزل قيمة الموضع {index} إلى حيث يجب أن تستقر.',
      es: 'Hunde el valor del puesto {index} tan abajo como haga falta.',
      fr: "Faire descendre la valeur de la place {index} aussi bas qu'il le faut.",
      hi: 'स्थान {index} के मान को जितना नीचे जाना है उतना उतारें।',
      id: 'Turunkan nilai di kursi {index} sejauh yang diperlukan.',
      pt: 'Afunde o valor do lugar {index} até onde for preciso.',
    },
    'caption.siftRoot': {
      en: 'Sink the new top back down through the smaller heap.',
      ko: '새 꼭대기를 줄어든 힙 안에서 다시 내린다',
      ar: 'أنزل القمة الجديدة من جديد داخل الكومة الأصغر.',
      es: 'Vuelve a hundir la nueva cima dentro del montículo ya más pequeño.',
      fr: 'Faire redescendre le nouveau sommet dans le tas devenu plus petit.',
      hi: 'नए शिखर को छोटी हुई हीप में फिर से नीचे उतारें।',
      id: 'Turunkan kembali puncak baru di dalam heap yang sudah mengecil.',
      pt: 'Afunde de novo o novo topo dentro do heap já menor.',
    },
    'caption.compareChildren': {
      en: 'Two children {left} and {right} — {big} is bigger.',
      ko: '두 자식 {left} 와 {right} 중 큰 쪽은 {big}',
      ar: 'الابنان {left} و {right} — الأكبر هو {big}.',
      es: 'Dos hijos, {left} y {right}: el mayor es {big}.',
      fr: 'Deux enfants {left} et {right} — le plus grand est {big}.',
      hi: 'दो बच्चे {left} और {right} — बड़ा {big} है।',
      id: 'Dua anak {left} dan {right} — yang lebih besar adalah {big}.',
      pt: 'Dois filhos {left} e {right} — o maior é {big}.',
    },
    'caption.compareParent': {
      en: 'Is the parent {parent} already at least {child}?',
      ko: '부모 {parent} 가 이미 {child} 만 한가',
      ar: 'هل الأب {parent} أكبر من {child} أو يساويه؟',
      es: '¿El padre {parent} ya es al menos {child}?',
      fr: 'Le parent {parent} vaut-il déjà au moins {child} ?',
      hi: 'क्या माता-पिता {parent} पहले से ही कम-से-कम {child} है?',
      id: 'Apakah induk {parent} sudah setidaknya sebesar {child}?',
      pt: 'O pai {parent} já é pelo menos {child}?',
    },
    'caption.moveDown': {
      en: '{parent} is the smaller one — it sinks past {child}.',
      ko: '{parent} 가 더 작다 — {child} 와 자리를 바꿔 내려간다',
      ar: '{parent} هو الأصغر — ينزل مبادلًا مكانه مع {child}.',
      es: '{parent} es el menor: baja intercambiándose con {child}.',
      fr: '{parent} est le plus petit — il descend en échangeant avec {child}.',
      hi: '{parent} छोटा है — यह {child} से जगह बदलकर नीचे उतरता है।',
      id: '{parent} lebih kecil — ia turun bertukar tempat dengan {child}.',
      pt: '{parent} é o menor — desce trocando de lugar com {child}.',
    },
    'caption.settleDown': {
      en: '{value} has nowhere lower to go — it rests here.',
      ko: '{value} 는 더 내려갈 곳이 없다 — 여기서 멈춘다',
      ar: 'لا مكان أدنى لـ {value} — يستقر هنا.',
      es: '{value} no puede bajar más: se queda aquí.',
      fr: "{value} ne peut pas descendre plus bas — il s'arrête ici.",
      hi: '{value} और नीचे नहीं जा सकता — यहीं ठहरता है।',
      id: '{value} tidak bisa turun lagi — ia berhenti di sini.',
      pt: '{value} não pode descer mais — para aqui.',
    },
    'caption.buildEnd': {
      en: 'It is a max heap now — the top {top} is the largest value.',
      ko: '최대 힙이 됐다 — 꼭대기 {top} 이 가장 큰 값이다',
      ar: 'صارت كومة عظمى — القمة {top} هي أكبر قيمة.',
      es: 'Ya es un montículo máximo: la cima {top} es el mayor valor.',
      fr: "C'est maintenant un tas max — le sommet {top} est la plus grande valeur.",
      hi: 'अब यह अधिकतम हीप है — शिखर {top} सबसे बड़ा मान है।',
      id: 'Sekarang sudah heap maksimum — puncak {top} adalah nilai terbesar.',
      pt: 'Agora é um heap máximo — o topo {top} é o maior valor.',
    },
    'caption.swapTopEnd': {
      en: 'Swap the top {top} with the last cell {tail} of the heap.',
      ko: '꼭대기 {top} 과 힙의 마지막 칸 {tail} 을 맞바꾼다',
      ar: 'بدّل القمة {top} مع آخر خانة في الكومة {tail}.',
      es: 'Intercambia la cima {top} con la última casilla {tail} del montículo.',
      fr: 'Échanger le sommet {top} avec la dernière case {tail} du tas.',
      hi: 'शिखर {top} की हीप के अंतिम खाने {tail} से अदला-बदली करें।',
      id: 'Tukar puncak {top} dengan sel terakhir heap {tail}.',
      pt: 'Troque o topo {top} com a última casa {tail} do heap.',
    },
    'caption.settleSeat': {
      en: '{value} takes seat {index} and never moves again.',
      ko: '{value} 가 {index} 번 자리에 앉는다. 다시 움직이지 않는다',
      ar: '{value} يأخذ الموضع {index} ولا يتحرك بعدها أبدًا.',
      es: '{value} ocupa el puesto {index} y ya no vuelve a moverse.',
      fr: '{value} prend la place {index} et ne bougera plus.',
      hi: '{value} स्थान {index} पर बैठ जाता है और फिर कभी नहीं हिलता।',
      id: '{value} menempati kursi {index} dan tidak bergerak lagi.',
      pt: '{value} ocupa o lugar {index} e nunca mais se move.',
    },
    'caption.shrinkHeap': {
      en: 'The heap shrinks to {size} cells — that seat left the tree.',
      ko: '힙이 {size} 칸으로 줄었다 — 그 자리는 트리에서 빠졌다',
      ar: 'انكمشت الكومة إلى {size} خانات — خرج ذلك الموضع من الشجرة.',
      es: 'El montículo se reduce a {size} casillas: ese puesto salió del árbol.',
      fr: "Le tas se réduit à {size} cases — cette place est sortie de l'arbre.",
      hi: 'हीप घटकर {size} खाने रह गई — वह स्थान वृक्ष से बाहर हो गया।',
      id: 'Heap menyusut menjadi {size} sel — kursi itu keluar dari pohon.',
      pt: 'O heap encolhe para {size} casas — aquele lugar saiu da árvore.',
    },
    'caption.done': {
      en: 'Sorted with {compares} compares and {swaps} swaps.',
      ko: '견줌 {compares} 번 · 맞바꿈 {swaps} 번으로 정렬됐다',
      ar: 'تم الترتيب بـ {compares} مقارنة و {swaps} تبديلًا.',
      es: 'Ordenado con {compares} comparaciones y {swaps} intercambios.',
      fr: 'Trié avec {compares} comparaisons et {swaps} échanges.',
      hi: '{compares} तुलनाओं और {swaps} अदला-बदली के साथ क्रम में लग गया।',
      id: 'Terurut dengan {compares} perbandingan dan {swaps} pertukaran.',
      pt: 'Ordenado com {compares} comparações e {swaps} trocas.',
    },
  },
};
