import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const simdFacet: FacetJson = {
  id: 'facet:simd',
  title: {
    en: 'SIMD',
    ko: 'SIMD',
    ja: 'SIMD',
    zh: 'SIMD',
    ar: 'SIMD',
    es: 'SIMD',
    fr: 'SIMD',
    hi: 'SIMD',
    id: 'SIMD',
    pt: 'SIMD',
  },
  description: {
    en: 'One add pushes several lanes at once — but the leftover tail still crawls one element at a time.',
    ko: '덧셈 하나가 여러 차선을 한꺼번에 민다. 그러나 나누어떨어지지 않고 남은 꼬리는 하나씩 기어간다.',
    ja: '1 回の加算が複数のレーンをまとめて押し進める。だが割り切れずに残った端数は 1 つずつ進むしかない。',
    zh: '一次加法同时推进多个通道——但除不尽剩下的尾部仍要一个一个地加。',
    ar: 'عملية جمع واحدة تدفع عدة مسارات معًا — لكن الذيل المتبقي لا يزال يزحف عنصرًا عنصرًا.',
    es: 'Una suma empuja varios carriles a la vez, pero la cola sobrante sigue avanzando de uno en uno.',
    fr: 'Une addition pousse plusieurs voies à la fois — mais la queue restante avance encore un élément à la fois.',
    hi: 'एक जोड़ कई लेन को एक साथ आगे बढ़ाता है — पर बची हुई पूंछ अब भी एक-एक करके चलती है।',
    id: 'Satu penjumlahan mendorong beberapa jalur sekaligus — tetapi sisa ekornya tetap merayap satu per satu.',
    pt: 'Uma soma empurra várias faixas de uma vez — mas a cauda que sobra ainda avança um elemento por vez.',
  },
  algorithm: 'module:simd',
  projector: 'module:simdProjector',
  initialData: {
    type: 'simd',
    a: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    b: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180],
    laneLadder: [1, 2, 4, 8],
    stepMs: 500,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'simd-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback!,
        {
          widget: 'segmented-slider',
          action: 'lanes',
          name: 'lanes',
          label: {
            en: 'Lanes',
            ko: '차선 수',
            ja: 'レーン数',
            zh: '通道数',
            ar: 'عدد المسارات',
            es: 'Carriles',
            fr: 'Voies',
            hi: 'लेन',
            id: 'Jalur',
            pt: 'Faixas',
          },
          segments: [
            { value: 1, label: '1', default: true },
            { value: 2, label: '2' },
            { value: 4, label: '4' },
            { value: 8, label: '8' },
          ],
        },
      ],
      metrics: [
        {
          name: 'add-op-count',
          label: {
            en: 'add instructions',
            ko: '덧셈 명령',
            ja: '加算命令',
            zh: '加法指令',
            ar: 'تعليمات الجمع',
            es: 'instrucciones de suma',
            fr: "instructions d'addition",
            hi: 'जोड़ निर्देश',
            id: 'instruksi tambah',
            pt: 'instruções de soma',
          },
          initial: 0,
        },
        {
          name: 'tail-op-count',
          label: {
            en: 'tail adds',
            ko: '꼬리 덧셈',
            ja: '端数の加算',
            zh: '尾部加法',
            ar: 'جمع الذيل',
            es: 'sumas de cola',
            fr: 'additions de queue',
            hi: 'पूंछ के जोड़',
            id: 'tambah ekor',
            pt: 'somas da cauda',
          },
          initial: 0,
        },
        {
          name: 'speedup-percent',
          label: {
            en: 'speedup %',
            ko: '빨라짐 %',
            ja: '高速化 %',
            zh: '加速 %',
            ar: 'التسريع %',
            es: 'aceleración %',
            fr: 'accélération %',
            hi: 'गति वृद्धि %',
            id: 'percepatan %',
            pt: 'aceleração %',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:simd-imperative',
      label: {
        en: 'Code',
        ko: '코드',
        ja: 'コード',
        zh: '代码',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
    },
  },
  messages: {
    'label.a': { en: 'a', ko: 'a', ja: 'a', zh: 'a', ar: 'a', es: 'a', fr: 'a', hi: 'a', id: 'a', pt: 'a' },
    'label.b': { en: 'b', ko: 'b', ja: 'b', zh: 'b', ar: 'b', es: 'b', fr: 'b', hi: 'b', id: 'b', pt: 'b' },
    'label.c': {
      en: 'c = a + b',
      ko: 'c = a + b',
      ja: 'c = a + b',
      zh: 'c = a + b',
      ar: 'c = a + b',
      es: 'c = a + b',
      fr: 'c = a + b',
      hi: 'c = a + b',
      id: 'c = a + b',
      pt: 'c = a + b',
    },
    'label.time': {
      en: 'adds',
      ko: '덧셈',
      ja: '加算',
      zh: '加法',
      ar: 'الجمع',
      es: 'sumas',
      fr: 'additions',
      hi: 'जोड़',
      id: 'tambah',
      pt: 'somas',
    },
    'label.scalar': {
      en: 'one lane: {n}',
      ko: '차선 하나: {n}',
      ja: '1 レーン: {n}',
      zh: '单通道: {n}',
      ar: 'مسار واحد: {n}',
      es: 'un carril: {n}',
      fr: 'une voie : {n}',
      hi: 'एक लेन: {n}',
      id: 'satu jalur: {n}',
      pt: 'uma faixa: {n}',
    },
    'caption.idle': {
      en: 'c = a + b over {n} elements',
      ko: '원소 {n}개에 c = a + b',
      ja: '{n} 個の要素に c = a + b',
      zh: '对 {n} 个元素计算 c = a + b',
      ar: 'c = a + b على {n} عنصرًا',
      es: 'c = a + b sobre {n} elementos',
      fr: 'c = a + b sur {n} éléments',
      hi: '{n} तत्वों पर c = a + b',
      id: 'c = a + b atas {n} elemen',
      pt: 'c = a + b sobre {n} elementos',
    },
    'caption.plan': {
      en: 'Lanes = {lanes}: {packs} packed adds, then {tail} tail adds',
      ko: '차선 {lanes}개: 묶음 덧셈 {packs}번, 이어서 꼬리 덧셈 {tail}번',
      ja: '{lanes} レーン: まとめた加算 {packs} 回、続いて端数の加算 {tail} 回',
      zh: '{lanes} 个通道: 打包加法 {packs} 次, 然后尾部加法 {tail} 次',
      ar: 'المسارات = {lanes}: {packs} عمليات جمع مجمّعة، ثم {tail} للذيل',
      es: 'Carriles = {lanes}: {packs} sumas empaquetadas y luego {tail} de cola',
      fr: 'Voies = {lanes} : {packs} additions groupées, puis {tail} de queue',
      hi: '{lanes} लेन: {packs} समूह जोड़, फिर पूंछ के {tail} जोड़',
      id: '{lanes} jalur: {packs} tambah berkelompok, lalu {tail} tambah ekor',
      pt: 'Faixas = {lanes}: {packs} somas agrupadas, depois {tail} da cauda',
    },
    'caption.pack': {
      en: 'One add fills c[{from}] … c[{to}] at once',
      ko: '덧셈 하나가 한꺼번에 채운다: c[{from}] … c[{to}]',
      ja: '1 回の加算で c[{from}] … c[{to}] をまとめて埋める',
      zh: '一次加法同时填满 c[{from}] … c[{to}]',
      ar: 'جمع واحد يملأ c[{from}] … c[{to}] دفعة واحدة',
      es: 'Una suma llena c[{from}] … c[{to}] de una vez',
      fr: 'Une addition remplit c[{from}] … c[{to}] d’un coup',
      hi: 'एक जोड़ c[{from}] … c[{to}] को एक साथ भरता है',
      id: 'Satu penjumlahan mengisi c[{from}] … c[{to}] sekaligus',
      pt: 'Uma soma preenche c[{from}] … c[{to}] de uma vez',
    },
    'caption.one': {
      en: 'One lane: one add fills c[{index}] alone',
      ko: '차선 하나: 덧셈 하나로 c[{index}] 하나만',
      ja: '1 レーン: 1 回の加算で c[{index}] ひとつだけ',
      zh: '单通道: 一次加法只填 c[{index}]',
      ar: 'مسار واحد: جمع واحد يملأ c[{index}] وحده',
      es: 'Un carril: una suma llena solo c[{index}]',
      fr: 'Une voie : une addition ne remplit que c[{index}]',
      hi: 'एक लेन: एक जोड़ केवल c[{index}] भरता है',
      id: 'Satu jalur: satu penjumlahan hanya mengisi c[{index}]',
      pt: 'Uma faixa: uma soma preenche só c[{index}]',
    },
    'caption.tail': {
      en: 'Tail: c[{index}] takes an add of its own',
      ko: '꼬리: c[{index}] 하나에 덧셈 하나',
      ja: '端数: c[{index}] ひとつに加算 1 回',
      zh: '尾部: c[{index}] 单独占用一次加法',
      ar: 'الذيل: c[{index}] يحتاج جمعًا خاصًا به',
      es: 'Cola: c[{index}] necesita una suma propia',
      fr: 'Queue : c[{index}] prend une addition à lui seul',
      hi: 'पूंछ: c[{index}] के लिए अलग एक जोड़',
      id: 'Ekor: c[{index}] butuh satu penjumlahan sendiri',
      pt: 'Cauda: c[{index}] precisa de uma soma só sua',
    },
    'caption.done': {
      en: '{ops} adds for {n} elements — {pct}% of one-lane speed',
      ko: '원소 {n}개에 덧셈 {ops}번 — 차선 하나의 {pct}% 빠르기',
      ja: '{n} 個の要素に加算 {ops} 回 — 1 レーンの {pct}% の速さ',
      zh: '{n} 个元素用 {ops} 次加法 — 单通道速度的 {pct}%',
      ar: '{ops} عمليات جمع لـ {n} عنصرًا — {pct}% من سرعة المسار الواحد',
      es: '{ops} sumas para {n} elementos: {pct}% de la velocidad de un carril',
      fr: '{ops} additions pour {n} éléments — {pct} % de la vitesse à une voie',
      hi: '{n} तत्वों के लिए {ops} जोड़ — एक लेन की गति का {pct}%',
      id: '{ops} penjumlahan untuk {n} elemen — {pct}% kecepatan satu jalur',
      pt: '{ops} somas para {n} elementos — {pct}% da velocidade de uma faixa',
    },
    'readout.ops': {
      en: '{ops} adds, {tail} in the tail',
      ko: '덧셈 {ops}번, 그중 꼬리 {tail}번',
      ja: '加算 {ops} 回、うち端数 {tail} 回',
      zh: '加法 {ops} 次, 其中尾部 {tail} 次',
      ar: '{ops} عمليات جمع، منها {tail} للذيل',
      es: '{ops} sumas, {tail} de cola',
      fr: '{ops} additions, dont {tail} de queue',
      hi: '{ops} जोड़, जिनमें {tail} पूंछ के',
      id: '{ops} penjumlahan, {tail} di ekor',
      pt: '{ops} somas, {tail} da cauda',
    },
  },
};
