import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: if-else 는 두 갈래를 다 밟는가.
 *
 * 흐름이 조건 줄에서 참인 갈래 쪽으로 꺾여 들어가 그 몸을 밟고, 다른 갈래는 한 줄도
 * 밟히지 않은 채 제자리에 남는다. 두 갈래 뒤의 줄에서 흐름은 다시 하나로 이어진다.
 */
export const branchTakeOnePathFacet: FacetJson = {
  id: 'facet:branchTakeOnePath',
  title: {
    en: 'At a fork, only one way',
    ko: '갈림길에서 한쪽만 간다',
    ja: '分かれ道では片方だけ進む',
    zh: '岔路口只走一边',
    ar: 'عند مفترق الطرق يُسلك طريق واحد فقط',
    es: 'En la bifurcación, solo un camino',
    fr: 'À la bifurcation, un seul chemin',
    hi: 'दोराहे पर सिर्फ़ एक रास्ता',
    id: 'Di persimpangan, hanya satu jalan',
    pt: 'Na bifurcação, só um caminho',
  },
  description: {
    en: 'Does if-else step through both branches?',
    ko: 'if-else 는 두 갈래를 다 밟는가?',
    ja: 'if-else は両方の枝を通るのか?',
    zh: 'if-else 会走过两个分支吗?',
    ar: 'هل تمرّ if-else بالفرعين كليهما؟',
    es: '¿Recorre if-else las dos ramas?',
    fr: 'Le if-else parcourt-il les deux branches ?',
    hi: 'क्या if-else दोनों शाखाओं से गुज़रता है?',
    id: 'Apakah if-else melewati kedua cabang?',
    pt: 'O if-else percorre os dois ramos?',
  },
  algorithm: 'module:branchTakeOnePath',
  scene: 'module:branchTakeOnePathScene',
  initialData: {
    type: 'branch-take-one-path',
    stepMs: 1600,
    lines: [
      {
        indent: 0,
        text: 'let temp = 31',
        stmt: { k: 'assign', to: 'temp', value: { num: 31 }, declare: true },
      },
      {
        indent: 0,
        text: 'let wear = ""',
        stmt: { k: 'assign', to: 'wear', value: { str: '' }, declare: true },
      },
      {
        indent: 0,
        text: 'let fan = "off"',
        stmt: { k: 'assign', to: 'fan', value: { str: 'off' }, declare: true },
      },
      {
        indent: 0,
        text: 'let heater = "off"',
        stmt: { k: 'assign', to: 'heater', value: { str: 'off' }, declare: true },
      },
      {
        indent: 0,
        text: 'if temp > 25',
        stmt: { k: 'if', cond: { op: '>', l: { var: 'temp' }, r: { num: 25 } } },
      },
      {
        indent: 1,
        text: 'wear = "shorts"',
        stmt: { k: 'assign', to: 'wear', value: { str: 'shorts' } },
      },
      { indent: 1, text: 'fan = "on"', stmt: { k: 'assign', to: 'fan', value: { str: 'on' } } },
      { indent: 0, text: 'else', stmt: { k: 'else' } },
      { indent: 1, text: 'wear = "coat"', stmt: { k: 'assign', to: 'wear', value: { str: 'coat' } } },
      {
        indent: 1,
        text: 'heater = "on"',
        stmt: { k: 'assign', to: 'heater', value: { str: 'on' } },
      },
      { indent: 0, text: 'show wear', stmt: { k: 'show', value: { var: 'wear' } } },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has run yet. The flow starts at the top.',
      ko: '아직 아무 줄도 밟지 않았다. 흐름은 맨 위에서 시작한다.',
      ja: 'まだどの行も実行していない。流れは一番上から始まる。',
      zh: '还没有执行任何一行。流程从最上面开始。',
      ar: 'لم يُنفَّذ أي سطر بعد. يبدأ التدفق من الأعلى.',
      es: 'Aún no se ha ejecutado nada. El flujo empieza arriba.',
      fr: "Rien n'a encore été exécuté. Le flux part du haut.",
      hi: 'अभी तक कोई पंक्ति नहीं चली। प्रवाह सबसे ऊपर से शुरू होता है।',
      id: 'Belum ada baris yang dijalankan. Alur mulai dari atas.',
      pt: 'Nada foi executado ainda. O fluxo começa no topo.',
    },
    'caption.cond': {
      en: 'The condition is {verdict}. The flow turns into that branch; the other branch stays where it is.',
      ko: '조건은 {verdict}. 흐름은 그쪽 갈래로 꺾이고, 다른 갈래는 제자리에 남는다.',
      ja: '条件は {verdict}。流れはその枝へ曲がり、もう一方の枝はそのまま残る。',
      zh: '条件为 {verdict}。流程拐进那一支,另一支原地留下。',
      ar: 'الشرط {verdict}. ينعطف التدفق إلى ذلك الفرع، ويبقى الفرع الآخر في مكانه.',
      es: 'La condición es {verdict}. El flujo gira hacia esa rama; la otra se queda donde está.',
      fr: "La condition vaut {verdict}. Le flux tourne dans cette branche ; l'autre reste en place.",
      hi: 'शर्त {verdict} है। प्रवाह उसी शाखा में मुड़ता है; दूसरी शाखा जहाँ है वहीं रहती है।',
      id: 'Kondisinya {verdict}. Alur berbelok ke cabang itu; cabang lain tetap di tempatnya.',
      pt: 'A condição é {verdict}. O fluxo entra nesse ramo; o outro fica onde está.',
    },
    'caption.create': {
      en: 'New variable {name}, holding {value}.',
      ko: '새 변수 {name} — 담긴 값: {value}.',
      ja: '新しい変数 {name}、値は {value}。',
      zh: '新变量 {name},值为 {value}。',
      ar: 'متغير جديد {name}، قيمته {value}.',
      es: 'Nueva variable {name}, con {value}.',
      fr: 'Nouvelle variable {name}, qui vaut {value}.',
      hi: 'नया चर {name}, मान {value}।',
      id: 'Variabel baru {name}, berisi {value}.',
      pt: 'Nova variável {name}, com {value}.',
    },
    'caption.assign': {
      en: '{name} now holds {value}.',
      ko: '{name} 칸의 값이 바뀌었다: {value}.',
      ja: '{name} の値が変わった: {value}。',
      zh: '{name} 的值变为 {value}。',
      ar: 'أصبحت قيمة {name} الآن {value}.',
      es: '{name} ahora vale {value}.',
      fr: '{name} vaut maintenant {value}.',
      hi: '{name} का मान अब {value} है।',
      id: '{name} kini berisi {value}.',
      pt: '{name} agora vale {value}.',
    },
    'caption.rejoin': {
      en: 'The two branches meet again here. Shown: {out}',
      ko: '두 갈래가 여기서 다시 하나로 이어진다. 출력: {out}',
      ja: '二つの枝はここで再び一つになる。出力: {out}',
      zh: '两条分支在这里重新汇合。输出: {out}',
      ar: 'يلتقي الفرعان هنا من جديد. المخرَج: {out}',
      es: 'Las dos ramas vuelven a unirse aquí. Salida: {out}',
      fr: 'Les deux branches se rejoignent ici. Sortie : {out}',
      hi: 'दोनों शाखाएँ यहाँ फिर मिलती हैं। आउटपुट: {out}',
      id: 'Kedua cabang bertemu lagi di sini. Keluaran: {out}',
      pt: 'Os dois ramos voltam a se unir aqui. Saída: {out}',
    },
    'caption.show': {
      en: 'Shown: {out}',
      ko: '출력: {out}',
      ja: '出力: {out}',
      zh: '输出: {out}',
      ar: 'المخرَج: {out}',
      es: 'Salida: {out}',
      fr: 'Sortie : {out}',
      hi: 'आउटपुट: {out}',
      id: 'Keluaran: {out}',
      pt: 'Saída: {out}',
    },
    'caption.line': {
      en: 'This line runs.',
      ko: '이 줄이 실행된다.',
      ja: 'この行が実行される。',
      zh: '执行这一行。',
      ar: 'يُنفَّذ هذا السطر.',
      es: 'Se ejecuta esta línea.',
      fr: "Cette ligne s'exécute.",
      hi: 'यह पंक्ति चलती है।',
      id: 'Baris ini dijalankan.',
      pt: 'Esta linha é executada.',
    },
    'label.true': {
      en: 'true',
      ko: '참',
      ja: '真',
      zh: '真',
      ar: 'صحيح',
      es: 'verdadero',
      fr: 'vrai',
      hi: 'सत्य',
      id: 'benar',
      pt: 'verdadeiro',
    },
    'label.false': {
      en: 'false',
      ko: '거짓',
      ja: '偽',
      zh: '假',
      ar: 'خطأ',
      es: 'falso',
      fr: 'faux',
      hi: 'असत्य',
      id: 'salah',
      pt: 'falso',
    },
    'tag.cond': {
      en: '{expr} → {verdict}',
      ko: '{expr} → {verdict}',
      ja: '{expr} → {verdict}',
      zh: '{expr} → {verdict}',
      ar: '{expr} → {verdict}',
      es: '{expr} → {verdict}',
      fr: '{expr} → {verdict}',
      hi: '{expr} → {verdict}',
      id: '{expr} → {verdict}',
      pt: '{expr} → {verdict}',
    },
    'label.notTaken': {
      en: 'branch not taken · lines run: {n}',
      ko: '가지 않은 갈래 · 밟은 줄 {n}',
      ja: '進まなかった枝 · 実行した行 {n}',
      zh: '未走的分支 · 执行行数 {n}',
      ar: 'فرع لم يُسلك · أسطر نُفِّذت: {n}',
      es: 'rama no tomada · líneas ejecutadas: {n}',
      fr: 'branche non prise · lignes exécutées : {n}',
      hi: 'न ली गई शाखा · चली पंक्तियाँ: {n}',
      id: 'cabang tak diambil · baris dijalankan: {n}',
      pt: 'ramo não seguido · linhas executadas: {n}',
    },
    'label.vars': {
      en: 'variables',
      ko: '변수',
      ja: '変数',
      zh: '变量',
      ar: 'المتغيرات',
      es: 'variables',
      fr: 'variables',
      hi: 'चर',
      id: 'variabel',
      pt: 'variáveis',
    },
    'label.unchanged': {
      en: 'still its first value',
      ko: '처음 값 그대로',
      ja: '最初の値のまま',
      zh: '仍是最初的值',
      ar: 'ما زال على قيمته الأولى',
      es: 'sigue con su primer valor',
      fr: 'toujours sa première valeur',
      hi: 'अब भी पहला मान',
      id: 'masih nilai awalnya',
      pt: 'ainda com o primeiro valor',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المخرَج',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
  },
  blocks: {
    stage: { type: 'branch-take-one-path-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
