import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece 셋이 서로를 기다리면 왜 아무도 움직일 수 없게 되는가
 *
 * 잠드는 스레드마다 "누구를 기다린다" 는 화살이 하나씩 이어진다. 셋째 화살이 첫
 * 스레드로 돌아와 꽂히면 고리가 닫히고, 다음 틱에 차례를 받을 스레드가 없다.
 */
export const waitCycleFacet: FacetJson = {
  id: 'facet:waitCycle',
  title: {
    en: 'Circular wait',
    ko: '순환 대기',
    ja: '循環待ち',
    zh: '循环等待',
    ar: 'الانتظار الدائري',
    es: 'Espera circular',
    fr: 'Attente circulaire',
    hi: 'चक्रीय प्रतीक्षा',
    id: 'Penantian melingkar',
    pt: 'Espera circular',
  },
  description: {
    en: 'When three threads each wait for the next, why can none of them move?',
    ko: '셋이 서로를 기다리면 왜 아무도 움직일 수 없게 되는가',
    ja: '三つのスレッドが互いを待つと、なぜ誰も動けなくなるのか',
    zh: '三个线程互相等待时，为什么谁都无法前进？',
    ar: 'عندما تنتظر ثلاثة خيوط بعضها بعضًا، لماذا لا يستطيع أي منها التقدّم؟',
    es: 'Cuando tres hilos se esperan entre sí, ¿por qué ninguno puede avanzar?',
    fr: 'Quand trois threads s’attendent l’un l’autre, pourquoi aucun ne peut-il avancer ?',
    hi: 'जब तीन थ्रेड एक-दूसरे की प्रतीक्षा करते हैं, तो कोई भी आगे क्यों नहीं बढ़ पाता?',
    id: 'Saat tiga thread saling menunggu, mengapa tak satu pun bisa bergerak?',
    pt: 'Quando três threads esperam umas pelas outras, por que nenhuma consegue avançar?',
  },
  algorithm: 'module:waitCycle',
  scene: 'module:waitCycleScene',
  initialData: {
    type: 'wait-cycle',
    stepMs: 1400,
    locks: ['m1', 'm2', 'm3'],
    threads: [
      {
        id: 'A',
        program: [
          { op: 'lock', lock: 'm1' },
          { op: 'lock', lock: 'm2' },
          { op: 'work' },
          { op: 'unlock', lock: 'm2' },
          { op: 'unlock', lock: 'm1' },
        ],
      },
      {
        id: 'B',
        program: [
          { op: 'lock', lock: 'm2' },
          { op: 'lock', lock: 'm3' },
          { op: 'work' },
          { op: 'unlock', lock: 'm3' },
          { op: 'unlock', lock: 'm2' },
        ],
      },
      {
        id: 'C',
        program: [
          { op: 'lock', lock: 'm3' },
          { op: 'lock', lock: 'm1' },
          { op: 'work' },
          { op: 'unlock', lock: 'm1' },
          { op: 'unlock', lock: 'm3' },
        ],
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.tick': {
      en: 'Tick {n}',
      ko: '틱 {n}',
      ja: 'ティック {n}',
      zh: '时钟 {n}',
      ar: 'النبضة {n}',
      es: 'Tic {n}',
      fr: 'Tic {n}',
      hi: 'टिक {n}',
      id: 'Tik {n}',
      pt: 'Tique {n}',
    },
    'label.asleep': {
      en: 'asleep',
      ko: '잠듦',
      ja: '休眠',
      zh: '睡眠',
      ar: 'نائم',
      es: 'dormido',
      fr: 'endormi',
      hi: 'सुप्त',
      id: 'tidur',
      pt: 'dormindo',
    },
    'label.done': {
      en: 'done',
      ko: '끝남',
      ja: '終了',
      zh: '完成',
      ar: 'انتهى',
      es: 'terminado',
      fr: 'terminé',
      hi: 'पूर्ण',
      id: 'selesai',
      pt: 'concluída',
    },
    'label.cpu': {
      en: 'CPU',
      ko: 'CPU',
      ja: 'CPU',
      zh: 'CPU',
      ar: 'CPU',
      es: 'CPU',
      fr: 'CPU',
      hi: 'CPU',
      id: 'CPU',
      pt: 'CPU',
    },
    'caption.start': {
      en: 'No tick yet. Every lock is free.',
      ko: '아직 틱 전이다. 자물쇠는 모두 비어 있다.',
      ja: 'まだティックの前。ロックはすべて空いている。',
      zh: '还没有时钟节拍。所有锁都空着。',
      ar: 'لم تبدأ أي نبضة بعد. كل الأقفال حرة.',
      es: 'Aún no hay tics. Todos los cerrojos están libres.',
      fr: 'Aucun tic encore. Tous les verrous sont libres.',
      hi: 'अभी कोई टिक नहीं। सभी लॉक खाली हैं।',
      id: 'Belum ada tik. Semua kunci bebas.',
      pt: 'Nenhum tique ainda. Todas as travas estão livres.',
    },
    'caption.took': {
      en: '{thread} runs lock({lock}). It was free — now {thread} holds it.',
      ko: '{thread} 차례: lock({lock}). 비어 있어서 잡았다.',
      ja: '{thread} の番: lock({lock})。空いていたので取った。',
      zh: '轮到 {thread}：lock({lock})。锁是空的，于是拿到了。',
      ar: 'دور {thread}: lock({lock}). كان حرًا — الآن يمسكه {thread}.',
      es: 'Turno de {thread}: lock({lock}). Estaba libre; ahora lo tiene {thread}.',
      fr: 'Tour de {thread} : lock({lock}). Il était libre — {thread} le détient.',
      hi: '{thread} की बारी: lock({lock})। यह खाली था — अब {thread} के पास है।',
      id: 'Giliran {thread}: lock({lock}). Kunci bebas — kini dipegang {thread}.',
      pt: 'Vez de {thread}: lock({lock}). Estava livre — agora {thread} a detém.',
    },
    'caption.blocked': {
      en: '{thread} runs lock({lock}). Held by {owner} — {thread} sleeps and waits.',
      ko: '{thread} 차례: lock({lock}). 주인은 {owner}. 잠들어 기다린다.',
      ja: '{thread} の番: lock({lock})。持ち主は {owner}。眠って待つ。',
      zh: '轮到 {thread}：lock({lock})。持有者是 {owner}。{thread} 睡下等待。',
      ar: 'دور {thread}: lock({lock}). يمسكه {owner} — ينام {thread} وينتظر.',
      es: 'Turno de {thread}: lock({lock}). Lo tiene {owner}; {thread} se duerme y espera.',
      fr: 'Tour de {thread} : lock({lock}). Détenu par {owner} — {thread} s’endort et attend.',
      hi: '{thread} की बारी: lock({lock})। यह {owner} के पास है — {thread} सोकर प्रतीक्षा करता है।',
      id: 'Giliran {thread}: lock({lock}). Dipegang {owner} — {thread} tidur dan menunggu.',
      pt: 'Vez de {thread}: lock({lock}). Com {owner} — {thread} dorme e espera.',
    },
    'caption.closed': {
      en: '{thread} runs lock({lock}). Held by {owner}. Follow the arrows: {ring}',
      ko: '{thread} 차례: lock({lock}). 주인은 {owner}. 화살을 따라가면: {ring}',
      ja: '{thread} の番: lock({lock})。持ち主は {owner}。矢印をたどると: {ring}',
      zh: '轮到 {thread}：lock({lock})。持有者是 {owner}。顺着箭头走：{ring}',
      ar: 'دور {thread}: lock({lock}). يمسكه {owner}. اتبع الأسهم: {ring}',
      es: 'Turno de {thread}: lock({lock}). Lo tiene {owner}. Sigue las flechas: {ring}',
      fr: 'Tour de {thread} : lock({lock}). Détenu par {owner}. Suivez les flèches : {ring}',
      hi: '{thread} की बारी: lock({lock})। यह {owner} के पास है। तीरों पर चलें: {ring}',
      id: 'Giliran {thread}: lock({lock}). Dipegang {owner}. Ikuti panahnya: {ring}',
      pt: 'Vez de {thread}: lock({lock}). Com {owner}. Siga as setas: {ring}',
    },
    'caption.ran': {
      en: '{thread} runs {code}.',
      ko: '{thread} 차례: {code}.',
      ja: '{thread} の番: {code}。',
      zh: '轮到 {thread}：{code}。',
      ar: 'دور {thread}: {code}.',
      es: 'Turno de {thread}: {code}.',
      fr: 'Tour de {thread} : {code}.',
      hi: '{thread} की बारी: {code}।',
      id: 'Giliran {thread}: {code}.',
      pt: 'Vez de {thread}: {code}.',
    },
    'caption.released': {
      en: '{thread} runs unlock({lock}). No one is waiting, so it is free.',
      ko: '{thread} 차례: unlock({lock}). 기다리는 스레드가 없어 비운다.',
      ja: '{thread} の番: unlock({lock})。待つスレッドがないので空ける。',
      zh: '轮到 {thread}：unlock({lock})。没有线程在等，锁空出来。',
      ar: 'دور {thread}: unlock({lock}). لا أحد ينتظر، فيصبح حرًا.',
      es: 'Turno de {thread}: unlock({lock}). Nadie espera, así que queda libre.',
      fr: 'Tour de {thread} : unlock({lock}). Personne n’attend, il est libéré.',
      hi: '{thread} की बारी: unlock({lock})। कोई प्रतीक्षा में नहीं, इसलिए यह खाली है।',
      id: 'Giliran {thread}: unlock({lock}). Tak ada yang menunggu, jadi kunci bebas.',
      pt: 'Vez de {thread}: unlock({lock}). Ninguém espera, então fica livre.',
    },
    'caption.handed': {
      en: '{thread} runs unlock({lock}). Handed to {heir}, who wakes up.',
      ko: '{thread} 차례: unlock({lock}). 넘겨받는 쪽: {heir} — 깨어난다.',
      ja: '{thread} の番: unlock({lock})。受け取るのは {heir} — 目を覚ます。',
      zh: '轮到 {thread}：unlock({lock})。交给 {heir}，{heir} 醒来。',
      ar: 'دور {thread}: unlock({lock}). يُسلَّم إلى {heir} فيستيقظ.',
      es: 'Turno de {thread}: unlock({lock}). Pasa a {heir}, que despierta.',
      fr: 'Tour de {thread} : unlock({lock}). Transmis à {heir}, qui se réveille.',
      hi: '{thread} की बारी: unlock({lock})। {heir} को सौंपा गया, वह जाग जाता है।',
      id: 'Giliran {thread}: unlock({lock}). Diserahkan ke {heir}, yang lalu bangun.',
      pt: 'Vez de {thread}: unlock({lock}). Passa para {heir}, que acorda.',
    },
    'caption.halt': {
      en: 'Ready: {ready} · Asleep: {asleep} · Finished: {done} — no thread can take this tick.',
      ko: '준비: {ready} · 잠듦: {asleep} · 끝남: {done} — 이 틱을 받을 스레드가 없다.',
      ja: '準備: {ready} · 休眠: {asleep} · 終了: {done} — このティックを受け取るスレッドがない。',
      zh: '就绪：{ready} · 睡眠：{asleep} · 完成：{done} — 没有线程能接这个节拍。',
      ar: 'جاهز: {ready} · نائم: {asleep} · منتهٍ: {done} — لا خيط يستطيع أخذ هذه النبضة.',
      es: 'Listos: {ready} · Dormidos: {asleep} · Terminados: {done} — ningún hilo puede tomar este tic.',
      fr: 'Prêts : {ready} · Endormis : {asleep} · Terminés : {done} — aucun thread ne peut prendre ce tic.',
      hi: 'तैयार: {ready} · सुप्त: {asleep} · पूर्ण: {done} — कोई थ्रेड यह टिक नहीं ले सकता।',
      id: 'Siap: {ready} · Tidur: {asleep} · Selesai: {done} — tak ada thread yang bisa mengambil tik ini.',
      pt: 'Prontas: {ready} · Dormindo: {asleep} · Concluídas: {done} — nenhuma thread pode pegar este tique.',
    },
    'caption.end': {
      en: 'Every thread has finished. Finished: {done}.',
      ko: '모든 스레드가 끝났다. 끝남: {done}.',
      ja: 'すべてのスレッドが終わった。終了: {done}。',
      zh: '所有线程都已结束。完成：{done}。',
      ar: 'انتهت كل الخيوط. المنتهية: {done}.',
      es: 'Todos los hilos terminaron. Terminados: {done}.',
      fr: 'Tous les threads ont fini. Terminés : {done}.',
      hi: 'सभी थ्रेड पूरे हो गए। पूर्ण: {done}।',
      id: 'Semua thread selesai. Selesai: {done}.',
      pt: 'Todas as threads terminaram. Concluídas: {done}.',
    },
  },
  blocks: {
    stage: { type: 'wait-cycle-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
