import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 뒤 명령어는 기다리지 않고 앞 명령어의 결과를 쓸 수 있는가?
 *
 * 앞 명령어가 EX 에서 낸 값이 레지스터 파일을 거치지 않고 EX/MEM 단계 레지스터에서 뒤
 * 명령어의 EX 입구로 곧장 건너간다. 그때 레지스터 파일의 r1 은 아직 옛 값이다.
 */
export const operandForwardingFacet: FacetJson = {
  id: 'facet:operandForwarding',
  title: {
    en: 'Operand forwarding',
    ko: '포워딩',
    ja: 'フォワーディング',
    zh: '数据前递',
    ar: 'تمرير المعاملات',
    es: 'Reenvío de operandos',
    fr: 'Transfert d’opérandes',
    hi: 'ऑपरेंड फ़ॉरवर्डिंग',
    id: 'Penerusan operan',
    pt: 'Encaminhamento de operandos',
  },
  description: {
    en: 'The result I1 makes in EX crosses straight into the EX of I2, before the register file is written.',
    ko: 'I1 이 EX 에서 낸 결과가 레지스터 파일에 쓰이기 전에 I2 의 EX 로 곧장 건너간다.',
    ja: 'I1 が EX で出した結果は、レジスタファイルに書かれる前に I2 の EX へ直接渡る。',
    zh: 'I1 在 EX 得出的结果，在写回寄存器堆之前就直接送到 I2 的 EX。',
    ar: 'النتيجة التي يخرجها I1 في EX تعبر مباشرة إلى EX الخاص بـ I2 قبل أن تُكتب في ملف السجلات.',
    es: 'El resultado que I1 produce en EX pasa directo al EX de I2, antes de escribirse en el banco de registros.',
    fr: 'Le résultat produit par I1 en EX passe directement dans l’EX de I2, avant d’être écrit dans le banc de registres.',
    hi: 'I1 का EX में निकला परिणाम रजिस्टर फ़ाइल में लिखे जाने से पहले ही सीधे I2 के EX में पहुँच जाता है।',
    id: 'Hasil yang dibuat I1 di EX langsung menyeberang ke EX milik I2, sebelum ditulis ke berkas register.',
    pt: 'O resultado que I1 gera no EX passa direto para o EX de I2, antes de ser escrito no banco de registradores.',
  },
  algorithm: 'module:operandForwarding',
  scene: 'module:operandForwardingScene',
  initialData: {
    type: 'operand-forwarding',
    stepMs: 800,
    registers: [
      { name: 'r1', value: 3 },
      { name: 'r2', value: 7 },
      { name: 'r3', value: 5 },
      { name: 'r4', value: null },
      { name: 'r5', value: 4 },
    ],
    program: [
      { op: 'add', rd: 'r1', rs: 'r2', rt: 'r3' },
      { op: 'sub', rd: 'r4', rs: 'r1', rt: 'r5' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'stage.if': { en: 'IF', ko: 'IF', ja: 'IF', zh: 'IF', ar: 'IF', es: 'IF', fr: 'IF', hi: 'IF', id: 'IF', pt: 'IF' },
    'stage.id': { en: 'ID', ko: 'ID', ja: 'ID', zh: 'ID', ar: 'ID', es: 'ID', fr: 'ID', hi: 'ID', id: 'ID', pt: 'ID' },
    'stage.ex': { en: 'EX', ko: 'EX', ja: 'EX', zh: 'EX', ar: 'EX', es: 'EX', fr: 'EX', hi: 'EX', id: 'EX', pt: 'EX' },
    'stage.mem': { en: 'MEM', ko: 'MEM', ja: 'MEM', zh: 'MEM', ar: 'MEM', es: 'MEM', fr: 'MEM', hi: 'MEM', id: 'MEM', pt: 'MEM' },
    'stage.wb': { en: 'WB', ko: 'WB', ja: 'WB', zh: 'WB', ar: 'WB', es: 'WB', fr: 'WB', hi: 'WB', id: 'WB', pt: 'WB' },
    'label.exmem': {
      en: 'EX/MEM', ko: 'EX/MEM', ja: 'EX/MEM', zh: 'EX/MEM', ar: 'EX/MEM',
      es: 'EX/MEM', fr: 'EX/MEM', hi: 'EX/MEM', id: 'EX/MEM', pt: 'EX/MEM',
    },
    'label.instr': { en: 'I{n}', ko: 'I{n}', ja: 'I{n}', zh: 'I{n}', ar: 'I{n}', es: 'I{n}', fr: 'I{n}', hi: 'I{n}', id: 'I{n}', pt: 'I{n}' },
    'label.program': {
      en: 'program', ko: '프로그램', ja: 'プログラム', zh: '程序', ar: 'البرنامج',
      es: 'programa', fr: 'programme', hi: 'प्रोग्राम', id: 'program', pt: 'programa',
    },
    'label.regfile': {
      en: 'register file', ko: '레지스터 파일', ja: 'レジスタファイル', zh: '寄存器堆', ar: 'ملف السجلات',
      es: 'banco de registros', fr: 'banc de registres', hi: 'रजिस्टर फ़ाइल', id: 'berkas register', pt: 'banco de registradores',
    },
    'label.writeback': {
      en: 'write back', ko: '되쓰기', ja: '書き戻し', zh: '写回', ar: 'الكتابة الراجعة',
      es: 'escritura', fr: 'réécriture', hi: 'वापस लिखना', id: 'tulis balik', pt: 'escrita',
    },
    'label.stale': {
      en: 'old value', ko: '옛 값', ja: '古い値', zh: '旧值', ar: 'قيمة قديمة',
      es: 'valor viejo', fr: 'ancienne', hi: 'पुराना मान', id: 'nilai lama', pt: 'valor antigo',
    },
    'label.cycle': {
      en: 'cycle', ko: '사이클', ja: 'サイクル', zh: '周期', ar: 'الدورة',
      es: 'ciclo', fr: 'cycle', hi: 'चक्र', id: 'siklus', pt: 'ciclo',
    },
    'label.noForward': {
      en: 'without forwarding', ko: '포워딩 없이', ja: 'フォワーディングなし', zh: '无前递', ar: 'بلا تمرير',
      es: 'sin reenvío', fr: 'sans transfert', hi: 'फ़ॉरवर्डिंग के बिना', id: 'tanpa penerusan', pt: 'sem encaminhamento',
    },
    'label.forward': {
      en: 'forward', ko: '포워딩', ja: 'フォワード', zh: '前递', ar: 'تمرير',
      es: 'reenvío', fr: 'transfert', hi: 'फ़ॉरवर्ड', id: 'penerusan', pt: 'encaminhamento',
    },
    'caption.init': {
      en: '{to} reads {reg}, which {from} writes.',
      ko: '{to} 쪽이 읽는 레지스터 {reg} — 그것을 쓰는 쪽은 {from}.',
      ja: '{to} は {from} が書く {reg} を読む。',
      zh: '{to} 要读 {from} 写入的 {reg}。',
      ar: '{to} يقرأ {reg} الذي يكتبه {from}.',
      es: '{to} lee {reg}, que escribe {from}.',
      fr: '{to} lit {reg}, que {from} écrit.',
      hi: '{to} वही {reg} पढ़ता है जिसे {from} लिखता है।',
      id: '{to} membaca {reg} yang ditulis {from}.',
      pt: '{to} lê {reg}, que {from} escreve.',
    },
    'caption.fetch': {
      en: 'Cycle {c}: {who} is fetched.',
      ko: '사이클 {c}: 가져온다 — {who}.',
      ja: 'サイクル {c}: {who} を取り込む。',
      zh: '周期 {c}：取出 {who}。',
      ar: 'الدورة {c}: يُجلب {who}.',
      es: 'Ciclo {c}: se busca {who}.',
      fr: 'Cycle {c} : {who} est chargée.',
      hi: 'चक्र {c}: {who} लाया जाता है।',
      id: 'Siklus {c}: {who} diambil.',
      pt: 'Ciclo {c}: {who} é buscada.',
    },
    'caption.read': {
      en: 'Cycle {c}: {who} reads {ra} = {va} and {rb} = {vb} from the register file.',
      ko: '사이클 {c}: 레지스터 파일에서 읽는다 — {who}, {ra} = {va}, {rb} = {vb}.',
      ja: 'サイクル {c}: {who} がレジスタファイルから {ra} = {va} と {rb} = {vb} を読む。',
      zh: '周期 {c}：{who} 从寄存器堆读出 {ra} = {va} 和 {rb} = {vb}。',
      ar: 'الدورة {c}: يقرأ {who} من ملف السجلات {ra} = {va} و{rb} = {vb}.',
      es: 'Ciclo {c}: {who} lee {ra} = {va} y {rb} = {vb} del banco de registros.',
      fr: 'Cycle {c} : {who} lit {ra} = {va} et {rb} = {vb} dans le banc de registres.',
      hi: 'चक्र {c}: {who} रजिस्टर फ़ाइल से {ra} = {va} और {rb} = {vb} पढ़ता है।',
      id: 'Siklus {c}: {who} membaca {ra} = {va} dan {rb} = {vb} dari berkas register.',
      pt: 'Ciclo {c}: {who} lê {ra} = {va} e {rb} = {vb} do banco de registradores.',
    },
    'caption.alu': {
      en: 'Cycle {c}: {who} computes {a} {op} {b} = {v} in EX.',
      ko: '사이클 {c}: EX 에서 셈한다 — {who}, {a} {op} {b} = {v}.',
      ja: 'サイクル {c}: {who} が EX で {a} {op} {b} = {v} を計算する。',
      zh: '周期 {c}：{who} 在 EX 算出 {a} {op} {b} = {v}。',
      ar: 'الدورة {c}: يحسب {who} في EX ‏{a} {op} {b} = {v}.',
      es: 'Ciclo {c}: {who} calcula {a} {op} {b} = {v} en EX.',
      fr: 'Cycle {c} : {who} calcule {a} {op} {b} = {v} en EX.',
      hi: 'चक्र {c}: {who} EX में {a} {op} {b} = {v} निकालता है।',
      id: 'Siklus {c}: {who} menghitung {a} {op} {b} = {v} di EX.',
      pt: 'Ciclo {c}: {who} calcula {a} {op} {b} = {v} no EX.',
    },
    'caption.stale': {
      en: 'Cycle {c}: {from} gets {v} in EX.',
      ko: '사이클 {c}: EX 에서 값이 나온다 — {from}, {v}.',
      ja: 'サイクル {c}: {from} が EX で {v} を得る。',
      zh: '周期 {c}：{from} 在 EX 得到 {v}。',
      ar: 'الدورة {c}: يحصل {from} على {v} في EX.',
      es: 'Ciclo {c}: {from} obtiene {v} en EX.',
      fr: 'Cycle {c} : {from} obtient {v} en EX.',
      hi: 'चक्र {c}: {from} को EX में {v} मिलता है।',
      id: 'Siklus {c}: {from} mendapat {v} di EX.',
      pt: 'Ciclo {c}: {from} obtém {v} no EX.',
    },
    'caption.stale.note': {
      en: 'At the same time {to} reads {reg} = {old} from the register file, the old value.',
      ko: '같은 때 레지스터 파일에서 읽는 쪽 — {to}, {reg} = {old}. 옛 값이다.',
      ja: '同じとき {to} はレジスタファイルから {reg} = {old} を読む。古い値だ。',
      zh: '同时 {to} 从寄存器堆读出 {reg} = {old}，这是旧值。',
      ar: 'في الوقت نفسه يقرأ {to} من ملف السجلات {reg} = {old}، وهي القيمة القديمة.',
      es: 'A la vez {to} lee {reg} = {old} del banco de registros: el valor viejo.',
      fr: 'Au même moment {to} lit {reg} = {old} dans le banc de registres : l’ancienne valeur.',
      hi: 'उसी समय {to} रजिस्टर फ़ाइल से {reg} = {old} पढ़ता है — पुराना मान।',
      id: 'Pada saat yang sama {to} membaca {reg} = {old} dari berkas register, nilai lama.',
      pt: 'Ao mesmo tempo {to} lê {reg} = {old} do banco de registradores: o valor antigo.',
    },
    'caption.forward': {
      en: "Cycle {c}: {v} crosses from EX/MEM straight into {to}'s EX.",
      ko: '사이클 {c}: EX/MEM 에서 EX 입구로 곧장 건너간다 — {v}, 받는 쪽은 {to}.',
      ja: 'サイクル {c}: {v} が EX/MEM から {to} の EX へ直接渡る。',
      zh: '周期 {c}：{v} 从 EX/MEM 直接送进 {to} 的 EX。',
      ar: 'الدورة {c}: تعبر {v} من EX/MEM مباشرة إلى EX الخاص بـ {to}.',
      es: 'Ciclo {c}: {v} pasa de EX/MEM directo al EX de {to}.',
      fr: 'Cycle {c} : {v} passe d’EX/MEM directement dans l’EX de {to}.',
      hi: 'चक्र {c}: {v} EX/MEM से सीधे {to} के EX में पहुँचता है।',
      id: 'Siklus {c}: {v} menyeberang dari EX/MEM langsung ke EX milik {to}.',
      pt: 'Ciclo {c}: {v} passa de EX/MEM direto para o EX de {to}.',
    },
    'caption.forward.note': {
      en: 'The register file still holds {reg} = {old}.',
      ko: '레지스터 파일에는 아직 {reg} = {old}.',
      ja: 'レジスタファイルはまだ {reg} = {old}。',
      zh: '寄存器堆里仍是 {reg} = {old}。',
      ar: 'ملف السجلات ما زال يحمل {reg} = {old}.',
      es: 'El banco de registros aún tiene {reg} = {old}.',
      fr: 'Le banc de registres contient encore {reg} = {old}.',
      hi: 'रजिस्टर फ़ाइल में अब भी {reg} = {old} है।',
      id: 'Berkas register masih berisi {reg} = {old}.',
      pt: 'O banco de registradores ainda guarda {reg} = {old}.',
    },
    'caption.write': {
      en: 'Cycle {c}: {who} writes {reg} = {v} into the register file.',
      ko: '사이클 {c}: 레지스터 파일에 쓴다 — {who}, {reg} = {v}.',
      ja: 'サイクル {c}: {who} がレジスタファイルに {reg} = {v} を書く。',
      zh: '周期 {c}：{who} 把 {reg} = {v} 写入寄存器堆。',
      ar: 'الدورة {c}: يكتب {who} ‏{reg} = {v} في ملف السجلات.',
      es: 'Ciclo {c}: {who} escribe {reg} = {v} en el banco de registros.',
      fr: 'Cycle {c} : {who} écrit {reg} = {v} dans le banc de registres.',
      hi: 'चक्र {c}: {who} रजिस्टर फ़ाइल में {reg} = {v} लिखता है।',
      id: 'Siklus {c}: {who} menulis {reg} = {v} ke berkas register.',
      pt: 'Ciclo {c}: {who} escreve {reg} = {v} no banco de registradores.',
    },
    'caption.done': {
      en: '{count} instructions, {stalls} stall cycles: they finish at cycle {end}.',
      ko: '명령어 {count} 개, 멈춘 사이클 {stalls} 개 — 끝나는 사이클은 {end}.',
      ja: '命令 {count} 個、停止サイクル {stalls} — 終わるのはサイクル {end}。',
      zh: '{count} 条指令，停顿 {stalls} 个周期，在周期 {end} 结束。',
      ar: '{count} تعليمات، و{stalls} دورات توقف: تنتهي في الدورة {end}.',
      es: '{count} instrucciones, {stalls} ciclos de parada: terminan en el ciclo {end}.',
      fr: '{count} instructions, {stalls} cycles d’arrêt : elles finissent au cycle {end}.',
      hi: '{count} निर्देश, {stalls} रुकने वाले चक्र: वे चक्र {end} पर पूरे होते हैं।',
      id: '{count} instruksi, {stalls} siklus berhenti: selesai di siklus {end}.',
      pt: '{count} instruções, {stalls} ciclos de parada: terminam no ciclo {end}.',
    },
    'caption.done.note': {
      en: 'Without forwarding, {to} waits {stall} more cycles and they finish at cycle {slow}.',
      ko: '포워딩이 없으면 {to} 쪽이 사이클 {stall} 개를 더 멈춘다. 끝나는 사이클은 {slow}.',
      ja: 'フォワーディングがなければ {to} はさらに {stall} サイクル待ち、終わるのはサイクル {slow}。',
      zh: '没有前递时，{to} 要多等 {stall} 个周期，到周期 {slow} 才结束。',
      ar: 'بلا تمرير ينتظر {to} ‏{stall} دورات إضافية وينتهيان في الدورة {slow}.',
      es: 'Sin reenvío, {to} espera {stall} ciclos más y terminan en el ciclo {slow}.',
      fr: 'Sans transfert, {to} attend {stall} cycles de plus et elles finissent au cycle {slow}.',
      hi: 'फ़ॉरवर्डिंग के बिना {to} {stall} चक्र और रुकता है और वे चक्र {slow} पर पूरे होते हैं।',
      id: 'Tanpa penerusan, {to} menunggu {stall} siklus lagi dan keduanya selesai di siklus {slow}.',
      pt: 'Sem encaminhamento, {to} espera mais {stall} ciclos e terminam no ciclo {slow}.',
    },
  },
  blocks: {
    stage: { type: 'operand-forwarding-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
