import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 빛이 한 번 튀고 끝나지 않으면 픽셀의 밝기는 어떻게 쌓이는가 — 끝없이 커지는가.
 *
 * 눈에서 나간 한 경로가 방 안에서 튈 때마다 새 꼭짓점이 생기고, 그 꼭짓점이 빛에서 직접 받은
 * 몫에 지나온 몫을 곱한 것이 픽셀의 합에 더해진다. 튈 때마다 반사율이 곱해져 더하는 몫이 줄고
 * 합은 한곳으로 모인다.
 */
export const lightBouncesManyFacet: FacetJson = {
  id: 'facet:lightBouncesMany',
  title: {
    en: 'Light bounces many times',
    ko: '빛이 여러 번 튄다',
    ja: '光は何度も跳ね返る',
    zh: '光线多次反弹',
    ar: 'الضوء يرتد مرات كثيرة',
    es: 'La luz rebota muchas veces',
    fr: 'La lumière rebondit plusieurs fois',
    hi: 'प्रकाश कई बार उछलता है',
    id: 'Cahaya memantul berkali-kali',
    pt: 'A luz ricocheteia muitas vezes',
  },
  description: {
    en: 'Each bounce multiplies what the path carries by the reflectance, so each added share shrinks and the pixel sum settles.',
    ko: '튈 때마다 지나온 몫에 반사율이 곱해져 더하는 몫이 줄고, 픽셀의 합은 한곳으로 모인다.',
    ja: '跳ね返るたびに経路が運ぶ分に反射率が掛かり、加える分が減ってピクセルの合計は一点に落ち着く。',
    zh: '每次反弹，路径携带的份额都乘以反射率，加上的份额越来越小，像素的总和趋于稳定。',
    ar: 'مع كل ارتداد يُضرب ما يحمله المسار في معامل الانعكاس، فتصغر الحصة المضافة ويستقر مجموع البكسل.',
    es: 'En cada rebote lo que lleva el camino se multiplica por la reflectancia, así que cada aporte es menor y la suma del píxel se asienta.',
    fr: 'À chaque rebond, ce que porte le chemin est multiplié par la réflectance : chaque apport diminue et la somme du pixel se stabilise.',
    hi: 'हर उछाल पर पथ जो हिस्सा ढोता है वह परावर्तकता से गुणा होता है, इसलिए जुड़ने वाला हिस्सा घटता है और पिक्सेल का योग स्थिर हो जाता है।',
    id: 'Setiap pantulan mengalikan bagian yang dibawa jalur dengan reflektansi, sehingga bagian yang ditambahkan mengecil dan jumlah piksel mengendap.',
    pt: 'A cada ricochete, o que o caminho carrega é multiplicado pela refletância, então cada parcela somada diminui e a soma do pixel se estabiliza.',
  },
  algorithm: 'module:lightBouncesMany',
  scene: 'module:lightBouncesManyScene',
  initialData: {
    type: 'light-bounces-many',
    stepMs: 1800,
    room: { width: 4, height: 2.5 },
    surfaces: [
      { id: 'floor', normal: [0, 1] },
      { id: 'ceiling', normal: [0, -1] },
      { id: 'left', normal: [1, 0] },
      { id: 'right', normal: [-1, 0] },
    ],
    reflectance: 0.6,
    light: { at: [2.8, 2.2], intensity: 10 },
    eye: [0.5, 1.8],
    aim: [1.6, 0],
    turns: [45, 30, 15, -60],
  },
  shuffleOnReset: false,
  messages: {
    'label.floor': {
      en: 'Floor',
      ko: '바닥',
      ja: '床',
      zh: '地板',
      ar: 'الأرضية',
      es: 'Suelo',
      fr: 'Sol',
      hi: 'फ़र्श',
      id: 'Lantai',
      pt: 'Chão',
    },
    'label.ceiling': {
      en: 'Ceiling',
      ko: '천장',
      ja: '天井',
      zh: '天花板',
      ar: 'السقف',
      es: 'Techo',
      fr: 'Plafond',
      hi: 'छत',
      id: 'Langit-langit',
      pt: 'Teto',
    },
    'label.left': {
      en: 'Left wall',
      ko: '왼쪽 벽',
      ja: '左の壁',
      zh: '左墙',
      ar: 'الجدار الأيسر',
      es: 'Pared izquierda',
      fr: 'Mur gauche',
      hi: 'बाईं दीवार',
      id: 'Dinding kiri',
      pt: 'Parede esquerda',
    },
    'label.right': {
      en: 'Right wall',
      ko: '오른쪽 벽',
      ja: '右の壁',
      zh: '右墙',
      ar: 'الجدار الأيمن',
      es: 'Pared derecha',
      fr: 'Mur droit',
      hi: 'दाईं दीवार',
      id: 'Dinding kanan',
      pt: 'Parede direita',
    },
    'label.light': {
      en: 'Light',
      ko: '빛',
      ja: '光源',
      zh: '光源',
      ar: 'الضوء',
      es: 'Luz',
      fr: 'Lumière',
      hi: 'प्रकाश',
      id: 'Cahaya',
      pt: 'Luz',
    },
    'label.eye': {
      en: 'Eye',
      ko: '눈',
      ja: '目',
      zh: '眼睛',
      ar: 'العين',
      es: 'Ojo',
      fr: 'Œil',
      hi: 'आँख',
      id: 'Mata',
      pt: 'Olho',
    },
    'label.row': {
      en: 'This vertex',
      ko: '이번 꼭짓점',
      ja: '今回の頂点',
      zh: '本次顶点',
      ar: 'هذه الرأس',
      es: 'Este vértice',
      fr: 'Ce sommet',
      hi: 'यह शीर्ष',
      id: 'Simpul ini',
      pt: 'Este vértice',
    },
    'label.direct': {
      en: 'Direct {direct} × carried {through}',
      ko: '직접광 {direct} × 지나온 몫 {through}',
      ja: '直接光 {direct} × 運んできた分 {through}',
      zh: '直接光 {direct} × 携带份额 {through}',
      ar: 'مباشر {direct} × محمول {through}',
      es: 'Directa {direct} × acarreado {through}',
      fr: 'Direct {direct} × porté {through}',
      hi: 'प्रत्यक्ष {direct} × वहन {through}',
      id: 'Langsung {direct} × terbawa {through}',
      pt: 'Direta {direct} × carregado {through}',
    },
    'label.pixel': {
      en: 'Pixel brightness',
      ko: '픽셀 밝기',
      ja: 'ピクセルの明るさ',
      zh: '像素亮度',
      ar: 'سطوع البكسل',
      es: 'Brillo del píxel',
      fr: 'Luminosité du pixel',
      hi: 'पिक्सेल की चमक',
      id: 'Kecerahan piksel',
      pt: 'Brilho do pixel',
    },
    'label.sum': {
      en: 'Sum: {sum}',
      ko: '합: {sum}',
      ja: '合計: {sum}',
      zh: '总和: {sum}',
      ar: 'المجموع: {sum}',
      es: 'Suma: {sum}',
      fr: 'Somme : {sum}',
      hi: 'योग: {sum}',
      id: 'Jumlah: {sum}',
      pt: 'Soma: {sum}',
    },
    'caption.start': {
      en: 'One ray leaves the eye into the room.',
      ko: '눈에서 광선 하나가 방 안으로 나간다.',
      ja: '目から光線が一本、部屋の中へ出ていく。',
      zh: '一条光线从眼睛射入房间。',
      ar: 'يخرج شعاع واحد من العين إلى داخل الغرفة.',
      es: 'Un rayo sale del ojo hacia la habitación.',
      fr: 'Un rayon part de l’œil dans la pièce.',
      hi: 'आँख से एक किरण कमरे में निकलती है।',
      id: 'Satu sinar keluar dari mata ke dalam ruangan.',
      pt: 'Um raio sai do olho para dentro da sala.',
    },
    'caption.vertex': {
      en: 'Vertex {k} · {surface} · adds {add}',
      ko: '꼭짓점 {k} · {surface} · 더하는 몫 {add}',
      ja: '頂点 {k} · {surface} · 加える分 {add}',
      zh: '顶点 {k} · {surface} · 加上 {add}',
      ar: 'الرأس {k} · {surface} · يضيف {add}',
      es: 'Vértice {k} · {surface} · suma {add}',
      fr: 'Sommet {k} · {surface} · ajoute {add}',
      hi: 'शीर्ष {k} · {surface} · जोड़ता है {add}',
      id: 'Simpul {k} · {surface} · menambah {add}',
      pt: 'Vértice {k} · {surface} · soma {add}',
    },
    'caption.last': {
      en: 'Vertex {k} · {surface} · adds {add} · the path stops here',
      ko: '꼭짓점 {k} · {surface} · 더하는 몫 {add} · 경로는 여기서 멈춘다',
      ja: '頂点 {k} · {surface} · 加える分 {add} · 経路はここで止まる',
      zh: '顶点 {k} · {surface} · 加上 {add} · 路径到此为止',
      ar: 'الرأس {k} · {surface} · يضيف {add} · يتوقف المسار هنا',
      es: 'Vértice {k} · {surface} · suma {add} · el camino se detiene aquí',
      fr: 'Sommet {k} · {surface} · ajoute {add} · le chemin s’arrête ici',
      hi: 'शीर्ष {k} · {surface} · जोड़ता है {add} · पथ यहीं रुकता है',
      id: 'Simpul {k} · {surface} · menambah {add} · jalur berhenti di sini',
      pt: 'Vértice {k} · {surface} · soma {add} · o caminho para aqui',
    },
  },
  blocks: {
    stage: { type: 'light-bounces-many-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
