import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 행렬에 벡터를 곱한 답은 행렬의 열들로 무엇을 한 것인가
 */
export const matvecAsCombinationFacet: FacetJson = {
  id: 'facet:matvecAsCombination',
  title: {
    en: 'Matrix times vector: a weighted sum of columns',
    ko: '행렬 곱하기 벡터: 열의 가중합',
    ja: '行列とベクトルの積: 列の重み付き和',
    zh: '矩阵乘向量: 列的加权和',
    ar: 'ضرب مصفوفة في متجه: مجموع مرجّح للأعمدة',
    es: 'Matriz por vector: suma ponderada de columnas',
    fr: 'Matrice fois vecteur : somme pondérée des colonnes',
    hi: 'आव्यूह गुणा सदिश: स्तंभों का भारित योग',
    id: 'Matriks kali vektor: jumlah berbobot kolom',
    pt: 'Matriz vezes vetor: soma ponderada das colunas',
  },
  description: {
    en: 'Each number of v weights one column of A — the column stretches, flips or shrinks — and the columns added up are A v.',
    ko: 'v 의 수 하나하나가 A 의 열 하나에 무게로 걸린다. 열은 늘고, 뒤집히고, 줄고, 그렇게 바뀐 열을 다 더한 것이 A v 다.',
    ja: 'v の数がひとつずつ A の列に重みとしてかかる。列は伸び、反転し、縮み、それらを足し合わせたものが A v になる。',
    zh: 'v 的每个数作为权重作用在 A 的一列上。列被拉长、翻转或缩短，把这些列加起来就是 A v。',
    ar: 'كل عدد في v يزن عمودًا واحدًا من A — فيتمدّد العمود أو ينقلب أو ينكمش — ومجموع الأعمدة هو A v.',
    es: 'Cada número de v pondera una columna de A —la columna se estira, se invierte o se encoge— y la suma de las columnas es A v.',
    fr: 'Chaque nombre de v pèse sur une colonne de A — la colonne s’étire, se retourne ou rétrécit — et la somme des colonnes est A v.',
    hi: 'v की हर संख्या A के एक स्तंभ पर भार बनती है — स्तंभ खिंचता, पलटता या सिकुड़ता है — और स्तंभों का योग A v है।',
    id: 'Setiap bilangan di v menjadi bobot satu kolom A — kolom memanjang, terbalik, atau memendek — dan jumlah kolom-kolom itu adalah A v.',
    pt: 'Cada número de v pesa uma coluna de A — a coluna se estica, se inverte ou encolhe — e a soma das colunas é A v.',
  },
  algorithm: 'module:matvecAsCombination',
  scene: 'module:matvecAsCombinationScene',
  initialData: {
    type: 'matvec-as-combination',
    matrix: [
      [1, 2, -2],
      [2, -1, 2],
    ],
    vector: [2, -1, 0.5],
    stepMs: 2000,
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'matvec-as-combination-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'Sum starts at {sum}',
      ko: '합의 출발: {sum}',
      ja: '和の出発点: {sum}',
      zh: '和的起点: {sum}',
      ar: 'يبدأ المجموع عند {sum}',
      es: 'La suma empieza en {sum}',
      fr: 'La somme part de {sum}',
      hi: 'योग की शुरुआत: {sum}',
      id: 'Jumlah mulai dari {sum}',
      pt: 'A soma começa em {sum}',
    },
    'caption.stretch': {
      en: 'Column {j} × {w} stretches: {col} → {scaled}. Sum: {sum}',
      ko: '열 {j} × {w} — 늘어난다: {col} → {scaled}. 합: {sum}',
      ja: '列 {j} × {w} — 伸びる: {col} → {scaled}。和: {sum}',
      zh: '第 {j} 列 × {w} — 拉长: {col} → {scaled}。和: {sum}',
      ar: 'العمود {j} × {w} يتمدّد: {col} → {scaled}. المجموع: {sum}',
      es: 'Columna {j} × {w} se estira: {col} → {scaled}. Suma: {sum}',
      fr: 'Colonne {j} × {w} s’étire : {col} → {scaled}. Somme : {sum}',
      hi: 'स्तंभ {j} × {w} — खिंचता है: {col} → {scaled}। योग: {sum}',
      id: 'Kolom {j} × {w} memanjang: {col} → {scaled}. Jumlah: {sum}',
      pt: 'Coluna {j} × {w} se estica: {col} → {scaled}. Soma: {sum}',
    },
    'caption.flip': {
      en: 'Column {j} × {w} flips: {col} → {scaled}. Sum: {sum}',
      ko: '열 {j} × {w} — 뒤집힌다: {col} → {scaled}. 합: {sum}',
      ja: '列 {j} × {w} — 反転する: {col} → {scaled}。和: {sum}',
      zh: '第 {j} 列 × {w} — 翻转: {col} → {scaled}。和: {sum}',
      ar: 'العمود {j} × {w} ينقلب: {col} → {scaled}. المجموع: {sum}',
      es: 'Columna {j} × {w} se invierte: {col} → {scaled}. Suma: {sum}',
      fr: 'Colonne {j} × {w} se retourne : {col} → {scaled}. Somme : {sum}',
      hi: 'स्तंभ {j} × {w} — पलटता है: {col} → {scaled}। योग: {sum}',
      id: 'Kolom {j} × {w} terbalik: {col} → {scaled}. Jumlah: {sum}',
      pt: 'Coluna {j} × {w} se inverte: {col} → {scaled}. Soma: {sum}',
    },
    'caption.shrink': {
      en: 'Column {j} × {w} shrinks: {col} → {scaled}. Sum: {sum}',
      ko: '열 {j} × {w} — 줄어든다: {col} → {scaled}. 합: {sum}',
      ja: '列 {j} × {w} — 縮む: {col} → {scaled}。和: {sum}',
      zh: '第 {j} 列 × {w} — 缩短: {col} → {scaled}。和: {sum}',
      ar: 'العمود {j} × {w} ينكمش: {col} → {scaled}. المجموع: {sum}',
      es: 'Columna {j} × {w} se encoge: {col} → {scaled}. Suma: {sum}',
      fr: 'Colonne {j} × {w} rétrécit : {col} → {scaled}. Somme : {sum}',
      hi: 'स्तंभ {j} × {w} — सिकुड़ता है: {col} → {scaled}। योग: {sum}',
      id: 'Kolom {j} × {w} memendek: {col} → {scaled}. Jumlah: {sum}',
      pt: 'Coluna {j} × {w} encolhe: {col} → {scaled}. Soma: {sum}',
    },
    'caption.result': {
      en: 'Columns added: {n}. A v = {av}',
      ko: '더한 열: {n}. A v = {av}',
      ja: '足した列: {n}。A v = {av}',
      zh: '已相加的列: {n}。A v = {av}',
      ar: 'الأعمدة المضافة: {n}. A v = {av}',
      es: 'Columnas sumadas: {n}. A v = {av}',
      fr: 'Colonnes ajoutées : {n}. A v = {av}',
      hi: 'जोड़े गए स्तंभ: {n}। A v = {av}',
      id: 'Kolom yang dijumlahkan: {n}. A v = {av}',
      pt: 'Colunas somadas: {n}. A v = {av}',
    },
    'label.matrix': {
      en: 'A',
      ko: 'A',
      ja: 'A',
      zh: 'A',
      ar: 'A',
      es: 'A',
      fr: 'A',
      hi: 'A',
      id: 'A',
      pt: 'A',
    },
    'label.vector': {
      en: 'v',
      ko: 'v',
      ja: 'v',
      zh: 'v',
      ar: 'v',
      es: 'v',
      fr: 'v',
      hi: 'v',
      id: 'v',
      pt: 'v',
    },
    'label.sum': {
      en: 'Sum',
      ko: '합',
      ja: '和',
      zh: '和',
      ar: 'المجموع',
      es: 'Suma',
      fr: 'Somme',
      hi: 'योग',
      id: 'Jumlah',
      pt: 'Soma',
    },
    'label.result': {
      en: 'A v',
      ko: 'A v',
      ja: 'A v',
      zh: 'A v',
      ar: 'A v',
      es: 'A v',
      fr: 'A v',
      hi: 'A v',
      id: 'A v',
      pt: 'A v',
    },
    'label.weight': {
      en: '× {w}',
      ko: '× {w}',
      ja: '× {w}',
      zh: '× {w}',
      ar: '× {w}',
      es: '× {w}',
      fr: '× {w}',
      hi: '× {w}',
      id: '× {w}',
      pt: '× {w}',
    },
  },
};
