import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece 어느 두 값이 같은 레지스터를 나눠 쓸 수 없는가.
 *
 * 명령 열을 끝에서 앞으로 거슬러 훑으며, 줄이 값을 정의하는 순간 그때 살아 있는 값마다 선을 긋는다.
 * 다 훑은 뒤 값마다 이웃이 쓰지 않은 가장 낮은 번호의 레지스터를 준다.
 *
 * @notation native — 컴파일러 내부 표기. 할당 전 기계 명령(`load t1, a`)은 프로그램의 표기가 아니라
 * 컴파일러가 만드는 자료다.
 */
export const interferenceGraphFacet: FacetJson = {
  id: 'facet:interferenceGraph',
  title: {
    en: 'Interference graph',
    ko: '간섭 그래프',
    ja: '干渉グラフ',
    zh: '冲突图',
    ar: 'مخطط التداخل',
    es: 'Grafo de interferencia',
    fr: "Graphe d'interférence",
    hi: 'इंटरफ़ेरेंस ग्राफ़',
    id: 'Graf interferensi',
    pt: 'Grafo de interferência',
  },
  description: {
    en: 'Two values alive at the same moment cannot share a register — scanning backward draws an edge between them.',
    ko: '같은 때 살아 있는 두 값은 한 레지스터를 나눠 쓸 수 없다 — 거꾸로 훑으며 그 둘 사이에 선을 긋는다.',
    ja: '同時に生きている二つの値は一つのレジスタを共有できない — 逆向きに走査しながら二つの間に辺を引く。',
    zh: '同时存活的两个值不能共用一个寄存器——逆向扫描时在它们之间连一条边。',
    ar: 'قيمتان حيّتان في اللحظة نفسها لا تتشاركان سجلًا واحدًا — المسح العكسي يرسم حافة بينهما.',
    es: 'Dos valores vivos a la vez no pueden compartir registro: al recorrer hacia atrás se traza una arista entre ellos.',
    fr: 'Deux valeurs vivantes au même moment ne peuvent pas partager un registre : le parcours à rebours trace une arête entre elles.',
    hi: 'एक ही समय जीवित दो मान एक रजिस्टर साझा नहीं कर सकते — पीछे की ओर स्कैन करते हुए उनके बीच किनारा खींचा जाता है।',
    id: 'Dua nilai yang hidup bersamaan tidak bisa berbagi register — pemindaian mundur menarik sisi di antara keduanya.',
    pt: 'Dois valores vivos ao mesmo tempo não podem dividir um registrador — a varredura de trás para frente traça uma aresta entre eles.',
  },
  algorithm: 'module:interferenceGraph',
  scene: 'module:interferenceGraphScene',
  initialData: {
    type: 'interference-graph',
    stepMs: 900,
    program: [
      { op: 'load', dst: 't1', srcs: [], mem: 'a', imm: null },
      { op: 'load', dst: 't2', srcs: [], mem: 'b', imm: null },
      { op: 'load', dst: 't3', srcs: [], mem: 'c', imm: null },
      { op: 'add', dst: 't4', srcs: ['t1', 't2'], mem: null, imm: null },
      { op: 'mul', dst: 't5', srcs: ['t4', 't3'], mem: null, imm: null },
      { op: 'sub', dst: 't6', srcs: ['t5', 't1'], mem: null, imm: null },
      { op: 'store', dst: null, srcs: ['t6'], mem: 'x', imm: null },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Scan from the end, one line up at a time. Nothing is live after L{last}.',
      ko: '끝에서부터 한 줄씩 거슬러 오른다. L{last} 뒤에는 살아 있는 값이 없다.',
      ja: '末尾から一行ずつさかのぼる。L{last} の後で生きている値はない。',
      zh: '从末尾起一行一行往上扫。L{last} 之后没有存活的值。',
      ar: 'نمسح من النهاية صعودًا سطرًا بعد سطر. لا شيء حيّ بعد L{last}.',
      es: 'Se recorre desde el final, subiendo línea a línea. Tras L{last} no hay nada vivo.',
      fr: 'On part de la fin et on remonte ligne par ligne. Rien n’est vivant après L{last}.',
      hi: 'अंत से एक-एक पंक्ति ऊपर स्कैन करें। L{last} के बाद कुछ भी जीवित नहीं।',
      id: 'Pindai dari akhir, naik satu baris demi satu baris. Tak ada yang hidup setelah L{last}.',
      pt: 'Varre-se do fim, subindo linha a linha. Nada está vivo depois de L{last}.',
    },
    'caption.def': {
      en: 'L{line} defines {value}. One new edge to each value live beside it: {others}.',
      ko: 'L{line} 에서 {value} 정의. 같이 살아 있는 값마다 새 선 하나 — {others}.',
      ja: 'L{line} で {value} を定義。一緒に生きている値ごとに新しい辺を一本 — {others}。',
      zh: 'L{line} 定义 {value}。与同时存活的每个值各连一条新边：{others}。',
      ar: 'L{line} يعرّف {value}. حافة جديدة إلى كل قيمة حيّة معها: {others}.',
      es: 'L{line} define {value}. Una arista nueva hacia cada valor vivo a su lado: {others}.',
      fr: 'L{line} définit {value}. Une arête neuve vers chaque valeur vivante à côté : {others}.',
      hi: 'L{line} {value} को परिभाषित करती है। साथ जीवित हर मान तक एक नया किनारा: {others}।',
      id: 'L{line} mendefinisikan {value}. Satu sisi baru ke tiap nilai yang hidup bersamanya: {others}.',
      pt: 'L{line} define {value}. Uma aresta nova para cada valor vivo ao lado: {others}.',
    },
    'caption.defAlone': {
      en: 'L{line} defines {value}. Nothing else is live beside it, so no edge.',
      ko: 'L{line} 에서 {value} 정의. 같이 살아 있는 값이 없어 선은 없다.',
      ja: 'L{line} で {value} を定義。一緒に生きている値がないので辺はない。',
      zh: 'L{line} 定义 {value}。没有与它同时存活的值，所以不连边。',
      ar: 'L{line} يعرّف {value}. لا قيمة حيّة أخرى معه، فلا حافة.',
      es: 'L{line} define {value}. No hay otro valor vivo a su lado: ninguna arista.',
      fr: 'L{line} définit {value}. Aucune autre valeur vivante à côté : pas d’arête.',
      hi: 'L{line} {value} को परिभाषित करती है। साथ कोई और जीवित नहीं, इसलिए कोई किनारा नहीं।',
      id: 'L{line} mendefinisikan {value}. Tak ada nilai lain yang hidup bersamanya, jadi tak ada sisi.',
      pt: 'L{line} define {value}. Nenhum outro valor vivo ao lado: nenhuma aresta.',
    },
    'caption.use': {
      en: 'L{line} defines nothing. Its reads come alive: {values}.',
      ko: 'L{line} — 정의하는 값 없음. 읽는 값이 살아난다 — {values}.',
      ja: 'L{line} は何も定義しない。読む値が生き始める — {values}。',
      zh: 'L{line} 不定义任何值。它读取的值开始存活：{values}。',
      ar: 'L{line} لا يعرّف شيئًا. ما يقرؤه يصبح حيًّا: {values}.',
      es: 'L{line} no define nada. Lo que lee pasa a estar vivo: {values}.',
      fr: 'L{line} ne définit rien. Ce qu’elle lit devient vivant : {values}.',
      hi: 'L{line} कुछ परिभाषित नहीं करती। जो वह पढ़ती है वह जीवित होता है: {values}।',
      id: 'L{line} tidak mendefinisikan apa pun. Yang dibacanya menjadi hidup: {values}.',
      pt: 'L{line} não define nada. O que ela lê passa a estar vivo: {values}.',
    },
    'caption.color': {
      en: '{value}: colored neighbors hold {taken}. Lowest free: {reg}.',
      ko: '{value} 차례. 칠한 이웃이 쥔 것 — {taken}. 남은 가장 낮은 번호 — {reg}.',
      ja: '{value} の番。塗った隣が持つもの — {taken}。空いている最小番号 — {reg}。',
      zh: '轮到 {value}。已着色的邻居占用：{taken}。最小的空闲编号：{reg}。',
      ar: '{value}: الجيران الملوّنون يشغلون {taken}. أدنى رقم حرّ: {reg}.',
      es: '{value}: los vecinos coloreados ocupan {taken}. El libre más bajo: {reg}.',
      fr: '{value} : les voisins colorés tiennent {taken}. Plus bas libre : {reg}.',
      hi: '{value}: रंगे पड़ोसियों के पास {taken}। सबसे छोटा खाली: {reg}।',
      id: '{value}: tetangga yang diwarnai memegang {taken}. Terendah yang bebas: {reg}.',
      pt: '{value}: os vizinhos coloridos ocupam {taken}. O livre mais baixo: {reg}.',
    },
    'caption.colorFree': {
      en: '{value}: no colored neighbor. Lowest register: {reg}.',
      ko: '{value} 차례. 칠한 이웃이 없다. 가장 낮은 번호 — {reg}.',
      ja: '{value} の番。塗った隣はない。最小番号 — {reg}。',
      zh: '轮到 {value}。没有已着色的邻居。最小编号：{reg}。',
      ar: '{value}: لا جار ملوّن. أدنى سجل: {reg}.',
      es: '{value}: ningún vecino coloreado. El registro más bajo: {reg}.',
      fr: '{value} : aucun voisin coloré. Plus bas registre : {reg}.',
      hi: '{value}: कोई रंगा पड़ोसी नहीं। सबसे छोटा रजिस्टर: {reg}।',
      id: '{value}: tak ada tetangga yang diwarnai. Register terendah: {reg}.',
      pt: '{value}: nenhum vizinho colorido. O registrador mais baixo: {reg}.',
    },
    summary: {
      en: 'Values: {n} · Registers used: {k}',
      ko: '값: {n} · 쓴 레지스터: {k}',
      ja: '値: {n} · 使ったレジスタ: {k}',
      zh: '值：{n} · 用到的寄存器：{k}',
      ar: 'القيم: {n} · السجلات المستخدمة: {k}',
      es: 'Valores: {n} · Registros usados: {k}',
      fr: 'Valeurs : {n} · Registres utilisés : {k}',
      hi: 'मान: {n} · प्रयुक्त रजिस्टर: {k}',
      id: 'Nilai: {n} · Register terpakai: {k}',
      pt: 'Valores: {n} · Registradores usados: {k}',
    },
    'label.live': {
      en: 'Live',
      ko: '살아 있는 값',
      ja: '生きている値',
      zh: '存活的值',
      ar: 'الحيّة',
      es: 'Vivos',
      fr: 'Vivantes',
      hi: 'जीवित',
      id: 'Hidup',
      pt: 'Vivos',
    },
    'label.edges': {
      en: 'Edges: {n}',
      ko: '선: {n}',
      ja: '辺: {n}',
      zh: '边：{n}',
      ar: 'الحواف: {n}',
      es: 'Aristas: {n}',
      fr: 'Arêtes : {n}',
      hi: 'किनारे: {n}',
      id: 'Sisi: {n}',
      pt: 'Arestas: {n}',
    },
    'label.registers': {
      en: 'Registers',
      ko: '레지스터',
      ja: 'レジスタ',
      zh: '寄存器',
      ar: 'السجلات',
      es: 'Registros',
      fr: 'Registres',
      hi: 'रजिस्टर',
      id: 'Register',
      pt: 'Registradores',
    },
  },
  blocks: {
    stage: { type: 'interference-graph-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
