/**
 * clock-sync — 같은 메시지 열둘을 물리 도장과 램포트 수 두 눈으로 견준다.
 *
 * 손잡이 둘: 빠르기 배수(시계가 벌어지는 기울기) · 다시 맞춤 주기(분, 0 = 다시 없음).
 * 구조(프로세스 · 빠르기 · 맞춤 길 · 메시지 · 사다리)가 1 차 데이터이고, 남는 어긋남 · 도장 · 거꾸로 수 ·
 * 벌어짐 · 축은 algorithm 이 셈한다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { ClockSyncData } from './algorithm.js';

const initialData: ClockSyncData = {
  type: 'clock-sync',
  stepMs: 520,
  processes: ['P1', 'P2', 'P3'],
  ratePerMinute: [3, -2, 1],
  syncPaths: [
    { process: 'P1', goMs: 12, backMs: 8 },
    { process: 'P2', goMs: 9, backMs: 11 },
    { process: 'P3', goMs: 7, backMs: 5 },
  ],
  messages: [
    { id: 'm1', sendMinute: 1, src: 'P1', dst: 'P2', delayMs: 20 },
    { id: 'm2', sendMinute: 2, src: 'P2', dst: 'P3', delayMs: 15 },
    { id: 'm3', sendMinute: 3, src: 'P3', dst: 'P1', delayMs: 30 },
    { id: 'm4', sendMinute: 5, src: 'P1', dst: 'P3', delayMs: 10 },
    { id: 'm5', sendMinute: 6, src: 'P2', dst: 'P1', delayMs: 25 },
    { id: 'm6', sendMinute: 8, src: 'P3', dst: 'P2', delayMs: 12 },
    { id: 'm7', sendMinute: 9, src: 'P1', dst: 'P2', delayMs: 40 },
    { id: 'm8', sendMinute: 11, src: 'P2', dst: 'P3', delayMs: 8 },
    { id: 'm9', sendMinute: 12, src: 'P3', dst: 'P1', delayMs: 18 },
    { id: 'm10', sendMinute: 14, src: 'P1', dst: 'P3', delayMs: 22 },
    { id: 'm11', sendMinute: 15, src: 'P2', dst: 'P1', delayMs: 35 },
    { id: 'm12', sendMinute: 17, src: 'P3', dst: 'P2', delayMs: 16 },
  ],
  drifts: [0, 1, 2, 4, 8],
  resyncs: [0, 8, 4, 2],
  initialDrift: 4,
  initialResync: 0,
};

export const clockSyncFacet: FacetJson = {
  id: 'facet:clockSync',
  title: {
    en: 'Clock Sync',
    ko: '시계 동기화',
    ja: 'クロック同期',
    zh: '时钟同步',
    ar: 'مزامنة الساعات',
    es: 'Sincronización de relojes',
    fr: 'Synchronisation des horloges',
    hi: 'घड़ी सिंक्रनाइज़ेशन',
    id: 'Sinkronisasi jam',
    pt: 'Sincronização de relógios',
  },
  description: {
    en: 'Three process clocks drift apart and are resynced with a time server. Stamp twelve messages with physical clocks and some receives can land before their sends; the same messages under Lamport numbers never stand backward. Turn the drift and the resync period and watch which arrows flip.',
    ko: '프로세스 셋의 시계가 제 빠르기로 벌어지고 시간 서버와 다시 맞춘다. 메시지 열둘에 물리 시계로 도장을 찍으면 받음이 보냄보다 앞서는 것이 생길 수 있고, 같은 메시지를 램포트 수로 보면 거꾸로 서지 않는다. 빠르기 배수와 다시 맞춤 주기를 돌려 어느 화살표가 꺾이는지 본다.',
    ja: '3 つのプロセスの時計がそれぞれの速さでずれ、時刻サーバーと合わせ直す。12 通のメッセージに物理時計で刻印すると、受信が送信より前になるものが出ることがあるが、同じメッセージをランポート数で見ると逆向きにならない。ずれの倍率と再同期の周期を回し、どの矢印が折れるかを見る。',
    zh: '三个进程的时钟以各自的速度偏离，并与时间服务器重新对时。用物理时钟给十二条消息盖戳，可能出现接收早于发送的消息；同样的消息用 Lamport 数看则不会倒置。调节漂移倍数和重新同步周期，看哪些箭头折回。',
    ar: 'تنحرف ساعات ثلاث عمليات كلٌّ بسرعتها وتُعاد مزامنتها مع خادم الوقت. عند ختم اثنتي عشرة رسالة بالساعات الفعلية قد يسبق الاستلام الإرسال في بعضها، أما بأرقام لامبورت فلا تنقلب الرسائل نفسها أبدًا. غيّر معامل الانحراف ودورة إعادة المزامنة وراقب أي الأسهم تنقلب.',
    es: 'Los relojes de tres procesos se desvían a su ritmo y se resincronizan con un servidor de tiempo. Al sellar doce mensajes con relojes físicos, algunas recepciones pueden quedar antes de su envío; con números de Lamport los mismos mensajes nunca quedan al revés. Gira la deriva y el periodo de resincronización y mira qué flechas se invierten.',
    fr: "Les horloges de trois processus dérivent chacune à son rythme et sont resynchronisées avec un serveur de temps. En horodatant douze messages avec les horloges physiques, certaines réceptions peuvent tomber avant leur envoi ; avec les nombres de Lamport, les mêmes messages ne s'inversent jamais. Tournez la dérive et la période de resynchronisation et regardez quelles flèches basculent.",
    hi: 'तीन प्रक्रियाओं की घड़ियाँ अपनी गति से खिसकती हैं और समय सर्वर से फिर मिलाई जाती हैं। बारह संदेशों पर भौतिक घड़ी की मुहर लगाने पर कुछ में प्राप्ति भेजने से पहले पड़ सकती है; वही संदेश लैम्पोर्ट संख्या में कभी उलटे नहीं होते। विचलन गुणक और पुनः मिलान अवधि बदलें और देखें कौन से तीर पलटते हैं।',
    id: 'Jam tiga proses menyimpang dengan lajunya masing-masing dan disinkronkan ulang dengan server waktu. Jika dua belas pesan dicap dengan jam fisik, sebagian penerimaan bisa jatuh sebelum pengirimannya; dengan angka Lamport pesan yang sama tidak pernah terbalik. Putar pengali drift dan periode sinkron ulang, lalu lihat panah mana yang terbalik.',
    pt: 'Os relógios de três processos derivam cada um a seu ritmo e são ressincronizados com um servidor de tempo. Ao carimbar doze mensagens com relógios físicos, algumas recepções podem cair antes do envio; com números de Lamport as mesmas mensagens nunca ficam invertidas. Gire a deriva e o período de ressincronização e veja quais setas se invertem.',
  },
  algorithm: 'module:clockSync',
  projector: 'module:clockSyncProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'clock-sync-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback!,
        {
          widget: 'segmented-slider',
          action: 'drift',
          name: 'drift',
          label: {
            en: 'Drift ×',
            ko: '빠르기 배수',
            ja: 'ずれの倍率',
            zh: '漂移倍数',
            ar: 'معامل الانحراف',
            es: 'Deriva ×',
            fr: 'Dérive ×',
            hi: 'विचलन गुणक',
            id: 'Pengali drift',
            pt: 'Deriva ×',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 4, label: '4', default: true },
            { value: 8, label: '8' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'resync',
          name: 'resync',
          label: {
            en: 'Resync (min)',
            ko: '다시 맞춤 주기(분)',
            ja: '再同期の周期(分)',
            zh: '重新同步周期(分)',
            ar: 'دورة المزامنة (دقيقة)',
            es: 'Resincronizar (min)',
            fr: 'Resynchro (min)',
            hi: 'पुनः मिलान (मिनट)',
            id: 'Sinkron ulang (menit)',
            pt: 'Ressincronizar (min)',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'none',
                ko: '없음',
                ja: 'なし',
                zh: '无',
                ar: 'لا شيء',
                es: 'nunca',
                fr: 'aucune',
                hi: 'नहीं',
                id: 'tidak',
                pt: 'nunca',
              },
              default: true,
            },
            { value: 8, label: '8' },
            { value: 4, label: '4' },
            { value: 2, label: '2' },
          ],
        },
      ],
      metrics: [
        {
          name: 'physical-inverted',
          label: {
            en: 'Physical inverted',
            ko: '물리 도장 거꾸로',
            ja: '物理刻印の逆転',
            zh: '物理戳倒置',
            ar: 'انقلاب الختم الفعلي',
            es: 'Invertidos (físico)',
            fr: 'Inversés (physique)',
            hi: 'भौतिक उलटे',
            id: 'Terbalik (fisik)',
            pt: 'Invertidos (físico)',
          },
          initial: 0,
        },
        {
          name: 'lamport-inverted',
          label: {
            en: 'Lamport inverted',
            ko: '램포트 거꾸로',
            ja: 'ランポートの逆転',
            zh: 'Lamport 倒置',
            ar: 'انقلاب لامبورت',
            es: 'Invertidos (Lamport)',
            fr: 'Inversés (Lamport)',
            hi: 'लैम्पोर्ट उलटे',
            id: 'Terbalik (Lamport)',
            pt: 'Invertidos (Lamport)',
          },
          initial: 0,
        },
        {
          name: 'max-skew-ms',
          label: {
            en: 'Max skew (ms)',
            ko: '가장 큰 벌어짐(ms)',
            ja: '最大のずれ幅(ms)',
            zh: '最大偏差(ms)',
            ar: 'أكبر تباعد (ms)',
            es: 'Desfase máx. (ms)',
            fr: 'Écart max (ms)',
            hi: 'अधिकतम अंतर (ms)',
            id: 'Selisih maks (ms)',
            pt: 'Desvio máx. (ms)',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:clock-sync-imperative',
      label: {
        en: 'Code',
        ko: '코드',
        ja: 'コード',
        zh: '代码',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
    },
  },
  messages: {
    'label.offset': {
      en: 'Clock offset (ms)',
      ko: '어긋남(ms)',
      ja: '時計のずれ(ms)',
      zh: '时钟偏差(ms)',
      ar: 'انحراف الساعة (ms)',
      es: 'Desfase del reloj (ms)',
      fr: "Décalage d'horloge (ms)",
      hi: 'घड़ी विचलन (ms)',
      id: 'Selisih jam (ms)',
      pt: 'Desvio do relógio (ms)',
    },
    'label.physical': {
      en: 'Physical stamp',
      ko: '물리 도장',
      ja: '物理刻印',
      zh: '物理时间戳',
      ar: 'الختم الفعلي',
      es: 'Sello físico',
      fr: 'Horodatage physique',
      hi: 'भौतिक मुहर',
      id: 'Cap fisik',
      pt: 'Carimbo físico',
    },
    'label.lamport': {
      en: 'Lamport number',
      ko: '램포트 수',
      ja: 'ランポート数',
      zh: 'Lamport 数',
      ar: 'رقم لامبورت',
      es: 'Número de Lamport',
      fr: 'Nombre de Lamport',
      hi: 'लैम्पोर्ट संख्या',
      id: 'Angka Lamport',
      pt: 'Número de Lamport',
    },
    'label.minute': {
      en: 'min',
      ko: '분',
      ja: '分',
      zh: '分',
      ar: 'دقيقة',
      es: 'min',
      fr: 'min',
      hi: 'मिनट',
      id: 'menit',
      pt: 'min',
    },
    'label.resync': {
      en: 'resync',
      ko: '맞춤',
      ja: '同期',
      zh: '对时',
      ar: 'مزامنة',
      es: 'resinc.',
      fr: 'resynchro',
      hi: 'मिलान',
      id: 'sinkron',
      pt: 'ressinc.',
    },
    'caption.minute': {
      en: 'minute {minute}',
      ko: '분 {minute}',
      ja: '{minute} 分',
      zh: '第 {minute} 分',
      ar: 'الدقيقة {minute}',
      es: 'minuto {minute}',
      fr: 'minute {minute}',
      hi: 'मिनट {minute}',
      id: 'menit {minute}',
      pt: 'minuto {minute}',
    },
    'caption.send': {
      en: '{id} · minute {minute} · {src} → {dst}',
      ko: '{id} · 분 {minute} · {src} → {dst}',
      ja: '{id} · {minute} 分 · {src} → {dst}',
      zh: '{id} · 第 {minute} 分 · {src} → {dst}',
      ar: '{id} · الدقيقة {minute} · {src} → {dst}',
      es: '{id} · minuto {minute} · {src} → {dst}',
      fr: '{id} · minute {minute} · {src} → {dst}',
      hi: '{id} · मिनट {minute} · {src} → {dst}',
      id: '{id} · menit {minute} · {src} → {dst}',
      pt: '{id} · minuto {minute} · {src} → {dst}',
    },
    'caption.receive': {
      en: '{id} · receive − send: {ms} ms',
      ko: '{id} · 받음 − 보냄: {ms} ms',
      ja: '{id} · 受信 − 送信: {ms} ms',
      zh: '{id} · 接收 − 发送: {ms} ms',
      ar: '{id} · الاستلام − الإرسال: {ms} ms',
      es: '{id} · recepción − envío: {ms} ms',
      fr: '{id} · réception − envoi : {ms} ms',
      hi: '{id} · प्राप्ति − भेजना: {ms} ms',
      id: '{id} · terima − kirim: {ms} ms',
      pt: '{id} · recepção − envio: {ms} ms',
    },
    'caption.receiveInverted': {
      en: '{id} · receive − send: {ms} ms · inverted',
      ko: '{id} · 받음 − 보냄: {ms} ms · 거꾸로',
      ja: '{id} · 受信 − 送信: {ms} ms · 逆転',
      zh: '{id} · 接收 − 发送: {ms} ms · 倒置',
      ar: '{id} · الاستلام − الإرسال: {ms} ms · مقلوبة',
      es: '{id} · recepción − envío: {ms} ms · invertido',
      fr: '{id} · réception − envoi : {ms} ms · inversé',
      hi: '{id} · प्राप्ति − भेजना: {ms} ms · उलटा',
      id: '{id} · terima − kirim: {ms} ms · terbalik',
      pt: '{id} · recepção − envio: {ms} ms · invertido',
    },
    'caption.lamport': {
      en: 'Lamport: {send} → {recv}',
      ko: '램포트: {send} → {recv}',
      ja: 'ランポート: {send} → {recv}',
      zh: 'Lamport: {send} → {recv}',
      ar: 'لامبورت: {send} → {recv}',
      es: 'Lamport: {send} → {recv}',
      fr: 'Lamport : {send} → {recv}',
      hi: 'लैम्पोर्ट: {send} → {recv}',
      id: 'Lamport: {send} → {recv}',
      pt: 'Lamport: {send} → {recv}',
    },
  },
};
