import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 리더가 받은 쓰기를 팔로워에게 똑같이 옮겨 두면 무엇이 지켜지는가.
 */
export const copyToFollowersFacet: FacetJson = {
  id: 'facet:copyToFollowers',
  title: {
    en: 'Copy to followers',
    ko: '팔로워에게 사본 옮기기',
    ja: 'フォロワーへのコピー',
    zh: '复制到跟随者',
    ar: 'النسخ إلى التابعين',
    es: 'Copiar a los seguidores',
    fr: 'Copier vers les suiveurs',
    hi: 'फ़ॉलोअर तक प्रतिलिपि',
    id: 'Salin ke pengikut',
    pt: 'Copiar para os seguidores',
  },
  description: {
    en: 'The leader writes each value, copies it to both followers, and replies only when all three hold it. When the leader stops, a follower still answers the read.',
    ko: '리더는 값을 적어 두 팔로워에게 옮기고, 셋 모두 적은 뒤에야 응답한다. 리더가 멈춰도 팔로워가 읽기에 답한다.',
    ja: 'リーダーは値を書き、二つのフォロワーへ写し、三つすべてが書いてから応答する。リーダーが止まってもフォロワーが読み取りに答える。',
    zh: '领导者写下值，复制给两个跟随者，三者都写好后才回复。领导者停止后，跟随者仍能回答读取。',
    ar: 'يكتب القائد القيمة وينسخها إلى التابعَين، ولا يرد إلا بعد أن تحملها العقد الثلاث. وحين يتوقف القائد يظل تابع يجيب عن القراءة.',
    es: 'El líder escribe cada valor, lo copia a los dos seguidores y responde solo cuando los tres lo tienen. Si el líder se detiene, un seguidor sigue respondiendo la lectura.',
    fr: 'Le leader écrit chaque valeur, la copie vers les deux suiveurs et ne répond que lorsque les trois la détiennent. Quand le leader s’arrête, un suiveur répond encore à la lecture.',
    hi: 'लीडर हर मान लिखता है, उसे दोनों फ़ॉलोअर तक कॉपी करता है और तीनों के लिख लेने पर ही उत्तर देता है। लीडर रुक जाए तब भी फ़ॉलोअर पढ़ने का उत्तर देता है।',
    id: 'Pemimpin menulis setiap nilai, menyalinnya ke dua pengikut, dan baru membalas setelah ketiganya memegangnya. Saat pemimpin berhenti, pengikut tetap menjawab pembacaan.',
    pt: 'O líder escreve cada valor, copia-o para os dois seguidores e só responde quando os três o têm. Quando o líder para, um seguidor ainda responde à leitura.',
  },
  algorithm: 'module:copyToFollowers',
  scene: 'module:copyToFollowersScene',
  initialData: {
    type: 'copy-to-followers',
    stepMs: 1100,
    nodes: ['n1', 'n2', 'n3'],
    leader: 'n1',
    writes: ['a=1', 'b=2'],
    stop: 'n1',
    read: { key: 'b', at: 'n2' },
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Every node is empty.',
      ko: '모든 노드가 비어 있다.',
      ja: 'どのノードも空だ。',
      zh: '每个节点都是空的。',
      ar: 'كل العقد فارغة.',
      es: 'Todos los nodos están vacíos.',
      fr: 'Tous les nœuds sont vides.',
      hi: 'हर नोड खाली है।',
      id: 'Semua node kosong.',
      pt: 'Todos os nós estão vazios.',
    },
    'caption.write': {
      en: 'Write {cmd} lands on the leader first. Copies: {n}',
      ko: '쓰기 {cmd} — 먼저 리더에 적힌다. 사본: {n}',
      ja: '書き込み {cmd} — まずリーダーに書かれる。コピー: {n}',
      zh: '写入 {cmd} 先落在领导者上。副本: {n}',
      ar: 'الكتابة {cmd} تصل إلى القائد أولًا. النسخ: {n}',
      es: 'La escritura {cmd} llega primero al líder. Copias: {n}',
      fr: 'L’écriture {cmd} arrive d’abord chez le leader. Copies : {n}',
      hi: 'लेखन {cmd} पहले लीडर पर पहुँचता है। प्रतियाँ: {n}',
      id: 'Tulisan {cmd} lebih dulu masuk ke pemimpin. Salinan: {n}',
      pt: 'A escrita {cmd} chega primeiro ao líder. Cópias: {n}',
    },
    'caption.replicate': {
      en: 'The leader sends {cmd} to every follower at once. Copies: {n}',
      ko: '리더가 팔로워 모두에게 한꺼번에 보낸다: {cmd}. 사본: {n}',
      ja: 'リーダーがすべてのフォロワーへ同時に送る: {cmd}。コピー: {n}',
      zh: '领导者同时把 {cmd} 发给所有跟随者。副本: {n}',
      ar: 'يرسل القائد {cmd} إلى كل التابعين دفعة واحدة. النسخ: {n}',
      es: 'El líder envía {cmd} a todos los seguidores a la vez. Copias: {n}',
      fr: 'Le leader envoie {cmd} à tous les suiveurs en même temps. Copies : {n}',
      hi: 'लीडर {cmd} को सभी फ़ॉलोअर तक एक साथ भेजता है। प्रतियाँ: {n}',
      id: 'Pemimpin mengirim {cmd} ke semua pengikut sekaligus. Salinan: {n}',
      pt: 'O líder envia {cmd} a todos os seguidores de uma vez. Cópias: {n}',
    },
    'caption.ack': {
      en: 'Reply comes back only after all have written: ok. Copies: {n}',
      ko: '모두 적은 뒤에야 응답이 돌아온다: ok. 사본: {n}',
      ja: 'すべてが書いてから応答が返る: ok。コピー: {n}',
      zh: '全部写好后才返回回复: ok。副本: {n}',
      ar: 'لا يعود الرد إلا بعد أن يكتب الجميع: ok. النسخ: {n}',
      es: 'La respuesta vuelve solo cuando todos han escrito: ok. Copias: {n}',
      fr: 'La réponse ne revient qu’une fois que tous ont écrit : ok. Copies : {n}',
      hi: 'सबके लिख लेने के बाद ही उत्तर लौटता है: ok. प्रतियाँ: {n}',
      id: 'Balasan baru kembali setelah semua menulis: ok. Salinan: {n}',
      pt: 'A resposta só volta depois que todos escreveram: ok. Cópias: {n}',
    },
    'caption.stop': {
      en: 'Node {node} stops.',
      ko: '노드 {node} 멈춤.',
      ja: 'ノード {node} が止まる。',
      zh: '节点 {node} 停止。',
      ar: 'العقدة {node} تتوقف.',
      es: 'El nodo {node} se detiene.',
      fr: 'Le nœud {node} s’arrête.',
      hi: 'नोड {node} रुक जाता है।',
      id: 'Node {node} berhenti.',
      pt: 'O nó {node} para.',
    },
    'caption.read': {
      en: 'Read {key} goes to {node}. Answer: {value}. Live copies: {n}',
      ko: '읽기 {key} → {node}. 답: {value}. 살아 있는 사본: {n}',
      ja: '読み取り {key} → {node}。答え: {value}。生きているコピー: {n}',
      zh: '读取 {key} 发往 {node}。回答: {value}。存活副本: {n}',
      ar: 'القراءة {key} تذهب إلى {node}. الجواب: {value}. النسخ الحية: {n}',
      es: 'La lectura {key} va a {node}. Respuesta: {value}. Copias vivas: {n}',
      fr: 'La lecture {key} va vers {node}. Réponse : {value}. Copies vivantes : {n}',
      hi: 'पढ़ना {key} → {node}. उत्तर: {value}. जीवित प्रतियाँ: {n}',
      id: 'Pembacaan {key} menuju {node}. Jawaban: {value}. Salinan hidup: {n}',
      pt: 'A leitura {key} vai para {node}. Resposta: {value}. Cópias vivas: {n}',
    },
    'label.client': {
      en: 'client',
      ko: '클라이언트',
      ja: 'クライアント',
      zh: '客户端',
      ar: 'العميل',
      es: 'cliente',
      fr: 'client',
      hi: 'क्लाइंट',
      id: 'klien',
      pt: 'cliente',
    },
    'label.leader': {
      en: 'leader',
      ko: '리더',
      ja: 'リーダー',
      zh: '领导者',
      ar: 'القائد',
      es: 'líder',
      fr: 'leader',
      hi: 'लीडर',
      id: 'pemimpin',
      pt: 'líder',
    },
    'label.follower': {
      en: 'follower',
      ko: '팔로워',
      ja: 'フォロワー',
      zh: '跟随者',
      ar: 'تابع',
      es: 'seguidor',
      fr: 'suiveur',
      hi: 'फ़ॉलोअर',
      id: 'pengikut',
      pt: 'seguidor',
    },
    'label.stopped': {
      en: 'stopped',
      ko: '멈춤',
      ja: '停止',
      zh: '已停止',
      ar: 'متوقفة',
      es: 'detenido',
      fr: 'arrêté',
      hi: 'रुका हुआ',
      id: 'berhenti',
      pt: 'parado',
    },
    'label.ok': {
      en: 'ok',
      ko: 'ok',
      ja: 'ok',
      zh: 'ok',
      ar: 'ok',
      es: 'ok',
      fr: 'ok',
      hi: 'ok',
      id: 'ok',
      pt: 'ok',
    },
  },
  blocks: {
    stage: { type: 'copy-to-followers-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
