import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 맞춘 자료로 재면 왜 안 되는가 — 맞출 때 떼어 둔 것으로 재면 무엇이 다른가.
 *
 * 점 열 가운데 셋이 맞추기 전에 떨어져 나가 따로 선다. 직선은 남은 일곱에만 맞춰 놓이고,
 * 같은 직선에서 잰 벗어남이 떼어 둔 셋에서 더 크게 벌어진다.
 */
export const holdOutSomeFacet: FacetJson = {
  id: 'facet:holdOutSome',
  title: {
    en: 'Hold some out',
    ko: '몇을 떼어 둔다',
    ja: 'いくつかを取り分ける',
    zh: '留出一部分',
    ar: 'تنحية بعض النقاط',
    es: 'Apartar algunos',
    fr: 'En mettre de côté',
    hi: 'कुछ को अलग रखना',
    id: 'Sisihkan sebagian',
    pt: 'Separar alguns',
  },
  description: {
    en: 'Why not score a model on the data it was fitted to — and what changes when you score it on points set aside before fitting?',
    ko: '맞춘 자료로 재면 왜 안 되는가 — 맞출 때 떼어 둔 것으로 재면 무엇이 다른가?',
    ja: '当てはめたデータで測るとなぜいけないのか — 当てはめる前に取り分けた点で測ると何が違うのか?',
    zh: '为什么不能用拟合所用的数据来评估 — 用拟合前留出的点来评估，会有什么不同？',
    ar: 'لماذا لا نقيس النموذج على البيانات التي طُوبق عليها — وما الذي يتغير حين نقيسه على نقاط نُحّيت قبل المطابقة؟',
    es: '¿Por qué no medir un modelo con los datos a los que se ajustó — y qué cambia al medirlo con puntos apartados antes de ajustar?',
    fr: 'Pourquoi ne pas évaluer un modèle sur les données qui ont servi à l’ajuster — et que change une évaluation sur des points mis de côté avant ?',
    hi: 'जिस डेटा पर मॉडल फ़िट किया गया उसी पर मापना क्यों ठीक नहीं — और फ़िट करने से पहले अलग रखे बिंदुओं पर मापने से क्या बदलता है?',
    id: 'Mengapa model tidak diukur pada data yang dipakai mencocokkannya — dan apa bedanya bila diukur pada titik yang disisihkan sebelum pencocokan?',
    pt: 'Por que não medir um modelo nos dados em que foi ajustado — e o que muda ao medi-lo em pontos separados antes do ajuste?',
  },
  algorithm: 'module:holdOutSome',
  scene: 'module:holdOutSomeScene',
  initialData: {
    type: 'hold-out-some',
    points: [
      { x: 1, y: 1.3 },
      { x: 2, y: 3.2 },
      { x: 3, y: 3.6 },
      { x: 4, y: 2.7 },
      { x: 5, y: 4.9 },
      { x: 6, y: 4.9 },
      { x: 7, y: 4.1 },
      { x: 8, y: 6.9 },
      { x: 9, y: 5.8 },
      { x: 10, y: 6.5 },
    ],
    // 무작위로 섞은 결과를 값으로 적었다 — 앞 일곱이 훈련, 뒤 셋이 떼어 둠
    order: [3, 9, 0, 2, 7, 5, 4, 8, 1, 6],
    holdOut: 3,
    stepMs: 2200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.points': {
      en: 'Points: {n}. Nothing fitted yet.',
      ko: '점: {n}. 아직 아무것도 맞추지 않았다.',
      ja: '点: {n}。まだ何も当てはめていない。',
      zh: '点：{n}。尚未拟合任何东西。',
      ar: 'النقاط: {n}. لم تُجرَ أي مطابقة بعد.',
      es: 'Puntos: {n}. Aún no se ha ajustado nada.',
      fr: 'Points : {n}. Rien n’est encore ajusté.',
      hi: 'बिंदु: {n}. अभी कुछ भी फ़िट नहीं किया गया।',
      id: 'Titik: {n}. Belum ada yang dicocokkan.',
      pt: 'Pontos: {n}. Nada foi ajustado ainda.',
    },
    'caption.split': {
      en: 'Set aside before fitting — x: {xs}',
      ko: '맞추기 전에 떼어 둔다 — x: {xs}',
      ja: '当てはめる前に取り分ける — x: {xs}',
      zh: '拟合之前先留出 — x：{xs}',
      ar: 'تُنحّى جانبًا قبل المطابقة — x: {xs}',
      es: 'Apartados antes de ajustar — x: {xs}',
      fr: 'Mis de côté avant l’ajustement — x : {xs}',
      hi: 'फ़िट करने से पहले अलग रखे गए — x: {xs}',
      id: 'Disisihkan sebelum pencocokan — x: {xs}',
      pt: 'Separados antes do ajuste — x: {xs}',
    },
    'caption.fit': {
      en: 'Fitted to the training points only: ŷ = {a} + {b}·x',
      ko: '훈련 점으로만 맞춘 직선: ŷ = {a} + {b}·x',
      ja: '訓練点だけで当てはめた直線: ŷ = {a} + {b}·x',
      zh: '只用训练点拟合的直线：ŷ = {a} + {b}·x',
      ar: 'خط مُطابَق على نقاط التدريب وحدها: ŷ = {a} + {b}·x',
      es: 'Recta ajustada solo a los puntos de entrenamiento: ŷ = {a} + {b}·x',
      fr: 'Droite ajustée sur les seuls points d’entraînement : ŷ = {a} + {b}·x',
      hi: 'केवल प्रशिक्षण बिंदुओं पर फ़िट की गई रेखा: ŷ = {a} + {b}·x',
      id: 'Garis yang dicocokkan hanya pada titik latih: ŷ = {a} + {b}·x',
      pt: 'Reta ajustada só aos pontos de treino: ŷ = {a} + {b}·x',
    },
    'caption.train': {
      en: 'Measured on the training points — MSE: {mse}',
      ko: '훈련 점에서 잰다 — MSE: {mse}',
      ja: '訓練点で測る — MSE: {mse}',
      zh: '在训练点上测量 — MSE：{mse}',
      ar: 'القياس على نقاط التدريب — MSE: {mse}',
      es: 'Medido en los puntos de entrenamiento — MSE: {mse}',
      fr: 'Mesuré sur les points d’entraînement — MSE : {mse}',
      hi: 'प्रशिक्षण बिंदुओं पर मापा गया — MSE: {mse}',
      id: 'Diukur pada titik latih — MSE: {mse}',
      pt: 'Medido nos pontos de treino — MSE: {mse}',
    },
    'caption.held': {
      en: 'Same line, measured on the held-out points — MSE: {mse}',
      ko: '같은 직선을 떼어 둔 점에서 잰다 — MSE: {mse}',
      ja: '同じ直線を取り分けた点で測る — MSE: {mse}',
      zh: '同一条直线，在留出的点上测量 — MSE：{mse}',
      ar: 'الخط نفسه، مقيسًا على النقاط المُنحّاة — MSE: {mse}',
      es: 'La misma recta, medida en los puntos apartados — MSE: {mse}',
      fr: 'La même droite, mesurée sur les points mis de côté — MSE : {mse}',
      hi: 'वही रेखा, अलग रखे बिंदुओं पर मापी गई — MSE: {mse}',
      id: 'Garis yang sama, diukur pada titik yang disisihkan — MSE: {mse}',
      pt: 'A mesma reta, medida nos pontos separados — MSE: {mse}',
    },
    'label.held': {
      en: 'Held out',
      ko: '떼어 둠',
      ja: '取り分け',
      zh: '留出',
      ar: 'المُنحّاة',
      es: 'Apartados',
      fr: 'Mis de côté',
      hi: 'अलग रखे',
      id: 'Disisihkan',
      pt: 'Separados',
    },
    'label.mseTrain': {
      en: 'Training MSE: {v}',
      ko: '훈련 MSE: {v}',
      ja: '訓練 MSE: {v}',
      zh: '训练 MSE：{v}',
      ar: 'MSE التدريب: {v}',
      es: 'MSE de entrenamiento: {v}',
      fr: 'MSE d’entraînement : {v}',
      hi: 'प्रशिक्षण MSE: {v}',
      id: 'MSE latih: {v}',
      pt: 'MSE de treino: {v}',
    },
    'label.mseHeld': {
      en: 'Held-out MSE: {v}',
      ko: '떼어 둠 MSE: {v}',
      ja: '取り分け MSE: {v}',
      zh: '留出 MSE：{v}',
      ar: 'MSE المُنحّاة: {v}',
      es: 'MSE de apartados: {v}',
      fr: 'MSE mis de côté : {v}',
      hi: 'अलग रखे MSE: {v}',
      id: 'MSE disisihkan: {v}',
      pt: 'MSE dos separados: {v}',
    },
  },
  blocks: {
    stage: { type: 'hold-out-some-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
