import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: IP 주소만 아는 상대의 MAC 주소를 어떻게 알아내는가.
 *
 * 묻는 이가 "이 IP 는 누구 것이냐" 는 요청 하나를 방송 MAC 으로 보내면, 보낸 이를 뺀 모두가
 * 같은 순간 받는다. 저마다 찾는 IP 를 제 IP 와 견주어 아닌 곳은 버리고, 주인 하나만 묻는
 * 이의 MAC 으로 곧장 답한다. 묻는 이 손에 IP → MAC 한 쌍이 남는다.
 */
export const askWhoHasFacet: FacetJson = {
  id: 'facet:askWhoHas',
  title: {
    en: 'ARP request',
    ko: 'ARP 요청',
    ja: 'ARP 要求',
    zh: 'ARP 请求',
    ar: 'طلب ARP',
    es: 'Solicitud ARP',
    fr: 'Requête ARP',
    hi: 'ARP अनुरोध',
    id: 'Permintaan ARP',
    pt: 'Pedido ARP',
  },
  description: {
    en: 'Ask everyone whose IP this is — the question reaches all at once, and only the owner answers back.',
    ko: '이 IP 가 누구 것이냐고 모두에게 묻는다 — 물음은 한꺼번에 퍼지고, 주인 하나만 답을 돌려보낸다.',
    ja: 'この IP は誰のものかと全員に尋ねる — 問いは一度に広がり、持ち主だけが答えを返す。',
    zh: '向所有人询问这个 IP 属于谁——询问同时传到每一台，只有主人回答。',
    ar: 'اسأل الجميع لمن هذا الـ IP — يصل السؤال إلى الكل دفعة واحدة، ويجيب المالك وحده.',
    es: 'Preguntar a todos de quién es esta IP: la pregunta llega a todos a la vez y solo el dueño responde.',
    fr: 'Demander à tous à qui est cette IP — la question atteint tout le monde d’un coup, seul le propriétaire répond.',
    hi: 'सबसे पूछो कि यह IP किसका है — सवाल एक साथ सब तक पहुँचता है, और केवल मालिक जवाब लौटाता है।',
    id: 'Tanya semua orang milik siapa IP ini — pertanyaan sampai ke semua sekaligus, dan hanya pemiliknya yang menjawab.',
    pt: 'Perguntar a todos de quem é este IP — a pergunta chega a todos de uma vez e só o dono responde.',
  },
  algorithm: 'module:askWhoHas',
  scene: 'module:askWhoHasScene',
  initialData: {
    type: 'ask-who-has',
    stepMs: 1700,
    hosts: [
      { id: 'a', ip: '192.168.10.5', mac: 'b8:27:eb:4d:19:a2' },
      { id: 'b', ip: '192.168.10.17', mac: 'dc:a6:32:07:5e:c1' },
      { id: 'c', ip: '192.168.10.23', mac: '00:0c:29:8f:31:6b' },
      { id: 'd', ip: '192.168.10.42', mac: '48:2a:e3:b0:77:14' },
      { id: 'e', ip: '192.168.10.61', mac: 'e4:5f:01:c9:02:3d' },
    ],
    asker: 'a',
    targetIp: '192.168.10.23',
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'The asker knows an IP but not its MAC. Wanted: {ip}',
      ko: '묻는 이는 IP 만 알고 MAC 은 모른다. 찾는 IP: {ip}',
      ja: '尋ねる側は IP だけを知り、MAC を知らない。探す IP: {ip}',
      zh: '询问方只知道 IP，不知道 MAC。要找的 IP：{ip}',
      ar: 'السائل يعرف عنوان IP لكن لا يعرف MAC. المطلوب: {ip}',
      es: 'Quien pregunta conoce una IP pero no su MAC. Buscada: {ip}',
      fr: 'Le demandeur connaît une IP mais pas sa MAC. Recherchée : {ip}',
      hi: 'पूछने वाला IP जानता है पर उसका MAC नहीं। खोजा गया: {ip}',
      id: 'Penanya tahu IP-nya tetapi tidak tahu MAC-nya. Dicari: {ip}',
      pt: 'Quem pergunta conhece um IP mas não o seu MAC. Procurado: {ip}',
    },
    'caption.request': {
      en: 'The broadcast request spreads. Received: {n}',
      ko: '방송 요청이 퍼진다. 받은 곳: {n}',
      ja: 'ブロードキャスト要求が広がる。受け取った数: {n}',
      zh: '广播请求传开。收到的：{n}',
      ar: 'ينتشر طلب البث. المستلمون: {n}',
      es: 'La solicitud de difusión se propaga. Recibida por: {n}',
      fr: 'La requête en diffusion se propage. Reçue par : {n}',
      hi: 'प्रसारण अनुरोध फैलता है। पाने वाले: {n}',
      id: 'Permintaan siaran menyebar. Diterima: {n}',
      pt: 'O pedido em difusão se espalha. Recebido por: {n}',
    },
    'caption.compare': {
      en: 'Each compares the wanted IP with its own. Dropped: {dropped} · Owner: {owner}',
      ko: '저마다 찾는 IP 를 제 IP 와 견준다. 버린 곳: {dropped} · 주인: {owner}',
      ja: 'それぞれが探す IP を自分の IP と比べる。捨てた数: {dropped} · 持ち主: {owner}',
      zh: '每台主机把要找的 IP 与自己的比较。丢弃的：{dropped} · 主人：{owner}',
      ar: 'كل مضيف يقارن العنوان المطلوب بعنوانه. أُسقط: {dropped} · المالك: {owner}',
      es: 'Cada uno compara la IP buscada con la suya. Descartada por: {dropped} · Dueño: {owner}',
      fr: 'Chacun compare l’IP recherchée à la sienne. Ignorée par : {dropped} · Propriétaire : {owner}',
      hi: 'हर कोई खोजे गए IP को अपने IP से मिलाता है। छोड़ने वाले: {dropped} · मालिक: {owner}',
      id: 'Masing-masing membandingkan IP yang dicari dengan miliknya. Dibuang: {dropped} · Pemilik: {owner}',
      pt: 'Cada um compara o IP procurado com o seu. Descartado por: {dropped} · Dono: {owner}',
    },
    'caption.reply': {
      en: 'The owner answers straight to the asker’s MAC. Received: {n}',
      ko: '주인은 묻는 이의 MAC 으로 곧장 답한다. 받은 곳: {n}',
      ja: '持ち主は尋ねた側の MAC へ直接答える。受け取った数: {n}',
      zh: '主人直接回答到询问方的 MAC。收到的：{n}',
      ar: 'يجيب المالك مباشرة إلى عنوان MAC الخاص بالسائل. المستلمون: {n}',
      es: 'El dueño responde directo a la MAC de quien pregunta. Recibida por: {n}',
      fr: 'Le propriétaire répond directement à la MAC du demandeur. Reçue par : {n}',
      hi: 'मालिक सीधे पूछने वाले के MAC पर जवाब देता है। पाने वाले: {n}',
      id: 'Pemilik menjawab langsung ke MAC penanya. Diterima: {n}',
      pt: 'O dono responde direto ao MAC de quem perguntou. Recebido por: {n}',
    },
    'caption.learn': {
      en: 'Learned: {ip} → {mac} · Frames on the wire: {frames}',
      ko: '얻은 쌍: {ip} → {mac} · 선 위 프레임: {frames}',
      ja: '得た組: {ip} → {mac} · 回線上のフレーム: {frames}',
      zh: '得到的对应：{ip} → {mac} · 线路上的帧：{frames}',
      ar: 'ما عُرف: {ip} → {mac} · الإطارات على السلك: {frames}',
      es: 'Aprendido: {ip} → {mac} · Tramas en el cable: {frames}',
      fr: 'Appris : {ip} → {mac} · Trames sur le fil : {frames}',
      hi: 'मिली जोड़ी: {ip} → {mac} · तार पर फ़्रेम: {frames}',
      id: 'Didapat: {ip} → {mac} · Frame di kabel: {frames}',
      pt: 'Aprendido: {ip} → {mac} · Quadros no fio: {frames}',
    },
    'label.asker': {
      en: 'Asker',
      ko: '묻는 이',
      ja: '尋ねる側',
      zh: '询问方',
      ar: 'السائل',
      es: 'Pregunta',
      fr: 'Demandeur',
      hi: 'पूछने वाला',
      id: 'Penanya',
      pt: 'Quem pergunta',
    },
    'label.host': {
      en: 'Host {n}',
      ko: '호스트 {n}',
      ja: 'ホスト {n}',
      zh: '主机 {n}',
      ar: 'المضيف {n}',
      es: 'Host {n}',
      fr: 'Hôte {n}',
      hi: 'होस्ट {n}',
      id: 'Host {n}',
      pt: 'Host {n}',
    },
    'label.dropped': {
      en: 'dropped',
      ko: '버림',
      ja: '破棄',
      zh: '丢弃',
      ar: 'أُسقط',
      es: 'descartado',
      fr: 'ignoré',
      hi: 'छोड़ा',
      id: 'dibuang',
      pt: 'descartado',
    },
    'label.owner': {
      en: 'mine',
      ko: '내 것',
      ja: '自分のもの',
      zh: '是我的',
      ar: 'لي',
      es: 'es mía',
      fr: 'c’est moi',
      hi: 'मेरा',
      id: 'milikku',
      pt: 'é meu',
    },
    'slot.title': {
      en: 'Wanted',
      ko: '찾는 것',
      ja: '探すもの',
      zh: '要找的',
      ar: 'المطلوب',
      es: 'Buscado',
      fr: 'Recherché',
      hi: 'खोज',
      id: 'Dicari',
      pt: 'Procurado',
    },
    'slot.ip': {
      en: 'IP',
      ko: 'IP',
      ja: 'IP',
      zh: 'IP',
      ar: 'IP',
      es: 'IP',
      fr: 'IP',
      hi: 'IP',
      id: 'IP',
      pt: 'IP',
    },
    'slot.mac': {
      en: 'MAC',
      ko: 'MAC',
      ja: 'MAC',
      zh: 'MAC',
      ar: 'MAC',
      es: 'MAC',
      fr: 'MAC',
      hi: 'MAC',
      id: 'MAC',
      pt: 'MAC',
    },
    'slot.unknown': {
      en: '?',
      ko: '?',
      ja: '?',
      zh: '?',
      ar: '؟',
      es: '?',
      fr: '?',
      hi: '?',
      id: '?',
      pt: '?',
    },
    'group.eth': {
      en: 'Ethernet header',
      ko: '이더넷 머리',
      ja: 'イーサネットヘッダー',
      zh: '以太网头部',
      ar: 'ترويسة إيثرنت',
      es: 'Cabecera Ethernet',
      fr: 'En-tête Ethernet',
      hi: 'ईथरनेट हेडर',
      id: 'Header Ethernet',
      pt: 'Cabeçalho Ethernet',
    },
    'group.request': {
      en: 'ARP request',
      ko: 'ARP 요청',
      ja: 'ARP 要求',
      zh: 'ARP 请求',
      ar: 'طلب ARP',
      es: 'Solicitud ARP',
      fr: 'Requête ARP',
      hi: 'ARP अनुरोध',
      id: 'Permintaan ARP',
      pt: 'Pedido ARP',
    },
    'group.reply': {
      en: 'ARP reply',
      ko: 'ARP 답',
      ja: 'ARP 応答',
      zh: 'ARP 应答',
      ar: 'رد ARP',
      es: 'Respuesta ARP',
      fr: 'Réponse ARP',
      hi: 'ARP उत्तर',
      id: 'Balasan ARP',
      pt: 'Resposta ARP',
    },
    'field.ethDst': {
      en: 'Dest MAC',
      ko: '받는 이 MAC',
      ja: '宛先 MAC',
      zh: '目的 MAC',
      ar: 'MAC الوجهة',
      es: 'MAC destino',
      fr: 'MAC dest.',
      hi: 'गंतव्य MAC',
      id: 'MAC tujuan',
      pt: 'MAC destino',
    },
    'field.ethSrc': {
      en: 'Source MAC',
      ko: '보낸 이 MAC',
      ja: '送信元 MAC',
      zh: '源 MAC',
      ar: 'MAC المصدر',
      es: 'MAC origen',
      fr: 'MAC source',
      hi: 'स्रोत MAC',
      id: 'MAC sumber',
      pt: 'MAC origem',
    },
    'field.op': {
      en: 'op',
      ko: 'op',
      ja: 'op',
      zh: 'op',
      ar: 'op',
      es: 'op',
      fr: 'op',
      hi: 'op',
      id: 'op',
      pt: 'op',
    },
    'field.senderMac': {
      en: 'Sender MAC',
      ko: '보낸 이 MAC',
      ja: '送信者 MAC',
      zh: '发送方 MAC',
      ar: 'MAC المرسل',
      es: 'MAC emisor',
      fr: 'MAC émetteur',
      hi: 'प्रेषक MAC',
      id: 'MAC pengirim',
      pt: 'MAC emissor',
    },
    'field.senderIp': {
      en: 'Sender IP',
      ko: '보낸 이 IP',
      ja: '送信者 IP',
      zh: '发送方 IP',
      ar: 'IP المرسل',
      es: 'IP emisor',
      fr: 'IP émetteur',
      hi: 'प्रेषक IP',
      id: 'IP pengirim',
      pt: 'IP emissor',
    },
    'field.targetMac': {
      en: 'Target MAC',
      ko: '대상 MAC',
      ja: '対象 MAC',
      zh: '目标 MAC',
      ar: 'MAC الهدف',
      es: 'MAC objetivo',
      fr: 'MAC cible',
      hi: 'लक्ष्य MAC',
      id: 'MAC target',
      pt: 'MAC alvo',
    },
    'field.targetIp': {
      en: 'Target IP',
      ko: '대상 IP',
      ja: '対象 IP',
      zh: '目标 IP',
      ar: 'IP الهدف',
      es: 'IP objetivo',
      fr: 'IP cible',
      hi: 'लक्ष्य IP',
      id: 'IP target',
      pt: 'IP alvo',
    },
  },
  blocks: {
    stage: { type: 'ask-who-has-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
