/**
 * facet:suffixArray — 한 번 줄 세워 두면, 그 뒤로는 이분 탐색으로 찾는다.
 *
 * 조각 `allSuffixesSorted` 가 꼬리를 줄 세우는 데서 멈춘다. 이 완제품은 줄 세운
 * 것 위에서 **실제로 찾기까지** 간다.
 *
 * 선언에 두는 것은 구조와 문안뿐이다. 글 넷과 그 글에서 찾을 패턴만이 1차
 * 데이터이고, 접미사 배열 · 이웃 겹침 · 덩어리의 자리와 크기는 전부 algorithm 이
 * 그 자리에서 셈한다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const suffixArrayFacet: FacetJson = {
  id: 'facet:suffixArray',
  title: {
    en: 'Suffix array',
    ko: '접미사 배열',
    ja: '接尾辞配列',
    zh: '后缀数组',
    ar: 'مصفوفة اللواحق',
    es: 'Arreglo de sufijos',
    fr: 'Tableau des suffixes',
    hi: 'प्रत्यय सरणी',
    id: 'Larik sufiks',
    pt: 'Arranjo de sufixos',
  },
  description: {
    en: 'Line the tails up once and any pattern is a binary search away — every occurrence sits in one block.',
    ko: '꼬리를 한 번 줄 세워 두면 어떤 패턴이든 이분 탐색으로 찾는다 — 모든 등장 자리가 한 덩어리에 모여 있다.',
    ja: '接尾辞を一度並べておけば、どんなパターンも二分探索で見つかる — すべての出現が一つの塊に集まる。',
    zh: '把后缀排好序一次，任何模式都能用二分查找找到 —— 所有出现位置都聚在一段里。',
    ar: 'رتِّب اللواحق مرة واحدة فيصبح أي نمط على بُعد بحث ثنائي — كل المواضع تتجمع في كتلة واحدة.',
    es: 'Ordena los sufijos una vez y cualquier patrón queda a una búsqueda binaria: todas las apariciones caen en un solo bloque.',
    fr: 'Triez les suffixes une fois et tout motif se trouve par recherche dichotomique : toutes les occurrences forment un seul bloc.',
    hi: 'प्रत्ययों को एक बार क्रम में लगा दें, फिर कोई भी पैटर्न द्विआधारी खोज से मिल जाता है — सभी उपस्थितियाँ एक ही खंड में बैठती हैं।',
    id: 'Urutkan sufiks sekali saja, lalu pola apa pun cukup dicari dengan pencarian biner — semua kemunculan berkumpul dalam satu blok.',
    pt: 'Ordene os sufixos uma vez e qualquer padrão fica a uma busca binária: todas as ocorrências ficam em um único bloco.',
  },
  algorithm: 'module:suffixArray',
  projector: 'module:suffixArrayProjector',
  initialData: {
    type: 'suffix-array',
    /**
     * 되풀이가 심해지는 차례로 넷. **길이를 11 로 맞춘 것은 화면 때문이다** —
     * 꼬리 줄 수가 곧 글자 수라, 길이가 달라지면 캔버스 세로가 바뀐다 (S-view).
     *
     * 이웃 겹침 평균은 algorithm 이 셈한다. 여기 적지 않는 것은 수를 손으로
     * 옮기지 않기 위해서다 — 실측값은 `description.ts` 의 표에 있다.
     */
    texts: [
      { text: 'buckminster', pattern: 'min' },
      { text: 'abracadabra', pattern: 'abra' },
      { text: 'aabbaabbaab', pattern: 'ab' },
      { text: 'abababababa', pattern: 'aba' },
    ],
    /** 처음 고른 단. 손잡이의 기본과 같아야 한다. */
    level: 2,
    stepMs: 620,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { ref: 'controls' },
      { ref: 'codePanel' },
    ],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'suffix-array-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'repetition',
          name: 'repetition',
          // 손잡이의 라벨은 이름이지 설명이 아니다.
          label: {
            en: 'Repetition',
            ko: '되풀이',
            ja: '繰り返し',
            zh: '重复度',
            ar: 'التكرار',
            es: 'Repetición',
            fr: 'Répétition',
            hi: 'पुनरावृत्ति',
            id: 'Pengulangan',
            pt: 'Repetição',
          },
          // 숫자는 표식이라 번역하지 않는다 (C10).
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2', default: true },
            { value: 3, label: '3' },
            { value: 4, label: '4' },
          ],
        },
      ],
      metrics: [
        {
          name: 'overlap-sum',
          label: {
            en: 'Overlap sum',
            ko: '겹침 합',
            ja: '重なりの合計',
            zh: '重叠合计',
            ar: 'مجموع التداخل',
            es: 'Suma de solapes',
            fr: 'Somme des recouvrements',
            hi: 'अतिव्यापन योग',
            id: 'Jumlah tumpang tindih',
            pt: 'Soma das sobreposições',
          },
          initial: 0,
        },
        {
          name: 'compare-count',
          label: {
            en: 'Compare',
            ko: '견줌',
            ja: '比較',
            zh: '比较',
            ar: 'مقارنة',
            es: 'Comparar',
            fr: 'Comparer',
            hi: 'तुलना',
            id: 'Banding',
            pt: 'Comparar',
          },
          initial: 0,
        },
        {
          name: 'match-count',
          label: {
            en: 'Matches',
            ko: '찾은 자리',
            ja: '見つけた位置',
            zh: '命中位置',
            ar: 'المواضع المطابقة',
            es: 'Coincidencias',
            fr: 'Occurrences',
            hi: 'मिले स्थान',
            id: 'Kecocokan',
            pt: 'Ocorrências',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:suffix-array-imperative',
      label: {
        en: 'Line up, then search',
        ko: '줄 세우고, 찾기',
        ja: '並べてから探す',
        zh: '先排序，再查找',
        ar: 'الترتيب ثم البحث',
        es: 'Ordenar y luego buscar',
        fr: 'Trier puis chercher',
        hi: 'क्रम में लगाएँ, फिर खोजें',
        id: 'Urutkan lalu cari',
        pt: 'Ordenar e depois buscar',
      },
    },
  },
  messages: {
    'label.text': {
      en: 'Text',
      ko: '글',
      ja: '文字列',
      zh: '文本',
      ar: 'النص',
      es: 'Texto',
      fr: 'Texte',
      hi: 'पाठ',
      id: 'Teks',
      pt: 'Texto',
    },
    'label.inOrder': {
      en: 'Tails in order',
      ko: '사전 순으로 선 꼬리',
      ja: '辞書順に並んだ接尾辞',
      zh: '按字典序排好的后缀',
      ar: 'اللواحق بالترتيب المعجمي',
      es: 'Sufijos en orden',
      fr: 'Suffixes dans l’ordre',
      hi: 'क्रम में लगे प्रत्यय',
      id: 'Sufiks terurut',
      pt: 'Sufixos em ordem',
    },
    'label.overlap': {
      en: 'Overlap',
      ko: '겹침',
      ja: '重なり',
      zh: '重叠',
      ar: 'التداخل',
      es: 'Solape',
      fr: 'Recouvrement',
      hi: 'अतिव्यापन',
      id: 'Tumpang tindih',
      pt: 'Sobreposição',
    },
    'label.pattern': {
      en: 'Looking for',
      ko: '찾는 것',
      ja: '探すもの',
      zh: '要找的',
      ar: 'المطلوب',
      es: 'Se busca',
      fr: 'On cherche',
      hi: 'खोज',
      id: 'Yang dicari',
      pt: 'Procurando',
    },
    'label.avgOverlap': {
      en: 'Average neighbour overlap',
      ko: '이웃 겹침 평균',
      ja: '隣どうしの重なりの平均',
      zh: '相邻重叠平均',
      ar: 'متوسط تداخل الجيران',
      es: 'Solape medio entre vecinos',
      fr: 'Recouvrement moyen des voisins',
      hi: 'पड़ोसी अतिव्यापन औसत',
      id: 'Rerata tumpang tindih tetangga',
      pt: 'Sobreposição média entre vizinhos',
    },
    'label.range': {
      en: 'Search range',
      ko: '남은 구간',
      ja: '残りの区間',
      zh: '剩余区间',
      ar: 'المجال المتبقي',
      es: 'Rango restante',
      fr: 'Intervalle restant',
      hi: 'शेष दायरा',
      id: 'Rentang tersisa',
      pt: 'Intervalo restante',
    },
    'label.block': {
      en: 'One block',
      ko: '한 덩어리',
      ja: '一つの塊',
      zh: '一整段',
      ar: 'كتلة واحدة',
      es: 'Un solo bloque',
      fr: 'Un seul bloc',
      hi: 'एक ही खंड',
      id: 'Satu blok',
      pt: 'Um único bloco',
    },
    'caption.setup': {
      en: 'One text, one pattern. The tails get lined up just once.',
      ko: '글 하나에 패턴 하나. 꼬리는 딱 한 번만 줄 세운다.',
      ja: '文字列一つにパターン一つ。接尾辞を並べるのは一度きりだ。',
      zh: '一段文本，一个模式。后缀只排一次序。',
      ar: 'نص واحد ونمط واحد. تُرتَّب اللواحق مرة واحدة فقط.',
      es: 'Un texto, un patrón. Los sufijos se ordenan una sola vez.',
      fr: 'Un texte, un motif. Les suffixes ne sont triés qu’une fois.',
      hi: 'एक पाठ, एक पैटर्न। प्रत्यय केवल एक बार क्रम में लगते हैं।',
      id: 'Satu teks, satu pola. Sufiks diurutkan sekali saja.',
      pt: 'Um texto, um padrão. Os sufixos são ordenados uma única vez.',
    },
    'caption.cut': {
      en: 'Every position leaves a tail — {count} of them.',
      ko: '자리마다 꼬리가 하나씩 — 모두 {count} 개다.',
      ja: '各位置に接尾辞が一つずつ — 全部で {count} 個だ。',
      zh: '每个位置留下一个后缀 —— 一共 {count} 个。',
      ar: 'كل موضع يترك لاحقة — وعددها {count}.',
      es: 'Cada posición deja un sufijo: {count} en total.',
      fr: 'Chaque position laisse un suffixe — {count} en tout.',
      hi: 'हर स्थान एक प्रत्यय छोड़ता है — कुल {count}।',
      id: 'Tiap posisi meninggalkan satu sufiks — semuanya {count}.',
      pt: 'Cada posição deixa um sufixo — {count} no total.',
    },
    'caption.sorted': {
      en: 'Lined up once. Neighbouring tails now share {avg} letters on average.',
      ko: '한 번 줄 세웠다. 이제 이웃한 꼬리끼리 앞이 평균 {avg} 글자 겹친다.',
      ja: '一度並べた。隣り合う接尾辞は平均 {avg} 文字を共有している。',
      zh: '排好序了。相邻后缀平均共享 {avg} 个字母。',
      ar: 'رُتِّبت مرة واحدة. تشترك اللواحق المتجاورة الآن في {avg} حرفًا وسطيًا.',
      es: 'Ordenados una vez. Los sufijos vecinos comparten ahora {avg} letras de media.',
      fr: 'Triés une fois. Les suffixes voisins partagent désormais {avg} lettres en moyenne.',
      hi: 'एक बार क्रम में लग गए। अब पड़ोसी प्रत्यय औसतन {avg} अक्षर साझा करते हैं।',
      id: 'Sudah diurutkan sekali. Sufiks bertetangga kini berbagi rata-rata {avg} huruf.',
      pt: 'Ordenados uma vez. Sufixos vizinhos agora compartilham {avg} letras em média.',
    },
    'caption.goRight': {
      en: 'Row {rank} sorts before the pattern — the block can only be below.',
      ko: '{rank} 번 줄은 패턴보다 앞선다 — 덩어리는 아래쪽에만 있을 수 있다.',
      ja: '{rank} 行目はパターンより前だ — 塊は下にしかない。',
      zh: '第 {rank} 行排在模式之前 —— 那一段只可能在下面。',
      ar: 'الصف {rank} يسبق النمط — لا يمكن أن تكون الكتلة إلا أسفل.',
      es: 'La fila {rank} va antes que el patrón: el bloque solo puede estar debajo.',
      fr: 'La ligne {rank} précède le motif — le bloc ne peut être qu’en dessous.',
      hi: 'पंक्ति {rank} पैटर्न से पहले आती है — खंड केवल नीचे हो सकता है।',
      id: 'Baris {rank} terurut sebelum pola — bloknya hanya mungkin di bawah.',
      pt: 'A linha {rank} vem antes do padrão — o bloco só pode estar abaixo.',
    },
    'caption.goLeft': {
      en: 'Row {rank} does not sort before the pattern — the block starts here or above.',
      ko: '{rank} 번 줄은 패턴보다 앞서지 않는다 — 덩어리는 여기이거나 위쪽이다.',
      ja: '{rank} 行目はパターンより前ではない — 塊はここか上だ。',
      zh: '第 {rank} 行不排在模式之前 —— 那一段从这里或更上面开始。',
      ar: 'الصف {rank} لا يسبق النمط — تبدأ الكتلة هنا أو أعلى.',
      es: 'La fila {rank} no va antes que el patrón: el bloque empieza aquí o más arriba.',
      fr: 'La ligne {rank} ne précède pas le motif — le bloc commence ici ou au-dessus.',
      hi: 'पंक्ति {rank} पैटर्न से पहले नहीं आती — खंड यहीं या ऊपर से शुरू होता है।',
      id: 'Baris {rank} tidak terurut sebelum pola — bloknya mulai di sini atau di atas.',
      pt: 'A linha {rank} não vem antes do padrão — o bloco começa aqui ou acima.',
    },
    'caption.block': {
      en: 'Binary search lands on row {start}. Every match sits from here.',
      ko: '이분 탐색이 {start} 번 줄에 닿았다. 찾는 자리는 전부 여기서부터다.',
      ja: '二分探索が {start} 行目に着いた。見つかる位置はすべてここからだ。',
      zh: '二分查找落在第 {start} 行。所有命中都从这里开始。',
      ar: 'حطّ البحث الثنائي عند الصف {start}. كل المواضع المطابقة تبدأ من هنا.',
      es: 'La búsqueda binaria cae en la fila {start}. Todas las coincidencias empiezan aquí.',
      fr: 'La recherche dichotomique aboutit à la ligne {start}. Toutes les occurrences partent d’ici.',
      hi: 'द्विआधारी खोज पंक्ति {start} पर पहुँची। सभी मेल यहीं से शुरू होते हैं।',
      id: 'Pencarian biner mendarat di baris {start}. Semua kecocokan mulai dari sini.',
      pt: 'A busca binária chega à linha {start}. Todas as ocorrências começam aqui.',
    },
    'caption.match': {
      en: 'Row {rank} starts with the pattern — position {from}.',
      ko: '{rank} 번 줄이 패턴으로 시작한다 — 글의 {from} 번 자리다.',
      ja: '{rank} 行目がパターンで始まる — 文字列の {from} 番目だ。',
      zh: '第 {rank} 行以模式开头 —— 对应文本第 {from} 位。',
      ar: 'الصف {rank} يبدأ بالنمط — عند الموضع {from}.',
      es: 'La fila {rank} empieza con el patrón: posición {from}.',
      fr: 'La ligne {rank} commence par le motif — position {from}.',
      hi: 'पंक्ति {rank} पैटर्न से शुरू होती है — स्थान {from}।',
      id: 'Baris {rank} diawali pola — posisi {from}.',
      pt: 'A linha {rank} começa com o padrão — posição {from}.',
    },
    'caption.done': {
      en: '{count} matches, all in one block, reached with {compares} comparisons.',
      ko: '찾은 자리 {count} 개가 모두 한 덩어리에 있고, 거기 닿는 데 견줌 {compares} 번이면 됐다.',
      ja: '見つけた位置 {count} 個がすべて一つの塊にあり、そこへ着くのに比較 {compares} 回で足りた。',
      zh: '命中 {count} 处，全在一段里，走到那里只用了 {compares} 次比较。',
      ar: '{count} مواضع مطابقة، كلها في كتلة واحدة، بلغناها بـ {compares} مقارنات.',
      es: '{count} coincidencias, todas en un bloque, alcanzadas con {compares} comparaciones.',
      fr: '{count} occurrences, toutes dans un bloc, atteintes en {compares} comparaisons.',
      hi: '{count} मेल, सभी एक ही खंड में, {compares} तुलनाओं से मिल गए।',
      id: '{count} kecocokan, semuanya dalam satu blok, dicapai dengan {compares} perbandingan.',
      pt: '{count} ocorrências, todas em um bloco, alcançadas com {compares} comparações.',
    },
  },
};
