/**
 * 병합과 리베이스 — 완제품.
 *
 * @notation native — 커밋 글자 · 해시 · 해시 입력 줄(`tree …` · `parent …`)이 곧 주장이다.
 *
 * IR 을 두지 않아 코드 패널 블록이 없다 (irs.ts 의 까닭 주석).
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const rebaseVsMergeFacet: FacetJson = {
  id: 'facet:rebaseVsMerge',
  title: {
    en: 'Merge and rebase',
    ko: '병합과 리베이스',
    ja: 'マージとリベース',
    zh: '合并与变基',
    ar: 'الدمج وإعادة التأسيس',
    es: 'Fusionar y rebasar',
    fr: 'Fusion et rebase',
    hi: 'मर्ज और रीबेस',
    id: 'Merge dan rebase',
    pt: 'Merge e rebase',
  },
  description: {
    en: 'Two ways to join branches reach the same files but leave different history: a merge adds one commit and keeps every hash, a rebase rewrites the changes on a new base with new hashes and leaves the old ones without a name.',
    ko: '두 줄기를 합치는 두 길은 같은 파일에 닿지만 이력을 다르게 남긴다. 병합은 커밋 하나를 더하고 해시를 지키며, 리베이스는 고침을 새 바닥 위에 새 해시로 다시 쓰고 옛것을 이름 없이 남긴다.',
    ja: 'ブランチを統合する二つの方法は同じファイルにたどり着くが、履歴の残り方が違う。マージはコミットを一つ足してハッシュを保ち、リベースは変更を新しい土台の上に新しいハッシュで書き直し、古いものを名前のないまま残す。',
    zh: '合并分支的两种方式得到相同的文件,却留下不同的历史:合并添加一个提交并保留所有哈希,变基则在新的基底上用新哈希重写改动,旧提交失去名字留在原处。',
    ar: 'طريقتا ضمّ الفرعين تصلان إلى الملفات نفسها لكنهما تتركان تاريخًا مختلفًا: الدمج يضيف إيداعًا واحدًا ويحفظ كل التجزئات، وإعادة التأسيس تعيد كتابة التغييرات فوق قاعدة جديدة بتجزئات جديدة وتترك القديمة بلا اسم.',
    es: 'Las dos formas de unir ramas llegan a los mismos archivos pero dejan historias distintas: la fusión añade un commit y conserva cada hash; el rebase reescribe los cambios sobre una base nueva con hashes nuevos y deja los viejos sin nombre.',
    fr: 'Les deux façons de joindre des branches aboutissent aux mêmes fichiers mais laissent un historique différent : la fusion ajoute un commit et garde chaque hachage, le rebase réécrit les changements sur une nouvelle base avec de nouveaux hachages et laisse les anciens sans nom.',
    hi: 'शाखाओं को जोड़ने के दो तरीके एक ही फ़ाइलों तक पहुँचते हैं पर इतिहास अलग छोड़ते हैं: मर्ज एक कमिट जोड़ता है और हर हैश बचाता है, रीबेस बदलावों को नए आधार पर नए हैश के साथ फिर से लिखता है और पुराने कमिट बिना नाम के छोड़ देता है।',
    id: 'Dua cara menggabungkan cabang sampai pada berkas yang sama tetapi meninggalkan riwayat berbeda: merge menambah satu commit dan menjaga setiap hash, rebase menulis ulang perubahan di atas dasar baru dengan hash baru dan meninggalkan yang lama tanpa nama.',
    pt: 'Os dois jeitos de juntar ramos chegam aos mesmos arquivos mas deixam históricos diferentes: o merge acrescenta um commit e mantém cada hash; o rebase reescreve as mudanças sobre uma base nova com hashes novos e deixa os antigos sem nome.',
  },
  algorithm: 'module:rebaseVsMerge',
  projector: 'module:rebaseVsMergeProjector',
  initialData: {
    type: 'rebase-vs-merge',
    stepMs: 1800,
    ways: ['merge', 'rebase-then-merge'],
    aheadLadder: [0, 1, 2],
    way: 1,
    ahead: 1,
    roots: [
      { id: 'A', change: 'init', parents: [] },
      { id: 'B', change: 'add-login', parents: ['A'] },
    ],
    mainNew: [
      { id: 'C', change: 'add-db', parents: ['B'] },
      { id: 'D', change: 'add-cache', parents: ['C'] },
    ],
    feature: [
      { id: 'X', change: 'add-button', parents: ['B'] },
      { id: 'Y', change: 'fix-color', parents: ['X'] },
    ],
    mergeCommit: { id: 'M', change: 'merge-feature' },
    names: { main: 'main', feature: 'feature' },
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'rebase-vs-merge-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'way',
          name: 'way',
          label: {
            en: 'How to join',
            ko: '합치는 길',
            ja: '統合の方法',
            zh: '合并方式',
            ar: 'طريقة الضم',
            es: 'Cómo unir',
            fr: 'Façon de joindre',
            hi: 'जोड़ने का तरीका',
            id: 'Cara menggabung',
            pt: 'Como juntar',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Merge',
                ko: '병합',
                ja: 'マージ',
                zh: '合并',
                ar: 'دمج',
                es: 'Fusionar',
                fr: 'Fusionner',
                hi: 'मर्ज',
                id: 'Merge',
                pt: 'Merge',
              },
            },
            {
              value: 1,
              label: {
                en: 'Rebase, then merge',
                ko: '리베이스 뒤 병합',
                ja: 'リベース後にマージ',
                zh: '变基后合并',
                ar: 'إعادة تأسيس ثم دمج',
                es: 'Rebasar y fusionar',
                fr: 'Rebaser puis fusionner',
                hi: 'रीबेस, फिर मर्ज',
                id: 'Rebase lalu merge',
                pt: 'Rebase e depois merge',
              },
              default: true,
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'ahead',
          name: 'ahead',
          label: {
            en: 'New commits on main',
            ko: 'main 의 새 커밋',
            ja: 'main の新しいコミット',
            zh: 'main 上的新提交',
            ar: 'إيداعات جديدة على main',
            es: 'Commits nuevos en main',
            fr: 'Commits neufs sur main',
            hi: 'main पर नए कमिट',
            id: 'Commit baru di main',
            pt: 'Commits novos na main',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 1, label: '1', default: true },
            { value: 2, label: '2' },
          ],
        },
      ],
      metrics: [
        {
          name: 'new-commits',
          label: {
            en: 'New commits',
            ko: '새 커밋',
            ja: '新しいコミット',
            zh: '新提交',
            ar: 'إيداعات جديدة',
            es: 'Commits nuevos',
            fr: 'Nouveaux commits',
            hi: 'नए कमिट',
            id: 'Commit baru',
            pt: 'Commits novos',
          },
          initial: 0,
        },
        {
          name: 'merge-commits',
          label: {
            en: 'Merge commits',
            ko: '병합 커밋',
            ja: 'マージコミット',
            zh: '合并提交',
            ar: 'إيداعات دمج',
            es: 'Commits de fusión',
            fr: 'Commits de fusion',
            hi: 'मर्ज कमिट',
            id: 'Commit merge',
            pt: 'Commits de merge',
          },
          initial: 0,
        },
        {
          name: 'rehashed',
          label: {
            en: 'Copies with a new hash',
            ko: '해시가 바뀐 복제',
            ja: 'ハッシュが変わった複製',
            zh: '哈希改变的副本',
            ar: 'نسخ بتجزئة جديدة',
            es: 'Copias con hash nuevo',
            fr: 'Copies au hachage neuf',
            hi: 'नए हैश वाली प्रतियाँ',
            id: 'Salinan berhash baru',
            pt: 'Cópias com hash novo',
          },
          initial: 0,
        },
        {
          name: 'unnamed',
          label: {
            en: 'Old commits left unnamed',
            ko: '이름 없이 남은 옛 커밋',
            ja: '名前を失った古いコミット',
            zh: '失去名字的旧提交',
            ar: 'إيداعات قديمة بلا اسم',
            es: 'Commits viejos sin nombre',
            fr: 'Anciens commits sans nom',
            hi: 'बिना नाम के पुराने कमिट',
            id: 'Commit lama tanpa nama',
            pt: 'Commits antigos sem nome',
          },
          initial: 0,
        },
        {
          name: 'label-jump',
          label: {
            en: 'Steps the main label jumped',
            ko: 'main 이름표가 건넌 칸',
            ja: 'main のラベルが飛んだ数',
            zh: 'main 标签跨过的格数',
            ar: 'خانات قفزتها تسمية main',
            es: 'Saltos de la etiqueta main',
            fr: "Sauts de l'étiquette main",
            hi: 'main लेबल की छलाँगें',
            id: 'Lompatan label main',
            pt: 'Saltos do rótulo main',
          },
          initial: 0,
        },
      ],
    },
  },
  messages: {
    'caption.start': {
      en: 'Start · commits: {n}',
      ko: '처음 · 커밋: {n}',
      ja: '開始 · コミット: {n}',
      zh: '开始 · 提交: {n}',
      ar: 'البداية · الإيداعات: {n}',
      es: 'Inicio · commits: {n}',
      fr: 'Départ · commits : {n}',
      hi: 'शुरुआत · कमिट: {n}',
      id: 'Awal · commit: {n}',
      pt: 'Início · commits: {n}',
    },
    'caption.fork': {
      en: 'Parted at {at} · {mainName} side: {m} · {featureName} side: {f}',
      ko: '갈라진 자리: {at} · {mainName} 쪽: {m} · {featureName} 쪽: {f}',
      ja: '分岐点: {at} · {mainName} 側: {m} · {featureName} 側: {f}',
      zh: '分叉点: {at} · {mainName} 侧: {m} · {featureName} 侧: {f}',
      ar: 'نقطة الافتراق: {at} · جهة {mainName}: {m} · جهة {featureName}: {f}',
      es: 'Se separaron en {at} · lado {mainName}: {m} · lado {featureName}: {f}',
      fr: 'Séparation en {at} · côté {mainName} : {m} · côté {featureName} : {f}',
      hi: 'अलग होने की जगह: {at} · {mainName} तरफ़: {m} · {featureName} तरफ़: {f}',
      id: 'Berpisah di {at} · sisi {mainName}: {m} · sisi {featureName}: {f}',
      pt: 'Separaram-se em {at} · lado {mainName}: {m} · lado {featureName}: {f}',
    },
    'caption.forkReplay': {
      en: 'Parted at {at} · {mainName} side: {m} · {featureName} side: {f} · to replay: {list}',
      ko: '갈라진 자리: {at} · {mainName} 쪽: {m} · {featureName} 쪽: {f} · 다시 놓을 커밋: {list}',
      ja: '分岐点: {at} · {mainName} 側: {m} · {featureName} 側: {f} · 積み直すコミット: {list}',
      zh: '分叉点: {at} · {mainName} 侧: {m} · {featureName} 侧: {f} · 要重放的提交: {list}',
      ar: 'نقطة الافتراق: {at} · جهة {mainName}: {m} · جهة {featureName}: {f} · للإعادة: {list}',
      es: 'Se separaron en {at} · lado {mainName}: {m} · lado {featureName}: {f} · a reaplicar: {list}',
      fr: 'Séparation en {at} · côté {mainName} : {m} · côté {featureName} : {f} · à rejouer : {list}',
      hi: 'अलग होने की जगह: {at} · {mainName} तरफ़: {m} · {featureName} तरफ़: {f} · दोबारा रखने हैं: {list}',
      id: 'Berpisah di {at} · sisi {mainName}: {m} · sisi {featureName}: {f} · diputar ulang: {list}',
      pt: 'Separaram-se em {at} · lado {mainName}: {m} · lado {featureName}: {f} · a reaplicar: {list}',
    },
    'caption.forkAncestor': {
      en: 'Parted at {at} = tip of {mainName} · {mainName} is an ancestor of {featureName}',
      ko: '갈라진 자리: {at} = {mainName} 끝 · {mainName} 끝은 {featureName} 끝의 조상',
      ja: '分岐点: {at} = {mainName} の先端 · {mainName} は {featureName} の祖先',
      zh: '分叉点: {at} = {mainName} 的末端 · {mainName} 是 {featureName} 的祖先',
      ar: 'نقطة الافتراق: {at} = طرف {mainName} · {mainName} سلفٌ لـ {featureName}',
      es: 'Se separaron en {at} = punta de {mainName} · {mainName} es ancestro de {featureName}',
      fr: 'Séparation en {at} = pointe de {mainName} · {mainName} est un ancêtre de {featureName}',
      hi: 'अलग होने की जगह: {at} = {mainName} का सिरा · {mainName}, {featureName} का पूर्वज है',
      id: 'Berpisah di {at} = ujung {mainName} · {mainName} leluhur {featureName}',
      pt: 'Separaram-se em {at} = ponta de {mainName} · {mainName} é ancestral de {featureName}',
    },
    'caption.forkNothing': {
      en: 'Parted at {at} = tip of {mainName} · nothing to replay',
      ko: '갈라진 자리: {at} = {mainName} 끝 · 다시 놓을 커밋 없음',
      ja: '分岐点: {at} = {mainName} の先端 · 積み直すコミットなし',
      zh: '分叉点: {at} = {mainName} 的末端 · 没有要重放的提交',
      ar: 'نقطة الافتراق: {at} = طرف {mainName} · لا شيء لإعادته',
      es: 'Se separaron en {at} = punta de {mainName} · nada que reaplicar',
      fr: 'Séparation en {at} = pointe de {mainName} · rien à rejouer',
      hi: 'अलग होने की जगह: {at} = {mainName} का सिरा · दोबारा रखने को कुछ नहीं',
      id: 'Berpisah di {at} = ujung {mainName} · tidak ada yang diputar ulang',
      pt: 'Separaram-se em {at} = ponta de {mainName} · nada a reaplicar',
    },
    'caption.merge': {
      en: 'New commit {id} · parents: {p1}, {p2}',
      ko: '새 커밋 {id} · 부모: {p1}, {p2}',
      ja: '新しいコミット {id} · 親: {p1}, {p2}',
      zh: '新提交 {id} · 父提交: {p1}, {p2}',
      ar: 'إيداع جديد {id} · الأبوان: {p1}، {p2}',
      es: 'Commit nuevo {id} · padres: {p1}, {p2}',
      fr: 'Nouveau commit {id} · parents : {p1}, {p2}',
      hi: 'नया कमिट {id} · पैरेंट: {p1}, {p2}',
      id: 'Commit baru {id} · induk: {p1}, {p2}',
      pt: 'Commit novo {id} · pais: {p1}, {p2}',
    },
    'caption.replay': {
      en: '{from} → {id} · parent: {oldParent} → {parent}',
      ko: '{from} → {id} · 부모: {oldParent} → {parent}',
      ja: '{from} → {id} · 親: {oldParent} → {parent}',
      zh: '{from} → {id} · 父提交: {oldParent} → {parent}',
      ar: '{from} → {id} · الأب: {oldParent} → {parent}',
      es: '{from} → {id} · padre: {oldParent} → {parent}',
      fr: '{from} → {id} · parent : {oldParent} → {parent}',
      hi: '{from} → {id} · पैरेंट: {oldParent} → {parent}',
      id: '{from} → {id} · induk: {oldParent} → {parent}',
      pt: '{from} → {id} · pai: {oldParent} → {parent}',
    },
    'caption.advance': {
      en: '{name}: {from} → {to} · onto the new commit',
      ko: '{name}: {from} → {to} · 새 커밋 위로',
      ja: '{name}: {from} → {to} · 新しいコミットへ',
      zh: '{name}: {from} → {to} · 移到新提交',
      ar: '{name}: {from} → {to} · إلى الإيداع الجديد',
      es: '{name}: {from} → {to} · al commit nuevo',
      fr: '{name} : {from} → {to} · sur le nouveau commit',
      hi: '{name}: {from} → {to} · नए कमिट पर',
      id: '{name}: {from} → {to} · ke commit baru',
      pt: '{name}: {from} → {to} · para o commit novo',
    },
    'caption.fastForward': {
      en: '{name}: {from} → {to} · no new commit',
      ko: '{name}: {from} → {to} · 새 커밋 없음',
      ja: '{name}: {from} → {to} · 新しいコミットなし',
      zh: '{name}: {from} → {to} · 没有新提交',
      ar: '{name}: {from} → {to} · بلا إيداع جديد',
      es: '{name}: {from} → {to} · sin commit nuevo',
      fr: '{name} : {from} → {to} · sans nouveau commit',
      hi: '{name}: {from} → {to} · कोई नया कमिट नहीं',
      id: '{name}: {from} → {to} · tanpa commit baru',
      pt: '{name}: {from} → {to} · sem commit novo',
    },
    'caption.featureMove': {
      en: '{name}: {from} → {to} · left without a name: {list}',
      ko: '{name}: {from} → {to} · 이름 없이 남음: {list}',
      ja: '{name}: {from} → {to} · 名前を失った: {list}',
      zh: '{name}: {from} → {to} · 失去名字: {list}',
      ar: '{name}: {from} → {to} · بقيت بلا اسم: {list}',
      es: '{name}: {from} → {to} · sin nombre: {list}',
      fr: '{name} : {from} → {to} · restés sans nom : {list}',
      hi: '{name}: {from} → {to} · बिना नाम के रह गए: {list}',
      id: '{name}: {from} → {to} · tertinggal tanpa nama: {list}',
      pt: '{name}: {from} → {to} · ficaram sem nome: {list}',
    },
    'label.hashInput': {
      en: 'Hash input · {id}',
      ko: '해시 입력 · {id}',
      ja: 'ハッシュの入力 · {id}',
      zh: '哈希输入 · {id}',
      ar: 'مدخل التجزئة · {id}',
      es: 'Entrada del hash · {id}',
      fr: 'Entrée du hachage · {id}',
      hi: 'हैश इनपुट · {id}',
      id: 'Masukan hash · {id}',
      pt: 'Entrada do hash · {id}',
    },
    'label.init': {
      en: 'first commit',
      ko: '처음',
      ja: '最初',
      zh: '初始',
      ar: 'البداية',
      es: 'inicio',
      fr: 'début',
      hi: 'शुरुआत',
      id: 'awal',
      pt: 'início',
    },
    'label.add-login': {
      en: 'add login',
      ko: '로그인 추가',
      ja: 'ログイン追加',
      zh: '添加登录',
      ar: 'إضافة الدخول',
      es: 'añadir login',
      fr: 'ajout connexion',
      hi: 'लॉगिन जोड़ा',
      id: 'tambah login',
      pt: 'adicionar login',
    },
    'label.add-db': {
      en: 'add DB',
      ko: 'DB 추가',
      ja: 'DB 追加',
      zh: '添加数据库',
      ar: 'إضافة قاعدة بيانات',
      es: 'añadir BD',
      fr: 'ajout BD',
      hi: 'DB जोड़ा',
      id: 'tambah DB',
      pt: 'adicionar BD',
    },
    'label.add-cache': {
      en: 'add cache',
      ko: '캐시 추가',
      ja: 'キャッシュ追加',
      zh: '添加缓存',
      ar: 'إضافة ذاكرة مؤقتة',
      es: 'añadir caché',
      fr: 'ajout cache',
      hi: 'कैश जोड़ा',
      id: 'tambah cache',
      pt: 'adicionar cache',
    },
    'label.add-button': {
      en: 'add button',
      ko: '단추 추가',
      ja: 'ボタン追加',
      zh: '添加按钮',
      ar: 'إضافة زر',
      es: 'añadir botón',
      fr: 'ajout bouton',
      hi: 'बटन जोड़ा',
      id: 'tambah tombol',
      pt: 'adicionar botão',
    },
    'label.fix-color': {
      en: 'fix color',
      ko: '색 고침',
      ja: '色の修正',
      zh: '修正颜色',
      ar: 'إصلاح اللون',
      es: 'corregir color',
      fr: 'correction couleur',
      hi: 'रंग सुधारा',
      id: 'perbaiki warna',
      pt: 'corrigir cor',
    },
    'label.merge-feature': {
      en: 'join feature',
      ko: 'feature 합침',
      ja: 'feature を統合',
      zh: '合入 feature',
      ar: 'ضمّ feature',
      es: 'unir feature',
      fr: 'joindre feature',
      hi: 'feature जोड़ा',
      id: 'gabung feature',
      pt: 'juntar feature',
    },
  },
};
