import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 같은 순간에 두 컴퓨터의 시계를 읽으면 왜 다른 값이 나오고, 맞춰 준 뒤에는 왜 다시 벌어지는가.
 */
export const clocksDriftFacet: FacetJson = {
  id: 'facet:clocksDrift',
  title: {
    en: 'Clocks drift apart',
    ko: '시계는 저마다 어긋난다',
    ja: '時計はそれぞれずれていく',
    zh: '时钟各自漂移',
    ar: 'الساعات تنحرف كلٌّ على حدة',
    es: 'Los relojes se desvían',
    fr: 'Les horloges dérivent',
    hi: 'घड़ियाँ अपने-अपने ढंग से खिसकती हैं',
    id: 'Jam bergeser masing-masing',
    pt: 'Os relógios se desviam',
  },
  description: {
    en: 'Two clocks read the same true time differently, the gap grows every hour, and after syncing with a time server it opens up again at the same slope.',
    ko: '같은 참 시각에 두 시계의 읽음이 다르고, 그 차이는 시간마다 벌어지며, 시간 서버와 맞춘 뒤에도 같은 기울기로 다시 벌어진다.',
    ja: '同じ真の時刻でも二つの時計の読みは異なり、その差は一時間ごとに広がり、時刻サーバーと合わせた後も同じ傾きで再び広がる。',
    zh: '同一真实时刻两只时钟读数不同，差距每小时扩大，与时间服务器同步后又以相同斜率再次拉开。',
    ar: 'تقرأ ساعتان الوقت الحقيقي نفسه بشكل مختلف، ويتسع الفرق كل ساعة، وبعد المزامنة مع خادم الوقت ينفتح من جديد بالميل نفسه.',
    es: 'Dos relojes leen distinto el mismo instante real, la diferencia crece cada hora y, tras sincronizar con un servidor de hora, vuelve a abrirse con la misma pendiente.',
    fr: 'Deux horloges lisent différemment le même instant réel, l’écart grandit chaque heure et, après synchronisation avec un serveur de temps, se rouvre avec la même pente.',
    hi: 'एक ही वास्तविक समय पर दो घड़ियाँ अलग पढ़ती हैं, अंतर हर घंटे बढ़ता है, और समय सर्वर से मिलाने के बाद भी उसी ढलान से फिर खुलता है।',
    id: 'Dua jam membaca waktu nyata yang sama secara berbeda, selisihnya melebar tiap jam, dan setelah disinkronkan dengan server waktu melebar lagi dengan kemiringan yang sama.',
    pt: 'Dois relógios leem de forma diferente o mesmo instante real, a diferença cresce a cada hora e, após sincronizar com um servidor de horário, volta a abrir com a mesma inclinação.',
  },
  algorithm: 'module:clocksDrift',
  scene: 'module:clocksDriftScene',
  initialData: {
    type: 'clocks-drift',
    stepMs: 1400,
    server: 'S',
    holdMs: 0,
    endHour: 5,
    clocks: [
      { id: 'A', ppm: 40, offsetMs0: 0 },
      { id: 'B', ppm: -25, offsetMs0: 0 },
    ],
    syncs: [
      { clock: 'A', atHour: 3, outMs: 30, backMs: 10 },
      { clock: 'B', atHour: 3, outMs: 12, backMs: 20 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.hour': {
      en: 'True time: {h} h',
      ko: '참 시각: {h}시간',
      ja: '真の時刻: {h} 時間',
      zh: '真实时间：{h} 小时',
      ar: 'الوقت الحقيقي: {h} س',
      es: 'Hora real: {h} h',
      fr: 'Temps réel : {h} h',
      hi: 'वास्तविक समय: {h} घंटे',
      id: 'Waktu nyata: {h} jam',
      pt: 'Tempo real: {h} h',
    },
    'caption.gap': {
      en: 'Gap between the clocks: {g} ms',
      ko: '두 시계 사이 벌어짐: {g} ms',
      ja: '二つの時計の開き: {g} ms',
      zh: '两只时钟之间的差距：{g} ms',
      ar: 'الفرق بين الساعتين: {g} ms',
      es: 'Diferencia entre los relojes: {g} ms',
      fr: 'Écart entre les horloges : {g} ms',
      hi: 'दोनों घड़ियों के बीच अंतर: {g} ms',
      id: 'Selisih antara kedua jam: {g} ms',
      pt: 'Diferença entre os relógios: {g} ms',
    },
    'caption.sync': {
      en: 'Sync {name} ↔ {server}: correction θ {theta} ms',
      ko: '맞추기 · {name} ↔ {server}: 보정 θ {theta} ms',
      ja: '同期 · {name} ↔ {server}: 補正 θ {theta} ms',
      zh: '同步 · {name} ↔ {server}：校正 θ {theta} ms',
      ar: 'مزامنة {name} ↔ {server}: التصحيح θ {theta} ms',
      es: 'Sincronizar {name} ↔ {server}: corrección θ {theta} ms',
      fr: 'Synchro {name} ↔ {server} : correction θ {theta} ms',
      hi: 'मिलान {name} ↔ {server}: सुधार θ {theta} ms',
      id: 'Sinkron {name} ↔ {server}: koreksi θ {theta} ms',
      pt: 'Sincronizar {name} ↔ {server}: correção θ {theta} ms',
    },
    'caption.syncOffset': {
      en: 'Offset of {name}: {before} → {after} ms',
      ko: '{name} 어긋남: {before} → {after} ms',
      ja: '{name} のずれ: {before} → {after} ms',
      zh: '{name} 的偏差：{before} → {after} ms',
      ar: 'انحراف {name}: {before} → {after} ms',
      es: 'Desfase de {name}: {before} → {after} ms',
      fr: 'Décalage de {name} : {before} → {after} ms',
      hi: '{name} का विचलन: {before} → {after} ms',
      id: 'Selisih {name}: {before} → {after} ms',
      pt: 'Desvio de {name}: {before} → {after} ms',
    },
    'label.A': {
      en: 'Clock A',
      ko: '시계 A',
      ja: '時計 A',
      zh: '时钟 A',
      ar: 'الساعة A',
      es: 'Reloj A',
      fr: 'Horloge A',
      hi: 'घड़ी A',
      id: 'Jam A',
      pt: 'Relógio A',
    },
    'label.B': {
      en: 'Clock B',
      ko: '시계 B',
      ja: '時計 B',
      zh: '时钟 B',
      ar: 'الساعة B',
      es: 'Reloj B',
      fr: 'Horloge B',
      hi: 'घड़ी B',
      id: 'Jam B',
      pt: 'Relógio B',
    },
    'label.S': {
      en: 'Time server S',
      ko: '시간 서버 S',
      ja: '時刻サーバー S',
      zh: '时间服务器 S',
      ar: 'خادم الوقت S',
      es: 'Servidor de hora S',
      fr: 'Serveur de temps S',
      hi: 'समय सर्वर S',
      id: 'Server waktu S',
      pt: 'Servidor de horário S',
    },
    'label.rate': {
      en: 'Rate: {ppm} ppm',
      ko: '빠르기: {ppm} ppm',
      ja: '速さ: {ppm} ppm',
      zh: '快慢：{ppm} ppm',
      ar: 'المعدل: {ppm} ppm',
      es: 'Ritmo: {ppm} ppm',
      fr: 'Cadence : {ppm} ppm',
      hi: 'दर: {ppm} ppm',
      id: 'Laju: {ppm} ppm',
      pt: 'Ritmo: {ppm} ppm',
    },
    'label.theta': {
      en: 'θ {theta} ms',
      ko: 'θ {theta} ms',
      ja: 'θ {theta} ms',
      zh: 'θ {theta} ms',
      ar: 'θ {theta} ms',
      es: 'θ {theta} ms',
      fr: 'θ {theta} ms',
      hi: 'θ {theta} ms',
      id: 'θ {theta} ms',
      pt: 'θ {theta} ms',
    },
    'label.gap': {
      en: 'Gap {g} ms',
      ko: '벌어짐 {g} ms',
      ja: '開き {g} ms',
      zh: '差距 {g} ms',
      ar: 'الفرق {g} ms',
      es: 'Diferencia {g} ms',
      fr: 'Écart {g} ms',
      hi: 'अंतर {g} ms',
      id: 'Selisih {g} ms',
      pt: 'Diferença {g} ms',
    },
    'label.offset': {
      en: '{name}: {ms} ms',
      ko: '{name}: {ms} ms',
      ja: '{name}: {ms} ms',
      zh: '{name}：{ms} ms',
      ar: '{name}: {ms} ms',
      es: '{name}: {ms} ms',
      fr: '{name} : {ms} ms',
      hi: '{name}: {ms} ms',
      id: '{name}: {ms} ms',
      pt: '{name}: {ms} ms',
    },
    'label.zoom': {
      en: 'Left after sync · scale ±{r} ms',
      ko: '맞춘 뒤 남은 어긋남 · 눈금 ±{r} ms',
      ja: '同期後に残るずれ · 目盛り ±{r} ms',
      zh: '同步后剩余偏差 · 刻度 ±{r} ms',
      ar: 'المتبقي بعد المزامنة · المقياس ±{r} ms',
      es: 'Resto tras sincronizar · escala ±{r} ms',
      fr: 'Reste après synchro · échelle ±{r} ms',
      hi: 'मिलान के बाद शेष · पैमाना ±{r} ms',
      id: 'Sisa setelah sinkron · skala ±{r} ms',
      pt: 'Resto após sincronizar · escala ±{r} ms',
    },
    'axis.offset': {
      en: 'Offset (ms)',
      ko: '어긋남 (ms)',
      ja: 'ずれ (ms)',
      zh: '偏差 (ms)',
      ar: 'الانحراف (ms)',
      es: 'Desfase (ms)',
      fr: 'Décalage (ms)',
      hi: 'विचलन (ms)',
      id: 'Selisih (ms)',
      pt: 'Desvio (ms)',
    },
    'axis.hour': {
      en: '{h} h',
      ko: '{h}시간',
      ja: '{h} 時間',
      zh: '{h} 小时',
      ar: '{h} س',
      es: '{h} h',
      fr: '{h} h',
      hi: '{h} घं',
      id: '{h} j',
      pt: '{h} h',
    },
    'axis.true': {
      en: 'True time',
      ko: '참 시각',
      ja: '真の時刻',
      zh: '真实时间',
      ar: 'الوقت الحقيقي',
      es: 'Hora real',
      fr: 'Temps réel',
      hi: 'वास्तविक समय',
      id: 'Waktu nyata',
      pt: 'Tempo real',
    },
  },
  blocks: {
    stage: { type: 'clocks-drift-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
