import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: Paxos 수락자의 약속은 무엇을 막는가.
 *
 * 더 큰 번호에 약속한 수락자는 작은 번호의 제안을 받아 주지 않는다. 두 제안자가 번호표를 들고
 * 수락자에게 약속을 받으러 가고, 더 큰 번호의 약속이 먼저 박힌 수락자에게서 작은 번호의 값이 튕겨 나온다.
 */
export const proposeAndPromiseFacet: FacetJson = {
  id: 'facet:proposeAndPromise',
  title: {
    en: 'Propose and promise',
    ko: '제안과 약속',
    ja: '提案と約束',
    zh: '提议与承诺',
    ar: 'الاقتراح والوعد',
    es: 'Proponer y prometer',
    fr: 'Proposer et promettre',
    hi: 'प्रस्ताव और वादा',
    id: 'Usulan dan janji',
    pt: 'Propor e prometer',
  },
  description: {
    en: 'An acceptor that promised a larger number refuses a proposal with a smaller one.',
    ko: '더 큰 번호에 약속한 수락자는 작은 번호의 제안을 받아 주지 않는다.',
    ja: 'より大きな番号に約束したアクセプタは、小さな番号の提案を受け入れない。',
    zh: '已向更大编号作出承诺的接受者，不会接受编号更小的提议。',
    ar: 'المُتقبِّل الذي وعد برقم أكبر يرفض اقتراحًا برقم أصغر.',
    es: 'Un aceptador que prometió un número mayor rechaza una propuesta con un número menor.',
    fr: 'Un accepteur qui a promis un numéro plus grand refuse une proposition au numéro plus petit.',
    hi: 'जिस स्वीकारकर्ता ने बड़ी संख्या का वादा किया है, वह छोटी संख्या वाले प्रस्ताव को नहीं मानता।',
    id: 'Akseptor yang sudah berjanji pada nomor lebih besar menolak usulan bernomor lebih kecil.',
    pt: 'Um aceitador que prometeu um número maior recusa uma proposta com número menor.',
  },
  algorithm: 'module:proposeAndPromise',
  scene: 'module:proposeAndPromiseScene',
  initialData: {
    type: 'propose-and-promise',
    stepMs: 1200,
    acceptors: ['A1', 'A2', 'A3'],
    proposers: [
      { id: 'P1', n: 1, v: 7 },
      { id: 'P2', n: 2, v: 9 },
    ],
    deliveries: [
      { from: 'P1', kind: 'prepare', to: 'A1' },
      { from: 'P1', kind: 'prepare', to: 'A2' },
      { from: 'P2', kind: 'prepare', to: 'A2' },
      { from: 'P2', kind: 'prepare', to: 'A3' },
      { from: 'P1', kind: 'accept', to: 'A1' },
      { from: 'P1', kind: 'accept', to: 'A2' },
      { from: 'P2', kind: 'accept', to: 'A2' },
      { from: 'P2', kind: 'accept', to: 'A3' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'No acceptor has promised anything yet.',
      ko: '아직 약속한 수락자가 없다.',
      ja: 'まだどのアクセプタも約束していない。',
      zh: '还没有接受者作出承诺。',
      ar: 'لم يَعِد أي مُتقبِّل بشيء بعد.',
      es: 'Ningún aceptador ha prometido nada todavía.',
      fr: 'Aucun accepteur n’a encore rien promis.',
      hi: 'अभी तक किसी स्वीकारकर्ता ने वादा नहीं किया है।',
      id: 'Belum ada akseptor yang berjanji.',
      pt: 'Nenhum aceitador prometeu nada ainda.',
    },
    'caption.promise': {
      en: '{a} promises number {n} to {p}.',
      ko: '{a}: 번호 {n} 에 약속한다 ({p} 의 prepare).',
      ja: '{a}: 番号 {n} に約束する ({p} の prepare)。',
      zh: '{a}：向 {p} 承诺编号 {n}。',
      ar: '{a} يَعِد {p} بالرقم {n}.',
      es: '{a} promete el número {n} a {p}.',
      fr: '{a} promet le numéro {n} à {p}.',
      hi: '{a}: {p} को संख्या {n} का वादा।',
      id: '{a} berjanji pada nomor {n} dari {p}.',
      pt: '{a} promete o número {n} a {p}.',
    },
    'caption.promiseUp': {
      en: '{a} raises its promise: number {was} → number {n} ({p}).',
      ko: '{a}: 약속을 올린다 — 번호 {was} → 번호 {n} ({p}).',
      ja: '{a}: 約束を引き上げる — 番号 {was} → 番号 {n} ({p})。',
      zh: '{a}：承诺提高 — 编号 {was} → 编号 {n}（{p}）。',
      ar: '{a} يرفع وعده: الرقم {was} ← الرقم {n} ({p}).',
      es: '{a} sube su promesa: número {was} → número {n} ({p}).',
      fr: '{a} relève sa promesse : numéro {was} → numéro {n} ({p}).',
      hi: '{a} वादा बढ़ाता है: संख्या {was} → संख्या {n} ({p})।',
      id: '{a} menaikkan janji: nomor {was} → nomor {n} ({p}).',
      pt: '{a} eleva a promessa: número {was} → número {n} ({p}).',
    },
    'caption.promises': {
      en: 'Promises for {p}: {k} / {total}',
      ko: '{p} 의 받은 약속: {k} / {total}',
      ja: '{p} の約束: {k} / {total}',
      zh: '{p} 获得的承诺：{k} / {total}',
      ar: 'وعود {p}: {k} / {total}',
      es: 'Promesas para {p}: {k} / {total}',
      fr: 'Promesses pour {p} : {k} / {total}',
      hi: '{p} के वादे: {k} / {total}',
      id: 'Janji untuk {p}: {k} / {total}',
      pt: 'Promessas para {p}: {k} / {total}',
    },
    'caption.sendOwn': {
      en: 'Promises for {p}: {k} / {total}, a majority. Value to send: {v}, its own.',
      ko: '{p} 의 받은 약속: {k} / {total}, 과반. 보낼 값: {v} (제 값).',
      ja: '{p} の約束: {k} / {total}、過半数。送る値: {v} (自分の値)。',
      zh: '{p} 获得的承诺：{k} / {total}，过半。要发送的值：{v}（自己的值）。',
      ar: 'وعود {p}: {k} / {total}، أغلبية. القيمة المُرسَلة: {v}، قيمته هو.',
      es: 'Promesas para {p}: {k} / {total}, mayoría. Valor a enviar: {v}, el suyo.',
      fr: 'Promesses pour {p} : {k} / {total}, une majorité. Valeur à envoyer : {v}, la sienne.',
      hi: '{p} के वादे: {k} / {total}, बहुमत। भेजा जाने वाला मान: {v}, अपना।',
      id: 'Janji untuk {p}: {k} / {total}, mayoritas. Nilai yang dikirim: {v}, miliknya sendiri.',
      pt: 'Promessas para {p}: {k} / {total}, maioria. Valor a enviar: {v}, o próprio.',
    },
    'caption.sendCarried': {
      en: 'Promises for {p}: {k} / {total}, a majority. Value to send: {v}, from number {m}.',
      ko: '{p} 의 받은 약속: {k} / {total}, 과반. 보낼 값: {v} (이어받은 번호 {m}).',
      ja: '{p} の約束: {k} / {total}、過半数。送る値: {v} (番号 {m} から引き継ぐ)。',
      zh: '{p} 获得的承诺：{k} / {total}，过半。要发送的值：{v}（沿用编号 {m}）。',
      ar: 'وعود {p}: {k} / {total}، أغلبية. القيمة المُرسَلة: {v}، من الرقم {m}.',
      es: 'Promesas para {p}: {k} / {total}, mayoría. Valor a enviar: {v}, del número {m}.',
      fr: 'Promesses pour {p} : {k} / {total}, une majorité. Valeur à envoyer : {v}, reprise du numéro {m}.',
      hi: '{p} के वादे: {k} / {total}, बहुमत। भेजा जाने वाला मान: {v}, संख्या {m} से।',
      id: 'Janji untuk {p}: {k} / {total}, mayoritas. Nilai yang dikirim: {v}, dari nomor {m}.',
      pt: 'Promessas para {p}: {k} / {total}, maioria. Valor a enviar: {v}, do número {m}.',
    },
    'caption.prepareRefused': {
      en: '{a} refuses number {n}: it already promised number {m}.',
      ko: '{a}: 번호 {n} 거절 — 이미 번호 {m} 에 약속했다.',
      ja: '{a}: 番号 {n} を拒否 — すでに番号 {m} に約束した。',
      zh: '{a}：拒绝编号 {n} — 已承诺编号 {m}。',
      ar: '{a} يرفض الرقم {n}: وعد بالفعل بالرقم {m}.',
      es: '{a} rechaza el número {n}: ya prometió el número {m}.',
      fr: '{a} refuse le numéro {n} : il a déjà promis le numéro {m}.',
      hi: '{a} संख्या {n} ठुकराता है: पहले ही संख्या {m} का वादा किया है।',
      id: '{a} menolak nomor {n}: sudah berjanji pada nomor {m}.',
      pt: '{a} recusa o número {n}: já prometeu o número {m}.',
    },
    'caption.accepted': {
      en: '{a} accepts {pair}.',
      ko: '{a}: {pair} 받아들임.',
      ja: '{a}: {pair} を受け入れる。',
      zh: '{a}：接受 {pair}。',
      ar: '{a} يقبل {pair}.',
      es: '{a} acepta {pair}.',
      fr: '{a} accepte {pair}.',
      hi: '{a} {pair} स्वीकार करता है।',
      id: '{a} menerima {pair}.',
      pt: '{a} aceita {pair}.',
    },
    'caption.accepts': {
      en: 'Accepts for {p}: {k} / {total}',
      ko: '{p} 의 받은 수락: {k} / {total}',
      ja: '{p} の受理: {k} / {total}',
      zh: '{p} 获得的接受：{k} / {total}',
      ar: 'قبولات {p}: {k} / {total}',
      es: 'Aceptaciones para {p}: {k} / {total}',
      fr: 'Acceptations pour {p} : {k} / {total}',
      hi: '{p} की स्वीकृतियाँ: {k} / {total}',
      id: 'Penerimaan untuk {p}: {k} / {total}',
      pt: 'Aceitações para {p}: {k} / {total}',
    },
    'caption.chosen': {
      en: 'Accepts for {p}: {k} / {total}, a majority. Chosen value: {v}.',
      ko: '{p} 의 받은 수락: {k} / {total}, 과반. 정해진 값: {v}.',
      ja: '{p} の受理: {k} / {total}、過半数。決まった値: {v}。',
      zh: '{p} 获得的接受：{k} / {total}，过半。选定的值：{v}。',
      ar: 'قبولات {p}: {k} / {total}، أغلبية. القيمة المختارة: {v}.',
      es: 'Aceptaciones para {p}: {k} / {total}, mayoría. Valor elegido: {v}.',
      fr: 'Acceptations pour {p} : {k} / {total}, une majorité. Valeur choisie : {v}.',
      hi: '{p} की स्वीकृतियाँ: {k} / {total}, बहुमत। चुना गया मान: {v}।',
      id: 'Penerimaan untuk {p}: {k} / {total}, mayoritas. Nilai terpilih: {v}.',
      pt: 'Aceitações para {p}: {k} / {total}, maioria. Valor escolhido: {v}.',
    },
    'caption.acceptRefused': {
      en: '{a} refuses {pair}: it already promised number {m}.',
      ko: '{a}: {pair} 거절 — 이미 번호 {m} 에 약속했다.',
      ja: '{a}: {pair} を拒否 — すでに番号 {m} に約束した。',
      zh: '{a}：拒绝 {pair} — 已承诺编号 {m}。',
      ar: '{a} يرفض {pair}: وعد بالفعل بالرقم {m}.',
      es: '{a} rechaza {pair}: ya prometió el número {m}.',
      fr: '{a} refuse {pair} : il a déjà promis le numéro {m}.',
      hi: '{a} {pair} ठुकराता है: पहले ही संख्या {m} का वादा किया है।',
      id: '{a} menolak {pair}: sudah berjanji pada nomor {m}.',
      pt: '{a} recusa {pair}: já prometeu o número {m}.',
    },
    'caption.doneNone': {
      en: 'No value was chosen.',
      ko: '정해진 값이 없다.',
      ja: '決まった値はない。',
      zh: '没有选定的值。',
      ar: 'لم تُختَر أي قيمة.',
      es: 'No se eligió ningún valor.',
      fr: 'Aucune valeur n’a été choisie.',
      hi: 'कोई मान नहीं चुना गया।',
      id: 'Tidak ada nilai yang terpilih.',
      pt: 'Nenhum valor foi escolhido.',
    },
    'caption.done': {
      en: 'Chosen {pair}: accepted by {k} / {total}.',
      ko: '정해진 쌍 {pair}: 받아들인 수락자 {k} / {total}.',
      ja: '決まった組 {pair}: 受け入れたアクセプタ {k} / {total}。',
      zh: '选定的一对 {pair}：接受者 {k} / {total}。',
      ar: 'الزوج المختار {pair}: قبله {k} / {total}.',
      es: 'Par elegido {pair}: aceptado por {k} / {total}.',
      fr: 'Paire choisie {pair} : acceptée par {k} / {total}.',
      hi: 'चुना गया जोड़ा {pair}: स्वीकार करने वाले {k} / {total}।',
      id: 'Pasangan terpilih {pair}: diterima oleh {k} / {total}.',
      pt: 'Par escolhido {pair}: aceito por {k} / {total}.',
    },
    'caption.stray': {
      en: '{pair} left on {a}: accepted by {k} / {total}. Majority: {m}.',
      ko: '{a} 에 남은 {pair}: 받아들인 수락자 {k} / {total}. 과반: {m}.',
      ja: '{a} に残る {pair}: 受け入れたアクセプタ {k} / {total}。過半数: {m}。',
      zh: '留在 {a} 的 {pair}：接受者 {k} / {total}。过半：{m}。',
      ar: '{pair} باقٍ على {a}: قبله {k} / {total}. الأغلبية: {m}.',
      es: '{pair} queda en {a}: aceptado por {k} / {total}. Mayoría: {m}.',
      fr: '{pair} reste sur {a} : accepté par {k} / {total}. Majorité : {m}.',
      hi: '{a} पर बचा {pair}: स्वीकार करने वाले {k} / {total}। बहुमत: {m}।',
      id: '{pair} tersisa di {a}: diterima oleh {k} / {total}. Mayoritas: {m}.',
      pt: '{pair} fica em {a}: aceito por {k} / {total}. Maioria: {m}.',
    },
    'label.none': {
      en: '—',
      ko: '—',
      ja: '—',
      zh: '—',
      ar: '—',
      es: '—',
      fr: '—',
      hi: '—',
      id: '—',
      pt: '—',
    },
    'label.proposer': {
      en: 'Proposer',
      ko: '제안자',
      ja: 'プロポーザ',
      zh: '提议者',
      ar: 'المُقترِح',
      es: 'Proponente',
      fr: 'Proposeur',
      hi: 'प्रस्तावक',
      id: 'Pengusul',
      pt: 'Proponente',
    },
    'label.acceptors': {
      en: 'Acceptors',
      ko: '수락자',
      ja: 'アクセプタ',
      zh: '接受者',
      ar: 'المُتقبِّلون',
      es: 'Aceptadores',
      fr: 'Accepteurs',
      hi: 'स्वीकारकर्ता',
      id: 'Akseptor',
      pt: 'Aceitadores',
    },
    'label.value': {
      en: 'Value {v}',
      ko: '값 {v}',
      ja: '値 {v}',
      zh: '值 {v}',
      ar: 'القيمة {v}',
      es: 'Valor {v}',
      fr: 'Valeur {v}',
      hi: 'मान {v}',
      id: 'Nilai {v}',
      pt: 'Valor {v}',
    },
    'label.promises': {
      en: 'Promises',
      ko: '받은 약속',
      ja: '約束',
      zh: '承诺',
      ar: 'الوعود',
      es: 'Promesas',
      fr: 'Promesses',
      hi: 'वादे',
      id: 'Janji',
      pt: 'Promessas',
    },
    'label.accepts': {
      en: 'Accepts',
      ko: '받은 수락',
      ja: '受理',
      zh: '接受',
      ar: 'القبولات',
      es: 'Aceptaciones',
      fr: 'Acceptations',
      hi: 'स्वीकृतियाँ',
      id: 'Penerimaan',
      pt: 'Aceitações',
    },
    'label.send': {
      en: 'Sends {v}',
      ko: '보낼 값 {v}',
      ja: '送る値 {v}',
      zh: '发送值 {v}',
      ar: 'يُرسل {v}',
      es: 'Envía {v}',
      fr: 'Envoie {v}',
      hi: 'भेजेगा {v}',
      id: 'Mengirim {v}',
      pt: 'Envia {v}',
    },
    'label.sendCarried': {
      en: 'Sends {v} (from number {m})',
      ko: '보낼 값 {v} (이어받은 번호 {m})',
      ja: '送る値 {v} (番号 {m} から)',
      zh: '发送值 {v}（来自编号 {m}）',
      ar: 'يُرسل {v} (من الرقم {m})',
      es: 'Envía {v} (del número {m})',
      fr: 'Envoie {v} (du numéro {m})',
      hi: 'भेजेगा {v} (संख्या {m} से)',
      id: 'Mengirim {v} (dari nomor {m})',
      pt: 'Envia {v} (do número {m})',
    },
    'label.promised': {
      en: 'Promised',
      ko: '약속한 번호',
      ja: '約束番号',
      zh: '已承诺',
      ar: 'الموعود',
      es: 'Prometido',
      fr: 'Promis',
      hi: 'वादा',
      id: 'Dijanjikan',
      pt: 'Prometido',
    },
    'label.accepted': {
      en: 'Accepted',
      ko: '받아들인 것',
      ja: '受け入れ済み',
      zh: '已接受',
      ar: 'المقبول',
      es: 'Aceptado',
      fr: 'Accepté',
      hi: 'स्वीकृत',
      id: 'Diterima',
      pt: 'Aceito',
    },
    'label.refused': {
      en: 'Refused',
      ko: '거절',
      ja: '拒否',
      zh: '拒绝',
      ar: 'مرفوض',
      es: 'Rechazado',
      fr: 'Refusé',
      hi: 'अस्वीकृत',
      id: 'Ditolak',
      pt: 'Recusado',
    },
    'label.chosen': {
      en: 'Chosen value: {v}',
      ko: '정해진 값: {v}',
      ja: '決まった値: {v}',
      zh: '选定的值：{v}',
      ar: 'القيمة المختارة: {v}',
      es: 'Valor elegido: {v}',
      fr: 'Valeur choisie : {v}',
      hi: 'चुना गया मान: {v}',
      id: 'Nilai terpilih: {v}',
      pt: 'Valor escolhido: {v}',
    },
  },
  blocks: {
    stage: { type: 'propose-and-promise-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
