import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { FirewallData } from './algorithm.js';

/**
 * 1차 데이터 — 규칙 넷(원래 차례) · 패킷 여섯 · 옮기는 줄 · 자리 사다리.
 * 주소 · 포트 · 프로토콜 · `any` · 규칙 id · 패킷 id 는 번역하지 않는 자료다. 동작은 식별자(`allow` · `deny`)이고
 * 표시 이름은 `messages` 의 `label.*` 에 있다. 깊이 · 판정 · 죽은 줄은 알고리즘이 셈한다.
 */
const initialData: FirewallData = {
  type: 'firewall',
  stepMs: 1100,
  rules: [
    { id: 'R1', action: 'allow', proto: 'tcp', src: 'any', dst: '10.0.0.0/24', port: 443 },
    { id: 'R2', action: 'deny', proto: 'tcp', src: '203.0.113.0/24', dst: 'any', port: 'any' },
    { id: 'R3', action: 'allow', proto: 'tcp', src: 'any', dst: '10.0.0.5/32', port: 22 },
    { id: 'R4', action: 'deny', proto: 'any', src: 'any', dst: 'any', port: 'any' },
  ],
  packets: [
    { id: 'p1', proto: 'tcp', src: '203.0.113.9', dst: '10.0.0.5', port: 443 },
    { id: 'p2', proto: 'tcp', src: '203.0.113.9', dst: '10.0.0.5', port: 22 },
    { id: 'p3', proto: 'tcp', src: '198.51.100.4', dst: '10.0.0.5', port: 22 },
    { id: 'p4', proto: 'tcp', src: '198.51.100.4', dst: '10.0.0.9', port: 25 },
    { id: 'p5', proto: 'tcp', src: '198.51.100.4', dst: '10.0.0.7', port: 443 },
    { id: 'p6', proto: 'tcp', src: '203.0.113.50', dst: '10.0.0.7', port: 443 },
  ],
  movingRule: 'R2',
  positionLadder: [1, 2, 3, 4],
  position: 2,
};

export const firewallFacet: FacetJson = {
  id: 'facet:firewall',
  title: {
    en: 'Firewall',
    ko: '방화벽',
    ja: 'ファイアウォール',
    zh: '防火墙',
    ar: 'جدار الحماية',
    es: 'Cortafuegos',
    fr: 'Pare-feu',
    hi: 'फ़ायरवॉल',
    id: 'Firewall',
    pt: 'Firewall',
  },
  description: {
    en: 'A firewall stops at the first rule that matches, so where a rule sits decides the verdict. Move the deny rule R2 through positions 1–4 and watch six packets flip.',
    ko: '방화벽은 처음 맞은 규칙에서 멈추므로 규칙의 자리가 판정을 정한다. 차단 줄 R2 를 1–4 번째 자리로 옮기며 패킷 여섯의 판정이 뒤집히는 것을 본다.',
    ja: 'ファイアウォールは最初に一致した規則で止まるため、規則の位置が判定を決める。拒否規則 R2 を 1–4 番目に動かし、6 つのパケットの判定が変わるのを見る。',
    zh: '防火墙在第一条匹配的规则处停下，因此规则的位置决定判定。把拒绝规则 R2 移到第 1–4 位，观察六个数据包的判定如何翻转。',
    ar: 'يتوقف جدار الحماية عند أول قاعدة تطابق، لذا يحدد موضع القاعدة الحكم. حرّك قاعدة المنع R2 بين المواضع 1–4 وراقب أحكام ست حزم تنقلب.',
    es: 'Un cortafuegos se detiene en la primera regla que coincide, así que la posición de una regla decide el veredicto. Mueve la regla de denegación R2 por las posiciones 1–4 y observa cómo cambian seis paquetes.',
    fr: "Un pare-feu s'arrête à la première règle qui correspond : la position d'une règle décide du verdict. Déplacez la règle de refus R2 aux positions 1–4 et regardez six paquets basculer.",
    hi: 'फ़ायरवॉल पहले मेल खाने वाले नियम पर रुकता है, इसलिए नियम का स्थान निर्णय तय करता है। रोकने वाले नियम R2 को स्थान 1–4 पर ले जाकर छह पैकेटों के निर्णय पलटते देखें।',
    id: 'Firewall berhenti pada aturan pertama yang cocok, jadi posisi aturan menentukan putusan. Pindahkan aturan tolak R2 ke posisi 1–4 dan lihat putusan enam paket berbalik.',
    pt: 'Um firewall para na primeira regra que casa, então a posição de uma regra decide o veredito. Mova a regra de negação R2 pelas posições 1–4 e veja seis pacotes mudarem.',
  },
  algorithm: 'module:firewall',
  projector: 'module:firewallProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'firewall-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'position',
          name: 'position',
          label: {
            en: 'R2 position',
            ko: 'R2 자리',
            ja: 'R2 の位置',
            zh: 'R2 的位置',
            ar: 'موضع R2',
            es: 'Posición de R2',
            fr: 'Position de R2',
            hi: 'R2 का स्थान',
            id: 'Posisi R2',
            pt: 'Posição de R2',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2', default: true },
            { value: 3, label: '3' },
            { value: 4, label: '4' },
          ],
        },
      ],
      metrics: [
        {
          name: 'allowed',
          label: {
            en: 'Allowed',
            ko: '허용',
            ja: '許可',
            zh: '允许',
            ar: 'مسموح',
            es: 'Permitidos',
            fr: 'Admis',
            hi: 'अनुमत',
            id: 'Diizinkan',
            pt: 'Permitidos',
          },
          initial: 0,
        },
        {
          name: 'denied',
          label: {
            en: 'Denied',
            ko: '차단',
            ja: '拒否',
            zh: '拒绝',
            ar: 'ممنوع',
            es: 'Denegados',
            fr: 'Refusés',
            hi: 'रोके गए',
            id: 'Ditolak',
            pt: 'Negados',
          },
          initial: 0,
        },
        {
          name: 'rule-checks',
          label: {
            en: 'Rules checked',
            ko: '맞춰 본 줄',
            ja: '照合した規則',
            zh: '检查的规则',
            ar: 'القواعد المفحوصة',
            es: 'Reglas revisadas',
            fr: 'Règles testées',
            hi: 'जाँचे गए नियम',
            id: 'Aturan diperiksa',
            pt: 'Regras verificadas',
          },
          initial: 0,
        },
        {
          name: 'dead-rules',
          label: {
            en: 'Dead rules',
            ko: '죽은 줄',
            ja: '死んだ規則',
            zh: '死规则',
            ar: 'قواعد ميتة',
            es: 'Reglas muertas',
            fr: 'Règles mortes',
            hi: 'मृत नियम',
            id: 'Aturan mati',
            pt: 'Regras mortas',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:firewall-imperative',
      label: {
        en: 'First-match filter',
        ko: '첫 일치 거르기',
        ja: '最初の一致で判定',
        zh: '首次匹配过滤',
        ar: 'التصفية بأول تطابق',
        es: 'Filtro de primera coincidencia',
        fr: 'Filtre à première correspondance',
        hi: 'पहले मेल से छँटाई',
        id: 'Penyaring kecocokan pertama',
        pt: 'Filtro por primeira correspondência',
      },
    },
  },
  messages: {
    'head.slot': {
      en: 'Pos',
      ko: '자리',
      ja: '位置',
      zh: '位置',
      ar: 'الموضع',
      es: 'Pos.',
      fr: 'Pos.',
      hi: 'स्थान',
      id: 'Posisi',
      pt: 'Pos.',
    },
    'head.rule': {
      en: 'Rule',
      ko: '규칙',
      ja: '規則',
      zh: '规则',
      ar: 'القاعدة',
      es: 'Regla',
      fr: 'Règle',
      hi: 'नियम',
      id: 'Aturan',
      pt: 'Regra',
    },
    'head.action': {
      en: 'Action',
      ko: '동작',
      ja: '動作',
      zh: '动作',
      ar: 'الإجراء',
      es: 'Acción',
      fr: 'Action',
      hi: 'क्रिया',
      id: 'Aksi',
      pt: 'Ação',
    },
    'head.proto': {
      en: 'Proto',
      ko: '프로토콜',
      ja: 'プロトコル',
      zh: '协议',
      ar: 'البروتوكول',
      es: 'Proto',
      fr: 'Proto',
      hi: 'प्रोटोकॉल',
      id: 'Proto',
      pt: 'Proto',
    },
    'head.src': {
      en: 'Source',
      ko: '보낸 주소',
      ja: '送信元',
      zh: '源地址',
      ar: 'المصدر',
      es: 'Origen',
      fr: 'Source',
      hi: 'स्रोत',
      id: 'Sumber',
      pt: 'Origem',
    },
    'head.dst': {
      en: 'Destination',
      ko: '받는 주소',
      ja: '宛先',
      zh: '目的地址',
      ar: 'الوجهة',
      es: 'Destino',
      fr: 'Destination',
      hi: 'गंतव्य',
      id: 'Tujuan',
      pt: 'Destino',
    },
    'head.port': {
      en: 'Port',
      ko: '포트',
      ja: 'ポート',
      zh: '端口',
      ar: 'المنفذ',
      es: 'Puerto',
      fr: 'Port',
      hi: 'पोर्ट',
      id: 'Port',
      pt: 'Porta',
    },
    'head.verdict': {
      en: 'Verdict',
      ko: '판정',
      ja: '判定',
      zh: '判定',
      ar: 'الحكم',
      es: 'Veredicto',
      fr: 'Verdict',
      hi: 'निर्णय',
      id: 'Putusan',
      pt: 'Veredito',
    },
    'head.firstMatch': {
      en: 'First match',
      ko: '먼저 맞은 줄',
      ja: '最初の一致',
      zh: '首个匹配',
      ar: 'أول تطابق',
      es: 'Primera coincidencia',
      fr: 'Première correspondance',
      hi: 'पहला मेल',
      id: 'Cocok pertama',
      pt: 'Primeira correspondência',
    },
    'label.allow': {
      en: 'Allow',
      ko: '허용',
      ja: '許可',
      zh: '允许',
      ar: 'سماح',
      es: 'Permitir',
      fr: 'Admis',
      hi: 'अनुमति',
      id: 'Izinkan',
      pt: 'Permitir',
    },
    'label.deny': {
      en: 'Deny',
      ko: '차단',
      ja: '拒否',
      zh: '拒绝',
      ar: 'منع',
      es: 'Denegar',
      fr: 'Rejeté',
      hi: 'रोक',
      id: 'Tolak',
      pt: 'Negar',
    },
    'label.dead': {
      en: 'Dead',
      ko: '죽은 줄',
      ja: '死んだ規則',
      zh: '死规则',
      ar: 'ميتة',
      es: 'Muerta',
      fr: 'Morte',
      hi: 'मृत',
      id: 'Mati',
      pt: 'Morta',
    },
    'caption.order': {
      en: '{rule} position: {pos} · order: {order}',
      ko: '{rule} 자리: {pos} · 차례: {order}',
      ja: '{rule} の位置: {pos} · 順序: {order}',
      zh: '{rule} 位置：{pos} · 顺序：{order}',
      ar: 'موضع {rule}: {pos} · الترتيب: {order}',
      es: 'Posición de {rule}: {pos} · orden: {order}',
      fr: 'Position de {rule} : {pos} · ordre : {order}',
      hi: '{rule} का स्थान: {pos} · क्रम: {order}',
      id: 'Posisi {rule}: {pos} · urutan: {order}',
      pt: 'Posição de {rule}: {pos} · ordem: {order}',
    },
    'caption.packet': {
      en: '{packet}: stopped at position {depth} on {rule} → {verdict}',
      ko: '{packet}: 자리 {depth}의 {rule}에서 멈춤 → {verdict}',
      ja: '{packet}: 位置 {depth} の {rule} で停止 → {verdict}',
      zh: '{packet}：在位置 {depth} 的 {rule} 处停下 → {verdict}',
      ar: '{packet}: توقف عند الموضع {depth} على {rule} → {verdict}',
      es: '{packet}: se detiene en la posición {depth}, en {rule} → {verdict}',
      fr: '{packet} : arrêt à la position {depth}, sur {rule} → {verdict}',
      hi: '{packet}: स्थान {depth} पर {rule} में रुका → {verdict}',
      id: '{packet}: berhenti di posisi {depth} pada {rule} → {verdict}',
      pt: '{packet}: para na posição {depth}, em {rule} → {verdict}',
    },
    'caption.deadNone': {
      en: 'Rules never matched first: {n}',
      ko: '한 번도 먼저 맞지 않은 줄: {n}',
      ja: '一度も最初に一致しなかった規則: {n}',
      zh: '从未率先匹配的规则：{n}',
      ar: 'قواعد لم تطابق أولًا قط: {n}',
      es: 'Reglas que nunca coinciden primero: {n}',
      fr: 'Règles jamais atteintes en premier : {n}',
      hi: 'कभी पहले मेल न खाए नियम: {n}',
      id: 'Aturan yang tak pernah cocok lebih dulu: {n}',
      pt: 'Regras que nunca casam primeiro: {n}',
    },
    'caption.deadSome': {
      en: 'Rules never matched first: {n} ({ids})',
      ko: '한 번도 먼저 맞지 않은 줄: {n} ({ids})',
      ja: '一度も最初に一致しなかった規則: {n} ({ids})',
      zh: '从未率先匹配的规则：{n}（{ids}）',
      ar: 'قواعد لم تطابق أولًا قط: {n} ({ids})',
      es: 'Reglas que nunca coinciden primero: {n} ({ids})',
      fr: 'Règles jamais atteintes en premier : {n} ({ids})',
      hi: 'कभी पहले मेल न खाए नियम: {n} ({ids})',
      id: 'Aturan yang tak pernah cocok lebih dulu: {n} ({ids})',
      pt: 'Regras que nunca casam primeiro: {n} ({ids})',
    },
  },
};
