import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 같은 로그를 읽는 두 소비자 그룹은 어디까지 읽었는지를 어떻게 따로 세는가.
 */
export const consumerOffsetFacet: FacetJson = {
  id: 'facet:consumerOffset',
  title: {
    en: 'Consumer offset',
    ko: '컨슈머 오프셋',
    ja: 'コンシューマーオフセット',
    zh: '消费者偏移量',
    ar: 'إزاحة المستهلك',
    es: 'Offset del consumidor',
    fr: 'Offset du consommateur',
    hi: 'कंज़्यूमर ऑफ़सेट',
    id: 'Offset konsumen',
    pt: 'Offset do consumidor',
  },
  description: {
    en: 'Two consumer groups read the same log, and each keeps its own count of how far it has read.',
    ko: '두 소비자 그룹이 같은 로그를 읽고, 어디까지 읽었는지는 각자 센다.',
    ja: '二つのコンシューマーグループが同じログを読み、どこまで読んだかはそれぞれが数える。',
    zh: '两个消费者组读取同一份日志，读到哪里由各自分别记录。',
    ar: 'مجموعتا مستهلكين تقرآن السجل نفسه، وكل منهما تعدّ بنفسها إلى أين وصلت في القراءة.',
    es: 'Dos grupos de consumidores leen el mismo log y cada uno lleva su propia cuenta de hasta dónde ha leído.',
    fr: 'Deux groupes de consommateurs lisent le même journal, et chacun compte lui-même jusqu’où il a lu.',
    hi: 'दो कंज़्यूमर समूह एक ही लॉग पढ़ते हैं, और कहाँ तक पढ़ा यह हर समूह अपने आप गिनता है।',
    id: 'Dua grup konsumen membaca log yang sama, dan masing-masing menghitung sendiri sampai mana ia sudah membaca.',
    pt: 'Dois grupos de consumidores leem o mesmo log, e cada um conta por conta própria até onde já leu.',
  },
  algorithm: 'module:consumerOffset',
  scene: 'module:consumerOffsetScene',
  initialData: {
    type: 'consumer-offset',
    stepMs: 1300,
    log: [11, 24, 5, 17, 30, 8],
    groups: [
      { id: 'billing', maxPoll: 3 },
      { id: 'audit', maxPoll: 1 },
    ],
    events: [
      { kind: 'poll', group: 'billing' },
      { kind: 'poll', group: 'audit' },
      { kind: 'poll', group: 'billing' },
      { kind: 'append', value: 13 },
      { kind: 'poll', group: 'audit' },
      { kind: 'poll', group: 'billing' },
      { kind: 'poll', group: 'audit' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Two groups read one log. End: {end}.',
      ko: '두 그룹이 로그 하나를 읽는다. 끝: {end}.',
      ja: '二つのグループが一つのログを読む。終端: {end}。',
      zh: '两个组读取同一份日志。末尾: {end}。',
      ar: 'مجموعتان تقرآن سجلًا واحدًا. النهاية: {end}.',
      es: 'Dos grupos leen un mismo log. Final: {end}.',
      fr: 'Deux groupes lisent un même journal. Fin : {end}.',
      hi: 'दो समूह एक ही लॉग पढ़ते हैं। अंत: {end}.',
      id: 'Dua grup membaca satu log. Ujung: {end}.',
      pt: 'Dois grupos leem um mesmo log. Fim: {end}.',
    },
    'caption.read': {
      en: 'Read by {group}: offsets {from}–{last}. Its offset → {offset}; {other} stays at {otherOffset}.',
      ko: '{group} 읽기: 오프셋 {from}–{last}. {group} 오프셋 → {offset} · {other} 오프셋은 그대로 {otherOffset}.',
      ja: '{group} の読み取り: オフセット {from}–{last}。{group} のオフセット → {offset}、{other} は {otherOffset} のまま。',
      zh: '{group} 读取: 偏移量 {from}–{last}。{group} 的偏移量 → {offset}；{other} 仍停在 {otherOffset}。',
      ar: 'قراءة {group}: الإزاحات {from}–{last}. إزاحتها → {offset}؛ و{other} باقية عند {otherOffset}.',
      es: 'Lee {group}: offsets {from}–{last}. Su offset → {offset}; {other} sigue en {otherOffset}.',
      fr: 'Lecture par {group} : offsets {from}–{last}. Son offset → {offset} ; {other} reste à {otherOffset}.',
      hi: '{group} ने पढ़ा: ऑफ़सेट {from}–{last}. उसका ऑफ़सेट → {offset}; {other} वहीं {otherOffset} पर।',
      id: 'Dibaca {group}: offset {from}–{last}. Offset-nya → {offset}; {other} tetap di {otherOffset}.',
      pt: 'Leitura de {group}: offsets {from}–{last}. Seu offset → {offset}; {other} fica em {otherOffset}.',
    },
    'caption.readOne': {
      en: 'Read by {group}: offset {from}. Its offset → {offset}; {other} stays at {otherOffset}.',
      ko: '{group} 읽기: 오프셋 {from}. {group} 오프셋 → {offset} · {other} 오프셋은 그대로 {otherOffset}.',
      ja: '{group} の読み取り: オフセット {from}。{group} のオフセット → {offset}、{other} は {otherOffset} のまま。',
      zh: '{group} 读取: 偏移量 {from}。{group} 的偏移量 → {offset}；{other} 仍停在 {otherOffset}。',
      ar: 'قراءة {group}: الإزاحة {from}. إزاحتها → {offset}؛ و{other} باقية عند {otherOffset}.',
      es: 'Lee {group}: offset {from}. Su offset → {offset}; {other} sigue en {otherOffset}.',
      fr: 'Lecture par {group} : offset {from}. Son offset → {offset} ; {other} reste à {otherOffset}.',
      hi: '{group} ने पढ़ा: ऑफ़सेट {from}. उसका ऑफ़सेट → {offset}; {other} वहीं {otherOffset} पर।',
      id: 'Dibaca {group}: offset {from}. Offset-nya → {offset}; {other} tetap di {otherOffset}.',
      pt: 'Leitura de {group}: offset {from}. Seu offset → {offset}; {other} fica em {otherOffset}.',
    },
    'caption.append': {
      en: 'Record {value} at offset {offset}, end → {end}. Offsets {a} {ao} · {b} {bo}; lag {al} · {bl}.',
      ko: '새 기록 {value} → 오프셋 {offset}, 끝 → {end}. 오프셋 {a} {ao} · {b} {bo}, 밀림 {al} · {bl}.',
      ja: '新しいレコード {value} → オフセット {offset}、終端 → {end}。オフセット {a} {ao} · {b} {bo}、ラグ {al} · {bl}。',
      zh: '新记录 {value} → 偏移量 {offset}，末尾 → {end}。偏移量 {a} {ao} · {b} {bo}，滞后 {al} · {bl}。',
      ar: 'السجل {value} عند الإزاحة {offset}، النهاية → {end}. الإزاحات {a} {ao} · {b} {bo}؛ التأخر {al} · {bl}.',
      es: 'Registro {value} en el offset {offset}, final → {end}. Offsets {a} {ao} · {b} {bo}; retraso {al} · {bl}.',
      fr: 'Enregistrement {value} à l’offset {offset}, fin → {end}. Offsets {a} {ao} · {b} {bo} ; retard {al} · {bl}.',
      hi: 'रिकॉर्ड {value} ऑफ़सेट {offset} पर, अंत → {end}. ऑफ़सेट {a} {ao} · {b} {bo}; लैग {al} · {bl}.',
      id: 'Rekaman {value} di offset {offset}, ujung → {end}. Offset {a} {ao} · {b} {bo}; lag {al} · {bl}.',
      pt: 'Registro {value} no offset {offset}, fim → {end}. Offsets {a} {ao} · {b} {bo}; atraso {al} · {bl}.',
    },
    'label.billing': {
      en: 'Billing',
      ko: '청구',
      ja: '請求',
      zh: '账单',
      ar: 'الفوترة',
      es: 'Facturación',
      fr: 'Facturation',
      hi: 'बिलिंग',
      id: 'Tagihan',
      pt: 'Faturamento',
    },
    'label.audit': {
      en: 'Audit',
      ko: '감사',
      ja: '監査',
      zh: '审计',
      ar: 'التدقيق',
      es: 'Auditoría',
      fr: 'Audit',
      hi: 'ऑडिट',
      id: 'Audit',
      pt: 'Auditoria',
    },
    'label.log': {
      en: 'Log',
      ko: '로그',
      ja: 'ログ',
      zh: '日志',
      ar: 'السجل',
      es: 'Log',
      fr: 'Journal',
      hi: 'लॉग',
      id: 'Log',
      pt: 'Log',
    },
    'label.end': {
      en: 'End {n}',
      ko: '끝 {n}',
      ja: '終端 {n}',
      zh: '末尾 {n}',
      ar: 'النهاية {n}',
      es: 'Final {n}',
      fr: 'Fin {n}',
      hi: 'अंत {n}',
      id: 'Ujung {n}',
      pt: 'Fim {n}',
    },
    'label.maxPoll': {
      en: 'Per read: {n}',
      ko: '한 번에 {n}',
      ja: '一度に {n}',
      zh: '每次 {n}',
      ar: 'في كل قراءة: {n}',
      es: 'Por lectura: {n}',
      fr: 'Par lecture : {n}',
      hi: 'एक बार में: {n}',
      id: 'Per baca: {n}',
      pt: 'Por leitura: {n}',
    },
    'label.offset': {
      en: 'Offset {n}',
      ko: '오프셋 {n}',
      ja: 'オフセット {n}',
      zh: '偏移量 {n}',
      ar: 'الإزاحة {n}',
      es: 'Offset {n}',
      fr: 'Offset {n}',
      hi: 'ऑफ़सेट {n}',
      id: 'Offset {n}',
      pt: 'Offset {n}',
    },
    'label.lag': {
      en: 'Lag {n}',
      ko: '밀림 {n}',
      ja: 'ラグ {n}',
      zh: '滞后 {n}',
      ar: 'التأخر {n}',
      es: 'Retraso {n}',
      fr: 'Retard {n}',
      hi: 'लैग {n}',
      id: 'Lag {n}',
      pt: 'Atraso {n}',
    },
    'label.gap': {
      en: 'Apart: {n}',
      ko: '벌어짐 {n}',
      ja: '開き {n}',
      zh: '相差 {n}',
      ar: 'الفارق: {n}',
      es: 'Separación: {n}',
      fr: 'Écart : {n}',
      hi: 'अंतर: {n}',
      id: 'Selisih: {n}',
      pt: 'Distância: {n}',
    },
  },
  blocks: {
    stage: { type: 'consumer-offset-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
