import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 같은 배열을 행으로 도는 것과 열로 도는 것은 왜 속도가 다른가.
 *
 * 4×4 int 배열(행 우선 배치, 캐시 줄 = 한 행, 캐시 2 줄 · 완전 연관 · LRU)을 두 순서로
 * 더한다. 행으로 돌면 커서가 올라온 줄 안에서 옆으로 미끄러지고, 열로 돌면 줄을 건너
 * 뛰며 매번 줄을 새로 불러오고 밀어낸다.
 */
export const rowVsColumnWalkFacet: FacetJson = {
  id: 'facet:rowVsColumnWalk',
  title: {
    en: 'Row-major vs column-major walk',
    ko: '행 우선과 열 우선',
    ja: '行優先と列優先の走査',
    zh: '行优先与列优先遍历',
    ar: 'المرور حسب الصفوف مقابل الأعمدة',
    es: 'Recorrido por filas frente a por columnas',
    fr: 'Parcours par lignes contre par colonnes',
    hi: 'पंक्ति-क्रम बनाम स्तंभ-क्रम भ्रमण',
    id: 'Penelusuran per baris vs per kolom',
    pt: 'Percurso por linhas vs por colunas',
  },
  description: {
    en: 'The same array summed row by row and column by column: the sum matches, the cache misses do not.',
    ko: '같은 배열을 행으로 더하고 열로 더한다. 합은 같은데 캐시 실패는 다르다.',
    ja: '同じ配列を行ごと・列ごとに足す。合計は同じだが、キャッシュミスは違う。',
    zh: '同一个数组按行求和、按列求和：和相同，缓存未命中却不同。',
    ar: 'المصفوفة نفسها تُجمع صفًا صفًا ثم عمودًا عمودًا: المجموع واحد، لكن إخفاقات الذاكرة المخبئية تختلف.',
    es: 'El mismo arreglo sumado por filas y por columnas: la suma coincide, los fallos de caché no.',
    fr: 'Le même tableau additionné par lignes puis par colonnes : la somme est la même, pas les défauts de cache.',
    hi: 'एक ही सरणी को पंक्ति-दर-पंक्ति और स्तंभ-दर-स्तंभ जोड़ा जाता है: योग वही, कैश मिस अलग।',
    id: 'Larik yang sama dijumlahkan per baris dan per kolom: jumlahnya sama, cache miss-nya tidak.',
    pt: 'O mesmo arranjo somado por linhas e por colunas: a soma é igual, as falhas de cache não.',
  },
  algorithm: 'module:rowVsColumnWalk',
  scene: 'module:rowVsColumnWalkScene',
  initialData: {
    type: 'row-vs-column-walk',
    stepMs: 500,
    values: [
      [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12],
      [13, 14, 15, 16],
    ],
    lineElems: 4,
    cacheLines: 2,
  },
  shuffleOnReset: false,
  messages: {
    'label.rowWalk': {
      en: 'Row walk: r outer, c inner',
      ko: '행 순회 — r 바깥, c 안쪽',
      ja: '行走査 — r が外、c が内',
      zh: '按行遍历 — r 在外，c 在内',
      ar: 'المرور بالصفوف: r خارجي، c داخلي',
      es: 'Por filas: r fuera, c dentro',
      fr: 'Par lignes : r dehors, c dedans',
      hi: 'पंक्ति-क्रम: r बाहर, c भीतर',
      id: 'Per baris: r luar, c dalam',
      pt: 'Por linhas: r fora, c dentro',
    },
    'label.colWalk': {
      en: 'Column walk: c outer, r inner',
      ko: '열 순회 — c 바깥, r 안쪽',
      ja: '列走査 — c が外、r が内',
      zh: '按列遍历 — c 在外，r 在内',
      ar: 'المرور بالأعمدة: c خارجي، r داخلي',
      es: 'Por columnas: c fuera, r dentro',
      fr: 'Par colonnes : c dehors, r dedans',
      hi: 'स्तंभ-क्रम: c बाहर, r भीतर',
      id: 'Per kolom: c luar, r dalam',
      pt: 'Por colunas: c fora, r dentro',
    },
    'label.rowTag': {
      en: 'row {r}',
      ko: '행 {r}',
      ja: '行 {r}',
      zh: '行 {r}',
      ar: 'الصف {r}',
      es: 'fila {r}',
      fr: 'ligne {r}',
      hi: 'पंक्ति {r}',
      id: 'baris {r}',
      pt: 'linha {r}',
    },
    'label.cache': {
      en: 'cache · {n} lines',
      ko: '캐시 · 줄 {n}',
      ja: 'キャッシュ · {n} ライン',
      zh: '缓存 · {n} 行',
      ar: 'الذاكرة المخبئية · {n} أسطر',
      es: 'caché · {n} líneas',
      fr: 'cache · {n} lignes',
      hi: 'कैश · {n} लाइनें',
      id: 'cache · {n} baris',
      pt: 'cache · {n} linhas',
    },
    'label.miss': {
      en: 'miss {n}',
      ko: '실패 {n}',
      ja: 'ミス {n}',
      zh: '未命中 {n}',
      ar: 'إخفاق {n}',
      es: 'fallos {n}',
      fr: 'défauts {n}',
      hi: 'मिस {n}',
      id: 'miss {n}',
      pt: 'falhas {n}',
    },
    'label.hit': {
      en: 'hit {n}',
      ko: '적중 {n}',
      ja: 'ヒット {n}',
      zh: '命中 {n}',
      ar: 'إصابة {n}',
      es: 'aciertos {n}',
      fr: 'succès {n}',
      hi: 'हिट {n}',
      id: 'hit {n}',
      pt: 'acertos {n}',
    },
    'label.sum': {
      en: 'sum {n}',
      ko: '합 {n}',
      ja: '合計 {n}',
      zh: '和 {n}',
      ar: 'المجموع {n}',
      es: 'suma {n}',
      fr: 'somme {n}',
      hi: 'योग {n}',
      id: 'jumlah {n}',
      pt: 'soma {n}',
    },
    'caption.ready': {
      en: 'Two walks add the same {n} values, each from an empty cache.',
      ko: '두 순회가 같은 값 {n} 개를 더한다. 둘 다 빈 캐시에서 시작한다.',
      ja: '二つの走査が同じ {n} 個の値を足す。どちらも空のキャッシュから始まる。',
      zh: '两种遍历把同样的 {n} 个值相加，各自从空缓存开始。',
      ar: 'مروران يجمعان القيم نفسها وعددها {n}، وكل منهما يبدأ بذاكرة مخبئية فارغة.',
      es: 'Dos recorridos suman los mismos {n} valores, cada uno desde una caché vacía.',
      fr: 'Deux parcours additionnent les mêmes {n} valeurs, chacun depuis un cache vide.',
      hi: 'दो भ्रमण वही {n} मान जोड़ते हैं, दोनों खाली कैश से शुरू।',
      id: 'Dua penelusuran menjumlahkan {n} nilai yang sama, masing-masing dari cache kosong.',
      pt: 'Dois percursos somam os mesmos {n} valores, cada um a partir de um cache vazio.',
    },
    'caption.row': {
      en: 'Row {r}: {miss} misses, {out} lines pushed out, {hit} hits.',
      ko: '행 {r} — 실패 {miss} · 밀려난 줄 {out} · 적중 {hit}.',
      ja: '行 {r} — ミス {miss} · 追い出したライン {out} · ヒット {hit}。',
      zh: '第 {r} 行：未命中 {miss}，挤出 {out} 行，命中 {hit}。',
      ar: 'الصف {r}: إخفاقات {miss}، أسطر مطرودة {out}، إصابات {hit}.',
      es: 'Fila {r}: fallos {miss}, líneas expulsadas {out}, aciertos {hit}.',
      fr: 'Ligne {r} : défauts {miss}, lignes évincées {out}, succès {hit}.',
      hi: 'पंक्ति {r}: मिस {miss}, निकाली गई लाइनें {out}, हिट {hit}।',
      id: 'Baris {r}: miss {miss}, baris terusir {out}, hit {hit}.',
      pt: 'Linha {r}: falhas {miss}, linhas expulsas {out}, acertos {hit}.',
    },
    'caption.col': {
      en: 'Column {c}: {miss} misses, {out} lines pushed out, {hit} hits.',
      ko: '열 {c} — 실패 {miss} · 밀려난 줄 {out} · 적중 {hit}.',
      ja: '列 {c} — ミス {miss} · 追い出したライン {out} · ヒット {hit}。',
      zh: '第 {c} 列：未命中 {miss}，挤出 {out} 行，命中 {hit}。',
      ar: 'العمود {c}: إخفاقات {miss}، أسطر مطرودة {out}، إصابات {hit}.',
      es: 'Columna {c}: fallos {miss}, líneas expulsadas {out}, aciertos {hit}.',
      fr: 'Colonne {c} : défauts {miss}, lignes évincées {out}, succès {hit}.',
      hi: 'स्तंभ {c}: मिस {miss}, निकाली गई लाइनें {out}, हिट {hit}।',
      id: 'Kolom {c}: miss {miss}, baris terusir {out}, hit {hit}.',
      pt: 'Coluna {c}: falhas {miss}, linhas expulsas {out}, acertos {hit}.',
    },
    'caption.done': {
      en: 'Sum: rows {rowSum}, columns {colSum}. Misses: rows {rowMiss}, columns {colMiss}.',
      ko: '합 — 행 순회 {rowSum}, 열 순회 {colSum}. 실패 — 행 순회 {rowMiss}, 열 순회 {colMiss}.',
      ja: '合計 — 行走査 {rowSum}、列走査 {colSum}。ミス — 行走査 {rowMiss}、列走査 {colMiss}。',
      zh: '和：按行 {rowSum}，按列 {colSum}。未命中：按行 {rowMiss}，按列 {colMiss}。',
      ar: 'المجموع: {rowSum} و{colSum}. الإخفاقات: {rowMiss} و{colMiss}.',
      es: 'Suma: {rowSum} y {colSum}. Fallos: {rowMiss} y {colMiss}.',
      fr: 'Somme : {rowSum} et {colSum}. Défauts : {rowMiss} et {colMiss}.',
      hi: 'योग: {rowSum} और {colSum}। मिस: {rowMiss} और {colMiss}।',
      id: 'Jumlah: {rowSum} dan {colSum}. Miss: {rowMiss} dan {colMiss}.',
      pt: 'Soma: {rowSum} e {colSum}. Falhas: {rowMiss} e {colMiss}.',
    },
  },
  blocks: {
    stage: { type: 'row-vs-column-walk-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
