import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece top-k 는 무엇을 버리고 무엇에서 뽑는가.
 *
 * 로짓은 예로 정한 값이다 — 실제 언어 모형이 낸 수가 아니다. 뽑기 값 u 도 난수가 아니라
 * 데이터로 정한 수다.
 */
export const cutTheTailFacet: FacetJson = {
  id: 'facet:cutTheTail',
  title: {
    en: 'Top-k: cut the tail, then draw',
    ko: 'top-k — 꼬리를 자르고 뽑는다',
    ja: 'top-k — 裾を切ってから引く',
    zh: 'top-k：先剪掉尾部，再抽取',
    ar: 'top-k: اقطع الذيل ثم اسحب',
    es: 'Top-k: cortar la cola y luego sortear',
    fr: 'Top-k : couper la queue, puis tirer',
    hi: 'टॉप-k: पूँछ काटो, फिर चुनो',
    id: 'Top-k: potong ekor, lalu undi',
    pt: 'Top-k: cortar a cauda e depois sortear',
  },
  description: {
    en: 'Top-k drops every candidate below rank k, spreads their share over the survivors in proportion to size, and draws only from those.',
    ko: 'top-k 는 k 등 아래 후보를 버리고, 그들이 쥐던 몫을 남은 후보에게 크기에 비례해 나눠 준 뒤, 남은 것에서만 뽑는다.',
    ja: 'top-k は k 位より下の候補を捨て、その分を残った候補に大きさに比例して配り、残りからだけ引く。',
    zh: 'top-k 丢掉排名 k 以下的候选，把它们的份额按大小比例分给剩下的候选，只在剩下的里面抽取。',
    ar: 'يُسقط top-k كل مرشح دون المرتبة k، ويوزّع حصته على الباقين بنسبة أحجامهم، ثم يسحب منهم فقط.',
    es: 'Top-k descarta los candidatos por debajo del puesto k, reparte su parte entre los que quedan según su tamaño y sortea solo entre ellos.',
    fr: 'Top-k écarte tout candidat sous le rang k, répartit leur part entre les restants selon leur taille, puis tire seulement parmi eux.',
    hi: 'टॉप-k रैंक k से नीचे के सभी उम्मीदवार छोड़ देता है, उनका हिस्सा बचे हुओं में उनके आकार के अनुपात में बाँटता है, और सिर्फ़ उन्हीं में से चुनता है।',
    id: 'Top-k membuang semua kandidat di bawah peringkat k, membagi bagian mereka ke yang tersisa sesuai ukuran, lalu mengundi hanya dari yang tersisa.',
    pt: 'Top-k descarta os candidatos abaixo da posição k, reparte a parte deles entre os que ficam conforme o tamanho e sorteia só entre eles.',
  },
  algorithm: 'module:cutTheTail',
  scene: 'module:cutTheTailScene',
  initialData: {
    type: 'cut-the-tail',
    context: 'She opened the',
    candidates: [
      { token: 'door', logit: 2.6 },
      { token: 'window', logit: 2.0 },
      { token: 'box', logit: 1.7 },
      { token: 'letter', logit: 1.1 },
      { token: 'oven', logit: 0.3 },
      { token: 'banana', logit: -0.4 },
      { token: 'cloud', logit: -0.9 },
    ],
    k: 3,
    u: 0.95,
    stepMs: 1600,
  },
  shuffleOnReset: false,
  messages: {
    'caption.init': {
      en: 'Softmax over all {n} candidates: {top} holds {p}.',
      ko: '후보 {n} 개 전체로 소프트맥스. 가장 큰 몫은 {top}, {p}.',
      ja: '候補 {n} 個すべてでソフトマックス。最大は {top} の {p}。',
      zh: '在全部 {n} 个候选上做 softmax：{top} 占 {p}。',
      ar: 'سوفت ماكس على كل المرشحين الـ {n}: {top} يحمل {p}.',
      es: 'Softmax sobre los {n} candidatos: {top} tiene {p}.',
      fr: 'Softmax sur les {n} candidats : {top} détient {p}.',
      hi: 'सभी {n} उम्मीदवारों पर सॉफ्टमैक्स: {top} के पास {p}.',
      id: 'Softmax atas semua {n} kandidat: {top} memegang {p}.',
      pt: 'Softmax sobre os {n} candidatos: {top} tem {p}.',
    },
    'caption.cut': {
      en: 'Keep the top {k}. The other {m} fall away, taking {mass}.',
      ko: '위 {k} 개만 남긴다. 나머지 {m} 개가 떨어져 나가며 가져간 몫은 {mass}.',
      ja: '上位 {k} 個だけ残す。残り {m} 個は {mass} を持って離れる。',
      zh: '只留前 {k} 个。其余 {m} 个带着 {mass} 脱落。',
      ar: 'نُبقي أعلى {k}. الـ {m} الباقية تسقط آخذةً {mass}.',
      es: 'Se quedan los {k} primeros. Los otros {m} caen y se llevan {mass}.',
      fr: 'On garde les {k} premiers. Les {m} autres tombent et emportent {mass}.',
      hi: 'ऊपर के {k} रखो। बाकी {m} अपना {mass} लेकर गिर जाते हैं।',
      id: 'Simpan {k} teratas. {m} lainnya jatuh, membawa {mass}.',
      pt: 'Ficam os {k} primeiros. Os outros {m} caem e levam {mass}.',
    },
    'caption.renormalize': {
      en: 'The {mass} left behind is shared out to the {k}, each by its size.',
      ko: '빈 몫 {mass}. 남은 {k} 개가 자기 크기에 비례해 나눠 가진다.',
      ja: '空いた {mass} を、残った {k} 個が大きさに比例して分け合う。',
      zh: '空出的 {mass} 按大小比例分给剩下的 {k} 个。',
      ar: 'الـ {mass} المتروكة تُوزَّع على الـ {k} كلٌّ بحسب حجمه.',
      es: 'El {mass} que queda libre se reparte entre los {k}, según su tamaño.',
      fr: 'Les {mass} libérés sont répartis entre les {k}, selon leur taille.',
      hi: 'छूटा हुआ {mass} बचे {k} में उनके आकार के अनुपात में बँटता है।',
      id: '{mass} yang ditinggalkan dibagi ke {k} sisanya, sesuai ukuran masing-masing.',
      pt: 'Os {mass} deixados são repartidos entre os {k}, conforme o tamanho.',
    },
    'caption.draw': {
      en: 'Draw value u = {u}: the running total first passes it at {token}.',
      ko: '뽑기 값 u = {u}. 누적이 처음 u 를 넘는 자리는 {token}.',
      ja: '抽選値 u = {u}。累積が初めて u を超えるのは {token}。',
      zh: '抽取值 u = {u}：累计首次超过它的是 {token}。',
      ar: 'قيمة السحب u = {u}: يتجاوزها المجموع التراكمي أولًا عند {token}.',
      es: 'Valor de sorteo u = {u}: el acumulado lo supera primero en {token}.',
      fr: "Valeur de tirage u = {u} : le cumul la dépasse d'abord à {token}.",
      hi: 'ड्रॉ मान u = {u}: संचयी योग इसे पहली बार {token} पर पार करता है।',
      id: 'Nilai undian u = {u}: jumlah kumulatif pertama melewatinya di {token}.',
      pt: 'Valor de sorteio u = {u}: o acumulado passa dele primeiro em {token}.',
    },
    'label.dropped': {
      en: 'dropped {mass}',
      ko: '버린 몫 {mass}',
      ja: '捨てた分 {mass}',
      zh: '丢弃 {mass}',
      ar: 'المُسقَط {mass}',
      es: 'descartado {mass}',
      fr: 'écarté {mass}',
      hi: 'छोड़ा गया {mass}',
      id: 'dibuang {mass}',
      pt: 'descartado {mass}',
    },
    'label.k': {
      en: 'k = {k}',
      ko: 'k = {k}',
      ja: 'k = {k}',
      zh: 'k = {k}',
      ar: 'k = {k}',
      es: 'k = {k}',
      fr: 'k = {k}',
      hi: 'k = {k}',
      id: 'k = {k}',
      pt: 'k = {k}',
    },
    'label.u': {
      en: 'u = {u}',
      ko: 'u = {u}',
      ja: 'u = {u}',
      zh: 'u = {u}',
      ar: 'u = {u}',
      es: 'u = {u}',
      fr: 'u = {u}',
      hi: 'u = {u}',
      id: 'u = {u}',
      pt: 'u = {u}',
    },
  },
  blocks: {
    stage: { type: 'cut-the-tail-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
