import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 장치가 부르면 CPU 는 하던 일을 언제 멈추고, 어디로 갔다가, 어디로 돌아오는가.
 */
export const interruptPreemptsFacet: FacetJson = {
  id: 'facet:interruptPreempts',
  title: {
    en: 'Interrupt: step out, then come back',
    ko: '인터럽트 — 끼어들었다 돌아온다',
    ja: '割り込み — 抜け出して、戻ってくる',
    zh: '中断——跳出去，再回来',
    ar: 'المقاطعة: الخروج ثم العودة',
    es: 'Interrupción: salir y volver',
    fr: 'Interruption : partir, puis revenir',
    hi: 'इंटरप्ट: बाहर जाना, फिर लौटना',
    id: 'Interupsi: keluar, lalu kembali',
    pt: 'Interrupção: sair e voltar',
  },
  description: {
    en: 'A device calls in the middle of an instruction. The CPU finishes that instruction, writes down where to come back, runs the handler, and returns to the very next instruction.',
    ko: '장치가 명령 도중에 부른다. CPU 는 그 명령을 마저 끝내고, 돌아올 자리를 적고, 처리기를 돌린 뒤 바로 다음 명령으로 돌아온다.',
    ja: '命令の途中でデバイスが呼ぶ。CPU はその命令を最後まで終え、戻る場所を書き留め、ハンドラを実行してから、すぐ次の命令へ戻る。',
    zh: '设备在一条指令执行中途发出请求。CPU 先把这条指令执行完，记下返回的位置，运行处理程序，然后回到紧接着的下一条指令。',
    ar: 'يستدعي جهازٌ المعالجَ في منتصف تعليمة. يُنهي المعالج تلك التعليمة، ويدوّن موضع العودة، ويشغّل المعالِج، ثم يعود إلى التعليمة التالية مباشرة.',
    es: 'Un dispositivo llama a mitad de una instrucción. La CPU termina esa instrucción, anota a dónde volver, ejecuta el manejador y regresa a la instrucción siguiente.',
    fr: 'Un périphérique appelle au milieu d’une instruction. Le processeur termine cette instruction, note où revenir, exécute le gestionnaire, puis reprend à l’instruction suivante.',
    hi: 'कोई डिवाइस एक निर्देश के बीच में पुकारता है। CPU उस निर्देश को पूरा करता है, लौटने की जगह लिख लेता है, हैंडलर चलाता है और ठीक अगले निर्देश पर लौट आता है।',
    id: 'Sebuah perangkat memanggil di tengah sebuah instruksi. CPU menuntaskan instruksi itu, mencatat tempat kembali, menjalankan penangan, lalu kembali ke instruksi berikutnya.',
    pt: 'Um dispositivo chama no meio de uma instrução. A CPU termina essa instrução, anota para onde voltar, executa o tratador e retorna à instrução seguinte.',
  },
  algorithm: 'module:interruptPreempts',
  scene: 'module:interruptPreemptsScene',
  initialData: {
    type: 'interrupt-preempts',
    program: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
    handler: ['read', 'store', 'return'],
    device: 'keyboard',
    callAt: 2.5,
    stepMs: 1000,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Instructions in the program: {n}. No call yet.',
      ko: '프로그램 명령 수: {n}. 아직 부름은 없다.',
      ja: 'プログラムの命令数: {n}。まだ呼び出しはない。',
      zh: '程序中的指令数：{n}。还没有请求。',
      ar: 'عدد تعليمات البرنامج: {n}. لا استدعاء بعد.',
      es: 'Instrucciones del programa: {n}. Aún no hay llamada.',
      fr: 'Instructions du programme : {n}. Pas encore d’appel.',
      hi: 'प्रोग्राम में निर्देश: {n}. अभी कोई पुकार नहीं।',
      id: 'Instruksi dalam program: {n}. Belum ada panggilan.',
      pt: 'Instruções do programa: {n}. Ainda sem chamada.',
    },
    'caption.run': {
      en: 'Instruction {n} runs. Time: {from} → {to}',
      ko: '명령 {n} 실행. 시각: {from} → {to}',
      ja: '命令 {n} を実行。時刻: {from} → {to}',
      zh: '执行指令 {n}。时刻：{from} → {to}',
      ar: 'تُنفَّذ التعليمة {n}. الزمن: {from} → {to}',
      es: 'Se ejecuta la instrucción {n}. Tiempo: {from} → {to}',
      fr: 'L’instruction {n} s’exécute. Temps : {from} → {to}',
      hi: 'निर्देश {n} चलता है। समय: {from} → {to}',
      id: 'Instruksi {n} berjalan. Waktu: {from} → {to}',
      pt: 'A instrução {n} executa. Tempo: {from} → {to}',
    },
    'caption.call': {
      en: 'Instruction {n} runs. {device} calls at time {at}; the instruction keeps going.',
      ko: '명령 {n} 실행. 시각 {at}, {device}의 부름 — 명령은 끝까지 간다.',
      ja: '命令 {n} を実行。時刻 {at} に {device} が呼ぶ — 命令は最後まで進む。',
      zh: '执行指令 {n}。时刻 {at}，{device} 发出请求——指令继续执行到底。',
      ar: 'تُنفَّذ التعليمة {n}. يستدعي {device} عند الزمن {at}؛ وتستمر التعليمة.',
      es: 'Se ejecuta la instrucción {n}. {device} llama en el tiempo {at}; la instrucción sigue.',
      fr: 'L’instruction {n} s’exécute. {device} appelle au temps {at} ; l’instruction continue.',
      hi: 'निर्देश {n} चलता है। समय {at} पर {device} पुकारता है; निर्देश चलता रहता है।',
      id: 'Instruksi {n} berjalan. {device} memanggil pada waktu {at}; instruksi terus berjalan.',
      pt: 'A instrução {n} executa. {device} chama no tempo {at}; a instrução continua.',
    },
    'caption.handler': {
      en: 'Handler: {name}. Time: {from} → {to}',
      ko: '처리기: {name}. 시각: {from} → {to}',
      ja: 'ハンドラ: {name}。時刻: {from} → {to}',
      zh: '处理程序：{name}。时刻：{from} → {to}',
      ar: 'المعالِج: {name}. الزمن: {from} → {to}',
      es: 'Manejador: {name}. Tiempo: {from} → {to}',
      fr: 'Gestionnaire : {name}. Temps : {from} → {to}',
      hi: 'हैंडलर: {name}. समय: {from} → {to}',
      id: 'Penangan: {name}. Waktu: {from} → {to}',
      pt: 'Tratador: {name}. Tempo: {from} → {to}',
    },
    'caption.accept': {
      en: 'Boundary at time {at}: the call is taken. Return point saved: {ret}',
      ko: '시각 {at}, 명령 경계에서 부름을 받는다. 적어 둔 돌아올 자리: {ret}',
      ja: '時刻 {at} の境界で呼び出しを受ける。書き留めた戻り先: {ret}',
      zh: '在时刻 {at} 的边界接受请求。记下的返回位置：{ret}',
      ar: 'عند الحدّ في الزمن {at} يُقبَل الاستدعاء. موضع العودة المدوَّن: {ret}',
      es: 'En el límite del tiempo {at} se atiende la llamada. Punto de regreso anotado: {ret}',
      fr: 'À la frontière du temps {at}, l’appel est pris. Point de retour noté : {ret}',
      hi: 'समय {at} की सीमा पर पुकार ली जाती है। लिखी गई लौटने की जगह: {ret}',
      id: 'Di batas waktu {at}, panggilan diterima. Tempat kembali yang dicatat: {ret}',
      pt: 'Na fronteira do tempo {at}, a chamada é atendida. Ponto de retorno anotado: {ret}',
    },
    'caption.wait': {
      en: 'Called: {called} · taken: {at} · waited: {wait}',
      ko: '부른 시각: {called} · 받은 시각: {at} · 기다림: {wait}',
      ja: '呼んだ時刻: {called} · 受けた時刻: {at} · 待ち: {wait}',
      zh: '请求时刻：{called} · 接受时刻：{at} · 等待：{wait}',
      ar: 'وقت الاستدعاء: {called} · وقت القبول: {at} · الانتظار: {wait}',
      es: 'Llamó: {called} · atendida: {at} · espera: {wait}',
      fr: 'Appel : {called} · pris : {at} · attente : {wait}',
      hi: 'पुकारा: {called} · लिया: {at} · प्रतीक्षा: {wait}',
      id: 'Dipanggil: {called} · diterima: {at} · menunggu: {wait}',
      pt: 'Chamou: {called} · atendida: {at} · espera: {wait}',
    },
    'caption.return': {
      en: 'Time {at}: the handler is done. Back to the saved point: {ret}',
      ko: '시각 {at}, 처리기 끝. 적어 둔 자리로 돌아온다: {ret}',
      ja: '時刻 {at}、ハンドラ終了。書き留めた場所へ戻る: {ret}',
      zh: '时刻 {at}，处理程序结束。回到记下的位置：{ret}',
      ar: 'الزمن {at}: انتهى المعالِج. العودة إلى الموضع المدوَّن: {ret}',
      es: 'Tiempo {at}: el manejador termina. De vuelta al punto anotado: {ret}',
      fr: 'Temps {at} : le gestionnaire a fini. Retour au point noté : {ret}',
      hi: 'समय {at}: हैंडलर पूरा। लिखी गई जगह पर वापसी: {ret}',
      id: 'Waktu {at}: penangan selesai. Kembali ke tempat yang dicatat: {ret}',
      pt: 'Tempo {at}: o tratador terminou. De volta ao ponto anotado: {ret}',
    },
    'caption.finish': {
      en: 'Program ends at: {end} · without the call: {plain} · later by: {delay}',
      ko: '프로그램이 끝난 시각: {end} · 부름이 없었다면: {plain} · 늦어짐: {delay}',
      ja: 'プログラム終了時刻: {end} · 呼び出しがなければ: {plain} · 遅れ: {delay}',
      zh: '程序结束时刻：{end} · 若没有请求：{plain} · 推迟：{delay}',
      ar: 'ينتهي البرنامج عند: {end} · دون استدعاء: {plain} · التأخّر: {delay}',
      es: 'El programa termina en: {end} · sin la llamada: {plain} · retraso: {delay}',
      fr: 'Fin du programme : {end} · sans l’appel : {plain} · retard : {delay}',
      hi: 'प्रोग्राम समाप्त: {end} · पुकार के बिना: {plain} · देरी: {delay}',
      id: 'Program selesai pada: {end} · tanpa panggilan: {plain} · terlambat: {delay}',
      pt: 'O programa termina em: {end} · sem a chamada: {plain} · atraso: {delay}',
    },
    'label.time': {
      en: 'Time: {t}',
      ko: '시각: {t}',
      ja: '時刻: {t}',
      zh: '时刻：{t}',
      ar: 'الزمن: {t}',
      es: 'Tiempo: {t}',
      fr: 'Temps : {t}',
      hi: 'समय: {t}',
      id: 'Waktu: {t}',
      pt: 'Tempo: {t}',
    },
    'label.program': {
      en: 'Program',
      ko: '프로그램',
      ja: 'プログラム',
      zh: '程序',
      ar: 'البرنامج',
      es: 'Programa',
      fr: 'Programme',
      hi: 'प्रोग्राम',
      id: 'Program',
      pt: 'Programa',
    },
    'label.handler': {
      en: 'Handler',
      ko: '처리기',
      ja: 'ハンドラ',
      zh: '处理程序',
      ar: 'المعالِج',
      es: 'Manejador',
      fr: 'Gestionnaire',
      hi: 'हैंडलर',
      id: 'Penangan',
      pt: 'Tratador',
    },
    'label.keyboard': {
      en: 'Keyboard',
      ko: '키보드',
      ja: 'キーボード',
      zh: '键盘',
      ar: 'لوحة المفاتيح',
      es: 'Teclado',
      fr: 'Clavier',
      hi: 'कीबोर्ड',
      id: 'Papan ketik',
      pt: 'Teclado',
    },
    'label.read': {
      en: 'Read from device',
      ko: '장치에서 읽기',
      ja: 'デバイスから読む',
      zh: '从设备读取',
      ar: 'القراءة من الجهاز',
      es: 'Leer del dispositivo',
      fr: 'Lire le périphérique',
      hi: 'डिवाइस से पढ़ना',
      id: 'Baca dari perangkat',
      pt: 'Ler do dispositivo',
    },
    'label.store': {
      en: 'Put in buffer',
      ko: '버퍼에 넣기',
      ja: 'バッファに入れる',
      zh: '放入缓冲区',
      ar: 'الوضع في المخزن المؤقت',
      es: 'Guardar en el búfer',
      fr: 'Mettre en tampon',
      hi: 'बफ़र में रखना',
      id: 'Simpan ke penyangga',
      pt: 'Pôr no buffer',
    },
    'label.return': {
      en: 'Return',
      ko: '돌아가기',
      ja: '戻る',
      zh: '返回',
      ar: 'العودة',
      es: 'Volver',
      fr: 'Revenir',
      hi: 'लौटना',
      id: 'Kembali',
      pt: 'Voltar',
    },
    'label.saved': {
      en: 'Return point',
      ko: '돌아올 자리',
      ja: '戻り先',
      zh: '返回位置',
      ar: 'موضع العودة',
      es: 'Regreso',
      fr: 'Retour',
      hi: 'लौटने की जगह',
      id: 'Tempat kembali',
      pt: 'Retorno',
    },
    'label.call': {
      en: 'Call: {t}',
      ko: '부름: {t}',
      ja: '呼び出し: {t}',
      zh: '请求：{t}',
      ar: 'استدعاء: {t}',
      es: 'Llamada: {t}',
      fr: 'Appel : {t}',
      hi: 'पुकार: {t}',
      id: 'Panggilan: {t}',
      pt: 'Chamada: {t}',
    },
    'label.span': {
      en: '{from} → {to}',
      ko: '{from} → {to}',
      ja: '{from} → {to}',
      zh: '{from} → {to}',
      ar: '{from} → {to}',
      es: '{from} → {to}',
      fr: '{from} → {to}',
      hi: '{from} → {to}',
      id: '{from} → {to}',
      pt: '{from} → {to}',
    },
  },
  blocks: {
    stage: { type: 'interrupt-preempts-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
