import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 브랜치를 지우거나 되돌리면 그 커밋은 언제, 왜 사라지는가.
 *
 * 이름이 떠나도 커밋은 그 자리에 있다. 치우기 때 남은 이름마다 부모를 따라 거슬러 가며
 * 표시를 붙이고, 표시 없는 커밋만 사라진다.
 */
export const unreachableSnapshotFacet: FacetJson = {
  id: 'facet:unreachableSnapshot',
  title: {
    en: 'Unreachable commits get swept',
    ko: '닿지 않는 커밋이 치워진다',
    ja: '届かないコミットが片付けられる',
    zh: '无法到达的提交被清除',
    ar: 'الإيداعات التي لا يمكن بلوغها تُزال',
    es: 'Los commits inalcanzables se barren',
    fr: 'Les commits inaccessibles sont balayés',
    hi: 'पहुँच से बाहर कमिट हटा दिए जाते हैं',
    id: 'Commit yang tak terjangkau disapu',
    pt: 'Commits inalcançáveis são varridos',
  },
  description: {
    en: 'A commit stays as long as some name can reach it by walking back through parents. Only the unreachable ones are swept.',
    ko: '어느 이름에서든 부모를 따라 거슬러 닿는 한 커밋은 남는다. 닿지 않는 것만 치워진다.',
    ja: 'どれかの名前から親をたどって届く限り、コミットは残る。届かないものだけが片付けられる。',
    zh: '只要能从某个名字沿父提交往回走到，提交就会留下。只有无法到达的才被清除。',
    ar: 'يبقى الإيداع ما دام يمكن بلوغه من اسم ما بالرجوع عبر الآباء. لا يُزال إلا ما لا يمكن بلوغه.',
    es: 'Un commit se queda mientras algún nombre pueda alcanzarlo recorriendo los padres hacia atrás. Solo se barren los inalcanzables.',
    fr: 'Un commit reste tant qu’un nom peut l’atteindre en remontant les parents. Seuls les inaccessibles sont balayés.',
    hi: 'जब तक कोई नाम पैरेंट के सहारे पीछे चलकर किसी कमिट तक पहुँच सकता है, वह बचा रहता है। केवल पहुँच से बाहर वाले हटते हैं।',
    id: 'Commit tetap ada selama suatu nama bisa mencapainya dengan menelusuri induk ke belakang. Hanya yang tak terjangkau yang disapu.',
    pt: 'Um commit fica enquanto algum nome consegue alcançá-lo recuando pelos pais. Só os inalcançáveis são varridos.',
  },
  algorithm: 'module:unreachableSnapshot',
  scene: 'module:unreachableSnapshotScene',
  initialData: {
    type: 'unreachable-snapshot',
    commits: [
      { id: 'A', parents: [] },
      { id: 'B', parents: ['A'] },
      { id: 'C', parents: ['B'] },
      { id: 'D', parents: ['C'] },
      { id: 'E', parents: ['B'] },
      { id: 'F', parents: ['E'] },
      { id: 'G', parents: ['E'] },
    ],
    // 이 차례가 표시할 때의 이름 차례다
    names: [
      { name: 'main', at: 'D' },
      { name: 'exp', at: 'F' },
      { name: 'fix', at: 'G' },
    ],
    happenings: [
      { kind: 'delete', name: 'exp' },
      { kind: 'move', name: 'main', to: 'C' },
    ],
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Names point at commits. Commits: {n}',
      ko: '이름이 커밋을 가리킨다. 커밋: {n}',
      ja: '名前がコミットを指す。コミット: {n}',
      zh: '名字指向提交。提交数: {n}',
      ar: 'الأسماء تشير إلى الإيداعات. الإيداعات: {n}',
      es: 'Los nombres apuntan a commits. Commits: {n}',
      fr: 'Les noms pointent vers des commits. Commits : {n}',
      hi: 'नाम कमिट की ओर इशारा करते हैं। कमिट: {n}',
      id: 'Nama menunjuk ke commit. Commit: {n}',
      pt: 'Os nomes apontam para commits. Commits: {n}',
    },
    'caption.delete': {
      en: 'Deleted name {name}. Commits: {n}',
      ko: '이름 {name} 삭제. 커밋: {n}',
      ja: '名前 {name} を削除。コミット: {n}',
      zh: '删除名字 {name}。提交数: {n}',
      ar: 'حُذف الاسم {name}. الإيداعات: {n}',
      es: 'Nombre {name} borrado. Commits: {n}',
      fr: 'Nom {name} supprimé. Commits : {n}',
      hi: 'नाम {name} हटाया गया। कमिट: {n}',
      id: 'Nama {name} dihapus. Commit: {n}',
      pt: 'Nome {name} apagado. Commits: {n}',
    },
    'caption.move': {
      en: 'Moved {name} back: {from} → {to}. Commits: {n}',
      ko: '{name} 되돌림: {from} → {to}. 커밋: {n}',
      ja: '{name} を戻す: {from} → {to}。コミット: {n}',
      zh: '{name} 退回: {from} → {to}。提交数: {n}',
      ar: 'أُعيد {name}: {from} → {to}. الإيداعات: {n}',
      es: '{name} retrocede: {from} → {to}. Commits: {n}',
      fr: '{name} recule : {from} → {to}. Commits : {n}',
      hi: '{name} पीछे किया गया: {from} → {to}। कमिट: {n}',
      id: '{name} dimundurkan: {from} → {to}. Commit: {n}',
      pt: '{name} recua: {from} → {to}. Commits: {n}',
    },
    'caption.markFirst': {
      en: 'Cleanup: walking back from {name}. Marked: {commit}',
      ko: '치우기 — {name} 에서 거슬러 간다. 표시: {commit}',
      ja: '片付け — {name} からたどる。印: {commit}',
      zh: '清理 — 从 {name} 往回走。标记: {commit}',
      ar: 'التنظيف — الرجوع من {name}. عُلِّم: {commit}',
      es: 'Limpieza: se recorre hacia atrás desde {name}. Marcado: {commit}',
      fr: 'Nettoyage : on remonte depuis {name}. Marqué : {commit}',
      hi: 'सफ़ाई — {name} से पीछे की ओर। चिह्नित: {commit}',
      id: 'Pembersihan — telusur mundur dari {name}. Ditandai: {commit}',
      pt: 'Limpeza: recuando a partir de {name}. Marcado: {commit}',
    },
    'caption.markNext': {
      en: 'From {name}, on to the parent. Marked: {commit}',
      ko: '{name} 의 길, 부모로. 표시: {commit}',
      ja: '{name} から親へ。印: {commit}',
      zh: '从 {name} 走向父提交。标记: {commit}',
      ar: 'من {name} إلى الأب. عُلِّم: {commit}',
      es: 'Desde {name}, hacia el padre. Marcado: {commit}',
      fr: 'Depuis {name}, vers le parent. Marqué : {commit}',
      hi: '{name} से, पैरेंट की ओर। चिह्नित: {commit}',
      id: 'Dari {name}, lanjut ke induk. Ditandai: {commit}',
      pt: 'A partir de {name}, para o pai. Marcado: {commit}',
    },
    'caption.halt': {
      en: 'Next parent {commit} is already marked. This path stops.',
      ko: '다음 부모 {commit} — 이미 표시됨. 이 길은 멈춘다.',
      ja: '次の親 {commit} は印済み。この道はここで止まる。',
      zh: '下一个父提交 {commit} 已有标记。这条路停下。',
      ar: 'الأب التالي {commit} مُعلَّم مسبقًا. يتوقف هذا المسار.',
      es: 'El siguiente padre {commit} ya está marcado. Este camino se detiene.',
      fr: 'Le parent suivant {commit} est déjà marqué. Ce chemin s’arrête.',
      hi: 'अगला पैरेंट {commit} पहले से चिह्नित है। यह रास्ता रुकता है।',
      id: 'Induk berikutnya {commit} sudah ditandai. Jalur ini berhenti.',
      pt: 'O próximo pai {commit} já está marcado. Este caminho para.',
    },
    'caption.sweep': {
      en: 'Swept the unmarked: {gone}. Commits: {n}',
      ko: '표시 없는 커밋 치움: {gone}. 커밋: {n}',
      ja: '印のないコミットを片付け: {gone}。コミット: {n}',
      zh: '清除无标记的提交: {gone}。提交数: {n}',
      ar: 'أُزيلت غير المُعلَّمة: {gone}. الإيداعات: {n}',
      es: 'Se barren los no marcados: {gone}. Commits: {n}',
      fr: 'Non marqués balayés : {gone}. Commits : {n}',
      hi: 'बिना चिह्न वाले हटाए गए: {gone}। कमिट: {n}',
      id: 'Yang tak ditandai disapu: {gone}. Commit: {n}',
      pt: 'Varridos os não marcados: {gone}. Commits: {n}',
    },
    'caption.tally': {
      en: 'Marked: {m} · Swept: {k}',
      ko: '표시: {m} · 치움: {k}',
      ja: '印: {m} · 片付け: {k}',
      zh: '标记: {m} · 清除: {k}',
      ar: 'مُعلَّمة: {m} · أُزيلت: {k}',
      es: 'Marcados: {m} · Barridos: {k}',
      fr: 'Marqués : {m} · Balayés : {k}',
      hi: 'चिह्नित: {m} · हटाए गए: {k}',
      id: 'Ditandai: {m} · Disapu: {k}',
      pt: 'Marcados: {m} · Varridos: {k}',
    },
  },
  blocks: {
    stage: { type: 'unreachable-snapshot-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
