import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece 앞질러 가져오기 (prefetching)
 *
 * 질문: 차례로 읽을 때 메모리의 기다림을 어떻게 숨기는가?
 *
 * 원소 열여섯을 차례로 읽는 두 줄기를 같은 시계로 돌린다. 프리페치가 없으면 줄 경계마다
 * 커서가 서서 줄이 오기를 기다린다. 다음 줄 프리페치는 지금 줄을 읽기 시작하는 사이클에
 * 다음 줄을 불러, 지금 줄을 다 읽을 즈음 다음 줄이 이미 와 있다.
 */
export const fetchAheadFacet: FacetJson = {
  id: 'facet:fetchAhead',
  title: {
    en: 'Fetching ahead',
    ko: '앞질러 가져오기',
    ja: '先回りして読み込む',
    zh: '提前取数',
    ar: 'الجلب المسبق',
    es: 'Traer por adelantado',
    fr: 'Charger en avance',
    hi: 'पहले से लाना',
    id: 'Mengambil lebih dulu',
    pt: 'Buscar adiantado',
  },
  description: {
    en: 'Reading elements in order: when the next line is requested as soon as the current one starts, it arrives before the cursor gets there.',
    ko: '원소를 차례로 읽을 때, 지금 줄을 읽기 시작하자마자 다음 줄을 부르면 커서가 닿기 전에 그 줄이 와 있다.',
    ja: '要素を順に読むとき、今の行を読み始めた時点で次の行を要求すれば、カーソルが着く前にその行は届いている。',
    zh: '按顺序读取元素时，一开始读当前行就请求下一行，光标到达之前那一行已经到了。',
    ar: 'عند قراءة العناصر بالترتيب، إذا طُلب السطر التالي فور بدء قراءة السطر الحالي فإنه يصل قبل أن يبلغه المؤشر.',
    es: 'Al leer elementos en orden, si la línea siguiente se pide en cuanto empieza la actual, llega antes que el cursor.',
    fr: 'En lisant les éléments dans l’ordre, si la ligne suivante est demandée dès le début de la ligne courante, elle arrive avant le curseur.',
    hi: 'तत्वों को क्रम से पढ़ते समय, अगर मौजूदा लाइन शुरू होते ही अगली लाइन माँग ली जाए, तो कर्सर के पहुँचने से पहले वह आ चुकी होती है।',
    id: 'Saat membaca elemen berurutan, jika baris berikutnya diminta begitu baris sekarang mulai dibaca, baris itu sudah tiba sebelum kursor sampai.',
    pt: 'Ao ler elementos em ordem, se a próxima linha é pedida assim que a atual começa, ela chega antes do cursor.',
  },
  algorithm: 'module:fetchAhead',
  scene: 'module:fetchAheadScene',
  initialData: {
    type: 'fetch-ahead',
    stepMs: 500,
    elements: 16,
    lineSize: 4,
    latency: 4,
    policies: ['none', 'nextLine'],
  },
  shuffleOnReset: false,
  messages: {
    'lane.none': {
      en: 'No prefetch',
      ko: '프리페치 없음',
      ja: 'プリフェッチなし',
      zh: '无预取',
      ar: 'بلا جلب مسبق',
      es: 'Sin precarga',
      fr: 'Sans préchargement',
      hi: 'बिना प्रीफ़ेच',
      id: 'Tanpa prefetch',
      pt: 'Sem pré-busca',
    },
    'lane.nextLine': {
      en: 'Next-line prefetch',
      ko: '다음 줄 프리페치',
      ja: '次の行をプリフェッチ',
      zh: '预取下一行',
      ar: 'جلب السطر التالي مسبقًا',
      es: 'Precarga de la línea siguiente',
      fr: 'Préchargement de la ligne suivante',
      hi: 'अगली लाइन का प्रीफ़ेच',
      id: 'Prefetch baris berikutnya',
      pt: 'Pré-busca da próxima linha',
    },
    'status.read': {
      en: 'Reading element {e}.',
      ko: '읽는 원소: {e}.',
      ja: '読んでいる要素: {e}。',
      zh: '正在读元素 {e}。',
      ar: 'يقرأ العنصر {e}.',
      es: 'Leyendo el elemento {e}.',
      fr: 'Lecture de l’élément {e}.',
      hi: 'तत्व {e} पढ़ा जा रहा है।',
      id: 'Membaca elemen {e}.',
      pt: 'Lendo o elemento {e}.',
    },
    'status.wait': {
      en: 'Waiting for line {l}.',
      ko: '기다리는 줄: {l}.',
      ja: '待っている行: {l}。',
      zh: '正在等第 {l} 行。',
      ar: 'بانتظار السطر {l}.',
      es: 'Esperando la línea {l}.',
      fr: 'En attente de la ligne {l}.',
      hi: 'लाइन {l} का इंतज़ार।',
      id: 'Menunggu baris {l}.',
      pt: 'Esperando a linha {l}.',
    },
    'status.done': {
      en: 'Done: {total} cycles, {waited} of them waiting.',
      ko: '끝. 총 사이클 {total}, 그중 기다림 {waited}.',
      ja: '完了。総サイクル {total}、うち待ち {waited}。',
      zh: '完成：共 {total} 个周期，其中等待 {waited} 个。',
      ar: 'انتهى: {total} دورة، منها {waited} انتظار.',
      es: 'Listo: {total} ciclos, {waited} de ellos esperando.',
      fr: 'Terminé : {total} cycles, dont {waited} d’attente.',
      hi: 'पूरा: {total} चक्र, जिनमें {waited} इंतज़ार।',
      id: 'Selesai: {total} siklus, {waited} di antaranya menunggu.',
      pt: 'Pronto: {total} ciclos, {waited} deles esperando.',
    },
    'label.memory': {
      en: 'memory',
      ko: '메모리',
      ja: 'メモリ',
      zh: '内存',
      ar: 'الذاكرة',
      es: 'memoria',
      fr: 'mémoire',
      hi: 'मेमोरी',
      id: 'memori',
      pt: 'memória',
    },
    'label.cache': {
      en: 'cache',
      ko: '캐시',
      ja: 'キャッシュ',
      zh: '缓存',
      ar: 'الذاكرة المخبئية',
      es: 'caché',
      fr: 'cache',
      hi: 'कैश',
      id: 'cache',
      pt: 'cache',
    },
    'label.cycles': {
      en: 'cycles',
      ko: '사이클',
      ja: 'サイクル',
      zh: '周期',
      ar: 'الدورات',
      es: 'ciclos',
      fr: 'cycles',
      hi: 'चक्र',
      id: 'siklus',
      pt: 'ciclos',
    },
    'label.line': {
      en: 'line {l}',
      ko: '줄 {l}',
      ja: '行 {l}',
      zh: '第 {l} 行',
      ar: 'السطر {l}',
      es: 'línea {l}',
      fr: 'ligne {l}',
      hi: 'लाइन {l}',
      id: 'baris {l}',
      pt: 'linha {l}',
    },
    'label.clock': {
      en: 'cycle {c}',
      ko: '사이클 {c}',
      ja: 'サイクル {c}',
      zh: '周期 {c}',
      ar: 'الدورة {c}',
      es: 'ciclo {c}',
      fr: 'cycle {c}',
      hi: 'चक्र {c}',
      id: 'siklus {c}',
      pt: 'ciclo {c}',
    },
  },
  blocks: {
    stage: { type: 'fetch-ahead-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
