import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 두 객체가 서로를 가리키면 참조 계수는 0 이 되는가?
 *
 * 줄 걸음 여섯 (걸음 0 을 더해 일곱). 수가 0 이 되는 줄이 오면 그 뒤에 치움 걸음이
 * 붙지만 이 데이터에서는 한 번도 생기지 않는다 — 마지막 줄 걸음이 곧 끝의 모습이다.
 */
export const referenceCycleFacet: FacetJson = {
  id: 'facet:referenceCycle',
  title: {
    en: 'Reference cycle',
    ko: '순환 참조',
    ja: '循環参照',
    zh: '循环引用',
    ar: 'المرجع الدائري',
    es: 'Referencia circular',
    fr: 'Référence circulaire',
    hi: 'चक्रीय संदर्भ',
    id: 'Referensi melingkar',
    pt: 'Referência circular',
  },
  description: {
    en: 'Two objects that point at each other keep a count of 1 each after every name lets go, so the count never reaches 0.',
    ko: '서로 가리키는 두 객체는 이름이 모두 놓아도 서로에게 받은 1 이 남아, 수가 0 에 닿지 않는다.',
    ja: '互いを指す二つのオブジェクトは、名前がすべて手放しても相手から受けた 1 が残り、カウントは 0 にならない。',
    zh: '互相指向的两个对象，即使所有名字都放开，彼此给的 1 仍然留着，计数到不了 0。',
    ar: 'كائنان يشير كل منهما إلى الآخر يبقى لكل منهما عدد 1 بعد أن تتركهما كل الأسماء، فلا يصل العدد إلى 0.',
    es: 'Dos objetos que se apuntan entre sí conservan una cuenta de 1 cada uno aunque todos los nombres los suelten, así que la cuenta nunca llega a 0.',
    fr: 'Deux objets qui pointent l’un vers l’autre gardent chacun un compte de 1 même quand tous les noms les lâchent : le compte n’atteint jamais 0.',
    hi: 'एक-दूसरे की ओर इशारा करते दो ऑब्जेक्ट, सभी नामों के छोड़ देने पर भी एक-दूसरे से मिला 1 रखते हैं, इसलिए गिनती 0 तक नहीं पहुँचती।',
    id: 'Dua objek yang saling menunjuk tetap punya hitungan 1 masing-masing meski semua nama melepasnya, jadi hitungan tak pernah mencapai 0.',
    pt: 'Dois objetos que apontam um para o outro mantêm contagem 1 cada mesmo depois que todos os nomes os soltam, então a contagem nunca chega a 0.',
  },
  algorithm: 'module:referenceCycle',
  scene: 'module:referenceCycleScene',
  initialData: {
    type: 'reference-cycle',
    stepMs: 1700,
    types: [{ name: 'Node', fields: ['next'] }],
    lines: [
      { indent: 0, text: 'let a = new Node()', stmt: { k: 'assign', to: 'a', declare: true, value: { new: 'Node' } } },
      { indent: 0, text: 'let b = new Node()', stmt: { k: 'assign', to: 'b', declare: true, value: { new: 'Node' } } },
      { indent: 0, text: 'a.next = b', stmt: { k: 'setField', obj: 'a', field: 'next', value: { var: 'b' } } },
      { indent: 0, text: 'b.next = a', stmt: { k: 'setField', obj: 'b', field: 'next', value: { var: 'a' } } },
      { indent: 0, text: 'a = null', stmt: { k: 'assign', to: 'a', value: { null: true } } },
      { indent: 0, text: 'b = null', stmt: { k: 'assign', to: 'b', value: { null: true } } },
    ],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'reference-cycle-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'Start. No line has run yet; the name cells are empty.',
      ko: '시작. 아직 아무 줄도 돌지 않았다 — 이름 칸은 비어 있다.',
      ja: 'スタート。まだどの行も実行されていない。名前のセルは空だ。',
      zh: '开始。还没有执行任何一行，名字的格子是空的。',
      ar: 'البداية. لم يُنفَّذ أي سطر بعد، وخانات الأسماء فارغة.',
      es: 'Inicio. Ninguna línea ejecutada; las celdas de nombres están vacías.',
      fr: 'Début. Aucune ligne exécutée ; les cases des noms sont vides.',
      hi: 'शुरुआत। अभी कोई पंक्ति नहीं चली; नामों के खाने खाली हैं।',
      id: 'Mulai. Belum ada baris yang dijalankan; sel nama masih kosong.',
      pt: 'Início. Nenhuma linha executada; as células dos nomes estão vazias.',
    },
    'caption.create': {
      en: 'New object {obj}. {by} → {obj}. Count of {obj}: {n}',
      ko: '새 객체 {obj}. {by} → {obj}. {obj} 의 수: {n}',
      ja: '新しいオブジェクト {obj}。{by} → {obj}。{obj} の参照数: {n}',
      zh: '新对象 {obj}。{by} → {obj}。{obj} 的计数: {n}',
      ar: 'كائن جديد {obj}. {by} → {obj}. عدد {obj}: {n}',
      es: 'Objeto nuevo {obj}. {by} → {obj}. Cuenta de {obj}: {n}',
      fr: 'Nouvel objet {obj}. {by} → {obj}. Compte de {obj} : {n}',
      hi: 'नया ऑब्जेक्ट {obj}। {by} → {obj}। {obj} की गिनती: {n}',
      id: 'Objek baru {obj}. {by} → {obj}. Hitungan {obj}: {n}',
      pt: 'Novo objeto {obj}. {by} → {obj}. Contagem de {obj}: {n}',
    },
    'caption.hold': {
      en: '{by} → {obj}. Count of {obj}: {n}',
      ko: '{by} → {obj}. {obj} 의 수: {n}',
      ja: '{by} → {obj}。{obj} の参照数: {n}',
      zh: '{by} → {obj}。{obj} 的计数: {n}',
      ar: '{by} → {obj}. عدد {obj}: {n}',
      es: '{by} → {obj}. Cuenta de {obj}: {n}',
      fr: '{by} → {obj}. Compte de {obj} : {n}',
      hi: '{by} → {obj}। {obj} की गिनती: {n}',
      id: '{by} → {obj}. Hitungan {obj}: {n}',
      pt: '{by} → {obj}. Contagem de {obj}: {n}',
    },
    'caption.release': {
      en: 'Let go: {by} → {obj}. Count of {obj}: {n}',
      ko: '놓음: {by} → {obj}. {obj} 의 수: {n}',
      ja: '手放した: {by} → {obj}。{obj} の参照数: {n}',
      zh: '放开: {by} → {obj}。{obj} 的计数: {n}',
      ar: 'تُرِك: {by} → {obj}. عدد {obj}: {n}',
      es: 'Suelta: {by} → {obj}. Cuenta de {obj}: {n}',
      fr: 'Lâché : {by} → {obj}. Compte de {obj} : {n}',
      hi: 'छोड़ा: {by} → {obj}। {obj} की गिनती: {n}',
      id: 'Dilepas: {by} → {obj}. Hitungan {obj}: {n}',
      pt: 'Solto: {by} → {obj}. Contagem de {obj}: {n}',
    },
    'caption.reclaim': {
      en: 'Count reached 0 — reclaimed: {obj}',
      ko: '수가 0 — 치움: {obj}',
      ja: 'カウントが 0 — 回収: {obj}',
      zh: '计数为 0 — 回收: {obj}',
      ar: 'بلغ العدد 0 — استُرِدّ: {obj}',
      es: 'La cuenta llegó a 0 — recogido: {obj}',
      fr: 'Le compte atteint 0 — récupéré : {obj}',
      hi: 'गिनती 0 हुई — हटाया: {obj}',
      id: 'Hitungan mencapai 0 — dibereskan: {obj}',
      pt: 'A contagem chegou a 0 — recolhido: {obj}',
    },
    'caption.line': {
      en: 'Ran: {code}',
      ko: '실행: {code}',
      ja: '実行: {code}',
      zh: '执行: {code}',
      ar: 'نُفِّذ: {code}',
      es: 'Ejecutado: {code}',
      fr: 'Exécuté : {code}',
      hi: 'चला: {code}',
      id: 'Dijalankan: {code}',
      pt: 'Executado: {code}',
    },
    'label.stack': {
      en: 'Stack',
      ko: '스택',
      ja: 'スタック',
      zh: '栈',
      ar: 'المكدس',
      es: 'Pila',
      fr: 'Pile',
      hi: 'स्टैक',
      id: 'Stack',
      pt: 'Pilha',
    },
    'label.heap': {
      en: 'Heap',
      ko: '힙',
      ja: 'ヒープ',
      zh: '堆',
      ar: 'الكومة',
      es: 'Heap',
      fr: 'Tas',
      hi: 'हीप',
      id: 'Heap',
      pt: 'Heap',
    },
    'label.status': {
      en: 'Names pointing at an object: {names} · Objects reclaimed: {gone}',
      ko: '객체를 가리키는 이름: {names} · 치운 객체: {gone}',
      ja: 'オブジェクトを指す名前: {names} · 回収したオブジェクト: {gone}',
      zh: '指向对象的名字: {names} · 已回收的对象: {gone}',
      ar: 'أسماء تشير إلى كائن: {names} · كائنات مُستردّة: {gone}',
      es: 'Nombres que apuntan a un objeto: {names} · Objetos recogidos: {gone}',
      fr: 'Noms qui pointent vers un objet : {names} · Objets récupérés : {gone}',
      hi: 'किसी ऑब्जेक्ट की ओर इशारा करते नाम: {names} · हटाए गए ऑब्जेक्ट: {gone}',
      id: 'Nama yang menunjuk objek: {names} · Objek yang dibereskan: {gone}',
      pt: 'Nomes que apontam para um objeto: {names} · Objetos recolhidos: {gone}',
    },
  },
};
