import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 포인터를 역참조하면 무슨 일이 일어나는가 — 두 번 하면?
 *
 * 칸에 적힌 수를 주소로 읽고 그 칸으로 건너가 값을 읽는다. 한 번 따라가면 한 번,
 * 두 번 따라가면 두 번 건너간 뒤에야 42 에 닿는다.
 */
export const pointerDereferenceFacet: FacetJson = {
  id: 'facet:pointerDereference',
  title: {
    en: 'Following a pointer — once, then twice',
    ko: '포인터 따라가기 — 한 번, 그리고 두 번',
    ja: 'ポインタをたどる — 一回、そして二回',
    zh: '沿着指针走 — 一次，再两次',
    ar: 'تتبّع المؤشر — مرة، ثم مرتين',
    es: 'Seguir un puntero — una vez, luego dos',
    fr: 'Suivre un pointeur — une fois, puis deux',
    hi: 'पॉइंटर का पीछा — एक बार, फिर दो बार',
    id: 'Mengikuti pointer — sekali, lalu dua kali',
    pt: 'Seguir um ponteiro — uma vez, depois duas',
  },
  description: {
    en: 'valueAt reads the number in a cell as an address and crosses to that cell. Nested twice, it crosses twice before it reaches the value.',
    ko: 'valueAt 은 칸에 든 수를 주소로 읽고 그 칸으로 건너간다. 두 겹이면 두 번 건너간 뒤에야 값에 닿는다.',
    ja: 'valueAt はセルの数をアドレスとして読み、そのセルへ渡る。二重なら二回渡ってからやっと値に届く。',
    zh: 'valueAt 把格子里的数当作地址读出，跳到那个格子。套两层，就要跳两次才到达值。',
    ar: 'تقرأ valueAt الرقم في الخلية كعنوان وتعبر إلى تلك الخلية. إذا تداخلت مرتين تعبر مرتين قبل أن تصل إلى القيمة.',
    es: 'valueAt lee el número de una celda como dirección y cruza a esa celda. Anidado dos veces, cruza dos veces antes de llegar al valor.',
    fr: "valueAt lit le nombre d'une case comme une adresse et passe à cette case. Imbriqué deux fois, il passe deux fois avant d'atteindre la valeur.",
    hi: 'valueAt खाने की संख्या को पते की तरह पढ़ता है और उस खाने तक जाता है। दो बार लिपटा हो तो मान तक पहुँचने से पहले दो बार छलांग लगाता है।',
    id: 'valueAt membaca angka di sebuah sel sebagai alamat lalu menyeberang ke sel itu. Bersarang dua kali, ia menyeberang dua kali sebelum sampai ke nilainya.',
    pt: 'valueAt lê o número de uma célula como endereço e atravessa para essa célula. Aninhado duas vezes, atravessa duas vezes antes de chegar ao valor.',
  },
  algorithm: 'module:pointerDereference',
  scene: 'module:pointerDereferenceScene',
  initialData: {
    type: 'pointer-dereference',
    stepMs: 1500,
    stackBase: 500,
    lines: [
      {
        indent: 0,
        text: 'let x = 42',
        stmt: { k: 'assign', to: 'x', declare: true, value: { num: 42 } },
      },
      {
        indent: 0,
        text: 'let p = address(x)',
        stmt: { k: 'assign', to: 'p', declare: true, value: { call: 'address', args: [{ var: 'x' }] } },
      },
      {
        indent: 0,
        text: 'let pp = address(p)',
        stmt: { k: 'assign', to: 'pp', declare: true, value: { call: 'address', args: [{ var: 'p' }] } },
      },
      {
        indent: 0,
        text: 'show valueAt(p)',
        stmt: { k: 'show', value: { call: 'valueAt', args: [{ var: 'p' }] } },
      },
      {
        indent: 0,
        text: 'show valueAt(valueAt(pp))',
        stmt: {
          k: 'show',
          value: { call: 'valueAt', args: [{ call: 'valueAt', args: [{ var: 'pp' }] }] },
        },
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Each name has its own cell. The cells are still empty.',
      ko: '이름마다 제 칸이 있다. 칸은 아직 비어 있다.',
      ja: '名前ごとに自分のセルがある。セルはまだ空だ。',
      zh: '每个名字都有自己的格子。格子还是空的。',
      ar: 'لكل اسم خليته الخاصة. الخلايا ما زالت فارغة.',
      es: 'Cada nombre tiene su propia celda. Las celdas aún están vacías.',
      fr: 'Chaque nom a sa propre case. Les cases sont encore vides.',
      hi: 'हर नाम का अपना खाना है। खाने अभी खाली हैं।',
      id: 'Setiap nama punya selnya sendiri. Sel-selnya masih kosong.',
      pt: 'Cada nome tem sua própria célula. As células ainda estão vazias.',
    },
    'caption.storeValue': {
      en: 'The cell of {name} now holds {value}.',
      ko: '{name} 의 칸에 들어간 값: {value}',
      ja: '{name} のセルに入った値: {value}',
      zh: '{name} 的格子里的值: {value}',
      ar: 'خلية {name} تحمل الآن: {value}',
      es: 'La celda de {name} ahora contiene {value}.',
      fr: 'La case de {name} contient maintenant {value}.',
      hi: '{name} के खाने में अब मान: {value}',
      id: 'Sel {name} kini berisi {value}.',
      pt: 'A célula de {name} agora contém {value}.',
    },
    'caption.storeAddress': {
      en: 'address({src}) gives {addr}, the number of its cell. It goes into the cell of {name}.',
      ko: 'address({src}) 의 결과: 그 칸의 번호 {addr}. 이 수를 {name} 의 칸에 넣는다.',
      ja: 'address({src}) の結果: そのセルの番号 {addr}。この数を {name} のセルに入れる。',
      zh: 'address({src}) 的结果: 那个格子的编号 {addr}。把这个数放进 {name} 的格子。',
      ar: 'address({src}) يعطي {addr}، رقم خليته. يوضع في خلية {name}.',
      es: 'address({src}) da {addr}, el número de su celda. Va a la celda de {name}.',
      fr: 'address({src}) donne {addr}, le numéro de sa case. Il va dans la case de {name}.',
      hi: 'address({src}) देता है {addr}, उसके खाने का नंबर। यह {name} के खाने में जाता है।',
      id: 'address({src}) memberi {addr}, nomor selnya. Nilai itu masuk ke sel {name}.',
      pt: 'address({src}) dá {addr}, o número da sua célula. Ele vai para a célula de {name}.',
    },
    'caption.read': {
      en: 'Read the cell of {name}: {value}. This number is used as an address.',
      ko: '{name} 의 칸에서 읽은 수: {value}. 이 수를 주소로 쓴다.',
      ja: '{name} のセルから読んだ数: {value}。この数をアドレスとして使う。',
      zh: '从 {name} 的格子读到的数: {value}。把这个数当作地址。',
      ar: 'قراءة خلية {name}: {value}. يُستخدم هذا الرقم عنوانًا.',
      es: 'Se lee la celda de {name}: {value}. Este número se usa como dirección.',
      fr: "Lecture de la case de {name} : {value}. Ce nombre sert d'adresse.",
      hi: '{name} का खाना पढ़ा: {value}। यह संख्या पते की तरह इस्तेमाल होती है।',
      id: 'Baca sel {name}: {value}. Angka ini dipakai sebagai alamat.',
      pt: 'Lê-se a célula de {name}: {value}. Este número é usado como endereço.',
    },
    'caption.hop': {
      en: 'Hop {n}: over to address {addr}. Its cell holds {value}.',
      ko: '건넘 {n}: 주소 {addr} 의 칸으로. 그 칸의 내용: {value}',
      ja: 'ホップ {n}: アドレス {addr} のセルへ。中身: {value}',
      zh: '第 {n} 跳: 到地址 {addr} 的格子。内容: {value}',
      ar: 'القفزة {n}: إلى العنوان {addr}. محتوى الخلية: {value}',
      es: 'Salto {n}: a la dirección {addr}. Su celda contiene {value}.',
      fr: "Saut {n} : vers l'adresse {addr}. Sa case contient {value}.",
      hi: 'छलांग {n}: पता {addr} पर। उसके खाने में: {value}',
      id: 'Lompatan {n}: ke alamat {addr}. Selnya berisi {value}.',
      pt: 'Salto {n}: para o endereço {addr}. Sua célula contém {value}.',
    },
    'caption.hopLast': {
      en: 'Hop {n}: over to address {addr}. Its cell holds {value}. Output: {value}',
      ko: '건넘 {n}: 주소 {addr} 의 칸으로. 그 칸의 내용: {value}. 출력: {value}',
      ja: 'ホップ {n}: アドレス {addr} のセルへ。中身: {value}。出力: {value}',
      zh: '第 {n} 跳: 到地址 {addr} 的格子。内容: {value}。输出: {value}',
      ar: 'القفزة {n}: إلى العنوان {addr}. محتوى الخلية: {value}. الناتج: {value}',
      es: 'Salto {n}: a la dirección {addr}. Su celda contiene {value}. Salida: {value}',
      fr: "Saut {n} : vers l'adresse {addr}. Sa case contient {value}. Sortie : {value}",
      hi: 'छलांग {n}: पता {addr} पर। उसके खाने में: {value}। आउटपुट: {value}',
      id: 'Lompatan {n}: ke alamat {addr}. Selnya berisi {value}. Keluaran: {value}',
      pt: 'Salto {n}: para o endereço {addr}. Sua célula contém {value}. Saída: {value}',
    },
    'label.addr': {
      en: 'address {addr}',
      ko: '주소 {addr}',
      ja: 'アドレス {addr}',
      zh: '地址 {addr}',
      ar: 'العنوان {addr}',
      es: 'dirección {addr}',
      fr: 'adresse {addr}',
      hi: 'पता {addr}',
      id: 'alamat {addr}',
      pt: 'endereço {addr}',
    },
    'label.hops': {
      en: 'hops: {n}',
      ko: '건넘: {n}',
      ja: 'ホップ: {n}',
      zh: '跳转: {n}',
      ar: 'القفزات: {n}',
      es: 'saltos: {n}',
      fr: 'sauts : {n}',
      hi: 'छलांगें: {n}',
      id: 'lompatan: {n}',
      pt: 'saltos: {n}',
    },
    'label.output': {
      en: 'output: {value}',
      ko: '출력: {value}',
      ja: '出力: {value}',
      zh: '输出: {value}',
      ar: 'الناتج: {value}',
      es: 'salida: {value}',
      fr: 'sortie : {value}',
      hi: 'आउटपुट: {value}',
      id: 'keluaran: {value}',
      pt: 'saída: {value}',
    },
  },
  blocks: {
    stage: { type: 'pointer-dereference-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
