/**
 * @piece
 * 평소 속도 한도가 초당 하나인데, 한동안 조용하던 클라이언트가 한꺼번에 몰아 보내면 몇이 지나가는가.
 *
 * 동사: 쌓였다가 한꺼번에 빠진다 — 1 초마다 토큰이 통에 쌓이고, 가득이면 넘쳐 버려진다.
 * 몰려온 요청이 쌓인 토큰을 한 번에 들고 나가고, 토큰이 없는 요청은 거절된다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const tokenBucketFacet: FacetJson = {
  id: 'facet:tokenBucket',
  title: {
    en: 'Token bucket',
    ko: '토큰 버킷',
    ja: 'トークンバケット',
    zh: '令牌桶',
    ar: 'دلو الرموز',
    es: 'Cubo de fichas',
    fr: 'Seau à jetons',
    hi: 'टोकन बकेट',
    id: 'Ember token',
    pt: 'Balde de fichas',
  },
  description: {
    en: 'Tokens drip into the bucket one per second until it is full. A burst of requests spends every saved token at once; requests without a token are rejected.',
    ko: '토큰이 1 초마다 하나씩 통에 쌓여 가득 찰 때까지 모인다. 몰려온 요청은 쌓인 토큰을 한꺼번에 쓰고, 토큰을 못 얻은 요청은 거절된다.',
    ja: 'トークンは満杯になるまで 1 秒ごとに一つずつバケットにたまる。まとめて届いたリクエストはためたトークンを一度に使い、トークンを得られないリクエストは拒否される。',
    zh: '令牌每秒一个落入桶中，直到装满。一阵突发请求一次用掉所有攒下的令牌；拿不到令牌的请求被拒绝。',
    ar: 'تتساقط الرموز في الدلو رمزًا كل ثانية حتى يمتلئ. دفعة الطلبات تنفق كل الرموز المدّخرة دفعة واحدة، والطلبات التي لا تجد رمزًا تُرفض.',
    es: 'Las fichas caen al cubo una por segundo hasta llenarlo. Una ráfaga de peticiones gasta de golpe todas las fichas guardadas; las que no consiguen ficha se rechazan.',
    fr: 'Les jetons tombent dans le seau un par seconde jusqu’à ce qu’il soit plein. Une rafale de requêtes dépense d’un coup tous les jetons accumulés ; celles sans jeton sont refusées.',
    hi: 'टोकन हर सेकंड एक-एक करके बकेट में गिरते हैं जब तक वह भर न जाए। अनुरोधों की बौछार जमा सारे टोकन एक साथ खर्च करती है; जिन अनुरोधों को टोकन नहीं मिलता वे अस्वीकार होते हैं।',
    id: 'Token menetes ke ember satu per detik sampai penuh. Serbuan permintaan menghabiskan semua token yang tersimpan sekaligus; permintaan tanpa token ditolak.',
    pt: 'As fichas caem no balde uma por segundo até enchê-lo. Uma rajada de pedidos gasta de uma vez todas as fichas guardadas; os pedidos sem ficha são rejeitados.',
  },
  algorithm: 'module:tokenBucket',
  scene: 'module:tokenBucketScene',
  initialData: {
    type: 'token-bucket',
    stepMs: 1300,
    capacity: 4,
    refillPerSecond: 1,
    startTokens: 0,
    arrivals: [
      { at: 6, count: 6 },
      { at: 7, count: 1 },
      { at: 8, count: 2 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.time': {
      en: 'Time: {sec} s',
      ko: '시각: {sec} 초',
      ja: '時刻: {sec} 秒',
      zh: '时刻: {sec} 秒',
      ar: 'الزمن: {sec} ث',
      es: 'Tiempo: {sec} s',
      fr: 'Temps : {sec} s',
      hi: 'समय: {sec} से.',
      id: 'Waktu: {sec} dtk',
      pt: 'Tempo: {sec} s',
    },
    'label.requests': {
      en: 'Requests',
      ko: '요청',
      ja: 'リクエスト',
      zh: '请求',
      ar: 'الطلبات',
      es: 'Peticiones',
      fr: 'Requêtes',
      hi: 'अनुरोध',
      id: 'Permintaan',
      pt: 'Pedidos',
    },
    'label.refill': {
      en: 'Refill: {n} per second',
      ko: '채움: 초당 {n}',
      ja: '補充: 毎秒 {n}',
      zh: '补充: 每秒 {n}',
      ar: 'التعبئة: {n} في الثانية',
      es: 'Recarga: {n} por segundo',
      fr: 'Recharge : {n} par seconde',
      hi: 'भराई: प्रति सेकंड {n}',
      id: 'Isi ulang: {n} per detik',
      pt: 'Recarga: {n} por segundo',
    },
    'label.tokens': {
      en: 'Tokens: {n} / {cap}',
      ko: '토큰: {n} / {cap}',
      ja: 'トークン: {n} / {cap}',
      zh: '令牌: {n} / {cap}',
      ar: 'الرموز: {n} / {cap}',
      es: 'Fichas: {n} / {cap}',
      fr: 'Jetons : {n} / {cap}',
      hi: 'टोकन: {n} / {cap}',
      id: 'Token: {n} / {cap}',
      pt: 'Fichas: {n} / {cap}',
    },
    'label.spilled': {
      en: 'Spilled: {n}',
      ko: '버림: {n}',
      ja: 'あふれ: {n}',
      zh: '溢出: {n}',
      ar: 'المنسكب: {n}',
      es: 'Derramadas: {n}',
      fr: 'Débordés : {n}',
      hi: 'छलके: {n}',
      id: 'Tumpah: {n}',
      pt: 'Derramadas: {n}',
    },
    'label.rejected': {
      en: 'Rejected: {n}',
      ko: '거절: {n}',
      ja: '拒否: {n}',
      zh: '拒绝: {n}',
      ar: 'المرفوض: {n}',
      es: 'Rechazadas: {n}',
      fr: 'Refusées : {n}',
      hi: 'अस्वीकृत: {n}',
      id: 'Ditolak: {n}',
      pt: 'Rejeitados: {n}',
    },
    'label.passedPerSec': {
      en: 'Passed per second',
      ko: '초마다 지나간 수',
      ja: '毎秒の通過数',
      zh: '每秒通过数',
      ar: 'العابر في كل ثانية',
      es: 'Pasadas por segundo',
      fr: 'Passées par seconde',
      hi: 'हर सेकंड पार हुए',
      id: 'Lolos per detik',
      pt: 'Passaram por segundo',
    },
    'label.rate': {
      en: 'Refill rate',
      ko: '채움 빠르기',
      ja: '補充の速さ',
      zh: '补充速率',
      ar: 'معدل التعبئة',
      es: 'Ritmo de recarga',
      fr: 'Rythme de recharge',
      hi: 'भराई की दर',
      id: 'Laju isi ulang',
      pt: 'Ritmo de recarga',
    },
    'caption.start': {
      en: 'Time 0. Tokens in the bucket: {n}.',
      ko: '시각 0. 통 안의 토큰: {n}.',
      ja: '時刻 0。バケットのトークン: {n}。',
      zh: '时刻 0。桶中令牌: {n}。',
      ar: 'الزمن 0. الرموز في الدلو: {n}.',
      es: 'Tiempo 0. Fichas en el cubo: {n}.',
      fr: 'Temps 0. Jetons dans le seau : {n}.',
      hi: 'समय 0. बकेट में टोकन: {n}.',
      id: 'Waktu 0. Token di ember: {n}.',
      pt: 'Tempo 0. Fichas no balde: {n}.',
    },
    'caption.fill': {
      en: 'Refill: +{k}. Tokens in the bucket: {n}.',
      ko: '채움: +{k}. 통 안의 토큰: {n}.',
      ja: '補充: +{k}。バケットのトークン: {n}。',
      zh: '补充: +{k}。桶中令牌: {n}。',
      ar: 'التعبئة: +{k}. الرموز في الدلو: {n}.',
      es: 'Recarga: +{k}. Fichas en el cubo: {n}.',
      fr: 'Recharge : +{k}. Jetons dans le seau : {n}.',
      hi: 'भराई: +{k}. बकेट में टोकन: {n}.',
      id: 'Isi ulang: +{k}. Token di ember: {n}.',
      pt: 'Recarga: +{k}. Fichas no balde: {n}.',
    },
    'caption.fillOnly': {
      en: 'Refill: +{k}.',
      ko: '채움: +{k}.',
      ja: '補充: +{k}。',
      zh: '补充: +{k}。',
      ar: 'التعبئة: +{k}.',
      es: 'Recarga: +{k}.',
      fr: 'Recharge : +{k}.',
      hi: 'भराई: +{k}.',
      id: 'Isi ulang: +{k}.',
      pt: 'Recarga: +{k}.',
    },
    'caption.spill': {
      en: 'The bucket is full. Tokens spilled: {k}.',
      ko: '통이 가득 찼다. 넘쳐 버린 토큰: {k}.',
      ja: 'バケットは満杯。あふれたトークン: {k}。',
      zh: '桶已满。溢出的令牌: {k}。',
      ar: 'الدلو ممتلئ. الرموز المنسكبة: {k}.',
      es: 'El cubo está lleno. Fichas derramadas: {k}.',
      fr: 'Le seau est plein. Jetons débordés : {k}.',
      hi: 'बकेट भरा है. छलके टोकन: {k}.',
      id: 'Ember penuh. Token tumpah: {k}.',
      pt: 'O balde está cheio. Fichas derramadas: {k}.',
    },
    'caption.fillSpill': {
      en: 'Refill: +{k}. The bucket is full. Tokens spilled: {s}.',
      ko: '채움: +{k}. 통이 가득 찼다. 넘쳐 버린 토큰: {s}.',
      ja: '補充: +{k}。バケットは満杯。あふれたトークン: {s}。',
      zh: '补充: +{k}。桶已满。溢出的令牌: {s}。',
      ar: 'التعبئة: +{k}. الدلو ممتلئ. الرموز المنسكبة: {s}.',
      es: 'Recarga: +{k}. El cubo está lleno. Fichas derramadas: {s}.',
      fr: 'Recharge : +{k}. Le seau est plein. Jetons débordés : {s}.',
      hi: 'भराई: +{k}. बकेट भरा है. छलके टोकन: {s}.',
      id: 'Isi ulang: +{k}. Ember penuh. Token tumpah: {s}.',
      pt: 'Recarga: +{k}. O balde está cheio. Fichas derramadas: {s}.',
    },
    'caption.requests': {
      en: 'Requests: {n} · Passed: {p} · Rejected: {r} · Tokens left: {m}.',
      ko: '요청: {n} · 지나감: {p} · 거절: {r} · 남은 토큰: {m}.',
      ja: 'リクエスト: {n} · 通過: {p} · 拒否: {r} · 残りトークン: {m}。',
      zh: '请求: {n} · 通过: {p} · 拒绝: {r} · 剩余令牌: {m}。',
      ar: 'الطلبات: {n} · العابر: {p} · المرفوض: {r} · الرموز الباقية: {m}.',
      es: 'Peticiones: {n} · Pasan: {p} · Rechazadas: {r} · Fichas restantes: {m}.',
      fr: 'Requêtes : {n} · Passées : {p} · Refusées : {r} · Jetons restants : {m}.',
      hi: 'अनुरोध: {n} · पार: {p} · अस्वीकृत: {r} · बचे टोकन: {m}.',
      id: 'Permintaan: {n} · Lolos: {p} · Ditolak: {r} · Sisa token: {m}.',
      pt: 'Pedidos: {n} · Passaram: {p} · Rejeitados: {r} · Fichas restantes: {m}.',
    },
    'caption.idle': {
      en: 'No requests this second.',
      ko: '이 초에 온 요청은 없다.',
      ja: 'この秒にリクエストはない。',
      zh: '这一秒没有请求。',
      ar: 'لا طلبات في هذه الثانية.',
      es: 'Ninguna petición en este segundo.',
      fr: 'Aucune requête pendant cette seconde.',
      hi: 'इस सेकंड कोई अनुरोध नहीं।',
      id: 'Tidak ada permintaan pada detik ini.',
      pt: 'Nenhum pedido neste segundo.',
    },
  },
  blocks: {
    stage: { type: 'token-bucket-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
