/**
 * critical-path — facet 선언.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { CriticalPathData } from './algorithm.js';

const initialData: CriticalPathData = {
  type: 'critical-path',
  stepMs: 700,
  attr: 0,
  preload: 0,
  attrLadder: [0, 1, 2],
  preloadLadder: [0, 1],
  preloadLine: '<link rel="preload" href="brand.woff2" as="font" type="font/woff2" crossorigin>',
  cssLine: '<link rel="stylesheet" href="site.css">',
  appLineByAttr: {
    0: '<script src="app.js"></script>',
    1: '<script defer src="app.js"></script>',
    2: '<script async src="app.js"></script>',
  },
  bodyLines: [
    { id: 'h1', code: '<h1>Today</h1>' },
    { id: 'p1', code: '<p>First story</p>' },
    { id: 'p2', code: '<p>Second story</p>' },
    { id: 'brand', code: '<p class="brand">Fonts often arrive later than the words they dress</p>' },
    { id: 'p3', code: '<p>Third story</p>' },
    { id: 'footer', code: '<footer>Contact</footer>' },
  ],
  cssText: [
    '@font-face { font-family: Brand; src: url(brand.woff2); font-display: swap; }',
    '.brand { font-family: Brand, sans-serif; }',
  ],
  resources: {
    site: { receiveMs: 150 },
    app: { receiveMs: 250, execMs: 60 },
    font: { receiveMs: 300 },
  },
  words: ['Fonts', 'often', 'arrive', 'later', 'than', 'the', 'words', 'they', 'dress'],
  fallbackFont: { charPx: 8, spacePx: 8 },
  brandFont: { charPx: 10, spacePx: 10 },
  boxWidthPx: 220,
};

export const criticalPathFacet: FacetJson = {
  id: 'facet:criticalPath',
  title: {
    en: 'Critical rendering path',
    ko: '크리티컬 렌더링 패스',
    ja: 'クリティカルレンダリングパス',
    zh: '关键渲染路径',
    ar: 'مسار العرض الحرج',
    es: 'Ruta crítica de renderizado',
    fr: 'Chemin de rendu critique',
    hi: 'क्रिटिकल रेंडरिंग पथ',
    id: 'Jalur render kritis',
    pt: 'Caminho crítico de renderização',
  },
  description: {
    en: 'How a script attribute and a font preload hint shift when the first paint lands and whether the font swap is ever seen.',
    ko: '스크립트 속성과 글꼴 preload 힌트가 첫 장이 찍히는 시각과 글꼴 바뀜이 보이는지를 어떻게 가르는지 본다.',
    ja: 'スクリプト属性とフォントのプリロードヒントが、最初の描画のタイミングとフォント切り替えの見え方をどう変えるかを見る。',
    zh: '查看脚本属性和字体预加载提示如何改变首次绘制的时间以及是否能看到字体切换。',
    ar: 'كيف تُغيّر سمة السكربت وتلميح التحميل المسبق للخط توقيت أول رسم وما إذا كان تبديل الخط سيظهر.',
    es: 'Cómo el atributo del script y la pista de precarga de fuente cambian el momento del primer pintado y si se ve el cambio de fuente.',
    fr: 'Comment l\'attribut du script et l\'indice de préchargement de police déplacent le premier affichage et rendent visible ou non le changement de police.',
    hi: 'स्क्रिप्ट एट्रिब्यूट और फ़ॉन्ट प्रीलोड संकेत पहले पेंट के समय और फ़ॉन्ट बदलाव दिखने को कैसे बदलते हैं।',
    id: 'Bagaimana atribut skrip dan petunjuk preload font mengubah waktu cat pertama dan apakah pergantian font terlihat.',
    pt: 'Como o atributo do script e a dica de pré-carregamento de fonte deslocam o primeiro paint e se a troca de fonte chega a aparecer.',
  },
  algorithm: 'module:criticalPath',
  projector: 'module:criticalPathProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'critical-path-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'setAttr',
          name: 'setAttr',
          label: {
            en: 'Script attribute',
            ko: '스크립트 속성',
            ja: 'スクリプト属性',
            zh: '脚本属性',
            ar: 'سمة السكربت',
            es: 'Atributo del script',
            fr: 'Attribut du script',
            hi: 'स्क्रिप्ट एट्रिब्यूट',
            id: 'Atribut skrip',
            pt: 'Atributo do script',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'none',
                ko: '없음',
                ja: 'なし',
                zh: '无',
                ar: 'بلا',
                es: 'ninguno',
                fr: 'aucun',
                hi: 'कोई नहीं',
                id: 'tidak ada',
                pt: 'nenhum',
              },
              default: true,
            },
            { value: 1, label: 'defer' },
            { value: 2, label: 'async' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'setPreload',
          name: 'setPreload',
          label: {
            en: 'Font preload',
            ko: '글꼴 preload',
            ja: 'フォント preload',
            zh: '字体 preload',
            ar: 'تحميل الخط مسبقًا',
            es: 'Preload de fuente',
            fr: 'Préchargement de police',
            hi: 'फ़ॉन्ट प्रीलोड',
            id: 'Preload font',
            pt: 'Preload de fonte',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'none',
                ko: '없음',
                ja: 'なし',
                zh: '无',
                ar: 'بلا',
                es: 'ninguno',
                fr: 'aucun',
                hi: 'कोई नहीं',
                id: 'tidak ada',
                pt: 'nenhum',
              },
              default: true,
            },
            {
              value: 1,
              label: {
                en: 'on',
                ko: '있음',
                ja: 'あり',
                zh: '有',
                ar: 'موجود',
                es: 'activado',
                fr: 'activé',
                hi: 'मौजूद',
                id: 'ada',
                pt: 'ativado',
              },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'parser-stall-ms',
          label: {
            en: 'Parser stall (ms)',
            ko: '파서 멎음 (ms)',
            ja: 'パーサー停止 (ms)',
            zh: '解析器停顿 (ms)',
            ar: 'توقف المحلل (مللي ثانية)',
            es: 'Bloqueo del parser (ms)',
            fr: "Arrêt du parseur (ms)",
            hi: 'पार्सर रुकावट (ms)',
            id: 'Parser berhenti (ms)',
            pt: 'Parada do parser (ms)',
          },
          initial: 0,
        },
        {
          name: 'first-paint-ms',
          label: {
            en: 'First paint (ms)',
            ko: '첫 장 (ms)',
            ja: '最初の描画 (ms)',
            zh: '首次绘制 (ms)',
            ar: 'أول رسم (مللي ثانية)',
            es: 'Primer pintado (ms)',
            fr: 'Premier affichage (ms)',
            hi: 'पहला पेंट (ms)',
            id: 'Cat pertama (ms)',
            pt: 'Primeiro paint (ms)',
          },
          initial: 0,
        },
        {
          name: 'fallback-shown-ms',
          label: {
            en: 'Fallback font shown (ms)',
            ko: '대체 글꼴 표시 (ms)',
            ja: '代替フォント表示 (ms)',
            zh: '备用字体显示 (ms)',
            ar: 'مدة ظهور الخط البديل (مللي ثانية)',
            es: 'Fuente alternativa mostrada (ms)',
            fr: 'Police de repli affichée (ms)',
            hi: 'फ़ॉलबैक फ़ॉन्ट दिखा (ms)',
            id: 'Font cadangan tampil (ms)',
            pt: 'Fonte alternativa exibida (ms)',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:critical-path-imperative',
      label: {
        en: 'Critical path',
        ko: '크리티컬 패스',
        ja: 'クリティカルパス',
        zh: '关键路径',
        ar: 'المسار الحرج',
        es: 'Ruta crítica',
        fr: 'Chemin critique',
        hi: 'क्रिटिकल पथ',
        id: 'Jalur kritis',
        pt: 'Caminho crítico',
      },
    },
  },
  messages: {
    'label.resourcePanel': {
      en: 'Request → arrive',
      ko: '요청 → 도착',
      ja: 'リクエスト → 到着',
      zh: '请求 → 到达',
      ar: 'الطلب ← الوصول',
      es: 'Solicitud → llegada',
      fr: 'Requête → arrivée',
      hi: 'अनुरोध → आगमन',
      id: 'Permintaan → tiba',
      pt: 'Requisição → chegada',
    },
    'label.paintDom': {
      en: 'First paint · DOM complete',
      ko: '첫 장 · DOM 완성',
      ja: '最初の描画 · DOM 完成',
      zh: '首次绘制 · DOM 完成',
      ar: 'أول رسم · اكتمال DOM',
      es: 'Primer pintado · DOM completo',
      fr: 'Premier affichage · DOM complet',
      hi: 'पहला पेंट · DOM पूर्ण',
      id: 'Cat pertama · DOM selesai',
      pt: 'Primeiro paint · DOM completo',
    },
    'label.screen': {
      en: 'Screen',
      ko: '화면',
      ja: '画面',
      zh: '屏幕',
      ar: 'الشاشة',
      es: 'Pantalla',
      fr: 'Écran',
      hi: 'स्क्रीन',
      id: 'Layar',
      pt: 'Tela',
    },
    'label.brandBox': {
      en: '.brand paragraph',
      ko: '.brand 문단',
      ja: '.brand 段落',
      zh: '.brand 段落',
      ar: 'فقرة .brand',
      es: 'Párrafo .brand',
      fr: 'Paragraphe .brand',
      hi: '.brand अनुच्छेद',
      id: 'Paragraf .brand',
      pt: 'Parágrafo .brand',
    },
    'caption.gapDomFirst': {
      en: 'DOM complete first — {ms}ms until first paint',
      ko: 'DOM 완성이 먼저 — 첫 장까지 {ms}ms',
      ja: 'DOM 完成が先 — 最初の描画まで {ms}ms',
      zh: 'DOM 先完成 — 距首次绘制 {ms}ms',
      ar: 'اكتمال DOM أولاً — {ms} مللي ثانية حتى أول رسم',
      es: 'DOM completo primero — {ms}ms hasta el primer pintado',
      fr: "DOM d'abord complet — {ms}ms avant le premier affichage",
      hi: 'पहले DOM पूर्ण — पहले पेंट तक {ms}ms',
      id: 'DOM selesai duluan — {ms}ms sampai cat pertama',
      pt: 'DOM completo primeiro — {ms}ms até o primeiro paint',
    },
    'caption.gapPaintFirst': {
      en: 'First paint first — {ms}ms until DOM complete',
      ko: '첫 장이 먼저 — DOM 완성까지 {ms}ms',
      ja: '最初の描画が先 — DOM 完成まで {ms}ms',
      zh: '首次绘制先完成 — 距 DOM 完成 {ms}ms',
      ar: 'أول رسم أولاً — {ms} مللي ثانية حتى اكتمال DOM',
      es: 'Primer pintado primero — {ms}ms hasta el DOM completo',
      fr: "Premier affichage d'abord — {ms}ms avant le DOM complet",
      hi: 'पहले पेंट पहले — DOM पूर्ण तक {ms}ms',
      id: 'Cat pertama duluan — {ms}ms sampai DOM selesai',
      pt: 'Primeiro paint primeiro — {ms}ms até o DOM completo',
    },
  },
};
