/**
 * cache-invalidation 선언 — 층 캐시는 앞 층의 열쇠를 품으므로 바뀐 층 뒤가 전부 다시 된다.
 *
 * 손잡이 둘: 층 차례(의존 먼저 · 소스 먼저) × 바뀐 파일(app.src · deps.txt). 곱 넷이 곧 주장이다.
 * IR 을 두지 않아 코드 패널이 없다 (irs.ts 의 주석).
 * 층 식별자 · 파일 이름 · 파일 내용은 번역하지 않는 자료 — 표시 이름은 messages 의 label.*.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { CacheInvalidationData } from './algorithm.js';

const initialData: CacheInvalidationData = {
  type: 'cache-invalidation',
  stepMs: 1800,
  layers: [
    { id: 'base', file: null, seconds: 0 },
    { id: 'copy-deps', file: 'deps.txt', seconds: 1 },
    { id: 'install', file: null, seconds: 60 },
    { id: 'copy-src', file: 'app.src', seconds: 1 },
    { id: 'build', file: null, seconds: 20 },
    { id: 'test', file: null, seconds: 10 },
  ],
  files: [
    { name: 'app.src', before: 'show greet()', after: 'show greet("hi")' },
    { name: 'deps.txt', before: 'left-pad 1.0', after: 'left-pad 1.1' },
  ],
  orders: [
    { id: 'deps-first', layers: ['base', 'copy-deps', 'install', 'copy-src', 'build', 'test'] },
    { id: 'src-first', layers: ['base', 'copy-src', 'copy-deps', 'install', 'build', 'test'] },
  ],
  initialOrder: 1,
  initialChanged: 0,
};

export const cacheInvalidationFacet: FacetJson = {
  id: 'facet:cacheInvalidation',
  title: {
    en: 'Cache invalidation',
    ko: '캐시 무효화',
    ja: 'キャッシュの無効化',
    zh: '缓存失效',
    ar: 'إبطال ذاكرة التخزين المؤقت',
    es: 'Invalidación de caché',
    fr: 'Invalidation du cache',
    hi: 'कैश अमान्यकरण',
    id: 'Invalidasi cache',
    pt: 'Invalidação de cache',
  },
  description: {
    en: 'A layer key holds the key of the layer above, so every layer after a changed one is redone. Swap the layer order and see how many seconds the rebuild costs.',
    ko: '층 열쇠는 앞 층의 열쇠를 품는다. 그래서 바뀐 층 뒤가 전부 다시 된다. 층 차례를 바꿔 다시 드는 초가 어떻게 달라지는지 본다.',
    ja: '層のキーは上の層のキーを含むため、変わった層より後ろはすべてやり直しになる。層の順序を入れ替えて、やり直しにかかる秒数を見る。',
    zh: '每层的键包含上一层的键，所以变化层之后的所有层都要重做。调换层的顺序，看重做要花多少秒。',
    ar: 'مفتاح كل طبقة يحمل مفتاح الطبقة التي فوقها، لذا تُعاد كل طبقة بعد الطبقة المتغيّرة. بدّل ترتيب الطبقات وانظر كم ثانية تكلّف الإعادة.',
    es: 'La clave de cada capa contiene la de la capa anterior, así que todo lo que sigue a una capa cambiada se rehace. Cambia el orden de las capas y mira cuántos segundos cuesta rehacer.',
    fr: 'La clé d’une couche contient celle de la couche précédente : tout ce qui suit une couche modifiée est refait. Change l’ordre des couches et vois combien de secondes coûte la reprise.',
    hi: 'हर परत की कुंजी में ऊपर वाली परत की कुंजी शामिल होती है, इसलिए बदली परत के बाद की हर परत फिर से बनती है। परतों का क्रम बदलें और देखें कि फिर से बनाने में कितने सेकंड लगते हैं।',
    id: 'Kunci tiap lapisan memuat kunci lapisan sebelumnya, jadi semua lapisan setelah lapisan yang berubah dikerjakan ulang. Tukar urutan lapisan dan lihat berapa detik yang dibutuhkan.',
    pt: 'A chave de cada camada contém a da camada anterior, então tudo depois de uma camada alterada é refeito. Troque a ordem das camadas e veja quantos segundos custa refazer.',
  },
  algorithm: 'module:cacheInvalidation',
  projector: 'module:cacheInvalidationProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'cache-invalidation-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'layer-order',
          name: 'layer-order',
          label: {
            en: 'Layer order',
            ko: '층 차례',
            ja: '層の順序',
            zh: '层的顺序',
            ar: 'ترتيب الطبقات',
            es: 'Orden de capas',
            fr: 'Ordre des couches',
            hi: 'परतों का क्रम',
            id: 'Urutan lapisan',
            pt: 'Ordem das camadas',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Deps first',
                ko: '의존 먼저',
                ja: '依存が先',
                zh: '依赖在前',
                ar: 'التبعيات أولًا',
                es: 'Dependencias antes',
                fr: 'Dépendances d’abord',
                hi: 'निर्भरता पहले',
                id: 'Dependensi dulu',
                pt: 'Dependências antes',
              },
            },
            {
              value: 1,
              label: {
                en: 'Source first',
                ko: '소스 먼저',
                ja: 'ソースが先',
                zh: '源码在前',
                ar: 'المصدر أولًا',
                es: 'Código antes',
                fr: 'Source d’abord',
                hi: 'स्रोत पहले',
                id: 'Sumber dulu',
                pt: 'Código antes',
              },
              default: true,
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'changed-file',
          name: 'changed-file',
          label: {
            en: 'Changed file',
            ko: '바뀐 파일',
            ja: '変わったファイル',
            zh: '变化的文件',
            ar: 'الملف المتغيّر',
            es: 'Archivo cambiado',
            fr: 'Fichier modifié',
            hi: 'बदली फ़ाइल',
            id: 'Berkas yang berubah',
            pt: 'Arquivo alterado',
          },
          segments: [
            { value: 0, label: 'app.src', default: true },
            { value: 1, label: 'deps.txt' },
          ],
        },
      ],
      metrics: [
        {
          name: 'cached',
          label: {
            en: 'Cached',
            ko: '꺼내 씀',
            ja: 'キャッシュ利用',
            zh: '命中缓存',
            ar: 'من الذاكرة',
            es: 'De caché',
            fr: 'Repris du cache',
            hi: 'कैश से',
            id: 'Dari cache',
            pt: 'Do cache',
          },
          initial: 0,
        },
        {
          name: 'redone',
          label: {
            en: 'Redone',
            ko: '다시',
            ja: 'やり直し',
            zh: '重做',
            ar: 'مُعاد',
            es: 'Rehechas',
            fr: 'Refaites',
            hi: 'फिर से',
            id: 'Diulang',
            pt: 'Refeitas',
          },
          initial: 0,
        },
        {
          name: 'redo-seconds',
          label: {
            en: 'Redo seconds',
            ko: '다시 드는 초',
            ja: 'やり直しの秒',
            zh: '重做秒数',
            ar: 'ثواني الإعادة',
            es: 'Segundos a rehacer',
            fr: 'Secondes refaites',
            hi: 'दोबारा के सेकंड',
            id: 'Detik ulang',
            pt: 'Segundos refeitos',
          },
          initial: 0,
        },
      ],
    },
  },
  messages: {
    'label.layer.base': {
      en: 'Base',
      ko: '바탕',
      ja: 'ベース',
      zh: '基础',
      ar: 'الأساس',
      es: 'Base',
      fr: 'Base',
      hi: 'आधार',
      id: 'Dasar',
      pt: 'Base',
    },
    'label.layer.copy-deps': {
      en: 'Add dependency list',
      ko: '의존 목록 넣기',
      ja: '依存リストを入れる',
      zh: '放入依赖列表',
      ar: 'إضافة قائمة التبعيات',
      es: 'Añadir lista de deps',
      fr: 'Ajouter la liste deps',
      hi: 'निर्भरता सूची डालना',
      id: 'Tambah daftar dep',
      pt: 'Adicionar lista de deps',
    },
    'label.layer.install': {
      en: 'Install dependencies',
      ko: '의존 설치',
      ja: '依存をインストール',
      zh: '安装依赖',
      ar: 'تثبيت التبعيات',
      es: 'Instalar deps',
      fr: 'Installer les deps',
      hi: 'निर्भरता इंस्टॉल',
      id: 'Pasang dependensi',
      pt: 'Instalar deps',
    },
    'label.layer.copy-src': {
      en: 'Add source',
      ko: '소스 넣기',
      ja: 'ソースを入れる',
      zh: '放入源码',
      ar: 'إضافة المصدر',
      es: 'Añadir código',
      fr: 'Ajouter la source',
      hi: 'स्रोत डालना',
      id: 'Tambah sumber',
      pt: 'Adicionar código',
    },
    'label.layer.build': {
      en: 'Build',
      ko: '빌드',
      ja: 'ビルド',
      zh: '构建',
      ar: 'البناء',
      es: 'Compilar',
      fr: 'Compiler',
      hi: 'बिल्ड',
      id: 'Bangun',
      pt: 'Compilar',
    },
    'label.layer.test': {
      en: 'Test',
      ko: '테스트',
      ja: 'テスト',
      zh: '测试',
      ar: 'الاختبار',
      es: 'Probar',
      fr: 'Tester',
      hi: 'परीक्षण',
      id: 'Uji',
      pt: 'Testar',
    },
    'label.order.deps-first': {
      en: 'Dependencies first',
      ko: '의존 먼저',
      ja: '依存が先',
      zh: '依赖在前',
      ar: 'التبعيات أولًا',
      es: 'Dependencias antes',
      fr: 'Dépendances d’abord',
      hi: 'निर्भरता पहले',
      id: 'Dependensi dulu',
      pt: 'Dependências antes',
    },
    'label.order.src-first': {
      en: 'Source first',
      ko: '소스 먼저',
      ja: 'ソースが先',
      zh: '源码在前',
      ar: 'المصدر أولًا',
      es: 'Código antes',
      fr: 'Source d’abord',
      hi: 'स्रोत पहले',
      id: 'Sumber dulu',
      pt: 'Código antes',
    },
    'label.files': {
      en: 'File fingerprints',
      ko: '파일 지문',
      ja: 'ファイル指紋',
      zh: '文件指纹',
      ar: 'بصمات الملفات',
      es: 'Huellas de archivo',
      fr: 'Empreintes',
      hi: 'फ़ाइल फ़िंगरप्रिंट',
      id: 'Sidik berkas',
      pt: 'Impressões',
    },
    'label.col.layer': {
      en: 'Layer',
      ko: '층',
      ja: '層',
      zh: '层',
      ar: 'الطبقة',
      es: 'Capa',
      fr: 'Couche',
      hi: 'परत',
      id: 'Lapisan',
      pt: 'Camada',
    },
    'label.col.file': {
      en: 'File',
      ko: '파일',
      ja: 'ファイル',
      zh: '文件',
      ar: 'الملف',
      es: 'Archivo',
      fr: 'Fichier',
      hi: 'फ़ाइल',
      id: 'Berkas',
      pt: 'Arquivo',
    },
    'label.col.seconds': {
      en: 'Seconds',
      ko: '초',
      ja: '秒',
      zh: '秒',
      ar: 'الثواني',
      es: 'Segundos',
      fr: 'Secondes',
      hi: 'सेकंड',
      id: 'Detik',
      pt: 'Segundos',
    },
    'label.col.prevKey': {
      en: 'Last key',
      ko: '지난 열쇠',
      ja: '前回のキー',
      zh: '上次的键',
      ar: 'المفتاح السابق',
      es: 'Clave previa',
      fr: 'Clé d’avant',
      hi: 'पिछली कुंजी',
      id: 'Kunci lalu',
      pt: 'Chave anterior',
    },
    'label.col.newKey': {
      en: 'New key',
      ko: '새 열쇠',
      ja: '新しいキー',
      zh: '新的键',
      ar: 'المفتاح الجديد',
      es: 'Clave nueva',
      fr: 'Nouvelle clé',
      hi: 'नई कुंजी',
      id: 'Kunci baru',
      pt: 'Chave nova',
    },
    'label.col.verdict': {
      en: 'Verdict',
      ko: '판정',
      ja: '判定',
      zh: '判定',
      ar: 'الحكم',
      es: 'Veredicto',
      fr: 'Verdict',
      hi: 'निर्णय',
      id: 'Putusan',
      pt: 'Veredito',
    },
    'label.verdict.cached': {
      en: 'Cached',
      ko: '꺼내 씀',
      ja: 'キャッシュ利用',
      zh: '命中缓存',
      ar: 'من الذاكرة',
      es: 'De caché',
      fr: 'Du cache',
      hi: 'कैश से',
      id: 'Dari cache',
      pt: 'Do cache',
    },
    'label.verdict.own': {
      en: 'Redo · own file',
      ko: '다시 · 제 파일',
      ja: 'やり直し · 自分のファイル',
      zh: '重做 · 自身文件',
      ar: 'إعادة · ملفها',
      es: 'Rehacer · su archivo',
      fr: 'Refaire · son fichier',
      hi: 'फिर से · अपनी फ़ाइल',
      id: 'Ulang · berkasnya',
      pt: 'Refazer · seu arquivo',
    },
    'label.verdict.prev': {
      en: 'Redo · layer above',
      ko: '다시 · 앞 층',
      ja: 'やり直し · 前の層',
      zh: '重做 · 上一层',
      ar: 'إعادة · الطبقة السابقة',
      es: 'Rehacer · capa previa',
      fr: 'Refaire · couche avant',
      hi: 'फिर से · पिछली परत',
      id: 'Ulang · lapisan atas',
      pt: 'Refazer · camada acima',
    },
    'label.seconds': {
      en: '{n} s',
      ko: '{n}초',
      ja: '{n}秒',
      zh: '{n}秒',
      ar: '{n} ث',
      es: '{n} s',
      fr: '{n} s',
      hi: '{n} से.',
      id: '{n} dtk',
      pt: '{n} s',
    },
    'label.redoSeconds': {
      en: 'Redo seconds',
      ko: '다시 드는 초',
      ja: 'やり直しの秒',
      zh: '重做秒数',
      ar: 'ثواني الإعادة',
      es: 'Segundos a rehacer',
      fr: 'Secondes refaites',
      hi: 'दोबारा के सेकंड',
      id: 'Detik ulang',
      pt: 'Segundos refeitos',
    },
    'caption.start': {
      en: 'Layer order: {order} · every last key is in the cache',
      ko: '층 차례: {order} · 지난번 열쇠가 모두 캐시에 있다',
      ja: '層の順序: {order} · 前回のキーはすべてキャッシュにある',
      zh: '层的顺序：{order} · 上次的键都在缓存里',
      ar: 'ترتيب الطبقات: {order} · كل المفاتيح السابقة في الذاكرة المؤقتة',
      es: 'Orden de capas: {order} · todas las claves previas están en caché',
      fr: 'Ordre des couches : {order} · toutes les clés d’avant sont en cache',
      hi: 'परतों का क्रम: {order} · पिछली सभी कुंजियाँ कैश में हैं',
      id: 'Urutan lapisan: {order} · semua kunci lalu ada di cache',
      pt: 'Ordem das camadas: {order} · todas as chaves anteriores estão no cache',
    },
    'caption.changed': {
      en: 'Changed: {name} · fingerprint {before} → {after}',
      ko: '바뀐 파일: {name} · 지문 {before} → {after}',
      ja: '変わったファイル: {name} · 指紋 {before} → {after}',
      zh: '变化的文件：{name} · 指纹 {before} → {after}',
      ar: 'الملف المتغيّر: {name} · البصمة {before} → {after}',
      es: 'Cambió: {name} · huella {before} → {after}',
      fr: 'Modifié : {name} · empreinte {before} → {after}',
      hi: 'बदली फ़ाइल: {name} · फ़िंगरप्रिंट {before} → {after}',
      id: 'Berubah: {name} · sidik {before} → {after}',
      pt: 'Alterado: {name} · impressão {before} → {after}',
    },
    'caption.cascade': {
      en: 'First new key at layer {pos}: {name}',
      ko: '처음 달라진 열쇠: {pos}번째 층 · {name}',
      ja: '最初に変わったキー: {pos}番目の層 · {name}',
      zh: '第一个变化的键：第 {pos} 层 · {name}',
      ar: 'أول مفتاح جديد: الطبقة {pos} · {name}',
      es: 'Primera clave nueva: capa {pos} · {name}',
      fr: 'Première clé nouvelle : couche {pos} · {name}',
      hi: 'पहली नई कुंजी: परत {pos} · {name}',
      id: 'Kunci baru pertama: lapisan {pos} · {name}',
      pt: 'Primeira chave nova: camada {pos} · {name}',
    },
    'caption.sum': {
      en: 'Seconds of redone layers: {parts}',
      ko: '다시 하는 층의 초: {parts}',
      ja: 'やり直す層の秒: {parts}',
      zh: '重做各层的秒数：{parts}',
      ar: 'ثواني الطبقات المُعادة: {parts}',
      es: 'Segundos de las capas rehechas: {parts}',
      fr: 'Secondes des couches refaites : {parts}',
      hi: 'फिर से बनने वाली परतों के सेकंड: {parts}',
      id: 'Detik lapisan yang diulang: {parts}',
      pt: 'Segundos das camadas refeitas: {parts}',
    },
  },
};
