/**
 * @piece
 * 질문: 앞에 캐시를 둔 서버에서, 같은 요청이 어떤 때는 1 ms 에 끝나고 어떤 때는 21 ms 가 걸리는 까닭은 무엇인가.
 *
 * 동사: 갈라진다 — 요청마다 캐시에 먼저 닿고, 키가 있으면 거기서 돌아서며, 없으면 DB 까지 더 가서
 * 가져온 뒤 돌아오는 길에 캐시에 그 키를 남긴다. 걸린 ms 가 누계로 쌓인다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const cacheHitMissFacet: FacetJson = {
  id: 'facet:cacheHitMiss',
  title: {
    en: 'Cache Hit and Miss',
    ko: '캐시 적중과 실패',
    ja: 'キャッシュヒットとミス',
    zh: '缓存命中与未命中',
    ar: 'إصابة الذاكرة المؤقتة وإخفاقها',
    es: 'Acierto y fallo de caché',
    fr: 'Succès et échec de cache',
    hi: 'कैश हिट और मिस',
    id: 'Cache hit dan miss',
    pt: 'Acerto e falha de cache',
  },
  description: {
    en: 'A request that finds its key turns back at the cache; one that does not goes on to the DB and leaves the key behind.',
    ko: '키가 있는 요청은 캐시에서 돌아서고, 없는 요청은 DB 까지 가서 키를 캐시에 남긴다.',
    ja: 'キーがある要求はキャッシュで引き返し、ない要求は DB まで行ってキーをキャッシュに残す。',
    zh: '找到键的请求在缓存处折返；找不到的请求继续前往 DB，并把键留在缓存里。',
    ar: 'الطلب الذي يجد مفتاحه يعود من الذاكرة المؤقتة، والذي لا يجده يمضي إلى قاعدة البيانات ويترك المفتاح خلفه.',
    es: 'Una petición que encuentra su clave da la vuelta en la caché; la que no, sigue hasta la BD y deja la clave en la caché.',
    fr: 'Une requête qui trouve sa clé fait demi-tour au cache ; sinon elle va jusqu’à la BD et laisse la clé dans le cache.',
    hi: 'जिस अनुरोध को कुंजी मिलती है वह कैश से लौटता है; जिसे नहीं मिलती वह DB तक जाता है और कुंजी कैश में छोड़ता है।',
    id: 'Permintaan yang menemukan kuncinya berbalik di cache; yang tidak, terus ke DB dan meninggalkan kunci di cache.',
    pt: 'Um pedido que encontra a chave volta no cache; o que não encontra segue até o BD e deixa a chave no cache.',
  },
  algorithm: 'module:cacheHitMiss',
  scene: 'module:cacheHitMissScene',
  initialData: {
    type: 'cache-hit-miss',
    stepMs: 1300,
    requests: ['user:7', 'user:3', 'user:7', 'user:7', 'user:9', 'user:3', 'user:7', 'user:9'],
    cacheMs: 1,
    dbMs: 20,
    capacity: 4,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Requests waiting: {n} · Keys in cache: {k}',
      ko: '기다리는 요청: {n} · 캐시에 든 키: {k}',
      ja: '待っている要求: {n} · キャッシュ内のキー: {k}',
      zh: '等待的请求: {n} · 缓存中的键: {k}',
      ar: 'الطلبات المنتظرة: {n} · المفاتيح في الذاكرة المؤقتة: {k}',
      es: 'Peticiones en espera: {n} · Claves en caché: {k}',
      fr: 'Requêtes en attente : {n} · Clés en cache : {k}',
      hi: 'प्रतीक्षारत अनुरोध: {n} · कैश में कुंजियाँ: {k}',
      id: 'Permintaan menunggu: {n} · Kunci di cache: {k}',
      pt: 'Pedidos à espera: {n} · Chaves no cache: {k}',
    },
    'caption.hit': {
      en: 'Hit: {key} is in the cache — turned back there',
      ko: '적중: 캐시에 {key} 있음 — 거기서 돌아섰다',
      ja: 'ヒット: キャッシュに {key} あり — そこで引き返した',
      zh: '命中: 缓存里有 {key} — 在那里折返',
      ar: 'إصابة: {key} في الذاكرة المؤقتة — عاد الطلب من هناك',
      es: 'Acierto: {key} está en la caché — dio la vuelta allí',
      fr: 'Succès : {key} est dans le cache — demi-tour là',
      hi: 'हिट: {key} कैश में है — वहीं से लौटा',
      id: 'Hit: {key} ada di cache — berbalik di sana',
      pt: 'Acerto: {key} está no cache — voltou dali',
    },
    'caption.miss': {
      en: 'Miss: {key} is not in the cache — fetched from the DB and kept in the cache',
      ko: '실패: 캐시에 {key} 없음 — DB 에서 가져와 캐시에 남겼다',
      ja: 'ミス: キャッシュに {key} なし — DB から取ってきてキャッシュに残した',
      zh: '未命中: 缓存里没有 {key} — 从 DB 取回并留在缓存里',
      ar: 'إخفاق: {key} ليس في الذاكرة المؤقتة — جُلب من قاعدة البيانات وحُفظ فيها',
      es: 'Fallo: {key} no está en la caché — se trajo de la BD y se guardó en la caché',
      fr: 'Échec : {key} n’est pas dans le cache — lu dans la BD et gardé dans le cache',
      hi: 'मिस: {key} कैश में नहीं — DB से लाकर कैश में रखा',
      id: 'Miss: {key} tidak ada di cache — diambil dari DB lalu disimpan di cache',
      pt: 'Falha: {key} não está no cache — trazido do BD e guardado no cache',
    },
    'caption.took': {
      en: 'This request: {ms} ms',
      ko: '이번 요청: {ms} ms',
      ja: 'この要求: {ms} ms',
      zh: '本次请求: {ms} ms',
      ar: 'هذا الطلب: {ms} ms',
      es: 'Esta petición: {ms} ms',
      fr: 'Cette requête : {ms} ms',
      hi: 'यह अनुरोध: {ms} ms',
      id: 'Permintaan ini: {ms} ms',
      pt: 'Este pedido: {ms} ms',
    },
    'label.counters': {
      en: 'Total: {total} ms · Hits: {hits} · Misses: {misses}',
      ko: '누계: {total} ms · 적중: {hits} · 실패: {misses}',
      ja: '累計: {total} ms · ヒット: {hits} · ミス: {misses}',
      zh: '累计: {total} ms · 命中: {hits} · 未命中: {misses}',
      ar: 'المجموع: {total} ms · إصابات: {hits} · إخفاقات: {misses}',
      es: 'Total: {total} ms · Aciertos: {hits} · Fallos: {misses}',
      fr: 'Total : {total} ms · Succès : {hits} · Échecs : {misses}',
      hi: 'कुल: {total} ms · हिट: {hits} · मिस: {misses}',
      id: 'Total: {total} ms · Hit: {hits} · Miss: {misses}',
      pt: 'Total: {total} ms · Acertos: {hits} · Falhas: {misses}',
    },
    'label.server': {
      en: 'Server',
      ko: '서버',
      ja: 'サーバー',
      zh: '服务器',
      ar: 'الخادم',
      es: 'Servidor',
      fr: 'Serveur',
      hi: 'सर्वर',
      id: 'Server',
      pt: 'Servidor',
    },
    'label.cache': {
      en: 'Cache',
      ko: '캐시',
      ja: 'キャッシュ',
      zh: '缓存',
      ar: 'الذاكرة المؤقتة',
      es: 'Caché',
      fr: 'Cache',
      hi: 'कैश',
      id: 'Cache',
      pt: 'Cache',
    },
    'label.db': {
      en: 'DB',
      ko: 'DB',
      ja: 'DB',
      zh: 'DB',
      ar: 'قاعدة البيانات',
      es: 'BD',
      fr: 'BD',
      hi: 'DB',
      id: 'DB',
      pt: 'BD',
    },
    'label.hit': {
      en: 'Hit',
      ko: '적중',
      ja: 'ヒット',
      zh: '命中',
      ar: 'إصابة',
      es: 'Acierto',
      fr: 'Succès',
      hi: 'हिट',
      id: 'Hit',
      pt: 'Acerto',
    },
    'label.miss': {
      en: 'Miss',
      ko: '실패',
      ja: 'ミス',
      zh: '未命中',
      ar: 'إخفاق',
      es: 'Fallo',
      fr: 'Échec',
      hi: 'मिस',
      id: 'Miss',
      pt: 'Falha',
    },
  },
  blocks: {
    stage: { type: 'cache-hit-miss-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
