import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 회전 행렬로 원점 밖의 도형을 돌리면 도형은 어디를 중심으로 돌고, 도는 동안 무엇이 그대로인가.
 */
export const rotateTurnsFacet: FacetJson = {
  id: 'facet:rotateTurns',
  title: {
    en: 'Rotation turns around the origin',
    ko: '회전은 원점 둘레를 돈다',
    ja: '回転は原点のまわりを回る',
    zh: '旋转绕原点转动',
    ar: 'الدوران يدور حول الأصل',
    es: 'La rotación gira alrededor del origen',
    fr: "La rotation tourne autour de l'origine",
    hi: 'घूर्णन मूल बिंदु के चारों ओर घूमता है',
    id: 'Rotasi berputar mengelilingi titik asal',
    pt: 'A rotação gira em torno da origem',
  },
  description: {
    en: 'A triangle away from the origin is rotated 45° at a time. Each vertex follows an arc around the origin, and the distances, side lengths and angles are measured again at every step.',
    ko: '원점 밖의 삼각형을 45° 씩 돌린다. 꼭짓점마다 원점 둘레의 호를 따라 가고, 걸음마다 원점까지 거리 · 변 길이 · 꼭짓점 각을 새로 잰다.',
    ja: '原点から離れた三角形を 45° ずつ回す。各頂点は原点のまわりの弧をたどり、一歩ごとに原点までの距離・辺の長さ・角を測り直す。',
    zh: '把远离原点的三角形每次旋转 45°。每个顶点沿绕原点的圆弧移动，每一步都重新测量到原点的距离、边长和角度。',
    ar: 'يُدار مثلث بعيد عن الأصل بمقدار 45° في كل مرة. يتبع كل رأس قوسًا حول الأصل، وتُقاس المسافات وأطوال الأضلاع والزوايا من جديد في كل خطوة.',
    es: 'Un triángulo alejado del origen gira 45° cada vez. Cada vértice sigue un arco alrededor del origen, y en cada paso se vuelven a medir distancias, lados y ángulos.',
    fr: "Un triangle éloigné de l'origine tourne de 45° à chaque fois. Chaque sommet suit un arc autour de l'origine, et distances, côtés et angles sont remesurés à chaque étape.",
    hi: 'मूल बिंदु से दूर एक त्रिभुज को हर बार 45° घुमाया जाता है। हर शीर्ष मूल बिंदु के चारों ओर एक चाप पर चलता है, और हर चरण में दूरी, भुजाओं की लंबाई और कोण फिर से मापे जाते हैं।',
    id: 'Segitiga yang jauh dari titik asal diputar 45° setiap kali. Setiap titik sudut mengikuti busur mengelilingi titik asal, dan jarak, panjang sisi, serta sudut diukur ulang di setiap langkah.',
    pt: 'Um triângulo longe da origem é girado 45° de cada vez. Cada vértice segue um arco em torno da origem, e distâncias, lados e ângulos são medidos de novo a cada passo.',
  },
  algorithm: 'module:rotateTurns',
  scene: 'module:rotateTurnsScene',
  initialData: {
    type: 'rotate-turns',
    stepMs: 1400,
    vertices: [
      { id: 'a', x: 3, y: 1 },
      { id: 'b', x: 5, y: 1 },
      { id: 'c', x: 4, y: 3 },
    ],
    stepDeg: 45,
    steps: 4,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Starting triangle. Total angle: {deg}°',
      ko: '처음 삼각형. 누적 각: {deg}°',
      ja: '最初の三角形。累積角: {deg}°',
      zh: '初始三角形。累计角度：{deg}°',
      ar: 'المثلث الأولي. الزاوية الكلية: {deg}°',
      es: 'Triángulo inicial. Ángulo total: {deg}°',
      fr: 'Triangle de départ. Angle total : {deg}°',
      hi: 'शुरुआती त्रिभुज। कुल कोण: {deg}°',
      id: 'Segitiga awal. Sudut total: {deg}°',
      pt: 'Triângulo inicial. Ângulo total: {deg}°',
    },
    'caption.turn': {
      en: 'Turn around the origin: +{by}°. Total angle: {deg}°',
      ko: '원점 둘레로 돈다: +{by}°. 누적 각: {deg}°',
      ja: '原点のまわりを回転: +{by}°。累積角: {deg}°',
      zh: '绕原点旋转：+{by}°。累计角度：{deg}°',
      ar: 'دوران حول الأصل: +{by}°. الزاوية الكلية: {deg}°',
      es: 'Giro alrededor del origen: +{by}°. Ángulo total: {deg}°',
      fr: "Rotation autour de l'origine : +{by}°. Angle total : {deg}°",
      hi: 'मूल बिंदु के चारों ओर घूर्णन: +{by}°। कुल कोण: {deg}°',
      id: 'Putar mengelilingi titik asal: +{by}°. Sudut total: {deg}°',
      pt: 'Giro em torno da origem: +{by}°. Ângulo total: {deg}°',
    },
    'label.a': { en: 'A', ko: 'A', ja: 'A', zh: 'A', ar: 'A', es: 'A', fr: 'A', hi: 'A', id: 'A', pt: 'A' },
    'label.b': { en: 'B', ko: 'B', ja: 'B', zh: 'B', ar: 'B', es: 'B', fr: 'B', hi: 'B', id: 'B', pt: 'B' },
    'label.c': { en: 'C', ko: 'C', ja: 'C', zh: 'C', ar: 'C', es: 'C', fr: 'C', hi: 'C', id: 'C', pt: 'C' },
    'label.x': { en: 'x', ko: 'x', ja: 'x', zh: 'x', ar: 'x', es: 'x', fr: 'x', hi: 'x', id: 'x', pt: 'x' },
    'label.y': { en: 'y', ko: 'y', ja: 'y', zh: 'y', ar: 'y', es: 'y', fr: 'y', hi: 'y', id: 'y', pt: 'y' },
    'label.origin': {
      en: 'origin',
      ko: '원점',
      ja: '原点',
      zh: '原点',
      ar: 'الأصل',
      es: 'origen',
      fr: 'origine',
      hi: 'मूल बिंदु',
      id: 'titik asal',
      pt: 'origem',
    },
    'head.position': {
      en: 'Position (x, y)',
      ko: '자리 (x, y)',
      ja: '位置 (x, y)',
      zh: '位置 (x, y)',
      ar: 'الموضع (x, y)',
      es: 'Posición (x, y)',
      fr: 'Position (x, y)',
      hi: 'स्थिति (x, y)',
      id: 'Posisi (x, y)',
      pt: 'Posição (x, y)',
    },
    'head.toOrigin': {
      en: 'To origin',
      ko: '원점까지',
      ja: '原点まで',
      zh: '到原点',
      ar: 'إلى الأصل',
      es: 'Al origen',
      fr: "À l'origine",
      hi: 'मूल बिंदु तक',
      id: 'Ke titik asal',
      pt: 'Até a origem',
    },
    'head.centroid': {
      en: 'Centroid',
      ko: '무게중심',
      ja: '重心',
      zh: '重心',
      ar: 'مركز الثقل',
      es: 'Centroide',
      fr: 'Centre de gravité',
      hi: 'केंद्रक',
      id: 'Titik berat',
      pt: 'Centroide',
    },
    'head.sides': {
      en: 'Side lengths',
      ko: '변 길이',
      ja: '辺の長さ',
      zh: '边长',
      ar: 'أطوال الأضلاع',
      es: 'Longitud de los lados',
      fr: 'Longueurs des côtés',
      hi: 'भुजाओं की लंबाई',
      id: 'Panjang sisi',
      pt: 'Comprimento dos lados',
    },
    'head.corners': {
      en: 'Interior angles',
      ko: '꼭짓점 각',
      ja: '内角',
      zh: '内角',
      ar: 'الزوايا الداخلية',
      es: 'Ángulos interiores',
      fr: 'Angles intérieurs',
      hi: 'आंतरिक कोण',
      id: 'Sudut dalam',
      pt: 'Ângulos internos',
    },
    'value.point': {
      en: '({x}, {y})',
      ko: '({x}, {y})',
      ja: '({x}, {y})',
      zh: '({x}, {y})',
      ar: '({x}, {y})',
      es: '({x}, {y})',
      fr: '({x}, {y})',
      hi: '({x}, {y})',
      id: '({x}, {y})',
      pt: '({x}, {y})',
    },
    'value.side': { en: '{p}{q}', ko: '{p}{q}', ja: '{p}{q}', zh: '{p}{q}', ar: '{p}{q}', es: '{p}{q}', fr: '{p}{q}', hi: '{p}{q}', id: '{p}{q}', pt: '{p}{q}' },
    'value.deg': { en: '{v}°', ko: '{v}°', ja: '{v}°', zh: '{v}°', ar: '{v}°', es: '{v}°', fr: '{v}°', hi: '{v}°', id: '{v}°', pt: '{v}°' },
  },
  blocks: {
    stage: { type: 'rotate-turns-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
