import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece 윈도 함수는 이웃 줄을 보면서도 어떻게 줄을 줄이지 않는가.
 *
 * @notation native — 화면의 질의는 SQL 그대로다. `ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING`
 * 이라는 문장 자체가 틀의 크기를 정하는 주장의 소재라 가상 표기로 옮기지 않는다.
 */
export const windowSlidesFacet: FacetJson = {
  id: 'facet:windowSlides',
  title: {
    en: 'Window function — the frame slides, the rows stay',
    ko: '윈도 함수 — 틀은 미끄러지고 줄은 남는다',
    ja: 'ウィンドウ関数 — 枠は滑り、行は残る',
    zh: '窗口函数 — 窗框滑动，行都留下',
    ar: 'دالة النافذة — الإطار ينزلق والصفوف تبقى',
    es: 'Función de ventana — el marco se desliza, las filas se quedan',
    fr: 'Fonction de fenêtre — le cadre glisse, les lignes restent',
    hi: 'विंडो फ़ंक्शन — फ़्रेम खिसकता है, पंक्तियाँ बनी रहती हैं',
    id: 'Fungsi jendela — bingkai bergeser, baris tetap ada',
    pt: 'Função de janela — o quadro desliza, as linhas ficam',
  },
  description: {
    en: 'A frame holding one row before and one row after slides down in day order. The sum inside it is written into that row’s own cell, and not a single row is merged away.',
    ko: '앞 한 줄과 뒤 한 줄을 감싼 틀이 day 차례로 미끄러진다. 틀 안의 합은 그 줄 자신의 칸에 적히고, 합쳐져 사라지는 줄은 하나도 없다.',
    ja: '前の1行と後ろの1行を囲む枠が day の順に滑り下りる。枠の中の合計はその行自身のセルに書かれ、まとめられて消える行は一つもない。',
    zh: '框住前一行和后一行的窗框按 day 顺序向下滑动。框内的和写进该行自己的格子里，没有任何一行被合并掉。',
    ar: 'إطار يضم صفًا قبله وصفًا بعده ينزلق بترتيب day. يُكتب المجموع داخله في خلية ذلك الصف نفسه، ولا يُدمج أي صف أو يختفي.',
    es: 'Un marco que abarca una fila anterior y una posterior se desliza en orden de day. La suma de su interior se escribe en la propia celda de esa fila, y ninguna fila se fusiona ni desaparece.',
    fr: 'Un cadre qui englobe une ligne avant et une ligne après glisse dans l’ordre de day. La somme à l’intérieur s’écrit dans la cellule de cette ligne même, et aucune ligne n’est fusionnée ni perdue.',
    hi: 'एक पंक्ति पहले और एक पंक्ति बाद को घेरने वाला फ़्रेम day के क्रम में नीचे खिसकता है। उसके भीतर का योग उसी पंक्ति के अपने खाने में लिखा जाता है, और कोई भी पंक्ति मिलकर गायब नहीं होती।',
    id: 'Bingkai yang memuat satu baris sebelum dan satu baris sesudah bergeser turun menurut urutan day. Jumlah di dalamnya ditulis ke sel baris itu sendiri, dan tidak ada satu baris pun yang digabung hilang.',
    pt: 'Um quadro que abrange uma linha antes e uma depois desliza na ordem de day. A soma dentro dele é escrita na própria célula dessa linha, e nenhuma linha é fundida ou some.',
  },
  algorithm: 'module:windowSlides',
  scene: 'module:windowSlidesScene',
  initialData: {
    type: 'window-slides',
    stepMs: 1200,
    table: 'sales',
    columns: ['day', 'amount'],
    rows: [
      [1, 4],
      [2, 7],
      [3, 2],
      [4, 9],
      [5, 5],
      [6, 3],
    ],
    orderBy: 'day',
    sumOf: 'amount',
    preceding: 1,
    following: 1,
    alias: 'near',
    sql: [
      'SELECT day, amount,',
      '       SUM(amount) OVER (ORDER BY day',
      '         ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS near',
      'FROM sales;',
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Before the query runs, the near column is empty.',
      ko: '질의가 돌기 전이라 near 칸이 비어 있다.',
      ja: '問い合わせが動く前なので near の列は空だ。',
      zh: '查询运行之前，near 列是空的。',
      ar: 'قبل تشغيل الاستعلام، عمود near فارغ.',
      es: 'Antes de ejecutar la consulta, la columna near está vacía.',
      fr: 'Avant l’exécution de la requête, la colonne near est vide.',
      hi: 'क्वेरी चलने से पहले near कॉलम खाली है।',
      id: 'Sebelum kueri berjalan, kolom near masih kosong.',
      pt: 'Antes de a consulta rodar, a coluna near está vazia.',
    },
    'caption.frame': {
      en: 'day {day}: the frame holds day {from}–{to} · sum {sum}',
      ko: 'day {day}: 틀 안은 day {from}–{to} · 합 {sum}',
      ja: 'day {day}: 枠の中は day {from}–{to} · 合計 {sum}',
      zh: 'day {day}：框内是 day {from}–{to} · 和 {sum}',
      ar: 'day {day}: داخل الإطار day {from}–{to} · المجموع {sum}',
      es: 'day {day}: el marco abarca day {from}–{to} · suma {sum}',
      fr: 'day {day} : le cadre contient day {from}–{to} · somme {sum}',
      hi: 'day {day}: फ़्रेम में day {from}–{to} · योग {sum}',
      id: 'day {day}: bingkai memuat day {from}–{to} · jumlah {sum}',
      pt: 'day {day}: o quadro abrange day {from}–{to} · soma {sum}',
    },
    'caption.edge': {
      en: 'day {day}: the frame runs past the table · inside: day {from}–{to} · sum {sum}',
      ko: 'day {day}: 틀이 표 밖으로 나간다 · 틀 안은 day {from}–{to} · 합 {sum}',
      ja: 'day {day}: 枠が表の外にはみ出す · 枠の中は day {from}–{to} · 合計 {sum}',
      zh: 'day {day}：窗框伸出表外 · 框内是 day {from}–{to} · 和 {sum}',
      ar: 'day {day}: الإطار يتجاوز الجدول · داخله day {from}–{to} · المجموع {sum}',
      es: 'day {day}: el marco sale de la tabla · dentro: day {from}–{to} · suma {sum}',
      fr: 'day {day} : le cadre dépasse du tableau · dedans : day {from}–{to} · somme {sum}',
      hi: 'day {day}: फ़्रेम तालिका से बाहर निकलता है · भीतर day {from}–{to} · योग {sum}',
      id: 'day {day}: bingkai keluar dari tabel · di dalam: day {from}–{to} · jumlah {sum}',
      pt: 'day {day}: o quadro passa da tabela · dentro: day {from}–{to} · soma {sum}',
    },
    'label.rows': {
      en: 'Rows: {n}',
      ko: '줄: {n}',
      ja: '行: {n}',
      zh: '行数：{n}',
      ar: 'الصفوف: {n}',
      es: 'Filas: {n}',
      fr: 'Lignes : {n}',
      hi: 'पंक्तियाँ: {n}',
      id: 'Baris: {n}',
      pt: 'Linhas: {n}',
    },
  },
  blocks: {
    stage: { type: 'window-slides-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
