import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: CPU 가 하나뿐일 때, 돌 준비가 된 프로세스들은 어디서 기다렸다가 언제 오르는가?
 *
 * 도착한 프로세스는 CPU 가 차 있으면 준비 큐 끝에 서고, CPU 가 비는 그 순간에만
 * 줄 맨 앞이 빠져 CPU 로 오른다. 화면이 쥐는 것은 줄의 구성원이다 — 시각의 축은 없다.
 */
export const readyQueuePickFacet: FacetJson = {
  id: 'facet:readyQueuePick',
  title: {
    en: 'Ready queue',
    ko: '준비 큐',
    ja: 'レディキュー',
    zh: '就绪队列',
    ar: 'طابور الجاهزية',
    es: 'Cola de listos',
    fr: 'File des prêts',
    hi: 'रेडी क्यू',
    id: 'Antrean siap',
    pt: 'Fila de prontos',
  },
  description: {
    en: 'While the CPU is busy, arriving processes join the back of the line; only when the CPU frees up does the front of the line leave and go up.',
    ko: 'CPU 가 차 있는 동안 도착한 프로세스는 줄 끝에 서고, CPU 가 비는 순간에만 줄 맨 앞이 빠져 오른다.',
    ja: 'CPU が使用中のあいだ、到着したプロセスは列の最後に並ぶ。CPU が空いた瞬間にだけ、列の先頭が抜けて CPU に上がる。',
    zh: 'CPU 忙碌时，到达的进程排到队尾；只有在 CPU 空出来的那一刻，队首才离开队列登上 CPU。',
    ar: 'ما دامت وحدة المعالجة مشغولة تقف العمليات الواصلة في آخر الطابور، ولا يغادر أول الطابور ليصعد إليها إلا لحظة فراغها.',
    es: 'Mientras la CPU está ocupada, los procesos que llegan se ponen al final de la cola; solo cuando la CPU queda libre sale el primero de la cola y sube.',
    fr: 'Tant que le processeur est occupé, les processus qui arrivent se placent en fin de file ; ce n’est qu’au moment où il se libère que la tête de file sort et monte.',
    hi: 'जब तक CPU व्यस्त है, आने वाली प्रक्रियाएँ कतार के अंत में लगती हैं; केवल CPU खाली होने के क्षण कतार का पहला निकलकर ऊपर जाता है।',
    id: 'Selama CPU sibuk, proses yang tiba berdiri di ujung antrean; hanya saat CPU kosong, yang paling depan keluar dan naik.',
    pt: 'Enquanto a CPU está ocupada, os processos que chegam vão para o fim da fila; só quando a CPU fica livre o primeiro da fila sai e sobe.',
  },
  algorithm: 'module:readyQueuePick',
  scene: 'module:readyQueuePickScene',
  initialData: {
    type: 'ready-queue-pick',
    stepMs: 1400,
    procs: [
      { id: 'p1', arrive: 0, burst: 3 },
      { id: 'p2', arrive: 1, burst: 2 },
      { id: 'p3', arrive: 2, burst: 4 },
      { id: 'p4', arrive: 6, burst: 1 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'No one has arrived yet. The line and the CPU are empty.',
      ko: '아직 아무도 오지 않았다. 줄도 CPU 도 비어 있다.',
      ja: 'まだ誰も到着していない。列も CPU も空いている。',
      zh: '还没有进程到达。队列和 CPU 都是空的。',
      ar: 'لم يصل أحد بعد. الطابور ووحدة المعالجة فارغان.',
      es: 'Todavía no ha llegado nadie. La cola y la CPU están vacías.',
      fr: 'Personne n’est encore arrivé. La file et le processeur sont vides.',
      hi: 'अभी कोई नहीं आया। कतार और CPU दोनों खाली हैं।',
      id: 'Belum ada yang tiba. Antrean dan CPU kosong.',
      pt: 'Ninguém chegou ainda. A fila e a CPU estão vazias.',
    },
    'caption.tick': {
      en: 'Tick {tick}',
      ko: '틱 {tick}',
      ja: 'ティック {tick}',
      zh: '时刻 {tick}',
      ar: 'النبضة {tick}',
      es: 'Tic {tick}',
      fr: 'Tic {tick}',
      hi: 'टिक {tick}',
      id: 'Tik {tick}',
      pt: 'Tique {tick}',
    },
    'caption.finishPick': {
      en: 'Finished: {done}. The CPU is free — the front of the line goes up: {name}.',
      ko: '끝남: {done}. CPU 가 비었다 — 줄 맨 앞이 빠져 오른다: {name}.',
      ja: '終了: {done}。CPU が空いた — 列の先頭が抜けて上がる: {name}。',
      zh: '完成：{done}。CPU 空出来了 — 队首离队登上：{name}。',
      ar: 'انتهى: {done}. وحدة المعالجة فارغة — يصعد أول الطابور: {name}.',
      es: 'Terminado: {done}. La CPU queda libre — sube el primero de la cola: {name}.',
      fr: 'Terminé : {done}. Le processeur est libre — la tête de file monte : {name}.',
      hi: 'समाप्त: {done}। CPU खाली है — कतार का पहला ऊपर जाता है: {name}।',
      id: 'Selesai: {done}. CPU kosong — yang paling depan naik: {name}.',
      pt: 'Terminou: {done}. A CPU está livre — o primeiro da fila sobe: {name}.',
    },
    'caption.finishIdle': {
      en: 'Finished: {done}. The line is empty — the CPU stays idle.',
      ko: '끝남: {done}. 줄이 비어 CPU 는 빈 채로 남는다.',
      ja: '終了: {done}。列が空なので CPU は空いたままになる。',
      zh: '完成：{done}。队列为空 — CPU 保持空闲。',
      ar: 'انتهى: {done}. الطابور فارغ — تبقى وحدة المعالجة خاملة.',
      es: 'Terminado: {done}. La cola está vacía — la CPU queda ociosa.',
      fr: 'Terminé : {done}. La file est vide — le processeur reste inactif.',
      hi: 'समाप्त: {done}। कतार खाली है — CPU खाली ही रहता है।',
      id: 'Selesai: {done}. Antrean kosong — CPU tetap menganggur.',
      pt: 'Terminou: {done}. A fila está vazia — a CPU fica ociosa.',
    },
    'caption.finishOnly': {
      en: 'Finished: {done}. The CPU is free.',
      ko: '끝남: {done}. CPU 가 비었다.',
      ja: '終了: {done}。CPU が空いた。',
      zh: '完成：{done}。CPU 空出来了。',
      ar: 'انتهى: {done}. وحدة المعالجة فارغة.',
      es: 'Terminado: {done}. La CPU queda libre.',
      fr: 'Terminé : {done}. Le processeur est libre.',
      hi: 'समाप्त: {done}। CPU खाली है।',
      id: 'Selesai: {done}. CPU kosong.',
      pt: 'Terminou: {done}. A CPU está livre.',
    },
    'caption.pick': {
      en: 'The CPU is free — the front of the line goes up: {name}.',
      ko: 'CPU 가 비었다 — 줄 맨 앞이 빠져 오른다: {name}.',
      ja: 'CPU が空いた — 列の先頭が抜けて上がる: {name}。',
      zh: 'CPU 空出来了 — 队首离队登上：{name}。',
      ar: 'وحدة المعالجة فارغة — يصعد أول الطابور: {name}.',
      es: 'La CPU queda libre — sube el primero de la cola: {name}.',
      fr: 'Le processeur est libre — la tête de file monte : {name}.',
      hi: 'CPU खाली है — कतार का पहला ऊपर जाता है: {name}।',
      id: 'CPU kosong — yang paling depan naik: {name}.',
      pt: 'A CPU está livre — o primeiro da fila sobe: {name}.',
    },
    'caption.arriveStraight': {
      en: 'Arrives: {name}. Nobody is waiting and the CPU is free — it goes straight up.',
      ko: '도착: {name}. 기다리는 것이 없고 CPU 도 비어 곧장 오른다.',
      ja: '到着: {name}。待っているものがなく CPU も空いているので、そのまま上がる。',
      zh: '到达：{name}。没有进程在等，CPU 也空着 — 直接登上。',
      ar: 'وصل: {name}. لا أحد ينتظر ووحدة المعالجة فارغة — يصعد مباشرة.',
      es: 'Llega: {name}. Nadie espera y la CPU está libre — sube directamente.',
      fr: 'Arrivée : {name}. Personne n’attend, processeur libre — il monte directement.',
      hi: 'आगमन: {name}। कोई प्रतीक्षा में नहीं और CPU खाली है — सीधे ऊपर जाता है।',
      id: 'Tiba: {name}. Tak ada yang menunggu dan CPU kosong — langsung naik.',
      pt: 'Chega: {name}. Ninguém espera e a CPU está livre — sobe direto.',
    },
    'caption.arriveBusy': {
      en: 'Arrives: {name}. The CPU is busy — joins the back of the line.',
      ko: '도착: {name}. CPU 가 차 있어 줄 끝에 선다.',
      ja: '到着: {name}。CPU が使用中なので列の最後に並ぶ。',
      zh: '到达：{name}。CPU 正忙 — 排到队尾。',
      ar: 'وصل: {name}. وحدة المعالجة مشغولة — يقف في آخر الطابور.',
      es: 'Llega: {name}. La CPU está ocupada — se pone al final de la cola.',
      fr: 'Arrivée : {name}. Le processeur est occupé — se place en fin de file.',
      hi: 'आगमन: {name}। CPU व्यस्त है — कतार के अंत में लगता है।',
      id: 'Tiba: {name}. CPU sibuk — berdiri di ujung antrean.',
      pt: 'Chega: {name}. A CPU está ocupada — vai para o fim da fila.',
    },
    'label.cpu': {
      en: 'CPU',
      ko: 'CPU',
      ja: 'CPU',
      zh: 'CPU',
      ar: 'وحدة المعالجة',
      es: 'CPU',
      fr: 'Processeur',
      hi: 'CPU',
      id: 'CPU',
      pt: 'CPU',
    },
    'label.cpuIdle': {
      en: 'idle',
      ko: '비어 있음',
      ja: '空き',
      zh: '空闲',
      ar: 'خامل',
      es: 'ociosa',
      fr: 'inactif',
      hi: 'खाली',
      id: 'kosong',
      pt: 'ociosa',
    },
    'label.done': {
      en: 'Finished',
      ko: '끝난 것',
      ja: '終了したもの',
      zh: '已完成',
      ar: 'المنتهية',
      es: 'Terminados',
      fr: 'Terminés',
      hi: 'समाप्त',
      id: 'Selesai',
      pt: 'Terminados',
    },
    'label.queue': {
      en: 'Ready queue',
      ko: '준비 큐',
      ja: 'レディキュー',
      zh: '就绪队列',
      ar: 'طابور الجاهزية',
      es: 'Cola de listos',
      fr: 'File des prêts',
      hi: 'रेडी क्यू',
      id: 'Antrean siap',
      pt: 'Fila de prontos',
    },
    'label.front': {
      en: 'front',
      ko: '앞',
      ja: '先頭',
      zh: '队首',
      ar: 'الأول',
      es: 'frente',
      fr: 'tête',
      hi: 'आगे',
      id: 'depan',
      pt: 'frente',
    },
    'label.back': {
      en: 'back',
      ko: '뒤',
      ja: '最後尾',
      zh: '队尾',
      ar: 'الأخير',
      es: 'final',
      fr: 'queue',
      hi: 'पीछे',
      id: 'belakang',
      pt: 'fim',
    },
    'label.outside': {
      en: 'Not yet arrived',
      ko: '아직 오지 않음',
      ja: '未到着',
      zh: '尚未到达',
      ar: 'لم يصل بعد',
      es: 'Aún no llegan',
      fr: 'Pas encore arrivés',
      hi: 'अभी नहीं आए',
      id: 'Belum tiba',
      pt: 'Ainda não chegaram',
    },
  },
  blocks: {
    stage: { type: 'ready-queue-pick-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
