import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: MVCC 는 줄을 고칠 때 옛 값을 어떻게 하는가.
 *
 * 줄 tea 의 판 30(시작 틱 1) 위에 T2 가 35 를, T3 가 40 을 쓰고 각자 커밋한다.
 * 쓰기는 새 판을 얹기만 하고, 커밋 틱이 옛 판의 끝과 새 판의 시작에 함께 찍힌다. 끝에 판 셋이 남는다.
 */
export const keepOldVersionFacet: FacetJson = {
  id: 'facet:keepOldVersion',
  title: {
    en: 'Keep the old version',
    ko: '옛 판을 남긴다',
    ja: '古い版を残す',
    zh: '保留旧版本',
    ar: 'الإبقاء على النسخة القديمة',
    es: 'Conservar la versión antigua',
    fr: 'Garder l’ancienne version',
    hi: 'पुराना संस्करण बनाए रखना',
    id: 'Menyimpan versi lama',
    pt: 'Manter a versão antiga',
  },
  description: {
    en: 'MVCC never overwrites a row: each write stacks a new version beside the old one, and the commit tick closes the old and opens the new.',
    ko: 'MVCC 는 줄을 덮어쓰지 않는다. 쓸 때마다 새 판이 옛 판 곁에 쌓이고, 커밋 틱이 옛 판을 닫고 새 판을 연다.',
    ja: 'MVCC は行を上書きしない。書くたびに新しい版が古い版の隣に積まれ、コミットのティックが古い版を閉じて新しい版を開く。',
    zh: 'MVCC 从不覆盖一行：每次写入都在旧版本旁叠上一个新版本，提交时刻关闭旧版本并开启新版本。',
    ar: 'لا يكتب MVCC فوق الصف أبدًا: كل كتابة تكدّس نسخة جديدة بجانب القديمة، وعلامة الالتزام تغلق القديمة وتفتح الجديدة.',
    es: 'MVCC nunca sobrescribe una fila: cada escritura apila una versión nueva junto a la antigua, y el tic del commit cierra la antigua y abre la nueva.',
    fr: 'MVCC n’écrase jamais une ligne : chaque écriture empile une nouvelle version à côté de l’ancienne, et le tic du commit ferme l’ancienne et ouvre la nouvelle.',
    hi: 'MVCC किसी पंक्ति को कभी अधिलेखित नहीं करता: हर लेखन पुराने संस्करण के पास एक नया संस्करण जोड़ता है, और कमिट टिक पुराने को बंद कर नए को खोलता है।',
    id: 'MVCC tidak pernah menimpa baris: setiap tulisan menumpuk versi baru di samping versi lama, dan tik commit menutup yang lama serta membuka yang baru.',
    pt: 'O MVCC nunca sobrescreve uma linha: cada escrita empilha uma versão nova ao lado da antiga, e o tique do commit fecha a antiga e abre a nova.',
  },
  algorithm: 'module:keepOldVersion',
  scene: 'module:keepOldVersionScene',
  initialData: {
    type: 'keep-old-version',
    stepMs: 1800,
    row: 'tea',
    versions: [{ value: 30, start: 1, end: null }],
    firstTick: 2,
    events: [
      { op: 'write', txn: 'T2', value: 35 },
      { op: 'commit', txn: 'T2' },
      { op: 'write', txn: 'T3', value: 40 },
      { op: 'commit', txn: 'T3' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Row {row} before any change. Versions: {n}.',
      ko: '고치기 전의 줄 {row}. 판 수: {n}.',
      ja: '変更前の行 {row}。版の数: {n}。',
      zh: '修改前的行 {row}。版本数：{n}。',
      ar: 'الصف {row} قبل أي تغيير. عدد النسخ: {n}.',
      es: 'Fila {row} antes de cualquier cambio. Versiones: {n}.',
      fr: 'Ligne {row} avant toute modification. Versions : {n}.',
      hi: 'किसी बदलाव से पहले पंक्ति {row}। संस्करण: {n}।',
      id: 'Baris {row} sebelum ada perubahan. Versi: {n}.',
      pt: 'Linha {row} antes de qualquer mudança. Versões: {n}.',
    },
    'caption.write': {
      en: '{op}: a new version is stacked on top. Versions: {n}.',
      ko: '{op} — 새 판이 위에 쌓인다. 판 수: {n}.',
      ja: '{op}：新しい版が上に積まれる。版の数: {n}。',
      zh: '{op}：新版本叠在上面。版本数：{n}。',
      ar: '{op}: تُكدَّس نسخة جديدة في الأعلى. عدد النسخ: {n}.',
      es: '{op}: se apila una versión nueva encima. Versiones: {n}.',
      fr: '{op} : une nouvelle version s’empile au-dessus. Versions : {n}.',
      hi: '{op}: ऊपर एक नया संस्करण जुड़ता है। संस्करण: {n}।',
      id: '{op}: versi baru ditumpuk di atas. Versi: {n}.',
      pt: '{op}: uma versão nova é empilhada no topo. Versões: {n}.',
    },
    'caption.commit': {
      en: '{op} at tick {tick}: version {old} ends, version {new} begins. Versions: {n}.',
      ko: '{op} · 틱 {tick} — 판 {old} 끝, 판 {new} 시작. 판 수: {n}.',
      ja: '{op} · ティック {tick}：版 {old} が終わり、版 {new} が始まる。版の数: {n}。',
      zh: '{op} · 时刻 {tick}：版本 {old} 结束，版本 {new} 开始。版本数：{n}。',
      ar: '{op} عند العلامة {tick}: تنتهي النسخة {old} وتبدأ النسخة {new}. عدد النسخ: {n}.',
      es: '{op} en el tic {tick}: termina la versión {old}, empieza la versión {new}. Versiones: {n}.',
      fr: '{op} au tic {tick} : la version {old} se termine, la version {new} commence. Versions : {n}.',
      hi: 'टिक {tick} पर {op}: संस्करण {old} समाप्त, संस्करण {new} आरंभ। संस्करण: {n}।',
      id: '{op} pada tik {tick}: versi {old} berakhir, versi {new} dimulai. Versi: {n}.',
      pt: '{op} no tique {tick}: a versão {old} termina, a versão {new} começa. Versões: {n}.',
    },
    'label.tick': {
      en: 'Tick',
      ko: '틱',
      ja: 'ティック',
      zh: '时刻',
      ar: 'العلامة',
      es: 'Tic',
      fr: 'Tic',
      hi: 'टिक',
      id: 'Tik',
      pt: 'Tique',
    },
    'label.row': {
      en: 'Row {row}',
      ko: '줄 {row}',
      ja: '行 {row}',
      zh: '行 {row}',
      ar: 'الصف {row}',
      es: 'Fila {row}',
      fr: 'Ligne {row}',
      hi: 'पंक्ति {row}',
      id: 'Baris {row}',
      pt: 'Linha {row}',
    },
    'label.start': {
      en: 'Start tick',
      ko: '시작 틱',
      ja: '開始ティック',
      zh: '起始时刻',
      ar: 'علامة البدء',
      es: 'Tic inicial',
      fr: 'Tic de début',
      hi: 'आरंभ टिक',
      id: 'Tik mulai',
      pt: 'Tique inicial',
    },
    'label.end': {
      en: 'End tick',
      ko: '끝 틱',
      ja: '終了ティック',
      zh: '结束时刻',
      ar: 'علامة الانتهاء',
      es: 'Tic final',
      fr: 'Tic de fin',
      hi: 'अंत टिक',
      id: 'Tik akhir',
      pt: 'Tique final',
    },
    'label.current': {
      en: 'Current',
      ko: '지금 판',
      ja: '現在の版',
      zh: '当前版本',
      ar: 'الحالية',
      es: 'Actual',
      fr: 'Actuelle',
      hi: 'वर्तमान',
      id: 'Saat ini',
      pt: 'Atual',
    },
  },
  blocks: {
    stage: { type: 'keep-old-version-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
