import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 베어러 토큰을 받는 서버는 요청을 통과시킬 때 무엇을 보는가 — 누가 보냈는지를 보는가.
 *
 * 토큰이 발급 서버에서 앱의 손으로 넘어가고, 그 사본이 훔친 쪽의 손으로 넘어간다.
 * 두 쪽이 서로 다른 주소에서 같은 토큰을 실어 요청하면 문은 토큰 글자만 읽고 둘 다 연다.
 */
export const tokenBearerFacet: FacetJson = {
  id: 'facet:tokenBearer',
  title: {
    en: 'The door reads only the token',
    ko: '문은 토큰만 본다',
    ja: 'ドアはトークンだけを見る',
    zh: '门只看令牌',
    ar: 'الباب لا يقرأ إلا الرمز',
    es: 'La puerta solo lee el token',
    fr: 'La porte ne lit que le jeton',
    hi: 'दरवाज़ा सिर्फ़ टोकन पढ़ता है',
    id: 'Pintu hanya membaca token',
    pt: 'A porta só lê o token',
  },
  description: {
    en: 'A bearer token passes from hand to hand, and a copy works just like the original: the API server lets in whoever presents it, from any address.',
    ko: '베어러 토큰은 손에서 손으로 넘어가고, 사본도 원본과 똑같이 통한다. API 서버는 어느 주소에서 오든 토큰을 내민 쪽을 들여보낸다.',
    ja: 'ベアラートークンは手から手へ渡り、コピーも原本とまったく同じように通る。API サーバーはどのアドレスから来ても、トークンを差し出した者を通す。',
    zh: '持有者令牌在人手之间传递，副本和原件一样有效：无论来自哪个地址，API 服务器都会放行出示令牌的一方。',
    ar: 'ينتقل رمز الحامل من يد إلى يد، والنسخة تعمل تمامًا مثل الأصل: خادم API يسمح بالدخول لمن يقدّمه، من أي عنوان.',
    es: 'Un token portador pasa de mano en mano y una copia funciona igual que el original: el servidor de la API deja pasar a quien lo presente, desde cualquier dirección.',
    fr: 'Un jeton porteur passe de main en main, et une copie fonctionne comme l’original : le serveur d’API laisse entrer quiconque le présente, depuis n’importe quelle adresse.',
    hi: 'बेयरर टोकन एक हाथ से दूसरे हाथ जाता है, और उसकी प्रति मूल की तरह ही काम करती है: API सर्वर किसी भी पते से आए, टोकन दिखाने वाले को अंदर जाने देता है।',
    id: 'Token pembawa berpindah dari tangan ke tangan, dan salinannya berlaku sama seperti aslinya: server API meloloskan siapa pun yang menunjukkannya, dari alamat mana pun.',
    pt: 'Um token portador passa de mão em mão, e uma cópia funciona igual ao original: o servidor da API deixa passar quem o apresentar, de qualquer endereço.',
  },
  algorithm: 'module:tokenBearer',
  scene: 'module:tokenBearerScene',
  initialData: {
    type: 'token-bearer',
    stepMs: 1500,
    ledger: [{ token: 'mF_9.B5f-4.1JqM', subject: 'u42', issuedAt: 0, expiresAt: 300 }],
    addresses: { app: '198.51.100.7', attacker: '203.0.113.66' },
    requestLine: 'GET /orders HTTP/1.1',
    authPrefix: 'Authorization: Bearer',
    events: [
      { at: 0, kind: 'issue', token: 'mF_9.B5f-4.1JqM', to: 'app' },
      { at: 10, kind: 'request', from: 'app', token: 'mF_9.B5f-4.1JqM' },
      { at: 40, kind: 'leak', from: 'app', to: 'attacker' },
      { at: 60, kind: 'request', from: 'attacker', token: 'mF_9.B5f-4.1JqM' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.issuer': {
      en: 'Issuer',
      ko: '발급 서버',
      ja: '発行サーバー',
      zh: '签发服务器',
      ar: 'خادم الإصدار',
      es: 'Emisor',
      fr: 'Émetteur',
      hi: 'जारीकर्ता',
      id: 'Penerbit',
      pt: 'Emissor',
    },
    'label.app': {
      en: 'App',
      ko: '앱',
      ja: 'アプリ',
      zh: '应用',
      ar: 'التطبيق',
      es: 'App',
      fr: 'Appli',
      hi: 'ऐप',
      id: 'Aplikasi',
      pt: 'App',
    },
    'label.attacker': {
      en: 'Thief',
      ko: '훔친 쪽',
      ja: '盗んだ側',
      zh: '窃取者',
      ar: 'السارق',
      es: 'Ladrón',
      fr: 'Voleur',
      hi: 'चोर',
      id: 'Pencuri',
      pt: 'Ladrão',
    },
    'label.api': {
      en: 'API server',
      ko: 'API 서버',
      ja: 'API サーバー',
      zh: 'API 服务器',
      ar: 'خادم API',
      es: 'Servidor API',
      fr: 'Serveur d’API',
      hi: 'API सर्वर',
      id: 'Server API',
      pt: 'Servidor da API',
    },
    'label.clock': {
      en: 't = {now} s',
      ko: 't = {now} 초',
      ja: 't = {now} 秒',
      zh: 't = {now} 秒',
      ar: 't = {now} ث',
      es: 't = {now} s',
      fr: 't = {now} s',
      hi: 't = {now} से.',
      id: 't = {now} dtk',
      pt: 't = {now} s',
    },
    'label.from': {
      en: 'From: {addr}',
      ko: '보낸 곳: {addr}',
      ja: '送信元: {addr}',
      zh: '来源: {addr}',
      ar: 'من: {addr}',
      es: 'Desde: {addr}',
      fr: 'De : {addr}',
      hi: 'भेजने वाला: {addr}',
      id: 'Dari: {addr}',
      pt: 'De: {addr}',
    },
    'label.ledger': {
      en: 'Issued tokens',
      ko: '발급 기록',
      ja: '発行記録',
      zh: '签发记录',
      ar: 'سجل الإصدار',
      es: 'Tokens emitidos',
      fr: 'Jetons émis',
      hi: 'जारी टोकन',
      id: 'Token terbit',
      pt: 'Tokens emitidos',
    },
    'label.record': {
      en: 'Subject: {sub} · Expires: t={exp} s',
      ko: '주체: {sub} · 만료: t={exp} 초',
      ja: '主体: {sub} · 期限: t={exp} 秒',
      zh: '主体: {sub} · 过期: t={exp} 秒',
      ar: 'الجهة: {sub} · الانتهاء: t={exp} ث',
      es: 'Sujeto: {sub} · Vence: t={exp} s',
      fr: 'Sujet : {sub} · Expire : t={exp} s',
      hi: 'विषय: {sub} · समाप्ति: t={exp} से.',
      id: 'Subjek: {sub} · Kedaluwarsa: t={exp} dtk',
      pt: 'Sujeito: {sub} · Expira: t={exp} s',
    },
    'label.colFrom': {
      en: 'From',
      ko: '보낸 곳',
      ja: '送信元',
      zh: '来源',
      ar: 'من',
      es: 'Desde',
      fr: 'De',
      hi: 'कहाँ से',
      id: 'Dari',
      pt: 'De',
    },
    'label.colToken': {
      en: 'Token the door read',
      ko: '문이 읽은 토큰',
      ja: 'ドアが読んだトークン',
      zh: '门读到的令牌',
      ar: 'الرمز الذي قرأه الباب',
      es: 'Token que leyó la puerta',
      fr: 'Jeton lu par la porte',
      hi: 'दरवाज़े ने जो टोकन पढ़ा',
      id: 'Token yang dibaca pintu',
      pt: 'Token lido pela porta',
    },
    'label.colStatus': {
      en: 'Status',
      ko: '판정',
      ja: '判定',
      zh: '判定',
      ar: 'الحكم',
      es: 'Estado',
      fr: 'Statut',
      hi: 'फ़ैसला',
      id: 'Status',
      pt: 'Status',
    },
    'caption.start': {
      en: 'Nobody holds a token yet.',
      ko: '아직 아무도 토큰을 들지 않았다.',
      ja: 'まだ誰もトークンを持っていない。',
      zh: '还没有人持有令牌。',
      ar: 'لا أحد يحمل رمزًا بعد.',
      es: 'Nadie tiene todavía un token.',
      fr: 'Personne ne détient encore de jeton.',
      hi: 'अभी किसी के पास टोकन नहीं है।',
      id: 'Belum ada yang memegang token.',
      pt: 'Ninguém tem um token ainda.',
    },
    'caption.issue': {
      en: 'The issuer hands a token to {to}.',
      ko: '발급 서버가 {to}에게 토큰을 건넨다.',
      ja: '発行サーバーがトークンを渡す。受け取る側: {to}',
      zh: '签发服务器把令牌交给{to}。',
      ar: 'يسلّم خادم الإصدار رمزًا إلى {to}.',
      es: 'El emisor entrega un token a {to}.',
      fr: 'L’émetteur remet un jeton à {to}.',
      hi: 'जारीकर्ता टोकन सौंपता है — पाने वाला: {to}।',
      id: 'Penerbit menyerahkan token kepada {to}.',
      pt: 'O emissor entrega um token para {to}.',
    },
    'caption.expires': {
      en: 'Expires at: t={exp} s',
      ko: '만료: t={exp} 초',
      ja: '期限: t={exp} 秒',
      zh: '过期时间: t={exp} 秒',
      ar: 'ينتهي عند: t={exp} ث',
      es: 'Vence en: t={exp} s',
      fr: 'Expire à : t={exp} s',
      hi: 'समाप्ति: t={exp} से.',
      id: 'Kedaluwarsa pada: t={exp} dtk',
      pt: 'Expira em: t={exp} s',
    },
    'caption.leak': {
      en: 'A copy of the token passes from {from} to {to}. {from} still holds it.',
      ko: '토큰 사본이 넘어간다: {from} → {to}. {from}도 그대로 들고 있다.',
      ja: 'トークンのコピーが渡る: {from} → {to}。{from}も元のまま持っている。',
      zh: '令牌的副本传了过去: {from} → {to}。{from}仍然持有它。',
      ar: 'تنتقل نسخة من الرمز من {from} إلى {to}. وما زال {from} يحمله.',
      es: 'Una copia del token pasa de {from} a {to}. {from} lo sigue teniendo.',
      fr: 'Une copie du jeton passe de {from} à {to}. {from} le détient toujours.',
      hi: 'टोकन की प्रति जाती है: {from} → {to}। {from} के पास भी वह बना रहता है।',
      id: 'Salinan token berpindah dari {from} ke {to}. {from} tetap memegangnya.',
      pt: 'Uma cópia do token passa de {from} para {to}. {from} continua com ele.',
    },
    'caption.holders': {
      en: 'Holders: {n}',
      ko: '든 쪽: {n}',
      ja: '持っている側: {n}',
      zh: '持有者: {n}',
      ar: 'الحاملون: {n}',
      es: 'Portadores: {n}',
      fr: 'Détenteurs : {n}',
      hi: 'धारक: {n}',
      id: 'Pemegang: {n}',
      pt: 'Portadores: {n}',
    },
    'caption.request': {
      en: 'Request from {from}, address {addr}. The door reads the token.',
      ko: '요청 — 보낸 쪽 {from}, 주소 {addr}. 문이 토큰을 읽는다.',
      ja: 'リクエスト — 送り手 {from}、アドレス {addr}。ドアがトークンを読む。',
      zh: '请求 — 发送方 {from}，地址 {addr}。门读取令牌。',
      ar: 'طلب من {from}، العنوان {addr}. الباب يقرأ الرمز.',
      es: 'Petición de {from}, dirección {addr}. La puerta lee el token.',
      fr: 'Requête de {from}, adresse {addr}. La porte lit le jeton.',
      hi: 'अनुरोध — भेजने वाला {from}, पता {addr}। दरवाज़ा टोकन पढ़ता है।',
      id: 'Permintaan dari {from}, alamat {addr}. Pintu membaca token.',
      pt: 'Pedido de {from}, endereço {addr}. A porta lê o token.',
    },
    'caption.valid': {
      en: 'Status: {status} · on record · time left: {left} s',
      ko: '판정: {status} · 기록에 있음 · 남은 시간: {left} 초',
      ja: '判定: {status} · 記録にある · 残り時間: {left} 秒',
      zh: '判定: {status} · 有记录 · 剩余时间: {left} 秒',
      ar: 'الحكم: {status} · موجود في السجل · الوقت المتبقي: {left} ث',
      es: 'Estado: {status} · registrado · tiempo restante: {left} s',
      fr: 'Statut : {status} · enregistré · temps restant : {left} s',
      hi: 'फ़ैसला: {status} · रिकॉर्ड में है · बचा समय: {left} से.',
      id: 'Status: {status} · tercatat · sisa waktu: {left} dtk',
      pt: 'Status: {status} · registrado · tempo restante: {left} s',
    },
    'caption.expired': {
      en: 'Status: {status} · expired · overdue: {over} s',
      ko: '판정: {status} · 만료됨 · 지난 시간: {over} 초',
      ja: '判定: {status} · 期限切れ · 超過: {over} 秒',
      zh: '判定: {status} · 已过期 · 超出: {over} 秒',
      ar: 'الحكم: {status} · منتهي الصلاحية · التأخر: {over} ث',
      es: 'Estado: {status} · vencido · retraso: {over} s',
      fr: 'Statut : {status} · expiré · dépassement : {over} s',
      hi: 'फ़ैसला: {status} · समाप्त · देरी: {over} से.',
      id: 'Status: {status} · kedaluwarsa · lewat: {over} dtk',
      pt: 'Status: {status} · expirado · atraso: {over} s',
    },
    'caption.unknown': {
      en: 'Status: {status} · not on record',
      ko: '판정: {status} · 기록에 없음',
      ja: '判定: {status} · 記録にない',
      zh: '判定: {status} · 无记录',
      ar: 'الحكم: {status} · غير موجود في السجل',
      es: 'Estado: {status} · sin registro',
      fr: 'Statut : {status} · non enregistré',
      hi: 'फ़ैसला: {status} · रिकॉर्ड में नहीं',
      id: 'Status: {status} · tidak tercatat',
      pt: 'Status: {status} · sem registro',
    },
  },
  blocks: {
    stage: { type: 'token-bearer-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
