import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 길이가 제각각인 화살표들을 길이 1 로 맞추면 무엇이 남는가.
 */
export const vectorNormalizeFacet: FacetJson = {
  id: 'facet:vectorNormalize',
  title: {
    en: 'Normalizing: every arrow to length 1',
    ko: '정규화: 모든 화살표를 길이 1 로',
    ja: '正規化：すべての矢印を長さ 1 に',
    zh: '归一化：把每个箭头变成长度 1',
    ar: 'التسوية: كل سهم إلى الطول 1',
    es: 'Normalizar: cada flecha a longitud 1',
    fr: 'Normaliser : chaque flèche à la longueur 1',
    hi: 'सामान्यीकरण: हर तीर की लंबाई 1',
    id: 'Normalisasi: setiap panah menjadi panjang 1',
    pt: 'Normalizar: cada seta com comprimento 1',
  },
  description: {
    en: 'Four arrows of different lengths are each divided by their own length. They all end up at length 1, and only their angles still tell them apart.',
    ko: '길이가 다른 화살표 넷을 저마다 제 길이로 나눈다. 모두 길이 1 에 모이고, 넷을 가르는 것은 각만 남는다.',
    ja: '長さの違う四本の矢印を、それぞれ自分の長さで割る。すべて長さ 1 にそろい、四本を分けるのは角度だけになる。',
    zh: '四个长度不同的箭头各自除以自己的长度。它们都变成长度 1，区分它们的只剩角度。',
    ar: 'أربعة أسهم بأطوال مختلفة يُقسم كل منها على طوله. تنتهي كلها بالطول 1، ولا يبقى ما يميزها سوى زواياها.',
    es: 'Cuatro flechas de distinta longitud se dividen cada una por su propia longitud. Todas acaban con longitud 1 y solo sus ángulos las distinguen.',
    fr: 'Quatre flèches de longueurs différentes sont chacune divisées par leur propre longueur. Toutes finissent à la longueur 1, et seuls leurs angles les distinguent encore.',
    hi: 'अलग-अलग लंबाई के चार तीरों को हर एक की अपनी लंबाई से भाग दिया जाता है। सब लंबाई 1 पर आ जाते हैं, और उन्हें अलग करता है केवल कोण।',
    id: 'Empat panah dengan panjang berbeda masing-masing dibagi dengan panjangnya sendiri. Semuanya berakhir dengan panjang 1, dan hanya sudutnya yang masih membedakan mereka.',
    pt: 'Quatro setas de comprimentos diferentes são divididas cada uma pelo próprio comprimento. Todas terminam com comprimento 1, e só os ângulos ainda as distinguem.',
  },
  algorithm: 'module:vectorNormalize',
  scene: 'module:vectorNormalizeScene',
  initialData: {
    type: 'vector-normalize',
    vectors: [
      { name: 'p', x: 3, y: 4 },
      { name: 'q', x: -2.4, y: 1.8 },
      { name: 'r', x: 0, y: -2 },
      { name: 's', x: 0.3, y: -0.4 },
    ],
    stepMs: 1800,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Divide each arrow by its own length.',
      ko: '화살표마다 제 길이로 나눈다.',
      ja: '矢印をそれぞれ自分の長さで割る。',
      zh: '每个箭头除以自己的长度。',
      ar: 'اقسم كل سهم على طوله.',
      es: 'Divide cada flecha por su propia longitud.',
      fr: 'Divise chaque flèche par sa propre longueur.',
      hi: 'हर तीर को उसकी अपनी लंबाई से भाग दो।',
      id: 'Bagi setiap panah dengan panjangnya sendiri.',
      pt: 'Divida cada seta pelo próprio comprimento.',
    },
    'caption.divide': {
      en: '{name} ÷ {length} → {coords}',
      ko: '{name} ÷ {length} → {coords}',
      ja: '{name} ÷ {length} → {coords}',
      zh: '{name} ÷ {length} → {coords}',
      ar: '{name} ÷ {length} → {coords}',
      es: '{name} ÷ {length} → {coords}',
      fr: '{name} ÷ {length} → {coords}',
      hi: '{name} ÷ {length} → {coords}',
      id: '{name} ÷ {length} → {coords}',
      pt: '{name} ÷ {length} → {coords}',
    },
    'caption.shrinks': {
      en: 'Length: {length} · Angle: {before} → {after} · Shrinks: ×{factor}',
      ko: '길이: {length} · 각: {before} → {after} · 줄어든다: ×{factor}',
      ja: '長さ: {length} · 角度: {before} → {after} · 縮む: ×{factor}',
      zh: '长度：{length} · 角度：{before} → {after} · 缩短：×{factor}',
      ar: 'الطول: {length} · الزاوية: {before} → {after} · يقصر: ×{factor}',
      es: 'Longitud: {length} · Ángulo: {before} → {after} · Se acorta: ×{factor}',
      fr: 'Longueur : {length} · Angle : {before} → {after} · Raccourcit : ×{factor}',
      hi: 'लंबाई: {length} · कोण: {before} → {after} · घटती है: ×{factor}',
      id: 'Panjang: {length} · Sudut: {before} → {after} · Memendek: ×{factor}',
      pt: 'Comprimento: {length} · Ângulo: {before} → {after} · Encolhe: ×{factor}',
    },
    'caption.grows': {
      en: 'Length: {length} · Angle: {before} → {after} · Grows: ×{factor}',
      ko: '길이: {length} · 각: {before} → {after} · 늘어난다: ×{factor}',
      ja: '長さ: {length} · 角度: {before} → {after} · 伸びる: ×{factor}',
      zh: '长度：{length} · 角度：{before} → {after} · 伸长：×{factor}',
      ar: 'الطول: {length} · الزاوية: {before} → {after} · يطول: ×{factor}',
      es: 'Longitud: {length} · Ángulo: {before} → {after} · Se alarga: ×{factor}',
      fr: 'Longueur : {length} · Angle : {before} → {after} · S’allonge : ×{factor}',
      hi: 'लंबाई: {length} · कोण: {before} → {after} · बढ़ती है: ×{factor}',
      id: 'Panjang: {length} · Sudut: {before} → {after} · Memanjang: ×{factor}',
      pt: 'Comprimento: {length} · Ângulo: {before} → {after} · Cresce: ×{factor}',
    },
    'caption.stays': {
      en: 'Length: {length} · Angle: {before} → {after} · Stays: ×{factor}',
      ko: '길이: {length} · 각: {before} → {after} · 그대로: ×{factor}',
      ja: '長さ: {length} · 角度: {before} → {after} · 変わらない: ×{factor}',
      zh: '长度：{length} · 角度：{before} → {after} · 不变：×{factor}',
      ar: 'الطول: {length} · الزاوية: {before} → {after} · يبقى: ×{factor}',
      es: 'Longitud: {length} · Ángulo: {before} → {after} · Se mantiene: ×{factor}',
      fr: 'Longueur : {length} · Angle : {before} → {after} · Inchangée : ×{factor}',
      hi: 'लंबाई: {length} · कोण: {before} → {after} · वैसी ही: ×{factor}',
      id: 'Panjang: {length} · Sudut: {before} → {after} · Tetap: ×{factor}',
      pt: 'Comprimento: {length} · Ângulo: {before} → {after} · Mantém: ×{factor}',
    },
    'caption.all': {
      en: 'Lengths: {lengths}  ·  Angles: {angles}',
      ko: '길이: {lengths}  ·  각: {angles}',
      ja: '長さ: {lengths}  ·  角度: {angles}',
      zh: '长度：{lengths}  ·  角度：{angles}',
      ar: 'الأطوال: {lengths}  ·  الزوايا: {angles}',
      es: 'Longitudes: {lengths}  ·  Ángulos: {angles}',
      fr: 'Longueurs : {lengths}  ·  Angles : {angles}',
      hi: 'लंबाइयाँ: {lengths}  ·  कोण: {angles}',
      id: 'Panjang: {lengths}  ·  Sudut: {angles}',
      pt: 'Comprimentos: {lengths}  ·  Ângulos: {angles}',
    },
    'label.length': {
      en: 'Length',
      ko: '길이',
      ja: '長さ',
      zh: '长度',
      ar: 'الطول',
      es: 'Longitud',
      fr: 'Longueur',
      hi: 'लंबाई',
      id: 'Panjang',
      pt: 'Comprimento',
    },
    'label.angle': {
      en: 'Angle',
      ko: '각',
      ja: '角度',
      zh: '角度',
      ar: 'الزاوية',
      es: 'Ángulo',
      fr: 'Angle',
      hi: 'कोण',
      id: 'Sudut',
      pt: 'Ângulo',
    },
  },
  blocks: {
    stage: { type: 'vector-normalize-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
