import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 감당보다 많은 요청이 몰릴 때, 모두 받아 주는 서버와 일부를 곧바로 거절하는 서버 가운데
 * 누가 더 많은 요청을 제때 끝내는가.
 */
export const shedToSurviveFacet: FacetJson = {
  id: 'facet:shedToSurvive',
  title: {
    en: 'Shed to survive',
    ko: '버려서 살아남기',
    ja: '捨てて生き残る',
    zh: '舍弃以求生存',
    ar: 'التخلّي من أجل البقاء',
    es: 'Descartar para sobrevivir',
    fr: 'Délester pour survivre',
    hi: 'बचने के लिए छोड़ना',
    id: 'Membuang agar bertahan',
    pt: 'Descartar para sobreviver',
  },
  description: {
    en: 'Rather than let everything collapse, turn some away.',
    ko: '다 무너지느니 일부를 거절한다.',
    ja: 'すべてが崩れるより、一部を断る。',
    zh: '与其全部崩溃，不如拒绝一部分。',
    ar: 'بدلًا من أن ينهار كل شيء، ارفض بعض الطلبات.',
    es: 'Antes que dejar que todo se derrumbe, rechaza una parte.',
    fr: 'Plutôt que de tout laisser s’effondrer, en refuser une partie.',
    hi: 'सब कुछ ढहने देने के बजाय, कुछ को लौटा दो।',
    id: 'Daripada semuanya runtuh, tolak sebagian.',
    pt: 'Em vez de deixar tudo desabar, recusar uma parte.',
  },
  algorithm: 'module:shedToSurvive',
  scene: 'module:shedToSurviveScene',
  initialData: {
    type: 'shed-to-survive',
    stepMs: 1500,
    arrivals: [
      { tick: 0, ids: ['r1', 'r2', 'r3'] },
      { tick: 1, ids: ['r4', 'r5', 'r6'] },
      { tick: 2, ids: ['r7', 'r8', 'r9'] },
      { tick: 3, ids: ['r10', 'r11', 'r12'] },
    ],
    work: 1,
    capacity: 1,
    deadline: 3,
    limit: 1,
    code: '503',
  },
  shuffleOnReset: false,
  messages: {
    'cap.ready': {
      en: 'Before tick 0 — both servers are empty.',
      ko: '틱 0 전 — 두 서버 모두 비어 있다.',
      ja: 'ティック 0 の前 — 両方のサーバーは空。',
      zh: '第 0 刻之前 — 两台服务器都是空的。',
      ar: 'قبل النبضة 0 — الخادمان فارغان.',
      es: 'Antes del tick 0: ambos servidores están vacíos.',
      fr: 'Avant le tick 0 — les deux serveurs sont vides.',
      hi: 'टिक 0 से पहले — दोनों सर्वर खाली हैं।',
      id: 'Sebelum tik 0 — kedua server kosong.',
      pt: 'Antes do tique 0 — os dois servidores estão vazios.',
    },
    'cap.tick': {
      en: 'Tick {tick}',
      ko: '틱 {tick}',
      ja: 'ティック {tick}',
      zh: '第 {tick} 刻',
      ar: 'النبضة {tick}',
      es: 'Tick {tick}',
      fr: 'Tick {tick}',
      hi: 'टिक {tick}',
      id: 'Tik {tick}',
      pt: 'Tique {tick}',
    },
    'cap.end': {
      en: 'Tick {tick} — done in time: accept-all {a} / {total} · shedder {b} / {total}',
      ko: '틱 {tick} — 기한 안에 끝남: 다 받는 쪽 {a} / {total} · 거절하는 쪽 {b} / {total}',
      ja: 'ティック {tick} — 期限内に完了: 全部受ける側 {a} / {total} · 断る側 {b} / {total}',
      zh: '第 {tick} 刻 — 按时完成：全部接收 {a} / {total} · 拒绝一部分 {b} / {total}',
      ar: 'النبضة {tick} — أُنجز في الوقت: القابل للكل {a} / {total} · الرافض {b} / {total}',
      es: 'Tick {tick} — a tiempo: acepta todo {a} / {total} · descarta {b} / {total}',
      fr: 'Tick {tick} — finies à temps : accepte tout {a} / {total} · délesteur {b} / {total}',
      hi: 'टिक {tick} — समय पर पूरे: सब लेने वाला {a} / {total} · लौटाने वाला {b} / {total}',
      id: 'Tik {tick} — selesai tepat waktu: terima semua {a} / {total} · penolak {b} / {total}',
      pt: 'Tique {tick} — concluídas a tempo: aceita tudo {a} / {total} · descarta {b} / {total}',
    },
    'capA.take': {
      en: 'Took {ids}. No work done yet.',
      ko: '받음: {ids}. 아직 한 일은 없다.',
      ja: '受けた: {ids}。まだ仕事はしていない。',
      zh: '接收：{ids}。还没有做任何工作。',
      ar: 'استُقبل: {ids}. لم يُنجز أي عمل بعد.',
      es: 'Aceptó: {ids}. Aún no hay trabajo hecho.',
      fr: 'Acceptées : {ids}. Aucun travail fait pour l’instant.',
      hi: 'लिए गए: {ids}। अभी कोई काम नहीं हुआ।',
      id: 'Diterima: {ids}. Belum ada kerja.',
      pt: 'Aceitou: {ids}. Nenhum trabalho feito ainda.',
    },
    'capA.workTake': {
      en: 'Split the tick {m} ways — 1/{m} each. Took {ids}.',
      ko: '한 틱을 {m} 갈래로 — 하나에 1/{m}. 받음: {ids}.',
      ja: '1 ティックを {m} 等分 — 各 1/{m}。受けた: {ids}。',
      zh: '把一刻分成 {m} 份 — 每个 1/{m}。接收：{ids}。',
      ar: 'قُسِّمت النبضة على {m} — لكلٍّ 1/{m}. استُقبل: {ids}.',
      es: 'El tick se reparte entre {m}: 1/{m} cada uno. Aceptó: {ids}.',
      fr: 'Le tick est partagé en {m} — 1/{m} chacune. Acceptées : {ids}.',
      hi: 'टिक को {m} हिस्सों में बाँटा — हर एक को 1/{m}। लिए गए: {ids}।',
      id: 'Satu tik dibagi {m} — masing-masing 1/{m}. Diterima: {ids}.',
      pt: 'O tique é dividido em {m} — 1/{m} para cada. Aceitou: {ids}.',
    },
    'capA.workLeaveTake': {
      en: 'Split {m} ways — 1/{m} each. Past the deadline, left: {left}. Took {ids}.',
      ko: '{m} 갈래로 — 하나에 1/{m}. 기한을 넘겨 떠남: {left}. 받음: {ids}.',
      ja: '{m} 等分 — 各 1/{m}。期限切れで去った: {left}。受けた: {ids}。',
      zh: '分成 {m} 份 — 每个 1/{m}。超过期限离开：{left}。接收：{ids}。',
      ar: 'على {m} — لكلٍّ 1/{m}. تجاوز المهلة وغادر: {left}. استُقبل: {ids}.',
      es: 'Entre {m}: 1/{m} cada uno. Pasado el plazo, se fueron: {left}. Aceptó: {ids}.',
      fr: 'En {m} — 1/{m} chacune. Délai dépassé, partis : {left}. Acceptées : {ids}.',
      hi: '{m} हिस्से — हर एक को 1/{m}। समय-सीमा पार, चले गए: {left}। लिए गए: {ids}।',
      id: 'Dibagi {m} — masing-masing 1/{m}. Lewat tenggat, pergi: {left}. Diterima: {ids}.',
      pt: 'Em {m} — 1/{m} para cada. Prazo vencido, foram embora: {left}. Aceitou: {ids}.',
    },
    'capA.workLeave': {
      en: 'Split {m} ways — 1/{m} each, gone clients included. Past the deadline, left: {left}.',
      ko: '{m} 갈래로 — 하나에 1/{m}, 떠난 손님 몫까지. 기한을 넘겨 떠남: {left}.',
      ja: '{m} 等分 — 各 1/{m}、去った客の分も。期限切れで去った: {left}。',
      zh: '分成 {m} 份 — 每个 1/{m}，已离开的客户也算在内。超过期限离开：{left}。',
      ar: 'على {m} — لكلٍّ 1/{m}، بما فيها من غادروا. تجاوز المهلة وغادر: {left}.',
      es: 'Entre {m}: 1/{m} cada uno, incluidos los que se fueron. Pasado el plazo, se fueron: {left}.',
      fr: 'En {m} — 1/{m} chacune, clients partis compris. Délai dépassé, partis : {left}.',
      hi: '{m} हिस्से — हर एक को 1/{m}, जा चुके ग्राहकों सहित। समय-सीमा पार, चले गए: {left}।',
      id: 'Dibagi {m} — masing-masing 1/{m}, termasuk yang sudah pergi. Lewat tenggat, pergi: {left}.',
      pt: 'Em {m} — 1/{m} para cada, incluindo quem já foi. Prazo vencido, foram embora: {left}.',
    },
    'capA.work': {
      en: 'Split the tick {m} ways — 1/{m} each.',
      ko: '한 틱을 {m} 갈래로 — 하나에 1/{m}.',
      ja: '1 ティックを {m} 等分 — 各 1/{m}。',
      zh: '把一刻分成 {m} 份 — 每个 1/{m}。',
      ar: 'قُسِّمت النبضة على {m} — لكلٍّ 1/{m}.',
      es: 'El tick se reparte entre {m}: 1/{m} cada uno.',
      fr: 'Le tick est partagé en {m} — 1/{m} chacune.',
      hi: 'टिक को {m} हिस्सों में बाँटा — हर एक को 1/{m}।',
      id: 'Satu tik dibagi {m} — masing-masing 1/{m}.',
      pt: 'O tique é dividido em {m} — 1/{m} para cada.',
    },
    'capB.takeReject': {
      en: 'Took {id}. Turned away at once with {code}: {rejected}.',
      ko: '받음: {id}. 곧바로 돌려보냄({code}): {rejected}.',
      ja: '受けた: {id}。すぐに {code} で断った: {rejected}。',
      zh: '接收：{id}。立即以 {code} 拒绝：{rejected}。',
      ar: 'استُقبل: {id}. رُفض فورًا بـ {code}: {rejected}.',
      es: 'Aceptó: {id}. Rechazados al instante con {code}: {rejected}.',
      fr: 'Acceptée : {id}. Refusées aussitôt avec {code} : {rejected}.',
      hi: 'लिया: {id}। तुरंत {code} के साथ लौटाए: {rejected}।',
      id: 'Diterima: {id}. Langsung ditolak dengan {code}: {rejected}.',
      pt: 'Aceitou: {id}. Recusadas na hora com {code}: {rejected}.',
    },
    'capB.finishTakeReject': {
      en: 'Whole tick, finished: {done}. Took {id}. At once {code}: {rejected}.',
      ko: '한 틱 통째로 받아 끝남: {done}. 받음: {id}. 곧바로 돌려보냄({code}): {rejected}.',
      ja: '1 ティック丸ごとで完了: {done}。受けた: {id}。すぐに {code}: {rejected}。',
      zh: '独占整刻，完成：{done}。接收：{id}。立即 {code}：{rejected}。',
      ar: 'نبضة كاملة، اكتمل: {done}. استُقبل: {id}. فورًا {code}: {rejected}.',
      es: 'Con el tick entero, terminó: {done}. Aceptó: {id}. Al instante {code}: {rejected}.',
      fr: 'Tick entier, terminée : {done}. Acceptée : {id}. Aussitôt {code} : {rejected}.',
      hi: 'पूरा टिक, पूरा हुआ: {done}। लिया: {id}। तुरंत {code}: {rejected}।',
      id: 'Satu tik penuh, selesai: {done}. Diterima: {id}. Langsung {code}: {rejected}.',
      pt: 'Tique inteiro, concluída: {done}. Aceitou: {id}. Na hora {code}: {rejected}.',
    },
    'capB.finishTake': {
      en: 'Whole tick, finished: {done}. Took {id}.',
      ko: '한 틱 통째로 받아 끝남: {done}. 받음: {id}.',
      ja: '1 ティック丸ごとで完了: {done}。受けた: {id}。',
      zh: '独占整刻，完成：{done}。接收：{id}。',
      ar: 'نبضة كاملة، اكتمل: {done}. استُقبل: {id}.',
      es: 'Con el tick entero, terminó: {done}. Aceptó: {id}.',
      fr: 'Tick entier, terminée : {done}. Acceptée : {id}.',
      hi: 'पूरा टिक, पूरा हुआ: {done}। लिया: {id}।',
      id: 'Satu tik penuh, selesai: {done}. Diterima: {id}.',
      pt: 'Tique inteiro, concluída: {done}. Aceitou: {id}.',
    },
    'capB.take': {
      en: 'Took {id}.',
      ko: '받음: {id}.',
      ja: '受けた: {id}。',
      zh: '接收：{id}。',
      ar: 'استُقبل: {id}.',
      es: 'Aceptó: {id}.',
      fr: 'Acceptée : {id}.',
      hi: 'लिया: {id}।',
      id: 'Diterima: {id}.',
      pt: 'Aceitou: {id}.',
    },
    'capB.finish': {
      en: 'Whole tick, finished: {done}. Nothing held now.',
      ko: '한 틱 통째로 받아 끝남: {done}. 이제 들고 있는 것 없음.',
      ja: '1 ティック丸ごとで完了: {done}。いまは何も持っていない。',
      zh: '独占整刻，完成：{done}。现在手上没有请求。',
      ar: 'نبضة كاملة، اكتمل: {done}. لا شيء قيد المعالجة الآن.',
      es: 'Con el tick entero, terminó: {done}. Ahora no sostiene nada.',
      fr: 'Tick entier, terminée : {done}. Plus rien en cours.',
      hi: 'पूरा टिक, पूरा हुआ: {done}। अब कुछ नहीं पकड़ा है।',
      id: 'Satu tik penuh, selesai: {done}. Kini tak memegang apa pun.',
      pt: 'Tique inteiro, concluída: {done}. Agora nada em andamento.',
    },
    'capB.idle': {
      en: 'Nothing held — the server sits idle.',
      ko: '들고 있는 것 없음 — 서버가 논다.',
      ja: '何も持っていない — サーバーは空いている。',
      zh: '手上没有请求 — 服务器空闲。',
      ar: 'لا شيء قيد المعالجة — الخادم خامل.',
      es: 'No sostiene nada: el servidor está ocioso.',
      fr: 'Rien en cours — le serveur est inactif.',
      hi: 'कुछ नहीं पकड़ा — सर्वर खाली बैठा है।',
      id: 'Tak memegang apa pun — server menganggur.',
      pt: 'Nada em andamento — o servidor está ocioso.',
    },
    'label.arrivals': {
      en: 'Arrivals',
      ko: '도착',
      ja: '到着',
      zh: '到达',
      ar: 'الواصلة',
      es: 'Llegadas',
      fr: 'Arrivées',
      hi: 'आगमन',
      id: 'Kedatangan',
      pt: 'Chegadas',
    },
    'label.row': {
      en: 'Tick {tick}',
      ko: '틱 {tick}',
      ja: 'ティック {tick}',
      zh: '第 {tick} 刻',
      ar: 'نبضة {tick}',
      es: 'Tick {tick}',
      fr: 'Tick {tick}',
      hi: 'टिक {tick}',
      id: 'Tik {tick}',
      pt: 'Tique {tick}',
    },
    'label.accept': {
      en: 'Accepts everything',
      ko: '다 받는 서버',
      ja: '全部受けるサーバー',
      zh: '全部接收的服务器',
      ar: 'خادم يقبل كل شيء',
      es: 'Acepta todo',
      fr: 'Accepte tout',
      hi: 'सब लेने वाला सर्वर',
      id: 'Menerima semua',
      pt: 'Aceita tudo',
    },
    'label.shed': {
      en: 'Sheds load — limit: {limit}',
      ko: '거절하는 서버 — 한도: {limit}',
      ja: '断るサーバー — 上限: {limit}',
      zh: '拒绝一部分的服务器 — 上限：{limit}',
      ar: 'خادم يرفض الزائد — الحد: {limit}',
      es: 'Descarta carga — límite: {limit}',
      fr: 'Déleste — limite : {limit}',
      hi: 'लौटाने वाला सर्वर — सीमा: {limit}',
      id: 'Membuang beban — batas: {limit}',
      pt: 'Descarta carga — limite: {limit}',
    },
    'label.share': {
      en: 'Share: 1/{n}',
      ko: '몫: 1/{n}',
      ja: '取り分: 1/{n}',
      zh: '份额：1/{n}',
      ar: 'الحصة: 1/{n}',
      es: 'Parte: 1/{n}',
      fr: 'Part : 1/{n}',
      hi: 'हिस्सा: 1/{n}',
      id: 'Jatah: 1/{n}',
      pt: 'Fatia: 1/{n}',
    },
    'label.idle': {
      en: 'Idle',
      ko: '한가함',
      ja: '空き',
      zh: '空闲',
      ar: 'خامل',
      es: 'Ocioso',
      fr: 'Inactif',
      hi: 'खाली',
      id: 'Menganggur',
      pt: 'Ocioso',
    },
    'label.doneRow': {
      en: 'Done',
      ko: '끝',
      ja: '完了',
      zh: '完成',
      ar: 'مكتمل',
      es: 'Hechas',
      fr: 'Finies',
      hi: 'पूरे',
      id: 'Selesai',
      pt: 'Concluídas',
    },
    'label.rejectRow': {
      en: 'Rejected',
      ko: '거절',
      ja: '拒否',
      zh: '拒绝',
      ar: 'مرفوض',
      es: 'Rechazadas',
      fr: 'Refusées',
      hi: 'लौटाए',
      id: 'Ditolak',
      pt: 'Recusadas',
    },
    'tally.accept': {
      en: 'Held: {held} · Done: {ok} · Left: {gone}',
      ko: '들고 있음: {held} · 끝: {ok} · 떠남: {gone}',
      ja: '保持: {held} · 完了: {ok} · 去った: {gone}',
      zh: '持有：{held} · 完成：{ok} · 离开：{gone}',
      ar: 'قيد المعالجة: {held} · مكتمل: {ok} · غادر: {gone}',
      es: 'En curso: {held} · Hechas: {ok} · Se fueron: {gone}',
      fr: 'En cours : {held} · Finies : {ok} · Partis : {gone}',
      hi: 'पकड़े: {held} · पूरे: {ok} · चले गए: {gone}',
      id: 'Dipegang: {held} · Selesai: {ok} · Pergi: {gone}',
      pt: 'Em andamento: {held} · Concluídas: {ok} · Foram embora: {gone}',
    },
    'tally.shed': {
      en: 'Held: {held} · Done: {ok} · Rejected: {rej}',
      ko: '들고 있음: {held} · 끝: {ok} · 거절: {rej}',
      ja: '保持: {held} · 完了: {ok} · 拒否: {rej}',
      zh: '持有：{held} · 完成：{ok} · 拒绝：{rej}',
      ar: 'قيد المعالجة: {held} · مكتمل: {ok} · مرفوض: {rej}',
      es: 'En curso: {held} · Hechas: {ok} · Rechazadas: {rej}',
      fr: 'En cours : {held} · Finies : {ok} · Refusées : {rej}',
      hi: 'पकड़े: {held} · पूरे: {ok} · लौटाए: {rej}',
      id: 'Dipegang: {held} · Selesai: {ok} · Ditolak: {rej}',
      pt: 'Em andamento: {held} · Concluídas: {ok} · Recusadas: {rej}',
    },
  },
  blocks: {
    stage: { type: 'shed-to-survive-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
