import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 한 번 떼어 둔 점수는 어느 것을 뗐느냐에 달린다 — 모두가 한 번씩 시험지가 되게 하려면?
 *
 * 시험지 자리가 폴드에서 폴드로 한 칸씩 돌고, 자리를 비운 폴드는 배우는 쪽으로 돌아간다.
 * 자리가 옮길 때마다 나머지로 배운 가름점이 움직이고 폴드마다 맞힌 수가 쌓인다.
 */
export const rotateTheFoldFacet: FacetJson = {
  id: 'facet:rotateTheFold',
  title: {
    en: 'Rotate the fold',
    ko: '돌아가는 시험지',
    ja: '回るテストの席',
    zh: '轮流当测试集',
    ar: 'تدوير الطيّة',
    es: 'Rotar el pliegue',
    fr: 'Faire tourner le pli',
    hi: 'फ़ोल्ड को घुमाना',
    id: 'Memutar lipatan',
    pt: 'Girar a dobra',
  },
  description: {
    en: 'Cross-validation: the test seat moves from fold to fold, the rest learn a new split each time, and every item sits on the test seat exactly once.',
    ko: '교차 검증: 시험지 자리가 폴드에서 폴드로 옮겨 가고, 나머지가 그때마다 가름점을 새로 배우며, 모든 항목이 정확히 한 번 시험지에 앉는다.',
    ja: '交差検証：テストの席がフォールドからフォールドへ移り、残りが毎回新しい境界を学び、どの項目もちょうど一度テストの席に座る。',
    zh: '交叉验证：测试位置在各折之间轮换，其余各折每次重新学习分界点，每个样本恰好当一次测试集。',
    ar: 'التحقق المتقاطع: ينتقل مقعد الاختبار من طيّة إلى أخرى، ويتعلّم الباقي حدًّا فاصلًا جديدًا كل مرة، ويجلس كل عنصر على مقعد الاختبار مرة واحدة بالضبط.',
    es: 'Validación cruzada: el asiento de prueba pasa de pliegue en pliegue, el resto aprende un corte nuevo cada vez y cada elemento se sienta en él exactamente una vez.',
    fr: 'Validation croisée : la place de test passe d’un pli à l’autre, les autres apprennent chaque fois un nouveau seuil, et chaque élément occupe la place de test exactement une fois.',
    hi: 'क्रॉस-वैलिडेशन: टेस्ट की सीट एक फ़ोल्ड से दूसरे फ़ोल्ड पर जाती है, बाकी हर बार नई विभाजन रेखा सीखते हैं, और हर आइटम ठीक एक बार टेस्ट की सीट पर बैठता है।',
    id: 'Validasi silang: kursi uji berpindah dari lipatan ke lipatan, sisanya mempelajari batas baru setiap kali, dan setiap item duduk di kursi uji tepat satu kali.',
    pt: 'Validação cruzada: o assento de teste passa de dobra em dobra, o resto aprende um novo corte a cada vez e cada item ocupa o assento de teste exatamente uma vez.',
  },
  algorithm: 'module:rotateTheFold',
  scene: 'module:rotateTheFoldScene',
  initialData: {
    type: 'rotate-the-fold',
    stepMs: 1600,
    items: [
      { id: 'a', x: 1.3, cls: 0, fold: 1 },
      { id: 'b', x: 6.8, cls: 1, fold: 1 },
      { id: 'c', x: 5.7, cls: 0, fold: 2 },
      { id: 'd', x: 7.6, cls: 1, fold: 2 },
      { id: 'e', x: 2.3, cls: 0, fold: 3 },
      { id: 'f', x: 4.6, cls: 1, fold: 3 },
      { id: 'g', x: 3.9, cls: 0, fold: 4 },
      { id: 'h', x: 8.6, cls: 1, fold: 4 },
      { id: 'i', x: 3.1, cls: 0, fold: 5 },
      { id: 'j', x: 6.2, cls: 1, fold: 5 },
    ],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'rotate-the-fold-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'label.seat': {
      en: 'Test seat',
      ko: '시험지',
      ja: 'テストの席',
      zh: '测试位',
      ar: 'مقعد الاختبار',
      es: 'Asiento de prueba',
      fr: 'Place de test',
      hi: 'टेस्ट सीट',
      id: 'Kursi uji',
      pt: 'Assento de teste',
    },
    'label.learn': {
      en: 'Learning',
      ko: '배우는 쪽',
      ja: '学ぶ側',
      zh: '学习方',
      ar: 'التعلّم',
      es: 'Aprenden',
      fr: 'Apprennent',
      hi: 'सीखने वाले',
      id: 'Belajar',
      pt: 'Aprendem',
    },
    'label.correct': {
      en: 'Correct',
      ko: '맞힌 수',
      ja: '正解数',
      zh: '答对数',
      ar: 'الصحيح',
      es: 'Aciertos',
      fr: 'Justes',
      hi: 'सही',
      id: 'Benar',
      pt: 'Acertos',
    },
    'label.fold': {
      en: 'Fold {k}',
      ko: '폴드 {k}',
      ja: 'フォールド {k}',
      zh: '第 {k} 折',
      ar: 'الطيّة {k}',
      es: 'Pliegue {k}',
      fr: 'Pli {k}',
      hi: 'फ़ोल्ड {k}',
      id: 'Lipatan {k}',
      pt: 'Dobra {k}',
    },
    'label.split': {
      en: 'Split: {v}',
      ko: '가름점: {v}',
      ja: '境界: {v}',
      zh: '分界点: {v}',
      ar: 'الحد الفاصل: {v}',
      es: 'Corte: {v}',
      fr: 'Seuil : {v}',
      hi: 'विभाजन: {v}',
      id: 'Batas: {v}',
      pt: 'Corte: {v}',
    },
    'label.class0': {
      en: 'Class 0',
      ko: '부류 0',
      ja: 'クラス 0',
      zh: '类别 0',
      ar: 'الفئة 0',
      es: 'Clase 0',
      fr: 'Classe 0',
      hi: 'वर्ग 0',
      id: 'Kelas 0',
      pt: 'Classe 0',
    },
    'label.class1': {
      en: 'Class 1',
      ko: '부류 1',
      ja: 'クラス 1',
      zh: '类别 1',
      ar: 'الفئة 1',
      es: 'Clase 1',
      fr: 'Classe 1',
      hi: 'वर्ग 1',
      id: 'Kelas 1',
      pt: 'Classe 1',
    },
    'label.trail': {
      en: 'Splits so far',
      ko: '지나온 가름점',
      ja: 'これまでの境界',
      zh: '已有分界点',
      ar: 'الحدود السابقة',
      es: 'Cortes hasta ahora',
      fr: 'Seuils passés',
      hi: 'अब तक के विभाजन',
      id: 'Batas sejauh ini',
      pt: 'Cortes até agora',
    },
    'label.right': {
      en: 'right',
      ko: '맞음',
      ja: '正解',
      zh: '对',
      ar: 'صحيح',
      es: 'acierto',
      fr: 'juste',
      hi: 'सही',
      id: 'benar',
      pt: 'certo',
    },
    'label.wrong': {
      en: 'wrong',
      ko: '틀림',
      ja: '不正解',
      zh: '错',
      ar: 'خطأ',
      es: 'fallo',
      fr: 'faux',
      hi: 'ग़लत',
      id: 'salah',
      pt: 'errado',
    },
    'caption.start': {
      en: 'Items: {n} · number of folds: {k}. The test seat is empty.',
      ko: '항목 수: {n} · 폴드 수: {k}. 시험지 자리는 비어 있다.',
      ja: '項目数: {n} · フォールド数: {k}。テストの席はまだ空いている。',
      zh: '样本数: {n} · 折数: {k}。测试位还空着。',
      ar: 'عدد العناصر: {n} · عدد الطيّات: {k}. مقعد الاختبار فارغ.',
      es: 'Elementos: {n} · número de pliegues: {k}. El asiento de prueba está vacío.',
      fr: 'Éléments : {n} · nombre de plis : {k}. La place de test est vide.',
      hi: 'आइटम: {n} · फ़ोल्ड की संख्या: {k}। टेस्ट सीट खाली है।',
      id: 'Item: {n} · jumlah lipatan: {k}. Kursi uji masih kosong.',
      pt: 'Itens: {n} · número de dobras: {k}. O assento de teste está vazio.',
    },
    'caption.fold': {
      en: 'Test seat: fold {k} · split learned from the rest: {split}',
      ko: '시험지 자리: 폴드 {k} · 나머지로 배운 가름점: {split}',
      ja: 'テストの席: フォールド {k} · 残りから学んだ境界: {split}',
      zh: '测试位: 第 {k} 折 · 由其余各折学到的分界点: {split}',
      ar: 'مقعد الاختبار: الطيّة {k} · الحد الفاصل المتعلَّم من الباقي: {split}',
      es: 'Asiento de prueba: pliegue {k} · corte aprendido del resto: {split}',
      fr: 'Place de test : pli {k} · seuil appris sur le reste : {split}',
      hi: 'टेस्ट सीट: फ़ोल्ड {k} · बाकी से सीखा विभाजन: {split}',
      id: 'Kursi uji: lipatan {k} · batas yang dipelajari dari sisanya: {split}',
      pt: 'Assento de teste: dobra {k} · corte aprendido com o resto: {split}',
    },
    'caption.foldScore': {
      en: 'Correct on the test seat: {c}/{n}',
      ko: '시험지에서 맞힌 수: {c}/{n}',
      ja: 'テストの席での正解数: {c}/{n}',
      zh: '测试位答对数: {c}/{n}',
      ar: 'الصحيح على مقعد الاختبار: {c}/{n}',
      es: 'Aciertos en el asiento de prueba: {c}/{n}',
      fr: 'Justes sur la place de test : {c}/{n}',
      hi: 'टेस्ट सीट पर सही: {c}/{n}',
      id: 'Benar di kursi uji: {c}/{n}',
      pt: 'Acertos no assento de teste: {c}/{n}',
    },
    'caption.sum': {
      en: 'Total correct: {c}/{n} · mean accuracy: {acc}',
      ko: '맞힌 수 합: {c}/{n} · 평균 정확도: {acc}',
      ja: '正解数の合計: {c}/{n} · 平均正解率: {acc}',
      zh: '答对总数: {c}/{n} · 平均准确率: {acc}',
      ar: 'مجموع الصحيح: {c}/{n} · متوسط الدقة: {acc}',
      es: 'Aciertos totales: {c}/{n} · exactitud media: {acc}',
      fr: 'Total juste : {c}/{n} · exactitude moyenne : {acc}',
      hi: 'कुल सही: {c}/{n} · औसत सटीकता: {acc}',
      id: 'Total benar: {c}/{n} · akurasi rata-rata: {acc}',
      pt: 'Acertos totais: {c}/{n} · acurácia média: {acc}',
    },
    'caption.seats': {
      en: 'Times on the test seat per item — fewest: {min} · most: {max}',
      ko: '항목마다 시험지에 앉은 횟수 — 가장 적게: {min} · 가장 많이: {max}',
      ja: '項目ごとのテストの席に座った回数 — 最少: {min} · 最多: {max}',
      zh: '每个样本当测试集的次数 — 最少: {min} · 最多: {max}',
      ar: 'مرات الجلوس على مقعد الاختبار لكل عنصر — الأقل: {min} · الأكثر: {max}',
      es: 'Veces en el asiento de prueba por elemento — mínimo: {min} · máximo: {max}',
      fr: 'Passages sur la place de test par élément — le moins : {min} · le plus : {max}',
      hi: 'हर आइटम टेस्ट सीट पर कितनी बार — सबसे कम: {min} · सबसे ज़्यादा: {max}',
      id: 'Berapa kali tiap item di kursi uji — paling sedikit: {min} · paling banyak: {max}',
      pt: 'Vezes no assento de teste por item — mínimo: {min} · máximo: {max}',
    },
  },
};
