import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 라우터는 들어온 패킷마다 어느 문으로, 누구에게 넘길지를 무엇을 보고 정하는가.
 *
 * 한 문으로 들어온 패킷 넷이 표의 줄(목적지 망 · 넘길 곳 · 문)에 따라 서로 다른 문으로
 * 흩어져 나간다. 같은 망으로 가는 둘은 주소가 달라도 같은 문으로, 표에 망이 없는 하나는
 * 기본 줄의 문으로 나간다. 주소는 문서용 · 사설 대역이고 표와 패킷은 예로 정한 값이다.
 */
export const forwardingTableFacet: FacetJson = {
  id: 'facet:forwardingTable',
  title: {
    en: 'Forwarding table',
    ko: '포워딩 테이블',
    ja: 'フォワーディングテーブル',
    zh: '转发表',
    ar: 'جدول التمرير',
    es: 'Tabla de reenvío',
    fr: 'Table de transfert',
    hi: 'फ़ॉरवर्डिंग टेबल',
    id: 'Tabel penerusan',
    pt: 'Tabela de encaminhamento',
  },
  description: {
    en: 'Packets that enter by one interface leave by different ones. The router looks up each destination network in its table and hands the packet to the next hop written there.',
    ko: '한 문으로 들어온 패킷들이 서로 다른 문으로 나간다. 라우터는 목적지의 망을 표에서 찾아 거기 적힌 넘길 곳에 패킷을 건넨다.',
    ja: '一つのインターフェースから入ったパケットが別々のインターフェースから出ていく。ルーターは宛先のネットワークを表で探し、そこに書かれた次の転送先へパケットを渡す。',
    zh: '从一个接口进入的数据包从不同的接口离开。路由器在表中查找目的网络，把数据包交给那里写的下一跳。',
    ar: 'الحزم التي تدخل من واجهة واحدة تخرج من واجهات مختلفة. يبحث الموجّه عن شبكة الوجهة في جدوله ويسلّم الحزمة إلى القفزة التالية المكتوبة هناك.',
    es: 'Los paquetes que entran por una interfaz salen por otras distintas. El router busca la red de destino en su tabla y entrega el paquete al siguiente salto que figura allí.',
    fr: 'Les paquets entrés par une interface sortent par des interfaces différentes. Le routeur cherche le réseau de destination dans sa table et remet le paquet au prochain saut qui y est inscrit.',
    hi: 'एक इंटरफ़ेस से आए पैकेट अलग-अलग इंटरफ़ेस से निकलते हैं। राउटर गंतव्य नेटवर्क को अपनी टेबल में ढूँढता है और पैकेट वहाँ लिखे अगले हॉप को सौंप देता है।',
    id: 'Paket yang masuk lewat satu antarmuka keluar lewat antarmuka yang berbeda. Router mencari jaringan tujuan di tabelnya dan menyerahkan paket ke lompatan berikutnya yang tertulis di sana.',
    pt: 'Pacotes que entram por uma interface saem por interfaces diferentes. O roteador procura a rede de destino na tabela e entrega o pacote ao próximo salto escrito ali.',
  },
  algorithm: 'module:forwardingTable',
  scene: 'module:forwardingTableScene',
  initialData: {
    type: 'forwarding-table',
    stepMs: 1600,
    sender: '192.168.10.5',
    inDoor: 'eth0',
    table: [
      { net: '192.168.10.0/24', hop: null, door: 'eth0' },
      { net: '192.168.20.0/24', hop: null, door: 'eth1' },
      { net: '172.16.0.0/16', hop: '10.0.0.2', door: 'eth2' },
      { net: '0.0.0.0/0', hop: '10.0.1.1', door: 'eth3' },
    ],
    packets: ['192.168.20.14', '172.16.4.9', '198.51.100.23', '192.168.20.99'],
  },
  shuffleOnReset: false,
  messages: {
    'label.sender': {
      en: 'From {addr}',
      ko: '보낸 곳 {addr}',
      ja: '送信元 {addr}',
      zh: '发送方 {addr}',
      ar: 'من {addr}',
      es: 'Desde {addr}',
      fr: 'Depuis {addr}',
      hi: 'भेजने वाला {addr}',
      id: 'Dari {addr}',
      pt: 'De {addr}',
    },
    'role.router': {
      en: 'Router',
      ko: '라우터',
      ja: 'ルーター',
      zh: '路由器',
      ar: 'موجّه',
      es: 'Router',
      fr: 'Routeur',
      hi: 'राउटर',
      id: 'Router',
      pt: 'Roteador',
    },
    'head.net': {
      en: 'Destination network',
      ko: '목적지 망',
      ja: '宛先ネットワーク',
      zh: '目的网络',
      ar: 'شبكة الوجهة',
      es: 'Red de destino',
      fr: 'Réseau de destination',
      hi: 'गंतव्य नेटवर्क',
      id: 'Jaringan tujuan',
      pt: 'Rede de destino',
    },
    'head.hop': {
      en: 'Next hop',
      ko: '넘길 곳',
      ja: '次の転送先',
      zh: '下一跳',
      ar: 'القفزة التالية',
      es: 'Siguiente salto',
      fr: 'Prochain saut',
      hi: 'अगला हॉप',
      id: 'Lompatan berikutnya',
      pt: 'Próximo salto',
    },
    'head.door': {
      en: 'Interface',
      ko: '문',
      ja: 'インターフェース',
      zh: '接口',
      ar: 'الواجهة',
      es: 'Interfaz',
      fr: 'Interface',
      hi: 'इंटरफ़ेस',
      id: 'Antarmuka',
      pt: 'Interface',
    },
    'label.direct': {
      en: 'direct',
      ko: '직접',
      ja: '直接',
      zh: '直连',
      ar: 'مباشر',
      es: 'directo',
      fr: 'direct',
      hi: 'सीधे',
      id: 'langsung',
      pt: 'direto',
    },
    'caption.start': {
      en: 'Packets waiting at {door}: {n}.',
      ko: '{door} 앞에서 기다리는 패킷: {n}.',
      ja: '{door} の前で待つパケット: {n}。',
      zh: '在 {door} 前等待的数据包：{n}。',
      ar: 'الحزم المنتظرة عند {door}: {n}.',
      es: 'Paquetes esperando en {door}: {n}.',
      fr: 'Paquets en attente à {door} : {n}.',
      hi: '{door} पर प्रतीक्षा कर रहे पैकेट: {n}।',
      id: 'Paket yang menunggu di {door}: {n}.',
      pt: 'Pacotes esperando em {door}: {n}.',
    },
    'caption.fit': {
      en: 'Destination {dst} fits row {net}.',
      ko: '목적지 {dst} — 맞는 줄: {net}.',
      ja: '宛先 {dst} — 合う行: {net}。',
      zh: '目的地址 {dst} — 匹配的行：{net}。',
      ar: 'الوجهة {dst} — السطر المطابق: {net}.',
      es: 'Destino {dst}: encaja en la fila {net}.',
      fr: 'Destination {dst} : elle correspond à la ligne {net}.',
      hi: 'गंतव्य {dst} — मेल खाने वाली पंक्ति: {net}।',
      id: 'Tujuan {dst} cocok dengan baris {net}.',
      pt: 'Destino {dst}: cabe na linha {net}.',
    },
    'caption.noFit': {
      en: 'No row fits {dst}; the default row {net} takes it.',
      ko: '목적지 {dst} — 맞는 줄이 없어 기본 줄이 맡는다: {net}.',
      ja: '宛先 {dst} — 合う行がないのでデフォルト行が受け持つ: {net}。',
      zh: '目的地址 {dst} — 没有匹配的行，由默认行接手：{net}。',
      ar: 'لا سطر يطابق {dst}، فيتولاها السطر الافتراضي {net}.',
      es: 'Ninguna fila encaja con {dst}; la fila por defecto {net} se encarga.',
      fr: 'Aucune ligne pour {dst} ; la ligne par défaut {net} le prend.',
      hi: '{dst} से कोई पंक्ति मेल नहीं खाती; डिफ़ॉल्ट पंक्ति {net} इसे लेती है।',
      id: 'Tidak ada baris yang cocok dengan {dst}; baris bawaan {net} mengambilnya.',
      pt: 'Nenhuma linha cabe para {dst}; a linha padrão {net} fica com ele.',
    },
    'caption.outDirect': {
      en: 'Out through {door}, straight to {hop} itself.',
      ko: '나가는 문: {door}. 넘길 곳: 목적지 자신 {hop}.',
      ja: '出るインターフェース: {door}。渡す先: 宛先そのもの {hop}。',
      zh: '出接口：{door}。交给：目的地址本身 {hop}。',
      ar: 'يخرج عبر {door}، مباشرة إلى {hop} نفسه.',
      es: 'Sale por {door}, directo al propio {hop}.',
      fr: 'Sortie par {door}, directement vers {hop} lui-même.',
      hi: '{door} से बाहर, सीधे {hop} को ही।',
      id: 'Keluar lewat {door}, langsung ke {hop} itu sendiri.',
      pt: 'Sai por {door}, direto para o próprio {hop}.',
    },
    'caption.outRouter': {
      en: 'Out through {door}, handed to router {hop}.',
      ko: '나가는 문: {door}. 넘길 곳: 라우터 {hop}.',
      ja: '出るインターフェース: {door}。渡す先: ルーター {hop}。',
      zh: '出接口：{door}。交给：路由器 {hop}。',
      ar: 'يخرج عبر {door}، ويُسلَّم إلى الموجّه {hop}.',
      es: 'Sale por {door} y se entrega al router {hop}.',
      fr: 'Sortie par {door}, remis au routeur {hop}.',
      hi: '{door} से बाहर, राउटर {hop} को सौंपा गया।',
      id: 'Keluar lewat {door}, diserahkan ke router {hop}.',
      pt: 'Sai por {door} e é entregue ao roteador {hop}.',
    },
  },
  blocks: {
    stage: { type: 'forwarding-table-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
