/**
 * @piece
 * 질문: 페이징은 프로세스 하나를 메모리에 어떻게 나눠 싣는가.
 *
 * 값은 모두 예로 정한 것이다 (칸 여덟 · 칸 하나 4 KiB · 찬 칸 넷 · 프로세스 14 KiB).
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { FixedSizeFramesFacetData } from './algorithm.js';

const initialData: FixedSizeFramesFacetData = {
  type: 'fixed-size-frames',
  stepMs: 1600,
  frameCount: 8,
  pageKib: 4,
  occupied: [
    { frame: 0, owner: 'q' },
    { frame: 2, owner: 'q' },
    { frame: 4, owner: 'r' },
    { frame: 6, owner: 'r' },
  ],
  process: { id: 'p', sizeKib: 14 },
};

export const fixedSizeFramesFacet: FacetJson = {
  id: 'facet:fixedSizeFrames',
  title: {
    en: 'Cut into equal frames',
    ko: '같은 크기로 잘라 칸에 싣기',
    ja: '同じ大きさに切ってフレームに載せる',
    zh: '切成等长的页装入帧',
    ar: 'التقطيع إلى إطارات متساوية',
    es: 'Cortar en marcos iguales',
    fr: 'Découper en cadres égaux',
    hi: 'बराबर फ़्रेम में काटना',
    id: 'Dipotong menjadi frame sama besar',
    pt: 'Cortar em quadros iguais',
  },
  description: {
    en: 'Paging cuts a process into equal pages and drops each one into a free frame, even when the free frames are far apart.',
    ko: '페이징은 프로세스를 같은 길이의 페이지로 잘라, 서로 떨어진 빈 프레임에도 하나씩 넣는다.',
    ja: 'ページングはプロセスを同じ長さのページに切り、離れた空きフレームにも一つずつ入れる。',
    zh: '分页把进程切成等长的页，即使空闲帧彼此分散，也逐一放入。',
    ar: 'يقطّع الترحيل العملية إلى صفحات متساوية ويضع كل صفحة في إطار فارغ، حتى لو كانت الإطارات الفارغة متباعدة.',
    es: 'La paginación corta un proceso en páginas iguales y coloca cada una en un marco libre, aunque los marcos libres estén separados.',
    fr: 'La pagination découpe un processus en pages égales et place chacune dans un cadre libre, même si les cadres libres sont éloignés.',
    hi: 'पेजिंग प्रोसेस को बराबर पेजों में काटती है और हर पेज को किसी खाली फ़्रेम में रखती है, भले ही खाली फ़्रेम दूर-दूर हों।',
    id: 'Paging memotong proses menjadi halaman sama panjang dan memasukkan masing-masing ke frame kosong, meski frame kosong saling berjauhan.',
    pt: 'A paginação corta um processo em páginas iguais e coloca cada uma num quadro livre, mesmo que os quadros livres estejam separados.',
  },
  algorithm: 'module:fixedSizeFrames',
  scene: 'module:fixedSizeFramesScene',
  initialData: { ...initialData },
  shuffleOnReset: false,
  messages: {
    'label.process': {
      en: 'Process {id}',
      ko: '프로세스 {id}',
      ja: 'プロセス {id}',
      zh: '进程 {id}',
      ar: 'العملية {id}',
      es: 'Proceso {id}',
      fr: 'Processus {id}',
      hi: 'प्रोसेस {id}',
      id: 'Proses {id}',
      pt: 'Processo {id}',
    },
    'label.size': {
      en: '{n} KiB',
      ko: '{n} KiB',
      ja: '{n} KiB',
      zh: '{n} KiB',
      ar: '{n} KiB',
      es: '{n} KiB',
      fr: '{n} Kio',
      hi: '{n} KiB',
      id: '{n} KiB',
      pt: '{n} KiB',
    },
    'label.memory': {
      en: 'Memory',
      ko: '메모리',
      ja: 'メモリ',
      zh: '内存',
      ar: 'الذاكرة',
      es: 'Memoria',
      fr: 'Mémoire',
      hi: 'मेमोरी',
      id: 'Memori',
      pt: 'Memória',
    },
    'label.frames': {
      en: 'Frame',
      ko: '프레임',
      ja: 'フレーム',
      zh: '帧',
      ar: 'الإطار',
      es: 'Marco',
      fr: 'Cadre',
      hi: 'फ़्रेम',
      id: 'Frame',
      pt: 'Quadro',
    },
    'caption.start': {
      en: 'Process {id}: {size} KiB. Free frames: {free}.',
      ko: '프로세스 {id}: {size} KiB. 빈 프레임 수: {free}.',
      ja: 'プロセス {id}: {size} KiB。空きフレーム数: {free}。',
      zh: '进程 {id}：{size} KiB。空闲帧数：{free}。',
      ar: 'العملية {id}: {size} KiB. الإطارات الفارغة: {free}.',
      es: 'Proceso {id}: {size} KiB. Marcos libres: {free}.',
      fr: 'Processus {id} : {size} Kio. Cadres libres : {free}.',
      hi: 'प्रोसेस {id}: {size} KiB. खाली फ़्रेम: {free}.',
      id: 'Proses {id}: {size} KiB. Frame kosong: {free}.',
      pt: 'Processo {id}: {size} KiB. Quadros livres: {free}.',
    },
    'caption.cut': {
      en: 'Cut every {page} KiB. Pages: {n}.',
      ko: '{page} KiB 씩 자른다. 페이지 수: {n}.',
      ja: '{page} KiB ごとに切る。ページ数: {n}。',
      zh: '每 {page} KiB 切一段。页数：{n}。',
      ar: 'التقطيع كل {page} KiB. الصفحات: {n}.',
      es: 'Corte cada {page} KiB. Páginas: {n}.',
      fr: 'Découpe tous les {page} Kio. Pages : {n}.',
      hi: 'हर {page} KiB पर कटाई. पेज: {n}.',
      id: 'Dipotong tiap {page} KiB. Halaman: {n}.',
      pt: 'Corte a cada {page} KiB. Páginas: {n}.',
    },
    'caption.place': {
      en: 'Page {page} → free frame {frame}.',
      ko: '페이지 {page} → 빈 프레임 {frame}.',
      ja: 'ページ {page} → 空きフレーム {frame}。',
      zh: '页 {page} → 空闲帧 {frame}。',
      ar: 'الصفحة {page} → الإطار الفارغ {frame}.',
      es: 'Página {page} → marco libre {frame}.',
      fr: 'Page {page} → cadre libre {frame}.',
      hi: 'पेज {page} → खाली फ़्रेम {frame}.',
      id: 'Halaman {page} → frame kosong {frame}.',
      pt: 'Página {page} → quadro livre {frame}.',
    },
    'caption.placeShort': {
      en: 'Page {page} → frame {frame}. Used {used} KiB, unused {slack} KiB.',
      ko: '페이지 {page} → 프레임 {frame}. 쓴 몫 {used} KiB · 빈 몫 {slack} KiB.',
      ja: 'ページ {page} → フレーム {frame}。使用 {used} KiB・未使用 {slack} KiB。',
      zh: '页 {page} → 帧 {frame}。已用 {used} KiB，空余 {slack} KiB。',
      ar: 'الصفحة {page} → الإطار {frame}. المستخدم {used} KiB، غير المستخدم {slack} KiB.',
      es: 'Página {page} → marco {frame}. Usado {used} KiB, sin usar {slack} KiB.',
      fr: 'Page {page} → cadre {frame}. Utilisé {used} Kio, inutilisé {slack} Kio.',
      hi: 'पेज {page} → फ़्रेम {frame}. उपयोग {used} KiB, खाली {slack} KiB.',
      id: 'Halaman {page} → frame {frame}. Terpakai {used} KiB, tak terpakai {slack} KiB.',
      pt: 'Página {page} → quadro {frame}. Usado {used} KiB, sem uso {slack} KiB.',
    },
  },
  blocks: {
    stage: { type: 'fixed-size-frames-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
