/**
 * all-suffixes-sorted — 한 문자열의 모든 꼬리를 줄 세워 두는 조각.
 *
 * @piece 질문 하나에 답하고 멈춘다 — 모든 꼬리를 줄 세워 두면 무엇이 쉬워지는가.
 *        답은 앞머리가 같은 꼬리끼리 반드시 이웃하게 된다는 것이다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const allSuffixesSortedFacet: FacetJson = {
  id: 'facet:allSuffixesSorted',
  title: {
    en: 'All suffixes, sorted',
    ko: '모든 꼬리를 줄 세우기',
    ja: 'すべての接尾辞を並べる',
    zh: '把所有后缀排好序',
    ar: 'كل اللواحق مرتَّبة',
    es: 'Todos los sufijos, ordenados',
    fr: 'Tous les suffixes, triés',
    hi: 'सभी प्रत्यय, क्रम में',
    id: 'Semua sufiks, terurut',
    pt: 'Todos os sufixos, ordenados',
  },
  description: {
    en: 'Line up every tail of a string in order and the ones that start alike end up side by side.',
    ko: '한 문자열의 모든 꼬리를 줄 세우면, 앞머리가 같은 것끼리 나란히 모인다.',
    ja: '文字列のすべての接尾辞を並べ替えると、先頭が同じものが隣り合う。',
    zh: '把一个字符串的所有后缀排好序，开头相同的就会挨在一起。',
    ar: 'رتِّب كل لواحق النص فتتجاور اللواحق التي تبدأ بالحرف نفسه.',
    es: 'Si ordenas todos los sufijos de una cadena, los que empiezan igual quedan juntos.',
    fr: 'Triez tous les suffixes d’une chaîne et ceux qui commencent pareil se retrouvent côte à côte.',
    hi: 'किसी स्ट्रिंग के सभी प्रत्ययों को क्रम में लगाएँ तो एक जैसे शुरू होने वाले पास-पास आ जाते हैं।',
    id: 'Urutkan semua sufiks sebuah string, maka yang berawalan sama akan berdampingan.',
    pt: 'Ordene todos os sufixos de um texto e os que começam igual ficam lado a lado.',
  },
  algorithm: 'module:allSuffixesSorted',
  projector: 'module:allSuffixesSortedProjector',
  initialData: {
    type: 'all-suffixes-sorted',
    text: 'banana',
    stepMs: 820,
  },
  blocks: {
    stage: { type: 'all-suffixes-sorted-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'label.byPosition': {
      en: 'By position',
      ko: '자리 순',
      ja: '位置の順',
      zh: '按位置',
      ar: 'حسب الموضع',
      es: 'Por posición',
      fr: 'Par position',
      hi: 'स्थान के क्रम में',
      id: 'Urut posisi',
      pt: 'Por posição',
    },
    'label.inOrder': {
      en: 'In order',
      ko: '사전 순',
      ja: '辞書の順',
      zh: '按字典序',
      ar: 'حسب الترتيب المعجمي',
      es: 'En orden',
      fr: 'Dans l’ordre',
      hi: 'शब्दकोश क्रम में',
      id: 'Urut kamus',
      pt: 'Em ordem',
    },
    'caption.cutTails': {
      en: 'Cut at every position — each cut leaves a tail.',
      ko: '자리마다 자른다 — 자른 자리에서 끝까지가 꼬리다.',
      ja: '各位置で切る — 切った所から末尾までが接尾辞だ。',
      zh: '在每个位置切一刀 —— 切口到末尾就是一个后缀。',
      ar: 'اقطع عند كل موضع — ما يبقى حتى النهاية هو لاحقة.',
      es: 'Corta en cada posición: lo que queda hasta el final es un sufijo.',
      fr: 'Coupez à chaque position : ce qui reste jusqu’à la fin est un suffixe.',
      hi: 'हर स्थान पर काटें — कटान से अंत तक जो बचे वही प्रत्यय है।',
      id: 'Potong di tiap posisi — sisa sampai ujung itulah sufiks.',
      pt: 'Corte em cada posição: o que sobra até o fim é um sufixo.',
    },
    'caption.alignLeft': {
      en: 'Line up the left edges — now the tails can be compared.',
      ko: '왼쪽 끝을 맞춘다 — 이제 꼬리끼리 견줄 수 있다.',
      ja: '左端をそろえる — これで接尾辞どうしを比べられる。',
      zh: '把左端对齐 —— 现在可以互相比较了。',
      ar: 'حاذِ الحواف اليسرى — الآن يمكن مقارنة اللواحق.',
      es: 'Alinea los bordes izquierdos: ya se pueden comparar.',
      fr: 'Alignez les bords gauches : les suffixes deviennent comparables.',
      hi: 'बाएँ सिरे एक कर दें — अब प्रत्ययों की तुलना हो सकती है।',
      id: 'Ratakan tepi kiri — kini sufiks bisa dibandingkan.',
      pt: 'Alinhe as bordas esquerdas: agora dá para comparar.',
    },
    'caption.takePlace': {
      en: 'Next in line: {tail}',
      ko: '줄에 선다: {tail}',
      ja: '次に並ぶ: {tail}',
      zh: '下一个入列：{tail}',
      ar: 'التالي في الصف: {tail}',
      es: 'El siguiente en la fila: {tail}',
      fr: 'Suivant dans la file : {tail}',
      hi: 'पंक्ति में अगला: {tail}',
      id: 'Berikutnya dalam barisan: {tail}',
      pt: 'Próximo na fila: {tail}',
    },
    'caption.cluster': {
      en: 'Tails that start alike now sit together — one stretch to search.',
      ko: '앞머리가 같은 꼬리끼리 한 구간에 모였다. 찾을 때는 이 구간만 본다.',
      ja: '先頭が同じ接尾辞が一つの区間に集まった。探すときはここだけ見ればよい。',
      zh: '开头相同的后缀聚成一段 —— 查找时只看这一段。',
      ar: 'اللواحق ذات البداية نفسها صارت في نطاق واحد — يكفي البحث فيه.',
      es: 'Los sufijos que empiezan igual quedan juntos: basta con buscar en ese tramo.',
      fr: 'Les suffixes qui commencent pareil forment un bloc : il suffit d’y chercher.',
      hi: 'एक जैसे शुरू होने वाले प्रत्यय एक ही खंड में आ गए — खोजने के लिए बस यही खंड देखें।',
      id: 'Sufiks yang berawalan sama kini menyatu — cukup cari di rentang itu.',
      pt: 'Os sufixos que começam igual ficam juntos: basta procurar nesse trecho.',
    },
  },
};
