import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 평균 줄 길이와 들어오는 빠르기와 한 요청이 머무는 시간은 서로 어떤 관계인가?
 *
 * 요청마다 도착에서 떠남까지 머문 시간이 드러나 머묾의 합에 보태지고, 같은 합을 요청 수로
 * 나누면 W, 관측 시간으로 나누면 L 이 되어 L 과 λ × W 가 맞아떨어진다.
 */
export const lengthIsRateTimesWaitFacet: FacetJson = {
  id: 'facet:lengthIsRateTimesWait',
  title: {
    en: "Little's law: length is rate times wait",
    ko: '리틀의 법칙 — 줄 길이는 빠르기와 머묾의 곱',
    ja: 'リトルの法則 — 行列の長さは到着率と滞在時間の積',
    zh: '利特尔法则——队列长度等于到达率乘以停留时间',
    ar: 'قانون ليتل: طول الطابور هو المعدل مضروبًا في زمن البقاء',
    es: 'Ley de Little: la longitud es la tasa por la espera',
    fr: 'Loi de Little : la longueur vaut le débit fois l’attente',
    hi: 'लिटल का नियम: कतार की लंबाई = दर × ठहराव',
    id: 'Hukum Little: panjang antrean adalah laju kali lama tinggal',
    pt: 'Lei de Little: o comprimento é a taxa vezes a espera',
  },
  description: {
    en: 'Each request’s stay is added to one sum. Divided by the number of requests it gives W, divided by the observed time it gives L — and L comes out equal to λ × W.',
    ko: '요청마다 머문 시간이 하나의 합에 보태진다. 그 합을 요청 수로 나누면 W, 관측 시간으로 나누면 L 이고, L 은 λ × W 와 같은 수로 나온다.',
    ja: '各リクエストの滞在時間が一つの合計に足される。リクエスト数で割れば W、観測時間で割れば L になり、L は λ × W と同じ数になる。',
    zh: '每个请求的停留时间都加到同一个总和里。除以请求数得到 W，除以观测时间得到 L——L 与 λ × W 相等。',
    ar: 'يُضاف زمن بقاء كل طلب إلى مجموع واحد. بقسمته على عدد الطلبات نحصل على W، وبقسمته على زمن المراقبة نحصل على L، فيخرج L مساويًا لـ λ × W.',
    es: 'La estancia de cada solicitud se suma a un mismo total. Dividido entre el número de solicitudes da W; entre el tiempo observado da L, y L resulta igual a λ × W.',
    fr: 'Le séjour de chaque requête s’ajoute à une même somme. Divisée par le nombre de requêtes, elle donne W ; par la durée observée, elle donne L — et L vaut λ × W.',
    hi: 'हर अनुरोध का ठहराव एक ही जोड़ में जुड़ता है। अनुरोधों की संख्या से भाग देने पर W, देखे गए समय से भाग देने पर L मिलता है — और L, λ × W के बराबर निकलता है।',
    id: 'Lama tinggal tiap permintaan ditambahkan ke satu jumlah. Dibagi banyaknya permintaan menjadi W, dibagi waktu pengamatan menjadi L — dan L sama dengan λ × W.',
    pt: 'A permanência de cada pedido soma-se a um só total. Dividido pelo número de pedidos dá W; pelo tempo observado dá L — e L sai igual a λ × W.',
  },
  algorithm: 'module:lengthIsRateTimesWait',
  scene: 'module:lengthIsRateTimesWaitScene',
  initialData: {
    type: 'length-is-rate-times-wait',
    window: 16,
    requests: [
      { id: 'q1', arrive: 0, service: 2 },
      { id: 'q2', arrive: 1, service: 3 },
      { id: 'q3', arrive: 1, service: 1 },
      { id: 'q4', arrive: 4, service: 1 },
      { id: 'q5', arrive: 8, service: 1 },
      { id: 'q6', arrive: 9, service: 2 },
      { id: 'q7', arrive: 9, service: 2 },
      { id: 'q8', arrive: 11, service: 1 },
    ],
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.ready': {
      en: 'Requests: {n}. Observed from 0 s to {end} s. Stays are not known yet.',
      ko: '요청 수: {n}. 관측 구간: 0초부터 {end}초까지. 머문 시간은 아직 모른다.',
      ja: 'リクエスト数: {n}。観測: 0 秒から {end} 秒まで。滞在時間はまだ分からない。',
      zh: '请求数：{n}。观测：0 秒到 {end} 秒。停留时间尚不知道。',
      ar: 'عدد الطلبات: {n}. المراقبة من 0 ث إلى {end} ث. أزمنة البقاء غير معروفة بعد.',
      es: 'Solicitudes: {n}. Observado de 0 s a {end} s. Aún no se conocen las estancias.',
      fr: 'Requêtes : {n}. Observé de 0 s à {end} s. Les séjours ne sont pas encore connus.',
      hi: 'अनुरोध: {n}. 0 s से {end} s तक देखा गया। ठहराव अभी पता नहीं।',
      id: 'Permintaan: {n}. Diamati dari 0 s sampai {end} s. Lama tinggal belum diketahui.',
      pt: 'Pedidos: {n}. Observado de 0 s a {end} s. As permanências ainda não são conhecidas.',
    },
    'caption.stay': {
      en: '{id}: arrives at {a} s, starts at {start} s, leaves at {leave} s. Stay: {stay} s.',
      ko: '{id} — 도착 {a}초 · 처리 시작 {start}초 · 떠남 {leave}초. 머묾: {stay}초.',
      ja: '{id} — 到着 {a} 秒 · 処理開始 {start} 秒 · 退出 {leave} 秒。滞在: {stay} 秒。',
      zh: '{id}——到达 {a} 秒 · 开始处理 {start} 秒 · 离开 {leave} 秒。停留：{stay} 秒。',
      ar: '{id}: يصل عند {a} ث، يبدأ عند {start} ث، يغادر عند {leave} ث. البقاء: {stay} ث.',
      es: '{id}: llega en {a} s, empieza en {start} s, sale en {leave} s. Estancia: {stay} s.',
      fr: '{id} : arrive à {a} s, commence à {start} s, part à {leave} s. Séjour : {stay} s.',
      hi: '{id}: आगमन {a} s, शुरू {start} s, प्रस्थान {leave} s. ठहराव: {stay} s.',
      id: '{id}: tiba {a} s, mulai {start} s, pergi {leave} s. Lama tinggal: {stay} s.',
      pt: '{id}: chega em {a} s, começa em {start} s, sai em {leave} s. Permanência: {stay} s.',
    },
    'caption.balance': {
      en: 'λ = {count}/{window} = {rate}/s · W = {sum}/{count} = {w} s · L = {area}/{window} = {l}',
      ko: 'λ = {count}/{window} = {rate}건/초 · W = {sum}/{count} = {w}초 · L = {area}/{window} = {l}',
      ja: 'λ = {count}/{window} = {rate} 件/秒 · W = {sum}/{count} = {w} 秒 · L = {area}/{window} = {l}',
      zh: 'λ = {count}/{window} = {rate} 个/秒 · W = {sum}/{count} = {w} 秒 · L = {area}/{window} = {l}',
      ar: 'λ = {count}/{window} = {rate}/ث · W = {sum}/{count} = {w} ث · L = {area}/{window} = {l}',
      es: 'λ = {count}/{window} = {rate}/s · W = {sum}/{count} = {w} s · L = {area}/{window} = {l}',
      fr: 'λ = {count}/{window} = {rate}/s · W = {sum}/{count} = {w} s · L = {area}/{window} = {l}',
      hi: 'λ = {count}/{window} = {rate}/s · W = {sum}/{count} = {w} s · L = {area}/{window} = {l}',
      id: 'λ = {count}/{window} = {rate}/s · W = {sum}/{count} = {w} s · L = {area}/{window} = {l}',
      pt: 'λ = {count}/{window} = {rate}/s · W = {sum}/{count} = {w} s · L = {area}/{window} = {l}',
    },
    'caption.product': {
      en: 'λ × W = {rate} × {w} = {product}',
      ko: 'λ × W = {rate} × {w} = {product}',
      ja: 'λ × W = {rate} × {w} = {product}',
      zh: 'λ × W = {rate} × {w} = {product}',
      ar: 'λ × W = {rate} × {w} = {product}',
      es: 'λ × W = {rate} × {w} = {product}',
      fr: 'λ × W = {rate} × {w} = {product}',
      hi: 'λ × W = {rate} × {w} = {product}',
      id: 'λ × W = {rate} × {w} = {product}',
      pt: 'λ × W = {rate} × {w} = {product}',
    },
    'label.seconds': {
      en: 's',
      ko: '초',
      ja: '秒',
      zh: '秒',
      ar: 'ث',
      es: 's',
      fr: 's',
      hi: 's',
      id: 's',
      pt: 's',
    },
    'label.perRequest': {
      en: 'Stay of each request',
      ko: '요청마다 머문 시간',
      ja: 'リクエストごとの滞在時間',
      zh: '每个请求的停留时间',
      ar: 'بقاء كل طلب',
      es: 'Estancia de cada solicitud',
      fr: 'Séjour de chaque requête',
      hi: 'हर अनुरोध का ठहराव',
      id: 'Lama tinggal tiap permintaan',
      pt: 'Permanência de cada pedido',
    },
    'label.sum': {
      en: 'Sum: {sum}',
      ko: '합: {sum}',
      ja: '合計: {sum}',
      zh: '总和：{sum}',
      ar: 'المجموع: {sum}',
      es: 'Suma: {sum}',
      fr: 'Somme : {sum}',
      hi: 'जोड़: {sum}',
      id: 'Jumlah: {sum}',
      pt: 'Soma: {sum}',
    },
    'label.perSecond': {
      en: 'Requests in the system at each second',
      ko: '시각마다 시스템 안의 요청 수',
      ja: '各時刻にシステム内にいるリクエスト数',
      zh: '每一秒系统内的请求数',
      ar: 'الطلبات داخل النظام في كل ثانية',
      es: 'Solicitudes en el sistema en cada segundo',
      fr: 'Requêtes dans le système à chaque seconde',
      hi: 'हर सेकंड सिस्टम में अनुरोध',
      id: 'Permintaan di dalam sistem tiap detik',
      pt: 'Pedidos no sistema a cada segundo',
    },
    'label.area': {
      en: 'Sum: {area}',
      ko: '합: {area}',
      ja: '合計: {area}',
      zh: '总和：{area}',
      ar: 'المجموع: {area}',
      es: 'Suma: {area}',
      fr: 'Somme : {area}',
      hi: 'जोड़: {area}',
      id: 'Jumlah: {area}',
      pt: 'Soma: {area}',
    },
    'label.w': {
      en: 'W = {w}',
      ko: 'W = {w}',
      ja: 'W = {w}',
      zh: 'W = {w}',
      ar: 'W = {w}',
      es: 'W = {w}',
      fr: 'W = {w}',
      hi: 'W = {w}',
      id: 'W = {w}',
      pt: 'W = {w}',
    },
    'label.l': {
      en: 'L = {l}',
      ko: 'L = {l}',
      ja: 'L = {l}',
      zh: 'L = {l}',
      ar: 'L = {l}',
      es: 'L = {l}',
      fr: 'L = {l}',
      hi: 'L = {l}',
      id: 'L = {l}',
      pt: 'L = {l}',
    },
  },
  blocks: {
    stage: { type: 'length-is-rate-times-wait-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
