/**
 * @piece 앞의 태스크가 도는 도중에 새 태스크가 오면, 둘이 번갈아 도는가?
 *
 * 아니다 — 줄 맨 앞 태스크가 꺼내지면 제 단위를 하나씩 끝까지 다 돌고, 그 뒤에야
 * 다음 태스크가 꺼내진다. 도는 도중 새로 온 태스크는 도는 것 사이로 끼어들지 않고
 * 줄 맨 뒤에 선다. 시각(ms)은 이 조각의 주장이 아니다 — 차례만 본다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const oneTurnAtATimeFacet: FacetJson = {
  id: 'facet:oneTurnAtATime',
  title: {
    en: 'One turn at a time',
    ko: '한 번에 한 차례',
    ja: '一度に一巡',
    zh: '一次一轮',
    ar: 'دور واحد في كل مرة',
    es: 'Un turno a la vez',
    fr: 'Un tour à la fois',
    hi: 'एक बार में एक बारी',
    id: 'Satu giliran dalam satu waktu',
    pt: 'Uma vez por turno',
  },
  description: {
    en: 'A running task finishes completely before the next one starts; a task that arrives meanwhile waits at the back of the queue.',
    ko: '도는 태스크는 다음이 시작되기 전에 끝까지 돈다. 그사이 온 태스크는 줄 뒤에서 기다린다.',
    ja: '実行中のタスクは次が始まる前に最後まで動く。その間に来たタスクは列の最後で待つ。',
    zh: '正在运行的任务会先完全跑完,下一个才开始;这期间到达的任务在队列末尾等待。',
    ar: 'تُنجز المهمة الجارية بالكامل قبل أن تبدأ التالية؛ والمهمة التي تصل في الأثناء تنتظر في آخر الطابور.',
    es: 'Una tarea en ejecución termina por completo antes de que empiece la siguiente; una tarea que llega mientras tanto espera al final de la cola.',
    fr: "Une tâche en cours se termine entièrement avant que la suivante ne commence ; une tâche qui arrive entre-temps attend au bout de la file.",
    hi: 'चल रहा टास्क अगला शुरू होने से पहले पूरी तरह खत्म होता है; बीच में आया टास्क कतार के अंत में इंतज़ार करता है।',
    id: 'Tugas yang sedang berjalan selesai sepenuhnya sebelum yang berikutnya dimulai; tugas yang tiba di tengah jalan menunggu di belakang antrean.',
    pt: 'Uma tarefa em execução termina completamente antes que a próxima comece; uma tarefa que chega nesse meio-tempo espera no fim da fila.',
  },
  algorithm: 'module:oneTurnAtATime',
  scene: 'module:oneTurnAtATimeScene',
  initialData: {
    type: 'oneTurnAtATime',
    stepMs: 1300,
    queue: ['clickA', 'timer'],
    tasks: [
      { id: 'clickA', units: 3 },
      { id: 'timer', units: 2 },
      { id: 'clickB', units: 2 },
    ],
    arrivals: [{ id: 'clickB', duringTask: 'clickA', duringUnit: 2 }],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'one-turn-at-a-time-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.initial': {
      en: 'The queue is set. Nothing runs yet.',
      ko: '줄이 섰다. 아직 도는 것이 없다.',
      ja: 'キューが並んだ。まだ動いているものはない。',
      zh: '队列已就绪。还没有正在运行的任务。',
      ar: 'الطابور جاهز. لا شيء يعمل بعد.',
      es: 'La cola está lista. Nada se ejecuta todavía.',
      fr: 'La file est prête. Rien ne tourne encore.',
      hi: 'कतार तैयार है। अभी कुछ नहीं चल रहा।',
      id: 'Antrean sudah siap. Belum ada yang berjalan.',
      pt: 'A fila está pronta. Nada está em execução ainda.',
    },
    'caption.dequeue': {
      en: '{task}: taken from the queue, starts running.',
      ko: '{task}: 줄에서 꺼내져 돌기 시작.',
      ja: '{task}: キューから取り出され、実行を始める。',
      zh: '{task}:从队列中取出,开始运行。',
      ar: '{task}: أُخرجت من الطابور وبدأت العمل.',
      es: '{task}: se saca de la cola y empieza a ejecutarse.',
      fr: "{task} : sorti de la file, commence à s'exécuter.",
      hi: '{task}: कतार से निकाला गया, चलना शुरू।',
      id: '{task}: diambil dari antrean, mulai berjalan.',
      pt: '{task}: retirada da fila, começa a executar.',
    },
    'caption.progress': {
      en: '{task}: keeps running. Unit {u} of {total}.',
      ko: '{task}: 계속 돈다. 단위 {u}/{total}.',
      ja: '{task}: 実行を続ける。単位 {u}/{total}。',
      zh: '{task}:继续运行。单元 {u}/{total}。',
      ar: '{task}: يستمر بالعمل. الوحدة {u}/{total}.',
      es: '{task}: sigue ejecutándose. Unidad {u} de {total}.',
      fr: "{task} : continue de s'exécuter. Unité {u}/{total}.",
      hi: '{task}: चलना जारी। इकाई {u}/{total}।',
      id: '{task}: terus berjalan. Unit {u}/{total}.',
      pt: '{task}: continua em execução. Unidade {u} de {total}.',
    },
    'caption.finish': {
      en: '{task}: runs to the end.',
      ko: '{task}: 끝까지 돌았다.',
      ja: '{task}: 最後まで動いた。',
      zh: '{task}:一直运行到结束。',
      ar: '{task}: عمل حتى النهاية.',
      es: '{task}: se ejecuta hasta el final.',
      fr: "{task} : s'exécute jusqu'au bout.",
      hi: '{task}: अंत तक चला।',
      id: '{task}: berjalan sampai selesai.',
      pt: '{task}: executa até o fim.',
    },
    'caption.arrive': {
      en: '{task}: lines up at the back of the queue.',
      ko: '{task}: 줄 뒤에 섰다.',
      ja: '{task}: キューの最後尾に並ぶ。',
      zh: '{task}:排到队列末尾。',
      ar: '{task}: يقف في آخر الطابور.',
      es: '{task}: se pone al final de la cola.',
      fr: "{task} : se place au bout de la file.",
      hi: '{task}: कतार के अंत में लगा।',
      id: '{task}: berdiri di belakang antrean.',
      pt: '{task}: entra no fim da fila.',
    },
    'label.clickA': {
      en: 'Click A',
      ko: '클릭 A',
      ja: 'クリック A',
      zh: '点击 A',
      ar: 'نقرة A',
      es: 'Clic A',
      fr: 'Clic A',
      hi: 'क्लिक A',
      id: 'Klik A',
      pt: 'Clique A',
    },
    'label.timer': {
      en: 'Timer',
      ko: '타이머',
      ja: 'タイマー',
      zh: '计时器',
      ar: 'المؤقت',
      es: 'Temporizador',
      fr: 'Minuteur',
      hi: 'टाइमर',
      id: 'Timer',
      pt: 'Temporizador',
    },
    'label.clickB': {
      en: 'Click B',
      ko: '클릭 B',
      ja: 'クリック B',
      zh: '点击 B',
      ar: 'نقرة B',
      es: 'Clic B',
      fr: 'Clic B',
      hi: 'क्लिक B',
      id: 'Klik B',
      pt: 'Clique B',
    },
    'label.queueSection': {
      en: 'Task queue',
      ko: '태스크 줄',
      ja: 'タスクキュー',
      zh: '任务队列',
      ar: 'طابور المهام',
      es: 'Cola de tareas',
      fr: 'File des tâches',
      hi: 'टास्क कतार',
      id: 'Antrean tugas',
      pt: 'Fila de tarefas',
    },
    'label.runningSection': {
      en: 'Running',
      ko: '도는 것',
      ja: '実行中',
      zh: '正在运行',
      ar: 'قيد التشغيل',
      es: 'En ejecución',
      fr: 'En cours',
      hi: 'चल रहा',
      id: 'Sedang berjalan',
      pt: 'Em execução',
    },
    'label.finishedSection': {
      en: 'Finished order',
      ko: '끝난 차례',
      ja: '終了した順序',
      zh: '完成顺序',
      ar: 'ترتيب الانتهاء',
      es: 'Orden de finalización',
      fr: 'Ordre de fin',
      hi: 'समाप्ति क्रम',
      id: 'Urutan selesai',
      pt: 'Ordem de conclusão',
    },
  },
};
