import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 수를 다른 이름에 넣으면 무엇이 옮겨 가는가.
 *
 * 수는 자리 안에 값 그대로 든다. `let height = width` 는 width 자리의 3 을 남겨 둔 채
 * 똑같은 3 하나를 베껴 height 자리에 넣는다. 그 뒤 height 가 6 이 되어도 width 는 3 이다.
 */
export const valueInPlaceFacet: FacetJson = {
  id: 'facet:valueInPlace',
  title: {
    en: 'A value sits in its slot',
    ko: '값은 자리에 들어 있다',
    ja: '値は場所の中にある',
    zh: '值就在位置里',
    ar: 'القيمة تسكن في خانتها',
    es: 'El valor está dentro de su casilla',
    fr: 'La valeur est dans sa case',
    hi: 'मान अपने खाने में रहता है',
    id: 'Nilai berada di dalam slotnya',
    pt: 'O valor fica dentro da sua casa',
  },
  description: {
    en: 'Put a number into another name and a copy of the number crosses over — the original stays where it was.',
    ko: '수를 다른 이름에 넣으면 그 수를 베낀 것이 건너간다 — 본래 수는 제자리에 남는다.',
    ja: '数を別の名前に入れると、その数の写しが渡っていく。元の数はその場に残る。',
    zh: '把一个数放进另一个名字时，过去的是这个数的副本——原来的数留在原处。',
    ar: 'حين تضع عددًا في اسم آخر تعبر نسخة منه — ويبقى العدد الأصلي في مكانه.',
    es: 'Al poner un número en otro nombre, lo que cruza es una copia; el original se queda donde estaba.',
    fr: 'Mettre un nombre dans un autre nom y fait passer une copie ; l’original reste à sa place.',
    hi: 'किसी संख्या को दूसरे नाम में रखने पर उसकी एक प्रति जाती है — मूल संख्या अपनी जगह रहती है।',
    id: 'Menaruh angka ke nama lain membuat salinannya menyeberang — angka aslinya tetap di tempat.',
    pt: 'Ao pôr um número em outro nome, o que atravessa é uma cópia — o original fica onde estava.',
  },
  algorithm: 'module:valueInPlace',
  scene: 'module:valueInPlaceScene',
  initialData: {
    type: 'value-in-place',
    stepMs: 1800,
    lines: [
      {
        indent: 0,
        text: 'let width = 3',
        stmt: { k: 'assign', to: 'width', value: { num: 3 }, declare: true },
      },
      {
        indent: 0,
        text: 'let height = width',
        stmt: { k: 'assign', to: 'height', value: { var: 'width' }, declare: true },
      },
      {
        indent: 0,
        text: 'height = height * 2',
        stmt: { k: 'assign', to: 'height', value: { op: '*', l: { var: 'height' }, r: { num: 2 } } },
      },
      { indent: 0, text: 'show width', stmt: { k: 'show', value: { var: 'width' } } },
      { indent: 0, text: 'show height', stmt: { k: 'show', value: { var: 'height' } } },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.slots': {
      en: 'slots',
      ko: '자리',
      ja: '場所',
      zh: '位置',
      ar: 'الخانات',
      es: 'casillas',
      fr: 'cases',
      hi: 'खाने',
      id: 'slot',
      pt: 'casas',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المخرجات',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
    'caption.start': {
      en: 'No line has run yet.',
      ko: '아직 아무 줄도 밟지 않았다.',
      ja: 'まだどの行も実行していない。',
      zh: '还没有执行任何一行。',
      ar: 'لم يُنفَّذ أي سطر بعد.',
      es: 'Aún no se ha ejecutado ninguna línea.',
      fr: 'Aucune ligne n’a encore été exécutée.',
      hi: 'अभी तक कोई पंक्ति नहीं चली है।',
      id: 'Belum ada baris yang dijalankan.',
      pt: 'Nenhuma linha foi executada ainda.',
    },
    'caption.declareLiteral': {
      en: 'A new slot opens for {name}. The number {value} goes inside it.',
      ko: '새 자리를 잡는다 — 이름 {name}. 그 안에 수 {value} 하나가 들어간다.',
      ja: '新しい場所を取る — 名前は {name}。その中に数 {value} がひとつ入る。',
      zh: '为 {name} 开出一个新位置，数 {value} 放进去。',
      ar: 'تُفتح خانة جديدة للاسم {name}، ويدخلها العدد {value}.',
      es: 'Se abre una casilla nueva para {name}. Dentro entra el número {value}.',
      fr: 'Une nouvelle case s’ouvre pour {name}. Le nombre {value} y entre.',
      hi: '{name} के लिए नया खाना बनता है। उसमें संख्या {value} जाती है।',
      id: 'Slot baru dibuka untuk {name}. Angka {value} masuk ke dalamnya.',
      pt: 'Abre-se uma casa nova para {name}. O número {value} entra nela.',
    },
    'caption.declareCopy': {
      en: 'A new slot opens for {name}. The {value} in {src} is copied into it.',
      ko: '새 자리 {name} 에 {src} 자리의 수를 베껴 넣는다 — 들어간 것은 {value} 하나를 베낀 것.',
      ja: '新しい場所 {name} に {src} の場所の数を写して入れる — 入ったのは {value} の写し。',
      zh: '为 {name} 开出新位置，把 {src} 位置里的 {value} 复制进去。',
      ar: 'تُفتح خانة جديدة للاسم {name}، وتُنسخ إليها القيمة {value} من {src}.',
      es: 'Se abre una casilla nueva para {name}. El {value} de {src} se copia dentro.',
      fr: 'Une nouvelle case s’ouvre pour {name}. Le {value} de {src} y est copié.',
      hi: '{name} के लिए नया खाना बनता है। {src} के {value} की प्रति उसमें जाती है।',
      id: 'Slot baru dibuka untuk {name}. Nilai {value} dari {src} disalin ke dalamnya.',
      pt: 'Abre-se uma casa nova para {name}. O {value} de {src} é copiado para ela.',
    },
    'caption.declareCalc': {
      en: 'A new slot opens for {name}. The computed {value} goes inside it.',
      ko: '새 자리를 잡는다 — 이름 {name}. 셈한 수 {value} 하나가 들어간다.',
      ja: '新しい場所を取る — 名前は {name}。計算した数 {value} が入る。',
      zh: '为 {name} 开出一个新位置，算出的 {value} 放进去。',
      ar: 'تُفتح خانة جديدة للاسم {name}، ويدخلها الناتج {value}.',
      es: 'Se abre una casilla nueva para {name}. Dentro entra el resultado {value}.',
      fr: 'Une nouvelle case s’ouvre pour {name}. Le résultat {value} y entre.',
      hi: '{name} के लिए नया खाना बनता है। उसमें गणना से मिला {value} जाता है।',
      id: 'Slot baru dibuka untuk {name}. Hasil hitung {value} masuk ke dalamnya.',
      pt: 'Abre-se uma casa nova para {name}. O resultado {value} entra nela.',
    },
    'caption.assign': {
      en: 'Only slot {name} changes: {was} is replaced by {value}.',
      ko: '{name} 자리만 바뀐다 — 들어 있던 {was} 대신 {value}.',
      ja: '変わるのは {name} の場所だけ — {was} の代わりに {value}。',
      zh: '只有 {name} 的位置变了：{was} 换成了 {value}。',
      ar: 'تتغيّر خانة {name} وحدها: تحلّ {value} محلّ {was}.',
      es: 'Solo cambia la casilla {name}: {value} reemplaza a {was}.',
      fr: 'Seule la case {name} change : {value} remplace {was}.',
      hi: 'केवल {name} का खाना बदलता है: {was} की जगह {value}।',
      id: 'Hanya slot {name} yang berubah: {was} diganti {value}.',
      pt: 'Só a casa {name} muda: {value} substitui {was}.',
    },
    'caption.keep': {
      en: 'Slot {other} still holds {kept}.',
      ko: '{other} 자리에는 여전히 {kept}.',
      ja: '{other} の場所は今も {kept}。',
      zh: '{other} 的位置里仍是 {kept}。',
      ar: 'ما زالت خانة {other} تحمل {kept}.',
      es: 'La casilla {other} sigue guardando {kept}.',
      fr: 'La case {other} contient toujours {kept}.',
      hi: '{other} के खाने में अब भी {kept} है।',
      id: 'Slot {other} masih berisi {kept}.',
      pt: 'A casa {other} continua com {kept}.',
    },
    'caption.showCopy': {
      en: 'The {value} in {src} is copied out to the output.',
      ko: '{src} 자리의 수를 베껴 내보낸다 — 출력에 {value}.',
      ja: '{src} の場所の数を写して出す — 出力に {value}。',
      zh: '把 {src} 位置里的 {value} 复制到输出。',
      ar: 'تُنسخ القيمة {value} من {src} إلى المخرجات.',
      es: 'El {value} de {src} se copia a la salida.',
      fr: 'Le {value} de {src} est copié vers la sortie.',
      hi: '{src} के {value} की प्रति आउटपुट में जाती है।',
      id: 'Nilai {value} dari {src} disalin ke keluaran.',
      pt: 'O {value} de {src} é copiado para a saída.',
    },
    'caption.show': {
      en: '{value} goes to the output.',
      ko: '출력에 {value}.',
      ja: '出力に {value}。',
      zh: '输出 {value}。',
      ar: 'تخرج {value} إلى المخرجات.',
      es: '{value} va a la salida.',
      fr: '{value} va vers la sortie.',
      hi: '{value} आउटपुट में जाता है।',
      id: '{value} masuk ke keluaran.',
      pt: '{value} vai para a saída.',
    },
    'caption.end': {
      en: 'The program ends.',
      ko: '프로그램이 끝났다.',
      ja: 'プログラムが終わった。',
      zh: '程序结束了。',
      ar: 'انتهى البرنامج.',
      es: 'El programa termina.',
      fr: 'Le programme se termine.',
      hi: 'प्रोग्राम समाप्त हुआ।',
      id: 'Program selesai.',
      pt: 'O programa termina.',
    },
  },
  blocks: {
    stage: { type: 'value-in-place-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
