import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 갈래가 여럿인 규칙에서 파서는 어느 갈래로 갈지 무엇을 보고 정하는가.
 *
 * @notation native
 * 문법 규칙(화살표 · 세로줄 · ε)은 컴파일러 내부 표기이고 이 조각의 소재 그 자체다.
 * 원시 프로그램 글자는 가상 표기 그대로다.
 */
export const lookaheadOneFacet: FacetJson = {
  id: 'facet:lookaheadOne',
  title: {
    en: 'One token ahead',
    ko: '한 토큰 앞을 본다',
    ja: 'トークンを一つ先読みする',
    zh: '向前看一个记号',
    ar: 'النظر إلى رمز واحد للأمام',
    es: 'Mirar un token por delante',
    fr: 'Regarder un jeton en avant',
    hi: 'एक टोकन आगे देखना',
    id: 'Melihat satu token ke depan',
    pt: 'Olhar um token à frente',
  },
  description: {
    en: 'To choose a branch, the parser looks at the next token without eating it.',
    ko: '갈래를 고르려고 파서는 다음 토큰 하나를 먹지 않고 들여다본다.',
    ja: '分岐を選ぶために、パーサは次のトークンを消費せずに覗き見る。',
    zh: '为了选择分支，解析器查看下一个记号，但不吃掉它。',
    ar: 'لكي يختار المحلل فرعًا، ينظر إلى الرمز التالي دون أن يستهلكه.',
    es: 'Para elegir una rama, el analizador mira el siguiente token sin consumirlo.',
    fr: 'Pour choisir une branche, l’analyseur regarde le jeton suivant sans le consommer.',
    hi: 'शाखा चुनने के लिए पार्सर अगले टोकन को खाए बिना देखता है।',
    id: 'Untuk memilih cabang, parser melihat token berikutnya tanpa memakannya.',
    pt: 'Para escolher um ramo, o analisador olha o próximo token sem consumi-lo.',
  },
  algorithm: 'module:lookaheadOne',
  scene: 'module:lookaheadOneScene',
  initialData: {
    type: 'lookahead-one',
    stepMs: 1600,
    source: ['let n = 5', 'show n', 'n = 6'],
    tokens: [
      { kind: 'LET', text: 'let' },
      { kind: 'NAME', text: 'n' },
      { kind: 'OP', text: '=' },
      { kind: 'NUM', text: '5' },
      { kind: 'SHOW', text: 'show' },
      { kind: 'NAME', text: 'n' },
      { kind: 'NAME', text: 'n' },
      { kind: 'OP', text: '=' },
      { kind: 'NUM', text: '6' },
    ],
    rules: [
      { id: 'R1', lhs: 'Stmts', rhs: ['Stmt', 'Stmts'] },
      { id: 'R2', lhs: 'Stmts', rhs: [] },
      { id: 'R3', lhs: 'Stmt', rhs: ['let', 'NAME', '=', 'NUM'] },
      { id: 'R4', lhs: 'Stmt', rhs: ['show', 'NAME'] },
      { id: 'R5', lhs: 'Stmt', rhs: ['NAME', '=', 'NUM'] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.picks': {
      en: 'Picks',
      ko: '고른 차례',
      ja: '選んだ順',
      zh: '选择顺序',
      ar: 'الاختيارات',
      es: 'Elecciones',
      fr: 'Choix',
      hi: 'चुनाव',
      id: 'Pilihan',
      pt: 'Escolhas',
    },
    'label.looked': {
      en: 'Looked: {n}',
      ko: '들여다봄: {n}',
      ja: '覗き見: {n}',
      zh: '查看: {n}',
      ar: 'نظرات: {n}',
      es: 'Miradas: {n}',
      fr: 'Regards : {n}',
      hi: 'देखे: {n}',
      id: 'Dilihat: {n}',
      pt: 'Olhadas: {n}',
    },
    'label.eaten': {
      en: 'Eaten: {n}',
      ko: '먹음: {n}',
      ja: '消費: {n}',
      zh: '吃掉: {n}',
      ar: 'مستهلكة: {n}',
      es: 'Consumidos: {n}',
      fr: 'Consommés : {n}',
      hi: 'खाए: {n}',
      id: 'Dimakan: {n}',
      pt: 'Consumidos: {n}',
    },
    'caption.start': {
      en: 'Start. Reading position: #{pos}',
      ko: '시작. 읽는 자리: #{pos}',
      ja: '開始。読む位置: #{pos}',
      zh: '开始。读取位置: #{pos}',
      ar: 'البداية. موضع القراءة: #{pos}',
      es: 'Inicio. Posición de lectura: #{pos}',
      fr: 'Début. Position de lecture : #{pos}',
      hi: 'शुरुआत। पढ़ने की जगह: #{pos}',
      id: 'Mulai. Posisi baca: #{pos}',
      pt: 'Início. Posição de leitura: #{pos}',
    },
    'caption.pick': {
      en: '{nt}: the next token at #{pos} is {tok}. Branch: {rule}',
      ko: '{nt}: 자리 #{pos} 의 다음 토큰은 {tok}. 고른 갈래: {rule}',
      ja: '{nt}: 位置 #{pos} の次のトークンは {tok}。選んだ分岐: {rule}',
      zh: '{nt}: 位置 #{pos} 的下一个记号是 {tok}。选中的分支: {rule}',
      ar: '{nt}: الرمز التالي في #{pos} هو {tok}. الفرع: {rule}',
      es: '{nt}: el siguiente token en #{pos} es {tok}. Rama: {rule}',
      fr: '{nt} : le jeton suivant en #{pos} est {tok}. Branche : {rule}',
      hi: '{nt}: #{pos} पर अगला टोकन {tok} है। शाखा: {rule}',
      id: '{nt}: token berikutnya di #{pos} adalah {tok}. Cabang: {rule}',
      pt: '{nt}: o próximo token em #{pos} é {tok}. Ramo: {rule}',
    },
    'caption.ate': {
      en: 'Eaten since the last look: {n}',
      ko: '지난 들여다봄 뒤 먹은 토큰: {n}',
      ja: '前回の覗き見以降に消費したトークン: {n}',
      zh: '上次查看之后吃掉的记号: {n}',
      ar: 'المستهلك منذ آخر نظرة: {n}',
      es: 'Consumidos desde la última mirada: {n}',
      fr: 'Consommés depuis le dernier regard : {n}',
      hi: 'पिछली बार देखने के बाद खाए गए: {n}',
      id: 'Dimakan sejak lihat terakhir: {n}',
      pt: 'Consumidos desde a última olhada: {n}',
    },
    'caption.empty': {
      en: 'Empty branch: {nt} ends here.',
      ko: '빈 갈래 — 여기서 {nt} 끝.',
      ja: '空の分岐 — ここで {nt} は終わる。',
      zh: '空分支 — {nt} 到此结束。',
      ar: 'فرع فارغ: ينتهي {nt} هنا.',
      es: 'Rama vacía: {nt} termina aquí.',
      fr: 'Branche vide : {nt} s’arrête ici.',
      hi: 'खाली शाखा: {nt} यहीं खत्म होता है।',
      id: 'Cabang kosong: {nt} berakhir di sini.',
      pt: 'Ramo vazio: {nt} termina aqui.',
    },
  },
  blocks: {
    stage: { type: 'lookahead-one-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
