import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 오토마타가 글줄을 받는지는 무엇이 정하는가 — 받는 자리를 지나쳤다면?
 *
 * 무늬 `[0-9]+(e[0-9]+)?` 의 DFA 에 `120e` 를 넣는다. 지금 자리가 받는 자리 B 를 세 번 밟고
 * 지나가다 마지막 글자 `e` 에 받지 않는 자리 C 로 옮겨 간다. 판정은 다 먹은 뒤 멈춘 자리 하나로만 한다.
 *
 * @notation native — 컴파일러 내부 표기 (정규 표현식 · 오토마타의 옮김 이름표 `[0-9]`)
 */
export const acceptStateFacet: FacetJson = {
  id: 'facet:acceptState',
  title: {
    en: 'Only the stopping state decides',
    ko: '멈춘 자리만 판정한다',
    ja: '判定するのは止まった状態だけ',
    zh: '只有停下的状态才做判定',
    ar: 'الحالة التي يتوقف عندها هي وحدها التي تقرر',
    es: 'Solo decide el estado donde se detiene',
    fr: "Seul l'état d'arrêt décide",
    hi: 'फ़ैसला सिर्फ़ रुकने वाली अवस्था करती है',
    id: 'Hanya keadaan tempat berhenti yang menentukan',
    pt: 'Só o estado onde para decide',
  },
  description: {
    en: 'A DFA passes through an accepting state three times, then the last character moves it to a non-accepting one. Once the input runs out, the verdict falls on where it stopped — the accepting states it passed do not count.',
    ko: 'DFA 가 받는 자리를 세 번 밟고 지나가다 마지막 글자에 받지 않는 자리로 옮겨 간다. 입력이 다 떨어진 그 자리에 판정이 내려앉고, 앞서 밟은 받는 자리는 판정에 끼지 못한다.',
    ja: 'DFA は受理状態を三度通り過ぎ、最後の文字で非受理状態へ移る。入力が尽きたその場所に判定が下り、先に踏んだ受理状態は判定に入らない。',
    zh: 'DFA 三次经过接受状态,最后一个字符却把它带到非接受状态。输入用完时,判定落在停下的位置——之前经过的接受状态都不算。',
    ar: 'يمر الـ DFA بحالة قبول ثلاث مرات، ثم ينقله الحرف الأخير إلى حالة غير قابلة. حين تنفد المدخلات يقع الحكم على المكان الذي توقف فيه — حالات القبول التي مر بها لا تُحتسب.',
    es: 'Un AFD pasa tres veces por un estado de aceptación y el último carácter lo lleva a uno que no acepta. Al agotarse la entrada, el veredicto cae donde se detuvo: los estados de aceptación por los que pasó no cuentan.',
    fr: "Un AFD traverse trois fois un état acceptant, puis le dernier caractère le mène à un état non acceptant. Quand l'entrée est épuisée, le verdict tombe là où il s'arrête — les états acceptants traversés ne comptent pas.",
    hi: 'DFA तीन बार स्वीकार अवस्था से गुज़रता है, फिर आख़िरी अक्षर उसे अस्वीकार अवस्था में ले जाता है। इनपुट ख़त्म होने पर फ़ैसला वहीं होता है जहाँ वह रुका — रास्ते की स्वीकार अवस्थाएँ नहीं गिनी जातीं।',
    id: 'DFA melewati keadaan penerima tiga kali, lalu karakter terakhir memindahkannya ke keadaan bukan penerima. Saat masukan habis, putusan jatuh di tempat ia berhenti — keadaan penerima yang dilewati tidak dihitung.',
    pt: 'Um AFD passa três vezes por um estado de aceitação e o último caractere o leva a um que não aceita. Quando a entrada acaba, o veredito cai onde ele parou — os estados de aceitação pelos quais passou não contam.',
  },
  algorithm: 'module:acceptState',
  scene: 'module:acceptStateScene',
  initialData: {
    type: 'accept-state',
    stepMs: 1600,
    pattern: '[0-9]+(e[0-9]+)?',
    states: ['A', 'B', 'C', 'D'],
    start: 'A',
    accept: ['B', 'D'],
    edges: [
      { from: 'A', to: 'B', on: { kind: 'class', lo: '0', hi: '9' } },
      { from: 'B', to: 'B', on: { kind: 'class', lo: '0', hi: '9' } },
      { from: 'B', to: 'C', on: { kind: 'lit', ch: 'e' } },
      { from: 'C', to: 'D', on: { kind: 'class', lo: '0', hi: '9' } },
      { from: 'D', to: 'D', on: { kind: 'class', lo: '0', hi: '9' } },
    ],
    input: '120e',
  },
  shuffleOnReset: false,
  messages: {
    'label.start': {
      en: 'start',
      ko: '시작',
      ja: '開始',
      zh: '开始',
      ar: 'البداية',
      es: 'inicio',
      fr: 'départ',
      hi: 'शुरू',
      id: 'mulai',
      pt: 'início',
    },
    'label.pattern': {
      en: 'Pattern',
      ko: '무늬',
      ja: 'パターン',
      zh: '模式',
      ar: 'النمط',
      es: 'Patrón',
      fr: 'Motif',
      hi: 'पैटर्न',
      id: 'Pola',
      pt: 'Padrão',
    },
    'label.accepting': {
      en: 'accepting state',
      ko: '받는 자리',
      ja: '受理状態',
      zh: '接受状态',
      ar: 'حالة قبول',
      es: 'estado de aceptación',
      fr: 'état acceptant',
      hi: 'स्वीकार अवस्था',
      id: 'keadaan penerima',
      pt: 'estado de aceitação',
    },
    'label.trail': {
      en: 'Characters read · positions stood on',
      ko: '먹은 글자 · 선 자리',
      ja: '読んだ文字 · 立った状態',
      zh: '读过的字符 · 停过的状态',
      ar: 'الحروف المقروءة · الحالات التي وقف عندها',
      es: 'Caracteres leídos · estados pisados',
      fr: 'Caractères lus · états visités',
      hi: 'पढ़े गए अक्षर · जिन अवस्थाओं पर रुका',
      id: 'Karakter terbaca · keadaan yang disinggahi',
      pt: 'Caracteres lidos · estados pisados',
    },
    'label.accept': {
      en: 'accepted',
      ko: '받음',
      ja: '受理',
      zh: '接受',
      ar: 'مقبول',
      es: 'aceptada',
      fr: 'acceptée',
      hi: 'स्वीकृत',
      id: 'diterima',
      pt: 'aceita',
    },
    'label.reject': {
      en: 'rejected',
      ko: '안 받음',
      ja: '不受理',
      zh: '不接受',
      ar: 'مرفوض',
      es: 'rechazada',
      fr: 'rejetée',
      hi: 'अस्वीकृत',
      id: 'ditolak',
      pt: 'rejeitada',
    },
    'caption.start': {
      en: 'Start at {state}. Characters to read: {n}',
      ko: '시작 자리: {state}. 먹을 글자: {n}',
      ja: '開始状態: {state}。読む文字: {n}',
      zh: '起始状态: {state}。待读字符: {n}',
      ar: 'البداية عند {state}. الحروف المتبقية للقراءة: {n}',
      es: 'Empieza en {state}. Caracteres por leer: {n}',
      fr: 'Départ en {state}. Caractères à lire : {n}',
      hi: 'शुरुआत {state} से। पढ़ने को अक्षर: {n}',
      id: 'Mulai di {state}. Karakter yang akan dibaca: {n}',
      pt: 'Começa em {state}. Caracteres a ler: {n}',
    },
    'caption.move': {
      en: "Read '{ch}': {from} → {to}. Characters left: {n}",
      ko: "글자 '{ch}' 먹음: {from} → {to}. 남은 글자: {n}",
      ja: "文字 '{ch}' を読む: {from} → {to}。残りの文字: {n}",
      zh: "读入 '{ch}': {from} → {to}。剩余字符: {n}",
      ar: "قراءة '{ch}': {from} → {to}. الحروف المتبقية: {n}",
      es: "Lee '{ch}': {from} → {to}. Caracteres restantes: {n}",
      fr: "Lu '{ch}' : {from} → {to}. Caractères restants : {n}",
      hi: "'{ch}' पढ़ा: {from} → {to}। बचे अक्षर: {n}",
      id: "Baca '{ch}': {from} → {to}. Karakter tersisa: {n}",
      pt: "Lê '{ch}': {from} → {to}. Caracteres restantes: {n}",
    },
    'caption.moveAccepting': {
      en: "Read '{ch}': {from} → {to}, an accepting state. Characters left: {n}",
      ko: "글자 '{ch}' 먹음: {from} → {to} (받는 자리). 남은 글자: {n}",
      ja: "文字 '{ch}' を読む: {from} → {to}(受理状態)。残りの文字: {n}",
      zh: "读入 '{ch}': {from} → {to}(接受状态)。剩余字符: {n}",
      ar: "قراءة '{ch}': {from} → {to} (حالة قبول). الحروف المتبقية: {n}",
      es: "Lee '{ch}': {from} → {to} (estado de aceptación). Caracteres restantes: {n}",
      fr: "Lu '{ch}' : {from} → {to} (état acceptant). Caractères restants : {n}",
      hi: "'{ch}' पढ़ा: {from} → {to} (स्वीकार अवस्था)। बचे अक्षर: {n}",
      id: "Baca '{ch}': {from} → {to} (keadaan penerima). Karakter tersisa: {n}",
      pt: "Lê '{ch}': {from} → {to} (estado de aceitação). Caracteres restantes: {n}",
    },
    'caption.verdictAccept': {
      en: 'Input used up. Stopped at {state}, an accepting state: accepted',
      ko: '글자를 다 먹었다. 멈춘 자리 {state} — 받는 자리다. 받음',
      ja: '入力を読み終えた。止まった状態 {state} — 受理状態。受理',
      zh: '输入已读完。停在 {state} —— 是接受状态。接受',
      ar: 'نفدت المدخلات. التوقف عند {state} — حالة قبول. مقبول',
      es: 'Entrada agotada. Se detiene en {state}, estado de aceptación: aceptada',
      fr: "Entrée épuisée. Arrêt en {state}, un état acceptant : acceptée",
      hi: 'इनपुट ख़त्म। रुका {state} पर — स्वीकार अवस्था। स्वीकृत',
      id: 'Masukan habis. Berhenti di {state}, keadaan penerima: diterima',
      pt: 'Entrada esgotada. Parou em {state}, estado de aceitação: aceita',
    },
    'caption.verdictReject': {
      en: 'Input used up. Stopped at {state}, not an accepting state: rejected',
      ko: '글자를 다 먹었다. 멈춘 자리 {state} — 받는 자리가 아니다. 안 받음',
      ja: '入力を読み終えた。止まった状態 {state} — 受理状態ではない。不受理',
      zh: '输入已读完。停在 {state} —— 不是接受状态。不接受',
      ar: 'نفدت المدخلات. التوقف عند {state} — ليست حالة قبول. مرفوض',
      es: 'Entrada agotada. Se detiene en {state}, que no acepta: rechazada',
      fr: "Entrée épuisée. Arrêt en {state}, un état non acceptant : rejetée",
      hi: 'इनपुट ख़त्म। रुका {state} पर — स्वीकार अवस्था नहीं। अस्वीकृत',
      id: 'Masukan habis. Berhenti di {state}, bukan keadaan penerima: ditolak',
      pt: 'Entrada esgotada. Parou em {state}, que não aceita: rejeitada',
    },
    'caption.passed': {
      en: 'Steps that stood on an accepting state before the stop: {k}. They do not count',
      ko: '멈추기 전 받는 자리에 선 걸음: {k}. 판정에 들지 않는다',
      ja: '止まる前に受理状態に立った歩数: {k}。判定には入らない',
      zh: '停下之前站在接受状态的步数: {k}。它们不计入判定',
      ar: 'الخطوات التي وقفت على حالة قبول قبل التوقف: {k}. لا تُحتسب',
      es: 'Pasos en un estado de aceptación antes de detenerse: {k}. No cuentan',
      fr: "Pas passés sur un état acceptant avant l'arrêt : {k}. Ils ne comptent pas",
      hi: 'रुकने से पहले स्वीकार अवस्था पर खड़े कदम: {k}। ये नहीं गिने जाते',
      id: 'Langkah di keadaan penerima sebelum berhenti: {k}. Tidak dihitung',
      pt: 'Passos num estado de aceitação antes de parar: {k}. Não contam',
    },
  },
  blocks: {
    stage: { type: 'accept-state-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
