import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 요청이 온 차례와 상관없이, 팔은 어떤 차례로 요청을 받는가?
 */
export const elevatorSweepFacet: FacetJson = {
  id: 'facet:elevatorSweep',
  title: {
    en: 'The Elevator Sweep',
    ko: '엘리베이터 훑기',
    ja: 'エレベーター走査',
    zh: '电梯式扫描',
    ar: 'مسح المصعد',
    es: 'El barrido del ascensor',
    fr: 'Le balayage de l’ascenseur',
    hi: 'एलिवेटर स्वीप',
    id: 'Sapuan elevator',
    pt: 'A varredura do elevador',
  },
  description: {
    en: 'Disk requests wait in the order they arrived, but the arm takes them in the order of its path: nearest ahead first, turning only when nothing is left that way. New requests ahead join this sweep; those behind wait for the return.',
    ko: '디스크 요청은 온 차례로 서 있지만 팔은 제 길의 차례로 받는다. 가는 쪽에서 가장 가까운 것부터 받고, 그쪽에 남은 것이 없을 때만 돌아선다. 새 요청이 팔 앞에 있으면 이번 훑기에 끼고, 뒤에 있으면 돌아올 때까지 남는다.',
    ja: 'ディスク要求は届いた順に並んでいるが、アームは自分の進む道の順に受け取る。進む側でいちばん近いものから受け、その側に残りがなくなったときだけ向きを変える。新しい要求がアームの前にあれば今回の走査に入り、後ろにあれば戻ってくるまで待つ。',
    zh: '磁盘请求按到达顺序排队，但磁臂按自己路径上的顺序处理：先处理前进方向上最近的请求，只有那一侧没有剩余请求时才掉头。新请求若在磁臂前方就加入本次扫描，在后方则等到掉头回来。',
    ar: 'تنتظر طلبات القرص بترتيب وصولها، لكن الذراع يأخذها بترتيب مساره: الأقرب أمامه أولًا، ولا يستدير إلا حين لا يبقى شيء في ذلك الاتجاه. الطلبات الجديدة التي أمامه تنضم إلى هذا المسح، والتي خلفه تنتظر العودة.',
    es: 'Las peticiones de disco esperan en el orden en que llegaron, pero el brazo las atiende en el orden de su recorrido: primero la más cercana por delante, y solo gira cuando no queda nada en esa dirección. Las nuevas que están delante entran en este barrido; las de detrás esperan la vuelta.',
    fr: 'Les requêtes disque attendent dans leur ordre d’arrivée, mais le bras les sert dans l’ordre de son trajet : la plus proche devant d’abord, et il ne fait demi-tour que lorsqu’il ne reste rien de ce côté. Les nouvelles requêtes devant rejoignent ce balayage ; celles derrière attendent le retour.',
    hi: 'डिस्क अनुरोध आने के क्रम में खड़े रहते हैं, पर आर्म उन्हें अपने रास्ते के क्रम में लेता है: आगे का सबसे नज़दीकी पहले, और तभी मुड़ता है जब उस तरफ़ कुछ न बचे। आगे आए नए अनुरोध इसी स्वीप में जुड़ते हैं; पीछे वाले लौटने तक रुकते हैं।',
    id: 'Permintaan disk menunggu sesuai urutan datang, tetapi lengan melayaninya sesuai urutan jalurnya: yang terdekat di depan lebih dulu, dan baru berbalik saat arah itu sudah kosong. Permintaan baru di depan ikut sapuan ini; yang di belakang menunggu lengan kembali.',
    pt: 'As requisições de disco esperam na ordem em que chegaram, mas o braço as atende na ordem do seu caminho: primeiro a mais próxima à frente, e só dá meia-volta quando não resta nada naquele sentido. As novas à frente entram nesta varredura; as de trás esperam a volta.',
  },
  algorithm: 'module:elevatorSweep',
  scene: 'module:elevatorSweepScene',
  initialData: {
    type: 'elevator-sweep',
    stepMs: 1300,
    cylinders: 200,
    start: 90,
    direction: 1,
    queue: [150, 40, 120, 20, 170, 95],
    arrivals: [{ after: 2, requests: [110, 185] }],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start.up': {
      en: 'Requests wait in arrival order. The arm is heading up.',
      ko: '요청이 온 차례로 서 있다. 팔은 위로 가는 중이다.',
      ja: '要求が届いた順に並んでいる。アームは上へ進んでいる。',
      zh: '请求按到达顺序排队。磁臂正向上移动。',
      ar: 'تنتظر الطلبات بترتيب وصولها. الذراع متجه إلى الأعلى.',
      es: 'Las peticiones esperan en orden de llegada. El brazo va hacia arriba.',
      fr: 'Les requêtes attendent dans l’ordre d’arrivée. Le bras monte.',
      hi: 'अनुरोध आने के क्रम में खड़े हैं। आर्म ऊपर की ओर जा रहा है।',
      id: 'Permintaan menunggu sesuai urutan datang. Lengan sedang bergerak naik.',
      pt: 'As requisições esperam na ordem de chegada. O braço está subindo.',
    },
    'caption.start.down': {
      en: 'Requests wait in arrival order. The arm is heading down.',
      ko: '요청이 온 차례로 서 있다. 팔은 아래로 가는 중이다.',
      ja: '要求が届いた順に並んでいる。アームは下へ進んでいる。',
      zh: '请求按到达顺序排队。磁臂正向下移动。',
      ar: 'تنتظر الطلبات بترتيب وصولها. الذراع متجه إلى الأسفل.',
      es: 'Las peticiones esperan en orden de llegada. El brazo va hacia abajo.',
      fr: 'Les requêtes attendent dans l’ordre d’arrivée. Le bras descend.',
      hi: 'अनुरोध आने के क्रम में खड़े हैं। आर्म नीचे की ओर जा रहा है।',
      id: 'Permintaan menunggu sesuai urutan datang. Lengan sedang bergerak turun.',
      pt: 'As requisições esperam na ordem de chegada. O braço está descendo.',
    },
    'caption.serve': {
      en: 'Nearest request ahead of the arm is served: cylinder {cyl}, #{order}',
      ko: '팔 앞쪽에서 가장 가까운 요청을 받는다: 실린더 {cyl}, 차례 {order}',
      ja: 'アームの前でいちばん近い要求を受ける: シリンダー {cyl}、順番 {order}',
      zh: '处理磁臂前方最近的请求：柱面 {cyl}，第 {order} 个',
      ar: 'يُخدَم أقرب طلب أمام الذراع: الأسطوانة {cyl}، الترتيب {order}',
      es: 'Se atiende la petición más cercana por delante del brazo: cilindro {cyl}, n.º {order}',
      fr: 'La requête la plus proche devant le bras est servie : cylindre {cyl}, n° {order}',
      hi: 'आर्म के आगे का सबसे नज़दीकी अनुरोध लिया गया: सिलिंडर {cyl}, क्रम {order}',
      id: 'Permintaan terdekat di depan lengan dilayani: silinder {cyl}, urutan {order}',
      pt: 'A requisição mais próxima à frente do braço é atendida: cilindro {cyl}, n.º {order}',
    },
    'caption.last': {
      en: 'Last request served: cylinder {cyl}, #{order}. Turns: {turns}',
      ko: '마지막 요청을 받았다: 실린더 {cyl}, 차례 {order} · 돌아선 횟수 {turns}',
      ja: '最後の要求を受けた: シリンダー {cyl}、順番 {order} · 向きを変えた回数 {turns}',
      zh: '最后一个请求已处理：柱面 {cyl}，第 {order} 个 · 掉头次数 {turns}',
      ar: 'خُدم آخر طلب: الأسطوانة {cyl}، الترتيب {order}. مرات الاستدارة: {turns}',
      es: 'Última petición atendida: cilindro {cyl}, n.º {order}. Giros: {turns}',
      fr: 'Dernière requête servie : cylindre {cyl}, n° {order}. Demi-tours : {turns}',
      hi: 'आख़िरी अनुरोध लिया गया: सिलिंडर {cyl}, क्रम {order}। मुड़ना: {turns}',
      id: 'Permintaan terakhir dilayani: silinder {cyl}, urutan {order}. Berbalik: {turns}',
      pt: 'Última requisição atendida: cilindro {cyl}, n.º {order}. Voltas: {turns}',
    },
    'caption.arrive': {
      en: 'New requests arrive. Ahead of the arm: this sweep. Behind: after the turn.',
      ko: '새 요청이 온다. 팔 앞이면 이번 훑기에, 뒤면 돌아선 뒤에.',
      ja: '新しい要求が届く。アームの前なら今回の走査で、後ろなら折り返した後で。',
      zh: '新请求到达。在磁臂前方的进入本次扫描，在后方的等掉头之后。',
      ar: 'تصل طلبات جديدة. ما أمام الذراع: في هذا المسح. ما خلفه: بعد الاستدارة.',
      es: 'Llegan peticiones nuevas. Delante del brazo: en este barrido. Detrás: tras el giro.',
      fr: 'De nouvelles requêtes arrivent. Devant le bras : ce balayage. Derrière : après le demi-tour.',
      hi: 'नए अनुरोध आते हैं। आर्म के आगे वाले: इसी स्वीप में। पीछे वाले: मुड़ने के बाद।',
      id: 'Permintaan baru datang. Di depan lengan: sapuan ini. Di belakang: setelah berbalik.',
      pt: 'Chegam novas requisições. À frente do braço: nesta varredura. Atrás: depois da volta.',
    },
    'caption.turn.down': {
      en: 'Nothing left above the arm. It turns down.',
      ko: '팔 위쪽에 남은 요청이 없다. 아래로 돌아선다.',
      ja: 'アームより上に残りの要求がない。下へ向きを変える。',
      zh: '磁臂上方已没有请求。掉头向下。',
      ar: 'لم يبق شيء فوق الذراع. يستدير إلى الأسفل.',
      es: 'No queda nada por encima del brazo. Gira hacia abajo.',
      fr: 'Plus rien au-dessus du bras. Il repart vers le bas.',
      hi: 'आर्म के ऊपर कोई अनुरोध नहीं बचा। वह नीचे की ओर मुड़ता है।',
      id: 'Tidak ada yang tersisa di atas lengan. Lengan berbalik turun.',
      pt: 'Não resta nada acima do braço. Ele volta para baixo.',
    },
    'caption.turn.up': {
      en: 'Nothing left below the arm. It turns up.',
      ko: '팔 아래쪽에 남은 요청이 없다. 위로 돌아선다.',
      ja: 'アームより下に残りの要求がない。上へ向きを変える。',
      zh: '磁臂下方已没有请求。掉头向上。',
      ar: 'لم يبق شيء تحت الذراع. يستدير إلى الأعلى.',
      es: 'No queda nada por debajo del brazo. Gira hacia arriba.',
      fr: 'Plus rien au-dessous du bras. Il repart vers le haut.',
      hi: 'आर्म के नीचे कोई अनुरोध नहीं बचा। वह ऊपर की ओर मुड़ता है।',
      id: 'Tidak ada yang tersisa di bawah lengan. Lengan berbalik naik.',
      pt: 'Não resta nada abaixo do braço. Ele volta para cima.',
    },
    'label.arrived': {
      en: 'Arrival order',
      ko: '온 차례',
      ja: '届いた順',
      zh: '到达顺序',
      ar: 'ترتيب الوصول',
      es: 'Orden de llegada',
      fr: 'Ordre d’arrivée',
      hi: 'आने का क्रम',
      id: 'Urutan datang',
      pt: 'Ordem de chegada',
    },
    'label.served': {
      en: 'Service order',
      ko: '받은 차례',
      ja: '受けた順',
      zh: '处理顺序',
      ar: 'ترتيب الخدمة',
      es: 'Orden de atención',
      fr: 'Ordre de service',
      hi: 'लेने का क्रम',
      id: 'Urutan dilayani',
      pt: 'Ordem de atendimento',
    },
    'label.arm': {
      en: 'Arm {cyl}',
      ko: '팔 {cyl}',
      ja: 'アーム {cyl}',
      zh: '磁臂 {cyl}',
      ar: 'الذراع {cyl}',
      es: 'Brazo {cyl}',
      fr: 'Bras {cyl}',
      hi: 'आर्म {cyl}',
      id: 'Lengan {cyl}',
      pt: 'Braço {cyl}',
    },
    'label.ahead': {
      en: 'ahead',
      ko: '앞',
      ja: '前',
      zh: '前方',
      ar: 'أمام',
      es: 'delante',
      fr: 'devant',
      hi: 'आगे',
      id: 'depan',
      pt: 'à frente',
    },
    'label.behind': {
      en: 'behind',
      ko: '뒤',
      ja: '後ろ',
      zh: '后方',
      ar: 'خلف',
      es: 'detrás',
      fr: 'derrière',
      hi: 'पीछे',
      id: 'belakang',
      pt: 'atrás',
    },
  },
  blocks: {
    stage: { type: 'elevator-sweep-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
