/**
 * @piece
 * CSS 안에서만 불리는 그림(`hero.jpg`)을 `<link rel="preload">` 로 미리 알려 두면,
 * 그 그림의 요청은 언제 출발하는가 — 그것을 실제로 부르는 스타일시트가 도착하기
 * 전인가, 후인가?
 *
 * @notation native — 주장이 `<link rel="preload">` 힌트와 CSS `url()` 이 늦게
 * 발견되는 동작 그 자체다. 화면의 코드는 사양이 준 HTML·CSS 그대로이며 줄을
 * 바꾸거나 더하지 않는다.
 */
import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const preloadHintFacet: FacetJson = {
  id: 'facet:preloadHint',
  title: {
    en: 'Preload Hint',
    ko: '미리 읽기 힌트',
    ja: 'プリロードヒント',
    zh: '预加载提示',
    ar: 'تلميح التحميل المسبق',
    es: 'Pista de precarga',
    fr: 'Indice de préchargement',
    hi: 'प्रीलोड संकेत',
    id: 'Petunjuk preload',
    pt: 'Dica de pré-carregamento',
  },
  description: {
    en: 'A `<link rel="preload">` hint starts a CSS-only image\'s request long before the stylesheet that calls it even arrives.',
    ko: 'CSS 안에서만 불리는 그림도 `<link rel="preload">` 힌트를 달면, 그 그림을 부르는 스타일시트가 도착하기 한참 전에 이미 요청이 나가 있다.',
    ja: '`<link rel="preload">` ヒントは、CSS の中でしか呼ばれない画像のリクエストを、それを呼び出すスタイルシートが届くよりずっと前に開始させる。',
    zh: '`<link rel="preload">` 提示能让一张只在 CSS 里被调用的图片,在调用它的样式表到达之前很久,请求就已经出发。',
    ar: 'يجعل تلميح `<link rel="preload">` طلب صورة لا تُستدعى إلا داخل CSS ينطلق قبل وصول ورقة الأنماط التي تستدعيها بوقت طويل.',
    es: 'Una pista `<link rel="preload">` hace que la solicitud de una imagen invocada solo desde CSS parta mucho antes de que llegue la hoja de estilos que la llama.',
    fr: 'Un indice `<link rel="preload">` fait partir la requête d’une image appelée uniquement depuis le CSS bien avant l’arrivée de la feuille de style qui l’appelle.',
    hi: 'एक `<link rel="preload">` संकेत, केवल CSS के भीतर बुलाई जाने वाली तस्वीर के अनुरोध को, उसे बुलाने वाली स्टाइलशीट के पहुँचने से बहुत पहले ही रवाना कर देता है।',
    id: 'Petunjuk `<link rel="preload">` membuat permintaan gambar yang hanya dipanggil dari dalam CSS berangkat jauh sebelum stylesheet yang memanggilnya tiba.',
    pt: 'Uma dica `<link rel="preload">` faz o pedido de uma imagem chamada apenas dentro do CSS partir bem antes de a folha de estilo que a chama sequer chegar.',
  },
  algorithm: 'module:preloadHint',
  scene: 'module:preloadHintScene',
  initialData: {
    type: 'preload-hint',
    stepMs: 1400,
    docLines: [
      { id: 'preload', kind: 'preload', code: '<link rel="preload" href="hero.jpg" as="image">', resource: 'hero.jpg' },
      { id: 'link', kind: 'css', code: '<link rel="stylesheet" href="site.css">', resource: 'site.css' },
      { id: 'hero', kind: 'text', code: '<div class="hero"></div>' },
      { id: 'p1', kind: 'text', code: '<p>Welcome</p>' },
    ],
    cssRule: {
      code: '.hero { background-image: url(hero.jpg); }',
      slotId: 'hero',
      refResource: 'hero.jpg',
    },
    resources: [
      { file: 'site.css', durationMs: 200 },
      { file: 'hero.jpg', durationMs: 300 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.initial': {
      en: 'Four document lines are about to be parsed.',
      ko: '문서 넉 줄이 곧 파싱된다.',
      ja: 'ドキュメントの4行がまさに解析されようとしている。',
      zh: '文档的四行即将被解析。',
      ar: 'أربعة أسطر من المستند على وشك أن تُحلَّل.',
      es: 'Las cuatro líneas del documento están a punto de analizarse.',
      fr: 'Les quatre lignes du document sont sur le point d’être analysées.',
      hi: 'दस्तावेज़ की चार पंक्तियाँ अभी पार्स होने वाली हैं।',
      id: 'Empat baris dokumen akan segera diurai.',
      pt: 'As quatro linhas do documento estão prestes a ser analisadas.',
    },
    'caption.initialNote': {
      en: 'One line already asks for {file} ahead of time.',
      ko: '한 줄은 이미 {file} 요청을 미리 걸어 둔다.',
      ja: 'その一行はすでに{file}を先読みで要求している。',
      zh: '其中一行已经提前请求了{file}。',
      ar: 'أحد الأسطر يطلب {file} مسبقًا بالفعل.',
      es: 'Una línea ya pide {file} por adelantado.',
      fr: 'Une ligne demande déjà {file} par avance.',
      hi: 'एक पंक्ति पहले ही {file} को समय से पहले माँग चुकी है।',
      id: 'Satu baris sudah meminta {file} lebih awal.',
      pt: 'Uma linha já pede {file} com antecedência.',
    },
    'caption.preloadRequest': {
      en: 'The preload line is read — its request for {file} departs.',
      ko: 'preload 줄을 읽는다 — {file} 요청이 벌써 출발한다.',
      ja: 'preload行が読まれる — {file}のリクエストがすでに出発する。',
      zh: '解析到 preload 行 — {file} 的请求已经出发。',
      ar: 'يُقرأ سطر preload — يغادر طلب {file} بالفعل.',
      es: 'Se lee la línea preload — su solicitud de {file} ya parte.',
      fr: 'La ligne preload est lue — sa requête pour {file} part déjà.',
      hi: 'preload पंक्ति पढ़ी जाती है — {file} का अनुरोध पहले ही रवाना हो जाता है।',
      id: 'Baris preload dibaca — permintaan {file} sudah berangkat.',
      pt: 'A linha preload é lida — o pedido de {file} já parte.',
    },
    'caption.styleRequest': {
      en: 'The stylesheet line is read — its request for {file} departs.',
      ko: 'stylesheet 줄을 읽는다 — {file} 요청이 벌써 출발한다.',
      ja: 'stylesheet行が読まれる — {file}のリクエストがすでに出発する。',
      zh: '解析到 stylesheet 行 — {file} 的请求已经出发。',
      ar: 'يُقرأ سطر stylesheet — يغادر طلب {file} بالفعل.',
      es: 'Se lee la línea stylesheet — su solicitud de {file} ya parte.',
      fr: 'La ligne stylesheet est lue — sa requête pour {file} part déjà.',
      hi: 'stylesheet पंक्ति पढ़ी जाती है — {file} का अनुरोध पहले ही रवाना हो जाता है।',
      id: 'Baris stylesheet dibaca — permintaan {file} sudah berangkat.',
      pt: 'A linha stylesheet é lida — o pedido de {file} já parte.',
    },
    'caption.parseEnd': {
      en: 'The remaining lines are read — parsing ends.',
      ko: '남은 줄을 마저 읽는다 — 파싱이 끝난다.',
      ja: '残りの行を読み終える — 解析が終わる。',
      zh: '读完剩下的行 — 解析结束。',
      ar: 'تُقرأ بقية الأسطر — ينتهي التحليل.',
      es: 'Se leen las líneas restantes — el análisis termina.',
      fr: 'Les lignes restantes sont lues — l’analyse se termine.',
      hi: 'बची पंक्तियाँ पढ़ी जाती हैं — पार्सिंग खत्म होती है।',
      id: 'Baris yang tersisa dibaca — penguraian selesai.',
      pt: 'As linhas restantes são lidas — a análise termina.',
    },
    'caption.parseEndNote': {
      en: 'Two requests are already in flight.',
      ko: '이미 요청 둘이 떠 있다.',
      ja: 'すでに二つのリクエストが進行中だ。',
      zh: '已经有两个请求在途中。',
      ar: 'طلبان في الطريق بالفعل.',
      es: 'Ya hay dos solicitudes en curso.',
      fr: 'Deux requêtes sont déjà en vol.',
      hi: 'दो अनुरोध पहले से ही चल रहे हैं।',
      id: 'Dua permintaan sudah dalam perjalanan.',
      pt: 'Já há dois pedidos em andamento.',
    },
    'caption.needed': {
      en: 'The stylesheet arrives, and its rule calls {file} for the first time.',
      ko: '스타일시트가 도착한다 — 그 규칙이 이제 {file} 호출을 시작한다.',
      ja: 'スタイルシートが到着し、そのルールが{file}を初めて呼び出す。',
      zh: '样式表到达,它的规则第一次调用{file}。',
      ar: 'تصل ورقة الأنماط، وتستدعي قاعدتها {file} لأول مرة.',
      es: 'La hoja de estilos llega, y su regla llama a {file} por primera vez.',
      fr: 'La feuille de style arrive, et sa règle appelle {file} pour la première fois.',
      hi: 'स्टाइलशीट पहुँचती है, और उसका नियम पहली बार {file} को बुलाता है।',
      id: 'Stylesheet tiba, dan aturannya memanggil {file} untuk pertama kali.',
      pt: 'A folha de estilo chega, e sua regra chama {file} pela primeira vez.',
    },
    'caption.neededNote': {
      en: 'It is already {percent}% received.',
      ko: '이미 {percent}% 만큼 받은 상태다.',
      ja: 'すでに{percent}%受信済みだ。',
      zh: '已经收到 {percent}%。',
      ar: 'تم استلام {percent}٪ منه بالفعل.',
      es: 'Ya se ha recibido el {percent}%.',
      fr: 'Il est déjà reçu à {percent}%.',
      hi: 'इसका {percent}% पहले ही मिल चुका है।',
      id: 'Sudah diterima {percent}% darinya.',
      pt: 'Já foi recebido {percent}% dele.',
    },
    'caption.firstPaint': {
      en: 'The page paints for the first time — the background-image area stays empty.',
      ko: '페이지가 처음 그려진다 — 배경 그림 자리는 아직 비어 있다.',
      ja: 'ページが初めて描画される — 背景画像の場所はまだ空だ。',
      zh: '页面第一次绘制 — 背景图区域仍是空的。',
      ar: 'تُرسم الصفحة لأول مرة — تبقى منطقة صورة الخلفية فارغة.',
      es: 'La página se pinta por primera vez — el área de la imagen de fondo sigue vacía.',
      fr: 'La page se peint pour la première fois — la zone de l’image de fond reste vide.',
      hi: 'पेज पहली बार बनता है — बैकग्राउंड इमेज की जगह अभी भी खाली है।',
      id: 'Halaman tergambar untuk pertama kali — area gambar latar tetap kosong.',
      pt: 'A página é pintada pela primeira vez — a área da imagem de fundo continua vazia.',
    },
    'caption.firstPaintNote': {
      en: 'The rule already fired — only the image is still on the way.',
      ko: '규칙은 이미 불렸다 — 그림만 아직 오는 중이다.',
      ja: 'ルールはすでに発火した — 画像だけがまだ届いていない。',
      zh: '规则已经触发 — 只是图片还在路上。',
      ar: 'أُطلقت القاعدة بالفعل — الصورة فقط ما زالت في الطريق.',
      es: 'La regla ya se disparó — solo falta que llegue la imagen.',
      fr: 'La règle s’est déjà déclenchée — seule l’image est encore en chemin.',
      hi: 'नियम पहले ही चल चुका है — बस तस्वीर अभी आ रही है।',
      id: 'Aturan sudah aktif — hanya gambarnya yang masih dalam perjalanan.',
      pt: 'A regra já disparou — só falta a imagem chegar.',
    },
    'caption.arrived': {
      en: '{file} arrives, and the area fills in.',
      ko: '{file} 도착 — 그 자리가 채워진다.',
      ja: '{file}が到着し、その場所が埋まる。',
      zh: '{file} 到达,区域被填满。',
      ar: 'يصل {file}، وتمتلئ المنطقة.',
      es: '{file} llega, y el área se rellena.',
      fr: '{file} arrive, et la zone se remplit.',
      hi: '{file} पहुँचता है, और जगह भर जाती है।',
      id: '{file} tiba, dan area itu terisi.',
      pt: '{file} chega, e a área se preenche.',
    },
    'caption.arrivedNote': {
      en: 'It departed {leadMs}ms before this moment was needed.',
      ko: '이 순간이 필요해지기 {leadMs}ms 전에 이미 출발해 있었다.',
      ja: 'この瞬間が必要になる{leadMs}ms前に、すでに出発していた。',
      zh: '它在这一刻被需要之前 {leadMs}ms 就已经出发了。',
      ar: 'غادر قبل {leadMs}ms من هذه اللحظة التي احتيج فيها إليه.',
      es: 'Partió {leadMs}ms antes de que este momento lo necesitara.',
      fr: 'Elle est partie {leadMs}ms avant que ce moment en ait besoin.',
      hi: 'यह इस पल की ज़रूरत से {leadMs}ms पहले ही रवाना हो चुका था।',
      id: 'Ia berangkat {leadMs}ms sebelum saat ini dibutuhkan.',
      pt: 'Ele partiu {leadMs}ms antes deste momento ser necessário.',
    },
    'label.document': {
      en: 'Document',
      ko: '문서',
      ja: 'ドキュメント',
      zh: '文档',
      ar: 'المستند',
      es: 'Documento',
      fr: 'Document',
      hi: 'दस्तावेज़',
      id: 'Dokumen',
      pt: 'Documento',
    },
    'label.timeline': {
      en: 'Requests over time',
      ko: '시간에 따른 요청',
      ja: '時間ごとのリクエスト',
      zh: '按时间排列的请求',
      ar: 'الطلبات عبر الزمن',
      es: 'Solicitudes a lo largo del tiempo',
      fr: 'Requêtes dans le temps',
      hi: 'समय के साथ अनुरोध',
      id: 'Permintaan sepanjang waktu',
      pt: 'Pedidos ao longo do tempo',
    },
    'label.heroArea': {
      en: 'Where the background image lands',
      ko: '배경 그림이 놓일 자리',
      ja: '背景画像が収まる場所',
      zh: '背景图落地的位置',
      ar: 'أين تحطّ صورة الخلفية',
      es: 'Dónde cae la imagen de fondo',
      fr: 'Où atterrit l’image de fond',
      hi: 'जहाँ बैकग्राउंड इमेज बैठती है',
      id: 'Tempat gambar latar mendarat',
      pt: 'Onde a imagem de fundo se encaixa',
    },
  },
  blocks: {
    stage: { type: 'preload-hint-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
