import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 함수 깊은 곳에서 예외를 던지면 그것은 어디서 멈추는가?
 *
 * check 가 던진 ValueError 가 자기 틀을 떠나 부른 자리(load 의 줄 6)로 오르고, load 에는
 * try 가 없어 그 틀도 떠나 맨 바깥의 줄 9 로 오른다. 그 자리가 try 몸 안이라 except 로
 * 떨어진다. 지나온 틀의 남은 줄(4 · 7 · 10)은 밟히지 않는다.
 */
export const exceptionPropagateFacet: FacetJson = {
  id: 'facet:exceptionPropagate',
  title: {
    en: 'An exception climbs to the call sites',
    ko: '예외는 부른 자리를 거슬러 오른다',
    ja: '例外は呼び出し元をさかのぼる',
    zh: '异常沿着调用处向上传播',
    ar: 'الاستثناء يصعد إلى مواضع الاستدعاء',
    es: 'Una excepción sube hasta los puntos de llamada',
    fr: 'Une exception remonte vers les points d’appel',
    hi: 'अपवाद बुलाने वाली जगहों तक ऊपर चढ़ता है',
    id: 'Pengecualian naik ke tempat pemanggilan',
    pt: 'Uma exceção sobe até os pontos de chamada',
  },
  description: {
    en: 'An error raised deep inside a function leaves its frame, skips every frame with no try, and stops at the first call site inside a try.',
    ko: '함수 깊은 곳에서 던진 오류는 자기 틀을 떠나 try 가 없는 틀을 모두 건너뛰고, try 몸 안의 첫 부른 자리에서 멈춘다.',
    ja: '関数の奥で投げられたエラーは自分のフレームを離れ、try のないフレームをすべて飛び越え、try の中にある最初の呼び出し元で止まる。',
    zh: '在函数深处抛出的错误离开自己的栈帧，跳过所有没有 try 的栈帧，停在第一个位于 try 内的调用处。',
    ar: 'الخطأ الذي يُرمى في عمق دالة يغادر إطاره، ويتخطى كل إطار لا يحوي try، ويتوقف عند أول موضع استدعاء داخل try.',
    es: 'Un error lanzado en lo profundo de una función abandona su marco, salta cada marco sin try y se detiene en el primer punto de llamada dentro de un try.',
    fr: 'Une erreur levée au fond d’une fonction quitte son cadre, saute chaque cadre sans try et s’arrête au premier point d’appel situé dans un try.',
    hi: 'फ़ंक्शन की गहराई में फेंकी गई त्रुटि अपना फ़्रेम छोड़ती है, try के बिना हर फ़्रेम लाँघती है और try के भीतर वाली पहली बुलाने की जगह पर रुकती है।',
    id: 'Galat yang dilempar jauh di dalam fungsi meninggalkan bingkainya, melompati setiap bingkai tanpa try, dan berhenti di tempat pemanggilan pertama yang berada di dalam try.',
    pt: 'Um erro lançado no fundo de uma função deixa seu quadro, salta cada quadro sem try e para no primeiro ponto de chamada dentro de um try.',
  },
  algorithm: 'module:exceptionPropagate',
  scene: 'module:exceptionPropagateScene',
  initialData: {
    type: 'exception-propagate',
    stepMs: 1200,
    lines: [
      { indent: 0, text: 'def check(v):', stmt: { k: 'def', name: 'check', params: ['v'] } },
      {
        indent: 1,
        text: 'if v < 0:',
        stmt: { k: 'if', cond: { op: '<', l: { var: 'v' }, r: { num: 0 } } },
      },
      { indent: 2, text: 'raise ValueError', stmt: { k: 'raise', error: 'ValueError' } },
      { indent: 1, text: 'return v', stmt: { k: 'return', value: { var: 'v' } } },
      { indent: 0, text: 'def load(v):', stmt: { k: 'def', name: 'load', params: ['v'] } },
      {
        indent: 1,
        text: 'x = check(v)',
        stmt: { k: 'assign', to: 'x', value: { call: 'check', args: [{ var: 'v' }] } },
      },
      {
        indent: 1,
        text: 'return x * 2',
        stmt: { k: 'return', value: { op: '*', l: { var: 'x' }, r: { num: 2 } } },
      },
      { indent: 0, text: 'try:', stmt: { k: 'try' } },
      {
        indent: 1,
        text: 'y = load(-3)',
        stmt: { k: 'assign', to: 'y', value: { call: 'load', args: [{ num: -3 }] } },
      },
      {
        indent: 1,
        text: 'print(y)',
        stmt: { k: 'expr', value: { call: 'print', args: [{ var: 'y' }] } },
      },
      { indent: 0, text: 'except ValueError:', stmt: { k: 'except', error: 'ValueError' } },
      {
        indent: 1,
        text: 'print("bad value")',
        stmt: { k: 'expr', value: { call: 'print', args: [{ str: 'bad value' }] } },
      },
      {
        indent: 0,
        text: 'print("done")',
        stmt: { k: 'expr', value: { call: 'print', args: [{ str: 'done' }] } },
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has run yet.',
      ko: '아직 아무 줄도 밟지 않았다.',
      ja: 'まだどの行も実行していない。',
      zh: '还没有执行任何一行。',
      ar: 'لم يُنفَّذ أي سطر بعد.',
      es: 'Todavía no se ha ejecutado nada.',
      fr: 'Rien ne s’est encore exécuté.',
      hi: 'अभी तक कोई पंक्ति नहीं चली।',
      id: 'Belum ada baris yang dijalankan.',
      pt: 'Nada foi executado ainda.',
    },
    'caption.enter': {
      en: 'Line {line}: into the try body.',
      ko: '줄 {line} — try 몸으로 들어간다.',
      ja: '{line} 行目 — try の本体に入る。',
      zh: '第 {line} 行 — 进入 try 的主体。',
      ar: 'السطر {line}: الدخول إلى جسم try.',
      es: 'Línea {line}: entra en el cuerpo del try.',
      fr: 'Ligne {line} : on entre dans le corps du try.',
      hi: 'पंक्ति {line}: try के भीतर प्रवेश।',
      id: 'Baris {line}: masuk ke badan try.',
      pt: 'Linha {line}: entra no corpo do try.',
    },
    'caption.call': {
      en: 'Line {line} calls {fn} — a new frame stands.',
      ko: '줄 {line} — {fn} 부름. 새 틀이 선다.',
      ja: '{line} 行目 — {fn} を呼ぶ。新しいフレームが立つ。',
      zh: '第 {line} 行调用 {fn} — 新的栈帧立起。',
      ar: 'السطر {line} يستدعي {fn} — يقوم إطار جديد.',
      es: 'La línea {line} llama a {fn}: se levanta un marco nuevo.',
      fr: 'La ligne {line} appelle {fn} : un nouveau cadre se dresse.',
      hi: 'पंक्ति {line} {fn} को बुलाती है — नया फ़्रेम खड़ा होता है।',
      id: 'Baris {line} memanggil {fn} — bingkai baru berdiri.',
      pt: 'A linha {line} chama {fn}: um novo quadro se ergue.',
    },
    'caption.test': {
      en: 'Line {line}: the condition is {value}.',
      ko: '줄 {line} — 조건: {value}.',
      ja: '{line} 行目 — 条件: {value}。',
      zh: '第 {line} 行 — 条件：{value}。',
      ar: 'السطر {line}: الشرط {value}.',
      es: 'Línea {line}: la condición es {value}.',
      fr: 'Ligne {line} : la condition est {value}.',
      hi: 'पंक्ति {line}: शर्त {value}।',
      id: 'Baris {line}: kondisinya {value}.',
      pt: 'Linha {line}: a condição é {value}.',
    },
    'caption.assign': {
      en: 'Line {line}: {name} = {value}.',
      ko: '줄 {line} — {name} = {value}.',
      ja: '{line} 行目 — {name} = {value}。',
      zh: '第 {line} 行 — {name} = {value}。',
      ar: 'السطر {line}: {name} = {value}.',
      es: 'Línea {line}: {name} = {value}.',
      fr: 'Ligne {line} : {name} = {value}.',
      hi: 'पंक्ति {line}: {name} = {value}।',
      id: 'Baris {line}: {name} = {value}.',
      pt: 'Linha {line}: {name} = {value}.',
    },
    'caption.print': {
      en: 'Line {line} prints: {out}',
      ko: '줄 {line} — 출력: {out}',
      ja: '{line} 行目 — 出力: {out}',
      zh: '第 {line} 行 — 输出：{out}',
      ar: 'السطر {line} يطبع: {out}',
      es: 'La línea {line} imprime: {out}',
      fr: 'La ligne {line} affiche : {out}',
      hi: 'पंक्ति {line} छापती है: {out}',
      id: 'Baris {line} mencetak: {out}',
      pt: 'A linha {line} imprime: {out}',
    },
    'caption.line': {
      en: 'Line {line}.',
      ko: '줄 {line}.',
      ja: '{line} 行目。',
      zh: '第 {line} 行。',
      ar: 'السطر {line}.',
      es: 'Línea {line}.',
      fr: 'Ligne {line}.',
      hi: 'पंक्ति {line}।',
      id: 'Baris {line}.',
      pt: 'Linha {line}.',
    },
    'caption.return': {
      en: 'Line {line}: {fn} returns and its frame comes down.',
      ko: '줄 {line} — {fn} 돌아감. 그 틀이 걷힌다.',
      ja: '{line} 行目 — {fn} が戻り、そのフレームが外れる。',
      zh: '第 {line} 行 — {fn} 返回，它的栈帧撤下。',
      ar: 'السطر {line}: تعود {fn} ويُزال إطارها.',
      es: 'Línea {line}: {fn} regresa y su marco se retira.',
      fr: 'Ligne {line} : {fn} revient et son cadre est retiré.',
      hi: 'पंक्ति {line}: {fn} लौटता है और उसका फ़्रेम हटता है।',
      id: 'Baris {line}: {fn} kembali dan bingkainya dilepas.',
      pt: 'Linha {line}: {fn} retorna e seu quadro é retirado.',
    },
    'caption.throw': {
      en: 'Line {line} raises {error} inside {fn}.',
      ko: '줄 {line} — {fn} 안에서 {error} 던짐.',
      ja: '{line} 行目 — {fn} の中で {error} を投げる。',
      zh: '第 {line} 行在 {fn} 内抛出 {error}。',
      ar: 'السطر {line} يرمي {error} داخل {fn}.',
      es: 'La línea {line} lanza {error} dentro de {fn}.',
      fr: 'La ligne {line} lève {error} dans {fn}.',
      hi: 'पंक्ति {line} {fn} के भीतर {error} फेंकती है।',
      id: 'Baris {line} melempar {error} di dalam {fn}.',
      pt: 'A linha {line} lança {error} dentro de {fn}.',
    },
    'caption.arrive': {
      en: '{error} leaves {left} and reaches line {line} in {fn}.',
      ko: '{error} — {left} 틀을 떠나 {fn} 의 줄 {line} 에 닿는다.',
      ja: '{error} — {left} のフレームを離れ、{fn} の {line} 行目に届く。',
      zh: '{error} 离开 {left}，到达 {fn} 的第 {line} 行。',
      ar: '{error} يغادر {left} ويصل إلى السطر {line} في {fn}.',
      es: '{error} deja {left} y llega a la línea {line} de {fn}.',
      fr: '{error} quitte {left} et atteint la ligne {line} de {fn}.',
      hi: '{error} {left} छोड़कर {fn} की पंक्ति {line} तक पहुँचता है।',
      id: '{error} meninggalkan {left} dan tiba di baris {line} pada {fn}.',
      pt: '{error} deixa {left} e chega à linha {line} de {fn}.',
    },
    'caption.noTry': {
      en: 'No try here — the rest of {fn} is skipped as well.',
      ko: '여기엔 try 가 없다 — {fn} 의 남은 줄도 건너뛴다.',
      ja: 'ここに try はない — {fn} の残りの行も飛ばされる。',
      zh: '这里没有 try — {fn} 剩下的行也被跳过。',
      ar: 'لا يوجد try هنا — تُتخطّى بقية {fn} أيضًا.',
      es: 'Aquí no hay try: el resto de {fn} también se salta.',
      fr: 'Pas de try ici : le reste de {fn} est sauté lui aussi.',
      hi: 'यहाँ try नहीं है — {fn} की बाकी पंक्तियाँ भी छूट जाती हैं।',
      id: 'Tidak ada try di sini — sisa {fn} juga dilewati.',
      pt: 'Não há try aqui: o resto de {fn} também é pulado.',
    },
    'caption.inTry': {
      en: 'This call site is inside try.',
      ko: '이 부른 자리는 try 몸 안이다.',
      ja: 'この呼び出し元は try の中にある。',
      zh: '这个调用处位于 try 之内。',
      ar: 'موضع الاستدعاء هذا داخل try.',
      es: 'Este punto de llamada está dentro del try.',
      fr: 'Ce point d’appel est dans le try.',
      hi: 'यह बुलाने की जगह try के भीतर है।',
      id: 'Tempat pemanggilan ini berada di dalam try.',
      pt: 'Este ponto de chamada está dentro do try.',
    },
    'caption.catch': {
      en: 'Line {line}: except {error} catches it.',
      ko: '줄 {line} — except {error} 에서 잡힌다.',
      ja: '{line} 行目 — except {error} で捕まる。',
      zh: '第 {line} 行 — 被 except {error} 捕获。',
      ar: 'السطر {line}: يلتقطه except {error}.',
      es: 'Línea {line}: except {error} lo atrapa.',
      fr: 'Ligne {line} : except {error} l’attrape.',
      hi: 'पंक्ति {line}: except {error} इसे पकड़ता है।',
      id: 'Baris {line}: except {error} menangkapnya.',
      pt: 'Linha {line}: except {error} a captura.',
    },
    'caption.passed': {
      en: 'Frames skipped without catching: {n}.',
      ko: '잡지 않고 건너뛴 틀: {n}.',
      ja: '捕まえずに飛ばしたフレーム: {n}。',
      zh: '未捕获而跳过的栈帧：{n}。',
      ar: 'الإطارات المتخطاة دون التقاط: {n}.',
      es: 'Marcos saltados sin atrapar: {n}.',
      fr: 'Cadres sautés sans attraper : {n}.',
      hi: 'बिना पकड़े लाँघे गए फ़्रेम: {n}।',
      id: 'Bingkai yang dilewati tanpa menangkap: {n}.',
      pt: 'Quadros pulados sem capturar: {n}.',
    },
    'label.top': {
      en: 'top level',
      ko: '맨 바깥',
      ja: '最上位',
      zh: '顶层',
      ar: 'المستوى الأعلى',
      es: 'nivel superior',
      fr: 'niveau supérieur',
      hi: 'सबसे बाहरी स्तर',
      id: 'tingkat teratas',
      pt: 'nível superior',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المخرجات',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
    'label.skipped': {
      en: 'skipped',
      ko: '건너뜀',
      ja: '飛ばされた',
      zh: '已跳过',
      ar: 'متخطّى',
      es: 'saltado',
      fr: 'sauté',
      hi: 'लाँघा गया',
      id: 'dilewati',
      pt: 'pulado',
    },
    'label.true': {
      en: 'true',
      ko: '참',
      ja: '真',
      zh: '真',
      ar: 'صحيح',
      es: 'verdadera',
      fr: 'vraie',
      hi: 'सत्य',
      id: 'benar',
      pt: 'verdadeira',
    },
    'label.false': {
      en: 'false',
      ko: '거짓',
      ja: '偽',
      zh: '假',
      ar: 'خاطئ',
      es: 'falsa',
      fr: 'fausse',
      hi: 'असत्य',
      id: 'salah',
      pt: 'falsa',
    },
    'label.bind': {
      en: '{name} = {value}',
      ko: '{name} = {value}',
      ja: '{name} = {value}',
      zh: '{name} = {value}',
      ar: '{name} = {value}',
      es: '{name} = {value}',
      fr: '{name} = {value}',
      hi: '{name} = {value}',
      id: '{name} = {value}',
      pt: '{name} = {value}',
    },
  },
  blocks: {
    stage: { type: 'exception-propagate-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
