/**
 * @piece
 * 빌린 메모리를 돌려주지 않으면 어떻게 되는가.
 *
 * 반복마다 buf 가 새 덩이를 빌리고 그 순간 앞 덩이의 주소는 buf 칸에서 덮여 사라진다. 주소를 잃은
 * 덩이는 빌린 채 힙에 쌓이고, 끝의 free 는 buf 가 쥔 마지막 하나만 돌려준다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const memoryLeakFacet: FacetJson = {
  id: 'facet:memoryLeak',
  title: {
    en: 'Memory leak',
    ko: '메모리 누수',
    ja: 'メモリリーク',
    zh: '内存泄漏',
    ar: 'تسرّب الذاكرة',
    es: 'Fuga de memoria',
    fr: 'Fuite de mémoire',
    hi: 'मेमोरी लीक',
    id: 'Kebocoran memori',
    pt: 'Vazamento de memória',
  },
  description: {
    en: 'Each round borrows a new block and overwrites the only address of the last one. The lost blocks pile up, and the final free returns just one.',
    ko: '반복마다 새 덩이를 빌리며 앞 덩이의 하나뿐인 주소를 덮는다. 주소를 잃은 덩이가 쌓이고, 끝의 free 는 하나만 돌려준다.',
    ja: '繰り返すたびに新しいブロックを借り、前のブロックの唯一のアドレスを上書きする。アドレスを失ったブロックが積み重なり、最後の free は一つしか返さない。',
    zh: '每一轮都借一块新内存，并覆盖上一块唯一的地址。丢失地址的块不断堆积，最后的 free 只归还一块。',
    ar: 'في كل دورة تُستعار كتلة جديدة ويُكتب فوق العنوان الوحيد للكتلة السابقة. تتراكم الكتل الضائعة، ولا يُعيد free الأخير إلا واحدة.',
    es: 'Cada vuelta pide un bloque nuevo y sobrescribe la única dirección del anterior. Los bloques perdidos se acumulan y el free final devuelve solo uno.',
    fr: "Chaque tour emprunte un nouveau bloc et écrase la seule adresse du précédent. Les blocs perdus s'empilent et le free final n'en rend qu'un.",
    hi: 'हर चक्कर में एक नया खंड उधार लिया जाता है और पिछले खंड का इकलौता पता मिट जाता है। पता खोए खंड जमा होते जाते हैं और आख़िरी free बस एक लौटाता है।',
    id: 'Setiap putaran meminjam blok baru dan menimpa satu-satunya alamat blok sebelumnya. Blok yang hilang menumpuk dan free terakhir hanya mengembalikan satu.',
    pt: 'Cada volta pede um bloco novo e sobrescreve o único endereço do anterior. Os blocos perdidos se acumulam e o free final devolve só um.',
  },
  algorithm: 'module:memoryLeak',
  scene: 'module:memoryLeakScene',
  initialData: {
    type: 'memory-leak',
    stepMs: 1000,
    heapBase: 100,
    lines: [
      {
        indent: 0,
        text: 'let buf = null',
        stmt: { k: 'assign', to: 'buf', declare: true, value: { null: true } },
      },
      {
        indent: 0,
        text: 'for i from 1 to 4',
        stmt: { k: 'for', var: 'i', from: { num: 1 }, to: { num: 4 } },
      },
      {
        indent: 1,
        text: 'buf = allocate(2)',
        stmt: { k: 'assign', to: 'buf', value: { call: 'allocate', args: [{ num: 2 }] } },
      },
      {
        indent: 1,
        text: 'valueAt(buf) = i',
        stmt: { k: 'store', addr: { var: 'buf' }, value: { var: 'i' } },
      },
      {
        indent: 0,
        text: 'free(buf)',
        stmt: { k: 'expr', value: { call: 'free', args: [{ var: 'buf' }] } },
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has run yet.',
      ko: '아직 아무 줄도 실행하지 않았다.',
      ja: 'まだ何も実行していない。',
      zh: '还没有执行任何一行。',
      ar: 'لم يُنفَّذ أي سطر بعد.',
      es: 'Todavía no se ha ejecutado nada.',
      fr: "Rien n'a encore été exécuté.",
      hi: 'अभी तक कुछ भी नहीं चला।',
      id: 'Belum ada yang dijalankan.',
      pt: 'Nada foi executado ainda.',
    },
    'caption.set': {
      en: '{name} now holds {value}.',
      ko: '{name} 칸의 값: {value}.',
      ja: '{name} の値: {value}。',
      zh: '{name} 现在是 {value}。',
      ar: '{name} يحمل الآن {value}.',
      es: '{name} ahora guarda {value}.',
      fr: '{name} contient maintenant {value}.',
      hi: '{name} में अब {value} है।',
      id: '{name} kini berisi {value}.',
      pt: '{name} agora guarda {value}.',
    },
    'caption.iter': {
      en: 'Next round: {name} = {value}.',
      ko: '다음 바퀴: {name} = {value}.',
      ja: '次の周回: {name} = {value}。',
      zh: '下一轮: {name} = {value}。',
      ar: 'الدورة التالية: {name} = {value}.',
      es: 'Siguiente vuelta: {name} = {value}.',
      fr: 'Tour suivant : {name} = {value}.',
      hi: 'अगला चक्कर: {name} = {value}।',
      id: 'Putaran berikutnya: {name} = {value}.',
      pt: 'Próxima volta: {name} = {value}.',
    },
    'caption.exit': {
      en: 'The range is used up. The loop ends.',
      ko: '범위를 다 썼다. 반복을 빠져나간다.',
      ja: '範囲を使い切った。ループを抜ける。',
      zh: '范围用完了，退出循环。',
      ar: 'انتهى المدى، فتنتهي الحلقة.',
      es: 'Se agotó el rango. El bucle termina.',
      fr: 'La plage est épuisée. La boucle se termine.',
      hi: 'सीमा पूरी हो गई। लूप ख़त्म।',
      id: 'Rentang sudah habis. Perulangan selesai.',
      pt: 'O intervalo acabou. O laço termina.',
    },
    'caption.alloc': {
      en: 'A new block starts at {addr}. {name} now holds {addr}.',
      ko: '새 덩이의 시작 주소: {addr}. {name} 칸의 값: {addr}.',
      ja: '新しいブロックの先頭アドレス: {addr}。{name} の値: {addr}。',
      zh: '新块的起始地址: {addr}。{name} 现在是 {addr}。',
      ar: 'كتلة جديدة تبدأ عند {addr}. {name} يحمل الآن {addr}.',
      es: 'Un bloque nuevo empieza en {addr}. {name} ahora guarda {addr}.',
      fr: 'Un nouveau bloc commence à {addr}. {name} contient maintenant {addr}.',
      hi: 'नया खंड {addr} से शुरू होता है। {name} में अब {addr} है।',
      id: 'Blok baru mulai di {addr}. {name} kini berisi {addr}.',
      pt: 'Um bloco novo começa em {addr}. {name} agora guarda {addr}.',
    },
    'caption.allocLost': {
      en: '{name} now holds {addr}. The old address {was} is in no cell any more.',
      ko: '{name} 칸의 새 값: {addr}. 옛 주소 {was} — 이제 어느 칸에도 없다.',
      ja: '{name} の新しい値: {addr}。古いアドレス {was} はもうどのセルにもない。',
      zh: '{name} 的新值: {addr}。旧地址 {was} 已不在任何格子里。',
      ar: '{name} يحمل الآن {addr}. العنوان القديم {was} لم يعد في أي خانة.',
      es: '{name} ahora guarda {addr}. La dirección vieja {was} ya no está en ninguna celda.',
      fr: "{name} contient maintenant {addr}. L'ancienne adresse {was} n'est plus dans aucune case.",
      hi: '{name} में अब {addr} है। पुराना पता {was} अब किसी खाने में नहीं है।',
      id: '{name} kini berisi {addr}. Alamat lama {was} tak ada lagi di sel mana pun.',
      pt: '{name} agora guarda {addr}. O endereço antigo {was} não está mais em nenhuma célula.',
    },
    'caption.store': {
      en: 'Cell {addr} now holds {value}.',
      ko: '칸 {addr} 에 든 값: {value}.',
      ja: 'セル {addr} の値: {value}。',
      zh: '格子 {addr} 现在是 {value}。',
      ar: 'الخانة {addr} تحمل الآن {value}.',
      es: 'La celda {addr} ahora guarda {value}.',
      fr: 'La case {addr} contient maintenant {value}.',
      hi: 'खाना {addr} में अब {value} है।',
      id: 'Sel {addr} kini berisi {value}.',
      pt: 'A célula {addr} agora guarda {value}.',
    },
    'caption.free': {
      en: 'free returns the block at {addr}.',
      ko: 'free 로 돌아간 덩이: {addr}.',
      ja: 'free で返したブロック: {addr}。',
      zh: 'free 归还了 {addr} 处的块。',
      ar: 'يعيد free الكتلة عند {addr}.',
      es: 'free devuelve el bloque en {addr}.',
      fr: 'free rend le bloc à {addr}.',
      hi: 'free ने {addr} वाला खंड लौटाया।',
      id: 'free mengembalikan blok di {addr}.',
      pt: 'free devolve o bloco em {addr}.',
    },
    'stat.used': {
      en: 'Borrowed cells: {n}',
      ko: '빌린 칸: {n}',
      ja: '借りているセル: {n}',
      zh: '借出的格子: {n}',
      ar: 'الخانات المستعارة: {n}',
      es: 'Celdas prestadas: {n}',
      fr: 'Cases empruntées : {n}',
      hi: 'उधार लिए खाने: {n}',
      id: 'Sel dipinjam: {n}',
      pt: 'Células emprestadas: {n}',
    },
    'stat.lost': {
      en: 'Lost blocks: {n}',
      ko: '주소를 잃은 덩이: {n}',
      ja: 'アドレスを失ったブロック: {n}',
      zh: '丢失地址的块: {n}',
      ar: 'كتل بلا عنوان: {n}',
      es: 'Bloques perdidos: {n}',
      fr: 'Blocs perdus : {n}',
      hi: 'पता खोए खंड: {n}',
      id: 'Blok hilang: {n}',
      pt: 'Blocos perdidos: {n}',
    },
    'label.stack': {
      en: 'Stack',
      ko: '스택',
      ja: 'スタック',
      zh: '栈',
      ar: 'المكدس',
      es: 'Pila',
      fr: 'Pile',
      hi: 'स्टैक',
      id: 'Stack',
      pt: 'Pilha',
    },
    'label.heap': {
      en: 'Heap',
      ko: '힙',
      ja: 'ヒープ',
      zh: '堆',
      ar: 'الكومة',
      es: 'Montón',
      fr: 'Tas',
      hi: 'हीप',
      id: 'Heap',
      pt: 'Heap',
    },
    'label.free': {
      en: 'Free list',
      ko: '빈 자리 목록',
      ja: '空きリスト',
      zh: '空闲列表',
      ar: 'قائمة الفراغ',
      es: 'Lista libre',
      fr: 'Liste libre',
      hi: 'खाली सूची',
      id: 'Daftar kosong',
      pt: 'Lista livre',
    },
    'label.newEnd': {
      en: 'Fresh: {addr}',
      ko: '새 땅: {addr}',
      ja: '未使用: {addr}',
      zh: '新地: {addr}',
      ar: 'أرض جديدة: {addr}',
      es: 'Nuevo: {addr}',
      fr: 'Neuf : {addr}',
      hi: 'नई ज़मीन: {addr}',
      id: 'Baru: {addr}',
      pt: 'Novo: {addr}',
    },
  },
  blocks: {
    stage: { type: 'memory-leak-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
