import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 가장 적은 손질을 찾아 두 파일을 맞춰 갈 때, 어느 걸음이 값을 치르고 어느 걸음이 공짜인가?
 */
export const diagonalIsFreeFacet: FacetJson = {
  id: 'facet:diagonalIsFree',
  title: {
    en: 'Diagonals are free',
    ko: '대각선은 공짜다',
    ja: '対角線はタダ',
    zh: '对角线是免费的',
    ar: 'الأقطار مجانية',
    es: 'Las diagonales son gratis',
    fr: 'Les diagonales sont gratuites',
    hi: 'विकर्ण मुफ़्त हैं',
    id: 'Diagonal itu gratis',
    pt: 'As diagonais são grátis',
  },
  description: {
    en: 'Myers diff pays only to delete or insert a line, and slides for free along equal lines.',
    ko: '마이어스 diff 는 줄을 지우거나 넣을 때만 값을 치르고, 같은 줄을 따라서는 공짜로 미끄러진다.',
    ja: 'Myers diff は行を削除・挿入するときだけコストを払い、同じ行に沿っては無料で滑る。',
    zh: 'Myers diff 只在删除或插入一行时付出代价，沿着相同的行则免费滑过。',
    ar: 'يدفع Myers diff تكلفة فقط عند حذف سطر أو إدراجه، وينزلق مجانًا على الأسطر المتطابقة.',
    es: 'Myers diff solo paga al borrar o insertar una línea y se desliza gratis por las líneas iguales.',
    fr: 'Myers diff ne paie que pour supprimer ou insérer une ligne et glisse gratuitement le long des lignes égales.',
    hi: 'Myers diff केवल पंक्ति हटाने या जोड़ने पर लागत चुकाता है और समान पंक्तियों पर मुफ़्त फिसलता है।',
    id: 'Myers diff hanya membayar saat menghapus atau menyisipkan baris, dan meluncur gratis di sepanjang baris yang sama.',
    pt: 'O Myers diff só paga ao apagar ou inserir uma linha e desliza de graça pelas linhas iguais.',
  },
  algorithm: 'module:diagonalIsFree',
  scene: 'module:diagonalIsFreeScene',
  initialData: {
    type: 'diagonal-is-free',
    a: [
      'let n = 10',
      'let sum = 0',
      'for i from 1 to n',
      '    let sq = i * i',
      '    sum = sum + sq',
      '    show i',
      'show sum',
    ],
    b: [
      'let n = 10',
      'let sum = 0',
      'show n',
      'for i from 1 to n',
      '    let sq = i * i',
      '    sum = sum + sq',
      'show sum',
    ],
    stepMs: 1400,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Start at (0, 0): no line passed yet.',
      ko: '(0, 0) 에서 출발한다. 아직 지나온 줄이 없다.',
      ja: '(0, 0) から出発。まだ通った行はない。',
      zh: '从 (0, 0) 出发：还没有经过任何一行。',
      ar: 'البداية عند (0, 0): لم نمرّ بأي سطر بعد.',
      es: 'Inicio en (0, 0): aún no se ha pasado ninguna línea.',
      fr: 'Départ en (0, 0) : aucune ligne franchie.',
      hi: '(0, 0) से शुरुआत: अभी कोई पंक्ति पार नहीं हुई।',
      id: 'Mulai di (0, 0): belum ada baris yang dilewati.',
      pt: 'Início em (0, 0): nenhuma linha percorrida ainda.',
    },
    'caption.free': {
      en: 'Cost {d}: nothing paid — cells slid for free: {n}',
      ko: '값 {d}: 치른 칸 없이 공짜로 미끄러진 칸: {n}',
      ja: 'コスト {d}：支払いなし — 無料で滑ったマス: {n}',
      zh: '代价 {d}：没有付出 — 免费滑过的格数：{n}',
      ar: 'التكلفة {d}: لا دفع — خانات انزلقت مجانًا: {n}',
      es: 'Coste {d}: nada pagado — casillas deslizadas gratis: {n}',
      fr: 'Coût {d} : rien payé — cases glissées gratuitement : {n}',
      hi: 'लागत {d}: कुछ नहीं चुकाया — मुफ़्त फिसले खाने: {n}',
      id: 'Biaya {d}: tidak ada yang dibayar — kotak meluncur gratis: {n}',
      pt: 'Custo {d}: nada pago — casas deslizadas de graça: {n}',
    },
    'caption.down': {
      en: 'Cost {d}: paid 1 to insert B{row}, then cells slid for free: {n}',
      ko: '값 {d}: 넣음(B{row}) 한 칸에 값 1, 이어 공짜로 미끄러진 칸: {n}',
      ja: 'コスト {d}：B{row} の挿入に 1 を支払い、続いて無料で滑ったマス: {n}',
      zh: '代价 {d}：插入 B{row} 付出 1，接着免费滑过的格数：{n}',
      ar: 'التكلفة {d}: دُفع 1 لإدراج B{row}، ثم خانات انزلقت مجانًا: {n}',
      es: 'Coste {d}: se paga 1 por insertar B{row}, luego casillas deslizadas gratis: {n}',
      fr: 'Coût {d} : 1 payé pour insérer B{row}, puis cases glissées gratuitement : {n}',
      hi: 'लागत {d}: B{row} जोड़ने के लिए 1 चुकाया, फिर मुफ़्त फिसले खाने: {n}',
      id: 'Biaya {d}: bayar 1 untuk menyisipkan B{row}, lalu kotak meluncur gratis: {n}',
      pt: 'Custo {d}: paga 1 para inserir B{row}, depois casas deslizadas de graça: {n}',
    },
    'caption.right': {
      en: 'Cost {d}: paid 1 to delete A{row}, then cells slid for free: {n}',
      ko: '값 {d}: 지움(A{row}) 한 칸에 값 1, 이어 공짜로 미끄러진 칸: {n}',
      ja: 'コスト {d}：A{row} の削除に 1 を支払い、続いて無料で滑ったマス: {n}',
      zh: '代价 {d}：删除 A{row} 付出 1，接着免费滑过的格数：{n}',
      ar: 'التكلفة {d}: دُفع 1 لحذف A{row}، ثم خانات انزلقت مجانًا: {n}',
      es: 'Coste {d}: se paga 1 por borrar A{row}, luego casillas deslizadas gratis: {n}',
      fr: 'Coût {d} : 1 payé pour supprimer A{row}, puis cases glissées gratuitement : {n}',
      hi: 'लागत {d}: A{row} हटाने के लिए 1 चुकाया, फिर मुफ़्त फिसले खाने: {n}',
      id: 'Biaya {d}: bayar 1 untuk menghapus A{row}, lalu kotak meluncur gratis: {n}',
      pt: 'Custo {d}: paga 1 para apagar A{row}, depois casas deslizadas de graça: {n}',
    },
    'caption.end': {
      en: 'Reached ({x}, {y}). Path cost: {d} · free cells: {f}',
      ko: '끝 ({x}, {y}) 에 닿았다. 경로의 값: {d} · 공짜 칸: {f}',
      ja: '({x}, {y}) に到達。経路のコスト: {d} · 無料のマス: {f}',
      zh: '到达 ({x}, {y})。路径代价：{d} · 免费格数：{f}',
      ar: 'الوصول إلى ({x}, {y}). تكلفة المسار: {d} · خانات مجانية: {f}',
      es: 'Llegada a ({x}, {y}). Coste del camino: {d} · casillas gratis: {f}',
      fr: 'Arrivée en ({x}, {y}). Coût du chemin : {d} · cases gratuites : {f}',
      hi: '({x}, {y}) तक पहुँचे। पथ की लागत: {d} · मुफ़्त खाने: {f}',
      id: 'Tiba di ({x}, {y}). Biaya jalur: {d} · kotak gratis: {f}',
      pt: 'Chegou a ({x}, {y}). Custo do caminho: {d} · casas grátis: {f}',
    },
    'label.axisA': {
      en: 'A → right: delete one line',
      ko: 'A → 오른쪽: 한 줄 지움',
      ja: 'A → 右: 1 行削除',
      zh: 'A → 向右：删除一行',
      ar: 'A → يمينًا: حذف سطر',
      es: 'A → derecha: borrar una línea',
      fr: 'A → droite : supprimer une ligne',
      hi: 'A → दाएँ: एक पंक्ति हटाना',
      id: 'A → kanan: hapus satu baris',
      pt: 'A → direita: apagar uma linha',
    },
    'label.axisB': {
      en: 'B ↓ down: insert one line',
      ko: 'B ↓ 아래: 한 줄 넣음',
      ja: 'B ↓ 下: 1 行挿入',
      zh: 'B ↓ 向下：插入一行',
      ar: 'B ↓ لأسفل: إدراج سطر',
      es: 'B ↓ abajo: insertar una línea',
      fr: 'B ↓ bas : insérer une ligne',
      hi: 'B ↓ नीचे: एक पंक्ति जोड़ना',
      id: 'B ↓ bawah: sisipkan satu baris',
      pt: 'B ↓ baixo: inserir uma linha',
    },
    'label.paid': {
      en: 'paid step: cost 1',
      ko: '치른 칸: 값 1',
      ja: '支払うマス: コスト 1',
      zh: '付费一步：代价 1',
      ar: 'خطوة مدفوعة: التكلفة 1',
      es: 'paso pagado: coste 1',
      fr: 'pas payé : coût 1',
      hi: 'चुकाया कदम: लागत 1',
      id: 'langkah berbayar: biaya 1',
      pt: 'passo pago: custo 1',
    },
    'label.free': {
      en: 'free slide: cost 0',
      ko: '공짜 칸: 값 0',
      ja: '無料の滑り: コスト 0',
      zh: '免费滑动：代价 0',
      ar: 'انزلاق مجاني: التكلفة 0',
      es: 'deslizamiento gratis: coste 0',
      fr: 'glissade gratuite : coût 0',
      hi: 'मुफ़्त फिसलन: लागत 0',
      id: 'luncur gratis: biaya 0',
      pt: 'deslize grátis: custo 0',
    },
    'label.cost': {
      en: 'Cost {d}',
      ko: '값 {d}',
      ja: 'コスト {d}',
      zh: '代价 {d}',
      ar: 'التكلفة {d}',
      es: 'Coste {d}',
      fr: 'Coût {d}',
      hi: 'लागत {d}',
      id: 'Biaya {d}',
      pt: 'Custo {d}',
    },
    'label.point': {
      en: '({x}, {y})',
      ko: '({x}, {y})',
      ja: '({x}, {y})',
      zh: '({x}, {y})',
      ar: '({x}, {y})',
      es: '({x}, {y})',
      fr: '({x}, {y})',
      hi: '({x}, {y})',
      id: '({x}, {y})',
      pt: '({x}, {y})',
    },
  },
  blocks: {
    stage: { type: 'diagonal-is-free-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
