import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 방화벽은 한 패킷에 맞는 규칙이 여럿일 때 어느 것을 따르는가.
 *
 * 패킷은 규칙 목록을 위에서부터 한 줄씩 내려가며 맞춰 보고, 처음 맞은 줄에서 멈춘다.
 * 그 아래에 더 알맞은 줄이 있어도 닿지 않는다.
 */
export const ruleMatchOrderFacet: FacetJson = {
  id: 'facet:ruleMatchOrder',
  title: {
    en: 'Firewall rule order',
    ko: '방화벽 규칙의 차례',
    ja: 'ファイアウォールのルール順序',
    zh: '防火墙规则的顺序',
    ar: 'ترتيب قواعد الجدار الناري',
    es: 'Orden de las reglas del cortafuegos',
    fr: 'Ordre des règles du pare-feu',
    hi: 'फ़ायरवॉल नियमों का क्रम',
    id: 'Urutan aturan firewall',
    pt: 'Ordem das regras do firewall',
  },
  description: {
    en: 'A packet walks down the rule list from the top and stops at the first rule that matches.',
    ko: '패킷은 규칙 목록을 위에서부터 내려가며 맞춰 보고, 처음 맞은 규칙에서 멈춘다.',
    ja: 'パケットはルール一覧を上から順に照らし合わせ、最初に一致したルールで止まる。',
    zh: '数据包从上往下逐条比对规则列表，在第一条匹配的规则处停下。',
    ar: 'تنزل الحزمة في قائمة القواعد من الأعلى وتتوقف عند أول قاعدة تطابقها.',
    es: 'Un paquete recorre la lista de reglas desde arriba y se detiene en la primera que coincide.',
    fr: 'Un paquet descend la liste des règles depuis le haut et s’arrête à la première qui correspond.',
    hi: 'पैकेट नियम सूची में ऊपर से नीचे मिलान करता है और पहले मेल खाने वाले नियम पर रुक जाता है।',
    id: 'Paket menuruni daftar aturan dari atas dan berhenti pada aturan pertama yang cocok.',
    pt: 'Um pacote desce a lista de regras a partir do topo e para na primeira regra que corresponde.',
  },
  algorithm: 'module:ruleMatchOrder',
  scene: 'module:ruleMatchOrderScene',
  initialData: {
    type: 'rule-match-order',
    stepMs: 900,
    rules: [
      { action: 'allow', proto: 'tcp', src: 'any', dst: '10.0.0.0/24', port: '443' },
      { action: 'deny', proto: 'tcp', src: '203.0.113.0/24', dst: 'any', port: 'any' },
      { action: 'allow', proto: 'tcp', src: 'any', dst: '10.0.0.5/32', port: '22' },
      { action: 'deny', proto: 'any', src: 'any', dst: 'any', port: 'any' },
    ],
    packets: [
      { id: 'p1', proto: 'tcp', src: '203.0.113.9', dst: '10.0.0.5', port: 443 },
      { id: 'p2', proto: 'tcp', src: '203.0.113.9', dst: '10.0.0.5', port: 22 },
      { id: 'p3', proto: 'tcp', src: '198.51.100.4', dst: '10.0.0.5', port: 22 },
      { id: 'p4', proto: 'tcp', src: '198.51.100.4', dst: '10.0.0.9', port: 25 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'col.action': {
      en: 'Action',
      ko: '동작',
      ja: '動作',
      zh: '动作',
      ar: 'الإجراء',
      es: 'Acción',
      fr: 'Action',
      hi: 'कार्रवाई',
      id: 'Tindakan',
      pt: 'Ação',
    },
    'field.proto': {
      en: 'Protocol',
      ko: '프로토콜',
      ja: 'プロトコル',
      zh: '协议',
      ar: 'البروتوكول',
      es: 'Protocolo',
      fr: 'Protocole',
      hi: 'प्रोटोकॉल',
      id: 'Protokol',
      pt: 'Protocolo',
    },
    'field.src': {
      en: 'Source',
      ko: '보낸 주소',
      ja: '送信元',
      zh: '源地址',
      ar: 'المصدر',
      es: 'Origen',
      fr: 'Source',
      hi: 'स्रोत',
      id: 'Sumber',
      pt: 'Origem',
    },
    'field.dst': {
      en: 'Destination',
      ko: '받는 주소',
      ja: '宛先',
      zh: '目的地址',
      ar: 'الوجهة',
      es: 'Destino',
      fr: 'Destination',
      hi: 'गंतव्य',
      id: 'Tujuan',
      pt: 'Destino',
    },
    'field.port': {
      en: 'Port',
      ko: '포트',
      ja: 'ポート',
      zh: '端口',
      ar: 'المنفذ',
      es: 'Puerto',
      fr: 'Port',
      hi: 'पोर्ट',
      id: 'Port',
      pt: 'Porta',
    },
    'label.allow': {
      en: 'allow',
      ko: '허용',
      ja: '許可',
      zh: '允许',
      ar: 'سماح',
      es: 'permitir',
      fr: 'autoriser',
      hi: 'अनुमति',
      id: 'izinkan',
      pt: 'permitir',
    },
    'label.deny': {
      en: 'deny',
      ko: '차단',
      ja: '拒否',
      zh: '拒绝',
      ar: 'حظر',
      es: 'bloquear',
      fr: 'bloquer',
      hi: 'रोक',
      id: 'tolak',
      pt: 'bloquear',
    },
    'caption.start': {
      en: 'Rules: {r} · Packets: {p}',
      ko: '규칙: {r} · 패킷: {p}',
      ja: 'ルール: {r} · パケット: {p}',
      zh: '规则: {r} · 数据包: {p}',
      ar: 'القواعد: {r} · الحزم: {p}',
      es: 'Reglas: {r} · Paquetes: {p}',
      fr: 'Règles : {r} · Paquets : {p}',
      hi: 'नियम: {r} · पैकेट: {p}',
      id: 'Aturan: {r} · Paket: {p}',
      pt: 'Regras: {r} · Pacotes: {p}',
    },
    'caption.miss': {
      en: 'Rule {n} × {pkt}: {field} differs — down one row.',
      ko: '규칙 {n} × {pkt}: {field} 칸이 다르다 — 한 줄 내려간다.',
      ja: 'ルール {n} × {pkt}: {field} が違う — 一行下へ。',
      zh: '规则 {n} × {pkt}: {field} 不同 — 下移一行。',
      ar: 'القاعدة {n} × {pkt}: {field} مختلف — انزل سطرًا.',
      es: 'Regla {n} × {pkt}: {field} no coincide — baja una fila.',
      fr: 'Règle {n} × {pkt} : {field} diffère — une ligne plus bas.',
      hi: 'नियम {n} × {pkt}: {field} अलग है — एक पंक्ति नीचे।',
      id: 'Aturan {n} × {pkt}: {field} berbeda — turun satu baris.',
      pt: 'Regra {n} × {pkt}: {field} difere — desce uma linha.',
    },
    'caption.match': {
      en: 'Rule {n} × {pkt}: all fields match → {action}. Rows below are not reached.',
      ko: '규칙 {n} × {pkt}: 모든 칸이 맞다 → {action}. 아래 줄에는 닿지 않는다.',
      ja: 'ルール {n} × {pkt}: すべての欄が一致 → {action}。下の行には届かない。',
      zh: '规则 {n} × {pkt}: 所有字段匹配 → {action}。下面的行不再比对。',
      ar: 'القاعدة {n} × {pkt}: كل الحقول متطابقة ← {action}. لا يُوصَل إلى الأسطر التالية.',
      es: 'Regla {n} × {pkt}: todos los campos coinciden → {action}. Las filas de abajo no se alcanzan.',
      fr: 'Règle {n} × {pkt} : tous les champs correspondent → {action}. Les lignes du dessous ne sont pas atteintes.',
      hi: 'नियम {n} × {pkt}: सभी खाने मेल खाते हैं → {action}। नीचे की पंक्तियों तक नहीं पहुँचता।',
      id: 'Aturan {n} × {pkt}: semua kolom cocok → {action}. Baris di bawahnya tidak tercapai.',
      pt: 'Regra {n} × {pkt}: todos os campos correspondem → {action}. As linhas abaixo não são alcançadas.',
    },
    'caption.matchLast': {
      en: 'Rule {n} × {pkt}: all fields match → {action}.',
      ko: '규칙 {n} × {pkt}: 모든 칸이 맞다 → {action}.',
      ja: 'ルール {n} × {pkt}: すべての欄が一致 → {action}。',
      zh: '规则 {n} × {pkt}: 所有字段匹配 → {action}。',
      ar: 'القاعدة {n} × {pkt}: كل الحقول متطابقة ← {action}.',
      es: 'Regla {n} × {pkt}: todos los campos coinciden → {action}.',
      fr: 'Règle {n} × {pkt} : tous les champs correspondent → {action}.',
      hi: 'नियम {n} × {pkt}: सभी खाने मेल खाते हैं → {action}।',
      id: 'Aturan {n} × {pkt}: semua kolom cocok → {action}.',
      pt: 'Regra {n} × {pkt}: todos os campos correspondem → {action}.',
    },
  },
  blocks: {
    stage: { type: 'rule-match-order-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
