/**
 * @piece 먼저 줄에 선 타이머 콜백과 뒤에 등록된 then 콜백 가운데 무엇이 먼저 도는가?
 * @notation native — setTimeout 과 Promise.then 의 차례가 곧 주장이다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { Statement } from './algorithm.js';

const code: string[] = [
  "console.log('A');",
  "setTimeout(() => console.log('B'), 0);",
  'Promise.resolve()',
  "  .then(() => console.log('C'))",
  "  .then(() => console.log('D'));",
  "console.log('E');",
];

const statements: Statement[] = [
  { op: 'log', id: 'A', line: 1 },
  { op: 'timeout', id: 'B', delay: 0, line: 2 },
  { op: 'thenChain', ids: ['C', 'D'], lines: [3, 4, 5], callbackLines: [4, 5] },
  { op: 'log', id: 'E', line: 6 },
];

export const microtaskCutsInFacet: FacetJson = {
  id: 'facet:microtaskCutsIn',
  title: {
    en: 'Microtasks cut in line',
    ko: '마이크로태스크가 줄을 가로챈다',
    ja: 'マイクロタスクが列に割り込む',
    zh: '微任务插队',
    ar: 'المهام الدقيقة تتجاوز الطابور',
    es: 'Las microtareas se cuelan en la fila',
    fr: 'Les microtâches passent devant la file',
    hi: 'माइक्रोटास्क कतार में आगे निकल जाते हैं',
    id: 'Microtask menyela antrean',
    pt: 'As microtarefas furam a fila',
  },
  description: {
    en: 'A timer callback already sits in the task queue, but a promise chain registered after it finishes first — twice — before the timer gets its turn.',
    ko: '타이머 콜백이 이미 태스크 줄에 서 있지만, 그 뒤에 등록된 약속 사슬이 두 번이나 먼저 끝나고 나서야 타이머의 차례가 온다.',
    ja: 'タイマーのコールバックはすでにタスクキューに並んでいるが、その後に登録されたプロミスの連鎖が二回とも先に終わってから、ようやくタイマーの番が来る。',
    zh: '定时器回调已经排在任务队列里,但在它之后注册的 Promise 链却先执行了两次,定时器才轮到自己。',
    ar: 'استدعاء المؤقّت واقف بالفعل في طابور المهام، لكن سلسلة الوعود المسجَّلة بعده تنتهي أولاً - مرتين - قبل أن يأتي دور المؤقّت.',
    es: 'Un callback de temporizador ya está en la cola de tareas, pero una cadena de promesas registrada después termina primero — dos veces — antes de que le llegue el turno al temporizador.',
    fr: "Un callback de minuteur attend déjà dans la file des tâches, mais une chaîne de promesses enregistrée après lui se termine d'abord — deux fois — avant que son tour n'arrive.",
    hi: 'एक टाइमर कॉलबैक पहले से ही टास्क कतार में बैठा है, लेकिन उसके बाद पंजीकृत प्रॉमिस चेन पहले - दो बार - पूरी होती है, तब जाकर टाइमर की बारी आती है।',
    id: 'Callback timer sudah berada di antrean tugas, tetapi rantai promise yang didaftarkan setelahnya justru selesai lebih dulu — dua kali — sebelum giliran timer tiba.',
    pt: 'Um callback de temporizador já está na fila de tarefas, mas uma cadeia de promessas registrada depois dele termina primeiro — duas vezes — antes que chegue a vez do temporizador.',
  },
  algorithm: 'module:microtaskCutsIn',
  scene: 'module:microtaskCutsInScene',
  initialData: {
    type: 'microtaskCutsIn',
    code,
    statements,
    stepMs: 1400,
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'microtask-cuts-in-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'label.code': {
      en: 'Code',
      ko: '코드',
      ja: 'コード',
      zh: '代码',
      ar: 'الشيفرة',
      es: 'Código',
      fr: 'Code',
      hi: 'कोड',
      id: 'Kode',
      pt: 'Código',
    },
    'label.taskQueue': {
      en: 'Task queue',
      ko: '태스크 줄',
      ja: 'タスクキュー',
      zh: '任务队列',
      ar: 'طابور المهام',
      es: 'Cola de tareas',
      fr: 'File des tâches',
      hi: 'टास्क कतार',
      id: 'Antrean tugas',
      pt: 'Fila de tarefas',
    },
    'label.microQueue': {
      en: 'Microtask queue',
      ko: '마이크로태스크 줄',
      ja: 'マイクロタスクキュー',
      zh: '微任务队列',
      ar: 'طابور المهام الدقيقة',
      es: 'Cola de microtareas',
      fr: 'File des microtâches',
      hi: 'माइक्रोटास्क कतार',
      id: 'Antrean microtask',
      pt: 'Fila de microtarefas',
    },
    'label.waiting': {
      en: 'Waiting on a promise',
      ko: '약속을 기다리는 콜백',
      ja: 'プロミス待ちのコールバック',
      zh: '等待约定的回调',
      ar: 'بانتظار وعد',
      es: 'Esperando una promesa',
      fr: "En attente d'une promesse",
      hi: 'प्रॉमिस की प्रतीक्षा में',
      id: 'Menunggu promise',
      pt: 'Aguardando uma promessa',
    },
    'label.output': {
      en: 'Console output',
      ko: '콘솔 출력',
      ja: 'コンソール出力',
      zh: '控制台输出',
      ar: 'مخرجات الطرفية',
      es: 'Salida de consola',
      fr: 'Sortie console',
      hi: 'कंसोल आउटपुट',
      id: 'Output konsol',
      pt: 'Saída do console',
    },
    'caption.init': {
      en: 'Nothing has run yet. Both queues are empty.',
      ko: '아직 아무것도 실행되지 않았다. 두 줄이 모두 비어 있다.',
      ja: 'まだ何も実行されていない。どちらのキューも空だ。',
      zh: '还没有任何代码执行。两个队列都是空的。',
      ar: 'لم يُنفَّذ شيء بعد. كلا الطابورين فارغان.',
      es: 'Todavía no se ha ejecutado nada. Ambas colas están vacías.',
      fr: 'Rien ne s’est encore exécuté. Les deux files sont vides.',
      hi: 'अभी तक कुछ भी नहीं चला है। दोनों कतारें खाली हैं।',
      id: 'Belum ada yang berjalan. Kedua antrean masih kosong.',
      pt: 'Nada foi executado ainda. As duas filas estão vazias.',
    },
    'caption.log': {
      en: 'A synchronous log adds a value to the output: {id}',
      ko: '동기 로그가 출력에 값을 더한다: {id}',
      ja: '同期的なログが出力に値を加える: {id}',
      zh: '一次同步日志把值加进输出: {id}',
      ar: 'سجل متزامن يضيف قيمة إلى المخرجات: {id}',
      es: 'Un log síncrono añade un valor a la salida: {id}',
      fr: 'Un log synchrone ajoute une valeur à la sortie : {id}',
      hi: 'एक सिंक्रोनस लॉग आउटपुट में मान जोड़ता है: {id}',
      id: 'Log sinkron menambahkan nilai ke output: {id}',
      pt: 'Um log síncrono adiciona um valor à saída: {id}',
    },
    'caption.scheduleTimer': {
      en: 'The timer callback is already due, so it joins the back of the task queue: {id}',
      ko: '타이머 콜백의 만기가 이미 지나 태스크 줄 끝에 선다: {id}',
      ja: 'タイマーのコールバックはすでに満了しているので、タスクキューの末尾に並ぶ: {id}',
      zh: '定时器的回调已经到期,于是排到任务队列末尾: {id}',
      ar: 'استحقاق استدعاء المؤقّت قد حان بالفعل، فينضم إلى نهاية طابور المهام: {id}',
      es: 'El callback del temporizador ya venció, así que se une al final de la cola de tareas: {id}',
      fr: 'Le délai du minuteur est déjà écoulé, il rejoint donc la fin de la file des tâches : {id}',
      hi: 'टाइमर के कॉलबैक की अवधि पहले ही पूरी हो चुकी है, इसलिए यह टास्क कतार के अंत में जुड़ता है: {id}',
      id: 'Callback timer sudah jatuh tempo, jadi ia bergabung di akhir antrean tugas: {id}',
      pt: 'O callback do temporizador já venceu, então ele entra no final da fila de tarefas: {id}',
    },
    'caption.scheduleChain': {
      en: 'The promise is already settled, so its first callback joins the microtask queue right away: {first}. The next callback waits for that promise instead of queueing: {next}',
      ko: '이미 이루어진 약속이라 첫 콜백은 곧장 마이크로태스크 줄에 선다: {first}. 다음 콜백은 줄에 서는 대신 그 약속을 기다린다: {next}',
      ja: 'すでに解決済みのプロミスなので、最初のコールバックはすぐにマイクロタスクキューに並ぶ: {first}。次のコールバックは列に並ばず、そのプロミスを待つ: {next}',
      zh: '这个约定已经完成,所以第一个回调立刻排进微任务队列: {first}。下一个回调不排队,而是等待那个约定: {next}',
      ar: 'الوعد محقَّق بالفعل، فينضم أول استدعاء إلى طابور المهام الدقيقة فورًا: {first}. أما الاستدعاء التالي فينتظر ذلك الوعد بدل الوقوف في الطابور: {next}',
      es: 'La promesa ya está resuelta, así que su primer callback se une a la cola de microtareas de inmediato: {first}. El siguiente callback espera esa promesa en vez de encolarse: {next}',
      fr: 'La promesse est déjà tenue, donc son premier callback rejoint aussitôt la file des microtâches : {first}. Le callback suivant attend cette promesse au lieu de faire la queue : {next}',
      hi: 'प्रॉमिस पहले से ही पूरा हो चुका है, इसलिए उसका पहला कॉलबैक तुरंत माइक्रोटास्क कतार में शामिल होता है: {first}। अगला कॉलबैक कतार में लगने के बजाय उसी प्रॉमिस की प्रतीक्षा करता है: {next}',
      id: 'Promise sudah terselesaikan, jadi callback pertamanya langsung bergabung ke antrean microtask: {first}. Callback berikutnya menunggu promise itu, bukan ikut mengantre: {next}',
      pt: 'A promessa já está resolvida, então seu primeiro callback entra na fila de microtarefas imediatamente: {first}. O próximo callback espera essa promessa em vez de entrar na fila: {next}',
    },
    'caption.runMicrotaskPromote': {
      en: 'The stack is empty, so the front of the microtask queue runs: {id}. Finishing it settles the next promise, and its callback joins the queue: {next}',
      ko: '스택이 비어 마이크로태스크 줄 앞머리가 실행된다: {id}. 끝나며 다음 약속이 풀려 그 콜백이 줄에 선다: {next}',
      ja: 'スタックが空になったので、マイクロタスクキューの先頭が実行される: {id}。それが終わると次のプロミスが解決し、そのコールバックがキューに並ぶ: {next}',
      zh: '调用栈已空,于是微任务队列的最前面开始执行: {id}。它一结束就让下一个约定完成,其回调随即排进队列: {next}',
      ar: 'المكدّس فارغ، فيُنفَّذ مقدّمة طابور المهام الدقيقة: {id}. وعند انتهائه يتحقّق الوعد التالي، فينضم استدعاؤه إلى الطابور: {next}',
      es: 'La pila está vacía, así que se ejecuta el frente de la cola de microtareas: {id}. Al terminar, se resuelve la siguiente promesa y su callback se une a la cola: {next}',
      fr: 'La pile est vide, donc la tête de la file des microtâches s’exécute : {id}. Une fois terminée, la promesse suivante est tenue et son callback rejoint la file : {next}',
      hi: 'स्टैक खाली है, इसलिए माइक्रोटास्क कतार का अगला भाग चलता है: {id}। इसके पूरा होते ही अगला प्रॉमिस पूरा होता है, और उसका कॉलबैक कतार में जुड़ जाता है: {next}',
      id: 'Stack kosong, jadi bagian depan antrean microtask berjalan: {id}. Setelah selesai, promise berikutnya terselesaikan dan callback-nya bergabung ke antrean: {next}',
      pt: 'A pilha está vazia, então a frente da fila de microtarefas executa: {id}. Ao terminar, a próxima promessa se resolve e seu callback entra na fila: {next}',
    },
    'caption.runMicrotaskPlain': {
      en: 'The stack is empty, so the front of the microtask queue runs: {id}',
      ko: '스택이 비어 마이크로태스크 줄 앞머리가 실행된다: {id}',
      ja: 'スタックが空になったので、マイクロタスクキューの先頭が実行される: {id}',
      zh: '调用栈已空,于是微任务队列的最前面开始执行: {id}',
      ar: 'المكدّس فارغ، فيُنفَّذ مقدّمة طابور المهام الدقيقة: {id}',
      es: 'La pila está vacía, así que se ejecuta el frente de la cola de microtareas: {id}',
      fr: 'La pile est vide, donc la tête de la file des microtâches s’exécute : {id}',
      hi: 'स्टैक खाली है, इसलिए माइक्रोटास्क कतार का अगला भाग चलता है: {id}',
      id: 'Stack kosong, jadi bagian depan antrean microtask berjalan: {id}',
      pt: 'A pilha está vazia, então a frente da fila de microtarefas executa: {id}',
    },
    'caption.runTask': {
      en: 'The microtask queue is empty, so the front of the task queue finally runs: {id}',
      ko: '마이크로태스크 줄이 비어서야 태스크 줄 앞머리가 실행된다: {id}',
      ja: 'マイクロタスクキューが空になり、ようやくタスクキューの先頭が実行される: {id}',
      zh: '微任务队列已空,任务队列的最前面终于开始执行: {id}',
      ar: 'طابور المهام الدقيقة فارغ الآن، فيُنفَّذ أخيرًا مقدّمة طابور المهام: {id}',
      es: 'La cola de microtareas está vacía, así que por fin se ejecuta el frente de la cola de tareas: {id}',
      fr: 'La file des microtâches est vide, la tête de la file des tâches s’exécute enfin : {id}',
      hi: 'माइक्रोटास्क कतार खाली होते ही आख़िरकार टास्क कतार का अगला भाग चलता है: {id}',
      id: 'Antrean microtask sudah kosong, akhirnya bagian depan antrean tugas berjalan: {id}',
      pt: 'A fila de microtarefas está vazia, então finalmente a frente da fila de tarefas executa: {id}',
    },
  },
};
