/**
 * @piece 문서를 다 읽었는데 스타일시트가 아직 오지 않았다면, 브라우저는 그동안
 * 화면에 무엇을 그리는가.
 *
 * @notation native — 주장이 `<link rel="stylesheet">` 가 렌더를 막는 브라우저의
 * 동작 그 자체다. 문서 줄의 코드 글자는 번역하지 않는 자료로 `initialData` 에 둔다.
 */
import type { FacetJson } from '@ffacet/core';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const styleBlocksPaintFacet: FacetJson = {
  id: 'facet:styleBlocksPaint',
  title: {
    en: 'Style Blocks Paint',
    ko: '스타일이 그리기를 막는다',
    ja: 'スタイルが描画を止める',
    zh: '样式阻塞绘制',
    ar: 'التنسيق يحجب الرسم',
    es: 'El estilo bloquea el pintado',
    fr: "Le style bloque l'affichage",
    hi: 'स्टाइल पेंट को रोकता है',
    id: 'Gaya menghalangi pengecatan',
    pt: 'O estilo bloqueia a pintura',
  },
  description: {
    en: 'The DOM finishes growing, but the screen stays blank until the stylesheet arrives — then everything appears at once.',
    ko: 'DOM 은 다 자라지만, 스타일시트가 도착할 때까지 화면은 비어 있다가 — 그 순간 한꺼번에 나타난다.',
    ja: 'DOM は成長し終えるが、スタイルシートが届くまで画面は空のままで — その瞬間に一斉に現れる。',
    zh: 'DOM 已经长成，但屏幕保持空白，直到样式表到达 — 那一刻，一切同时出现。',
    ar: 'تكتمل شجرة DOM لكن الشاشة تبقى فارغة حتى تصل ورقة الأنماط — عندها يظهر كل شيء دفعة واحدة.',
    es: 'El DOM termina de crecer, pero la pantalla permanece en blanco hasta que llega la hoja de estilos — entonces todo aparece de golpe.',
    fr: "Le DOM finit de grandir, mais l'écran reste vide jusqu'à l'arrivée de la feuille de style — alors tout apparaît d'un coup.",
    hi: 'DOM बढ़ना पूरा कर लेता है, पर स्टाइलशीट के पहुँचने तक स्क्रीन खाली रहती है — फिर सब कुछ एक साथ दिखता है।',
    id: 'DOM selesai tumbuh, tapi layar tetap kosong sampai lembar gaya tiba — lalu semuanya muncul sekaligus.',
    pt: 'O DOM termina de crescer, mas a tela permanece em branco até que a folha de estilos chegue — então tudo aparece de uma vez.',
  },
  algorithm: 'module:styleBlocksPaint',
  scene: 'module:styleBlocksPaintScene',
  initialData: {
    type: 'style-blocks-paint',
    lines: [
      { id: 'link', kind: 'link', code: '<link rel="stylesheet" href="site.css">', src: 'site.css' },
      { id: 'h1', kind: 'text', code: '<h1>Today</h1>', text: 'Today', heading: true },
      { id: 'p1', kind: 'text', code: '<p>First story</p>', text: 'First story' },
      { id: 'p2', kind: 'text', code: '<p>Second story</p>', text: 'Second story' },
      { id: 'p3', kind: 'text', code: '<p>Third story</p>', text: 'Third story' },
    ],
    cssDurationMs: 300,
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Five lines wait to be read. The screen is blank.',
      ko: '다섯 줄이 읽히기를 기다린다. 화면은 비어 있다.',
      ja: '5行が読まれるのを待っている。画面は空だ。',
      zh: '五行等待被读取。屏幕是空的。',
      ar: 'خمسة أسطر تنتظر أن تُقرأ. الشاشة فارغة.',
      es: 'Cinco líneas esperan ser leídas. La pantalla está en blanco.',
      fr: "Cinq lignes attendent d'être lues. L'écran est vide.",
      hi: 'पाँच पंक्तियाँ पढ़े जाने की प्रतीक्षा में हैं। स्क्रीन खाली है।',
      id: 'Lima baris menunggu dibaca. Layar masih kosong.',
      pt: 'Cinco linhas aguardam para ser lidas. A tela está em branco.',
    },
    'caption.readLine': {
      en: '{code} read.',
      ko: '{code} 읽음.',
      ja: '{code} を読んだ。',
      zh: '{code} 已读取。',
      ar: 'تمت قراءة {code}.',
      es: '{code} leída.',
      fr: '{code} lue.',
      hi: '{code} पढ़ी गई।',
      id: '{code} dibaca.',
      pt: '{code} lida.',
    },
    'caption.readLineRequestsCss': {
      en: '{code} read — {resource} requested.',
      ko: '{code} 읽음 — {resource} 요청.',
      ja: '{code} を読んだ — {resource} を要求。',
      zh: '{code} 已读取 — 已请求 {resource}。',
      ar: 'تمت قراءة {code} — تم طلب {resource}.',
      es: '{code} leída — {resource} solicitado.',
      fr: '{code} lue — {resource} demandé.',
      hi: '{code} पढ़ी गई — {resource} का अनुरोध किया गया।',
      id: '{code} dibaca — {resource} diminta.',
      pt: '{code} lida — {resource} solicitado.',
    },
    'caption.readLineDomComplete': {
      en: '{code} read. The DOM is complete, but the screen stays blank.',
      ko: '{code} 읽음. DOM 은 다 됐지만 화면은 그대로 비어 있다.',
      ja: '{code} を読んだ。DOM は完成したが、画面はまだ空のままだ。',
      zh: '{code} 已读取。DOM 已完成，但屏幕仍然空白。',
      ar: 'تمت قراءة {code}. اكتمل DOM لكن الشاشة تبقى فارغة.',
      es: '{code} leída. El DOM está completo, pero la pantalla sigue en blanco.',
      fr: "{code} lue. Le DOM est complet, mais l'écran reste vide.",
      hi: '{code} पढ़ी गई। DOM पूरा हो गया, पर स्क्रीन अब भी खाली है।',
      id: '{code} dibaca. DOM sudah lengkap, tapi layar tetap kosong.',
      pt: '{code} lida. O DOM está completo, mas a tela continua em branco.',
    },
    'caption.arrived': {
      en: '{resource} arrived.',
      ko: '{resource} 도착.',
      ja: '{resource} が届いた。',
      zh: '{resource} 已到达。',
      ar: 'وصل {resource}.',
      es: '{resource} llegó.',
      fr: '{resource} est arrivé.',
      hi: '{resource} पहुँच गया।',
      id: '{resource} tiba.',
      pt: '{resource} chegou.',
    },
    'caption.firstPaint': {
      en: 'First paint. The screen was blank for {ms}ms.',
      ko: '첫 장. 화면은 {ms}ms 동안 비어 있었다.',
      ja: '初回描画。画面は{ms}ms間、空のままだった。',
      zh: '首次绘制。屏幕空白了 {ms}ms。',
      ar: 'الرسم الأول. بقيت الشاشة فارغة لمدة {ms}ms.',
      es: 'Primer pintado. La pantalla estuvo en blanco durante {ms}ms.',
      fr: "Premier affichage. L'écran est resté vide pendant {ms}ms.",
      hi: 'पहला पेंट। स्क्रीन {ms}ms तक खाली रही।',
      id: 'Cat pertama. Layar kosong selama {ms}ms.',
      pt: 'Primeira pintura. A tela ficou em branco por {ms}ms.',
    },
    'label.document': {
      en: 'Document',
      ko: '문서',
      ja: '文書',
      zh: '文档',
      ar: 'المستند',
      es: 'Documento',
      fr: 'Document',
      hi: 'दस्तावेज़',
      id: 'Dokumen',
      pt: 'Documento',
    },
    'label.screen': {
      en: 'Screen',
      ko: '화면',
      ja: '画面',
      zh: '屏幕',
      ar: 'الشاشة',
      es: 'Pantalla',
      fr: 'Écran',
      hi: 'स्क्रीन',
      id: 'Layar',
      pt: 'Tela',
    },
    'label.now': {
      en: 'Now: {ms}ms',
      ko: '지금: {ms}ms',
      ja: '現在: {ms}ms',
      zh: '现在: {ms}ms',
      ar: 'الآن: {ms}ms',
      es: 'Ahora: {ms}ms',
      fr: 'Maintenant : {ms}ms',
      hi: 'अभी: {ms}ms',
      id: 'Sekarang: {ms}ms',
      pt: 'Agora: {ms}ms',
    },
    'label.waiting': {
      en: 'Blocked so far: {ms}ms',
      ko: '막힌 지: {ms}ms',
      ja: '止まってから: {ms}ms',
      zh: '已阻塞: {ms}ms',
      ar: 'محظور منذ: {ms}ms',
      es: 'Bloqueado desde hace: {ms}ms',
      fr: 'Bloqué depuis : {ms}ms',
      hi: 'रुके हुए: {ms}ms',
      id: 'Terhambat sejak: {ms}ms',
      pt: 'Bloqueado há: {ms}ms',
    },
    'label.waited': {
      en: 'Blocked for: {ms}ms',
      ko: '막힌 시간: {ms}ms',
      ja: '止まっていた時間: {ms}ms',
      zh: '阻塞了: {ms}ms',
      ar: 'مدة الحظر: {ms}ms',
      es: 'Bloqueado durante: {ms}ms',
      fr: 'Bloqué pendant : {ms}ms',
      hi: 'रुकावट: {ms}ms',
      id: 'Terhambat selama: {ms}ms',
      pt: 'Bloqueado por: {ms}ms',
    },
  },
  blocks: {
    stage: { type: 'style-blocks-paint-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
