import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: `count = count + 1` 한 줄은 CPU 에서 몇 걸음으로 실행되는가.
 */
export const nonAtomicIncrementFacet: FacetJson = {
  id: 'facet:nonAtomicIncrement',
  title: {
    en: 'Non-atomic increment',
    ko: '원자적이지 않은 더하기',
    ja: '非アトミックなインクリメント',
    zh: '非原子的自增',
    ar: 'زيادة غير ذرية',
    es: 'Incremento no atómico',
    fr: 'Incrément non atomique',
    hi: 'गैर-परमाणु वृद्धि',
    id: 'Penambahan non-atomik',
    pt: 'Incremento não atômico',
  },
  description: {
    en: 'How many steps does the single line count = count + 1 take on the CPU?',
    ko: 'count = count + 1 한 줄은 CPU 에서 몇 걸음으로 실행되는가?',
    ja: 'count = count + 1 という一行は、CPU では何ステップで実行されるのか?',
    zh: 'count = count + 1 这一行在 CPU 上要分几步执行?',
    ar: 'كم خطوة يستغرق السطر الواحد count = count + 1 على المعالج؟',
    es: '¿En cuántos pasos ejecuta la CPU la línea única count = count + 1?',
    fr: 'En combien d’étapes le CPU exécute-t-il la seule ligne count = count + 1 ?',
    hi: 'एक पंक्ति count = count + 1 CPU पर कितने चरणों में चलती है?',
    id: 'Berapa langkah yang dibutuhkan CPU untuk satu baris count = count + 1?',
    pt: 'Em quantos passos a CPU executa a única linha count = count + 1?',
  },
  algorithm: 'module:nonAtomicIncrement',
  scene: 'module:nonAtomicIncrementScene',
  initialData: {
    type: 'non-atomic-increment',
    stepMs: 1600,
    thread: 'A',
    memory: 'count',
    register: 'r',
    start: 41,
    line: 'count = count + 1',
    steps: ['let r = count', 'r = r + 1', 'count = r'],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'non-atomic-increment-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.line': {
      en: 'One line of code, about to run.',
      ko: '곧 실행할 코드 한 줄.',
      ja: 'これから実行するコード一行。',
      zh: '即将执行的一行代码。',
      ar: 'سطر واحد من الشيفرة على وشك التنفيذ.',
      es: 'Una línea de código a punto de ejecutarse.',
      fr: 'Une ligne de code sur le point de s’exécuter.',
      hi: 'कोड की एक पंक्ति, चलने ही वाली है।',
      id: 'Satu baris kode yang akan dijalankan.',
      pt: 'Uma linha de código prestes a ser executada.',
    },
    'caption.unfold': {
      en: 'The CPU runs it as separate steps. Steps: {n} · Gaps: {g}',
      ko: 'CPU 는 이 줄을 따로따로의 걸음으로 실행한다. 걸음: {n} · 틈: {g}',
      ja: 'CPU はこれを別々のステップとして実行する。ステップ: {n} · すき間: {g}',
      zh: 'CPU 把它拆成几个独立的步骤执行。步骤: {n} · 间隙: {g}',
      ar: 'ينفّذه المعالج على شكل خطوات منفصلة. الخطوات: {n} · الفجوات: {g}',
      es: 'La CPU lo ejecuta en pasos separados. Pasos: {n} · Huecos: {g}',
      fr: 'Le CPU l’exécute en étapes séparées. Étapes : {n} · Interstices : {g}',
      hi: 'CPU इसे अलग-अलग चरणों में चलाता है। चरण: {n} · अंतराल: {g}',
      id: 'CPU menjalankannya sebagai langkah-langkah terpisah. Langkah: {n} · Celah: {g}',
      pt: 'A CPU a executa em passos separados. Passos: {n} · Brechas: {g}',
    },
    'caption.load': {
      en: 'Read: the memory value is copied into the register. Memory: {m} · Register: {r}',
      ko: '읽기 — 메모리의 값을 레지스터로 베낀다. 메모리: {m} · 레지스터: {r}',
      ja: '読み込み — メモリの値をレジスタに写す。メモリ: {m} · レジスタ: {r}',
      zh: '读取 — 把内存中的值复制到寄存器。内存: {m} · 寄存器: {r}',
      ar: 'قراءة: تُنسخ قيمة الذاكرة إلى السجل. الذاكرة: {m} · السجل: {r}',
      es: 'Leer: el valor de memoria se copia al registro. Memoria: {m} · Registro: {r}',
      fr: 'Lire : la valeur en mémoire est copiée dans le registre. Mémoire : {m} · Registre : {r}',
      hi: 'पढ़ना: मेमोरी का मान रजिस्टर में कॉपी होता है। मेमोरी: {m} · रजिस्टर: {r}',
      id: 'Baca: nilai memori disalin ke register. Memori: {m} · Register: {r}',
      pt: 'Ler: o valor da memória é copiado para o registrador. Memória: {m} · Registrador: {r}',
    },
    'caption.add': {
      en: 'Add: only the register changes. Memory: {m} · Register: {r}',
      ko: '더하기 — 레지스터만 바뀐다. 메모리: {m} · 레지스터: {r}',
      ja: '加算 — 変わるのはレジスタだけ。メモリ: {m} · レジスタ: {r}',
      zh: '相加 — 只有寄存器改变。内存: {m} · 寄存器: {r}',
      ar: 'جمع: يتغيّر السجل وحده. الذاكرة: {m} · السجل: {r}',
      es: 'Sumar: solo cambia el registro. Memoria: {m} · Registro: {r}',
      fr: 'Ajouter : seul le registre change. Mémoire : {m} · Registre : {r}',
      hi: 'जोड़ना: केवल रजिस्टर बदलता है। मेमोरी: {m} · रजिस्टर: {r}',
      id: 'Tambah: hanya register yang berubah. Memori: {m} · Register: {r}',
      pt: 'Somar: só o registrador muda. Memória: {m} · Registrador: {r}',
    },
    'caption.store': {
      en: 'Write: the register value is copied back to memory. Memory: {m} · Register: {r}',
      ko: '쓰기 — 레지스터의 값을 메모리로 되돌려 쓴다. 메모리: {m} · 레지스터: {r}',
      ja: '書き込み — レジスタの値をメモリへ書き戻す。メモリ: {m} · レジスタ: {r}',
      zh: '写回 — 把寄存器的值写回内存。内存: {m} · 寄存器: {r}',
      ar: 'كتابة: تُنسخ قيمة السجل عائدةً إلى الذاكرة. الذاكرة: {m} · السجل: {r}',
      es: 'Escribir: el valor del registro vuelve a copiarse en memoria. Memoria: {m} · Registro: {r}',
      fr: 'Écrire : la valeur du registre est recopiée en mémoire. Mémoire : {m} · Registre : {r}',
      hi: 'लिखना: रजिस्टर का मान वापस मेमोरी में कॉपी होता है। मेमोरी: {m} · रजिस्टर: {r}',
      id: 'Tulis: nilai register disalin kembali ke memori. Memori: {m} · Register: {r}',
      pt: 'Escrever: o valor do registrador volta a ser copiado para a memória. Memória: {m} · Registrador: {r}',
    },
    'label.gap': {
      en: 'gap',
      ko: '틈',
      ja: 'すき間',
      zh: '间隙',
      ar: 'فجوة',
      es: 'hueco',
      fr: 'interstice',
      hi: 'अंतराल',
      id: 'celah',
      pt: 'brecha',
    },
    'label.memory': {
      en: 'Memory',
      ko: '메모리',
      ja: 'メモリ',
      zh: '内存',
      ar: 'الذاكرة',
      es: 'Memoria',
      fr: 'Mémoire',
      hi: 'मेमोरी',
      id: 'Memori',
      pt: 'Memória',
    },
    'label.thread': {
      en: 'Thread {id}',
      ko: '스레드 {id}',
      ja: 'スレッド {id}',
      zh: '线程 {id}',
      ar: 'الخيط {id}',
      es: 'Hilo {id}',
      fr: 'Thread {id}',
      hi: 'थ्रेड {id}',
      id: 'Thread {id}',
      pt: 'Thread {id}',
    },
    'label.register': {
      en: 'register',
      ko: '레지스터',
      ja: 'レジスタ',
      zh: '寄存器',
      ar: 'سجل',
      es: 'registro',
      fr: 'registre',
      hi: 'रजिस्टर',
      id: 'register',
      pt: 'registrador',
    },
    'tag.load': {
      en: 'read',
      ko: '읽기',
      ja: '読み込み',
      zh: '读取',
      ar: 'قراءة',
      es: 'leer',
      fr: 'lire',
      hi: 'पढ़ना',
      id: 'baca',
      pt: 'ler',
    },
    'tag.add': {
      en: 'add',
      ko: '더하기',
      ja: '加算',
      zh: '相加',
      ar: 'جمع',
      es: 'sumar',
      fr: 'ajouter',
      hi: 'जोड़ना',
      id: 'tambah',
      pt: 'somar',
    },
    'tag.store': {
      en: 'write',
      ko: '쓰기',
      ja: '書き込み',
      zh: '写回',
      ar: 'كتابة',
      es: 'escribir',
      fr: 'écrire',
      hi: 'लिखना',
      id: 'tulis',
      pt: 'escrever',
    },
  },
};
