import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 곧은 선만 긋는 단위들을 겹치면 어떻게 굽은 경계가 나오는가.
 */
export const layersComposeFacet: FacetJson = {
  id: 'facet:layersCompose',
  title: {
    en: 'Stacked layers bend the boundary',
    ko: '층을 겹치면 경계가 굽는다',
    ja: '層を重ねると境界が曲がる',
    zh: '叠加层让边界弯折',
    ar: 'الطبقات المتراكبة تثني الحد الفاصل',
    es: 'Las capas apiladas doblan la frontera',
    fr: 'Empiler des couches courbe la frontière',
    hi: 'परतें जोड़ने से सीमा मुड़ती है',
    id: 'Lapisan bertumpuk membengkokkan batas',
    pt: 'Camadas empilhadas dobram a fronteira',
  },
  description: {
    en: 'Each ReLU unit draws one straight hinge line; adding the units one by one to the second-layer sum gives the boundary on the input plane new corners until it bends into a bowl.',
    ko: '곧은 꺾임선 하나씩을 가진 ReLU 단위를 둘째 층의 합에 하나씩 더하면, 입력 평면의 경계가 새 모서리를 얻으며 그릇 모양으로 굽는다.',
    ja: 'ReLU ユニットはそれぞれまっすぐな折れ線を一本ずつ持つ。ユニットを第2層の和に一つずつ加えると、入力平面の境界が新しい角を得て器の形に曲がる。',
    zh: '每个 ReLU 单元只有一条笔直的折线；把单元逐个加入第二层的和，输入平面上的边界就不断获得新拐角，弯成碗形。',
    ar: 'كل وحدة ReLU ترسم خط انثناء مستقيمًا واحدًا؛ وبإضافة الوحدات واحدة تلو الأخرى إلى مجموع الطبقة الثانية يكتسب الحد على مستوى المدخلات زوايا جديدة حتى ينثني على شكل وعاء.',
    es: 'Cada unidad ReLU traza una sola línea de pliegue recta; al sumar las unidades una a una en la segunda capa, la frontera del plano de entrada gana esquinas nuevas hasta curvarse en forma de cuenco.',
    fr: 'Chaque unité ReLU trace une seule ligne de pli droite ; en ajoutant les unités une à une à la somme de la deuxième couche, la frontière du plan d’entrée gagne de nouveaux coins jusqu’à se courber en bol.',
    hi: 'हर ReLU इकाई एक सीधी मोड़-रेखा खींचती है; इकाइयों को एक-एक करके दूसरी परत के योग में जोड़ने पर इनपुट तल की सीमा नए कोने पाकर कटोरे जैसी मुड़ जाती है।',
    id: 'Setiap unit ReLU menarik satu garis lipat lurus; menambahkan unit satu per satu ke jumlah lapisan kedua membuat batas di bidang masukan mendapat sudut baru hingga melengkung seperti mangkuk.',
    pt: 'Cada unidade ReLU traça uma única linha de dobra reta; somando as unidades uma a uma na segunda camada, a fronteira no plano de entrada ganha cantos novos até se curvar em forma de tigela.',
  },
  algorithm: 'module:layersCompose',
  scene: 'module:layersComposeScene',
  initialData: {
    type: 'layers-compose',
    stepMs: 2400,
    box: 2,
    c: -1,
    units: [
      { a: 1, b: -0.5, d: 0, v: 1 },
      { a: -1, b: -0.5, d: 0, v: 1 },
      { a: 0, b: 1, d: -1, v: 1 },
    ],
    probes: [
      [0, 0],
      [0, -1.5],
      [1.5, 0],
      [0, 1.5],
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.axisX1': { en: 'x₁', ko: 'x₁', ja: 'x₁', zh: 'x₁', ar: 'x₁', es: 'x₁', fr: 'x₁', hi: 'x₁', id: 'x₁', pt: 'x₁' },
    'label.axisX2': { en: 'x₂', ko: 'x₂', ja: 'x₂', zh: 'x₂', ar: 'x₂', es: 'x₂', fr: 'x₂', hi: 'x₂', id: 'x₂', pt: 'x₂' },
    'label.layer2': {
      en: 'Second-layer sum',
      ko: '둘째 층의 합',
      ja: '第2層の和',
      zh: '第二层的和',
      ar: 'مجموع الطبقة الثانية',
      es: 'Suma de la segunda capa',
      fr: 'Somme de la deuxième couche',
      hi: 'दूसरी परत का योग',
      id: 'Jumlah lapisan kedua',
      pt: 'Soma da segunda camada',
    },
    'label.on': {
      en: 'On: o > 0',
      ko: '켜짐: o > 0',
      ja: 'オン: o > 0',
      zh: '激活: o > 0',
      ar: 'مُفعَّل: o > 0',
      es: 'Activo: o > 0',
      fr: 'Actif : o > 0',
      hi: 'चालू: o > 0',
      id: 'Menyala: o > 0',
      pt: 'Ativo: o > 0',
    },
    'label.corner': {
      en: 'Corner',
      ko: '모서리',
      ja: '角',
      zh: '拐角',
      ar: 'زاوية',
      es: 'Esquina',
      fr: 'Coin',
      hi: 'कोना',
      id: 'Sudut',
      pt: 'Canto',
    },
    'label.corners': {
      en: 'Corners: {n}',
      ko: '모서리: {n}',
      ja: '角: {n}',
      zh: '拐角: {n}',
      ar: 'الزوايا: {n}',
      es: 'Esquinas: {n}',
      fr: 'Coins : {n}',
      hi: 'कोने: {n}',
      id: 'Sudut: {n}',
      pt: 'Cantos: {n}',
    },
    'caption.start': {
      en: 'Nothing in the sum yet: o = {c} across the whole plane.',
      ko: '합에 든 단위가 아직 없다 — 평면 어디서나 o = {c}.',
      ja: 'まだ和には何も入っていない — 平面のどこでも o = {c}。',
      zh: '和中还没有任何单元——整个平面上 o = {c}。',
      ar: 'لا شيء في المجموع بعد: o = {c} على المستوى كله.',
      es: 'Aún no hay nada en la suma: o = {c} en todo el plano.',
      fr: 'Rien dans la somme pour l’instant : o = {c} sur tout le plan.',
      hi: 'योग में अभी कुछ नहीं: पूरे तल पर o = {c}।',
      id: 'Belum ada apa pun dalam jumlah: o = {c} di seluruh bidang.',
      pt: 'Ainda nada na soma: o = {c} em todo o plano.',
    },
    'caption.add': {
      en: 'Added to the sum: {unit}.',
      ko: '합에 더한 것: {unit}.',
      ja: '和に加えたもの: {unit}。',
      zh: '加入和中的: {unit}。',
      ar: 'أُضيف إلى المجموع: {unit}.',
      es: 'Añadido a la suma: {unit}.',
      fr: 'Ajouté à la somme : {unit}.',
      hi: 'योग में जोड़ा गया: {unit}।',
      id: 'Ditambahkan ke jumlah: {unit}.',
      pt: 'Adicionado à soma: {unit}.',
    },
  },
  blocks: {
    stage: { type: 'layers-compose-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
