/**
 * @notation native — 화면은 컴파일러 내부 표기다: IR 나무 마디(`STORE · ADD · MUL · MEM · NAME y · NUM 16`)와
 * 할당 전 기계 명령(`load t1, list` · `load t2, [t1+16]` · `li t2, 16`). 원시 줄은 나무 위 한 줄과 손잡이 라벨로만 둔다.
 * 코드 패널은 이 나무가 아니라 나무를 덮는 컴파일러 함수(가장 큰 무늬 먼저)다 — IR → 여섯 언어.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { InstructionSelectionData } from './algorithm.js';

const tree = (kind: 'STORE' | 'ADD' | 'MUL' | 'MEM', kids: InstructionSelectionData['trees']) => ({ kind, val: null, kids });
const name = (val: string) => ({ kind: 'NAME' as const, val, kids: [] });
const numLeaf = (val: number) => ({ kind: 'NUM' as const, val, kids: [] });

export const instructionSelectionInitialData: InstructionSelectionData = {
  type: 'instruction-selection',
  stepMs: 1000,
  isaLadder: [0, 1, 2],
  exprLadder: [0, 1],
  isa: 0,
  expr: 0,
  sources: ['let y = list[2] + n * 4', 'let y = list[i] + n * 4'],
  trees: [
    // STORE(NAME y, ADD(MEM(ADD(NAME list, NUM 16)), MUL(NAME n, NUM 4))) — 칸 하나 8 바이트, list[2] 는 +16
    tree('STORE', [
      name('y'),
      tree('ADD', [tree('MEM', [tree('ADD', [name('list'), numLeaf(16)])]), tree('MUL', [name('n'), numLeaf(4)])]),
    ]),
    // STORE(NAME y, ADD(MEM(ADD(NAME list, MUL(NAME i, NUM 8))), MUL(NAME n, NUM 4)))
    tree('STORE', [
      name('y'),
      tree('ADD', [
        tree('MEM', [tree('ADD', [name('list'), tree('MUL', [name('i'), numLeaf(8)])])]),
        tree('MUL', [name('n'), numLeaf(4)]),
      ]),
    ]),
  ],
  // 무늬 아홉 — 목록 차례 그대로. set 은 처음 드는 모음 (0 기본 · 1 + 즉시값 · 2 + 주소 더하기)
  patterns: [
    { name: 'store', set: 0, shape: { kind: 'STORE', kids: [{ kind: 'NAME', bind: 'x' }, { hole: true }] }, form: 'store {x}, {e0}' },
    {
      name: 'load-offset',
      set: 2,
      shape: { kind: 'MEM', kids: [{ kind: 'ADD', kids: [{ hole: true }, { kind: 'NUM', bind: 'k' }] }] },
      form: 'load {d}, [{e0}+{k}]',
    },
    { name: 'load-mem', set: 0, shape: { kind: 'MEM', kids: [{ hole: true }] }, form: 'load {d}, [{e0}+0]' },
    { name: 'addi', set: 1, shape: { kind: 'ADD', kids: [{ hole: true }, { kind: 'NUM', bind: 'k' }] }, form: 'addi {d}, {e0}, {k}' },
    { name: 'muli', set: 1, shape: { kind: 'MUL', kids: [{ hole: true }, { kind: 'NUM', bind: 'k' }] }, form: 'mul {d}, {e0}, {k}' },
    { name: 'add', set: 0, shape: { kind: 'ADD', kids: [{ hole: true }, { hole: true }] }, form: 'add {d}, {e0}, {e1}' },
    { name: 'mul', set: 0, shape: { kind: 'MUL', kids: [{ hole: true }, { hole: true }] }, form: 'mul {d}, {e0}, {e1}' },
    { name: 'load-name', set: 0, shape: { kind: 'NAME', bind: 'x' }, form: 'load {d}, {x}' },
    { name: 'li', set: 0, shape: { kind: 'NUM', bind: 'k' }, form: 'li {d}, {k}' },
  ],
};

export const instructionSelectionFacet: FacetJson = {
  id: 'facet:instructionSelection',
  title: {
    en: 'Instruction selection',
    ko: '명령 선택',
    ja: '命令選択',
    zh: '指令选择',
    ar: 'اختيار التعليمات',
    es: 'Selección de instrucciones',
    fr: 'Sélection d’instructions',
    hi: 'निर्देश चयन',
    id: 'Pemilihan instruksi',
    pt: 'Seleção de instruções',
  },
  description: {
    en: 'Patterns land on the IR tree biggest first — a richer instruction set covers the same tree with fewer, larger patterns, but only where the tree has the right shape.',
    ko: '무늬가 가장 큰 것부터 IR 나무에 내려앉는다 — 명령 모음이 넓으면 같은 나무를 더 큰 무늬 몇 개로 덮지만, 나무의 모양이 맞는 자리에서만 그렇다.',
    ja: 'パターンが大きいものから IR 木に降りる — 命令セットが豊かなら同じ木をより大きな少数のパターンで覆うが、木の形が合う所だけだ。',
    zh: '模式从最大的开始落到 IR 树上——指令集越丰富，同一棵树就被更少、更大的模式覆盖，但只在树的形状吻合的地方。',
    ar: 'تهبط الأنماط على شجرة IR من الأكبر أولًا — مجموعة تعليمات أغنى تغطي الشجرة نفسها بأنماط أقل وأكبر، لكن فقط حيث يوافق شكل الشجرة.',
    es: 'Los patrones caen sobre el árbol IR empezando por el mayor: un repertorio más rico cubre el mismo árbol con menos patrones más grandes, pero solo donde el árbol tiene la forma adecuada.',
    fr: 'Les motifs se posent sur l’arbre IR du plus grand au plus petit : un jeu d’instructions plus riche couvre le même arbre avec moins de motifs, plus grands, mais seulement là où l’arbre a la bonne forme.',
    hi: 'पैटर्न सबसे बड़े से शुरू होकर IR पेड़ पर उतरते हैं — समृद्ध निर्देश समूह उसी पेड़ को कम, बड़े पैटर्न से ढकता है, पर केवल वहीं जहाँ पेड़ का आकार मेल खाता है।',
    id: 'Pola mendarat di pohon IR mulai dari yang terbesar — set instruksi yang lebih kaya menutup pohon yang sama dengan pola lebih sedikit dan lebih besar, tetapi hanya di tempat bentuk pohonnya cocok.',
    pt: 'Os padrões pousam na árvore IR do maior para o menor: um conjunto de instruções mais rico cobre a mesma árvore com menos padrões, maiores, mas só onde a árvore tem a forma certa.',
  },
  algorithm: 'module:instructionSelection',
  projector: 'module:instructionSelectionProjector',
  initialData: instructionSelectionInitialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'instruction-selection-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'isa',
          name: 'isa',
          label: {
            en: 'Instruction set',
            ko: '명령 모음',
            ja: '命令セット',
            zh: '指令集',
            ar: 'مجموعة التعليمات',
            es: 'Repertorio',
            fr: 'Jeu d’instructions',
            hi: 'निर्देश समूह',
            id: 'Set instruksi',
            pt: 'Conjunto de instruções',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: {
                en: 'Basic',
                ko: '기본',
                ja: '基本',
                zh: '基本',
                ar: 'أساسي',
                es: 'Básico',
                fr: 'De base',
                hi: 'बुनियादी',
                id: 'Dasar',
                pt: 'Básico',
              },
            },
            {
              value: 1,
              label: {
                en: '+ immediates',
                ko: '+ 즉시값',
                ja: '+ 即値',
                zh: '+ 立即数',
                ar: '+ قيم فورية',
                es: '+ inmediatos',
                fr: '+ immédiats',
                hi: '+ तत्काल मान',
                id: '+ nilai langsung',
                pt: '+ imediatos',
              },
            },
            {
              value: 2,
              label: {
                en: '+ address offset',
                ko: '+ 주소 더하기',
                ja: '+ アドレス加算',
                zh: '+ 地址偏移',
                ar: '+ إزاحة العنوان',
                es: '+ desplazamiento',
                fr: '+ décalage d’adresse',
                hi: '+ पता ऑफ़सेट',
                id: '+ offset alamat',
                pt: '+ deslocamento',
              },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'expr',
          name: 'expr',
          label: {
            en: 'Expression',
            ko: '식',
            ja: '式',
            zh: '表达式',
            ar: 'التعبير',
            es: 'Expresión',
            fr: 'Expression',
            hi: 'व्यंजक',
            id: 'Ekspresi',
            pt: 'Expressão',
          },
          segments: [
            { value: 0, default: true, label: 'list[2] + n * 4' },
            { value: 1, label: 'list[i] + n * 4' },
          ],
        },
      ],
      metrics: [
        {
          name: 'tile-count',
          initial: 0,
          label: {
            en: 'Patterns',
            ko: '무늬',
            ja: 'パターン',
            zh: '模式',
            ar: 'الأنماط',
            es: 'Patrones',
            fr: 'Motifs',
            hi: 'पैटर्न',
            id: 'Pola',
            pt: 'Padrões',
          },
        },
        {
          name: 'instr-count',
          initial: 0,
          label: {
            en: 'Instructions',
            ko: '명령',
            ja: '命令',
            zh: '指令',
            ar: 'التعليمات',
            es: 'Instrucciones',
            fr: 'Instructions',
            hi: 'निर्देश',
            id: 'Instruksi',
            pt: 'Instruções',
          },
        },
        {
          name: 'max-live',
          initial: 0,
          label: {
            en: 'Max live values',
            ko: '산 값 최대',
            ja: '生存値の最大',
            zh: '最大活跃值',
            ar: 'أقصى قيم حية',
            es: 'Máx. valores vivos',
            fr: 'Valeurs vivantes max',
            hi: 'अधिकतम जीवित मान',
            id: 'Nilai hidup maks',
            pt: 'Máx. valores vivos',
          },
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:instruction-selection-imperative',
      label: {
        en: 'Maximal munch — biggest pattern first',
        ko: '가장 큰 무늬 먼저 덮기',
        ja: '最大のパターンから覆う',
        zh: '先用最大的模式覆盖',
        ar: 'التغطية بالنمط الأكبر أولًا',
        es: 'Cubrir con el patrón mayor primero',
        fr: 'Couvrir d’abord par le plus grand motif',
        hi: 'सबसे बड़े पैटर्न से पहले ढकना',
        id: 'Menutup dengan pola terbesar dulu',
        pt: 'Cobrir primeiro com o maior padrão',
      },
    },
  },
  messages: {
    'label.patterns': {
      en: 'Patterns',
      ko: '무늬',
      ja: 'パターン',
      zh: '模式',
      ar: 'الأنماط',
      es: 'Patrones',
      fr: 'Motifs',
      hi: 'पैटर्न',
      id: 'Pola',
      pt: 'Padrões',
    },
    'label.covers': {
      en: 'Covers',
      ko: '덮는 마디',
      ja: '覆う節点',
      zh: '覆盖节点',
      ar: 'العُقد المغطاة',
      es: 'Nodos que cubre',
      fr: 'Nœuds couverts',
      hi: 'ढके नोड',
      id: 'Simpul ditutup',
      pt: 'Nós cobertos',
    },
    'label.instructions': {
      en: 'Instructions',
      ko: '명령',
      ja: '命令',
      zh: '指令',
      ar: 'التعليمات',
      es: 'Instrucciones',
      fr: 'Instructions',
      hi: 'निर्देश',
      id: 'Instruksi',
      pt: 'Instruções',
    },
    'caption.start': {
      en: 'Uncovered tree · nodes: {nodes}',
      ko: '덮이지 않은 나무 · 마디: {nodes}',
      ja: '覆われていない木 · 節点: {nodes}',
      zh: '未覆盖的树 · 节点: {nodes}',
      ar: 'شجرة غير مغطاة · العُقد: {nodes}',
      es: 'Árbol sin cubrir · nodos: {nodes}',
      fr: 'Arbre non couvert · nœuds : {nodes}',
      hi: 'बिना ढका पेड़ · नोड: {nodes}',
      id: 'Pohon belum tertutup · simpul: {nodes}',
      pt: 'Árvore descoberta · nós: {nodes}',
    },
    'caption.tile': {
      en: '{pattern} · covers: {size} · covered: {covered} / {nodes}',
      ko: '{pattern} · 덮는 마디: {size} · 덮인 마디: {covered} / {nodes}',
      ja: '{pattern} · 覆う節点: {size} · 覆われた節点: {covered} / {nodes}',
      zh: '{pattern} · 覆盖节点: {size} · 已覆盖: {covered} / {nodes}',
      ar: '{pattern} · يغطي: {size} · المغطى: {covered} / {nodes}',
      es: '{pattern} · cubre: {size} · cubiertos: {covered} / {nodes}',
      fr: '{pattern} · couvre : {size} · couverts : {covered} / {nodes}',
      hi: '{pattern} · ढकता है: {size} · ढके गए: {covered} / {nodes}',
      id: '{pattern} · menutup: {size} · tertutup: {covered} / {nodes}',
      pt: '{pattern} · cobre: {size} · cobertos: {covered} / {nodes}',
    },
    'caption.tileSkip': {
      en: '{pattern} · no fit: {skipped} · covers: {size} · covered: {covered} / {nodes}',
      ko: '{pattern} · 안 맞음: {skipped} · 덮는 마디: {size} · 덮인 마디: {covered} / {nodes}',
      ja: '{pattern} · 合わない: {skipped} · 覆う節点: {size} · 覆われた節点: {covered} / {nodes}',
      zh: '{pattern} · 不匹配: {skipped} · 覆盖节点: {size} · 已覆盖: {covered} / {nodes}',
      ar: '{pattern} · لا يطابق: {skipped} · يغطي: {size} · المغطى: {covered} / {nodes}',
      es: '{pattern} · no encaja: {skipped} · cubre: {size} · cubiertos: {covered} / {nodes}',
      fr: '{pattern} · ne colle pas : {skipped} · couvre : {size} · couverts : {covered} / {nodes}',
      hi: '{pattern} · मेल नहीं: {skipped} · ढकता है: {size} · ढके गए: {covered} / {nodes}',
      id: '{pattern} · tidak cocok: {skipped} · menutup: {size} · tertutup: {covered} / {nodes}',
      pt: '{pattern} · não encaixa: {skipped} · cobre: {size} · cobertos: {covered} / {nodes}',
    },
    'caption.emit': {
      en: 'Instructions: {instrs} · temporaries: {temps} · max live: {live}',
      ko: '명령: {instrs} · 임시: {temps} · 산 값 최대: {live}',
      ja: '命令: {instrs} · 一時値: {temps} · 生存値の最大: {live}',
      zh: '指令: {instrs} · 临时值: {temps} · 最大活跃值: {live}',
      ar: 'التعليمات: {instrs} · المؤقتات: {temps} · أقصى قيم حية: {live}',
      es: 'Instrucciones: {instrs} · temporales: {temps} · máx. vivos: {live}',
      fr: 'Instructions : {instrs} · temporaires : {temps} · vivantes max : {live}',
      hi: 'निर्देश: {instrs} · अस्थायी: {temps} · अधिकतम जीवित: {live}',
      id: 'Instruksi: {instrs} · sementara: {temps} · hidup maks: {live}',
      pt: 'Instruções: {instrs} · temporários: {temps} · máx. vivos: {live}',
    },
  },
};
