import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 한 선을 함께 쓰는 둘이 동시에 보내 부딪히면, 어떻게 다음번에는 부딪히지 않는가.
 */
export const collisionAndBackoffFacet: FacetJson = {
  id: 'facet:collisionAndBackoff',
  title: {
    en: 'Collide, back off, try again',
    ko: '부딪히면 물러났다 다시',
    ja: 'ぶつかったら退いて、もう一度',
    zh: '相撞后退让，再试一次',
    ar: 'تصطدم فتتراجع ثم تحاول من جديد',
    es: 'Chocar, retroceder y volver a intentar',
    fr: 'Collision, recul, nouvel essai',
    hi: 'टकराओ, पीछे हटो, फिर कोशिश करो',
    id: 'Bertabrakan, mundur, lalu coba lagi',
    pt: 'Colidir, recuar e tentar de novo',
  },
  description: {
    en: 'When two stations sharing one line send at once and collide, how do they avoid colliding the next time?',
    ko: '한 선을 함께 쓰는 둘이 동시에 보내 부딪히면, 어떻게 다음번에는 부딪히지 않는가?',
    ja: '一本の線を共有する二つの局が同時に送って衝突したら、次はどうやって衝突を避けるのか？',
    zh: '共用一条线路的两个站同时发送而相撞后，下一次如何避免再次相撞？',
    ar: 'إذا أرسلت محطتان تتشاركان خطًا واحدًا في اللحظة نفسها فاصطدمتا، فكيف تتجنبان الاصطدام في المرة التالية؟',
    es: 'Si dos estaciones que comparten una línea envían a la vez y chocan, ¿cómo evitan chocar la próxima vez?',
    fr: 'Quand deux stations qui partagent une ligne émettent en même temps et entrent en collision, comment évitent-elles la collision suivante ?',
    hi: 'एक ही लाइन साझा करने वाले दो स्टेशन एक साथ भेजकर टकरा जाएँ, तो अगली बार वे टकराने से कैसे बचते हैं?',
    id: 'Jika dua stasiun yang berbagi satu jalur mengirim bersamaan lalu bertabrakan, bagaimana mereka menghindari tabrakan berikutnya?',
    pt: 'Quando duas estações que compartilham uma linha enviam ao mesmo tempo e colidem, como evitam colidir na próxima vez?',
  },
  algorithm: 'module:collisionAndBackoff',
  scene: 'module:collisionAndBackoffScene',
  initialData: {
    type: 'collision-and-backoff',
    stepMs: 1100,
    frameSlots: 3,
    stations: [
      { id: 'a', readyAt: 0, backoffK: [0] },
      { id: 'b', readyAt: 0, backoffK: [1] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.ready': {
      en: 'Next: slot {slot}. Stations with a frame ready: {n}',
      ko: '다음은 슬롯 {slot}. 보낼 프레임이 준비된 스테이션: {n}',
      ja: '次はスロット {slot}。送るフレームが準備できた局：{n}',
      zh: '下一个：时隙 {slot}。已备好帧的站：{n}',
      ar: 'التالي: الفتحة {slot}. المحطات التي لديها إطار جاهز: {n}',
      es: 'Siguiente: ranura {slot}. Estaciones con una trama lista: {n}',
      fr: 'Suivant : créneau {slot}. Stations avec une trame prête : {n}',
      hi: 'अगला: स्लॉट {slot}। फ़्रेम तैयार वाले स्टेशन: {n}',
      id: 'Berikutnya: slot {slot}. Stasiun dengan bingkai siap: {n}',
      pt: 'Próximo: slot {slot}. Estações com um quadro pronto: {n}',
    },
    'caption.frame': {
      en: 'Frame length in slots: {n}',
      ko: '프레임 길이(슬롯): {n}',
      ja: 'フレームの長さ（スロット）：{n}',
      zh: '帧长（时隙）：{n}',
      ar: 'طول الإطار بالفتحات: {n}',
      es: 'Longitud de la trama en ranuras: {n}',
      fr: 'Longueur de trame en créneaux : {n}',
      hi: 'फ़्रेम की लंबाई (स्लॉट): {n}',
      id: 'Panjang bingkai dalam slot: {n}',
      pt: 'Comprimento do quadro em slots: {n}',
    },
    'caption.collide': {
      en: 'Slot {slot}: collision. Started together on an idle line: {n}',
      ko: '슬롯 {slot}: 충돌. 빈 선에서 함께 시작한 스테이션: {n}',
      ja: 'スロット {slot}：衝突。空いた線で同時に送り始めた局：{n}',
      zh: '时隙 {slot}：冲突。在空闲线路上同时开始的站：{n}',
      ar: 'الفتحة {slot}: تصادم. محطات بدأت معًا على خط خالٍ: {n}',
      es: 'Ranura {slot}: colisión. Empezaron a la vez en una línea libre: {n}',
      fr: 'Créneau {slot} : collision. Parties ensemble sur une ligne libre : {n}',
      hi: 'स्लॉट {slot}: टक्कर। खाली लाइन पर साथ शुरू करने वाले: {n}',
      id: 'Slot {slot}: tabrakan. Mulai bersamaan di jalur kosong: {n}',
      pt: 'Slot {slot}: colisão. Começaram juntas numa linha livre: {n}',
    },
    'caption.backoff': {
      en: 'Stopped, each backing off to its own mark: {n}',
      ko: '멈추고 각자의 표시까지 물러난 스테이션: {n}',
      ja: '止まってそれぞれの印まで退いた局：{n}',
      zh: '停下并各自退让到自己标记的站：{n}',
      ar: 'محطات توقفت وتراجعت كل منها حتى علامتها: {n}',
      es: 'Detenidas, cada una retrocede hasta su marca: {n}',
      fr: 'Arrêtées, chacune recule jusqu’à sa marque : {n}',
      hi: 'रुककर अपने-अपने निशान तक पीछे हटे: {n}',
      id: 'Berhenti, masing-masing mundur sampai tandanya: {n}',
      pt: 'Paradas, cada uma recua até a sua marca: {n}',
    },
    'caption.start': {
      en: 'Slot {slot}: {name} hears an idle line and sends.',
      ko: '슬롯 {slot}: {name} — 빈 선을 듣고 보낸다.',
      ja: 'スロット {slot}：{name} — 空いた線を聞いて送る。',
      zh: '时隙 {slot}：{name} — 听到线路空闲，开始发送。',
      ar: 'الفتحة {slot}: {name} — تسمع خطًا خاليًا فترسل.',
      es: 'Ranura {slot}: {name} — oye la línea libre y envía.',
      fr: 'Créneau {slot} : {name} — entend une ligne libre et émet.',
      hi: 'स्लॉट {slot}: {name} — लाइन खाली सुनकर भेजता है।',
      id: 'Slot {slot}: {name} — mendengar jalur kosong lalu mengirim.',
      pt: 'Slot {slot}: {name} — ouve a linha livre e envia.',
    },
    'caption.hold': {
      en: 'Slot {slot}: {name} holds the line.',
      ko: '슬롯 {slot}: {name} — 선을 차지하고 있다.',
      ja: 'スロット {slot}：{name} — 線を占めている。',
      zh: '时隙 {slot}：{name} — 占用着线路。',
      ar: 'الفتحة {slot}: {name} — تشغل الخط.',
      es: 'Ranura {slot}: {name} — ocupa la línea.',
      fr: 'Créneau {slot} : {name} — occupe la ligne.',
      hi: 'स्लॉट {slot}: {name} — लाइन पर कब्ज़ा रखता है।',
      id: 'Slot {slot}: {name} — menguasai jalur.',
      pt: 'Slot {slot}: {name} — ocupa a linha.',
    },
    'caption.last': {
      en: 'Slot {slot}: {name} sends its last slot and is done.',
      ko: '슬롯 {slot}: {name} — 마지막 슬롯을 보내고 끝.',
      ja: 'スロット {slot}：{name} — 最後のスロットを送って終わり。',
      zh: '时隙 {slot}：{name} — 发完最后一个时隙，结束。',
      ar: 'الفتحة {slot}: {name} — ترسل فتحتها الأخيرة وتنتهي.',
      es: 'Ranura {slot}: {name} — envía su última ranura y termina.',
      fr: 'Créneau {slot} : {name} — émet son dernier créneau et termine.',
      hi: 'स्लॉट {slot}: {name} — आख़िरी स्लॉट भेजकर पूरा।',
      id: 'Slot {slot}: {name} — mengirim slot terakhirnya dan selesai.',
      pt: 'Slot {slot}: {name} — envia o último slot e termina.',
    },
    'caption.defer': {
      en: '{name} hears a busy line and keeps listening.',
      ko: '{name} — 선이 차 있다. 빌 때까지 듣는다.',
      ja: '{name} — 線がふさがっている。空くまで聞き続ける。',
      zh: '{name} — 线路忙，一直听到它空闲。',
      ar: '{name} — الخط مشغول، فتواصل الإصغاء.',
      es: '{name} — la línea está ocupada; sigue escuchando.',
      fr: '{name} — la ligne est occupée ; elle continue d’écouter.',
      hi: '{name} — लाइन व्यस्त है, खाली होने तक सुनता रहता है।',
      id: '{name} — jalur sibuk, terus mendengarkan.',
      pt: '{name} — a linha está ocupada; continua ouvindo.',
    },
    'caption.wait': {
      en: '{name} — slots of waiting left: {n}',
      ko: '{name} — 남은 기다림(슬롯): {n}',
      ja: '{name} — 残りの待ち（スロット）：{n}',
      zh: '{name} — 剩余等待（时隙）：{n}',
      ar: '{name} — فتحات الانتظار المتبقية: {n}',
      es: '{name} — ranuras de espera restantes: {n}',
      fr: '{name} — créneaux d’attente restants : {n}',
      hi: '{name} — बचे प्रतीक्षा स्लॉट: {n}',
      id: '{name} — sisa slot menunggu: {n}',
      pt: '{name} — slots de espera restantes: {n}',
    },
    'caption.left': {
      en: 'Frame slots left: {n}',
      ko: '남은 프레임 슬롯: {n}',
      ja: '残りのフレームスロット：{n}',
      zh: '剩余帧时隙：{n}',
      ar: 'فتحات الإطار المتبقية: {n}',
      es: 'Ranuras de trama restantes: {n}',
      fr: 'Créneaux de trame restants : {n}',
      hi: 'बचे फ़्रेम स्लॉट: {n}',
      id: 'Sisa slot bingkai: {n}',
      pt: 'Slots de quadro restantes: {n}',
    },
    'caption.end': {
      en: 'Collisions: {n}',
      ko: '충돌 횟수: {n}',
      ja: '衝突の回数：{n}',
      zh: '冲突次数：{n}',
      ar: 'عدد التصادمات: {n}',
      es: 'Colisiones: {n}',
      fr: 'Collisions : {n}',
      hi: 'टक्करें: {n}',
      id: 'Jumlah tabrakan: {n}',
      pt: 'Colisões: {n}',
    },
    'label.a': {
      en: 'Station A',
      ko: '스테이션 A',
      ja: '局 A',
      zh: '站 A',
      ar: 'المحطة A',
      es: 'Estación A',
      fr: 'Station A',
      hi: 'स्टेशन A',
      id: 'Stasiun A',
      pt: 'Estação A',
    },
    'label.b': {
      en: 'Station B',
      ko: '스테이션 B',
      ja: '局 B',
      zh: '站 B',
      ar: 'المحطة B',
      es: 'Estación B',
      fr: 'Station B',
      hi: 'स्टेशन B',
      id: 'Stasiun B',
      pt: 'Estação B',
    },
    'label.station': {
      en: 'Station',
      ko: '스테이션',
      ja: '局',
      zh: '站',
      ar: 'محطة',
      es: 'Estación',
      fr: 'Station',
      hi: 'स्टेशन',
      id: 'Stasiun',
      pt: 'Estação',
    },
    'label.line': {
      en: 'Shared line',
      ko: '공유 선',
      ja: '共有の線',
      zh: '共享线路',
      ar: 'الخط المشترك',
      es: 'Línea compartida',
      fr: 'Ligne partagée',
      hi: 'साझा लाइन',
      id: 'Jalur bersama',
      pt: 'Linha compartilhada',
    },
    'label.slot': {
      en: 'Slot',
      ko: '슬롯',
      ja: 'スロット',
      zh: '时隙',
      ar: 'الفتحة',
      es: 'Ranura',
      fr: 'Créneau',
      hi: 'स्लॉट',
      id: 'Slot',
      pt: 'Slot',
    },
    'label.listen': {
      en: 'listening',
      ko: '듣는 중',
      ja: '聞いている',
      zh: '监听中',
      ar: 'تُصغي',
      es: 'escucha',
      fr: 'écoute',
      hi: 'सुन रहा',
      id: 'mendengar',
      pt: 'ouvindo',
    },
    'label.k': {
      en: 'k = {k} (0–{hi})',
      ko: 'k = {k} (0–{hi})',
      ja: 'k = {k} (0–{hi})',
      zh: 'k = {k} (0–{hi})',
      ar: 'k = {k} (0–{hi})',
      es: 'k = {k} (0–{hi})',
      fr: 'k = {k} (0–{hi})',
      hi: 'k = {k} (0–{hi})',
      id: 'k = {k} (0–{hi})',
      pt: 'k = {k} (0–{hi})',
    },
  },
  blocks: {
    stage: { type: 'collision-and-backoff-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
