/**
 * repaint-cost — 완제품 선언.
 *
 * @notation native — 데이터와 화면에 나오는 태그·CSS 속성·CSS 선언·렌더링 파이프라인 단계 이름
 * (header/intro/card/card-title/card-text/list/footer/badge/page, display/height/color/transform,
 * style/layout/paint/composite, `will-change: transform`)은 실제 웹 표준 어휘 그 자체이며 번역하지
 * 않는다. 역할 이름(다시 칠함·층·함께 등)만 `messages` 를 거친다.
 */
import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const repaintCostFacet: FacetJson = {
  id: 'facet:repaintCost',
  title: {
    en: 'Repaint cost',
    ko: '다시 칠하기 비용',
    ja: '再描画のコスト',
    zh: '重绘的代价',
    ar: 'تكلفة إعادة الطلاء',
    es: 'Costo de repintado',
    fr: 'Coût de repeinture',
    hi: 'फिर से रंगने की लागत',
    id: 'Biaya pengecatan ulang',
    pt: 'Custo de repintura',
  },
  description: {
    en: 'Which property you change decides how far the rendering pipeline reruns, and whether giving an element its own layer can skip repainting.',
    ko: '바뀌는 속성이 렌더링 파이프라인의 어디서부터 다시 도는지 가르고, 요소를 제 층에 두면 다시 칠하기를 건너뛸 수 있는지 보인다.',
    ja: '変える property が、レンダリングパイプラインのどこから再実行されるかを分け、要素を専用レイヤーに置くと再描画を省けるかを示す。',
    zh: '所改变的属性决定渲染管线从哪一步重新开始,以及让元素拥有自己的图层能否跳过重绘。',
    ar: 'الخاصية التي تغيّرها تحدد من أين يعيد خط أنابيب العرض تشغيله، وهل يمكن لوضع عنصر في طبقته الخاصة تجاوز إعادة الطلاء.',
    es: 'La propiedad que cambias decide desde dónde se reanuda el pipeline de renderizado, y si darle su propia capa a un elemento puede evitar el repintado.',
    fr: 'La propriété que vous changez décide à partir d\'où le pipeline de rendu reprend, et si donner sa propre couche à un élément permet d\'éviter le repeint.',
    hi: 'जो property आप बदलते हैं वह तय करती है कि रेंडरिंग पाइपलाइन कहाँ से फिर चलती है, और क्या किसी एलिमेंट को अपनी परत देने से पुनः रंगना टल सकता है।',
    id: 'Properti yang kamu ubah menentukan dari mana pipeline rendering berjalan ulang, dan apakah memberi elemen lapisannya sendiri bisa melewati pengecatan ulang.',
    pt: 'A propriedade que você muda decide de onde o pipeline de renderização recomeça, e se dar sua própria camada a um elemento pode evitar a repintura.',
  },
  algorithm: 'module:repaintCost',
  projector: 'module:repaintCostProjector',
  initialData: {
    type: 'repaint-cost',
    stepMs: 1300,
    width: 300,
    elements: [
      { id: 'header', h: 40 },
      { id: 'intro', h: 48 },
      { id: 'card', h: 96 },
      { id: 'list', h: 72 },
      { id: 'footer', h: 40 },
    ],
    cardTitleH: 30,
    heightGrow: 48,
    translateX: 40,
    badge: { x: 240, y: 150, w: 50, h: 60 },
    property: 0,
    cardLayer: 0,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'repaint-cost-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'property',
          name: 'property',
          label: {
            en: 'Property',
            ko: '속성',
            ja: 'プロパティ',
            zh: '属性',
            ar: 'الخاصية',
            es: 'Propiedad',
            fr: 'Propriété',
            hi: 'गुण',
            id: 'Properti',
            pt: 'Propriedade',
          },
          segments: [
            { value: 0, label: 'display', default: true },
            { value: 1, label: 'height' },
            { value: 2, label: 'color' },
            { value: 3, label: 'transform' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'cardLayer',
          name: 'cardLayer',
          label: {
            en: 'Card layer',
            ko: '카드 층',
            ja: 'カードの層',
            zh: '卡片层',
            ar: 'طبقة البطاقة',
            es: 'Capa de tarjeta',
            fr: 'Calque de carte',
            hi: 'कार्ड परत',
            id: 'Lapisan kartu',
            pt: 'Camada do cartão',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Together',
                ko: '함께',
                ja: '一緒に',
                zh: '一起',
                ar: 'معًا',
                es: 'Juntos',
                fr: 'Ensemble',
                hi: 'साथ',
                id: 'Bersama',
                pt: 'Juntos',
              },
              default: true,
            },
            { value: 1, label: 'will-change: transform' },
          ],
        },
      ],
      metrics: [
        {
          name: 'repainted',
          label: {
            en: 'Repainted',
            ko: '다시 칠함',
            ja: '再描画',
            zh: '重绘',
            ar: 'أعيد طلاؤه',
            es: 'Repintado',
            fr: 'Repeint',
            hi: 'पुनः रंगा',
            id: 'Dicat ulang',
            pt: 'Repintado',
          },
          initial: 0,
        },
        {
          name: 'stages',
          label: {
            en: 'Stages run',
            ko: '도는 단계',
            ja: '実行段階',
            zh: '运行阶段',
            ar: 'المراحل التي عملت',
            es: 'Etapas ejecutadas',
            fr: 'Étapes exécutées',
            hi: 'चलने वाले चरण',
            id: 'Tahapan berjalan',
            pt: 'Etapas executadas',
          },
          initial: 0,
        },
        {
          name: 'layers',
          label: {
            en: 'Layers',
            ko: '층',
            ja: 'レイヤー',
            zh: '图层',
            ar: 'الطبقات',
            es: 'Capas',
            fr: 'Calques',
            hi: 'परतें',
            id: 'Lapisan',
            pt: 'Camadas',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:repaint-cost-imperative',
      label: {
        en: 'Code',
        ko: '코드',
        ja: 'コード',
        zh: '代码',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
    },
  },
  messages: {
    'caption.chain': {
      en: 'Pipeline: {chain}',
      ko: '파이프라인: {chain}',
      ja: 'パイプライン: {chain}',
      zh: '管线: {chain}',
      ar: 'خط الأنابيب: {chain}',
      es: 'Canal: {chain}',
      fr: 'Pipeline : {chain}',
      hi: 'पाइपलाइन: {chain}',
      id: 'Pipeline: {chain}',
      pt: 'Pipeline: {chain}',
    },
    'caption.repaint': {
      en: 'Render tree Δ{tree} · Remeasured {boxes} · Repainted {count} ({list}) · Layers {layers}',
      ko: '렌더 트리 변화 {tree} · 다시 잰 상자 {boxes} · 다시 칠함 {count}개 ({list}) · 층 {layers}',
      ja: 'レンダーツリー変化 {tree} · 再計測 {boxes} · 再描画 {count}件 ({list}) · レイヤー {layers}',
      zh: '渲染树变化 {tree} · 重新测量 {boxes} · 重绘 {count} 个 ({list}) · 图层 {layers}',
      ar: 'تغيّر شجرة العرض {tree} · أعيد قياسه {boxes} · أعيد طلاء {count} ({list}) · الطبقات {layers}',
      es: 'Cambio del árbol de render {tree} · Recalculado {boxes} · Repintado {count} ({list}) · Capas {layers}',
      fr: "Changement de l'arbre de rendu {tree} · Remesuré {boxes} · Repeint {count} ({list}) · Calques {layers}",
      hi: 'रेंडर ट्री बदलाव {tree} · फिर मापा {boxes} · फिर रंगा {count} ({list}) · परतें {layers}',
      id: 'Perubahan render tree {tree} · Diukur ulang {boxes} · Dicat ulang {count} ({list}) · Lapisan {layers}',
      pt: 'Mudança na render tree {tree} · Remedido {boxes} · Repintado {count} ({list}) · Camadas {layers}',
    },
    'caption.layerOwn': {
      en: 'card has its own compositing layer',
      ko: 'card 가 제 합성 층을 가진다',
      ja: 'card は専用の合成レイヤーを持つ',
      zh: 'card 拥有自己的合成图层',
      ar: 'لدى card طبقة تركيب خاصة به',
      es: 'card tiene su propia capa de composición',
      fr: 'card a sa propre couche de composition',
      hi: 'card की अपनी कंपोज़िटिंग परत है',
      id: 'card memiliki lapisan compositing sendiri',
      pt: 'card tem sua própria camada de composição',
    },
    'caption.layerTogether': {
      en: 'card paints together with the page',
      ko: 'card 가 page 와 함께 칠해진다',
      ja: 'card は page と一緒に描画される',
      zh: 'card 与 page 一起被绘制',
      ar: 'يُطلى card مع page معًا',
      es: 'card se pinta junto con la page',
      fr: 'card est peint avec la page',
      hi: 'card, page के साथ रंगा जाता है',
      id: 'card dicat bersama page',
      pt: 'card é pintado junto com a page',
    },
  },
};
