/**
 * @piece long-task-blocks — 120ms 걸리는 일 하나가 도는 동안 누른 클릭 셋은 각각
 * 얼마나 기다리는가.
 */
import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const longTaskBlocksFacet: FacetJson = {
  id: 'facet:longTaskBlocks',
  title: {
    en: 'A Long Task Blocks Clicks',
    ko: '긴 셈이 클릭을 막는다',
    ja: '長い処理がクリックを塞ぐ',
    zh: '一次长计算挡住点击',
    ar: 'مهمة طويلة تحجب النقرات',
    es: 'Una tarea larga bloquea los clics',
    fr: 'Une tâche longue bloque les clics',
    hi: 'एक लंबा कार्य क्लिक को रोकता है',
    id: 'Tugas panjang memblokir klik',
    pt: 'Uma tarefa longa bloqueia os cliques',
  },
  description: {
    en: 'A 120ms long calc runs first. Three clicks arrive while it runs and queue up. When it ends, each click is handled in order and waits before it starts.',
    ko: '120ms짜리 긴 셈이 먼저 돈다. 그동안 클릭 셋이 도착해 태스크 줄에 쌓인다. 긴 셈이 끝나면 클릭이 차례로 처리되고, 저마다 시작 전까지 기다린다.',
    ja: '120ミリ秒の長い処理が先に動く。その間にクリックが三つ届き、タスクの列に積み重なる。長い処理が終わると、クリックは順番に処理され、それぞれ始まる前に待つ。',
    zh: '一次120毫秒的长计算先运行。运行期间三次点击到达并堆积在任务队列里。长计算结束后，点击依次被处理，每次处理前都要等待。',
    ar: 'تعمل مهمة حسابية طويلة مدتها 120 مللي ثانية أولاً. أثناء تشغيلها تصل ثلاث نقرات وتتراكم في طابور المهام. عند انتهائها تُعالَج النقرات بالترتيب، وكل واحدة تنتظر قبل أن تبدأ.',
    es: 'Un cálculo largo de 120ms se ejecuta primero. Mientras corre, llegan tres clics y se acumulan en la cola de tareas. Cuando termina, cada clic se procesa en orden y espera antes de comenzar.',
    fr: "Un calcul long de 120ms s'exécute en premier. Pendant ce temps, trois clics arrivent et s'accumulent dans la file de tâches. Une fois terminé, chaque clic est traité dans l'ordre et attend avant de commencer.",
    hi: 'पहले 120ms का एक लंबा हिसाब चलता है। इस दौरान तीन क्लिक आते हैं और कार्य-सूची में जमा होते हैं। हिसाब खत्म होने पर हर क्लिक बारी-बारी संभाला जाता है, और शुरू होने से पहले इंतज़ार करता है।',
    id: 'Sebuah hitungan panjang 120ms berjalan lebih dulu. Selama itu tiga klik tiba dan menumpuk di antrean tugas. Setelah selesai, setiap klik ditangani secara berurutan dan menunggu sebelum mulai diproses.',
    pt: 'Um cálculo longo de 120ms roda primeiro. Enquanto ele roda, três cliques chegam e se acumulam na fila de tarefas. Quando termina, cada clique é tratado em ordem e espera antes de começar.',
  },
  algorithm: 'module:longTaskBlocks',
  scene: 'module:longTaskBlocksScene',
  initialData: {
    type: 'long-task-blocks',
    stepMs: 1300,
    long: { id: 'long', durationMs: 120 },
    clicks: [
      { id: 'click1', arrivalMs: 20 },
      { id: 'click2', arrivalMs: 50 },
      { id: 'click3', arrivalMs: 80 },
    ],
    handlerMs: 2,
  },
  shuffleOnReset: false,
  messages: {
    'caption.init': {
      en: 'The task queue is empty.',
      ko: '태스크 줄이 비어 있다.',
      ja: 'タスクの列は空だ。',
      zh: '任务队列是空的。',
      ar: 'طابور المهام فارغ.',
      es: 'La cola de tareas está vacía.',
      fr: 'La file de tâches est vide.',
      hi: 'कार्य-सूची खाली है।',
      id: 'Antrean tugas kosong.',
      pt: 'A fila de tarefas está vazia.',
    },
    'caption.longStart': {
      en: 'The long calc starts. It blocks the queue for {durationMs}ms.',
      ko: '긴 셈이 시작됐다. {durationMs}ms 동안 태스크 줄을 막는다.',
      ja: '長い処理が始まった。{durationMs}ミリ秒の間、列を塞ぐ。',
      zh: '长计算开始了。它会挡住队列{durationMs}毫秒。',
      ar: 'بدأت المهمة الطويلة. تحجب الطابور لمدة {durationMs} مللي ثانية.',
      es: 'El cálculo largo empieza. Bloquea la cola durante {durationMs}ms.',
      fr: 'Le calcul long commence. Il bloque la file pendant {durationMs}ms.',
      hi: 'लंबा हिसाब शुरू हुआ। यह {durationMs}ms तक सूची को रोकता है।',
      id: 'Hitungan panjang dimulai. Ia memblokir antrean selama {durationMs}ms.',
      pt: 'O cálculo longo começa. Ele bloqueia a fila por {durationMs}ms.',
    },
    'caption.arrive': {
      en: 'Click {no} arrives. Queue length {len}.',
      ko: '클릭 {no} 도착. 태스크 줄 길이 {len}.',
      ja: 'クリック{no}が届いた。列の長さ{len}。',
      zh: '点击{no}到达。队列长度{len}。',
      ar: 'وصلت النقرة {no}. طول الطابور {len}.',
      es: 'Llega el clic {no}. Largo de la cola {len}.',
      fr: 'Le clic {no} arrive. Longueur de la file {len}.',
      hi: 'क्लिक {no} पहुंचा। सूची की लंबाई {len}।',
      id: 'Klik {no} tiba. Panjang antrean {len}.',
      pt: 'O clique {no} chega. Tamanho da fila {len}.',
    },
    'caption.longEnd': {
      en: 'The long calc ends. Queue length {len}.',
      ko: '긴 셈이 끝났다. 태스크 줄 길이 {len}.',
      ja: '長い処理が終わった。列の長さ{len}。',
      zh: '长计算结束了。队列长度{len}。',
      ar: 'انتهت المهمة الطويلة. طول الطابور {len}.',
      es: 'El cálculo largo termina. Largo de la cola {len}.',
      fr: 'Le calcul long se termine. Longueur de la file {len}.',
      hi: 'लंबा हिसाब खत्म हुआ। सूची की लंबाई {len}।',
      id: 'Hitungan panjang selesai. Panjang antrean {len}.',
      pt: 'O cálculo longo termina. Tamanho da fila {len}.',
    },
    'caption.process': {
      en: 'Click {no} starts processing. Wait {waitMs}ms.',
      ko: '클릭 {no} 처리 시작. 기다림 {waitMs}ms.',
      ja: 'クリック{no}の処理が始まる。待ち{waitMs}ミリ秒。',
      zh: '点击{no}开始处理。等待{waitMs}毫秒。',
      ar: 'بدأت معالجة النقرة {no}. الانتظار {waitMs} مللي ثانية.',
      es: 'Empieza a procesarse el clic {no}. Espera {waitMs}ms.',
      fr: 'Le clic {no} commence à être traité. Attente {waitMs}ms.',
      hi: 'क्लिक {no} की प्रक्रिया शुरू। प्रतीक्षा {waitMs}ms।',
      id: 'Klik {no} mulai diproses. Menunggu {waitMs}ms.',
      pt: 'O clique {no} começa a ser processado. Espera {waitMs}ms.',
    },
    'label.queue': {
      en: 'Task queue',
      ko: '태스크 줄',
      ja: 'タスクの列',
      zh: '任务队列',
      ar: 'طابور المهام',
      es: 'Cola de tareas',
      fr: 'File de tâches',
      hi: 'कार्य-सूची',
      id: 'Antrean tugas',
      pt: 'Fila de tarefas',
    },
    'label.done': {
      en: 'Done',
      ko: '처리됨',
      ja: '処理済み',
      zh: '已处理',
      ar: 'منتهية',
      es: 'Hecho',
      fr: 'Terminé',
      hi: 'पूर्ण',
      id: 'Selesai',
      pt: 'Concluído',
    },
    'label.long': {
      en: 'Long calc',
      ko: '긴 셈',
      ja: '長い処理',
      zh: '长计算',
      ar: 'مهمة طويلة',
      es: 'Cálculo largo',
      fr: 'Calcul long',
      hi: 'लंबा हिसाब',
      id: 'Hitungan panjang',
      pt: 'Cálculo longo',
    },
    'label.click': {
      en: 'Click {no}',
      ko: '클릭 {no}',
      ja: 'クリック{no}',
      zh: '点击{no}',
      ar: 'النقرة {no}',
      es: 'Clic {no}',
      fr: 'Clic {no}',
      hi: 'क्लिक {no}',
      id: 'Klik {no}',
      pt: 'Clique {no}',
    },
    'label.wait': {
      en: 'Wait: {waitMs}ms',
      ko: '기다림: {waitMs}ms',
      ja: '待ち: {waitMs}ミリ秒',
      zh: '等待：{waitMs}毫秒',
      ar: 'الانتظار: {waitMs} مللي ثانية',
      es: 'Espera: {waitMs}ms',
      fr: 'Attente : {waitMs}ms',
      hi: 'प्रतीक्षा: {waitMs}ms',
      id: 'Menunggu: {waitMs}ms',
      pt: 'Espera: {waitMs}ms',
    },
  },
  blocks: {
    stage: { type: 'long-task-blocks-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
