import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 출력의 틀림은 앞쪽 무게 각각에 얼마씩 돌아가는가.
 */
export const errorFlowsBackwardFacet: FacetJson = {
  id: 'facet:errorFlowsBackward',
  title: {
    en: 'Error flows backward',
    ko: '틀림은 뒤로 갈라져 흐른다',
    ja: '誤差は後ろへ枝分かれして流れる',
    zh: '误差沿分支向后分流',
    ar: 'الخطأ يتدفق إلى الخلف',
    es: 'El error fluye hacia atrás',
    fr: "L'erreur remonte en arrière",
    hi: 'त्रुटि पीछे की ओर बहती है',
    id: 'Galat mengalir ke belakang',
    pt: 'O erro flui para trás',
  },
  description: {
    en: 'The output error splits over its branches in proportion to their weights; a negative weight flips its sign.',
    ko: '출력의 틀림이 가지 무게에 비례해 갈라져 뒤로 흐르고, 음수 무게를 지난 몫은 부호가 뒤집힌다.',
    ja: '出力の誤差は枝の重みに比例して分かれて後ろへ流れ、負の重みを通った分は符号が反転する。',
    zh: '输出误差按分支权重成比例地分开并向后流动，经过负权重的那一份符号会翻转。',
    ar: 'ينقسم خطأ المخرج على الفروع بنسبة أوزانها، والوزن السالب يقلب إشارة حصته.',
    es: 'El error de salida se reparte entre las ramas en proporción a sus pesos; un peso negativo invierte su signo.',
    fr: "L'erreur de sortie se répartit sur les branches en proportion de leurs poids ; un poids négatif inverse son signe.",
    hi: 'आउटपुट की त्रुटि शाखाओं के भार के अनुपात में बँटकर पीछे बहती है; ऋणात्मक भार से गुज़रा हिस्सा चिह्न उलट देता है।',
    id: 'Galat keluaran terbagi ke cabang-cabang sebanding dengan bobotnya; bobot negatif membalik tandanya.',
    pt: 'O erro da saída se divide pelos ramos na proporção dos pesos; um peso negativo inverte o sinal.',
  },
  algorithm: 'module:errorFlowsBackward',
  scene: 'module:errorFlowsBackwardScene',
  initialData: {
    type: 'error-flows-backward',
    stepMs: 2400,
    x: [1.0, 0.6],
    W1: [
      [0.4, 0.2],
      [-0.3, 0.8],
      [0.6, -0.1],
    ],
    w2: [0.9, -0.5, 0.4],
    y: 1.2,
  },
  shuffleOnReset: false,
  messages: {
    'caption.forward': {
      en: 'Forward pass done — ŷ: {yhat} · target y: {y} · loss L: {loss}',
      ko: '앞으로 셈이 끝났다 — ŷ: {yhat} · 목표 y: {y} · 손실 L: {loss}',
      ja: '順方向の計算は終わった — ŷ: {yhat} · 目標 y: {y} · 損失 L: {loss}',
      zh: '前向计算已完成 — ŷ: {yhat} · 目标 y: {y} · 损失 L: {loss}',
      ar: 'انتهى الحساب الأمامي — ŷ: {yhat} · الهدف y: {y} · الخسارة L: {loss}',
      es: 'Pasada hacia delante hecha — ŷ: {yhat} · objetivo y: {y} · pérdida L: {loss}',
      fr: 'Passe avant terminée — ŷ : {yhat} · cible y : {y} · perte L : {loss}',
      hi: 'आगे की गणना पूरी — ŷ: {yhat} · लक्ष्य y: {y} · हानि L: {loss}',
      id: 'Hitungan maju selesai — ŷ: {yhat} · target y: {y} · loss L: {loss}',
      pt: 'Passagem direta feita — ŷ: {yhat} · alvo y: {y} · perda L: {loss}',
    },
    'caption.error': {
      en: 'Error at the output: δ = ŷ − y = {d}',
      ko: '출력의 틀림: δ = ŷ − y = {d}',
      ja: '出力の誤差: δ = ŷ − y = {d}',
      zh: '输出的误差: δ = ŷ − y = {d}',
      ar: 'الخطأ عند المخرج: δ = ŷ − y = {d}',
      es: 'Error en la salida: δ = ŷ − y = {d}',
      fr: 'Erreur en sortie : δ = ŷ − y = {d}',
      hi: 'आउटपुट पर त्रुटि: δ = ŷ − y = {d}',
      id: 'Galat di keluaran: δ = ŷ − y = {d}',
      pt: 'Erro na saída: δ = ŷ − y = {d}',
    },
    'caption.hidden': {
      en: 'It splits by branch weight: δ_h = w · δ — sign flipped at: {ids}',
      ko: '가지 무게대로 갈라진다: δ_h = w · δ — 부호가 뒤집힌 곳: {ids}',
      ja: '枝の重みで分かれる: δ_h = w · δ — 符号が反転した所: {ids}',
      zh: '按分支权重分开: δ_h = w · δ — 符号翻转处: {ids}',
      ar: 'ينقسم بحسب وزن الفرع: δ_h = w · δ — انقلبت الإشارة عند: {ids}',
      es: 'Se reparte según el peso de la rama: δ_h = w · δ — signo invertido en: {ids}',
      fr: 'Il se répartit selon le poids de la branche : δ_h = w · δ — signe inversé en : {ids}',
      hi: 'शाखा के भार से बँटता है: δ_h = w · δ — चिह्न उलटा यहाँ: {ids}',
      id: 'Terbagi menurut bobot cabang: δ_h = w · δ — tanda terbalik di: {ids}',
      pt: 'Divide-se pelo peso do ramo: δ_h = w · δ — sinal invertido em: {ids}',
    },
    'caption.hiddenNoFlip': {
      en: 'It splits by branch weight: δ_h = w · δ',
      ko: '가지 무게대로 갈라진다: δ_h = w · δ',
      ja: '枝の重みで分かれる: δ_h = w · δ',
      zh: '按分支权重分开: δ_h = w · δ',
      ar: 'ينقسم بحسب وزن الفرع: δ_h = w · δ',
      es: 'Se reparte según el peso de la rama: δ_h = w · δ',
      fr: 'Il se répartit selon le poids de la branche : δ_h = w · δ',
      hi: 'शाखा के भार से बँटता है: δ_h = w · δ',
      id: 'Terbagi menurut bobot cabang: δ_h = w · δ',
      pt: 'Divide-se pelo peso do ramo: δ_h = w · δ',
    },
    'caption.hiddenGrad': {
      en: 'Left on each branch: ∂L/∂w = δ · h',
      ko: '가지마다 남는 기울기: ∂L/∂w = δ · h',
      ja: '各枝に残る勾配: ∂L/∂w = δ · h',
      zh: '每条分支留下的梯度: ∂L/∂w = δ · h',
      ar: 'ما يبقى على كل فرع: ∂L/∂w = δ · h',
      es: 'Queda en cada rama: ∂L/∂w = δ · h',
      fr: 'Reste sur chaque branche : ∂L/∂w = δ · h',
      hi: 'हर शाखा पर बचा प्रवणता: ∂L/∂w = δ · h',
      id: 'Tertinggal di tiap cabang: ∂L/∂w = δ · h',
      pt: 'Fica em cada ramo: ∂L/∂w = δ · h',
    },
    'caption.inputs': {
      en: 'Each share splits again over its input branches',
      ko: '각 몫이 다시 입력 가지로 갈라진다',
      ja: '各々の分け前が再び入力の枝へ分かれる',
      zh: '每一份再分到各自的输入分支',
      ar: 'تنقسم كل حصة مرة أخرى على فروع مدخلاتها',
      es: 'Cada parte se reparte de nuevo por sus ramas de entrada',
      fr: "Chaque part se répartit à nouveau sur ses branches d'entrée",
      hi: 'हर हिस्सा फिर अपनी इनपुट शाखाओं में बँटता है',
      id: 'Tiap bagian terbagi lagi ke cabang masukannya',
      pt: 'Cada parte se divide de novo pelos ramos de entrada',
    },
    'caption.inputsGrad': {
      en: 'Left on each branch: ∂L/∂W1 = δ_h · x',
      ko: '가지마다 남는 기울기: ∂L/∂W1 = δ_h · x',
      ja: '各枝に残る勾配: ∂L/∂W1 = δ_h · x',
      zh: '每条分支留下的梯度: ∂L/∂W1 = δ_h · x',
      ar: 'ما يبقى على كل فرع: ∂L/∂W1 = δ_h · x',
      es: 'Queda en cada rama: ∂L/∂W1 = δ_h · x',
      fr: 'Reste sur chaque branche : ∂L/∂W1 = δ_h · x',
      hi: 'हर शाखा पर बचा प्रवणता: ∂L/∂W1 = δ_h · x',
      id: 'Tertinggal di tiap cabang: ∂L/∂W1 = δ_h · x',
      pt: 'Fica em cada ramo: ∂L/∂W1 = δ_h · x',
    },
  },
  blocks: {
    stage: { type: 'error-flows-backward-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
