import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * @notation native
 *
 * 질문: B+ 트리에서 찾는 열쇠를 위층에서 이미 만났는데 왜 끝까지 내려가는가.
 *
 * 화면의 질의 글자는 SQL 이다 (SQL) — 이 분야의 소재 자체라 가상 표기로 옮기지 않는다.
 * 트리 구조 · 줄 · 찾기 셋은 사양이 준 그대로다. 읽은 페이지 · 고른 가지 · 쥔 값은 알고리즘이 셈한다.
 */
export const allDataInLeavesFacet: FacetJson = {
  id: 'facet:allDataInLeaves',
  title: {
    en: 'Values live only in the leaves',
    ko: '값은 잎에만 있다',
    ja: '値はリーフにだけある',
    zh: '值只在叶子里',
    ar: 'القيم في الأوراق فقط',
    es: 'Los valores solo están en las hojas',
    fr: 'Les valeurs ne sont que dans les feuilles',
    hi: 'मान केवल पत्तों में होते हैं',
    id: 'Nilai hanya ada di daun',
    pt: 'Os valores só ficam nas folhas',
  },
  description: {
    en: 'In a B+ tree, why keep descending after the search key already appears on an upper page?',
    ko: 'B+ 트리에서 찾는 열쇠를 위층에서 이미 만났는데 왜 끝까지 내려가는가?',
    ja: 'B+ 木で、探すキーを上の階層ですでに見たのに、なぜ最後まで降りるのか？',
    zh: '在 B+ 树中，要找的键已经在上层出现了，为什么还要一直往下走？',
    ar: 'في شجرة B+، لماذا نواصل النزول بعد أن يظهر مفتاح البحث في صفحة أعلى؟',
    es: 'En un árbol B+, ¿por qué seguir bajando si la clave buscada ya apareció en una página superior?',
    fr: 'Dans un arbre B+, pourquoi continuer à descendre alors que la clé cherchée est déjà apparue plus haut ?',
    hi: 'B+ ट्री में खोजी जा रही कुंजी ऊपर के पेज पर दिख जाने के बाद भी नीचे तक क्यों उतरते हैं?',
    id: 'Di pohon B+, mengapa terus turun padahal kunci yang dicari sudah muncul di halaman atas?',
    pt: 'Numa árvore B+, por que continuar descendo se a chave procurada já apareceu numa página de cima?',
  },
  algorithm: 'module:allDataInLeaves',
  scene: 'module:allDataInLeavesScene',
  initialData: {
    type: 'all-data-in-leaves',
    index: 'users_pkey',
    root: 'R',
    pages: [
      { id: 'R', kind: 'inner', keys: [30, 60], children: ['I1', 'I2', 'I3'] },
      { id: 'I1', kind: 'inner', keys: [15], children: ['L1', 'L2'] },
      { id: 'I2', kind: 'inner', keys: [45], children: ['L3', 'L4'] },
      { id: 'I3', kind: 'inner', keys: [75], children: ['L5', 'L6'] },
      { id: 'L1', kind: 'leaf', keys: [4, 9], names: ['Ana', 'Ben'] },
      { id: 'L2', kind: 'leaf', keys: [15, 22], names: ['Cy', 'Dan'] },
      { id: 'L3', kind: 'leaf', keys: [30, 38], names: ['Eve', 'Fay'] },
      { id: 'L4', kind: 'leaf', keys: [45, 52], names: ['Gus', 'Hal'] },
      { id: 'L5', kind: 'leaf', keys: [60, 67], names: ['Ivy', 'Jo'] },
      { id: 'L6', kind: 'leaf', keys: [75, 83], names: ['Kai', 'Lu'] },
    ],
    lookups: [
      { key: 60, sql: 'WHERE id = 60' },
      { key: 45, sql: 'WHERE id = 45' },
      { key: 22, sql: 'WHERE id = 22' },
    ],
    stepMs: 1100,
  },
  shuffleOnReset: false,
  messages: {
    'caption.seen': {
      en: '{key} is on this page, but no value is stored here. Next page: {next}.',
      ko: '열쇠 {key} — 이 페이지에 있지만 값은 여기 없다. 다음 페이지: {next}.',
      ja: 'キー {key} はこのページにあるが、値はここにない。次のページ：{next}。',
      zh: '键 {key} 在这一页上，但这里没有值。下一页：{next}。',
      ar: 'المفتاح {key} في هذه الصفحة، لكن لا قيمة مخزنة هنا. الصفحة التالية: {next}.',
      es: '{key} está en esta página, pero aquí no hay valor. Página siguiente: {next}.',
      fr: '{key} est sur cette page, mais aucune valeur n’y est stockée. Page suivante : {next}.',
      hi: '{key} इस पेज पर है, पर यहाँ कोई मान नहीं है। अगला पेज: {next}।',
      id: '{key} ada di halaman ini, tetapi tidak ada nilai di sini. Halaman berikutnya: {next}.',
      pt: '{key} está nesta página, mas aqui não há valor. Próxima página: {next}.',
    },
    'caption.pass': {
      en: 'No {key} on this page. Next page: {next}.',
      ko: '열쇠 {key} — 이 페이지에는 없다. 다음 페이지: {next}.',
      ja: 'キー {key} はこのページにない。次のページ：{next}。',
      zh: '这一页上没有 {key}。下一页：{next}。',
      ar: 'لا يوجد {key} في هذه الصفحة. الصفحة التالية: {next}.',
      es: 'No hay {key} en esta página. Página siguiente: {next}.',
      fr: 'Pas de {key} sur cette page. Page suivante : {next}.',
      hi: '{key} इस पेज पर नहीं है। अगला पेज: {next}।',
      id: 'Tidak ada {key} di halaman ini. Halaman berikutnya: {next}.',
      pt: 'Não há {key} nesta página. Próxima página: {next}.',
    },
    'caption.leaf': {
      en: 'Leaf {page}: the row is here. Value: {value}.',
      ko: '잎 {page} — 줄이 여기 있다. 값: {value}.',
      ja: 'リーフ {page}：行はここにある。値：{value}。',
      zh: '叶子 {page}：行就在这里。值：{value}。',
      ar: 'الورقة {page}: الصف هنا. القيمة: {value}.',
      es: 'Hoja {page}: la fila está aquí. Valor: {value}.',
      fr: 'Feuille {page} : la ligne est ici. Valeur : {value}.',
      hi: 'पत्ता {page}: पंक्ति यहीं है। मान: {value}।',
      id: 'Daun {page}: barisnya ada di sini. Nilai: {value}.',
      pt: 'Folha {page}: a linha está aqui. Valor: {value}.',
    },
    'label.pagesRead': {
      en: 'Pages read: {n}',
      ko: '읽은 페이지: {n}',
      ja: '読んだページ：{n}',
      zh: '已读页数：{n}',
      ar: 'الصفحات المقروءة: {n}',
      es: 'Páginas leídas: {n}',
      fr: 'Pages lues : {n}',
      hi: 'पढ़े गए पेज: {n}',
      id: 'Halaman dibaca: {n}',
      pt: 'Páginas lidas: {n}',
    },
    'legend.seen': {
      en: 'key seen, no value',
      ko: '열쇠 봄 · 값 없음',
      ja: 'キーを見た・値なし',
      zh: '见到键，无值',
      ar: 'مفتاح بلا قيمة',
      es: 'clave vista, sin valor',
      fr: 'clé vue, sans valeur',
      hi: 'कुंजी दिखी, मान नहीं',
      id: 'kunci terlihat, tanpa nilai',
      pt: 'chave vista, sem valor',
    },
    'legend.value': {
      en: 'value',
      ko: '값',
      ja: '値',
      zh: '值',
      ar: 'القيمة',
      es: 'valor',
      fr: 'valeur',
      hi: 'मान',
      id: 'nilai',
      pt: 'valor',
    },
  },
  blocks: {
    stage: { type: 'all-data-in-leaves-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
