import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * matrix-ops 의 1차 데이터 — 변환 여섯 · 점 넷 · 손잡이 사다리.
 * 행렬은 행 차례 평평한 배열 [a, b, c, d] = [a b ; c d]. 곱 · det · 옮긴 자리 · 개수는 알고리즘이 셈한다.
 * 기호(R · R⁻¹ · H · S · F · P)는 번역하지 않는 자료이고, 변환의 표시 이름은 messages 의 label.map.* 다.
 */
export type MatrixOpsInitialData = {
  type: 'matrix-ops';
  stepMs: number;
  motionMs: number;
  maps: { id: string; m: number[] }[];
  symbols: string[];
  points: number[][];
  mapLadder: number[];
  firstMap: number;
  secondMap: number;
};

export const matrixOpsInitialData: MatrixOpsInitialData = {
  type: 'matrix-ops',
  stepMs: 1600,
  motionMs: 600,
  maps: [
    { id: 'R', m: [0, -1, 1, 0] },
    { id: 'Rinv', m: [0, 1, -1, 0] },
    { id: 'H', m: [1, 1, 0, 1] },
    { id: 'S', m: [1, 0, 0, 2] },
    { id: 'F', m: [1, 0, 0, -1] },
    { id: 'P', m: [1, 0, 0, 0] },
  ],
  symbols: ['R', 'R⁻¹', 'H', 'S', 'F', 'P'],
  points: [
    [1, 1],
    [2, -1],
    [-1, 2],
    [1, 2],
  ],
  mapLadder: [0, 1, 2, 3, 4, 5],
  firstMap: 2,
  secondMap: 3,
};

export const matrixOpsFacet: FacetJson = {
  id: 'facet:matrixOps',
  title: {
    en: 'Chaining Transformations with Matrix Products',
    ko: '변환을 잇는 행렬 곱',
    ja: '変換をつなぐ行列の積',
    zh: '串联变换的矩阵乘法',
    ar: 'ضرب المصفوفات لربط التحويلات',
    es: 'Producto de matrices que encadena transformaciones',
    fr: 'Le produit matriciel qui enchaîne les transformations',
    hi: 'रूपांतरणों को जोड़ने वाला मैट्रिक्स गुणन',
    id: 'Perkalian matriks yang merangkai transformasi',
    pt: 'Produto de matrizes que encadeia transformações',
  },
  description: {
    en: 'Four points jump twice, first by X and then by Y, then jump once from home by the product YX so the two landings can be compared. For each pair, count how many points jumped by the swapped product XY land where YX sends them, how many come back home, and how many distinct spots the points land on.',
    ko: '점 넷이 먼저 X, 다음 Y 로 두 번 뛴 뒤, 처음 자리에서 곱 YX 로 한 번에 뛰어 두 도착을 견준다. 짝마다 차례를 바꾼 XY 로 뛴 점 가운데 YX 와 같은 곳에 선 점, 제자리로 온 점, 점들이 선 서로 다른 자리를 센다.',
    ja: '4つの点が先に X、次に Y で2回跳び、そのあと最初の位置から積 YX で一度に跳んで2つの着地を比べる。組ごとに、順序を入れ替えた XY で跳んだ点のうち YX と同じ位置に立つ点、元の位置に戻る点、点が立つ異なる位置の数を数える。',
    zh: '四个点先用 X、再用 Y 跳两次，然后从起点用乘积 YX 一次跳过去，比较两次落点。每一对变换都数一数：用交换顺序的 XY 跳的点中有几个与 YX 同位置，有几个回到原位，点落在几个不同的位置。',
    ar: 'تقفز أربع نقاط مرتين، أولًا بـ X ثم بـ Y، ثم تقفز مرة واحدة من البداية بالحاصل YX لمقارنة موضعي الهبوط. لكل زوج نعدّ النقاط التي قفزت بالحاصل المعكوس XY وهبطت حيث يرسلها YX، والنقاط التي عادت إلى مكانها، وعدد المواضع المختلفة التي هبطت فيها النقاط.',
    es: 'Cuatro puntos saltan dos veces, primero con X y después con Y, y luego saltan una sola vez desde el inicio con el producto YX para comparar las llegadas. Para cada par se cuenta cuántos puntos saltados con el producto invertido XY caen donde los lleva YX, cuántos vuelven al inicio y en cuántos sitios distintos caen.',
    fr: 'Quatre points sautent deux fois, d’abord par X puis par Y, puis sautent une seule fois depuis le départ par le produit YX pour comparer les arrivées. Pour chaque paire, on compte les points sautés par le produit inversé XY qui tombent là où YX les envoie, ceux qui reviennent au départ et le nombre de places distinctes occupées.',
    hi: 'चार बिंदु पहले X से और फिर Y से दो बार छलाँग लगाते हैं, फिर शुरुआती जगह से गुणनफल YX से एक ही छलाँग लगाते हैं ताकि दोनों पहुँच की तुलना हो सके। हर जोड़ी के लिए गिनते हैं कि उलटे क्रम XY से कूदे कितने बिंदु वहीं पहुँचते हैं जहाँ YX भेजता है, कितने अपनी जगह लौटते हैं, और बिंदु कितनी अलग जगहों पर पहुँचते हैं।',
    id: 'Empat titik melompat dua kali, pertama dengan X lalu dengan Y, kemudian melompat sekali dari posisi awal dengan hasil kali YX untuk membandingkan tempat mendaratnya. Untuk setiap pasangan dihitung berapa titik yang dilompatkan dengan urutan terbalik XY mendarat di tempat YX, berapa yang kembali ke awal, dan berapa posisi berbeda yang ditempati.',
    pt: 'Quatro pontos saltam duas vezes, primeiro por X e depois por Y, e então saltam uma só vez do início pelo produto YX para comparar as chegadas. Para cada par, conta-se quantos pontos saltados pelo produto trocado XY caem onde YX os leva, quantos voltam ao início e em quantos lugares distintos os pontos caem.',
  },
  algorithm: 'module:matrixOps',
  projector: 'module:matrixOpsProjector',
  initialData: matrixOpsInitialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'matrix-ops-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'firstMap',
          name: 'firstMap',
          label: { en: 'First', ko: '먼저', ja: '先に', zh: '先', ar: 'أولًا', es: 'Primero', fr: 'D’abord', hi: 'पहले', id: 'Pertama', pt: 'Primeiro' },
          segments: [
            { value: 0, label: 'R' },
            { value: 1, label: 'R⁻¹' },
            { value: 2, label: 'H', default: true },
            { value: 3, label: 'S' },
            { value: 4, label: 'F' },
            { value: 5, label: 'P' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'secondMap',
          name: 'secondMap',
          label: { en: 'Then', ko: '다음', ja: '次に', zh: '再', ar: 'ثم', es: 'Después', fr: 'Puis', hi: 'फिर', id: 'Lalu', pt: 'Depois' },
          segments: [
            { value: 0, label: 'R' },
            { value: 1, label: 'R⁻¹' },
            { value: 2, label: 'H' },
            { value: 3, label: 'S', default: true },
            { value: 4, label: 'F' },
            { value: 5, label: 'P' },
          ],
        },
      ],
      metrics: [
        {
          name: 'same-spot',
          label: { en: 'Same spot', ko: '같은 곳', ja: '同じ位置', zh: '同一位置', ar: 'نفس الموضع', es: 'Mismo sitio', fr: 'Même place', hi: 'समान जगह', id: 'Tempat sama', pt: 'Mesmo lugar' },
          initial: 0,
        },
        {
          name: 'back-home',
          label: { en: 'Back home', ko: '제자리', ja: '元の位置', zh: '回到原位', ar: 'في مكانها', es: 'De vuelta', fr: 'Revenus', hi: 'अपनी जगह', id: 'Kembali', pt: 'De volta' },
          initial: 0,
        },
        {
          name: 'landing-spots',
          label: { en: 'Landing spots', ko: '도착 자리', ja: '着地点', zh: '落点', ar: 'مواضع الهبوط', es: 'Sitios de llegada', fr: 'Places d’arrivée', hi: 'पहुँच की जगहें', id: 'Posisi mendarat', pt: 'Lugares de chegada' },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:matrix-ops-imperative',
      label: { en: 'Code', ko: '코드', ja: 'コード', zh: '代码', ar: 'الشيفرة', es: 'Código', fr: 'Code', hi: 'कोड', id: 'Kode', pt: 'Código' },
    },
  },
  messages: {
    'label.map.R': {
      en: 'Quarter turn counterclockwise',
      ko: '반시계로 직각',
      ja: '反時計回りに直角',
      zh: '逆时针转直角',
      ar: 'ربع دورة عكس عقارب الساعة',
      es: 'Cuarto de vuelta antihorario',
      fr: 'Quart de tour antihoraire',
      hi: 'वामावर्त चौथाई घुमाव',
      id: 'Seperempat putaran berlawanan jarum jam',
      pt: 'Quarto de volta anti-horário',
    },
    'label.map.Rinv': {
      en: 'Quarter turn clockwise',
      ko: '시계로 직각',
      ja: '時計回りに直角',
      zh: '顺时针转直角',
      ar: 'ربع دورة مع عقارب الساعة',
      es: 'Cuarto de vuelta horario',
      fr: 'Quart de tour horaire',
      hi: 'दक्षिणावर्त चौथाई घुमाव',
      id: 'Seperempat putaran searah jarum jam',
      pt: 'Quarto de volta horário',
    },
    'label.map.H': {
      en: 'Shear sideways',
      ko: '옆으로 밀기',
      ja: '横にずらす',
      zh: '横向错切',
      ar: 'قص جانبي',
      es: 'Cizalla lateral',
      fr: 'Cisaillement latéral',
      hi: 'बगल की ओर खिसकाना',
      id: 'Geser ke samping',
      pt: 'Cisalhamento lateral',
    },
    'label.map.S': {
      en: 'Double vertically',
      ko: '세로 두 배',
      ja: '縦に2倍',
      zh: '纵向两倍',
      ar: 'مضاعفة رأسية',
      es: 'Doble en vertical',
      fr: 'Double en hauteur',
      hi: 'ऊर्ध्वाधर दोगुना',
      id: 'Dua kali vertikal',
      pt: 'Dobro na vertical',
    },
    'label.map.F': {
      en: 'Flip upside down',
      ko: '위아래 뒤집기',
      ja: '上下反転',
      zh: '上下翻转',
      ar: 'قلب رأسي',
      es: 'Voltear arriba-abajo',
      fr: 'Retournement haut-bas',
      hi: 'ऊपर-नीचे पलटना',
      id: 'Balik atas-bawah',
      pt: 'Virar de cabeça para baixo',
    },
    'label.map.P': {
      en: 'Flatten onto the x-axis',
      ko: '가로축으로 납작',
      ja: 'x軸へ押しつぶす',
      zh: '压扁到横轴',
      ar: 'تسطيح على المحور الأفقي',
      es: 'Aplastar sobre el eje x',
      fr: 'Écraser sur l’axe des x',
      hi: 'x-अक्ष पर चपटा करना',
      id: 'Pipihkan ke sumbu x',
      pt: 'Achatar no eixo x',
    },
    'label.stack': {
      en: '×{n}',
      ko: '×{n}',
      ja: '×{n}',
      zh: '×{n}',
      ar: '×{n}',
      es: '×{n}',
      fr: '×{n}',
      hi: '×{n}',
      id: '×{n}',
      pt: '×{n}',
    },
    'label.detOf': {
      en: 'det {name} = {d}',
      ko: 'det {name} = {d}',
      ja: 'det {name} = {d}',
      zh: 'det {name} = {d}',
      ar: 'det {name} = {d}',
      es: 'det {name} = {d}',
      fr: 'det {name} = {d}',
      hi: 'det {name} = {d}',
      id: 'det {name} = {d}',
      pt: 'det {name} = {d}',
    },
    'label.first': {
      en: 'First',
      ko: '먼저',
      ja: '先に',
      zh: '先',
      ar: 'أولًا',
      es: 'Primero',
      fr: 'D’abord',
      hi: 'पहले',
      id: 'Pertama',
      pt: 'Primeiro',
    },
    'label.then': {
      en: 'Then',
      ko: '다음',
      ja: '次に',
      zh: '再',
      ar: 'ثم',
      es: 'Después',
      fr: 'Puis',
      hi: 'फिर',
      id: 'Lalu',
      pt: 'Depois',
    },
    'label.legend.home': {
      en: 'Home',
      ko: '처음 자리',
      ja: '最初の位置',
      zh: '起点',
      ar: 'نقطة البداية',
      es: 'Inicio',
      fr: 'Départ',
      hi: 'शुरुआती जगह',
      id: 'Posisi awal',
      pt: 'Início',
    },
    'label.legend.dot': {
      en: 'Two jumps',
      ko: '두 번 뛰는 점',
      ja: '2回跳ぶ点',
      zh: '跳两次的点',
      ar: 'قفزتان',
      es: 'Dos saltos',
      fr: 'Deux sauts',
      hi: 'दो छलाँग',
      id: 'Dua lompatan',
      pt: 'Dois saltos',
    },
    'label.legend.ring': {
      en: 'YX in one jump',
      ko: 'YX 로 한 번에',
      ja: 'YX で一度に',
      zh: '用 YX 一次跳',
      ar: 'YX بقفزة واحدة',
      es: 'YX en un salto',
      fr: 'YX en un seul saut',
      hi: 'YX से एक छलाँग में',
      id: 'YX sekali lompat',
      pt: 'YX em um salto',
    },
    'label.legend.ghost': {
      en: 'XY in one jump',
      ko: 'XY 로 한 번에',
      ja: 'XY で一度に',
      zh: '用 XY 一次跳',
      ar: 'XY بقفزة واحدة',
      es: 'XY en un salto',
      fr: 'XY en un seul saut',
      hi: 'XY से एक छलाँग में',
      id: 'XY sekali lompat',
      pt: 'XY em um salto',
    },
    'label.product': {
      en: 'One matrix for both',
      ko: '둘을 행렬 하나로',
      ja: '二つを一つの行列に',
      zh: '两步合成一个矩阵',
      ar: 'مصفوفة واحدة للاثنين',
      es: 'Una matriz para ambos',
      fr: 'Une matrice pour les deux',
      hi: 'दोनों के लिए एक मैट्रिक्स',
      id: 'Satu matriks untuk keduanya',
      pt: 'Uma matriz para os dois',
    },
    'label.detProduct': {
      en: 'det Y × det X = {dy} × {dx} = {d}',
      ko: 'det Y × det X = {dy} × {dx} = {d}',
      ja: 'det Y × det X = {dy} × {dx} = {d}',
      zh: 'det Y × det X = {dy} × {dx} = {d}',
      ar: 'det Y × det X = {dy} × {dx} = {d}',
      es: 'det Y × det X = {dy} × {dx} = {d}',
      fr: 'det Y × det X = {dy} × {dx} = {d}',
      hi: 'det Y × det X = {dy} × {dx} = {d}',
      id: 'det Y × det X = {dy} × {dx} = {d}',
      pt: 'det Y × det X = {dy} × {dx} = {d}',
    },
    'label.swapped': {
      en: 'Order swapped',
      ko: '차례를 바꾼 곱',
      ja: '順序を入れ替えた積',
      zh: '交换顺序的积',
      ar: 'بترتيب معكوس',
      es: 'Orden invertido',
      fr: 'Ordre inversé',
      hi: 'क्रम बदला हुआ',
      id: 'Urutan ditukar',
      pt: 'Ordem trocada',
    },
    'label.sameSpot': {
      en: 'Same spot as YX: {s} / {total}',
      ko: 'YX 와 같은 곳 {s} / {total}',
      ja: 'YX と同じ位置 {s} / {total}',
      zh: '与 YX 同位置 {s} / {total}',
      ar: 'نفس موضع YX: {s} / {total}',
      es: 'Mismo sitio que YX: {s} / {total}',
      fr: 'Même place que YX : {s} / {total}',
      hi: 'YX जैसी जगह: {s} / {total}',
      id: 'Sama dengan YX: {s} / {total}',
      pt: 'Mesmo lugar que YX: {s} / {total}',
    },
    'caption.round': {
      en: 'First X = {x}, then Y = {y} · points at home: {n}',
      ko: '먼저 X = {x} · 다음 Y = {y} · 처음 자리의 점 {n}',
      ja: '先に X = {x}、次に Y = {y} · 最初の位置の点 {n}',
      zh: '先 X = {x}，再 Y = {y} · 起点上的点 {n}',
      ar: 'أولًا X = {x}، ثم Y = {y} · نقاط في البداية: {n}',
      es: 'Primero X = {x}, después Y = {y} · puntos en el inicio: {n}',
      fr: 'D’abord X = {x}, puis Y = {y} · points au départ : {n}',
      hi: 'पहले X = {x}, फिर Y = {y} · शुरुआती जगह पर बिंदु: {n}',
      id: 'Pertama X = {x}, lalu Y = {y} · titik di posisi awal: {n}',
      pt: 'Primeiro X = {x}, depois Y = {y} · pontos no início: {n}',
    },
    'caption.jumpX': {
      en: 'Jump by X → spots: {n}',
      ko: 'X 로 뛴다 → 자리 {n}',
      ja: 'X で跳ぶ → 位置 {n}',
      zh: '用 X 跳 → 位置 {n}',
      ar: 'قفزة بـ X → مواضع: {n}',
      es: 'Salto con X → sitios: {n}',
      fr: 'Saut par X → places : {n}',
      hi: 'X से छलाँग → जगहें: {n}',
      id: 'Lompat dengan X → posisi: {n}',
      pt: 'Salto por X → lugares: {n}',
    },
    'caption.jumpY': {
      en: 'Jump by Y → spots: {n} · back home: {h} / {total}',
      ko: 'Y 로 뛴다 → 자리 {n} · 제자리 {h} / {total}',
      ja: 'Y で跳ぶ → 位置 {n} · 元の位置 {h} / {total}',
      zh: '用 Y 跳 → 位置 {n} · 回到原位 {h} / {total}',
      ar: 'قفزة بـ Y → مواضع: {n} · عادت إلى مكانها: {h} / {total}',
      es: 'Salto con Y → sitios: {n} · de vuelta al inicio: {h} / {total}',
      fr: 'Saut par Y → places : {n} · revenus au départ : {h} / {total}',
      hi: 'Y से छलाँग → जगहें: {n} · अपनी जगह पर: {h} / {total}',
      id: 'Lompat dengan Y → posisi: {n} · kembali ke awal: {h} / {total}',
      pt: 'Salto por Y → lugares: {n} · de volta ao início: {h} / {total}',
    },
    'caption.product': {
      en: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      ko: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      ja: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      zh: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      ar: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      es: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      fr: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      hi: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      id: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
      pt: 'YX = {m} · det Y × det X = {dy} × {dx} = {d}',
    },
    'caption.once': {
      en: 'From home by YX in one jump → same as two jumps: {k} / {total}',
      ko: '처음 자리에서 YX 로 한 번에 → 두 번 간 자리와 같은 점 {k} / {total}',
      ja: '最初の位置から YX で一度に → 2回跳んだ位置と同じ点 {k} / {total}',
      zh: '从起点用 YX 一次跳 → 与跳两次同位置的点 {k} / {total}',
      ar: 'من البداية بـ YX بقفزة واحدة → مثل القفزتين: {k} / {total}',
      es: 'Desde el inicio con YX en un salto → igual que dos saltos: {k} / {total}',
      fr: 'Du départ par YX en un saut → comme les deux sauts : {k} / {total}',
      hi: 'शुरुआत से YX से एक छलाँग में → दो छलाँगों जैसी जगह: {k} / {total}',
      id: 'Dari awal dengan YX sekali lompat → sama dengan dua lompatan: {k} / {total}',
      pt: 'Do início por YX em um salto → igual aos dois saltos: {k} / {total}',
    },
    'caption.swapped': {
      en: 'XY = {m} in one jump → same spot as YX: {s} / {total}',
      ko: 'XY = {m} · 한 번에 뛴다 → YX 와 같은 곳 {s} / {total}',
      ja: 'XY = {m} で一度に → YX と同じ位置 {s} / {total}',
      zh: 'XY = {m} 一次跳 → 与 YX 同位置 {s} / {total}',
      ar: 'XY = {m} بقفزة واحدة → نفس موضع YX: {s} / {total}',
      es: 'XY = {m} en un salto → mismo sitio que YX: {s} / {total}',
      fr: 'XY = {m} en un saut → même place que YX : {s} / {total}',
      hi: 'XY = {m} से एक छलाँग में → YX जैसी जगह: {s} / {total}',
      id: 'XY = {m} sekali lompat → sama dengan YX: {s} / {total}',
      pt: 'XY = {m} em um salto → mesmo lugar que YX: {s} / {total}',
    },
  },
};
