/**
 * @piece
 * 일을 작은 마이크로태스크로 쪼개어 이어 걸면, 그 사이에 화면이 한 번이라도 다시
 * 그려지는가?
 *
 * @notation native — `queueMicrotask` 로 이어 건다는 것이 곧 주장이다
 * (`setTimeout` 이었다면 결과가 다르다). 화면의 코드는 사양의 자바스크립트
 * 그대로이며 줄을 바꾸거나 더하지 않는다.
 */
import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const microtaskStarvationFacet: FacetJson = {
  id: 'facet:microtaskStarvation',
  title: {
    en: 'Microtask Starvation',
    ko: '마이크로태스크 굶주림',
    ja: 'マイクロタスクの飢餓',
    zh: '微任务饥饿',
    ar: 'تجويع المهام الصغيرة',
    es: 'Inanición de microtareas',
    fr: 'Famine de microtâches',
    hi: 'माइक्रोटास्क भुखमरी',
    id: 'Kelaparan Microtask',
    pt: 'Inanição de microtarefas',
  },
  description: {
    en: 'A step that requeues itself on the microtask queue never lets the render get a turn.',
    ko: '마이크로태스크 줄에 스스로를 다시 세우는 걸음은 렌더에 차례를 내주지 않는다.',
    ja: 'マイクロタスクキューに自分自身を積み直すステップは、レンダリングに順番を渡さない。',
    zh: '不断把自己重新排进微任务队列的一步,永远不给渲染让出机会。',
    ar: 'خطوة تعيد جدولة نفسها في طابور المهام الصغيرة لا تمنح الرسم أي فرصة.',
    es: 'Un paso que se vuelve a encolar en la cola de microtareas nunca le da su turno al renderizado.',
    fr: 'Une étape qui se remet elle-même dans la file de microtâches ne laisse jamais sa place au rendu.',
    hi: 'एक कदम जो माइक्रोटास्क कतार में खुद को दोबारा जोड़ता है, रेंडर को कभी बारी नहीं देता।',
    id: 'Langkah yang mengantre ulang dirinya sendiri di antrean microtask tidak pernah memberi giliran untuk render.',
    pt: 'Um passo que se reenfileira na fila de microtarefas nunca dá espaço para a renderização.',
  },
  algorithm: 'module:microtaskStarvation',
  scene: 'module:microtaskStarvationScene',
  initialData: {
    type: 'microtask-starvation',
    stepMs: 1100,
    code: [
      'let n = 0;',
      'function step() {',
      '  busyFor(7);',
      '  el.textContent = ++n;',
      '  if (n < 8) queueMicrotask(step);',
      '}',
      'button.onclick = () => queueMicrotask(step);',
    ],
    workMs: 7,
    count: 8,
  },
  shuffleOnReset: false,
  messages: {
    'caption.initial': {
      en: 'Start — DOM {dom}, screen {screen}.',
      ko: '시작 — DOM {dom} · 화면 {screen}.',
      ja: '開始 — DOM {dom}・画面 {screen}。',
      zh: '开始 — DOM {dom} · 画面 {screen}。',
      ar: 'البداية — DOM {dom}، الشاشة {screen}.',
      es: 'Inicio — DOM {dom}, pantalla {screen}.',
      fr: 'Début — DOM {dom}, écran {screen}.',
      hi: 'शुरुआत — DOM {dom}, स्क्रीन {screen}.',
      id: 'Awal — DOM {dom}, layar {screen}.',
      pt: 'Início — DOM {dom}, tela {screen}.',
    },
    'caption.initialNote': {
      en: 'The microtask queue is empty.',
      ko: '마이크로 줄이 비어 있다.',
      ja: 'マイクロタスク待ち行列は空だ。',
      zh: '微任务队列是空的。',
      ar: 'طابور المهام الصغيرة فارغ.',
      es: 'La cola de microtareas está vacía.',
      fr: 'La file de microtâches est vide.',
      hi: 'माइक्रोटास्क कतार खाली है।',
      id: 'Antrean microtask kosong.',
      pt: 'A fila de microtarefas está vazia.',
    },
    'caption.click': {
      en: 'The click task queues one run on the microtask queue.',
      ko: 'click 태스크 — 마이크로 줄에 실행을 하나 세운다.',
      ja: 'click タスクがマイクロタスク待ち行列に実行を一つ積む。',
      zh: 'click 任务在微任务队列里排入一次执行。',
      ar: 'مهمة النقر تضع تشغيلًا واحدًا في طابور المهام الصغيرة.',
      es: 'La tarea de clic encola una ejecución en la cola de microtareas.',
      fr: 'La tâche du clic met une exécution dans la file de microtâches.',
      hi: 'क्लिक टास्क माइक्रोटास्क कतार में एक रन जोड़ता है।',
      id: 'Tugas klik mengantrekan satu jalannya di antrean microtask.',
      pt: 'A tarefa do clique enfileira uma execução na fila de microtarefas.',
    },
    'caption.clickNote': {
      en: 'It empties the queue once the task ends.',
      ko: '태스크가 끝나면 줄부터 비운다.',
      ja: 'タスクが終わるとまず待ち行列を空にする。',
      zh: '任务结束后先清空队列。',
      ar: 'بعد انتهاء المهمة، يُفرَّغ الطابور أولًا.',
      es: 'Al terminar la tarea, primero se vacía la cola.',
      fr: 'À la fin de la tâche, la file est vidée en premier.',
      hi: 'टास्क खत्म होते ही पहले कतार खाली होती है।',
      id: 'Begitu tugas selesai, antrean dikosongkan lebih dulu.',
      pt: 'Ao terminar a tarefa, a fila é esvaziada primeiro.',
    },
    'caption.step': {
      en: 'A run holds the stack for {workMs}ms — DOM {n}.',
      ko: '실행이 {workMs}ms 동안 스택을 잡는다 — DOM {n}.',
      ja: '実行が {workMs}ms の間スタックを握る — DOM {n}。',
      zh: '一次执行占住调用栈 {workMs}ms — DOM {n}。',
      ar: 'تشغيل واحد يمسك المكدس لمدة {workMs}ms — DOM {n}.',
      es: 'Una ejecución ocupa la pila durante {workMs}ms — DOM {n}.',
      fr: 'Une exécution occupe la pile pendant {workMs}ms — DOM {n}.',
      hi: 'एक रन {workMs}ms तक स्टैक पकड़े रहता है — DOM {n}.',
      id: 'Satu jalan menahan stack selama {workMs}ms — DOM {n}.',
      pt: 'Uma execução segura a pilha por {workMs}ms — DOM {n}.',
    },
    'caption.boundaryMissed': {
      en: 'Boundary {ms}ms passes with no render — screen stays {screen}.',
      ko: '경계 {ms}ms 지점 — 렌더 없이 지난다. 화면 값은 {screen} 그대로.',
      ja: '境界 {ms}ms を描画なしで通り過ぎる — 画面は {screen} のまま。',
      zh: '经过 {ms}ms 边界却没有渲染 — 画面仍是 {screen}。',
      ar: 'يمر حد {ms}ms دون رسم — تبقى الشاشة عند {screen}.',
      es: 'El límite de {ms}ms pasa sin renderizar — la pantalla sigue en {screen}.',
      fr: 'La frontière {ms}ms passe sans rendu — l’écran reste à {screen}.',
      hi: 'सीमा {ms}ms बिना रेंडर के गुज़र जाती है — स्क्रीन {screen} पर ही रहती है।',
      id: 'Batas {ms}ms lewat tanpa render — layar tetap {screen}.',
      pt: 'O limite de {ms}ms passa sem renderizar — a tela permanece em {screen}.',
    },
    'caption.stepRequeue': {
      en: 'It requeues itself before finishing — the queue never empties.',
      ko: '끝나기 전에 스스로를 다시 세운다 — 줄이 비지 않는다.',
      ja: '終わる前に自分自身を積み直す — 待ち行列は空にならない。',
      zh: '结束前把自己重新排队 — 队列不会清空。',
      ar: 'يعيد جدولة نفسه قبل الانتهاء — الطابور لا يفرغ أبدًا.',
      es: 'Se vuelve a encolar antes de terminar — la cola nunca se vacía.',
      fr: 'Elle se remet en file avant de finir — la file ne se vide jamais.',
      hi: 'खत्म होने से पहले खुद को फिर कतार में डालता है — कतार कभी खाली नहीं होती।',
      id: 'Ia mengantrekan dirinya lagi sebelum selesai — antrean tidak pernah kosong.',
      pt: 'Ela se reenfileira antes de terminar — a fila nunca esvazia.',
    },
    'caption.stepLast': {
      en: 'It stops requeuing — the queue is about to empty.',
      ko: '더 세우지 않는다 — 줄이 곧 빈다.',
      ja: 'もう積み直さない — 待ち行列はまもなく空になる。',
      zh: '不再重新排队 — 队列即将清空。',
      ar: 'يتوقف عن إعادة الجدولة — الطابور على وشك أن يفرغ.',
      es: 'Deja de volver a encolarse — la cola está por vaciarse.',
      fr: 'Elle arrête de se remettre en file — la file est sur le point de se vider.',
      hi: 'अब दोबारा कतार में नहीं डालता — कतार जल्द खाली होने वाली है।',
      id: 'Berhenti mengantre ulang — antrean akan segera kosong.',
      pt: 'Para de se reenfileirar — a fila está prestes a esvaziar.',
    },
    'caption.render': {
      en: 'The queue empties and the turn ends — {count} passed boundaries become one paint.',
      ko: '줄이 비어 차례가 끝난다 — 지난 경계 {count}개를 한 장으로 그린다.',
      ja: '待ち行列が空になり順番が終わる — 通り過ぎた境界 {count} 個を一枚にまとめて描く。',
      zh: '队列清空,回合结束 — 把经过的 {count} 个边界画成一张。',
      ar: 'يفرغ الطابور وتنتهي الجولة — تتحول {count} حدود عابرة إلى رسمة واحدة.',
      es: 'La cola se vacía y termina el turno — {count} límites pasados se convierten en un solo dibujo.',
      fr: 'La file se vide et le tour se termine — {count} frontières passées deviennent un seul rendu.',
      hi: 'कतार खाली होती है और बारी खत्म होती है — बीती {count} सीमाएँ एक ही चित्र में बनती हैं।',
      id: 'Antrean kosong dan giliran berakhir — {count} batas yang terlewati menjadi satu gambar.',
      pt: 'A fila esvazia e o turno termina — {count} limites passados viram um único desenho.',
    },
    'caption.renderJump': {
      en: 'The screen jumps to {screen} — the values in between never appeared.',
      ko: '화면 값: {screen} — 건너뛴 값, 중간은 뜨지 않았다.',
      ja: '画面は {screen} へ飛ぶ — その間の値は一度も現れなかった。',
      zh: '画面直接跳到 {screen} — 中间的值从未出现过。',
      ar: 'تقفز الشاشة إلى {screen} — لم تظهر القيم بينهما أبدًا.',
      es: 'La pantalla salta a {screen} — los valores intermedios nunca aparecieron.',
      fr: 'L’écran saute à {screen} — les valeurs intermédiaires ne sont jamais apparues.',
      hi: 'स्क्रीन सीधे {screen} पर पहुँच जाती है — बीच के मान कभी नहीं दिखे।',
      id: 'Layar melompat ke {screen} — nilai-nilai di antaranya tidak pernah muncul.',
      pt: 'A tela salta para {screen} — os valores intermediários nunca apareceram.',
    },
    'label.microQueue': {
      en: 'Microtask queue',
      ko: '마이크로 줄',
      ja: 'マイクロタスク待ち行列',
      zh: '微任务队列',
      ar: 'طابور المهام الصغيرة',
      es: 'Cola de microtareas',
      fr: 'File de microtâches',
      hi: 'माइक्रोटास्क कतार',
      id: 'Antrean microtask',
      pt: 'Fila de microtarefas',
    },
    'label.dom': {
      en: 'DOM',
      ko: 'DOM',
      ja: 'DOM',
      zh: 'DOM',
      ar: 'DOM',
      es: 'DOM',
      fr: 'DOM',
      hi: 'DOM',
      id: 'DOM',
      pt: 'DOM',
    },
    'label.screen': {
      en: 'Screen',
      ko: '화면',
      ja: '画面',
      zh: '画面',
      ar: 'الشاشة',
      es: 'Pantalla',
      fr: 'Écran',
      hi: 'स्क्रीन',
      id: 'Layar',
      pt: 'Tela',
    },
    'label.gap': {
      en: 'Gap {n}',
      ko: '벌어짐 {n}',
      ja: '差 {n}',
      zh: '差距 {n}',
      ar: 'الفجوة {n}',
      es: 'Brecha {n}',
      fr: 'Écart {n}',
      hi: 'अंतर {n}',
      id: 'Selisih {n}',
      pt: 'Diferença {n}',
    },
  },
  blocks: {
    stage: { type: 'microtask-starvation-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
