import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 합칠 쪽이 갈라지지 않고 앞서 있기만 하면, 병합은 무엇을 만드는가?
 *
 * 받는 쪽 이름이 합칠 쪽 줄기의 조상 자리에 있다는 것이 판정되면, 그 이름표가 새 커밋 없이
 * 사이 커밋들을 한꺼번에 건너 합칠 쪽 커밋에 가서 붙는다.
 */
export const fastForwardFacet: FacetJson = {
  id: 'facet:fastForward',
  title: {
    en: 'Fast-forward',
    ko: '빨리 감기 병합',
    ja: 'Fast-forward マージ',
    zh: '快进合并',
    ar: 'الدمج بالتقديم السريع',
    es: 'Avance rápido (fast-forward)',
    fr: 'Avance rapide (fast-forward)',
    hi: 'फ़ास्ट-फ़ॉरवर्ड मर्ज',
    id: 'Fast-forward',
    pt: 'Avanço rápido (fast-forward)',
  },
  description: {
    en: 'When the branch being merged is simply ahead, not diverged, what does the merge make?',
    ko: '합칠 쪽이 갈라지지 않고 앞서 있기만 하면, 병합은 무엇을 만드는가?',
    ja: '取り込む側が分岐せず先に進んでいるだけなら、マージは何を作るのか?',
    zh: '当要合并的一方没有分叉、只是领先时,合并会产生什么?',
    ar: 'إذا كان الفرع المدموج متقدمًا فقط دون أن يتفرّع، فماذا ينتج الدمج؟',
    es: 'Si la rama que se fusiona solo va por delante, sin divergir, ¿qué crea la fusión?',
    fr: 'Si la branche à fusionner est seulement en avance, sans diverger, que crée la fusion ?',
    hi: 'अगर मिलाई जाने वाली शाखा अलग नहीं हुई, बस आगे है, तो मर्ज क्या बनाता है?',
    id: 'Jika cabang yang digabung hanya berada di depan tanpa bercabang, apa yang dibuat penggabungan?',
    pt: 'Se o ramo a mesclar só está à frente, sem divergir, o que a mesclagem cria?',
  },
  algorithm: 'module:fastForward',
  scene: 'module:fastForwardScene',
  initialData: {
    type: 'fast-forward',
    stepMs: 2200,
    commits: [
      { id: 'A', parents: [] },
      { id: 'B', parents: ['A'] },
      { id: 'C', parents: ['B'] },
      { id: 'D', parents: ['C'] },
      { id: 'E', parents: ['D'] },
    ],
    branches: [
      { name: 'main', at: 'B' },
      { name: 'feature', at: 'E' },
    ],
    head: 'main',
    merge: { from: 'feature', into: 'main' },
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      ko: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      ja: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      zh: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      ar: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      es: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      fr: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      hi: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      id: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
      pt: '{from} → {fromAt} · {into} → {intoAt} · HEAD → {head}',
    },
    'caption.count': {
      en: 'Commits: {n}',
      ko: '커밋: {n}',
      ja: 'コミット: {n}',
      zh: '提交: {n}',
      ar: 'الإيداعات: {n}',
      es: 'Commits: {n}',
      fr: 'Commits : {n}',
      hi: 'कमिट: {n}',
      id: 'Commit: {n}',
      pt: 'Commits: {n}',
    },
    'caption.walk': {
      en: 'Back from {from}: {path}',
      ko: '{from} 에서 거슬러 간 길: {path}',
      ja: '{from} から遡った道: {path}',
      zh: '从 {from} 回溯的路径: {path}',
      ar: 'الرجوع من {from}: {path}',
      es: 'Hacia atrás desde {from}: {path}',
      fr: 'En remontant depuis {from} : {path}',
      hi: '{from} से पीछे की ओर: {path}',
      id: 'Mundur dari {from}: {path}',
      pt: 'Voltando de {from}: {path}',
    },
    'caption.base': {
      en: 'On the path: the commit of {into} — merge base: {base}',
      ko: '길 위에서 만난 {into} 의 커밋 — 병합 기준점: {base}',
      ja: '道の途中に {into} のコミット — マージベース: {base}',
      zh: '路径上遇到 {into} 的提交 — 合并基点: {base}',
      ar: 'على المسار: إيداع {into} — قاعدة الدمج: {base}',
      es: 'En el camino: el commit de {into} — base de fusión: {base}',
      fr: 'Sur le chemin : le commit de {into} — base de fusion : {base}',
      hi: 'रास्ते में {into} का कमिट — मर्ज बेस: {base}',
      id: 'Di jalur: commit milik {into} — basis gabung: {base}',
      pt: 'No caminho: o commit de {into} — base de mesclagem: {base}',
    },
    'caption.jump': {
      en: '{name}: {from} → {to}, in one move',
      ko: '{name}: {from} → {to}, 한 번에',
      ja: '{name}: {from} → {to}、一度に',
      zh: '{name}: {from} → {to},一步到位',
      ar: '{name}: {from} → {to}، دفعة واحدة',
      es: '{name}: {from} → {to}, de un salto',
      fr: '{name} : {from} → {to}, d’un seul bond',
      hi: '{name}: {from} → {to}, एक ही बार में',
      id: '{name}: {from} → {to}, sekali lompat',
      pt: '{name}: {from} → {to}, de uma vez',
    },
    'caption.crossed': {
      en: 'Commits passed over: {crossed}',
      ko: '건넌 커밋: {crossed}',
      ja: '飛び越えたコミット: {crossed}',
      zh: '越过的提交: {crossed}',
      ar: 'الإيداعات التي تخطّاها: {crossed}',
      es: 'Commits saltados: {crossed}',
      fr: 'Commits franchis : {crossed}',
      hi: 'पार किए गए कमिट: {crossed}',
      id: 'Commit yang dilewati: {crossed}',
      pt: 'Commits pulados: {crossed}',
    },
    'caption.tally': {
      en: 'New commits: {made} · Names moved: {moved} · Commits: {before} → {after}',
      ko: '새 커밋: {made} · 옮긴 이름: {moved} · 커밋: {before} → {after}',
      ja: '新しいコミット: {made} · 動いた名前: {moved} · コミット: {before} → {after}',
      zh: '新提交: {made} · 移动的名字: {moved} · 提交: {before} → {after}',
      ar: 'إيداعات جديدة: {made} · أسماء نُقلت: {moved} · الإيداعات: {before} → {after}',
      es: 'Commits nuevos: {made} · Nombres movidos: {moved} · Commits: {before} → {after}',
      fr: 'Nouveaux commits : {made} · Noms déplacés : {moved} · Commits : {before} → {after}',
      hi: 'नए कमिट: {made} · खिसके नाम: {moved} · कमिट: {before} → {after}',
      id: 'Commit baru: {made} · Nama dipindah: {moved} · Commit: {before} → {after}',
      pt: 'Commits novos: {made} · Nomes movidos: {moved} · Commits: {before} → {after}',
    },
    'caption.reach': {
      en: 'Newly reachable from {into}: {reach}',
      ko: '{into} 에서 새로 닿는 커밋: {reach}',
      ja: '{into} から新たに届くコミット: {reach}',
      zh: '从 {into} 新可达的提交: {reach}',
      ar: 'إيداعات يصل إليها {into} حديثًا: {reach}',
      es: 'Nuevos alcanzables desde {into}: {reach}',
      fr: 'Nouvellement atteints depuis {into} : {reach}',
      hi: '{into} से नए पहुँचने योग्य कमिट: {reach}',
      id: 'Baru terjangkau dari {into}: {reach}',
      pt: 'Novos alcançáveis a partir de {into}: {reach}',
    },
  },
  blocks: {
    stage: { type: 'fast-forward-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
