import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 한 순간에 함께 실패한 클라이언트들이 기다렸다 다시 올 때, 기다림을 흩으면 무엇이 달라지는가.
 *
 * 흩지 않는 쪽은 실패한 클라이언트가 한 덩이로 같은 칸에 되돌아와 또 부딪히고,
 * 흩는 쪽은 여러 칸으로 갈라져 돌아와 한 칸에 몰리는 수가 준다.
 */
export const jitteredBackoffFacet: FacetJson = {
  id: 'facet:jitteredBackoff',
  title: {
    en: 'Jittered backoff',
    ko: '지터를 더한 백오프',
    ja: 'ジッター付きバックオフ',
    zh: '带抖动的退避',
    ar: 'التراجع مع التشويش',
    es: 'Espera exponencial con jitter',
    fr: 'Backoff avec gigue',
    hi: 'जिटर वाला बैकऑफ़',
    id: 'Backoff dengan jitter',
    pt: 'Backoff com jitter',
  },
  description: {
    en: 'Clients that failed together come back together if they all wait the same; spread the wait and they return to different cells and collide less.',
    ko: '함께 실패한 클라이언트는 똑같이 기다리면 함께 되돌아온다. 기다림을 흩으면 여러 칸으로 갈라져 돌아와 덜 부딪힌다.',
    ja: '一緒に失敗したクライアントは同じだけ待つと一緒に戻ってくる。待ち時間を散らすと別々のマスに戻り、衝突が減る。',
    zh: '一起失败的客户端若等待相同，就会一起回来；把等待打散，它们会回到不同的格子，冲突更少。',
    ar: 'العملاء الذين فشلوا معًا يعودون معًا إذا انتظروا المدة نفسها؛ وإذا بُعثر الانتظار عادوا إلى خانات مختلفة وتصادموا أقل.',
    es: 'Los clientes que fallaron juntos vuelven juntos si esperan lo mismo; si se dispersa la espera, vuelven a casillas distintas y chocan menos.',
    fr: 'Des clients qui ont échoué ensemble reviennent ensemble s’ils attendent autant ; dispersez l’attente et ils reviennent dans des cases différentes et se heurtent moins.',
    hi: 'साथ विफल हुए क्लाइंट बराबर प्रतीक्षा करें तो साथ ही लौटते हैं; प्रतीक्षा बिखेरें तो वे अलग-अलग खानों में लौटते हैं और कम टकराते हैं।',
    id: 'Klien yang gagal bersamaan kembali bersamaan bila menunggu sama lama; sebarkan waktu tunggunya, mereka kembali ke sel berbeda dan lebih jarang bertabrakan.',
    pt: 'Clientes que falharam juntos voltam juntos se esperam o mesmo; espalhe a espera e eles voltam em células diferentes e colidem menos.',
  },
  algorithm: 'module:jitteredBackoff',
  scene: 'module:jitteredBackoffScene',
  initialData: {
    type: 'jittered-backoff',
    stepMs: 1400,
    clients: ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8'],
    firstCell: 0,
    capacity: 2,
    windowBase: 2,
    lcg: { a: 75, c: 74, m: 65537, seed: 42 },
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'jittered-backoff-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'Cell {cell}. Every client arrives at once — clients: {n}.',
      ko: '칸 {cell}. 모든 클라이언트가 한꺼번에 온다 — 클라이언트: {n}.',
      ja: 'マス {cell}。すべてのクライアントが一度に来る — クライアント: {n}。',
      zh: '格 {cell}。所有客户端同时到来 — 客户端：{n}。',
      ar: 'الخانة {cell}. يصل كل العملاء دفعة واحدة — العملاء: {n}.',
      es: 'Casilla {cell}. Todos los clientes llegan a la vez — clientes: {n}.',
      fr: 'Case {cell}. Tous les clients arrivent en même temps — clients : {n}.',
      hi: 'खाना {cell}। सभी क्लाइंट एक साथ आते हैं — क्लाइंट: {n}।',
      id: 'Sel {cell}. Semua klien datang sekaligus — klien: {n}.',
      pt: 'Célula {cell}. Todos os clientes chegam de uma vez — clientes: {n}.',
    },
    'caption.visit': {
      en: 'Cell {cell}. Arrived — no jitter: {a}, jitter: {b}.',
      ko: '칸 {cell}. 찾아옴 — 흩지 않음: {a}, 흩음: {b}.',
      ja: 'マス {cell}。到着 — ジッターなし: {a}、ジッターあり: {b}。',
      zh: '格 {cell}。到达 — 不加抖动：{a}，加抖动：{b}。',
      ar: 'الخانة {cell}. الواصلون — بلا تشويش: {a}، مع التشويش: {b}.',
      es: 'Casilla {cell}. Llegan — sin jitter: {a}, con jitter: {b}.',
      fr: 'Case {cell}. Arrivées — sans gigue : {a}, avec gigue : {b}.',
      hi: 'खाना {cell}। आए — बिना जिटर: {a}, जिटर के साथ: {b}।',
      id: 'Sel {cell}. Datang — tanpa jitter: {a}, dengan jitter: {b}.',
      pt: 'Célula {cell}. Chegaram — sem jitter: {a}, com jitter: {b}.',
    },
    'caption.failed': {
      en: 'Failed here — no jitter: {fa}, jitter: {fb}.',
      ko: '이 칸에서 실패 — 흩지 않음: {fa}, 흩음: {fb}.',
      ja: 'このマスで失敗 — ジッターなし: {fa}、ジッターあり: {fb}。',
      zh: '本格失败 — 不加抖动：{fa}，加抖动：{fb}。',
      ar: 'فشل في هذه الخانة — بلا تشويش: {fa}، مع التشويش: {fb}.',
      es: 'Fallan aquí — sin jitter: {fa}, con jitter: {fb}.',
      fr: 'Échecs ici — sans gigue : {fa}, avec gigue : {fb}.',
      hi: 'यहाँ विफल — बिना जिटर: {fa}, जिटर के साथ: {fb}।',
      id: 'Gagal di sini — tanpa jitter: {fa}, dengan jitter: {fb}.',
      pt: 'Falharam aqui — sem jitter: {fa}, com jitter: {fb}.',
    },
    'caption.end': {
      en: 'Everyone served. Collision failures in all — no jitter: {fa}, jitter: {fb}.',
      ko: '서버가 모두 받아 줬다. 부딪혀 실패한 합 — 흩지 않음: {fa}, 흩음: {fb}.',
      ja: '全員受け付けられた。衝突による失敗の合計 — ジッターなし: {fa}、ジッターあり: {fb}。',
      zh: '全部被接收。冲突失败合计 — 不加抖动：{fa}，加抖动：{fb}。',
      ar: 'قُبل الجميع. مجموع الإخفاقات بالتصادم — بلا تشويش: {fa}، مع التشويش: {fb}.',
      es: 'Todos atendidos. Fallos por choque en total — sin jitter: {fa}, con jitter: {fb}.',
      fr: 'Tous servis. Échecs par collision au total — sans gigue : {fa}, avec gigue : {fb}.',
      hi: 'सभी स्वीकार हुए। टकराव से कुल विफलता — बिना जिटर: {fa}, जिटर के साथ: {fb}।',
      id: 'Semua dilayani. Total gagal karena tabrakan — tanpa jitter: {fa}, dengan jitter: {fb}.',
      pt: 'Todos atendidos. Falhas por colisão no total — sem jitter: {fa}, com jitter: {fb}.',
    },
    'label.plain': {
      en: 'No jitter',
      ko: '흩지 않음',
      ja: 'ジッターなし',
      zh: '不加抖动',
      ar: 'بلا تشويش',
      es: 'Sin jitter',
      fr: 'Sans gigue',
      hi: 'बिना जिटर',
      id: 'Tanpa jitter',
      pt: 'Sem jitter',
    },
    'label.jitter': {
      en: 'Jitter',
      ko: '흩음',
      ja: 'ジッターあり',
      zh: '加抖动',
      ar: 'مع التشويش',
      es: 'Con jitter',
      fr: 'Avec gigue',
      hi: 'जिटर के साथ',
      id: 'Dengan jitter',
      pt: 'Com jitter',
    },
    'label.failed': {
      en: 'Failed: {n}',
      ko: '실패: {n}',
      ja: '失敗: {n}',
      zh: '失败：{n}',
      ar: 'الإخفاقات: {n}',
      es: 'Fallos: {n}',
      fr: 'Échecs : {n}',
      hi: 'विफल: {n}',
      id: 'Gagal: {n}',
      pt: 'Falhas: {n}',
    },
    'label.last': {
      en: 'Last cell: {cell}',
      ko: '끝난 칸: {cell}',
      ja: '最後のマス: {cell}',
      zh: '最后一格：{cell}',
      ar: 'الخانة الأخيرة: {cell}',
      es: 'Última casilla: {cell}',
      fr: 'Dernière case : {cell}',
      hi: 'अंतिम खाना: {cell}',
      id: 'Sel terakhir: {cell}',
      pt: 'Última célula: {cell}',
    },
    'label.cell': {
      en: 'Cell',
      ko: '칸',
      ja: 'マス',
      zh: '格',
      ar: 'الخانة',
      es: 'Casilla',
      fr: 'Case',
      hi: 'खाना',
      id: 'Sel',
      pt: 'Célula',
    },
    'label.server': {
      en: 'Server',
      ko: '서버',
      ja: 'サーバー',
      zh: '服务器',
      ar: 'الخادم',
      es: 'Servidor',
      fr: 'Serveur',
      hi: 'सर्वर',
      id: 'Server',
      pt: 'Servidor',
    },
  },
};
