import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { ScopeAndSymbolsData } from './algorithm.js';

/**
 * 1차 데이터 — 원시 프로그램 열 줄의 구조. 글자(`text`)는 소재라 번역하지 않고, 알고리즘이
 * 구조에서 찍은 글자와 한 글자라도 다르면 던진다. 스코프 · 선언 · 쓰임은 알고리즘이 셈한다.
 */
const data: ScopeAndSymbolsData = {
  type: 'scope-and-symbols',
  stepMs: 1100,
  lines: [
    { indent: 0, text: 'let size = 10', stmt: { k: 'let', name: 'size', value: { int: 10 } } },
    { indent: 0, text: 'let i = 0', stmt: { k: 'let', name: 'i', value: { int: 0 } } },
    { indent: 0, text: 'function fill(n)', stmt: { k: 'function', name: 'fill', params: ['n'] } },
    {
      indent: 1,
      text: 'let size = n * 2',
      stmt: { k: 'let', name: 'size', value: { op: '*', l: { var: 'n' }, r: { int: 2 } } },
    },
    { indent: 1, text: 'for i from 1 to n', stmt: { k: 'for', var: 'i', lo: { int: 1 }, hi: { var: 'n' } } },
    {
      indent: 2,
      text: 'let last = i * size',
      stmt: { k: 'let', name: 'last', value: { op: '*', l: { var: 'i' }, r: { var: 'size' } } },
    },
    { indent: 1, text: 'if n > size', stmt: { k: 'if', cond: { op: '>', l: { var: 'n' }, r: { var: 'size' } } } },
    { indent: 2, text: 'let size = 0', stmt: { k: 'let', name: 'size', value: { int: 0 } } },
    {
      indent: 1,
      text: 'return size + last + i',
      stmt: {
        k: 'return',
        value: { op: '+', l: { op: '+', l: { var: 'size' }, r: { var: 'last' } }, r: { var: 'i' } },
      },
    },
    {
      indent: 0,
      text: 'show fill(3) + size + i',
      stmt: {
        k: 'show',
        value: {
          op: '+',
          l: { op: '+', l: { call: 'fill', args: [{ int: 3 }] }, r: { var: 'size' } },
          r: { var: 'i' },
        },
      },
    },
  ],
  scopeRules: [{ id: 'block' }, { id: 'function' }, { id: 'single' }],
  scopeRuleLadder: [0, 1, 2],
  defaultScopeRule: 0,
};

export const scopeAndSymbolsFacet: FacetJson = {
  id: 'facet:scopeAndSymbols',
  title: {
    en: 'Scope and symbol tables',
    ko: '스코프와 심볼 테이블',
    ja: 'スコープとシンボル表',
    zh: '作用域与符号表',
    ar: 'النطاق وجداول الرموز',
    es: 'Ámbito y tablas de símbolos',
    fr: 'Portée et tables des symboles',
    hi: 'स्कोप और सिंबल टेबल',
    id: 'Cakupan dan tabel simbol',
    pt: 'Escopo e tabelas de símbolos',
  },
  description: {
    en: 'The same ten lines read top to bottom under three scope rules — as the pile of tables changes, the declaration each name reaches moves.',
    ko: '같은 열 줄을 세 스코프 규칙으로 위에서 아래로 읽는다 — 쌓이는 표가 바뀌면 이름마다 닿는 선언이 옮겨 간다.',
    ja: '同じ十行を三つのスコープ規則で上から下へ読む — 積まれる表が変わると、名前が届く宣言が移る。',
    zh: '用三种作用域规则从上到下读同样的十行 — 叠起的表一变，每个名字连到的声明就跟着移动。',
    ar: 'تُقرأ الأسطر العشرة نفسها من الأعلى إلى الأسفل بثلاث قواعد نطاق — حين تتغير كومة الجداول ينتقل الإعلان الذي يصل إليه كل اسم.',
    es: 'Las mismas diez líneas leídas de arriba abajo con tres reglas de ámbito: al cambiar la pila de tablas, se mueve la declaración a la que llega cada nombre.',
    fr: 'Les mêmes dix lignes lues de haut en bas selon trois règles de portée : quand la pile de tables change, la déclaration atteinte par chaque nom se déplace.',
    hi: 'वही दस पंक्तियाँ तीन स्कोप नियमों से ऊपर से नीचे पढ़ी जाती हैं — टेबलों का ढेर बदलते ही हर नाम जिस घोषणा तक पहुँचता है वह खिसक जाती है।',
    id: 'Sepuluh baris yang sama dibaca dari atas ke bawah dengan tiga aturan cakupan — saat tumpukan tabel berubah, deklarasi yang dicapai tiap nama ikut berpindah.',
    pt: 'As mesmas dez linhas lidas de cima para baixo com três regras de escopo: quando a pilha de tabelas muda, a declaração que cada nome alcança se desloca.',
  },
  algorithm: 'module:scopeAndSymbols',
  projector: 'module:scopeAndSymbolsProjector',
  initialData: data,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'scope-and-symbols-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'scopeRule',
          name: 'scopeRule',
          label: {
            en: 'Scope rule',
            ko: '스코프 규칙',
            ja: 'スコープ規則',
            zh: '作用域规则',
            ar: 'قاعدة النطاق',
            es: 'Regla de ámbito',
            fr: 'Règle de portée',
            hi: 'स्कोप नियम',
            id: 'Aturan cakupan',
            pt: 'Regra de escopo',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: {
                en: 'Per block',
                ko: '블록마다',
                ja: 'ブロックごと',
                zh: '按块',
                ar: 'لكل كتلة',
                es: 'Por bloque',
                fr: 'Par bloc',
                hi: 'प्रति ब्लॉक',
                id: 'Per blok',
                pt: 'Por bloco',
              },
            },
            {
              value: 1,
              label: {
                en: 'Per function',
                ko: '함수마다',
                ja: '関数ごと',
                zh: '按函数',
                ar: 'لكل دالة',
                es: 'Por función',
                fr: 'Par fonction',
                hi: 'प्रति फ़ंक्शन',
                id: 'Per fungsi',
                pt: 'Por função',
              },
            },
            {
              value: 2,
              label: {
                en: 'Just one',
                ko: '하나뿐',
                ja: 'ひとつだけ',
                zh: '仅一个',
                ar: 'واحد فقط',
                es: 'Solo una',
                fr: 'Une seule',
                hi: 'केवल एक',
                id: 'Hanya satu',
                pt: 'Só uma',
              },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'tables-made',
          initial: 0,
          label: {
            en: 'Tables made',
            ko: '만든 표',
            ja: '作った表',
            zh: '建表数',
            ar: 'الجداول المنشأة',
            es: 'Tablas creadas',
            fr: 'Tables créées',
            hi: 'बनी टेबल',
            id: 'Tabel dibuat',
            pt: 'Tabelas criadas',
          },
        },
        {
          name: 'links',
          initial: 0,
          label: {
            en: 'Links',
            ko: '이은 선',
            ja: '結んだ線',
            zh: '连线',
            ar: 'الروابط',
            es: 'Enlaces',
            fr: 'Liens',
            hi: 'लिंक',
            id: 'Tautan',
            pt: 'Ligações',
          },
        },
        {
          name: 'scope-errors',
          initial: 0,
          label: {
            en: 'Errors',
            ko: '걸림',
            ja: 'エラー',
            zh: '错误',
            ar: 'الأخطاء',
            es: 'Errores',
            fr: 'Erreurs',
            hi: 'त्रुटियाँ',
            id: 'Galat',
            pt: 'Erros',
          },
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:scope-and-symbols-imperative',
      label: {
        en: 'Name resolver',
        ko: '이름 해석기',
        ja: '名前解決器',
        zh: '名称解析器',
        ar: 'مُحلِّل الأسماء',
        es: 'Resolutor de nombres',
        fr: 'Résolveur de noms',
        hi: 'नाम रिज़ॉल्वर',
        id: 'Penyelesai nama',
        pt: 'Resolvedor de nomes',
      },
    },
  },
  messages: {
    'label.rule.block': {
      en: 'Per block',
      ko: '블록마다',
      ja: 'ブロックごと',
      zh: '按块',
      ar: 'لكل كتلة',
      es: 'Por bloque',
      fr: 'Par bloc',
      hi: 'प्रति ब्लॉक',
      id: 'Per blok',
      pt: 'Por bloco',
    },
    'label.rule.function': {
      en: 'Per function',
      ko: '함수마다',
      ja: '関数ごと',
      zh: '按函数',
      ar: 'لكل دالة',
      es: 'Por función',
      fr: 'Par fonction',
      hi: 'प्रति फ़ंक्शन',
      id: 'Per fungsi',
      pt: 'Por função',
    },
    'label.rule.single': {
      en: 'Just one',
      ko: '하나뿐',
      ja: 'ひとつだけ',
      zh: '仅一个',
      ar: 'واحد فقط',
      es: 'Solo una',
      fr: 'Une seule',
      hi: 'केवल एक',
      id: 'Hanya satu',
      pt: 'Só uma',
    },
    'label.ruleNow': {
      en: 'Rule: {rule}',
      ko: '규칙: {rule}',
      ja: '規則: {rule}',
      zh: '规则: {rule}',
      ar: 'القاعدة: {rule}',
      es: 'Regla: {rule}',
      fr: 'Règle : {rule}',
      hi: 'नियम: {rule}',
      id: 'Aturan: {rule}',
      pt: 'Regra: {rule}',
    },
    'label.table.top': {
      en: 'outermost',
      ko: '맨 바깥',
      ja: '最外側',
      zh: '最外层',
      ar: 'الخارجي',
      es: 'más externa',
      fr: 'extérieure',
      hi: 'सबसे बाहरी',
      id: 'terluar',
      pt: 'mais externa',
    },
    'label.table.body': {
      en: '{name} body',
      ko: '{name} 몸',
      ja: '{name} 本体',
      zh: '{name} 体',
      ar: 'جسم {name}',
      es: 'cuerpo de {name}',
      fr: 'corps de {name}',
      hi: '{name} बॉडी',
      id: 'badan {name}',
      pt: 'corpo de {name}',
    },
    'label.stack': {
      en: 'Symbol tables — searched from the top',
      ko: '심볼 테이블 — 맨 위부터 훑는다',
      ja: 'シンボル表 — 上から探す',
      zh: '符号表 — 从上往下查',
      ar: 'جداول الرموز — البحث من الأعلى',
      es: 'Tablas de símbolos — se buscan desde arriba',
      fr: 'Tables des symboles — parcourues depuis le haut',
      hi: 'सिंबल टेबल — ऊपर से खोज',
      id: 'Tabel simbol — dicari dari atas',
      pt: 'Tabelas de símbolos — busca a partir do topo',
    },
    'label.errors': {
      en: 'Errors',
      ko: '걸림',
      ja: 'エラー',
      zh: '错误',
      ar: 'الأخطاء',
      es: 'Errores',
      fr: 'Erreurs',
      hi: 'त्रुटियाँ',
      id: 'Galat',
      pt: 'Erros',
    },
    'label.dup': {
      en: 'declared twice',
      ko: '두 번 선언',
      ja: '二重宣言',
      zh: '重复声明',
      ar: 'مُعلن مرتين',
      es: 'declarada dos veces',
      fr: 'déclarée deux fois',
      hi: 'दो बार घोषित',
      id: 'dideklarasikan dua kali',
      pt: 'declarada duas vezes',
    },
    'label.missing': {
      en: 'no declaration',
      ko: '선언 없음',
      ja: '宣言なし',
      zh: '无声明',
      ar: 'بلا إعلان',
      es: 'sin declaración',
      fr: 'aucune déclaration',
      hi: 'कोई घोषणा नहीं',
      id: 'tanpa deklarasi',
      pt: 'sem declaração',
    },
    'caption.start': {
      en: '{rule}: reading starts with one empty outermost table',
      ko: '{rule} — 비어 있는 맨 바깥 표 하나로 읽기 시작',
      ja: '{rule} — 空の最外側の表ひとつから読み始める',
      zh: '{rule} — 从一张空的最外层表开始读',
      ar: '{rule} — تبدأ القراءة بجدول خارجي واحد فارغ',
      es: '{rule}: la lectura empieza con una sola tabla externa vacía',
      fr: '{rule} : la lecture commence avec une seule table extérieure vide',
      hi: '{rule} — एक खाली सबसे बाहरी टेबल से पढ़ना शुरू',
      id: '{rule} — membaca dimulai dengan satu tabel terluar kosong',
      pt: '{rule}: a leitura começa com uma única tabela externa vazia',
    },
    'caption.pop': {
      en: '{table} lifted off',
      ko: '{table} 걷음',
      ja: '{table} を外す',
      zh: '移除 {table}',
      ar: 'رُفع {table}',
      es: 'se retira {table}',
      fr: '{table} retirée',
      hi: '{table} हटाई',
      id: '{table} diangkat',
      pt: '{table} retirada',
    },
    'caption.push': {
      en: '{table} stacked on top (height {h})',
      ko: '{table} 얹음 (높이 {h})',
      ja: '{table} を積む (高さ {h})',
      zh: '叠上 {table} (高度 {h})',
      ar: 'وُضع {table} في الأعلى (الارتفاع {h})',
      es: '{table} apilada arriba (altura {h})',
      fr: '{table} empilée au sommet (hauteur {h})',
      hi: '{table} ऊपर रखी (ऊँचाई {h})',
      id: '{table} ditumpuk di atas (tinggi {h})',
      pt: '{table} empilhada no topo (altura {h})',
    },
    'caption.place': {
      en: '{name} written into {table}',
      ko: '{name} 적음 → {table}',
      ja: '{name} を {table} に記入',
      zh: '{name} 写入 {table}',
      ar: 'كُتب {name} في {table}',
      es: '{name} anotada en {table}',
      fr: '{name} inscrite dans {table}',
      hi: '{name} {table} में लिखा',
      id: '{name} ditulis ke {table}',
      pt: '{name} escrita em {table}',
    },
    'caption.clash': {
      en: '{name} declared twice — {table} already holds L{line}',
      ko: '{name} 두 번 선언 — {table} 에 이미 L{line}',
      ja: '{name} 二重宣言 — {table} に L{line} がある',
      zh: '{name} 重复声明 — {table} 已有 L{line}',
      ar: '{name} مُعلن مرتين — في {table} سلفًا L{line}',
      es: '{name} declarada dos veces — {table} ya tiene L{line}',
      fr: '{name} déclarée deux fois — {table} contient déjà L{line}',
      hi: '{name} दो बार घोषित — {table} में पहले से L{line}',
      id: '{name} dideklarasikan dua kali — {table} sudah memuat L{line}',
      pt: '{name} declarada duas vezes — {table} já tem L{line}',
    },
    'caption.hit': {
      en: '{name} → L{line} (table {depth} from the top)',
      ko: '{name} → L{line} (위에서 {depth} 장째 표)',
      ja: '{name} → L{line} (上から {depth} 枚目の表)',
      zh: '{name} → L{line} (从上数第 {depth} 张表)',
      ar: '{name} → L{line} (الجدول {depth} من الأعلى)',
      es: '{name} → L{line} (tabla {depth} desde arriba)',
      fr: '{name} → L{line} (table {depth} depuis le haut)',
      hi: '{name} → L{line} (ऊपर से टेबल {depth})',
      id: '{name} → L{line} (tabel ke-{depth} dari atas)',
      pt: '{name} → L{line} (tabela {depth} a partir do topo)',
    },
    'caption.miss': {
      en: '{name} → no declaration (all {n} tables scanned)',
      ko: '{name} → 선언 없음 (표 {n} 장 모두 훑음)',
      ja: '{name} → 宣言なし (表 {n} 枚をすべて探した)',
      zh: '{name} → 无声明 (查遍 {n} 张表)',
      ar: '{name} → بلا إعلان (فُحصت الجداول كلها: {n})',
      es: '{name} → sin declaración (revisadas las {n} tablas)',
      fr: '{name} → aucune déclaration ({n} tables parcourues)',
      hi: '{name} → कोई घोषणा नहीं (सभी {n} टेबल देखी)',
      id: '{name} → tanpa deklarasi (semua {n} tabel diperiksa)',
      pt: '{name} → sem declaração (todas as {n} tabelas vistas)',
    },
    'caption.end': {
      en: 'Read to the end — links {links} · errors {errors}',
      ko: '끝까지 읽음 — 이은 선 {links} · 걸림 {errors}',
      ja: '最後まで読んだ — 結んだ線 {links} · エラー {errors}',
      zh: '读到末尾 — 连线 {links} · 错误 {errors}',
      ar: 'قُرئ حتى النهاية — الروابط {links} · الأخطاء {errors}',
      es: 'Leído hasta el final — enlaces {links} · errores {errors}',
      fr: 'Lu jusqu’au bout — liens {links} · erreurs {errors}',
      hi: 'अंत तक पढ़ा — लिंक {links} · त्रुटियाँ {errors}',
      id: 'Dibaca sampai akhir — tautan {links} · galat {errors}',
      pt: 'Lido até o fim — ligações {links} · erros {errors}',
    },
  },
};
