/**
 * 곱 양자화 완제품 선언.
 *
 * 손잡이(토막 수)가 논증을 진다 — 1 · 2 · 4 · 8 로 옮기면 오차가 단조로 줄고
 * 자리가 단조로 는다. 코드 패널은 두지 않는다 (까닭은 irs.ts).
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core';

export const productQuantizationFacet: FacetJson = {
  id: 'facet:productQuantization',
  title: {
    en: 'Product quantization',
    ko: '곱 양자화',
    ja: '直積量子化',
    zh: '乘积量化',
    ar: 'التكميم الجدائي',
    es: 'Cuantización por producto',
    fr: 'Quantification par produit',
    hi: 'प्रोडक्ट क्वांटाइज़ेशन',
    id: 'Kuantisasi produk',
    pt: 'Quantização de produto',
  },
  description: {
    en: 'Split a vector into chunks and keep one number per chunk — finer chunks, less error, more space.',
    ko: '벡터를 토막으로 쪼개 토막마다 번호 하나만 남긴다. 잘게 쪼갤수록 오차는 줄고 자리는 는다.',
    ja: 'ベクトルを区画に分け、区画ごとに番号を一つだけ残す。細かく分けるほど誤差は減り、記憶は増える。',
    zh: '把向量切成若干段，每段只保留一个编号。切得越细，误差越小，占用越多。',
    ar: 'قسّم المتجه إلى أجزاء واحتفظ برقم واحد لكل جزء: أجزاء أدق تعني خطأ أقل ومساحة أكبر.',
    es: 'Divide un vector en trozos y guarda un número por trozo: trozos más finos, menos error y más espacio.',
    fr: "Découpe un vecteur en blocs et garde un numéro par bloc : des blocs plus fins, moins d'erreur et plus de place.",
    hi: 'वेक्टर को खंडों में बाँटें और हर खंड के लिए एक संख्या रखें — छोटे खंड, कम त्रुटि, अधिक जगह।',
    id: 'Bagi vektor menjadi potongan dan simpan satu nomor per potongan: makin halus, makin kecil galat, makin besar ruang.',
    pt: 'Divide um vetor em blocos e guarda um número por bloco: blocos menores, menos erro e mais espaço.',
  },
  algorithm: 'module:productQuantization',
  projector: 'module:productQuantizationProjector',
  initialData: {
    type: 'product-quantization',
    // 1차 데이터는 이 둘뿐이다 — 벡터 여덟 값과 대표 격자 넷.
    // 고른 번호 · 되살린 값 · 오차 · 자리는 algorithm 이 셈한다.
    vector: [6, 2, 7, 3, 5, 8, 2, 6],
    grid: [2, 4, 6, 8],
    // 손잡이의 처음 자리. 아래 segments 의 default 와 같아야 한다.
    parts: 2,
    // 걸음 하나를 읽을 시간. 애니메이션이 끝난 뒤의 정지 시간이다.
    stepMs: 520,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage', padding: '8px 0' }, { ref: 'controls' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'product-quantization-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'parts',
          name: 'parts',
          label: {
            en: 'Chunks',
            ko: '토막 수',
            ja: '区画の数',
            zh: '分段数',
            ar: 'عدد الأجزاء',
            es: 'Trozos',
            fr: 'Blocs',
            hi: 'खंड',
            id: 'Potongan',
            pt: 'Blocos',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2', default: true },
            { value: 4, label: '4' },
            { value: 8, label: '8' },
          ],
        },
      ],
      metrics: [
        {
          name: 'code-bytes',
          label: {
            en: 'Bytes',
            ko: '자리 B',
            ja: 'バイト',
            zh: '字节',
            ar: 'بايت',
            es: 'Bytes',
            fr: 'Octets',
            hi: 'बाइट',
            id: 'Byte',
            pt: 'Bytes',
          },
          initial: 0,
        },
        {
          name: 'error-percent',
          label: {
            en: 'Error %',
            ko: '오차 %',
            ja: '誤差 %',
            zh: '误差 %',
            ar: 'الخطأ %',
            es: 'Error %',
            fr: 'Erreur %',
            hi: 'त्रुटि %',
            id: 'Galat %',
            pt: 'Erro %',
          },
          initial: 0,
        },
      ],
    },
  },
  messages: {
    'label.original': {
      en: 'Original',
      ko: '원본',
      ja: '元の値',
      zh: '原始值',
      ar: 'الأصل',
      es: 'Original',
      fr: 'Original',
      hi: 'मूल',
      id: 'Asli',
      pt: 'Original',
    },
    'label.restored': {
      en: 'Restored',
      ko: '되살린 것',
      ja: '復元した値',
      zh: '还原值',
      ar: 'المستعاد',
      es: 'Restaurado',
      fr: 'Restauré',
      hi: 'पुनर्निर्मित',
      id: 'Dipulihkan',
      pt: 'Restaurado',
    },
    'label.gap': {
      en: 'Gap = error',
      ko: '벌어짐 = 오차',
      ja: 'ずれ = 誤差',
      zh: '差距 = 误差',
      ar: 'الفجوة = الخطأ',
      es: 'Hueco = error',
      fr: 'Écart = erreur',
      hi: 'अंतर = त्रुटि',
      id: 'Selisih = galat',
      pt: 'Distância = erro',
    },
    'label.slots': {
      en: 'Numbers kept',
      ko: '남긴 번호',
      ja: '残す番号',
      zh: '保留的编号',
      ar: 'الأرقام المحفوظة',
      es: 'Números guardados',
      fr: 'Numéros gardés',
      hi: 'रखी गई संख्याएँ',
      id: 'Nomor disimpan',
      pt: 'Números guardados',
    },
    'caption.split': {
      en: 'Split into {parts} chunks of {size}.',
      ko: '토막 {parts} · 토막 크기 {size}.',
      ja: '{parts} 個の区画に分ける。区画の大きさは {size}。',
      zh: '切成 {parts} 段，每段 {size} 个值。',
      ar: 'التقسيم إلى {parts} أجزاء، حجم كل جزء {size}.',
      es: 'Dividido en {parts} trozos de {size}.',
      fr: 'Découpé en {parts} blocs de {size}.',
      hi: '{parts} खंडों में बाँटा, हर खंड का आकार {size}।',
      id: 'Dibagi menjadi {parts} potongan berukuran {size}.',
      pt: 'Dividido em {parts} blocos de {size}.',
    },
    'caption.code': {
      en: 'Chunk {index}: nearest grid value {value}, number #{code}.',
      ko: '토막 {index}: 가장 가까운 대표 {value}, 번호 #{code}.',
      ja: '区画 {index}: 最も近い代表値は {value}、番号は #{code}。',
      zh: '第 {index} 段：最近的代表值 {value}，编号 #{code}。',
      ar: 'الجزء {index}: أقرب قيمة {value}، الرقم #{code}.',
      es: 'Trozo {index}: valor de rejilla más cercano {value}, número #{code}.',
      fr: 'Bloc {index} : valeur de grille la plus proche {value}, numéro #{code}.',
      hi: 'खंड {index}: निकटतम ग्रिड मान {value}, संख्या #{code}।',
      id: 'Potongan {index}: nilai kisi terdekat {value}, nomor #{code}.',
      pt: 'Bloco {index}: valor de grade mais próximo {value}, número #{code}.',
    },
    'caption.settled': {
      en: 'Error {error} · numbers {codes} · {bytes} B of 32 B.',
      ko: '오차 {error} · 번호 {codes} · 자리 {bytes} B / 원본 32 B.',
      ja: '誤差 {error} · 番号 {codes} · 記憶 {bytes} B / 元は 32 B。',
      zh: '误差 {error} · 编号 {codes} · 占用 {bytes} B / 原始 32 B。',
      ar: 'الخطأ {error} · الأرقام {codes} · {bytes} بايت من 32 بايت.',
      es: 'Error {error} · números {codes} · {bytes} B de 32 B.',
      fr: 'Erreur {error} · numéros {codes} · {bytes} B sur 32 B.',
      hi: 'त्रुटि {error} · संख्याएँ {codes} · 32 B में से {bytes} B।',
      id: 'Galat {error} · nomor {codes} · {bytes} B dari 32 B.',
      pt: 'Erro {error} · números {codes} · {bytes} B de 32 B.',
    },
  },
};
