import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * @notation native
 *
 * 질문: 브라우저는 화면 한 장을 한 번에 칠하는가, 아니면 따로 칠한 여러 장을 겹쳐 만드는가.
 *
 * 층마다 제 장에 칠하기 동작이 찍히고, 합성에서 장들이 아래부터 들려 올라와 포개진다.
 * 칠하기 동작 이름(fillRect · drawText) · 층과 요소의 식별자는 번역하지 않는 자료다.
 */
export const stackOfSheetsFacet: FacetJson = {
  id: 'facet:stackOfSheets',
  title: {
    en: 'Painted apart, stacked into one',
    ko: '따로 칠하고 겹쳐 한 장으로',
    ja: '別々に塗り、重ねて一枚に',
    zh: '分开绘制，叠成一张',
    ar: 'تُرسم منفصلة وتُكدَّس في صورة واحدة',
    es: 'Pintadas por separado, apiladas en una',
    fr: 'Peintes à part, empilées en une seule',
    hi: 'अलग-अलग पेंट, एक पर एक रखकर एक चित्र',
    id: 'Dilukis terpisah, ditumpuk menjadi satu',
    pt: 'Pintadas à parte, empilhadas numa só',
  },
  description: {
    en: 'Each layer is painted on its own sheet. Compositing lifts the sheets and stacks them from the bottom up — it paints nothing.',
    ko: '층마다 제 장에 따로 칠한다. 합성은 장들을 들어 아래부터 포갤 뿐 아무것도 칠하지 않는다.',
    ja: '層ごとに自分のシートへ別々に塗る。合成はシートを持ち上げて下から重ねるだけで、何も塗らない。',
    zh: '每一层都画在自己的图层纸上。合成只是把这些纸从下往上叠起来，什么也不画。',
    ar: 'تُرسم كل طبقة على ورقتها الخاصة. التركيب يرفع الأوراق ويكدّسها من الأسفل إلى الأعلى، ولا يرسم شيئًا.',
    es: 'Cada capa se pinta en su propia hoja. La composición levanta las hojas y las apila de abajo arriba: no pinta nada.',
    fr: 'Chaque calque est peint sur sa propre feuille. La composition soulève les feuilles et les empile de bas en haut — elle ne peint rien.',
    hi: 'हर परत अपनी शीट पर अलग से पेंट होती है। कंपोज़िटिंग शीटों को उठाकर नीचे से ऊपर रखती है — वह कुछ भी पेंट नहीं करती।',
    id: 'Setiap lapisan dilukis di lembarnya sendiri. Komposisi mengangkat lembar-lembar itu dan menumpuknya dari bawah ke atas — tanpa melukis apa pun.',
    pt: 'Cada camada é pintada na sua própria folha. A composição levanta as folhas e empilha-as de baixo para cima — não pinta nada.',
  },
  algorithm: 'module:stackOfSheets',
  scene: 'module:stackOfSheetsScene',
  initialData: {
    type: 'stack-of-sheets',
    stepMs: 1500,
    layers: [
      {
        id: 'root',
        z: 0,
        ops: [
          { el: 'page', op: 'fillRect' },
          { el: 'heading', op: 'drawText' },
          { el: 'body-text', op: 'drawText' },
        ],
      },
      {
        id: 'card',
        z: 1,
        ops: [
          { el: 'card-box', op: 'fillRect' },
          { el: 'card-label', op: 'drawText' },
        ],
      },
      {
        id: 'toast',
        z: 2,
        ops: [
          { el: 'toast-box', op: 'fillRect' },
          { el: 'toast-text', op: 'drawText' },
        ],
      },
    ],
    covers: [
      { top: 'card-box', under: ['body-text'] },
      { top: 'toast-box', under: ['card-box', 'card-label'] },
    ],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'stack-of-sheets-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'label.composite': {
      en: 'Composite',
      ko: '합성',
      ja: '合成',
      zh: '合成',
      ar: 'التركيب',
      es: 'Composición',
      fr: 'Composition',
      hi: 'कंपोज़िट',
      id: 'Komposit',
      pt: 'Composição',
    },
    'label.top': {
      en: 'Top',
      ko: '위',
      ja: '上',
      zh: '顶层',
      ar: 'الأعلى',
      es: 'Arriba',
      fr: 'Haut',
      hi: 'ऊपर',
      id: 'Atas',
      pt: 'Topo',
    },
    'label.total': {
      en: 'Paint operations: {n}',
      ko: '칠하기 동작: {n}',
      ja: '描画命令: {n}',
      zh: '绘制操作: {n}',
      ar: 'عمليات الرسم: {n}',
      es: 'Operaciones de pintado: {n}',
      fr: 'Opérations de peinture : {n}',
      hi: 'पेंट ऑपरेशन: {n}',
      id: 'Operasi lukis: {n}',
      pt: 'Operações de pintura: {n}',
    },
    'label.thisStep': {
      en: 'Painted this step: {n}',
      ko: '이번 걸음의 칠하기: {n}',
      ja: 'この段階の描画: {n}',
      zh: '本步绘制: {n}',
      ar: 'رسم هذه الخطوة: {n}',
      es: 'Pintado en este paso: {n}',
      fr: 'Peint à cette étape : {n}',
      hi: 'इस चरण में पेंट: {n}',
      id: 'Dilukis di langkah ini: {n}',
      pt: 'Pintado neste passo: {n}',
    },
    'label.covered': {
      en: 'Partly covered: {n}',
      ko: '일부 가려진 것: {n}',
      ja: '一部隠れたもの: {n}',
      zh: '部分被遮挡: {n}',
      ar: 'مغطّى جزئيًا: {n}',
      es: 'Tapados en parte: {n}',
      fr: 'Partiellement cachés : {n}',
      hi: 'आंशिक रूप से ढके: {n}',
      id: 'Tertutup sebagian: {n}',
      pt: 'Tapados em parte: {n}',
    },
    'label.none': {
      en: 'none',
      ko: '없음',
      ja: 'なし',
      zh: '无',
      ar: 'لا شيء',
      es: 'ninguno',
      fr: 'aucun',
      hi: 'कोई नहीं',
      id: 'tidak ada',
      pt: 'nenhum',
    },
    'caption.start': {
      en: 'Elements: {elements} · Layers: {layers} · Sheets painted: {painted}',
      ko: '요소: {elements} · 층: {layers} · 칠한 장: {painted}',
      ja: '要素: {elements} · 層: {layers} · 塗ったシート: {painted}',
      zh: '元素: {elements} · 层: {layers} · 已绘制的纸: {painted}',
      ar: 'العناصر: {elements} · الطبقات: {layers} · الأوراق المرسومة: {painted}',
      es: 'Elementos: {elements} · Capas: {layers} · Hojas pintadas: {painted}',
      fr: 'Éléments : {elements} · Calques : {layers} · Feuilles peintes : {painted}',
      hi: 'तत्व: {elements} · परतें: {layers} · पेंट हुई शीटें: {painted}',
      id: 'Elemen: {elements} · Lapisan: {layers} · Lembar dilukis: {painted}',
      pt: 'Elementos: {elements} · Camadas: {layers} · Folhas pintadas: {painted}',
    },
    'caption.paint': {
      en: 'Layer {layer} is painted on its own sheet. Operations: {n}',
      ko: '{layer} 층을 제 장에 칠한다. 동작: {n}',
      ja: '層 {layer} を自分のシートに塗る。命令: {n}',
      zh: '层 {layer} 画在自己的纸上。操作: {n}',
      ar: 'تُرسم الطبقة {layer} على ورقتها الخاصة. العمليات: {n}',
      es: 'La capa {layer} se pinta en su propia hoja. Operaciones: {n}',
      fr: 'Le calque {layer} est peint sur sa propre feuille. Opérations : {n}',
      hi: 'परत {layer} अपनी शीट पर पेंट होती है। ऑपरेशन: {n}',
      id: 'Lapisan {layer} dilukis di lembarnya sendiri. Operasi: {n}',
      pt: 'A camada {layer} é pintada na sua própria folha. Operações: {n}',
    },
    'caption.composeFirst': {
      en: 'Composite: sheet {layer} goes down first. Partly covered: {covered}',
      ko: '합성: {layer} 장을 맨 아래에 놓는다. 일부 가려진 것: {covered}',
      ja: '合成: シート {layer} を最初に一番下へ置く。一部隠れたもの: {covered}',
      zh: '合成: 纸 {layer} 先放在最底下。部分被遮挡: {covered}',
      ar: 'التركيب: توضع الورقة {layer} أولًا في الأسفل. مغطّى جزئيًا: {covered}',
      es: 'Composición: la hoja {layer} va primero, abajo. Tapados en parte: {covered}',
      fr: 'Composition : la feuille {layer} est posée en premier, en bas. Partiellement cachés : {covered}',
      hi: 'कंपोज़िट: शीट {layer} सबसे पहले नीचे रखी जाती है। आंशिक रूप से ढके: {covered}',
      id: 'Komposit: lembar {layer} diletakkan pertama, paling bawah. Tertutup sebagian: {covered}',
      pt: 'Composição: a folha {layer} vai primeiro, em baixo. Tapados em parte: {covered}',
    },
    'caption.compose': {
      en: 'Composite: sheet {layer} goes on top. Partly covered below: {covered}',
      ko: '합성: {layer} 장을 위에 얹는다. 아래에서 일부 가려진 것: {covered}',
      ja: '合成: シート {layer} を上に重ねる。下で一部隠れたもの: {covered}',
      zh: '合成: 纸 {layer} 叠到上面。下方部分被遮挡: {covered}',
      ar: 'التركيب: توضع الورقة {layer} في الأعلى. مغطّى جزئيًا في الأسفل: {covered}',
      es: 'Composición: la hoja {layer} va encima. Tapados en parte debajo: {covered}',
      fr: 'Composition : la feuille {layer} passe dessus. Partiellement cachés dessous : {covered}',
      hi: 'कंपोज़िट: शीट {layer} ऊपर रखी जाती है। नीचे आंशिक रूप से ढके: {covered}',
      id: 'Komposit: lembar {layer} ditumpuk di atas. Tertutup sebagian di bawah: {covered}',
      pt: 'Composição: a folha {layer} vai por cima. Tapados em parte por baixo: {covered}',
    },
  },
};
