/**
 * integral — 미분과 적분: 쪼개어 다가간다 (완제품).
 *
 * 1차 데이터는 항 목록 · 점 a · 구간 · 두 손잡이 사다리뿐이다. n · 할선 · 조각 높이 · 추정 · 오차 · 비 · 참값은
 * 알고리즘이 셈한다. 곡선 x³ · 점 1 · 구간 [0, 2] · 2 진 폭 사다리는 예로 정한 값이다 (설명 글이 밝힌다).
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { IntegralData } from './algorithm.js';

const initialData: IntegralData = {
  type: 'integral',
  stepMs: 2000,
  terms: [[1, 3]],
  a: 1,
  lo: 0,
  hi: 2,
  ruleLadder: [0, 1, 2],
  rule: 0,
  widthLadder: [1, 0.5, 0.25, 0.125, 0.0625, 0.03125],
  width: 0.25,
};

export const integralFacet: FacetJson = {
  id: 'facet:integral',
  title: {
    en: 'Derivative and Integral: Closing In by Slicing',
    ko: '미분과 적분 — 쪼개어 다가간다',
    ja: '微分と積分 — 刻んで近づく',
    zh: '微分与积分——切分逼近',
    ar: 'التفاضل والتكامل: الاقتراب بالتقطيع',
    es: 'Derivada e integral: acercarse troceando',
    fr: "Dérivée et intégrale : s'approcher en découpant",
    hi: 'अवकलज और समाकल: टुकड़ों में बाँटकर पास पहुँचना',
    id: 'Turunan dan Integral: Mendekat dengan Memotong',
    pt: 'Derivada e integral: aproximar-se fatiando',
  },
  description: {
    en: 'Shrink the width h and both the secant slope and the Riemann sum approach the true value. See, for each sampling point, the ratio of errors when the width is halved — at an end it heads toward 0.5, at the middle it is 0.250.',
    ko: '폭 h 를 줄이면 할선 기울기와 리만 합이 참값에 다가간다. 폭을 반으로 줄일 때 오차의 비를 잡는 자리마다 본다 — 끝을 잡으면 0.5 쪽으로, 가운데를 잡으면 0.250.',
    ja: '幅 h を縮めると、割線の傾きもリーマン和も真の値に近づく。幅を半分にしたときの誤差の比を取る位置ごとに見る — 端を取ると 0.5 の方へ、真ん中を取ると 0.250。',
    zh: '缩小宽度 h，割线斜率和黎曼和都会接近真值。按取点位置查看宽度减半时误差之比——取端点时趋向 0.5，取中点时为 0.250。',
    ar: 'صغّر العرض h فيقترب ميل القاطع ومجموع ريمان كلاهما من القيمة الحقيقية. انظر إلى نسبة الخطأ عند تنصيف العرض لكل موضع قياس: عند الطرف تتجه نحو 0.5، وعند المنتصف 0.250.',
    es: 'Al reducir el ancho h, la pendiente de la secante y la suma de Riemann se acercan al valor real. Mira la razón de errores al reducir el ancho a la mitad según dónde se mide: en un extremo tiende a 0.5, en el centro es 0.250.',
    fr: "Réduisez la largeur h : la pente de la sécante et la somme de Riemann s'approchent de la vraie valeur. Observez le rapport des erreurs quand la largeur est divisée par deux, selon l'endroit mesuré : à une extrémité il tend vers 0.5, au milieu il vaut 0.250.",
    hi: 'चौड़ाई h घटाने पर छेदक रेखा की ढलान और रीमान योग दोनों असली मान के पास आते हैं। चौड़ाई आधी करने पर त्रुटियों का अनुपात हर मापने की जगह के लिए देखें — किनारे पर यह 0.5 की ओर जाता है, बीच में 0.250 रहता है।',
    id: 'Perkecil lebar h, maka kemiringan garis potong dan jumlah Riemann sama-sama mendekati nilai sebenarnya. Lihat rasio galat saat lebar dibagi dua menurut titik ukurnya — di ujung menuju 0.5, di tengah 0.250.',
    pt: 'Ao diminuir a largura h, a inclinação da secante e a soma de Riemann se aproximam do valor real. Veja a razão dos erros ao reduzir a largura à metade conforme o ponto medido: na extremidade tende a 0.5, no meio é 0.250.',
  },
  algorithm: 'module:integral',
  projector: 'module:integralProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'integral-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'rule',
          name: 'rule',
          label: {
            en: 'Sample at',
            ko: '잡는 자리',
            ja: '取る位置',
            zh: '取点位置',
            ar: 'موضع القياس',
            es: 'Medir en',
            fr: 'Mesurer à',
            hi: 'मापने की जगह',
            id: 'Titik ukur',
            pt: 'Medir em',
          },
          segments: [
            {
              value: 0,
              default: true,
              label: { en: 'Left', ko: '왼쪽', ja: '左端', zh: '左端', ar: 'اليسار', es: 'Izquierda', fr: 'Gauche', hi: 'बायाँ', id: 'Kiri', pt: 'Esquerda' },
            },
            {
              value: 1,
              label: { en: 'Right', ko: '오른쪽', ja: '右端', zh: '右端', ar: 'اليمين', es: 'Derecha', fr: 'Droite', hi: 'दायाँ', id: 'Kanan', pt: 'Direita' },
            },
            {
              value: 2,
              label: { en: 'Middle', ko: '가운데', ja: '中央', zh: '中点', ar: 'المنتصف', es: 'Centro', fr: 'Milieu', hi: 'बीच', id: 'Tengah', pt: 'Meio' },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'width',
          name: 'width',
          label: {
            en: 'Width h',
            ko: '폭 h',
            ja: '幅 h',
            zh: '宽度 h',
            ar: 'العرض h',
            es: 'Ancho h',
            fr: 'Largeur h',
            hi: 'चौड़ाई h',
            id: 'Lebar h',
            pt: 'Largura h',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 0.5, label: '1/2' },
            { value: 0.25, label: '1/4', default: true },
            { value: 0.125, label: '1/8' },
            { value: 0.0625, label: '1/16' },
            { value: 0.03125, label: '1/32' },
          ],
        },
      ],
      metrics: [
        {
          name: 'strip-count',
          label: {
            en: 'Strips',
            ko: '조각 수',
            ja: '短冊の数',
            zh: '条数',
            ar: 'عدد الشرائح',
            es: 'Franjas',
            fr: 'Bandes',
            hi: 'पट्टियाँ',
            id: 'Jumlah pita',
            pt: 'Faixas',
          },
          initial: 0,
        },
        {
          name: 'curve-evals',
          label: {
            en: 'Calls to f',
            ko: 'f 를 부른 수',
            ja: 'f を呼んだ回数',
            zh: '调用 f 的次数',
            ar: 'مرات استدعاء f',
            es: 'Llamadas a f',
            fr: 'Appels de f',
            hi: 'f को बुलाने की संख्या',
            id: 'Panggilan f',
            pt: 'Chamadas de f',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:integral-imperative',
      label: {
        en: 'Difference and sum',
        ko: '차분과 합',
        ja: '差分と和',
        zh: '差分与求和',
        ar: 'الفرق والمجموع',
        es: 'Diferencia y suma',
        fr: 'Différence et somme',
        hi: 'अंतर और योग',
        id: 'Selisih dan jumlah',
        pt: 'Diferença e soma',
      },
    },
  },
  messages: {
    'caption.init': {
      en: 'Slope at the point, area over the interval · width h = {h}',
      ko: '점의 기울기와 구간의 넓이 · 폭 h = {h}',
      ja: '点での傾きと区間の面積 · 幅 h = {h}',
      zh: '点处的斜率与区间上的面积 · 宽度 h = {h}',
      ar: 'الميل عند النقطة والمساحة على الفترة · العرض h = {h}',
      es: 'Pendiente en el punto, área sobre el intervalo · ancho h = {h}',
      fr: "Pente au point, aire sur l'intervalle · largeur h = {h}",
      hi: 'बिंदु पर ढलान, अंतराल पर क्षेत्रफल · चौड़ाई h = {h}',
      id: 'Kemiringan di titik, luas pada selang · lebar h = {h}',
      pt: 'Inclinação no ponto, área no intervalo · largura h = {h}',
    },
    'caption.secant.left': {
      en: 'Backward difference (f(a) − f(a − h)) / h · slope estimate {est}',
      ko: '뒤 차분 (f(a) − f(a − h)) / h · 기울기 추정 {est}',
      ja: '後退差分 (f(a) − f(a − h)) / h · 傾きの推定 {est}',
      zh: '后向差分 (f(a) − f(a − h)) / h · 斜率估计 {est}',
      ar: 'الفرق الخلفي (f(a) − f(a − h)) / h · تقدير الميل {est}',
      es: 'Diferencia hacia atrás (f(a) − f(a − h)) / h · pendiente estimada {est}',
      fr: 'Différence arrière (f(a) − f(a − h)) / h · pente estimée {est}',
      hi: 'पिछला अंतर (f(a) − f(a − h)) / h · ढलान का अनुमान {est}',
      id: 'Selisih mundur (f(a) − f(a − h)) / h · taksiran kemiringan {est}',
      pt: 'Diferença regressiva (f(a) − f(a − h)) / h · inclinação estimada {est}',
    },
    'caption.secant.right': {
      en: 'Forward difference (f(a + h) − f(a)) / h · slope estimate {est}',
      ko: '앞 차분 (f(a + h) − f(a)) / h · 기울기 추정 {est}',
      ja: '前進差分 (f(a + h) − f(a)) / h · 傾きの推定 {est}',
      zh: '前向差分 (f(a + h) − f(a)) / h · 斜率估计 {est}',
      ar: 'الفرق الأمامي (f(a + h) − f(a)) / h · تقدير الميل {est}',
      es: 'Diferencia hacia adelante (f(a + h) − f(a)) / h · pendiente estimada {est}',
      fr: 'Différence avant (f(a + h) − f(a)) / h · pente estimée {est}',
      hi: 'अगला अंतर (f(a + h) − f(a)) / h · ढलान का अनुमान {est}',
      id: 'Selisih maju (f(a + h) − f(a)) / h · taksiran kemiringan {est}',
      pt: 'Diferença progressiva (f(a + h) − f(a)) / h · inclinação estimada {est}',
    },
    'caption.secant.mid': {
      en: 'Central difference (f(a + h) − f(a − h)) / 2h · slope estimate {est}',
      ko: '가운데 차분 (f(a + h) − f(a − h)) / 2h · 기울기 추정 {est}',
      ja: '中心差分 (f(a + h) − f(a − h)) / 2h · 傾きの推定 {est}',
      zh: '中心差分 (f(a + h) − f(a − h)) / 2h · 斜率估计 {est}',
      ar: 'الفرق المركزي (f(a + h) − f(a − h)) / 2h · تقدير الميل {est}',
      es: 'Diferencia central (f(a + h) − f(a − h)) / 2h · pendiente estimada {est}',
      fr: 'Différence centrée (f(a + h) − f(a − h)) / 2h · pente estimée {est}',
      hi: 'केंद्रीय अंतर (f(a + h) − f(a − h)) / 2h · ढलान का अनुमान {est}',
      id: 'Selisih tengah (f(a + h) − f(a − h)) / 2h · taksiran kemiringan {est}',
      pt: 'Diferença central (f(a + h) − f(a − h)) / 2h · inclinação estimada {est}',
    },
    'caption.strips.left': {
      en: "Height measured at each strip's left end · strips {n}",
      ko: '조각마다 왼쪽 끝에서 높이를 잰다 · 조각 {n}',
      ja: '各短冊の左端で高さを測る · 短冊 {n}',
      zh: '在每条的左端测高度 · 条数 {n}',
      ar: 'يُقاس الارتفاع عند الطرف الأيسر لكل شريحة · الشرائح {n}',
      es: 'Altura medida en el extremo izquierdo de cada franja · franjas {n}',
      fr: "Hauteur mesurée à l'extrémité gauche de chaque bande · bandes {n}",
      hi: 'हर पट्टी के बाएँ सिरे पर ऊँचाई मापी जाती है · पट्टियाँ {n}',
      id: 'Tinggi diukur di ujung kiri tiap pita · pita {n}',
      pt: 'Altura medida na extremidade esquerda de cada faixa · faixas {n}',
    },
    'caption.strips.right': {
      en: "Height measured at each strip's right end · strips {n}",
      ko: '조각마다 오른쪽 끝에서 높이를 잰다 · 조각 {n}',
      ja: '各短冊の右端で高さを測る · 短冊 {n}',
      zh: '在每条的右端测高度 · 条数 {n}',
      ar: 'يُقاس الارتفاع عند الطرف الأيمن لكل شريحة · الشرائح {n}',
      es: 'Altura medida en el extremo derecho de cada franja · franjas {n}',
      fr: "Hauteur mesurée à l'extrémité droite de chaque bande · bandes {n}",
      hi: 'हर पट्टी के दाएँ सिरे पर ऊँचाई मापी जाती है · पट्टियाँ {n}',
      id: 'Tinggi diukur di ujung kanan tiap pita · pita {n}',
      pt: 'Altura medida na extremidade direita de cada faixa · faixas {n}',
    },
    'caption.strips.mid': {
      en: "Height measured at each strip's midpoint · strips {n}",
      ko: '조각마다 가운데에서 높이를 잰다 · 조각 {n}',
      ja: '各短冊の中央で高さを測る · 短冊 {n}',
      zh: '在每条的中点测高度 · 条数 {n}',
      ar: 'يُقاس الارتفاع عند منتصف كل شريحة · الشرائح {n}',
      es: 'Altura medida en el punto medio de cada franja · franjas {n}',
      fr: 'Hauteur mesurée au milieu de chaque bande · bandes {n}',
      hi: 'हर पट्टी के बीच में ऊँचाई मापी जाती है · पट्टियाँ {n}',
      id: 'Tinggi diukur di titik tengah tiap pita · pita {n}',
      pt: 'Altura medida no ponto médio de cada faixa · faixas {n}',
    },
    'caption.sum': {
      en: 'Add height × width strip by strip · area estimate {est}',
      ko: '조각마다 높이 × 폭을 더한다 · 넓이 추정 {est}',
      ja: '短冊ごとに高さ × 幅を足す · 面積の推定 {est}',
      zh: '逐条累加 高度 × 宽度 · 面积估计 {est}',
      ar: 'اجمع الارتفاع × العرض شريحةً شريحة · تقدير المساحة {est}',
      es: 'Suma altura × ancho franja por franja · área estimada {est}',
      fr: 'Ajouter hauteur × largeur bande par bande · aire estimée {est}',
      hi: 'हर पट्टी का ऊँचाई × चौड़ाई जोड़ें · क्षेत्रफल का अनुमान {est}',
      id: 'Jumlahkan tinggi × lebar tiap pita · taksiran luas {est}',
      pt: 'Somar altura × largura faixa a faixa · área estimada {est}',
    },
    'caption.compare': {
      en: 'Width {h2} → {h} · slope error ratio {rs} · area error ratio {ra}',
      ko: '폭 {h2} → {h} · 기울기 오차 비 {rs} · 넓이 오차 비 {ra}',
      ja: '幅 {h2} → {h} · 傾きの誤差比 {rs} · 面積の誤差比 {ra}',
      zh: '宽度 {h2} → {h} · 斜率误差比 {rs} · 面积误差比 {ra}',
      ar: 'العرض {h2} → {h} · نسبة خطأ الميل {rs} · نسبة خطأ المساحة {ra}',
      es: 'Ancho {h2} → {h} · razón del error de pendiente {rs} · razón del error de área {ra}',
      fr: "Largeur {h2} → {h} · rapport d'erreur de pente {rs} · rapport d'erreur d'aire {ra}",
      hi: 'चौड़ाई {h2} → {h} · ढलान त्रुटि अनुपात {rs} · क्षेत्रफल त्रुटि अनुपात {ra}',
      id: 'Lebar {h2} → {h} · rasio galat kemiringan {rs} · rasio galat luas {ra}',
      pt: 'Largura {h2} → {h} · razão do erro de inclinação {rs} · razão do erro de área {ra}',
    },
    'caption.compareNone': {
      en: 'Width {h} · no wider rung 2h to compare',
      ko: '폭 {h} · 견줄 윗 칸 2h 없음',
      ja: '幅 {h} · 比べる一段上の 2h がない',
      zh: '宽度 {h} · 没有可比较的上一级 2h',
      ar: 'العرض {h} · لا توجد درجة أعرض 2h للمقارنة',
      es: 'Ancho {h} · no hay un escalón 2h más ancho para comparar',
      fr: 'Largeur {h} · pas de cran 2h plus large à comparer',
      hi: 'चौड़ाई {h} · तुलना के लिए ऊपर का 2h नहीं है',
      id: 'Lebar {h} · tidak ada anak tangga 2h yang lebih lebar untuk dibandingkan',
      pt: 'Largura {h} · não há degrau 2h mais largo para comparar',
    },
    'label.slope': {
      en: 'Slope', ko: '기울기', ja: '傾き', zh: '斜率', ar: 'الميل', es: 'Pendiente', fr: 'Pente', hi: 'ढलान', id: 'Kemiringan', pt: 'Inclinação',
    },
    'label.area': {
      en: 'Area', ko: '넓이', ja: '面積', zh: '面积', ar: 'المساحة', es: 'Área', fr: 'Aire', hi: 'क्षेत्रफल', id: 'Luas', pt: 'Área',
    },
    'label.estimate': {
      en: 'Estimate', ko: '추정', ja: '推定', zh: '估计', ar: 'التقدير', es: 'Estimación', fr: 'Estimation', hi: 'अनुमान', id: 'Taksiran', pt: 'Estimativa',
    },
    'label.error': {
      en: 'Error', ko: '오차', ja: '誤差', zh: '误差', ar: 'الخطأ', es: 'Error', fr: 'Erreur', hi: 'त्रुटि', id: 'Galat', pt: 'Erro',
    },
    'label.trueValue': {
      en: 'True value', ko: '참값', ja: '真の値', zh: '真值', ar: 'القيمة الحقيقية', es: 'Valor real', fr: 'Vraie valeur', hi: 'असली मान', id: 'Nilai sebenarnya', pt: 'Valor real',
    },
    'label.ratio': {
      en: 'Ratio', ko: '비', ja: '比', zh: '比', ar: 'النسبة', es: 'Razón', fr: 'Rapport', hi: 'अनुपात', id: 'Rasio', pt: 'Razão',
    },
    'label.compare': {
      en: 'Error, width 2h → h',
      ko: '오차 · 폭 2h → h',
      ja: '誤差 · 幅 2h → h',
      zh: '误差 · 宽度 2h → h',
      ar: 'الخطأ · العرض 2h → h',
      es: 'Error, ancho 2h → h',
      fr: 'Erreur, largeur 2h → h',
      hi: 'त्रुटि, चौड़ाई 2h → h',
      id: 'Galat, lebar 2h → h',
      pt: 'Erro, largura 2h → h',
    },
    'label.slopeError': {
      en: 'Slope error', ko: '기울기 오차', ja: '傾きの誤差', zh: '斜率误差', ar: 'خطأ الميل', es: 'Error de pendiente', fr: 'Erreur de pente', hi: 'ढलान की त्रुटि', id: 'Galat kemiringan', pt: 'Erro de inclinação',
    },
    'label.areaError': {
      en: 'Area error', ko: '넓이 오차', ja: '面積の誤差', zh: '面积误差', ar: 'خطأ المساحة', es: 'Error de área', fr: "Erreur d'aire", hi: 'क्षेत्रफल की त्रुटि', id: 'Galat luas', pt: 'Erro de área',
    },
    'label.width': {
      en: 'width {h}', ko: '폭 {h}', ja: '幅 {h}', zh: '宽度 {h}', ar: 'العرض {h}', es: 'ancho {h}', fr: 'largeur {h}', hi: 'चौड़ाई {h}', id: 'lebar {h}', pt: 'largura {h}',
    },
  },
};
