/**
 * 랜덤 포레스트 facet JSON 선언.
 *
 * 진행 모델은 reactive 다. 마운트하면 나무 열여섯을 하나씩 기르며 확신 밭을
 * 다시 셈하고, 다 자라면 **숲 크기 슬라이더** 를 기다린다. 1 · 2 · 4 · 8 · 16
 * 중에서 고르면 그 값으로 밭과 물음점의 표를 처음부터 다시 셈한다 — 재생을
 * 처음으로 돌리지 않아야 값끼리 견줄 수 있다.
 *
 * 데이터는 decisionTree 와 같은 계단 배치에 잡음 하나 (1.4, 1.6) 를 더한 열여덟
 * 점이다. 그 하나가 순수한 잎을 만들기 어렵게 해 나무마다 다른 경계를 낳는다.
 *
 * 물음점 (3, 3) 은 열여섯 그루가 정확히 8 대 8 로 갈리는 자리다. 표가 갈리는
 * 것이 무슨 뜻인지를 한 점에서 보이려고 골랐다.
 */

import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

/** 이름표 있는 점 열여덟. label 0 = A, 1 = B. */
const POINTS_18 = [
  { x: 1.0, y: 1.0, label: 0 },
  { x: 1.5, y: 2.5, label: 0 },
  { x: 2.0, y: 1.5, label: 0 },
  { x: 1.0, y: 4.0, label: 0 },
  { x: 2.0, y: 5.0, label: 0 },
  { x: 3.0, y: 4.5, label: 0 },
  { x: 4.0, y: 5.5, label: 0 },
  { x: 3.5, y: 4.0, label: 0 },
  { x: 4.5, y: 5.0, label: 0 },
  { x: 3.0, y: 1.0, label: 1 },
  { x: 4.0, y: 2.0, label: 1 },
  { x: 3.5, y: 1.5, label: 1 },
  { x: 4.5, y: 2.5, label: 1 },
  { x: 5.5, y: 1.5, label: 1 },
  { x: 6.0, y: 3.0, label: 1 },
  { x: 5.5, y: 5.0, label: 1 },
  { x: 6.5, y: 4.0, label: 1 },
  { x: 1.4, y: 1.6, label: 1 },
];

export const randomForestFacet: FacetJson = {
  id: 'facet:randomForest',
  title: {
    en: 'Random Forest — What Many Trees Add',
    ko: '랜덤 포레스트 — 여럿을 기르면 무엇이 더 생기는가',
    ja: 'ランダムフォレスト — 木を増やすと何が加わるか',
    zh: '随机森林 — 多种几棵树能多出什么',
    ar: 'الغابة العشوائية — ما الذي تضيفه أشجار كثيرة',
    es: 'Bosque aleatorio: lo que añaden muchos árboles',
    fr: 'Forêt aléatoire — ce qu\'apportent plusieurs arbres',
    hi: 'रैंडम फ़ॉरेस्ट — कई पेड़ क्या जोड़ते हैं',
    id: 'Random forest — apa yang ditambahkan banyak pohon',
    pt: 'Floresta aleatória — o que muitas árvores acrescentam',
  },
  description: {
    en: 'One tree is 100% sure everywhere. A forest also tells you how sure it is.',
    ko: '나무 하나는 평면 어디서나 100% 확신한다. 숲은 자기가 얼마나 확신하는지도 말한다.',
    ja: '木が一本なら、どこでも 100% 言い切る。森はどれだけ確かかまで教えてくれる。',
    zh: '一棵树在哪里都是 100% 笃定。森林还会告诉你它有多笃定。',
    ar: 'شجرة واحدة واثقة 100% في كل مكان. أما الغابة فتخبرك أيضًا بمدى ثقتها.',
    es: 'Un solo árbol está 100% seguro en todas partes. Un bosque además te dice cuánta seguridad tiene.',
    fr: 'Un seul arbre est sûr à 100% partout. Une forêt vous dit en plus à quel point elle est sûre.',
    hi: 'एक पेड़ हर जगह 100% निश्चित होता है। जंगल यह भी बताता है कि वह कितना निश्चित है।',
    id: 'Satu pohon 100% yakin di mana pun. Hutan juga memberi tahu seberapa yakin dirinya.',
    pt: 'Uma só árvore tem 100% de certeza em toda parte. Uma floresta ainda diz quanta certeza tem.',
  },
  algorithm: 'module:randomForest',
  projector: 'module:randomForestProjector',
  initialData: {
    type: 'random-forest',
    points: POINTS_18,
    seed: 20260910,
    treeCount: 16,
    gridSize: 32,
    planeMax: 7,
    probe: { x: 3.0, y: 3.0 },
    initialSize: 16,
    timings: { walkStepMs: 60, treeBeatMs: 200, settleMs: 400 },
  },
  shuffleOnReset: false,
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'stage', padding: '8px 0' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  messages: {
    'caption.start': {
      en: 'Growing {total} trees, one at a time.',
      ko: '나무 {total} 그루를 하나씩 기른다.',
      ja: '木を {total} 本、一本ずつ育てる。',
      zh: '一棵接一棵，种下 {total} 棵树。',
      ar: 'نزرع {total} شجرة، واحدة تلو الأخرى.',
      es: 'Cultivando {total} árboles, uno a uno.',
      fr: 'On fait pousser {total} arbres, un par un.',
      hi: '{total} पेड़ एक-एक करके उगाए जा रहे हैं।',
      id: 'Menumbuhkan {total} pohon, satu per satu.',
      pt: 'Cultivando {total} árvores, uma de cada vez.',
    },
    'caption.grown': {
      en: 'Tree {t} of {total} — {leaves} leaves, right on {correct} of {points} training points.',
      ko: '나무 {t}/{total} — 잎 {leaves} 개, 훈련 점 {points} 개 가운데 {correct} 개 적중.',
      ja: '木 {t}/{total} — 葉 {leaves} 枚、訓練点 {points} 個のうち {correct} 個に的中。',
      zh: '第 {t}/{total} 棵树 — {leaves} 片叶子，{points} 个训练点中说对 {correct} 个。',
      ar: 'الشجرة {t} من {total} — {leaves} ورقة، تصيب {correct} من {points} نقطة تدريب.',
      es: 'Árbol {t} de {total}: {leaves} hojas, acierta en {correct} de {points} puntos de entrenamiento.',
      fr: 'Arbre {t} sur {total} — {leaves} feuilles, juste sur {correct} des {points} points d\'entraînement.',
      hi: 'पेड़ {t}/{total} — {leaves} पत्तियाँ, {points} प्रशिक्षण बिंदुओं में से {correct} सही।',
      id: 'Pohon {t} dari {total} — {leaves} daun, benar pada {correct} dari {points} titik latih.',
      pt: 'Árvore {t} de {total} — {leaves} folhas, acerta {correct} de {points} pontos de treino.',
    },
    'caption.slide': {
      en: 'Now drag the forest size. At 1 the plane is one flat colour; the band appears only once trees disagree.',
      ko: '이제 숲 크기를 옮겨 보아라. 1 에서는 평면이 한 가지 색이고, 나무들이 갈리고 나서야 띠가 생긴다.',
      ja: '森の大きさを動かしてみよう。1 では平面は一色で、木の意見が割れて初めて帯が現れる。',
      zh: '现在拖动森林的大小。到 1 时整个平面只有一种颜色；只有当树意见分歧，带子才会出现。',
      ar: 'حرّك الآن حجم الغابة. عند 1 يكون المستوى بلون واحد؛ ولا يظهر الشريط إلا حين تختلف الأشجار.',
      es: 'Ahora mueve el tamaño del bosque. En 1 el plano es de un solo color; la franja aparece solo cuando los árboles discrepan.',
      fr: 'Faites maintenant glisser la taille de la forêt. À 1 le plan est d\'une seule couleur ; la bande n\'apparaît que lorsque les arbres divergent.',
      hi: 'अब जंगल का आकार खिसकाइए। 1 पर समतल एक ही रंग का है; पट्टी तभी उभरती है जब पेड़ आपस में असहमत हों।',
      id: 'Sekarang geser ukuran hutan. Pada 1 bidangnya satu warna rata; pita muncul hanya setelah pohon-pohon berbeda pendapat.',
      pt: 'Agora arraste o tamanho da floresta. Em 1 o plano tem uma só cor; a faixa só aparece quando as árvores discordam.',
    },
    'caption.oneTree': {
      en: 'One tree — sure everywhere. Split cells: {split} of {cells}. Right on {correct} of {points}.',
      ko: '나무 하나 — 어디서나 확신한다. 갈리는 칸은 {cells} 중 {split}. 적중은 {points} 중 {correct}.',
      ja: '木は一本 — どこでも言い切る。割れた枠は {cells} 中 {split}。的中は {points} 中 {correct}。',
      zh: '只有一棵树 — 哪里都笃定。分歧的格子 {cells} 中有 {split}。说对 {points} 中的 {correct}。',
      ar: 'شجرة واحدة — واثقة في كل مكان. الخلايا المنقسمة: {split} من {cells}. تصيب {correct} من {points}.',
      es: 'Un solo árbol: seguro en todas partes. Celdas divididas: {split} de {cells}. Acierta en {correct} de {points}.',
      fr: 'Un seul arbre — sûr partout. Cases partagées : {split} sur {cells}. Juste sur {correct} sur {points}.',
      hi: 'एक पेड़ — हर जगह निश्चित। बँटी कोशिकाएँ: {cells} में से {split}. सही: {points} में से {correct}.',
      id: 'Satu pohon — yakin di mana-mana. Sel terbelah: {split} dari {cells}. Benar pada {correct} dari {points}.',
      pt: 'Uma só árvore — segura em toda parte. Células divididas: {split} de {cells}. Acerta {correct} de {points}.',
    },
    'caption.size': {
      en: 'Forest of {n} — split cells: {split} of {cells}. Right on {correct} of {points}.',
      ko: '나무 {n} 그루의 숲 — 갈리는 칸은 {cells} 중 {split}. 적중은 {points} 중 {correct}.',
      ja: '木 {n} 本の森 — 割れた枠は {cells} 中 {split}。的中は {points} 中 {correct}。',
      zh: '{n} 棵树的森林 — 分歧的格子 {cells} 中有 {split}。说对 {points} 中的 {correct}。',
      ar: 'غابة من {n} — الخلايا المنقسمة: {split} من {cells}. تصيب {correct} من {points}.',
      es: 'Bosque de {n}: celdas divididas: {split} de {cells}. Acierta en {correct} de {points}.',
      fr: 'Forêt de {n} — cases partagées : {split} sur {cells}. Juste sur {correct} sur {points}.',
      hi: '{n} पेड़ों का जंगल — बँटी कोशिकाएँ: {cells} में से {split}. सही: {points} में से {correct}.',
      id: 'Hutan {n} pohon — sel terbelah: {split} dari {cells}. Benar pada {correct} dari {points}.',
      pt: 'Floresta de {n} — células divididas: {split} de {cells}. Acerta {correct} de {points}.',
    },
    'label.grown': {
      en: 'trees grown',
      ko: '기른 나무',
      ja: '育てた木',
      zh: '已种的树',
      ar: 'الأشجار المزروعة',
      es: 'árboles cultivados',
      fr: 'arbres poussés',
      hi: 'उगाए गए पेड़',
      id: 'pohon yang tumbuh',
      pt: 'árvores cultivadas',
    },
    'label.votes': {
      en: 'votes at the probe point',
      ko: '물음점이 받은 표',
      ja: '問いの点が集めた票',
      zh: '探针点收到的票',
      ar: 'الأصوات عند نقطة الفحص',
      es: 'votos en el punto de prueba',
      fr: 'votes au point sondé',
      hi: 'जाँच बिंदु पर मत',
      id: 'suara di titik uji',
      pt: 'votos no ponto de sondagem',
    },
    'label.sureness': {
      en: 'how sure the forest is',
      ko: '숲이 얼마나 확신하는가',
      ja: '森がどれだけ確かか',
      zh: '森林有多笃定',
      ar: 'إلى أي مدى تثق الغابة',
      es: 'cuánta seguridad tiene el bosque',
      fr: 'à quel point la forêt est sûre',
      hi: 'जंगल कितना निश्चित है',
      id: 'seberapa yakin hutan itu',
      pt: 'quanta certeza a floresta tem',
    },
    'label.rampSplit': {
      en: 'split',
      ko: '갈림',
      ja: '割れる',
      zh: '分歧',
      ar: 'منقسم',
      es: 'dividido',
      fr: 'partagé',
      hi: 'बँटा',
      id: 'terbelah',
      pt: 'dividido',
    },
    'label.rampSure': {
      en: 'unanimous',
      ko: '만장일치',
      ja: '全会一致',
      zh: '一致',
      ar: 'بالإجماع',
      es: 'unánime',
      fr: 'unanime',
      hi: 'सर्वसम्मत',
      id: 'bulat',
      pt: 'unânime',
    },
    'label.seen': {
      en: 'looking at {n} of {total} trees',
      ko: '보는 나무는 {total} 중 {n}',
      ja: '見ている木は {total} 中 {n}',
      zh: '正看着 {total} 棵中的 {n} 棵',
      ar: 'ننظر إلى {n} من {total} شجرة',
      es: 'mirando {n} de {total} árboles',
      fr: 'on regarde {n} arbres sur {total}',
      hi: '{total} पेड़ों में से {n} देखे जा रहे हैं',
      id: 'melihat {n} dari {total} pohon',
      pt: 'olhando {n} de {total} árvores',
    },
    'label.treeStat': {
      en: 'tree {t}: {distinct} rows drawn, {left} left out, {leaves} leaves',
      ko: '나무 {t}: 뽑힌 자리 {distinct}, 남은 것 {left}, 잎 {leaves}',
      ja: '木 {t}: 引いた行 {distinct}、外れた行 {left}、葉 {leaves}',
      zh: '第 {t} 棵：抽到 {distinct} 行，落下 {left} 行，{leaves} 片叶子',
      ar: 'الشجرة {t}: {distinct} صفًا مسحوبًا، {left} خارجًا، {leaves} ورقة',
      es: 'árbol {t}: {distinct} filas sacadas, {left} fuera, {leaves} hojas',
      fr: 'arbre {t} : {distinct} lignes tirées, {left} laissées de côté, {leaves} feuilles',
      hi: 'पेड़ {t}: {distinct} पंक्तियाँ चुनी गईं, {left} बाहर, {leaves} पत्तियाँ',
      id: 'pohon {t}: {distinct} baris terambil, {left} tersisa, {leaves} daun',
      pt: 'árvore {t}: {distinct} linhas sorteadas, {left} de fora, {leaves} folhas',
    },
    'label.verdict': {
      en: '{size} trees say {mark} ({a} to {b})',
      ko: '나무 {size} 그루의 답은 {mark} ({a} 대 {b})',
      ja: '木 {size} 本の答えは {mark}（{a} 対 {b}）',
      zh: '{size} 棵树的答案是 {mark}（{a} 比 {b}）',
      ar: '{size} شجرة تقول {mark} ({a} مقابل {b})',
      es: '{size} árboles dicen {mark} ({a} a {b})',
      fr: '{size} arbres disent {mark} ({a} contre {b})',
      hi: '{size} पेड़ कहते हैं {mark} ({a} बनाम {b})',
      id: '{size} pohon berkata {mark} ({a} banding {b})',
      pt: '{size} árvores dizem {mark} ({a} a {b})',
    },
  },
  blocks: {
    stage: { type: 'random-forest-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback!,
        {
          widget: 'segmented-slider',
          action: 'forest-size',
          name: 'forestSize',
          label: {
            en: 'Forest size',
            ko: '숲 크기',
            ja: '森の大きさ',
            zh: '森林大小',
            ar: 'حجم الغابة',
            es: 'Tamaño del bosque',
            fr: 'Taille de la forêt',
            hi: 'जंगल का आकार',
            id: 'Ukuran hutan',
            pt: 'Tamanho da floresta',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 4, label: '4' },
            { value: 8, label: '8' },
            { value: 16, label: '16', default: true },
          ],
        },
      ],
      metrics: [
        {
          name: 'tree-count',
          label: {
            en: 'Trees grown',
            ko: '기른 나무',
            ja: '育てた木',
            zh: '已种的树',
            ar: 'الأشجار المزروعة',
            es: 'Árboles cultivados',
            fr: 'Arbres poussés',
            hi: 'उगाए गए पेड़',
            id: 'Pohon tumbuh',
            pt: 'Árvores cultivadas',
          },
          initial: 0,
        },
        {
          name: 'correct-count',
          label: {
            en: 'Points the forest gets right',
            ko: '숲이 맞힌 점',
            ja: '森が当てた点',
            zh: '森林答对的点',
            ar: 'النقاط التي تصيبها الغابة',
            es: 'Puntos que el bosque acierta',
            fr: 'Points justes de la forêt',
            hi: 'जंगल के सही बिंदु',
            id: 'Titik yang benar',
            pt: 'Pontos que a floresta acerta',
          },
          initial: 0,
        },
        {
          name: 'split-cell-count',
          label: {
            en: 'Cells where the vote splits',
            ko: '표가 갈리는 칸',
            ja: '票が割れる枠',
            zh: '投票分歧的格子',
            ar: 'الخلايا التي ينقسم فيها التصويت',
            es: 'Celdas donde el voto se divide',
            fr: 'Cases où le vote se partage',
            hi: 'जहाँ मत बँटता है',
            id: 'Sel dengan suara terbelah',
            pt: 'Células com voto dividido',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      label: {
        en: 'Code',
        ko: '코드',
        ja: 'コード',
        zh: '代码',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
      ir: 'ir:random-forest',
    },
  },
};
