import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 함수 둘을 이어 붙이면, 입력을 조금 밀었을 때 출력은 몇 배로 움직이는가?
 *
 * 입력 x 를 0.01 밀면 그 움직임이 안쪽 함수 u = 3x 를 건너며 3 배로, 바깥 함수 y = u²/3 을
 * 건너며 다시 2.01 배로 불어난다. 통째 배 6.03 은 두 단계 배의 곱이고, 민 폭을 0 으로 보내면
 * 3 · 2 · 6 이 선다.
 */
export const chainRuleMultiplyFacet: FacetJson = {
  id: 'facet:chainRuleMultiply',
  title: {
    en: 'Chain rule: changes multiply',
    ko: '연쇄 법칙: 변화가 곱해진다',
    ja: '連鎖律：変化は掛け合わされる',
    zh: '链式法则：变化相乘',
    ar: 'قاعدة السلسلة: التغيّرات تتضاعف',
    es: 'Regla de la cadena: los cambios se multiplican',
    fr: 'Dérivation en chaîne : les variations se multiplient',
    hi: 'शृंखला नियम: बदलाव गुणा होते हैं',
    id: 'Aturan rantai: perubahan saling mengali',
    pt: 'Regra da cadeia: as variações se multiplicam',
  },
  description: {
    en: 'Nudge the input of two chained functions and watch the small move grow once at each function; the whole ratio is the product.',
    ko: '이어 붙인 두 함수의 입력을 조금 밀면, 그 작은 움직임이 함수마다 한 번씩 불어나고 통째 배는 두 배의 곱이 된다.',
    ja: '連結した二つの関数の入力を少しずらすと、小さな動きが関数ごとに一度ずつ膨らみ、全体の倍率はその積になる。',
    zh: '把两个串联函数的输入推动一点，这个小变化每经过一个函数就放大一次，整体倍数是两者之积。',
    ar: 'ادفع مدخل دالتين متتاليتين قليلًا، فتكبر الحركة الصغيرة مرة عند كل دالة، والنسبة الكلية هي حاصل الضرب.',
    es: 'Empuja un poco la entrada de dos funciones encadenadas: el pequeño movimiento crece una vez en cada función y la razón total es el producto.',
    fr: "Poussez un peu l'entrée de deux fonctions enchaînées : le petit déplacement grandit une fois à chaque fonction, et le rapport total est le produit.",
    hi: 'दो जुड़े फलनों के इनपुट को थोड़ा खिसकाइए — छोटी हलचल हर फलन पर एक बार बढ़ती है और कुल अनुपात दोनों का गुणनफल है।',
    id: 'Dorong sedikit masukan dua fungsi berantai: gerak kecil itu membesar sekali di tiap fungsi, dan rasio totalnya adalah hasil kali.',
    pt: 'Empurre um pouco a entrada de duas funções encadeadas: o pequeno movimento cresce uma vez em cada função e a razão total é o produto.',
  },
  algorithm: 'module:chainRuleMultiply',
  scene: 'module:chainRuleMultiplyScene',
  initialData: {
    type: 'chain-rule-multiply',
    symbols: ['x', 'u', 'y'],
    inner: [[3, 1]],
    outer: [[1 / 3, 2]],
    x0: 1,
    dx: 0.01,
    stepMs: 1800,
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has moved yet.',
      ko: '아직 아무것도 움직이지 않았다.',
      ja: 'まだ何も動いていない。',
      zh: '还没有任何东西移动。',
      ar: 'لم يتحرك شيء بعد.',
      es: 'Todavía no se ha movido nada.',
      fr: "Rien n'a encore bougé.",
      hi: 'अभी कुछ भी नहीं हिला है।',
      id: 'Belum ada yang bergerak.',
      pt: 'Nada se moveu ainda.',
    },
    'caption.push': {
      en: 'Push {in} by {dx}.',
      ko: '{in} 쪽을 {dx} 만큼 민다.',
      ja: '{in} を {dx} だけ押す。',
      zh: '把 {in} 推动 {dx}。',
      ar: 'ادفع {in} بمقدار {dx}.',
      es: 'Empuja {in} en {dx}.',
      fr: 'On pousse {in} de {dx}.',
      hi: '{in} को {dx} खिसकाइए।',
      id: 'Dorong {in} sebesar {dx}.',
      pt: 'Empurre {in} em {dx}.',
    },
    'caption.inner': {
      en: 'Across the inner function: Δ{mid} = {d} · ratio ×{r}',
      ko: '안쪽 함수를 건넜다 · Δ{mid} = {d} · 배 ×{r}',
      ja: '内側の関数を渡った · Δ{mid} = {d} · 倍率 ×{r}',
      zh: '穿过内层函数 · Δ{mid} = {d} · 倍数 ×{r}',
      ar: 'عبر الدالة الداخلية · Δ{mid} = {d} · النسبة ×{r}',
      es: 'Cruza la función interior · Δ{mid} = {d} · razón ×{r}',
      fr: 'Traversée de la fonction intérieure · Δ{mid} = {d} · rapport ×{r}',
      hi: 'भीतरी फलन पार हुआ · Δ{mid} = {d} · अनुपात ×{r}',
      id: 'Melewati fungsi dalam · Δ{mid} = {d} · rasio ×{r}',
      pt: 'Atravessa a função interna · Δ{mid} = {d} · razão ×{r}',
    },
    'caption.outer': {
      en: 'Across the outer function: Δ{out} = {d} · ratio ×{r}',
      ko: '바깥 함수를 건넜다 · Δ{out} = {d} · 배 ×{r}',
      ja: '外側の関数を渡った · Δ{out} = {d} · 倍率 ×{r}',
      zh: '穿过外层函数 · Δ{out} = {d} · 倍数 ×{r}',
      ar: 'عبر الدالة الخارجية · Δ{out} = {d} · النسبة ×{r}',
      es: 'Cruza la función exterior · Δ{out} = {d} · razón ×{r}',
      fr: 'Traversée de la fonction extérieure · Δ{out} = {d} · rapport ×{r}',
      hi: 'बाहरी फलन पार हुआ · Δ{out} = {d} · अनुपात ×{r}',
      id: 'Melewati fungsi luar · Δ{out} = {d} · rasio ×{r}',
      pt: 'Atravessa a função externa · Δ{out} = {d} · razão ×{r}',
    },
    'caption.whole': {
      en: 'Whole ratio Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      ko: '통째 배 Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      ja: '全体の倍率 Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      zh: '整体倍数 Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      ar: 'النسبة الكلية Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      es: 'Razón total Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      fr: 'Rapport total Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      hi: 'कुल अनुपात Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      id: 'Rasio total Δ{out}/Δ{in} = {w} = {r1} × {r2}',
      pt: 'Razão total Δ{out}/Δ{in} = {w} = {r1} × {r2}',
    },
    'caption.limit': {
      en: 'Push width → 0: d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · product {d}',
      ko: '민 폭 → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · 곱 {d}',
      ja: '押す幅 → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · 積 {d}',
      zh: '推动幅度 → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · 乘积 {d}',
      ar: 'عرض الدفع → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · الناتج {d}',
      es: 'Ancho del empuje → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · producto {d}',
      fr: 'Largeur de poussée → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · produit {d}',
      hi: 'धक्के की चौड़ाई → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · गुणनफल {d}',
      id: 'Lebar dorongan → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · hasil kali {d}',
      pt: 'Largura do empurrão → 0 · d{mid}/d{in} = {d1} · d{out}/d{mid} = {d2} · produto {d}',
    },
    'label.inner': {
      en: 'inner function',
      ko: '안쪽 함수',
      ja: '内側の関数',
      zh: '内层函数',
      ar: 'الدالة الداخلية',
      es: 'función interior',
      fr: 'fonction intérieure',
      hi: 'भीतरी फलन',
      id: 'fungsi dalam',
      pt: 'função interna',
    },
    'label.outer': {
      en: 'outer function',
      ko: '바깥 함수',
      ja: '外側の関数',
      zh: '外层函数',
      ar: 'الدالة الخارجية',
      es: 'función exterior',
      fr: 'fonction extérieure',
      hi: 'बाहरी फलन',
      id: 'fungsi luar',
      pt: 'função externa',
    },
    'label.formula': {
      en: '{name} = {expr}',
      ko: '{name} = {expr}',
      ja: '{name} = {expr}',
      zh: '{name} = {expr}',
      ar: '{name} = {expr}',
      es: '{name} = {expr}',
      fr: '{name} = {expr}',
      hi: '{name} = {expr}',
      id: '{name} = {expr}',
      pt: '{name} = {expr}',
    },
    'label.value': {
      en: '{name} {v}',
      ko: '{name} {v}',
      ja: '{name} {v}',
      zh: '{name} {v}',
      ar: '{name} {v}',
      es: '{name} {v}',
      fr: '{name} {v}',
      hi: '{name} {v}',
      id: '{name} {v}',
      pt: '{name} {v}',
    },
    'label.delta': {
      en: 'Δ{name} {v}',
      ko: 'Δ{name} {v}',
      ja: 'Δ{name} {v}',
      zh: 'Δ{name} {v}',
      ar: 'Δ{name} {v}',
      es: 'Δ{name} {v}',
      fr: 'Δ{name} {v}',
      hi: 'Δ{name} {v}',
      id: 'Δ{name} {v}',
      pt: 'Δ{name} {v}',
    },
    'label.ratio': {
      en: '×{r}',
      ko: '×{r}',
      ja: '×{r}',
      zh: '×{r}',
      ar: '×{r}',
      es: '×{r}',
      fr: '×{r}',
      hi: '×{r}',
      id: '×{r}',
      pt: '×{r}',
    },
  },
  blocks: {
    stage: { type: 'chain-rule-multiply-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
