import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 프로그램이 쓰는 주소는 어떻게 메모리의 실제 자리가 되는가.
 *
 * 가상 주소가 페이지 번호와 오프셋으로 갈라지고, 페이지 번호만 페이지 표를 거쳐 프레임
 * 번호로 바뀐 뒤 손대지 않은 오프셋과 다시 붙는다. 표와 주소는 예로 정한 값이다.
 */
export const pageTableLookupFacet: FacetJson = {
  id: 'facet:pageTableLookup',
  title: {
    en: 'Page table lookup',
    ko: '페이지 테이블 찾기',
    ja: 'ページテーブルの参照',
    zh: '页表查找',
    ar: 'البحث في جدول الصفحات',
    es: 'Consulta de la tabla de páginas',
    fr: 'Consultation de la table des pages',
    hi: 'पेज टेबल लुकअप',
    id: 'Pencarian tabel halaman',
    pt: 'Consulta à tabela de páginas',
  },
  description: {
    en: 'An address splits in two; only the front part goes through the table and changes.',
    ko: '주소가 둘로 갈라지고 앞쪽만 표를 거쳐 바뀐다.',
    ja: 'アドレスが二つに分かれ、前の部分だけが表を通って変わる。',
    zh: '地址一分为二，只有前半部分经过页表被替换。',
    ar: 'ينقسم العنوان إلى جزأين، ويمر الجزء الأمامي وحده عبر الجدول فيتغيّر.',
    es: 'La dirección se parte en dos; solo la parte delantera pasa por la tabla y cambia.',
    fr: "L'adresse se coupe en deux ; seule la partie avant passe par la table et change.",
    hi: 'पता दो हिस्सों में बँटता है; केवल आगे का हिस्सा तालिका से होकर बदलता है।',
    id: 'Alamat terbelah dua; hanya bagian depan yang melewati tabel dan berubah.',
    pt: 'O endereço divide-se em dois; só a parte da frente passa pela tabela e muda.',
  },
  algorithm: 'module:pageTableLookup',
  scene: 'module:pageTableLookupScene',
  initialData: {
    type: 'page-table-lookup',
    stepMs: 1300,
    addressBits: 16,
    pageSize: 0x1000,
    table: [
      { page: 0x0, frame: 0x6 },
      { page: 0x1, frame: 0x3 },
      { page: 0x2, frame: 0xb },
      { page: 0x3, frame: 0x1 },
    ],
    addresses: [0x2a3c, 0x0104, 0x3ff0],
  },
  shuffleOnReset: false,
  messages: {
    'label.virtual': {
      en: 'Virtual address',
      ko: '가상 주소',
      ja: '仮想アドレス',
      zh: '虚拟地址',
      ar: 'العنوان الافتراضي',
      es: 'Dirección virtual',
      fr: 'Adresse virtuelle',
      hi: 'आभासी पता',
      id: 'Alamat virtual',
      pt: 'Endereço virtual',
    },
    'label.physical': {
      en: 'Physical address',
      ko: '실제 주소',
      ja: '物理アドレス',
      zh: '物理地址',
      ar: 'العنوان الفعلي',
      es: 'Dirección física',
      fr: 'Adresse physique',
      hi: 'भौतिक पता',
      id: 'Alamat fisik',
      pt: 'Endereço físico',
    },
    'label.table': {
      en: 'Page table',
      ko: '페이지 표',
      ja: 'ページテーブル',
      zh: '页表',
      ar: 'جدول الصفحات',
      es: 'Tabla de páginas',
      fr: 'Table des pages',
      hi: 'पेज टेबल',
      id: 'Tabel halaman',
      pt: 'Tabela de páginas',
    },
    'label.page': {
      en: 'Page',
      ko: '페이지',
      ja: 'ページ',
      zh: '页',
      ar: 'الصفحة',
      es: 'Página',
      fr: 'Page',
      hi: 'पेज',
      id: 'Halaman',
      pt: 'Página',
    },
    'label.frame': {
      en: 'Frame',
      ko: '프레임',
      ja: 'フレーム',
      zh: '帧',
      ar: 'الإطار',
      es: 'Marco',
      fr: 'Cadre',
      hi: 'फ़्रेम',
      id: 'Bingkai',
      pt: 'Quadro',
    },
    'label.offset': {
      en: 'Offset',
      ko: '오프셋',
      ja: 'オフセット',
      zh: '偏移',
      ar: 'الإزاحة',
      es: 'Desplazamiento',
      fr: 'Décalage',
      hi: 'ऑफ़सेट',
      id: 'Offset',
      pt: 'Deslocamento',
    },
    'caption.start': {
      en: 'Addresses to translate: {n}',
      ko: '번역할 주소: {n}',
      ja: '変換するアドレス: {n}',
      zh: '待转换的地址：{n}',
      ar: 'العناوين المطلوب ترجمتها: {n}',
      es: 'Direcciones por traducir: {n}',
      fr: 'Adresses à traduire : {n}',
      hi: 'अनुवाद करने वाले पते: {n}',
      id: 'Alamat yang akan diterjemahkan: {n}',
      pt: 'Endereços a traduzir: {n}',
    },
    'caption.split': {
      en: 'Split: {address} → page {page} · offset {offset}',
      ko: '갈라짐: {address} → 페이지 {page} · 오프셋 {offset}',
      ja: '分割: {address} → ページ {page} · オフセット {offset}',
      zh: '拆分：{address} → 页 {page} · 偏移 {offset}',
      ar: 'التقسيم: {address} ← الصفحة {page} · الإزاحة {offset}',
      es: 'División: {address} → página {page} · desplazamiento {offset}',
      fr: 'Découpe : {address} → page {page} · décalage {offset}',
      hi: 'विभाजन: {address} → पेज {page} · ऑफ़सेट {offset}',
      id: 'Terbelah: {address} → halaman {page} · offset {offset}',
      pt: 'Divisão: {address} → página {page} · deslocamento {offset}',
    },
    'caption.lookup': {
      en: 'Table row {page} → frame {frame}',
      ko: '표의 줄 {page} → 프레임 {frame}',
      ja: '表の行 {page} → フレーム {frame}',
      zh: '页表第 {page} 行 → 帧 {frame}',
      ar: 'صف الجدول {page} ← الإطار {frame}',
      es: 'Fila {page} de la tabla → marco {frame}',
      fr: 'Ligne {page} de la table → cadre {frame}',
      hi: 'तालिका की पंक्ति {page} → फ़्रेम {frame}',
      id: 'Baris tabel {page} → bingkai {frame}',
      pt: 'Linha {page} da tabela → quadro {frame}',
    },
    'caption.join': {
      en: 'Joined: frame {frame} + offset {offset} → {physical}',
      ko: '붙음: 프레임 {frame} + 오프셋 {offset} → {physical}',
      ja: '結合: フレーム {frame} + オフセット {offset} → {physical}',
      zh: '拼接：帧 {frame} + 偏移 {offset} → {physical}',
      ar: 'الدمج: الإطار {frame} + الإزاحة {offset} ← {physical}',
      es: 'Unión: marco {frame} + desplazamiento {offset} → {physical}',
      fr: 'Réunion : cadre {frame} + décalage {offset} → {physical}',
      hi: 'जोड़: फ़्रेम {frame} + ऑफ़सेट {offset} → {physical}',
      id: 'Tersambung: bingkai {frame} + offset {offset} → {physical}',
      pt: 'União: quadro {frame} + deslocamento {offset} → {physical}',
    },
  },
  blocks: {
    stage: { type: 'page-table-lookup-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
