import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { UnrollLoopFacetData } from './algorithm.js';

const v = (name: string) => ({ var: name });
const n = (value: number) => ({ num: value });

const initialData: UnrollLoopFacetData = {
  type: 'unroll-loop',
  stepMs: 1400,
  factor: 4,
  lines: [
    { indent: 0, text: 'function total(list)', stmt: { k: 'function', name: 'total', params: ['list'] } },
    { indent: 1, text: 'let sum = 0', stmt: { k: 'let', name: 'sum', value: n(0) } },
    { indent: 1, text: 'let i = 0', stmt: { k: 'let', name: 'i', value: n(0) } },
    { indent: 1, text: 'while i < 10', stmt: { k: 'while', cond: { op: '<', l: v('i'), r: n(10) } } },
    {
      indent: 2,
      text: 'sum = sum + list[i]',
      stmt: { k: 'set', name: 'sum', value: { op: '+', l: v('sum'), r: { index: 'list', at: v('i') } } },
    },
    { indent: 2, text: 'i = i + 1', stmt: { k: 'set', name: 'i', value: { op: '+', l: v('i'), r: n(1) } } },
    { indent: 1, text: 'return sum', stmt: { k: 'return', value: v('sum') } },
  ],
};

/**
 * @piece
 * 질문: 반복을 펴서 늘어놓으면 무엇이 줄고, 벌 수에 딱 떨어지지 않는 나머지는 어디로 가는가.
 */
export const unrollLoopFacet: FacetJson = {
  id: 'facet:unrollLoop',
  title: {
    en: 'Unrolling a loop',
    ko: '루프 펼치기',
    ja: 'ループ展開',
    zh: '循环展开',
    ar: 'فك الحلقة',
    es: 'Desenrollar un bucle',
    fr: 'Déroulement de boucle',
    hi: 'लूप को खोलना',
    id: 'Membuka perulangan',
    pt: 'Desenrolar um laço',
  },
  description: {
    en: 'The loop body is laid out several times per lap, and the leftover that does not fill a group goes after the loop.',
    ko: '반복의 몸을 한 바퀴에 여러 벌 늘어놓고, 묶음을 채우지 못한 나머지는 반복 뒤에 붙인다.',
    ja: 'ループ本体を1周に何個も並べ、まとまりに満たない余りはループの後ろに付ける。',
    zh: '把循环体在一圈里排开多份，凑不满一组的余下部分放到循环之后。',
    ar: 'يُفرد جسم الحلقة عدة مرات في كل دورة، وما يتبقى دون أن يملأ مجموعة يوضع بعد الحلقة.',
    es: 'El cuerpo del bucle se repite varias veces por vuelta, y lo que no llena un grupo va después del bucle.',
    fr: 'Le corps de la boucle est recopié plusieurs fois par tour, et le reste qui ne remplit pas un groupe passe après la boucle.',
    hi: 'लूप का शरीर हर चक्कर में कई बार रखा जाता है, और जो बचा हिस्सा समूह नहीं भरता वह लूप के बाद जाता है।',
    id: 'Badan perulangan dijajarkan beberapa kali per putaran, dan sisa yang tidak mengisi satu kelompok ditaruh setelah perulangan.',
    pt: 'O corpo do laço é repetido várias vezes por volta, e o que sobra sem encher um grupo vai depois do laço.',
  },
  algorithm: 'module:unrollLoop',
  scene: 'module:unrollLoopScene',
  initialData,
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'unroll-loop-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.start': {
      en: 'One copy of the body per lap. Laps: {n}',
      ko: '한 바퀴에 몸 한 벌. 바퀴 수: {n}',
      ja: '1周に本体が1つ。周回数: {n}',
      zh: '每圈一份循环体。圈数：{n}',
      ar: 'نسخة واحدة من الجسم في كل دورة. الدورات: {n}',
      es: 'Una copia del cuerpo por vuelta. Vueltas: {n}',
      fr: 'Une copie du corps par tour. Tours : {n}',
      hi: 'हर चक्कर में शरीर की एक प्रति। चक्कर: {n}',
      id: 'Satu salinan badan per putaran. Putaran: {n}',
      pt: 'Uma cópia do corpo por volta. Voltas: {n}',
    },
    'caption.copy': {
      en: 'Body copy {k} — reads {read}',
      ko: '몸의 벌 {k} — 읽는 칸: {read}',
      ja: '本体のコピー {k} — 読むマス: {read}',
      zh: '循环体副本 {k} — 读取：{read}',
      ar: 'نسخة الجسم {k} — تقرأ {read}',
      es: 'Copia {k} del cuerpo — lee {read}',
      fr: 'Copie {k} du corps — lit {read}',
      hi: 'शरीर की प्रति {k} — पढ़ती है {read}',
      id: 'Salinan badan {k} — membaca {read}',
      pt: 'Cópia {k} do corpo — lê {read}',
    },
    'caption.retune': {
      en: 'Bump: {bump} · Condition: {cond} · Left over: {rest}',
      ko: '올림: {bump} · 조건: {cond} · 남는 칸: {rest}',
      ja: '増分: {bump} · 条件: {cond} · 余り: {rest}',
      zh: '递增：{bump} · 条件：{cond} · 余下：{rest}',
      ar: 'الزيادة: {bump} · الشرط: {cond} · المتبقي: {rest}',
      es: 'Incremento: {bump} · Condición: {cond} · Sobran: {rest}',
      fr: 'Pas : {bump} · Condition : {cond} · Reste : {rest}',
      hi: 'बढ़त: {bump} · शर्त: {cond} · बचे: {rest}',
      id: 'Kenaikan: {bump} · Syarat: {cond} · Sisa: {rest}',
      pt: 'Incremento: {bump} · Condição: {cond} · Sobram: {rest}',
    },
    'caption.peel': {
      en: 'Leftover {k}/{rest} after the loop: {text}',
      ko: '나머지 {k}/{rest} — 반복 뒤에: {text}',
      ja: '余り {k}/{rest} — ループの後ろへ: {text}',
      zh: '余下 {k}/{rest} — 放到循环之后：{text}',
      ar: 'المتبقي {k}/{rest} بعد الحلقة: {text}',
      es: 'Sobrante {k}/{rest} tras el bucle: {text}',
      fr: 'Reste {k}/{rest} après la boucle : {text}',
      hi: 'बचा {k}/{rest} लूप के बाद: {text}',
      id: 'Sisa {k}/{rest} setelah perulangan: {text}',
      pt: 'Sobra {k}/{rest} depois do laço: {text}',
    },
    'caption.compare': {
      en: 'Per call — loop upkeep: {before} → {after}',
      ko: '한 번 부를 때 반복 관리: {before} → {after}',
      ja: '1回の呼び出しでのループ管理: {before} → {after}',
      zh: '每次调用的循环开销：{before} → {after}',
      ar: 'في كل استدعاء — إدارة الحلقة: {before} → {after}',
      es: 'Por llamada — gestión del bucle: {before} → {after}',
      fr: 'Par appel — gestion de la boucle : {before} → {after}',
      hi: 'हर कॉल में — लूप का प्रबंधन: {before} → {after}',
      id: 'Per panggilan — urusan perulangan: {before} → {after}',
      pt: 'Por chamada — gestão do laço: {before} → {after}',
    },
    'label.lines': {
      en: 'Program lines',
      ko: '프로그램 줄',
      ja: 'プログラムの行',
      zh: '程序行数',
      ar: 'أسطر البرنامج',
      es: 'Líneas',
      fr: 'Lignes',
      hi: 'प्रोग्राम पंक्तियाँ',
      id: 'Baris program',
      pt: 'Linhas',
    },
    'label.checks': {
      en: 'Condition checks',
      ko: '조건 셈',
      ja: '条件判定',
      zh: '条件判断',
      ar: 'فحوص الشرط',
      es: 'Comprobaciones',
      fr: 'Tests',
      hi: 'शर्त जाँच',
      id: 'Cek syarat',
      pt: 'Testes',
    },
    'label.bumps': {
      en: 'Bumps',
      ko: '올림',
      ja: '増分',
      zh: '递增',
      ar: 'الزيادات',
      es: 'Incrementos',
      fr: 'Pas',
      hi: 'बढ़त',
      id: 'Kenaikan',
      pt: 'Incrementos',
    },
    'label.adds': {
      en: 'Additions',
      ko: '더하기',
      ja: '加算',
      zh: '加法',
      ar: 'الجمع',
      es: 'Sumas',
      fr: 'Additions',
      hi: 'जोड़',
      id: 'Penjumlahan',
      pt: 'Somas',
    },
    'value.change': {
      en: '{before} → {after}',
      ko: '{before} → {after}',
      ja: '{before} → {after}',
      zh: '{before} → {after}',
      ar: '{before} → {after}',
      es: '{before} → {after}',
      fr: '{before} → {after}',
      hi: '{before} → {after}',
      id: '{before} → {after}',
      pt: '{before} → {after}',
    },
  },
};
