/**
 * @piece
 * 질문: 토큰기는 원시 프로그램의 글자 가운데 무엇을 토큰으로 남기고 무엇을 버리는가.
 *
 * 원문 한 줄을 왼쪽부터 덩이로 끊는다. 토큰은 토큰 열로 가 맞붙고, 빈칸 덩이는
 * 한 칸이든 세 칸이든 떨어져 버려진다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const splitIntoTokensFacet: FacetJson = {
  id: 'facet:splitIntoTokens',
  title: {
    en: 'Blanks are not tokens',
    ko: '빈칸은 토큰이 아니다',
    ja: '空白はトークンではない',
    zh: '空白不是词法单元',
    ar: 'الفراغات ليست رموزًا',
    es: 'Los espacios no son tokens',
    fr: 'Les espaces ne sont pas des jetons',
    hi: 'रिक्त स्थान टोकन नहीं हैं',
    id: 'Spasi bukan token',
    pt: 'Espaços não são tokens',
  },
  description: {
    en: 'The tokenizer cuts a source line into chunks from the left. Tokens go to the token row and sit side by side; runs of blanks fall away, whatever their length.',
    ko: '토큰기는 원문 한 줄을 왼쪽부터 덩이로 끊는다. 토큰은 토큰 열로 가 맞붙고, 빈칸 덩이는 길이와 상관없이 떨어져 버려진다.',
    ja: 'トークナイザは原文の一行を左から塊に切る。トークンはトークン列に行って隣り合い、空白の塊は長さに関係なく落ちて捨てられる。',
    zh: '词法分析器从左向右把一行源码切成块。词法单元进入单元列并紧挨在一起；空白块不论长短都会掉落并被丢弃。',
    ar: 'يقطع المُرمِّز سطر المصدر إلى كتل من اليسار. تذهب الرموز إلى صف الرموز وتتلاصق، وتسقط كتل الفراغات مهما كان طولها.',
    es: 'El tokenizador corta una línea de código en trozos desde la izquierda. Los tokens van a la fila de tokens y quedan pegados; los tramos de espacios caen y se descartan, sea cual sea su longitud.',
    fr: 'Le tokeniseur découpe une ligne source en morceaux depuis la gauche. Les jetons rejoignent la rangée de jetons et se touchent ; les suites d’espaces tombent et sont jetées, quelle que soit leur longueur.',
    hi: 'टोकनाइज़र स्रोत की एक पंक्ति को बाएँ से टुकड़ों में काटता है। टोकन टोकन पंक्ति में जाकर सटकर बैठते हैं; रिक्त स्थानों के टुकड़े, लंबाई चाहे जो हो, गिरकर फेंक दिए जाते हैं।',
    id: 'Tokenizer memotong satu baris sumber menjadi potongan dari kiri. Token masuk ke baris token dan saling menempel; deretan spasi jatuh dan dibuang, berapa pun panjangnya.',
    pt: 'O tokenizador corta uma linha de código em pedaços a partir da esquerda. Os tokens vão para a fila de tokens e ficam colados; as sequências de espaços caem e são descartadas, seja qual for o comprimento.',
  },
  algorithm: 'module:splitIntoTokens',
  scene: 'module:splitIntoTokensScene',
  initialData: {
    type: 'split-into-tokens',
    source: 'let total =   price*2',
    keywords: [
      'let', 'const', 'if', 'else', 'while', 'for', 'from', 'to', 'function', 'return',
      'and', 'or', 'not', 'true', 'false', 'null',
    ],
    operators: ['==', '!=', '<=', '>=', '=', '<', '>', '+', '-', '*', '/', '(', ')', ','],
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'label.source': {
      en: 'Source',
      ko: '원문',
      ja: '原文',
      zh: '源码',
      ar: 'المصدر',
      es: 'Código fuente',
      fr: 'Source',
      hi: 'स्रोत',
      id: 'Sumber',
      pt: 'Código-fonte',
    },
    'label.tokens': {
      en: 'Tokens: {n}',
      ko: '토큰: {n}',
      ja: 'トークン: {n}',
      zh: '词法单元：{n}',
      ar: 'الرموز: {n}',
      es: 'Tokens: {n}',
      fr: 'Jetons : {n}',
      hi: 'टोकन: {n}',
      id: 'Token: {n}',
      pt: 'Tokens: {n}',
    },
    'label.dropped': {
      en: 'Dropped characters: {n}',
      ko: '버린 글자: {n}',
      ja: '捨てた文字: {n}',
      zh: '丢弃的字符：{n}',
      ar: 'الأحرف المُسقَطة: {n}',
      es: 'Caracteres descartados: {n}',
      fr: 'Caractères jetés : {n}',
      hi: 'फेंके गए अक्षर: {n}',
      id: 'Karakter dibuang: {n}',
      pt: 'Caracteres descartados: {n}',
    },
    'caption.start': {
      en: 'Cut the line from the left, one chunk at a time.',
      ko: '줄을 왼쪽부터 덩이 하나씩 끊는다.',
      ja: '行を左から一塊ずつ切る。',
      zh: '从左边开始，一次切下一块。',
      ar: 'اقطع السطر من اليسار، كتلة في كل مرة.',
      es: 'Corta la línea desde la izquierda, un trozo cada vez.',
      fr: 'On découpe la ligne depuis la gauche, un morceau à la fois.',
      hi: 'पंक्ति को बाएँ से, एक बार में एक टुकड़ा काटो।',
      id: 'Potong baris dari kiri, satu potongan setiap kali.',
      pt: 'Corta a linha a partir da esquerda, um pedaço de cada vez.',
    },
    'caption.cut': {
      en: 'Cut [{from},{to}) — token {token}. It joins the end of the token row.',
      ko: '끊음 [{from},{to}) — 토큰 {token}. 토큰 열 끝에 맞붙는다.',
      ja: '切り出し [{from},{to}) — トークン {token}。トークン列の末尾に付く。',
      zh: '切下 [{from},{to}) — 词法单元 {token}。它接到单元列末尾。',
      ar: 'قطع [{from},{to}) — الرمز {token}. ينضم إلى نهاية صف الرموز.',
      es: 'Corte [{from},{to}) — token {token}. Se pega al final de la fila de tokens.',
      fr: 'Coupe [{from},{to}) — jeton {token}. Il se colle à la fin de la rangée de jetons.',
      hi: 'कटा [{from},{to}) — टोकन {token}। यह टोकन पंक्ति के अंत से जुड़ता है।',
      id: 'Potong [{from},{to}) — token {token}. Ia menempel di ujung baris token.',
      pt: 'Corte [{from},{to}) — token {token}. Cola-se ao fim da fila de tokens.',
    },
    'caption.drop': {
      en: 'Cut [{from},{to}) — a blank run, length {n}. Dropped; it never reaches the token row.',
      ko: '끊음 [{from},{to}) — 빈칸 덩이, 길이 {n}. 버린다 — 토큰 열로 가지 않는다.',
      ja: '切り出し [{from},{to}) — 空白の塊、長さ {n}。捨てる — トークン列には行かない。',
      zh: '切下 [{from},{to}) — 空白块，长度 {n}。丢弃 — 它不会进入单元列。',
      ar: 'قطع [{from},{to}) — كتلة فراغات، الطول {n}. تُسقَط ولا تصل إلى صف الرموز.',
      es: 'Corte [{from},{to}) — tramo de espacios, longitud {n}. Se descarta; nunca llega a la fila de tokens.',
      fr: 'Coupe [{from},{to}) — suite d’espaces, longueur {n}. Jetée ; elle n’atteint jamais la rangée de jetons.',
      hi: 'कटा [{from},{to}) — रिक्त स्थानों का टुकड़ा, लंबाई {n}। फेंका गया; यह टोकन पंक्ति तक नहीं पहुँचता।',
      id: 'Potong [{from},{to}) — deretan spasi, panjang {n}. Dibuang; tidak pernah sampai ke baris token.',
      pt: 'Corte [{from},{to}) — sequência de espaços, comprimento {n}. Descartada; nunca chega à fila de tokens.',
    },
  },
  blocks: {
    stage: { type: 'split-into-tokens-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
