import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * priority-aging — 에이징 간격을 줄이면 낮은 순위의 월말 보고서가 눈금을 빨리 타고 올라 CPU 에 끼어들고,
 * 그 대가로 앞질러 간 높은 일들이 기다린다.
 */
export const priorityAgingFacet: FacetJson = {
  id: 'facet:priorityAging',
  title: {
    en: 'Priority and aging',
    ko: '우선순위와 에이징',
    ja: '優先度とエージング',
    zh: '优先级与老化',
    ar: 'الأولوية والتقادم',
    es: 'Prioridad y envejecimiento',
    fr: 'Priorité et vieillissement',
    hi: 'प्राथमिकता और एजिंग',
    id: 'Prioritas dan aging',
    pt: 'Prioridade e envelhecimento',
  },
  description: {
    en: 'Raise the priority of whatever waits, and the low one no longer starves — but the high ones wait in its place.',
    ko: '기다린 만큼 순위를 올려 주면 낮은 것이 굶지 않는다 — 그 대신 높은 것들이 그만큼 기다린다.',
    ja: '待った分だけ優先度を上げれば低いものは飢えない — その代わり高いものがその分待つ。',
    zh: '按等待时间提升优先级，低优先级的进程就不会饿死——代价是高优先级的进程要多等。',
    ar: 'ارفع أولوية ما ينتظر فلا تجوع العملية المنخفضة — لكن العمليات العالية تنتظر مكانها.',
    es: 'Sube la prioridad de lo que espera y el de baja prioridad ya no pasa hambre, pero los de alta esperan en su lugar.',
    fr: 'Montez la priorité de ce qui attend et le moins prioritaire ne meurt plus de faim — mais les prioritaires attendent à sa place.',
    hi: 'जो प्रतीक्षा करे उसकी प्राथमिकता बढ़ाएँ तो निचला भूखा नहीं रहता — पर ऊँचे वाले उसकी जगह प्रतीक्षा करते हैं।',
    id: 'Naikkan prioritas yang menunggu, maka yang rendah tidak kelaparan — tetapi yang tinggi menunggu sebagai gantinya.',
    pt: 'Suba a prioridade de quem espera e o de baixa prioridade deixa de passar fome — mas os de alta esperam no lugar dele.',
  },
  algorithm: 'module:priorityAging',
  projector: 'module:priorityAgingProjector',
  initialData: {
    type: 'priority-aging',
    stepMs: 700,
    procs: [
      { id: 'report', arrive: 0, burst: 4, prio: 1 },
      { id: 'j1', arrive: 0, burst: 2, prio: 3 },
      { id: 'j2', arrive: 2, burst: 2, prio: 3 },
      { id: 'j3', arrive: 4, burst: 2, prio: 3 },
      { id: 'j4', arrive: 6, burst: 2, prio: 3 },
      { id: 'j5', arrive: 8, burst: 2, prio: 3 },
      { id: 'j6', arrive: 10, burst: 2, prio: 3 },
      { id: 'j7', arrive: 12, burst: 2, prio: 3 },
    ],
    intervalLadder: [0, 6, 4, 3, 2, 1],
    interval: 0,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'priority-aging-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'interval',
          name: 'interval',
          label: {
            en: 'Aging interval',
            ko: '에이징 간격',
            ja: 'エージング間隔',
            zh: '老化间隔',
            ar: 'فاصل التقادم',
            es: 'Paso de envejecimiento',
            fr: 'Pas de vieillissement',
            hi: 'एजिंग अंतराल',
            id: 'Interval aging',
            pt: 'Passo de envelhecimento',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'None',
                ko: '없음',
                ja: 'なし',
                zh: '无',
                ar: 'بلا',
                es: 'Ninguno',
                fr: 'Aucun',
                hi: 'कोई नहीं',
                id: 'Tidak ada',
                pt: 'Nenhum',
              },
              default: true,
            },
            { value: 6, label: '6' },
            { value: 4, label: '4' },
            { value: 3, label: '3' },
            { value: 2, label: '2' },
            { value: 1, label: '1' },
          ],
        },
      ],
      metrics: [
        {
          name: 'low-wait',
          label: {
            en: 'Report wait',
            ko: '보고서 대기',
            ja: '報告書の待ち',
            zh: '报告等待',
            ar: 'انتظار التقرير',
            es: 'Espera del informe',
            fr: 'Attente du rapport',
            hi: 'रिपोर्ट की प्रतीक्षा',
            id: 'Tunggu laporan',
            pt: 'Espera do relatório',
          },
          initial: 0,
        },
        {
          name: 'high-wait',
          label: {
            en: 'J wait total',
            ko: 'J 대기 합',
            ja: 'J の待ち合計',
            zh: 'J 等待总和',
            ar: 'مجموع انتظار J',
            es: 'Espera total de J',
            fr: 'Attente totale des J',
            hi: 'J की कुल प्रतीक्षा',
            id: 'Total tunggu J',
            pt: 'Espera total dos J',
          },
          initial: 0,
        },
        {
          name: 'overtaken',
          label: {
            en: 'J ahead of report',
            ko: '앞질러 간 J',
            ja: '報告書より先の J',
            zh: '先于报告的 J',
            ar: 'J قبل التقرير',
            es: 'J antes del informe',
            fr: 'J avant le rapport',
            hi: 'रिपोर्ट से पहले J',
            id: 'J sebelum laporan',
            pt: 'J antes do relatório',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:priority-aging-imperative',
      label: {
        en: 'Priority scheduling with aging',
        ko: '에이징을 더한 우선순위 스케줄',
        ja: 'エージング付き優先度スケジューリング',
        zh: '带老化的优先级调度',
        ar: 'جدولة بالأولوية مع التقادم',
        es: 'Planificación por prioridad con envejecimiento',
        fr: 'Ordonnancement par priorité avec vieillissement',
        hi: 'एजिंग के साथ प्राथमिकता शेड्यूलिंग',
        id: 'Penjadwalan prioritas dengan aging',
        pt: 'Escalonamento por prioridade com envelhecimento',
      },
    },
  },
  messages: {
    'label.priority': {
      en: 'Priority (higher is up)',
      ko: '순위 (클수록 위)',
      ja: '優先度（大きいほど上）',
      zh: '优先级（越大越高）',
      ar: 'الأولوية (الأعلى فوق)',
      es: 'Prioridad (mayor arriba)',
      fr: 'Priorité (plus haut = plus grand)',
      hi: 'प्राथमिकता (बड़ा ऊपर)',
      id: 'Prioritas (lebih besar di atas)',
      pt: 'Prioridade (maior acima)',
    },
    'label.pending': {
      en: 'Not arrived yet',
      ko: '도착 전',
      ja: '未到着',
      zh: '尚未到达',
      ar: 'لم تصل بعد',
      es: 'Aún no llegan',
      fr: 'Pas encore arrivés',
      hi: 'अभी नहीं पहुँचे',
      id: 'Belum tiba',
      pt: 'Ainda não chegaram',
    },
    'label.cpu': {
      en: 'CPU',
      ko: 'CPU',
      ja: 'CPU',
      zh: 'CPU',
      ar: 'CPU',
      es: 'CPU',
      fr: 'CPU',
      hi: 'CPU',
      id: 'CPU',
      pt: 'CPU',
    },
    'label.done': {
      en: 'Finished',
      ko: '끝남',
      ja: '終了',
      zh: '已完成',
      ar: 'انتهت',
      es: 'Terminados',
      fr: 'Terminés',
      hi: 'पूरे हुए',
      id: 'Selesai',
      pt: 'Concluídos',
    },
    'label.waitBars': {
      en: 'Wait (ticks)',
      ko: '대기 (틱)',
      ja: '待ち（ティック）',
      zh: '等待（tick）',
      ar: 'الانتظار (نبضات)',
      es: 'Espera (ticks)',
      fr: 'Attente (ticks)',
      hi: 'प्रतीक्षा (टिक)',
      id: 'Tunggu (tick)',
      pt: 'Espera (ticks)',
    },
    'label.report': {
      en: 'Month-end report',
      ko: '월말 보고서',
      ja: '月末報告書',
      zh: '月末报告',
      ar: 'تقرير نهاية الشهر',
      es: 'Informe de fin de mes',
      fr: 'Rapport de fin de mois',
      hi: 'मासांत रिपोर्ट',
      id: 'Laporan akhir bulan',
      pt: 'Relatório de fim de mês',
    },
    'label.arriveTick': {
      en: 'tick {n}',
      ko: '{n}틱',
      ja: '{n} ティック',
      zh: '第 {n} tick',
      ar: 'النبضة {n}',
      es: 'tick {n}',
      fr: 'tick {n}',
      hi: 'टिक {n}',
      id: 'tick {n}',
      pt: 'tick {n}',
    },
    'label.doneTick': {
      en: 'at tick {n}',
      ko: '{n}틱에 끝',
      ja: '{n} ティックで終了',
      zh: '第 {n} tick 结束',
      ar: 'عند النبضة {n}',
      es: 'en el tick {n}',
      fr: 'au tick {n}',
      hi: 'टिक {n} पर',
      id: 'pada tick {n}',
      pt: 'no tick {n}',
    },
    'label.jTotal': {
      en: 'J total: {n}',
      ko: 'J 합: {n}',
      ja: 'J 合計: {n}',
      zh: 'J 合计: {n}',
      ar: 'مجموع J: {n}',
      es: 'Total J: {n}',
      fr: 'Total J : {n}',
      hi: 'J कुल: {n}',
      id: 'Total J: {n}',
      pt: 'Total J: {n}',
    },
    'label.prevStart': {
      en: 'Last run: tick {n}',
      ko: '앞 판: {n}틱',
      ja: '前回: {n} ティック',
      zh: '上一轮: 第 {n} tick',
      ar: 'الجولة السابقة: النبضة {n}',
      es: 'Ronda anterior: tick {n}',
      fr: 'Tour précédent : tick {n}',
      hi: 'पिछला दौर: टिक {n}',
      id: 'Putaran lalu: tick {n}',
      pt: 'Rodada anterior: tick {n}',
    },
    'caption.round': {
      en: 'Aging interval: {n} ticks',
      ko: '에이징 간격: {n}틱',
      ja: 'エージング間隔: {n} ティック',
      zh: '老化间隔: {n} tick',
      ar: 'فاصل التقادم: {n} نبضات',
      es: 'Intervalo de envejecimiento: {n} ticks',
      fr: 'Intervalle de vieillissement : {n} ticks',
      hi: 'एजिंग अंतराल: {n} टिक',
      id: 'Interval aging: {n} tick',
      pt: 'Intervalo de envelhecimento: {n} ticks',
    },
    'caption.roundNone': {
      en: 'Aging interval: none',
      ko: '에이징 간격: 없음',
      ja: 'エージング間隔: なし',
      zh: '老化间隔: 无',
      ar: 'فاصل التقادم: بلا',
      es: 'Intervalo de envejecimiento: ninguno',
      fr: 'Intervalle de vieillissement : aucun',
      hi: 'एजिंग अंतराल: कोई नहीं',
      id: 'Interval aging: tidak ada',
      pt: 'Intervalo de envelhecimento: nenhum',
    },
    'caption.tick': {
      en: 'Tick {n}',
      ko: '틱 {n}',
      ja: 'ティック {n}',
      zh: 'tick {n}',
      ar: 'النبضة {n}',
      es: 'Tick {n}',
      fr: 'Tick {n}',
      hi: 'टिक {n}',
      id: 'Tick {n}',
      pt: 'Tick {n}',
    },
    'caption.finish': {
      en: 'Done: {name}',
      ko: '끝: {name}',
      ja: '終了: {name}',
      zh: '完成: {name}',
      ar: 'انتهت: {name}',
      es: 'Termina: {name}',
      fr: 'Terminé : {name}',
      hi: 'पूरा: {name}',
      id: 'Selesai: {name}',
      pt: 'Termina: {name}',
    },
    'caption.arrive': {
      en: 'Arrived: {names}',
      ko: '도착: {names}',
      ja: '到着: {names}',
      zh: '到达: {names}',
      ar: 'وصلت: {names}',
      es: 'Llega: {names}',
      fr: 'Arrivée : {names}',
      hi: 'पहुँचे: {names}',
      id: 'Tiba: {names}',
      pt: 'Chega: {names}',
    },
    'caption.age': {
      en: '{name} priority: {from} → {to}',
      ko: '{name} 순위: {from} → {to}',
      ja: '{name} 優先度: {from} → {to}',
      zh: '{name} 优先级: {from} → {to}',
      ar: 'أولوية {name}: {from} → {to}',
      es: 'Prioridad de {name}: {from} → {to}',
      fr: 'Priorité de {name} : {from} → {to}',
      hi: '{name} प्राथमिकता: {from} → {to}',
      id: 'Prioritas {name}: {from} → {to}',
      pt: 'Prioridade de {name}: {from} → {to}',
    },
    'caption.dispatch': {
      en: 'To CPU: {name} (priority {level})',
      ko: 'CPU 로: {name} (순위 {level})',
      ja: 'CPU へ: {name}（優先度 {level}）',
      zh: '上 CPU: {name}（优先级 {level}）',
      ar: 'إلى المعالج: {name} (الأولوية {level})',
      es: 'A la CPU: {name} (prioridad {level})',
      fr: 'Vers le CPU : {name} (priorité {level})',
      hi: 'CPU पर: {name} (प्राथमिकता {level})',
      id: 'Ke CPU: {name} (prioritas {level})',
      pt: 'Para a CPU: {name} (prioridade {level})',
    },
    'caption.tie': {
      en: 'Tied at {level} with {names}: first in line wins',
      ko: '순위 {level} 동률 ({names}) · 줄에 먼저 선 쪽이 오른다',
      ja: '優先度 {level} で同点（{names}）· 先に並んだ方が進む',
      zh: '优先级 {level} 并列（{names}）· 先排队者上',
      ar: 'تعادل عند {level} مع {names}: الأسبق في الطابور يفوز',
      es: 'Empate en {level} con {names}: gana el primero en la fila',
      fr: 'Égalité à {level} avec {names} : le premier dans la file passe',
      hi: '{level} पर बराबरी ({names}) · कतार में पहले वाला जाता है',
      id: 'Seri di {level} dengan {names}: yang lebih dulu antre menang',
      pt: 'Empate em {level} com {names}: vence o primeiro da fila',
    },
    'caption.running': {
      en: 'Still on CPU: {name}',
      ko: 'CPU 에 그대로: {name}',
      ja: 'CPU で継続: {name}',
      zh: '仍在 CPU 上: {name}',
      ar: 'لا يزال على المعالج: {name}',
      es: 'Sigue en la CPU: {name}',
      fr: 'Toujours sur le CPU : {name}',
      hi: 'अब भी CPU पर: {name}',
      id: 'Masih di CPU: {name}',
      pt: 'Continua na CPU: {name}',
    },
    'caption.end': {
      en: 'Report start: tick {start} · Report wait: {wait} · J wait total: {high}',
      ko: '보고서 시작: {start}틱 · 보고서 대기: {wait} · J 대기 합: {high}',
      ja: '報告書の開始: {start} ティック · 報告書の待ち: {wait} · J の待ち合計: {high}',
      zh: '报告开始: 第 {start} tick · 报告等待: {wait} · J 等待总和: {high}',
      ar: 'بدء التقرير: النبضة {start} · انتظار التقرير: {wait} · مجموع انتظار J: {high}',
      es: 'Inicio del informe: tick {start} · Espera del informe: {wait} · Espera total de J: {high}',
      fr: 'Début du rapport : tick {start} · Attente du rapport : {wait} · Attente totale des J : {high}',
      hi: 'रिपोर्ट शुरू: टिक {start} · रिपोर्ट प्रतीक्षा: {wait} · J कुल प्रतीक्षा: {high}',
      id: 'Laporan mulai: tick {start} · Tunggu laporan: {wait} · Total tunggu J: {high}',
      pt: 'Início do relatório: tick {start} · Espera do relatório: {wait} · Espera total dos J: {high}',
    },
  },
};
