import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 컴파일러는 실행하기 전에 무엇을 미리 셈해 둘 수 있는가.
 *
 * 두 값이 다 정해진 연산은 컴파일 때 수 하나로 접힌다. 한쪽에 이름이 걸리면 거기서 멈추고,
 * 그 위로는 접힘이 번지지 않는다. 상수 전파는 하지 않는다 — `ms` 는 수로 정해졌어도 이름이다.
 */
export const foldAtCompileFacet: FacetJson = {
  id: 'facet:foldAtCompile',
  title: {
    en: 'Folded at compile time',
    ko: '컴파일 때 접힌다',
    ja: 'コンパイル時に畳まれる',
    zh: '编译时折叠',
    ar: 'يُطوى وقت الترجمة',
    es: 'Plegado en compilación',
    fr: 'Plié à la compilation',
    hi: 'कंपाइल के समय मोड़ा जाता है',
    id: 'Dilipat saat kompilasi',
    pt: 'Dobrado na compilação',
  },
  description: {
    en: 'An operation whose two sides are both numbers becomes one number at compile time. A name stops the folding there.',
    ko: '두 값이 다 정해진 연산은 컴파일 때 수 하나로 바뀐다. 이름이 끼면 거기서 멈춘다.',
    ja: '両辺とも数の演算は、コンパイル時に一つの数になる。名前が入るとそこで止まる。',
    zh: '两边都是数的运算在编译时变成一个数。一旦夹着名字，折叠就停在那里。',
    ar: 'العملية التي طرفاها عددان تصير عددًا واحدًا وقت الترجمة. وإذا دخل اسمٌ توقّف الطيّ عنده.',
    es: 'Una operación con dos números a los lados se convierte en un solo número al compilar. Un nombre detiene el plegado ahí.',
    fr: 'Une opération dont les deux côtés sont des nombres devient un seul nombre à la compilation. Un nom arrête le pliage là.',
    hi: 'जिस संक्रिया के दोनों ओर संख्याएँ हों, वह कंपाइल के समय एक संख्या बन जाती है। कोई नाम आ जाए तो मोड़ना वहीं रुकता है।',
    id: 'Operasi yang kedua sisinya angka menjadi satu angka saat kompilasi. Sebuah nama menghentikan pelipatan di situ.',
    pt: 'Uma operação com números dos dois lados vira um só número na compilação. Um nome para a dobra ali.',
  },
  algorithm: 'module:foldAtCompile',
  scene: 'module:foldAtCompileScene',
  initialData: {
    type: 'fold-at-compile',
    stepMs: 1600,
    lines: [
      {
        indent: 0,
        text: 'function timeout(n)',
        stmt: { k: 'function', name: 'timeout', params: ['n'] },
      },
      {
        indent: 1,
        text: 'let ms = 60 * 60 * 1000',
        stmt: {
          k: 'let',
          name: 'ms',
          value: { op: '*', l: { op: '*', l: { num: 60 }, r: { num: 60 } }, r: { num: 1000 } },
        },
      },
      {
        indent: 1,
        text: 'let tries = (2 + 3) * 4 - n',
        stmt: {
          k: 'let',
          name: 'tries',
          value: {
            op: '-',
            l: { op: '*', l: { op: '+', l: { num: 2 }, r: { num: 3 } }, r: { num: 4 } },
            r: { var: 'n' },
          },
        },
      },
      {
        indent: 1,
        text: 'return ms * tries',
        stmt: { k: 'return', value: { op: '*', l: { var: 'ms' }, r: { var: 'tries' } } },
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Start — nothing is folded yet.',
      ko: '시작 — 아직 접은 것이 없다.',
      ja: '開始 — まだ何も畳んでいない。',
      zh: '开始 — 还没有折叠任何运算。',
      ar: 'البداية — لم يُطوَ شيء بعد.',
      es: 'Inicio — aún no se ha plegado nada.',
      fr: 'Début — rien n’est encore plié.',
      hi: 'शुरुआत — अभी कुछ भी मोड़ा नहीं गया।',
      id: 'Mulai — belum ada yang dilipat.',
      pt: 'Início — nada foi dobrado ainda.',
    },
    'caption.fold': {
      en: 'L{line} · {expr} — both sides are numbers. Folded: {value}',
      ko: 'L{line} · {expr} — 양쪽이 모두 수. 접은 값: {value}',
      ja: 'L{line} · {expr} — 両辺とも数。畳んだ値: {value}',
      zh: 'L{line} · {expr} — 两边都是数。折叠结果：{value}',
      ar: 'L{line} · {expr} — الطرفان عددان. القيمة المطويّة: {value}',
      es: 'L{line} · {expr} — ambos lados son números. Plegado: {value}',
      fr: 'L{line} · {expr} — les deux côtés sont des nombres. Plié : {value}',
      hi: 'L{line} · {expr} — दोनों ओर संख्याएँ हैं। मोड़ा गया मान: {value}',
      id: 'L{line} · {expr} — kedua sisi berupa angka. Hasil lipatan: {value}',
      pt: 'L{line} · {expr} — os dois lados são números. Dobrado: {value}',
    },
    'caption.keep.left': {
      en: 'L{line} · {expr} — the left side is not a number: {name}. Kept.',
      ko: 'L{line} · {expr} — 왼쪽이 수가 아니다: {name}. 그대로 둔다.',
      ja: 'L{line} · {expr} — 左辺が数ではない: {name}。そのまま残す。',
      zh: 'L{line} · {expr} — 左边不是数：{name}。保持不变。',
      ar: 'L{line} · {expr} — الطرف الأيسر ليس عددًا: {name}. يبقى كما هو.',
      es: 'L{line} · {expr} — el lado izquierdo no es un número: {name}. Se queda.',
      fr: 'L{line} · {expr} — le côté gauche n’est pas un nombre : {name}. Laissé tel quel.',
      hi: 'L{line} · {expr} — बायाँ पक्ष संख्या नहीं है: {name}। जैसा है वैसा रहता है।',
      id: 'L{line} · {expr} — sisi kiri bukan angka: {name}. Dibiarkan.',
      pt: 'L{line} · {expr} — o lado esquerdo não é um número: {name}. Fica como está.',
    },
    'caption.keep.right': {
      en: 'L{line} · {expr} — the right side is not a number: {name}. Kept.',
      ko: 'L{line} · {expr} — 오른쪽이 수가 아니다: {name}. 그대로 둔다.',
      ja: 'L{line} · {expr} — 右辺が数ではない: {name}。そのまま残す。',
      zh: 'L{line} · {expr} — 右边不是数：{name}。保持不变。',
      ar: 'L{line} · {expr} — الطرف الأيمن ليس عددًا: {name}. يبقى كما هو.',
      es: 'L{line} · {expr} — el lado derecho no es un número: {name}. Se queda.',
      fr: 'L{line} · {expr} — le côté droit n’est pas un nombre : {name}. Laissé tel quel.',
      hi: 'L{line} · {expr} — दायाँ पक्ष संख्या नहीं है: {name}। जैसा है वैसा रहता है।',
      id: 'L{line} · {expr} — sisi kanan bukan angka: {name}. Dibiarkan.',
      pt: 'L{line} · {expr} — o lado direito não é um número: {name}. Fica como está.',
    },
    'caption.keep.both': {
      en: 'L{line} · {expr} — neither side is a number. Kept.',
      ko: 'L{line} · {expr} — 양쪽 다 수가 아니다. 그대로 둔다.',
      ja: 'L{line} · {expr} — どちらの辺も数ではない。そのまま残す。',
      zh: 'L{line} · {expr} — 两边都不是数。保持不变。',
      ar: 'L{line} · {expr} — ليس أيٌّ من الطرفين عددًا. يبقى كما هو.',
      es: 'L{line} · {expr} — ningún lado es un número. Se queda.',
      fr: 'L{line} · {expr} — aucun côté n’est un nombre. Laissé tel quel.',
      hi: 'L{line} · {expr} — कोई भी पक्ष संख्या नहीं है। जैसा है वैसा रहता है।',
      id: 'L{line} · {expr} — kedua sisi bukan angka. Dibiarkan.',
      pt: 'L{line} · {expr} — nenhum lado é um número. Fica como está.',
    },
    'label.folded': {
      en: 'Folded',
      ko: '접힘',
      ja: '畳んだ',
      zh: '已折叠',
      ar: 'مطويّة',
      es: 'Plegadas',
      fr: 'Pliées',
      hi: 'मोड़ी गईं',
      id: 'Dilipat',
      pt: 'Dobradas',
    },
    'label.kept': {
      en: 'Kept',
      ko: '그대로',
      ja: 'そのまま',
      zh: '保持',
      ar: 'باقية',
      es: 'Sin cambio',
      fr: 'Laissées',
      hi: 'जैसी की तैसी',
      id: 'Dibiarkan',
      pt: 'Mantidas',
    },
    'label.runtime': {
      en: 'Operations at run time',
      ko: '실행 때 셈하는 연산',
      ja: '実行時に計算する演算',
      zh: '运行时要算的运算',
      ar: 'عمليات تُحسب وقت التشغيل',
      es: 'Operaciones en ejecución',
      fr: 'Opérations à l’exécution',
      hi: 'चलते समय की संक्रियाएँ',
      id: 'Operasi saat dijalankan',
      pt: 'Operações na execução',
    },
    'label.line': {
      en: 'L{n}',
      ko: 'L{n}',
      ja: 'L{n}',
      zh: 'L{n}',
      ar: 'L{n}',
      es: 'L{n}',
      fr: 'L{n}',
      hi: 'L{n}',
      id: 'L{n}',
      pt: 'L{n}',
    },
  },
  blocks: {
    stage: { type: 'fold-at-compile-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
