/**
 * @piece
 * 질문: 문법에 맞는 출력만 나오게 하려면 언제 막아야 하는가
 *
 * 문법 제약 디코딩. 고르기 **전에** 문법이 허락하지 않는 후보를 지우고, 그 몫은 남은 후보가
 * 나눠 갖는다. 두 결정 모두 모형의 1등이 지워져 답이 바뀐다.
 * 로짓은 모두 예로 정한 값이다 — 실제 언어 모형에서 나온 수가 아니다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const eraseTheImpossibleFacet: FacetJson = {
  id: 'facet:eraseTheImpossible',
  title: {
    en: 'Erase the impossible',
    ko: '불가능한 후보는 미리 지운다',
    ja: '不可能な候補は先に消す',
    zh: '先删去不可能的候选',
    ar: 'امحُ المستحيل أولًا',
    es: 'Borrar lo imposible',
    fr: 'Effacer l’impossible',
    hi: 'असंभव को पहले मिटाओ',
    id: 'Hapus yang mustahil',
    pt: 'Apagar o impossível',
  },
  description: {
    en: 'Grammar-constrained decoding: before choosing, the grammar erases the candidates it forbids and their share goes to the rest.',
    ko: '문법 제약 디코딩 — 고르기 전에 문법이 막는 후보를 지우고, 그 몫은 남은 후보가 나눠 갖는다.',
    ja: '文法制約付きデコーディング — 選ぶ前に文法が禁じる候補を消し、その分を残りの候補が分け合う。',
    zh: '语法约束解码:在选择之前,语法删去它禁止的候选,其份额由其余候选分摊。',
    ar: 'فك الترميز المقيد بالقواعد: قبل الاختيار تمحو القواعد المرشحين الممنوعين ويتقاسم الباقون حصتهم.',
    es: 'Decodificación restringida por gramática: antes de elegir, la gramática borra los candidatos que prohíbe y su parte pasa al resto.',
    fr: 'Décodage contraint par une grammaire : avant de choisir, la grammaire efface les candidats interdits et leur part revient aux autres.',
    hi: 'व्याकरण-बाधित डिकोडिंग: चुनने से पहले व्याकरण वर्जित उम्मीदवारों को मिटा देता है और उनका हिस्सा बाकी को मिलता है।',
    id: 'Dekode berkendala tata bahasa: sebelum memilih, tata bahasa menghapus kandidat yang dilarangnya dan bagiannya jatuh ke sisanya.',
    pt: 'Decodificação restrita por gramática: antes de escolher, a gramática apaga os candidatos que proíbe e a parte deles vai para o resto.',
  },
  algorithm: 'module:eraseTheImpossible',
  scene: 'module:eraseTheImpossibleScene',
  initialData: {
    type: 'erase-the-impossible',
    // 목표 문법 {"age": <정수>} — `<int>` 는 수 토큰 하나
    grammar: ['{', '"age"', ':', '<int>', '}'],
    prefix: ['{', '"age"', ':'],
    vocab: ['"', '42', '7', 'null', ',', '}'],
    // 결정마다 어휘 차례의 로짓 (예로 정한 값)
    logits: [
      [2.3, 1.9, 0.8, 0.6, -0.4, -0.9],
      [-1.2, -0.7, -0.3, -2.0, 1.7, 1.2],
    ],
    stepMs: 1400,
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'erase-the-impossible-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.offer': {
      en: "Model's #1 here: {token} at {p}. The grammar wants {slot}.",
      ko: '여기서 모형의 1등: {token} (확률 {p}). 문법이 바라는 자리: {slot}.',
      ja: 'ここでのモデルの1位: {token}(確率 {p})。文法が求めるもの: {slot}。',
      zh: '此处模型第一: {token}(概率 {p})。语法要求: {slot}。',
      ar: 'الأول لدى النموذج هنا: {token} باحتمال {p}. القواعد تطلب {slot}.',
      es: 'N.º 1 del modelo aquí: {token}, con {p}. La gramática pide {slot}.',
      fr: 'N° 1 du modèle ici : {token}, à {p}. La grammaire attend {slot}.',
      hi: 'यहाँ मॉडल का पहला: {token}, प्रायिकता {p}. व्याकरण चाहता है: {slot}.',
      id: 'Peringkat 1 model di sini: {token}, dengan {p}. Tata bahasa meminta {slot}.',
      pt: 'N.º 1 do modelo aqui: {token}, com {p}. A gramática pede {slot}.',
    },
    'caption.erase': {
      en: 'Erased {n} forbidden tokens ({mass} in all); the rest share it.',
      ko: '문법이 막는 후보 {n}개를 지웠다 (몫 합 {mass}). 남은 후보끼리 나눠 갖는다.',
      ja: '文法が禁じる候補を {n} 個消した(合計 {mass})。残りで分け合う。',
      zh: '删去语法禁止的 {n} 个候选(合计 {mass}),由其余候选分摊。',
      ar: 'حُذف {n} من المرشحين الممنوعين (مجموعها {mass})، ويتقاسمها الباقون.',
      es: 'Borrados {n} tokens prohibidos ({mass} en total); el resto se lo reparte.',
      fr: '{n} jetons interdits effacés ({mass} au total) ; les autres se le partagent.',
      hi: '{n} वर्जित टोकन मिटाए (कुल {mass}); बाकी इसे बाँट लेते हैं.',
      id: '{n} token terlarang dihapus (total {mass}); sisanya membaginya.',
      pt: '{n} tokens proibidos apagados ({mass} no total); o resto o reparte.',
    },
    'caption.eraseOne': {
      en: 'Erased {n} forbidden tokens ({mass} in all); all of it goes to {token}.',
      ko: '문법이 막는 후보 {n}개를 지웠다 (몫 합 {mass}). 남은 하나가 전부 받는다: {token}.',
      ja: '文法が禁じる候補を {n} 個消した(合計 {mass})。残った一つが全部を受け取る: {token}。',
      zh: '删去语法禁止的 {n} 个候选(合计 {mass}),剩下的一个全部接收: {token}。',
      ar: 'حُذف {n} من المرشحين الممنوعين (مجموعها {mass})، وتذهب كلها إلى {token}.',
      es: 'Borrados {n} tokens prohibidos ({mass} en total); todo pasa a {token}.',
      fr: '{n} jetons interdits effacés ({mass} au total) ; tout va à {token}.',
      hi: '{n} वर्जित टोकन मिटाए (कुल {mass}); सब कुछ मिलता है: {token}.',
      id: '{n} token terlarang dihapus (total {mass}); semuanya ke {token}.',
      pt: '{n} tokens proibidos apagados ({mass} no total); tudo vai para {token}.',
    },
    'caption.pick': {
      en: 'Picked: {token}. Without erasing: {top}.',
      ko: '고른 것: {token}. 지우지 않았다면: {top}.',
      ja: '選んだもの: {token}。消さなければ: {top}。',
      zh: '选中: {token}。若不删除: {top}。',
      ar: 'المختار: {token}. من دون حذف: {top}.',
      es: 'Elegido: {token}. Sin borrar: {top}.',
      fr: 'Choisi : {token}. Sans effacer : {top}.',
      hi: 'चुना गया: {token}. बिना मिटाए: {top}.',
      id: 'Dipilih: {token}. Tanpa menghapus: {top}.',
      pt: 'Escolhido: {token}. Sem apagar: {top}.',
    },
    'label.grammar': {
      en: 'grammar',
      ko: '문법',
      ja: '文法',
      zh: '语法',
      ar: 'القواعد',
      es: 'gramática',
      fr: 'grammaire',
      hi: 'व्याकरण',
      id: 'tata bahasa',
      pt: 'gramática',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المخرج',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
    'label.int': {
      en: '<integer>',
      ko: '<정수>',
      ja: '<整数>',
      zh: '<整数>',
      ar: '<عدد صحيح>',
      es: '<entero>',
      fr: '<entier>',
      hi: '<पूर्णांक>',
      id: '<bulat>',
      pt: '<inteiro>',
    },
    'label.decision': {
      en: 'Next token — decision {k} of {n}',
      ko: '다음 토큰 — 결정 {k} / {n}',
      ja: '次のトークン — 決定 {k} / {n}',
      zh: '下一个词元 — 决定 {k} / {n}',
      ar: 'الرمز التالي — القرار {k} من {n}',
      es: 'Siguiente token — decisión {k} de {n}',
      fr: 'Jeton suivant — décision {k} sur {n}',
      hi: 'अगला टोकन — निर्णय {k} / {n}',
      id: 'Token berikutnya — keputusan {k} dari {n}',
      pt: 'Próximo token — decisão {k} de {n}',
    },
    'label.modelTop': {
      en: "model's #1",
      ko: '모형 1등',
      ja: 'モデルの1位',
      zh: '模型第一',
      ar: 'أول النموذج',
      es: 'n.º 1 del modelo',
      fr: 'n° 1 du modèle',
      hi: 'मॉडल का पहला',
      id: 'no. 1 model',
      pt: 'n.º 1 do modelo',
    },
    'label.picked': {
      en: 'picked',
      ko: '고른 것',
      ja: '選択',
      zh: '选中',
      ar: 'المختار',
      es: 'elegido',
      fr: 'choisi',
      hi: 'चुना गया',
      id: 'dipilih',
      pt: 'escolhido',
    },
    'label.renorm': {
      en: '{from} → {to}',
      ko: '{from} → {to}',
      ja: '{from} → {to}',
      zh: '{from} → {to}',
      ar: '{from} → {to}',
      es: '{from} → {to}',
      fr: '{from} → {to}',
      hi: '{from} → {to}',
      id: '{from} → {to}',
      pt: '{from} → {to}',
    },
  },
};
