import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const fiveStagePipelineFacet: FacetJson = {
  id: 'facet:fiveStagePipeline',
  title: {
    en: 'Five-Stage Pipeline',
    ko: '5단계 파이프라인',
    ja: '5段パイプライン',
    zh: '五级流水线',
    ar: 'خط الأنابيب ذو المراحل الخمس',
    es: 'Segmentación en cinco etapas',
    fr: 'Pipeline à cinq étages',
    hi: 'पाँच-चरण पाइपलाइन',
    id: 'Pipeline Lima Tahap',
    pt: 'Pipeline de cinco estágios',
  },
  description: {
    en: 'Split each instruction into five stages and let the next one enter before the last one leaves. One instruction still takes five cycles; many finish sooner.',
    ko: '명령어를 다섯 단계로 나누고 앞 명령어가 나가기 전에 다음 명령어를 들인다. 명령어 하나는 여전히 5 박자가 걸리고, 여럿은 더 일찍 끝난다.',
    ja: '命令を五つの段に分け、前の命令が出る前に次の命令を入れる。命令一つは相変わらず 5 サイクルかかり、たくさんの命令はより早く終わる。',
    zh: '把每条指令分成五级，前一条尚未离开时就让下一条进入。单条指令仍需 5 个周期，多条指令则更早完成。',
    ar: 'قسّم كل تعليمة إلى خمس مراحل ودع التالية تدخل قبل أن تغادر السابقة. التعليمة الواحدة ما زالت تستغرق خمس دورات، أما الكثيرة فتنتهي أبكر.',
    es: 'Divide cada instrucción en cinco etapas y deja entrar la siguiente antes de que salga la anterior. Una instrucción sigue tardando cinco ciclos; muchas terminan antes.',
    fr: 'Découpez chaque instruction en cinq étages et laissez entrer la suivante avant que la précédente ne sorte. Une instruction prend toujours cinq cycles ; plusieurs finissent plus tôt.',
    hi: 'हर निर्देश को पाँच चरणों में बाँटें और पिछले के निकलने से पहले अगले को भीतर आने दें। एक निर्देश को अब भी पाँच चक्र लगते हैं; कई निर्देश जल्दी पूरे होते हैं।',
    id: 'Bagi setiap instruksi menjadi lima tahap dan biarkan instruksi berikutnya masuk sebelum yang sebelumnya keluar. Satu instruksi tetap butuh lima siklus; banyak instruksi selesai lebih cepat.',
    pt: 'Divida cada instrução em cinco estágios e deixe a próxima entrar antes que a anterior saia. Uma instrução continua levando cinco ciclos; muitas terminam mais cedo.',
  },
  algorithm: 'module:fiveStagePipeline',
  projector: 'module:fiveStagePipelineProjector',
  initialData: {
    type: 'five-stage-pipeline',
    program: [
      'add r1, r17, r18',
      'sub r2, r19, r20',
      'and r3, r21, r22',
      'or r4, r23, r24',
      'add r5, r17, r19',
      'sub r6, r18, r20',
      'and r7, r21, r23',
      'or r8, r22, r24',
      'add r9, r17, r20',
      'sub r10, r18, r19',
      'and r11, r21, r24',
      'or r12, r22, r23',
      'add r13, r17, r21',
      'sub r14, r18, r22',
      'and r15, r19, r23',
      'or r16, r20, r24',
    ],
    stageCount: 5,
    countLadder: [1, 2, 4, 8, 16],
    startCount: 4,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'five-stage-pipeline-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback!,
        {
          widget: 'segmented-slider',
          action: 'count',
          name: 'count',
          label: {
            en: 'Instructions',
            ko: '명령어 수',
            ja: '命令の数',
            zh: '指令数',
            ar: 'عدد التعليمات',
            es: 'Instrucciones',
            fr: 'Instructions',
            hi: 'निर्देशों की संख्या',
            id: 'Jumlah instruksi',
            pt: 'Instruções',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 4, label: '4', default: true },
            { value: 8, label: '8' },
            { value: 16, label: '16' },
          ],
        },
      ],
      metrics: [
        {
          name: 'cycle-count',
          label: {
            en: 'Pipelined cycles',
            ko: '파이프 박자',
            ja: 'パイプラインのサイクル',
            zh: '流水线周期',
            ar: 'دورات خط الأنابيب',
            es: 'Ciclos segmentado',
            fr: 'Cycles en pipeline',
            hi: 'पाइपलाइन चक्र',
            id: 'Siklus pipeline',
            pt: 'Ciclos em pipeline',
          },
          initial: 0,
        },
        {
          name: 'serial-cycle-count',
          label: {
            en: 'One-at-a-time cycles',
            ko: '하나씩 박자',
            ja: '一つずつのサイクル',
            zh: '逐条执行周期',
            ar: 'دورات التنفيذ واحدة تلو الأخرى',
            es: 'Ciclos de una en una',
            fr: 'Cycles une à la fois',
            hi: 'एक-एक करके चक्र',
            id: 'Siklus satu per satu',
            pt: 'Ciclos uma de cada vez',
          },
          initial: 0,
        },
        {
          name: 'latency-cycle-count',
          label: {
            en: 'Latency cycles',
            ko: '지연 박자',
            ja: 'レイテンシのサイクル',
            zh: '延迟周期',
            ar: 'دورات زمن الاستجابة',
            es: 'Ciclos de latencia',
            fr: 'Cycles de latence',
            hi: 'विलंब चक्र',
            id: 'Siklus latensi',
            pt: 'Ciclos de latência',
          },
          initial: 0,
        },
        {
          name: 'speedup-percent',
          label: {
            en: 'Speedup %',
            ko: '빨라짐 %',
            ja: '高速化 %',
            zh: '加速 %',
            ar: 'التسريع %',
            es: 'Aceleración %',
            fr: 'Accélération %',
            hi: 'गति-वृद्धि %',
            id: 'Percepatan %',
            pt: 'Aceleração %',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:five-stage-pipeline-imperative',
      label: {
        en: 'Counting cycles',
        ko: '박자 세기',
        ja: 'サイクルを数える',
        zh: '计算周期',
        ar: 'عدّ الدورات',
        es: 'Contar ciclos',
        fr: 'Compter les cycles',
        hi: 'चक्र गिनना',
        id: 'Menghitung siklus',
        pt: 'Contando ciclos',
      },
    },
  },
  messages: {
    'stage.if': {
      en: 'IF',
      ko: 'IF',
      ja: 'IF',
      zh: 'IF',
      ar: 'IF',
      es: 'IF',
      fr: 'IF',
      hi: 'IF',
      id: 'IF',
      pt: 'IF',
    },
    'stage.id': {
      en: 'ID',
      ko: 'ID',
      ja: 'ID',
      zh: 'ID',
      ar: 'ID',
      es: 'ID',
      fr: 'ID',
      hi: 'ID',
      id: 'ID',
      pt: 'ID',
    },
    'stage.ex': {
      en: 'EX',
      ko: 'EX',
      ja: 'EX',
      zh: 'EX',
      ar: 'EX',
      es: 'EX',
      fr: 'EX',
      hi: 'EX',
      id: 'EX',
      pt: 'EX',
    },
    'stage.mem': {
      en: 'MEM',
      ko: 'MEM',
      ja: 'MEM',
      zh: 'MEM',
      ar: 'MEM',
      es: 'MEM',
      fr: 'MEM',
      hi: 'MEM',
      id: 'MEM',
      pt: 'MEM',
    },
    'stage.wb': {
      en: 'WB',
      ko: 'WB',
      ja: 'WB',
      zh: 'WB',
      ar: 'WB',
      es: 'WB',
      fr: 'WB',
      hi: 'WB',
      id: 'WB',
      pt: 'WB',
    },
    'label.waiting': {
      en: 'Waiting',
      ko: '대기',
      ja: '待機',
      zh: '等待',
      ar: 'في الانتظار',
      es: 'En espera',
      fr: 'En attente',
      hi: 'प्रतीक्षा में',
      id: 'Menunggu',
      pt: 'Na fila',
    },
    'label.retired': {
      en: 'Done',
      ko: '완료',
      ja: '完了',
      zh: '完成',
      ar: 'منتهية',
      es: 'Hechas',
      fr: 'Terminées',
      hi: 'पूर्ण',
      id: 'Selesai',
      pt: 'Concluídas',
    },
    'label.cycle': {
      en: 'Cycle {cycle}',
      ko: '박자 {cycle}',
      ja: 'サイクル {cycle}',
      zh: '周期 {cycle}',
      ar: 'الدورة {cycle}',
      es: 'Ciclo {cycle}',
      fr: 'Cycle {cycle}',
      hi: 'चक्र {cycle}',
      id: 'Siklus {cycle}',
      pt: 'Ciclo {cycle}',
    },
    'label.pipelined': {
      en: 'Pipelined',
      ko: '파이프라인',
      ja: 'パイプライン',
      zh: '流水线',
      ar: 'بخط أنابيب',
      es: 'Segmentado',
      fr: 'En pipeline',
      hi: 'पाइपलाइन',
      id: 'Pipeline',
      pt: 'Em pipeline',
    },
    'label.serial': {
      en: 'One at a time',
      ko: '하나씩',
      ja: '一つずつ',
      zh: '逐条执行',
      ar: 'واحدة تلو الأخرى',
      es: 'De una en una',
      fr: 'Une à la fois',
      hi: 'एक-एक करके',
      id: 'Satu per satu',
      pt: 'Uma de cada vez',
    },
    'label.axis': {
      en: 'cycle',
      ko: '박자',
      ja: 'サイクル',
      zh: '周期',
      ar: 'الدورة',
      es: 'ciclo',
      fr: 'cycle',
      hi: 'चक्र',
      id: 'siklus',
      pt: 'ciclo',
    },
    'label.latency': {
      en: 'Latency {latency}',
      ko: '지연 {latency}',
      ja: 'レイテンシ {latency}',
      zh: '延迟 {latency}',
      ar: 'زمن الاستجابة {latency}',
      es: 'Latencia {latency}',
      fr: 'Latence {latency}',
      hi: 'विलंब {latency}',
      id: 'Latensi {latency}',
      pt: 'Latência {latency}',
    },
    'label.gap': {
      en: '+{gap} cycles',
      ko: '+{gap} 박자',
      ja: '+{gap} サイクル',
      zh: '+{gap} 个周期',
      ar: '+{gap} دورة',
      es: '+{gap} ciclos',
      fr: '+{gap} cycles',
      hi: '+{gap} चक्र',
      id: '+{gap} siklus',
      pt: '+{gap} ciclos',
    },
    'caption.start': {
      en: 'Feeding {count} instructions. One at a time, the last would finish at cycle {serial}.',
      ko: '명령어 {count} 개를 흘린다. 하나씩 돌리면 마지막은 박자 {serial} 에 끝난다.',
      ja: '命令 {count} 個を流す。一つずつなら最後はサイクル {serial} で終わる。',
      zh: '送入 {count} 条指令。逐条执行时，最后一条在第 {serial} 个周期完成。',
      ar: 'نُدخل {count} تعليمات. لو نُفّذت واحدة تلو الأخرى لانتهت الأخيرة في الدورة {serial}.',
      es: 'Entran {count} instrucciones. De una en una, la última terminaría en el ciclo {serial}.',
      fr: '{count} instructions entrent. Une à la fois, la dernière finirait au cycle {serial}.',
      hi: '{count} निर्देश भेजे जा रहे हैं। एक-एक करके चलाने पर आख़िरी चक्र {serial} में पूरा होता।',
      id: 'Mengalirkan {count} instruksi. Satu per satu, yang terakhir selesai di siklus {serial}.',
      pt: 'Entram {count} instruções. Uma de cada vez, a última terminaria no ciclo {serial}.',
    },
    'caption.tick': {
      en: 'Cycle {cycle}: {busy} of {stages} stages busy.',
      ko: '박자 {cycle} — 단계 {stages} 개 가운데 {busy} 개가 일한다.',
      ja: 'サイクル {cycle} — {stages} 段のうち {busy} 段が動いている。',
      zh: '第 {cycle} 个周期：{stages} 级中有 {busy} 级在工作。',
      ar: 'الدورة {cycle}: {busy} من {stages} مراحل تعمل.',
      es: 'Ciclo {cycle}: {busy} de {stages} etapas ocupadas.',
      fr: 'Cycle {cycle} : {busy} étages sur {stages} occupés.',
      hi: 'चक्र {cycle}: {stages} में से {busy} चरण काम पर।',
      id: 'Siklus {cycle}: {busy} dari {stages} tahap sibuk.',
      pt: 'Ciclo {cycle}: {busy} de {stages} estágios ocupados.',
    },
    'caption.retire': {
      en: 'Cycle {cycle}: {text} leaves WB, {latency} cycles after entering IF.',
      ko: '박자 {cycle} — WB 를 나선 명령어 {text} · IF 에 든 뒤 {latency} 박자.',
      ja: 'サイクル {cycle} — {text} が WB を出る。IF に入ってから {latency} サイクル。',
      zh: '第 {cycle} 个周期：{text} 离开 WB，距进入 IF 共 {latency} 个周期。',
      ar: 'الدورة {cycle}: تغادر {text} مرحلة WB بعد {latency} دورات من دخول IF.',
      es: 'Ciclo {cycle}: {text} sale de WB, {latency} ciclos después de entrar en IF.',
      fr: 'Cycle {cycle} : {text} quitte WB, {latency} cycles après être entrée en IF.',
      hi: 'चक्र {cycle}: {text} WB से निकली, IF में आने के {latency} चक्र बाद।',
      id: 'Siklus {cycle}: {text} keluar dari WB, {latency} siklus setelah masuk IF.',
      pt: 'Ciclo {cycle}: {text} sai de WB, {latency} ciclos depois de entrar em IF.',
    },
    'caption.end': {
      en: 'Pipelined {pipe} cycles · one at a time {serial} · speedup {speedup}% · stages busy {util}%',
      ko: '파이프 {pipe} 박자 · 하나씩 {serial} 박자 · 빨라짐 {speedup}% · 단계 가동 {util}%',
      ja: 'パイプライン {pipe} サイクル · 一つずつ {serial} · 高速化 {speedup}% · 段の稼働 {util}%',
      zh: '流水线 {pipe} 个周期 · 逐条 {serial} · 加速 {speedup}% · 各级利用率 {util}%',
      ar: 'خط الأنابيب {pipe} دورة · واحدة تلو الأخرى {serial} · التسريع {speedup}% · انشغال المراحل {util}%',
      es: 'Segmentado {pipe} ciclos · de una en una {serial} · aceleración {speedup}% · etapas ocupadas {util}%',
      fr: 'Pipeline {pipe} cycles · une à la fois {serial} · accélération {speedup} % · étages occupés {util} %',
      hi: 'पाइपलाइन {pipe} चक्र · एक-एक करके {serial} · गति-वृद्धि {speedup}% · चरण उपयोग {util}%',
      id: 'Pipeline {pipe} siklus · satu per satu {serial} · percepatan {speedup}% · tahap terpakai {util}%',
      pt: 'Em pipeline {pipe} ciclos · uma de cada vez {serial} · aceleração {speedup}% · estágios ocupados {util}%',
    },
    'caption.shape': {
      en: 'All stages full for {full} cycles · filling and draining {edge} cycles',
      ko: '모든 단계가 찬 박자 {full} · 채우고 비우는 박자 {edge}',
      ja: '全段が埋まるサイクル {full} · 満たしと空けのサイクル {edge}',
      zh: '各级全满 {full} 个周期 · 填充与排空 {edge} 个周期',
      ar: 'كل المراحل ممتلئة {full} دورة · الملء والتفريغ {edge} دورة',
      es: 'Todas las etapas llenas {full} ciclos · llenado y vaciado {edge} ciclos',
      fr: 'Tous les étages pleins {full} cycles · remplissage et vidage {edge} cycles',
      hi: 'सभी चरण भरे {full} चक्र · भरना और खाली करना {edge} चक्र',
      id: 'Semua tahap penuh {full} siklus · pengisian dan pengosongan {edge} siklus',
      pt: 'Todos os estágios cheios {full} ciclos · enchimento e esvaziamento {edge} ciclos',
    },
  },
};
