/**
 * @piece
 * 갈 곳이 여럿일 수 있는 기계(NFA)를 어떻게 갈 곳이 하나인 기계(DFA)로 바꾸는가.
 *
 * @notation native — 컴파일러 내부 표기 (정규 표현식 · 오토마타의 옮김, ε)
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const nfaToDfaFacet: FacetJson = {
  id: 'facet:nfaToDfa',
  title: {
    en: 'Subset construction: states that clump into one',
    ko: '부분집합 구성 — 여러 자리가 한 덩이로',
    ja: '部分集合構成 — 複数の状態がひとかたまりに',
    zh: '子集构造：多个状态合成一个',
    ar: 'بناء المجموعات الجزئية: حالات تتكتل في حالة واحدة',
    es: 'Construcción de subconjuntos: estados que se agrupan en uno',
    fr: 'Construction des sous-ensembles : des états qui se regroupent en un seul',
    hi: 'उपसमुच्चय निर्माण: कई अवस्थाएँ एक गुच्छ में',
    id: 'Konstruksi subhimpunan: keadaan-keadaan yang menggumpal jadi satu',
    pt: 'Construção de subconjuntos: estados que se juntam em um só',
  },
  description: {
    en: 'An NFA can be in several states at once. Each clump of states it can be in together becomes one state of a DFA.',
    ko: 'NFA 는 여러 자리에 동시에 있을 수 있다. 함께 있을 수 있는 자리들의 덩이 하나가 DFA 의 자리 하나가 된다.',
    ja: 'NFA は同時に複数の状態にいられる。一緒にいられる状態のかたまり一つが DFA の状態一つになる。',
    zh: 'NFA 可以同时处在多个状态。能同时所处的一组状态，成为 DFA 的一个状态。',
    ar: 'يمكن للآلة NFA أن تكون في عدة حالات معًا. كل كتلة من الحالات التي يمكن أن تكون فيها معًا تصبح حالة واحدة في DFA.',
    es: 'Un NFA puede estar en varios estados a la vez. Cada grupo de estados en que puede estar junto se vuelve un estado del DFA.',
    fr: 'Un NFA peut se trouver dans plusieurs états à la fois. Chaque groupe d’états où il peut être ensemble devient un état du DFA.',
    hi: 'NFA एक साथ कई अवस्थाओं में हो सकता है। जिन अवस्थाओं में वह साथ-साथ हो सकता है, उनका हर गुच्छ DFA की एक अवस्था बनता है।',
    id: 'NFA bisa berada di beberapa keadaan sekaligus. Setiap gumpalan keadaan yang bisa ditempati bersama menjadi satu keadaan DFA.',
    pt: 'Um NFA pode estar em vários estados ao mesmo tempo. Cada grupo de estados em que pode estar junto vira um estado do DFA.',
  },
  algorithm: 'module:nfaToDfa',
  scene: 'module:nfaToDfaScene',
  initialData: {
    type: 'nfa-to-dfa',
    stepMs: 1300,
    nfa: {
      states: [0, 1, 2, 3, 4, 5],
      start: 0,
      alphabet: ['i', 'f'],
      edges: [
        { from: 0, to: 1, on: null },
        { from: 0, to: 4, on: null },
        { from: 1, to: 2, on: 'i' },
        { from: 2, to: 3, on: 'f' },
        { from: 4, to: 5, on: 'i' },
        { from: 4, to: 5, on: 'f' },
        { from: 5, to: 5, on: 'i' },
        { from: 5, to: 5, on: 'f' },
      ],
      accepts: [
        { state: 3, kind: 'IF' },
        { state: 5, kind: 'NAME' },
      ],
    },
    rules: [
      { kind: 'IF', pattern: 'if' },
      { kind: 'NAME', pattern: '(i|f)(i|f)*' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.nfa': {
      en: 'NFA', ko: 'NFA', ja: 'NFA', zh: 'NFA', ar: 'NFA', es: 'NFA', fr: 'NFA', hi: 'NFA', id: 'NFA', pt: 'NFA',
    },
    'label.dfa': {
      en: 'DFA', ko: 'DFA', ja: 'DFA', zh: 'DFA', ar: 'DFA', es: 'DFA', fr: 'DFA', hi: 'DFA', id: 'DFA', pt: 'DFA',
    },
    'label.todo': {
      en: 'To do: {list}',
      ko: '할 일: {list}',
      ja: '未処理: {list}',
      zh: '待处理：{list}',
      ar: 'المتبقي: {list}',
      es: 'Pendientes: {list}',
      fr: 'À traiter : {list}',
      hi: 'बाकी: {list}',
      id: 'Belum diproses: {list}',
      pt: 'Pendentes: {list}',
    },
    'label.todoNone': {
      en: 'To do: none',
      ko: '할 일: 없음',
      ja: '未処理: なし',
      zh: '待处理：无',
      ar: 'المتبقي: لا شيء',
      es: 'Pendientes: ninguno',
      fr: 'À traiter : aucun',
      hi: 'बाकी: कोई नहीं',
      id: 'Belum diproses: tidak ada',
      pt: 'Pendentes: nenhum',
    },
    'caption.start': {
      en: 'Start state: {start}. The DFA is still empty.',
      ko: '시작 자리: {start}. DFA 는 아직 비었다.',
      ja: '開始状態: {start}。DFA はまだ空だ。',
      zh: '起始状态：{start}。DFA 还是空的。',
      ar: 'حالة البداية: {start}. الآلة DFA ما زالت فارغة.',
      es: 'Estado inicial: {start}. El DFA aún está vacío.',
      fr: 'État initial : {start}. Le DFA est encore vide.',
      hi: 'आरंभ अवस्था: {start}। DFA अभी खाली है।',
      id: 'Keadaan awal: {start}. DFA masih kosong.',
      pt: 'Estado inicial: {start}. O DFA ainda está vazio.',
    },
    'caption.open': {
      en: 'Gather every state reachable from {seed} by ε alone: {set}. New state: {d}.',
      ko: '{seed} 에서 ε 로만 닿는 자리를 모두 모은다: {set}. 새 자리: {d}.',
      ja: '{seed} から ε だけで届く状態をすべて集める: {set}。新しい状態: {d}。',
      zh: '收集从 {seed} 只经 ε 能到的所有状态：{set}。新状态：{d}。',
      ar: 'اجمع كل حالة يمكن بلوغها من {seed} عبر ε وحدها: {set}. حالة جديدة: {d}.',
      es: 'Reúne todo estado alcanzable desde {seed} solo con ε: {set}. Estado nuevo: {d}.',
      fr: 'Réunir tout état atteignable depuis {seed} par ε seul : {set}. Nouvel état : {d}.',
      hi: '{seed} से केवल ε द्वारा पहुँचने वाली सब अवस्थाएँ जुटाओ: {set}। नई अवस्था: {d}।',
      id: 'Kumpulkan semua keadaan yang tercapai dari {seed} hanya lewat ε: {set}. Keadaan baru: {d}.',
      pt: 'Reúna todo estado alcançável a partir de {seed} só por ε: {set}. Estado novo: {d}.',
    },
    'caption.new': {
      en: 'From {from} on {ch}: {set}. New state: {to}.',
      ko: '{from} · 글자 {ch} → {set}. 새 자리: {to}.',
      ja: '{from} · 文字 {ch} → {set}。新しい状態: {to}。',
      zh: '{from} · 字符 {ch} → {set}。新状态：{to}。',
      ar: 'من {from} بالحرف {ch}: {set}. حالة جديدة: {to}.',
      es: 'Desde {from} con {ch}: {set}. Estado nuevo: {to}.',
      fr: 'Depuis {from} sur {ch} : {set}. Nouvel état : {to}.',
      hi: '{from} से अक्षर {ch} पर: {set}। नई अवस्था: {to}।',
      id: 'Dari {from} dengan {ch}: {set}. Keadaan baru: {to}.',
      pt: 'De {from} com {ch}: {set}. Estado novo: {to}.',
    },
    'caption.newClosure': {
      en: 'From {from} on {ch}: {moved}, ε-closure {set}. New state: {to}.',
      ko: '{from} · 글자 {ch} → {moved}, ε-닫힘 {set}. 새 자리: {to}.',
      ja: '{from} · 文字 {ch} → {moved}、ε 閉包 {set}。新しい状態: {to}。',
      zh: '{from} · 字符 {ch} → {moved}，ε 闭包 {set}。新状态：{to}。',
      ar: 'من {from} بالحرف {ch}: {moved}، وإغلاق ε هو {set}. حالة جديدة: {to}.',
      es: 'Desde {from} con {ch}: {moved}, cierre ε {set}. Estado nuevo: {to}.',
      fr: 'Depuis {from} sur {ch} : {moved}, fermeture ε {set}. Nouvel état : {to}.',
      hi: '{from} से अक्षर {ch} पर: {moved}, ε-संवरण {set}। नई अवस्था: {to}।',
      id: 'Dari {from} dengan {ch}: {moved}, tutupan ε {set}. Keadaan baru: {to}.',
      pt: 'De {from} com {ch}: {moved}, fecho ε {set}. Estado novo: {to}.',
    },
    'caption.same': {
      en: 'From {from} on {ch}: {set}. Already a state: {to}.',
      ko: '{from} · 글자 {ch} → {set}. 이미 있는 자리: {to}.',
      ja: '{from} · 文字 {ch} → {set}。すでにある状態: {to}。',
      zh: '{from} · 字符 {ch} → {set}。已有的状态：{to}。',
      ar: 'من {from} بالحرف {ch}: {set}. حالة موجودة من قبل: {to}.',
      es: 'Desde {from} con {ch}: {set}. Ya es un estado: {to}.',
      fr: 'Depuis {from} sur {ch} : {set}. État déjà là : {to}.',
      hi: '{from} से अक्षर {ch} पर: {set}। पहले से मौजूद अवस्था: {to}।',
      id: 'Dari {from} dengan {ch}: {set}. Keadaan yang sudah ada: {to}.',
      pt: 'De {from} com {ch}: {set}. Estado que já existe: {to}.',
    },
    'caption.sameClosure': {
      en: 'From {from} on {ch}: {moved}, ε-closure {set}. Already a state: {to}.',
      ko: '{from} · 글자 {ch} → {moved}, ε-닫힘 {set}. 이미 있는 자리: {to}.',
      ja: '{from} · 文字 {ch} → {moved}、ε 閉包 {set}。すでにある状態: {to}。',
      zh: '{from} · 字符 {ch} → {moved}，ε 闭包 {set}。已有的状态：{to}。',
      ar: 'من {from} بالحرف {ch}: {moved}، وإغلاق ε هو {set}. حالة موجودة من قبل: {to}.',
      es: 'Desde {from} con {ch}: {moved}, cierre ε {set}. Ya es un estado: {to}.',
      fr: 'Depuis {from} sur {ch} : {moved}, fermeture ε {set}. État déjà là : {to}.',
      hi: '{from} से अक्षर {ch} पर: {moved}, ε-संवरण {set}। पहले से मौजूद अवस्था: {to}।',
      id: 'Dari {from} dengan {ch}: {moved}, tutupan ε {set}. Keadaan yang sudah ada: {to}.',
      pt: 'De {from} com {ch}: {moved}, fecho ε {set}. Estado que já existe: {to}.',
    },
    'caption.summary': {
      en: 'DFA states: {n} · transitions: {m}. Nothing left to do.',
      ko: 'DFA 자리: {n} · 옮김: {m}. 할 일이 비었다.',
      ja: 'DFA の状態: {n} · 遷移: {m}。未処理はもうない。',
      zh: 'DFA 状态：{n} · 转移：{m}。没有待处理的了。',
      ar: 'حالات DFA: {n} · الانتقالات: {m}. لم يبق شيء.',
      es: 'Estados del DFA: {n} · transiciones: {m}. No queda nada pendiente.',
      fr: 'États du DFA : {n} · transitions : {m}. Plus rien à traiter.',
      hi: 'DFA अवस्थाएँ: {n} · संक्रमण: {m}। कुछ बाकी नहीं।',
      id: 'Keadaan DFA: {n} · transisi: {m}. Tidak ada yang tersisa.',
      pt: 'Estados do DFA: {n} · transições: {m}. Nada pendente.',
    },
  },
  blocks: {
    stage: { type: 'nfa-to-dfa-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
