import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 밖에서 공인 주소로 돌아온 답을 NAT 는 안의 누구에게 되돌려야 하는지 어떻게 아는가.
 */
export const natMappingTableFacet: FacetJson = {
  id: 'facet:natMappingTable',
  title: {
    en: 'NAT mapping table',
    ko: 'NAT 매핑 테이블',
    ja: 'NAT マッピングテーブル',
    zh: 'NAT 映射表',
    ar: 'جدول تعيين NAT',
    es: 'Tabla de traducción NAT',
    fr: 'Table de correspondance NAT',
    hi: 'NAT मैपिंग तालिका',
    id: 'Tabel pemetaan NAT',
    pt: 'Tabela de mapeamento NAT',
  },
  description: {
    en: 'Each outgoing packet writes a row. A reply finds its owner by the port it arrives on.',
    ko: '나가는 패킷마다 줄이 적힌다. 돌아온 답은 받는 포트로 그 줄을 찾아 주인에게 간다.',
    ja: '出ていくパケットごとに行が書かれる。戻ってきた返事は、届いたポートで持ち主を見つける。',
    zh: '每个出去的数据包都会写下一行。回来的应答凭到达的端口找到它的主人。',
    ar: 'كل حزمة خارجة تكتب سطرًا. يجد الرد صاحبه عبر المنفذ الذي وصل إليه.',
    es: 'Cada paquete saliente escribe una fila. La respuesta encuentra a su dueño por el puerto al que llega.',
    fr: 'Chaque paquet sortant inscrit une ligne. La réponse retrouve son destinataire par le port où elle arrive.',
    hi: 'हर बाहर जाने वाला पैकेट एक पंक्ति लिखता है। जवाब उस पोर्ट से अपने मालिक तक पहुँचता है जिस पर वह आता है।',
    id: 'Setiap paket keluar menulis satu baris. Balasan menemukan pemiliknya lewat port tempat ia tiba.',
    pt: 'Cada pacote que sai escreve uma linha. A resposta encontra o dono pela porta em que chega.',
  },
  algorithm: 'module:natMappingTable',
  scene: 'module:natMappingTableScene',
  initialData: {
    type: 'nat-mapping-table',
    stepMs: 1500,
    publicAddr: '203.0.113.9',
    firstPort: 61001,
    outgoing: [
      { from: { addr: '10.0.0.11', port: 50500 }, to: { addr: '198.51.100.7', port: 443 } },
      { from: { addr: '10.0.0.12', port: 50500 }, to: { addr: '192.0.2.44', port: 443 } },
    ],
    incoming: [
      { from: { addr: '192.0.2.44', port: 443 }, toPort: 61002 },
      { from: { addr: '198.51.100.7', port: 443 }, toPort: 61001 },
      { from: { addr: '192.0.2.99', port: 443 }, toPort: 61005 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.empty': {
      en: 'The table is empty. Public address: {addr}.',
      ko: '표가 비어 있다. 공인 주소: {addr}.',
      ja: '表は空だ。公開アドレス: {addr}。',
      zh: '表是空的。公网地址:{addr}。',
      ar: 'الجدول فارغ. العنوان العام: {addr}.',
      es: 'La tabla está vacía. Dirección pública: {addr}.',
      fr: 'La table est vide. Adresse publique : {addr}.',
      hi: 'तालिका खाली है। सार्वजनिक पता: {addr}।',
      id: 'Tabel masih kosong. Alamat publik: {addr}.',
      pt: 'A tabela está vazia. Endereço público: {addr}.',
    },
    'caption.write': {
      en: 'Out from {inside}. Row written for public port {port}.',
      ko: '나감 — 보낸 이 {inside}. 공인 포트 {port} 줄을 적었다.',
      ja: '送信 — 送り元 {inside}。公開ポート {port} の行を書いた。',
      zh: '外发 — 来自 {inside}。已为公网端口 {port} 写下一行。',
      ar: 'خروج من {inside}. كُتب سطر للمنفذ العام {port}.',
      es: 'Sale de {inside}. Fila escrita para el puerto público {port}.',
      fr: 'Sortie depuis {inside}. Ligne inscrite pour le port public {port}.',
      hi: '{inside} से बाहर। सार्वजनिक पोर्ट {port} के लिए पंक्ति लिखी गई।',
      id: 'Keluar dari {inside}. Baris ditulis untuk port publik {port}.',
      pt: 'Sai de {inside}. Linha escrita para a porta pública {port}.',
    },
    'caption.return': {
      en: 'In to public port {port}. Row found. Back to: {inside}.',
      ko: '들어옴 — 받는 포트 {port}. 줄을 찾았다. 돌려보낼 곳: {inside}.',
      ja: '受信 — 宛先ポート {port}。行が見つかった。戻す先: {inside}。',
      zh: '进入 — 公网端口 {port}。找到了这一行。送回:{inside}。',
      ar: 'دخول إلى المنفذ العام {port}. وُجد السطر. يعود إلى: {inside}.',
      es: 'Entra al puerto público {port}. Fila encontrada. De vuelta a: {inside}.',
      fr: 'Entrée sur le port public {port}. Ligne trouvée. Renvoyé à : {inside}.',
      hi: 'सार्वजनिक पोर्ट {port} पर आया। पंक्ति मिली। वापस भेजा: {inside}।',
      id: 'Masuk ke port publik {port}. Baris ditemukan. Kembali ke: {inside}.',
      pt: 'Entra na porta pública {port}. Linha encontrada. De volta para: {inside}.',
    },
    'caption.drop': {
      en: 'In to public port {port}. No row. Dropped at the boundary.',
      ko: '들어옴 — 받는 포트 {port}. 적힌 줄 없음. 경계에서 버린다.',
      ja: '受信 — 宛先ポート {port}。行がない。境界で捨てる。',
      zh: '进入 — 公网端口 {port}。没有这一行。在边界丢弃。',
      ar: 'دخول إلى المنفذ العام {port}. لا يوجد سطر. أُسقطت عند الحد.',
      es: 'Entra al puerto público {port}. No hay fila. Descartado en el borde.',
      fr: 'Entrée sur le port public {port}. Aucune ligne. Rejeté à la frontière.',
      hi: 'सार्वजनिक पोर्ट {port} पर आया। कोई पंक्ति नहीं। सीमा पर गिरा दिया।',
      id: 'Masuk ke port publik {port}. Tidak ada baris. Dibuang di batas.',
      pt: 'Entra na porta pública {port}. Nenhuma linha. Descartado na fronteira.',
    },
    'label.outside': {
      en: 'Outside',
      ko: '밖',
      ja: '外側',
      zh: '外部',
      ar: 'الخارج',
      es: 'Fuera',
      fr: 'Extérieur',
      hi: 'बाहर',
      id: 'Luar',
      pt: 'Fora',
    },
    'label.inside': {
      en: 'Inside',
      ko: '안',
      ja: '内側',
      zh: '内部',
      ar: 'الداخل',
      es: 'Dentro',
      fr: 'Intérieur',
      hi: 'अंदर',
      id: 'Dalam',
      pt: 'Dentro',
    },
    'label.nat': {
      en: 'NAT',
      ko: 'NAT',
      ja: 'NAT',
      zh: 'NAT',
      ar: 'NAT',
      es: 'NAT',
      fr: 'NAT',
      hi: 'NAT',
      id: 'NAT',
      pt: 'NAT',
    },
    'label.dropped': {
      en: 'Dropped',
      ko: '버림',
      ja: '破棄',
      zh: '丢弃',
      ar: 'أُسقطت',
      es: 'Descartado',
      fr: 'Rejeté',
      hi: 'गिराया',
      id: 'Dibuang',
      pt: 'Descartado',
    },
    'col.port': {
      en: 'Public port',
      ko: '공인 포트',
      ja: '公開ポート',
      zh: '公网端口',
      ar: 'المنفذ العام',
      es: 'Puerto público',
      fr: 'Port public',
      hi: 'सार्वजनिक पोर्ट',
      id: 'Port publik',
      pt: 'Porta pública',
    },
    'col.inside': {
      en: 'Inside',
      ko: '안쪽',
      ja: '内側',
      zh: '内部',
      ar: 'الداخل',
      es: 'Dentro',
      fr: 'Intérieur',
      hi: 'अंदर',
      id: 'Dalam',
      pt: 'Dentro',
    },
    'col.remote': {
      en: 'Remote',
      ko: '먼 쪽',
      ja: '相手側',
      zh: '远端',
      ar: 'الطرف البعيد',
      es: 'Remoto',
      fr: 'Distant',
      hi: 'दूर वाला',
      id: 'Jarak jauh',
      pt: 'Remoto',
    },
  },
  blocks: {
    stage: { type: 'nat-mapping-table-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
