/**
 * facet:wrongInOneDirection — 블룸 필터의 답을 믿는 법.
 *
 * @piece 질문 하나에 답하고 멈추는 조각 (S-piece).
 *
 * 묻는 넷은 모두 실측이다. h1 은 Java `String.hashCode` 를 `& 0x7FFFFFFF` 한 값,
 * h2 는 FNV-1a 32bit 를 `& 0x7FFFFFFF` 한 뒤 `| 1` 로 홀수로 만든 값이며, 자리는
 * algorithm 이 `(h1 + i·h2) mod 16` 으로 그 자리에서 셈한다. 시작 비트열은
 * fig · kiwi · mango 를 넣어 얻은 것과 같다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const wrongInOneDirectionFacet: FacetJson = {
  id: 'facet:wrongInOneDirection',
  title: {
    en: 'Wrong in only one direction',
    ko: '한쪽으로만 틀린다',
    ja: '間違いは一方向だけ',
    zh: '只会朝一个方向出错',
    ar: 'الخطأ في اتجاه واحد فقط',
    es: 'Se equivoca en un solo sentido',
    fr: 'Faux dans un seul sens',
    hi: 'गलती केवल एक दिशा में',
    id: 'Salah hanya di satu arah',
    pt: 'Erra em uma só direção',
  },
  description: {
    en: 'A Bloom filter can say "present" about something never put in, but it never says "absent" about something that was.',
    ko: '블룸 필터는 넣지 않은 것을 "있다" 고 할 수 있지만, 넣은 것을 "없다" 고 하지는 않는다.',
    ja: 'ブルームフィルタは入れていないものを「ある」と答えることはあっても、入れたものを「ない」とは答えない。',
    zh: '布隆过滤器可能对没放进去的东西回答"有"，但绝不会对放进去的东西回答"没有"。',
    ar: 'قد يقول مرشح بلوم "موجود" عن شيء لم يُدخل قط، لكنه لا يقول أبدًا "غير موجود" عن شيء أُدخل.',
    es: 'Un filtro de Bloom puede decir "presente" de algo que nunca se insertó, pero jamás dice "ausente" de algo insertado.',
    fr: 'Un filtre de Bloom peut dire « présent » pour un élément jamais inséré, mais il ne dit jamais « absent » pour un élément inséré.',
    hi: 'ब्लूम फ़िल्टर उस चीज़ को भी "मौजूद" कह सकता है जो कभी डाली ही नहीं गई, पर डाली गई चीज़ को "अनुपस्थित" कभी नहीं कहता।',
    id: 'Filter Bloom bisa menjawab "ada" untuk sesuatu yang tidak pernah dimasukkan, tetapi tidak pernah menjawab "tidak ada" untuk yang sudah dimasukkan.',
    pt: 'Um filtro de Bloom pode dizer "presente" sobre algo que nunca foi inserido, mas nunca diz "ausente" sobre algo que foi.',
  },
  algorithm: 'module:wrongInOneDirection',
  projector: 'module:wrongInOneDirectionProjector',
  initialData: {
    type: 'wrong-in-one-direction',
    slotCount: 16,
    hashCount: 3,
    bits: '1010100101001010',
    inserted: ['fig', 'kiwi', 'mango'],
    queries: ['fig', 'date', 'apple', 'cherry'],
    hashes: {
      fig: { h1: 101380, h2: 1105500693 },
      kiwi: { h1: 3292336, h2: 1073607833 },
      mango: { h1: 103662530, h2: 242548693 },
      date: { h1: 3076014, h2: 1416813657 },
      apple: { h1: 93029210, h2: 280767167 },
      cherry: { h1: 785970585, h2: 1232791673 },
    },
    stepMs: 780,
  },
  blocks: {
    stage: { type: 'wrong-in-one-direction-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'label.inserted': {
      en: 'Put in',
      ko: '넣은 것',
      ja: '入れたもの',
      zh: '放进去的',
      ar: 'ما أُدخل',
      es: 'Insertados',
      fr: 'Insérés',
      hi: 'डाले गए',
      id: 'Yang dimasukkan',
      pt: 'Inseridos',
    },
    'label.answerYes': {
      en: '"Present"',
      ko: '"있다"',
      ja: '「ある」',
      zh: '"有"',
      ar: '«موجود»',
      es: '"Presente"',
      fr: '« Présent »',
      hi: '"मौजूद"',
      id: '"Ada"',
      pt: '"Presente"',
    },
    'label.answerNo': {
      en: '"Absent"',
      ko: '"없다"',
      ja: '「ない」',
      zh: '"没有"',
      ar: '«غير موجود»',
      es: '"Ausente"',
      fr: '« Absent »',
      hi: '"अनुपस्थित"',
      id: '"Tidak ada"',
      pt: '"Ausente"',
    },
    'label.canBeWrong': {
      en: 'can be wrong',
      ko: '틀릴 수 있다',
      ja: '間違うことがある',
      zh: '可能出错',
      ar: 'قد يكون خاطئًا',
      es: 'puede fallar',
      fr: 'peut se tromper',
      hi: 'गलत हो सकता है',
      id: 'bisa salah',
      pt: 'pode errar',
    },
    'label.neverWrong': {
      en: 'never wrong',
      ko: '틀리지 않는다',
      ja: '間違わない',
      zh: '绝不出错',
      ar: 'لا يخطئ أبدًا',
      es: 'nunca falla',
      fr: 'ne se trompe jamais',
      hi: 'कभी गलत नहीं',
      id: 'tidak pernah salah',
      pt: 'nunca erra',
    },
    'caption.pass': {
      en: 'Slot {slot} is on. It passes.',
      ko: '{slot} 번 자리는 켜져 있다. 지난다.',
      ja: '{slot} 番のビットは立っている。通り抜ける。',
      zh: '第 {slot} 位是 1，可以通过。',
      ar: 'الخانة {slot} مضيئة. يمر.',
      es: 'La casilla {slot} está encendida. Pasa.',
      fr: 'La case {slot} est allumée. Il passe.',
      hi: 'खाना {slot} चालू है। आगे बढ़ता है।',
      id: 'Slot {slot} menyala. Lolos.',
      pt: 'A posição {slot} está ligada. Passa.',
    },
    'caption.block': {
      en: 'Slot {slot} is off. It stops here.',
      ko: '{slot} 번 자리는 꺼져 있다. 여기서 막힌다.',
      ja: '{slot} 番のビットは 0。ここで止まる。',
      zh: '第 {slot} 位是 0，在这里被挡住。',
      ar: 'الخانة {slot} مطفأة. يتوقف هنا.',
      es: 'La casilla {slot} está apagada. Se detiene aquí.',
      fr: 'La case {slot} est éteinte. Il est bloqué ici.',
      hi: 'खाना {slot} बंद है। यहीं रुक जाता है।',
      id: 'Slot {slot} padam. Berhenti di sini.',
      pt: 'A posição {slot} está desligada. Para aqui.',
    },
    'caption.yesTrue': {
      en: 'All three on, so "present" — and it really was put in: {word}.',
      ko: '셋 다 켜져 있다 — "있다". 넣은 것이 맞다: {word}.',
      ja: '三つとも立っている — 「ある」。実際に入れたもの: {word}。',
      zh: '三位都是 1 — 回答"有"。它确实放进去过: {word}。',
      ar: 'الثلاثة مضيئة — «موجود»، وقد أُدخل فعلاً: {word}.',
      es: 'Las tres encendidas — "presente", y de verdad se insertó: {word}.',
      fr: 'Les trois sont allumées — « présent », et il a bien été inséré : {word}.',
      hi: 'तीनों चालू — "मौजूद", और यह सचमुच डाला गया था: {word}।',
      id: 'Ketiganya menyala — "ada", dan memang pernah dimasukkan: {word}.',
      pt: 'As três ligadas — "presente", e de fato foi inserido: {word}.',
    },
    'caption.yesFalse': {
      en: 'All three on, so "present". But it was never put in: {word}.',
      ko: '셋 다 켜져 있다 — "있다". 그런데 넣은 적이 없다: {word}.',
      ja: '三つとも立っている — 「ある」。しかし一度も入れていない: {word}。',
      zh: '三位都是 1 — 回答"有"。但它从未放进去: {word}。',
      ar: 'الثلاثة مضيئة — «موجود». لكنه لم يُدخل قط: {word}.',
      es: 'Las tres encendidas — "presente". Pero nunca se insertó: {word}.',
      fr: 'Les trois sont allumées — « présent ». Mais il n’a jamais été inséré : {word}.',
      hi: 'तीनों चालू — "मौजूद"। पर यह कभी डाला ही नहीं गया: {word}।',
      id: 'Ketiganya menyala — "ada". Padahal tidak pernah dimasukkan: {word}.',
      pt: 'As três ligadas — "presente". Mas nunca foi inserido: {word}.',
    },
    'caption.no': {
      en: 'It met an off slot, so "absent". This answer cannot be wrong.',
      ko: '꺼진 자리를 만났다 — "없다". 이 답은 틀릴 수 없다.',
      ja: '0 のビットに当たった — 「ない」。この答えは間違いようがない。',
      zh: '遇到了 0 — 回答"没有"。这个回答不可能出错。',
      ar: 'صادف خانة مطفأة — «غير موجود». هذا الجواب لا يمكن أن يخطئ.',
      es: 'Encontró una casilla apagada — "ausente". Esta respuesta no puede fallar.',
      fr: 'Il a rencontré une case éteinte — « absent ». Cette réponse ne peut pas être fausse.',
      hi: 'एक बंद खाना मिला — "अनुपस्थित"। यह उत्तर गलत हो ही नहीं सकता।',
      id: 'Bertemu slot padam — "tidak ada". Jawaban ini tidak mungkin salah.',
      pt: 'Encontrou uma posição desligada — "ausente". Esta resposta não pode estar errada.',
    },
    'caption.owners': {
      en: 'Others had switched those three on: {owners}.',
      ko: '그 셋을 켠 것은 다른 것들이다: {owners}.',
      ja: 'その三つを立てたのは別のもの: {owners}。',
      zh: '把那三位点亮的是别的东西: {owners}。',
      ar: 'من أضاء تلك الخانات الثلاث هم غيره: {owners}.',
      es: 'Otros habían encendido esas tres: {owners}.',
      fr: 'D’autres avaient allumé ces trois cases : {owners}.',
      hi: 'उन तीनों को दूसरों ने चालू किया था: {owners}।',
      id: 'Yang menyalakan ketiganya adalah yang lain: {owners}.',
      pt: 'Outros haviam ligado essas três: {owners}.',
    },
    'caption.conclusion': {
      en: '"Absent" is always right. "Present" is not.',
      ko: '"없다" 는 늘 옳다. "있다" 는 그렇지 않다.',
      ja: '「ない」は常に正しい。「ある」はそうではない。',
      zh: '"没有"总是对的。"有"则不然。',
      ar: '«غير موجود» صحيح دائمًا. «موجود» ليس كذلك.',
      es: '"Ausente" siempre acierta. "Presente" no.',
      fr: '« Absent » a toujours raison. « Présent » non.',
      hi: '"अनुपस्थित" हमेशा सही होता है। "मौजूद" नहीं।',
      id: '"Tidak ada" selalu benar. "Ada" tidak.',
      pt: '"Ausente" está sempre certo. "Presente" não.',
    },
  },
};
