/**
 * @piece
 * 질문: KV 캐시는 글이 길어지면 얼마나 커지는가
 *
 * 자리 하나가 모든 층에 K 한 줄 · V 한 줄을 얹는다. 자리 하나마다 512 KiB 로 곧게 늘고,
 * 쌓인 것은 줄지 않는다. 모형 구성은 Llama 2 7B 의 공개 구성값이다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const cacheKeepsGrowingFacet: FacetJson = {
  id: 'facet:cacheKeepsGrowing',
  title: {
    en: 'The cache keeps growing',
    ko: '캐시는 계속 자란다',
    ja: 'キャッシュは増え続ける',
    zh: '缓存不断增长',
    ar: 'الذاكرة المؤقتة تواصل النمو',
    es: 'La caché no para de crecer',
    fr: 'Le cache ne cesse de grossir',
    hi: 'कैश बढ़ता ही जाता है',
    id: 'Cache terus membesar',
    pt: 'O cache não para de crescer',
  },
  description: {
    en: 'How large does the KV cache get as the text grows longer?',
    ko: 'KV 캐시는 글이 길어지면 얼마나 커지는가',
    ja: '文章が長くなると KV キャッシュはどれだけ大きくなるか',
    zh: '文本变长时，KV 缓存会变得多大？',
    ar: 'إلى أي حد تكبر ذاكرة KV المؤقتة كلما طال النص؟',
    es: '¿Cuánto crece la caché KV a medida que el texto se alarga?',
    fr: 'Jusqu’où grossit le cache KV quand le texte s’allonge ?',
    hi: 'पाठ लंबा होने पर KV कैश कितना बड़ा हो जाता है?',
    id: 'Seberapa besar cache KV saat teks makin panjang?',
    pt: 'Quanto o cache KV cresce à medida que o texto fica mais longo?',
  },
  algorithm: 'module:cacheKeepsGrowing',
  scene: 'module:cacheKeepsGrowingScene',
  initialData: {
    type: 'cache-keeps-growing',
    // Llama 2 7B 의 공개 구성값. 값 하나는 fp16 이라 2 바이트.
    model: { layers: 32, kvHeads: 32, headDim: 128, valueBytes: 2 },
    positions: [1, 1024, 2048, 3072, 4096],
    contextLimit: 4096,
    stepMs: 1200,
  },
  shuffleOnReset: false,
  messages: {
    'caption.unitFormula': {
      en: 'K and V 2 × {layers} layers × {heads} heads × {dim} dims × {bytes} bytes each',
      ko: 'K·V 2 × 층 {layers} × 머리 {heads} × 차원 {dim} × 값마다 {bytes} 바이트',
      ja: 'K と V で 2 × 層 {layers} × ヘッド {heads} × 次元 {dim} × 値ごとに {bytes} バイト',
      zh: 'K 与 V 共 2 × {layers} 层 × {heads} 头 × {dim} 维 × 每个值 {bytes} 字节',
      ar: 'K و V ‏2 × {layers} طبقة × {heads} رأس × {dim} بُعد × {bytes} بايت لكل قيمة',
      es: 'K y V 2 × {layers} capas × {heads} cabezas × {dim} dimensiones × {bytes} bytes cada valor',
      fr: 'K et V 2 × {layers} couches × {heads} têtes × {dim} dimensions × {bytes} octets par valeur',
      hi: 'K और V 2 × {layers} परतें × {heads} हेड × {dim} आयाम × हर मान {bytes} बाइट',
      id: 'K dan V 2 × {layers} lapisan × {heads} kepala × {dim} dimensi × {bytes} byte per nilai',
      pt: 'K e V 2 × {layers} camadas × {heads} cabeças × {dim} dimensões × {bytes} bytes por valor',
    },
    'caption.unitTotal': {
      en: '= {total} bytes for one position, {size}',
      ko: '= {total} 바이트. 자리 하나에 {size}',
      ja: '= {total} バイト。1 位置で {size}',
      zh: '= {total} 字节，一个位置 {size}',
      ar: '= {total} بايت لموضع واحد، أي {size}',
      es: '= {total} bytes por posición, {size}',
      fr: '= {total} octets pour une position, soit {size}',
      hi: '= एक स्थान के लिए {total} बाइट, यानी {size}',
      id: '= {total} byte untuk satu posisi, {size}',
      pt: '= {total} bytes por posição, {size}',
    },
    'caption.grow': {
      en: 'Positions {from} → {to}. Every layer gains {added} more K and V rows.',
      ko: '자리 {from} → {to}. 층마다 K 줄 · V 줄이 {added} 개씩 더 붙는다.',
      ja: '位置 {from} → {to}。各層に K 行と V 行が {added} ずつ加わる。',
      zh: '位置 {from} → {to}。每一层各多出 {added} 行 K 和 V。',
      ar: 'المواضع {from} → {to}. تكسب كل طبقة {added} صفًا إضافيًا من K و V.',
      es: 'Posiciones {from} → {to}. Cada capa gana {added} filas más de K y de V.',
      fr: 'Positions {from} → {to}. Chaque couche gagne {added} lignes de K et de V.',
      hi: 'स्थान {from} → {to}। हर परत में K और V की {added} पंक्तियाँ और जुड़ती हैं।',
      id: 'Posisi {from} → {to}. Setiap lapisan bertambah {added} baris K dan V.',
      pt: 'Posições {from} → {to}. Cada camada ganha mais {added} linhas de K e de V.',
    },
    'caption.growFull': {
      en: 'Positions {from} → {to}, the context limit. Every layer gains {added} more K and V rows.',
      ko: '자리 {from} → {to}, 문맥 한도. 층마다 K 줄 · V 줄이 {added} 개씩 더 붙는다.',
      ja: '位置 {from} → {to}、文脈の上限。各層に K 行と V 行が {added} ずつ加わる。',
      zh: '位置 {from} → {to}，达到上下文上限。每一层各多出 {added} 行 K 和 V。',
      ar: 'المواضع {from} → {to}، حدّ السياق. تكسب كل طبقة {added} صفًا إضافيًا من K و V.',
      es: 'Posiciones {from} → {to}, el límite de contexto. Cada capa gana {added} filas más de K y de V.',
      fr: 'Positions {from} → {to}, la limite de contexte. Chaque couche gagne {added} lignes de K et de V.',
      hi: 'स्थान {from} → {to}, संदर्भ की सीमा। हर परत में K और V की {added} पंक्तियाँ और जुड़ती हैं।',
      id: 'Posisi {from} → {to}, batas konteks. Setiap lapisan bertambah {added} baris K dan V.',
      pt: 'Posições {from} → {to}, o limite de contexto. Cada camada ganha mais {added} linhas de K e de V.',
    },
    'caption.cache': {
      en: 'Cache {size} ({total} bytes), still {per} per position',
      ko: '캐시 {size} ({total} 바이트). 자리마다 여전히 {per}',
      ja: 'キャッシュ {size}（{total} バイト）、1 位置あたりは変わらず {per}',
      zh: '缓存 {size}（{total} 字节），每个位置仍是 {per}',
      ar: 'الذاكرة المؤقتة {size} ({total} بايت)، ولا يزال كل موضع {per}',
      es: 'Caché {size} ({total} bytes), sigue siendo {per} por posición',
      fr: 'Cache {size} ({total} octets), toujours {per} par position',
      hi: 'कैश {size} ({total} बाइट), हर स्थान अब भी {per}',
      id: 'Cache {size} ({total} byte), tetap {per} per posisi',
      pt: 'Cache {size} ({total} bytes), ainda {per} por posição',
    },
    size: {
      en: '{value} {unit}',
      ko: '{value} {unit}',
      ja: '{value} {unit}',
      zh: '{value} {unit}',
      ar: '{value} {unit}',
      es: '{value} {unit}',
      fr: '{value} {unit}',
      hi: '{value} {unit}',
      id: '{value} {unit}',
      pt: '{value} {unit}',
    },
    'unit.B': {
      en: 'B', ko: 'B', ja: 'B', zh: 'B', ar: 'B', es: 'B', fr: 'o', hi: 'B', id: 'B', pt: 'B',
    },
    'unit.KiB': {
      en: 'KiB', ko: 'KiB', ja: 'KiB', zh: 'KiB', ar: 'KiB', es: 'KiB', fr: 'Kio', hi: 'KiB', id: 'KiB', pt: 'KiB',
    },
    'unit.MiB': {
      en: 'MiB', ko: 'MiB', ja: 'MiB', zh: 'MiB', ar: 'MiB', es: 'MiB', fr: 'Mio', hi: 'MiB', id: 'MiB', pt: 'MiB',
    },
    'unit.GiB': {
      en: 'GiB', ko: 'GiB', ja: 'GiB', zh: 'GiB', ar: 'GiB', es: 'GiB', fr: 'Gio', hi: 'GiB', id: 'GiB', pt: 'GiB',
    },
    'label.layerFirst': {
      en: 'layer 1',
      ko: '층 1',
      ja: '層 1',
      zh: '第 1 层',
      ar: 'الطبقة 1',
      es: 'capa 1',
      fr: 'couche 1',
      hi: 'परत 1',
      id: 'lapisan 1',
      pt: 'camada 1',
    },
    'label.layerLast': {
      en: 'layer {n}',
      ko: '층 {n}',
      ja: '層 {n}',
      zh: '第 {n} 层',
      ar: 'الطبقة {n}',
      es: 'capa {n}',
      fr: 'couche {n}',
      hi: 'परत {n}',
      id: 'lapisan {n}',
      pt: 'camada {n}',
    },
    'label.onePosition': {
      en: 'one position',
      ko: '자리 하나',
      ja: '1 位置',
      zh: '一个位置',
      ar: 'موضع واحد',
      es: 'una posición',
      fr: 'une position',
      hi: 'एक स्थान',
      id: 'satu posisi',
      pt: 'uma posição',
    },
    'label.k': {
      en: 'K', ko: 'K', ja: 'K', zh: 'K', ar: 'K', es: 'K', fr: 'K', hi: 'K', id: 'K', pt: 'K',
    },
    'label.v': {
      en: 'V', ko: 'V', ja: 'V', zh: 'V', ar: 'V', es: 'V', fr: 'V', hi: 'V', id: 'V', pt: 'V',
    },
    'label.positions': {
      en: 'positions',
      ko: '자리 수',
      ja: '位置数',
      zh: '位置数',
      ar: 'المواضع',
      es: 'posiciones',
      fr: 'positions',
      hi: 'स्थान',
      id: 'posisi',
      pt: 'posições',
    },
    'label.cache': {
      en: 'cache',
      ko: '캐시',
      ja: 'キャッシュ',
      zh: '缓存',
      ar: 'الذاكرة المؤقتة',
      es: 'caché',
      fr: 'cache',
      hi: 'कैश',
      id: 'cache',
      pt: 'cache',
    },
    'label.limit': {
      en: 'context limit {n}',
      ko: '문맥 한도 {n}',
      ja: '文脈の上限 {n}',
      zh: '上下文上限 {n}',
      ar: 'حدّ السياق {n}',
      es: 'límite de contexto {n}',
      fr: 'limite de contexte {n}',
      hi: 'संदर्भ सीमा {n}',
      id: 'batas konteks {n}',
      pt: 'limite de contexto {n}',
    },
  },
  blocks: {
    stage: { type: 'cache-keeps-growing-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
