/**
 * @piece 이 조각이 답하는 질문: `transform` 으로 상자를 움직이면, 이미 칠해 둔
 * 픽셀은 장마다 어떻게 되는가.
 * @notation native — 데이터의 코드 한 줄은 실제 CSS 선언(`transform: translateX(...)`)이다.
 */
import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const moveWithoutRepaintFacet: FacetJson = {
  id: 'facet:moveWithoutRepaint',
  title: {
    en: 'Move Without Repaint',
    ko: '다시 칠하지 않고 밀리기',
    ja: '再描画せずに動く',
    zh: '不重绘的移动',
    ar: 'التحريك دون إعادة الطلاء',
    es: 'Mover sin repintar',
    fr: 'Déplacer sans repeindre',
    hi: 'बिना दोबारा पेंट किए हिलाना',
    id: 'Bergerak tanpa mengecat ulang',
    pt: 'Mover sem repintar',
  },
  description: {
    en: 'A painted layer already sits ready; each frame only slides it and re-composites — paint count never rises.',
    ko: '이미 칠해 둔 장을 장마다 밀어 합성만 한다 — 칠한 횟수는 오르지 않는다.',
    ja: 'すでに描画された層を毎フレーム動かして合成するだけで、描画回数は増えない。',
    zh: '已绘制好的图层每帧只是被移动并重新合成——绘制次数不会增加。',
    ar: 'طبقة مرسومة مسبقًا يتم تحريكها فقط في كل إطار وإعادة تركيبها — عدد مرات الرسم لا يزداد.',
    es: 'Una capa ya pintada se desliza cada cuadro y solo se recompone — el número de pintados nunca sube.',
    fr: "Un calque déjà peint est simplement déplacé à chaque image et recomposé — le nombre de peintures n'augmente jamais.",
    hi: 'पहले से रंगी हुई परत हर फ्रेम में केवल खिसकाई और फिर से संयोजित की जाती है — रंगने की गिनती कभी नहीं बढ़ती।',
    id: 'Lapisan yang sudah dicat hanya digeser tiap bingkai dan disusun ulang — jumlah pengecatan tidak pernah naik.',
    pt: 'Uma camada já pintada é apenas deslizada a cada quadro e recomposta — a contagem de pinturas nunca sobe.',
  },
  algorithm: 'module:moveWithoutRepaint',
  scene: 'module:moveWithoutRepaintScene',
  initialData: {
    type: 'move-without-repaint',
    stepMs: 1400,
    frames: 6,
    perFramePx: 25,
    paintedCount: 1,
    layoutCount: 0,
    codeTemplate: 'transform: translateX({x}px);',
  },
  shuffleOnReset: false,
  messages: {
    'caption.init': {
      en: 'The box is already painted once (paint count {painted}) before the animation starts.',
      ko: '애니메이션이 시작되기 전, 상자는 이미 한 번 칠해졌다. 칠한 횟수 {painted}.',
      ja: 'アニメーションが始まる前から、この箱はすでに一度描画されている。描画回数 {painted}。',
      zh: '动画开始前，这个盒子已经被绘制过一次。绘制次数 {painted}。',
      ar: 'قبل بدء الرسوم المتحركة، تم رسم الصندوق بالفعل مرة واحدة. عدد مرات الرسم {painted}.',
      es: 'Antes de que empiece la animación, la caja ya está pintada una vez. Recuento de pintados {painted}.',
      fr: "Avant que l'animation ne commence, la boîte est déjà peinte une fois. Nombre de peintures {painted}.",
      hi: 'एनिमेशन शुरू होने से पहले, यह बॉक्स पहले ही एक बार रंगा जा चुका है। रंगने की गिनती {painted}।',
      id: 'Sebelum animasi dimulai, kotak ini sudah dicat sekali. Jumlah pengecatan {painted}.',
      pt: 'Antes de a animação começar, a caixa já está pintada uma vez. Contagem de pinturas {painted}.',
    },
    'caption.frame': {
      en: 'Frame {frame} — the same painted box slides to {x}px. Composite count {composites}.',
      ko: '{frame} 번째 장 — 같은 칠한 상자가 {x}px 로 밀린다. 합성 횟수 {composites}.',
      ja: 'フレーム {frame} — 同じ描画済みの箱が {x}px へ滑る。合成回数 {composites}。',
      zh: '第 {frame} 帧 — 同一个已绘制的盒子滑动到 {x}px。合成次数 {composites}。',
      ar: 'الإطار {frame} — نفس الصندوق المرسوم ينزلق إلى {x}px. عدد التركيب {composites}.',
      es: 'Cuadro {frame} — la misma caja pintada se desliza a {x}px. Recuento de composición {composites}.',
      fr: 'Image {frame} — la même boîte peinte glisse à {x}px. Nombre de compositions {composites}.',
      hi: 'फ्रेम {frame} — वही रंगा हुआ बॉक्स {x}px तक खिसकता है। संयोजन गिनती {composites}।',
      id: 'Bingkai {frame} — kotak yang sama yang sudah dicat bergeser ke {x}px. Jumlah komposit {composites}.',
      pt: 'Quadro {frame} — a mesma caixa pintada desliza para {x}px. Contagem de composição {composites}.',
    },
    'label.layer': {
      en: 'Painted layer',
      ko: '칠한 장',
      ja: '描画済みレイヤー',
      zh: '已绘制的图层',
      ar: 'الطبقة المرسومة',
      es: 'Capa pintada',
      fr: 'Calque peint',
      hi: 'रंगी हुई परत',
      id: 'Lapisan yang dicat',
      pt: 'Camada pintada',
    },
    'label.painted': {
      en: 'Paint count',
      ko: '칠한 횟수',
      ja: '描画回数',
      zh: '绘制次数',
      ar: 'عدد مرات الرسم',
      es: 'Recuento de pintados',
      fr: 'Nombre de peintures',
      hi: 'रंगने की गिनती',
      id: 'Jumlah pengecatan',
      pt: 'Contagem de pinturas',
    },
    'label.composites': {
      en: 'Composite count',
      ko: '합성 횟수',
      ja: '合成回数',
      zh: '合成次数',
      ar: 'عدد التركيب',
      es: 'Recuento de composición',
      fr: 'Nombre de compositions',
      hi: 'संयोजन गिनती',
      id: 'Jumlah komposit',
      pt: 'Contagem de composição',
    },
    'label.layout': {
      en: 'Layout count',
      ko: '레이아웃 횟수',
      ja: 'レイアウト回数',
      zh: '布局次数',
      ar: 'عدد التخطيط',
      es: 'Recuento de diseño',
      fr: 'Nombre de mises en page',
      hi: 'लेआउट गिनती',
      id: 'Jumlah tata letak',
      pt: 'Contagem de layout',
    },
    'label.declaration': {
      en: 'Declaration',
      ko: '선언',
      ja: '宣言',
      zh: '声明',
      ar: 'الإعلان',
      es: 'Declaración',
      fr: 'Déclaration',
      hi: 'घोषणा',
      id: 'Deklarasi',
      pt: 'Declaração',
    },
  },
  blocks: {
    stage: { type: 'move-without-repaint-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
