import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece 실행 계획은 어떤 차례로 줄을 만들어 내는가.
 * @notation native — SQL 자체가 주장의 소재다. SQL 문 · 연산자 이름 · 조건식은 EXPLAIN 표기 그대로 둔다.
 *
 * 표 · 줄 · 계획은 예로 정한 작은 자료다 (실제 데이터베이스의 EXPLAIN 이 아니다).
 */
export const planIsATreeFacet: FacetJson = {
  id: 'facet:planIsATree',
  title: {
    en: 'A plan is a tree: rows flow up',
    ko: '실행 계획은 나무다 — 줄이 위로 흘러 오른다',
    ja: '実行計画は木 — 行が下から上へ流れる',
    zh: '执行计划是一棵树——行自下而上流动',
    ar: 'خطة التنفيذ شجرة: تتدفق الصفوف إلى الأعلى',
    es: 'Un plan es un árbol: las filas suben',
    fr: 'Un plan est un arbre : les lignes remontent',
    hi: 'प्लान एक पेड़ है: पंक्तियाँ ऊपर बहती हैं',
    id: 'Rencana adalah pohon: baris mengalir ke atas',
    pt: 'Um plano é uma árvore: as linhas sobem',
  },
  description: {
    en: 'Rows leave the table scans one at a time and climb through each operator. The build side pools in the hash table first; filtered rows stop where they fail; only rows that reach the top become answers.',
    ko: '줄이 표 읽기에서 하나씩 나와 연산자를 차례로 거쳐 오른다. 짓는 쪽은 먼저 해시표에 고이고, 걸린 줄은 그 자리에서 멈추고, 끝까지 오른 줄만 답이 된다.',
    ja: '行はテーブル読み取りから一行ずつ出て、演算子を順に通って上る。ビルド側はまずハッシュ表にたまり、条件に落ちた行はその場で止まり、頂上まで届いた行だけが答えになる。',
    zh: '行从表扫描中逐一出发，依次穿过各个算子向上。构建侧先汇集到哈希表中；被过滤的行停在失败处；只有到达顶端的行才成为答案。',
    ar: 'تخرج الصفوف من مسح الجداول واحدًا تلو الآخر وتصعد عبر كل مُعامل. يتجمع جانب البناء في جدول التجزئة أولًا، وتتوقف الصفوف المرفوضة حيث تفشل، ولا يصبح جوابًا إلا ما يبلغ القمة.',
    es: 'Las filas salen de los recorridos de tabla de una en una y suben por cada operador. El lado de construcción se acumula primero en la tabla hash; las filas filtradas se detienen donde fallan; solo las que llegan arriba son respuesta.',
    fr: 'Les lignes quittent les lectures de table une à une et remontent à travers chaque opérateur. Le côté construction s’accumule d’abord dans la table de hachage ; les lignes filtrées s’arrêtent là où elles échouent ; seules celles qui atteignent le sommet deviennent des réponses.',
    hi: 'पंक्तियाँ टेबल स्कैन से एक-एक करके निकलती हैं और हर ऑपरेटर से होकर ऊपर चढ़ती हैं। बिल्ड पक्ष पहले हैश टेबल में जमा होता है; छँटी पंक्तियाँ वहीं रुक जाती हैं; केवल शिखर तक पहुँचने वाली पंक्तियाँ उत्तर बनती हैं।',
    id: 'Baris keluar dari pemindaian tabel satu per satu dan naik melewati tiap operator. Sisi build mengumpul dulu di tabel hash; baris yang gagal filter berhenti di sana; hanya yang sampai puncak menjadi jawaban.',
    pt: 'As linhas saem das leituras de tabela uma a uma e sobem por cada operador. O lado de construção se acumula primeiro na tabela hash; as linhas filtradas param onde falham; só as que chegam ao topo viram resposta.',
  },
  algorithm: 'module:planIsATree',
  scene: 'module:planIsATreeScene',
  initialData: {
    type: 'plan-is-a-tree',
    stepMs: 1100,
    sql: [
      'SELECT e.name, d.floor',
      'FROM emp e JOIN dept d ON e.dept_id = d.id',
      'WHERE e.salary > 5000',
    ],
    tables: {
      emp: {
        cols: ['id', 'name', 'dept_id', 'salary'],
        rows: [
          [1, 'Ana', 10, 6200],
          [2, 'Ben', 20, 4800],
          [3, 'Cho', 10, 5100],
          [4, 'Dev', 30, 7000],
          [5, 'Eli', 20, 3900],
        ],
      },
      dept: {
        cols: ['id', 'floor'],
        rows: [
          [10, 3],
          [20, 5],
          [30, 2],
        ],
      },
    },
    plan: {
      op: 'Project',
      cols: ['e.name', 'd.floor'],
      input: {
        op: 'Hash Join',
        on: { left: 'e.dept_id', right: 'd.id' },
        build: { op: 'Seq Scan', table: 'dept', alias: 'd' },
        probe: {
          op: 'Filter',
          cond: { col: 'e.salary', cmp: '>', value: 5000 },
          input: { op: 'Seq Scan', table: 'emp', alias: 'e' },
        },
      },
    },
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'The plan waits for its first row. Nothing has risen yet.',
      ko: '계획이 첫 줄을 기다린다. 아직 올라온 줄이 없다.',
      ja: '計画は最初の行を待っている。まだ何も上ってきていない。',
      zh: '计划在等待第一行。还没有任何行上来。',
      ar: 'تنتظر الخطة صفها الأول. لم يصعد شيء بعد.',
      es: 'El plan espera su primera fila. Todavía no ha subido nada.',
      fr: 'Le plan attend sa première ligne. Rien n’est encore monté.',
      hi: 'प्लान अपनी पहली पंक्ति की प्रतीक्षा में है। अभी कुछ ऊपर नहीं आया।',
      id: 'Rencana menunggu baris pertamanya. Belum ada yang naik.',
      pt: 'O plano espera sua primeira linha. Nada subiu ainda.',
    },
    'caption.stored': {
      en: 'The build side is read to the end first. {table} {label} rises and stays in the hash table. Stored rows: {n}',
      ko: '짓는 쪽을 먼저 끝까지 읽는다. {table} {label} 줄이 올라가 해시표에 고인다. 담긴 줄 수: {n}',
      ja: 'ビルド側を先に最後まで読む。{table} {label} の行が上ってハッシュ表にたまる。格納した行数: {n}',
      zh: '先把构建侧读到底。{table} {label} 这一行上升并留在哈希表中。已存行数：{n}',
      ar: 'يُقرأ جانب البناء حتى نهايته أولًا. يصعد الصف {table} {label} ويبقى في جدول التجزئة. الصفوف المخزنة: {n}',
      es: 'Primero se lee el lado de construcción hasta el final. La fila {table} {label} sube y se queda en la tabla hash. Filas guardadas: {n}',
      fr: 'Le côté construction est lu jusqu’au bout d’abord. La ligne {table} {label} monte et reste dans la table de hachage. Lignes stockées : {n}',
      hi: 'पहले बिल्ड पक्ष को अंत तक पढ़ा जाता है। पंक्ति {table} {label} ऊपर जाकर हैश टेबल में रुकती है। संग्रहीत पंक्तियाँ: {n}',
      id: 'Sisi build dibaca sampai habis lebih dulu. Baris {table} {label} naik dan tinggal di tabel hash. Baris tersimpan: {n}',
      pt: 'O lado de construção é lido até o fim primeiro. A linha {table} {label} sobe e fica na tabela hash. Linhas guardadas: {n}',
    },
    'caption.stopped': {
      en: '{table} {label} rises and stops at {op}: {col} {value} fails {cond}. Stopped rows: {n}',
      ko: '{table} {label} 줄이 올라가다 멈춘다 — 멈춘 자리: {op}, {col} {value}, 조건 {cond} 불만족. 멈춘 줄 수: {n}',
      ja: '{table} {label} の行は上る途中で止まる — 止まった所: {op}、{col} {value}、条件 {cond} を満たさない。止まった行数: {n}',
      zh: '{table} {label} 这一行上升后停下——停在：{op}，{col} {value}，不满足 {cond}。停下的行数：{n}',
      ar: 'يصعد الصف {table} {label} ثم يتوقف عند {op}: القيمة {col} {value} لا تحقق {cond}. الصفوف المتوقفة: {n}',
      es: 'La fila {table} {label} sube y se detiene en {op}: {col} {value} no cumple {cond}. Filas detenidas: {n}',
      fr: 'La ligne {table} {label} monte et s’arrête à {op} : {col} {value} ne vérifie pas {cond}. Lignes arrêtées : {n}',
      hi: 'पंक्ति {table} {label} ऊपर जाकर {op} पर रुकती है: {col} {value} शर्त {cond} पूरी नहीं करता। रुकी पंक्तियाँ: {n}',
      id: 'Baris {table} {label} naik lalu berhenti di {op}: {col} {value} tidak memenuhi {cond}. Baris berhenti: {n}',
      pt: 'A linha {table} {label} sobe e para em {op}: {col} {value} não satisfaz {cond}. Linhas paradas: {n}',
    },
    'caption.nomatch': {
      en: '{table} {label} rises and stops at {op}: the hash table has no match. Stopped rows: {n}',
      ko: '{table} {label} 줄이 올라가다 멈춘다 — 멈춘 자리: {op}, 해시표에 짝이 없다. 멈춘 줄 수: {n}',
      ja: '{table} {label} の行は上る途中で止まる — 止まった所: {op}、ハッシュ表に相手がない。止まった行数: {n}',
      zh: '{table} {label} 这一行上升后停下——停在：{op}，哈希表中没有匹配。停下的行数：{n}',
      ar: 'يصعد الصف {table} {label} ثم يتوقف عند {op}: لا مطابق في جدول التجزئة. الصفوف المتوقفة: {n}',
      es: 'La fila {table} {label} sube y se detiene en {op}: la tabla hash no tiene pareja. Filas detenidas: {n}',
      fr: 'La ligne {table} {label} monte et s’arrête à {op} : la table de hachage n’a pas de correspondance. Lignes arrêtées : {n}',
      hi: 'पंक्ति {table} {label} ऊपर जाकर {op} पर रुकती है: हैश टेबल में जोड़ी नहीं है। रुकी पंक्तियाँ: {n}',
      id: 'Baris {table} {label} naik lalu berhenti di {op}: tabel hash tidak punya pasangan. Baris berhenti: {n}',
      pt: 'A linha {table} {label} sobe e para em {op}: a tabela hash não tem par. Linhas paradas: {n}',
    },
    'caption.answer': {
      en: '{table} {label} rises all the way: {col} {value} meets {cond}, it pairs with {mtable} {mlabel} from the hash table, and becomes an answer. Answer rows: {n}',
      ko: '{table} {label} 줄이 끝까지 오른다 — {col} {value}, 조건 {cond} 만족. 해시표의 짝 {mtable} {mlabel}, 그리고 답. 답 줄 수: {n}',
      ja: '{table} {label} の行は頂上まで上る — {col} {value}、条件 {cond} を満たす。ハッシュ表の相手 {mtable} {mlabel} と組み、答えになる。答えの行数: {n}',
      zh: '{table} {label} 这一行一路上升——{col} {value}，满足 {cond}；与哈希表中的 {mtable} {mlabel} 配对，成为答案。答案行数：{n}',
      ar: 'يصعد الصف {table} {label} حتى القمة: القيمة {col} {value} تحقق {cond}، ويقترن بـ {mtable} {mlabel} من جدول التجزئة، ويصير جوابًا. صفوف الجواب: {n}',
      es: 'La fila {table} {label} sube hasta arriba: {col} {value} cumple {cond}, se empareja con {mtable} {mlabel} de la tabla hash y se vuelve respuesta. Filas de respuesta: {n}',
      fr: 'La ligne {table} {label} monte jusqu’en haut : {col} {value} vérifie {cond}, elle s’apparie avec {mtable} {mlabel} de la table de hachage et devient une réponse. Lignes de réponse : {n}',
      hi: 'पंक्ति {table} {label} शिखर तक चढ़ती है: {col} {value} शर्त {cond} पूरी करता है, हैश टेबल के {mtable} {mlabel} से जुड़ती है और उत्तर बनती है। उत्तर पंक्तियाँ: {n}',
      id: 'Baris {table} {label} naik sampai puncak: {col} {value} memenuhi {cond}, berpasangan dengan {mtable} {mlabel} dari tabel hash, dan menjadi jawaban. Baris jawaban: {n}',
      pt: 'A linha {table} {label} sobe até o topo: {col} {value} satisfaz {cond}, forma par com {mtable} {mlabel} da tabela hash e vira resposta. Linhas de resposta: {n}',
    },
    'caption.answerNoFilter': {
      en: '{table} {label} rises all the way: it pairs with {mtable} {mlabel} from the hash table and becomes an answer. Answer rows: {n}',
      ko: '{table} {label} 줄이 끝까지 오른다 — 해시표의 짝 {mtable} {mlabel}, 그리고 답. 답 줄 수: {n}',
      ja: '{table} {label} の行は頂上まで上る — ハッシュ表の相手 {mtable} {mlabel} と組み、答えになる。答えの行数: {n}',
      zh: '{table} {label} 这一行一路上升——与哈希表中的 {mtable} {mlabel} 配对，成为答案。答案行数：{n}',
      ar: 'يصعد الصف {table} {label} حتى القمة: يقترن بـ {mtable} {mlabel} من جدول التجزئة ويصير جوابًا. صفوف الجواب: {n}',
      es: 'La fila {table} {label} sube hasta arriba: se empareja con {mtable} {mlabel} de la tabla hash y se vuelve respuesta. Filas de respuesta: {n}',
      fr: 'La ligne {table} {label} monte jusqu’en haut : elle s’apparie avec {mtable} {mlabel} de la table de hachage et devient une réponse. Lignes de réponse : {n}',
      hi: 'पंक्ति {table} {label} शिखर तक चढ़ती है: हैश टेबल के {mtable} {mlabel} से जुड़ती है और उत्तर बनती है। उत्तर पंक्तियाँ: {n}',
      id: 'Baris {table} {label} naik sampai puncak: berpasangan dengan {mtable} {mlabel} dari tabel hash dan menjadi jawaban. Baris jawaban: {n}',
      pt: 'A linha {table} {label} sobe até o topo: forma par com {mtable} {mlabel} da tabela hash e vira resposta. Linhas de resposta: {n}',
    },
    'label.hash': {
      en: 'hash table',
      ko: '해시표',
      ja: 'ハッシュ表',
      zh: '哈希表',
      ar: 'جدول التجزئة',
      es: 'tabla hash',
      fr: 'table de hachage',
      hi: 'हैश टेबल',
      id: 'tabel hash',
      pt: 'tabela hash',
    },
    'label.answer': {
      en: 'answer',
      ko: '답',
      ja: '答え',
      zh: '答案',
      ar: 'الجواب',
      es: 'respuesta',
      fr: 'réponse',
      hi: 'उत्तर',
      id: 'jawaban',
      pt: 'resposta',
    },
    'label.build': {
      en: 'build',
      ko: '짓는 쪽',
      ja: 'ビルド側',
      zh: '构建侧',
      ar: 'البناء',
      es: 'construcción',
      fr: 'construction',
      hi: 'बिल्ड',
      id: 'build',
      pt: 'construção',
    },
    'label.probe': {
      en: 'probe',
      ko: '찔러보는 쪽',
      ja: 'プローブ側',
      zh: '探测侧',
      ar: 'الفحص',
      es: 'sondeo',
      fr: 'sondage',
      hi: 'प्रोब',
      id: 'probe',
      pt: 'sondagem',
    },
  },
  blocks: {
    stage: { type: 'plan-is-a-tree-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
