import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 표에서 줄 하나를 틀림없이 집어내려면 무엇으로 불러야 하는가.
 *
 * 부르는 값이 조건이 되어 표를 거른다. 이름이나 도시로 부르면 둘이 남고, 기본 키로 부르면 하나만 남는다.
 * 부를 때마다 표는 다시 모든 줄로 돌아온다.
 *
 * @notation native
 * 조건 글자는 SQL 비교식(`name = 'Kim'`)이다 — 관계 모델의 부르기를 SQL 그대로 보인다.
 */
export const primaryKeyIdentifiesFacet: FacetJson = {
  id: 'facet:primaryKeyIdentifies',
  title: {
    en: 'A primary key picks out one row',
    ko: '기본 키가 줄 하나를 집어낸다',
    ja: '主キーは行を一つだけ特定する',
    zh: '主键唯一地挑出一行',
    ar: 'المفتاح الأساسي يحدد صفًا واحدًا',
    es: 'La clave primaria señala una sola fila',
    fr: 'La clé primaire désigne une seule ligne',
    hi: 'प्राथमिक कुंजी एक ही पंक्ति चुनती है',
    id: 'Kunci primer menunjuk satu baris',
    pt: 'A chave primária aponta uma única linha',
  },
  description: {
    en: 'Call a row by name or by city and two rows remain; call it by the primary key and only one remains.',
    ko: '이름이나 도시로 부르면 두 줄이 남고, 기본 키로 부르면 한 줄만 남는다.',
    ja: '名前や都市で呼ぶと二行が残り、主キーで呼ぶと一行だけが残る。',
    zh: '按姓名或城市调用会剩下两行，按主键调用只剩一行。',
    ar: 'إذا استدعيت صفًا بالاسم أو بالمدينة يبقى صفان، وإذا استدعيته بالمفتاح الأساسي يبقى صف واحد فقط.',
    es: 'Si llamas a una fila por nombre o por ciudad quedan dos; si la llamas por la clave primaria queda solo una.',
    fr: "Appeler une ligne par le nom ou la ville en laisse deux ; l'appeler par la clé primaire n'en laisse qu'une.",
    hi: 'नाम या शहर से बुलाने पर दो पंक्तियाँ बचती हैं; प्राथमिक कुंजी से बुलाने पर केवल एक बचती है।',
    id: 'Memanggil baris dengan nama atau kota menyisakan dua baris; dengan kunci primer hanya satu yang tersisa.',
    pt: 'Chamar uma linha pelo nome ou pela cidade deixa duas; pela chave primária resta apenas uma.',
  },
  algorithm: 'module:primaryKeyIdentifies',
  scene: 'module:primaryKeyIdentifiesScene',
  initialData: {
    type: 'primary-key-identifies',
    stepMs: 2000,
    table: 'students',
    columns: ['student_id', 'name', 'city'],
    primaryKey: 'student_id',
    rows: [
      [101, 'Kim', 'Seoul'],
      [102, 'Lee', 'Busan'],
      [103, 'Kim', 'Busan'],
      [104, 'Park', 'Seoul'],
      [105, 'Choi', 'Daegu'],
    ],
    calls: [
      { column: 'name', value: 'Kim' },
      { column: 'city', value: 'Busan' },
      { column: 'student_id', value: 103 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.table': {
      en: 'Table {table} — rows: {n}.',
      ko: '표 {table} — 줄 수: {n}.',
      ja: '表 {table} — 行数: {n}。',
      zh: '表 {table} — 行数：{n}。',
      ar: 'الجدول {table} — عدد الصفوف: {n}.',
      es: 'Tabla {table} — filas: {n}.',
      fr: 'Table {table} — lignes : {n}.',
      hi: 'तालिका {table} — पंक्तियाँ: {n}।',
      id: 'Tabel {table} — jumlah baris: {n}.',
      pt: 'Tabela {table} — linhas: {n}.',
    },
    'caption.call': {
      en: 'Called by {column} — rows left: {left}.',
      ko: '부른 열: {column} — 남은 줄: {left}.',
      ja: '呼んだ列: {column} — 残った行: {left}。',
      zh: '按 {column} 调用 — 剩余行数：{left}。',
      ar: 'الاستدعاء بالعمود {column} — الصفوف المتبقية: {left}.',
      es: 'Llamada por {column} — filas restantes: {left}.',
      fr: 'Appel par {column} — lignes restantes : {left}.',
      hi: '{column} से बुलाया — बची पंक्तियाँ: {left}।',
      id: 'Dipanggil dengan {column} — baris tersisa: {left}.',
      pt: 'Chamada por {column} — linhas restantes: {left}.',
    },
    'caption.distinct': {
      en: 'Distinct values in {column}: {distinct} / {n}.',
      ko: '{column} 열의 서로 다른 값: {distinct} / {n}.',
      ja: '{column} 列の異なる値: {distinct} / {n}。',
      zh: '{column} 列的不同值：{distinct} / {n}。',
      ar: 'القيم المختلفة في {column}: {distinct} / {n}.',
      es: 'Valores distintos en {column}: {distinct} / {n}.',
      fr: 'Valeurs distinctes dans {column} : {distinct} / {n}.',
      hi: '{column} में अलग-अलग मान: {distinct} / {n}।',
      id: 'Nilai berbeda di {column}: {distinct} / {n}.',
      pt: 'Valores distintos em {column}: {distinct} / {n}.',
    },
    'label.pk': {
      en: 'primary key',
      ko: '기본 키',
      ja: '主キー',
      zh: '主键',
      ar: 'مفتاح أساسي',
      es: 'clave primaria',
      fr: 'clé primaire',
      hi: 'प्राथमिक कुंजी',
      id: 'kunci primer',
      pt: 'chave primária',
    },
    'label.out': {
      en: 'Filtered out',
      ko: '걸러져 빠진 줄',
      ja: '除かれた行',
      zh: '被筛掉的行',
      ar: 'صفوف مستبعدة',
      es: 'Filas descartadas',
      fr: 'Lignes écartées',
      hi: 'छँटी हुई पंक्तियाँ',
      id: 'Baris tersaring',
      pt: 'Linhas descartadas',
    },
    'label.calls': {
      en: 'Calls',
      ko: '부르기',
      ja: '呼び出し',
      zh: '调用',
      ar: 'الاستدعاءات',
      es: 'Llamadas',
      fr: 'Appels',
      hi: 'पुकारें',
      id: 'Panggilan',
      pt: 'Chamadas',
    },
    'label.left': {
      en: 'Rows left: {n}',
      ko: '남은 줄: {n}',
      ja: '残った行: {n}',
      zh: '剩余行：{n}',
      ar: 'الصفوف المتبقية: {n}',
      es: 'Filas restantes: {n}',
      fr: 'Lignes restantes : {n}',
      hi: 'बची पंक्तियाँ: {n}',
      id: 'Baris tersisa: {n}',
      pt: 'Linhas restantes: {n}',
    },
  },
  blocks: {
    stage: { type: 'primary-key-identifies-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
