/**
 * dropout — 뒤집은 드롭아웃의 출력 무리. 손잡이 둘: 쉴 확률 p · 되살림.
 *
 * initialData 는 1차 데이터뿐이다 — 칸 여섯의 h · v (조각 drop-random-units 와 같다), 뽑힌 수 u 마흔 벌
 * (sim.py `DO_U` 에서 옮겼다 — 한 번 뽑아 고정, 모든 p 에 같이 쓴다), 손잡이 사다리. 기댓값 · y · 평균 ·
 * 흩어짐 · 쉰 칸은 알고리즘이 셈한다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { DropoutData } from './algorithm.js';

export const DROPOUT_INITIAL: DropoutData = {
  type: 'dropout',
  stepMs: 1300,
  h: [0.8, 0.3, 0.6, 0.9, 0.2, 0.5],
  v: [0.5, -0.4, 0.7, 0.3, -0.6, 0.4],
  us: [
    [0.15, 0.97, 0.23, 0.51, 0.87, 0.68], [0.41, 0.07, 0.62, 0.33, 0.79, 0.94],
    [0.58, 0.21, 0.86, 0.04, 0.47, 0.72], [0.93, 0.64, 0.12, 0.77, 0.36, 0.28],
    [0.02, 0.43, 0.69, 0.91, 0.17, 0.56], [0.74, 0.88, 0.31, 0.19, 0.62, 0.09],
    [0.37, 0.53, 0.98, 0.66, 0.08, 0.44], [0.81, 0.14, 0.46, 0.27, 0.95, 0.61],
    [0.26, 0.71, 0.05, 0.84, 0.52, 0.39], [0.65, 0.32, 0.78, 0.49, 0.13, 0.99],
    [0.11, 0.59, 0.42, 0.96, 0.73, 0.22], [0.89, 0.06, 0.67, 0.35, 0.29, 0.83],
    [0.48, 0.92, 0.18, 0.61, 0.84, 0.03], [0.54, 0.38, 0.76, 0.12, 0.66, 0.47],
    [0.97, 0.24, 0.53, 0.71, 0.94, 0.58], [0.33, 0.79, 0.01, 0.44, 0.92, 0.16],
    [0.69, 0.46, 0.87, 0.23, 0.41, 0.74], [0.07, 0.63, 0.34, 0.82, 0.57, 0.91],
    [0.85, 0.19, 0.61, 0.06, 0.78, 0.37], [0.42, 0.86, 0.27, 0.59, 0.14, 0.68],
    [0.03, 0.02, 0.94, 0.38, 0.46, 0.21], [0.18, 0.57, 0.43, 0.89, 0.63, 0.81],
    [0.76, 0.41, 0.08, 0.64, 0.97, 0.29], [0.29, 0.93, 0.72, 0.17, 0.34, 0.52],
    [0.53, 0.16, 0.38, 0.93, 0.71, 0.06], [0.94, 0.68, 0.59, 0.42, 0.22, 0.87],
    [0.08, 0.34, 0.81, 0.73, 0.49, 0.64], [0.67, 0.77, 0.14, 0.28, 0.86, 0.43],
    [0.39, 0.12, 0.66, 0.54, 0.03, 0.96], [0.82, 0.49, 0.29, 0.07, 0.58, 0.34],
    [0.23, 0.84, 0.96, 0.62, 0.39, 0.11], [0.57, 0.27, 0.48, 0.86, 0.94, 0.63],
    [0.98, 0.61, 0.37, 0.14, 0.67, 0.49], [0.13, 0.45, 0.79, 0.99, 0.28, 0.72],
    [0.93, 0.73, 0.22, 0.36, 0.81, 0.18], [0.71, 0.09, 0.57, 0.69, 0.16, 0.92],
    [0.34, 0.96, 0.84, 0.21, 0.53, 0.38], [0.86, 0.36, 0.11, 0.47, 0.72, 0.57],
    [0.04, 0.52, 0.63, 0.79, 0.44, 0.27], [0.62, 0.81, 0.39, 0.02, 0.98, 0.76],
  ],
  batch: 5,
  dropRates: [0, 0.1, 0.4, 0.7],
  rescales: [1, 0],
  defaultDropRate: 0.4,
  defaultRescale: 1,
};

export const dropoutFacet: FacetJson = {
  id: 'facet:dropout',
  title: {
    en: 'Dropout',
    ko: '드롭아웃',
    ja: 'ドロップアウト',
    zh: 'Dropout 随机失活',
    ar: 'الإسقاط العشوائي (Dropout)',
    es: 'Dropout',
    fr: 'Dropout',
    hi: 'ड्रॉपआउट',
    id: 'Dropout',
    pt: 'Dropout',
  },
  description: {
    en: 'Each mask switches off some of six hidden units with drop rate p, and the units left on make up for them by dividing by (1 − p). Forty masks give forty outputs that fall one by one onto an axis. With rescaling on, raising p spreads the cloud while its expected value stays at the all-on output; with rescaling off, the expected value is (1 − p) times the all-on output. The sample mean of the forty masks is shown apart from the expected value.',
    ko: '마스크마다 은닉 칸 여섯 가운데 몇 칸이 쉴 확률 p 로 쉬고, 켜진 칸이 (1 − p) 로 나눠 그 몫을 메운다. 마스크 마흔 벌이 출력 마흔 개를 내고, 출력은 한 점씩 축 위에 떨어져 쌓인다. 되살림을 켜면 p 를 올릴수록 무리가 퍼지고 기댓값은 모두 켠 출력에 머문다. 되살림을 끄면 기댓값이 모두 켠 출력의 (1 − p) 배가 된다. 마흔 벌의 표본 평균은 기댓값과 따로 보인다.',
    ja: 'マスクごとに、6 つの隠れユニットのうちいくつかがドロップ率 p で休み、残ったユニットが (1 − p) で割ってその分を埋める。40 枚のマスクが 40 個の出力を出し、出力は一点ずつ軸の上に落ちて積もる。再スケールをオンにすると、p を上げるほど群れは広がり、期待値はすべてオンの出力にとどまる。オフにすると期待値はすべてオンの出力の (1 − p) 倍になる。40 枚の標本平均は期待値とは別に示す。',
    zh: '每个掩码以丢弃率 p 关掉六个隐藏单元中的几个，留下的单元除以 (1 − p) 来补上它们的份额。四十个掩码给出四十个输出，一个个落到轴上堆起来。开启重新缩放时，p 越大点群越散开，而期望值停在全部开启时的输出上；关闭时，期望值变为全部开启输出的 (1 − p) 倍。四十个掩码的样本均值与期望值分开显示。',
    ar: 'في كل قناع تتوقف بعض الوحدات الست المخفية باحتمال إسقاط p، وتعوّضها الوحدات الباقية بالقسمة على (1 − p). تعطي أربعون قناعًا أربعين مخرجًا تسقط واحدًا تلو الآخر على محور. مع تشغيل إعادة القياس، كلما رفعت p اتسعت السحابة وبقيت قيمتها المتوقعة عند مخرج جميع الوحدات؛ ومع إيقافها تصبح القيمة المتوقعة (1 − p) من مخرج جميع الوحدات. يظهر متوسط العينة للأقنعة الأربعين منفصلًا عن القيمة المتوقعة.',
    es: 'Cada máscara apaga algunas de seis unidades ocultas con tasa de descarte p, y las que quedan encendidas compensan dividiendo entre (1 − p). Cuarenta máscaras dan cuarenta salidas que caen una a una sobre un eje. Con el reescalado activado, al subir p la nube se abre y su valor esperado se queda en la salida con todo encendido; con el reescalado apagado, el valor esperado es (1 − p) veces esa salida. La media muestral de las cuarenta máscaras se muestra aparte del valor esperado.',
    fr: 'Chaque masque éteint quelques-unes des six unités cachées avec un taux d’abandon p, et les unités restées allumées compensent en divisant par (1 − p). Quarante masques donnent quarante sorties qui tombent une à une sur un axe. Avec la remise à l’échelle, augmenter p élargit le nuage tandis que sa valeur attendue reste à la sortie tout allumé ; sans elle, la valeur attendue vaut (1 − p) fois cette sortie. La moyenne des quarante masques est montrée à part de la valeur attendue.',
    hi: 'हर मास्क में छह छिपी इकाइयों में से कुछ ड्रॉप दर p से बंद होती हैं, और चालू इकाइयाँ (1 − p) से भाग देकर उनकी कमी पूरी करती हैं। चालीस मास्क चालीस आउटपुट देते हैं जो एक-एक कर अक्ष पर गिरते हैं। पुनःस्केल चालू हो तो p बढ़ाने पर बादल फैलता है और उसका अपेक्षित मान सब-चालू आउटपुट पर टिका रहता है; बंद हो तो अपेक्षित मान सब-चालू आउटपुट का (1 − p) गुना होता है। चालीस मास्क का नमूना माध्य अपेक्षित मान से अलग दिखाया जाता है।',
    id: 'Setiap masker mematikan beberapa dari enam unit tersembunyi dengan laju putus p, dan unit yang tetap menyala menutupinya dengan membagi (1 − p). Empat puluh masker memberi empat puluh keluaran yang jatuh satu per satu ke sebuah sumbu. Dengan skala ulang menyala, menaikkan p melebarkan awan sementara nilai harapannya tetap di keluaran semua-menyala; tanpa skala ulang, nilai harapan menjadi (1 − p) kali keluaran itu. Rata-rata sampel empat puluh masker ditampilkan terpisah dari nilai harapan.',
    pt: 'Cada máscara desliga algumas de seis unidades ocultas com taxa de descarte p, e as que ficam ligadas compensam dividindo por (1 − p). Quarenta máscaras dão quarenta saídas que caem uma a uma sobre um eixo. Com o reescalonamento ligado, subir p abre a nuvem enquanto o valor esperado fica na saída com tudo ligado; desligado, o valor esperado é (1 − p) vezes essa saída. A média amostral das quarenta máscaras aparece à parte do valor esperado.',
  },
  algorithm: 'module:dropout',
  projector: 'module:dropoutProjector',
  initialData: DROPOUT_INITIAL,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'dropout-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'dropRate',
          name: 'dropRate',
          label: {
            en: 'Drop rate p',
            ko: '쉴 확률 p',
            ja: 'ドロップ率 p',
            zh: '丢弃率 p',
            ar: 'معدل الإسقاط p',
            es: 'Tasa de descarte p',
            fr: 'Taux d’abandon p',
            hi: 'ड्रॉप दर p',
            id: 'Laju putus p',
            pt: 'Taxa de descarte p',
          },
          segments: [
            { value: 0, label: '0' },
            { value: 0.1, label: '0.1' },
            { value: 0.4, label: '0.4', default: true },
            { value: 0.7, label: '0.7' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'rescale',
          name: 'rescale',
          label: {
            en: 'Rescale',
            ko: '되살림',
            ja: '再スケール',
            zh: '重新缩放',
            ar: 'إعادة القياس',
            es: 'Reescalar',
            fr: 'Remise à l’échelle',
            hi: 'पुनःस्केल',
            id: 'Skala ulang',
            pt: 'Reescalar',
          },
          segments: [
            {
              value: 1,
              label: { en: 'On', ko: '켬', ja: 'オン', zh: '开', ar: 'تشغيل', es: 'Sí', fr: 'Oui', hi: 'चालू', id: 'Nyala', pt: 'Sim' },
              default: true,
            },
            {
              value: 0,
              label: { en: 'Off', ko: '끔', ja: 'オフ', zh: '关', ar: 'إيقاف', es: 'No', fr: 'Non', hi: 'बंद', id: 'Mati', pt: 'Não' },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'masks',
          label: { en: 'Masks', ko: '마스크', ja: 'マスク', zh: '掩码', ar: 'الأقنعة', es: 'Máscaras', fr: 'Masques', hi: 'मास्क', id: 'Masker', pt: 'Máscaras' },
          initial: 0,
        },
        {
          name: 'units-off',
          label: {
            en: 'Units dropped',
            ko: '쉰 칸',
            ja: '休んだユニット',
            zh: '丢弃的单元',
            ar: 'الوحدات المُسقطة',
            es: 'Unidades apagadas',
            fr: 'Unités éteintes',
            hi: 'बंद इकाइयाँ',
            id: 'Unit dimatikan',
            pt: 'Unidades desligadas',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:dropout-imperative',
      label: {
        en: 'Dropout: outputs, mean, spread',
        ko: '드롭아웃: 출력 · 평균 · 흩어짐',
        ja: 'ドロップアウト: 出力・平均・ばらつき',
        zh: 'Dropout：输出、均值、离散',
        ar: 'الإسقاط: المخرجات والمتوسط والتشتت',
        es: 'Dropout: salidas, media, dispersión',
        fr: 'Dropout : sorties, moyenne, dispersion',
        hi: 'ड्रॉपआउट: आउटपुट, माध्य, फैलाव',
        id: 'Dropout: keluaran, rata-rata, sebaran',
        pt: 'Dropout: saídas, média, dispersão',
      },
    },
  },
  messages: {
    'caption.allOn': {
      en: 'All units on: y = {y}. Expected value {e}',
      ko: '모든 칸 켬: y = {y}. 기댓값 {e}',
      ja: 'すべてのユニットがオン: y = {y}。期待値 {e}',
      zh: '所有单元开启：y = {y}。期望值 {e}',
      ar: 'كل الوحدات تعمل: y = {y}. القيمة المتوقعة {e}',
      es: 'Todas las unidades encendidas: y = {y}. Valor esperado {e}',
      fr: 'Toutes les unités allumées : y = {y}. Valeur attendue {e}',
      hi: 'सभी इकाइयाँ चालू: y = {y}। अपेक्षित मान {e}',
      id: 'Semua unit menyala: y = {y}. Nilai harapan {e}',
      pt: 'Todas as unidades ligadas: y = {y}. Valor esperado {e}',
    },
    'caption.masks': {
      en: 'Masks #{from}–#{to}: y {ys}. Units dropped so far: {off}',
      ko: '마스크 #{from}–#{to}: y {ys}. 지금까지 쉰 칸: {off}',
      ja: 'マスク #{from}–#{to}: y {ys}。これまでに休んだユニット: {off}',
      zh: '掩码 #{from}–#{to}：y {ys}。至今丢弃的单元：{off}',
      ar: 'الأقنعة #{from}–#{to}: y {ys}. الوحدات المُسقطة حتى الآن: {off}',
      es: 'Máscaras #{from}–#{to}: y {ys}. Unidades apagadas hasta ahora: {off}',
      fr: 'Masques #{from}–#{to} : y {ys}. Unités éteintes jusqu’ici : {off}',
      hi: 'मास्क #{from}–#{to}: y {ys}। अब तक बंद इकाइयाँ: {off}',
      id: 'Masker #{from}–#{to}: y {ys}. Unit dimatikan sejauh ini: {off}',
      pt: 'Máscaras #{from}–#{to}: y {ys}. Unidades desligadas até agora: {off}',
    },
    'caption.summary': {
      en: 'Sample mean {m}, spread {sd}. Expected value {e}. Dropped share {pct}%',
      ko: '표본 평균 {m} · 흩어짐 {sd}. 기댓값 {e}. 쉰 몫 {pct}%',
      ja: '標本平均 {m}、ばらつき {sd}。期待値 {e}。休んだ割合 {pct}%',
      zh: '样本均值 {m}，离散 {sd}。期望值 {e}。丢弃比例 {pct}%',
      ar: 'متوسط العينة {m}، التشتت {sd}. القيمة المتوقعة {e}. نسبة المُسقط {pct}%',
      es: 'Media muestral {m}, dispersión {sd}. Valor esperado {e}. Parte apagada {pct}%',
      fr: 'Moyenne observée {m}, dispersion {sd}. Valeur attendue {e}. Part éteinte {pct}%',
      hi: 'नमूना माध्य {m}, फैलाव {sd}। अपेक्षित मान {e}। बंद हिस्सा {pct}%',
      id: 'Rata-rata sampel {m}, sebaran {sd}. Nilai harapan {e}. Bagian dimatikan {pct}%',
      pt: 'Média amostral {m}, dispersão {sd}. Valor esperado {e}. Parte desligada {pct}%',
    },
    'formula.allOn': {
      en: 'y = Σ hᵢ·vᵢ',
      ko: 'y = Σ hᵢ·vᵢ',
      ja: 'y = Σ hᵢ·vᵢ',
      zh: 'y = Σ hᵢ·vᵢ',
      ar: 'y = Σ hᵢ·vᵢ',
      es: 'y = Σ hᵢ·vᵢ',
      fr: 'y = Σ hᵢ·vᵢ',
      hi: 'y = Σ hᵢ·vᵢ',
      id: 'y = Σ hᵢ·vᵢ',
      pt: 'y = Σ hᵢ·vᵢ',
    },
    'formula.rescale': {
      en: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      ko: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      ja: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      zh: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      ar: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      es: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      fr: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      hi: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      id: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
      pt: 'y = Σ mᵢ·hᵢ·vᵢ / (1 − p),   p = {p}',
    },
    'formula.plain': {
      en: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      ko: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      ja: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      zh: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      ar: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      es: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      fr: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      hi: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      id: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
      pt: 'y = Σ mᵢ·hᵢ·vᵢ,   p = {p}',
    },
    'label.cells': {
      en: 'Units and their shares',
      ko: '칸과 칸의 몫',
      ja: 'ユニットとその取り分',
      zh: '单元及其份额',
      ar: 'الوحدات وحصصها',
      es: 'Unidades y su parte',
      fr: 'Unités et leur part',
      hi: 'इकाइयाँ और उनका हिस्सा',
      id: 'Unit dan bagiannya',
      pt: 'Unidades e sua parte',
    },
    'label.off': {
      en: 'off',
      ko: '쉼',
      ja: '休み',
      zh: '关',
      ar: 'متوقفة',
      es: 'apagada',
      fr: 'éteinte',
      hi: 'बंद',
      id: 'mati',
      pt: 'desligada',
    },
    'label.mask': {
      en: 'Mask #{k}',
      ko: '마스크 #{k}',
      ja: 'マスク #{k}',
      zh: '掩码 #{k}',
      ar: 'القناع #{k}',
      es: 'Máscara #{k}',
      fr: 'Masque #{k}',
      hi: 'मास्क #{k}',
      id: 'Masker #{k}',
      pt: 'Máscara #{k}',
    },
    'label.output': {
      en: 'Output y',
      ko: '출력 y',
      ja: '出力 y',
      zh: '输出 y',
      ar: 'المخرج y',
      es: 'Salida y',
      fr: 'Sortie y',
      hi: 'आउटपुट y',
      id: 'Keluaran y',
      pt: 'Saída y',
    },
    'label.cloud': {
      en: 'Outputs, one dot per mask',
      ko: '마스크마다 출력 한 점',
      ja: 'マスクごとに出力を一点',
      zh: '每个掩码一个输出点',
      ar: 'المخرجات، نقطة لكل قناع',
      es: 'Salidas, un punto por máscara',
      fr: 'Sorties, un point par masque',
      hi: 'आउटपुट, हर मास्क का एक बिंदु',
      id: 'Keluaran, satu titik per masker',
      pt: 'Saídas, um ponto por máscara',
    },
    'label.allOn': {
      en: 'All-on output',
      ko: '모두 켠 값',
      ja: 'すべてオンの出力',
      zh: '全部开启的输出',
      ar: 'مخرج كل الوحدات',
      es: 'Salida con todo encendido',
      fr: 'Sortie tout allumé',
      hi: 'सब-चालू आउटपुट',
      id: 'Keluaran semua menyala',
      pt: 'Saída com tudo ligado',
    },
    'label.expected': {
      en: 'Expected value',
      ko: '기댓값',
      ja: '期待値',
      zh: '期望值',
      ar: 'القيمة المتوقعة',
      es: 'Valor esperado',
      fr: 'Valeur attendue',
      hi: 'अपेक्षित मान',
      id: 'Nilai harapan',
      pt: 'Valor esperado',
    },
    'label.mean': {
      en: 'Sample mean',
      ko: '표본 평균',
      ja: '標本平均',
      zh: '样本均值',
      ar: 'متوسط العينة',
      es: 'Media muestral',
      fr: 'Moyenne observée',
      hi: 'नमूना माध्य',
      id: 'Rata-rata sampel',
      pt: 'Média amostral',
    },
    'label.spread': {
      en: 'Spread (sd)',
      ko: '흩어짐 (sd)',
      ja: 'ばらつき (sd)',
      zh: '离散 (sd)',
      ar: 'التشتت (sd)',
      es: 'Dispersión (sd)',
      fr: 'Dispersion (sd)',
      hi: 'फैलाव (sd)',
      id: 'Sebaran (sd)',
      pt: 'Dispersão (sd)',
    },
    'label.dropShare': {
      en: 'Dropped share',
      ko: '쉰 몫',
      ja: '休んだ割合',
      zh: '丢弃比例',
      ar: 'نسبة المُسقط',
      es: 'Parte apagada',
      fr: 'Part éteinte',
      hi: 'बंद हिस्सा',
      id: 'Bagian dimatikan',
      pt: 'Parte desligada',
    },
    'tag.allOn': {
      en: 'all on {v}',
      ko: '모두 켬 {v}',
      ja: 'すべてオン {v}',
      zh: '全开 {v}',
      ar: 'الكل يعمل {v}',
      es: 'todo encendido {v}',
      fr: 'tout allumé {v}',
      hi: 'सब चालू {v}',
      id: 'semua nyala {v}',
      pt: 'tudo ligado {v}',
    },
    'tag.expected': {
      en: 'expected {v}',
      ko: '기댓값 {v}',
      ja: '期待値 {v}',
      zh: '期望值 {v}',
      ar: 'المتوقعة {v}',
      es: 'esperado {v}',
      fr: 'attendue {v}',
      hi: 'अपेक्षित {v}',
      id: 'harapan {v}',
      pt: 'esperado {v}',
    },
    'tag.mean': {
      en: 'sample mean {v}',
      ko: '표본 평균 {v}',
      ja: '標本平均 {v}',
      zh: '样本均值 {v}',
      ar: 'متوسط العينة {v}',
      es: 'media muestral {v}',
      fr: 'moyenne observée {v}',
      hi: 'नमूना माध्य {v}',
      id: 'rata-rata sampel {v}',
      pt: 'média amostral {v}',
    },
  },
};
