import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 몸 안에서 `let` 한 이름은 몸을 벗어난 뒤에도 쓸 수 있는가.
 *
 * 흐름이 `if` 의 몸을 벗어나는 순간 몸 안에서 선 `discount` 가 자리째 걷힌다. 몸 안에서 그 값을
 * 받아 바뀐 바깥 `price` 만 남고, 뒤의 줄이 `discount` 를 부르면 찾을 이름이 없어 거기서 멈춘다.
 */
export const scopeExitFacet: FacetJson = {
  id: 'facet:scopeExit',
  title: {
    en: 'A name declared in a body goes away with it',
    ko: '몸 안에서 만든 이름은 몸과 함께 걷힌다',
    ja: 'ブロックの中で宣言した名前はブロックと一緒に消える',
    zh: '在代码块里声明的名字随代码块一起消失',
    ar: 'الاسم المُعلن داخل الكتلة يزول معها',
    es: 'Un nombre declarado en un bloque desaparece con él',
    fr: 'Un nom déclaré dans un bloc disparaît avec lui',
    hi: 'ब्लॉक के भीतर घोषित नाम ब्लॉक के साथ ही हट जाता है',
    id: 'Nama yang dideklarasikan di dalam blok lenyap bersama bloknya',
    pt: 'Um nome declarado dentro de um bloco some junto com ele',
  },
  description: {
    en: 'When flow leaves the body of an if, the name declared inside it is cleared away along with its slot. A later line that calls that name finds nothing, and the program stops there.',
    ko: '흐름이 if 의 몸을 벗어나면 몸 안에서 선언한 이름이 자리째 걷힌다. 뒤의 줄이 그 이름을 부르면 찾을 곳이 없어 프로그램이 거기서 멈춘다.',
    ja: '流れが if のブロックを抜けると、その中で宣言した名前は置き場所ごと片付けられる。後の行がその名前を呼んでも見つからず、プログラムはそこで止まる。',
    zh: '流程离开 if 的代码块时，块内声明的名字连同它的位置一起被清走。后面的行再叫这个名字就找不到，程序在那里停下。',
    ar: 'حين يغادر التدفق جسم if يُزال الاسم المُعلن بداخله مع موضعه. وإذا نادى سطر لاحق ذلك الاسم لم يجده، فيتوقف البرنامج هناك.',
    es: 'Cuando el flujo sale del cuerpo de un if, el nombre declarado dentro se retira junto con su casilla. Una línea posterior que lo llama no encuentra nada y el programa se detiene ahí.',
    fr: 'Quand le flux quitte le corps d’un if, le nom déclaré à l’intérieur est retiré avec sa case. Une ligne suivante qui l’appelle ne trouve rien, et le programme s’arrête là.',
    hi: 'जब प्रवाह if के भीतरी भाग से बाहर निकलता है, तो भीतर घोषित नाम अपनी जगह समेत हटा दिया जाता है। बाद की पंक्ति उस नाम को पुकारे तो कुछ नहीं मिलता और प्रोग्राम वहीं रुक जाता है।',
    id: 'Saat alur keluar dari badan if, nama yang dideklarasikan di dalamnya disingkirkan bersama tempatnya. Baris berikutnya yang memanggil nama itu tidak menemukan apa pun, dan program berhenti di sana.',
    pt: 'Quando o fluxo sai do corpo de um if, o nome declarado dentro dele é retirado junto com sua casa. Uma linha posterior que chama esse nome não encontra nada, e o programa para ali.',
  },
  algorithm: 'module:scopeExit',
  scene: 'module:scopeExitScene',
  initialData: {
    type: 'scope-exit',
    stepMs: 1600,
    lines: [
      {
        indent: 0,
        text: 'let price = 40',
        stmt: { k: 'assign', to: 'price', value: { num: 40 }, declare: true },
      },
      {
        indent: 0,
        text: 'if price > 30',
        stmt: { k: 'if', cond: { op: '>', l: { var: 'price' }, r: { num: 30 } } },
      },
      {
        indent: 1,
        text: 'let discount = 5',
        stmt: { k: 'assign', to: 'discount', value: { num: 5 }, declare: true },
      },
      {
        indent: 1,
        text: 'price = price - discount',
        stmt: { k: 'assign', to: 'price', value: { op: '-', l: { var: 'price' }, r: { var: 'discount' } } },
      },
      {
        indent: 0,
        text: 'show price',
        stmt: { k: 'show', value: { var: 'price' } },
      },
      {
        indent: 0,
        text: 'show discount',
        stmt: { k: 'show', value: { var: 'discount' } },
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Lines: {n}. No line has run yet.',
      ko: '줄 수: {n}. 아직 아무 줄도 실행하지 않았다.',
      ja: '行数: {n}。まだどの行も実行していない。',
      zh: '行数：{n}。还没有执行任何一行。',
      ar: 'عدد الأسطر: {n}. لم يُنفَّذ أي سطر بعد.',
      es: 'Líneas: {n}. Aún no se ha ejecutado ninguna.',
      fr: 'Lignes : {n}. Aucune ligne n’a encore été exécutée.',
      hi: 'पंक्तियाँ: {n}। अभी कोई पंक्ति नहीं चली है।',
      id: 'Jumlah baris: {n}. Belum ada baris yang dijalankan.',
      pt: 'Linhas: {n}. Nenhuma linha foi executada ainda.',
    },
    'caption.declare': {
      en: 'A new slot opens: {name}, holding {value}.',
      ko: '새 자리가 선다 — {name}, 값 {value}.',
      ja: '新しい置き場所ができる — {name}、値 {value}。',
      zh: '开出一个新位置 — {name}，值 {value}。',
      ar: 'يُفتح موضع جديد: {name}، وفيه {value}.',
      es: 'Se abre una casilla nueva: {name}, con {value}.',
      fr: 'Une nouvelle case s’ouvre : {name}, qui contient {value}.',
      hi: 'एक नई जगह बनती है: {name}, मान {value}।',
      id: 'Tempat baru dibuka: {name}, berisi {value}.',
      pt: 'Abre-se uma casa nova: {name}, com {value}.',
    },
    'caption.declareBody': {
      en: 'Inside the body, a new slot opens: {name}, holding {value}.',
      ko: '몸 안에서 새 자리가 선다 — {name}, 값 {value}.',
      ja: 'ブロックの中で新しい置き場所ができる — {name}、値 {value}。',
      zh: '在代码块里开出一个新位置 — {name}，值 {value}。',
      ar: 'داخل الجسم يُفتح موضع جديد: {name}، وفيه {value}.',
      es: 'Dentro del cuerpo se abre una casilla nueva: {name}, con {value}.',
      fr: 'Dans le corps, une nouvelle case s’ouvre : {name}, qui contient {value}.',
      hi: 'भीतरी भाग में एक नई जगह बनती है: {name}, मान {value}।',
      id: 'Di dalam badan, tempat baru dibuka: {name}, berisi {value}.',
      pt: 'Dentro do corpo, abre-se uma casa nova: {name}, com {value}.',
    },
    'caption.assign': {
      en: '{name}: {was} → {value}.',
      ko: '{name}: {was} → {value}.',
      ja: '{name}: {was} → {value}。',
      zh: '{name}：{was} → {value}。',
      ar: '{name}: {was} ← {value}.',
      es: '{name}: {was} → {value}.',
      fr: '{name} : {was} → {value}.',
      hi: '{name}: {was} → {value}।',
      id: '{name}: {was} → {value}.',
      pt: '{name}: {was} → {value}.',
    },
    'caption.assignRead': {
      en: '{name}: {was} → {value}. It took the value of {read}.',
      ko: '{name}: {was} → {value}. {read} 의 값을 받았다.',
      ja: '{name}: {was} → {value}。{read} の値を受け取った。',
      zh: '{name}：{was} → {value}。用上了 {read} 的值。',
      ar: '{name}: {was} ← {value}. أخذ قيمة {read}.',
      es: '{name}: {was} → {value}. Tomó el valor de {read}.',
      fr: '{name} : {was} → {value}. Il a pris la valeur de {read}.',
      hi: '{name}: {was} → {value}। इसने {read} का मान लिया।',
      id: '{name}: {was} → {value}. Ia mengambil nilai {read}.',
      pt: '{name}: {was} → {value}. Recebeu o valor de {read}.',
    },
    'caption.branchTrue': {
      en: '{l} {op} {r} is true. Flow enters the body, and the body opens.',
      ko: '{l} {op} {r} — 참. 흐름이 몸으로 들어가고 몸이 열린다.',
      ja: '{l} {op} {r} — 真。流れがブロックに入り、ブロックが開く。',
      zh: '{l} {op} {r} — 真。流程进入代码块，代码块打开。',
      ar: '{l} {op} {r} صحيح. يدخل التدفق الجسم، فيُفتح الجسم.',
      es: '{l} {op} {r} es verdadero. El flujo entra en el cuerpo y el cuerpo se abre.',
      fr: '{l} {op} {r} est vrai. Le flux entre dans le corps, et le corps s’ouvre.',
      hi: '{l} {op} {r} सत्य है। प्रवाह भीतरी भाग में जाता है और भीतरी भाग खुलता है।',
      id: '{l} {op} {r} benar. Alur masuk ke badan, dan badan terbuka.',
      pt: '{l} {op} {r} é verdadeiro. O fluxo entra no corpo, e o corpo se abre.',
    },
    'caption.branchFalse': {
      en: '{l} {op} {r} is false. Flow skips the body.',
      ko: '{l} {op} {r} — 거짓. 흐름이 몸을 건너뛴다.',
      ja: '{l} {op} {r} — 偽。流れはブロックを飛ばす。',
      zh: '{l} {op} {r} — 假。流程跳过代码块。',
      ar: '{l} {op} {r} خطأ. يتخطى التدفق الجسم.',
      es: '{l} {op} {r} es falso. El flujo salta el cuerpo.',
      fr: '{l} {op} {r} est faux. Le flux saute le corps.',
      hi: '{l} {op} {r} असत्य है। प्रवाह भीतरी भाग को छोड़ देता है।',
      id: '{l} {op} {r} salah. Alur melewati badan.',
      pt: '{l} {op} {r} é falso. O fluxo pula o corpo.',
    },
    'caption.exit': {
      en: 'Flow leaves the body. The body is cleared away, taking {names} with it — name and slot.',
      ko: '흐름이 몸을 벗어난다. 몸이 걷히며 함께 사라진 것: {names} — 이름도 자리도.',
      ja: '流れがブロックを抜ける。ブロックが片付けられ、一緒に消えたもの: {names} — 名前も置き場所も。',
      zh: '流程离开代码块。代码块被清走，一起消失的是：{names} — 名字和位置都没了。',
      ar: 'يغادر التدفق الجسم. يُزال الجسم ويأخذ معه {names} — الاسم والموضع معًا.',
      es: 'El flujo sale del cuerpo. El cuerpo se retira y se lleva {names} — nombre y casilla.',
      fr: 'Le flux quitte le corps. Le corps est retiré et emporte {names} — le nom comme la case.',
      hi: 'प्रवाह भीतरी भाग से बाहर निकलता है। भीतरी भाग हट जाता है और साथ ले जाता है: {names} — नाम भी, जगह भी।',
      id: 'Alur keluar dari badan. Badan disingkirkan dan ikut membawa {names} — nama beserta tempatnya.',
      pt: 'O fluxo sai do corpo. O corpo é retirado e leva {names} junto — nome e casa.',
    },
    'caption.show': {
      en: 'Shows {value}.',
      ko: '내보낸 값: {value}.',
      ja: '表示した値: {value}。',
      zh: '显示的值：{value}。',
      ar: 'يعرض {value}.',
      es: 'Muestra {value}.',
      fr: 'Affiche {value}.',
      hi: 'दिखाया गया मान: {value}।',
      id: 'Menampilkan {value}.',
      pt: 'Mostra {value}.',
    },
    'caption.unknown': {
      en: 'No name {name} to be found anywhere. The program stops here.',
      ko: '{name} — 찾아갈 이름이 어디에도 없다. 프로그램이 여기서 멈춘다.',
      ja: '{name} — 探しに行ける名前がどこにもない。プログラムはここで止まる。',
      zh: '{name} — 哪里都找不到这个名字。程序在这里停下。',
      ar: 'لا يوجد اسم {name} في أي مكان. يتوقف البرنامج هنا.',
      es: 'No hay ningún nombre {name} que encontrar. El programa se detiene aquí.',
      fr: 'Aucun nom {name} à trouver nulle part. Le programme s’arrête ici.',
      hi: '{name} नाम कहीं नहीं मिलता। प्रोग्राम यहीं रुक जाता है।',
      id: 'Tidak ada nama {name} di mana pun. Program berhenti di sini.',
      pt: 'Não há nome {name} em lugar nenhum. O programa para aqui.',
    },
    'label.outer': {
      en: 'outside',
      ko: '바깥',
      ja: '外側',
      zh: '外层',
      ar: 'الخارج',
      es: 'fuera',
      fr: 'extérieur',
      hi: 'बाहर',
      id: 'luar',
      pt: 'fora',
    },
    'label.body': {
      en: 'body',
      ko: '몸',
      ja: 'ブロック',
      zh: '代码块',
      ar: 'الجسم',
      es: 'cuerpo',
      fr: 'corps',
      hi: 'भीतरी भाग',
      id: 'badan',
      pt: 'corpo',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المخرجات',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
    'label.halt': {
      en: 'stopped',
      ko: '멈춤',
      ja: '停止',
      zh: '停止',
      ar: 'توقف',
      es: 'detenido',
      fr: 'arrêté',
      hi: 'रुका',
      id: 'berhenti',
      pt: 'parado',
    },
  },
  blocks: {
    stage: { type: 'scope-exit-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
