import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const branchHistoryTableFacet: FacetJson = {
  id: 'facet:branchHistoryTable',
  title: {
    en: 'Branch History Table',
    ko: '분기 이력 표',
    ja: '分岐履歴テーブル',
    zh: '分支历史表',
    ar: 'جدول تاريخ التفرع',
    es: 'Tabla de historial de saltos',
    fr: 'Table d’historique des branchements',
    hi: 'ब्रांच हिस्ट्री टेबल',
    id: 'Tabel Riwayat Cabang',
    pt: 'Tabela de histórico de desvios',
  },
  description: {
    en: 'Index 2-bit counters by the branch’s last few outcomes: a repeating pattern stops missing once the history is long enough, a random one never gets past half.',
    ko: '분기의 지난 몇 번으로 2비트 카운터 칸을 고른다. 되풀이되는 무늬는 이력이 충분히 길어지면 틀림이 멎고, 무작위는 절반을 넘지 못한다.',
    ja: '分岐の直近数回の結果で 2 ビットカウンタを選ぶ。繰り返す模様は履歴が十分長くなると外れが止まり、ランダムな分岐は半分を超えない。',
    zh: '用分支最近几次的结果来选择 2 位计数器：重复的模式在历史足够长时不再猜错，随机分支始终超不过一半。',
    ar: 'تُفهرس عدادات ثنائية البت بآخر نتائج التفرع: النمط المتكرر يتوقف عن الخطأ حين يطول التاريخ بما يكفي، والعشوائي لا يتجاوز النصف أبدًا.',
    es: 'Indexa contadores de 2 bits con los últimos resultados del salto: un patrón repetido deja de fallar cuando el historial es lo bastante largo; uno aleatorio nunca pasa de la mitad.',
    fr: 'Indexer des compteurs 2 bits par les derniers résultats du branchement : un motif répété cesse d’échouer dès que l’historique est assez long, un branchement aléatoire ne dépasse jamais la moitié.',
    hi: 'ब्रांच के पिछले कुछ नतीजों से 2-बिट काउंटर चुनें: दोहराता पैटर्न इतिहास लंबा होते ही चूकना बंद कर देता है, यादृच्छिक ब्रांच आधे से ऊपर नहीं जाती।',
    id: 'Pilih penghitung 2-bit berdasarkan beberapa hasil terakhir cabang: pola berulang berhenti meleset begitu riwayatnya cukup panjang, cabang acak tak pernah melewati separuh.',
    pt: 'Indexe contadores de 2 bits pelos últimos resultados do desvio: um padrão repetido para de errar quando o histórico é longo o bastante; um aleatório nunca passa da metade.',
  },
  algorithm: 'module:branchHistoryTable',
  projector: 'module:branchHistoryTableProjector',
  initialData: {
    type: 'branch-history-table',
    traces: ['pattern', 'random'],
    outcomes: {
      // TTN × 6
      pattern: [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0],
      // TTTNTNNTTTNNNNNTTN — 파이썬 random.Random(2) 의 choice('TN') 18 번 (T 가 정확히 9 인 첫 씨앗)
      random: [1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0],
    },
    ladder: [0, 1, 2, 3],
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'branch-history-table-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback!,
        {
          widget: 'segmented-slider',
          action: 'history',
          name: 'history',
          label: {
            en: 'History length',
            ko: '이력 길이',
            ja: '履歴の長さ',
            zh: '历史长度',
            ar: 'طول التاريخ',
            es: 'Longitud del historial',
            fr: 'Longueur d’historique',
            hi: 'इतिहास की लंबाई',
            id: 'Panjang riwayat',
            pt: 'Tamanho do histórico',
          },
          segments: [
            { value: 0, label: '0', default: true },
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'trace',
          name: 'trace',
          label: {
            en: 'Branch',
            ko: '분기',
            ja: '分岐',
            zh: '分支',
            ar: 'التفرع',
            es: 'Salto',
            fr: 'Branchement',
            hi: 'ब्रांच',
            id: 'Cabang',
            pt: 'Desvio',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'Pattern',
                ko: '무늬',
                ja: '模様',
                zh: '模式',
                ar: 'نمط',
                es: 'Patrón',
                fr: 'Motif',
                hi: 'पैटर्न',
                id: 'Pola',
                pt: 'Padrão',
              },
              default: true,
            },
            {
              value: 1,
              label: {
                en: 'Random',
                ko: '무작위',
                ja: 'ランダム',
                zh: '随机',
                ar: 'عشوائي',
                es: 'Aleatorio',
                fr: 'Aléatoire',
                hi: 'यादृच्छिक',
                id: 'Acak',
                pt: 'Aleatório',
              },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'miss-count',
          label: {
            en: 'Misses',
            ko: '틀림',
            ja: '外れ',
            zh: '猜错',
            ar: 'الأخطاء',
            es: 'Fallos',
            fr: 'Échecs',
            hi: 'चूक',
            id: 'Meleset',
            pt: 'Erros',
          },
          initial: 0,
        },
        {
          name: 'hit-percent',
          label: {
            en: 'Hit %',
            ko: '맞힘 %',
            ja: '的中 %',
            zh: '命中 %',
            ar: 'الإصابة %',
            es: 'Aciertos %',
            fr: 'Réussite %',
            hi: 'सही %',
            id: 'Tepat %',
            pt: 'Acertos %',
          },
          initial: 0,
        },
        {
          name: 'entry-count',
          label: {
            en: 'Table cells',
            ko: '표 칸',
            ja: '表のマス',
            zh: '表项数',
            ar: 'خانات الجدول',
            es: 'Celdas de la tabla',
            fr: 'Cases de la table',
            hi: 'टेबल के खाने',
            id: 'Sel tabel',
            pt: 'Células da tabela',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:branch-history-table-imperative',
      label: {
        en: 'Local history table',
        ko: '지역 이력 표',
        ja: 'ローカル履歴テーブル',
        zh: '局部历史表',
        ar: 'جدول التاريخ المحلي',
        es: 'Tabla de historial local',
        fr: 'Table d’historique local',
        hi: 'लोकल हिस्ट्री टेबल',
        id: 'Tabel riwayat lokal',
        pt: 'Tabela de histórico local',
      },
    },
  },
  messages: {
    'trace.pattern': {
      en: 'Pattern {unit}',
      ko: '무늬 {unit}',
      ja: '模様 {unit}',
      zh: '模式 {unit}',
      ar: 'النمط {unit}',
      es: 'Patrón {unit}',
      fr: 'Motif {unit}',
      hi: 'पैटर्न {unit}',
      id: 'Pola {unit}',
      pt: 'Padrão {unit}',
    },
    'trace.random': {
      en: 'Random',
      ko: '무작위',
      ja: 'ランダム',
      zh: '随机',
      ar: 'عشوائي',
      es: 'Aleatorio',
      fr: 'Aléatoire',
      hi: 'यादृच्छिक',
      id: 'Acak',
      pt: 'Aleatório',
    },
    'caption.round': {
      en: '{trace} · history {bits} bits → {size} cells. Every counter starts at 2 (weakly taken).',
      ko: '{trace} · 이력 {bits}비트 → 칸 {size}개. 카운터는 모두 2(약하게 탄다)에서 시작한다.',
      ja: '{trace} · 履歴 {bits} ビット → マス {size} 個。カウンタはすべて 2(弱く分岐する)から始まる。',
      zh: '{trace} · 历史 {bits} 位 → {size} 个表项。所有计数器都从 2(弱跳转)开始。',
      ar: '{trace} · تاريخ من {bits} بت ← {size} خانات. يبدأ كل عداد من 2 (قفزة ضعيفة).',
      es: '{trace} · historial de {bits} bits → {size} celdas. Todos los contadores empiezan en 2 (salta, débil).',
      fr: '{trace} · historique de {bits} bits → {size} cases. Chaque compteur part de 2 (pris, faible).',
      hi: '{trace} · इतिहास {bits} बिट → {size} खाने। हर काउंटर 2 (कमज़ोर taken) से शुरू होता है।',
      id: '{trace} · riwayat {bits} bit → {size} sel. Semua penghitung mulai dari 2 (lemah melompat).',
      pt: '{trace} · histórico de {bits} bits → {size} células. Todo contador começa em 2 (salta, fraco).',
    },
    'caption.lookup': {
      en: 'Branch {n}: history {hist} picks its cell — counter {counter}, so guess {guess}.',
      ko: '분기 {n}: 이력 {hist} → 그 칸의 카운터 {counter}, 짐작 {guess}.',
      ja: '分岐 {n}: 履歴 {hist} が指すマス — カウンタ {counter}、予測 {guess}。',
      zh: '分支 {n}:历史 {hist} 指向的表项 — 计数器 {counter},预测 {guess}。',
      ar: 'التفرع {n}: التاريخ {hist} يختار خانته — العداد {counter}، إذن التخمين {guess}.',
      es: 'Salto {n}: el historial {hist} elige su celda — contador {counter}, predicción {guess}.',
      fr: 'Branchement {n} : l’historique {hist} choisit sa case — compteur {counter}, donc prédiction {guess}.',
      hi: 'ब्रांच {n}: इतिहास {hist} अपना खाना चुनता है — काउंटर {counter}, अनुमान {guess}।',
      id: 'Cabang {n}: riwayat {hist} memilih selnya — penghitung {counter}, tebakan {guess}.',
      pt: 'Desvio {n}: o histórico {hist} escolhe sua célula — contador {counter}, palpite {guess}.',
    },
    'caption.lookupNone': {
      en: 'Branch {n}: no history, one shared cell — counter {counter}, so guess {guess}.',
      ko: '분기 {n}: 이력 없음, 칸 하나를 함께 쓴다 — 카운터 {counter}, 짐작 {guess}.',
      ja: '分岐 {n}: 履歴なし、マスは一つだけ — カウンタ {counter}、予測 {guess}。',
      zh: '分支 {n}:没有历史,只有一个共用表项 — 计数器 {counter},预测 {guess}。',
      ar: 'التفرع {n}: بلا تاريخ، خانة واحدة مشتركة — العداد {counter}، إذن التخمين {guess}.',
      es: 'Salto {n}: sin historial, una sola celda compartida — contador {counter}, predicción {guess}.',
      fr: 'Branchement {n} : pas d’historique, une seule case partagée — compteur {counter}, donc prédiction {guess}.',
      hi: 'ब्रांच {n}: कोई इतिहास नहीं, एक ही साझा खाना — काउंटर {counter}, अनुमान {guess}।',
      id: 'Cabang {n}: tanpa riwayat, satu sel bersama — penghitung {counter}, tebakan {guess}.',
      pt: 'Desvio {n}: sem histórico, uma única célula — contador {counter}, palpite {guess}.',
    },
    'caption.hit': {
      en: 'Actual {taken} — hit. The counter moves to {counter}.',
      ko: '실제 {taken} — 맞힘. 카운터 → {counter}.',
      ja: '実際は {taken} — 的中。カウンタは {counter} へ。',
      zh: '实际为 {taken} — 命中。计数器变为 {counter}。',
      ar: 'الفعلي {taken} — إصابة. ينتقل العداد إلى {counter}.',
      es: 'Real {taken} — acierto. El contador pasa a {counter}.',
      fr: 'Réel {taken} — réussi. Le compteur passe à {counter}.',
      hi: 'असल में {taken} — सही। काउंटर {counter} पर जाता है।',
      id: 'Sebenarnya {taken} — tepat. Penghitung bergeser ke {counter}.',
      pt: 'Real {taken} — acerto. O contador vai para {counter}.',
    },
    'caption.miss': {
      en: 'Actual {taken} — miss (#{misses}). The counter moves to {counter}.',
      ko: '실제 {taken} — 틀림 ({misses}번째). 카운터 → {counter}.',
      ja: '実際は {taken} — 外れ ({misses} 回目)。カウンタは {counter} へ。',
      zh: '实际为 {taken} — 猜错(第 {misses} 次)。计数器变为 {counter}。',
      ar: 'الفعلي {taken} — خطأ (رقم {misses}). ينتقل العداد إلى {counter}.',
      es: 'Real {taken} — fallo (n.º {misses}). El contador pasa a {counter}.',
      fr: 'Réel {taken} — échec (n° {misses}). Le compteur passe à {counter}.',
      hi: 'असल में {taken} — चूक (#{misses})। काउंटर {counter} पर जाता है।',
      id: 'Sebenarnya {taken} — meleset (ke-{misses}). Penghitung bergeser ke {counter}.',
      pt: 'Real {taken} — erro (n.º {misses}). O contador vai para {counter}.',
    },
    'caption.shift': {
      en: '{taken} slides into the history — the next branch reads cell {cell}.',
      ko: '이력에 {taken} 밀어 넣기 — 다음 분기가 읽을 칸: {cell}.',
      ja: '{taken} が履歴に押し込まれる — 次の分岐はマス {cell} を読む。',
      zh: '{taken} 移入历史 — 下一次分支读取表项 {cell}。',
      ar: 'يدخل {taken} إلى التاريخ — التفرع التالي يقرأ الخانة {cell}.',
      es: '{taken} entra en el historial — el siguiente salto lee la celda {cell}.',
      fr: '{taken} entre dans l’historique — le branchement suivant lit la case {cell}.',
      hi: '{taken} इतिहास में खिसकता है — अगली ब्रांच खाना {cell} पढ़ेगी।',
      id: '{taken} masuk ke riwayat — cabang berikutnya membaca sel {cell}.',
      pt: '{taken} entra no histórico — o próximo desvio lê a célula {cell}.',
    },
    'caption.shiftNone': {
      en: 'No history to shift — the next branch reads the same cell.',
      ko: '밀어 넣을 이력이 없다 — 다음 분기도 같은 칸을 읽는다.',
      ja: '押し込む履歴はない — 次の分岐も同じマスを読む。',
      zh: '没有可移入的历史 — 下一次分支读取同一个表项。',
      ar: 'لا تاريخ لإزاحته — التفرع التالي يقرأ الخانة نفسها.',
      es: 'No hay historial que desplazar — el siguiente salto lee la misma celda.',
      fr: 'Pas d’historique à décaler — le branchement suivant lit la même case.',
      hi: 'खिसकाने को कोई इतिहास नहीं — अगली ब्रांच वही खाना पढ़ेगी।',
      id: 'Tidak ada riwayat untuk digeser — cabang berikutnya membaca sel yang sama.',
      pt: 'Não há histórico para deslocar — o próximo desvio lê a mesma célula.',
    },
    'caption.end': {
      en: '{misses} of {total} missed → {percent}% hit with {size} cells. Turn a knob to replay.',
      ko: '{total}번 중 {misses}번 틀림 → 칸 {size}개로 {percent}% 맞힘. 손잡이를 돌리면 다시 재생한다.',
      ja: '{total} 回中 {misses} 回外れ → マス {size} 個で的中 {percent}%。つまみを回すと再生し直す。',
      zh: '{total} 次中猜错 {misses} 次 → {size} 个表项命中 {percent}%。转动旋钮重新播放。',
      ar: 'أخطأ {misses} من {total} ← إصابة {percent}% مع {size} خانات. أدِر مقبضًا لإعادة التشغيل.',
      es: '{misses} de {total} fallados → {percent}% de aciertos con {size} celdas. Gira un control para repetir.',
      fr: '{misses} échecs sur {total} → {percent}% de réussite avec {size} cases. Tournez un réglage pour rejouer.',
      hi: '{total} में से {misses} चूके → {size} खानों से {percent}% सही। दोबारा चलाने के लिए कोई नॉब घुमाएँ।',
      id: '{misses} dari {total} meleset → {percent}% tepat dengan {size} sel. Putar kenop untuk memutar ulang.',
      pt: '{misses} de {total} errados → {percent}% de acertos com {size} células. Gire um controle para repetir.',
    },
    'label.outcomes': {
      en: 'Outcome',
      ko: '결과',
      ja: '結果',
      zh: '结果',
      ar: 'النتيجة',
      es: 'Resultado',
      fr: 'Résultat',
      hi: 'नतीजा',
      id: 'Hasil',
      pt: 'Resultado',
    },
    'label.history': {
      en: 'History',
      ko: '이력',
      ja: '履歴',
      zh: '历史',
      ar: 'التاريخ',
      es: 'Historial',
      fr: 'Historique',
      hi: 'इतिहास',
      id: 'Riwayat',
      pt: 'Histórico',
    },
    'label.table': {
      en: 'Counters',
      ko: '카운터',
      ja: 'カウンタ',
      zh: '计数器',
      ar: 'العدادات',
      es: 'Contadores',
      fr: 'Compteurs',
      hi: 'काउंटर',
      id: 'Penghitung',
      pt: 'Contadores',
    },
    'label.noHistory': {
      en: '0 bits — nothing remembered',
      ko: '0비트 — 기억하는 것이 없다',
      ja: '0 ビット — 何も覚えていない',
      zh: '0 位 — 什么也不记',
      ar: '0 بت — لا شيء محفوظ',
      es: '0 bits — no recuerda nada',
      fr: '0 bit — rien en mémoire',
      hi: '0 बिट — कुछ याद नहीं',
      id: '0 bit — tidak ada yang diingat',
      pt: '0 bits — nada lembrado',
    },
  },
};
