/**
 * 시간 지역성 — 방금 쓴 것을 곧 또 쓴다.
 *
 * @piece 한 질문에 답하고 멈춘다 — 같은 자리를 거듭 찾으면 아래층까지 내려갈
 * 일이 없고, 매번 다른 곳을 찾으면 올라온 것이 쓰이기도 전에 밀려난다.
 *
 * 선언에 두는 것은 구조뿐이다 — 칸 수 · 라인 크기 · 원소 크기 · 두 접근열의
 * 색인. 히트·미스 판정은 algorithm 이 내리고, 적중·실패의 **셈은 장면이** 하며
 * 좌표는 stage 가 셈한다 (S-piece). 화면을 명령이 아니라 장면으로 만들므로 띠를
 * 단다 (`CONTROL_SET.pieceScrub`). `stepMs` 는 읽을 시간을 정하는 저작 결정이라
 * 예외로 여기 둔다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const temporalLocalityFacet: FacetJson = {
  id: 'facet:temporalLocality',
  title: {
    en: 'Temporal locality',
    ko: '시간 지역성',
    ja: '時間的局所性',
    zh: '时间局部性',
    ar: 'المحلية الزمنية',
    es: 'Localidad temporal',
    fr: 'Localité temporelle',
    hi: 'कालिक स्थानिकता',
    id: 'Lokalitas temporal',
    pt: 'Localidade temporal',
  },
  description: {
    en: 'What you just read, you read again soon — so it stays upstairs.',
    ko: '방금 읽은 것을 곧 또 읽는다 — 그래서 위층에 머문다.',
    ja: '今読んだものをすぐまた読む — だから上の階にとどまる。',
    zh: '刚读过的马上又读 — 所以它留在上层。',
    ar: 'ما قرأته للتو تقرأه قريبًا مرة أخرى، لذلك يبقى في الأعلى.',
    es: 'Lo que acabas de leer lo vuelves a leer pronto: por eso se queda arriba.',
    fr: "Ce qu'on vient de lire, on le relit bientôt : voilà pourquoi cela reste en haut.",
    hi: 'जो अभी पढ़ा है वही जल्द फिर पढ़ा जाता है — इसलिए वह ऊपर बना रहता है।',
    id: 'Yang baru saja dibaca akan segera dibaca lagi — karena itu ia bertahan di atas.',
    pt: 'O que você acabou de ler, logo lê de novo — por isso fica em cima.',
  },
  algorithm: 'module:temporalLocality',
  scene: 'module:temporalLocalityScene',
  initialData: {
    type: 'temporal-locality',
    stepMs: 700,
    slots: 2,
    lineBytes: 16,
    elemBytes: 4,
    streams: [
      { name: 'near', indices: [3, 3, 3, 3, 3, 3] },
      { name: 'far', indices: [0, 20, 40, 0, 20, 40] },
    ],
  },
  blocks: {
    stage: { type: 'temporal-locality-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'label.near': {
      en: 'same spot',
      ko: '같은 자리',
      ja: '同じ場所',
      zh: '同一处',
      ar: 'المكان نفسه',
      es: 'mismo sitio',
      fr: 'même endroit',
      hi: 'वही जगह',
      id: 'tempat sama',
      pt: 'mesmo lugar',
    },
    'label.far': {
      en: 'scattered',
      ko: '흩어진 곳',
      ja: '散らばった先',
      zh: '分散各处',
      ar: 'أماكن متفرقة',
      es: 'disperso',
      fr: 'éparpillé',
      hi: 'बिखरी जगहें',
      id: 'berpencar',
      pt: 'espalhado',
    },
    'caption.near': {
      en: 'Six reads, all at the same spot. Slots upstairs: {slots}.',
      ko: '여섯 번 모두 같은 자리를 읽는다. 위층의 칸 수는 {slots}.',
      ja: '六回とも同じ場所を読む。上の階の枠の数は {slots}。',
      zh: '六次都读同一处。上层的格数为 {slots}。',
      ar: 'ست قراءات كلها من المكان نفسه. عدد الخانات في الأعلى: {slots}.',
      es: 'Seis lecturas, todas en el mismo sitio. Huecos arriba: {slots}.',
      fr: 'Six lectures, toutes au même endroit. Cases en haut : {slots}.',
      hi: 'छह बार पढ़ना, हर बार वही जगह। ऊपर की खानों की संख्या: {slots}।',
      id: 'Enam kali baca, semuanya di tempat yang sama. Jumlah kotak di atas: {slots}.',
      pt: 'Seis leituras, todas no mesmo lugar. Espaços em cima: {slots}.',
    },
    'caption.far': {
      en: 'Six reads again, but each one somewhere else.',
      ko: '이번에도 여섯 번, 다만 매번 다른 곳을 읽는다.',
      ja: '今度も六回、ただし毎回ちがう場所を読む。',
      zh: '这次也是六次，只是每次读的地方都不同。',
      ar: 'ست قراءات أخرى، لكن كل واحدة من مكان آخر.',
      es: 'Otras seis lecturas, pero cada una en otro sitio.',
      fr: 'Six lectures encore, mais chacune ailleurs.',
      hi: 'फिर छह बार पढ़ना, लेकिन हर बार अलग जगह।',
      id: 'Enam kali baca lagi, tetapi tiap kali di tempat lain.',
      pt: 'Mais seis leituras, mas cada uma em outro lugar.',
    },
    'caption.hit': {
      en: 'Already upstairs. The read turns back here.',
      ko: '이미 위층에 있다. 읽기가 여기서 되돌아온다.',
      ja: 'すでに上の階にある。読みはここで折り返す。',
      zh: '已经在上层。读取到此折返。',
      ar: 'موجود في الأعلى. تعود القراءة من هنا.',
      es: 'Ya está arriba. La lectura vuelve desde aquí.',
      fr: "Déjà en haut. La lecture repart d'ici.",
      hi: 'ऊपर पहले से मौजूद है। पढ़ाई यहीं से लौट आती है।',
      id: 'Sudah ada di atas. Pembacaan berbalik dari sini.',
      pt: 'Já está em cima. A leitura volta daqui.',
    },
    'caption.miss': {
      en: 'Not upstairs. The read goes down and the line rises.',
      ko: '위층에 없다. 아래층까지 내려가고, 그 라인이 올라온다.',
      ja: '上の階にない。下の階まで降り、その行が上がってくる。',
      zh: '上层没有。要下到下层，那一行随之升上来。',
      ar: 'ليس في الأعلى. ينزل الطلب إلى الأسفل ثم يصعد السطر.',
      es: 'No está arriba. La lectura baja y la línea sube.',
      fr: 'Pas en haut. La lecture descend et la ligne remonte.',
      hi: 'ऊपर नहीं है। नीचे तक जाना पड़ता है और वह पंक्ति ऊपर आती है।',
      id: 'Tidak ada di atas. Pembacaan turun ke bawah dan barisnya naik.',
      pt: 'Não está em cima. A leitura desce e a linha sobe.',
    },
    'caption.evict': {
      en: 'No free slot — the line that waited longest is pushed out.',
      ko: '빈 칸이 없다 — 가장 오래 기다린 라인이 밀려난다.',
      ja: '空き枠がない — いちばん長く待った行が押し出される。',
      zh: '没有空格 — 等得最久的行被挤出去。',
      ar: 'لا خانة فارغة — يُدفع إلى الخارج السطر الأطول انتظارًا.',
      es: 'No hay hueco libre: sale la línea que más esperó.',
      fr: "Plus de case libre — la ligne qui a attendu le plus longtemps est chassée.",
      hi: 'कोई खाना खाली नहीं — सबसे लंबे समय से प्रतीक्षा कर रही पंक्ति बाहर धकेल दी जाती है।',
      id: 'Tidak ada kotak kosong — baris yang paling lama menunggu terdorong keluar.',
      pt: 'Nenhum espaço livre — sai a linha que esperou mais tempo.',
    },
    'caption.nearResult': {
      en: 'Staying put. Trips downstairs: {miss}.',
      ko: '같은 자리에 머물렀다. 아래층까지 내려간 횟수는 {miss}.',
      ja: '同じ場所にとどまった。下の階へ降りた回数は {miss}。',
      zh: '始终停在同一处。下到下层的次数为 {miss}。',
      ar: 'بقيت القراءات في المكان نفسه. عدد النزولات إلى الأسفل: {miss}.',
      es: 'Se quedó en el mismo sitio. Bajadas al piso de abajo: {miss}.',
      fr: 'Tout est resté au même endroit. Descentes vers le bas : {miss}.',
      hi: 'सब कुछ एक ही जगह रहा। नीचे तक जाने की संख्या: {miss}।',
      id: 'Tetap di tempat yang sama. Jumlah turun ke bawah: {miss}.',
      pt: 'Tudo ficou no mesmo lugar. Descidas ao andar de baixo: {miss}.',
    },
    'caption.farResult': {
      en: 'Wandering off. Trips downstairs: {miss}.',
      ko: '매번 다른 곳을 찾았다. 아래층까지 내려간 횟수는 {miss}.',
      ja: '毎回ちがう場所を探した。下の階へ降りた回数は {miss}。',
      zh: '每次都找别处。下到下层的次数为 {miss}。',
      ar: 'تنقّلت القراءات بين الأماكن. عدد النزولات إلى الأسفل: {miss}.',
      es: 'Fue saltando de sitio. Bajadas al piso de abajo: {miss}.',
      fr: 'Chaque fois ailleurs. Descentes vers le bas : {miss}.',
      hi: 'हर बार नई जगह। नीचे तक जाने की संख्या: {miss}।',
      id: 'Berpindah-pindah tempat. Jumlah turun ke bawah: {miss}.',
      pt: 'Cada vez em outro lugar. Descidas ao andar de baixo: {miss}.',
    },
    'caption.verdict': {
      en: 'Same six reads either way. Trips downstairs: {near} and {far}.',
      ko: '읽은 횟수는 양쪽 다 여섯이다. 아래층까지 내려간 횟수는 {near} 대 {far}.',
      ja: '読んだ回数はどちらも六回。下の階へ降りた回数は {near} 対 {far}。',
      zh: '两边读取次数都是六次。下到下层的次数为 {near} 比 {far}。',
      ar: 'ست قراءات في الحالتين. عدد النزولات إلى الأسفل: {near} مقابل {far}.',
      es: 'Las mismas seis lecturas en ambos casos. Bajadas: {near} y {far}.',
      fr: 'Six lectures des deux côtés. Descentes vers le bas : {near} contre {far}.',
      hi: 'दोनों ओर पढ़ना छह बार। नीचे तक जाने की संख्या: {near} और {far}।',
      id: 'Sama-sama enam pembacaan. Jumlah turun ke bawah: {near} berbanding {far}.',
      pt: 'Seis leituras dos dois lados. Descidas: {near} e {far}.',
    },
  },
};
