/**
 * 셸 정렬 완결형 선언.
 *
 * 블록은 셋뿐이다 — `stage` · `controls` · `codePanel`. 제목 블록을 두지 않는다
 * (이름은 카탈로그 카드와 글의 문단이 준다). 대조 장부도 빌트인 view 를 빌리지
 * 않고 stage 가 직접 그린다.
 *
 * 이 facet 의 산출물은 그림이 아니라 **코드** 다. `ir:shellsort-gap` 하나가
 * 여섯 언어로 펼쳐지고, 재생 중인 phase 가 그 줄을 짚는다. 삽입 정렬과 같은
 * 골격에 `1` 이 `gap` 으로 바뀐 것뿐이라는 주장은 그 코드 패널에서 확인된다.
 *
 * 식별자 (C1): `index:<i>`.
 */

import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const shellSortFacet: FacetJson = {
  id: 'facet:shellSort',
  // 제목은 카탈로그 카드의 이름과 같다 (C4 명명 규칙 5).
  title: {
    en: 'Shell Sort',
    ko: '셸 정렬',
    ja: 'シェルソート',
    zh: '希尔排序',
    ar: 'ترتيب شل',
    es: 'Ordenamiento de Shell',
    fr: 'Tri de Shell',
    hi: 'शेल सॉर्ट',
    id: 'Pengurutan Shell',
    pt: 'Ordenação de Shell',
  },
  description: {
    en: 'Insertion sort taken with a stride — clear the far disorder first and the last pass has little left.',
    ko: '간격을 두고 하는 삽입 정렬 — 멀리 있는 어긋남을 먼저 걷어 내면 마지막 라운드가 할 일이 적다',
    ja: '歩幅を広げた挿入ソート — 遠くの乱れを先に片づければ、最後の一巡に残る仕事は少ない。',
    zh: '迈大步的插入排序 — 先清掉远处的错乱，最后一趟就没剩多少活。',
    ar: 'ترتيب بالإدراج بخطوة أوسع — أزِل الاختلال البعيد أولًا فلا يبقى للجولة الأخيرة الكثير.',
    es: 'Ordenamiento por inserción con zancada: quita primero el desorden lejano y a la última pasada le queda poco.',
    fr: "Tri par insertion à grandes enjambées — enlevez d'abord le désordre lointain et il reste peu à la dernière passe.",
    hi: 'लंबे कदम वाला सम्मिलन क्रमण — दूर की गड़बड़ी पहले हटा दें तो अंतिम दौर के लिए थोड़ा ही बचता है।',
    id: 'Pengurutan sisip berlangkah lebar — bereskan kekacauan yang jauh dulu, maka lintasan terakhir tinggal sedikit.',
    pt: 'Ordenação por inserção a passos largos — tire primeiro a desordem distante e sobra pouco para a última passagem.',
  },
  algorithm: 'module:shellSort',
  projector: 'module:shellSortProjector',
  // 사양이 정한 자료. `len(arr) // 2` 로 시작해 반씩 접으면 간격이 3 → 1 이 되고,
  // 간격 3 은 자리 0·3·6 / 1·4 / 2·5 세 사슬을 만든다. 섞으면 그 배치가 사라진다.
  initialData: { type: 'array', values: [64, 25, 12, 22, 11, 90, 34] },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    stage: { type: 'shell-sort-stage' },
    controls: {
      type: 'control-bar',
      controls: CONTROL_SET.playback,
      metrics: [
        {
          name: 'compare-count',
          label: {
            en: 'Compare',
            ko: '견줌',
            ja: '比較',
            zh: '比较',
            ar: 'مقارنة',
            es: 'Comparar',
            fr: 'Comparer',
            hi: 'तुलना',
            id: 'Banding',
            pt: 'Comparar',
          },
          initial: 0,
        },
        {
          name: 'shift-count',
          label: {
            en: 'Shift',
            ko: '이동',
            ja: '移動',
            zh: '移动',
            ar: 'إزاحة',
            es: 'Desplazar',
            fr: 'Décaler',
            hi: 'खिसकाव',
            id: 'Geser',
            pt: 'Deslocar',
          },
          initial: 0,
        },
        {
          name: 'gap-count',
          label: {
            en: 'Gap rounds',
            ko: '간격 라운드',
            ja: '間隔ラウンド',
            zh: '间隔轮数',
            ar: 'جولات الفجوة',
            es: 'Rondas de salto',
            fr: "Tours d'écart",
            hi: 'अंतराल दौर',
            id: 'Putaran jarak',
            pt: 'Rodadas de salto',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      label: {
        en: 'Code',
        ko: '코드',
        ja: 'コード',
        zh: '代码',
        ar: 'الشيفرة',
        es: 'Código',
        fr: 'Code',
        hi: 'कोड',
        id: 'Kode',
        pt: 'Código',
      },
      ir: 'ir:shellsort-gap',
    },
  },
  messages: {
    'label.gapSpan': {
      en: 'gap {gap}',
      ko: '간격 {gap}',
      ja: '間隔 {gap}',
      zh: '间隔 {gap}',
      ar: 'فجوة {gap}',
      es: 'salto {gap}',
      fr: 'écart {gap}',
      hi: 'अंतराल {gap}',
      id: 'jarak {gap}',
      pt: 'salto {gap}',
    },
    'label.shiftsWithGaps': {
      en: 'Shifts, with gaps',
      ko: '간격을 두면 이동',
      ja: '間隔ありの移動',
      zh: '有间隔时的移动',
      ar: 'إزاحات مع الفجوات',
      es: 'Desplazamientos con saltos',
      fr: 'Décalages avec écarts',
      hi: 'अंतराल के साथ खिसकाव',
      id: 'Geseran dengan jarak',
      pt: 'Deslocamentos com saltos',
    },
    'label.shiftsNeighbourOnly': {
      en: 'Shifts, gap 1 only',
      ko: '간격 1 만으로 하면 이동',
      ja: '間隔 1 だけの移動',
      zh: '仅间隔 1 时的移动',
      ar: 'إزاحات بفجوة 1 فقط',
      es: 'Desplazamientos solo con salto 1',
      fr: 'Décalages, écart 1 seulement',
      hi: 'केवल अंतराल 1 से खिसकाव',
      id: 'Geseran, hanya jarak 1',
      pt: 'Deslocamentos só com salto 1',
    },
    'caption.start': {
      en: 'Insertion sort, but the step is a gap instead of one cell.',
      ko: '삽입 정렬인데 걸음이 한 칸이 아니라 간격만큼이다',
      ja: '挿入ソートだが、歩幅は一マスではなく間隔ぶんだ。',
      zh: '还是插入排序，只是每步跨的不是一格，而是一个间隔。',
      ar: 'ترتيب بالإدراج، لكن الخطوة فجوة لا خانة واحدة.',
      es: 'Ordenamiento por inserción, pero el paso es un salto y no una casilla.',
      fr: "Tri par insertion, mais le pas est un écart et non une case.",
      hi: 'सम्मिलन क्रमण, पर कदम एक खाने का नहीं, अंतराल का है।',
      id: 'Pengurutan sisip, tetapi langkahnya sebuah jarak, bukan satu sel.',
      pt: 'Ordenação por inserção, mas o passo é um salto e não uma casa.',
    },
    'caption.baseline': {
      en: 'The same input with gap 1 only would shift {shifts} times. Watch that number.',
      ko: '같은 입력을 간격 1 만으로 하면 이동이 {shifts} 번이다. 이 수를 기억해 두자',
      ja: '同じ入力を間隔 1 だけでやると移動は {shifts} 回。この数を覚えておこう。',
      zh: '同样的输入若只用间隔 1，要移动 {shifts} 次。记住这个数。',
      ar: 'المدخل نفسه بفجوة 1 فقط يحتاج {shifts} إزاحة. تذكّر هذا الرقم.',
      es: 'La misma entrada solo con salto 1 haría {shifts} desplazamientos. Recuerda ese número.',
      fr: "La même entrée avec un écart de 1 seulement ferait {shifts} décalages. Retenez ce nombre.",
      hi: 'यही इनपुट केवल अंतराल 1 से {shifts} बार खिसकेगा। यह संख्या याद रखें।',
      id: 'Masukan yang sama dengan hanya jarak 1 akan menggeser {shifts} kali. Ingat angka itu.',
      pt: 'A mesma entrada só com salto 1 faria {shifts} deslocamentos. Guarde esse número.',
    },
    'caption.roundGap': {
      en: 'Round {round} — gap {gap} splits the row into {chains} chains that never touch.',
      ko: '라운드 {round} — 간격 {gap} 이 줄을 서로 닿지 않는 사슬 {chains} 개로 가른다',
      ja: 'ラウンド {round} — 間隔 {gap} が列を、互いに触れない {chains} 本の鎖に分ける。',
      zh: '第 {round} 轮 — 间隔 {gap} 把这排分成 {chains} 条互不相碰的链。',
      ar: 'الجولة {round} — الفجوة {gap} تقسم الصف إلى {chains} سلاسل لا تتلامس.',
      es: 'Ronda {round}: el salto {gap} divide la fila en {chains} cadenas que no se tocan.',
      fr: "Tour {round} — l'écart {gap} divise la rangée en {chains} chaînes qui ne se touchent pas.",
      hi: 'दौर {round} — अंतराल {gap} पंक्ति को {chains} ऐसी शृंखलाओं में बाँटता है जो एक-दूसरे को नहीं छूतीं।',
      id: 'Putaran {round} — jarak {gap} membelah baris menjadi {chains} rantai yang tak saling bersentuhan.',
      pt: 'Rodada {round} — o salto {gap} divide a fila em {chains} correntes que não se tocam.',
    },
    'caption.roundNeighbour': {
      en: 'Round {round} — gap 1. This is plain insertion sort, and little is left to do.',
      ko: '라운드 {round} — 간격 1. 보통의 삽입 정렬인데 할 일이 얼마 남지 않았다',
      ja: 'ラウンド {round} — 間隔 1。ふつうの挿入ソートだが、やることはもう少ない。',
      zh: '第 {round} 轮 — 间隔 1。这就是普通的插入排序，而且没剩多少活。',
      ar: 'الجولة {round} — فجوة 1. هذا ترتيب بالإدراج عادي، ولم يبقَ الكثير.',
      es: 'Ronda {round}: salto 1. Es el ordenamiento por inserción de siempre y queda poco por hacer.',
      fr: "Tour {round} — écart 1. C'est le tri par insertion ordinaire, et il reste peu à faire.",
      hi: 'दौर {round} — अंतराल 1। यह साधारण सम्मिलन क्रमण है, और करने को थोड़ा ही बचा है।',
      id: 'Putaran {round} — jarak 1. Ini pengurutan sisip biasa, dan tinggal sedikit yang tersisa.',
      pt: 'Rodada {round} — salto 1. É a ordenação por inserção comum e resta pouco a fazer.',
    },
    'caption.pick': {
      en: 'Lift {value} out of seat {index} — its seat is now a hole.',
      ko: '{index} 번 자리에서 {value} 를 집어 든다 — 그 자리는 구멍이 된다',
      ja: '席 {index} から {value} を持ち上げる — その席は穴になる。',
      zh: '把 {value} 从第 {index} 个位子上拿起 — 那个位子成了空洞。',
      ar: 'ارفع {value} من المقعد {index} — صار مقعده فجوة.',
      es: 'Levanta {value} del puesto {index}: su puesto queda como un hueco.',
      fr: 'On soulève {value} de la place {index} — sa place devient un trou.',
      hi: 'स्थान {index} से {value} उठाएँ — वह स्थान अब एक छेद है।',
      id: 'Angkat {value} dari kursi {index} — kursinya kini menjadi lubang.',
      pt: 'Levante {value} do lugar {index} — o lugar vira um buraco.',
    },
    'caption.compareGreater': {
      en: '{value} is larger than {held} — it must step aside.',
      ko: '{value} 는 {held} 보다 크다 — 비켜서야 한다',
      ja: '{value} は {held} より大きい — わきへどかねばならない。',
      zh: '{value} 比 {held} 大 — 得让开。',
      ar: '{value} أكبر من {held} — عليه أن يتنحّى.',
      es: '{value} es mayor que {held}: debe apartarse.',
      fr: '{value} est plus grand que {held} — il doit se décaler.',
      hi: '{value}, {held} से बड़ा है — इसे हटना होगा।',
      id: '{value} lebih besar dari {held} — ia harus menyingkir.',
      pt: '{value} é maior que {held} — precisa se afastar.',
    },
    'caption.compareStop': {
      en: '{value} is not larger than {held} — the hole is home.',
      ko: '{value} 는 {held} 보다 크지 않다 — 구멍이 곧 자리다',
      ja: '{value} は {held} より大きくない — 穴がその居場所だ。',
      zh: '{value} 不比 {held} 大 — 空洞就是它的位置。',
      ar: '{value} ليس أكبر من {held} — الفجوة هي الموضع.',
      es: '{value} no es mayor que {held}: el hueco es su sitio.',
      fr: "{value} n'est pas plus grand que {held} — le trou est la bonne place.",
      hi: '{value}, {held} से बड़ा नहीं है — छेद ही उसकी जगह है।',
      id: '{value} tidak lebih besar dari {held} — lubang itulah tempatnya.',
      pt: '{value} não é maior que {held} — o buraco é o lugar.',
    },
    'caption.shift': {
      en: '{value} steps aside: it moves right by {gap}, and the hole moves left.',
      ko: '{value} 가 비켜선다 — 오른쪽으로 {gap} 만큼 가고 구멍이 왼쪽으로 옮겨 간다',
      ja: '{value} がわきへどく — 右へ {gap} だけ動き、穴は左へ移る。',
      zh: '{value} 让开：向右移 {gap}，空洞往左挪。',
      ar: 'يتنحّى {value} — ينتقل يمينًا بمقدار {gap}، وتنتقل الفجوة يسارًا.',
      es: '{value} se aparta: avanza {gap} a la derecha y el hueco se mueve a la izquierda.',
      fr: '{value} se décale : il avance de {gap} vers la droite, et le trou va vers la gauche.',
      hi: '{value} हट जाता है — वह {gap} जितना दाईं ओर जाता है और छेद बाईं ओर।',
      id: '{value} menyingkir: ia maju {gap} ke kanan, dan lubangnya pindah ke kiri.',
      pt: '{value} se afasta: avança {gap} para a direita e o buraco vai para a esquerda.',
    },
    'caption.place': {
      en: '{value} drops into seat {index}.',
      ko: '{value} 가 {index} 번 자리에 내려앉는다',
      ja: '{value} が席 {index} に降りる。',
      zh: '{value} 落进第 {index} 个位子。',
      ar: 'يستقر {value} في المقعد {index}.',
      es: '{value} baja al puesto {index}.',
      fr: '{value} se pose sur la place {index}.',
      hi: '{value} स्थान {index} पर उतर जाता है।',
      id: '{value} turun ke kursi {index}.',
      pt: '{value} pousa no lugar {index}.',
    },
    'caption.placeStay': {
      en: '{value} was already in place — nothing moved.',
      ko: '{value} 는 이미 제자리였다 — 움직인 것이 없다',
      ja: '{value} はもとから所定の位置だった — 何も動かない。',
      zh: '{value} 本来就在位子上 — 什么都没动。',
      ar: '{value} كان في موضعه أصلًا — لم يتحرك شيء.',
      es: '{value} ya estaba en su sitio: nada se movió.',
      fr: "{value} était déjà à sa place — rien n'a bougé.",
      hi: '{value} पहले से अपनी जगह पर था — कुछ नहीं हिला।',
      id: '{value} sudah pada tempatnya — tidak ada yang bergerak.',
      pt: '{value} já estava no lugar — nada se moveu.',
    },
    'caption.roundEnd': {
      en: 'Gap {gap} done — {compares} compares, {shifts} shifts.',
      ko: '간격 {gap} 라운드 끝 — 견줌 {compares} 번, 이동 {shifts} 번',
      ja: '間隔 {gap} のラウンドが終わった — 比較 {compares} 回、移動 {shifts} 回。',
      zh: '间隔 {gap} 的一轮结束 — 比较 {compares} 次，移动 {shifts} 次。',
      ar: 'انتهت جولة الفجوة {gap} — {compares} مقارنة و {shifts} إزاحة.',
      es: 'Fin de la ronda con salto {gap}: {compares} comparaciones y {shifts} desplazamientos.',
      fr: "Fin du tour d'écart {gap} — {compares} comparaisons, {shifts} décalages.",
      hi: 'अंतराल {gap} का दौर पूरा — {compares} तुलनाएँ, {shifts} खिसकाव।',
      id: 'Putaran jarak {gap} selesai — {compares} pembandingan, {shifts} geseran.',
      pt: 'Rodada de salto {gap} concluída — {compares} comparações, {shifts} deslocamentos.',
    },
    'caption.done': {
      en: 'Sorted with {shifts} shifts instead of {baselineShifts} — the far rounds paid for it.',
      ko: '이동 {baselineShifts} 번이 아니라 {shifts} 번으로 정렬됐다 — 멀리 견준 앞 라운드가 벌어 준 몫이다',
      ja: '移動 {baselineShifts} 回ではなく {shifts} 回で並んだ — 遠くを見たラウンドが稼いだぶんだ。',
      zh: '只用 {shifts} 次移动就排好，而不是 {baselineShifts} 次 — 这是前面大间隔轮次挣来的。',
      ar: 'تم الترتيب بـ {shifts} إزاحة بدل {baselineShifts} — هذا ما وفّرته الجولات البعيدة.',
      es: 'Ordenado con {shifts} desplazamientos en vez de {baselineShifts}: lo ganaron las rondas de salto largo.',
      fr: "Trié en {shifts} décalages au lieu de {baselineShifts} — c'est ce que les tours à grand écart ont épargné.",
      hi: '{baselineShifts} के बजाय {shifts} खिसकावों में क्रम लग गया — यह दूर वाले दौरों की कमाई है।',
      id: 'Terurut dengan {shifts} geseran alih-alih {baselineShifts} — itulah hasil putaran berjarak jauh.',
      pt: 'Ordenado com {shifts} deslocamentos em vez de {baselineShifts} — foi o que as rodadas de salto longo pouparam.',
    },
  },
};
