/**
 * Kafka 패턴 — 선언.
 * 1차 데이터: 기록 값 24 (오프셋 0..23 차례) · 그룹 식별자 둘 · 되감기 청하는 자리 · 손잡이 사다리 둘.
 * 잃음 · 밀림 · 남은 수 · 튕김 · 되감기 자리는 algorithm 이 셈한다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const kafkaPatternFacet: FacetJson = {
  id: 'facet:kafkaPattern',
  title: {
    en: 'Kafka pattern',
    ko: 'Kafka 패턴',
    ja: 'Kafka パターン',
    zh: 'Kafka 模式',
    ar: 'نمط Kafka',
    es: 'Patrón Kafka',
    fr: 'Motif Kafka',
    hi: 'Kafka पैटर्न',
    id: 'Pola Kafka',
    pt: 'Padrão Kafka',
  },
  description: {
    en: 'A log keeps only as many records as its retention allows, whoever is reading. When the front is deleted, a slow group jumps ahead and loses what it had not read, and a rewind can only reach what is still kept. In this run, longer retention lowers the lost count or keeps it at 0, and raises the lag or leaves it unchanged.',
    ko: '로그는 읽는 쪽과 무관하게 보존 길이만큼만 남는다. 앞이 지워지면 느린 그룹은 앞으로 튕겨 읽지 못한 기록을 잃고, 되감아도 남은 기록까지만 닿는다. 이 판에서는 보존이 길수록 잃음은 줄거나 0 에 머물고, 밀림은 늘거나 그대로다.',
    ja: 'ログは読む側に関係なく保持期間の分だけ残る。先頭が消されると遅いグループは前へ飛ばされ、読んでいない記録を失う。巻き戻しても届くのは残っている記録まで。この実行では保持が長いほど、失う数は減るか 0 のままで、遅れは伸びるか変わらない。',
    zh: '日志无论谁在读，都只保留保留长度内的记录。开头被删除后，慢的消费组会被弹到前面，丢失尚未读取的记录；回退也只能到达仍保留的记录。在这一轮中，保留越长，丢失减少或保持为 0，滞后增大或保持不变。',
    ar: 'يحتفظ السجل بعدد من السجلات بقدر ما يسمح به الاحتفاظ، أيًّا كان القارئ. عندما تُحذف المقدمة تقفز المجموعة البطيئة إلى الأمام وتفقد ما لم تقرأه، ولا يصل الرجوع إلا إلى ما بقي محفوظًا. في هذا التشغيل، كلما طال الاحتفاظ قلّ المفقود أو بقي 0، وزاد التأخر أو بقي كما هو.',
    es: 'Un log conserva solo tantos registros como permite su retención, lea quien lea. Al borrarse el principio, un grupo lento salta hacia delante y pierde lo que no había leído, y rebobinar solo alcanza lo que sigue guardado. En esta ejecución, más retención reduce los registros perdidos o los deja en 0, y aumenta el retraso o lo deja igual.',
    fr: 'Un journal ne garde que le nombre d’enregistrements permis par sa rétention, quel que soit le lecteur. Quand le début est effacé, un groupe lent saute en avant et perd ce qu’il n’avait pas lu, et un retour arrière n’atteint que ce qui reste. Dans cette exécution, plus de rétention réduit les pertes ou les laisse à 0, et augmente le retard ou le laisse inchangé.',
    hi: 'लॉग, पढ़ने वाला कोई भी हो, सिर्फ़ उतने रिकॉर्ड रखता है जितनी अवधारण अनुमति देती है। आगे का हिस्सा मिटने पर धीमा समूह आगे उछल जाता है और बिना पढ़े रिकॉर्ड खो देता है, और रिवाइंड केवल बचे हुए रिकॉर्ड तक पहुँचता है। इस रन में अवधारण जितनी लंबी, खोए रिकॉर्ड घटते हैं या 0 पर रहते हैं, और पिछड़ना बढ़ता है या वैसा ही रहता है।',
    id: 'Log hanya menyimpan catatan sebanyak yang diizinkan retensinya, siapa pun pembacanya. Saat bagian depan dihapus, grup lambat melompat maju dan kehilangan yang belum dibacanya, dan putar ulang hanya mencapai yang masih tersimpan. Dalam putaran ini, retensi lebih panjang mengurangi catatan hilang atau membiarkannya 0, dan menambah lag atau membiarkannya tetap.',
    pt: 'Um log guarda apenas tantos registros quanto a retenção permite, seja quem for o leitor. Quando o início é apagado, um grupo lento salta para a frente e perde o que não tinha lido, e retroceder só alcança o que ainda está guardado. Nesta execução, mais retenção reduz os registros perdidos ou os mantém em 0, e aumenta o atraso ou o mantém igual.',
  },
  algorithm: 'module:kafkaPattern',
  projector: 'module:kafkaPatternProjector',
  initialData: {
    type: 'kafka-pattern',
    stepMs: 500,
    motionMs: 280,
    values: [12, 5, 31, 8, 22, 17, 3, 26, 14, 9, 30, 6, 19, 11, 27, 2, 24, 15, 7, 28, 10, 21, 4, 18],
    fastId: 'live',
    slowId: 'batch',
    rewindTo: 0,
    retentions: [4, 8, 12, 16, 0],
    everies: [2, 3],
    retention: 8,
    every: 2,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'kafka-pattern-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'retention',
          name: 'retention',
          label: {
            en: 'Retention',
            ko: '보존 길이',
            ja: '保持の長さ',
            zh: '保留长度',
            ar: 'مدة الاحتفاظ',
            es: 'Retención',
            fr: 'Rétention',
            hi: 'अवधारण लंबाई',
            id: 'Retensi',
            pt: 'Retenção',
          },
          segments: [
            { value: 4, label: '4' },
            { value: 8, label: '8', default: true },
            { value: 12, label: '12' },
            { value: 16, label: '16' },
            {
              value: 0,
              label: {
                en: 'Forever',
                ko: '끝없음',
                ja: '無期限',
                zh: '永久',
                ar: 'دائم',
                es: 'Siempre',
                fr: 'Toujours',
                hi: 'असीमित',
                id: 'Selamanya',
                pt: 'Sempre',
              },
            },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'every',
          name: 'every',
          label: {
            en: 'Slow group every',
            ko: '느린 그룹 간격',
            ja: '遅いグループの間隔',
            zh: '慢组间隔',
            ar: 'فاصل المجموعة البطيئة',
            es: 'Grupo lento cada',
            fr: 'Groupe lent tous les',
            hi: 'धीमे समूह का अंतराल',
            id: 'Grup lambat tiap',
            pt: 'Grupo lento a cada',
          },
          segments: [
            { value: 2, label: '2', default: true },
            { value: 3, label: '3' },
          ],
        },
      ],
      metrics: [
        {
          name: 'batch-lost',
          label: {
            en: 'Batch lost',
            ko: '일괄 잃음',
            ja: '一括の損失',
            zh: '批量丢失',
            ar: 'مفقود الدفعة',
            es: 'Perdidos (lote)',
            fr: 'Perdus (lot)',
            hi: 'बैच खोया',
            id: 'Hilang (batch)',
            pt: 'Perdidos (lote)',
          },
          initial: 0,
        },
        {
          name: 'live-lost',
          label: {
            en: 'Real-time lost',
            ko: '실시간 잃음',
            ja: 'リアルタイムの損失',
            zh: '实时丢失',
            ar: 'مفقود الفوري',
            es: 'Perdidos (tiempo real)',
            fr: 'Perdus (temps réel)',
            hi: 'रीयल-टाइम खोया',
            id: 'Hilang (real-time)',
            pt: 'Perdidos (tempo real)',
          },
          initial: 0,
        },
        {
          name: 'batch-lag',
          label: {
            en: 'Batch lag',
            ko: '일괄 밀림',
            ja: '一括の遅れ',
            zh: '批量滞后',
            ar: 'تأخر الدفعة',
            es: 'Retraso (lote)',
            fr: 'Retard (lot)',
            hi: 'बैच पिछड़न',
            id: 'Lag (batch)',
            pt: 'Atraso (lote)',
          },
          initial: 0,
        },
        {
          name: 'retained',
          label: {
            en: 'Records kept',
            ko: '남은 기록',
            ja: '残る記録',
            zh: '保留的记录',
            ar: 'السجلات المحفوظة',
            es: 'Registros guardados',
            fr: 'Enregistrements gardés',
            hi: 'बचे रिकॉर्ड',
            id: 'Catatan tersimpan',
            pt: 'Registros guardados',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:kafka-pattern-imperative',
      label: {
        en: 'Offsets under retention',
        ko: '보존 아래의 오프셋',
        ja: '保持の下のオフセット',
        zh: '保留下的偏移量',
        ar: 'الإزاحات تحت الاحتفاظ',
        es: 'Offsets bajo retención',
        fr: 'Offsets sous rétention',
        hi: 'अवधारण के तहत ऑफ़सेट',
        id: 'Offset di bawah retensi',
        pt: 'Offsets sob retenção',
      },
    },
  },
  messages: {
    'label.live': {
      en: 'Real-time', ko: '실시간', ja: 'リアルタイム', zh: '实时', ar: 'فوري',
      es: 'Tiempo real', fr: 'Temps réel', hi: 'रीयल-टाइम', id: 'Real-time', pt: 'Tempo real',
    },
    'label.batch': {
      en: 'Batch', ko: '일괄', ja: '一括', zh: '批量', ar: 'دفعة',
      es: 'Lote', fr: 'Lot', hi: 'बैच', id: 'Batch', pt: 'Lote',
    },
    'label.log': {
      en: 'Log', ko: '로그', ja: 'ログ', zh: '日志', ar: 'السجل',
      es: 'Log', fr: 'Journal', hi: 'लॉग', id: 'Log', pt: 'Log',
    },
    'label.lost': {
      en: 'Lost', ko: '잃음', ja: '損失', zh: '丢失', ar: 'مفقود',
      es: 'Perdido', fr: 'Perdu', hi: 'खोया', id: 'Hilang', pt: 'Perdido',
    },
    'caption.empty': {
      en: 'Log is empty', ko: '빈 로그', ja: '空のログ', zh: '日志为空', ar: 'السجل فارغ',
      es: 'Log vacío', fr: 'Journal vide', hi: 'लॉग खाली है', id: 'Log kosong', pt: 'Log vazio',
    },
    'caption.tick': {
      en: 'Tick {tick} · log {start}..{last}',
      ko: '틱 {tick} · 로그 {start}..{last}',
      ja: 'ティック {tick} · ログ {start}..{last}',
      zh: '刻 {tick} · 日志 {start}..{last}',
      ar: 'النبضة {tick} · السجل {start}..{last}',
      es: 'Tic {tick} · log {start}..{last}',
      fr: 'Tic {tick} · journal {start}..{last}',
      hi: 'टिक {tick} · लॉग {start}..{last}',
      id: 'Tik {tick} · log {start}..{last}',
      pt: 'Tique {tick} · log {start}..{last}',
    },
    'caption.skip': {
      en: 'Skip: {from} → {to}',
      ko: '튕김: {from} → {to}',
      ja: '飛ばし: {from} → {to}',
      zh: '跳过: {from} → {to}',
      ar: 'قفز: {from} → {to}',
      es: 'Salto: {from} → {to}',
      fr: 'Saut : {from} → {to}',
      hi: 'उछाल: {from} → {to}',
      id: 'Lompat: {from} → {to}',
      pt: 'Salto: {from} → {to}',
    },
    'caption.read': {
      en: 'Batch read: {offset}',
      ko: '일괄 읽음: {offset}',
      ja: '一括の読み取り: {offset}',
      zh: '批量读取: {offset}',
      ar: 'قراءة الدفعة: {offset}',
      es: 'Lectura del lote: {offset}',
      fr: 'Lecture du lot : {offset}',
      hi: 'बैच ने पढ़ा: {offset}',
      id: 'Batch membaca: {offset}',
      pt: 'Leitura do lote: {offset}',
    },
    'caption.trim': {
      en: 'Log start → {start}',
      ko: '로그 앞 → {start}',
      ja: 'ログの先頭 → {start}',
      zh: '日志开头 → {start}',
      ar: 'بداية السجل → {start}',
      es: 'Inicio del log → {start}',
      fr: 'Début du journal → {start}',
      hi: 'लॉग की शुरुआत → {start}',
      id: 'Awal log → {start}',
      pt: 'Início do log → {start}',
    },
    'caption.append': {
      en: 'Append: {offset}',
      ko: '붙음: {offset}',
      ja: '追記: {offset}',
      zh: '追加: {offset}',
      ar: 'إلحاق: {offset}',
      es: 'Añadido: {offset}',
      fr: 'Ajout : {offset}',
      hi: 'जोड़ा: {offset}',
      id: 'Tambah: {offset}',
      pt: 'Anexado: {offset}',
    },
    'caption.rewind': {
      en: 'Rewind → {offset}',
      ko: '되감기 → {offset}',
      ja: '巻き戻し → {offset}',
      zh: '回退 → {offset}',
      ar: 'إرجاع → {offset}',
      es: 'Rebobinado → {offset}',
      fr: 'Retour → {offset}',
      hi: 'रिवाइंड → {offset}',
      id: 'Putar ulang → {offset}',
      pt: 'Retrocesso → {offset}',
    },
    'caption.asked': {
      en: 'Asked for {offset}',
      ko: '청한 자리: {offset}',
      ja: '求めた位置: {offset}',
      zh: '请求位置: {offset}',
      ar: 'الموضع المطلوب: {offset}',
      es: 'Pedido: {offset}',
      fr: 'Demandé : {offset}',
      hi: 'माँगा गया: {offset}',
      id: 'Diminta: {offset}',
      pt: 'Pedido: {offset}',
    },
  },
};
