/**
 * @piece 질문 — `font-display: swap` 인 웹 글꼴이 늦게 오면, 그동안 글은 어떻게
 * 보이고 글꼴이 오면 무엇이 바뀌는가?
 * @notation native — 주장이 `<link>` · `<p>` 태그와 `@font-face` 의
 * `font-display: swap` 동작 그 자체다.
 */
import type { FacetJson } from '@ffacet/core/runtime';
import { CONTROL_SET } from '@ffacet/core/runtime';

export const fontSwapFacet: FacetJson = {
  id: 'facet:fontSwap',
  title: {
    en: 'Font swap',
    ko: '글꼴 바뀌어 앉기',
    ja: 'フォントの入れ替え',
    zh: '字体替换',
    ar: 'تبديل الخط',
    es: 'Cambio de fuente',
    fr: 'Permutation de police',
    hi: 'फ़ॉन्ट बदलाव',
    id: 'Penggantian font',
    pt: 'Troca de fonte',
  },
  description: {
    en: 'Text paints first in a fallback font; when the web font finishes downloading, the same words are laid out again in its wider letters.',
    ko: '글은 대체 글꼴로 먼저 뜬다. 웹 글꼴이 다 받아지면 같은 낱말들이 그 넓은 폭으로 다시 놓인다.',
    ja: 'テキストはまず代替フォントで表示される。ウェブフォントの取得が終わると、同じ単語がその幅で再び配置される。',
    zh: '文本先用后备字体绘制。网页字体下载完成后,相同的词会按其更宽的字形重新排版。',
    ar: 'يُرسم النص أولاً بخط بديل. وعند اكتمال تنزيل خط الويب، تُعاد صياغة الكلمات نفسها بعرض حروفه الأوسع.',
    es: 'El texto se pinta primero con una fuente alternativa; cuando la fuente web termina de descargarse, las mismas palabras se disponen de nuevo con sus letras más anchas.',
    fr: "Le texte s'affiche d'abord avec une police de secours ; une fois la police web téléchargée, les mêmes mots sont redisposés avec ses lettres plus larges.",
    hi: 'पाठ पहले वैकल्पिक फ़ॉन्ट में दिखाया जाता है। वेब फ़ॉन्ट डाउनलोड होने के बाद वही शब्द उसके चौड़े अक्षरों में फिर से रखे जाते हैं।',
    id: 'Teks pertama kali tampil dengan font cadangan; setelah font web selesai diunduh, kata-kata yang sama disusun ulang dengan huruf yang lebih lebar.',
    pt: 'O texto é pintado primeiro com uma fonte substituta; quando a fonte web termina de baixar, as mesmas palavras são dispostas novamente com suas letras mais largas.',
  },
  algorithm: 'module:fontSwap',
  scene: 'module:fontSwapScene',
  initialData: {
    type: 'font-swap',
    linkTag: '<link rel="stylesheet" href="site.css">',
    paragraphTag: '<p>Fonts often arrive later than the words they dress</p>',
    fontFaceRule: '@font-face { font-family: Brand; src: url(brand.woff2); font-display: swap; }',
    paragraphRule: 'p { font-family: Brand, sans-serif; }',
    words: ['Fonts', 'often', 'arrive', 'later', 'than', 'the', 'words', 'they', 'dress'],
    boxWidthPx: 220,
    fallbackCharPx: 8,
    fallbackSpacePx: 8,
    brandCharPx: 10,
    brandSpacePx: 10,
    cssFile: 'site.css',
    fontFile: 'brand.woff2',
    cssArriveMs: 100,
    fontArriveMs: 400,
    stepMs: 1800,
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'font-swap-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.blank': {
      en: 'Nothing has rendered yet.',
      ko: '아직 아무것도 그려지지 않았다.',
      ja: 'まだ何も描画されていない。',
      zh: '尚未绘制任何内容。',
      ar: 'لم يُرسم شيء بعد.',
      es: 'Todavía no se ha pintado nada.',
      fr: "Rien n'a encore été affiché.",
      hi: 'अभी तक कुछ भी नहीं दिखा है।',
      id: 'Belum ada yang digambar.',
      pt: 'Nada foi desenhado ainda.',
    },
    'caption.firstPaint': {
      en: '{file} arrived. First paint in fallback: {lines} lines.',
      ko: '{file} 도착. 첫 장은 대체 글꼴 — 줄 수 {lines}.',
      ja: '{file} が到着。フォールバックでの初描画 — 行数 {lines}。',
      zh: '{file} 已到达。首次绘制使用后备字体 — 行数 {lines}。',
      ar: 'وصل {file}. أول رسم بالخط البديل — عدد الأسطر {lines}.',
      es: '{file} llegó. Primer pintado con la fuente alternativa: {lines} líneas.',
      fr: "{file} est arrivé. Premier affichage avec la police de secours : {lines} lignes.",
      hi: '{file} पहुंचा। वैकल्पिक फ़ॉन्ट में पहला रेंडर — पंक्तियाँ {lines}।',
      id: '{file} tiba. Gambar pertama dengan font cadangan — jumlah baris {lines}.',
      pt: '{file} chegou. Primeira renderização com a fonte substituta: {lines} linhas.',
    },
    'caption.fontRequested': {
      en: 'Font requested: {file}.',
      ko: '글꼴 요청됨: {file}.',
      ja: 'フォント要求: {file}。',
      zh: '已请求字体:{file}。',
      ar: 'تم طلب الخط: {file}.',
      es: 'Fuente solicitada: {file}.',
      fr: 'Police demandée : {file}.',
      hi: 'फ़ॉन्ट अनुरोध किया गया: {file}।',
      id: 'Font diminta: {file}.',
      pt: 'Fonte solicitada: {file}.',
    },
    'caption.fontArrived': {
      en: 'Font arrived: {file}.',
      ko: '글꼴 도착: {file}.',
      ja: 'フォント到着: {file}。',
      zh: '字体已到达:{file}。',
      ar: 'وصل الخط: {file}.',
      es: 'Fuente llegada: {file}.',
      fr: 'Police arrivée : {file}.',
      hi: 'फ़ॉन्ट पहुंचा: {file}।',
      id: 'Font tiba: {file}.',
      pt: 'Fonte chegou: {file}.',
    },
    'caption.repaint': {
      en: 'Repainted in Brand — {lines} lines now, {moved} words moved down.',
      ko: '다시 놓임 — 이제 줄 수 {lines}, 다음 줄로 넘어간 낱말 {moved}.',
      ja: 'Brand で再描画 — 行数は今 {lines}、下の行に移った単語 {moved}。',
      zh: '已用 Brand 重新绘制 — 现在行数 {lines},换行的词 {moved}。',
      ar: 'أعيد الرسم بخط Brand — عدد الأسطر الآن {lines}، الكلمات التي انتقلت لسطر جديد {moved}.',
      es: 'Repintado con Brand — ahora {lines} líneas, {moved} palabras bajaron de línea.',
      fr: 'Réaffiché avec Brand — désormais {lines} lignes, {moved} mots passés à la ligne suivante.',
      hi: 'Brand में फिर से रेंडर — अब पंक्तियाँ {lines}, अगली पंक्ति में गए शब्द {moved}।',
      id: 'Digambar ulang dengan Brand — kini baris {lines}, kata yang pindah baris {moved}.',
      pt: 'Repintado com Brand — agora {lines} linhas, {moved} palavras desceram de linha.',
    },
  },
};
