import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 행렬식이 0 인 행렬로 옮기면, 옮긴 자리만 보고 어느 점에서 왔는지 알 수 있는가.
 */
export const determinantZeroCollapseFacet: FacetJson = {
  id: 'facet:determinantZeroCollapse',
  title: {
    en: 'A zero determinant stacks points',
    ko: '행렬식이 0 이면 점이 포개진다',
    ja: '行列式が 0 なら点が重なる',
    zh: '行列式为 0 时点会重叠',
    ar: 'المحدد الصفري يُكدّس النقاط',
    es: 'Un determinante cero apila los puntos',
    fr: 'Un déterminant nul empile les points',
    hi: 'शून्य सारणिक बिंदुओं को एक पर एक रख देता है',
    id: 'Determinan nol menumpuk titik',
    pt: 'Um determinante zero empilha os pontos',
  },
  description: {
    en: 'Move points with a matrix whose determinant is 0 — can you tell from the landing spot which point it came from?',
    ko: '행렬식이 0 인 행렬로 옮기면, 옮긴 자리만 보고 어느 점에서 왔는지 알 수 있는가',
    ja: '行列式が 0 の行列で点を移すと、移った先だけを見てどの点から来たか分かるか',
    zh: '用行列式为 0 的矩阵移动点，只看落点能否知道它来自哪个点？',
    ar: 'إذا نقلنا النقاط بمصفوفة محددها 0، فهل يمكن أن نعرف من موضع الوصول وحده من أي نقطة جاءت؟',
    es: 'Si movemos puntos con una matriz de determinante 0, ¿se puede saber por el lugar de llegada de qué punto vino?',
    fr: 'Si l’on déplace des points avec une matrice de déterminant 0, peut-on savoir d’après le point d’arrivée d’où il vient ?',
    hi: 'सारणिक 0 वाले आव्यूह से बिंदु खिसकाएँ, तो क्या पहुँचने की जगह देखकर बता सकते हैं कि बिंदु कहाँ से आया?',
    id: 'Jika titik dipindahkan dengan matriks berdeterminan 0, dapatkah kita tahu dari tempat tibanya titik itu berasal dari mana?',
    pt: 'Se movermos pontos com uma matriz de determinante 0, dá para saber pelo lugar de chegada de que ponto ele veio?',
  },
  algorithm: 'module:determinantZeroCollapse',
  scene: 'module:determinantZeroCollapseScene',
  initialData: {
    type: 'determinant-zero-collapse',
    stepMs: 1400,
    matrix: [
      [2, 1],
      [4, 2],
    ],
    points: [
      [1, 0],
      [1, 1],
      [0, 2],
      [0, 3],
      [2, -2],
      [2, -1],
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Points: {n} · spots: {m}',
      ko: '점 {n} · 자리 {m}',
      ja: '点 {n} · 位置 {m}',
      zh: '点 {n} · 位置 {m}',
      ar: 'النقاط: {n} · المواضع: {m}',
      es: 'Puntos: {n} · lugares: {m}',
      fr: 'Points : {n} · positions : {m}',
      hi: 'बिंदु: {n} · जगहें: {m}',
      id: 'Titik: {n} · tempat: {m}',
      pt: 'Pontos: {n} · lugares: {m}',
    },
    'caption.move': {
      en: '{from} → {to} · arrived here: {n}',
      ko: '{from} → {to} · 여기 온 점 {n}',
      ja: '{from} → {to} · ここに来た点 {n}',
      zh: '{from} → {to} · 落在此处的点 {n}',
      ar: '{from} → {to} · النقاط الواصلة هنا: {n}',
      es: '{from} → {to} · llegados aquí: {n}',
      fr: '{from} → {to} · arrivés ici : {n}',
      hi: '{from} → {to} · यहाँ पहुँचे बिंदु: {n}',
      id: '{from} → {to} · tiba di sini: {n}',
      pt: '{from} → {to} · chegaram aqui: {n}',
    },
    'caption.done': {
      en: 'Points {n} → spots {m} · det = {a}·{d} − {b}·{c} = {det}',
      ko: '점 {n} → 자리 {m} · det = {a}·{d} − {b}·{c} = {det}',
      ja: '点 {n} → 位置 {m} · det = {a}·{d} − {b}·{c} = {det}',
      zh: '点 {n} → 位置 {m} · det = {a}·{d} − {b}·{c} = {det}',
      ar: 'النقاط {n} → المواضع {m} · det = {a}·{d} − {b}·{c} = {det}',
      es: 'Puntos {n} → lugares {m} · det = {a}·{d} − {b}·{c} = {det}',
      fr: 'Points {n} → positions {m} · det = {a}·{d} − {b}·{c} = {det}',
      hi: 'बिंदु {n} → जगहें {m} · det = {a}·{d} − {b}·{c} = {det}',
      id: 'Titik {n} → tempat {m} · det = {a}·{d} − {b}·{c} = {det}',
      pt: 'Pontos {n} → lugares {m} · det = {a}·{d} − {b}·{c} = {det}',
    },
    'label.matrix': {
      en: 'A =',
      ko: 'A =',
      ja: 'A =',
      zh: 'A =',
      ar: 'A =',
      es: 'A =',
      fr: 'A =',
      hi: 'A =',
      id: 'A =',
      pt: 'A =',
    },
    'label.spot': {
      en: 'At {p}',
      ko: '자리 {p}',
      ja: '位置 {p}',
      zh: '位置 {p}',
      ar: 'الموضع {p}',
      es: 'En {p}',
      fr: 'En {p}',
      hi: 'जगह {p}',
      id: 'Di {p}',
      pt: 'Em {p}',
    },
    'label.arrived': {
      en: 'Arrived: {n}',
      ko: '여기 온 점 {n}',
      ja: '来た点 {n}',
      zh: '到达的点 {n}',
      ar: 'الواصلة: {n}',
      es: 'Llegados: {n}',
      fr: 'Arrivés : {n}',
      hi: 'पहुँचे: {n}',
      id: 'Tiba: {n}',
      pt: 'Chegaram: {n}',
    },
  },
  blocks: {
    stage: { type: 'determinant-zero-collapse-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
