/**
 * @piece
 * 질문: 밀어 주는 기울기가 0 인 평지에서 모멘텀은 멈추는가.
 *
 * 갱신마다 움직임이 이어 받은 몫(β·v)과 새로 민 몫(−η·g)으로 나뉘고, 평지에서는 새로 민 몫이 0 인데도
 * 이어 받은 몫만으로 w 가 같은 쪽으로 건너간다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const carryVelocityFacet: FacetJson = {
  id: 'facet:carryVelocity',
  title: {
    en: 'Momentum carries across the flat',
    ko: '모멘텀은 평지를 이어 받아 건넌다',
    ja: 'モーメンタムは平地を引き継いで渡る',
    zh: '动量借着惯性越过平地',
    ar: 'الزخم يعبر المنبسط بما حمله',
    es: 'El momento cruza el llano con lo heredado',
    fr: 'L’inertie traverse le plat avec ce qu’elle porte',
    hi: 'संवेग आगे लाए हिस्से से समतल पार करता है',
    id: 'Momentum menyeberangi dataran dengan bawaannya',
    pt: 'O momento atravessa o plano com o que herdou',
  },
  description: {
    en: 'Each update splits into a carried share and a new push. On the flat the new push is zero, yet w keeps going on what it carried.',
    ko: '갱신마다 움직임이 이어 받은 몫과 새로 민 몫으로 나뉜다. 평지에서 새로 민 몫이 0 이어도 w 는 이어 받은 몫으로 계속 간다.',
    ja: '更新ごとに動きが引き継いだ分と新たに押した分に分かれる。平地で新たな押しが 0 でも、w は引き継いだ分で進み続ける。',
    zh: '每次更新的移动分成继承部分与新推部分。在平地上新推部分为 0，w 仍靠继承部分继续前进。',
    ar: 'تنقسم كل خطوة تحديث إلى جزء محمول ودفعة جديدة. على المنبسط تكون الدفعة الجديدة صفرًا، ومع ذلك يواصل w التقدم بما حمله.',
    es: 'Cada actualización se divide en una parte heredada y un empuje nuevo. En el llano el empuje nuevo es cero, pero w sigue avanzando con lo heredado.',
    fr: 'Chaque mise à jour se divise en une part héritée et une nouvelle poussée. Sur le plat la poussée est nulle, mais w continue grâce à ce qu’il porte.',
    hi: 'हर अपडेट में चाल दो हिस्सों में बँटती है: आगे लाया हिस्सा और नया धक्का। समतल पर नया धक्का शून्य है, फिर भी w आगे लाए हिस्से से चलता रहता है।',
    id: 'Setiap pembaruan terbagi menjadi bagian bawaan dan dorongan baru. Di dataran dorongan baru nol, tetapi w tetap melaju dengan bawaannya.',
    pt: 'Cada atualização se divide em uma parte herdada e um novo empurrão. No plano o empurrão é zero, mas w continua com o que herdou.',
  },
  algorithm: 'module:carryVelocity',
  scene: 'module:carryVelocityScene',
  initialData: {
    type: 'carry-velocity',
    stepMs: 1100,
    breaks: [1.1, 2.5],
    pieces: [
      { intercept: 3, slope: -1 },
      { intercept: 1.9, slope: 0 },
      { intercept: 4.4, slope: -1 },
    ],
    beta: 0.9,
    eta: 0.2,
    w0: 0,
    v0: 0,
    updates: 8,
  },
  shuffleOnReset: false,
  messages: {
    'legend.carried': {
      en: 'carried β·v',
      ko: '이어 받은 몫 β·v',
      ja: '引き継いだ分 β·v',
      zh: '继承部分 β·v',
      ar: 'الجزء المحمول β·v',
      es: 'parte heredada β·v',
      fr: 'part héritée β·v',
      hi: 'आगे लाया हिस्सा β·v',
      id: 'bagian bawaan β·v',
      pt: 'parte herdada β·v',
    },
    'legend.push': {
      en: 'new push −η·g',
      ko: '새로 민 몫 −η·g',
      ja: '新たに押した分 −η·g',
      zh: '新推部分 −η·g',
      ar: 'الدفعة الجديدة −η·g',
      es: 'empuje nuevo −η·g',
      fr: 'nouvelle poussée −η·g',
      hi: 'नया धक्का −η·g',
      id: 'dorongan baru −η·g',
      pt: 'novo empurrão −η·g',
    },
    formula: {
      en: 'v ← β·v − η·g · w ← w + v',
      ko: 'v ← β·v − η·g · w ← w + v',
      ja: 'v ← β·v − η·g · w ← w + v',
      zh: 'v ← β·v − η·g · w ← w + v',
      ar: 'v ← β·v − η·g · w ← w + v',
      es: 'v ← β·v − η·g · w ← w + v',
      fr: 'v ← β·v − η·g · w ← w + v',
      hi: 'v ← β·v − η·g · w ← w + v',
      id: 'v ← β·v − η·g · w ← w + v',
      pt: 'v ← β·v − η·g · w ← w + v',
    },
    params: {
      en: 'β {b} · η {e}',
      ko: 'β {b} · η {e}',
      ja: 'β {b} · η {e}',
      zh: 'β {b} · η {e}',
      ar: 'β {b} · η {e}',
      es: 'β {b} · η {e}',
      fr: 'β {b} · η {e}',
      hi: 'β {b} · η {e}',
      id: 'β {b} · η {e}',
      pt: 'β {b} · η {e}',
    },
    'label.flat': {
      en: 'flat · g {g}',
      ko: '평지 · g {g}',
      ja: '平地 · g {g}',
      zh: '平地 · g {g}',
      ar: 'منبسط · g {g}',
      es: 'llano · g {g}',
      fr: 'plat · g {g}',
      hi: 'समतल · g {g}',
      id: 'datar · g {g}',
      pt: 'plano · g {g}',
    },
    'label.slope': {
      en: 'slope · g {g}',
      ko: '비탈 · g {g}',
      ja: '坂 · g {g}',
      zh: '斜坡 · g {g}',
      ar: 'منحدر · g {g}',
      es: 'pendiente · g {g}',
      fr: 'pente · g {g}',
      hi: 'ढलान · g {g}',
      id: 'lereng · g {g}',
      pt: 'rampa · g {g}',
    },
    'col.carried': {
      en: 'β·v',
      ko: 'β·v',
      ja: 'β·v',
      zh: 'β·v',
      ar: 'β·v',
      es: 'β·v',
      fr: 'β·v',
      hi: 'β·v',
      id: 'β·v',
      pt: 'β·v',
    },
    'col.push': {
      en: '−η·g',
      ko: '−η·g',
      ja: '−η·g',
      zh: '−η·g',
      ar: '−η·g',
      es: '−η·g',
      fr: '−η·g',
      hi: '−η·g',
      id: '−η·g',
      pt: '−η·g',
    },
    'col.v': {
      en: 'v',
      ko: 'v',
      ja: 'v',
      zh: 'v',
      ar: 'v',
      es: 'v',
      fr: 'v',
      hi: 'v',
      id: 'v',
      pt: 'v',
    },
    'label.row': {
      en: '#{k}',
      ko: '#{k}',
      ja: '#{k}',
      zh: '#{k}',
      ar: '#{k}',
      es: '#{k}',
      fr: '#{k}',
      hi: '#{k}',
      id: '#{k}',
      pt: '#{k}',
    },
    'label.marker': {
      en: 'w {w} · L {l}',
      ko: 'w {w} · L {l}',
      ja: 'w {w} · L {l}',
      zh: 'w {w} · L {l}',
      ar: 'w {w} · L {l}',
      es: 'w {w} · L {l}',
      fr: 'w {w} · L {l}',
      hi: 'w {w} · L {l}',
      id: 'w {w} · L {l}',
      pt: 'w {w} · L {l}',
    },
    'caption.start': {
      en: 'Start · w {w} · v {v}',
      ko: '처음 모습 · w {w} · v {v}',
      ja: '最初 · w {w} · v {v}',
      zh: '起点 · w {w} · v {v}',
      ar: 'البداية · w {w} · v {v}',
      es: 'Inicio · w {w} · v {v}',
      fr: 'Départ · w {w} · v {v}',
      hi: 'शुरुआत · w {w} · v {v}',
      id: 'Awal · w {w} · v {v}',
      pt: 'Início · w {w} · v {v}',
    },
    'caption.slope': {
      en: 'Update #{k} · slope, g {g}',
      ko: '갱신 #{k} · 비탈, g {g}',
      ja: '更新 #{k} · 坂, g {g}',
      zh: '更新 #{k} · 斜坡，g {g}',
      ar: 'التحديث #{k} · منحدر، g {g}',
      es: 'Actualización #{k} · pendiente, g {g}',
      fr: 'Mise à jour #{k} · pente, g {g}',
      hi: 'अपडेट #{k} · ढलान, g {g}',
      id: 'Pembaruan #{k} · lereng, g {g}',
      pt: 'Atualização #{k} · rampa, g {g}',
    },
    'caption.flat': {
      en: 'Update #{k} · flat, g {g}',
      ko: '갱신 #{k} · 평지, g {g}',
      ja: '更新 #{k} · 平地, g {g}',
      zh: '更新 #{k} · 平地，g {g}',
      ar: 'التحديث #{k} · منبسط، g {g}',
      es: 'Actualización #{k} · llano, g {g}',
      fr: 'Mise à jour #{k} · plat, g {g}',
      hi: 'अपडेट #{k} · समतल, g {g}',
      id: 'Pembaruan #{k} · datar, g {g}',
      pt: 'Atualização #{k} · plano, g {g}',
    },
    'caption.parts': {
      en: 'Carried β × {vp} = {c} · New push {p} → w {w}',
      ko: '이어 받은 몫 β × {vp} = {c} · 새로 민 몫 {p} → w {w}',
      ja: '引き継ぎ β × {vp} = {c} · 新たな押し {p} → w {w}',
      zh: '继承 β × {vp} = {c} · 新推 {p} → w {w}',
      ar: 'المحمول β × {vp} = {c} · الدفعة الجديدة {p} → w {w}',
      es: 'Heredado β × {vp} = {c} · Empuje nuevo {p} → w {w}',
      fr: 'Héritée β × {vp} = {c} · Nouvelle poussée {p} → w {w}',
      hi: 'आगे लाया β × {vp} = {c} · नया धक्का {p} → w {w}',
      id: 'Bawaan β × {vp} = {c} · Dorongan baru {p} → w {w}',
      pt: 'Herdada β × {vp} = {c} · Novo empurrão {p} → w {w}',
    },
  },
  blocks: {
    stage: { type: 'carry-velocity-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
