/**
 * 광선 추적 — 평면 단면에서 픽셀 12 칸마다 광선 하나가 유리 원을 굴절로 지나 줄무늬 벽에 닿고,
 * 그 자리에서 빛으로 쏜 그림자 광선이 칸의 밝기를 정한다. 손잡이는 유리의 굴절률.
 *
 * initialData 는 구조(눈 · 영상 줄 · 유리 · 벽 띠 · 빛 · 그림자 배율 · 사다리)뿐이다.
 * 픽셀 중심 · 교차 · 꺾인 방향 · 벽 x · 띠 · 그림자 판정 · 칸 색 · 각은 알고리즘이 셈한다.
 * `defaultIndex` 는 손잡이의 기본 구간(segments 의 default)과 같다 — 테스트가 잠근다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const rayTracingBaseFacet: FacetJson = {
  id: 'facet:rayTracingBase',
  title: {
    en: 'Ray Tracing',
    ko: '광선 추적',
    ja: 'レイトレーシング',
    zh: '光线追踪',
    ar: 'تتبع الأشعة',
    es: 'Trazado de rayos',
    fr: 'Lancer de rayons',
    hi: 'रे ट्रेसिंग',
    id: 'Penelusuran sinar',
    pt: 'Traçado de raios',
  },
  description: {
    en: 'One ray per pixel crosses a flat slice of the scene: it bends into and out of a glass disc, lands on a striped wall, and a shadow ray from that spot to the light decides whether the cell is lit. Raising the refractive index from 1.0 to 2.0 grows the largest bend from 0° to 73.6°; from 1.4 up, the six rays through the glass reach the wall in reversed order.',
    ko: '픽셀마다 광선 하나가 장면의 평면 단면을 지난다. 유리 원에 들어가고 나오며 꺾여 줄무늬 벽에 닿고, 그 자리에서 빛으로 쏜 그림자 광선이 칸의 밝기를 정한다. 굴절률을 1.0 에서 2.0 으로 올리면 가장 크게 꺾인 각이 0° 에서 73.6° 로 커지고, 1.4 부터는 유리를 지난 여섯 광선이 거꾸로 된 차례로 벽에 닿는다.',
    ja: '画素ごとに一本の光線が場面の平面断面を横切る。ガラスの円に入って出るときに曲がり、縞模様の壁に当たり、その点から光源へ放つシャドウレイがマスの明るさを決める。屈折率を 1.0 から 2.0 に上げると最大の曲がりは 0° から 73.6° に増え、1.4 以上ではガラスを通る六本の光線が逆の順序で壁に届く。',
    zh: '每个像素发出一条光线，穿过场景的一个平面截面：进出玻璃圆时发生折射，落在条纹墙上，再从该点向光源发出阴影光线，决定该格是否被照亮。把折射率从 1.0 提高到 2.0，最大偏折角从 0° 增至 73.6°；从 1.4 起，穿过玻璃的六条光线以颠倒的顺序到达墙面。',
    ar: 'شعاع واحد لكل بكسل يعبر مقطعاً مستوياً من المشهد: ينكسر داخلاً إلى قرص زجاجي وخارجاً منه، ويصل إلى جدار مخطط، ثم يقرر شعاع ظل من تلك النقطة إلى الضوء هل الخلية مضاءة. رفع معامل الانكسار من 1.0 إلى 2.0 يزيد أكبر انحراف من 0° إلى 73.6°، ومن 1.4 فما فوق تصل الأشعة الستة المارة بالزجاج إلى الجدار بترتيب معكوس.',
    es: 'Un rayo por píxel cruza un corte plano de la escena: se desvía al entrar y salir de un disco de vidrio, llega a una pared a franjas y un rayo de sombra desde ese punto hacia la luz decide si la celda queda iluminada. Subir el índice de refracción de 1.0 a 2.0 hace crecer el mayor desvío de 0° a 73.6°; desde 1.4, los seis rayos que atraviesan el vidrio llegan a la pared en orden invertido.',
    fr: 'Un rayon par pixel traverse une coupe plane de la scène : il se réfracte en entrant dans un disque de verre et en en sortant, atteint un mur rayé, puis un rayon d’ombre de ce point vers la lumière décide si la case est éclairée. Monter l’indice de réfraction de 1.0 à 2.0 fait passer la plus forte déviation de 0° à 73.6° ; dès 1.4, les six rayons qui traversent le verre atteignent le mur dans l’ordre inverse.',
    hi: 'हर पिक्सेल से एक किरण दृश्य के एक समतल खंड को पार करती है: काँच की चकती में घुसते और निकलते समय मुड़ती है, धारीदार दीवार पर पहुँचती है, और उस बिंदु से प्रकाश की ओर छाया किरण तय करती है कि खाना रोशन है या नहीं। अपवर्तनांक 1.0 से 2.0 करने पर सबसे बड़ा मोड़ 0° से 73.6° हो जाता है; 1.4 से ऊपर काँच से गुज़री छह किरणें उलटे क्रम में दीवार पर पहुँचती हैं।',
    id: 'Satu sinar per piksel melintasi irisan datar adegan: membelok saat masuk dan keluar cakram kaca, mendarat di dinding bergaris, lalu sinar bayangan dari titik itu ke cahaya menentukan apakah sel terang. Menaikkan indeks bias dari 1.0 ke 2.0 memperbesar belokan terbesar dari 0° menjadi 73.6°; mulai 1.4, enam sinar yang melewati kaca tiba di dinding dengan urutan terbalik.',
    pt: 'Um raio por pixel atravessa um corte plano da cena: desvia ao entrar e sair de um disco de vidro, chega a uma parede listrada e um raio de sombra desse ponto até a luz decide se a célula fica iluminada. Subir o índice de refração de 1.0 para 2.0 faz o maior desvio crescer de 0° para 73.6°; a partir de 1.4, os seis raios que passam pelo vidro chegam à parede em ordem invertida.',
  },
  algorithm: 'module:rayTracingBase',
  projector: 'module:rayTracingBaseProjector',
  initialData: {
    type: 'ray-tracing-base',
    stepMs: 1800,
    motionMs: 700,
    eye: { x: 0, y: 0 },
    row: { y: 2, left: -1.1, right: 1.1, count: 12 },
    glass: { id: 'glass', cx: 0, cy: 6, r: 1.5 },
    wall: {
      id: 'wall',
      y: 12,
      left: -9,
      bandWidth: 2,
      bands: [
        [0.85, 0.25, 0.25],
        [0.9, 0.5, 0.2],
        [0.9, 0.8, 0.25],
        [0.55, 0.8, 0.3],
        [0.25, 0.7, 0.45],
        [0.25, 0.65, 0.75],
        [0.3, 0.45, 0.85],
        [0.5, 0.35, 0.8],
        [0.75, 0.35, 0.7],
      ],
    },
    light: { id: 'light', x: -7, y: 0 },
    shadowScale: 0.3,
    indices: [1.0, 1.2, 1.4, 1.6, 2.0],
    defaultIndex: 1.6,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'ray-tracing-base-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'refractive-index',
          name: 'refractive-index',
          label: {
            en: 'Refractive index',
            ko: '굴절률',
            ja: '屈折率',
            zh: '折射率',
            ar: 'معامل الانكسار',
            es: 'Índice de refracción',
            fr: 'Indice de réfraction',
            hi: 'अपवर्तनांक',
            id: 'Indeks bias',
            pt: 'Índice de refração',
          },
          segments: [
            { value: 1.0, label: '1.0' },
            { value: 1.2, label: '1.2' },
            { value: 1.4, label: '1.4' },
            { value: 1.6, label: '1.6', default: true },
            { value: 2.0, label: '2.0' },
          ],
        },
      ],
      metrics: [
        {
          name: 'max-bend',
          label: {
            en: 'Largest bend (°)',
            ko: '가장 크게 꺾인 각 (°)',
            ja: '最大の曲がり (°)',
            zh: '最大偏折角 (°)',
            ar: 'أكبر انحراف (°)',
            es: 'Mayor desvío (°)',
            fr: 'Plus forte déviation (°)',
            hi: 'सबसे बड़ा मोड़ (°)',
            id: 'Belokan terbesar (°)',
            pt: 'Maior desvio (°)',
          },
          initial: 0,
        },
        {
          name: 'flipped-pairs',
          label: {
            en: 'Flipped pairs',
            ko: '뒤집힌 짝',
            ja: '逆転ペア',
            zh: '颠倒对',
            ar: 'أزواج مقلوبة',
            es: 'Pares invertidos',
            fr: 'Paires inversées',
            hi: 'उलटे जोड़े',
            id: 'Pasangan terbalik',
            pt: 'Pares invertidos',
          },
          initial: 0,
        },
        {
          name: 'shadowed-pixels',
          label: {
            en: 'Pixels in shadow',
            ko: '그림자 픽셀',
            ja: '影の画素',
            zh: '阴影像素',
            ar: 'بكسلات في الظل',
            es: 'Píxeles en sombra',
            fr: 'Pixels à l’ombre',
            hi: 'छाया में पिक्सेल',
            id: 'Piksel dalam bayangan',
            pt: 'Pixels na sombra',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:ray-tracing-base-imperative',
      label: {
        en: 'Tracing one row',
        ko: '한 줄 광선 추적',
        ja: '1 行の光線追跡',
        zh: '追踪一行光线',
        ar: 'تتبع صف واحد',
        es: 'Trazar una fila',
        fr: 'Tracer une ligne',
        hi: 'एक पंक्ति का ट्रेस',
        id: 'Menelusuri satu baris',
        pt: 'Traçar uma linha',
      },
    },
  },
  messages: {
    'label.eye': { en: 'eye', ko: '눈', ja: '目', zh: '眼睛', ar: 'العين', es: 'ojo', fr: 'œil', hi: 'आँख', id: 'mata', pt: 'olho' },
    'label.row': {
      en: 'image row',
      ko: '영상 줄',
      ja: '画像の行',
      zh: '图像行',
      ar: 'صف الصورة',
      es: 'fila de imagen',
      fr: 'ligne d’image',
      hi: 'छवि पंक्ति',
      id: 'baris gambar',
      pt: 'linha da imagem',
    },
    'label.glass': { en: 'glass', ko: '유리', ja: 'ガラス', zh: '玻璃', ar: 'الزجاج', es: 'vidrio', fr: 'verre', hi: 'काँच', id: 'kaca', pt: 'vidro' },
    'label.wall': { en: 'wall', ko: '벽', ja: '壁', zh: '墙', ar: 'الجدار', es: 'pared', fr: 'mur', hi: 'दीवार', id: 'dinding', pt: 'parede' },
    'label.light': { en: 'light', ko: '빛', ja: '光源', zh: '光源', ar: 'الضوء', es: 'luz', fr: 'lumière', hi: 'प्रकाश', id: 'cahaya', pt: 'luz' },
    'label.ray': { en: 'ray', ko: '광선', ja: '光線', zh: '光线', ar: 'شعاع', es: 'rayo', fr: 'rayon', hi: 'किरण', id: 'sinar', pt: 'raio' },
    'label.shadowRay': {
      en: 'shadow ray',
      ko: '그림자 광선',
      ja: 'シャドウレイ',
      zh: '阴影光线',
      ar: 'شعاع الظل',
      es: 'rayo de sombra',
      fr: 'rayon d’ombre',
      hi: 'छाया किरण',
      id: 'sinar bayangan',
      pt: 'raio de sombra',
    },
    'label.straight': {
      en: 'straight-line landing',
      ko: '곧게 갔다면 닿을 자리',
      ja: '直進した場合の着地点',
      zh: '直线到达点',
      ar: 'موضع الوصول المستقيم',
      es: 'llegada en línea recta',
      fr: 'arrivée en ligne droite',
      hi: 'सीधी रेखा का बिंदु',
      id: 'titik jika lurus',
      pt: 'chegada em linha reta',
    },
    'stage.index': { en: 'n {n}', ko: 'n {n}', ja: 'n {n}', zh: 'n {n}', ar: 'n {n}', es: 'n {n}', fr: 'n {n}', hi: 'n {n}', id: 'n {n}', pt: 'n {n}' },
    'caption.init': {
      en: 'The glass takes its refractive index; the rays are next',
      ko: '유리의 굴절률이 정해졌다 — 이제 광선을 쏜다',
      ja: 'ガラスの屈折率が決まった — 次は光線を放つ',
      zh: '玻璃的折射率已设定 — 接下来发射光线',
      ar: 'حُدِّد معامل انكسار الزجاج — الأشعة تالياً',
      es: 'El vidrio toma su índice de refracción; ahora los rayos',
      fr: 'Le verre prend son indice de réfraction ; place aux rayons',
      hi: 'काँच का अपवर्तनांक तय हुआ — अब किरणें',
      id: 'Kaca mendapat indeks biasnya; berikutnya sinar',
      pt: 'O vidro recebe seu índice de refração; agora os raios',
    },
    'caption.shoot': {
      en: 'One ray per pixel travels to the first thing it hits',
      ko: '픽셀마다 광선 하나가 처음 닿는 곳까지 간다',
      ja: '画素ごとに光線が一本、最初に当たる所まで進む',
      zh: '每个像素发出一条光线，直到第一次碰到物体',
      ar: 'شعاع واحد لكل بكسل يسير حتى أول ما يصطدم به',
      es: 'Un rayo por píxel viaja hasta lo primero que toca',
      fr: 'Un rayon par pixel file jusqu’au premier obstacle',
      hi: 'हर पिक्सेल से एक किरण पहली टक्कर तक जाती है',
      id: 'Satu sinar per piksel melaju sampai benda pertama yang dikenainya',
      pt: 'Um raio por pixel viaja até a primeira coisa que atinge',
    },
    'stat.shoot': {
      en: 'rays {rays} · glass {glass} · wall {wall}',
      ko: '광선 {rays} · 유리 {glass} · 벽 {wall}',
      ja: '光線 {rays} · ガラス {glass} · 壁 {wall}',
      zh: '光线 {rays} · 玻璃 {glass} · 墙 {wall}',
      ar: 'أشعة {rays} · زجاج {glass} · جدار {wall}',
      es: 'rayos {rays} · vidrio {glass} · pared {wall}',
      fr: 'rayons {rays} · verre {glass} · mur {wall}',
      hi: 'किरणें {rays} · काँच {glass} · दीवार {wall}',
      id: 'sinar {rays} · kaca {glass} · dinding {wall}',
      pt: 'raios {rays} · vidro {glass} · parede {wall}',
    },
    'caption.enter': {
      en: 'Entering the glass, each ray bends toward the normal',
      ko: '유리에 들어가며 광선이 법선 쪽으로 꺾인다',
      ja: 'ガラスに入るとき、光線は法線の側へ曲がる',
      zh: '进入玻璃时，光线向法线方向弯折',
      ar: 'عند دخول الزجاج ينكسر كل شعاع نحو العمودي',
      es: 'Al entrar en el vidrio, cada rayo se acerca a la normal',
      fr: 'En entrant dans le verre, chaque rayon se rapproche de la normale',
      hi: 'काँच में प्रवेश करते हुए हर किरण अभिलंब की ओर मुड़ती है',
      id: 'Saat masuk ke kaca, tiap sinar membelok mendekati garis normal',
      pt: 'Ao entrar no vidro, cada raio se aproxima da normal',
    },
    'caption.enterStraight': {
      en: 'Entering the glass, the rays go straight on without bending',
      ko: '유리에 들어가도 광선이 꺾이지 않고 곧게 나아간다',
      ja: 'ガラスに入っても光線は曲がらずまっすぐ進む',
      zh: '进入玻璃时，光线不弯折，直线前进',
      ar: 'عند دخول الزجاج تمضي الأشعة مستقيمة دون انكسار',
      es: 'Al entrar en el vidrio, los rayos siguen rectos sin desviarse',
      fr: 'En entrant dans le verre, les rayons filent tout droit sans dévier',
      hi: 'काँच में प्रवेश करते हुए किरणें बिना मुड़े सीधी चलती हैं',
      id: 'Saat masuk ke kaca, sinar terus lurus tanpa membelok',
      pt: 'Ao entrar no vidro, os raios seguem retos sem desviar',
    },
    'stat.enter': {
      en: 'pixel {pixel}: incidence {in}° → refraction {out}°',
      ko: '픽셀 {pixel} · 입사각 {in}° → 굴절각 {out}°',
      ja: '画素 {pixel} · 入射角 {in}° → 屈折角 {out}°',
      zh: '像素 {pixel} · 入射角 {in}° → 折射角 {out}°',
      ar: 'البكسل {pixel} · زاوية السقوط {in}° → زاوية الانكسار {out}°',
      es: 'píxel {pixel}: incidencia {in}° → refracción {out}°',
      fr: 'pixel {pixel} : incidence {in}° → réfraction {out}°',
      hi: 'पिक्सेल {pixel} · आपतन {in}° → अपवर्तन {out}°',
      id: 'piksel {pixel}: datang {in}° → bias {out}°',
      pt: 'pixel {pixel}: incidência {in}° → refração {out}°',
    },
    'caption.exit': {
      en: 'Leaving the glass, each ray bends away from the normal and slides along the wall',
      ko: '유리에서 나오며 법선에서 멀어지게 꺾여 벽 위를 미끄러진다',
      ja: 'ガラスから出るとき法線から離れる向きに曲がり、壁の上を滑る',
      zh: '离开玻璃时，光线偏离法线弯折，并在墙上滑动',
      ar: 'عند الخروج من الزجاج ينكسر كل شعاع بعيداً عن العمودي وينزلق على الجدار',
      es: 'Al salir del vidrio, cada rayo se aleja de la normal y se desliza por la pared',
      fr: 'En sortant du verre, chaque rayon s’écarte de la normale et glisse le long du mur',
      hi: 'काँच से निकलते हुए हर किरण अभिलंब से दूर मुड़ती है और दीवार पर खिसकती है',
      id: 'Saat keluar dari kaca, tiap sinar membelok menjauhi normal dan bergeser di dinding',
      pt: 'Ao sair do vidro, cada raio se afasta da normal e desliza pela parede',
    },
    'caption.exitStraight': {
      en: 'Leaving the glass without bending, the rays land on their straight-line spots',
      ko: '유리에서 나와도 꺾이지 않고 곧게 갔을 자리에 그대로 닿는다',
      ja: 'ガラスから出ても曲がらず、直進した場合の着地点にそのまま届く',
      zh: '离开玻璃时不弯折，光线正好落在直线到达点上',
      ar: 'عند الخروج من الزجاج دون انكسار تصل الأشعة إلى مواضعها المستقيمة نفسها',
      es: 'Al salir del vidrio sin desviarse, los rayos llegan a su punto en línea recta',
      fr: 'En sortant du verre sans dévier, les rayons arrivent à leur point en ligne droite',
      hi: 'काँच से बिना मुड़े निकलकर किरणें अपने सीधी रेखा वाले बिंदु पर पहुँचती हैं',
      id: 'Keluar dari kaca tanpa membelok, sinar tiba di titik lurusnya',
      pt: 'Ao sair do vidro sem desviar, os raios chegam ao ponto em linha reta',
    },
    'stat.exit': {
      en: 'largest bend {bend}° · flipped neighbour pairs {pairs}',
      ko: '가장 크게 꺾인 각 {bend}° · 뒤집힌 이웃 짝 {pairs}',
      ja: '最大の曲がり {bend}° · 順序が逆転した隣接ペア {pairs}',
      zh: '最大偏折角 {bend}° · 顺序颠倒的相邻对 {pairs}',
      ar: 'أكبر انحراف {bend}° · أزواج متجاورة مقلوبة {pairs}',
      es: 'mayor desvío {bend}° · pares vecinos invertidos {pairs}',
      fr: 'plus forte déviation {bend}° · paires voisines inversées {pairs}',
      hi: 'सबसे बड़ा मोड़ {bend}° · उलटे पड़ोसी जोड़े {pairs}',
      id: 'belokan terbesar {bend}° · pasangan tetangga terbalik {pairs}',
      pt: 'maior desvio {bend}° · pares vizinhos invertidos {pairs}',
    },
    'caption.shadow': {
      en: 'From each point on the wall a shadow ray heads for the light',
      ko: '벽에 닿은 점마다 빛으로 그림자 광선을 쏜다',
      ja: '壁の各点から光源へシャドウレイを放つ',
      zh: '从墙上的每个点向光源发出阴影光线',
      ar: 'من كل نقطة على الجدار ينطلق شعاع ظل نحو الضوء',
      es: 'Desde cada punto de la pared sale un rayo de sombra hacia la luz',
      fr: 'De chaque point du mur part un rayon d’ombre vers la lumière',
      hi: 'दीवार के हर बिंदु से प्रकाश की ओर छाया किरण जाती है',
      id: 'Dari tiap titik di dinding, sinar bayangan menuju cahaya',
      pt: 'De cada ponto da parede sai um raio de sombra rumo à luz',
    },
    'stat.shadow': {
      en: 'blocked by the glass {blocked} / {total}',
      ko: '유리에 막힘 {blocked} / {total}',
      ja: 'ガラスに遮られた {blocked} / {total}',
      zh: '被玻璃挡住 {blocked} / {total}',
      ar: 'حجبها الزجاج {blocked} / {total}',
      es: 'bloqueados por el vidrio {blocked} / {total}',
      fr: 'bloqués par le verre {blocked} / {total}',
      hi: 'काँच से रुकीं {blocked} / {total}',
      id: 'terhalang kaca {blocked} / {total}',
      pt: 'bloqueados pelo vidro {blocked} / {total}',
    },
    'caption.shade': {
      en: 'Each cell takes the colour of the band its ray hit, dimmed in shadow',
      ko: '칸마다 광선이 닿은 띠의 색을 받는다 — 그림자 속이면 어둡게',
      ja: '各マスは光線が当たった帯の色を受け取る — 影の中なら暗く',
      zh: '每格取光线击中的色带颜色 — 处于阴影中则变暗',
      ar: 'تأخذ كل خلية لون الشريط الذي أصابه شعاعها، معتماً في الظل',
      es: 'Cada celda toma el color de la franja que tocó su rayo, oscurecido en sombra',
      fr: 'Chaque case prend la couleur de la bande touchée par son rayon, assombrie à l’ombre',
      hi: 'हर खाना अपनी किरण से छुई पट्टी का रंग लेता है, छाया में धीमा',
      id: 'Tiap sel mengambil warna pita yang dikenai sinarnya, lebih gelap dalam bayangan',
      pt: 'Cada célula recebe a cor da faixa que seu raio atingiu, escurecida na sombra',
    },
    'stat.shade': {
      en: 'bands {bands} · shadow × {scale}',
      ko: '띠 {bands} · 그림자 × {scale}',
      ja: '帯 {bands} · 影 × {scale}',
      zh: '色带 {bands} · 阴影 × {scale}',
      ar: 'الأشرطة {bands} · الظل × {scale}',
      es: 'franjas {bands} · sombra × {scale}',
      fr: 'bandes {bands} · ombre × {scale}',
      hi: 'पट्टियाँ {bands} · छाया × {scale}',
      id: 'pita {bands} · bayangan × {scale}',
      pt: 'faixas {bands} · sombra × {scale}',
    },
  },
};
