import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 행렬로 옮기면 넓이는 몇 배가 되는가 — 모양과 자리가 달라도 그 배수는 같은가.
 *
 * 크기도 모양도 자리도 다른 두 도형을 같은 행렬 A 로 차례로 옮긴다. 넓이가 같은 배수로
 * 불어나고, 마지막에 A 의 네 칸으로 셈한 ad − bc 가 그 배수와 같은 수로 나온다.
 */
export const determinantAreaFacet: FacetJson = {
  id: 'facet:determinantArea',
  title: {
    en: 'The determinant scales area',
    ko: '행렬식은 넓이의 배수',
    ja: '行列式は面積の倍率',
    zh: '行列式是面积的倍数',
    ar: 'المحدِّد يضاعف المساحة',
    es: 'El determinante escala el área',
    fr: 'Le déterminant multiplie l’aire',
    hi: 'सारणिक क्षेत्रफल का गुणक है',
    id: 'Determinan melipatkan luas',
    pt: 'O determinante multiplica a área',
  },
  description: {
    en: 'Two shapes of different size, form and place are moved by the same matrix. Both areas grow by the same multiple, and ad − bc gives that number.',
    ko: '크기도 모양도 자리도 다른 두 도형을 같은 행렬로 옮긴다. 두 넓이가 같은 배수로 불어나고, ad − bc 가 그 수다.',
    ja: '大きさも形も位置も違う二つの図形を同じ行列で移す。どちらの面積も同じ倍数で増え、ad − bc がその数になる。',
    zh: '大小、形状、位置都不同的两个图形用同一个矩阵变换。两者面积按同一倍数增大，ad − bc 正是这个数。',
    ar: 'نحرّك شكلين مختلفين في الحجم والهيئة والموضع بالمصفوفة نفسها. تكبر المساحتان بالمضاعف نفسه، ويعطي ad − bc هذا العدد.',
    es: 'Dos figuras de distinto tamaño, forma y lugar se mueven con la misma matriz. Ambas áreas crecen por el mismo múltiplo, y ad − bc da ese número.',
    fr: 'Deux figures de taille, de forme et de place différentes sont déplacées par la même matrice. Les deux aires grandissent du même facteur, et ad − bc donne ce nombre.',
    hi: 'आकार, रूप और स्थान में अलग दो आकृतियों को एक ही आव्यूह से ले जाते हैं। दोनों क्षेत्रफल एक ही गुणक से बढ़ते हैं, और ad − bc वही संख्या देता है।',
    id: 'Dua bangun yang berbeda ukuran, bentuk, dan letaknya dipindahkan dengan matriks yang sama. Kedua luas bertambah dengan kelipatan yang sama, dan ad − bc memberi bilangan itu.',
    pt: 'Duas figuras de tamanho, forma e lugar diferentes são movidas pela mesma matriz. As duas áreas crescem pelo mesmo múltiplo, e ad − bc dá esse número.',
  },
  algorithm: 'module:determinantArea',
  scene: 'module:determinantAreaScene',
  initialData: {
    type: 'determinant-area',
    stepMs: 2400,
    matrix: [
      [2, 1],
      [-1, 1],
    ],
    shapes: [
      {
        id: 'tri',
        pts: [
          [0, 1],
          [2, 1],
          [1, 2],
        ],
      },
      {
        id: 'ell',
        pts: [
          [-2, -2],
          [0, -2],
          [0, -1],
          [-1, -1],
          [-1, 0],
          [-2, 0],
        ],
      },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.tri': {
      en: 'Triangle',
      ko: '삼각형',
      ja: '三角形',
      zh: '三角形',
      ar: 'مثلث',
      es: 'Triángulo',
      fr: 'Triangle',
      hi: 'त्रिभुज',
      id: 'Segitiga',
      pt: 'Triângulo',
    },
    'label.ell': {
      en: 'L-shape',
      ko: 'ㄴ자 도형',
      ja: 'L字形',
      zh: 'L 形',
      ar: 'شكل L',
      es: 'Forma de L',
      fr: 'Forme en L',
      hi: 'L आकृति',
      id: 'Bangun L',
      pt: 'Forma de L',
    },
    'head.area': {
      en: 'Area',
      ko: '넓이',
      ja: '面積',
      zh: '面积',
      ar: 'المساحة',
      es: 'Área',
      fr: 'Aire',
      hi: 'क्षेत्रफल',
      id: 'Luas',
      pt: 'Área',
    },
    'row.change': {
      en: '{before} → {after}',
      ko: '{before} → {after}',
      ja: '{before} → {after}',
      zh: '{before} → {after}',
      ar: '{before} → {after}',
      es: '{before} → {after}',
      fr: '{before} → {after}',
      hi: '{before} → {after}',
      id: '{before} → {after}',
      pt: '{before} → {after}',
    },
    'row.ratio': {
      en: '×{k}',
      ko: '{k}배',
      ja: '{k}倍',
      zh: '{k}倍',
      ar: '×{k}',
      es: '×{k}',
      fr: '×{k}',
      hi: '×{k}',
      id: '×{k}',
      pt: '×{k}',
    },
    'matrix.name': {
      en: 'A =',
      ko: 'A =',
      ja: 'A =',
      zh: 'A =',
      ar: 'A =',
      es: 'A =',
      fr: 'A =',
      hi: 'A =',
      id: 'A =',
      pt: 'A =',
    },
    'formula.lhs': {
      en: 'ad − bc =',
      ko: 'ad − bc =',
      ja: 'ad − bc =',
      zh: 'ad − bc =',
      ar: 'ad − bc =',
      es: 'ad − bc =',
      fr: 'ad − bc =',
      hi: 'ad − bc =',
      id: 'ad − bc =',
      pt: 'ad − bc =',
    },
    'caption.start': {
      en: 'Before moving — areas {areas}',
      ko: '옮기기 전 — 넓이 {areas}',
      ja: '移す前 — 面積 {areas}',
      zh: '变换前 — 面积 {areas}',
      ar: 'قبل التحريك — المساحات {areas}',
      es: 'Antes de mover — áreas {areas}',
      fr: 'Avant le déplacement — aires {areas}',
      hi: 'ले जाने से पहले — क्षेत्रफल {areas}',
      id: 'Sebelum dipindah — luas {areas}',
      pt: 'Antes de mover — áreas {areas}',
    },
    'caption.move': {
      en: '{name}: area {before} → {after} · ×{k}',
      ko: '{name}: 넓이 {before} → {after} · {k}배',
      ja: '{name}: 面積 {before} → {after} · {k}倍',
      zh: '{name}：面积 {before} → {after} · {k}倍',
      ar: '{name}: المساحة {before} → {after} · ×{k}',
      es: '{name}: área {before} → {after} · ×{k}',
      fr: '{name} : aire {before} → {after} · ×{k}',
      hi: '{name}: क्षेत्रफल {before} → {after} · ×{k}',
      id: '{name}: luas {before} → {after} · ×{k}',
      pt: '{name}: área {before} → {after} · ×{k}',
    },
    'caption.det': {
      en: 'Shapes whose multiple equals ad − bc: {same} / {n}',
      ko: 'ad − bc 와 배수가 같은 도형: {same} / {n}',
      ja: '倍数が ad − bc と等しい図形: {same} / {n}',
      zh: '倍数等于 ad − bc 的图形：{same} / {n}',
      ar: 'الأشكال التي يساوي مضاعفها ad − bc: {same} / {n}',
      es: 'Figuras cuyo múltiplo es igual a ad − bc: {same} / {n}',
      fr: 'Figures dont le facteur vaut ad − bc : {same} / {n}',
      hi: 'जिन आकृतियों का गुणक ad − bc के बराबर है: {same} / {n}',
      id: 'Bangun yang kelipatannya sama dengan ad − bc: {same} / {n}',
      pt: 'Figuras cujo múltiplo é igual a ad − bc: {same} / {n}',
    },
  },
  blocks: {
    stage: { type: 'determinant-area-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
