/**
 * number-theory — m 칸 시계에서 0 부터 a 칸씩 뛰면 몇 칸을 밟고 제자리로 오는가.
 *
 * 1차 데이터는 두 손잡이 사다리와 첫 판의 m · a 뿐이다. 뜀마다의 자리 · 밟은 칸 · 뜀 수 · gcd ·
 * m ÷ gcd 는 알고리즘이 셈한다. 수식 기호(mod · gcd · ÷)는 번역하지 않는 자료라 열 언어가 같다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const numberTheoryFacet: FacetJson = {
  id: 'facet:numberTheory',
  title: {
    en: 'Orbits Mod m and the GCD',
    ko: '나머지의 궤도와 최대공약수',
    ja: 'm を法とする軌道と最大公約数',
    zh: '模 m 的轨道与最大公约数',
    ar: 'المدارات بقياس m والقاسم المشترك الأكبر',
    es: 'Órbitas módulo m y el MCD',
    fr: 'Orbites modulo m et le PGCD',
    hi: 'मॉड्यूलो m कक्षाएँ और महत्तम समापवर्तक',
    id: 'Orbit modulo m dan FPB',
    pt: 'Órbitas módulo m e o MDC',
  },
  description: {
    en: 'On a clock of m cells, a marker starts at 0 and jumps a cells forward each time until it lands on 0 again. Each landing leaves a mark and a line from the previous mark, drawing a star. The last step shows gcd(a, m), m ÷ gcd(a, m) and the list of cells visited.',
    ko: 'm 칸 시계에서 말이 0 에서 출발해 한 번에 a 칸씩 앞으로 뛰며, 다시 0 에 닿으면 멈춘다. 닿은 칸마다 자국이 남고 앞 자국에서 줄이 그어져 별이 그려진다. 끝 걸음에 나오는 것 — gcd(a, m), m ÷ gcd(a, m), 밟은 칸 목록.',
    ja: 'm マスの時計で、駒が 0 から一度に a マスずつ前へ跳び、再び 0 に着くまで進む。着いたマスには印が残り、前の印から線が引かれて星が描かれる。最後の一歩で gcd(a, m)、m ÷ gcd(a, m)、踏んだマスの一覧を示す。',
    zh: '在 m 格的钟面上，棋子从 0 出发，每次向前跳 a 格，直到再次落在 0 上。每落一格留下记号，并从上一个记号连一条线，画出一颗星。最后一步给出 gcd(a, m)、m ÷ gcd(a, m) 和踩过的格。',
    ar: 'على ساعة من m خانة، تنطلق قطعة من 0 وتقفز a خانات إلى الأمام في كل مرة حتى تعود إلى 0. كل هبوط يترك علامة وخطًا من العلامة السابقة فيرتسم نجم. الخطوة الأخيرة تعرض gcd(a, m) و m ÷ gcd(a, m) وقائمة الخانات المزورة.',
    es: 'En un reloj de m casillas, una ficha sale de 0 y salta a casillas hacia delante cada vez, hasta caer de nuevo en 0. Cada caída deja una marca y una línea desde la marca anterior, dibujando una estrella. El último paso muestra gcd(a, m), m ÷ gcd(a, m) y la lista de casillas pisadas.',
    fr: 'Sur une horloge de m cases, un pion part de 0 et saute de a cases vers l’avant à chaque fois, jusqu’à retomber sur 0. Chaque arrivée laisse une marque et un trait depuis la marque précédente, qui dessinent une étoile. La dernière étape montre gcd(a, m), m ÷ gcd(a, m) et la liste des cases visitées.',
    hi: 'm खानों वाली घड़ी पर एक मोहरा 0 से चलकर हर बार a खाने आगे कूदता है, जब तक फिर से 0 पर न पहुँचे। हर पहुँच पर निशान बनता है और पिछले निशान से एक रेखा खिंचती है, जिससे तारा बनता है। अंतिम चरण gcd(a, m), m ÷ gcd(a, m) और छुए गए खानों की सूची दिखाता है।',
    id: 'Pada jam dengan m petak, sebuah bidak berangkat dari 0 dan melompat a petak ke depan setiap kali, sampai mendarat di 0 lagi. Setiap pendaratan meninggalkan tanda dan garis dari tanda sebelumnya sehingga tergambar bintang. Langkah terakhir menampilkan gcd(a, m), m ÷ gcd(a, m), dan daftar petak yang diinjak.',
    pt: 'Num relógio de m casas, uma peça parte de 0 e salta a casas para a frente de cada vez, até cair de novo em 0. Cada chegada deixa uma marca e uma linha desde a marca anterior, desenhando uma estrela. O último passo mostra gcd(a, m), m ÷ gcd(a, m) e a lista de casas visitadas.',
  },
  algorithm: 'module:numberTheory',
  projector: 'module:numberTheoryProjector',
  initialData: {
    type: 'number-theory',
    stepMs: 700,
    mLadder: [6, 7, 8, 9, 10, 11, 12],
    aLadder: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    m: 12,
    a: 9,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'number-theory-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'modulus',
          name: 'modulus',
          label: {
            en: 'Modulus m',
            ko: '법 m',
            ja: '法 m',
            zh: '模 m',
            ar: 'المقياس m',
            es: 'Módulo m',
            fr: 'Modulo m',
            hi: 'मॉड्यूलस m',
            id: 'Modulus m',
            pt: 'Módulo m',
          },
          segments: [
            { value: 6, label: '6' },
            { value: 7, label: '7' },
            { value: 8, label: '8' },
            { value: 9, label: '9' },
            { value: 10, label: '10' },
            { value: 11, label: '11' },
            { value: 12, label: '12', default: true },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'stride',
          name: 'stride',
          label: {
            en: 'Stride a',
            ko: '걸음 a',
            ja: '歩幅 a',
            zh: '步长 a',
            ar: 'الخطوة a',
            es: 'Paso a',
            fr: 'Pas a',
            hi: 'छलाँग a',
            id: 'Langkah a',
            pt: 'Passo a',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3' },
            { value: 4, label: '4' },
            { value: 5, label: '5' },
            { value: 6, label: '6' },
            { value: 7, label: '7' },
            { value: 8, label: '8' },
            { value: 9, label: '9', default: true },
          ],
        },
      ],
      metrics: [
        {
          name: 'visited-cells',
          label: { en: 'Visited cells', ko: '밟은 칸', ja: '踏んだマス', zh: '踩过的格', ar: 'الخانات المزورة', es: 'Casillas pisadas', fr: 'Cases visitées', hi: 'छुए गए खाने', id: 'Petak diinjak', pt: 'Casas visitadas' },
          initial: 0,
        },
        {
          name: 'gcd',
          label: { en: 'GCD', ko: '최대공약수', ja: '最大公約数', zh: '最大公约数', ar: 'القاسم المشترك الأكبر', es: 'MCD', fr: 'PGCD', hi: 'महत्तम समापवर्तक', id: 'FPB', pt: 'MDC' },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:number-theory-imperative',
      label: {
        en: 'Orbit length and GCD',
        ko: '궤도 길이와 최대공약수',
        ja: '軌道の長さと最大公約数',
        zh: '轨道长度与最大公约数',
        ar: 'طول المدار والقاسم المشترك الأكبر',
        es: 'Longitud de la órbita y MCD',
        fr: 'Longueur de l’orbite et PGCD',
        hi: 'कक्षा की लंबाई और महत्तम समापवर्तक',
        id: 'Panjang orbit dan FPB',
        pt: 'Comprimento da órbita e MDC',
      },
    },
  },
  messages: {
    'caption.round': {
      en: 'Cells: {m} · Stride: {a}',
      ko: '칸: {m} · 걸음: {a}',
      ja: 'マス: {m} · 歩幅: {a}',
      zh: '格数: {m} · 步长: {a}',
      ar: 'الخانات: {m} · الخطوة: {a}',
      es: 'Casillas: {m} · Paso: {a}',
      fr: 'Cases : {m} · Pas : {a}',
      hi: 'खाने: {m} · छलाँग: {a}',
      id: 'Petak: {m} · Langkah: {a}',
      pt: 'Casas: {m} · Passo: {a}',
    },
    'caption.start': {
      en: 'Start: {pos}',
      ko: '출발: {pos}',
      ja: '出発: {pos}',
      zh: '起点: {pos}',
      ar: 'البداية: {pos}',
      es: 'Salida: {pos}',
      fr: 'Départ : {pos}',
      hi: 'आरंभ: {pos}',
      id: 'Mulai: {pos}',
      pt: 'Partida: {pos}',
    },
    'caption.visited': {
      en: 'Visited: {count}',
      ko: '밟은 칸: {count}',
      ja: '踏んだマス: {count}',
      zh: '踩过的格: {count}',
      ar: 'الخانات المزورة: {count}',
      es: 'Casillas pisadas: {count}',
      fr: 'Cases visitées : {count}',
      hi: 'छुए गए खाने: {count}',
      id: 'Petak diinjak: {count}',
      pt: 'Casas visitadas: {count}',
    },
    'caption.visitedList': {
      en: 'Visited: {list}',
      ko: '밟은 칸: {list}',
      ja: '踏んだマス: {list}',
      zh: '踩过的格: {list}',
      ar: 'الخانات المزورة: {list}',
      es: 'Casillas pisadas: {list}',
      fr: 'Cases visitées : {list}',
      hi: 'छुए गए खाने: {list}',
      id: 'Petak diinjak: {list}',
      pt: 'Casas visitadas: {list}',
    },
    'caption.jump': {
      en: '({from} + {a}) mod {m} = {to}',
      ko: '({from} + {a}) mod {m} = {to}',
      ja: '({from} + {a}) mod {m} = {to}',
      zh: '({from} + {a}) mod {m} = {to}',
      ar: '({from} + {a}) mod {m} = {to}',
      es: '({from} + {a}) mod {m} = {to}',
      fr: '({from} + {a}) mod {m} = {to}',
      hi: '({from} + {a}) mod {m} = {to}',
      id: '({from} + {a}) mod {m} = {to}',
      pt: '({from} + {a}) mod {m} = {to}',
    },
    'caption.gcd': {
      en: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      ko: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      ja: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      zh: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      ar: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      es: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      fr: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      hi: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      id: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
      pt: 'gcd({a}, {m}) = {g} · {m} ÷ {g} = {len}',
    },
    'stage.center': {
      en: 'mod {m}',
      ko: 'mod {m}',
      ja: 'mod {m}',
      zh: 'mod {m}',
      ar: 'mod {m}',
      es: 'mod {m}',
      fr: 'mod {m}',
      hi: 'mod {m}',
      id: 'mod {m}',
      pt: 'mod {m}',
    },
  },
};
