import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 사슬 끝의 뿌리 인증서는 누가 보증하는가 — 제가 제게 한 서명으로 뿌리를 믿을 수 있는가?
 */
export const trustAnchorFacet: FacetJson = {
  id: 'facet:trustAnchor',
  title: {
    en: 'Trust anchor',
    ko: '신뢰 루트',
    ja: 'トラストアンカー',
    zh: '信任锚',
    ar: 'مرساة الثقة',
    es: 'Ancla de confianza',
    fr: 'Ancre de confiance',
    hi: 'ट्रस्ट एंकर',
    id: 'Jangkar kepercayaan',
    pt: 'Âncora de confiança',
  },
  description: {
    en: 'Two roots with the same name both pass their own self-signature check; only the key already in the trust store tells them apart.',
    ko: '이름이 같은 뿌리 둘은 제 서명 확인을 둘 다 통과한다. 미리 들여놓은 신뢰 저장소의 열쇠만이 둘을 가른다.',
    ja: '同じ名前のルート二つはどちらも自己署名の検証を通る。見分けられるのは、信頼ストアに前もって入れてある鍵だけだ。',
    zh: '同名的两个根证书都能通过自签名验证；只有事先放进信任库的密钥才能把它们区分开。',
    ar: 'جذران بالاسم نفسه يجتازان كلاهما فحص التوقيع الذاتي؛ وحده المفتاح الموجود مسبقًا في مخزن الثقة يميّز بينهما.',
    es: 'Dos raíces con el mismo nombre superan su propia comprobación de autofirma; solo la clave que ya estaba en el almacén de confianza las distingue.',
    fr: 'Deux racines au même nom passent chacune la vérification de leur autosignature ; seule la clé déjà présente dans le magasin de confiance les départage.',
    hi: 'एक ही नाम वाले दोनों रूट अपने स्व-हस्ताक्षर की जाँच पास कर लेते हैं; केवल ट्रस्ट स्टोर में पहले से रखी कुंजी ही उन्हें अलग करती है।',
    id: 'Dua akar bernama sama sama-sama lolos pemeriksaan tanda tangan dirinya sendiri; hanya kunci yang sudah ada di penyimpanan tepercaya yang membedakan keduanya.',
    pt: 'Duas raízes com o mesmo nome passam ambas na verificação da própria assinatura; só a chave que já estava no repositório de confiança as distingue.',
  },
  algorithm: 'module:trustAnchor',
  scene: 'module:trustAnchorScene',
  initialData: {
    type: 'trust-anchor',
    stepMs: 1800,
    roots: [
      { id: 'genuine', subject: 'CN=Demo Root CA', issuer: 'CN=Demo Root CA', p: 67, q: 71, e: 13 },
      { id: 'fake', subject: 'CN=Demo Root CA', issuer: 'CN=Demo Root CA', p: 59, q: 79, e: 7 },
    ],
    store: [{ subject: 'CN=Demo Root CA', root: 'genuine' }],
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'trust-anchor-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'label.genuine': {
      en: 'Genuine root',
      ko: '진짜 뿌리',
      ja: '本物のルート',
      zh: '真根证书',
      ar: 'الجذر الحقيقي',
      es: 'Raíz auténtica',
      fr: 'Racine authentique',
      hi: 'असली रूट',
      id: 'Akar asli',
      pt: 'Raiz genuína',
    },
    'label.fake': {
      en: 'Fake root',
      ko: '가짜 뿌리',
      ja: '偽のルート',
      zh: '假根证书',
      ar: 'الجذر المزيف',
      es: 'Raíz falsa',
      fr: 'Fausse racine',
      hi: 'नकली रूट',
      id: 'Akar palsu',
      pt: 'Raiz falsa',
    },
    'label.store': {
      en: 'Trust store',
      ko: '신뢰 저장소',
      ja: '信頼ストア',
      zh: '信任库',
      ar: 'مخزن الثقة',
      es: 'Almacén de confianza',
      fr: 'Magasin de confiance',
      hi: 'ट्रस्ट स्टोर',
      id: 'Penyimpanan tepercaya',
      pt: 'Repositório de confiança',
    },
    'store.entry': {
      en: '{name} · n {n} · e {e}',
      ko: '{name} · n {n} · e {e}',
      ja: '{name} · n {n} · e {e}',
      zh: '{name} · n {n} · e {e}',
      ar: '{name} · n {n} · e {e}',
      es: '{name} · n {n} · e {e}',
      fr: '{name} · n {n} · e {e}',
      hi: '{name} · n {n} · e {e}',
      id: '{name} · n {n} · e {e}',
      pt: '{name} · n {n} · e {e}',
    },
    'field.subject': {
      en: 'Subject: {v}',
      ko: '주체: {v}',
      ja: 'サブジェクト: {v}',
      zh: '主体: {v}',
      ar: 'الموضوع: {v}',
      es: 'Sujeto: {v}',
      fr: 'Sujet : {v}',
      hi: 'विषय: {v}',
      id: 'Subjek: {v}',
      pt: 'Titular: {v}',
    },
    'field.issuer': {
      en: 'Issuer: {v}',
      ko: '발급자: {v}',
      ja: '発行者: {v}',
      zh: '签发者: {v}',
      ar: 'المُصدِر: {v}',
      es: 'Emisor: {v}',
      fr: 'Émetteur : {v}',
      hi: 'जारीकर्ता: {v}',
      id: 'Penerbit: {v}',
      pt: 'Emissor: {v}',
    },
    'field.key': {
      en: 'Key: n {n} · e {e}',
      ko: '열쇠: n {n} · e {e}',
      ja: '鍵: n {n} · e {e}',
      zh: '密钥: n {n} · e {e}',
      ar: 'المفتاح: n {n} · e {e}',
      es: 'Clave: n {n} · e {e}',
      fr: 'Clé : n {n} · e {e}',
      hi: 'कुंजी: n {n} · e {e}',
      id: 'Kunci: n {n} · e {e}',
      pt: 'Chave: n {n} · e {e}',
    },
    'field.sig': {
      en: 'Self-signature: {v}',
      ko: '제 서명: {v}',
      ja: '自己署名: {v}',
      zh: '自签名: {v}',
      ar: 'التوقيع الذاتي: {v}',
      es: 'Autofirma: {v}',
      fr: 'Autosignature : {v}',
      hi: 'स्व-हस्ताक्षर: {v}',
      id: 'Tanda tangan diri: {v}',
      pt: 'Autoassinatura: {v}',
    },
    'verify.digest': {
      en: 'Digest of name and key: {v}',
      ko: '이름과 열쇠의 요약: {v}',
      ja: '名前と鍵の要約: {v}',
      zh: '名称与密钥的摘要: {v}',
      ar: 'ملخّص الاسم والمفتاح: {v}',
      es: 'Resumen de nombre y clave: {v}',
      fr: 'Condensé du nom et de la clé : {v}',
      hi: 'नाम और कुंजी का सार: {v}',
      id: 'Ringkasan nama dan kunci: {v}',
      pt: 'Resumo de nome e chave: {v}',
    },
    'verify.unseal': {
      en: 'Unsealed with its own key:',
      ko: '제 열쇠로 푼 값:',
      ja: '自分の鍵で開いた値:',
      zh: '用自己的密钥解开的值:',
      ar: 'القيمة بعد فكّها بمفتاحه نفسه:',
      es: 'Abierta con su propia clave:',
      fr: 'Ouverte avec sa propre clé :',
      hi: 'अपनी ही कुंजी से खोला गया मान:',
      id: 'Dibuka dengan kuncinya sendiri:',
      pt: 'Aberta com a própria chave:',
    },
    'verify.formula': {
      en: '{s}^{e} mod {n} = {v}',
      ko: '{s}^{e} mod {n} = {v}',
      ja: '{s}^{e} mod {n} = {v}',
      zh: '{s}^{e} mod {n} = {v}',
      ar: '{s}^{e} mod {n} = {v}',
      es: '{s}^{e} mod {n} = {v}',
      fr: '{s}^{e} mod {n} = {v}',
      hi: '{s}^{e} mod {n} = {v}',
      id: '{s}^{e} mod {n} = {v}',
      pt: '{s}^{e} mod {n} = {v}',
    },
    'verify.holds': {
      en: 'Holds',
      ko: '맞다',
      ja: '一致',
      zh: '成立',
      ar: 'صحيح',
      es: 'Válida',
      fr: 'Valide',
      hi: 'सही',
      id: 'Cocok',
      pt: 'Válida',
    },
    'verify.fails': {
      en: 'Fails',
      ko: '어긋난다',
      ja: '不一致',
      zh: '不成立',
      ar: 'خاطئ',
      es: 'No válida',
      fr: 'Invalide',
      hi: 'गलत',
      id: 'Tidak cocok',
      pt: 'Inválida',
    },
    'verdict.compare': {
      en: 'Store ({sn}, {se}) {op} this ({n}, {e})',
      ko: '저장소 ({sn}, {se}) {op} 건너온 ({n}, {e})',
      ja: 'ストア ({sn}, {se}) {op} 届いた鍵 ({n}, {e})',
      zh: '信任库 ({sn}, {se}) {op} 收到的 ({n}, {e})',
      ar: 'المخزن ({sn}, {se}) {op} الوارد ({n}, {e})',
      es: 'Almacén ({sn}, {se}) {op} recibida ({n}, {e})',
      fr: 'Magasin ({sn}, {se}) {op} reçue ({n}, {e})',
      hi: 'स्टोर ({sn}, {se}) {op} आई हुई ({n}, {e})',
      id: 'Penyimpanan ({sn}, {se}) {op} yang datang ({n}, {e})',
      pt: 'Repositório ({sn}, {se}) {op} recebida ({n}, {e})',
    },
    'verdict.trusted': {
      en: 'Trusted',
      ko: '믿는다',
      ja: '信頼する',
      zh: '信任',
      ar: 'موثوق',
      es: 'De confianza',
      fr: 'Approuvée',
      hi: 'भरोसेमंद',
      id: 'Dipercaya',
      pt: 'Confiável',
    },
    'verdict.rejected': {
      en: 'Not trusted',
      ko: '믿지 않는다',
      ja: '信頼しない',
      zh: '不信任',
      ar: 'غير موثوق',
      es: 'Sin confianza',
      fr: 'Non approuvée',
      hi: 'भरोसेमंद नहीं',
      id: 'Tidak dipercaya',
      pt: 'Não confiável',
    },
    'count.held': {
      en: 'Self-signatures that held: {h}',
      ko: '제 서명이 맞은 뿌리: {h}',
      ja: '自己署名が通ったルート: {h}',
      zh: '自签名成立的根: {h}',
      ar: 'جذور صحّ توقيعها الذاتي: {h}',
      es: 'Autofirmas válidas: {h}',
      fr: 'Autosignatures valides : {h}',
      hi: 'सही स्व-हस्ताक्षर वाले रूट: {h}',
      id: 'Tanda tangan diri yang cocok: {h}',
      pt: 'Autoassinaturas válidas: {h}',
    },
    'count.trusted': {
      en: 'Trusted roots: {k}',
      ko: '믿은 뿌리: {k}',
      ja: '信頼したルート: {k}',
      zh: '受信任的根: {k}',
      ar: 'جذور موثوقة: {k}',
      es: 'Raíces de confianza: {k}',
      fr: 'Racines approuvées : {k}',
      hi: 'भरोसेमंद रूट: {k}',
      id: 'Akar yang dipercaya: {k}',
      pt: 'Raízes confiáveis: {k}',
    },
    'caption.start': {
      en: 'Arrived roots: {r}, all named {name}. The store was filled before this connection.',
      ko: '건너온 뿌리: {r}, 이름은 모두 {name}. 저장소는 이 연결 전에 채워졌다.',
      ja: '届いたルート: {r}、名前はすべて {name}。ストアはこの接続の前に満たされていた。',
      zh: '收到的根: {r}，名称都是 {name}。信任库在这次连接之前就已填好。',
      ar: 'الجذور الواردة: {r}، وكلها باسم {name}. مُلئ المخزن قبل هذا الاتصال.',
      es: 'Raíces recibidas: {r}, todas con el nombre {name}. El almacén se llenó antes de esta conexión.',
      fr: 'Racines reçues : {r}, toutes nommées {name}. Le magasin a été rempli avant cette connexion.',
      hi: 'आए हुए रूट: {r}, सबका नाम {name}। स्टोर इस कनेक्शन से पहले भरा गया था।',
      id: 'Akar yang datang: {r}, semuanya bernama {name}. Penyimpanan diisi sebelum koneksi ini.',
      pt: 'Raízes recebidas: {r}, todas com o nome {name}. O repositório foi preenchido antes desta conexão.',
    },
    'caption.selfSigHolds': {
      en: '{role}, own key: {s}^{e} mod {n} = {v} = digest {d}.',
      ko: '{role}, 제 열쇠로: {s}^{e} mod {n} = {v} = 요약 {d}.',
      ja: '{role}、自分の鍵で: {s}^{e} mod {n} = {v} = 要約 {d}。',
      zh: '{role}，用自己的密钥: {s}^{e} mod {n} = {v} = 摘要 {d}。',
      ar: '{role}، بمفتاحه نفسه: {s}^{e} mod {n} = {v} = الملخّص {d}.',
      es: '{role}, con su propia clave: {s}^{e} mod {n} = {v} = resumen {d}.',
      fr: '{role}, avec sa propre clé : {s}^{e} mod {n} = {v} = condensé {d}.',
      hi: '{role}, अपनी कुंजी से: {s}^{e} mod {n} = {v} = सार {d}।',
      id: '{role}, dengan kuncinya sendiri: {s}^{e} mod {n} = {v} = ringkasan {d}.',
      pt: '{role}, com a própria chave: {s}^{e} mod {n} = {v} = resumo {d}.',
    },
    'caption.selfSigFails': {
      en: '{role}, own key: {s}^{e} mod {n} = {v} ≠ digest {d}.',
      ko: '{role}, 제 열쇠로: {s}^{e} mod {n} = {v} ≠ 요약 {d}.',
      ja: '{role}、自分の鍵で: {s}^{e} mod {n} = {v} ≠ 要約 {d}。',
      zh: '{role}，用自己的密钥: {s}^{e} mod {n} = {v} ≠ 摘要 {d}。',
      ar: '{role}، بمفتاحه نفسه: {s}^{e} mod {n} = {v} ≠ الملخّص {d}.',
      es: '{role}, con su propia clave: {s}^{e} mod {n} = {v} ≠ resumen {d}.',
      fr: '{role}, avec sa propre clé : {s}^{e} mod {n} = {v} ≠ condensé {d}.',
      hi: '{role}, अपनी कुंजी से: {s}^{e} mod {n} = {v} ≠ सार {d}।',
      id: '{role}, dengan kuncinya sendiri: {s}^{e} mod {n} = {v} ≠ ringkasan {d}.',
      pt: '{role}, com a própria chave: {s}^{e} mod {n} = {v} ≠ resumo {d}.',
    },
    'caption.trusted': {
      en: '{role}: found by name in the store; the keys match.',
      ko: '{role} — 이름으로 저장소에서 찾았고 열쇠가 같다.',
      ja: '{role} — 名前でストアから見つけ、鍵が一致する。',
      zh: '{role} — 按名称在信任库中找到，密钥相同。',
      ar: '{role}: وُجد بالاسم في المخزن، والمفتاحان متطابقان.',
      es: '{role}: encontrada por nombre en el almacén; las claves coinciden.',
      fr: '{role} : trouvée par son nom dans le magasin ; les clés concordent.',
      hi: '{role}: नाम से स्टोर में मिला; कुंजियाँ मेल खाती हैं।',
      id: '{role}: ditemukan lewat nama di penyimpanan; kuncinya sama.',
      pt: '{role}: encontrada pelo nome no repositório; as chaves coincidem.',
    },
    'caption.rejected': {
      en: '{role}: found by name in the store; the keys differ.',
      ko: '{role} — 이름으로 저장소에서 찾았지만 열쇠가 다르다.',
      ja: '{role} — 名前でストアから見つけたが、鍵が違う。',
      zh: '{role} — 按名称在信任库中找到，但密钥不同。',
      ar: '{role}: وُجد بالاسم في المخزن، لكن المفتاحين مختلفان.',
      es: '{role}: encontrada por nombre en el almacén; las claves difieren.',
      fr: '{role} : trouvée par son nom dans le magasin ; les clés diffèrent.',
      hi: '{role}: नाम से स्टोर में मिला; पर कुंजियाँ अलग हैं।',
      id: '{role}: ditemukan lewat nama di penyimpanan; kuncinya berbeda.',
      pt: '{role}: encontrada pelo nome no repositório; as chaves diferem.',
    },
  },
};
