/**
 * @piece
 * 질문: "10 초에 4 건" 을 칸을 고정해 세면 실제로 10 초 안에 몇 건까지 지나갈 수 있는가.
 *
 * 같은 요청 여덟을 고정 창과 미는 창(로그 꼴)이 한 걸음에 함께 판정한다.
 * 고정 창은 칸 경계에서 셈이 0 으로 돌아가 경계 앞뒤를 모두 받고, 미는 창은
 * 요청 시각을 따라 밀려가며 바로 앞 10 초를 센다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const slidingWindowCountFacet: FacetJson = {
  id: 'facet:slidingWindowCount',
  title: {
    en: 'Fixed window vs sliding window',
    ko: '고정 창과 미는 창',
    ja: '固定ウィンドウとスライディングウィンドウ',
    zh: '固定窗口与滑动窗口',
    ar: 'النافذة الثابتة مقابل النافذة المنزلقة',
    es: 'Ventana fija frente a ventana deslizante',
    fr: 'Fenêtre fixe contre fenêtre glissante',
    hi: 'स्थिर विंडो बनाम खिसकती विंडो',
    id: 'Jendela tetap vs jendela geser',
    pt: 'Janela fixa vs janela deslizante',
  },
  description: {
    en: 'Eight requests meet two limiters of the same limit. The fixed window counts per cell; the sliding window counts the 10 s just before each request.',
    ko: '요청 여덟이 한도가 같은 두 제한기를 지난다. 고정 창은 칸마다 세고, 미는 창은 요청마다 바로 앞 10 초를 센다.',
    ja: '8 件のリクエストが同じ上限の 2 つのリミッターを通る。固定ウィンドウは区間ごとに数え、スライディングウィンドウは各リクエストの直前 10 秒を数える。',
    zh: '八个请求经过限额相同的两个限流器。固定窗口按格计数,滑动窗口统计每个请求之前的 10 秒。',
    ar: 'ثمانية طلبات تمر عبر محدِّدين لهما الحد نفسه. النافذة الثابتة تعدّ لكل خانة، والمنزلقة تعدّ الثواني العشر السابقة لكل طلب.',
    es: 'Ocho solicitudes pasan por dos limitadores con el mismo límite. La ventana fija cuenta por celda; la deslizante cuenta los 10 s previos a cada solicitud.',
    fr: 'Huit requêtes traversent deux limiteurs de même limite. La fenêtre fixe compte par case ; la glissante compte les 10 s qui précèdent chaque requête.',
    hi: 'आठ अनुरोध एक ही सीमा वाले दो सीमकों से गुज़रते हैं। स्थिर विंडो हर खाने में गिनती है, खिसकती विंडो हर अनुरोध से ठीक पहले के 10 से. गिनती है।',
    id: 'Delapan permintaan melewati dua pembatas dengan batas yang sama. Jendela tetap menghitung per sel; jendela geser menghitung 10 dtk tepat sebelum tiap permintaan.',
    pt: 'Oito requisições passam por dois limitadores com o mesmo limite. A janela fixa conta por célula; a deslizante conta os 10 s logo antes de cada requisição.',
  },
  algorithm: 'module:slidingWindowCount',
  scene: 'module:slidingWindowCountScene',
  initialData: {
    type: 'sliding-window-count',
    stepMs: 1300,
    limit: 4,
    windowSec: 10,
    requests: [
      { id: 's1', at: 6 },
      { id: 's2', at: 8 },
      { id: 's3', at: 9 },
      { id: 's4', at: 9 },
      { id: 's5', at: 10 },
      { id: 's6', at: 10 },
      { id: 's7', at: 11 },
      { id: 's8', at: 13 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Requests: {n}. Limit: {limit} per {win} s.',
      ko: '요청 {n} 건. 한도: {win} 초에 {limit} 건.',
      ja: 'リクエスト: {n} 件。上限: {win} 秒に {limit} 件。',
      zh: '请求: {n} 个。限额: 每 {win} 秒 {limit} 个。',
      ar: 'الطلبات: {n}. الحد: {limit} لكل {win} ث.',
      es: 'Solicitudes: {n}. Límite: {limit} cada {win} s.',
      fr: 'Requêtes : {n}. Limite : {limit} par {win} s.',
      hi: 'अनुरोध: {n}. सीमा: हर {win} से. में {limit}.',
      id: 'Permintaan: {n}. Batas: {limit} per {win} dtk.',
      pt: 'Requisições: {n}. Limite: {limit} a cada {win} s.',
    },
    'caption.judge': {
      en: 'Request {id} at {sec} s',
      ko: '요청 {id} · {sec} 초',
      ja: 'リクエスト {id} · {sec} 秒',
      zh: '请求 {id} · 第 {sec} 秒',
      ar: 'الطلب {id} · الثانية {sec}',
      es: 'Solicitud {id} · {sec} s',
      fr: 'Requête {id} · {sec} s',
      hi: 'अनुरोध {id} · {sec} से.',
      id: 'Permintaan {id} · {sec} dtk',
      pt: 'Requisição {id} · {sec} s',
    },
    'label.fixed': {
      en: 'Fixed window',
      ko: '고정 창',
      ja: '固定ウィンドウ',
      zh: '固定窗口',
      ar: 'نافذة ثابتة',
      es: 'Ventana fija',
      fr: 'Fenêtre fixe',
      hi: 'स्थिर विंडो',
      id: 'Jendela tetap',
      pt: 'Janela fixa',
    },
    'label.slide': {
      en: 'Sliding window',
      ko: '미는 창',
      ja: 'スライディングウィンドウ',
      zh: '滑动窗口',
      ar: 'نافذة منزلقة',
      es: 'Ventana deslizante',
      fr: 'Fenêtre glissante',
      hi: 'खिसकती विंडो',
      id: 'Jendela geser',
      pt: 'Janela deslizante',
    },
    'label.accept': {
      en: 'Accept',
      ko: '받음',
      ja: '受理',
      zh: '接受',
      ar: 'قبول',
      es: 'Acepta',
      fr: 'Accepte',
      hi: 'स्वीकार',
      id: 'Terima',
      pt: 'Aceita',
    },
    'label.reject': {
      en: 'Reject',
      ko: '거절',
      ja: '拒否',
      zh: '拒绝',
      ar: 'رفض',
      es: 'Rechaza',
      fr: 'Rejette',
      hi: 'अस्वीकार',
      id: 'Tolak',
      pt: 'Rejeita',
    },
    'label.gauge': {
      en: '{n}/{limit}',
      ko: '{n}/{limit}',
      ja: '{n}/{limit}',
      zh: '{n}/{limit}',
      ar: '{n}/{limit}',
      es: '{n}/{limit}',
      fr: '{n}/{limit}',
      hi: '{n}/{limit}',
      id: '{n}/{limit}',
      pt: '{n}/{limit}',
    },
    'readout.recent': {
      en: 'Accepted in the last {win} s: {n}',
      ko: '지난 {win} 초 동안 받음: {n}',
      ja: '直近 {win} 秒の受理: {n}',
      zh: '最近 {win} 秒内接受: {n}',
      ar: 'المقبول في آخر {win} ث: {n}',
      es: 'Aceptadas en los últimos {win} s: {n}',
      fr: 'Acceptées sur les {win} dernières s : {n}',
      hi: 'पिछले {win} से. में स्वीकार: {n}',
      id: 'Diterima dalam {win} dtk terakhir: {n}',
      pt: 'Aceitas nos últimos {win} s: {n}',
    },
    'decide.fixed': {
      en: 'Cell {lo}–{hi} s · accepted before: {n}',
      ko: '칸 {lo}–{hi} 초 · 앞서 받은 수 {n}',
      ja: '区間 {lo}–{hi} 秒 · 先に受理: {n}',
      zh: '格 {lo}–{hi} 秒 · 先前接受: {n}',
      ar: 'الخانة {lo}–{hi} ث · المقبول قبلُ: {n}',
      es: 'Celda {lo}–{hi} s · aceptadas antes: {n}',
      fr: 'Case {lo}–{hi} s · acceptées avant : {n}',
      hi: 'खाना {lo}–{hi} से. · पहले स्वीकार: {n}',
      id: 'Sel {lo}–{hi} dtk · diterima sebelumnya: {n}',
      pt: 'Célula {lo}–{hi} s · aceitas antes: {n}',
    },
    'decide.slide': {
      en: 'Last {win} s up to {sec} s · accepted before: {n}',
      ko: '{sec} 초까지 {win} 초 · 앞서 받은 수 {n}',
      ja: '{sec} 秒までの {win} 秒 · 先に受理: {n}',
      zh: '到第 {sec} 秒为止的 {win} 秒 · 先前接受: {n}',
      ar: 'آخر {win} ث حتى {sec} ث · المقبول قبلُ: {n}',
      es: 'Últimos {win} s hasta {sec} s · aceptadas antes: {n}',
      fr: '{win} dernières s jusqu’à {sec} s · acceptées avant : {n}',
      hi: '{sec} से. तक के पिछले {win} से. · पहले स्वीकार: {n}',
      id: '{win} dtk terakhir hingga {sec} dtk · diterima sebelumnya: {n}',
      pt: 'Últimos {win} s até {sec} s · aceitas antes: {n}',
    },
    'axis.sec': {
      en: '{sec} s',
      ko: '{sec}초',
      ja: '{sec}秒',
      zh: '{sec}秒',
      ar: '{sec} ث',
      es: '{sec} s',
      fr: '{sec} s',
      hi: '{sec} से.',
      id: '{sec} dtk',
      pt: '{sec} s',
    },
  },
  blocks: {
    stage: { type: 'sliding-window-count-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
