/**
 * 지연 계단 — 한 계단 내려갈 때마다 수십 배.
 *
 * @piece 한 질문에만 답한다. "층이 넷뿐인데 처음과 끝이 왜 쉰 배인가."
 *
 * 선언에 두는 것은 구조뿐이다 — 층 식별자와 사이클 수. 배수 · 총 배수 ·
 * 나노초 환산은 algorithm 이 내준 순수 함수가 내고 장면이 그것을 부르며,
 * 좌표는 stage 가 캔버스에서 역산한다 (S-piece).
 *
 * 화면을 명령이 아니라 **장면**으로 만들므로 (`scene:`) 어느 걸음의 화면이든
 * 셈으로 얻는다 — 그래서 재생 위치를 끌어 보는 띠를 단다 (S-scene).
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const latencyLadderFacet: FacetJson = {
  id: 'facet:latencyLadder',
  title: {
    en: 'Latency ladder',
    ko: '지연 계단',
    ja: 'レイテンシの階段',
    zh: '延迟阶梯',
    ar: 'سلّم زمن الوصول',
    es: 'La escalera de latencia',
    fr: "L'escalier des latences",
    hi: 'विलंब की सीढ़ी',
    id: 'Tangga latensi',
    pt: 'A escada da latência',
  },
  description: {
    en: 'Each floor down costs tens of times more.',
    ko: '한 계단 내려갈 때마다 수십 배.',
    ja: '一段下りるたびに数十倍。',
    zh: '每往下一层，代价就贵上几十倍。',
    ar: 'كل طابق إلى الأسفل يكلّف أضعافاً مضاعفة.',
    es: 'Cada piso hacia abajo cuesta decenas de veces más.',
    fr: 'Chaque étage vers le bas coûte des dizaines de fois plus.',
    hi: 'हर मंज़िल नीचे जाने पर कीमत दसियों गुना बढ़ जाती है।',
    id: 'Setiap lantai ke bawah berharga puluhan kali lipat.',
    pt: 'Cada andar abaixo custa dezenas de vezes mais.',
  },
  algorithm: 'module:latencyLadder',
  scene: 'module:latencyLadderScene',
  initialData: {
    type: 'latency-ladder',
    stepMs: 700,
    levels: [
      { id: 'l1', cycles: 4 },
      { id: 'l2', cycles: 12 },
      { id: 'l3', cycles: 40 },
      { id: 'dram', cycles: 200 },
    ],
  },
  blocks: {
    stage: { type: 'latency-ladder-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'caption.ask': {
      en: 'The core asks the nearest floor first: {level}',
      ko: '가장 가까운 층부터 묻는다: {level}',
      ja: 'まず最も近い階に尋ねる: {level}',
      zh: '先问最近的一层：{level}',
      ar: 'تسأل النواة أقرب طابق أولاً: {level}',
      es: 'El núcleo pregunta primero al piso más cercano: {level}',
      fr: "Le cœur interroge d'abord l'étage le plus proche : {level}",
      hi: 'कोर पहले सबसे नज़दीकी मंज़िल से पूछता है: {level}',
      id: 'Inti bertanya ke lantai terdekat lebih dulu: {level}',
      pt: 'O núcleo pergunta primeiro ao andar mais próximo: {level}',
    },
    'caption.miss': {
      en: 'Not there. One floor further down: {level}',
      ko: '거기 없다. 한 층 더 내려간다: {level}',
      ja: 'そこには無い。もう一段下りる: {level}',
      zh: '不在这里。再往下一层：{level}',
      ar: 'ليست هناك. طابق آخر إلى الأسفل: {level}',
      es: 'Ahí no está. Un piso más abajo: {level}',
      fr: 'Pas là. Un étage plus bas : {level}',
      hi: 'वहाँ नहीं है। एक मंज़िल और नीचे: {level}',
      id: 'Tidak ada di sana. Turun satu lantai lagi: {level}',
      pt: 'Não está lá. Mais um andar abaixo: {level}',
    },
    'caption.hit': {
      en: 'Found here. Cycles spent: {cycles}',
      ko: '여기서 찾았다. 든 사이클: {cycles}',
      ja: 'ここで見つかった。かかったサイクル: {cycles}',
      zh: '在这里找到了。花费的周期：{cycles}',
      ar: 'وُجد هنا. الدورات المستهلكة: {cycles}',
      es: 'Encontrado aquí. Ciclos gastados: {cycles}',
      fr: 'Trouvé ici. Cycles dépensés : {cycles}',
      hi: 'यहाँ मिल गया। खर्च हुए चक्र: {cycles}',
      id: 'Ditemukan di sini. Siklus terpakai: {cycles}',
      pt: 'Encontrado aqui. Ciclos gastos: {cycles}',
    },
    'caption.span': {
      en: 'Same lookup, top floor to bottom: ×{factor}',
      ko: '같은 한 번 찾기인데 맨 위와 맨 아래의 차이: ×{factor}',
      ja: '同じ一度の探索が、最上階と最下階でこれだけ違う: ×{factor}',
      zh: '同样一次查找，最上层与最下层相差：×{factor}',
      ar: 'البحث نفسه، من الطابق الأعلى إلى الأدنى: ×{factor}',
      es: 'La misma búsqueda, del piso superior al inferior: ×{factor}',
      fr: 'La même recherche, du dernier étage au premier : ×{factor}',
      hi: 'वही एक खोज, सबसे ऊपर से सबसे नीचे तक: ×{factor}',
      id: 'Pencarian yang sama, lantai teratas ke terbawah: ×{factor}',
      pt: 'A mesma busca, do andar de cima ao de baixo: ×{factor}',
    },
    'label.l1': {
      en: 'L1 cache',
      ko: 'L1 캐시',
      ja: 'L1 キャッシュ',
      zh: 'L1 缓存',
      ar: 'ذاكرة L1 المخبأة',
      es: 'Caché L1',
      fr: 'Cache L1',
      hi: 'L1 कैश',
      id: 'Cache L1',
      pt: 'Cache L1',
    },
    'label.l2': {
      en: 'L2 cache',
      ko: 'L2 캐시',
      ja: 'L2 キャッシュ',
      zh: 'L2 缓存',
      ar: 'ذاكرة L2 المخبأة',
      es: 'Caché L2',
      fr: 'Cache L2',
      hi: 'L2 कैश',
      id: 'Cache L2',
      pt: 'Cache L2',
    },
    'label.l3': {
      en: 'L3 cache',
      ko: 'L3 캐시',
      ja: 'L3 キャッシュ',
      zh: 'L3 缓存',
      ar: 'ذاكرة L3 المخبأة',
      es: 'Caché L3',
      fr: 'Cache L3',
      hi: 'L3 कैश',
      id: 'Cache L3',
      pt: 'Cache L3',
    },
    'label.dram': {
      en: 'Main memory (DRAM)',
      ko: '주기억 (DRAM)',
      ja: '主記憶 (DRAM)',
      zh: '主存 (DRAM)',
      ar: 'الذاكرة الرئيسية (DRAM)',
      es: 'Memoria principal (DRAM)',
      fr: 'Mémoire principale (DRAM)',
      hi: 'मुख्य स्मृति (DRAM)',
      id: 'Memori utama (DRAM)',
      pt: 'Memória principal (DRAM)',
    },
    'label.cycles': {
      en: '{n} cycles',
      ko: '{n} 사이클',
      ja: '{n} サイクル',
      zh: '{n} 周期',
      ar: '{n} دورة',
      es: '{n} ciclos',
      fr: '{n} cycles',
      hi: '{n} चक्र',
      id: '{n} siklus',
      pt: '{n} ciclos',
    },
    'label.ns': {
      en: '≈{n} ns',
      ko: '약 {n} ns',
      ja: '約 {n} ns',
      zh: '约 {n} ns',
      ar: '≈{n} ns',
      es: '≈{n} ns',
      fr: '≈{n} ns',
      hi: '≈{n} ns',
      id: '≈{n} ns',
      pt: '≈{n} ns',
    },
  },
};
