/**
 * @piece 가장 넓게 퍼진 방향.
 *
 * 답하는 질문 — **점 무리를 한 방향에서만 본다면 어느 쪽에서 봐야 가장 많이
 * 보이는가.** 가운데를 지나는 축 하나가 돌고, 점을 그 축에 내려 찍은 자국의
 * 퍼짐이 오르내리다가, 가장 넓어지는 자리에서 멈춘다.
 *
 * 화면에 뜨는 수는 하나도 여기 적혀 있지 않다. 가운데도 퍼짐도 합도 몫도
 * algorithm 이 아래 좌표에서 직접 셈해 걸음마다 보낸다 (S-piece).
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const directionOfMostSpreadFacet: FacetJson = {
  id: 'facet:directionOfMostSpread',
  title: {
    en: 'The direction of most spread',
    ko: '가장 넓게 퍼진 방향',
    ja: '最も広がる方向',
    zh: '散布最广的方向',
    ar: 'اتجاه أوسع انتشار',
    es: 'La dirección de mayor dispersión',
    fr: 'La direction de plus grande dispersion',
    hi: 'सबसे अधिक फैलाव की दिशा',
    id: 'Arah dengan sebaran terlebar',
    pt: 'A direção de maior dispersão',
  },
  description: {
    en: 'Turn one axis through the cloud and stop where the projections spread widest.',
    ko: '점 무리를 지나는 축 하나를 돌려, 내려 찍은 자국이 가장 넓게 퍼지는 자리에서 멈춘다.',
    ja: '点の群れを貫く軸をまわし、落とした跡が最も広がるところで止める。',
    zh: '让一根轴穿过点云旋转，在投影散得最开处停下。',
    ar: 'أدر محورًا عبر سحابة النقاط وتوقّف حيث تنتشر الإسقاطات على أوسع نطاق.',
    es: 'Gira un eje a través de la nube y detente donde las proyecciones se dispersan más.',
    fr: "Faites tourner un axe à travers le nuage et arrêtez-vous là où les projections s'étalent le plus.",
    hi: 'बिंदु-मेघ से होकर एक अक्ष घुमाएँ और वहाँ रुकें जहाँ प्रक्षेप सबसे अधिक फैलते हैं।',
    id: 'Putar satu sumbu menembus awan titik dan berhenti di tempat proyeksinya paling menyebar.',
    pt: 'Gire um eixo através da nuvem e pare onde as projeções se espalham mais.',
  },
  algorithm: 'module:directionOfMostSpread',
  projector: 'module:directionOfMostSpreadProjector',
  initialData: {
    type: 'direction-of-most-spread',
    points: [
      [1.0, 1.8],
      [1.8, 1.4],
      [2.6, 2.8],
      [3.3, 2.2],
      [4.1, 3.7],
      [4.8, 3.0],
      [5.6, 4.5],
      [6.3, 3.9],
      [2.2, 0.8],
      [5.2, 4.8],
      [3.0, 1.6],
      [4.4, 4.1],
    ],
    stepMs: 700,
  },
  blocks: {
    stage: { type: 'direction-of-most-spread-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'caption.center': {
      en: 'The axis will pivot through the center of the cloud.',
      ko: '축은 점 무리의 가운데를 지난다.',
      ja: '軸は点の群れの中心を通ってまわる。',
      zh: '轴将绕点云的中心旋转。',
      ar: 'سيدور المحور حول مركز سحابة النقاط.',
      es: 'El eje girará por el centro de la nube.',
      fr: "L'axe pivote par le centre du nuage.",
      hi: 'अक्ष बिंदु-मेघ के केंद्र से होकर घूमेगा।',
      id: 'Sumbu berputar melewati pusat awan titik.',
      pt: 'O eixo gira pelo centro da nuvem.',
    },
    'caption.turn': {
      en: 'Turning the axis, measuring how far the marks spread.',
      ko: '축을 돌리며 자국이 얼마나 벌어지는지 잰다.',
      ja: '軸をまわしながら、跡がどれだけ広がるかを測る。',
      zh: '旋转轴线，量一量投影散开多远。',
      ar: 'ندير المحور ونقيس مدى انتشار العلامات.',
      es: 'Se gira el eje midiendo cuánto se dispersan las marcas.',
      fr: "On tourne l'axe en mesurant l'étalement des marques.",
      hi: 'अक्ष घुमाते हुए मापते हैं कि निशान कितने फैलते हैं।',
      id: 'Sumbu diputar sambil mengukur seberapa menyebar tandanya.',
      pt: 'Gira-se o eixo, medindo o quanto as marcas se espalham.',
    },
    'caption.stop': {
      en: 'It comes back and stops where the spread is widest.',
      ko: '되돌아가, 퍼짐이 가장 넓어지는 자리에서 멈춘다.',
      ja: '戻って、広がりが最大になるところで止まる。',
      zh: '它转回来，停在散布最广的位置。',
      ar: 'يعود ويتوقّف حيث يكون الانتشار أوسع ما يكون.',
      es: 'Vuelve atrás y se detiene donde la dispersión es mayor.',
      fr: "Il revient et s'arrête là où la dispersion est la plus grande.",
      hi: 'वह लौटकर वहीं रुकता है जहाँ फैलाव सबसे अधिक है।',
      id: 'Ia kembali dan berhenti di tempat sebarannya paling lebar.',
      pt: 'Volta atrás e para onde a dispersão é maior.',
    },
    'caption.done': {
      en: 'The widest direction holds this much of the total: {share}%.',
      ko: '가장 넓은 방향이 합에서 가진 몫: {share}%.',
      ja: '最も広がる方向が全体に占める割合: {share}%。',
      zh: '最广的方向占总量的比例：{share}%。',
      ar: 'حصة الاتجاه الأوسع من المجموع: {share}%.',
      es: 'La dirección más amplia abarca esta parte del total: {share}%.',
      fr: 'La direction la plus large occupe cette part du total : {share}%.',
      hi: 'सबसे चौड़ी दिशा का कुल में हिस्सा: {share}%।',
      id: 'Bagian arah terlebar dari keseluruhan: {share}%.',
      pt: 'A direção mais ampla detém esta parte do total: {share}%.',
    },
    'label.spread': {
      en: 'spread',
      ko: '퍼짐',
      ja: '広がり',
      zh: '散布',
      ar: 'الانتشار',
      es: 'dispersión',
      fr: 'dispersion',
      hi: 'फैलाव',
      id: 'sebaran',
      pt: 'dispersão',
    },
    'label.spreadValue': {
      en: 'spread = {v}',
      ko: '퍼짐 = {v}',
      ja: '広がり = {v}',
      zh: '散布 = {v}',
      ar: 'الانتشار = {v}',
      es: 'dispersión = {v}',
      fr: 'dispersion = {v}',
      hi: 'फैलाव = {v}',
      id: 'sebaran = {v}',
      pt: 'dispersão = {v}',
    },
    'label.acrossValue': {
      en: 'across = {v}',
      ko: '직각 = {v}',
      ja: '直交 = {v}',
      zh: '垂向 = {v}',
      ar: 'العمودي = {v}',
      es: 'perpendicular = {v}',
      fr: 'perpendiculaire = {v}',
      hi: 'लंबवत = {v}',
      id: 'tegak lurus = {v}',
      pt: 'perpendicular = {v}',
    },
    'label.sumValue': {
      en: 'sum = {v}',
      ko: '합 = {v}',
      ja: '合計 = {v}',
      zh: '合计 = {v}',
      ar: 'المجموع = {v}',
      es: 'suma = {v}',
      fr: 'somme = {v}',
      hi: 'योग = {v}',
      id: 'jumlah = {v}',
      pt: 'soma = {v}',
    },
  },
};
