import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 학습을 마친 첫 층의 창 하나에 여러 무늬를 대 보면, 어느 무늬에 가장 크게 반응하는가 —
 * 창의 값 자체가 그 무늬를 닮았는가.
 */
export const filtersLearnEdgesFacet: FacetJson = {
  id: 'facet:filtersLearnEdges',
  title: {
    en: 'What a learned filter responds to',
    ko: '배운 창은 무엇에 반응하는가',
    ja: '学習したフィルタは何に反応するか',
    zh: '学到的滤波器对什么起反应',
    ar: 'بماذا يستجيب المرشّح المتعلَّم',
    es: 'A qué responde un filtro aprendido',
    fr: 'À quoi réagit un filtre appris',
    hi: 'सीखा हुआ फ़िल्टर किस पर प्रतिक्रिया देता है',
    id: 'Apa yang direspons filter hasil belajar',
    pt: 'A que um filtro aprendido responde',
  },
  description: {
    en: 'Five patterns are pressed, one at a time, against a trained first-layer window that stays in place. Each draws one response, and then they line up by it.',
    ko: '제자리에 있는 학습을 마친 첫 층의 창에 무늬 다섯을 하나씩 맞댄다. 무늬마다 응답 한 수가 나오고, 끝에 그 크기 차례로 늘어선다.',
    ja: '学習を終えた第1層の窓は動かず、そこへ5つの模様を1つずつ当てる。模様ごとに応答が1つ出て、最後にその大きさの順に並ぶ。',
    zh: '训练好的第一层窗口保持不动，五种图案依次贴上去。每种图案得到一个响应，最后按响应大小排成一列。',
    ar: 'تُلصَق خمسة أنماط، واحدًا تلو الآخر، على نافذة مدرَّبة من الطبقة الأولى تبقى في مكانها. يُنتج كل نمط استجابة واحدة، ثم تصطف الأنماط بحسبها.',
    es: 'Cinco patrones se apoyan, uno a uno, sobre una ventana entrenada de la primera capa que no se mueve. Cada uno produce una respuesta y al final se ordenan por ella.',
    fr: 'Cinq motifs sont appliqués, un à un, contre une fenêtre entraînée de la première couche qui reste en place. Chacun donne une réponse, puis ils se rangent selon elle.',
    hi: 'पहली परत की प्रशिक्षित खिड़की अपनी जगह रहती है और पाँच पैटर्न एक-एक कर उससे सटाए जाते हैं। हर पैटर्न एक प्रतिक्रिया देता है, फिर वे उसी क्रम में पंक्ति बनाते हैं।',
    id: 'Lima pola ditempelkan satu per satu ke jendela lapisan pertama yang sudah dilatih dan tetap diam. Tiap pola menghasilkan satu respons, lalu semuanya berbaris menurut respons itu.',
    pt: 'Cinco padrões são encostados, um de cada vez, a uma janela treinada da primeira camada que fica parada. Cada um gera uma resposta e, no fim, eles se alinham por ela.',
  },
  algorithm: 'module:filtersLearnEdges',
  scene: 'module:filtersLearnEdgesScene',
  initialData: {
    type: 'filters-learn-edges',
    stepMs: 1500,
    kernel: [
      [-1.0, 0.2, 1.1],
      [-1.2, 0.1, 0.9],
      [-0.8, -0.1, 1.0],
    ],
    patterns: [
      { id: 'vertical', cells: [[0, 0, 1], [0, 0, 1], [0, 0, 1]] },
      { id: 'horizontal', cells: [[0, 0, 0], [0, 0, 0], [1, 1, 1]] },
      { id: 'flat', cells: [[1, 1, 1], [1, 1, 1], [1, 1, 1]] },
      { id: 'diagonal', cells: [[0, 0, 1], [0, 1, 0], [1, 0, 0]] },
      { id: 'reversed', cells: [[1, 0, 0], [1, 0, 0], [1, 0, 0]] },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'The window stays put. Patterns come to it one at a time.',
      ko: '창은 제자리에 있다. 무늬가 하나씩 창으로 온다.',
      ja: '窓は動かない。模様が1つずつ窓へやって来る。',
      zh: '窗口保持不动。图案一个接一个来到窗口。',
      ar: 'تبقى النافذة في مكانها. تأتي الأنماط إليها واحدًا تلو الآخر.',
      es: 'La ventana no se mueve. Los patrones llegan a ella uno a uno.',
      fr: 'La fenêtre reste en place. Les motifs viennent à elle un par un.',
      hi: 'खिड़की अपनी जगह रहती है। पैटर्न एक-एक कर उसके पास आते हैं।',
      id: 'Jendela tetap diam. Pola datang kepadanya satu per satu.',
      pt: 'A janela fica parada. Os padrões chegam a ela um de cada vez.',
    },
    'caption.press': {
      en: 'Against the window: {name}. Response: {r}',
      ko: '창에 맞댄 무늬: {name}. 응답: {r}',
      ja: '窓に当てた模様: {name}。応答: {r}',
      zh: '贴到窗口的图案：{name}。响应：{r}',
      ar: 'النمط الملاصق للنافذة: {name}. الاستجابة: {r}',
      es: 'Contra la ventana: {name}. Respuesta: {r}',
      fr: 'Contre la fenêtre : {name}. Réponse : {r}',
      hi: 'खिड़की से सटा पैटर्न: {name}। प्रतिक्रिया: {r}',
      id: 'Menempel ke jendela: {name}. Respons: {r}',
      pt: 'Encostado à janela: {name}. Resposta: {r}',
    },
    'caption.rank': {
      en: 'Lined up by response. Largest: {top} ({hi}). Smallest: {bottom} ({lo}).',
      ko: '응답 크기 차례로 늘어섰다. 가장 큼: {top} ({hi}). 가장 작음: {bottom} ({lo}).',
      ja: '応答の大きさの順に並んだ。最大: {top} ({hi})。最小: {bottom} ({lo})。',
      zh: '按响应大小排好了。最大：{top}（{hi}）。最小：{bottom}（{lo}）。',
      ar: 'اصطفّت بحسب الاستجابة. الأكبر: {top} ({hi}). الأصغر: {bottom} ({lo}).',
      es: 'Ordenados por respuesta. Mayor: {top} ({hi}). Menor: {bottom} ({lo}).',
      fr: 'Rangés par réponse. Plus grande : {top} ({hi}). Plus petite : {bottom} ({lo}).',
      hi: 'प्रतिक्रिया के क्रम में पंक्ति बनी। सबसे बड़ी: {top} ({hi})। सबसे छोटी: {bottom} ({lo})।',
      id: 'Berbaris menurut respons. Terbesar: {top} ({hi}). Terkecil: {bottom} ({lo}).',
      pt: 'Alinhados pela resposta. Maior: {top} ({hi}). Menor: {bottom} ({lo}).',
    },
    'label.window': {
      en: 'Window',
      ko: '창',
      ja: '窓',
      zh: '窗口',
      ar: 'النافذة',
      es: 'Ventana',
      fr: 'Fenêtre',
      hi: 'खिड़की',
      id: 'Jendela',
      pt: 'Janela',
    },
    'label.response': {
      en: 'Response',
      ko: '응답',
      ja: '応答',
      zh: '响应',
      ar: 'الاستجابة',
      es: 'Respuesta',
      fr: 'Réponse',
      hi: 'प्रतिक्रिया',
      id: 'Respons',
      pt: 'Resposta',
    },
    'label.pattern.vertical': {
      en: 'Vertical edge',
      ko: '세로 경계',
      ja: '縦の境界',
      zh: '竖直边缘',
      ar: 'حافة رأسية',
      es: 'Borde vertical',
      fr: 'Bord vertical',
      hi: 'खड़ी किनारी',
      id: 'Tepi tegak',
      pt: 'Borda vertical',
    },
    'label.pattern.horizontal': {
      en: 'Horizontal edge',
      ko: '가로 경계',
      ja: '横の境界',
      zh: '水平边缘',
      ar: 'حافة أفقية',
      es: 'Borde horizontal',
      fr: 'Bord horizontal',
      hi: 'आड़ी किनारी',
      id: 'Tepi datar',
      pt: 'Borda horizontal',
    },
    'label.pattern.flat': {
      en: 'Flat',
      ko: '고른 면',
      ja: '一様な面',
      zh: '均匀面',
      ar: 'سطح متجانس',
      es: 'Liso',
      fr: 'Uni',
      hi: 'सपाट',
      id: 'Rata',
      pt: 'Liso',
    },
    'label.pattern.diagonal': {
      en: 'Diagonal',
      ko: '대각선',
      ja: '斜め線',
      zh: '对角线',
      ar: 'قُطري',
      es: 'Diagonal',
      fr: 'Diagonale',
      hi: 'तिरछी रेखा',
      id: 'Diagonal',
      pt: 'Diagonal',
    },
    'label.pattern.reversed': {
      en: 'Reversed edge',
      ko: '뒤집힌 세로 경계',
      ja: '反転した縦の境界',
      zh: '反向竖直边缘',
      ar: 'حافة رأسية معكوسة',
      es: 'Borde invertido',
      fr: 'Bord inversé',
      hi: 'उलटी खड़ी किनारी',
      id: 'Tepi terbalik',
      pt: 'Borda invertida',
    },
  },
  blocks: {
    stage: { type: 'filters-learn-edges-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
