import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 같은 바닥 위의 점인데 왜 어떤 점은 빛을 받고 어떤 점은 그림자인가.
 */
export const shadowRayFacet: FacetJson = {
  id: 'facet:shadowRay',
  title: {
    en: 'Shadow ray',
    ko: '그림자 광선',
    ja: 'シャドウレイ',
    zh: '阴影光线',
    ar: 'شعاع الظل',
    es: 'Rayo de sombra',
    fr: 'Rayon d’ombre',
    hi: 'छाया किरण',
    id: 'Sinar bayangan',
    pt: 'Raio de sombra',
  },
  description: {
    en: 'Is the path from a floor point to the light blocked?',
    ko: '바닥의 점에서 빛까지 가는 길이 막혔는가',
    ja: '床の点から光までの道はふさがれているか',
    zh: '从地面上的点到光源的路径是否被挡住了？',
    ar: 'هل الطريق من نقطة على الأرض إلى الضوء مسدود؟',
    es: '¿Está bloqueado el camino desde un punto del suelo hasta la luz?',
    fr: 'Le chemin d’un point du sol jusqu’à la lumière est-il bloqué ?',
    hi: 'क्या फ़र्श के बिंदु से प्रकाश तक का रास्ता रुका हुआ है?',
    id: 'Apakah jalan dari titik di lantai ke cahaya terhalang?',
    pt: 'O caminho de um ponto do chão até a luz está bloqueado?',
  },
  algorithm: 'module:shadowRay',
  scene: 'module:shadowRayScene',
  initialData: {
    type: 'shadow-ray',
    stepMs: 1600,
    floor: { y: 0, normal: [0, 1] },
    light: { x: 0, y: 4 },
    points: [
      { id: 'p1', x: -3, y: 0 },
      { id: 'p2', x: -1.5, y: 0 },
      { id: 'p3', x: 0, y: 0 },
      { id: 'p4', x: 1.5, y: 0 },
      { id: 'p5', x: 3, y: 0 },
    ],
    blockers: [
      { id: 'ball', center: [-1.2, 2.2], r: 0.6 },
      { id: 'balloon', center: [-1.5, 6.0], r: 0.5 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Each floor point will send one ray toward the light.',
      ko: '바닥의 점마다 빛을 향해 광선 하나를 보낸다.',
      ja: '床の点ごとに、光へ向けて光線を一本ずつ送る。',
      zh: '地面上的每个点都会向光源发出一条光线。',
      ar: 'كل نقطة على الأرض سترسل شعاعًا واحدًا نحو الضوء.',
      es: 'Cada punto del suelo enviará un rayo hacia la luz.',
      fr: 'Chaque point du sol enverra un rayon vers la lumière.',
      hi: 'फ़र्श का हर बिंदु प्रकाश की ओर एक किरण भेजेगा।',
      id: 'Setiap titik di lantai akan mengirim satu sinar ke arah cahaya.',
      pt: 'Cada ponto do chão enviará um raio em direção à luz.',
    },
    'caption.ray': {
      en: 'Point {n} → light · d {d}',
      ko: '점 {n} → 빛 · d {d}',
      ja: '点 {n} → 光 · d {d}',
      zh: '点 {n} → 光源 · d {d}',
      ar: 'النقطة {n} ← الضوء · d {d}',
      es: 'Punto {n} → luz · d {d}',
      fr: 'Point {n} → lumière · d {d}',
      hi: 'बिंदु {n} → प्रकाश · d {d}',
      id: 'Titik {n} → cahaya · d {d}',
      pt: 'Ponto {n} → luz · d {d}',
    },
    'caption.visible': {
      en: 'Light reaching point {n}: {v}',
      ko: '점 {n} 에 닿는 빛: {v}',
      ja: '点 {n} に届く光: {v}',
      zh: '到达点 {n} 的光: {v}',
      ar: 'الضوء الواصل إلى النقطة {n}: {v}',
      es: 'Luz que llega al punto {n}: {v}',
      fr: 'Lumière qui atteint le point {n} : {v}',
      hi: 'बिंदु {n} तक पहुँचा प्रकाश: {v}',
      id: 'Cahaya yang sampai ke titik {n}: {v}',
      pt: 'Luz que chega ao ponto {n}: {v}',
    },
    'caption.tally': {
      en: 'Lit: {lit} · Shadow: {shadow}',
      ko: '빛 받음: {lit} · 그림자: {shadow}',
      ja: '光が届く: {lit} · 影: {shadow}',
      zh: '受光: {lit} · 阴影: {shadow}',
      ar: 'مضاءة: {lit} · ظل: {shadow}',
      es: 'Iluminados: {lit} · Sombra: {shadow}',
      fr: 'Éclairés : {lit} · Ombre : {shadow}',
      hi: 'प्रकाशित: {lit} · छाया: {shadow}',
      id: 'Terkena cahaya: {lit} · Bayangan: {shadow}',
      pt: 'Iluminados: {lit} · Sombra: {shadow}',
    },
    'test.before': {
      en: '{name}: t {t} < d {d}',
      ko: '{name}: t {t} < d {d}',
      ja: '{name}: t {t} < d {d}',
      zh: '{name}: t {t} < d {d}',
      ar: '{name}: t {t} < d {d}',
      es: '{name}: t {t} < d {d}',
      fr: '{name} : t {t} < d {d}',
      hi: '{name}: t {t} < d {d}',
      id: '{name}: t {t} < d {d}',
      pt: '{name}: t {t} < d {d}',
    },
    'test.after': {
      en: '{name}: t {t} ≥ d {d}',
      ko: '{name}: t {t} ≥ d {d}',
      ja: '{name}: t {t} ≥ d {d}',
      zh: '{name}: t {t} ≥ d {d}',
      ar: '{name}: t {t} ≥ d {d}',
      es: '{name}: t {t} ≥ d {d}',
      fr: '{name} : t {t} ≥ d {d}',
      hi: '{name}: t {t} ≥ d {d}',
      id: '{name}: t {t} ≥ d {d}',
      pt: '{name}: t {t} ≥ d {d}',
    },
    'test.miss': {
      en: '{name}: no hit',
      ko: '{name}: 맞지 않음',
      ja: '{name}: 当たらない',
      zh: '{name}: 未击中',
      ar: '{name}: لا تقاطع',
      es: '{name}: sin impacto',
      fr: '{name} : aucun impact',
      hi: '{name}: कोई टक्कर नहीं',
      id: '{name}: tidak kena',
      pt: '{name}: sem acerto',
    },
    'label.light': {
      en: 'Light',
      ko: '빛',
      ja: '光',
      zh: '光源',
      ar: 'الضوء',
      es: 'Luz',
      fr: 'Lumière',
      hi: 'प्रकाश',
      id: 'Cahaya',
      pt: 'Luz',
    },
    'label.floor': {
      en: 'Floor',
      ko: '바닥',
      ja: '床',
      zh: '地面',
      ar: 'الأرض',
      es: 'Suelo',
      fr: 'Sol',
      hi: 'फ़र्श',
      id: 'Lantai',
      pt: 'Chão',
    },
    'label.ball': {
      en: 'Ball',
      ko: '공',
      ja: 'ボール',
      zh: '球',
      ar: 'كرة',
      es: 'Pelota',
      fr: 'Balle',
      hi: 'गेंद',
      id: 'Bola',
      pt: 'Bola',
    },
    'label.balloon': {
      en: 'Balloon',
      ko: '풍선',
      ja: '風船',
      zh: '气球',
      ar: 'بالون',
      es: 'Globo',
      fr: 'Ballon',
      hi: 'गुब्बारा',
      id: 'Balon',
      pt: 'Balão',
    },
    'label.path': {
      en: 'Path to light',
      ko: '빛까지의 길',
      ja: '光までの道',
      zh: '到光源的路径',
      ar: 'الطريق إلى الضوء',
      es: 'Camino hasta la luz',
      fr: 'Chemin jusqu’à la lumière',
      hi: 'प्रकाश तक का रास्ता',
      id: 'Jalan ke cahaya',
      pt: 'Caminho até a luz',
    },
    'label.point': {
      en: 'Point {n}',
      ko: '점 {n}',
      ja: '点 {n}',
      zh: '点 {n}',
      ar: 'النقطة {n}',
      es: 'Punto {n}',
      fr: 'Point {n}',
      hi: 'बिंदु {n}',
      id: 'Titik {n}',
      pt: 'Ponto {n}',
    },
    'label.dist': {
      en: 'd {d}',
      ko: 'd {d}',
      ja: 'd {d}',
      zh: 'd {d}',
      ar: 'd {d}',
      es: 'd {d}',
      fr: 'd {d}',
      hi: 'd {d}',
      id: 'd {d}',
      pt: 'd {d}',
    },
    'label.axis': {
      en: 't',
      ko: 't',
      ja: 't',
      zh: 't',
      ar: 't',
      es: 't',
      fr: 't',
      hi: 't',
      id: 't',
      pt: 't',
    },
  },
  blocks: {
    stage: { type: 'shadow-ray-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
