/**
 * 맥락 조립 — 찾아온 조각을 맥락에 더 많이 넣으면 답을 더 잘 쓰게 되는가,
 * 무엇을 넣느냐만큼 어디에 두느냐가 왜 문제인가.
 *
 * 질문 · 조각 글은 자료라 번역하지 않는다. 조각 낱말 수 · 누적 · 자리 · 거리는
 * 알고리즘이 셈한다.
 */

import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const contextAssemblyFacet: FacetJson = {
  id: 'facet:contextAssembly',
  title: {
    en: 'Context assembly',
    ko: '맥락 조립',
    ja: 'コンテキストの組み立て',
    zh: '上下文组装',
    ar: 'تجميع السياق',
    es: 'Ensamblaje del contexto',
    fr: 'Assemblage du contexte',
    hi: 'संदर्भ जोड़ना',
    id: 'Menyusun konteks',
    pt: 'Montagem do contexto',
  },
  description: {
    en: 'Put more retrieved chunks into the context and the answer chunk drifts toward the middle. Where a chunk sits matters as much as whether it gets in.',
    ko: '찾아온 조각을 맥락에 더 넣을수록 답 조각은 가운데로 묻힌다. 무엇을 넣느냐만큼 어디에 두느냐가 문제다.',
    ja: '取ってきたチャンクを多く入れるほど、答えのチャンクは真ん中へ埋もれていく。何を入れるかと同じくらい、どこに置くかが効く。',
    zh: '把检索到的片段放进上下文越多，答案片段就越往中间沉。放在哪里和放不放进去一样重要。',
    ar: 'كلما أدخلت مقاطع مسترجعة أكثر في السياق انجرف مقطع الإجابة نحو الوسط. مكان المقطع مهم بقدر دخوله.',
    es: 'Cuantos más fragmentos recuperados metes en el contexto, más se hunde el fragmento de la respuesta hacia el medio. Dónde queda importa tanto como si entra.',
    fr: 'Plus on met de fragments récupérés dans le contexte, plus le fragment de la réponse glisse vers le milieu. Sa place compte autant que son entrée.',
    hi: 'संदर्भ में जितने ज़्यादा खोजे गए टुकड़े डालें, जवाब वाला टुकड़ा उतना बीच में दबता है। टुकड़ा कहाँ बैठता है, यह उतना ही मायने रखता है जितना उसका अंदर आना।',
    id: 'Makin banyak potongan hasil pencarian dimasukkan ke konteks, makin tenggelam potongan jawaban ke tengah. Letaknya sama pentingnya dengan masuk atau tidaknya.',
    pt: 'Quanto mais trechos recuperados entram no contexto, mais o trecho da resposta afunda para o meio. Onde ele fica importa tanto quanto entrar.',
  },
  algorithm: 'module:contextAssembly',
  projector: 'module:contextAssemblyProjector',
  initialData: {
    type: 'context-assembly',
    question: 'On what date did the Apollo 11 lunar module land on the Moon?',
    chunks: [
      'Apollo 11 was the first crewed mission to land on the Moon.',
      'The crew were Neil Armstrong, Buzz Aldrin and Michael Collins.',
      'The Saturn V rocket launched from Florida on 16 July.',
      'The lunar module Eagle touched down on 20 July 1969.',
      'Collins stayed in orbit aboard the command module Columbia.',
      'Armstrong and Aldrin spent about two and a half hours outside.',
      'About 650 million people watched the broadcast.',
      'The crew returned to Earth on 24 July and splashed down in the Pacific.',
    ],
    answerRank: 4,
    budgets: [45, 55, 65, 85],
    orders: [0, 1],
    budget: 45,
    order: 0,
    stepMs: 800,
  },
  layout: {
    type: 'column',
    gap: 8,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'context-assembly-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'budget',
          name: 'budget',
          label: {
            en: 'Budget',
            ko: '예산',
            ja: '予算',
            zh: '预算',
            ar: 'الميزانية',
            es: 'Presupuesto',
            fr: 'Budget',
            hi: 'बजट',
            id: 'Anggaran',
            pt: 'Orçamento',
          },
          segments: [
            { value: 45, label: '45', default: true },
            { value: 55, label: '55' },
            { value: 65, label: '65' },
            { value: 85, label: '85' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'order',
          name: 'order',
          label: {
            en: 'Placement',
            ko: '놓는 법',
            ja: '置き方',
            zh: '摆放方式',
            ar: 'طريقة الترتيب',
            es: 'Colocación',
            fr: 'Placement',
            hi: 'रखने का तरीका',
            id: 'Cara menata',
            pt: 'Disposição',
          },
          segments: [
            {
              value: 0,
              label: {
                en: 'By rank',
                ko: '등수대로',
                ja: '順位どおり',
                zh: '按名次',
                ar: 'حسب الترتيب',
                es: 'Por puesto',
                fr: 'Par rang',
                hi: 'रैंक के क्रम में',
                id: 'Menurut peringkat',
                pt: 'Por posição',
              },
              default: true,
            },
            {
              value: 1,
              label: {
                en: 'Ends first',
                ko: '끝부터 번갈아',
                ja: '両端から交互に',
                zh: '两端交替',
                ar: 'من الطرفين بالتناوب',
                es: 'Extremos primero',
                fr: 'Bords d’abord',
                hi: 'पहले दोनों छोर',
                id: 'Ujung dulu',
                pt: 'Pontas primeiro',
              },
            },
          ],
        },
      ],
      metrics: [
        {
          name: 'chunk-count',
          label: {
            en: 'Chunks in',
            ko: '담은 조각',
            ja: '入れたチャンク',
            zh: '放入的片段',
            ar: 'المقاطع المُدخلة',
            es: 'Fragmentos dentro',
            fr: 'Fragments admis',
            hi: 'अंदर आए टुकड़े',
            id: 'Potongan masuk',
            pt: 'Trechos dentro',
          },
          initial: 0,
        },
        {
          name: 'used-word-count',
          label: {
            en: 'Words used',
            ko: '쓴 낱말',
            ja: '使った単語',
            zh: '已用单词',
            ar: 'الكلمات المستخدمة',
            es: 'Palabras usadas',
            fr: 'Mots utilisés',
            hi: 'इस्तेमाल हुए शब्द',
            id: 'Kata terpakai',
            pt: 'Palavras usadas',
          },
          initial: 0,
        },
        {
          name: 'answer-depth',
          label: {
            en: 'Answer depth',
            ko: '답의 거리',
            ja: '答えの深さ',
            zh: '答案深度',
            ar: 'عمق الإجابة',
            es: 'Profundidad de la respuesta',
            fr: 'Profondeur de la réponse',
            hi: 'जवाब की गहराई',
            id: 'Kedalaman jawaban',
            pt: 'Profundidade da resposta',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:context-assembly-imperative',
      label: {
        en: 'Fill, place, measure',
        ko: '담기, 놓기, 거리 재기',
        ja: '入れる・置く・測る',
        zh: '放入、摆放、测距',
        ar: 'الإدخال والترتيب والقياس',
        es: 'Llenar, colocar, medir',
        fr: 'Remplir, placer, mesurer',
        hi: 'भरना, रखना, नापना',
        id: 'Isi, tata, ukur',
        pt: 'Encher, dispor, medir',
      },
    },
  },
  messages: {
    'label.question': {
      en: 'Question: {q}',
      ko: '질문: {q}',
      ja: '質問: {q}',
      zh: '问题：{q}',
      ar: 'السؤال: {q}',
      es: 'Pregunta: {q}',
      fr: 'Question : {q}',
      hi: 'सवाल: {q}',
      id: 'Pertanyaan: {q}',
      pt: 'Pergunta: {q}',
    },
    'label.shelf': {
      en: 'Retrieved chunks, by rank',
      ko: '찾아온 조각 (등수 차례)',
      ja: '取ってきたチャンク(順位順)',
      zh: '检索到的片段（按名次）',
      ar: 'المقاطع المسترجعة حسب الترتيب',
      es: 'Fragmentos recuperados, por puesto',
      fr: 'Fragments récupérés, par rang',
      hi: 'खोजे गए टुकड़े, रैंक के क्रम में',
      id: 'Potongan hasil pencarian, menurut peringkat',
      pt: 'Trechos recuperados, por posição',
    },
    'label.leftOut': {
      en: 'Left out: {n}',
      ko: '밖에 남은 조각: {n}',
      ja: '外に残った数: {n}',
      zh: '留在外面：{n}',
      ar: 'بقي خارجًا: {n}',
      es: 'Quedan fuera: {n}',
      fr: 'Laissés dehors : {n}',
      hi: 'बाहर रह गए: {n}',
      id: 'Tertinggal di luar: {n}',
      pt: 'Ficaram de fora: {n}',
    },
    'label.budget': {
      en: 'Budget: {budget} words',
      ko: '예산 낱말: {budget}',
      ja: '予算の単語数: {budget}',
      zh: '预算单词数：{budget}',
      ar: 'الميزانية بالكلمات: {budget}',
      es: 'Presupuesto: {budget} palabras',
      fr: 'Budget : {budget} mots',
      hi: 'बजट के शब्द: {budget}',
      id: 'Anggaran kata: {budget}',
      pt: 'Orçamento: {budget} palavras',
    },
    'label.context': {
      en: 'Context, front to back',
      ko: '맥락 (앞에서 뒤로)',
      ja: 'コンテキスト(前から後ろへ)',
      zh: '上下文（从前到后）',
      ar: 'السياق من الأمام إلى الخلف',
      es: 'Contexto, de delante hacia atrás',
      fr: 'Contexte, de l’avant vers l’arrière',
      hi: 'संदर्भ, आगे से पीछे',
      id: 'Konteks, dari depan ke belakang',
      pt: 'Contexto, da frente para trás',
    },
    'label.axis': {
      en: 'distance to nearest end',
      ko: '가까운 끝까지의 거리',
      ja: '近い端までの距離',
      zh: '到最近一端的距离',
      ar: 'المسافة إلى أقرب طرف',
      es: 'distancia al extremo más cercano',
      fr: 'distance au bord le plus proche',
      hi: 'नज़दीकी छोर तक दूरी',
      id: 'jarak ke ujung terdekat',
      pt: 'distância à ponta mais próxima',
    },
    'label.answer': {
      en: 'answer',
      ko: '답',
      ja: '答え',
      zh: '答案',
      ar: 'الإجابة',
      es: 'respuesta',
      fr: 'réponse',
      hi: 'जवाब',
      id: 'jawaban',
      pt: 'resposta',
    },
    'caption.start': {
      en: 'Budget {budget} words. Chunks go in by rank until one does not fit.',
      ko: '예산은 낱말 {budget}. 등수 차례로 담다가 넘치는 조각에서 멈춘다.',
      ja: '予算は {budget} 単語。順位の順に入れ、はみ出すチャンクで止まる。',
      zh: '预算 {budget} 个单词。按名次放入，遇到放不下的片段就停。',
      ar: 'الميزانية {budget} كلمة. تدخل المقاطع حسب الترتيب حتى يأتي مقطع لا يتسع.',
      es: 'Presupuesto de {budget} palabras. Los fragmentos entran por puesto hasta que uno no cabe.',
      fr: 'Budget de {budget} mots. Les fragments entrent par rang jusqu’à ce que l’un ne tienne plus.',
      hi: 'बजट {budget} शब्द। टुकड़े रैंक के क्रम में अंदर आते हैं, जब तक कोई न समाए।',
      id: 'Anggaran {budget} kata. Potongan masuk menurut peringkat sampai ada yang tidak muat.',
      pt: 'Orçamento de {budget} palavras. Os trechos entram por posição até um não caber.',
    },
    'caption.admit': {
      en: 'Rank {rank} fits: {words} words, {used} of {budget} used.',
      ko: '{rank} 위 조각이 든다. 낱말 {words}, 쓴 낱말 {used} / {budget}.',
      ja: '{rank} 位のチャンクが入る。{words} 単語、使用 {used} / {budget}。',
      zh: '第 {rank} 名的片段放得下：{words} 个单词，已用 {used} / {budget}。',
      ar: 'المقطع ذو الترتيب {rank} يتسع: {words} كلمة، المستخدم {used} من {budget}.',
      es: 'El puesto {rank} cabe: {words} palabras, {used} de {budget} usadas.',
      fr: 'Le rang {rank} tient : {words} mots, {used} sur {budget} utilisés.',
      hi: 'रैंक {rank} समा जाता है: {words} शब्द, {budget} में से {used} इस्तेमाल।',
      id: 'Peringkat {rank} muat: {words} kata, terpakai {used} dari {budget}.',
      pt: 'A posição {rank} cabe: {words} palavras, {used} de {budget} usadas.',
    },
    'caption.overflow': {
      en: 'Rank {rank} needs {words} words but only {room} are left. It bounces off, and nothing after it is looked at.',
      ko: '{rank} 위 조각에 필요한 낱말: {words}, 남은 자리: {room}. 튕겨 나고, 그 뒤 조각은 보지 않는다.',
      ja: '{rank} 位のチャンクには {words} 単語が要るが、残りは {room}。はじかれ、その後ろは見ない。',
      zh: '第 {rank} 名需要 {words} 个单词，只剩 {room}。它被弹开，后面的都不再看。',
      ar: 'المقطع ذو الترتيب {rank} يحتاج {words} كلمة والمتبقي {room} فقط. يرتد، ولا يُنظر إلى ما بعده.',
      es: 'El puesto {rank} necesita {words} palabras y solo quedan {room}. Rebota, y no se mira nada de lo que viene después.',
      fr: 'Le rang {rank} demande {words} mots et il n’en reste que {room}. Il rebondit, et rien après lui n’est examiné.',
      hi: 'रैंक {rank} को {words} शब्द चाहिए, पर बचे हैं सिर्फ़ {room}। वह लौट जाता है, और उसके बाद वालों को देखा ही नहीं जाता।',
      id: 'Peringkat {rank} butuh {words} kata, sisa hanya {room}. Ia terpental, dan yang sesudahnya tidak dilihat.',
      pt: 'A posição {rank} precisa de {words} palavras e só restam {room}. Ela ricocheteia, e nada depois dela é examinado.',
    },
    'caption.seat.append': {
      en: 'Rank {rank} is added after the others.',
      ko: '{rank} 위 조각을 맨 뒤에 붙인다.',
      ja: '{rank} 位のチャンクを最後尾に足す。',
      zh: '第 {rank} 名的片段接在最后。',
      ar: 'يُضاف المقطع ذو الترتيب {rank} بعد الباقين.',
      es: 'El puesto {rank} se añade detrás de los demás.',
      fr: 'Le rang {rank} s’ajoute après les autres.',
      hi: 'रैंक {rank} बाकी सबके बाद जोड़ा जाता है।',
      id: 'Peringkat {rank} ditambahkan di belakang yang lain.',
      pt: 'A posição {rank} entra depois das outras.',
    },
    'caption.seat.front': {
      en: 'Rank {rank} takes the frontmost free slot.',
      ko: '{rank} 위 조각을 비어 있는 가장 앞 자리에 놓는다.',
      ja: '{rank} 位のチャンクを空いているいちばん前の席に置く。',
      zh: '第 {rank} 名的片段放进最前面的空位。',
      ar: 'يأخذ المقطع ذو الترتيب {rank} أول مكان فارغ من الأمام.',
      es: 'El puesto {rank} ocupa el hueco libre más adelantado.',
      fr: 'Le rang {rank} prend la place libre la plus en avant.',
      hi: 'रैंक {rank} सबसे आगे की खाली जगह लेता है।',
      id: 'Peringkat {rank} mengisi tempat kosong paling depan.',
      pt: 'A posição {rank} ocupa o lugar livre mais à frente.',
    },
    'caption.seat.back': {
      en: 'Rank {rank} takes the backmost free slot.',
      ko: '{rank} 위 조각을 비어 있는 가장 뒤 자리에 놓는다.',
      ja: '{rank} 位のチャンクを空いているいちばん後ろの席に置く。',
      zh: '第 {rank} 名的片段放进最后面的空位。',
      ar: 'يأخذ المقطع ذو الترتيب {rank} آخر مكان فارغ من الخلف.',
      es: 'El puesto {rank} ocupa el hueco libre más atrasado.',
      fr: 'Le rang {rank} prend la place libre la plus en arrière.',
      hi: 'रैंक {rank} सबसे पीछे की खाली जगह लेता है।',
      id: 'Peringkat {rank} mengisi tempat kosong paling belakang.',
      pt: 'A posição {rank} ocupa o lugar livre mais atrás.',
    },
    'caption.depth': {
      en: 'The answer chunk is in slot {slot} of {count}. Distance to the nearest end: {depth}.',
      ko: '답 조각의 자리: {count} 중 {slot}. 가까운 끝까지의 거리: {depth}.',
      ja: '答えのチャンクの席: {count} 中 {slot}。近い端までの距離: {depth}。',
      zh: '答案片段位于 {count} 个中的第 {slot} 位。到最近一端的距离：{depth}。',
      ar: 'مقطع الإجابة في المكان {slot} من {count}. المسافة إلى أقرب طرف: {depth}.',
      es: 'El fragmento de la respuesta está en el hueco {slot} de {count}. Distancia al extremo más cercano: {depth}.',
      fr: 'Le fragment de la réponse est à la place {slot} sur {count}. Distance au bord le plus proche : {depth}.',
      hi: 'जवाब वाला टुकड़ा {count} में से जगह {slot} पर है। नज़दीकी छोर तक दूरी: {depth}।',
      id: 'Potongan jawaban ada di tempat {slot} dari {count}. Jarak ke ujung terdekat: {depth}.',
      pt: 'O trecho da resposta está no lugar {slot} de {count}. Distância à ponta mais próxima: {depth}.',
    },
    'caption.missing': {
      en: 'The answer chunk did not fit.',
      ko: '답 조각이 담기지 않았다.',
      ja: '答えのチャンクは入らなかった。',
      zh: '答案片段没有放进去。',
      ar: 'لم يتسع مقطع الإجابة.',
      es: 'El fragmento de la respuesta no cupo.',
      fr: 'Le fragment de la réponse n’a pas tenu.',
      hi: 'जवाब वाला टुकड़ा नहीं समाया।',
      id: 'Potongan jawaban tidak muat.',
      pt: 'O trecho da resposta não coube.',
    },
    'caption.chunk': {
      en: '“{text}”',
      ko: '“{text}”',
      ja: '“{text}”',
      zh: '“{text}”',
      ar: '“{text}”',
      es: '“{text}”',
      fr: '« {text} »',
      hi: '“{text}”',
      id: '“{text}”',
      pt: '“{text}”',
    },
  },
};
