import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

/**
 * @piece
 * 질문: 브랜치를 만들고 커밋하면, 커밋이 가지에 담기는가 이름이 옮겨 붙는가?
 */
export const branchIsALabelFacet: FacetJson = {
  id: 'facet:branchIsALabel',
  title: {
    en: 'A branch is a label',
    ko: '브랜치는 이름표다',
    ja: 'ブランチはラベルだ',
    zh: '分支只是一个标签',
    ar: 'الفرع مجرد لافتة',
    es: 'Una rama es una etiqueta',
    fr: 'Une branche est une étiquette',
    hi: 'ब्रांच बस एक लेबल है',
    id: 'Cabang adalah label',
    pt: 'Um branch é um rótulo',
  },
  description: {
    en: 'Creating a branch adds no commit, only a name on the current commit. Committing moves just the name HEAD points at.',
    ko: '브랜치를 만들면 커밋은 늘지 않고 지금 커밋에 이름 하나가 붙는다. 커밋을 하면 HEAD 가 가리키는 이름 하나만 옮겨 간다.',
    ja: 'ブランチを作ってもコミットは増えず、今のコミットに名前が一つ付くだけ。コミットすると HEAD が指す名前だけが移る。',
    zh: '创建分支不会增加提交，只在当前提交上多一个名字。提交时只有 HEAD 指向的那个名字会移动。',
    ar: 'إنشاء فرع لا يضيف أي إيداع، بل اسمًا على الإيداع الحالي فقط. وعند الإيداع ينتقل الاسم الذي يشير إليه HEAD وحده.',
    es: 'Crear una rama no añade ningún commit, solo un nombre en el commit actual. Al hacer commit se mueve solo el nombre al que apunta HEAD.',
    fr: 'Créer une branche n’ajoute aucun commit, seulement un nom sur le commit courant. Un commit ne déplace que le nom désigné par HEAD.',
    hi: 'ब्रांच बनाने से कोई कमिट नहीं बढ़ता, बस मौजूदा कमिट पर एक नाम जुड़ता है। कमिट करने पर केवल वही नाम खिसकता है जिस पर HEAD है।',
    id: 'Membuat cabang tidak menambah commit, hanya nama pada commit saat ini. Commit hanya memindahkan nama yang ditunjuk HEAD.',
    pt: 'Criar um branch não acrescenta commit, só um nome no commit atual. Um commit move apenas o nome para o qual HEAD aponta.',
  },
  algorithm: 'module:branchIsALabel',
  scene: 'module:branchIsALabelScene',
  initialData: {
    type: 'branch-is-a-label',
    stepMs: 1600,
    commits: [
      { id: 'A', parents: [] },
      { id: 'B', parents: ['A'] },
      { id: 'C', parents: ['B'] },
    ],
    names: [{ name: 'main', commit: 'C' }],
    head: 'main',
    actions: [
      { kind: 'create-name', name: 'feature' },
      { kind: 'switch', name: 'feature' },
      { kind: 'commit', id: 'D' },
      { kind: 'switch', name: 'main' },
      { kind: 'commit', id: 'E' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Start: {name} → {commit}, HEAD → {name}',
      ko: '처음: {name} → {commit}, HEAD → {name}',
      ja: '最初: {name} → {commit}、HEAD → {name}',
      zh: '开始：{name} → {commit}，HEAD → {name}',
      ar: 'البداية: {name} → {commit}، HEAD → {name}',
      es: 'Inicio: {name} → {commit}, HEAD → {name}',
      fr: 'Départ : {name} → {commit}, HEAD → {name}',
      hi: 'शुरुआत: {name} → {commit}, HEAD → {name}',
      id: 'Awal: {name} → {commit}, HEAD → {name}',
      pt: 'Início: {name} → {commit}, HEAD → {name}',
    },
    'caption.nameCreate': {
      en: 'New name {name} → {commit}',
      ko: '새 이름 {name} → {commit}',
      ja: '新しい名前 {name} → {commit}',
      zh: '新名字 {name} → {commit}',
      ar: 'اسم جديد {name} → {commit}',
      es: 'Nombre nuevo {name} → {commit}',
      fr: 'Nouveau nom {name} → {commit}',
      hi: 'नया नाम {name} → {commit}',
      id: 'Nama baru {name} → {commit}',
      pt: 'Nome novo {name} → {commit}',
    },
    'caption.headMove': {
      en: 'HEAD: {from} → {to}',
      ko: 'HEAD 가 가리키는 이름: {from} → {to}',
      ja: 'HEAD が指す名前: {from} → {to}',
      zh: 'HEAD 指向的名字：{from} → {to}',
      ar: 'الاسم الذي يشير إليه HEAD: {from} → {to}',
      es: 'Nombre al que apunta HEAD: {from} → {to}',
      fr: 'Nom désigné par HEAD : {from} → {to}',
      hi: 'HEAD जिस नाम पर है: {from} → {to}',
      id: 'Nama yang ditunjuk HEAD: {from} → {to}',
      pt: 'Nome para o qual HEAD aponta: {from} → {to}',
    },
    'caption.commit': {
      en: 'New commit {commit}, parent {parent} · {name}: {from} → {commit}',
      ko: '새 커밋 {commit}, 부모 {parent} · {name}: {from} → {commit}',
      ja: '新しいコミット {commit}、親 {parent} · {name}: {from} → {commit}',
      zh: '新提交 {commit}，父提交 {parent} · {name}：{from} → {commit}',
      ar: 'إيداع جديد {commit}، الأب {parent} · {name}: {from} → {commit}',
      es: 'Commit nuevo {commit}, padre {parent} · {name}: {from} → {commit}',
      fr: 'Nouveau commit {commit}, parent {parent} · {name} : {from} → {commit}',
      hi: 'नया कमिट {commit}, पैरेंट {parent} · {name}: {from} → {commit}',
      id: 'Commit baru {commit}, induk {parent} · {name}: {from} → {commit}',
      pt: 'Commit novo {commit}, pai {parent} · {name}: {from} → {commit}',
    },
    'label.commits': {
      en: 'Commits: {n}',
      ko: '커밋: {n}',
      ja: 'コミット: {n}',
      zh: '提交数：{n}',
      ar: 'الإيداعات: {n}',
      es: 'Commits: {n}',
      fr: 'Commits : {n}',
      hi: 'कमिट: {n}',
      id: 'Commit: {n}',
      pt: 'Commits: {n}',
    },
  },
  blocks: {
    stage: { type: 'branch-is-a-label-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
