/**
 * @piece
 * 질문: 클라이언트는 주소 하나만 아는데, 요청은 어떻게 여러 서비스에 닿는가.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const oneDoorManyRoomsFacet: FacetJson = {
  id: 'facet:oneDoorManyRooms',
  title: {
    en: 'One door, many rooms',
    ko: '문 하나, 방 여럿',
    ja: 'ひとつの扉、たくさんの部屋',
    zh: '一扇门，许多房间',
    ar: 'باب واحد وغرف كثيرة',
    es: 'Una puerta, muchas salas',
    fr: 'Une porte, plusieurs pièces',
    hi: 'एक दरवाज़ा, कई कमरे',
    id: 'Satu pintu, banyak ruang',
    pt: 'Uma porta, muitas salas',
  },
  description: {
    en: 'Every request enters through one gateway. It reads the first path segment, sends the request to the matching service — or to several at once — and gathers their answers into one.',
    ko: '모든 요청이 게이트웨이 하나로 들어온다. 게이트웨이는 경로의 첫 조각을 보고 맞는 서비스로 — 또는 여럿에 한꺼번에 — 보내고, 돌아온 답을 하나로 모은다.',
    ja: 'すべてのリクエストは一つのゲートウェイから入る。ゲートウェイはパスの最初の区切りを見て、対応するサービスへ——あるいは複数へ同時に——送り、返ってきた答えを一つにまとめる。',
    zh: '所有请求都从同一个网关进入。网关查看路径的第一段，把请求发往对应的服务——或同时发往多个——再把返回的答复合成一个。',
    ar: 'تدخل كل الطلبات من بوابة واحدة. تقرأ البوابة أول مقطع من المسار وترسل الطلب إلى الخدمة المطابقة — أو إلى عدة خدمات معًا — ثم تجمع الردود في رد واحد.',
    es: 'Todas las peticiones entran por una sola pasarela. Lee el primer segmento de la ruta, envía la petición al servicio que corresponde —o a varios a la vez— y reúne sus respuestas en una.',
    fr: 'Toutes les requêtes entrent par une seule passerelle. Elle lit le premier segment du chemin, envoie la requête au service correspondant — ou à plusieurs à la fois — et rassemble leurs réponses en une seule.',
    hi: 'हर अनुरोध एक ही गेटवे से अंदर आता है। गेटवे पथ का पहला खंड पढ़ता है, अनुरोध को मेल खाती सेवा को — या एक साथ कई को — भेजता है, और लौटे उत्तरों को एक में जोड़ता है।',
    id: 'Semua permintaan masuk lewat satu gateway. Gateway membaca segmen pertama jalur, mengirim permintaan ke layanan yang cocok — atau ke beberapa sekaligus — lalu mengumpulkan jawabannya menjadi satu.',
    pt: 'Todas as requisições entram por um único gateway. Ele lê o primeiro segmento do caminho, envia a requisição ao serviço correspondente — ou a vários ao mesmo tempo — e reúne as respostas em uma só.',
  },
  algorithm: 'module:oneDoorManyRooms',
  scene: 'module:oneDoorManyRoomsScene',
  initialData: {
    type: 'one-door-many-rooms',
    stepMs: 1300,
    services: [
      { id: 'users', ms: 30 },
      { id: 'orders', ms: 50 },
      { id: 'catalog', ms: 20 },
    ],
    routes: [
      { prefix: '/users', targets: ['users'] },
      { prefix: '/orders', targets: ['orders'] },
      { prefix: '/catalog', targets: ['catalog'] },
      { prefix: '/home', targets: ['users', 'orders', 'catalog'] },
    ],
    requests: [
      { method: 'GET', path: '/users/7' },
      { method: 'GET', path: '/orders/42' },
      { method: 'GET', path: '/home' },
      { method: 'GET', path: '/admin/stats' },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'label.client': {
      en: 'Client',
      ko: '클라이언트',
      ja: 'クライアント',
      zh: '客户端',
      ar: 'العميل',
      es: 'Cliente',
      fr: 'Client',
      hi: 'क्लाइंट',
      id: 'Klien',
      pt: 'Cliente',
    },
    'label.gateway': {
      en: 'Gateway',
      ko: '게이트웨이',
      ja: 'ゲートウェイ',
      zh: '网关',
      ar: 'البوابة',
      es: 'Pasarela',
      fr: 'Passerelle',
      hi: 'गेटवे',
      id: 'Gateway',
      pt: 'Gateway',
    },
    'label.users': {
      en: 'Users',
      ko: '사용자',
      ja: 'ユーザー',
      zh: '用户',
      ar: 'المستخدمون',
      es: 'Usuarios',
      fr: 'Utilisateurs',
      hi: 'उपयोगकर्ता',
      id: 'Pengguna',
      pt: 'Usuários',
    },
    'label.orders': {
      en: 'Orders',
      ko: '주문',
      ja: '注文',
      zh: '订单',
      ar: 'الطلبات',
      es: 'Pedidos',
      fr: 'Commandes',
      hi: 'ऑर्डर',
      id: 'Pesanan',
      pt: 'Pedidos',
    },
    'label.catalog': {
      en: 'Products',
      ko: '상품',
      ja: '商品',
      zh: '商品',
      ar: 'المنتجات',
      es: 'Productos',
      fr: 'Produits',
      hi: 'उत्पाद',
      id: 'Produk',
      pt: 'Produtos',
    },
    'label.calls': {
      en: 'Calls: {n}',
      ko: '부름: {n}',
      ja: '呼び出し: {n}',
      zh: '调用: {n}',
      ar: 'الاستدعاءات: {n}',
      es: 'Llamadas: {n}',
      fr: 'Appels : {n}',
      hi: 'कॉल: {n}',
      id: 'Panggilan: {n}',
      pt: 'Chamadas: {n}',
    },
    'label.gathered': {
      en: 'Gathered: {got}/{of}',
      ko: '모인 것: {got}/{of}',
      ja: '集まった数: {got}/{of}',
      zh: '已汇集: {got}/{of}',
      ar: 'المجمَّع: {got}/{of}',
      es: 'Reunidas: {got}/{of}',
      fr: 'Rassemblées : {got}/{of}',
      hi: 'जुटे: {got}/{of}',
      id: 'Terkumpul: {got}/{of}',
      pt: 'Reunidas: {got}/{of}',
    },
    'caption.start': {
      en: 'The client knows one address: the gateway. Requests: {n}',
      ko: '클라이언트가 아는 주소는 하나 — 게이트웨이. 요청: {n}',
      ja: 'クライアントが知っているアドレスは一つ——ゲートウェイ。リクエスト: {n}',
      zh: '客户端只知道一个地址——网关。请求: {n}',
      ar: 'يعرف العميل عنوانًا واحدًا: البوابة. الطلبات: {n}',
      es: 'El cliente conoce una sola dirección: la pasarela. Peticiones: {n}',
      fr: 'Le client connaît une seule adresse : la passerelle. Requêtes : {n}',
      hi: 'क्लाइंट एक ही पता जानता है: गेटवे। अनुरोध: {n}',
      id: 'Klien hanya tahu satu alamat: gateway. Permintaan: {n}',
      pt: 'O cliente conhece um só endereço: o gateway. Requisições: {n}',
    },
    'caption.route': {
      en: 'First segment {prefix} → {name}. Answer: {status} · {ms} ms',
      ko: '첫 조각 {prefix} → {name}. 응답: {status} · {ms} ms',
      ja: '最初の区切り {prefix} → {name}。応答: {status} · {ms} ms',
      zh: '第一段 {prefix} → {name}。响应: {status} · {ms} ms',
      ar: 'المقطع الأول {prefix} ← {name}. الرد: {status} · {ms} ms',
      es: 'Primer segmento {prefix} → {name}. Respuesta: {status} · {ms} ms',
      fr: 'Premier segment {prefix} → {name}. Réponse : {status} · {ms} ms',
      hi: 'पहला खंड {prefix} → {name}। उत्तर: {status} · {ms} ms',
      id: 'Segmen pertama {prefix} → {name}. Jawaban: {status} · {ms} ms',
      pt: 'Primeiro segmento {prefix} → {name}. Resposta: {status} · {ms} ms',
    },
    'caption.scatter': {
      en: 'First segment {prefix} → sent at once to: {names}',
      ko: '첫 조각 {prefix} → 한꺼번에 보낸 곳: {names}',
      ja: '最初の区切り {prefix} → 同時に送った先: {names}',
      zh: '第一段 {prefix} → 同时发往: {names}',
      ar: 'المقطع الأول {prefix} ← أُرسل معًا إلى: {names}',
      es: 'Primer segmento {prefix} → enviada a la vez a: {names}',
      fr: 'Premier segment {prefix} → envoyée en même temps à : {names}',
      hi: 'पहला खंड {prefix} → एक साथ भेजा गया: {names}',
      id: 'Segmen pertama {prefix} → dikirim sekaligus ke: {names}',
      pt: 'Primeiro segmento {prefix} → enviada ao mesmo tempo para: {names}',
    },
    'caption.gather': {
      en: 'Back at {ms} ms: {name}. Gathered: {got}/{of}',
      ko: '{ms} ms 에 돌아옴: {name}. 모인 것: {got}/{of}',
      ja: '{ms} ms で戻った: {name}。集まった数: {got}/{of}',
      zh: '{ms} ms 时返回: {name}。已汇集: {got}/{of}',
      ar: 'عاد عند {ms} ms: {name}. المجمَّع: {got}/{of}',
      es: 'Vuelve a los {ms} ms: {name}. Reunidas: {got}/{of}',
      fr: 'Revenu à {ms} ms : {name}. Rassemblées : {got}/{of}',
      hi: '{ms} ms पर लौटा: {name}। जुटे: {got}/{of}',
      id: 'Kembali pada {ms} ms: {name}. Terkumpul: {got}/{of}',
      pt: 'Volta aos {ms} ms: {name}. Reunidas: {got}/{of}',
    },
    'caption.bundle': {
      en: 'Bundled into one answer: {status} · {ms} ms',
      ko: '한 응답으로 묶음: {status} · {ms} ms',
      ja: '一つの応答にまとめた: {status} · {ms} ms',
      zh: '合并为一个响应: {status} · {ms} ms',
      ar: 'جُمعت في رد واحد: {status} · {ms} ms',
      es: 'Unidas en una respuesta: {status} · {ms} ms',
      fr: 'Réunies en une réponse : {status} · {ms} ms',
      hi: 'एक उत्तर में जोड़ा: {status} · {ms} ms',
      id: 'Digabung menjadi satu jawaban: {status} · {ms} ms',
      pt: 'Unidas em uma resposta: {status} · {ms} ms',
    },
    'caption.notFound': {
      en: 'First segment {prefix}: not in the route table. Gateway answers {status}. Service calls: {n}',
      ko: '첫 조각 {prefix}: 경로표에 없음. 게이트웨이 응답: {status}. 서비스 부름: {n}',
      ja: '最初の区切り {prefix}: 経路表にない。ゲートウェイの応答: {status}。サービス呼び出し: {n}',
      zh: '第一段 {prefix}: 不在路由表中。网关响应: {status}。服务调用: {n}',
      ar: 'المقطع الأول {prefix}: غير موجود في جدول المسارات. ترد البوابة {status}. استدعاءات الخدمات: {n}',
      es: 'Primer segmento {prefix}: no está en la tabla de rutas. La pasarela responde {status}. Llamadas a servicios: {n}',
      fr: 'Premier segment {prefix} : absent de la table des routes. La passerelle répond {status}. Appels aux services : {n}',
      hi: 'पहला खंड {prefix}: मार्ग तालिका में नहीं। गेटवे का उत्तर: {status}। सेवा कॉल: {n}',
      id: 'Segmen pertama {prefix}: tidak ada di tabel rute. Gateway menjawab {status}. Panggilan layanan: {n}',
      pt: 'Primeiro segmento {prefix}: fora da tabela de rotas. O gateway responde {status}. Chamadas a serviços: {n}',
    },
  },
  blocks: {
    stage: { type: 'one-door-many-rooms-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
