/**
 * @piece
 * 질문: 속성 시험이 성질을 깨는 입력을 찾았을 때, 그 입력을 어떻게 깨짐이 남는 가장 작은 입력으로 줄이는가?
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const shrinkToSmallestFacet: FacetJson = {
  id: 'facet:shrinkToSmallest',
  title: {
    en: 'Shrink to the smallest',
    ko: '가장 작은 것으로 깎기',
    ja: '最小まで縮める',
    zh: '缩到最小',
    ar: 'التقليص إلى الأصغر',
    es: 'Reducir hasta lo más pequeño',
    fr: 'Réduire au plus petit',
    hi: 'सबसे छोटे तक घटाना',
    id: 'Menyusutkan ke yang terkecil',
    pt: 'Encolher até o menor',
  },
  description: {
    en: 'A failing input is shaved one slot or one value at a time; a candidate that still breaks the property becomes the new input.',
    ko: '터진 입력을 칸 하나, 값 하나씩 깎는다. 여전히 성질을 깨는 후보가 새 입력이 된다.',
    ja: '失敗した入力を一つの枠、一つの値ずつ削る。まだ性質を破る候補が新しい入力になる。',
    zh: '把失败的输入一次删掉一格或减小一个值；仍然破坏性质的候选成为新的输入。',
    ar: 'يُقلَّص المدخل الفاشل خانةً أو قيمةً في كل مرة؛ والمرشح الذي لا يزال يكسر الخاصية يصبح المدخل الجديد.',
    es: 'La entrada que falla se recorta una casilla o un valor a la vez; el candidato que aún rompe la propiedad pasa a ser la nueva entrada.',
    fr: "L'entrée fautive est rognée d'une case ou d'une valeur à la fois ; un candidat qui casse encore la propriété devient la nouvelle entrée.",
    hi: 'विफल इनपुट को एक बार में एक खाना या एक मान घटाया जाता है; जो उम्मीदवार अब भी गुण तोड़ता है वही नया इनपुट बनता है।',
    id: 'Masukan yang gagal dipangkas satu slot atau satu nilai setiap kali; kandidat yang masih melanggar sifat menjadi masukan baru.',
    pt: 'A entrada que falha é aparada uma casa ou um valor por vez; o candidato que ainda quebra a propriedade vira a nova entrada.',
  },
  algorithm: 'module:shrinkToSmallest',
  scene: 'module:shrinkToSmallestScene',
  initialData: {
    type: 'shrink-to-smallest',
    property: 'decode(encode(list)) == list',
    input: [7, 23, 4, 1],
    stepMs: 1000,
  },
  shuffleOnReset: false,
  messages: {
    'label.input': {
      en: 'Input',
      ko: '입력',
      ja: '入力',
      zh: '输入',
      ar: 'المدخل',
      es: 'Entrada',
      fr: 'Entrée',
      hi: 'इनपुट',
      id: 'Masukan',
      pt: 'Entrada',
    },
    'label.candidate': {
      en: 'Candidate',
      ko: '후보',
      ja: '候補',
      zh: '候选',
      ar: 'المرشح',
      es: 'Candidato',
      fr: 'Candidat',
      hi: 'उम्मीदवार',
      id: 'Kandidat',
      pt: 'Candidato',
    },
    'label.tried': {
      en: 'Already run',
      ko: '돌려 본 입력',
      ja: '試した入力',
      zh: '已运行',
      ar: 'ما جُرِّب',
      es: 'Ya probadas',
      fr: 'Déjà essayées',
      hi: 'चलाए जा चुके',
      id: 'Sudah dijalankan',
      pt: 'Já testadas',
    },
    'label.skipped': {
      en: 'Skipped, already run: {n}',
      ko: '돌려 본 입력이라 건너뜀: {n}',
      ja: '試し済みで飛ばした数: {n}',
      zh: '已运行而跳过: {n}',
      ar: 'تُخطّي لأنه جُرِّب: {n}',
      es: 'Omitidas por ya probadas: {n}',
      fr: 'Sautées, déjà essayées : {n}',
      hi: 'पहले चलाए, छोड़े गए: {n}',
      id: 'Dilewati, sudah dijalankan: {n}',
      pt: 'Puladas, já testadas: {n}',
    },
    'label.smallest': {
      en: 'smallest',
      ko: '가장 작음',
      ja: '最小',
      zh: '最小',
      ar: 'الأصغر',
      es: 'mínima',
      fr: 'minimale',
      hi: 'सबसे छोटा',
      id: 'terkecil',
      pt: 'mínima',
    },
    'label.none': {
      en: 'no new candidate',
      ko: '새 후보 없음',
      ja: '新しい候補なし',
      zh: '没有新候选',
      ar: 'لا مرشح جديد',
      es: 'sin candidato nuevo',
      fr: 'aucun nouveau candidat',
      hi: 'कोई नया उम्मीदवार नहीं',
      id: 'tidak ada kandidat baru',
      pt: 'nenhum candidato novo',
    },
    'verdict.broke': {
      en: 'breaks',
      ko: '깨짐',
      ja: '破れる',
      zh: '被破坏',
      ar: 'تنكسر',
      es: 'se rompe',
      fr: 'cassée',
      hi: 'टूटता है',
      id: 'rusak',
      pt: 'quebra',
    },
    'verdict.holds': {
      en: 'holds',
      ko: '멀쩡',
      ja: '成り立つ',
      zh: '成立',
      ar: 'تصمد',
      es: 'se cumple',
      fr: 'tient',
      hi: 'टिकता है',
      id: 'bertahan',
      pt: 'vale',
    },
    'decision.kept': {
      en: 'kept',
      ko: '받음',
      ja: '採用',
      zh: '接受',
      ar: 'مقبول',
      es: 'aceptado',
      fr: 'gardé',
      hi: 'स्वीकार',
      id: 'diterima',
      pt: 'aceito',
    },
    'decision.dropped': {
      en: 'dropped',
      ko: '버림',
      ja: '破棄',
      zh: '丢弃',
      ar: 'مرفوض',
      es: 'descartado',
      fr: 'écarté',
      hi: 'छोड़ा',
      id: 'dibuang',
      pt: 'descartado',
    },
    'op.delete': {
      en: 'Round {r} · delete slot {i}',
      ko: '바퀴 {r} · {i}번 칸 지우기',
      ja: '周回 {r} · {i}番の枠を消す',
      zh: '第 {r} 轮 · 删除第 {i} 格',
      ar: 'الجولة {r} · حذف الخانة {i}',
      es: 'Vuelta {r} · borrar casilla {i}',
      fr: 'Tour {r} · supprimer la case {i}',
      hi: 'चक्कर {r} · खाना {i} हटाना',
      id: 'Putaran {r} · hapus slot {i}',
      pt: 'Volta {r} · apagar casa {i}',
    },
    'op.value': {
      en: 'Round {r} · slot {i} value {from} → {to}',
      ko: '바퀴 {r} · {i}번 칸 값 {from} → {to}',
      ja: '周回 {r} · {i}番の枠の値 {from} → {to}',
      zh: '第 {r} 轮 · 第 {i} 格的值 {from} → {to}',
      ar: 'الجولة {r} · قيمة الخانة {i}: {from} → {to}',
      es: 'Vuelta {r} · valor de la casilla {i}: {from} → {to}',
      fr: 'Tour {r} · valeur de la case {i} : {from} → {to}',
      hi: 'चक्कर {r} · खाना {i} का मान {from} → {to}',
      id: 'Putaran {r} · nilai slot {i}: {from} → {to}',
      pt: 'Volta {r} · valor da casa {i}: {from} → {to}',
    },
    'caption.start': {
      en: 'The property breaks on this input. Length: {n}',
      ko: '이 입력에서 성질이 깨진다. 길이: {n}',
      ja: 'この入力で性質が破れる。長さ: {n}',
      zh: '这个输入破坏了性质。长度: {n}',
      ar: 'هذا المدخل يكسر الخاصية. الطول: {n}',
      es: 'Esta entrada rompe la propiedad. Longitud: {n}',
      fr: 'Cette entrée casse la propriété. Longueur : {n}',
      hi: 'इस इनपुट पर गुण टूटता है। लंबाई: {n}',
      id: 'Masukan ini melanggar sifat. Panjang: {n}',
      pt: 'Esta entrada quebra a propriedade. Tamanho: {n}',
    },
    'caption.deleteKept': {
      en: 'Without slot {i} it still breaks. Kept — the candidate is the new input.',
      ko: '{i}번 칸 없이도 여전히 깨진다. 받음 — 후보가 새 입력이 된다.',
      ja: '{i}番の枠がなくてもまだ破れる。採用 — 候補が新しい入力になる。',
      zh: '去掉第 {i} 格仍然被破坏。接受 — 候选成为新的输入。',
      ar: 'بدون الخانة {i} لا تزال تنكسر. مقبول — المرشح هو المدخل الجديد.',
      es: 'Sin la casilla {i} todavía se rompe. Aceptado: el candidato es la nueva entrada.',
      fr: 'Sans la case {i}, elle casse encore. Gardé : le candidat devient la nouvelle entrée.',
      hi: 'खाना {i} के बिना भी टूटता है। स्वीकार — उम्मीदवार नया इनपुट बनता है।',
      id: 'Tanpa slot {i} masih rusak. Diterima — kandidat menjadi masukan baru.',
      pt: 'Sem a casa {i} ainda quebra. Aceito: o candidato vira a nova entrada.',
    },
    'caption.deleteDropped': {
      en: 'Without slot {i} the property holds. Dropped — the input stays.',
      ko: '{i}번 칸 없이는 성질이 멀쩡하다. 버림 — 입력은 그대로다.',
      ja: '{i}番の枠がないと性質が成り立つ。破棄 — 入力はそのまま。',
      zh: '去掉第 {i} 格后性质成立。丢弃 — 输入不变。',
      ar: 'بدون الخانة {i} تصمد الخاصية. مرفوض — يبقى المدخل كما هو.',
      es: 'Sin la casilla {i} la propiedad se cumple. Descartado: la entrada se queda.',
      fr: 'Sans la case {i}, la propriété tient. Écarté : l’entrée reste.',
      hi: 'खाना {i} के बिना गुण टिकता है। छोड़ा — इनपुट वैसा ही रहता है।',
      id: 'Tanpa slot {i} sifat bertahan. Dibuang — masukan tetap.',
      pt: 'Sem a casa {i} a propriedade vale. Descartado: a entrada fica.',
    },
    'caption.valueKept': {
      en: 'Value {from} → {to}: still breaks. Kept — the candidate is the new input.',
      ko: '값 {from} → {to}: 여전히 깨진다. 받음 — 후보가 새 입력이 된다.',
      ja: '値 {from} → {to}: まだ破れる。採用 — 候補が新しい入力になる。',
      zh: '值 {from} → {to}: 仍然被破坏。接受 — 候选成为新的输入。',
      ar: 'القيمة {from} → {to}: لا تزال تنكسر. مقبول — المرشح هو المدخل الجديد.',
      es: 'Valor {from} → {to}: todavía se rompe. Aceptado: el candidato es la nueva entrada.',
      fr: 'Valeur {from} → {to} : elle casse encore. Gardé : le candidat devient la nouvelle entrée.',
      hi: 'मान {from} → {to}: अब भी टूटता है। स्वीकार — उम्मीदवार नया इनपुट बनता है।',
      id: 'Nilai {from} → {to}: masih rusak. Diterima — kandidat menjadi masukan baru.',
      pt: 'Valor {from} → {to}: ainda quebra. Aceito: o candidato vira a nova entrada.',
    },
    'caption.valueDropped': {
      en: 'Value {from} → {to}: the property holds. Dropped — the input stays.',
      ko: '값 {from} → {to}: 성질이 멀쩡하다. 버림 — 입력은 그대로다.',
      ja: '値 {from} → {to}: 性質が成り立つ。破棄 — 入力はそのまま。',
      zh: '值 {from} → {to}: 性质成立。丢弃 — 输入不变。',
      ar: 'القيمة {from} → {to}: تصمد الخاصية. مرفوض — يبقى المدخل كما هو.',
      es: 'Valor {from} → {to}: la propiedad se cumple. Descartado: la entrada se queda.',
      fr: 'Valeur {from} → {to} : la propriété tient. Écarté : l’entrée reste.',
      hi: 'मान {from} → {to}: गुण टिकता है। छोड़ा — इनपुट वैसा ही रहता है।',
      id: 'Nilai {from} → {to}: sifat bertahan. Dibuang — masukan tetap.',
      pt: 'Valor {from} → {to}: a propriedade vale. Descartado: a entrada fica.',
    },
    'caption.done': {
      en: 'No new candidate left. Smallest input: {list}',
      ko: '새 후보가 없다. 가장 작은 입력: {list}',
      ja: '新しい候補はない。最小の入力: {list}',
      zh: '没有新的候选了。最小输入: {list}',
      ar: 'لم يبقَ مرشح جديد. أصغر مدخل: {list}',
      es: 'No quedan candidatos nuevos. Entrada mínima: {list}',
      fr: 'Plus de nouveau candidat. Entrée minimale : {list}',
      hi: 'कोई नया उम्मीदवार नहीं बचा। सबसे छोटा इनपुट: {list}',
      id: 'Tidak ada kandidat baru lagi. Masukan terkecil: {list}',
      pt: 'Não há candidato novo. Entrada mínima: {list}',
    },
    'caption.count': {
      en: 'Candidates run: {run} · kept: {kept} · dropped: {dropped}',
      ko: '돌려 본 후보: {run} · 받음: {kept} · 버림: {dropped}',
      ja: '試した候補: {run} · 採用: {kept} · 破棄: {dropped}',
      zh: '运行的候选: {run} · 接受: {kept} · 丢弃: {dropped}',
      ar: 'المرشحون المُجرَّبون: {run} · مقبول: {kept} · مرفوض: {dropped}',
      es: 'Candidatos probados: {run} · aceptados: {kept} · descartados: {dropped}',
      fr: 'Candidats essayés : {run} · gardés : {kept} · écartés : {dropped}',
      hi: 'चलाए गए उम्मीदवार: {run} · स्वीकार: {kept} · छोड़े: {dropped}',
      id: 'Kandidat dijalankan: {run} · diterima: {kept} · dibuang: {dropped}',
      pt: 'Candidatos testados: {run} · aceitos: {kept} · descartados: {dropped}',
    },
  },
  blocks: {
    stage: { type: 'shrink-to-smallest-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
