/**
 * @piece
 * 인자 셋을 받는 함수에 하나만 주면 무엇이 나오는가.
 *
 * 줄 목록이 1차 데이터다. 글자(`text`)와 구조(`stmt`)를 함께 두고, 알고리즘이 구조를 해석해
 * 남은 인자 수 · 남은 함수의 글자 · 담긴 값을 셈한다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { CurryingPartialFacetData } from './algorithm.js';

const initialData: CurryingPartialFacetData = {
  type: 'currying-partial',
  stepMs: 2200,
  lines: [
    {
      indent: 0,
      text: 'let add = a => b => c => a + b + c',
      stmt: {
        k: 'assign',
        to: 'add',
        declare: true,
        value: {
          lambda: ['a'],
          body: {
            lambda: ['b'],
            body: {
              lambda: ['c'],
              body: { op: '+', l: { op: '+', l: { var: 'a' }, r: { var: 'b' } }, r: { var: 'c' } },
            },
          },
        },
      },
    },
    {
      indent: 0,
      text: 'let add5 = add(5)',
      stmt: { k: 'assign', to: 'add5', declare: true, value: { call: 'add', args: [{ num: 5 }] } },
    },
    {
      indent: 0,
      text: 'let add7 = add5(2)',
      stmt: { k: 'assign', to: 'add7', declare: true, value: { call: 'add5', args: [{ num: 2 }] } },
    },
    {
      indent: 0,
      text: 'let total = add7(10)',
      stmt: { k: 'assign', to: 'total', declare: true, value: { call: 'add7', args: [{ num: 10 }] } },
    },
    { indent: 0, text: 'show total', stmt: { k: 'show', value: { var: 'total' } } },
  ],
};

export const curryingPartialFacet: FacetJson = {
  id: 'facet:curryingPartial',
  title: {
    en: 'Currying — one argument at a time',
    ko: '커링 — 인자를 하나씩',
    ja: 'カリー化 — 引数をひとつずつ',
    zh: '柯里化——一次一个参数',
    ar: 'الكاري — وسيط واحد في كل مرة',
    es: 'Currificación: un argumento cada vez',
    fr: 'Curryfication : un argument à la fois',
    hi: 'करीइंग — एक बार में एक आर्ग्युमेंट',
    id: 'Currying — satu argumen setiap kali',
    pt: 'Currying — um argumento por vez',
  },
  description: {
    en: 'Give a three-argument function just one argument and what comes out is a function with two open slots.',
    ko: '인자 셋을 받는 함수에 하나만 주면, 열린 칸이 둘인 함수가 나온다.',
    ja: '引数を3つ取る関数に1つだけ渡すと、空き枠が2つの関数が出てくる。',
    zh: '给接收三个参数的函数只传一个，得到的是一个还有两个空位的函数。',
    ar: 'أعطِ دالة تأخذ ثلاثة وسائط وسيطًا واحدًا فقط، فتخرج دالة فيها خانتان مفتوحتان.',
    es: 'Da un solo argumento a una función que recibe tres y sale una función con dos huecos abiertos.',
    fr: "Donnez un seul argument à une fonction qui en prend trois : il en sort une fonction à deux cases ouvertes.",
    hi: 'तीन आर्ग्युमेंट लेने वाले फ़ंक्शन को सिर्फ़ एक दें, तो दो खुले खानों वाला फ़ंक्शन निकलता है।',
    id: 'Beri fungsi yang menerima tiga argumen satu argumen saja, hasilnya fungsi dengan dua slot terbuka.',
    pt: 'Dê um só argumento a uma função que recebe três e sai uma função com duas vagas abertas.',
  },
  algorithm: 'module:curryingPartial',
  scene: 'module:curryingPartialScene',
  initialData,
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Nothing has run yet.',
      ko: '아직 아무 줄도 실행하지 않았다.',
      ja: 'まだ何も実行していない。',
      zh: '还没有执行任何一行。',
      ar: 'لم يُنفَّذ أي سطر بعد.',
      es: 'Todavía no se ha ejecutado nada.',
      fr: "Rien n'a encore été exécuté.",
      hi: 'अभी कुछ भी नहीं चला है।',
      id: 'Belum ada yang dijalankan.',
      pt: 'Nada foi executado ainda.',
    },
    'caption.bind': {
      en: '{name} is a function. Open slots: {n}.',
      ko: '{name} — 열린 인자 칸이 {n}개인 함수.',
      ja: '{name} — 空き枠が {n} 個の関数。',
      zh: '{name} 是一个有 {n} 个空位的函数。',
      ar: '{name} دالة. الخانات المفتوحة: {n}.',
      es: '{name} es una función. Huecos abiertos: {n}.',
      fr: '{name} est une fonction. Cases ouvertes : {n}.',
      hi: '{name} एक फ़ंक्शन है जिसमें {n} खुले खाने हैं।',
      id: '{name} adalah fungsi dengan {n} slot terbuka.',
      pt: '{name} é uma função. Vagas abertas: {n}.',
    },
    'caption.fill': {
      en: '{arg} goes into slot {param} and closes it.',
      ko: '{arg} → 칸 {param}. 그 칸이 닫힌다.',
      ja: '{arg} → 枠 {param}。その枠が閉じる。',
      zh: '{arg} 放进空位 {param}，这个空位关上了。',
      ar: '{arg} يدخل الخانة {param} فتُغلق.',
      es: '{arg} entra en el hueco {param} y lo cierra.',
      fr: '{arg} entre dans la case {param} et la ferme.',
      hi: '{arg} खाने {param} में जाता है और उसे बंद कर देता है।',
      id: '{arg} masuk ke slot {param} dan menutupnya.',
      pt: '{arg} entra na vaga {param} e a fecha.',
    },
    'caption.left': {
      en: '{name} holds a new function. Open slots: {n}.',
      ko: '{name} 에 담긴 것 — 열린 칸이 {n}개인 새 함수.',
      ja: '{name} に入るのは、空き枠が {n} 個の新しい関数。',
      zh: '{name} 里装的是一个有 {n} 个空位的新函数。',
      ar: 'يحمل {name} دالة جديدة. الخانات المفتوحة: {n}.',
      es: '{name} guarda una función nueva. Huecos abiertos: {n}.',
      fr: '{name} contient une nouvelle fonction. Cases ouvertes : {n}.',
      hi: '{name} में नया फ़ंक्शन है जिसमें {n} खुले खाने हैं।',
      id: '{name} menyimpan fungsi baru dengan {n} slot terbuka.',
      pt: '{name} guarda uma nova função. Vagas abertas: {n}.',
    },
    'caption.fillLast': {
      en: '{arg} goes into the last slot {param} and closes it.',
      ko: '{arg} → 마지막 칸 {param}. 그 칸이 닫힌다.',
      ja: '{arg} → 最後の枠 {param}。その枠が閉じる。',
      zh: '{arg} 放进最后一个空位 {param}，这个空位关上了。',
      ar: '{arg} يدخل الخانة الأخيرة {param} فتُغلق.',
      es: '{arg} entra en el último hueco {param} y lo cierra.',
      fr: '{arg} entre dans la dernière case {param} et la ferme.',
      hi: '{arg} आख़िरी खाने {param} में जाता है और उसे बंद कर देता है।',
      id: '{arg} masuk ke slot terakhir {param} dan menutupnya.',
      pt: '{arg} entra na última vaga {param} e a fecha.',
    },
    'caption.value': {
      en: 'Open slots: {n}. So {name} holds no function but the value {value}.',
      ko: '열린 칸이 {n}개라 {name} 에 담긴 것은 함수가 아닌 값 {value}.',
      ja: '空き枠が {n} 個なので、{name} に入るのは関数ではなく値 {value}。',
      zh: '空位剩 {n} 个，所以 {name} 里装的不是函数，而是值 {value}。',
      ar: 'الخانات المفتوحة: {n}. لذا يحمل {name} القيمة {value} لا دالة.',
      es: 'Huecos abiertos: {n}. Así que {name} no guarda una función sino el valor {value}.',
      fr: 'Cases ouvertes : {n}. Donc {name} ne contient plus une fonction mais la valeur {value}.',
      hi: '{n} खुले खाने बचे, इसलिए {name} में फ़ंक्शन नहीं बल्कि मान {value} है।',
      id: 'Tersisa {n} slot terbuka, jadi {name} menyimpan nilai {value}, bukan fungsi.',
      pt: 'Vagas abertas: {n}. Então {name} não guarda uma função, e sim o valor {value}.',
    },
    'caption.shown': {
      en: 'Shown: {value}.',
      ko: '보인 값: {value}.',
      ja: '表示した値: {value}。',
      zh: '显示的值：{value}。',
      ar: 'القيمة المعروضة: {value}.',
      es: 'Se muestra: {value}.',
      fr: 'Affiché : {value}.',
      hi: 'दिखाया गया: {value}।',
      id: 'Ditampilkan: {value}.',
      pt: 'Mostrado: {value}.',
    },
    'caption.unchanged': {
      en: '{first} is unchanged. Open slots: still {n}.',
      ko: '{first} — 그대로다. 열린 칸은 여전히 {n}개.',
      ja: '{first} — 変わらない。空き枠は今も {n} 個。',
      zh: '{first} 没有变：仍有 {n} 个空位。',
      ar: 'لم يتغيّر {first}. الخانات المفتوحة: ما زالت {n}.',
      es: '{first} no cambia. Huecos abiertos: siguen siendo {n}.',
      fr: "{first} n'a pas changé. Cases ouvertes : toujours {n}.",
      hi: '{first} नहीं बदला: अब भी {n} खुले खाने हैं।',
      id: '{first} tidak berubah: tetap {n} slot terbuka.',
      pt: '{first} não mudou. Vagas abertas: ainda {n}.',
    },
    'label.left': {
      en: '{n} left',
      ko: '남은 인자 {n}',
      ja: '残りの引数 {n}',
      zh: '剩余参数 {n}',
      ar: 'المتبقي {n}',
      es: 'quedan {n}',
      fr: 'reste {n}',
      hi: 'बाकी {n}',
      id: 'sisa {n}',
      pt: 'restam {n}',
    },
    'label.leftValue': {
      en: '{n} left · value',
      ko: '남은 인자 {n} · 값',
      ja: '残りの引数 {n} · 値',
      zh: '剩余参数 {n} · 值',
      ar: 'المتبقي {n} · قيمة',
      es: 'quedan {n} · valor',
      fr: 'reste {n} · valeur',
      hi: 'बाकी {n} · मान',
      id: 'sisa {n} · nilai',
      pt: 'restam {n} · valor',
    },
    'label.output': {
      en: 'output',
      ko: '출력',
      ja: '出力',
      zh: '输出',
      ar: 'المخرجات',
      es: 'salida',
      fr: 'sortie',
      hi: 'आउटपुट',
      id: 'keluaran',
      pt: 'saída',
    },
  },
  blocks: {
    stage: { type: 'currying-partial-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
