/**
 * @piece
 * 질문: 포워딩으로도 못 메우는 틈은 어떻게 되는가.
 *
 * 적재 바로 뒤 명령어가 그 값을 쓰면 한 사이클 멈춘다. 멈춘 자리에 생긴 빈 칸은
 * 명령어처럼 EX → MEM → WB 로 한 칸씩 흘러 나가고, 그 뒤 명령어들은 한 칸씩 밀려 있다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const pipelineBubbleFacet: FacetJson = {
  id: 'facet:pipelineBubble',
  title: {
    en: 'Pipeline bubble',
    ko: '파이프라인 거품',
    ja: 'パイプラインのバブル',
    zh: '流水线气泡',
    ar: 'فقاعة في خط الأنابيب',
    es: 'Burbuja en el pipeline',
    fr: 'Bulle dans le pipeline',
    hi: 'पाइपलाइन में बबल',
    id: 'Gelembung di pipeline',
    pt: 'Bolha no pipeline',
  },
  description: {
    en: 'When a load is followed right away by an instruction that uses its value, even forwarding cannot help: the pipeline stalls for one cycle, and the empty slot flows through EX, MEM and WB like an instruction while everything behind it finishes a cycle later.',
    ko: '적재 바로 뒤의 명령어가 그 값을 쓰면 포워딩으로도 메울 수 없다. 파이프라인이 한 사이클 멈추고, 그 자리에 생긴 빈 칸이 명령어처럼 EX · MEM · WB 를 흘러 나가며, 뒤따르는 명령어들은 한 사이클씩 늦게 끝난다.',
    ja: 'ロード命令の直後の命令がその値を使うと、フォワーディングでも間に合わない。パイプラインは 1 サイクル止まり、その空きが命令のように EX・MEM・WB を流れていき、後ろの命令はみな 1 サイクル遅れて終わる。',
    zh: '加载指令紧接着的指令要用它的值时，转发也来不及。流水线停顿一个周期，空出的槽像指令一样流过 EX、MEM、WB，后面的指令都晚一个周期完成。',
    ar: 'عندما تأتي بعد تعليمة التحميل مباشرة تعليمة تستخدم قيمتها، لا ينفع حتى التمرير: يتوقف خط الأنابيب دورة واحدة، وتمر الخانة الفارغة عبر EX وMEM وWB كأنها تعليمة، وينتهي كل ما خلفها متأخرًا دورة.',
    es: 'Cuando justo después de una carga viene una instrucción que usa su valor, ni el adelantamiento alcanza: el pipeline se detiene un ciclo y el hueco avanza por EX, MEM y WB como una instrucción, mientras todo lo que va detrás termina un ciclo más tarde.',
    fr: 'Quand une instruction utilise la valeur d’un chargement juste après lui, même le forwarding ne suffit pas : le pipeline s’arrête un cycle, et la case vide traverse EX, MEM et WB comme une instruction, tandis que tout ce qui suit finit un cycle plus tard.',
    hi: 'जब लोड के ठीक बाद वाला निर्देश उसी मान का उपयोग करता है, तो फ़ॉरवर्डिंग भी काम नहीं आती: पाइपलाइन एक चक्र रुकती है, और खाली जगह किसी निर्देश की तरह EX, MEM और WB से होकर निकलती है, जबकि उसके पीछे सब कुछ एक चक्र देर से पूरा होता है।',
    id: 'Jika instruksi tepat setelah load memakai nilainya, forwarding pun tidak cukup: pipeline berhenti satu siklus, dan slot kosong itu mengalir melewati EX, MEM, dan WB seperti instruksi, sementara semua yang di belakangnya selesai satu siklus lebih lambat.',
    pt: 'Quando logo depois de uma carga vem uma instrução que usa o valor dela, nem o encaminhamento resolve: o pipeline para um ciclo, e o espaço vazio passa por EX, MEM e WB como uma instrução, enquanto tudo o que vem atrás termina um ciclo depois.',
  },
  algorithm: 'module:pipelineBubble',
  scene: 'module:pipelineBubbleScene',
  initialData: {
    type: 'pipeline-bubble',
    stepMs: 700,
    instrs: [
      { op: 'lw', rd: 'r1', rs: ['r2'], imm: 0 },
      { op: 'add', rd: 'r3', rs: ['r1', 'r4'] },
      { op: 'sub', rd: 'r5', rs: ['r6', 'r7'] },
      { op: 'or', rd: 'r8', rs: ['r9', 'r10'] },
    ],
    regs: { r2: 100, r4: 5 },
    memory: { '100': 20 },
  },
  shuffleOnReset: false,
  blocks: {
    stage: { type: 'pipeline-bubble-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
  messages: {
    'stage.if': { en: 'IF', ko: 'IF', ja: 'IF', zh: 'IF', ar: 'IF', es: 'IF', fr: 'IF', hi: 'IF', id: 'IF', pt: 'IF' },
    'stage.id': { en: 'ID', ko: 'ID', ja: 'ID', zh: 'ID', ar: 'ID', es: 'ID', fr: 'ID', hi: 'ID', id: 'ID', pt: 'ID' },
    'stage.ex': { en: 'EX', ko: 'EX', ja: 'EX', zh: 'EX', ar: 'EX', es: 'EX', fr: 'EX', hi: 'EX', id: 'EX', pt: 'EX' },
    'stage.mem': { en: 'MEM', ko: 'MEM', ja: 'MEM', zh: 'MEM', ar: 'MEM', es: 'MEM', fr: 'MEM', hi: 'MEM', id: 'MEM', pt: 'MEM' },
    'stage.wb': { en: 'WB', ko: 'WB', ja: 'WB', zh: 'WB', ar: 'WB', es: 'WB', fr: 'WB', hi: 'WB', id: 'WB', pt: 'WB' },
    'label.instr': {
      en: 'I{n}',
      ko: 'I{n}',
      ja: 'I{n}',
      zh: 'I{n}',
      ar: 'I{n}',
      es: 'I{n}',
      fr: 'I{n}',
      hi: 'I{n}',
      id: 'I{n}',
      pt: 'I{n}',
    },
    'label.bubble': {
      en: 'bubble',
      ko: '빈 칸',
      ja: 'バブル',
      zh: '气泡',
      ar: 'فقاعة',
      es: 'burbuja',
      fr: 'bulle',
      hi: 'बबल',
      id: 'gelembung',
      pt: 'bolha',
    },
    'label.held': {
      en: 'held',
      ko: '머묾',
      ja: '待機',
      zh: '停住',
      ar: 'متوقف',
      es: 'retenida',
      fr: 'retenue',
      hi: 'रुका',
      id: 'tertahan',
      pt: 'retida',
    },
    'label.waiting': {
      en: 'waiting to be fetched',
      ko: '가져오기를 기다림',
      ja: 'フェッチ待ち',
      zh: '等待取指',
      ar: 'بانتظار الجلب',
      es: 'esperando a ser buscadas',
      fr: 'en attente de chargement',
      hi: 'फ़ेच होने की प्रतीक्षा में',
      id: 'menunggu diambil',
      pt: 'aguardando busca',
    },
    'label.cycle': {
      en: 'cycle {c}',
      ko: '사이클 {c}',
      ja: 'サイクル {c}',
      zh: '周期 {c}',
      ar: 'الدورة {c}',
      es: 'ciclo {c}',
      fr: 'cycle {c}',
      hi: 'चक्र {c}',
      id: 'siklus {c}',
      pt: 'ciclo {c}',
    },
    'label.out': {
      en: 'out of WB, by cycle',
      ko: 'WB 를 떠난 것, 사이클별',
      ja: 'WB を出たもの（サイクル順）',
      zh: '离开 WB 的（按周期）',
      ar: 'ما خرج من WB، حسب الدورة',
      es: 'salidas de WB, por ciclo',
      fr: 'sorties de WB, par cycle',
      hi: 'WB से निकले, चक्र के अनुसार',
      id: 'keluar dari WB, per siklus',
      pt: 'saídas de WB, por ciclo',
    },
    'label.forward': {
      en: '{reg} = {value}',
      ko: '{reg} = {value}',
      ja: '{reg} = {value}',
      zh: '{reg} = {value}',
      ar: '{reg} = {value}',
      es: '{reg} = {value}',
      fr: '{reg} = {value}',
      hi: '{reg} = {value}',
      id: '{reg} = {value}',
      pt: '{reg} = {value}',
    },
    'caption.ready': {
      en: 'Instructions waiting to be fetched: {n}.',
      ko: '가져오기를 기다리는 명령어: {n}개.',
      ja: 'フェッチを待つ命令: {n} 個。',
      zh: '等待取指的指令：{n} 条。',
      ar: 'التعليمات التي تنتظر الجلب: {n}.',
      es: 'Instrucciones esperando a ser buscadas: {n}.',
      fr: 'Instructions en attente de chargement : {n}.',
      hi: 'फ़ेच की प्रतीक्षा में निर्देश: {n}।',
      id: 'Instruksi yang menunggu diambil: {n}.',
      pt: 'Instruções aguardando busca: {n}.',
    },
    'caption.flow': {
      en: 'Cycle {c}: everything moves one stage to the right.',
      ko: '사이클 {c}: 모두 오른쪽으로 한 단계씩 흐른다.',
      ja: 'サイクル {c}: すべてが右へ 1 段ずつ進む。',
      zh: '周期 {c}：全部向右前进一级。',
      ar: 'الدورة {c}: يتقدم كل شيء مرحلة واحدة إلى اليمين.',
      es: 'Ciclo {c}: todo avanza una etapa hacia la derecha.',
      fr: 'Cycle {c} : tout avance d’un étage vers la droite.',
      hi: 'चक्र {c}: सब कुछ दाईं ओर एक चरण आगे बढ़ता है।',
      id: 'Siklus {c}: semuanya maju satu tahap ke kanan.',
      pt: 'Ciclo {c}: tudo avança um estágio para a direita.',
    },
    'caption.stall': {
      en: 'Cycle {c}: {prod} is still loading {reg} in MEM, and {cons} needs it in EX now. {cons} stays in ID, the one behind it stays in IF, and an empty slot goes into EX instead.',
      ko: '사이클 {c}: {reg} 값은 {prod} 의 MEM 이 끝나야 나오는데, 그 값을 지금 EX 에서 써야 할 차례는 {cons}. 그래서 {cons} 쪽은 ID 에, 그 뒤 명령어는 IF 에 머물고 EX 에는 빈 칸이 대신 들어간다.',
      ja: 'サイクル {c}: {prod} はまだ MEM で {reg} をロード中なのに、{cons} は今 EX でその値が要る。{cons} は ID に、その後ろは IF にとどまり、EX には代わりに空きが入る。',
      zh: '周期 {c}：{prod} 还在 MEM 中加载 {reg}，而 {cons} 现在就要在 EX 中用它。{cons} 留在 ID，后面那条留在 IF，EX 里改为进入一个空槽。',
      ar: 'الدورة {c}: لا يزال {prod} يحمّل {reg} في MEM، و{cons} يحتاجه الآن في EX. يبقى {cons} في ID، ويبقى ما خلفه في IF، وتدخل خانة فارغة إلى EX بدلًا منه.',
      es: 'Ciclo {c}: {prod} todavía está cargando {reg} en MEM y {cons} lo necesita ya en EX. {cons} se queda en ID, la de detrás se queda en IF y en su lugar entra un hueco en EX.',
      fr: 'Cycle {c} : {prod} charge encore {reg} en MEM, et {cons} en a besoin tout de suite en EX. {cons} reste en ID, celle qui suit reste en IF, et une case vide entre en EX à sa place.',
      hi: 'चक्र {c}: {prod} अभी भी MEM में {reg} लोड कर रहा है, और {cons} को यह अभी EX में चाहिए। {cons} ID में रुकता है, उसके पीछे वाला IF में रुकता है, और उसकी जगह EX में एक खाली जगह जाती है।',
      id: 'Siklus {c}: {prod} masih memuat {reg} di MEM, padahal {cons} butuh nilainya sekarang di EX. {cons} tetap di ID, yang di belakangnya tetap di IF, dan slot kosong masuk ke EX sebagai gantinya.',
      pt: 'Ciclo {c}: {prod} ainda está carregando {reg} em MEM, e {cons} precisa dele agora em EX. {cons} fica em ID, a de trás fica em IF, e um espaço vazio entra em EX no lugar.',
    },
    'caption.stallAlone': {
      en: 'Cycle {c}: {prod} is still loading {reg} in MEM, and {cons} needs it in EX now. {cons} stays in ID, and an empty slot goes into EX instead.',
      ko: '사이클 {c}: {reg} 값은 {prod} 의 MEM 이 끝나야 나오는데, 그 값을 지금 EX 에서 써야 할 차례는 {cons}. 그래서 {cons} 쪽은 ID 에 머물고 EX 에는 빈 칸이 대신 들어간다.',
      ja: 'サイクル {c}: {prod} はまだ MEM で {reg} をロード中なのに、{cons} は今 EX でその値が要る。{cons} は ID にとどまり、EX には代わりに空きが入る。',
      zh: '周期 {c}：{prod} 还在 MEM 中加载 {reg}，而 {cons} 现在就要在 EX 中用它。{cons} 留在 ID，EX 里改为进入一个空槽。',
      ar: 'الدورة {c}: لا يزال {prod} يحمّل {reg} في MEM، و{cons} يحتاجه الآن في EX. يبقى {cons} في ID، وتدخل خانة فارغة إلى EX بدلًا منه.',
      es: 'Ciclo {c}: {prod} todavía está cargando {reg} en MEM y {cons} lo necesita ya en EX. {cons} se queda en ID y en su lugar entra un hueco en EX.',
      fr: 'Cycle {c} : {prod} charge encore {reg} en MEM, et {cons} en a besoin tout de suite en EX. {cons} reste en ID, et une case vide entre en EX à sa place.',
      hi: 'चक्र {c}: {prod} अभी भी MEM में {reg} लोड कर रहा है, और {cons} को यह अभी EX में चाहिए। {cons} ID में रुकता है, और उसकी जगह EX में एक खाली जगह जाती है।',
      id: 'Siklus {c}: {prod} masih memuat {reg} di MEM, padahal {cons} butuh nilainya sekarang di EX. {cons} tetap di ID, dan slot kosong masuk ke EX sebagai gantinya.',
      pt: 'Ciclo {c}: {prod} ainda está carregando {reg} em MEM, e {cons} precisa dele agora em EX. {cons} fica em ID, e um espaço vazio entra em EX no lugar.',
    },
    'caption.forward': {
      en: 'Cycle {c}: {reg} = {value} is forwarded from MEM/WB to EX, and {cons} computes {rd} = {result}. The empty slot moves on to MEM.',
      ko: '사이클 {c}: MEM/WB 에서 EX 로 {reg} = {value} 전달. {cons} 의 셈은 {rd} = {result}. 빈 칸은 MEM 으로 흘러간다.',
      ja: 'サイクル {c}: {reg} = {value} が MEM/WB から EX へフォワードされ、{cons} は {rd} = {result} を計算する。空きは MEM へ流れる。',
      zh: '周期 {c}：{reg} = {value} 从 MEM/WB 转发到 EX，{cons} 算出 {rd} = {result}。空槽流到 MEM。',
      ar: 'الدورة {c}: تُمرَّر {reg} = {value} من MEM/WB إلى EX، ويحسب {cons} القيمة {rd} = {result}. تنتقل الخانة الفارغة إلى MEM.',
      es: 'Ciclo {c}: {reg} = {value} se adelanta de MEM/WB a EX, y {cons} calcula {rd} = {result}. El hueco pasa a MEM.',
      fr: 'Cycle {c} : {reg} = {value} est transmis de MEM/WB à EX, et {cons} calcule {rd} = {result}. La case vide passe en MEM.',
      hi: 'चक्र {c}: {reg} = {value} MEM/WB से EX में फ़ॉरवर्ड होता है, और {cons} {rd} = {result} निकालता है। खाली जगह MEM में जाती है।',
      id: 'Siklus {c}: {reg} = {value} diteruskan dari MEM/WB ke EX, dan {cons} menghitung {rd} = {result}. Slot kosong bergeser ke MEM.',
      pt: 'Ciclo {c}: {reg} = {value} é encaminhado de MEM/WB para EX, e {cons} calcula {rd} = {result}. O espaço vazio segue para MEM.',
    },
    'caption.forwardPlain': {
      en: 'Cycle {c}: {reg} is forwarded from MEM/WB to EX for {cons}. The empty slot moves on to MEM.',
      ko: '사이클 {c}: MEM/WB 에서 EX 로 {reg} 전달, 받는 쪽은 {cons}. 빈 칸은 MEM 으로 흘러간다.',
      ja: 'サイクル {c}: {reg} が MEM/WB から EX の {cons} へフォワードされる。空きは MEM へ流れる。',
      zh: '周期 {c}：{reg} 从 MEM/WB 转发到 EX，交给 {cons}。空槽流到 MEM。',
      ar: 'الدورة {c}: تُمرَّر {reg} من MEM/WB إلى EX من أجل {cons}. تنتقل الخانة الفارغة إلى MEM.',
      es: 'Ciclo {c}: {reg} se adelanta de MEM/WB a EX para {cons}. El hueco pasa a MEM.',
      fr: 'Cycle {c} : {reg} est transmis de MEM/WB à EX pour {cons}. La case vide passe en MEM.',
      hi: 'चक्र {c}: {cons} के लिए {reg} MEM/WB से EX में फ़ॉरवर्ड होता है। खाली जगह MEM में जाती है।',
      id: 'Siklus {c}: {reg} diteruskan dari MEM/WB ke EX untuk {cons}. Slot kosong bergeser ke MEM.',
      pt: 'Ciclo {c}: {reg} é encaminhado de MEM/WB para EX para {cons}. O espaço vazio segue para MEM.',
    },
    'caption.bubbleWb': {
      en: 'Cycle {c}: the empty slot reaches WB. Nothing is written back in this cycle.',
      ko: '사이클 {c}: 빈 칸이 WB 에 닿았다. 이번 사이클에는 아무것도 레지스터에 쓰이지 않는다.',
      ja: 'サイクル {c}: 空きが WB に着いた。このサイクルでは何も書き戻されない。',
      zh: '周期 {c}：空槽到达 WB。这个周期没有任何写回。',
      ar: 'الدورة {c}: تصل الخانة الفارغة إلى WB. لا يُكتب شيء في هذه الدورة.',
      es: 'Ciclo {c}: el hueco llega a WB. En este ciclo no se escribe nada.',
      fr: 'Cycle {c} : la case vide atteint WB. Rien n’est réécrit pendant ce cycle.',
      hi: 'चक्र {c}: खाली जगह WB तक पहुँचती है। इस चक्र में कुछ भी वापस नहीं लिखा जाता।',
      id: 'Siklus {c}: slot kosong sampai di WB. Tidak ada yang ditulis balik pada siklus ini.',
      pt: 'Ciclo {c}: o espaço vazio chega a WB. Nada é escrito neste ciclo.',
    },
    'caption.bubbleOut': {
      en: 'Cycle {c}: the empty slot has left. What came out of WB now has a hole at cycle {gap}.',
      ko: '사이클 {c}: 빈 칸이 빠져나갔다. WB 를 떠난 줄에는 사이클 {gap} 자리에 구멍이 남는다.',
      ja: 'サイクル {c}: 空きが抜けた。WB から出た列には、サイクル {gap} のところに穴が残る。',
      zh: '周期 {c}：空槽已经离开。离开 WB 的那一列在周期 {gap} 处留下一个空洞。',
      ar: 'الدورة {c}: خرجت الخانة الفارغة. صار فيما خرج من WB ثقب عند الدورة {gap}.',
      es: 'Ciclo {c}: el hueco ya salió. Lo que salió de WB tiene ahora un agujero en el ciclo {gap}.',
      fr: 'Cycle {c} : la case vide est sortie. Ce qui est sorti de WB a maintenant un trou au cycle {gap}.',
      hi: 'चक्र {c}: खाली जगह निकल गई। WB से निकली पंक्ति में अब चक्र {gap} पर एक छेद है।',
      id: 'Siklus {c}: slot kosong sudah keluar. Yang keluar dari WB kini berlubang di siklus {gap}.',
      pt: 'Ciclo {c}: o espaço vazio saiu. O que saiu de WB agora tem um buraco no ciclo {gap}.',
    },
    'caption.done': {
      en: 'All {n} instructions are finished at cycle {end}. Cycles lost to stalls: {lost}. Without them they would have finished at cycle {ideal}.',
      ko: '명령어 {n}개가 모두 끝난 때는 사이클 {end}. 멈춤으로 잃은 사이클: {lost}. 멈춤이 없었다면 사이클 {ideal}.',
      ja: '{n} 個の命令がすべて終わったのはサイクル {end}。ストールで失ったサイクル: {lost}。それがなければサイクル {ideal} だった。',
      zh: '{n} 条指令全部完成于周期 {end}。停顿损失的周期：{lost}。没有停顿的话会在周期 {ideal} 完成。',
      ar: 'انتهت التعليمات الـ{n} كلها في الدورة {end}. الدورات الضائعة بسبب التوقف: {lost}. لولاها لانتهت في الدورة {ideal}.',
      es: 'Las {n} instrucciones terminan en el ciclo {end}. Ciclos perdidos por detenciones: {lost}. Sin ellas habrían terminado en el ciclo {ideal}.',
      fr: 'Les {n} instructions sont terminées au cycle {end}. Cycles perdus en arrêts : {lost}. Sans eux, elles l’auraient été au cycle {ideal}.',
      hi: 'सभी {n} निर्देश चक्र {end} पर पूरे होते हैं। रुकावटों में गए चक्र: {lost}। उनके बिना वे चक्र {ideal} पर पूरे हो जाते।',
      id: 'Semua {n} instruksi selesai di siklus {end}. Siklus yang hilang karena berhenti: {lost}. Tanpa itu, semuanya selesai di siklus {ideal}.',
      pt: 'As {n} instruções terminam no ciclo {end}. Ciclos perdidos com paradas: {lost}. Sem elas, teriam terminado no ciclo {ideal}.',
    },
    'caption.doneNoStall': {
      en: 'All {n} instructions are finished at cycle {end}, with no stalls.',
      ko: '명령어 {n}개가 모두 끝난 때는 사이클 {end}. 멈춤은 없었다.',
      ja: '{n} 個の命令はストールなしでサイクル {end} にすべて終わった。',
      zh: '{n} 条指令在周期 {end} 全部完成，没有停顿。',
      ar: 'انتهت التعليمات الـ{n} كلها في الدورة {end} دون أي توقف.',
      es: 'Las {n} instrucciones terminan en el ciclo {end}, sin detenciones.',
      fr: 'Les {n} instructions sont terminées au cycle {end}, sans aucun arrêt.',
      hi: 'सभी {n} निर्देश बिना किसी रुकावट के चक्र {end} पर पूरे होते हैं।',
      id: 'Semua {n} instruksi selesai di siklus {end}, tanpa berhenti.',
      pt: 'As {n} instruções terminam no ciclo {end}, sem paradas.',
    },
  },
};
