import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';
import type { NetworkLayerData } from './algorithm.js';

const initialData: NetworkLayerData = {
  type: 'network-layer',
  stepMs: 600,
  message: 1200,
  layers: [
    { id: 'transport', header: 20, trailer: 0 },
    { id: 'network', header: 20, trailer: 0 },
    { id: 'link', header: 14, trailer: 4 },
  ],
  stack: ['application', 'transport', 'network', 'link', 'physical'],
  routerStack: ['network', 'link', 'physical'],
  splits: [1, 2, 3, 4, 6, 12],
  linkCounts: [1, 2, 3, 5],
  nodes: ['A', 'R1', 'R2', 'R3', 'R4', 'B'],
  split: 1,
  links: 3,
};

export const networkLayerFacet: FacetJson = {
  id: 'facet:networkLayer',
  title: {
    en: 'Encapsulation and hop-by-hop delivery',
    ko: '캡슐화와 홉 전달',
    ja: 'カプセル化とホップごとの転送',
    zh: '封装与逐跳传递',
    ar: 'التغليف والتسليم قفزة بقفزة',
    es: 'Encapsulación y entrega salto a salto',
    fr: 'Encapsulation et acheminement saut par saut',
    hi: 'एनकैप्सुलेशन और हॉप-दर-हॉप डिलीवरी',
    id: 'Enkapsulasi dan pengiriman hop demi hop',
    pt: 'Encapsulamento e entrega salto a salto',
  },
  description: {
    en: 'Splitting a message adds headers to every piece, yet lets the links work at once — and the number of links decides which split arrives first.',
    ko: '메시지를 쪼개면 조각마다 머리가 붙지만 여러 링크가 함께 일한다 — 가장 빨리 닿는 쪼갬은 링크 수가 정한다.',
    ja: 'メッセージを分割すると断片ごとにヘッダが付くが、複数のリンクが同時に働く — 最も早く届く分割数はリンク数が決める。',
    zh: '把消息切分后每一片都要加报头，但多条链路可以同时工作——最快到达的切分数由链路数决定。',
    ar: 'تقسيم الرسالة يضيف ترويسات لكل قطعة لكنه يجعل الروابط تعمل معًا — وعدد الروابط يحدد أي تقسيم يصل أولًا.',
    es: 'Dividir un mensaje añade cabeceras a cada trozo, pero permite que los enlaces trabajen a la vez; el número de enlaces decide qué división llega antes.',
    fr: 'Découper un message ajoute des en-têtes à chaque morceau, mais fait travailler les liens en même temps ; le nombre de liens décide quel découpage arrive le premier.',
    hi: 'संदेश को टुकड़ों में बाँटने से हर टुकड़े पर हेडर जुड़ते हैं, पर कई लिंक एक साथ काम करते हैं — सबसे पहले कौन-सा बँटवारा पहुँचेगा, यह लिंक की संख्या तय करती है।',
    id: 'Memecah pesan menambah header pada setiap potongan, tetapi membuat tautan bekerja bersamaan — jumlah tautan menentukan pemecahan mana yang tiba paling awal.',
    pt: 'Dividir uma mensagem acrescenta cabeçalhos a cada pedaço, mas deixa os enlaces trabalharem ao mesmo tempo — o número de enlaces decide qual divisão chega primeiro.',
  },
  algorithm: 'module:networkLayer',
  projector: 'module:networkLayerProjector',
  initialData,
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }, { ref: 'codePanel' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'network-layer-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'split',
          name: 'split',
          label: {
            en: 'Pieces',
            ko: '쪼갠 수',
            ja: '分割数',
            zh: '切分数',
            ar: 'عدد القطع',
            es: 'Trozos',
            fr: 'Morceaux',
            hi: 'टुकड़े',
            id: 'Potongan',
            pt: 'Pedaços',
          },
          segments: [
            { value: 1, label: '1', default: true },
            { value: 2, label: '2' },
            { value: 3, label: '3' },
            { value: 4, label: '4' },
            { value: 6, label: '6' },
            { value: 12, label: '12' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'links',
          name: 'links',
          label: {
            en: 'Links',
            ko: '링크 수',
            ja: 'リンク数',
            zh: '链路数',
            ar: 'عدد الروابط',
            es: 'Enlaces',
            fr: 'Liens',
            hi: 'लिंक',
            id: 'Tautan',
            pt: 'Enlaces',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2' },
            { value: 3, label: '3', default: true },
            { value: 5, label: '5' },
          ],
        },
      ],
      metrics: [
        {
          name: 'header-bytes',
          label: {
            en: 'Header bytes',
            ko: '머리 바이트',
            ja: 'ヘッダのバイト数',
            zh: '报头字节',
            ar: 'بايتات الترويسة',
            es: 'Bytes de cabecera',
            fr: 'Octets d’en-tête',
            hi: 'हेडर बाइट',
            id: 'Byte header',
            pt: 'Bytes de cabeçalho',
          },
          initial: 0,
        },
        {
          name: 'payload-share',
          label: {
            en: 'Application share %',
            ko: '응용 몫 %',
            ja: 'アプリデータの割合 %',
            zh: '应用数据占比 %',
            ar: 'حصة التطبيق %',
            es: 'Parte de aplicación %',
            fr: 'Part applicative %',
            hi: 'ऐप्लिकेशन हिस्सा %',
            id: 'Porsi aplikasi %',
            pt: 'Parte da aplicação %',
          },
          initial: 0,
        },
        {
          name: 'elapsed-time',
          label: {
            en: 'Elapsed (byte times)',
            ko: '지난 시간 (바이트 시간)',
            ja: '経過 (バイト時間)',
            zh: '已过时间 (字节时间)',
            ar: 'الوقت المنقضي (زمن بايت)',
            es: 'Transcurrido (tiempos de byte)',
            fr: 'Écoulé (temps d’octet)',
            hi: 'बीता समय (बाइट समय)',
            id: 'Berlalu (waktu byte)',
            pt: 'Decorrido (tempos de byte)',
          },
          initial: 0,
        },
      ],
    },
    codePanel: {
      type: 'code-view',
      ir: 'ir:network-layer-imperative',
      label: {
        en: 'Finish time',
        ko: '끝 시각',
        ja: '終了時刻',
        zh: '完成时刻',
        ar: 'وقت الانتهاء',
        es: 'Tiempo de llegada',
        fr: 'Instant d’arrivée',
        hi: 'पूरा होने का समय',
        id: 'Waktu selesai',
        pt: 'Tempo de chegada',
      },
    },
  },
  messages: {
    'caption.split': {
      en: 'Pieces: {n} · Piece size: {size} bytes · Links: {links}',
      ko: '조각 수: {n} · 조각 크기: {size} 바이트 · 링크 수: {links}',
      ja: '断片数: {n} · 断片の大きさ: {size} バイト · リンク数: {links}',
      zh: '片数: {n} · 每片大小: {size} 字节 · 链路数: {links}',
      ar: 'القطع: {n} · حجم القطعة: {size} بايت · الروابط: {links}',
      es: 'Trozos: {n} · Tamaño del trozo: {size} bytes · Enlaces: {links}',
      fr: 'Morceaux : {n} · Taille d’un morceau : {size} octets · Liens : {links}',
      hi: 'टुकड़े: {n} · टुकड़े का आकार: {size} बाइट · लिंक: {links}',
      id: 'Potongan: {n} · Ukuran potongan: {size} byte · Tautan: {links}',
      pt: 'Pedaços: {n} · Tamanho do pedaço: {size} bytes · Enlaces: {links}',
    },
    'caption.forward': {
      en: 'Tick {tick} · Busy links: {busy} · Elapsed: {elapsed} byte times',
      ko: '틱 {tick} · 바쁜 링크 수: {busy} · 지난 시간: {elapsed} 바이트 시간',
      ja: 'ティック {tick} · 使用中のリンク: {busy} · 経過: {elapsed} バイト時間',
      zh: '第 {tick} 拍 · 忙碌链路数: {busy} · 已过: {elapsed} 字节时间',
      ar: 'النبضة {tick} · الروابط المشغولة: {busy} · المنقضي: {elapsed} زمن بايت',
      es: 'Tic {tick} · Enlaces ocupados: {busy} · Transcurrido: {elapsed} tiempos de byte',
      fr: 'Top {tick} · Liens occupés : {busy} · Écoulé : {elapsed} temps d’octet',
      hi: 'टिक {tick} · व्यस्त लिंक: {busy} · बीता समय: {elapsed} बाइट समय',
      id: 'Tik {tick} · Tautan sibuk: {busy} · Berlalu: {elapsed} waktu byte',
      pt: 'Tique {tick} · Enlaces ocupados: {busy} · Decorrido: {elapsed} tempos de byte',
    },
    'caption.finish': {
      en: 'Finish time: {finish} byte times · Fastest split: {best}',
      ko: '끝 시각: {finish} 바이트 시간 · 가장 빠른 쪼갠 수: {best}',
      ja: '終了時刻: {finish} バイト時間 · 最速の分割数: {best}',
      zh: '完成时刻: {finish} 字节时间 · 最快切分数: {best}',
      ar: 'وقت الانتهاء: {finish} زمن بايت · أسرع تقسيم: {best}',
      es: 'Llegada: {finish} tiempos de byte · División más rápida: {best}',
      fr: 'Arrivée : {finish} temps d’octet · Découpage le plus rapide : {best}',
      hi: 'पूरा होने का समय: {finish} बाइट समय · सबसे तेज़ बँटवारा: {best}',
      id: 'Waktu selesai: {finish} waktu byte · Pemecahan tercepat: {best}',
      pt: 'Chegada: {finish} tempos de byte · Divisão mais rápida: {best}',
    },
    'label.band.wire': {
      en: 'Bytes over one link: {bytes}',
      ko: '한 링크를 지나는 바이트: {bytes}',
      ja: '1 本のリンクを通るバイト: {bytes}',
      zh: '经过一条链路的字节: {bytes}',
      ar: 'البايتات عبر رابط واحد: {bytes}',
      es: 'Bytes por un enlace: {bytes}',
      fr: 'Octets sur un lien : {bytes}',
      hi: 'एक लिंक से गुज़रने वाले बाइट: {bytes}',
      id: 'Byte melewati satu tautan: {bytes}',
      pt: 'Bytes num enlace: {bytes}',
    },
    'label.band.share': {
      en: 'Application share: {pct}%',
      ko: '응용 몫: {pct}%',
      ja: 'アプリデータの割合: {pct}%',
      zh: '应用数据占比: {pct}%',
      ar: 'حصة التطبيق: {pct}%',
      es: 'Parte de aplicación: {pct}%',
      fr: 'Part applicative : {pct}%',
      hi: 'ऐप्लिकेशन हिस्सा: {pct}%',
      id: 'Porsi aplikasi: {pct}%',
      pt: 'Parte da aplicação: {pct}%',
    },
    'label.bars.title': {
      en: 'Finish time for each split (links: {links})',
      ko: '쪼갠 수마다 끝 시각 (링크 수: {links})',
      ja: '分割数ごとの終了時刻 (リンク数: {links})',
      zh: '各切分数的完成时刻 (链路数: {links})',
      ar: 'وقت الانتهاء لكل تقسيم (الروابط: {links})',
      es: 'Llegada según la división (enlaces: {links})',
      fr: 'Arrivée selon le découpage (liens : {links})',
      hi: 'हर बँटवारे का पूरा होने का समय (लिंक: {links})',
      id: 'Waktu selesai tiap pemecahan (tautan: {links})',
      pt: 'Chegada por divisão (enlaces: {links})',
    },
    'label.bars.fastest': {
      en: '▲ Fastest',
      ko: '▲ 가장 빠름',
      ja: '▲ 最速',
      zh: '▲ 最快',
      ar: '▲ الأسرع',
      es: '▲ Más rápida',
      fr: '▲ Le plus rapide',
      hi: '▲ सबसे तेज़',
      id: '▲ Tercepat',
      pt: '▲ Mais rápida',
    },
    'label.finishMark': {
      en: 'Finish: {finish}',
      ko: '끝: {finish}',
      ja: '終了: {finish}',
      zh: '完成: {finish}',
      ar: 'الانتهاء: {finish}',
      es: 'Llegada: {finish}',
      fr: 'Arrivée : {finish}',
      hi: 'पूरा: {finish}',
      id: 'Selesai: {finish}',
      pt: 'Chegada: {finish}',
    },
    'label.layer.application': {
      en: 'Application',
      ko: '응용',
      ja: 'アプリケーション',
      zh: '应用层',
      ar: 'التطبيق',
      es: 'Aplicación',
      fr: 'Application',
      hi: 'ऐप्लिकेशन',
      id: 'Aplikasi',
      pt: 'Aplicação',
    },
    'label.layer.transport': {
      en: 'Transport',
      ko: '전송',
      ja: 'トランスポート',
      zh: '传输层',
      ar: 'النقل',
      es: 'Transporte',
      fr: 'Transport',
      hi: 'ट्रांसपोर्ट',
      id: 'Transpor',
      pt: 'Transporte',
    },
    'label.layer.network': {
      en: 'Network',
      ko: '네트워크',
      ja: 'ネットワーク',
      zh: '网络层',
      ar: 'الشبكة',
      es: 'Red',
      fr: 'Réseau',
      hi: 'नेटवर्क',
      id: 'Jaringan',
      pt: 'Rede',
    },
    'label.layer.link': {
      en: 'Link',
      ko: '링크',
      ja: 'リンク',
      zh: '链路层',
      ar: 'الربط',
      es: 'Enlace',
      fr: 'Liaison',
      hi: 'लिंक',
      id: 'Tautan',
      pt: 'Enlace',
    },
    'label.layer.physical': {
      en: 'Physical',
      ko: '물리',
      ja: '物理',
      zh: '物理层',
      ar: 'المادية',
      es: 'Física',
      fr: 'Physique',
      hi: 'भौतिक',
      id: 'Fisik',
      pt: 'Física',
    },
    'label.role.sender': {
      en: 'Sending host',
      ko: '보내는 호스트',
      ja: '送信ホスト',
      zh: '发送主机',
      ar: 'المضيف المرسل',
      es: 'Host emisor',
      fr: 'Hôte émetteur',
      hi: 'भेजने वाला होस्ट',
      id: 'Host pengirim',
      pt: 'Host emissor',
    },
    'label.role.router': {
      en: 'Router',
      ko: '라우터',
      ja: 'ルータ',
      zh: '路由器',
      ar: 'موجّه',
      es: 'Router',
      fr: 'Routeur',
      hi: 'राउटर',
      id: 'Router',
      pt: 'Roteador',
    },
    'label.role.receiver': {
      en: 'Receiving host',
      ko: '받는 호스트',
      ja: '受信ホスト',
      zh: '接收主机',
      ar: 'المضيف المستقبل',
      es: 'Host receptor',
      fr: 'Hôte récepteur',
      hi: 'पाने वाला होस्ट',
      id: 'Host penerima',
      pt: 'Host receptor',
    },
    'label.legend.link': {
      en: 'Link header · trailer',
      ko: '링크 머리 · 꼬리',
      ja: 'リンクのヘッダ · トレーラ',
      zh: '链路报头 · 报尾',
      ar: 'ترويسة الربط · ذيله',
      es: 'Cabecera · cola de enlace',
      fr: 'En-tête · queue de liaison',
      hi: 'लिंक हेडर · ट्रेलर',
      id: 'Header · trailer tautan',
      pt: 'Cabeçalho · cauda de enlace',
    },
    'label.legend.network': {
      en: 'Network header',
      ko: '네트워크 머리',
      ja: 'ネットワークのヘッダ',
      zh: '网络报头',
      ar: 'ترويسة الشبكة',
      es: 'Cabecera de red',
      fr: 'En-tête réseau',
      hi: 'नेटवर्क हेडर',
      id: 'Header jaringan',
      pt: 'Cabeçalho de rede',
    },
    'label.legend.transport': {
      en: 'Transport header',
      ko: '전송 머리',
      ja: 'トランスポートのヘッダ',
      zh: '传输报头',
      ar: 'ترويسة النقل',
      es: 'Cabecera de transporte',
      fr: 'En-tête transport',
      hi: 'ट्रांसपोर्ट हेडर',
      id: 'Header transpor',
      pt: 'Cabeçalho de transporte',
    },
    'label.legend.data': {
      en: 'Application data',
      ko: '응용 데이터',
      ja: 'アプリデータ',
      zh: '应用数据',
      ar: 'بيانات التطبيق',
      es: 'Datos de aplicación',
      fr: 'Données applicatives',
      hi: 'ऐप्लिकेशन डेटा',
      id: 'Data aplikasi',
      pt: 'Dados da aplicação',
    },
    'label.axis.byteTime': {
      en: 'Byte time',
      ko: '바이트 시간',
      ja: 'バイト時間',
      zh: '字节时间',
      ar: 'زمن البايت',
      es: 'Tiempo de byte',
      fr: 'Temps d’octet',
      hi: 'बाइट समय',
      id: 'Waktu byte',
      pt: 'Tempo de byte',
    },
    'label.axis.pieces': {
      en: 'Pieces',
      ko: '쪼갠 수',
      ja: '分割数',
      zh: '切分数',
      ar: 'القطع',
      es: 'Trozos',
      fr: 'Morceaux',
      hi: 'टुकड़े',
      id: 'Potongan',
      pt: 'Pedaços',
    },
  },
};
