/**
 * 선형 회귀 facet JSON 선언.
 *
 * 진행 모델: 시간 진행형 (mount 직후 자동 시연 한 호흡 — 수렴 또는 발산까지).
 * ReactiveMechanism 위에 자동 시연 + pollInput 인터럽트 패턴.
 *
 * 컨트롤바 어휘 (기획 §6 §8):
 *   [ ▶ play ] [ ⏸ pause ] [ ⏭ step ] [ ↺ reset ]
 *   [ 학습률 segmented-slider: 느림 / 적정 / 발산 ]
 *
 * 식별자 (C1): `point:` `line:` `square:` `param:` `loss:` `flag:` 명시 prefix.
 *
 * 기획서의 14점 데이터는 y = 1.8x + 0.5 + 잡음(σ ≈ 0.6) 의 고정 시드.
 * 여기서는 결정적 14점 (시드 hash 없이 직접 명시).
 */

import type { FacetJson } from '@ffacet/core/runtime';

// 고정 시드 14점 — y ≈ 1.8x + 0.5 + 가우시안 잡음. 잡음은 결정적 값.
const POINTS_14: Array<{ x: number; y: number }> = [
  { x: 0.30, y: 0.78 },
  { x: 0.55, y: 1.62 },
  { x: 0.85, y: 1.40 },
  { x: 1.10, y: 2.78 },
  { x: 1.40, y: 2.55 },
  { x: 1.75, y: 3.95 },
  { x: 2.05, y: 4.10 },
  { x: 2.40, y: 5.30 },
  { x: 2.70, y: 4.85 },
  { x: 3.05, y: 6.40 },
  { x: 3.40, y: 6.10 },
  { x: 3.70, y: 7.55 },
  { x: 4.05, y: 7.20 },
  { x: 4.45, y: 8.85 },
];

export const linearRegressionFacet: FacetJson = {
  id: 'facet:linearRegression',
  title: { en: 'Linear Regression — A Line Through the Points', ko: '선형 회귀 — 점들 사이를 가르는 직선', ja: '線形回帰 — 点の間を貫く直線', zh: '线性回归 — 穿过点群的一条直线', ar: 'الانحدار الخطي — خط يشقّ النقاط', es: 'Regresión lineal: una recta entre los puntos', fr: 'Régression linéaire — une droite à travers les points', hi: 'रैखिक प्रतिगमन — बिंदुओं के बीच एक रेखा', id: 'Regresi linear — sebuah garis menembus titik', pt: 'Regressão linear — uma reta entre os pontos' },
  description: { en: 'Fit a line by sliding (w, b) downhill — residual squares shrink as a point rolls into the valley', ko: '잔차 정사각형의 면적을 줄이며 매개변수 평면 위 점이 골짜기로 굴러가는 학습 운동', ja: '(w, b) を坂の下へ滑らせて直線を合わせる — 残差の正方形が縮むにつれ、点が谷へ転がっていく', zh: '让 (w, b) 顺坡下滑来拟合直线 — 残差方块缩小，点也就滚进了谷底', ar: 'نلائم الخط بإنزلاق (w, b) نحو الأسفل — تتقلّص مربعات البواقي بينما تتدحرج النقطة إلى الوادي', es: 'Ajustar una recta deslizando (w, b) cuesta abajo: los cuadrados de residuos encogen mientras el punto rueda al valle', fr: 'Ajuster une droite en faisant glisser (w, b) vers le bas — les carrés des résidus rétrécissent tandis que le point roule dans la vallée', hi: '(w, b) को ढलान पर सरकाकर रेखा बिठाना — अवशेष वर्ग सिकुड़ते हैं और बिंदु घाटी में लुढ़कता है', id: 'Mencocokkan garis dengan meluncurkan (w, b) menuruni lereng — kuadrat residu mengecil sementara titik menggelinding ke lembah', pt: 'Ajustar uma reta deslizando (w, b) ladeira abaixo — os quadrados dos resíduos encolhem enquanto o ponto rola ao vale' },
  algorithm: 'module:linearRegression',
  projector: 'module:linearRegressionProjector',
  initialData: {
    type: 'linear-regression',
    points: POINTS_14,
    initialW: -0.5,
    initialB: 3.0,
    lrSegments: [
      { value: 0.01, id: 'slow' },
      { value: 0.05, id: 'tuned' },
      { value: 0.18, id: 'diverge' },
    ],
    initialLrIndex: 1,
    timings: {
      autoStepIntervalMs: 200,
      stepDurationMs: 350,
      divergePulseMs: 420,
    },
    convergenceEpsilon: 0.005,
    maxAutoSteps: 200,
    contourLevels: 6,
    paramRange: [-1.5, 3.5, -1, 4],
  },
  shuffleOnReset: false,
  layout: {
    type: 'column',
    gap: 8,
    children: [
      { ref: 'header' },
      { ref: 'stage', padding: '8px 0' },
      { ref: 'controls' },
    ],
  },
  messages: {
    'caption.base': {
      en: 'Linear regression threads one straight line through a cloud of points, turning each residual into the area of a square, and nudges the line a step at a time so the total of those areas shrinks.',
      ko: '선형 회귀는 점 무리에 직선 한 줄을 끼우되, 잔차의 제곱을 면적으로 환원해 그 면적의 합이 가장 작아지도록 직선을 매 반복마다 한 걸음씩 회전·이동시키는 학습 운동이다.',
      ja: '線形回帰は点の群れに一本の直線を通し、残差それぞれを正方形の面積に置き換え、その面積の合計が縮むように直線を一歩ずつ動かしていく学習の運動だ。',
      zh: '线性回归在点群中穿过一条直线，把每个残差换算成一个正方形的面积，并一步一步地挪动直线，让这些面积的总和不断变小。',
      ar: 'يمرّر الانحدار الخطي خطًا مستقيمًا واحدًا عبر سحابة من النقاط، ويحوّل كل باقٍ إلى مساحة مربع، ثم يزحزح الخط خطوة تلو خطوة حتى يتقلّص مجموع تلك المساحات.',
      es: 'La regresión lineal pasa una sola recta por una nube de puntos, convierte cada residuo en el área de un cuadrado y va empujando la recta paso a paso para que la suma de esas áreas se encoja.',
      fr: 'La régression linéaire fait passer une seule droite dans un nuage de points, transforme chaque résidu en l\'aire d\'un carré, et déplace la droite pas à pas pour que la somme de ces aires diminue.',
      hi: 'रैखिक प्रतिगमन बिंदुओं के झुंड में एक ही सीधी रेखा पिरोता है, हर अवशेष को एक वर्ग के क्षेत्रफल में बदलता है, और रेखा को कदम-दर-कदम सरकाता है ताकि उन क्षेत्रफलों का योग घटता जाए।',
      id: 'Regresi linear menembuskan satu garis lurus melalui gugus titik, mengubah tiap residu menjadi luas sebuah persegi, lalu menyenggol garis itu selangkah demi selangkah agar jumlah luas tersebut mengecil.',
      pt: 'A regressão linear passa uma única reta por uma nuvem de pontos, transforma cada resíduo na área de um quadrado e empurra a reta passo a passo para que a soma dessas áreas encolha.',
    },
    'caption.converged': {
      en: 'Converged — it will not shrink any further.',
      ko: '수렴 — 더 줄지 않는다.',
      ja: '収束しました — これ以上は縮みません。',
      zh: '已收敛 — 不会再缩小了。',
      ar: 'تقارب — لن يتقلّص أكثر من ذلك.',
      es: 'Convergió: ya no se encogerá más.',
      fr: 'Convergé — cela ne diminuera plus.',
      hi: 'अभिसरण हो गया — अब और नहीं घटेगा।',
      id: 'Konvergen — tidak akan mengecil lagi.',
      pt: 'Convergiu — não vai encolher mais.',
    },
    'caption.diverged': {
      en: 'The learning rate is too large — the line diverged.',
      ko: '학습률이 너무 크다 — 직선이 발산했다.',
      ja: '学習率が大きすぎます — 直線が発散しました。',
      zh: '学习率太大 — 直线发散了。',
      ar: 'معدل التعلم كبير جدًا — تباعد الخط.',
      es: 'La tasa de aprendizaje es demasiado grande: la recta divergió.',
      fr: 'Le taux d\'apprentissage est trop grand — la droite a divergé.',
      hi: 'अधिगम दर बहुत बड़ी है — रेखा अपसरित हो गई।',
      id: 'Laju belajar terlalu besar — garisnya divergen.',
      pt: 'A taxa de aprendizado está grande demais — a reta divergiu.',
    },
    'caption.lrChanged': {
      en: 'learning rate → {label} (η = {eta})',
      ko: '학습률 → {label} (η = {eta})',
      ja: '学習率 → {label} (η = {eta})',
      zh: '学习率 → {label} (η = {eta})',
      ar: 'معدل التعلم ← {label} (η = {eta})',
      es: 'tasa de aprendizaje → {label} (η = {eta})',
      fr: 'taux d\'apprentissage → {label} (η = {eta})',
      hi: 'अधिगम दर → {label} (η = {eta})',
      id: 'laju belajar → {label} (η = {eta})',
      pt: 'taxa de aprendizado → {label} (η = {eta})',
    },
    'concept.line1': {
      en: 'Linear regression threads one line through a cloud of points,',
      ko: '선형 회귀는 점 무리에 직선 한 줄을 끼우되, 잔차 제곱을',
      ja: '線形回帰は点の群れに一本の直線を通し、',
      zh: '线性回归在点群中穿过一条直线，',
      ar: 'يمرّر الانحدار الخطي خطًا واحدًا عبر سحابة نقاط،',
      es: 'La regresión lineal pasa una recta por una nube de puntos,',
      fr: 'La régression linéaire fait passer une droite dans un nuage de points,',
      hi: 'रैखिक प्रतिगमन बिंदुओं के झुंड में एक सीधी रेखा पिरोता है,',
      id: 'Regresi linear menembuskan satu garis lurus melalui gugus titik,',
      pt: 'A regressão linear passa uma reta por uma nuvem de pontos,',
    },
    'concept.line2': {
      en: 'turning each residual into an area and rotating and shifting the line',
      ko: '면적으로 환원해 그 면적의 합이 가장 작아지도록 직선을 매',
      ja: '残差それぞれを面積に置き換え、直線を一歩ずつ',
      zh: '把每个残差换成面积，再每次迭代把直线',
      ar: 'محوّلًا كل باقٍ إلى مساحة، ويدير الخط ويزيحه',
      es: 'convierte cada residuo en un área y gira y desplaza la recta',
      fr: 'transforme chaque résidu en aire et fait tourner et glisser la droite',
      hi: 'हर अवशेष को क्षेत्रफल में बदलता है और रेखा को हर पुनरावृत्ति',
      id: 'mengubah tiap residu menjadi luas, lalu memutar dan menggeser garis',
      pt: 'transforma cada resíduo numa área e gira e desloca a reta',
    },
    'concept.line3': {
      en: 'one step per iteration so those areas add up to as little as possible.',
      ko: '반복마다 한 걸음씩 회전·이동시키는 학습 운동이다.',
      ja: '回し動かして、その面積の合計を最小にしていく。',
      zh: '旋转、平移一步，使这些面积之和尽可能小。',
      ar: 'خطوة كل تكرار حتى تصير مجموع تلك المساحات أصغر ما يمكن.',
      es: 'un paso por iteración para que esas áreas sumen lo menos posible.',
      fr: 'd\'un pas par itération pour que ces aires totalisent le moins possible.',
      hi: 'में एक कदम घुमाता-खिसकाता है ताकि वे क्षेत्रफल न्यूनतम जुड़ें।',
      id: 'satu langkah tiap iterasi agar jumlah luas itu sekecil mungkin.',
      pt: 'um passo por iteração para que essas áreas somem o mínimo possível.',
    },
    'label.aria': {
      en: 'Linear regression visualization — residual squares synchronized one-to-one with the contour map',
      ko: '선형 회귀 시각화 — 잔차 정사각형과 등고선의 1:1 동기',
      ja: '線形回帰の可視化 — 残差の正方形と等高線が一対一で同期する',
      zh: '线性回归可视化 — 残差方块与等高线一一同步',
      ar: 'تصور الانحدار الخطي — مربعات البواقي متزامنة واحدًا لواحد مع خريطة الكنتور',
      es: 'Visualización de regresión lineal: cuadrados de residuos sincronizados uno a uno con el mapa de contorno',
      fr: 'Visualisation de régression linéaire — carrés des résidus synchronisés un à un avec la carte de contour',
      hi: 'रैखिक प्रतिगमन का दृश्यीकरण — अवशेष वर्ग समोच्च मानचित्र से एक-एक कर समकालिक',
      id: 'Visualisasi regresi linear — kuadrat residu tersinkron satu-satu dengan peta kontur',
      pt: 'Visualização de regressão linear — quadrados dos resíduos sincronizados um a um com o mapa de contorno',
    },
    'label.contour': {
      en: 'contours: outer = larger, centre = smaller',
      ko: '등고선: 바깥=큼, 중심=작음',
      ja: '等高線: 外側 = 大きい, 中心 = 小さい',
      zh: '等高线: 外圈 = 大, 中心 = 小',
      ar: 'الكنتور: الخارج = أكبر، المركز = أصغر',
      es: 'contornos: exterior = mayor, centro = menor',
      fr: 'contours : extérieur = plus grand, centre = plus petit',
      hi: 'समोच्च: बाहर = बड़ा, केंद्र = छोटा',
      id: 'kontur: luar = lebih besar, pusat = lebih kecil',
      pt: 'contornos: fora = maior, centro = menor',
    },
    'label.converged': {
      en: 'converged',
      ko: '수렴',
      ja: '収束',
      zh: '收敛',
      ar: 'تقارب',
      es: 'convergido',
      fr: 'convergé',
      hi: 'अभिसरित',
      id: 'konvergen',
      pt: 'convergiu',
    },
    'label.lossCurve': {
      en: 'loss curve — RSS over time t',
      ko: '손실 곡선 — 시간 t 에 따른 RSS',
      ja: '損失曲線 — 時刻 t にともなう RSS',
      zh: '损失曲线 — 随时间 t 的 RSS',
      ar: 'منحنى الخسارة — RSS عبر الزمن t',
      es: 'curva de pérdida — RSS a lo largo de t',
      fr: 'courbe de perte — RSS au fil de t',
      hi: 'हानि वक्र — समय t के साथ RSS',
      id: 'kurva kerugian — RSS sepanjang waktu t',
      pt: 'curva de perda — RSS ao longo de t',
    },
    'label.references': {
      en: 'See also — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      ko: '참고 — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      ja: '参考 — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      zh: '参考 — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      ar: 'انظر أيضًا — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      es: 'Véase también — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      fr: 'Voir aussi — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      hi: 'और देखें — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      id: 'Lihat juga — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
      pt: 'Veja também — Setosa · ml-visualized · Google ML Crash Course · angeloyeo',
    },
    'label.residualSum': {
      en: 'residual sum (signed)',
      ko: '잔차 합 (부호 포함)',
      ja: '残差の和 (符号つき)',
      zh: '残差和 (含符号)',
      ar: 'مجموع البواقي (بإشارة)',
      es: 'suma de residuos (con signo)',
      fr: 'somme des résidus (signée)',
      hi: 'अवशेषों का योग (चिह्न सहित)',
      id: 'jumlah residu (bertanda)',
      pt: 'soma dos resíduos (com sinal)',
    },
    'label.rss': {
      en: 'sum of squared residuals (loss)',
      ko: '잔차 제곱 합 (손실)',
      ja: '残差平方和 (損失)',
      zh: '残差平方和 (损失)',
      ar: 'مجموع مربعات البواقي (الخسارة)',
      es: 'suma de residuos al cuadrado (pérdida)',
      fr: 'somme des carrés des résidus (perte)',
      hi: 'अवशेषों के वर्गों का योग (हानि)',
      id: 'jumlah kuadrat residu (kerugian)',
      pt: 'soma dos quadrados dos resíduos (perda)',
    },
    'label.title': {
      en: 'Linear regression — as the residual areas shrink, the dot rolls down into the valley',
      ko: '선형 회귀 — 잔차의 면적이 줄어들수록 점이 골짜기를 굴러간다',
      ja: '線形回帰 — 残差の面積が縮むほど点は谷へ転がる',
      zh: '线性回归 — 残差面积越小，点就越往谷底滚',
      ar: 'الانحدار الخطي — كلما تقلّصت مساحات البواقي تدحرجت النقطة إلى الوادي',
      es: 'Regresión lineal: cuanto más se encogen las áreas de los residuos, más rueda el punto hacia el valle',
      fr: 'Régression linéaire — plus les aires des résidus rétrécissent, plus le point roule vers la vallée',
      hi: 'रैखिक प्रतिगमन — अवशेषों के क्षेत्रफल जितने घटते हैं, बिंदु उतना घाटी में लुढ़कता है',
      id: 'Regresi linear — makin mengecil luas residu, makin menggelinding titik itu ke lembah',
      pt: 'Regressão linear — quanto mais as áreas dos resíduos encolhem, mais o ponto rola para o vale',
    },
    'lr.diverge': {
      en: 'diverging',
      ko: '발산',
      ja: '発散',
      zh: '发散',
      ar: 'متباعد',
      es: 'divergente',
      fr: 'divergent',
      hi: 'अपसरित',
      id: 'divergen',
      pt: 'divergente',
    },
    'lr.good': {
      en: 'just right',
      ko: '적정',
      ja: 'ちょうどよい',
      zh: '合适',
      ar: 'مناسب',
      es: 'justo',
      fr: 'juste',
      hi: 'उपयुक्त',
      id: 'pas',
      pt: 'adequado',
    },
    'lr.slow': {
      en: 'slow',
      ko: '느림',
      ja: '遅い',
      zh: '慢',
      ar: 'بطيء',
      es: 'lento',
      fr: 'lent',
      hi: 'धीमा',
      id: 'lambat',
      pt: 'lento',
    },
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'linear-regression-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        { widget: 'button', action: 'play', label: { en: '▶ Play', ko: '▶ 재생', ja: '▶ 再生', zh: '▶ 播放', ar: '▶ تشغيل', es: '▶ Reproducir', fr: '▶ Lecture', hi: '▶ चलाएं', id: '▶ Putar', pt: '▶ Reproduzir' } },
        { widget: 'button', action: 'pause', label: { en: '⏸ Pause', ko: '⏸ 일시정지', ja: '⏸ 停止', zh: '⏸ 暂停', ar: '⏸ إيقاف', es: '⏸ Pausa', fr: '⏸ Pause', hi: '⏸ रोकें', id: '⏸ Jeda', pt: '⏸ Pausar' } },
        { widget: 'button', action: 'step', label: { en: '⏭ Step', ko: '⏭ 한 스텝', ja: '⏭ 一歩', zh: '⏭ 单步', ar: '⏭ خطوة', es: '⏭ Paso', fr: '⏭ Pas', hi: '⏭ चरण', id: '⏭ Langkah', pt: '⏭ Passo' } },
        { widget: 'button', action: 'reset', label: { en: '↺ Reset', ko: '↺ 리셋', ja: '↺ リセット', zh: '↺ 重置', ar: '↺ إعادة', es: '↺ Reiniciar', fr: '↺ Réinit.', hi: '↺ रीसेट', id: '↺ Atur ulang', pt: '↺ Reiniciar' } },
        {
          widget: 'segmented-slider',
          action: 'lr',
          name: 'lr',
          label: { en: 'Learning rate', ko: '학습률', ja: '学習率', zh: '学习率', ar: 'معدل التعلم', es: 'Tasa de aprendizaje', fr: 'Taux d\'apprentissage', hi: 'अधिगम दर', id: 'Laju belajar', pt: 'Taxa de aprendizado' },
          segments: [
            { value: 0.01, label: { en: 'Slow', ko: '느림', ja: '遅い', zh: '慢', ar: 'بطيء', es: 'Lento', fr: 'Lent', hi: 'धीमा', id: 'Lambat', pt: 'Lento' } },
            { value: 0.05, label: { en: 'Tuned', ko: '적정', ja: '適正', zh: '合适', ar: 'مناسب', es: 'Justo', fr: 'Juste', hi: 'उपयुक्त', id: 'Pas', pt: 'Adequado' }, default: true },
            { value: 0.18, label: { en: 'Diverge', ko: '발산', ja: '発散', zh: '发散', ar: 'تباعد', es: 'Divergente', fr: 'Divergent', hi: 'अपसरित', id: 'Divergen', pt: 'Divergente' } },
          ],
        },
      ],
    },
  },
};
