/**
 * @piece — 차원을 하나 줄이면 무엇이 사라지는가.
 *
 * 이미 찾아 놓은 축 하나에 점을 수직으로 내려 찍는다. 떨어진 자리가 남는 것이고
 * 떨어진 거리가 잃는 것이다. 축을 **찾는** 일은 이웃 조각이 말한다 — 여기서는
 * 축을 주어진 것으로 두고, 내려 찍는 순간에 무엇이 사라지는지만 본다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const projectAndLoseFacet: FacetJson = {
  id: 'facet:projectAndLose',
  title: {
    en: 'Project and Lose',
    ko: '내려 찍고 잃기',
    ja: '射影して失う',
    zh: '投影与丢失',
    ar: 'الإسقاط والفقد',
    es: 'Proyectar y perder',
    fr: 'Projeter et perdre',
    hi: 'प्रक्षेपण और हानि',
    id: 'Memproyeksi dan kehilangan',
    pt: 'Projetar e perder',
  },
  description: {
    en: 'What disappears when one dimension is dropped.',
    ko: '차원을 하나 줄이면 무엇이 사라지는가.',
    ja: '次元を一つ落とすと何が消えるのか。',
    zh: '少了一个维度，会消失什么。',
    ar: 'ما الذي يختفي عند إسقاط بُعد واحد.',
    es: 'Qué desaparece al quitar una dimensión.',
    fr: 'Ce qui disparaît quand on supprime une dimension.',
    hi: 'एक आयाम हटाने पर क्या गायब हो जाता है।',
    id: 'Apa yang hilang ketika satu dimensi dibuang.',
    pt: 'O que desaparece quando se tira uma dimensão.',
  },
  algorithm: 'module:projectAndLose',
  projector: 'module:projectAndLoseProjector',
  initialData: {
    type: 'project-and-lose',
    /** 점 열둘. [x, y]. */
    points: [
      [1.0, 2.0],
      [2.0, 1.2],
      [2.4, 3.0],
      [3.2, 2.2],
      [3.8, 3.6],
      [4.4, 2.6],
      [5.0, 4.2],
      [5.6, 3.2],
      [2.8, 1.6],
      [4.0, 4.4],
      [1.6, 2.8],
      [5.2, 2.4],
    ],
    /**
     * 내려 찍을 축의 기울기(도). 축은 점들의 무게중심을 지난다 — 그 자리는
     * 알고리즘이 점에서 셈하므로 여기 적지 않는다.
     */
    axisAngleDeg: 24.9,
    stepMs: 750,
  },
  blocks: {
    stage: { type: 'project-and-lose-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.piece },
  },
  messages: {
    'caption.axisGiven': {
      en: 'One axis, already found. The points will drop onto it.',
      ko: '이미 찾아 놓은 축 하나. 여기에 점을 내려 찍는다.',
      ja: 'すでに見つけてある軸が一本。ここに点を落とす。',
      zh: '一条已经找好的轴。点将落到它上面。',
      ar: 'محور واحد، وُجد سلفًا. ستسقط النقاط عليه.',
      es: 'Un eje ya encontrado. Los puntos caerán sobre él.',
      fr: 'Un axe, déjà trouvé. Les points vont y tomber.',
      hi: 'एक अक्ष, पहले से मिला हुआ। बिंदु इसी पर गिरेंगे।',
      id: 'Satu sumbu, sudah ditemukan. Titik-titik akan jatuh ke atasnya.',
      pt: 'Um eixo, já encontrado. Os pontos vão cair sobre ele.',
    },
    'caption.drop': {
      en: 'Each point drops onto the axis at a right angle.',
      ko: '점이 축까지 수직으로 내려 찍힌다.',
      ja: '点が軸へ垂直に落ちる。',
      zh: '每个点垂直落到轴上。',
      ar: 'تسقط كل نقطة على المحور بزاوية قائمة.',
      es: 'Cada punto cae sobre el eje en ángulo recto.',
      fr: "Chaque point tombe sur l'axe à angle droit.",
      hi: 'हर बिंदु अक्ष पर समकोण में गिरता है।',
      id: 'Setiap titik jatuh tegak lurus ke sumbu.',
      pt: 'Cada ponto cai sobre o eixo em ângulo reto.',
    },
    'caption.measure': {
      en: 'The drop distance is what is lost — farthest {max}, average {mean}.',
      ko: '떨어진 거리가 잃는 것 — 가장 먼 것 {max}, 평균 {mean}.',
      ja: '落ちた距離が失うもの — 最も遠いもの {max}、平均 {mean}。',
      zh: '落下的距离就是丢失的东西 — 最远 {max}，平均 {mean}。',
      ar: 'مسافة السقوط هي ما يُفقد — أبعدها {max}، والمتوسط {mean}.',
      es: 'La distancia de caída es lo que se pierde: la mayor {max}, la media {mean}.',
      fr: 'La distance de chute est ce qui se perd — la plus grande {max}, la moyenne {mean}.',
      hi: 'गिरने की दूरी ही खोया हुआ हिस्सा है — सबसे अधिक {max}, औसत {mean}।',
      id: 'Jarak jatuh itulah yang hilang — terjauh {max}, rata-rata {mean}.',
      pt: 'A distância da queda é o que se perde — a maior {max}, a média {mean}.',
    },
    'caption.erase': {
      en: 'Erase the traces. Only the spots on the axis remain.',
      ko: '흔적을 지운다. 남는 것은 축 위의 자리뿐.',
      ja: '跡を消す。残るのは軸の上の位置だけ。',
      zh: '抹去痕迹。只剩下轴上的位置。',
      ar: 'امحُ الآثار. لا يبقى إلا المواضع على المحور.',
      es: 'Se borran los rastros. Solo quedan los puntos sobre el eje.',
      fr: "On efface les traces. Il ne reste que les positions sur l'axe.",
      hi: 'निशान मिटा दें। सिर्फ़ अक्ष पर के स्थान बचते हैं।',
      id: 'Hapus jejaknya. Yang tersisa hanya posisi di atas sumbu.',
      pt: 'Apagam-se os rastros. Só restam as posições sobre o eixo.',
    },
    'caption.ambiguous': {
      en: 'This spot on the axis looks the same from anywhere along this line.',
      ko: '축 위의 이 자리는 이 선 위 어디에서 와도 똑같다.',
      ja: '軸の上のこの位置は、この線上のどこから来ても同じだ。',
      zh: '轴上的这个位置，从这条线上任何地方来都一样。',
      ar: 'هذا الموضع على المحور يبدو نفسه من أي مكان على هذا الخط.',
      es: 'Este punto del eje se ve igual desde cualquier lugar de esta línea.',
      fr: "Cette position sur l'axe est la même d'où qu'on vienne sur cette ligne.",
      hi: 'अक्ष का यह स्थान इस रेखा पर कहीं से भी आएँ, एक जैसा ही दिखता है।',
      id: 'Posisi di sumbu ini tampak sama dari mana pun di garis ini.',
      pt: 'Esta posição no eixo parece a mesma de qualquer ponto desta linha.',
    },
    'caption.done': {
      en: 'So the original spot cannot be pointed back to.',
      ko: '그래서 원래 자리는 되짚을 수 없다.',
      ja: 'だから元の位置は指し戻せない。',
      zh: '所以原来的位置再也指不回去了。',
      ar: 'لذلك لا يمكن العودة للإشارة إلى الموضع الأصلي.',
      es: 'Por eso ya no se puede señalar el punto original.',
      fr: "Le point d'origine ne peut donc plus être retrouvé.",
      hi: 'इसलिए मूल स्थान की ओर लौटकर संकेत नहीं किया जा सकता।',
      id: 'Karena itu posisi aslinya tidak bisa ditunjuk kembali.',
      pt: 'Por isso não se pode apontar de volta o ponto original.',
    },
    'label.axis': {
      en: 'axis',
      ko: '축',
      ja: '軸',
      zh: '轴',
      ar: 'محور',
      es: 'eje',
      fr: 'axe',
      hi: 'अक्ष',
      id: 'sumbu',
      pt: 'eixo',
    },
    'label.kept': {
      en: 'Kept by the axis {pct}%',
      ko: '축이 담은 몫 {pct}%',
      ja: '軸が保つ分 {pct}%',
      zh: '轴保留 {pct}%',
      ar: 'ما حفظه المحور {pct}%',
      es: 'Conservado por el eje {pct}%',
      fr: "Conservé par l'axe {pct}%",
      hi: 'अक्ष ने रखा {pct}%',
      id: 'Ditahan sumbu {pct}%',
      pt: 'Retido pelo eixo {pct}%',
    },
    'label.lost': {
      en: 'Lost {pct}%',
      ko: '잃은 몫 {pct}%',
      ja: '失った分 {pct}%',
      zh: '丢失 {pct}%',
      ar: 'المفقود {pct}%',
      es: 'Perdido {pct}%',
      fr: 'Perdu {pct}%',
      hi: 'खोया {pct}%',
      id: 'Hilang {pct}%',
      pt: 'Perdido {pct}%',
    },
  },
};
