/**
 * @piece
 * 질문: 예측이 얼마나 틀렸는지를 어떻게 하나의 수로 만드는가?
 *
 * 보기마다 정답에서 벌어진 폭이 값으로 바뀌는데, 폭이 클수록 값이 폭보다 가파르게 불어난다.
 * 값들이 차례로 한 합에 쌓이고, 끝에 보기 수로 나뉘어 손실 하나로 모인다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const lossMeasuresWrongnessFacet: FacetJson = {
  id: 'facet:lossMeasuresWrongness',
  title: {
    en: 'Loss measures wrongness',
    ko: '손실은 틀린 정도를 잰다',
    ja: '損失は誤りの大きさを測る',
    zh: '损失衡量错误程度',
    ar: 'الخسارة تقيس مقدار الخطأ',
    es: 'La pérdida mide cuán equivocado es',
    fr: 'La perte mesure l’erreur',
    hi: 'हानि ग़लती को मापती है',
    id: 'Loss mengukur seberapa salah',
    pt: 'A perda mede o quanto se errou',
  },
  description: {
    en: 'How do you turn how wrong a prediction is into a single number?',
    ko: '예측이 얼마나 틀렸는지를 어떻게 하나의 수로 만드는가?',
    ja: '予測がどれだけ外れたかを、どうやって一つの数にするのか?',
    zh: '如何把预测错了多少变成一个数?',
    ar: 'كيف نحوّل مقدار خطأ التنبؤ إلى عدد واحد؟',
    es: '¿Cómo se convierte lo equivocada que es una predicción en un solo número?',
    fr: 'Comment réduire l’erreur d’une prédiction à un seul nombre ?',
    hi: 'कोई अनुमान कितना ग़लत है, इसे एक संख्या कैसे बनाया जाए?',
    id: 'Bagaimana mengubah seberapa salah sebuah prediksi menjadi satu angka?',
    pt: 'Como transformar o quanto uma previsão errou em um único número?',
  },
  algorithm: 'module:lossMeasuresWrongness',
  scene: 'module:lossMeasuresWrongnessScene',
  initialData: {
    type: 'loss-measures-wrongness',
    stepMs: 1500,
    examples: [
      { id: 'e1', y: 1, p: 0.9 },
      { id: 'e2', y: 0, p: 0.25 },
      { id: 'e3', y: 1, p: 0.6 },
      { id: 'e4', y: 0, p: 0.7 },
      { id: 'e5', y: 1, p: 0.05 },
    ],
  },
  shuffleOnReset: false,
  messages: {
    'caption.start': {
      en: 'Examples: {n}',
      ko: '보기 수: {n}',
      ja: '例の数: {n}',
      zh: '样例数: {n}',
      ar: 'عدد الأمثلة: {n}',
      es: 'Ejemplos: {n}',
      fr: 'Exemples : {n}',
      hi: 'उदाहरण: {n}',
      id: 'Contoh: {n}',
      pt: 'Exemplos: {n}',
    },
    'caption.startNote': {
      en: 'Ring: answer y · Dot: prediction p',
      ko: '고리: 답 y · 점: 예측 p',
      ja: '輪: 答え y · 点: 予測 p',
      zh: '圆环: 答案 y · 圆点: 预测 p',
      ar: 'الحلقة: الإجابة y · النقطة: التنبؤ p',
      es: 'Anillo: respuesta y · Punto: predicción p',
      fr: 'Anneau : réponse y · Point : prédiction p',
      hi: 'छल्ला: उत्तर y · बिंदु: अनुमान p',
      id: 'Cincin: jawaban y · Titik: prediksi p',
      pt: 'Anel: resposta y · Ponto: previsão p',
    },
    'caption.measure': {
      en: '{id} — gap: {gap} → value: {value}',
      ko: '{id} — 폭: {gap} → 값: {value}',
      ja: '{id} — 幅: {gap} → 値: {value}',
      zh: '{id} — 差距: {gap} → 值: {value}',
      ar: '{id} — الفجوة: {gap} ← القيمة: {value}',
      es: '{id} — distancia: {gap} → valor: {value}',
      fr: '{id} — écart : {gap} → valeur : {value}',
      hi: '{id} — अंतर: {gap} → मान: {value}',
      id: '{id} — selisih: {gap} → nilai: {value}',
      pt: '{id} — distância: {gap} → valor: {value}',
    },
    'caption.measureNote': {
      en: 'Value per unit of gap: {ratio} · Sum: {sum}',
      ko: '폭 한 단위당 값: {ratio} · 합: {sum}',
      ja: '幅 1 あたりの値: {ratio} · 合計: {sum}',
      zh: '每单位差距的值: {ratio} · 总和: {sum}',
      ar: 'القيمة لكل وحدة فجوة: {ratio} · المجموع: {sum}',
      es: 'Valor por unidad de distancia: {ratio} · Suma: {sum}',
      fr: 'Valeur par unité d’écart : {ratio} · Somme : {sum}',
      hi: 'अंतर की प्रति इकाई मान: {ratio} · योग: {sum}',
      id: 'Nilai per satuan selisih: {ratio} · Jumlah: {sum}',
      pt: 'Valor por unidade de distância: {ratio} · Soma: {sum}',
    },
    'caption.average': {
      en: 'Loss: {mean}',
      ko: '손실: {mean}',
      ja: '損失: {mean}',
      zh: '损失: {mean}',
      ar: 'الخسارة: {mean}',
      es: 'Pérdida: {mean}',
      fr: 'Perte : {mean}',
      hi: 'हानि: {mean}',
      id: 'Loss: {mean}',
      pt: 'Perda: {mean}',
    },
    'caption.averageNote': {
      en: 'Sum: {sum} · Examples: {n}',
      ko: '합: {sum} · 보기 수: {n}',
      ja: '合計: {sum} · 例の数: {n}',
      zh: '总和: {sum} · 样例数: {n}',
      ar: 'المجموع: {sum} · عدد الأمثلة: {n}',
      es: 'Suma: {sum} · Ejemplos: {n}',
      fr: 'Somme : {sum} · Exemples : {n}',
      hi: 'योग: {sum} · उदाहरण: {n}',
      id: 'Jumlah: {sum} · Contoh: {n}',
      pt: 'Soma: {sum} · Exemplos: {n}',
    },
    'label.row': {
      en: 'y = {y} · p = {p}',
      ko: 'y = {y} · p = {p}',
      ja: 'y = {y} · p = {p}',
      zh: 'y = {y} · p = {p}',
      ar: 'y = {y} · p = {p}',
      es: 'y = {y} · p = {p}',
      fr: 'y = {y} · p = {p}',
      hi: 'y = {y} · p = {p}',
      id: 'y = {y} · p = {p}',
      pt: 'y = {y} · p = {p}',
    },
    'label.gapAxis': {
      en: 'gap',
      ko: '폭',
      ja: '幅',
      zh: '差距',
      ar: 'الفجوة',
      es: 'distancia',
      fr: 'écart',
      hi: 'अंतर',
      id: 'selisih',
      pt: 'distância',
    },
    'label.valueAxis': {
      en: 'value',
      ko: '값',
      ja: '値',
      zh: '值',
      ar: 'القيمة',
      es: 'valor',
      fr: 'valeur',
      hi: 'मान',
      id: 'nilai',
      pt: 'valor',
    },
    'label.even': {
      en: 'value = gap',
      ko: '값 = 폭',
      ja: '値 = 幅',
      zh: '值 = 差距',
      ar: 'القيمة = الفجوة',
      es: 'valor = distancia',
      fr: 'valeur = écart',
      hi: 'मान = अंतर',
      id: 'nilai = selisih',
      pt: 'valor = distância',
    },
    'label.formula': {
      en: '−ln({given}) = {value}',
      ko: '−ln({given}) = {value}',
      ja: '−ln({given}) = {value}',
      zh: '−ln({given}) = {value}',
      ar: '−ln({given}) = {value}',
      es: '−ln({given}) = {value}',
      fr: '−ln({given}) = {value}',
      hi: '−ln({given}) = {value}',
      id: '−ln({given}) = {value}',
      pt: '−ln({given}) = {value}',
    },
    'label.divide': {
      en: '{sum} ÷ {n} = {mean}',
      ko: '{sum} ÷ {n} = {mean}',
      ja: '{sum} ÷ {n} = {mean}',
      zh: '{sum} ÷ {n} = {mean}',
      ar: '{sum} ÷ {n} = {mean}',
      es: '{sum} ÷ {n} = {mean}',
      fr: '{sum} ÷ {n} = {mean}',
      hi: '{sum} ÷ {n} = {mean}',
      id: '{sum} ÷ {n} = {mean}',
      pt: '{sum} ÷ {n} = {mean}',
    },
    'label.sum': {
      en: 'Sum: {sum}',
      ko: '합: {sum}',
      ja: '合計: {sum}',
      zh: '总和: {sum}',
      ar: 'المجموع: {sum}',
      es: 'Suma: {sum}',
      fr: 'Somme : {sum}',
      hi: 'योग: {sum}',
      id: 'Jumlah: {sum}',
      pt: 'Soma: {sum}',
    },
    'label.mean': {
      en: 'Mean: {mean}',
      ko: '평균: {mean}',
      ja: '平均: {mean}',
      zh: '平均: {mean}',
      ar: 'المتوسط: {mean}',
      es: 'Media: {mean}',
      fr: 'Moyenne : {mean}',
      hi: 'औसत: {mean}',
      id: 'Rata-rata: {mean}',
      pt: 'Média: {mean}',
    },
  },
  blocks: {
    stage: { type: 'loss-measures-wrongness-stage' },
    controls: { type: 'control-bar', controls: CONTROL_SET.pieceScrub },
  },
};
