/**
 * 입출력 방식 — 폴링 · 인터럽트 · DMA 가 같은 낱말을 받는 동안 CPU 가 잃은 틱을 낱말 수 × 장치 빠르기 평면에서 견준다.
 */
import { CONTROL_SET, type FacetJson } from '@ffacet/core/runtime';

export const ioTransferModesFacet: FacetJson = {
  id: 'facet:ioTransferModes',
  title: {
    en: 'I/O transfer modes',
    ko: '입출력 방식',
    ja: '入出力の方式',
    zh: '输入输出方式',
    ar: 'أنماط نقل الإدخال والإخراج',
    es: 'Modos de transferencia de E/S',
    fr: 'Modes de transfert d’E/S',
    hi: 'I/O स्थानांतरण के तरीके',
    id: 'Mode transfer I/O',
    pt: 'Modos de transferência de E/S',
  },
  description: {
    en: 'Polling, interrupts and DMA receive the same words. Which one costs the CPU the fewest ticks depends on how many words there are and how slow the device is.',
    ko: '폴링 · 인터럽트 · DMA 가 같은 낱말을 받는다. CPU 의 틱을 가장 덜 잃는 방식은 낱말 수와 장치 빠르기가 정한다.',
    ja: 'ポーリング・割り込み・DMA が同じワードを受け取る。CPU のティックを最も失わない方式は、ワード数と装置の速さで決まる。',
    zh: '轮询、中断和 DMA 接收同样的字。哪种方式让 CPU 损失的时钟最少，取决于字的数量和设备的快慢。',
    ar: 'يستقبل الاستطلاع والمقاطعات و DMA الكلمات نفسها. أيها يُفقد المعالج أقل عدد من النبضات يتوقف على عدد الكلمات وسرعة الجهاز.',
    es: 'Sondeo, interrupciones y DMA reciben las mismas palabras. Cuál hace perder menos ticks a la CPU depende de cuántas palabras hay y de la velocidad del dispositivo.',
    fr: 'L’interrogation, les interruptions et le DMA reçoivent les mêmes mots. Celui qui fait perdre le moins de ticks au CPU dépend du nombre de mots et de la vitesse du périphérique.',
    hi: 'पोलिंग, इंटरप्ट और DMA एक जैसे शब्द लेते हैं। CPU के सबसे कम टिक कौन गँवाता है, यह शब्दों की संख्या और डिवाइस की गति तय करती है।',
    id: 'Polling, interupsi, dan DMA menerima kata yang sama. Mana yang paling sedikit menghabiskan tick CPU bergantung pada jumlah kata dan kecepatan perangkat.',
    pt: 'Polling, interrupções e DMA recebem as mesmas palavras. Qual faz a CPU perder menos ticks depende de quantas palavras há e da velocidade do dispositivo.',
  },
  algorithm: 'module:ioTransferModes',
  projector: 'module:ioTransferModesProjector',
  initialData: {
    type: 'io-transfer-modes',
    stepMs: 700,
    handlerTicks: 3,
    setupTicks: 2,
    modes: ['polling', 'interrupt', 'dma'],
    wordLadder: [1, 2, 4, 8],
    tickLadder: [1, 2, 4, 8],
    words: 2,
    deviceTicks: 2,
  },
  layout: {
    type: 'column',
    gap: 12,
    children: [{ ref: 'header' }, { ref: 'stage' }, { ref: 'controls' }],
  },
  blocks: {
    header: { type: 'title-block' },
    stage: { type: 'io-transfer-modes-stage' },
    controls: {
      type: 'control-bar',
      controls: [
        ...CONTROL_SET.playback,
        {
          widget: 'segmented-slider',
          action: 'words',
          name: 'words',
          label: {
            en: 'Words',
            ko: '낱말 수',
            ja: 'ワード数',
            zh: '字数',
            ar: 'عدد الكلمات',
            es: 'Palabras',
            fr: 'Mots',
            hi: 'शब्द',
            id: 'Jumlah kata',
            pt: 'Palavras',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2', default: true },
            { value: 4, label: '4' },
            { value: 8, label: '8' },
          ],
        },
        {
          widget: 'segmented-slider',
          action: 'deviceTicks',
          name: 'deviceTicks',
          label: {
            en: 'Ticks per word',
            ko: '낱말 하나에 드는 틱',
            ja: '1 ワードのティック',
            zh: '每字时钟数',
            ar: 'نبضات لكل كلمة',
            es: 'Ticks por palabra',
            fr: 'Ticks par mot',
            hi: 'प्रति शब्द टिक',
            id: 'Tick per kata',
            pt: 'Ticks por palavra',
          },
          segments: [
            { value: 1, label: '1' },
            { value: 2, label: '2', default: true },
            { value: 4, label: '4' },
            { value: 8, label: '8' },
          ],
        },
      ],
      metrics: [
        {
          name: 'polling-lost',
          label: {
            en: 'Polling lost',
            ko: '폴링이 잃은 틱',
            ja: 'ポーリングの損失',
            zh: '轮询损失',
            ar: 'فاقد الاستطلاع',
            es: 'Perdido por sondeo',
            fr: 'Perte interrogation',
            hi: 'पोलिंग का नुकसान',
            id: 'Hilang polling',
            pt: 'Perda do polling',
          },
          initial: 0,
        },
        {
          name: 'interrupt-lost',
          label: {
            en: 'Interrupt lost',
            ko: '인터럽트가 잃은 틱',
            ja: '割り込みの損失',
            zh: '中断损失',
            ar: 'فاقد المقاطعة',
            es: 'Perdido por interrupción',
            fr: 'Perte interruption',
            hi: 'इंटरप्ट का नुकसान',
            id: 'Hilang interupsi',
            pt: 'Perda da interrupção',
          },
          initial: 0,
        },
        {
          name: 'dma-lost',
          label: {
            en: 'DMA lost',
            ko: 'DMA 가 잃은 틱',
            ja: 'DMA の損失',
            zh: 'DMA 损失',
            ar: 'فاقد DMA',
            es: 'Perdido por DMA',
            fr: 'Perte DMA',
            hi: 'DMA का नुकसान',
            id: 'Hilang DMA',
            pt: 'Perda do DMA',
          },
          initial: 0,
        },
      ],
    },
  },
  messages: {
    'label.polling': {
      en: 'Polling',
      ko: '폴링',
      ja: 'ポーリング',
      zh: '轮询',
      ar: 'الاستطلاع',
      es: 'Sondeo',
      fr: 'Interrogation',
      hi: 'पोलिंग',
      id: 'Polling',
      pt: 'Polling',
    },
    'label.interrupt': {
      en: 'Interrupt',
      ko: '인터럽트',
      ja: '割り込み',
      zh: '中断',
      ar: 'المقاطعة',
      es: 'Interrupción',
      fr: 'Interruption',
      hi: 'इंटरप्ट',
      id: 'Interupsi',
      pt: 'Interrupção',
    },
    // 약어 DMA 는 열 언어 모두 그대로 뜬다 (번역하지 않는 자료)
    'label.dma': {
      en: 'DMA',
      ko: 'DMA',
      ja: 'DMA',
      zh: 'DMA',
      ar: 'DMA',
      es: 'DMA',
      fr: 'DMA',
      hi: 'DMA',
      id: 'DMA',
      pt: 'DMA',
    },
    'stage.bars.title': {
      en: 'Ticks the CPU lost',
      ko: 'CPU 가 잃은 틱',
      ja: 'CPU が失ったティック',
      zh: 'CPU 损失的时钟',
      ar: 'النبضات التي فقدها المعالج',
      es: 'Ticks que perdió la CPU',
      fr: 'Ticks perdus par le CPU',
      hi: 'CPU के गँवाए टिक',
      id: 'Tick yang hilang dari CPU',
      pt: 'Ticks que a CPU perdeu',
    },
    'stage.bars.target': {
      en: 'Dashed outline: where this round ends',
      ko: '점선 테: 이번 판이 끝나는 자리',
      ja: '点線の枠: この回が終わる位置',
      zh: '虚线框：本轮结束的位置',
      ar: 'الإطار المتقطع: حيث تنتهي هذه الجولة',
      es: 'Contorno punteado: donde termina esta ronda',
      fr: 'Contour pointillé : fin de ce tour',
      hi: 'बिंदुदार रेखा: यह दौर जहाँ ख़त्म होगा',
      id: 'Garis putus-putus: akhir putaran ini',
      pt: 'Contorno tracejado: onde esta rodada termina',
    },
    'stage.value.lost': {
      en: 'Lost ticks: {n}',
      ko: '잃은 틱: {n}',
      ja: '失ったティック: {n}',
      zh: '损失时钟：{n}',
      ar: 'النبضات المفقودة: {n}',
      es: 'Ticks perdidos: {n}',
      fr: 'Ticks perdus : {n}',
      hi: 'गँवाए टिक: {n}',
      id: 'Tick hilang: {n}',
      pt: 'Ticks perdidos: {n}',
    },
    'stage.rule.polling': {
      en: 'Each word: asks for {d} ticks',
      ko: '낱말마다 묻는 틱: {d}',
      ja: 'ワードごとに問い合わせるティック: {d}',
      zh: '每个字询问的时钟：{d}',
      ar: 'لكل كلمة: نبضات السؤال {d}',
      es: 'Cada palabra: pregunta durante {d} ticks',
      fr: 'Chaque mot : interroge pendant {d} ticks',
      hi: 'हर शब्द: पूछने के टिक {d}',
      id: 'Tiap kata: tick bertanya {d}',
      pt: 'Cada palavra: pergunta por {d} ticks',
    },
    'stage.rule.interrupt': {
      en: 'Each word: handler {h} ticks',
      ko: '낱말마다 처리기 틱: {h}',
      ja: 'ワードごとのハンドラのティック: {h}',
      zh: '每个字处理程序时钟：{h}',
      ar: 'لكل كلمة: نبضات المعالِج {h}',
      es: 'Cada palabra: manejador de {h} ticks',
      fr: 'Chaque mot : gestionnaire de {h} ticks',
      hi: 'हर शब्द: हैंडलर के टिक {h}',
      id: 'Tiap kata: tick penangan {h}',
      pt: 'Cada palavra: tratador de {h} ticks',
    },
    'stage.rule.dma': {
      en: 'Setup {s} ticks · completion handler {h} ticks',
      ko: '준비 틱: {s} · 끝 부름 처리기 틱: {h}',
      ja: '準備のティック: {s} · 完了割り込みハンドラのティック: {h}',
      zh: '准备时钟：{s} · 完成中断处理程序时钟：{h}',
      ar: 'نبضات التهيئة: {s} · نبضات معالِج الانتهاء: {h}',
      es: 'Preparación: {s} ticks · manejador de fin: {h} ticks',
      fr: 'Préparation : {s} ticks · gestionnaire de fin : {h} ticks',
      hi: 'तैयारी के टिक: {s} · समापन हैंडलर के टिक: {h}',
      id: 'Tick persiapan: {s} · tick penangan selesai: {h}',
      pt: 'Preparação: {s} ticks · tratador de término: {h} ticks',
    },
    'stage.badge.least': {
      en: 'least lost',
      ko: '가장 적게 잃음',
      ja: '最も少ない損失',
      zh: '损失最少',
      ar: 'الأقل فقدًا',
      es: 'el que menos pierde',
      fr: 'le moins perdu',
      hi: 'सबसे कम नुकसान',
      id: 'paling sedikit hilang',
      pt: 'o que menos perde',
    },
    'stage.plane.title': {
      en: 'Least-losing mode',
      ko: '가장 적게 잃는 방식',
      ja: '最も失わない方式',
      zh: '损失最少的方式',
      ar: 'النمط الأقل فقدًا',
      es: 'Modo que menos pierde',
      fr: 'Mode qui perd le moins',
      hi: 'सबसे कम गँवाने वाला तरीका',
      id: 'Mode paling sedikit hilang',
      pt: 'Modo que menos perde',
    },
    'stage.plane.ticks': {
      en: 'Ticks per word',
      ko: '낱말 하나에 드는 틱',
      ja: '1 ワードのティック',
      zh: '每字时钟数',
      ar: 'نبضات لكل كلمة',
      es: 'Ticks por palabra',
      fr: 'Ticks par mot',
      hi: 'प्रति शब्द टिक',
      id: 'Tick per kata',
      pt: 'Ticks por palavra',
    },
    'stage.plane.words': {
      en: 'Words',
      ko: '낱말 수',
      ja: 'ワード数',
      zh: '字数',
      ar: 'الكلمات',
      es: 'Palabras',
      fr: 'Mots',
      hi: 'शब्द',
      id: 'Kata',
      pt: 'Palavras',
    },
    'caption.round.head': {
      en: 'Words: {w} · ticks per word: {d}',
      ko: '낱말 수: {w} · 낱말 하나에 드는 틱: {d}',
      ja: 'ワード数: {w} · 1 ワードのティック: {d}',
      zh: '字数：{w} · 每字时钟数：{d}',
      ar: 'الكلمات: {w} · نبضات لكل كلمة: {d}',
      es: 'Palabras: {w} · ticks por palabra: {d}',
      fr: 'Mots : {w} · ticks par mot : {d}',
      hi: 'शब्द: {w} · प्रति शब्द टिक: {d}',
      id: 'Kata: {w} · tick per kata: {d}',
      pt: 'Palavras: {w} · ticks por palavra: {d}',
    },
    'caption.round.detail': {
      en: 'Each bar counts the ticks the CPU spends on I/O instead of its own work',
      ko: '띠마다 CPU 가 제 일 대신 입출력에 쓴 틱을 센다',
      ja: '各帯は CPU が自分の仕事の代わりに入出力に使ったティックを数える',
      zh: '每条带子计算 CPU 用在输入输出而不是自己工作上的时钟',
      ar: 'يعدّ كل شريط النبضات التي يقضيها المعالج في الإدخال والإخراج بدل عمله',
      es: 'Cada barra cuenta los ticks que la CPU dedica a E/S en vez de a su trabajo',
      fr: 'Chaque barre compte les ticks que le CPU passe en E/S au lieu de son travail',
      hi: 'हर पट्टी वे टिक गिनती है जो CPU अपने काम के बजाय I/O में लगाता है',
      id: 'Tiap batang menghitung tick yang dipakai CPU untuk I/O, bukan pekerjaannya sendiri',
      pt: 'Cada barra conta os ticks que a CPU gasta em E/S em vez do próprio trabalho',
    },
    'caption.setup.head': {
      en: 'DMA setup',
      ko: 'DMA 준비',
      ja: 'DMA の準備',
      zh: 'DMA 准备',
      ar: 'تهيئة DMA',
      es: 'Preparación de DMA',
      fr: 'Préparation du DMA',
      hi: 'DMA की तैयारी',
      id: 'Persiapan DMA',
      pt: 'Preparação do DMA',
    },
    'caption.setup.detail': {
      en: 'The CPU writes the transfer into the controller',
      ko: 'CPU 가 옮길 일을 제어기에 적는다',
      ja: 'CPU が転送の内容をコントローラに書き込む',
      zh: 'CPU 把要传送的内容写进控制器',
      ar: 'يكتب المعالج مهمة النقل في المتحكم',
      es: 'La CPU escribe la transferencia en el controlador',
      fr: 'Le CPU inscrit le transfert dans le contrôleur',
      hi: 'CPU स्थानांतरण का काम नियंत्रक में लिखता है',
      id: 'CPU menulis tugas transfer ke pengendali',
      pt: 'A CPU escreve a transferência no controlador',
    },
    'caption.word.head': {
      en: 'Word {i} / {w}',
      ko: '낱말 {i} / {w}',
      ja: 'ワード {i} / {w}',
      zh: '字 {i} / {w}',
      ar: 'الكلمة {i} / {w}',
      es: 'Palabra {i} / {w}',
      fr: 'Mot {i} / {w}',
      hi: 'शब्द {i} / {w}',
      id: 'Kata {i} / {w}',
      pt: 'Palavra {i} / {w}',
    },
    'caption.word.detail': {
      en: 'Polling asks until the word is ready · interrupt runs the handler · DMA: the controller moves it',
      ko: '폴링은 낱말이 준비될 때까지 묻는다 · 인터럽트는 처리기를 돌린다 · DMA 는 제어기가 옮긴다',
      ja: 'ポーリングはワードが準備できるまで問い合わせる · 割り込みはハンドラを走らせる · DMA はコントローラが運ぶ',
      zh: '轮询一直询问直到字准备好 · 中断运行处理程序 · DMA 由控制器搬运',
      ar: 'الاستطلاع يسأل حتى تجهز الكلمة · المقاطعة تشغّل المعالِج · في DMA ينقلها المتحكم',
      es: 'El sondeo pregunta hasta que la palabra está lista · la interrupción ejecuta el manejador · DMA: la mueve el controlador',
      fr: 'L’interrogation demande jusqu’à ce que le mot soit prêt · l’interruption lance le gestionnaire · DMA : le contrôleur le déplace',
      hi: 'पोलिंग शब्द तैयार होने तक पूछती है · इंटरप्ट हैंडलर चलाता है · DMA में नियंत्रक उसे ले जाता है',
      id: 'Polling bertanya sampai kata siap · interupsi menjalankan penangan · DMA: pengendali yang memindahkan',
      pt: 'O polling pergunta até a palavra ficar pronta · a interrupção roda o tratador · DMA: o controlador a move',
    },
    'caption.finish.head': {
      en: 'DMA completion interrupt',
      ko: 'DMA 끝 부름',
      ja: 'DMA 完了の割り込み',
      zh: 'DMA 完成中断',
      ar: 'مقاطعة انتهاء DMA',
      es: 'Interrupción de fin de DMA',
      fr: 'Interruption de fin du DMA',
      hi: 'DMA समापन इंटरप्ट',
      id: 'Interupsi selesai DMA',
      pt: 'Interrupção de término do DMA',
    },
    'caption.finish.detail': {
      en: 'Least lost: {names}',
      ko: '가장 적게 잃은 방식: {names}',
      ja: '最も少なく失った方式: {names}',
      zh: '损失最少的方式：{names}',
      ar: 'الأقل فقدًا: {names}',
      es: 'El que menos pierde: {names}',
      fr: 'Le moins perdu : {names}',
      hi: 'सबसे कम नुकसान: {names}',
      id: 'Paling sedikit hilang: {names}',
      pt: 'O que menos perde: {names}',
    },
  },
};
